### ISSUE TITLE
Show battery percentage next to date

### ISSUE THREAD

**Issue by dsunildatta** [8bitPit/Niagara-Issues#100]
Add Battery Percentage into Home screen next to Time & Date.

**Comment by BluDragyn** [comment]
+1 for this idea.

**Comment by Montell2099** [comment]
This suggestion together with #101 would be fantastic.

**Comment by 8bitPit** [comment]
@Montell2099 😏

**Comment by 8bitPit** [comment]
Implemented in v0.10.3: https://github.com/8bitPit/Niagara-Issues/releases
