### ISSUE TITLE
Notifications are out of order

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1000]
When I receive multiple messages in a group chat like on this scheme:
A
B
C
D

Then what I see in notification at a glance (without swiping) is this:
D
A
Which I think should be either A B or C D because this way I could read either the start or the end of the message, but having the first and last line does not give much sense to me.

**Comment by 8bitPit** [comment]
You submitted the 1000th ticket :D 🎉🎈

**Comment by 8bitPit** [comment]
A few questions:
- This might be an app specific problem. For which app does the issue occur?
- Does it only happen when you receive group conversation messages?
- Did this already happen before the v0.9.0 update?
- Next time this happens, can you please share a notification log? (You can copy it by searching for "/notifications"). Please make sure to remove any personal data beforehand.

**Comment by Martin5001** [comment]
– It happened in Facebook Messenger.
– Yes, I think it does happen in group conversations only.
– Sorry, I don't remember when it started.
– Ok I'll send it to you next time. Should I post it there or send an email?

(Maybe adding some kind of debug "simulator" could help – if I had an option to send notifications to some testing app manually the same way Messenger does, then I could replicate the issue anytime.)

**Comment by 8bitPit** [comment]
Thanks for the info. I suggest to send the log here, but you can also send to me via mail, up to you. 

> (Maybe adding some kind of debug "simulator" could help – if I had an option to send notifications to some testing app manually the same way Messenger does, then I could replicate the issue anytime.)

Definitively, but there are so much different types of notifications, that it would take a lot of time to cover most cases.

**Comment by Martin5001** [comment]
I still don't have the log because I haven't spotted the issue again yet, but I don't know if it is fixed. (This is just to let you know that I didn't forgot about this issue.)

**Comment by 8bitPit** [comment]
@Martin5001 thanks 😁

**Comment by 8bitPit** [comment]
With v1.3, we'll improve how notification sorting works and sort them by the priority given by the notification host app and with our own priority system to move those notifications to the top which are most relevant to the user. It still doesn't reflect how the system sorts them but imo that's not necessary.

**Comment by 8bitPit** [comment]
Improved in v.1.3.
