### ISSUE TITLE
Auto sort apps by clicking ranking 

### ISSUE THREAD

**Issue by MorosithIi** [8bitPit/Niagara-Issues#1005]
I think it may be useful to automatic sort apps by clicking ranking daily.
so you don't need to find and add every apps anymore.
And support of other languages in index, so people who use another language like Chinese Japanese can find their apps easier.
Thanks for your work and app

**Comment by 8bitPit** [comment]
Thanks @MorosithIi. Niagara already shows usage-based suggestions below your favorites. The less favorites you have, the more suggestions will appear. 

> And support of other languages in index, so people who use another language like Chinese Japanese can find their apps easier.

This is in the works: #234 & https://github.com/8bitPit/Niagara-Issues/issues/455

**Comment by MorosithIi** [comment]
Thanks for your replies. @8bitPit
