### ISSUE TITLE
Search icon not hiding

### ISSUE THREAD

**Issue by mgithuber** [8bitPit/Niagara-Issues#1006]
Search icon not hiding after expanding the Notification in Niagara version 0.9.4, pls see the below screenshot that is app list. facing this bug since I started using the Niagara launcher 0.7. Playstore version but now only am reporting here. Sorry for the delay. Pls fix this bug. 

Android Version 5.0.2, ZenUI
Niagara Version 0.9.4

![Screenshot_2019-09-23-22-20-05](https://user-images.githubusercontent.com/50730036/65447296-d6dd7400-de53-11e9-8aa0-e0d90e66bdac.jpg)

**Comment by mgithuber** [comment]
Today I found even in homescreen search icon(Google Search icon) not hiding after expanding the Notification. Pls see the below screenshot. Pls fix these bugs

Android Version 5.0.2, ZenUI
Niagara Version 0.9.4 

![Screenshot_2019-09-25-07-03-35](https://user-images.githubusercontent.com/50730036/65562372-d0d6b880-df63-11e9-8d93-3ad48b753e4f.jpg)

**Comment by 8bitPit** [comment]
Hi. Unfortunately I cannot reproduce this bug. The action menu and app option menu are getting rendered above the button. This might be a partially caused by your OS. Nevertheless, I'm trying to fix it.

**Comment by mgithuber** [comment]
@8bitPit, above mentioned bug is fixed in Niagara version 0.9.5. Pls see the screenshot. Now the search icon going behind after expanding the Notification. Thanks for fixing the bug

Applist
![Screenshot_2019-10-01-11-17-50](https://user-images.githubusercontent.com/50730036/65937642-274d6680-e43e-11e9-986d-b6e272db0768.jpg)

Screenshot from homescreen
![Screenshot_2019-10-01-11-18-17](https://user-images.githubusercontent.com/50730036/65937699-5a8ff580-e43e-11e9-881d-407332c066d2.jpg)

**Comment by 8bitPit** [comment]
Glad it works now, thanks for letting me know.
