### ISSUE TITLE
Tap/hold to edit & UI overlapping

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1008]
When entering edit mode the info text says "tap to edit" — but when tapping, you get an alert saying "hold to edit".

Don't know if this is a simple mistake, or a workaround of some kind of problem that may occur otherwise.

Also when tapping "move whole list", from edit mode, the UI elements overlap. Is the "edit mode" bar at the top necessary, or would the FAB perhaps be enough?

**Screenshots:**

![149281387](https://user-images.githubusercontent.com/43126233/65843496-31823e80-e332-11e9-8104-add4cf13ad2b.png)
![Screenshot_20190930-031140](https://user-images.githubusercontent.com/43126233/65843501-3e9f2d80-e332-11e9-9230-19a6fa9d471a.png)

**Comment by Martin5001** [comment]
> When entering edit mode the info text says "tap to edit" — but when tapping, you get an alert saying "hold to edit".

Note: I submitted this as a translation issue at Crowdin too.

**Comment by 8bitPit** [comment]
Thanks for pointing this out guys, I'll change the string.

> Don't know if this is a simple mistake, or a workaround of some kind of problem that may occur otherwise.

I decided to only make the launcher show the app options dialog if the user long presses on an app, for the sake of consistency. This could also teach the user that the dialog can always be opened that way.

>Also when tapping "move whole list", from edit mode, the UI elements overlap. Is the "edit mode" bar at the top necessary, or would the FAB perhaps be enough?

Some users might be confused if the screen appears without further explanation / the bar at the top (e.g. after removing a suggestion).

Btw, happy to hear from you again @Montell2099 :)
