### ISSUE TITLE
Bigger font

### ISSUE THREAD

**Issue by Alan42Rose** [8bitPit/Niagara-Issues#1009]
This launcher would be perfect for my mother who has very limited vision if only the font could be made BIGGER.

**Comment by Martin5001** [comment]
As far as I know, this is already possible to achieve via Android accessibility settings. And apps probably should not interfere with this(?).

**Comment by Alan42Rose** [comment]
Thanks for your reply.

Yes, there are settings in Android that let you make the font bigger, but
even with those settings set to max and the Niagara setting set to max the
words are still perhaps half as big as they need to be to be helpful to a
visually impaired person.

**Comment by Martin5001** [comment]
You're welcome, but now I realized I should have left the developer (@8bitPit) or one of the moderators to reply first :D

**Comment by 8bitPit** [comment]
> As far as I know, this is already possible to achieve via Android accessibility settings. And apps probably should not interfere with this(?).

Yes, I agree. Android has implemented a great font scaling system. It's built in a way that all texts are getting scaled up or down automatically, depending on Android's text size multiplier that can be adjusted in Android's settings (aka the font size slider). When a custom font size multiplier gets added this system doesn’t work that way anymore, font sizes would have to be adjusted manually on all kinds of ui elements. That’s why I’m against a custom slider.
However, one of the following might help your mother:
-	Enable high contrast text
-	Enable Android’s magnification feature
-	Use a black wallpaper for maximum contrast
-	Custom fonts might be supported in the future. Then, you can pick one that is easier to read and is bigger than other fonts. (https://github.com/8bitPit/Niagara-Issues/issues/191) The custom font option might not affect all parts of the app, but it would change the labels of your apps and the scrollbar

Hope this helps.

**Comment by Martin5001** [comment]
(You probably know that but in case you don't: There are two different scaling options – one for font size and another for whole UI scaling – by combining these two together you can get bigger size than by using font scaling only. This may help too.)

**Comment by Alan42Rose** [comment]
Actually, I had to look up "UI scaling", but it was worth it. That helped.

**Comment by 8bitPit** [comment]
Great, thanks for the tip @Martin5001. I'll close this issue, but keep #191 open.
