### ISSUE TITLE
Option to hide status bar / notification bar

### ISSUE THREAD

**Issue by MatthewOrtega** [8bitPit/Niagara-Issues#101]
I love the simplicity of it but it'd be nice to get a toggle to hide the status bar.

**Comment by 8bitPit** [comment]
Can be hidden soon!

**Comment by jakcharvat** [comment]
Please see #43 😉

**Comment by 8bitPit** [comment]
@jakcharvat not exactly the same, I know, an “immersive mode” hides usually also the status bar
But hiding status and navigation bar should be separated, due to its implementation process.

**Comment by Montell2099** [comment]
@8bitPit: Would it also be possible toggling off only the status bar clock for the homescreen, since it's already displayed in the top of the launcher?

That's the only thing bothering me right now, other than that I have had no regrets since I began testing out your beautiful launcher.

**Comment by 8bitPit** [comment]
@Montell2099 thank you :) Unfortunately, I cannot hide just the clock, notification icons & your connections & DND indicator, etc. would also be invisible.

**Comment by Bushmills** [comment]
Android - at least recent versions - already provides option for hiding status bar. Adding that feature to launcher sounds redundant.

**Comment by colbycdev** [comment]
It cannot be manually triggered, though. At least not on any device I know of
________________________________

**Comment by 8bitPit** [comment]
> Can be hidden soon!

Okay, I was a bit naive there. Sorry for the misinformation. At some point there will be a trigger which lets you hide the status bar (and even the navigation bar at the bottom). There will also be a gesture to reveal it again, to quickly check e.g. your battery or Wi-Fi connection. Moreover, I experimented with hiding the status bar only sometimes, for example while scrolling through the app list. So just want to let you guys know that I didn’t forget the issue, but turned it is more complex to integrate it properly.

Btw, yeah @Bushmills, on some devices that's already possible, but the status bar would be hidden all the time not just in the launcher afaik.

**Comment by Bushmills** [comment]
I can set this up per app, including only for Niagara launcher.But it is quite possible that this is not an universal feature, I can't tell - in which case it may of course make sense to add such support to the launcher. Or to every other app one chooses to install :)

**Comment by 8bitPit** [comment]
@Bushmills ah okay, thanks for the clarification. Yeah ,I believe most roms don't have this feature.

**Comment by mikail1990** [comment]
Сделайте пожалуйста возможность отключения функции жеста опускании шторки.

**Comment by 8bitPit** [comment]
Implemented in v0.10.3: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by kousiksaran** [comment]
status bar hidden for few minutes only.. after few minutes later status bar will visible in home screen🥺🥺🥺

**Comment by 8bitPit** [comment]
@kousiksaran are you using Niagara Launcher to hide the bar or another app? Can you please also share which device you're using?

**Comment by kousiksaran** [comment]
I use vivo s1 pro mobile

**Comment by 8bitPit** [comment]
Thanks, we'll monitor if others report the same problem and take a closer look if this issue is directly related to Niagara Launcher if they do.
