### ISSUE TITLE
Add folders and custom categories 

### ISSUE THREAD

**Issue by StarrKiss** [8bitPit/Niagara-Issues#1010]
What I mean by this is that currently, there is a dot subcategory at the bottom for Niagara settings. It would be cool if we could make our own categories like that (and maybe even sort alphabetically inside them.)

**Comment by 8bitPit** [comment]
Hi @StarrKiss, #13 is about Folders and categories, please post your ideas here.

**Comment by 8bitPit** [comment]
Duplicate of #13
