### ISSUE TITLE
Spotify - swipe right actions 

### ISSUE THREAD

**Issue by ljukas** [8bitPit/Niagara-Issues#1011]
**Describe the bug**
Swiping right on the Spotify app and pressing "Like song" did not like the song. Nothing happenes. 

**To Reproduce**
1. Go to homescreen
2. Swipe right on the Spotify app whilst a song is playing. 
3. Click on "like this song". 
4. Enter Spotify and see that the song is not liked. 

**Smartphone (please complete the following information):**
 - Device: S10
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
Thanks for the bug report @ljukas.

**Comment by disacrol** [comment]
Is this sporadic? Can't reproduce this. Stock Android Pie, Niagara 0.9.10 (alpha version from Telegram)

**Comment by ljukas** [comment]
Seems to be sporadic. I did not work yesterday again when I tested it after your comment. But today it worked. I'll see if I can find a moment it does not work again and post a video or gif of it.

**Comment by ljukas** [comment]
Cant seem to get it to reproduce. Closing this issue.
