### ISSUE TITLE
Some niagara elements have a red background

### ISSUE THREAD

**Issue by FoxxMD** [8bitPit/Niagara-Issues#1012]
**Describe the bug**
The background for the **Search apps** input as well as the floating icon for current list location has a red background and I cannot determine how to reset it, or how they changed in the first place 🤔

**Smartphone (please complete the following information):**
 - Device: Pixel 1
 - Android version: 10

**Screenshots**

![Screenshot_20191004-130422](https://user-images.githubusercontent.com/4663766/66226206-42bbaa00-e6a8-11e9-9682-9919a1920d23.png)
![Screenshot_20191004-130637](https://user-images.githubusercontent.com/4663766/66226210-44856d80-e6a8-11e9-9340-ae3e11c381c7.png)

**Comment by FoxxMD** [comment]
Are they background based?

**Comment by Martin5001** [comment]
> Are they background based?
Yes, the colour changes automatically depending on the background.

**Comment by FoxxMD** [comment]
Ok, that makes sense. I'm using a live background with a mostly black fill though so I'm not sure where the red is coming from. Wish I could just set it in Niagara. Thanks!

**Comment by 8bitPit** [comment]
@FoxxMD this might be possible in the future: #303
