### ISSUE TITLE
Call screen display problem

### ISSUE THREAD

**Issue by deepanshujbans** [8bitPit/Niagara-Issues#1014]
When someone calling  me then full screen calling display is not shown only call cut ,caller name and call pickup button showing at upper side. I want to show full screen call display ( default call screen of my phone) when someone calling me.

 - Device: Redmii Note 7
 - Android version:  Android 9 (Pie)

**Comment by 8bitPit** [comment]
Hi @deepanshujbans, I don't doubt this can be caused or changed by your default launcher. Have you tried reproducing this with another third-party app?

**Comment by deepanshujbans** [comment]
How to retain it.

**Comment by 8bitPit** [comment]
@deepanshujbans does the full screen caller screen show when setting another launcher as default? For instance, you could try it with Nova launcher.

**Comment by deepanshujbans** [comment]
Yes sir in apex launcher full screen call display showing.

**Comment by 8bitPit** [comment]
@deepanshujbans pretty strange. I have no idea how a launcher could change the behavior of your phone app.

**Comment by deepanshujbans** [comment]
Its my phone properties to show full screen caller display .
Niagra launcher change the property of my phone ,incoming call display mode
is showing diffrent.

Another launcher shows stock call display while niagr launcher showing
another which is not my stock call display screen.

**Comment by 8bitPit** [comment]
@deepanshujbans can you please try out if the call screen works correctly with Lawnchair Launcher?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.

**Comment by deepanshujbans** [comment]
No

Thank you for developer most best launcher for us.

**Comment by 8bitPit** [comment]
Thank you very much :D
