### ISSUE TITLE
Option to show current letter instead of alphabet animation

### ISSUE THREAD

**Issue by jurf** [8bitPit/Niagara-Issues#1015]
I’m having trouble navigating through the app list with the animation, since the letters keep moving (i.e. it takes me several more seconds the find an app I want because I lose track of the letters).

For example, this is the approach Poweramp uses, which I navigate through several times faster:

![Screenshot_20191006-173429_Poweramp](https://user-images.githubusercontent.com/7472425/66271579-fb781980-e85f-11e9-8e65-540ecac6f5ab.png)

(related to #361, but that one has been closed since March)

**Comment by 8bitPit** [comment]
Hi @jurf, sorry for my late reply. If you have trouble keeping track of the moving letter, you could also look at the letter on the left (above the apps), that doesn't move.

**Comment by jurf** [comment]
Thanks, yeah that does help. :slightly_smiling_face:

To be fair the wavy animation is still one of my biggest hindrances with this launcher, but that’s out of scope of this issue.
