### ISSUE TITLE
Google to shut down free weather provider

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1016]
Unfortunately, Google decided to shut down its weather services. I’ve received the following message from Google:
>Starting January 31, 2020, the Places and Weather signals in the Awareness API will no longer be available. If your app uses a Weather signal, there are several third-party APIs that provide similar information. [...] Unfortunately, Google does not currently offer an alternative API for the Weather signal.

The Awareness API wasn’t great anyway. Weather data was infrequently updated, was often wrong in most places and the API needed GPS to be turned on at all times to work.

As of now, there is no good free global weather provider. Most weather services only offer free weather data to a certain quota limit (e.g. OpenWeatherMap). (There is a ‘trick’ to circumvent this limit by letting the user to provide his/her own API key, but I am against this. You can read more about this here: #179). Of course, it’s understandable that they need money to operate their servers and that they want something in exchange for their work. 

I decided to switch to a paid provider called Dark Sky. It offers way better data, hourly and daily forecasts and does not need GPS. This allows me to create a much more reliant and more useful widget. I also want to point out here that Dark Sky’s costs are request-based. The more weather requests they get, the more it will cost me. That’s why Niagara’s weather widget will cost a small yearly recurring fee instead of just a one-time fee. If this is not an option for you, you can still add a custom widget from the weather app of your choice.

**Comment by AndydeCleyre** [comment]
Will it be possible to use our own darksky API key if we already have one? I use the service on my computer as well.

**Comment by 8bitPit** [comment]
@AndydeCleyre Dark Sky's terms of service don't allow this:

> Your permission to use the Service is condition upon your agreement that you will not [...] direct your end-users to sign up for their own API account (The Dark Sky API not intended to be used directly by end-users); 

Source: https://darksky.net/dev/docs/terms#tos-api-key

**Comment by cauerego** [comment]
bravo, as usual!

the Google at glance will continue to work, right?

also, and this probably should be a new issue if one doesn't exist yet, the widget itself keeps crashing from time to time, apparently at random, and can be fixed by replacing itself. are you aware?

thanks for Niagara, once more! i do hope you'll find a nice stream of money with this or, eventually, with Google finally grabbing you into their team or something.

cheers!

**Comment by 8bitPit** [comment]
Haha, thank you very much @cauerego 😁

> the Google at glance will continue to work, right?

Yes, all third party widgets will still work.

> also, and this probably should be a new issue if one doesn't exist yet, the widget itself keeps crashing from time to time, apparently at random, and can be fixed by replacing itself. are you aware?

When the error happens, does a semi transparent white box appear instead of the widget (https://github.com/8bitPit/Niagara-Issues/issues/952)? Because this is a bug I already fixed the day before yesterday, I'll send a patch soon.

**Comment by Coedy** [comment]
What about yr.no as a provider?
https://www.yr.no/?lang=en
They are based in Norway hence the domain, however I know a very large open source home automation platform uses them by default (to the best of my knowledge without a formal agreement in place between the two) so imagine this would keep it free?
It also seems very accurate for me in the UK at least.
Disclaimer- I haven't checked their terms for the API....

**Comment by 8bitPit** [comment]
@Coedy thanks for your suggestions. Unfortunately, it seems that they don't provide global weather data though:

> The information is only available in Norwegian. You have to be able to understand Norwegian or get someone to translate the requirements and regulations into your language. It is very important that you understand and follow the guidelines! We regularily monitor the downloads of our XML-files, and will block you without warning if you don’t follow the requirements.We are sorry that this information is not available in English. yr.no is financed by Norwegian tax and license fee payers, and our main focus is Norwegian forecasts and services, although we do offer forecasts for every country and all major cities of the world. We are afraid to get overloaded with traffic if we translate the guidelines and promote the free weather data service in English.

**Comment by eliliam** [comment]
I just bought pro since I've been a user since the beginning and love this project, but I was under the impression that pro gets access to the new weather widget, however I don't seem to see it in settings>features. Is there another place I should go to enable it?

**Comment by eliliam** [comment]
To address my previous comment, I had to uninstall the Google Play version and install the 0.11.13(I think) version from the releases page and it all works now!

**Comment by 8bitPit** [comment]
@eliliam great to hear it's working now. Pro weather can be enabled since v0.10.1 as far as I can remember.
