### ISSUE TITLE
Icon Pack Reverts Back to System

### ISSUE THREAD

**Issue by Sharkaboi** [8bitPit/Niagara-Issues#1017]
Device : Mi A1
Android ver: Pie

Issue: The selected icon packs reverts to the system icon pack when it updates via playstore.
To see this issue in action, 
1)apply an older version of a third party icon pack
2)set icon pack in settings
3) update app
4) the icon pack gets removed

**Comment by 8bitPit** [comment]
Thank you for the report. Which version of Niagara Launcher are you using? (You can look it up in the advanced tab of Niagara's settings.)

**Comment by Sharkaboi** [comment]
Version 0.9.3

**Comment by 8bitPit** [comment]
All right, please try out if the problem is still present in v0.9.6 the next time one of your icon packs get updated. I tried to reproduce the issue (with 0.9.6) yesterday, but to no success.

You can download 0.9.6 from here:
https://github.com/8bitPit/Niagara-Issues/releases

**Comment by Sharkaboi** [comment]
Ok, I'll relay back if I find anything :)
Thanks for being a great dev

**Comment by 8bitPit** [comment]
Thank you very much :D

**Comment by 8bitPit** [comment]
Feel free to open the issue again if the issue reappears.
