### ISSUE TITLE
Notifications – YouTube link suggests opening calendar

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1018]
**Describe the bug**
Notification with link shows "Open YouTube" and "View/open calendar" but only the "Open YouTube" button should be displayed.

**To Reproduce**

Issue occured with this specific text in Facebook messenger notification:
https://youtu.be/7aC3ejCQgQo neasi, today's kidds be like 😂😂😂😂😂

**Smartphone (please complete the following information):**
 - Device: Nokia 5
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
That's funny, I believe Android's AI decided to show the calendar event because of the keyword "today".
Unfortunately I cannot tweak it, only exclude calendar events from showing up completely. I could only lower the maximum number of "smart actions" to one (instead of two).

**Comment by Martin5001** [comment]
This AI works on Android 9 too? I thought it's new in Android Q.

As you say you can exclude calendar events, does that mean Android provides you info about from which apps the suggestions are shown? If so then it may be possible to not limit it hard to number of two (which might interfere with smart text replies on Android Q, I think, don't know), but make a condition instead to limit the number only for certain combinations.

(Anyway, this issue does not occur really often, so it's not a big problem I think. Maybe Google will improve their AI eventually.)

**Comment by 8bitPit** [comment]
The AI to generate smart replies for example was only introduced with Android 10. However, some AI features were already introduced in Android 9, like basic text classification. For instance, you can see it in action when selecting and Address or date: https://www.online-tech-tips.com/smartphones/navigate-easier-with-androids-smart-text-selection-and-selected-text-magnification/
Android provides me the classification group (“phone number”, “flight number”, “email address”, etc.), but not the name / identifier of the app that will be opened. Btw, the maximum wouldn’t interfere with Android Q’s smart replies here as I only use this algorithm below Android Q (On Android Q, I get the buttons directly and don’t have to call a method that classifies the text first).

**Comment by Martin5001** [comment]
Thanks for your explanation, it's always great to get to know something new :)

**Comment by 8bitPit** [comment]
Haha ^^
