### ISSUE TITLE
location/time based favourites

### ISSUE THREAD

**Issue by gorriecoe** [8bitPit/Niagara-Issues#1019]
Would it be possible to add location and/or time based favourites?  This would allow a user to define their favorite set of apps while at work and a different set while their home or away from work.

As an example I use many communication, Todo list apps and issue tracking apps while at work.  But while I'm home it needs to be social, banking and a different set of communication apps.

Great app btw been using this for months.

Cheers gorrie

**Comment by 8bitPit** [comment]
Thanks @gorriecoe 😄
I'd like to merge this issue with #165, I think it goes in a very similar direction. Maybe you'd also like #537.
