### ISSUE TITLE
Alternatives to alphabet sorting

### ISSUE THREAD

**Issue by Deviousretard** [8bitPit/Niagara-Issues#102]
Some alerternatives to the sorting would be nice, a few i've thought of ;

* Reverse alphabet, as in Z at the top and A at the bottom
* Most recently used
* Most recently installed

You could probably use most recently used/installed instead of the favorites though.  Maybe even add an option that disabled it all together, like being in the app-drawer at all times?

**Comment by mare-413** [comment]
I agree, would love the option to reverse the alphabet

**Comment by 8bitPit** [comment]
@mare-413 But doesn't that sound a bit unintuitive?

**Comment by Deviousretard** [comment]
Not really, you shouldn't see it as reverse, but more like bottom to top. 
Whenever i want to go back to mainscreen from favorites, i have to swipe all the way to the top, which is kinda of a pain with a big phone, i'd rather swipe to the bottom.

But, i'm just a fan of customization, i like having different options available, and find out which one works best for me personally.

**Comment by disacrol** [comment]
But you can press home to get back to favorites anytime.

I think an option to revert the alphabet wouldn't hurt though.

**Comment by Deviousretard** [comment]
That'd be an extra press as usually my hand is already on the alphabet slider

**Comment by 8bitPit** [comment]
So, would you prefer the whole alphabet being placed more at the bottom (#334)?

**Comment by mare-413** [comment]
Dont know if that question was directed to me, but i dont think that's necessary. Just the option to change the alphabet sorting would be great.

**Comment by 8bitPit** [comment]
Hey guys. I've thought about the issue for a longer time and came to the conclusion not to offer custom sorting to keep the launcher simple. However the search screen will be reworked, so recently installed apps show up where when you haven't typed anything in yet.
Moreover, the size of the alphabet can be adjusted in the future: https://github.com/8bitPit/Niagara-Issues/issues/263.
If you want to reach the first letters of the alphabet easily with one hand, I recommend tapping at the bottom right of the screen and the alphabet will move down.
