### ISSUE TITLE
have the option to move the letter list to the right of the screen

### ISSUE THREAD

**Issue by cuilean** [8bitPit/Niagara-Issues#1021]
since most of us are right handed, i think this would be easier for the users and it would be that much easier to use the launcher with one hand.

**Comment by Montell2099** [comment]
Could you elaborate on what you're referring to? The scrollable alphabet-list is already on the right hand side.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case Montell's previous reply didn't help.
