### ISSUE TITLE
Rubber band effect tweak

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1022]
The new rubber band overscroll effect looks nice but I think it should not be applied when swiping down quickly to open the notifications shade. (It would be used only on slower swipe, which does not open notifications, instead.)

**Comment by 8bitPit** [comment]
To me, the rubber band animation also makes sense when the shade opens, I think the animations go hand in hand. For me it’s like pulling down on a string or something and something else drops down as a result. Moreover, the launcher decides to show / not show the shade when your finger leaves the screen; the animation is already running by this time.

**Comment by Montell2099** [comment]
> The **new rubber band overscroll effect looks nice** but I think it should not be applied when swiping down quickly to open the notifications shade

What is this new effect you're discussing? I haven't got any recent updates for the beta & can't seem to distinguish anything new.

**Comment by 8bitPit** [comment]
@Montell2099 you can see it in action on Twitter: https://twitter.com/NiagaraLauncher/status/1183417546168516610

You might get the update through Google Play this weak, but you can also download it from GitHub: 
https://github.com/8bitPit/Niagara-Issues/releases

**Comment by Montell2099** [comment]
@8bitPit Oh, thank you! Very clean animation, fits perfectly within in the launcher imo. It feels a little bit odd that the "scroll down for notification bar"-gesture still is active while in the app drawer.

But I can see that it's pretty pointless disabling it, just to be able to play with this new rubber band animation while being at the very top of the app drawer.

**Comment by 8bitPit** [comment]
Closing because of the reasons mentioned above.

**Comment by PaulBags** [comment]
What reasons? This still messes with notifications. Why are bugs closed as dupes of enhancements? Argh.

**Comment by 8bitPit** [comment]
@PaulBags That's because the new bounce effect does not mess with the swipe down gesture, it's just a visual effect.

**Comment by awnumar** [comment]
Can we at least have an option to disable this animation in the settings? It is unnecessary and makes the experience feel sluggish.

**Comment by 8bitPit** [comment]
@awnumar In my opinion, single animations shouldn't be toggleable, because then all kinds of animations should have toggle, the launchers maintainability & user experience would suffer a lot as a result, see: https://medium.com/niagara-launcher/niagara-launcher-in-2020-df3f6aa2d184
