### ISSUE TITLE
Highlight index letter if app within has notification.

### ISSUE THREAD

**Issue by Alobidat** [8bitPit/Niagara-Issues#1023]
Since the home page has limited real stat for apps, adding a notification mechanism by highlighting the index letter if an app within that index has a notification will be of great use and benefits for the user.

**Comment by 8bitPit** [comment]
Hi @Alobidat, what about a dedicated notification section: https://github.com/8bitPit/Niagara-Issues/issues/152? It's not exactly the same what you meant, but I believe this would also help you to reach apps with notifications quicker.

**Comment by Alobidat** [comment]
A dedicated notification section is good to browse through all the notification at once but without a clue on the main screen the user need to check this section to see if notification is available.

My suggestion is building on the unique and great design of the Niagara a notification on the letter index will direct the user to a more important app of interest and this will flow correctly with the notification process on the main and only screen.

Another approach is to add a special index (similar to the favourite star) that group all apps with notification under it and it become visible when notification is available.

The key is user awareness.

Thanks.

________________________________

**Comment by Alobidat** [comment]
Issue 152 is talking about the same thing I believe as adding a dedicated index for apps with notification, but I would like to add that this index need to be marked clearly if notification is pending.

**Comment by 8bitPit** [comment]
Thanks for your ideas @Alobidat. Notifications would directly show up above or below your favorites, so I believe the user can see pending notifications at a glance without having to swipe anywhere.

**Comment by 8bitPit** [comment]
If you want to discuss about this further, please refer to #152
