### ISSUE TITLE
Bounce animation interferes with swipe down for notifications 

### ISSUE THREAD

**Issue by premnirmal** [8bitPit/Niagara-Issues#1024]
I'm a big fan of the recent update where you added the responsive bounce animation when you scroll the list up or down. There is one issue however - it interferes with the swipe down for notifications gesture. I feel like of that gesture is enabled it shouldn't bounce when you pull down on favorites.

**Comment by Martin5001** [comment]
(This is probably the same as #1022)

**Comment by 8bitPit** [comment]
Duplicate of #1022
