### ISSUE TITLE
180° rotation

### ISSUE THREAD

**Issue by netilynik** [8bitPit/Niagara-Issues#1027]
It would be fine if You add at least 180 degree rotation support.
I understand, that implementation for all four sides rotation is complicated  - it s not compatible with whole idea of Niagara) 
But 180° rotation isn't concerned with any redesign.
Why do I need the feature: time to time I hold my phone upsidedown.

**Comment by Martin5001** [comment]
This also seems to be good for the future – with full side displays and in-screen fingerprint sensors – some device vendors tend to even replace physical lock screen and volume buttons with touch sensitive frame – it will probably become more common to hold a phone upside down without even noticing it.

**Comment by craPkit** [comment]
This is a feature that should—and perhaps will, in time—be implemented at system level. Moreover, I haven't seen it implemented in any app so far, but maybe I'm not holding my phone upside down "often enough".

**Comment by 8bitPit** [comment]
Once this is a system feature, I'll maybe add this. But as @craPkit mentioned, very few or almost no app supports this, right now. You wouldn't really benefit from it then (because you have to turn the phone after launching an app).

**Comment by netilynik** [comment]
I use custom ROM, i.e. lineages. And there settings to chose allowed rotation modes - 90, 180 270
I checked only 180 variant. 
And every app I ve tried with rotation were upside down when phone is upside down too... Except Niagara)

**Comment by 8bitPit** [comment]
Oh okay, thanks for the info.

**Comment by netilynik** [comment]
Not every app, but most of apps installed on my phone are OK with this rotation

**Comment by ralismark** [comment]
Supporting this might only require changing the [android:screenOrientation](https://developer.android.com/guide/topics/manifest/activity-element#screen) attribute in AndroidManifest.xml to "userPortrait", though I'm not sure if this is all that's needed.

**Comment by josh1244** [comment]
If you get the app Rotation off of the play store then every app including Niagara Launcher will support any rotation.

**Comment by netilynik** [comment]
Josh1244, thanks for advice!
Couldn't you give the link to the app or explicit name of it?
Thank you

**Comment by josh1244** [comment]
https://play.google.com/store/apps/details?id=com.pranavpandey.rotation

**Comment by netilynik** [comment]
It works, thanks a lot!

**Comment by 8bitPit** [comment]
Great that there's an app for that!
