### ISSUE TITLE
Option to disable rubber band overscroll.

### ISSUE THREAD

**Issue by George-Payne** [8bitPit/Niagara-Issues#1028]
The new rubber banding overscroll animation is too aggressive for me. 

An option to disable it would be appreciated.

Additionally, it would to helpful to automatically disable it if the user has selected the "remove animation" accessibility option enabled.

**Comment by Montell2099** [comment]
Too aggressive, as in you think it bounces **too much** once you've reached the end of your app list?

**Comment by 8bitPit** [comment]
I don't really want to add toggles for minor visual changes, because too much settings to choose from can ruin the clean experience (please also refer to #808). 

> Additionally, it would to helpful to automatically disable it if the user has selected the "remove animation" accessibility option enabled.

Yeah, that sounds better to me, but I believe very few people enable this setting, I'd say this has low priority.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
