### ISSUE TITLE
Offset during tap on an app

### ISSUE THREAD

**Issue by J-Gian** [8bitPit/Niagara-Issues#1031]
When I tap on an app, Niagara opens the app just below. 
As you can see in the video linked, when I tap on Opera, it opens Maps; when I tap on Galleria, it opens Camera, and so on.

It's happens only sometimes, and actually I can't find a a way to reproduce the bug. 

The problem solves itself after a few minutes of screen off, or by rebooting Niagara.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Mix 2S
 - Android version: Android 9 (Pie) with MIUI Global 10.3.6.0 - Niagara 0.9.8

**Screenshots**
I link a screen recording: https://photos.app.goo.gl/jEH1rm6Z462rVUht8

**Comment by Haini** [comment]
I have the same problem on my device and think it was introduced with the bumper animation.
I also can't reproduce the bug, but have the feeling that it happens more often after the bumper animation is triggered.

Smartphone (please complete the following information):

Device: Xiaomi Redmi Note 4
Android version: Android 7 with MIUI Niagara 0.9.8

**Comment by deepanshujbans** [comment]
I have the same issue when I click on app then it's downward app open.
Its very annoying to me as we need to open aap in hurry such calculator and you get chrom every time .
Dear Developer please solve it on earliest.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
