### ISSUE TITLE
Smooth Scroll (No Highlight)

### ISSUE THREAD

**Issue by QantumEntangled** [8bitPit/Niagara-Issues#1032]
When scrolling, I believe it would feel more fluid & precise to smoothly scroll the list vertically while swiping through the search bar.

**Comment by 8bitPit** [comment]
A scroll animation might feel smoother, but I fear this would cost you more time to find your apps.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
