### ISSUE TITLE
Add left screen please!

### ISSUE THREAD

**Issue by zhenyaxxo** [8bitPit/Niagara-Issues#1034]
I really like your application, but it’s really not convenient for me to use widgets at the top, why not make widgets in a separate screen on the left like Microsoft Launcher or Smart Launcher 5?

**Comment by 8bitPit** [comment]
Hi @zhenyaxxo, I also thought about this a while ago and answered the following to a similar question:

>I am not really a fan of widget pages. The only thing widgets have in common there is, well, they’re all widgets. So why should they be grouped together? Showing a weather widget below the clock and accessing your calendar agenda via a swipe / by tapping on a button makes more sense to me. Also, widgets often tend to use much ram. The concept of a widget list would kind of endorse user to cluster the page full of widgets. A swipe menu shows only a single widget at once, so not every widget has to be loaded into ram when you want to access one.
That’s why I’m planning to add the following integration:
You can place a single widget below the clock or replace it for showing weather and / or time, or an at a glance widget.
More widgets can be accessed by swiping right on an app.
Another idea would be that you can customize the google search button at the bottom right, so it can also launch a widget, e.g. your calendar. [Source: #117]
