### ISSUE TITLE
Custom icon doesn't get applied to calendar app

### ISSUE THREAD

**Issue by Amit2685** [8bitPit/Niagara-Issues#1035]
![Screenshot_20191027-123309_Niagara Launcher](https://user-images.githubusercontent.com/57060727/67632691-ab273100-f8cc-11e9-9fad-918b8bdf4d78.jpg)
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Hi @Amit2685. Does the icon pack have an icon for the calendar app that you're using?

**Comment by Amit2685** [comment]
Yes, on nova launcher it works

**Comment by 8bitPit** [comment]
Thanks. Can you please share the name of the icon pack you're using?

**Comment by alexesprit** [comment]
@8bitPit Hi! I have the same issue. I use [Nexa Icon Pack][nexa].

![image](https://user-images.githubusercontent.com/1119267/70851473-bf3be780-1ea6-11ea-85bd-ac841abd6f31.png)

[nexa]: https://play.google.com/store/apps/details?id=com.jndapp.square.nexa.iconpack

**Comment by 8bitPit** [comment]
Thanks @alexesprit, but I think this is related to https://github.com/8bitPit/Niagara-Issues/issues/533, because at least the icon shows up.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)
