### ISSUE TITLE
Double close animation

### ISSUE THREAD

**Issue by Sn00PiG** [8bitPit/Niagara-Issues#1036]
**Describe the bug**
When I close an application the "close animation" shows twice, and usually it's 2 different type animations. Never happens with stock launcher (Oneplus 7 Pro on Android10), and not always happening on Niagara, but very frequently - mostly when I close an application that I've used for a while (maybe RAM related?).

**To Reproduce**
1. Open a few applications
2. Stay in one app for a while (possibly filling up the RAM/cache)
3. Close the app

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro 6GB RAM
 - Android version: Official Android 10

**Screenshots**
https://youtu.be/DdmYTQHx7v8

**Comment by 8bitPit** [comment]
Hi @Sn00PiG, thanks a lot for your descriptive bug report and for the additional video! I fear that this might be caused by the OS, because third party launchers can't override close animations. Have you tried reproducing this with another third-party launcher (like Nova Launcher)?

**Comment by Sn00PiG** [comment]
Hi @8bitPit , you are correct, this behaviour happens in Nova too. The strange thing is that it isn't always happening with every close. Any way that this will be resolved in the future you think? Is this Android 10 related? As I haven't seen this on Pie.

**Comment by 8bitPit** [comment]
Thanks for letting me know @Sn00PiG. Yes, this could be related to Android 10, because stock Android doesn't yet support gesture navigation for third party launchers: #989
