### ISSUE TITLE
Qobuz cover missing

### ISSUE THREAD

**Issue by emschi77** [8bitPit/Niagara-Issues#1039]
**Describe the bug**
When using qobuz as music player the cover is not visible in niagara. Other player like SoundCloud or Tidal don't have that problem.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - Android version: 10

**Screenshots**

![Screenshot_20191029-082647](https://user-images.githubusercontent.com/47519667/67746193-47188000-fa26-11e9-86b8-c203ed6b78a0.png)

**Comment by 8bitPit** [comment]
Please refer to #485
