### ISSUE TITLE
Adjustable delay for Wake-Animation Wallpapers

### ISSUE THREAD

**Issue by skreenr** [8bitPit/Niagara-Issues#1040]
Wake-Animation Wallpapers (WAW) add a nice transitional animation effect when unlocking into Homescreen.
The Effect quality depends on length of the transition to a fully-painted Homescreen from the dark Lockscreen, and the newer devices tend to dish out icons much faster.

To make WAW experience more enjoyable, it helps to add a User-adjustable delay in the 100-350 msec range to the initial "Paint Homescreen" task.    
Implementation would require adding a simple UI picker for users to select the Delay value, and modifying Paint Homescreen' code to use that value.

To see example of WAW screen action check  http://wakeanimation.org which also explains the concept more.
These videos were shot on oldie handsets, and with faster phones you really wish you have that delay to enjoy art unfolding!    
  
![exampl3](https://user-images.githubusercontent.com/57162684/67824865-ca68be80-fa84-11e9-8aa5-66f04aa1575d.gif)

**Comment by 8bitPit** [comment]
Hi @skreenr, thanks for your request. I believe this feature is too specific for a simple Launcher like Niagara, I want to keep the number of settings & toggles to a minimum. However, I think that animated wallpapers work pretty well on Niagara by default, because apps are not covering much space. You could also hide the names of your favorites to see even more of your wallpaper.

**Comment by skreenr** [comment]
Yes with the apps not covering much space it looks better than in a grid setup, However if you just add 200 msec delay it will really pop your senses! Imagine all the creative opportunities this simple tweak may enable.  It can be a very small addition in Settings-Look
![Niagara_WAW_Picker2](https://user-images.githubusercontent.com/57162684/68079421-5bea7000-fda6-11e9-92e9-487612f252cf.png)
 UI, here's a prototype:
![Niagara_WAW_LookScreen23](https://user-images.githubusercontent.com/57162684/68079420-53923500-fda6-11e9-9a9a-044cf6b5e38e.png)

**Comment by 8bitPit** [comment]
Thanks for your mockup @skreenr. I also want to point out that Niagara is not really about customization - the app is about simplicity and efficiency. With too much toggles the app could feel less polished:
>  I believe adding a toggle for all kinds of stuff is often problematic. You lose control of designing good user experience. Think of it like a combination tree. If you add 10 switches for example, there are 1024 possible combinations of their states they could be in. Niagara should feel polished regardless of the user’s settings, every switch makes the overall experience harder to maintain. That’s why I want to keep it as simple as possible. [Source: #808]

I hope you're not too disappointed that it's quite likely your request will not be added. Sorry.

**Comment by skreenr** [comment]
Thanks for clarification Peter, about Simplicity not Customization,
By chance, which Launcher projects might be a better fit for this idea, in your opinion?

**Comment by 8bitPit** [comment]
I believe Nova and Lawnchair Launcher are all about customization. The latter one has also a GitHub repository: https://github.com/LawnchairLauncher/Lawnchair

**Comment by skreenr** [comment]
Lawnchair is cool, but they don't have this neat Feature Suggestion thing like you do, Peter!

**Comment by 8bitPit** [comment]
@skreenr I don't know how actively they respond to feature requests submitted to their GitHub page, but I think it's worth a try: https://github.com/LawnchairLauncher/Lawnchair/issues?page=1&q=is%3Aissue+is%3Aopen
Good luck :D
