### ISSUE TITLE
Background colour on the alphabet for readability on busy backgrounds.

### ISSUE THREAD

**Issue by adamdjensen** [8bitPit/Niagara-Issues#1041]
If you're using a busy background (unlike the one I'm using in this example) it can get difficult to read the alphabet no matter what colour you've set.

I think there should be an (optional) feature to add a background to the alphabet as shown here. You could show it only whilst you are scrolling on it or have it always be on. Since Niagara already picks a colour from the background for some elements like the search button or the letter you are touching, I figure it makes sense to use that colour too for this element. 

![mockupniagara1](https://user-images.githubusercontent.com/10334020/67947442-f8b0e000-fbe3-11e9-8e63-82c0e10ac7e1.png)
![mockupniagara2](https://user-images.githubusercontent.com/10334020/67947443-f9497680-fbe3-11e9-90be-6e8fe74ee226.png)

**Comment by 8bitPit** [comment]
Thanks for your mockup @adamdjensen. However I fear that the scrollbar background doesn't look as clean as [blurring or tinting the whole background](https://github.com/8bitPit/Niagara-Issues/issues/705). Moreover, redrawing the shadow every frame might be expensive.

**Comment by adamdjensen** [comment]
Thanks for the reply. You make some good points and blurring the bg will probably help a lot with readability too.  This is somewhat subjective but I do tend to prefer text to be on plain backgrounds, just so you have 100% certainty that the alphabet will be readable at all times. Can I just close this issue now? I don't know how Github works lol.

**Comment by 8bitPit** [comment]
Hey again. Yeah, you can now close the issue ^^, I'll do that for you.
