### ISSUE TITLE
Swipe down broken

### ISSUE THREAD

**Issue by PaulBags** [8bitPit/Niagara-Issues#1042]
**Describe the bug**
Swipe down just "bounces" the home screen now. Maybe 1/10 of the time notif actually drops.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the latest version
2. Swipe down on home screen

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A7 2017
 - Android version: Android 8.0.0

**Comment by 8bitPit** [comment]
Hi @PaulBags. the bouce effect is new, but I believe it doesn't affect the notification gesture. The notification tray only opens if you swipe pretty fast.

**Comment by 8bitPit** [comment]
Please refer to #1022
