### ISSUE TITLE
Question about Chinese sorting

### ISSUE THREAD

**Issue by Coxlin19** [8bitPit/Niagara-Issues#1043]
I hope to be able to add options that can be sorted in Chinese Pinyin.thank you.

**Comment by 8bitPit** [comment]
Hi @Coxlin19, since the latest alpha build (v0.9.9) you can take use of Pinyin transliteration.
More info about that here: https://twitter.com/NiagaraLauncher/status/1189458055408295936

**Comment by Coxlin19** [comment]
I am very happy to hear from you, thank you for your efforts.

Peter <notifications@github.com> 于 2019年11月2日周六 上午3:05写道：

**Comment by 8bitPit** [comment]
Thanks @Coxlin19 😁
