### ISSUE TITLE
Show battery percentage does not work

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1044]
**Describe the bug**
Show battery percentage toggle in At glance does nothing.

**Smartphone:**
 - Device: Nokia 5
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
Whoops. This feature is WIP and shouldn't have gone public yet 😅. I'll remove the toggle ASAP.
Thanks for letting me know Martin.

**Comment by 8bitPit** [comment]
Fixed in v.0.9.10
