### ISSUE TITLE
Pinyin categorization does not work for Traditional Chinese.

### ISSUE THREAD

**Issue by wfchang1975** [8bitPit/Niagara-Issues#1045]
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Thanks for the report @wfchang1975, I'll fix this.

**Comment by 8bitPit** [comment]
Fixed in v.0.9.10
