### ISSUE TITLE
Option to hide notification for some apps

### ISSUE THREAD

**Issue by Daniel-Brum** [8bitPit/Niagara-Issues#1047]
There is a persistent notification in my phone that is actually useful, so I wouldn't want to disable it, but in Niagara it only appears as an empty notification. It's not that annoying, but I often lose some seconds scrolling the app list, then scrolling back because it looked like I missed one notification, and then notice it's only this persistent notification (that I can't even read by swiping in the app, because the notification still shows as "empty").

![S91104-185630](https://user-images.githubusercontent.com/28717308/68164340-570af500-ff3b-11e9-87b7-026851b03bdd.jpg)
The notification in my notification bar

![S91104-185159](https://user-images.githubusercontent.com/28717308/68164379-6c801f00-ff3b-11e9-9054-12d3219a6c71.jpg)
Notification in the launcher

![S91104-063734](https://user-images.githubusercontent.com/28717308/68164447-8faace80-ff3b-11e9-9062-203500725eb5.jpg)
What I get when I swipe on the app to see the notification

A good solution for that, in my opinion, would be giving the user an option to hide notifications from some apps. This could also be the solution of the "want to hide music player notifications but don't want to lose the ability to show the other notifications" problem.

Edit: added some screenshots

**Comment by 8bitPit** [comment]
Thank you @Daniel-Brum  for taking the time to write your issue in such detail :)

>A good solution for that, in my opinion, would be giving the user an option to hide notifications from some apps. 

Android O/P/Q provide you the option to only hide notifications for certain apps. Simply go to the app's info screen and disable "Allow notification dot".  
![image](https://user-images.githubusercontent.com/9284845/68280141-3a72d800-0075-11ea-892a-0c2a5fe33d67.png)

Hope this helps.

**Comment by Daniel-Brum** [comment]
Thanks a lot for your reply! My phone doesn't have any of these versions of Android, but fortunately it seems that there is an option for that (it's Android 7 modified by Meizu). This could really be a good option, but in some cases the idea is to hide the notification only in Niagara, not in the notification bar (as in this case, because the notification in the notification bar is actually useful, it's just in Niagara that it doesn't display anything).

**Comment by 8bitPit** [comment]
Thanks. The "Allow notification dot" option only disables home screen notifications but not status bar notifications.

**Comment by Daniel-Brum** [comment]
Oh, now I got it. Thanks for explaining haha

Unfortunately, my phone doesn't seem to have this option (it does have some nice ones, though; today I learned how to stop apps from showing notifications as "pop-ups" on the top of the screen), so this wouldn't be possible to me. But your solution is right, feel free to close the issue if you want. Thanks a lot for your attention and help!

**Comment by 8bitPit** [comment]
That's a bummer, hope this doesn't bother you too much then.
