### ISSUE TITLE
Add clone app icon in the home sreen.

### ISSUE THREAD

**Issue by 54mv39** [8bitPit/Niagara-Issues#1049]
**Excerpt:**
After using the launcher from day one I promised myself I will only suggest missing features and I think it is the right time to suggest this. If i clone my apps; only the main app is visible in the home screen list. While after selecting the main app I can select the cloned one via another small screen that comes up; but it really affects the UX at that point and management as a whole.

**Request:** 
- Make cloned app icon available on the home screen list with the original app icon.

**Comment by 8bitPit** [comment]
Hi @54mv39, thanks for your request. Can I ask you how you clone your apps? I'm using [Island](https://play.google.com/store/apps/details?id=com.oasisfeng.island&hl=en) to add a work profile which allows me to have installed the same app multiple times. Cloned apps show app multiple times in my app list. I recommend to try out the same app and test if this also works on your device.

**Comment by 54mv39** [comment]
Im using a ColorOS version 6.0.1 device. The OS has a built in feature to clone supported apps. I have cloned WatsApp and Instagram. Both show same behavior. 

> I recommend to try out the same app and test if this also works on your device.
yes I know about that app but i found ColorOS system cloner much hassle free. Maybe something could be done to support the feature without the use of another app?

**Comment by 8bitPit** [comment]
@54mv39 Do other third-party launchers like Lawnchair Launcher support this?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
