### ISSUE TITLE
Media notification doesn't show cover / can't be dismissed

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1052]
1 - album art doesn't appear for Spotify
2 - when dismissing the media player after stopping playback, it reappears and becomes undismissable

**Comment by Orbeatle** [comment]
Any progress being made in fixing this bug? One of the few (if only one) bugs in this other perfect launcher!

**Comment by 8bitPit** [comment]
@Orbeatle yes, we developed a workaround and do currently some internal testing. Expect a patch in the next few weeks (if everything goes right).

**Comment by 8bitPit** [comment]
Fixed in v.0.18.0
