### ISSUE TITLE
"Use device theme" does not work for the launcher theme

### ISSUE THREAD

**Issue by grantsrosen** [8bitPit/Niagara-Issues#1054]
**Describe the bug**
I have the dark theme on my phone settings (system theme) set to enable from 6 pm to 6 am. All of my apps that support system theme follow this, staying light in the day and dark at night. Niagara is always dark, despite being set to "follow system theme". The attached screenshot was taken at noon, when my system theme is light (notice Niagara is dark).

**To Reproduce**
1. Set system dark theme to a time frame for night
2. Set Niagara dark theme to "follow system theme" 
3. Wait until daytime

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - Android version: e.g. Android 9 (Pie)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

![Screenshot_20191108-121508_Niagara Launcher](https://user-images.githubusercontent.com/49496173/68507733-734fb000-0221-11ea-9b60-4a7dad43040e.jpg)

**Comment by 8bitPit** [comment]
Thanks for the report @grantsrosen.

**Comment by yamnem** [comment]
I'm having the same issue. I have dark mode scheduled on my phone (Android Pie, MIUI11). Whenever Niagara's theme is set to 'device theme' it always sets Niagara to dark mode, regardless of system's scheduled theme. Seems to me as if Niagara interpets the scheduled state of the device theme as a default dark mode.

**Comment by 8bitPit** [comment]
Can I ask you guys if you're both using a dark wallpaper?

**Comment by grantsrosen** [comment]
> Can I ask you guys if you're both using a dark wallpaper?

I am using a dark wallpaper, yes. Though "dark theme" and "text color" are two separate settings in Niagara, they shouldn't affect each other should they?

**Comment by 8bitPit** [comment]
Text color and dark theme option don't affect each other, but on Android Pie, the stock Android Launcher called Launcher 3 uses dark theme when the wallpaper is dark. That's why Niagara does the same.

**Comment by yamnem** [comment]
Damn, I too have a dark wallpaper, I'd never imagined that that would be the issue. Is there any way to get around it? I'll try switching to a lighter wallpaper to see if the 'bug' persists.

**Comment by grantsrosen** [comment]
> Text color and dark theme option don't affect each other, but on Android Pie, the stock Android Launcher called Launcher 3 uses dark theme when the wallpaper is dark. That's why Niagara does the same on pie and 10

Might there be a way to update Niagara to follow the system theme on Samsung devices?

**Comment by zebateira** [comment]
I also stumbled upon this issue. I'm using Android 10 and Niagara is one of the very few apps that stays on wrong theme part of the day, not following the system theme when others do because of the sunrise/sunset schedule of dark theme/light theme.

Amazing launcher @8bitPit! Thank you for the hardwork! 🙏 On the of best launchers I've found lately 👌♥️

**Comment by 8bitPit** [comment]
thanks for your kind words @zebateira 😊 @yamnem, @grantsrosen & @zebateira how about ignoring the wallpaper on all devices running Android 10+?

**Comment by zebateira** [comment]
> how about ignoring the wallpaper on all devices running Android 10+?

Sounds great 🎉

**Comment by 8bitPit** [comment]
v0.32 introduced a new dark theme option on Android 10, which will enable dark theme only when the system theme is set to dark.
