### ISSUE TITLE
The setup button shows wrong translation 

### ISSUE THREAD

**Issue by WendySclerandi** [8bitPit/Niagara-Issues#1055]
In the apps menu, the setup button of Niagara shows like this:

![Screenshot_2019-11-11-01-55-58-838_bitpit launcher](https://user-images.githubusercontent.com/21165322/68562400-3570a880-0428-11ea-8f1c-6bc2b103d5f2.png)

 - Device: Xiaomi Redmi Note 7
 - Android version: Android 9 MIUI global 10.3.6
- Niagara version: 0.9.10

**Comment by 8bitPit** [comment]
Thanks @WendySclerandi, this should be fixed in v0.9.11

**Comment by 8bitPit** [comment]
Fixed in v.0.9.11
