### ISSUE TITLE
Uninstalling an app from the app's info screen will result in the options still showing

### ISSUE THREAD

**Issue by shmykelsa** [8bitPit/Niagara-Issues#1057]
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
![image](https://user-images.githubusercontent.com/9965637/69057051-7a40a480-0a11-11ea-9ff9-127b94dfae65.png)

**Comment by 8bitPit** [comment]
So you long press an app, open the info screen, uninstall it and then the dialog doesn't close, right?

**Comment by shmykelsa** [comment]
> So you long press an app, open the info screen, uninstall it and then the dialog doesn't close, right?

Correct. At the time of screenshot the app "lite" was indeed Uninstalled. The dialog stayed there. Some times Niagara goes back to favourite screen, sometimes it's on the app drawer.

I think this behaviour is partly because I don't go back from the settings app, but the settings app closes itself bringing me back to Niagara where I left.

**Comment by 8bitPit** [comment]
All right, thanks for the reply.

**Comment by 8bitPit** [comment]
It depends on how long you wait after going back to Niagara. If you press back immediately after opening another app Niagara will still show the dialog in case you pressed the wrong option.
