### ISSUE TITLE
Icon theme to work throughout device.

### ISSUE THREAD

**Issue by swooned** [8bitPit/Niagara-Issues#1058]
Using Samsung tab S4
Latest Android OS.

I don't k own if it is a bug, but it would be grrwet for the icon theme to work throughout the whole device, as stupid Samsung do not have a theme change option in settings, only wallpaper, for their tablets. Themes can change on their phones. Sad.
![Screenshot_20191116-182141_Niagara Launcher](https://user-images.githubusercontent.com/16494547/69093709-1a92d980-0aa3-11ea-80dd-0a2a4bbc6c17.jpg)
![Screenshot_20191116-182145_One UI Home](https://user-images.githubusercontent.com/16494547/69093710-1a92d980-0aa3-11ea-9ce1-f47164dea439.jpg)

**Comment by 8bitPit** [comment]
Hi @swooned, unfortunately this is not possible (at least on unrooted devices), because the recents screen is from Samsung, I cannot provide my own.
