### ISSUE TITLE
Widget page

### ISSUE THREAD

**Issue by ratanavv** [8bitPit/Niagara-Issues#1059]
It would be nice if possible have widget page under favorite page on Home screen. When reach the last app on favorite page then one more swipe up will load to widget page, so it could add more widget without mess with home screen.
Thanks.

**Comment by 8bitPit** [comment]
Hi @ratanavv, please refer to https://github.com/8bitPit/Niagara-Issues/issues/117:
> I am not really a fan of widget pages. The only thing widgets have in common there is, well, they’re all widgets. So why should they be grouped together? Showing a weather widget below the clock and accessing your calendar agenda via a swipe / by tapping on a button makes more sense to me. Also, widgets often tend to use much ram. The concept of a widget list would kind of endorse user to cluster the page full of widgets. A swipe menu shows only a single widget at once, so not every widget has to be loaded into ram when you want to access one.
That’s why I’m planning to add the following integration:
You can place a single widget below the clock or replace it for showing weather and / or time, or an at a glance widget.
More widgets can be accessed by swiping right on an app.
Another idea would be that you can customize the google search button at the bottom right, so it can also launch a widget, e.g. your calendar. [[Source](https://github.com/8bitPit/Niagara-Issues/issues/117#issuecomment-464157151)]

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
