### ISSUE TITLE
Vertical scrolling app list. 

### ISSUE THREAD

**Issue by FireLight25** [8bitPit/Niagara-Issues#106]
Navigating apps through character scroll is a great idea, but just swiping finger up for app drawer is more natural. And to come back home from app drawer should be like scroll down till the first app. Again scroll down to come back to home screen (favorite apps).

**Comment by 8bitPit** [comment]
Probably will be implemented. However just opening it with a gesture, wouldn't be helpful in my opinion, since you have to scroll anyway.
