### ISSUE TITLE
Wallpaper not being centered

### ISSUE THREAD

**Issue by LunarNSolar** [8bitPit/Niagara-Issues#1060]
![](https://cdn.discordapp.com/attachments/424620627933265921/648205459404357652/Screenshot_20191124-174957_Smart_Launcher.jpg)
This image shows the wallpaper is supposed to fit

![](https://cdn.discordapp.com/attachments/424620627933265921/648205459991429155/Screenshot_20191124-175006_Niagara_Launcher.jpg)
This image shows how the wallpaper fits in the Niagara Launcher

Any reason as to why this would happen?
The wallpaper is applied with a theme from Galaxy Themes

**Comment by 8bitPit** [comment]
Thanks for letting me know @LunarNSolar, I'll try to fix it.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/688
