### ISSUE TITLE
Suggest Niagara as a home application and widget issue

### ISSUE THREAD

**Issue by Prabhu1107** [8bitPit/Niagara-Issues#1061]
1). When I installed  it other launcher and uninstall it and while coming back to Niagara it should ask automatically select home application.

2). If I add the widgetto home screen half of the wallpaper will not be visible. Do something for that. 

I have solution for widget you can make it transparent or it should be in another  format.

**Comment by 8bitPit** [comment]
Hi @Prabhu1107, Niagara Launcher only checks every now and then if it's set as default home screen instead of doing it constantly to preserve your battery.
Furthermore, swipeable widgets are planned, check out https://github.com/8bitPit/Niagara-Issues/issues/1059 for more info.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
