### ISSUE TITLE
Notification issue 

### ISSUE THREAD

**Issue by Ladyvb22** [8bitPit/Niagara-Issues#1062]
**Describe the bug**
![Capture+_2019-11-24-15-18-19](https://user-images.githubusercontent.com/49797397/69500920-b4a4b880-0ecd-11ea-8e20-f82acd434f87.png)

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
I'm sorry, this can happen from time to time, unfortunately. Please try restarting your phone.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
