### ISSUE TITLE
Hide apps

### ISSUE THREAD

**Issue by jayahuja5** [8bitPit/Niagara-Issues#1063]
Like one plus slide right to see hide apps

Add in favourite menu, slide right to show hide apps or new features.

**Comment by 8bitPit** [comment]
Hi @jayahuja5, unfortunately all horizontal slide gestures are already taken (Swiping right opens the action menu of an app and swiping left dismisses app notifications if an app has any.)
However, you can access hidden apps quickly with Niagara's app search. Furthermore you could enable, "press home to search" to get to them even quicker. Hope this helps.

**Comment by jayahuja5** [comment]
> Hi @jayahuja5, unfortunately all horizontal slide gestures are already taken (Swiping right opens the action menu of an app and swiping left dismisses app notifications if an app has any.)
> However, you can access hidden apps quickly with Niagara's app search. Furthermore you could enable, "press home to search" to get to them even quicker. Hope this helps.

Thank you
