### ISSUE TITLE
Improve non-Latin character handling in search

### ISSUE THREAD

**Issue by MajorMajorMajorMajor** [8bitPit/Niagara-Issues#1066]
When the phone language is set to Russian, many apps, including Google apps, localize their names. As an example, "Photos" becomes "Фото" (romanization: "Foto").

In Niagara 0.9.8, romanization worked in search. For example, searching for 'fo' would match "Фото".

After 0.9.9, this is no longer the case. I tested this all the way through version 0.10.0 and ended up reverting to 0.9.8, where this still works.

**Comment by 8bitPit** [comment]
Thanks for letting me know, I'll investigate this.

**Comment by MajorMajorMajorMajor** [comment]
Please let me know if you need any help testing a fix. I am quite eager to get back to the leading edge :)

**Comment by MajorMajorMajorMajor** [comment]
Just checking if this has been fixed in the latest release by any chance?

**Comment by 8bitPit** [comment]
Sorry, I hope you can understand that this is not a high priority bugfix, this can take a little. For now, you could also append the romanized app name to the original app name, e.g. "Фото" becomes "Фото - Foto"

**Comment by 8bitPit** [comment]
Hey, sorry for keeping you waiting. This will be fixed in v0.26.

**Comment by MajorMajorMajorMajor** [comment]
Oh, amazing! Looks like it'll be a big update for me!!!

Thank you!

сб, 2 мая 2020 г., 6:40 Peter Huber <notifications@github.com>:

**Comment by 8bitPit** [comment]
@MajorMajorMajorMajor you're welcome :D

**Comment by 8bitPit** [comment]
Fixed in v.0.26.0

**Comment by MajorMajorMajorMajor** [comment]
Hello!

Appreciate the effort, but I can still reproduce this on 0.26.0 (premium purchased).

The workaround is not that good, because it means that I have to give a custom name to literally every app, and it resets every time the language changes.

**Comment by 8bitPit** [comment]
Just checked and recognized that only the first letter of apps are getting romanized. This might be changed in the future. ![image](https://user-images.githubusercontent.com/9284845/81475086-1a7dc600-920a-11ea-939c-84e72e1e0c3c.png)

**Comment by 8bitPit** [comment]
Update: We're planning to migrate to Android's new [App search library](https://developer.android.com/jetpack/androidx/releases/appsearch) once it's stable. The library looks promising and seems to take care of romanization.

**Comment by Lysander086** [comment]
The same issue applies to Japanese character.

**Comment by Maxr1998** [comment]
Fixed in [v1.10.0](https://github.com/8bitPit/Niagara-Issues/releases)🎈 This should improve Russian, Japanese, Chinese Korean and Greek app search.
