### ISSUE TITLE
Switching between applications sometimes hangs

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1067]
**Describe the bug**
App view sometimes doesn't open apps.

**To Reproduce**
When I'm in the the app switcher view, sometimes selecting an app will not open it. Instead I'm still stuck in the view. After some seconds or opening another app, it normally works somehow.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 XL
 - Android version: Android 10 Nov 2019

![Screenshot_20191130-193112](https://user-images.githubusercontent.com/13085980/69904554-05258580-13a8-11ea-93bd-9d5c710d1d5d.png)

**Comment by 8bitPit** [comment]
I'm sorry but I can't help you there. Niagara Launcher does not handle the recents screen. On Android 9 & 10, your preinstalled launcher does that.

**Comment by andys8** [comment]
Oh, something I didn't know. So, you did help me ;) Thanks

**Comment by 8bitPit** [comment]
Haha, no problem 😉
