### ISSUE TITLE
Clock not showing / Clock cropped

### ISSUE THREAD

**Issue by filikun** [8bitPit/Niagara-Issues#1069]
**Describe the bug**
Pro user trying out the new whether integration. On the same page there is "show date" and "show clock" but ticking "show clock" does not seem to add a clock for me at all.

**To Reproduce**

Now I have this in Swedish so this will be me translating it.
1. Go to 'Functions'
2. Click on 'Overview'
3. Click on 'Show clock'

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - Android version: A10 (the bad stable version)

**Screenshots**
https://imgur.com/a/peomaGO

**Comment by 8bitPit** [comment]
Sorry about that. You can manually move the clock by tapping on a favorized app > open edit mode > scroll all the way down > move whole list.

**Comment by filikun** [comment]
Oh! So it was that easy 👍

**Comment by 8bitPit** [comment]
Glad it helped. However, I still think there's a bug in the code, because the clock should be visible by default. Was the clock hidden since you installed Niagara?

**Comment by filikun** [comment]
Yeah, I usually only use Google's "At a glance" widget so I had clock, weather and date turned off. Glad to have it integrated now though!

**Comment by Montell2099** [comment]
@8bitPit Once I turned off the At a Glance-widget to add the default clock, with the new weather integration, this same thing happened to me.

**Comment by 8bitPit** [comment]
@Montell2099 @filikun Thanks for letting me know guys :D

**Comment by niakoi1** [comment]
I had described this bug months ago, when widgets were first introduced. It still exists.
Here is what happens.  Turn off at a glance and clock in settings. Add a widget. Move the widget all the way up. Now turn back on the "at a glance" and clock. At a glance will appear pushing down the widget, but the clock will stay off the screen. To show it, you will have to manually click "resize" widget, then move the widget down. And voila, you have the clock. Minor bug, but sometimes frustrating especially for a PRO  version.

**Comment by 8bitPit** [comment]
@niakoi1 sorry for the inconvenience. I'm currently pretty busy pushing a Weeks-of-Winter update every week, but I'll fix the bug once I got more time.

**Comment by 8bitPit** [comment]
Fixed in v.1.4
