### ISSUE TITLE
Share link not working

### ISSUE THREAD

**Issue by Topaz8** [8bitPit/Niagara-Issues#107]
So I wanted to make my friend enjoy this app as I do.
But the play store link(through the app) I sent to him says it does exist.
But when I send through play store itself, it works. Please have a look at that 😊

**Comment by 8bitPit** [comment]
Thank you very much! Yes, the link is broken ("com" shouldnt be in the link. Will be patched by the next update

**Comment by Topaz8** [comment]
You're welcome 😊. I'm digging for more

**Comment by 8bitPit** [comment]
Fixed with the latest Update
