### ISSUE TITLE
Home Screen Lock 

### ISSUE THREAD

**Issue by ajaykumar-s** [8bitPit/Niagara-Issues#1070]
Please update home screen lock,
Home Screen search bar

**Comment by 8bitPit** [comment]
Hi @ajaykumar-s. I'm sorry, but can you please elaborate more what you mean by "updating" the home screen lock and search bar?

**Comment by jayahuja5** [comment]
Customized home screen and lock screen may be.

**Comment by jayahuja5** [comment]
> Hi @ajaykumar-s. I'm sorry, but can you please elaborate more what you mean by "updating" the home screen lock and search bar?

Customized home screen and lock screen may be.

**Comment by 8bitPit** [comment]
Hey again. For now, I want to focus on making a great home screen, there's enough room for improvement there. 😅 I'm sorry, but I simply don't have enough time for that.
