### ISSUE TITLE
Change background, icons and fonts based on day time

### ISSUE THREAD

**Issue by hgmart** [8bitPit/Niagara-Issues#1071]
During daylight is better to see a white background to search and finds things easily. Because it has better contrast but during night it is painful to see at such a bright display.

It would be great to personalize all the launcher settings based on time of the day. Background, fonts, colors, icons even perhaps favorites apps.

**Comment by 8bitPit** [comment]
Hi @hgmart, I believe this is a duplicate of: #640

**Comment by 8bitPit** [comment]
Duplicate of #640
