### ISSUE TITLE
Request: Hide Launcher from Recents Menu

### ISSUE THREAD

**Issue by mirfalltnixein** [8bitPit/Niagara-Issues#1075]
**Problem**: When Niagara is not set as default launcher it shows up in Recents (=Task Manager). Most launchers avoid doing this.

**Use Case**: I switch Launchers based on wether I'm at work or not, to do that I use Tasker with AutoTools. AutoTools is set as default launcher, and just picks the launcher to actually open based on my set conditions. Annoyingly (and unlike most launchers), Niagara does show up in recents that way.

**Solution**: Niagara should be hidden from Recents. Apparently it should just be one setting in the manifest file. [StackOverflow: How to remove application from recent application list?](https://stackoverflow.com/questions/3762763/how-to-remove-application-from-recent-application-list)

**Comment by 8bitPit** [comment]
Hi. Thanks for the request, I'll do that.

**Comment by 8bitPit** [comment]
Implemented in v0.11.0
