### ISSUE TITLE
Weather pop up remains after switching to other app

### ISSUE THREAD

**Issue by acid1232** [8bitPit/Niagara-Issues#1077]
When I open new weather pop up, switch to other app and return to home again pop up is still open

**Comment by 8bitPit** [comment]
Thanks, I'll take core of it.

**Comment by Montell2099** [comment]
@8bitPit Thanks for sorting out the width/margin in the weather pop-up so the last visible day doesn't cut off — also adding a slight fade when scrolling between days. Perfect.

**Comment by 8bitPit** [comment]
Welcome @Montell2099 😁

**Comment by 8bitPit** [comment]
The pop up will close if you leave Niagara Launcher for more than ~5 seconds.
