### ISSUE TITLE
Notifications not showing Icons/label

### ISSUE THREAD

**Issue by mgithuber** [8bitPit/Niagara-Issues#1078]
I have a problem in my Android 5.0.2 device. Niagara's inbuilt Notifications not showing Groups, Channels, Webpage Icons or label. Pls see the below screenshots to see the differences . First screenshot is from Android 5.0.2. Second one is from Android 7.1.2.

First Screenshot from Android 5.0.2 device

![Screenshot_2019-12-10-08-47-48](https://user-images.githubusercontent.com/50730036/70493105-94f7cc00-1b2c-11ea-9dc6-645b5bbea2d9.jpg)

Second screenshot from Android 7.1.2 device

![IMG_20191210_085035](https://user-images.githubusercontent.com/50730036/70493250-fa4bbd00-1b2c-11ea-86af-7fc04fff532c.jpg)

Now you can see the difference in above two Screenshots. Here actual problem is Niagara Notifications not  showing Telegram Group  Icons/ label 'Esica' in Android 5.0.2. .pls fix this bug

Phone: Asus Zenfone 2 Laser
Android Version: 5.0.2, ZenUI
Launcher Version: 0.10.3 Pro( I have Niagara pro version)

**Comment by 8bitPit** [comment]
Hi @mgithuber. Android added proper group messaging support with Android 7. I've already implemented a couple of workarounds for Android 6, but there is not much I can do for your Android 5 device, sorry.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
