### ISSUE TITLE
New weather widget disappears

### ISSUE THREAD

**Issue by FreshPrince85** [8bitPit/Niagara-Issues#1079]
**Describe the bug**
The new weather widget disappears after closing Launcher settings.

**To Reproduce**
1. Go to 'Launcher Settings'
2. Click twice on the Android left-facing triangle button, which took users back one step or screen
3. The new weather widget disappears

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro (MIUI Global 11.0.3)
 - Android version: 10

**Comment by FreshPrince85** [comment]
**Before opening Launcher Settings**

![image](https://user-images.githubusercontent.com/58727843/70595871-b87e4d80-1be4-11ea-97a4-15144d3994ec.png)

**After**

![image](https://user-images.githubusercontent.com/58727843/70595841-a6041400-1be4-11ea-843c-28881fda4be6.png)

**Comment by 8bitPit** [comment]
Thank you for your report, I'm trying to reproduce it.

**Comment by 8bitPit** [comment]
Fixed in v.0.11.4
