### ISSUE TITLE
Battery percentage shown over Clock if Date is not selected.

### ISSUE THREAD

**Issue by jkwanness** [8bitPit/Niagara-Issues#1081]
**Describe the bug**
The battery percent is shown over the clock if i didn't choose to show the date or weather in At A Glance.

I prefer to use Google's at a glance as my widget..

**To Reproduce**
1. Select show battery percentage in at a glance
2. Select show clock.
3. Do not show weather or date.

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - Android version: Android 10

**Screenshots**
![Screenshot_20191211-154714](https://user-images.githubusercontent.com/58766705/70602213-d7a1cd00-1c2e-11ea-998d-e75f0923eccb.jpg)

**Comment by 8bitPit** [comment]
Thank you for the bug report

**Comment by 8bitPit** [comment]
Should work properly on v0.10.5
