### ISSUE TITLE
adjust vertical height of favorites

### ISSUE THREAD

**Issue by mercival** [8bitPit/Niagara-Issues#1082]
Before the edit tool was introduced, I remember being able to adjust the vertical position of the favorites column with a long press just above the first icon on the home screen, but i can't seem to be able to do this anymore, or locate it in settings.  Was this removed, or am i missing how to do this?

Thank you!

**Comment by 8bitPit** [comment]
You can move your favorites by scrolling all the way down in edit mode and tap on "move whole list". I have to admit, that the new button is a bit too hard to find.

**Comment by mercival** [comment]
ah, I see now. thanks for the clarification :)

**Comment by 8bitPit** [comment]
Welcome :D
