### ISSUE TITLE
Update weather location automatically based on GPS

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1083]

**Comment by Djspaceg** [comment]
Some details regarding the UI and radio buttons during location selection:

Upon looking into my settings, I noticed that the UI (Settings -> At a glance -> Weather -> Location) doesn't visually indicate the current selection (in the popup). Each of the radio items appears unselected, even after choosing "Current location", or the static current city. This makes it difficult to verify what your current selection is assigned as.

As a user, my assumption is that the selection "Current location" will update/change as I move on some automatic interval, while the first option "" is a way to statically select that place in a way that won't automatically change as I travel; initially based on the currently reported location.

**Comment by 8bitPit** [comment]
@Djspaceg agreed, the dialog's far from ideal.

**Comment by Bohne13** [comment]
I hope this feature will make it in upcoming releases

**Comment by 8bitPit** [comment]
Implemented in v0.19.0
