### ISSUE TITLE
Smart lock not working Samsung S10+

### ISSUE THREAD

**Issue by oakteal** [8bitPit/Niagara-Issues#1085]
Phone does not automatically unlock when trusted places is selected in Smart lock - lock screen. It does with MS launcher and Samsung launcher.

Samsung Galaxy S10 plus
Android 10
Niagara 0.10.3 not pro

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by oakteal** [comment]
On review smart lock is very variable and issue also exists on MS launcher and One UI.

**Comment by 8bitPit** [comment]
Hi @oakteal, that's a bummer. I believe this doesn't get caused by Niagara Launcher.
