### ISSUE TITLE
Up-swipe from bottom of screen not recognized.

### ISSUE THREAD

**Issue by RCNet46** [8bitPit/Niagara-Issues#1086]
**Describe the bug**
With the latest releases 0.10.2, 0.10.3, and 0.10.4 Android 10 System Gestures are no longer recognized when trying to swipe up from the bottom of the screen while edge swipes work fine.  This is true for both "Gesture navigation" and "2-button navigation" while "3-button navigation" seems to work normally.  When in 2-button navigation mode, the taps on the back and home button are acknowledged , but again nothing happens.

**To Reproduce**
1. Select either Gesture navigation or 2-button navigation from the Settings-> System -> Gestures -> System navigation menu.
2. Swipe up from bottom of screen or press on back or home buttons on screen.

**Smartphone (please complete the following information):**
 - Device: Essential PH-1
 - Android version: Android 10 with Dec 5, 2019 Security patch

**Screenshots**
N/A

**Comment by RCNet46** [comment]
Nevermind.  Rebooted phone and gestures started working as expected.

**Comment by 8bitPit** [comment]
Glad to hear it :)
