### ISSUE TITLE
App does not show inline notifications when they work everywhere else

### ISSUE THREAD

**Issue by jtagg82** [8bitPit/Niagara-Issues#1087]
**Describe the bug**
The app FairEmail does not show any notifications in the app list even though they show up in the Android notification panel and when I swipe the app to the right. This only happens in this app so it might be related to it specifically, but Niagara clearly sees the notification in order to show it in the right swipe. I have not noticed this issue with any other app.

**To Reproduce**
1. Receive email
2. Notification for FairEmail pops up in the notification top panel in Android
3. In the app list in Niagara, nothing changes
4. Swipe FairEmail app to the right, and the notification shows up there

Steps I have tried:
Turn notifications on and off again for FairEmail.
Removed notification access from Niagara and gave access again.
I checked that notifications are indeed active for the app and they work everywhere else.

**Smartphone (please complete the following information):**
Xiaomi Mi A2, Android 9

**Screenshots**
![Screenshot_20191212-162824](https://user-images.githubusercontent.com/7040490/70755548-68b19a80-1d3a-11ea-9fb1-70df6d743623.png)
![Screenshot_20191212-162923](https://user-images.githubusercontent.com/7040490/70755568-79faa700-1d3a-11ea-8144-a7b800e2a8a3.png)

Notice in the background of the second picture that FairEmail shows no notification in the list.

**Comment by jtagg82** [comment]
In the screenshots the app is called Email. I renamed it to that from FairEmail.

**Comment by 8bitPit** [comment]
Thanks for going into such detail @jtagg82. Niagara Launcher filters out some notifications. Have you enabled notification dots for FairEmail? https://github.com/8bitPit/Niagara-Issues/issues/920

**Comment by jtagg82** [comment]
Yes, dots are active. Here are the settings
![Screenshot_20191216-213723](https://user-images.githubusercontent.com/7040490/70941245-4e363480-204c-11ea-81bd-968f8d0cae42.png)
![Screenshot_20191216-213740](https://user-images.githubusercontent.com/7040490/70941295-6c039980-204c-11ea-8e2d-3afa1392c5b1.png)

**Comment by 8bitPit** [comment]
Hmm... could you please send me Niagara's notification log? You can share it by typing "/notifications" into Niagara's app search bar. But please remove all personal information from the log before you share it.

**Comment by jtagg82** [comment]
Here is the log which includes FairEmail notifications which I hadn't yet acknowledged but did not show in the app list.

Disclaimer: This log might include personal information. Device: jasmine Manufacturer: xiaomi Android version: 28 No. of visible notifications: 4 eu.faircode.email - 3 new messages - 3 new messages prio: 0 has low priority: false cat: status text: 3 new messages android.title: 3 new messages android.reduced.images: true android.subText: null android.template: android.app.Notification$BigTextStyle android.showChronometer: false android.icon: 2131230994 android.text: 3 new messages android.progress: 0 android.progressMax: 0 android.appInfo: ApplicationInfo{bb9ce8a eu.faircode.email} android.showWhen: false android.largeIcon: null android.bigText: Peter: Re: [8bitPit/Niagara-Issues] App does not show inline notifications when they work everywhere else (#1087) 19/12/2019 16:03 Service-public.fr: Suivi de vos actualités préférées : Inscriptions sur les listes électorales : jusqu'à quand ? (service-public.fr) 19/12/2019 16:08 xkcd comic: xkcd #2243: Star Wars Spoiler Generator 19/12/2019 17:08 android.infoText: null android.progressIndeterminate: false android.remoteInputHistory: null android.summaryText: 3 new messages local_only group_summary show: true filter: true imp. expl.: You set the importance of these notifications. importance: 4 low importance: false sentiment: positive eu.faircode.email - xkcd comic - xkcd #2243: Star Wars Spoiler Generator prio: 0 has low priority: false cat: email text: xkcd #2243: Star Wars Spoiler Generator android.title: xkcd comic android.reduced.images: true android.subText: Net-C · Inbox android.template: android.app.Notification$BigTextStyle android.showChronometer: false android.icon: 2131230996 android.text: xkcd #2243: Star Wars Spoiler Generator android.progress: 0 android.progressMax: 0 android.appInfo: ApplicationInfo{3c72cfb eu.faircode.email} android.showWhen: true android.largeIcon: android.graphics.Bitmap@a4d118 id: 5958 android.bigText: xkcd #2243: Star Wars Spoiler Generator Star Wars Spoiler Generator The heroes seem to be gaining the upper hand until Darth Juul manages to flip the switch on the car wash control panel from 'REGULAR' to 'PREMIUM.' My new book, How To: Absurd Scientific Advice for Common Real-World Problems, is available now! Chapters include How to Move, How to Ski, How to Build a Lava Moat, and How to Make an Emergency Landing (that last chapter features advice from astronaut and test pilot Chris Hadfield.) Buy it here: Amazon, Barnes & Noble (Excl… android.infoText: null android.wearable.EXTENSIONS: Bundle[mParcelledData.dataSize=944] android.progressIndeterminate: false android.remoteInputHistory: null android.summaryText: xkcd #2243: Star Wars Spoiler Generator android.colorized: true only_alert_once local_only show: true filter: true imp. expl.: You set the importance of these notifications. importance: 4 low importance: false sentiment: positive eu.faircode.email - Service-public.fr - Suivi de vos actualités préférées : Inscriptions sur les listes électorales : jusqu'à quand ? (service-public.fr) prio: 0 has low priority: false cat: email text: Suivi de vos actualités préférées : Inscriptions sur les listes électorales : jusqu'à quand ? (service-public.fr) android.title: Service-public.fr android.reduced.images: true android.subText: Net-C · Inbox android.template: android.app.Notification$BigTextStyle android.showChronometer: false android.icon: 2131230996 android.text: Suivi de vos actualités préférées : Inscriptions sur les listes électorales : jusqu'à quand ? (service-public.fr) android.progress: 0 android.progressMax: 0 android.appInfo: ApplicationInfo{e728771 eu.faircode.email} android.showWhen: true android.largeIcon: android.graphics.Bitmap@e6e4956 id: 5957 android.bigText: Suivi de vos actualités préférées : Inscriptions sur les listes électorales : jusqu'à quand ? (service-public.fr) Mise à jour de la page à laquelle vous êtes abonné(e). | service-public.fr L'équipe service-public.fr Bonjour, Une actualité vient d'être publiée sur un sujet auquel vous êtes abonné(e). Inscriptions sur les listes électorales : jusqu'à quand ? Pour pouvoir voter aux élections municipales prévues en mars 2020, il faut être inscrit sur les listes électorales. Cette démarche est possible jusqu'au vendredi 7 février 2020 (et non plus jusqu'au 31 décembre de l'année précédant le scrutin comme cela é… android.infoText: null android.wearable.EXTENSIONS: Bundle[mParcelledData.dataSize=944] android.progressIndeterminate: false android.remoteInputHistory: null android.summaryText: Suivi de vos actualités préférées : Inscriptions sur les listes électorales : jusqu'à quand ? (service-public.fr) android.colorized: true only_alert_once local_only show: true filter: true imp. expl.: You set the importance of these notifications. importance: 4 low importance: false sentiment: positive eu.faircode.email - Peter - Re: [8bitPit/Niagara-Issues] App does not show inline notifications when they work everywhere else (#1087) prio: 0 has low priority: false cat: email text: Re: [8bitPit/Niagara-Issues] App does not show inline notifications when they work everywhere else (#1087) android.title: Peter android.reduced.images: true android.subText: Net-C · Inbox android.template: android.app.Notification$BigTextStyle android.showChronometer: false android.icon: 2131230996 android.text: Re: [8bitPit/Niagara-Issues] App does not show inline notifications when they work everywhere else (#1087) android.progress: 0 android.progressMax: 0 android.appInfo: ApplicationInfo{dd19dd7 eu.faircode.email} android.showWhen: true android.largeIcon: android.graphics.Bitmap@ba1e6c4 id: 5956 android.bigText: Re: [8bitPit/Niagara-Issues] App does not show inline notifications when they work everywhere else (#1087) Hmm... could you please send me Niagara's notification log? You can share it by typing "/notifications" into Niagara's app search bar. But please remove all personal information from the log before you share it. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. android.infoText: null android.wearable.EXTENSIONS: Bundle[mParcelledData.dataSize=944] android.progressIndeterminate: false android.remoteInputHistory: null android.summaryText: Re: [8bitPit/Niagara-Issues] App does not show inline notifications when they work everywhere else (#1087) android.colorized: true only_alert_once local_only show: true filter: true imp. expl.: You set the importance of these notifications. importance: 4 low importance: false sentiment: positive

19 Dec 2019 16:03:46 Peter <notifications@github.com>:

**Comment by 8bitPit** [comment]
Thank you for the log. Your notification doesn't get shown, because FairEmail's puts its summary notification under the category "status". Niagara Launcher does not show status notifications because they are often not important enough to be shown. Here's what Android writes about the status-category: "Notification category: ongoing information about device or contextual status."

**Comment by jtagg82** [comment]
Thanks for looking into that. I'll get in touch with the FairEmail developer to see if anything can be done there.

29 Dec 2019 22:14:39 Peter <notifications@github.com>:

**Comment by jtagg82** [comment]
The developer of FairEmail tells me that the way I have set up notifications, I should be getting a summary notification which is labelled as status and each individual message is labelled as email. Is that not what you saw in the notification log I sent you?

Perhaps this is helpful to confirm that we are talking about the same things:

The summary notification is labelled as status:
https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/Core.java#L2782
and individual message notifications are labeled as email:
https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/Core.java#L2906

**Comment by 8bitPit** [comment]
Thank you very much for researching @jtagg82. Yes, that's what I expected. Other Email clients don't use the status category for summaries (I believe they're also labeled as email). Android and other apps may use the notification's category to guess the priority and change the order of notifications. That's why it's better to use the same notification category for individual and summary notifications. 

However, I'll adjust Niagara's algorithm, so status notifications won't be considered as unimportant.

**Comment by jtagg82** [comment]
It's always difficult to assess intent when there are so many options available to use, especially if they can be understood differently by different people. Thanks for taking the time to improve this. Let me know if I can help in validating any changes.

**Comment by 8bitPit** [comment]
Agreed. Thank you for your help as well :)
One last thing, can you please check if notifications show up properly in v0.11.13+?

**Comment by jtagg82** [comment]
I installed v0.11.13 and it now shows notifications for FairEmail now!

**Comment by 8bitPit** [comment]
Great :D

**Comment by 8bitPit** [comment]
Fixed in v.0.11.13
