### ISSUE TITLE
/pro but no pro

### ISSUE THREAD

**Issue by rowlandtock** [8bitPit/Niagara-Issues#1089]
So I purchased /pro yet nothing has changed with my launcher.Its actually giving me the opportunity to purchase this again.
![Screenshot_2019-12-14-09-51-02-640_com google android gm](https://user-images.githubusercontent.com/25535376/70851325-4e221300-1e59-11ea-8f20-dc83203c1cab.jpg)
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by mgithuber** [comment]
Lol don't show order number publically instead show the playstore purchased apps screenshot

**Comment by Slick999** [comment]
I'm having the same issue

**Comment by disacrol** [comment]
@mgithuber I'm curious, what's the harm on showing the order number?

**Comment by mgithuber** [comment]
Smart ppl would use your order number to get Redeem code from the
developer. They will try to fool and trap the developer

**Comment by disacrol** [comment]
I see, didn't know it would be that easy. However, that would require @8bitPit to quite distracted 😉

**Comment by 8bitPit** [comment]
That's a valid concern @mgithuber. In most error cases I'll refund the purchase through Google Play, so the real purchaser gets the money back.

**Comment by 8bitPit** [comment]
@rowlandtock & @Slick999 I hope following these steps resolves the issue: https://hackmd.io/@C1BuMppiTYazZhBH13jY3g/SyKlUgEkL
Please contact me again otherwise / if you want to issue a refund.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
