### ISSUE TITLE
Searching for app name beginning with digit

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1091]
**Describe the bug**
Searching for an app beginning with a digit doesn't show the app when typing the beginning digit. A single letter is enough for apps beginning with a letter. Would be great if one digit would work, too.

**To Reproduce**
1. Search for '9' doesn't show '9gag'
2. Search for '9g' does

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - Android version: 10

**Screenshots**

![Screenshot_20191215-223238](https://user-images.githubusercontent.com/13085980/70865031-a25bee80-1f50-11ea-8929-9e0ec3750793.png)
![Screenshot_20191215-223247](https://user-images.githubusercontent.com/13085980/70865032-a2f48500-1f50-11ea-8e59-f20f61fe9ef9.png)

**Comment by 8bitPit** [comment]
Thanks for reporting, I'll try t fix it.

**Comment by andys8** [comment]
How is it going? Any updates related to this. Sadly this project is closed source, otherwise it might be easy to contribute fixes for small issues like this.

**Comment by 8bitPit** [comment]
Hey, sorry for keeping you waiting. This will be fixed in v0.26.

**Comment by 8bitPit** [comment]
Fixed in v.0.26.0
