### ISSUE TITLE
(hide status bar) Wallpaper moves vertically on LG V40 with screen notch

### ISSUE THREAD

**Issue by EXOgreen** [8bitPit/Niagara-Issues#1092]
**Describe the bug**
When I turn on hide status bar in Niagara settings, my wallpaper slide down below my screen notch. When swiping to see the status bar, the wallpaper moves up to fill the status bar section. This may be a niche issue, lg software is usually a bit further from stock android, especially with Android 8 before notch support in Android 9. Let me know if I can provide any info to help, I'll keep status bar shown for the time being

**To Reproduce**
1. Turn on hide stus bar
2. Go to the home screen
3. Swipe down to show status bar
4. See black bar at top of screen

**Smartphone (please complete the following information):**
 - Device: LG V40 
 - Android version: 8.1.0 (screw you sprint, all other carriers AR Android 9)

**Screenshots**
![Screenshot_2019-12-15-09-56-53](https://user-images.githubusercontent.com/7752505/70865697-f1405e80-1f25-11ea-876d-e79fa0a6cdea.png)
![Screenshot_2019-12-15-09-57-03](https://user-images.githubusercontent.com/7752505/70865702-fb625d00-1f25-11ea-88ef-bbfc80b8378d.png)

**Comment by 8bitPit** [comment]
Hi @EXOgreen, that's really weird. The issue could be specific to LG-devices, you're the first one to report this. Can you please check if hiding the status bar works properly with other third party launchers (e.g. Lawnchair or Nova)?
Btw, great wallpaper!

**Comment by EXOgreen** [comment]
Thanks for the reply @8bitPit, it does look like the same thing happens in nova Launcher. When I swipe down from the top of the screen to open the notification tray the image jumps up to fill the black bar across the top that is basically hiding the status bar. Ah well, I will just never buy another lg device again. Not happy with their lack of updates for anything.

**Comment by 8bitPit** [comment]
Thanks for letting me know, that's a bummer. Also, thank you for sharing your wallpaper :D 
I'll close this issue then if you don't mind.
