### ISSUE TITLE
Status bar still noticeable after hiding it.

### ISSUE THREAD

**Issue by akastanis** [8bitPit/Niagara-Issues#1093]
It seems that the notification bar is still there, but the items in the bar have been removed.

**Describe the bug**
After the notification bar is disabled, scroll the items upward and you can still see the shadow and the space used by the navigation bar area.

**To Reproduce**
1. Disable the notification bar
2. Scroll the screen upwards so that the time is in the notifcation area.
3. Notice the time is covered up by an invisible notification bar, that becomes noticeable when scrolling upwards.

**Smartphone (please complete the following information):**
 - Device: OnePlus 3
 - Android version: Android 9

**Screenshots**
![image](https://user-images.githubusercontent.com/9420507/70871673-7a6f8980-1f56-11ea-81d1-4e9ff3a96e05.png)

**Comment by 8bitPit** [comment]
No wonder there's a bug, your clock shows 404 😉
Thanks for letting me know, I'll look into this.

**Comment by Montell2099** [comment]
> After the notification bar is disabled, scroll the items upward and you can still see the shadow and the space used by the navigation bar area.

@8bitPit Is this even possible to fully hide? I thought only the content of the status bar could be hidden, not its placeholder. Would be cool though.

**Comment by 8bitPit** [comment]
[It's possible](https://developer.android.com/training/system-ui/status). Currently I add extra padding to the ui, so it doesn't overlap with the status bar when it's visible.

**Comment by topsy-turvy99** [comment]
I no longer face this on the latest version, so most likely it's fixed somewhere along the line 😅?

**Comment by 8bitPit** [comment]
Oh yeah, we might have tweaked the effect, which looks better when the status bar is hidden. I'm closing this ticket then.
