### ISSUE TITLE
Launcher not showing Pro membership message

### ISSUE THREAD

**Issue by mgithuber** [8bitPit/Niagara-Issues#1094]
Bought pro version on 24th December 2019, Niagara launcher not showing pro membership message since version 0.10.0 pls see the below screenshot. This bug is still continuing in Niagara version 0.10.4.

Android Version: 5.0.2, ZenUI
Niagara version: 0.10.4

![Screenshot_2019-12-16-09-01-51](https://user-images.githubusercontent.com/50730036/70877799-06c88d80-1fe5-11ea-89c3-79d07778c663.jpg)

**Comment by 8bitPit** [comment]
Hey @mgithuber,

Since Niagara is still in beta, support for time travelling has not been implemented yet 😉

**Comment by 8bitPit** [comment]
No but seriously, thanks for letting me know, I think this bug only happens on Android 5, I'll take a look into it.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.

**Comment by mgithuber** [comment]
> Does the issue still happen on your device? If so, feel free to open the ticket again.

This issue still exists on my Android 6.01, ZenUI(Asus) And Niagara version.0.32.1. Pls see the screen shots

![Screenshot_20200904-091750](https://user-images.githubusercontent.com/50730036/92198612-7263cb00-ee92-11ea-810d-f1ee9d5b92d6.jpg)


![Screenshot_20200904-091822](https://user-images.githubusercontent.com/50730036/92198640-80b1e700-ee92-11ea-8460-ba6a8eb2969e.jpg)

**Comment by 8bitPit** [comment]
I just checked (v1.1.2), and the purchase text shows up fine on my Android 5 & 6 testing devices. If the issue is still persistent on your device, can you please send me your purchase's order number via mail (support@niagaralauncher.com) to check if your purchase is alright?

**Comment by mgithuber** [comment]
No problem  yesterday only i started using Android 10. Now no issues :))

![20210406_093650](https://user-images.githubusercontent.com/50730036/113657552-d023f400-96bb-11eb-918a-9ce6a0584410.jpg)
