### ISSUE TITLE
Battery percentage overlaid over clock

### ISSUE THREAD

**Issue by sbhattathiri** [8bitPit/Niagara-Issues#1097]
The battery percentage text is getting overlaid over the clock text

Version 10.0.4
1. Launcher Settings > Features > At a glance > Show Battery Percentage turned on
2. In home screen, observe that battery percentage is overlaid over the clock

 - Device: Xiaomi Redmi Note 5 Pro
 - Android version: Android 9 (Pie)

**Screenshots**

**Comment by Montell2099** [comment]
I believe this is a duplicate of #1081.

**Comment by sbhattathiri** [comment]
yes agree .

thanks,
