### ISSUE TITLE
Contextual music icons, getting displaced randomly

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1098]
The new contextual music icons are getting displaced quite randomly I've found out.

![Screenshot_20191217-093023](https://user-images.githubusercontent.com/43126233/70980432-9c325300-20b3-11ea-91e1-de784dfc08ae.png)

**To Reproduce**

1. Scroll around in app list, tap home button to get back
2. The SoundCloud name is now shortened to "*Soun...*". While Spotify's name remains intact, its contextual music icon is now very offset to the right (*right-swiping on either Spotify or SoundCloud almost consistently triggers this same bug as well*)
3. Pressing home button twice (opening & closing the "search apps" function) resets this behavior, displaying the contextual icons & SoundCloud's name properly once again. They're also getting reset & displayed correct if you long press **any** of your favourite apps

I'm on a Pixel 2 using the latest Android patch.

![Screenshot_20191217-094003](https://user-images.githubusercontent.com/43126233/70980468-ab190580-20b3-11ea-8052-368893021118.png)

Please let me know if I can provide any more valuable information to get this sorted out, @8bitPit.

**Comment by 8bitPit** [comment]
Thank you very much for your report. I've found the cause and will upload a patch soon.

**Comment by Montell2099** [comment]
> Thank you very much for your report. I've found the cause and will upload a patch soon.

Wonderful news, keep up the good work! Supporting you via Niagara Pro is worth every penny so far.

**Comment by 8bitPit** [comment]
Haha, thanks, should not appear anymore since v0.10.5 :D
