### ISSUE TITLE
Clock font color

### ISSUE THREAD

**Issue by skandy121** [8bitPit/Niagara-Issues#1099]
I have a feature request.
Is it possible to have a battery Bar, like and energy bar on top of the screen so it look more clean?
Just like a line which shortens and the battery percent comes down
Thank you

**Comment by Montell2099** [comment]
I think the current battery indicator is simplistic enough & in line with the overall design language of the launcher.

If you know your way around Photoshop you could do a mock-up and try to show more specific what it is you're suggesting.

**Comment by skandy121** [comment]
Something like this..... See the top part of the screen?

**Comment by Montell2099** [comment]
> Something like this..... See the top part of the screen?

You forgot to attach any image and quoted the email notification content instead, my friend.

**Comment by skandy121** [comment]
Fine now?

**Comment by Montell2099** [comment]
> Fine now?

No, same mistake again I'm afraid.

**Comment by skandy121** [comment]
![Screenshot_20191217-194832_Niagara Launcher](https://user-images.githubusercontent.com/58981004/71005207-3e305a80-2109-11ea-876d-eccc6737b75f.jpg)

**Comment by skandy121** [comment]
![Screenshot_20191217-201124_Niagara Launcher](https://user-images.githubusercontent.com/58981004/71005287-6e77f900-2109-11ea-8c61-9764dbab8c51.jpg)

The top part

**Comment by Montell2099** [comment]
> ![Screenshot_20191217-201124_Niagara Launcher](https://user-images.githubusercontent.com/58981004/71005287-6e77f900-2109-11ea-8c61-9764dbab8c51.jpg)
> 
> The top part

Aah, I see. But I don't think it's a very clean or good idea, it takes up a lot of space and could definitely cause visibility issues depending on the users wallpaper.

**Comment by skandy121** [comment]
Oh yea.... I didn't take that into account

**Comment by Montell2099** [comment]
If anything, I'd rather see an option to switch the "55%" text into a small circle as a battery indicator — like the one present in Cyanogenmod. Kind of like this but without text, very small, and only using white & grey:
![sWB1_qAe6i3m-aDAyxhJufJtWP3RavWsn_HYCtBM7SA](https://user-images.githubusercontent.com/43126233/71007433-4bd4e880-20e7-11ea-9b63-f0963841ec89.jpg)

**Comment by skandy121** [comment]
Yea.. possibly the ability to change then clock font colour too

**Comment by 8bitPit** [comment]
Hi guys. I think the circle and the bar booth look neat, but don't provide as much information. To keep Niagara Launcher simple & minimal, I'd say let's keep the battery percentage widget this way, without customization for now.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
