### ISSUE TITLE
Bug with Messaging.. doesn't open messages

### ISSUE THREAD

**Issue by 504Kingg** [8bitPit/Niagara-Issues#1101]
**Describe the bug**
Bug with Messaging.. doesn't open messages from front screen.. I open it the screen is blank in text messages..I have to close widget window and then go back in at messages after clearing cache..can you help..I have also subscribed to help with pro version.. Thanks 
![Screenshot_20191218-120647](https://user-images.githubusercontent.com/58827408/71111420-ff44e800-218e-11ea-945c-4b2f047573b7.jpg)
![Screenshot_20191218-120636](https://user-images.githubusercontent.com/58827408/71111421-ff44e800-218e-11ea-8f66-dbb18095b3c5.jpg)

**Comment by 8bitPit** [comment]
Thank you very much for your support :)
So, the screen is blank after tapping on the received message? What happens if you tap on the message that appears in Android's notification shade?

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
