### ISSUE TITLE
Dual widget support 

### ISSUE THREAD

**Issue by pradeep626** [8bitPit/Niagara-Issues#1102]
Having an option to have two user's widgets (other than default ones like weather) would help users customize the screen even more with kwgt widgets and stuff like that.

**Comment by 8bitPit** [comment]
Please submit this to: https://github.com/8bitPit/Niagara-Issues/issues/117

**Comment by 8bitPit** [comment]
I also submitted an idea there how multiple widgets could be integrated:
> [...] That’s why I’m planning to add the following integration:
You can place a single widget below the clock or replace it for showing weather and / or time, or an at a glance widget.
More widgets can be accessed by swiping right on an app.
Another idea would be that you can customize the google search button at the bottom right, so it can also launch a widget, e.g. your calendar.
