### ISSUE TITLE
Please let us set our default music app when we plug our headphones to show that app. I don't use goole play music as my default music app. I use amazon music. And I am unable to do that.

### ISSUE THREAD

**Issue by Aritra1996** [8bitPit/Niagara-Issues#1103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by Montell2099** [comment]
Could you describe more in-detail what you mean? No app gets opened automatically with the plug-and-play feature, it just gives you the ability to show your preferred music apps in your favorites list once you're connected via Bluetooth or 3,5 mm jack.

**Comment by Martin5001** [comment]
And you can add apps to this dynamic list in Edit mode (press long on empty space next to clock).

**Comment by Montell2099** [comment]
> (press long on empty space next to clock)

Long pressing also works on the clock, date & battery percentage FYI. But you're right, at the bottom of the list you can customize which music/audio/podcast apps shall appear when headphones/speakers are connected. 🙂

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case the replies of @Martin5001 & @Montell2099 didn't help.
