### ISSUE TITLE
"Wallpapers" menu option misleading

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1105]
Earlier the "Wallpapers" option, at the very end of the app list, lead the users to a Google Drive archive of a tiny selection of the developers blurred wallpapers.

Nowadays that option leads me to **_Settings_** -> **_Display_** -> **_Styles & wallpapers_**, looking like this:

![Screenshot_20191223-121104](https://user-images.githubusercontent.com/43126233/71355433-4bbd6880-257f-11ea-9c8c-aa273ec74d2a.png)

I'm on a Pixel 2 phone & from what I recall this styles editor is quite new, which might have something to do with this.

However I never really understood the purpose of the wallpapers app-list option anyway. There were only a few blurred wallpapers that never seemed to be updated either.

Personally I use Muzei to set wallpapers & find this option redundant. For people not using third-party wallpaper apps, is this "Wallpapers"-option the easiest solution for them to apply any wallpaper of their liking perhaps — or does it only lead to your ~10 blurred wallpapers as before?

**Comment by rd836** [comment]
I have some comments about this in #773 "tuck the Niagara Wallpapers into the Niagara Settings".

**Comment by 8bitPit** [comment]
Earlier the "Wallpapers" option, at the very end of the app list, lead the users to a Google Drive archive of a tiny selection of the developers blurred wallpapers.

> Did it really lead that way? Or did you go to Settings > Look > Wallpaper collection?

**Comment by Montell2099** [comment]
>Did it really lead that way? Or did you go to Settings > Look > Wallpaper collection?

Yes, it used to take me straight to that wallpaper collection. Isn't _Settings > Look > Wallpaper collection?_ a quite new addition amongst the settings? However, the "Wallpapers" option at the end of the app list only takes me to the "Styles & wallpapers" app by Google — is that the intended function?

**Comment by 8bitPit** [comment]
@Montell2099 that's very odd. Both the wallpaper and the wallpaper collection button haven't changed position and functionality for ~ a year. 

> However, the "Wallpapers" option at the end of the app list only takes me to the "Styles & wallpapers" app by Google — is that the intended function?

Yes, that's intended. Google flagged this app as a wallpaper app.

**Comment by Montell2099** [comment]
> Yes, that's intended. Google flagged this app as a wallpaper app.

Alright, thanks for the clarification!
