### ISSUE TITLE
/Weather/ Current location does not work

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1107]
When I choose my location for weather to "Current location" it does nothing and shows as "None selected". Manually set location works fine. (My location was Sušice, Czech Republic.) (Location permission granted.)

 - Device: Nokia 5
 - Android version: Android 9 (Pie)

**Comment by Montell2099** [comment]
On my Pixel 2 with Android 10 it works fine. I choose "current location" and can briefly see the GPS icon in the status bar scanning my location. Just my two cents. Merry Christmas by the way!

**Comment by Martin5001** [comment]
> Merry Christmas by the way!

Thanks, you too.

**Comment by 8bitPit** [comment]
Thank you for the report Martin, I'll investigate it.

**Comment by IdmFoundInHim** [comment]
Is the Current Location option supposed to act the same as the first option? I would expect it to change every so often as I move around, but instead it is just storing my location from the time I select it. 

![Screenshot_20191229-190123](https://user-images.githubusercontent.com/30935172/71564418-f5b05f80-2a6d-11ea-8695-764bd797d51a.jpg)

OnePlus 7 Pro, OxygenOS 10.3.0/Android 10

**Comment by Montell2099** [comment]
> Is the Current Location option supposed to act the same as the first option? I would expect it to change every so often as I move around, but instead it is just storing my location from the time I select it.
> 
> ![Screenshot_20191229-190123](https://user-images.githubusercontent.com/30935172/71564418-f5b05f80-2a6d-11ea-8695-764bd797d51a.jpg)
> 
> OnePlus 7 Pro, OxygenOS 10.3.0/Android 10

I've had the same experience, the location doesn't seem to change when choosing "_Current location_" — but stays at the location that were when that option was chosen.

**Comment by 8bitPit** [comment]
"Dynamic location" has not been implemented yet, sorry: #1083

**Comment by 8bitPit** [comment]
... but now it has :)

**Comment by 8bitPit** [comment]
Implemented in v0.19
