### ISSUE TITLE
Work profile apps : show only when work profile active

### ISSUE THREAD

**Issue by silvester-pari** [8bitPit/Niagara-Issues#1109]
**Is your feature request related to a problem? Please describe.**
It's great that Niagara Launcher shows the user's work profile apps alongside "normal" apps. But when the work profile is turned off, the user might not want to see them. 

**Describe the solution you'd like**
It would be awesome if work profile apps would be shown/hidden depending on the current status of work place - i. e. if it is currently active or not. This way, when the user wants no distraction during the weekend or holidays, the work profile apps don't take away space in the favorites and in the app list. This could either be a default behavior or an advanced setting. 

I'm not even sure if it is possible for an app to check the current work profile status; it depends on this if the implementation is realistic or not.

Thanks for your great work so far, really enjoying this launcher!

**Comment by 8bitPit** [comment]
Thanks for your request @silvester-pari. Yeah, this would be possible. I'm planning to group work apps in a separate category. There, I'll add a switch to enable/disable them: #537
Once disabled, work apps will gray out and incoming notifications wouldn't show up anymore.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
