### ISSUE TITLE
Music player toggle / hide media player

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#111]
Option to hide the media player.

**Comment by rastamanjohn** [comment]
Yes please! And it would be nice to have the album art be in a round frame, at least if round icons is toggled on. Keep up the great work!

**Comment by 8bitPit** [comment]
@rastamanjohn See #18 for that.

**Comment by colin-walker** [comment]
Now that widget support is in alpha I'd say it would be an ideal time to implement this allowing for users to have their own widget but keep home screen notifications.

**Comment by 8bitPit** [comment]
On top of that, it would be nice if the media player is automatically hidden when another widget from the same app has already been added.

**Comment by eugen-petersen** [comment]
Yes please. Registered just to ask for the "hide music player" feature :)

**Comment by ClaudiaAtGitHub** [comment]
Just got your email -- yay, I'm so happy to hear you're (eventually, time-allowing) planning to give us the option of disabling/hiding the media player widget!  

Good things are worth waiting for :-)

**Comment by shmykelsa** [comment]
Oh yes I would really like this feature to be implemented!

**Comment by timm0e** [comment]
Maybe a blacklist for some apps would be nice. 

KDE Connect for example spawns a persistent media notification that bloats the home screen, even though the media is played back on another device

**Comment by 8bitPit** [comment]
Implemented in v0.31
