### ISSUE TITLE
Ability to use multiple wallpapers as slideshow.

### ISSUE THREAD

**Issue by ogunsoladebayo** [8bitPit/Niagara-Issues#1110]
I've fallen In love with this app on first glance but I just need one more feature to give 6/5 stars (yeah... 6, You've got my 5 already).
I hope you can allow multiple wallpapers to be selected by the user that will keep changing at specific intervals and/or at a button click on the home screen.
Thanks in advance.

**Comment by 8bitPit** [comment]
Thank you very much 😊 Have you tried out [Muzei](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=de)? This app lets you create your own slideshow. Moreover if you double tap above the clock, the wallpaper will change. Hope this helps.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
