### ISSUE TITLE
Random music widget

### ISSUE THREAD

**Issue by PaulBags** [8bitPit/Niagara-Issues#1111]
**Describe the bug**
Unwanted music widget

**To Reproduce**
1. Start playing something in MX Player
2. Suddenly there's a new widget on the home screen pushing favourites down

**Smartphone (please complete the following information):**
 - Device: Samsung A5 2017
 - Android version: 8 something

**Comment by Montell2099** [comment]
Could you provide a screenshot of the unwanted widget that appears on your home screen?

**Comment by PaulBags** [comment]
![Screenshot_20191228-070702_Niagara Launcher](https://user-images.githubusercontent.com/19583196/71527545-cbad4f00-2940-11ea-8def-e2654bee0329.jpg)

**Comment by Montell2099** [comment]
Seems like the default widget can't fetch info from MX Player, because it always appears when you start playing music/podcasts/etc.

**Comment by ccocallas** [comment]
After a very recent update from Verizon, I had this happen with Google's Play Music. Whenever I would turn on my Bluetooth speaker, the Play Music app would suddenly appear. I was able to Hide the Google Play Music app (since I use Rocket Player), and I haven't had it reappear since!

**Comment by 8bitPit** [comment]
Thanks for letting us know. Did the Google Play Music media player appear at the same time in Android's notification shade?

**Comment by PaulBags** [comment]
No, but MX Players does.

**Comment by 8bitPit** [comment]
Hm, pretty odd. Thanks for reporting.

**Comment by PaulBags** [comment]
I think it's connected to the "Homescreen notifications" setting, but mx player isn't in my niagara favourites, and no other apps show up there that aren't favourites.

**Comment by ccocallas** [comment]
I'm sorry to say I didn't notice the answer to your question, 8bitPit; I was in a hurry and just hid the app.

**Comment by 8bitPit** [comment]
@ccocallas no problem :)

**Comment by 8bitPit** [comment]
By the way, the media widget can now be disabled completely, see #111

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)

**Comment by ccocallas** [comment]
Since I commented on this post, I have since traded in my Samsung Galaxy S8+ for a Google Pixel 4A 5G, and then I traded that for a Samsung Galaxy Z Fold3 5G. I have not experienced the problem on either the Pixel or the Fold!
