### ISSUE TITLE
"Screen Lock" shortcut Error

### ISSUE THREAD

**Issue by Kristianruiz24k** [8bitPit/Niagara-Issues#1112]
When I try to add the Screen lock shortcut on my Huawei device the launcher brings an "Error" message and I cannot add the shortcut.

1. Go to 'Launcher Settings'
2. Click on 'Features'
3. Click on 'Add shortcut'
4. Scroll down to 'System UI'
5. Click on 'Screen Lock'
6. "Error" message pop up

 - Device: Huawei ATU-L22
 - Android version: 8

**Comment by 8bitPit** [comment]
Sorry about that. Can the shortcut be added on other third-party launchers like Nova Launcher or Lawnchair Launcher?

**Comment by Kristianruiz24k** [comment]
Sadly i didn't like other third party launchers but i tried to install Nova just to test the problem and Nova launcher says "app not installed" when i tried to add that shourtcut. But on  my default one (Huawei home) it works well. i think i just wait for naigara launcher to have that Lockscreen feature instead. thank you for your response sir. God bless

**Comment by 8bitPit** [comment]
Thank you for trying it out. Unfortunately this doesn't seem fixable. However, there are apps on Google Play that do the same. e.g.: play.google.com/store/apps/details?id=com.katecca.screenofflock

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
