### ISSUE TITLE
Selective app name availability

### ISSUE THREAD

**Issue by pradeep626** [8bitPit/Niagara-Issues#1113]
Would be cool if we can still have app names for one or two apps/shortcuts even with the app names setting , set to disabled. 

Let me explain what I mean by that. For example, while my earphones are plugged in, two of my Spotify playlists pop up along with the Spotify app. If both of them playlists have their names , it would be easy for me to identify them. It maybe be easy now but if I add more playlists there, it would be an effort to remember the order.

**Comment by 8bitPit** [comment]
Hi @pradeep626, thanks for your request. I published [an article](https://medium.com/niagara-launcher/niagara-launcher-in-2020-df3f6aa2d184) today, that explains which features should be added to Niagara Launcher. They should match four criteria:

An addition to Niagara Launcher should be…
Simple · Easy to configure and easy to use. As few settings & toggles as possible.
Impactful · Either appealing for many or necessary for some.
Universal · Has to work everywhere: in every country, on all phones.
Independent · Doesn’t add complexity if it’s not being used.

I fear that this feature wouldn't be impactful, very few people would take use of it. Instead, I recommend to change the icon of one of your playlist in Niagara Launcher. Hope this helps.
>

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
