### ISSUE TITLE
Homescreen notifications broken for messenger

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1114]
When I receive a message through Facebook Messenger it never appears as a homescreen notification. It works for every other app I'm using though.

When right-swiping on messenger I can see the messages though, but still no notification on the homescreen for this particular app.

**Screenshot examples:**

![Screenshot_20191227-142413~2](https://user-images.githubusercontent.com/43126233/71520035-77f82280-28ba-11ea-8997-30f919d97a39.png)

![Screenshot_20191227-142424~2](https://user-images.githubusercontent.com/43126233/71520040-821a2100-28ba-11ea-8c53-433eca2f2012.png)

**Comment by 8bitPit** [comment]
I'm not sure, but this could be the same problem that annie-may experienced: https://github.com/8bitPit/Niagara-Issues/issues/920

**Comment by Montell2099** [comment]
> I'm not sure, but this could be the same problem that annie-may experienced: #920

Thanks, I'll try some of the things mentioned there & see if it'll make a difference.

**Comment by 8bitPit** [comment]
Great to hear :)
