### ISSUE TITLE
Dark Sky Weather Pop Up.

### ISSUE THREAD

**Issue by shakiehyenaboy** [8bitPit/Niagara-Issues#1116]
Hi Niagara,

The pop up for Dark Sky weather has a number that is cut off after the temperature. It appears to be precipitation percentage. Please fix!

Thanks, Bill

![Screenshot_20191229-145904](https://user-images.githubusercontent.com/59343603/71562002-110a7300-2a4c-11ea-9eb0-f53d136b041a.png)

**Comment by 8bitPit** [comment]
Thank you for reporting, I'll fix that.

**Comment by shakiehyenaboy** [comment]
Thanks for fixing that so fast! Only bug left in weather I find is that it won't follow your current location. You have to go into settings and update it manually. Love your app!

**Comment by 8bitPit** [comment]
You're welcome, thanks for your kind words :)
Dynamic location will also be supported at some point, it's tracked here:https://github.com/8bitPit/Niagara-Issues/issues/1083

**Comment by 8bitPit** [comment]
Fixed in v.0.11.13
