### ISSUE TITLE
Cache Cleaner

### ISSUE THREAD

**Issue by Muhammadhfayaz** [8bitPit/Niagara-Issues#1117]
Request for new feature - I would be great if you can add Cache Cleaner for Pro User.

**Comment by Montell2099** [comment]
Is there any specific reason you would like to clear the cache of Niagara if I may ask?

**Comment by 8bitPit** [comment]
@Montell2099 I believe he means a tool to clean the cache of every app.

**Comment by 8bitPit** [comment]
@Muhammadhfayaz There are already tons of cache cleaners out there, in my opinion Niagara Launcher doesn't need it integrated. Moreover, clearing the cache of apps often makes them slower.
