### ISSUE TITLE
Change widget location

### ISSUE THREAD

**Issue by MarcAlx** [8bitPit/Niagara-Issues#1118]
**Problem**
Not all widget are dedicated to display information, some are more actions/shortcuts. Like "add new entry in a todo list app" or "open X app ready to type (keyboard open)"

As screens are getting bigger, shortcuts/widgets placed on top of the screen are no more one-hand accessible.

**Describe the solution you'd like**
My solution is to allow users to change widget location.
In order to keep it simple you could have only two locations available : 

- Top of favorites (actual one)
- Bottom of favorites (new one, ideal for shortcuts).

**Usage**
For exemple the wikipedia (official) widget that open the app to perform a search (keyboard open ready to type in search bar) is the kind of widget I want on my screen but not on top of it, I prefer it on the bottom easily accessible one hand.

**Comment by Martin5001** [comment]
Nice idea.

**Comment by 8bitPit** [comment]
Hi Marc, for reasons of simplicity we decided against adding the option to move widgets to the bottom of the list. Moreover, the primary purpose of widgets is to show data, in my opinion. If an app wants to give users access to a specific feature quickly, it should offer a shortcut for that.
