### ISSUE TITLE
Custom top Padding

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#112]
That's the space between the top of your phone and the first app in your list. It's for using your phone with one hand.

**Comment by MydVDZ** [comment]
I think there should be an option in the settings to move the whole layout higher, that will satisfy all users and make the users have taller screens to fit more favourite apps in the favourite apps screen.

**Comment by squad99** [comment]
I would like and adjustment setting in the option :)

**Comment by vishnujayapal** [comment]
This is an awesome launcher. So far this has been the greatest concern for me. It looks awkward on my 19:9 screen. Please add an option to adjust the top padding or atleast change the top padding calculation to include screen ratio as a factor.

**Comment by GPAgethub** [comment]
https://github.com/8bitPit/Niagara-Issues/projects/1#card-14058858

**Comment by pimboli** [comment]
+1

**Comment by danielquasar** [comment]
I agree that there should be an option for adjusting the vertical layout of the apps and the letters, and even the option of aligning them separately. I know you want to keep everything low to continue the "use of one hand" with your launcher but I personally to care about single hand phone use. My screen is tall and I just can't use one hand, and I'm okay with that. Having the option as an 'opt-in' for those of us who would use it would be great!

**Comment by 8bitPit** [comment]
Implemented in v.0.7.6

**Comment by weendigo** [comment]
I'm using 0.32.4 and I can't this in the settings, is the option still there?

**Comment by 8bitPit** [comment]
Yes: Niagara settings > Features > Niagara widget > Move widget
