### ISSUE TITLE
Better handling for icons that don't have shortcut or notification features

### ISSUE THREAD

**Issue by kr428** [8bitPit/Niagara-Issues#1120]
Right now, I have a bunch of favorites on my start page to quickly reach them, which however makes my start page clutter up pretty quickly. Unfortunately, some of these favorites (camera, image gallery, ...) don't really fit into the Niagara navigation concept at all, as they neither ever receive any notifications nor provide meaningful shortcuts. For those favorites, the current navigation mode (both in the favorites and in the alphabet drawer) feels like a waste of screen space that makes navigation slower than it needs to be without adding any benefit.

Could handling of such apps / favorites in some way be improved? I'm not sure how this could look like without breaking the launcher core design altogether. However, after using it (even in Pro) for a couple of weeks and enjoying it in most of my use cases, this is the one issue that continuously gets into my way. :(

**Comment by 8bitPit** [comment]
Maybe folders would help: #13

**Comment by 8bitPit** [comment]
Moreover, a "Niagara button" will replace the Google button on the bottom right. It might be customizable, so you could also bind some apps to them. (more info at the end of: #776)

**Comment by 8bitPit** [comment]
I hope my replies helped. Feel free to open the issue in case it didn't.

**Comment by kr428** [comment]
Thanks. Both seem viable approaches; folders seeming a bit closer to what I am looking for than the button. Another option I see would be: In the app search window, keep a list of previously looked-up / launched applications or actions just below the search field as long as nothing has been entered. Not sure this is possible / makes sense from another point of view, though.

**Comment by 8bitPit** [comment]
I believe this would be possible once Sesame has been integrated: #88
