### ISSUE TITLE
Media controls never launch

### ISSUE THREAD

**Issue by JP-Doyon** [8bitPit/Niagara-Issues#1121]
**Describe the bug**
Media player 'widget' appears correctly with SoundCloud but never appears with Spotify

**To Reproduce**
Play Spotify music...

**Smartphone (please complete the following information):**
 - Device: Galaxy s10e
 - Android version: Android 10

**Comment by disacrol** [comment]
Exactly which Niagara version?

**Comment by 8bitPit** [comment]
Hi @JP-Doyon, please provide further information here: https://github.com/8bitPit/Niagara-Issues/issues/485

**Comment by 8bitPit** [comment]
Duplicate of #485
