### ISSUE TITLE
Music app no longer an option to launch when earphones are connected

### ISSUE THREAD

**Issue by JP-Doyon** [8bitPit/Niagara-Issues#1122]
**Describe the bug**
Spotify used to jump to the top of the favorites when earphones were plugged in. This no longer seems to be an option?

**To Reproduce**
Connect earphones

**Smartphone (please complete the following information):**
 - Device: Galaxy s10e
 - Android version: Android 10

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by disacrol** [comment]
Is this a persistent bug? Have you tried to restart the launcher, or even the device?

**Comment by folkg** [comment]
This happens to me as well. When the feature first launched Spotify gave me the option to jump into my favourites when headphones or bluetooth were activated. I don't know exactly when it stopped, but in 0.11.8 that feature is no longer available to Spotify or any of my music apps (soundcloud, pocketcasts).

**Comment by disacrol** [comment]
@folkg I believe you need to enter edit mode and scroll the way down select your music apps. When you first install Niagara you're asked to select your music apps, but that's an onboarding feature IIRC.

@JP-Doyon could you confirm this is also solves your problem?

**Comment by folkg** [comment]
You are correct, that was my issue. I have it back. Thanks!

Perhaps it could be added to the general settings where it might be easier found. To me at least, that would be more intuitive. Just a suggestion though.

**Comment by disacrol** [comment]
It's a valid suggestion, but I suspect the main idea here is to unclutter settings as much as possible, so you choose music apps as you choose your favorites: on edit mode.

**Comment by 8bitPit** [comment]
Niagara's settings are one of the things I want to improve in 2020, they are all over the place to be honest.

**Comment by 8bitPit** [comment]
Merged with #1128
