### ISSUE TITLE
Weather popup opening slowly and not smoothly 

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1124]
**Describe the bug**
When I click on the weather icon, the popup opens slower then other swipe animation elements and it is not really smooth. 

**Smartphone:**
 - Device: Samsung Galaxy J7
 - Android version: Android 9 (Pie), OneUI 1.1

**Comment by disacrol** [comment]
Yes, at least first time you tap it is not as smooth as expected. But I'd say this is a matter of performance, and not necessarily a bug.

**Comment by Martin5001** [comment]
I don't think that's the case. This phone has more than enough power I think. I didn't even have any other apps running at that time.

**Comment by 8bitPit** [comment]
I'll try to optimize it.

**Comment by 8bitPit** [comment]
@Martin5001 please download v0.11.13 and check if the dialog opens without stutter.

**Comment by Martin5001** [comment]
No it's still the same, unfortunately.

**Comment by 8bitPit** [comment]
Thanks for the feedback, I'll look further into this ^^

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
