### ISSUE TITLE
"Weather not free anymore" notification bug

### ISSUE THREAD

**Issue by TFackler** [8bitPit/Niagara-Issues#1125]
When going to the home screen, there is a dialog / alert for a split second. This tells the user that weather can't be used for free anymore altough the user has already purchased Niagara Pro.

The alert:
![image](https://user-images.githubusercontent.com/38538728/71757840-53dba900-2e99-11ea-822a-ed821fdaf025.png)

The problem:
![weather not free warning bug](https://user-images.githubusercontent.com/38538728/71757852-681fa600-2e99-11ea-864f-c47910f0da4a.gif)

**Comment by disacrol** [comment]
What is the problem exactly? That notification it's supposed to be there. To get weather from Niagara, you'll need to upgrade to pro, due to Google's weather API not being free anymore.

**Comment by TFackler** [comment]
The problem is that this dialog is only shown for a split second and it should not be shown, since Niagara Pro was purchased on the device.

**Comment by disacrol** [comment]
Oh I see. That's probably a glitch that should be fixed.

**Comment by 8bitPit** [comment]
Fixed in v.0.11.8
