### ISSUE TITLE
Cannot create any direct dial shortcut on Samsung One UI 2

### ISSUE THREAD

**Issue by craPkit** [8bitPit/Niagara-Issues#1127]
**Description**
I cannot create direct call shortcuts on Samsung One UI 2.0. Creation seems to fail silently. 
The same activity can be added to the home screen on e.g. Lawnchair. 

**To Reproduce**
1. Go to _Launcher Settings > Features_
2. Tap _Add Shortcut_
3. Select the _Contact_s' _Direct Dial_ activity 
4. Select any contact's phone number 

I'd expect to find the shortcut in either the letter group for the contact's name or under letter _D_ for direct dial. I cannot find it anywhere. 
There is no error message anywhere. 

**Smartphone**
Galaxy Note 10+
Android 10 
Samsung One UI 2.0
Niagara Version 0.11.7

**Comment by 8bitPit** [comment]
Thanks for letting me know, I'll look into it.

**Comment by craPkit** [comment]
Works with v0.11.12. 
Thank you!

**Comment by 8bitPit** [comment]
Awesome :)
Btw, I recommend to upgrade to 0.11.13, just fixed two more bugs :)
