### ISSUE TITLE
Media app not displayed in favorite media apps when Bluetooth device is connected after some time

### ISSUE THREAD

**Issue by eche779** [8bitPit/Niagara-Issues#1128]
Recent media app suggestions feature seems to be stopping after a while connected to the same device. 

**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by disacrol** [comment]
@eche779 could you share some details on your device? Device model, Android version?

**Comment by eche779** [comment]
Asus Zenfone 6 android 10

Le 6 janv. 2020 à 00:19, à 00:19, disacrol <notifications@github.com> a écrit:

**Comment by eche779** [comment]
Asus Zenfone 6 (2019) Android 10

**Comment by timm0e** [comment]
Please fill out the issue template completely, without these informations it will be very hard for us to reproduce the error and/or to understand it

**Comment by eche779** [comment]
I don't know exactly when it happens, it just happens "after a while".

**Comment by disacrol** [comment]
Yeah, issues like this are difficult to reproduce in a deterministic way.

@8bitPit any ideas?

**Comment by 8bitPit** [comment]
Hard to say. @eche779 Does restarting Niagara help (Launcher settings > Advanced > Restart)?

**Comment by 8bitPit** [comment]
Fixed in v.0.24
