### ISSUE TITLE
Hide current 'music app' while playing from that particular app

### ISSUE THREAD

**Issue by JuuIM** [8bitPit/Niagara-Issues#1129]
problem*
The music app list is great. But when you're playing a song from for example, spotify. You can open that app by hitting the build in music player. So seeing that app icon isn't necessary (you basically have two shortcuts for your media app)

Solution*
Hide the app that is currently in use for playing media, only show the other apps from the 'music list'

**Comment by disacrol** [comment]
Kind of like the idea, as long as it is restricted to the media apps on the homescreen, but no change in the app list.

**Comment by Martin5001** [comment]
Agree

**Comment by shmykelsa** [comment]
This could be an extension of #111

**Comment by 8bitPit** [comment]
Not everyone knows that you can tap on the player, though. 
Moreover, tapping on the media player doesn't do the exact same as tapping on the app, though. The former leads you directly to the song that is being played, the latter just opens the app.

**Comment by 8bitPit** [comment]
All in all I believe this wouldn't be ideal for everyone, a toggle would be needed. However, I'm against adding a toggle just for that.
