### ISSUE TITLE
App unresponsive in Realme X2

### ISSUE THREAD

**Issue by Muhammadhfayaz** [8bitPit/Niagara-Issues#1130]
Apps unresponsive in Realme X2

Issues.

1. At few times favorite list App doesn't open even after multiple taps.
2. Unable to remove app from favorite list.
3. Able to scroll down Alphabetical order but unable to open selected app.

**Smartphone**
 - Device: Realme X2 Phone
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
I'm sorry. However, I believe that this is not caused by Niagara.

**Comment by 8bitPit** [comment]
Have you tried out other third-party launchers like Nova Launcher or Lawnchair Launcher?

**Comment by Muhammadhfayaz** [comment]
No, I haven't tried any of the above.

**Comment by disacrol** [comment]
Please try with a different launcher next time apps become irresponsive, it is the best and fastest way to figure out if this is a bug in Niagara or not.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case @disacrol's reply didn't help.
