### ISSUE TITLE
Space between clock and date increase

### ISSUE THREAD

**Issue by Amit2685** [8bitPit/Niagara-Issues#1131]
If i change the font it increase space between clock & date, please find above the screenshot
![857419232_157848](https://user-images.githubusercontent.com/57060727/71801320-a1fed100-3080-11ea-92cb-75d5b0952691.jpg)

**Comment by disacrol** [comment]
It seems to me the layout area for the "at a glance" widgets is not adjusted to match the selected font. 

In some cases, the clock doesn't even completely fit.

From Telegram user Philipp Paul Köhler:
"Looks like the font is being cut off at the top: https://github.com/theleagueof/junction"

**Comment by 8bitPit** [comment]
These issues might be caused by the custom font itself, I'm not sure if I can fix it.

**Comment by 8bitPit** [comment]
I think I figured out the cause, this should be fixed in v0.32. @Amit2685
