### ISSUE TITLE
Regain the Clock / Date space

### ISSUE THREAD

**Issue by ishmadrad** [8bitPit/Niagara-Issues#1132]
Hallo everybody. I'm not sure if this is a bug just for me, or it's a standard thing, so I write it here. Samsung A70. When I go into the Niagara Settings, and I turn off Clock and Date switches, I end with a lot of "wasted black space" where hour and date was showed before in the "main screen". I think that the blank space could be really better used for extra suggestion apps, or a better presentation of Widget + Music bar + Starred apps.
Am I the only one with this issue? 
Side note: I think hour and date are pretty useless on the main screen, 'cause we already have them in the notification bar (hour) or in the lock screen, and/or in a Agenda widget (indispensable, imho).
Thanks in advance for the attention, and keep the wonderful job in this minimal, jet fast as hell to select from hundreds of App, launcher.
Andrea

**Comment by disacrol** [comment]
You can move thingd up and down in edit modo, to make up for that empty space. Long press an empty area of the homescreen to enter edit mode and select "move whole list".

**Comment by disacrol** [comment]
You can move thingd up and down in edit modo, to make up for that empty space. Long press an empty area of the homescreen to enter edit mode and select "move whole list".

**Comment by ishmadrad** [comment]
Uh, fantastic, thanks for the insight. I totally missed it.
I think we can close this one... :D
