### ISSUE TITLE
Toggle opening of edit menu on homescreen long press.

### ISSUE THREAD

**Issue by ziZyphus** [8bitPit/Niagara-Issues#1133]
An option (toggle) to disable opening edit menu whenever long pressing an icon on homescreen? Like a lock homescreen toggle in Niagara settings. I have accidentally pressed and dislocated items in my pocket lot of times. At least as a pro feature.!![](null)

**Comment by 8bitPit** [comment]
Niagara is already designed in such a way that it's hard to change your favorites accidentally. I fear that this addition wouldn't be used by many, so it wouldn't have much impact, sorry.

A feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
We discussed this internally and found out this feature could be necessary for some and therefore be impactful. However, I’m still against a toggle to keep Niagara Launcher simple.
Instead, what about improving Niagara’s user flows so it’s getting even harder to change something accidentally? For example, adding a confirmation dialog that pops up when removing favorites or hiding apps.

**Comment by topsy-turvy99** [comment]
still as a security standpoint i would still love to have this feature, a simple niagara secret command might help: /disable long press

**Comment by topsy-turvy99** [comment]
> Niagara is already designed in such a way that it's hard to change your favorites accidentally. I fear that this addition wouldn't be used by many, so it wouldn't have much impact, sorry.
> 
> A feature should be... _Simple_ · Easy to configure and easy to use. As few settings & toggles as possible. _Impactful_ · Either appealing for many or necessary for some. _Universal_ · Has to work everywhere: in every country, on all phones. _Independent_ · Doesn’t add complexity if it’s not being used.

still as a security standpoint i would still love to have this feature, a simple niagara secret command might help: /disable long press

**Comment by 8bitPit** [comment]
@topsy-turvy99 we try to reserve secret commands for debugging stuff. We made sure that changing any favorized item always requires several taps. And even in the low chance you accidentally trigger a change, you can easily revert it.

**Comment by topsy-turvy99** [comment]
![Screenshot_2022-07-17-21-36-39-91_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/96917972/179410720-30893ca0-4a83-4e7b-826f-1e1821ad3d7b.jpg)

Just Incase If you have a second thought about implementing it, niagara button menu will be the best place for enabling/disabling it 😊
