### ISSUE TITLE
Nothing happens on Media player tap

### ISSUE THREAD

**Issue by ilxa186** [8bitPit/Niagara-Issues#1134]
Some music apps, after opening, then leaving, then stoping the music, stop you from using the notification given on Niagara's homescreen to open the music app.

**Comment by 8bitPit** [comment]
Thank you for reporting.

**Comment by disacrol** [comment]
@ilxa186 did you manage to reproduce it with a specific app?

**Comment by ilxa186** [comment]
I've just opened the issue for someone else, but it seems to happen with youtube music, unless there's a way to send a video, I don't think you could understand, unfortunately.

**Comment by Montell2099** [comment]
I have experienced the same thing a handful of times, from what I recall it was mostly when playing from SoundCloud that the media player didn't open the app when pressed upon. It may have happened once or twice with Spotify as well, but I'm not entirely sure.

**Comment by 8bitPit** [comment]
Please refer to: https://niagaralauncher.helpscoutdocs.com/article/11-media-player-widget-issues
