### ISSUE TITLE
Can't apply fonts in 0.11.9

### ISSUE THREAD

**Issue by mgithuber** [8bitPit/Niagara-Issues#1135]
Not able to apply fonts in Niagara version 0.11.9. in earlier version I had no problem I used Google sans regular font(.ttf) but now I can't apply same font in Niagara 0.11.9.  pls see the screenshot

![Screenshot_2020-01-12-21-02-19](https://user-images.githubusercontent.com/50730036/72221365-05f13000-3580-11ea-82c9-b4c1894f8d2f.jpg)

Pls fix this bug I have Niagara pro version

My Android version 5.0.2, ZenUI
Niagara version 0.11.9

**Comment by 8bitPit** [comment]
Thanks for reporting, v0.11.10 should resolve it.

**Comment by 8bitPit** [comment]
Fixed in v.0.11.10
