### ISSUE TITLE
Unable to install update with APK

### ISSUE THREAD

**Issue by Orbeatle** [8bitPit/Niagara-Issues#1140]
I get an error message that the app cannot be installed via the downloaded apk from GitHub. This used to work in the past.

I'm now running version 0.11.11.1 installed via Google Play on my Huawei P20 Lite and trying to install the latest version but it keeps giving an error message.

**Comment by 8bitPit** [comment]
I'm sorry, this was my mistake: 

> Sorry for the confusion guys. Let me explain: first of all, the changelog on Google Play is wrong, it's version 0.11.11.1,  I'll fix the description asap. Yesterday night I found out that a critical bug (that could cause Niagara launcher to crash) was introduced in v0.11.11. I already fixed the bug, but I made the mistake to only fix it in 0.11.12+. This version is not publicly tested though, I can't release it on Google Play. That's why I decided to push another hotfix (0.11.11.1) on Google Play. I'll also release 0.11.14 in ~16 hours that has is more stable than 0.11.13. Of course this update will also include the changes from 0.11.12+. You don't miss a feature though if you got a downgrade to 0.11.11.1. Again, I'm sorry for the inconveniences. [Source: Niagara Launcher Discussion Group on Telegram]

**Comment by 8bitPit** [comment]
Fixed in v.0.11.14: https://github.com/8bitPit/Niagara-Issues/releases
