### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by HourGlassDk** [8bitPit/Niagara-Issues#1141]
Rounded corners for the media players widget, around the picture

**Comment by Rod911** [comment]
https://github.com/8bitPit/Niagara-Issues/issues/18#issuecomment-426212018

> I changed my mind about rounded corners for artworks, I believe it’s wouldn’t look good for every artwork. I looked at covers from my music library and noticed they are often designed specially to fit in a square, e.g. some of them have a border, which wouldn’t look with a “cropped” image.
> Spotify also recommends not to change the artwork’s shape:
> ![image](https://user-images.githubusercontent.com/9284845/46341135-bb240100-c637-11e8-9756-485a193da415.png)
