### ISSUE TITLE
Exclude Favourite Apps from Application List

### ISSUE THREAD

**Issue by stanleehub** [8bitPit/Niagara-Issues#1143]
Let me first say this a great launcher and has been my daily driver ever since I downloaded it. 

Feature request:
Excluding favourited apps from the general application list.

Implementation: enabled by default and/or provide toggle to activate in settings.

Rationale:
This will decrease the application number in the general list which makes it much easier to find apps that aren't favourited.

Also when apps are unfavoirted then they should re appear in the application list.

Unlike hiding apps which hides them from both the favorited and general application list.

I think this feature would add greatly to the minimalistic approach.

**Comment by 8bitPit** [comment]
Hi, you can already do this manually by hiding an app and pinning it to your favorites from the hidden apps screen. Admittedly, this is not intuitive, I'll make this option more obvious (e.g. instead of "hide app" the option could be called "hide from app list").

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
