### ISSUE TITLE
Notifications not Showing

### ISSUE THREAD

**Issue by phibr0** [8bitPit/Niagara-Issues#1144]
On my new phone running Android 10 MIUI no notifications are showing in the launcher. I think it's a problem with MIUI since it was working on my old phone.

1. Turn on Homescreen Notifications
2. Get Error Message 
3. Steps in the Error Message aren't helping.

 - Device: Xiaomi Mi 9T Pro
 - Android version: Android 10/Q MIUI 11

![Screenshot_2020-01-19-00-01-43-215_bitpit launcher](https://user-images.githubusercontent.com/59741989/72671733-e742db80-3a4e-11ea-80d3-1924570f5742.jpg)
![Screenshot_2020-01-19-00-01-36-317_bitpit launcher](https://user-images.githubusercontent.com/59741989/72671734-e742db80-3a4e-11ea-9b4c-03babb1b6456.jpg)

**Comment by phibr0** [comment]
Fixed the Issue.
It's a problem with MIUI.

**Comment by 8bitPit** [comment]
Thanks for letting me know. Can you tell me how you fixed it?

**Comment by phibr0** [comment]
I disabled MIUI Optimizations in the Developer Settings.
It sometimes causes issues through shitty RAM Managemt and so on.

**Comment by phibr0** [comment]
It just fixed it for a while the error is back and won't be fixed by enabling those Optimizations and disabling them again.
But I don't know if it's your Launcher or just Xiaomis bad OS..
Guess I have to use an Custom Rom

**Comment by 8bitPit** [comment]
Unfortunately this happens on many Xiaomi devices, more info here: https://github.com/8bitPit/Niagara-Issues/issues/588

**Comment by Martin5001** [comment]
@8bitPit You probably know about this but in case you don´t: Could it help to prompt the user to disable battery optimization for Niagara? Some apps (eg. Microsoft Authenticator) do that. AFAIK it is not possible to disable battery optimization via code, but you can prompt the user to do so and show them the settings page using [ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS](https://developer.android.com/reference/android/provider/Settings.html#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS)

**Comment by 8bitPit** [comment]
@Martin5001 thanks, I didn't know there was an intent action for this. I'm not certain if this helps, though. If I remember correctly some in Niagara's discussion group on Telegram reported it did not help.
