### ISSUE TITLE
Time/Clock cropped

### ISSUE THREAD

**Issue by cbosdell** [8bitPit/Niagara-Issues#1149]
I recently bought the new Unihertz Titan phone running Android Pie and having a 1440x1440 4.5" display. Niagara works great but isn't optimized for the aspect ratio. The time is cropped constantly. Attached is a screenshot. Also is there any way to have an option for the date and weather display to the right of the time to save space and be more optimized? Thanks.

![Screenshot_20200121025328](https://user-images.githubusercontent.com/44078937/72785990-822be900-3bfa-11ea-9ae0-9b469e8204fd.png)

**Comment by 8bitPit** [comment]
Thanks for reporting @cbosdell, I'll fix the cropping bug. You can also move the clock a bit down (long press on the clock > Move whole list) to fix it yourself.

**Comment by 8bitPit** [comment]
Furthermore, I did not implement customization options for the time/date widget to keep Niagara Launcher simple, about Niagara's key principles here: https://medium.com/niagara-launcher/niagara-launcher-in-2020-df3f6aa2d184.

**Comment by cbosdell** [comment]
Thank you for the quick response!

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1069
