### ISSUE TITLE
Clear all recent apps button gone when using 3 button navigation. Android 10.

### ISSUE THREAD

**Issue by renevdvorst** [8bitPit/Niagara-Issues#1151]
**Describe the bug**
When opening the recent apps in Android 10 using the 3 button navigation scrolling all the way to the left should show a "clear all" button. This button is gone when using Niagara Launcher. I tried switching to the system default launcher (Quickstep) and the button is there. It used to be there for Niagara in Pie. 

Also this only happens when 3 button navigation is used. 

**To Reproduce**
1. Select 3 button navigation 
2. Open the recent apps by pressing the square button 
3. Scroll all the way to the left. The "clear all" is button isn't there. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi A2 64gb
 - Android version: Android 10(Android One)

**Comment by 8bitPit** [comment]
I'm afraid I can't help. Niagara Launcher doesn't handle Androids recent screen, only your preinstalled launcher can override its behaviour (without root). If you use another third party launcher like Nova or Lawnchair you should reproduce the same issue.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
