### ISSUE TITLE
Edit mode icon misplaced

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1152]
After using Edit mode, icon from the rearrange apps list remains visible and sticks to the bottom of the screen and moves as I scroll. Opening and closing Edit mode didn't help so I had to restart the launcher.

Device: Samsung Galaxy J7
Android: 9 (Pie)
Niagara 0.12.0 alpha

![Screenshot_20200123-100817_Niagara Launcher](https://user-images.githubusercontent.com/35201200/72971292-b99cc000-3dc9-11ea-999a-7fc8b8741d9a.jpg)

**Comment by 8bitPit** [comment]
Have you found a way to reproduce this?

**Comment by Martin5001** [comment]
Unfortunately not. But I'll come back if I find it.

**Comment by 8bitPit** [comment]
This could be an [AndroidX ](https://developer.android.com/jetpack/androidx) bug and I think this happens so rarely that it's not wirth investigate the time to try to fix it. But please let me know if it happens again.
