### ISSUE TITLE
Option to jump directly into search with devices that have a physical keyboard

### ISSUE THREAD

**Issue by jjjhhhppp** [8bitPit/Niagara-Issues#1154]
There are certain android devices that have an in-built physical keyboard, and others that allow the use of an external keyboard. For those devices, it would be nice to type while on the homescreen and immediately be placed into the search option of Niagara. I feel as though this would increase efficiency for some power-users.

**Comment by 8bitPit** [comment]
Great request @jjjhhhppp. Hope you don't mind I merged it with #349.

**Comment by 8bitPit** [comment]
Merged with #349
