### ISSUE TITLE
Can't edit widget's size

### ISSUE THREAD

**Issue by ericfelipemoreira** [8bitPit/Niagara-Issues#1157]
**Describe the bug**
the second edit line at the Open Edit Mode isn't working

**To Reproduce**
1. Go to Open Edit Mode
2. Add a resizable widget like Daily Art's Screens
3. Try to move the second line

**Smartphone (please complete the following information):**
 - Device: Redmi Pro 5 Plus
 - Android version: MIUI 11

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Thanks for the report. Does it still happen after you restart Niagara Launcher?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
