### ISSUE TITLE
The Incredible Shrinking Widget!

### ISSUE THREAD

**Issue by ccocallas** [8bitPit/Niagara-Issues#1159]
When I choose and visually configure Rocket Player Pro's smallest of three widgets, it will appear as desired. After the screen goes to sleep, it will wake up with the widget scrunched down to a much shorter version of itself.

**To Reproduce**
1. Go to Launcher Settings -> Features -> Replace widget
2. Tap 'R' to see the Rocket Player widget options.
3. Tap Rocket Player.
4. Tap the smallest of the three widgets (a single-line widget).
5. Tap Replace Widget.
6. Tap Text color box.
7. Tap 'OK' to accept 'white'.
8. Slide Transparency slider to maximum.
9. Tap 'OK'.
10. Let the phone go to sleep (although this issue doesn't always occur the first time the phone goes to sleep).
11. Wake up the phone.
12. Notice that the widget has once again shrunken.
13. Alarm cat by muttering to self yet again.

 - Device: Samsung Galaxy S8+
 - Android version: Android 9

**Screenshots**
Freshly-loaded widget:
![image](https://user-images.githubusercontent.com/59316670/73238709-bd746d80-414e-11ea-9293-860bf5b84040.png)

Shrunken widget:
![image](https://user-images.githubusercontent.com/59316670/73238801-10e6bb80-414f-11ea-9b88-8ff1082c5367.png)

**Comment by 8bitPit** [comment]
Thank you very much for your detailed explanation and for putting so much in this bug report :D
I'll investigate it.

**Comment by ccocallas** [comment]
At first, I thought this issue was directly related to Screebl Pro, which I really like for its ability to instantly sleep my phone when I drop in my pocket upside down! But after disabling Screebl Pro and preventing it from reenabling itself on reboot and after updates, I still experienced the problem albeit less often. (Using Screebl Pro, the widget shrinks virtually every time I put the phone to sleep.) Now that I still have Screebl Pro disabled, I even had the widget shrink when I was working the volume control one time…though of course, not the next time I tried that! :(

**Comment by 8bitPit** [comment]
That's really weird. Thanks for the update :)

**Comment by ccocallas** [comment]
I had stopped using widgets because of this issue. Recently, I wanted to see if anything had changed, so I loaded a widget and watched as, before my very eyes, it immediately shrunk again! Disappointed, I moved to remove the widget.

And that's when I found the resizing arrows!

I resized the widget, and ever since, it has not become smaller! So I am closing this issue as Resolved.

**Comment by 8bitPit** [comment]
Thank you very much :)
