### ISSUE TITLE
Import Export Settings 

### ISSUE THREAD

**Issue by mtz** [8bitPit/Niagara-Issues#1161]
I would like to import and export the launcher settings to simple keep and set/reset quickly and stressless.

Thanks in advance. 
mtz

**Comment by Martin5001** [comment]
I would like this feature too. There are also some APIs for that: https://developer.android.com/guide/topics/data/backup

**Comment by 8bitPit** [comment]
Thank you both, it's under consideration: #222

**Comment by 8bitPit** [comment]
Duplicate of #222
