### ISSUE TITLE
Folders problems( translate from Brazilian Portuguese

### ISSUE THREAD

**Issue by j00ao** [8bitPit/Niagara-Issues#1167]
atualizei para o beta com os folders e o controle de música não está funcionando (translate from Brazil Portuguese)

**Comment by Martin5001** [comment]
> Updated to beta with folders and music control is not working.

**Comment by 8bitPit** [comment]
Thank you for translating @Martin5001 :D
@j00ao could you please elaborate on what's exactly not working? Posting a screenshot may also help.

In Portuguese:
Obrigado por traduzir @ Martin5001 :D
@ j00ao você poderia por favor explicar o que exatamente não está funcionando? A publicação de uma captura de tela também pode ajudar.

**Comment by j00ao** [comment]
basicamente, a atualização com recursos do Android 10 não está funcionando. Já reiniciei a launcher e já dei acesso às notificações muitas vezes. de vez em quando funciona e de vez em quando não funciona

**Comment by j00ao** [comment]
can I send the image though the email?

**Comment by 8bitPit** [comment]
Unfortunately, I'm afraid I can't help:
> Almost all devices are using Huaweis/Xiaomis EMUI/MIUI which run into that problem. It seems that they kill background processes like the notification listener service aggressively. One user on Telegram (Sean) linked me this site: https://dontkillmyapp.com 

[Source: #588]

**Comment by j00ao** [comment]
I did all of that stuff and didn't worked. but ok. no problem

**Comment by 8bitPit** [comment]
I'm very sorry. If nothing helps, disabling Niagara's home screen notification feature might be the only "solution".
