### ISSUE TITLE
Weather won't back away!

### ISSUE THREAD

**Issue by ccocallas** [8bitPit/Niagara-Issues#1169]
**Describe the bug**
Under certain conditions, it is impossible to use the Back button to leave the Dark Sky browser page.

**To Reproduce**
1. Notice that the weather on the Home screen shows the temperature is freezing outside.
 1.a. With curiosity piqued, tap the temperature number.
2. In the popup, look at the hourly forecast and notice that the daily forecast only shows three days.
 2.a. With curiosity piqued further, tap More.
 2.b. See that Dark Sky has opened a browser page.
3. Notice that Dark Sky is once again leading with the hourly forecast at the top.
 3.a. With mild annoyance at Dark Sky's inability to read your mind's desire to see the weekly forecast, flick upward to scroll down, seeking the weekly forecast.
4. _Inadvertently_ (but in actuality _deliberately_ for the purposes of this reproduction), your upward flick began on the map that was partially revealed at the bottom of the screen.
 4.a. Notice that the map has changed its focus while the rest of the page has remained stationary.
 4.b. (Optional) Decide to move the map around so that your location dot is once again showing.
5. Flick upward once again, exercising great care not to flick on the map.
 5.a. Read your weekly forecast.
 5.b. Become disinterested.
 5.c. Decide to return to the Home screen.
6. Tap the Back button.
7. The map flashes to recenter your location dot.
 7.a. The Dark Sky page remains showing, but you are not taken to the Home screen.
8. Tap the Back button again.
 8.a. The map flashes again.
 8.b. The Dark Sky page remains showing.
9. Tap the Back button repeatedly, because
![image](https://user-images.githubusercontent.com/59316670/73768767-72e68880-472e-11ea-9716-d7a848b040f8.png)
 9.a. Discover that no matter how many times the Back button is tapped, the map flashes and you are NOT taken Home.
10. Tap the Home button, because that's where you really wanted to go in the first place!

Secondary issue:
1. Repeat the entire process, INCLUDING deliberately tapping the map before tapping the Back button before tapping the Home button.
2. Scroll the edge of the screen to find the Chrome app.
 2.a. Tap the Chrome app to open your Home page.
 2.b. Notice that the Number of Tabs indicator shows multiple tabs are open.
3. Tap the number of Tabs indicator.
4. See that more than one instance of the Dark Sky web page has remained open and that each repetition of not being able to Back Home has left additional instances of Dark Sky open.

Caveat:
This issue does NOT present if the map is never touched.

**Smartphone:**
 - Device: Samsung Galaxy S8+
 - Android version: Android 9

**Screenshots**
Not necessary.

**Comment by 8bitPit** [comment]
Haha, such an awesome bug report, was very fun to read, thanks :D
I can reproduce this, but unfortunately I neither have control over Dark Sky's Website nor can I change how the browser handles back button events.

**Comment by ccocallas** [comment]
Okay, thanks for that. I’ll close the issue, since there’s nothing that can be done about it!
