### ISSUE TITLE
Lifetime subscription gone after reinstall

### ISSUE THREAD

**Issue by GeekLiberty** [8bitPit/Niagara-Issues#1170]
**Update** 
I was able to fix this by deleting my app data within the system settings for the app. I was given the prototypical launcher introduction and it thanked me for being a pro-lifetime member. That said, I shouldn't have had to spend that much time to figure it out. 

**Describe the bug**
Lifetime subscription isn't being reapplied or isn't able to re-apply in Pro menu after reinstalling the app after performing a factory reset. 

**To Reproduce**
1. Uninstall Niagara Launcher
2. Re-install Niagara Launcher
3. Scroll down to 'Niagara Pro' above 'Settings' 
4. Only the 7 day free trial is highlighted, the 'Buy Once * Own Forever' is greyed out. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android version: Android 10, Oxygen OS 10.3.0

![Screenshot_20200204-162022](https://user-images.githubusercontent.com/60677023/73799276-5d8f4f80-476a-11ea-8f3d-8355d1f04829.jpg)
![Screenshot_20200204-161910](https://user-images.githubusercontent.com/60677023/73799280-6122d680-476a-11ea-9352-03f240b2e942.jpg)
![Screenshot_20200204-161630](https://user-images.githubusercontent.com/60677023/73799285-64b65d80-476a-11ea-9c32-27cbb9dad5fc.jpg)

**Comment by athelas64** [comment]
When without reinstall the life-time purchase does not load and throws an error, even though it kind.9f still works. Kind of disappointed my lifetime didn't last over three months...

I think decision must be made if life-time purchases will be honored or refunded.

**Comment by Bohne13** [comment]
I have the same problem, my lifetime purchase is gone.
I think it was after the last update!

OnePlus 7T
OxygenOS 10.0.8.HD65BA
Any solution to this?

**Comment by 8bitPit** [comment]
Hi @athelas64 & @Bohne13, I'm very sorry that this happened. The error could be caused by being signed in with multiple Google accounts on your device. Please follow this guide: https://hackmd.io/@C1BuMppiTYazZhBH13jY3g/SyKlUgEkL
Of course you can also contact us via niagaralauncher@gmail.com.
Hope this helps.

**Comment by Bohne13** [comment]
Not only clear cash of Google play!
It helped finally when I removed the storage from Google play

**Comment by 8bitPit** [comment]
@Bohne13 I'm very glad you got your purchase back. Also thanks for the feedback, we'll probably edit the FAQ page.

**Comment by athelas64** [comment]
Hi, for me the problem kind of sorted itself out without any intervention. I am now seeing the Member since credit page and everything seems to be correct. Anyway, every day with Niagara is a happy day :-)

**Comment by 8bitPit** [comment]
@athelas64 awesome thanks so much :D

**Comment by 8bitPit** [comment]
For anyone else having this issue, please refer to: https://niagaralauncher.helpscoutdocs.com/article/29-lost-access-to-niagara-pro?preview=5e92ef5c04286364bc9839bf
