### ISSUE TITLE
Missing: option to hide letter list if not swiping 

### ISSUE THREAD

**Issue by shmykelsa** [8bitPit/Niagara-Issues#1171]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like an option to make so that the letter column is hidden if not swiping. Or at least hidden if the home is in the favourite list.

**Comment by 8bitPit** [comment]
@shmykelsa that's already possible (although a bit hidden) 😉 Launcher Settings > Look > Text > Hide alphabet. Hope this helps.

**Comment by shmykelsa** [comment]
> @shmykelsa that's already possible (although a bit hidden) 😉 Launcher Settings > Look > Text > Hide alphabet. Hope this helps.

Wow so I was remembering good! I remembered about this option... Couldn't find it no more. Thanks. Closing.

**Comment by 8bitPit** [comment]
Haha ^^
