### ISSUE TITLE
Edit mode: sort favourite apps by alphabet quickly

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1172]
I think it would be quite convenient to have an option to sort favourite apps quickly by alphabet in Edit mode. A "Sort apps:" label followed by a dropdown (or 2 pill buttons) could be added with options "A-Z" and "Z-A", which would sort the apps accordingly; but when the user moved any app in the list it would change to "Custom".

**Comment by 8bitPit** [comment]
I think that users favorize usually up to eight apps. In my opinion, an extra button to sort just those apps is not necessary.
