### ISSUE TITLE
Uninstall option shown for system app

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1173]
Niagara shows uninstall option for Samsung Gallery despite the fact that as a system app it cannot be uninstalled (it fails with android system package manager error notification when attempted).

PS: I got the same behaviour when I tried updating system camera app with a side-loaded apk on my previous phone, but that's not the case now.

 - Device: Galaxy J7
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1053
