### ISSUE TITLE
Different Icons For the home screen

### ISSUE THREAD

**Issue by DoggoOfSpeed** [8bitPit/Niagara-Issues#1175]
**Is your feature request related to a problem? Please describe.**
Having an option to have different icon packs for homescreen, and the app list would allow me to use an Icon pack like Lines on the homepage, but since not all my apps are supported, I would use an Icon pack like cavion. This way I could avoid inconsistencies.

**Describe the solution you'd like**
Basically an (optional) option to choose the Icon pack for the homepage.

**Comment by 8bitPit** [comment]
Hi @DoggoOfSpeed. To keep Niagara Launcher as simple as possible, I'm against adding an extra toggle for choosing different icons for your favorites. However, you may find hiding your favorites from Niagara's app list useful: https://github.com/8bitPit/Niagara-Issues/issues/955
