### ISSUE TITLE
Sort apps in swipe actions

### ISSUE THREAD

**Issue by matanui159** [8bitPit/Niagara-Issues#1176]
**Is your feature request related to a problem? Please describe.**
There is no way to sort the apps in swipe actions, either automatically (alphabetically) or manually. They keep the order they were added in so you have to remove/readd to sort them

**Describe the solution you'd like**
Some way to sort them either alphabetically or manually.

**Comment by Martin5001** [comment]
Yes, this came to my mind too. Maybe the same drag handlers as in Edit mode could be used?

**Comment by matanui159** [comment]
Yeah I was thinking the same thing

**Comment by 8bitPit** [comment]
In my opinion it would be great if Niagara Launcher automatically sorts swipe actions by usage (like Niagara sorts apps starting with the same letter in the app list). This wouldn't require additional settings and setup time, but your apps would still be ordered in a useful way.

**Comment by matanui159** [comment]
I would disagree or atleast ask for an option. I've never liked how Niagara sorts by usage since it makes muscle memory useless

**Comment by Martin5001** [comment]
For me the purpose of reordering them would be to make some groups more by context than by a set rule. So I personally would not like alphabetical nor usage–based sorting. For example if I had "Call contact" and "Write SMS" actions, I would have them together – even when I don't use one of them so often – but would like to decide what goes after or before these two. So flexible dragging would fit best in this case. But that's only my personal preference.

**Comment by Martin5001** [comment]
@matanui159 I like the current sorting for apps but not for this case with swipe actions.

**Comment by 8bitPit** [comment]
Implemented in v0.20.0
