### ISSUE TITLE
Vanilla Music widget

### ISSUE THREAD

**Issue by Jackal93** [8bitPit/Niagara-Issues#1177]
**Describe the bug**
The widgets of [Vanilla Music](https://play.google.com/store/apps/details?id=ch.blinkenlights.android.vanilla) only work after the controls in the notification are tapped

**To Reproduce**
1. Install vanilla music
2. Add widget to home
3. Tap on widget or its controls
4. Nothing happens
5. Start vanilla music and play a song
6. Open notifications bar
7. Tap on play/pause button
8. Tap on home widget or its controls
9. Now they work, but not permanently

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 Pro
 - Android version: 9
- MIUI version: 11.0.2

**Comment by 8bitPit** [comment]
Thank you for reporting.

**Comment by 8bitPit** [comment]
Hi again. Can you also reproduce this on other third party launchers like Nova or Lawnchair?

**Comment by Jackal93** [comment]
Hello I just tested this and yes, it has the same issue on both Nova and Lawnchair. The widget only works properly on the system launcher.

**Comment by 8bitPit** [comment]
Thank you very much for testing. This may indicate that the error is being caused by the widget itself, not by their hosts. You might want to report it here: https://github.com/vanilla-music/vanilla/issues

**Comment by Jackal93** [comment]
Yes I did as soon as I realized it doesn't work on most launchers:
https://github.com/vanilla-music/vanilla/issues/1020

Thank you!

**Comment by 8bitPit** [comment]
Awesome :) I'll close this one then.
