### ISSUE TITLE
Search background blur

### ISSUE THREAD

**Issue by praveenchandranpk** [8bitPit/Niagara-Issues#1178]
Would be nice to have blurred search background.

**Comment by Martin5001** [comment]
Agree. (Another option would be to darken it.)

**Comment by 8bitPit** [comment]
Once https://github.com/8bitPit/Niagara-Issues/issues/14 or https://github.com/8bitPit/Niagara-Issues/issues/705 gets implemented, the tint/blur effect will also be applied to Niagara's search screen.
