### ISSUE TITLE
/Concept/ Edit Mode: Apps list position reset button

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1179]
I made a simple concept how Reset button, shown when moving the apps list, could be placed to the bottom to avoid text intersection.

[![Video](https://user-images.githubusercontent.com/35201200/74440848-0dea0b80-4e6f-11ea-9db6-52d1d67df96f.png)](https://vimeo.com/391226166)

**Comment by Martin5001** [comment]
Furthermore, if this was implemented, the move button with the line would no longer have to be offset but could be aligned like so:
![image](https://user-images.githubusercontent.com/35201200/74445676-0dee0980-4e77-11ea-9bd5-f4aa7c76fecc.png)

**Comment by 8bitPit** [comment]
Wow, thanks for putting so much effort in a feature request :) I'll definitely consider this when redesigning the whole edit mode.

**Comment by 8bitPit** [comment]
Edit mode has been removed in v0.29
