### ISSUE TITLE
Double tap on home screen to sleep

### ISSUE THREAD

**Issue by js-d-coder** [8bitPit/Niagara-Issues#1180]
**Is your feature request related to a problem? Please describe.**
No problem, just feature request as mentioned in title. The app can request to be Device Admin to put device to sleep.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.

**Comment by 8bitPit** [comment]
Thanks for your request, but I believe this is a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/63

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/63
