### ISSUE TITLE
Notification are not showing up on the home screen. 

### ISSUE THREAD

**Issue by kazimShaikh** [8bitPit/Niagara-Issues#1181]
![Screenshot_2020-02-14-17-49-23-613_bitpit launcher](https://user-images.githubusercontent.com/40717328/74531356-6cd48100-4f52-11ea-90f6-766a1a960054.jpg)
**Describe the bug**
I am using this Niagara Launcher past 2-3 months and I love the concept how minimal it makes the device. 
The thing which I love the most is the home screen notification but it works sometime and sometime it doesn't. I ask you to please resolve it ASAP. 
And also I've purchased the Annual Subscription of Niagara. 
Don't make me regret. 

**To Reproduce**
1. None. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T pro/ Redmi K20 pro (Same phone different model name.) 
 - Android version: Android 10 (Q) 
 - MIUI 11.0.3 (Global) 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.
![Screenshot_2020-02-14-17-51-28-875_bitpit launcher](https://user-images.githubusercontent.com/40717328/74531459-b45b0d00-4f52-11ea-929b-f09493aeaffa.jpg)

**Comment by Martin5001** [comment]
(Already described here: #1144)

**Comment by Ladyvb22** [comment]
Notifications on home screen not working repeatedly asks to grant access. This is a recurring problem. This is the only issue that I have had.

**Comment by kazimShaikh** [comment]
This really needs to be fixed. 
Please work on this feature.

**Comment by 8bitPit** [comment]
@kazimShaikh I'm very sorry, I really tried a couple of workarounds to fix this to no avail. This mostly happens on Xiaomi devices by the way, I suppose they are killing background services aggressively. You can also read a bit more about this here: https://github.com/8bitPit/Niagara-Issues/issues/588

**Comment by 8bitPit** [comment]
You could also disable Xiaomi's battery optimization for Niagara Launcher. Some reported that it did help, while others said it made no difference.

**Comment by kazimShaikh** [comment]
Yes @8bitPit. 
Really thankful it does work for me. I disable the battery optimization for the Niagara Launcher and now it's working like charm. 
Really looking forward for more amazing features in the upcoming updates.

**Comment by 8bitPit** [comment]
Glad to hear that @kazimShaikh 😊
