### ISSUE TITLE
Weather and VPN

### ISSUE THREAD

**Issue by maven3-gh** [8bitPit/Niagara-Issues#1182]
When manually trying to change the weather location while connected via a VPN, I get the message that there is no Internet connection. With the VPN disconnected, I can change the weather location. 

**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Does only changing weather location not work with your VPN or does Niagara's weather widget not show up at all?

**Comment by maven3-gh** [comment]
I have seen both, but can not duplicate it at the moment. Rebooting my phone (LG G4 Android 6) fixed the widget that did not show up. In the other case I could not change the location via Settings. Whle VPN was connected, it gave a message that there is no connection to the Internet. 
On 2/16/2020 06:32:30, Peter Huber <notifications@github.com> wrote:
Does only changing weather location not work with your VPN or does Niagara's weather widget not show up at all?

**Comment by 8bitPit** [comment]
Thanks for your reply. Can you please reopen this issue once it happens again?
