### ISSUE TITLE
Fallback cover doesn't show up

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1186]
Some apps don't show any picture when playing audio/video (especially web browsers don't show any thumbnail, probably because the website does not provide one). Maybe it would be good if Niagara checked for this and if no picture is available, the player on the homescreen would get centered (or maybe better, aligned to the left as the clock is?) so it wouldn't be offset to the right. (Another option could be to show app icon instead, but the resolution would probably not be good enough.)

![Screenshot_20200216-193500_Niagara Launcher](https://user-images.githubusercontent.com/35201200/74611869-40f6fe00-5100-11ea-8643-4c7f30cc40e9.jpg)

**Comment by Montell2099** [comment]
I'm all for this! Some kind of fallback-approach for when there's no cover art to be displayed, like when playing audio from the browser as you mentioned.

A default sound/music icon, or just hide the cover art placeholder and shift the media controls to the left.

**Comment by 8bitPit** [comment]
Niagara already displays a fallback cover, but due to a bug in one of the recent versions, it's not showing, sorry.

**Comment by 8bitPit** [comment]
Fixed in v.0.18.0
