### ISSUE TITLE
Make Niagara Pro a separate app on the playstore 

### ISSUE THREAD

**Issue by GeekLiberty** [8bitPit/Niagara-Issues#1187]
I must admit this wouldn't be the best for acquiring new subscribers, but I love this launcher enough that I want to share the Pro version with individuals in my family library. Perhaps downloading the new Pro app could reference a uniquely generated code in the original to validate the in app purchase/subscription. It would be more to maintain, but I think it would be great for families looking to simplify their android experience. Eventually, Digital Well Being could be integrated to hide restricted apps, in the advent that a parent thinks Timmy is spending too much time on Minecraft.

**Comment by 8bitPit** [comment]
That's understandable. It also bothers me that in app purchases & subscriptions cannot be family-shared. Nevertheless, I fear that a separate apk would cause a lot of confusion. I really want to make sure that there are only two versions of Niagara Launcher (free and pro) and that the upgrade process is easy and straight forward.

**Comment by 8bitPit** [comment]
I hope you're not too disappointed, sorry.
