### ISSUE TITLE
Sth. wrong with homescreen notifications

### ISSUE THREAD

**Issue by tong07** [8bitPit/Niagara-Issues#1188]
**Describe the bug**
There is no music name displayed with Netease(the latest ver. ) and no front cover displayed with QQ music(same as above) either.

What's more, the pause break doesn't work out. when I press it the music is still playing.

**Smartphone (please complete the following information):**
 - Device: Sony xperia xzp
 - Android version: Android 9 (Pie)

**Screenshots**
![pt2020_02_17_11_22_00_mh1581909762902](https://user-images.githubusercontent.com/61130874/74621408-d5507780-5177-11ea-9fee-90870bf8caf5.jpg)

**Comment by 8bitPit** [comment]
Thanks for your report.

**Comment by 8bitPit** [comment]
The cover art problem was fixed in v.0.18.0. Regarding the issue with playback controls, please refer to https://github.com/8bitPit/Niagara-Issues/issues/485
