### ISSUE TITLE
Steps & calendar

### ISSUE THREAD

**Issue by Wtreck** [8bitPit/Niagara-Issues#1189]
It would be very cool if you could display **upcoming calendar events** and **appointments** as well as the **steps** on the start screen, as appropriate widgets destroy the minimalist design.
#543 #ux #ui

**Comment by Wtreck** [comment]
#543 #ux #ui

**Comment by 8bitPit** [comment]
I'm happy to tell you that this is likely to be implemented: https://github.com/8bitPit/Niagara-Issues/issues/55

**Comment by 8bitPit** [comment]
Duplicate of #55
