### ISSUE TITLE
Swipe right on apps for quick actions

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#119]
Right now, swipping on any app only opens "No new messages" pop-up.

**Comment by zbhoy** [comment]
I believe if the app has quick action options they show up. That is what happens for Gmail, Twitter, and others on mine. But if Dev hasn't implemented them then it shows no new messages

**Comment by Shinra04** [comment]
Oh I'm sorry, you're right. It wasn't working on YouTube or WhatsApp initially. It's all fine now.

**Comment by Getochuma** [comment]
Hi just started using the launcher. I noticed that when I swipe right on twitter app I can see the quick action options but unfortunately I can't use them. I get the error "niagara launcher: Shortcut isn't available". Is there something I need to do?
