### ISSUE TITLE
Search function doesn't accept  "&" sign

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1191]
When using the search function to enter Play Store looking for an app, using the "&" sign doesn't work. Searching for "H&M" only results in a search for "H".

Very minor inconvenience, but I just wanted you to be aware of it.

**Comment by 8bitPit** [comment]
Well spotted, thanks! Luckily there's an easy fix for that.

**Comment by 8bitPit** [comment]
Fixed in v.0.18.0
