### ISSUE TITLE
Moving the favourites posistion fails to do anything

### ISSUE THREAD

**Issue by hobhobuk** [8bitPit/Niagara-Issues#1192]
**Describe the bug**
When trying to move the entire list upwards, it just drops back to where it was before.
This results in there always being a large amount of space on the top of the screen, pushing items further down when playing music.

Recently changed phone and this issue seems to be on both.

**To Reproduce**
1. Open edit mode
2. Move the whole list
3. Tap the tick to confirm
4.List returns to how it was previously.

**Smartphone (please complete the following information):**
 - Samsung A80, also Huawei P30
 - Android version: 10

**Comment by hobhobuk** [comment]
Video showing issue.
https://youtu.be/NqGUIFsHG3c

**Comment by kazimShaikh** [comment]
You need to click on that up-down arrow button, and then move the whole list the way you like.

**Comment by hobhobuk** [comment]
Even holding the arrow, it still drops back to where it was.

**Comment by kazimShaikh** [comment]
Don't hold the arrow, just click it and it will enable the option to adjust the way you want it.

**Comment by 8bitPit** [comment]
@kazimShaikh thanks for the support :) @hobhobuk I hope this helped. Please reopen this issue in case it didn't
