### ISSUE TITLE
Apps list not refreshed

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1193]
Installed app is not shown in the all apps list. I noticed this when I was testing the new backup system. (But I don't know if it has anything to do with it.) EDIT: Restarting the launcher helped, but when I tried installing another app, it was not shown again. But now it works fine even without restart, so I'm not sure but maybe it was caused by my fiddling with Google drive backup toggle – there is a bug in Google Drive which causes it to stop working if it is disabled and re-enabled with lock screen password set.

**To Reproduce**
1. Create/update a device backup via Google Drive settings
2. Uninstall Niagara
3. Uninstall one of the apps to test the reinstall feature later
4. Install Niagara back and run it
5. Install the previously removed app using the icon
6. See that it is installed and shown in favourites, but does not show up in the all apps list.

**Smartphone:**
 - Device: Samsung Galaxy J7
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
Thanks, I'll investigate it.

**Comment by 8bitPit** [comment]
Fixed in v.0.19.1 Thank you for letting me know Martin.
