### ISSUE TITLE
Gesture Navigation

### ISSUE THREAD

**Issue by tomadamholtslander** [8bitPit/Niagara-Issues#1194]
Android 10 Navigation Gestures would be pretty clutch. I love the gesture nav on android 10 but this launcher doesn't support it yet. It would be cool! 
Action launcher and Evie both have it.

**Comment by 8bitPit** [comment]
Launchers don't have to do anything to support gesture navigation. Evie Launcher for example, hasn't been updated since June 2019. At this point, Android's gestures weren't even available on third party launchers. Can you please check again, if gestures don't work with Niagara? Moreover, can you please share the name of your phone and the rom you're using?

**Comment by tomadamholtslander** [comment]
Thank you for you response. I have checked an Niagara (my favorite launcher
btw) does not use android 10 gestures. I am using a Samsung Galaxy s1oe.
Perhaps this is a manufacturer issue (Samsung) and not a third party issue
(launchers). However, Evie and action launcher, as well as the default one
UI, use android 10 navigation gestures. These gestures are very intuitive
and similar to those on iPhone (the only thing I like about iOS).

Thank You

Tom Holtslander

**Comment by 8bitPit** [comment]
Thank you for your kind reply. Does gesture navigation also work on Action/Evie after you set them as default?

**Comment by tomadamholtslander** [comment]
Yes sir.

**Comment by 8bitPit** [comment]
Hmm weird. I did a quick search and it seems that Samsung doesn't offer gesture navigation for third party launchers yet, I really don't know why it works with only a couple of third party launchers: https://www.reddit.com/r/GalaxyS9/comments/evt2yd/new_full_gesture_support_on_android_10_but_you/
https://us.community.samsung.com/t5/Galaxy-S10/When-is-support-for-android-10-navigation-gestures-coming-to-3rd/td-p/1115709

**Comment by 8bitPit** [comment]
I will merge this issue with #989 and will give you an update if I hear any news about gestures.

**Comment by 8bitPit** [comment]
Merged with #989

**Comment by tomadamholtslander** [comment]
I think it's weird that some third party launchers can use the gestures and
others can't. Thank you for your patience. niagara launcher is my favorite
and this little hiccup is not where near enough to make me switch to a
different one. Keep up the good work

**Comment by 8bitPit** [comment]
Thank you very much for your kind words :)
