### ISSUE TITLE
Display currently playing song above widget instead of below

### ISSUE THREAD

**Issue by Gabe-hrh** [8bitPit/Niagara-Issues#1199]
I like to use my own weather and time widget but whenever I use my own widget Currently playing songs display under the widget instead of ontop like the current built in time widget does.

Some sort of option to have media display above widget.

**Comment by 8bitPit** [comment]
I'm sorry but the position of the media player won't be customizable to keep the launcher simple, but maybe you can swap Niagara's widget (clock & weather, etc.) with your custom widget in the feature.
