### ISSUE TITLE
Overview button stopped working while using Niagara launcher

### ISSUE THREAD

**Issue by thewrathofgrath** [8bitPit/Niagara-Issues#120]
I've set Niagara as default, and the overview button doesn't work anymore. Can't quit apps, double tap to switch to preview app, or anything.

**Comment by 8bitPit** [comment]
That's odd, are you using Android Pie?

**Comment by thewrathofgrath** [comment]
Yeah, on a Pixel 2 security patch level August 5

**Comment by 8bitPit** [comment]
Maybe that's a Pixel bug idk, im running also on Pixel and it works fine.
