### ISSUE TITLE
Battery charge level indicator

### ISSUE THREAD

**Issue by simonjbolton** [8bitPit/Niagara-Issues#1200]
I'm using the launcher on an full android 7.x  SmartWatch, LEMFO LEM 10 and LEMFO LEM T works great!! but missing the all important battery indicator next/near the the time, also ability increase time font size, in the at a glance section, I can see a very popular future of this launcher being used on full android watches if certain features mainly needed in full android watches can be implemented.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by Rod911** [comment]
Battery level indicator is available as a pro feature #100.
Discussion about font size is in #148.

**Comment by Rod911** [comment]
Duplicate of #100
