### ISSUE TITLE
Show notifications of apps inside (folder) pop-ups

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1201]
You can add apps as custom swipe actions to other apps, but they won't show their notifications inside the swipe menu yet.

**Comment by babb0** [comment]
I like the "folder-function" offered by swipe actions. To collect for example all chat apps under one swipe menu it would be nice to have a notification on the primary app that inside the swipe menu an app has a notification.

**Comment by 8bitPit** [comment]
@babb0 good thought!

**Comment by alirahimpour89** [comment]
> I like the "folder-function" offered by swipe actions. To collect for example all chat apps under one swipe menu it would be nice to have a notification on the primary app that inside the swipe menu an app has a notification.

This is exactly the reason why I need this!

**Comment by luxcalor** [comment]
After using Niagara for some time this is the feature I miss the most. Hope it is not very low priority. :)

**Comment by wimstefan** [comment]
That's indeed one of the few things I'm missing ...
It's very refreshing to have a new look at your launcher and do things different but those notifications would really add something to the (already very nice) picture.

**Comment by kklepacz** [comment]
I assume that @babb0 comment referred the "Popup Apps" (popup with one primary app and some connected apps under swipe action).
In case of newly introduced "Popup folders", situation is a bit different. 
Let's say we have 3 chat apps in Chat folder: Messenger, Google Messages, Signal.
I would say that all 3 of them are equally important so making one primary (and printing only notification for it) is not an option IMO. 
Having said that, it would be nice to see notification of any app in the folder but only one at the time to keep it clean. 
Which one? I can imagine two possibilities: 
1. Most recent notification of ANY app in folder.
2. Notification of ANY app in folder but based on priority (order in the folder).

**Comment by soymadip** [comment]
> I like the "folder-function" offered by swipe actions. To collect for example all chat apps under one swipe menu it would be nice to have a notification on the primary app that inside the swipe menu an app has a notification.

Yes

**Comment by luxcalor** [comment]
There was this picture posted on discord. I would prefer the pop-up folder notification summury to be something like this but wlth number of notifications in parantheses after each app name. 
![sketch16200831352000101](https://user-images.githubusercontent.com/76074147/118862214-1b9a0680-b8e6-11eb-937f-ec0abf7f6231.png)

**Comment by huggybjmn** [comment]
Notifications for sub folders should be displayed at the top level. That way a user knows that there is a notification available in the sub folder.

**Comment by Oddward** [comment]
> There was this picture posted on discord. I would prefer the pop-up folder notification summury to be something like this but wlth number of notifications in parantheses after each app name. 
> ![sketch16200831352000101](https://user-images.githubusercontent.com/76074147/118862214-1b9a0680-b8e6-11eb-937f-ec0abf7f6231.png)
> 

Yeah I made that along with a couple other mockups lol

That mockup is about as much text content as I'd want to see in folder notifications, the other mockups explored more minimal badges just to notify a user that "there are notifications here". At least I don't wanna see, like, full notification previews under folders as that kinda defeats the way we use folders in favourites to reduce the clutter from all those chat notifications for example 🤔

This way also adds a layer of privacy to the notification previews, so random people don't see your private chats on your home screen for example 👀

Others:
![sketch1620137325655~01~01.png](https://user-images.githubusercontent.com/22635314/119697592-a0d66b80-be50-11eb-9103-7c93894c8c52.png)
![sketch1620136287758~01~01.png](https://user-images.githubusercontent.com/22635314/119697615-a9c73d00-be50-11eb-9d5f-4a553aadfb6b.png)

**Comment by luxcalor** [comment]
> That mockup is about as much text content as I'd want to see in folder notifications, the other mockups explored more minimal badges just to notify a user that "there are notifications here". At least I don't wanna see, like, full notification previews under folders as that kinda defeats the way we use folders in favourites to reduce the clutter. 

Exactly. Previews on top level would be too much. But "there are notifications there" approach is also not convinient as one would still need to open the pop up to glance which apps have the notifications. Name of the app and number of notifications is optimum amount of information for top level imo. Good job with those mockups btw.

**Comment by pfuerste** [comment]
> 
> 
> > There was this picture posted on discord. I would prefer the pop-up folder notification summury to be something like this but wlth number of notifications in parantheses after each app name.
> > ![sketch16200831352000101](https://user-images.githubusercontent.com/76074147/118862214-1b9a0680-b8e6-11eb-937f-ec0abf7f6231.png)
> 
> Yeah I made that along with a couple other mockups lol
> 
> That mockup is about as much text content as I'd want to see in folder notifications, the other mockups explored more minimal badges just to notify a user that "there are notifications here". At least I don't wanna see, like, full notification previews under folders as that kinda defeats the way we use folders in favourites to reduce the clutter from all those chat notifications for example 🤔
> 
> This way also adds a layer of privacy to the notification previews, so random people don't see your private chats on your home screen for example 👀
> 
> Others:
> ![sketch16201373256550101.png](https://user-images.githubusercontent.com/22635314/119697592-a0d66b80-be50-11eb-9103-7c93894c8c52.png)
> ![sketch16201362877580101.png](https://user-images.githubusercontent.com/22635314/119697615-a9c73d00-be50-11eb-9d5f-4a553aadfb6b.png)

Is there currently a workaround for this? I grouped my messaging apps into a pop-up folder yesterday, but without a way to see if I have messages in any of the three apps inside the folder, it make the folder unusable for me.

**Comment by Oddward** [comment]
> Is there currently a workaround for this? I grouped my messaging apps into a pop-up folder yesterday, but without a way to see if I have messages in any of the three apps inside the folder, it make the folder unusable for me.

No built-in one I guess, not unless you use another service like KWGT/KLWP to create some kind of notification on your screen.

I also grouped my chat apps to declutter, I just check them regularly when I think I prolly have notifications, or see the shade/lockscreen

**Comment by 8bitPit** [comment]
Implemented in v1.3.2 :D

**Comment by 8bitPit** [comment]
![PopUpNotifications](https://user-images.githubusercontent.com/9284845/124631925-256ecd80-de84-11eb-9ff5-0f7ba4036ef3.png)

**Comment by luxcalor** [comment]
This works perfectly at the moment. Implementation and usability is top notch. Thank you very much.

**Comment by 8bitPit** [comment]
Thanks for testing @luxcalor, glad you like it :D
