### ISSUE TITLE
Cannot revert to an app's original icon when using custom icon pack

### ISSUE THREAD

**Issue by Xavi3RElvis** [8bitPit/Niagara-Issues#1202]
**Describe the bug**
Cannot revert to original icon.

**To Reproduce**
Apply a custom icon pack to the launcher.
Try to revert an app's initial icon to the launcher.
When using a custom icon set, when trying to revert an app's icon to the original used, there is no option to use the default but only one of the custom icon packs installed

**Smartphone (please complete the following information):**
 - Device: galaxy s8
 - Android version: Android 9 (Pie)

**Comment by Rod911** [comment]
Thanks for the report.
This has already been requested. See #553
