### ISSUE TITLE
At a glance clock cuts off KeepCalm-Medium font

### ISSUE THREAD

**Issue by dgunay** [8bitPit/Niagara-Issues#1205]
**Describe the bug**
When I use the [KeepCalm Medium](https://www.dafont.com/keep-calm.font) font, the At A Glance clock cuts off the tops of the numbers and it looks bad. I'm assuming the font reaches some boundary where letters/numbers get cut off.

**To Reproduce**
1. Use KeepCalm Medium from the link above as Niagara's font
2. Enable At A Glance clock
3. Go to homescreen

**Smartphone (please complete the following information):**
 - Samsung Galaxy Note 8 SM-N950U
 - Android 9

**Screenshots**
![image](https://user-images.githubusercontent.com/16074091/75944306-2d5fcd00-5e4c-11ea-8db1-0509d4640f90.png)

**Comment by 8bitPit** [comment]
Sorry, but I don't know if I can fix that: https://github.com/8bitPit/Niagara-Issues/issues/1131

**Comment by dgunay** [comment]
I'll see if I can find a way to tweak the custom font to fit within the clock better. Thanks.

**Comment by 8bitPit** [comment]
I think I figured out the cause, this should be fixed in v0.32. @dgunay

**Comment by dgunay** [comment]
Thanks! I've switched my home screen aesthetic up since opening this but I'll try it again later today.
