### ISSUE TITLE
Notifications not showing since pro upgrade

### ISSUE THREAD

**Issue by SnuffThePunkz** [8bitPit/Niagara-Issues#1206]
Hey so I've been using Niagara launcher for a few weeks and love it, figured I'd give pro a try and since I upgraded to Pro it has lost the option to display notifications. They still show up at the top of the phone, but nothing on the icons like it used to.

I've completed the troubleshooting, rebooting app, revoking and giving the permissions again, force closing the app, and rebooting the device.

It also occasionally will revert to the default launcher when off, and when I unlock my phone it will show the stock one. Even though Niagara is still set as the default.

I'm not sure how to reproduce it.

 - Device: Blackview BV9800
 - Android version: Android 9 (Pie)

![Screenshot_20200305074214](https://user-images.githubusercontent.com/61839882/75997888-de01b700-5eb4-11ea-8d37-4b98728539f0.png)

**Comment by 8bitPit** [comment]
Hi @SnuffThePunkz, I'm very sorry that notifications stopped working. I believe the problem isn't related to your purchase, but of course you can issue a refund if you're not happy with Niagara Pro. I recommend to check out https://dontkillmyapp.com/. The website describes several issues some firmwares have that cause Niagara's (and other app's notification listeners) to be stopped. Hope this helps. Thanks a lot for your support by the way .

**Comment by SnuffThePunkz** [comment]
Alright that is fair, but I'm at a loss as to why it worked with no issues since I installed it in maybe January, but an hour after upgrading it stopped working.

**Comment by 8bitPit** [comment]
That's strange indeed. Did https://dontkillmyapp.com/ help?

**Comment by SnuffThePunkz** [comment]
Not directly no, but it out me on the path of upgrading the firmware and it seems to have worked itself out hopefully going forward.

**Comment by 8bitPit** [comment]
That's great to hear :)
