### ISSUE TITLE
Simple folder support with dummy apps

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1209]
A folder icon that behaves like an app, but opens its action menu when tapped on.

**Comment by ZephyrMathi** [comment]
I thouight an Folder could have 2 purpose 
while tapping it will open the folder and
while swiping it will open some custom widgets (or an another set folder)
so you could have 1 folder icon do the work of 2 folder icons 
for my preference widgets would make a lot of sense .

**Comment by 8bitPit** [comment]
@ZephyrMathi something similar is planned: In the future it may also be possible to include widgets in the swipe menu / folder.

**Comment by ZephyrMathi** [comment]
> @ZephyrMathi something similar is planned: In the future it may also be possible to include widgets in the swipe menu / folder.

@8bitPit That would be great .

**Comment by GintokiHub** [comment]
Yeah Im definetly for gaving an option like this.
Comparable to smart launcher s double and triple tap actions.

**Comment by ChaoticDucc** [comment]
I second this suggestion massively. I would use it so much. As a suggestion, it would be nice if we could add a custom design.

**Comment by awgneo** [comment]
I love this idea as well; pinning apps to other apps is incredibly weird and awkward.

**Comment by labaland** [comment]
Let US create empty maps!

**Comment by ceejey** [comment]
I agree, the current solution is very weird.

**Comment by maciejkos** [comment]
@8bitPit Hi Peter, 

I was wondering if there is an ETA for this feature?

I would love to set Niagara as my main launcher, but folders are too critical for me to use a launcher that doesn't fully support them.

For users who, like me, have many folders with many apps, it would be important to either be able to import the existing ones or have Niagara assist in grouping them like, e.g., JINA app, does.

Thanks, and congratulations on creating an excellent launcher!
-M.

**Comment by 8bitPit** [comment]
I'm sorry @maciejkos, but we don't give you ETAs.

**Comment by foreverxhb** [comment]
> @8bitPit Hi Peter, 
> 
> I was wondering if there is an ETA for this feature?
> 
> I would love to set Niagara as my main launcher, but folders are too critical for me to use a launcher that doesn't fully support them.
> 
> For users who, like me, have many folders with many apps, it would be important to either be able to import the existing ones or have Niagara assist in grouping them like, e.g., JINA app, does.
> 
> Thanks, and congratulations on creating an excellent launcher!
> -M.

I don't like this

**Comment by GintokiHub** [comment]
Is this difficult to implement or are you afraid it might detract from the core launcher concept?

**Comment by 8bitPit** [comment]
@GintokiHub, it's more of a UX design challenge. We have received lots of different ideas on how folders could be integrated into Niagara, and now we have to merge them and create one system that is simple to setup and easy to use :)

**Comment by GintokiHub** [comment]
@8bitPit Would love to see the support of this feature, hope the merges go well.
All the best.

**Comment by GriffinTheThird** [comment]
It seems to me that the simplest solution to folders would be a custom heading in the alphabet list. A B C D E F G Games H I...

I already love this launcher and use it as my default, but this would improve the experience astronomically.

**Comment by 8bitPit** [comment]
Added in v.1.2 :D https://medium.com/niagara-launcher/pop-up-date-4a5d3522df2d
