### ISSUE TITLE
Minimalistic Media Player

### ISSUE THREAD

**Issue by AVHaCkErr** [8bitPit/Niagara-Issues#1210]
To the Developer, 

I have been using Niagara Pro since late December,
It is an absolutely wonderful launcher and I seriously can't even think of switching to any other launcher.
It is absolutely minimalistic and I love every bit of it.

If you could only change the design and position of the media player so that it would be either in a linear fashion either in the top of the bottom of the screen, that would just make it so much better.

![Screenshot_20200309-083252__01](https://user-images.githubusercontent.com/38064122/76179366-b0807a80-61e0-11ea-8f6d-b65c1f58b1ba.jpg)

Also I would love to see the media player shrunken down a bit as it just goes against my absolutely minimalistic theme. 

Again thanks a lot for this wonderful launcher.
Hoping to see this functionality added soon enough.
Have a good one. 

Regards
-Aditya

**Comment by 8bitPit** [comment]
Thanks a ton @AVHaCkErr :D The problem is, that the user can favorize as many apps as she wants. If the player would show up below these apps, it may not be visible by default. I could also make the player sticky and always visible, but I believe the way it is looks way cleaner.
