### ISSUE TITLE
Option to simplify weather widget

### ISSUE THREAD

**Issue by craiga007** [8bitPit/Niagara-Issues#1211]
Problem: At the moment when I tap on the weather widget I get the temperature for the next two hours and the high/low temperatures for the next two days. 99% of the time I then tap on "more" to take me into my weather app. Then when I leave my weather app I then have to tap outside the weather widget summary to get back to my home screen. That is two more taps than it needs to be which goes against the minimalist design that I like so much about Niagara Launcher.

Possible Solution: Add an option in the weather settings (off by default to preserve backward compatibility) to directly launch the weather app. This would save me two taps and could solve the requests that some people have by wanting additional information like feels like temperature and wind speed. They can get all the information they want from their weather app.

**Comment by 8bitPit** [comment]
Hi @craiga007, thanks for your request. Because Niagara Launcher should be as simple as possible, I would say it's not worth to introduce an extra toggle to save one tap every now and then. I believe it's really important to keep the amount of toggles to a minimum.

**Comment by craiga007** [comment]
Hi Peter,

Thanks for getting back to me. The reason I suggested the toggle to take you directly to the weather app was to save two taps, not one tap, if you normally want to then look at the weather app. Is there a reason why the weather summary you display is still displayed after you tap on “More” and then return from the weather app? I would think it should be removed once you tap on “More”. That is one tap that could be eliminated without any extra toggles.

In order to keep the user interface as simple as possible on my phone I have turned off Niagara Launcher from displaying the weather, and added Dark Sky to my favorites. That way I can get to the weather with a single tap and I don’t need to do another tap after I have closed Dark Sky to remove the Niagara Launcher weather summary. Unfortunately I now don’t get to see the temperature on the home screen. Another option could be to use KWGT to display the temperature and have it launch Dark Sky when you tap on it but that would be significantly more complicated than a toggle that would do the same thing, but I would only need to set it up once.

I think Niagara Launcher is by far the best Android launcher and I do appreciate how you are trying to keep it as simple as possible.

Craig

**Comment by 8bitPit** [comment]
Thank you very much for your explanation and for your kind words Craig. 

>  Is there a reason why the weather summary you display is still displayed after you tap on “More” and then return from the weather app? I would think it should be removed once you tap on “More”. 

The idea is, that you only need the more detailed weather forecast rarely. Niagara's weather widget gives you weather forecast at a glance without loading an app or website. 

>  I tap on the weather widget I get the temperature for the next two hours and the high/low temperatures for the next two days

You can also scroll horizontally on Niagara's weather dialog by the way. It let's you see the hourly forecast for the whole day.
