### ISSUE TITLE
No Icons

### ISSUE THREAD

**Issue by kokoslocos** [8bitPit/Niagara-Issues#1213]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I absolutely love this launcher and use it to minimize my use of my phone. I would suggest an option to remove the icons in the homescreen to reduce visual clutter. 

**Describe the solution you'd like**

The option to remove the application icons on the homescreen.
Launcher settings > Look > Icons > No Icon

**Comment by 8bitPit** [comment]
Thank you for your kind words @kokoslocos. Hiding app icons has already been requested, please refer to #140

**Comment by 8bitPit** [comment]
Duplicate of #140
