### ISSUE TITLE
App crashing not opening 

### ISSUE THREAD

**Issue by sathwikrao575** [8bitPit/Niagara-Issues#1218]
Using Xiaomi and 19 alpha
How to fix without reinstalling? 
![Screenshot_2020-03-17-12-15-09-353_com miui bugreport](https://user-images.githubusercontent.com/6828692/76829382-1310f080-6849-11ea-975d-6a68cf57c7d5.jpg) 

![Screenshot_2020-03-17-12-15-13-279_com miui bugreport](https://user-images.githubusercontent.com/6828692/76829377-0f7d6980-6849-11ea-9b66-f8de07015062.jpg)

**Comment by 8bitPit** [comment]
Hi, sorry for the crash. Does the latest version of Niagara Launcher solve the issue? You can download it from here: https://github.com/8bitPit/Niagara-Issues/releases/tag/v0.20.0-alpha

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
