### ISSUE TITLE
Multiple Icon Pack Support

### ISSUE THREAD

**Issue by Shadowspear123** [8bitPit/Niagara-Issues#1219]
Currently only one icon pack can be applied at a time, one icon pack does not always cover all the apps I have installed. In some other launchers (Lawnchair comes to mind), one is able to apply multiple icon packs simultaneously which covers a broader range of apps. Sure, right now one could apply a single pack then manually change each icon individually, but that is not efficient, convenient, or fun. Having the ability to apply multiple icon packs is an elegant and quick solution as well as a nice feature.
It is:
*Simple* · Easy to configure and easy to use. It does not even require a seperate toggle, just the ability to select more than one icon pack in the select icon pack option.
*Impactful* · This an option that many would take advantage of. I've yet to meet someone who has every app icon on their phone themed with a single icon pack (aside from manually doing it).
*Universal* · It is compatible with every phone at every location.
*Independent* · It doesn’t add complexity if it’s not being used.
I love this launcher.
Thank you!

**Comment by kazimShaikh** [comment]
Great, it would be even better if we had different icons for our favorite apps and different icons for the rest of the scrollable menu.

**Comment by ARCABRO** [comment]
Which icons pack can I install in Android 10?

**Comment by kazimShaikh** [comment]
> Which icons pack can I install in Android 10?

you can install any icon pack from playstore in Android 10.

**Comment by 8bitPit** [comment]
Hi @Shadowspear123 thank you for the idea. However, I'm against a multi-icon pack selector. In my opinion that adds too much complexity to the user and it's hard to find a second icon pack that fits perfectly well to another one. What I prefer, is a way to automatically apply fallback icons to apps that are not supported by an icon pack. If the icon pack does not provide an icon for your favorite calendar app for example, chances are high that it offers an icon for dozens of other calendar apps. The challenge is to make Niagara Launcher suggest these icons as alternatives.

**Comment by Manu99it** [comment]
Yep also I support that idea. I think it doesn't add complexity at all actually, just make things faster and easier for the end user. About the difficulty to find similar icon pack to fit well that's simply not true, play store is full of practically identical icon packs
