### ISSUE TITLE
Swipe up gesture

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#122]
Here you can post some what should happen open while swiping up (on the main/favorite screen).

**Comment by jamilkarami** [comment]
Perhaps a chosen custom action depending on the app that's being swiped up on?

e.g: swiping up on WhatsApp opens a specific chat

**Comment by dojwB** [comment]
Or should take us to app drawer maybe?

**Comment by Shinra04** [comment]
Tbh, the swipe up gesture has no room in this launcher. It would conflict with the apps scroll.

**Comment by pradyw** [comment]
It can  conflict, but there is already a swipe down gesture.

**Comment by Shinra04** [comment]
Which, as you know, is a rather choppy feature.

**Comment by Shinra04** [comment]
It's because the Dev set the swipe speed to be rather high for the gesture. It can be fixed, and the swipe up can be imlemented too, take a look at thread #131 where I mention it at the end.

**Comment by bbuccianti** [comment]
Can this bring the recent apps? I think would be useful

**Comment by disacrol** [comment]
Open in background could be useful for apps with persistent notifications, e.g. swipe up from Spotify would pop media controls in notification area. Also would feel natural as if you're 'moving' the app to the top to interact with it without exiting the main screen.

**Comment by lolbinarycat** [comment]
It should just scroll into the rest of your apps. This is useful if I want to just browse my apps, aren't the apps supposed to be in one continuous list?

**Comment by Dunkaan** [comment]
as i said in my #478 thread, it would be useful to access the app drawer with a swipe up

**Comment by mare-413** [comment]
i've just started using niagara, and as im used to other launchers i instinctively try to scroll up to look at the app list, without any success. i think it would be great if the scroll up would bring the app list af if you touched on the alphabet. Make it look like a big list and matches the flow of the launcher.

**Comment by Hoomum** [comment]
Personally I think the swipe up gesture would conflict with Android Pie. I know not many people are on it, but if the launcher was widespread it could be an issue waiting to cause problems. Quite a few newer mobiles like OnePlus also use gesture navigation.

**Comment by disacrol** [comment]
@Hoomum never used gestures but aren't they usually triggered only when swiping from the edges of the screen?

**Comment by Hoomum** [comment]
No. The gesture pill is about a cm from the bottom. And the overview screen is quite responsive. I can swipe up from the space-bar of my keyboard in an app. The gestures work inside every app as well as on the Homescreen.

**Comment by Hoomum** [comment]
Also the gesture pill can be covered by the bottom of an app as well. It is a weird setup on my pixel anyway.

**Comment by lolbinarycat** [comment]
I'm on Android pie, it's simple: swipe up on navbar for overview, swipe up
on the screen to scroll/whatever.

**Comment by azixaz** [comment]
There are some apps that i use lile twice or thrice a day..but i dont want em in the favorites..maybe a tray for quick launching apps?

**Comment by colbycdev** [comment]
How about Google discover?

**Comment by angltrs** [comment]
Would like to see a setting allowing users  control over gestures. The default swipe up gesture should just let you go into your app list.

**Comment by lucassantilli** [comment]
Favorite apps and Frequently used apps should be completely separated. A swipe up/down gesture would do the job and keep the proposed minimalistic approach.

**Comment by colin-walker** [comment]
Swipe up for apps is just duplicating the existing edge swipe for me. Yes, it would act the same as a number of other launchers but isn't the point here to be different?

Personally, I have no issue with the swipe down gesture and don't have an issue with it conflicting with the app list gesture as they target different areas of the screen. Don't see why an up swipe would be any different.

**Comment by satyapr93** [comment]
Would like to access search with swipe down gesture(currently being used from notification drawer) instead of swipe up(gets triggered accidentally and doesn't feel smooth).

**Comment by 8bitPit** [comment]
@satyapr93 In my opinion swiping down to access the shade is needed for large phones, so it can be accessed easily with one hand. On my device (Essential phone - stock Android) the notification shade shows up fluently, could you please elaborate why it doesn't feel smooth on your device? 
Btw, if you want to just scroll up without opening the notification shade, I recommend to finish the scroll gesture before leaving the finger. Moreover, I guess if the notification gesture would get triggered accidentally, the search gesture wouldn't do better ;)

**Comment by satyapr93** [comment]
@8bitPit sorry I made a mistake. Swiping down for notification shade works perfectly. Search by clicking home button is the one I feel weird(out of place, no so smooth animation). and yes swiping down gesture is really useful for large phones so that is necessary of course.

I have a pixel which already has a gesture for that using fingerprint sensor(swipe down), I was hoping if I could remap swipe down gesture for search. Clicking home button for search might get obsolete after Android Q(gestures pill with no buttons), so it would be good idea to find a different gesture for search to make it future proof.

About the accidental triggers, while I am on home screen I don't want anything to happen when I touch home button which happens a lot by mistake but I would like to keep some kind of shortcut or gesture for search.

I have attached a few screenshots of iOS swipe down gesture for reference.
![download](https://user-images.githubusercontent.com/3058630/57763915-07800500-7720-11e9-9562-b896cdfc1908.png)
![ios12-iphone-x-search-social-card](https://user-images.githubusercontent.com/3058630/57763937-1070d680-7720-11e9-97d7-d4cfe377ea2b.jpg)

**Comment by colin-walker** [comment]
@satyapr93 I use gestures on the Mate 20 Pro rather than buttons so "tap home" just becomes swipe up so it won't become obsolete.

**Comment by 8bitPit** [comment]
Gotcha @satyapr93, thanks for the additional explanation. I think, the swipe up gesture could be used to open search. It would be the opposite direction of the gesture on IOS, however a swipe up to open the keyboard makes sense to me. In that way everyone could access both the notification shade and search with a swipe gesture.

**Comment by PaulBags** [comment]
Niagra, to me, is a fancy apps list. So it's very weird and unintuitive that I can't just start scrolling the list from favourites - which is exactly the same action as swipe up.

**Comment by mlipocky** [comment]
I would prefer the quick access to phone office essentials such as calls, messages, contacts, calendar when dragging homescreen from the bottom. Anything else in the launcher is perfect, the quick access to anything, so the launcher should follow the line with it.

**Comment by filikun** [comment]
I would love swipe up to simply get me directly to app search.

**Comment by 8bitPit** [comment]
Because it's harder to trigger "press home to search" button/gesture on Android 11 with gesture navigation turned on, I think it would be a good idea to also to open search when you swipe up anywhere on the screen (except from the bottom when gesture navigation is enabled because that will open the recents menu since Android 10).

**Comment by UsamaKarim** [comment]
I am surprised why it's not implemented yet. BTW it's most needed feature

**Comment by UsamaKarim** [comment]
> Because it's harder to trigger "press home to search" button/gesture on Android 11 with gesture navigation turned on, I think it would be a good idea to also to open search when you swipe up anywhere on the screen (except from the bottom when gesture navigation is enabled because that will open Androids recents menu).

It should be implemented when favourite list of apps ended and then swipe up. We have many less choices for swipe up gesture. On the both edges we have apps by alphabets. As you said, On the bottom we have gestures navigation. (Most phones have it very early like Xiaomi, Samsung, Huawei, Oppo, Vivo, some of them have it since 2 years)

**Comment by mrbekong** [comment]
> Because it's harder to trigger "press home to search" button/gesture on Android 11 with gesture navigation turned on, I think it would be a good idea to also to open search when you swipe up anywhere on the screen (except from the bottom when gesture navigation is enabled because that will open Androids recents menu).

I use gesture navigation on oneplus 7 pro and swiping from the bottom opens sesame search easily...a quick swipe not a long hold enough to trigger the recents it's working out great so far.

**Comment by UsamaKarim** [comment]
> > Because it's harder to trigger "press home to search" button/gesture on Android 11 with gesture navigation turned on, I think it would be a good idea to also to open search when you swipe up anywhere on the screen (except from the bottom when gesture navigation is enabled because that will open Androids recents menu).
> 
> I use gesture navigation on oneplus 7 pro and swiping from the bottom opens sesame search easily...a quick swipe not a long hold enough to trigger the recents it's working out great so far.

Is it implemented? Because I am not able to use it. I am using MI 9T and it has fullscreen gestures. I am able to open sesame as you said 10 times in 100, But I am not able to figure out that how can I open it at once

**Comment by mrbekong** [comment]
When I am the home screen, I can swipe up as if to "go home" which triggers sesame search. Swipe up to search works only on home screen.

**Comment by UsamaKarim** [comment]
Sadly it's not working for me. May be it's interfering with system's fullscreen gestures on MIUI

**Comment by DavidMulder0** [comment]
@UsamaKarim That's exactly correct, the thing @mrbekong is describing is the "double home" "gesture". Xiaomi has decided that going home from your home screen probably isn't intended, and thus disables that gesture to prevent accidental triggering.

**Comment by UsamaKarim** [comment]
> @UsamaKarim That's exactly correct, the thing @mrbekong is describing is the "double home" "gesture". Xiaomi has decided that going home from your home screen probably isn't intended, and thus disables that gesture to prevent accidental triggering.

Double swipe gesture only works when an app is using full screen. Like YouTube in landscape mode or games in landscape mode. But still I tried the way you said. It still doesn't work the way with convenience. In my findings, there has to be a specific area from where if I swipe up, only then the search bar opens either double swipe is enabled or not. There must be another implementation of openings search bar like when favorite list of app ended or I also noticed difference in swipe down feature. If I swipe down fast, only then the notification bar appears but if I swipe down slow then the favorite list scroll. This implementation can also be useful in openings search bar. If we swipe up fast then the search bar opens but if we swipe up slow then favorite list scroll.

![IMG_20201121_072422](https://user-images.githubusercontent.com/64292174/99865300-9b127b80-2bca-11eb-91e8-121df4b87dc1.jpg)

**Comment by 8bitPit** [comment]
Thank you so much for all your input, guys! We have decided to add a swipe-up-to-search-gesture; you can try it for yourself in our latest alpha, v0.34.0 🎈

**Comment by Nxt3** [comment]
How do you get into the Alpha?

**Comment by 8bitPit** [comment]
You can download Early Access APKS here: https://github.com/8bitPit/Niagara-Issues/releases
