### ISSUE TITLE
Home button search and swipe action

### ISSUE THREAD

**Issue by TheC92** [8bitPit/Niagara-Issues#1220]
**Describe the bug**
When the home button search is executed, the swipe action window does not disappear.

So, the search contents are hidden and not visible.

**To Reproduce**
1. Swipe action
2. Home button

**Smartphone**
 - Device: Nokia 7 plus
 - Android version: Android 10

**Screenshots**
![IMG_bs65cw](https://user-images.githubusercontent.com/6590166/76994849-55921480-6992-11ea-942c-ca4a898d6020.gif)

**Comment by 8bitPit** [comment]
Thanks for reporting :)

**Comment by Martin5001** [comment]
Also when not in the homescreen, but the apps list, swipe action does not stay, but search does not show either, instead the screen just blinks for a moment.

**Comment by 8bitPit** [comment]
Thanks @Martin5001

**Comment by 8bitPit** [comment]
Fixed in v.0.26.0
