### ISSUE TITLE
Show bluetooth device battery level

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1221]
It would be great to be able to see battery level of my bluetooth headphones on the homescreen.

As the headphones provide this information to the system, maybe it could be possible to get that and display it right on the homescreen?
**EDIT: it should be possible using 
android.bluetooth.device.action.BATTERY_LEVEL_CHANGED**

I think this would be really useful for everyone using bluetooth headphones or speakers. And wouldn't need any additional toggle in the Settings.
(In case there would be more than one device connected, only the one with the lowest battery remaining would be shown on the homescreen to avoid clutter.)

**Comment by 8bitPit** [comment]
Cool idea :)

**Comment by fbald82** [comment]
Spero arrivi presto questa novità 🤞🏻

**Comment by 8bitPit** [comment]
Hi again @Martin5001. I decided to not add this feature, my apologies. The API is only pseudo-public and not intended to be used by other apps (see the hide tag in [Android's source code](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/bluetooth/BluetoothDevice.java)). Moreover, that option has low priority; I hope that's understandable.
