### ISSUE TITLE
Home page is rendered behind search app

### ISSUE THREAD

**Issue by awnumar** [8bitPit/Niagara-Issues#1224]
I have the swipe up to Google search enabled. When I trigger the feature and then slowly drag up from the bottom of the page to access the open apps drawer, the home page is rendered behind the app.

I have attached a screenshot.

![Screenshot](https://i.ibb.co/hCZmWXV/i-Markup-20200320-175749.jpg)

**Comment by 8bitPit** [comment]
Yes, that doesn't look great, but unfortunately that's not in my hands. Everything related to Android's recents screen (including gesture navigation) is controlled by your system (or by a system app to be more precise). Sorry.
