### ISSUE TITLE
Shifting of icons to prevent burn-in on AMOLED

### ISSUE THREAD

**Issue by T0nySt0ne** [8bitPit/Niagara-Issues#1227]
Would it be possible to have an option for the icons etc shift slightly at random to prevent burn in on AMOLED screens? (perhaps just horizontally)
Like the behavior of always on display.

**Comment by 8bitPit** [comment]
Hi, thanks for your writing us. I don think the icons will cause a burn in, every other launcher doesn't move icons either. However, if you're still concerned, you can occasionally go to Niagara's edit mode (long press on a favorite and tap the button at the bottom), and tap on 'move all items' to offset them a bit. Hope this helps
