### ISSUE TITLE
Different visual feedback on alphabet strip

### ISSUE THREAD

**Issue by oh1apps** [8bitPit/Niagara-Issues#1228]
I understand that wave is a hallmark of this launcher, but for my liking it is too intrusive. Maybe you can add option to control it's curve, or make other "themes"- like coloring active letter or just making it bigger etc

**Comment by ZephyrMathi** [comment]
Yes that would be some quality of life change

I wouldn't suggest removing the wave , but adding Colour to the active Alphabet and making it bigger and the letter far away from the selected letter to be smaller in comparison . would be an welcome quality of life change .

**Comment by 8bitPit** [comment]
I'm really against making it customizable, because it's one of Niagara Launcher's signature animations and I believe this goes against the first rule listed here: https://niagaralauncher.helpscoutdocs.com/article/8-niagaras-design-principles
