### ISSUE TITLE
Missing margins in custom icon search 

### ISSUE THREAD

**Issue by kazimShaikh** [8bitPit/Niagara-Issues#1229]
**Describe the bug**
When I change the icon from a selected icon pack, the first line of icons are hidden under the search bar. 

**To Reproduce**
1. Hold an app. 
2. Click on 'Change Icon'. 
3. Select any icon pack. 
4. Search for an Icon and there it is. The first line of icons are hidden behind search bar. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9t pro/ Redmi k20 pro
 - Android version: Android 10 (Q) 

**Screenshots**
![Screenshot_2020-03-23-12-19-19-324_bitpit launcher](https://user-images.githubusercontent.com/40717328/77289958-17358600-6d01-11ea-82b4-6b0674ca91a4.jpg)

**Comment by jbmorch** [comment]
I came here to report the same bug. I'm using App version 0.21.0-alpha on a Pixel 2 phone running Android 10 patch level March 5, 2020. Tried to change an icon using the Lox icon pack. Maybe this has something to do with the new "immersive" top to bottom app drawer feature (which I like)?

**Comment by 8bitPit** [comment]
Thanks for reporting.
