### ISSUE TITLE
Keyboard stays open for websites added to home screen

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1230]
**Describe the bug**
Websites can now be added to the list of applications with chrome and brave. Sadly the keyboard stays open and blocks the view. Clicking the lower left button to hide the keyboard will close the browser. This behavior is reproducible for every website added this way.

**To Reproduce**
1. Add website to home screen
2. Search for the name
3. Tap on the entry / result (the issue will not occur when hitting enter/search on the keyboard)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - Android version: 10
- Niagara: 0.20.1

**Screenshots**
Add to home screen
![Screenshot_20200326-002412](https://user-images.githubusercontent.com/13085980/77595149-afe22680-6ef8-11ea-9654-836d53169800.png)

Opening it
![Screenshot_20200326-002144](https://user-images.githubusercontent.com/13085980/77595145-aeb0f980-6ef8-11ea-964c-9d27190c8fc9.png)

Keyboard still open. Lower left button will close the website now.
![Screenshot_20200326-002151](https://user-images.githubusercontent.com/13085980/77595148-afe22680-6ef8-11ea-9368-b34843548118.png)

**Comment by 8bitPit** [comment]
Thank you very much for your report @andys8.

**Comment by 8bitPit** [comment]
Can you also reproduce that with Chrome? I opened a shortcut from search and the keyboard closes.

**Comment by andys8** [comment]
It looks like I can't reproduce it. But I also switches my phone. Were there changes in Niagara between versions 0.20.1 and 0.27.0 that could have influence the behavior and could have solved it?

**Comment by 8bitPit** [comment]
Yeah, there was a change in 0.27 that could have changed some things. I'll close this issue for now, but you can reopen it anytime if you run into it :)
