### ISSUE TITLE
Apps with notifications in favorites

### ISSUE THREAD

**Issue by tkarika** [8bitPit/Niagara-Issues#1231]
It would be nice to have an option for adding apps that have notifications to the favorites, like the mostly used ones.
The reason is simple: I love the way Niagara shows and handles the notifications. :)

**Comment by 8bitPit** [comment]
Thanks, I believe your request is similar to this one, right? https://github.com/8bitPit/Niagara-Issues/issues/152

**Comment by tkarika** [comment]
Indeed. Sorry for the duplicated post. Thanks.

**Comment by 8bitPit** [comment]
No problem :)
