### ISSUE TITLE
Recommendation of Uninstaller app

### ISSUE THREAD

**Issue by Frank-Mayer** [8bitPit/Niagara-Issues#1232]
I have uninstalled WhatsApp but it's recommended to the favorites list.
![Screenshot_20200326_113340_bitpit launcher](https://user-images.githubusercontent.com/53651857/77637268-adfa8080-6f55-11ea-828a-94f20f188926.jpg)

**Comment by y0c4** [comment]
I can also see apps I have uninstalled/deactivated such as gmail. Not a huge issue as I just hide the apps.

speaking of, anyone knows if it is possible to entirely remove gmail from android?

Thanks
Christian

**Comment by Martin5001** [comment]
> speaking of, anyone knows if it is possible to entirely remove gmail from android?

Normally system apps cannot be uninstalled, but it can be done via adb (android debug bridge) console commands.

**Comment by 8bitPit** [comment]
Thanks for the bug report, working on it :)

**Comment by 8bitPit** [comment]
Will be fixed in v0.26

**Comment by 8bitPit** [comment]
Fixed in v.0.26.0
