### ISSUE TITLE
Google Podcasts controls (10s back/30s ahead instead of previous/next track)

### ISSUE THREAD

**Issue by curio77** [8bitPit/Niagara-Issues#1233]
**Is your feature request related to a problem? Please describe.**
For Google Podcasts, Niagara shows the same controls as for any media player, and they work the same way (switch to previous/next track).  However, the Podcasts app's own control panel in the status dropdown (and in-app) has the backwards and forwards controls replaced with 10s rewind and 30s jump-ahead.  With podcasts, this makes more sense than the media controls that switch tracks (because you rarely skip podcasts like you skip songs).

**Describe the solution you'd like**
It'd be great if Niagara could adapt the widget display for the Google Podcasts app in the manner of the app's own controls.  I cannot judge the feasability of this in terms of whether there's an API for these modified controls.  Also, I don't know how other podcasts apps' controls are set up and whether this could apply to them as well or whether a special handling of a particular app (such as Google Podcasts) would be appropriate to begin with.

**Comment by 8bitPit** [comment]
That's a cool idea @curio77. I'm not sure if that's feasible, but let's try it out! Hope it's understandable that this is a low priority issue though.

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.

**Comment by tasmo** [comment]
It is an issue for all Podcast client apps. I also would very much appreciate this.

This is a real stopper for me to use the media widget – and so to buy the Pro version. It is unusable with podcast as most times users want to skip a certain time forward instead of jumping two hours forward to the next full episode.

**Comment by 8bitPit** [comment]
I agree that this feature would be neat indeed. I'll reopen the ticket but keep it at low priority.

**Comment by Zdmb91** [comment]
Agreed, ran I to this today.  Frustrating to have to open app to fast forward through commercials present on most podcasts.

**Comment by UrsKR** [comment]
With the recent end-of-life announcement for Google Podcasts, this issue no longer seems worth development effort if implemented for that player alone.
Otherwise, I would welcome it!

**Comment by 8bitPit** [comment]
Another Google service bites the dust 🫡 Thank you very much for the update @UrsKR.
@Maxr1998 recently checked ou several podcast apps and noticed that most of them (e.g., Spotify) rebinds the next and previous track buttons to x seconds ahead/back actions, so I believe we can leave it as it is. If you have any objections, please let me know.
