### ISSUE TITLE
Live Wallpaper is turning Google button into PINK

### ISSUE THREAD

**Issue by Harleybee** [8bitPit/Niagara-Issues#1234]
Everytime Im using a live wallpaper the searchbutton on the right bottom corner is becoming PINK. 

 - Device: Samsung Galaxy S10
 - Android version: 10

![Screenshot_20200329-003226_Niagara Launcher](https://user-images.githubusercontent.com/62818335/77836257-d9978980-7154-11ea-82d2-41913a917663.jpg)

**Comment by cucurucu666** [comment]
> Everytime Im using a live wallpaper the searchbutton on the right bottom corner is becoming PINK.
> 
> * Device: Samsung Galaxy S10
> * Android version: 10
> 
> ![Screenshot_20200329-003226_Niagara Launcher](https://user-images.githubusercontent.com/62818335/77836257-d9978980-7154-11ea-82d2-41913a917663.jpg)

I think it "takes" the color from the default theme wallpaper (that's mostly pink )

**Comment by Harleybee** [comment]
Thanks! I tried to change the theme to a Black an White. With or without Dark Mode. It stays pink 😅

**Comment by 8bitPit** [comment]
Have you tried another live wallpaper app? I suspect that the app you're using doesn't make use of this API: https://developer.android.com/about/versions/oreo/android-8.1#wallpaper, that tells the launcher which color to use. If you want to, you can forward this to the dev of the live wallpaper app.

**Comment by Harleybee** [comment]
Thank you very much. But I tried various apps with the same result. I think
the main problem is the standard wallpaper from Samsung. But it isn't
possible to change this. Do you have an idea?

Greetz Bigi

Peter Huber <notifications@github.com> schrieb am So., 26. Apr. 2020, 00:05:

**Comment by 8bitPit** [comment]
@Harleybee If the app doesn't support the new API I wrote about earlier, Niagara Launcher uses the most prominent color from the live wallpaper preview image. Is that pink by any chance?
