### ISSUE TITLE
Get custom app screen for workouts/gym 

### ISSUE THREAD

**Issue by y0c4** [8bitPit/Niagara-Issues#1235]
**Is your feature request related to a problem? 
As it is currently the main screen is full of favourite apps. This is great, and works for the most part, however there are certain typical situations where you would want the launcher to display apps that are relevant to you in just that situation. For example those typical situations might be 
1) gym/exercise 
2) On holidays / exploration 
3) work 

I think of those three situations I'd think that getting circumstantial lists of apps would be great. This also pairs up nicely to potentially having the favourites list replaced by notifications from your favourite apps instead, as this will create a cleaner ui and at the same time present more relevant information to the user. 

**Describe the solution you'd like**
The solution could be to tie the circumstantial apps into calendar events as a first step, as using geoloc is both more battery draining and might not work on all devices. Alternatively, using swipes/buttons on the home screen to activate a circumstance might work as well? 

Looking forward to some feedback and please continue the development of this gem of a launcher!

**Comment by 8bitPit** [comment]
Hi, I believe folders could help you there: https://niagaralauncher.helpscoutdocs.com/article/38-folders ( & https://github.com/8bitPit/Niagara-Issues/issues/1209). You can also make Niagara Launcher more contextual with Tasker in the future: https://github.com/8bitPit/Niagara-Issues/issues/786

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
