### ISSUE TITLE
Swipe on an app reveals widget

### ISSUE THREAD

**Issue by shmykelsa** [8bitPit/Niagara-Issues#1237]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Many apps on the phone don't push (many) notifications but have one or multiple widgets available. Since the swipe to the left of an item will swipe away the notification (if present), it would be a nice add to let the user have a widget on the swipe to the left action.

I imagine this feature to be only for Pro users. 

The concept could re-use things already into Niagara. The opening effect same as the quick actions, the same background, the same edit button to let the user pick the widget, and also the widget should not be of that app only, but could be picked from all available widgets. 

The feature should be user-lockable (if a widget is added, then it will persist, but if a widget is not added the swipe gesture will not open up the edit widget popup. 

IF a notification is present for that app, then there are two possibilities:

-Either the notification will override the widget thing (not ideal IMHO)
-The swipe to the left gesture will reveal two options: fading from the right, the first one to appear is to reveal the widget. A short swipe will reveal it. Continuing the swipe, from the right will be fade-appear the ignore notification option that will be taken if the swipe is longer.

**Comment by Rod911** [comment]
Thanks for the request, this has already been requested, please see #1165.
