### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by Martinligabue** [8bitPit/Niagara-Issues#1238]
I think there should be an option to ask for root access, it would be helpful to uninstall bloatware preinstalled, but probably could helpl also with other things, I don't know how much can a rooted device do, but sure it's more free

**Comment by 8bitPit** [comment]
Hi @Martinligabue. I think there are already other apps that let you uninstall rooted apps (e.g. Titanium Backup). For the sake of simplicity, Niagara Launcher on the other hand should work the same on every phone - whether rooted or not 😉 Hope this helps.
