### ISSUE TITLE
How to handle shuttering of Dark Sky API?

### ISSUE THREAD

**Issue by the-eric-swanson** [8bitPit/Niagara-Issues#1239]
**Is your feature request related to a problem? Please describe.**

Apple bought Dark Sky and will be shutting down Android version and API: https://www.theverge.com/2020/3/31/21201666/apple-acquires-weather-app-dark-sky-shut-down-android-wear-os-ios

**Describe the solution you'd like**

A different weather API (Open Weather?)

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by profwyattb** [comment]
Please, please have a simple toggle for the "Feels Like" temperature. It's far more important than the actual temperature.

**Comment by 8bitPit** [comment]
Yes, I'm planning to use a different API. Here's yesterday's post from Niagara's News Channel:

>Dark Sky, Niagara Launcher Pro’s weather provider, just announced that they were acquired by Apple ([source](https://blog.darksky.net/)).
They’re shutting down their Android app soon, but they’re committing on keeping the API (which we’re using) available until end of 2021. Before that, we’ll switch to another weather provider (we can’t say which one yet). That means, there will be no drastic changes, you can still enjoy Niagara Launcher’s minimalist weather widget beyond 2021. Have a good one and stay safe, 
Peter

**Comment by 8bitPit** [comment]
Hi @profwyattb. Sorry, currently I'm not planning to add further customization features to keep Niagara simple. However, I might add this at some point.
