### ISSUE TITLE
Hitting home button during widget editing mode should always make go back to non-editing mode

### ISSUE THREAD

**Issue by shmykelsa** [8bitPit/Niagara-Issues#1240]
**Describe the bug**
When long pressing on the widget, and then going into resize mode, the two scrollable guides will appear to make the widget resize, but if the option to activate search with home button is activated, they will stay on the screen and launcher would still go on search

**To Reproduce**
0. Activate option to search on home button press
1. Long press widget
2. Click on resize
3. Hit home

![image](https://user-images.githubusercontent.com/9965637/78500562-7d85c400-7757-11ea-8ee7-e1ec1e12e755.png)

That's what it looks like

**Smartphone (please complete the following information):**
 - Device: Oneplus 6T
 - Android version: 10

**Comment by 8bitPit** [comment]
Thanks for the report. This will be soon be fixed, because edit mode will be removed in the near future.

**Comment by 8bitPit** [comment]
Edit mode has been removed in v0.29
