### ISSUE TITLE
Media Player artwork not working for Qobuz Music.

### ISSUE THREAD

**Issue by shakiehyenaboy** [8bitPit/Niagara-Issues#1241]
Hi Peter,
  Just letting you know that for some reason the Qobuz album artwork doesn't show up in the media player. Every other service seems to work.

Thanks, Bill.
Keep up the great work and stay safe!

![Screenshot_20200402-114631](https://user-images.githubusercontent.com/59343603/78503210-34bc1400-7733-11ea-9e02-440c743e373e.png)

**Comment by 8bitPit** [comment]
Hi Bill, sorry for my late response. Unfortunately that is very likely caused by Qobuz, please check out https://niagaralauncher.helpscoutdocs.com/article/11-media-player-widget-issues for more information.
