### ISSUE TITLE
Homescreen list does not stay where it's moved

### ISSUE THREAD

**Issue by edisso10018** [8bitPit/Niagara-Issues#1243]
If I move the list on the homescreen via the edit option the list moves to its default position after tapping on the checkmark button to acknowledge the change. Tapping anywhere else before tapping on the checkmark has no effect regarding the bug.

1. Go to 'Edit mode'
2. Tap on 'Gesamt Liste verschieben and move the list all the way to the top'
3. Tap on checkmark button
4. See error: The list moves down to its default position again.

 - Device: Pixel 4 XL
 - Android version: 10 latest patch

**Comment by 8bitPit** [comment]
Thank you very much for reporting. Unfortunately, I can't reproduce the issue, it keeps the changes when I tap on the checkmark button. Does the issue occur every time on your device?

**Comment by edisso10018** [comment]
Yes, it does it everytime. But it's not really an issue for me so I will close this issue.
