### ISSUE TITLE
Alphabet drag limit

### ISSUE THREAD

**Issue by deuskopo** [8bitPit/Niagara-Issues#1244]
I have noticed that when dragging the alphabet to search for apps I can drag it all the way to the left side of my screen. There should be a limit on how far I can drag the alphabet (maybe one-third of the screen) and add a functionality like when dragging past the limit, the launcher goes back to its "favorites" page. Like a another shortcut to the favorites, instead of dragging all the way to the top

**Comment by Martin5001** [comment]
Good idea. I would say the limit should be closer to 2/3 on phones with screen size somewhere around 5,5" and 1/3 for bigger screens. This way you wouldn't accidentally activate the gesture on smaller phones and still would be able to reach comfortably on bigger ones.

**Comment by deuskopo** [comment]
> 
> 
> Good idea. I would say the limit should be closer to 2/3 on phones with screen size somewhere around 5,5" and 1/3 for bigger screens. This way you wouldn't accidentally activate the gesture on smaller phones and still would be able to reach comfortably on bigger ones.

You might be correct. I agree that the _limit_ depends on screen size.

**Comment by kazimShaikh** [comment]
Good one. ☑️

**Comment by ZephyrMathi** [comment]
But this launcher is for both Right handed and Left handed users if this feature is introduced it would be dificult for left handed users .

**Comment by Martin5001** [comment]
> But this launcher is for both Right handed and Left handed users if this feature is introduced it would be dificult for left handed users .

Good point.
Maybe a simple left/right handed toggle could be used to move the alphabet accordingly?
(Alphabet has it's own category in settings already anyway so it wouldn't be much of a problem to add the left/right handed toggle there.)

**Comment by ZephyrMathi** [comment]
> But this launcher is for both Right handed and Left handed users if this feature is introduced it would be dificult for left handed users .
> 
> Good point.
> Maybe a simple left/right handed toggle could be used to move the alphabet accordingly?
> (Alphabet has it's own category in settings already anyway so it wouldn't be much of a problem to add the left/right handed toggle there.)

Well I am a Right handed user Myself but I use my phone with my left hand when I am using computer , Driving , while in classes and While Eating as Right hand is occupied , Which is more Time than Me Dedicatedly use my Phone . Both Hands Usability I one of my favorite features and the one I use one a regular basis . Which , I cannot say everyone uses their phones regularly with the other hand but at times I am sure everyone uses their phone with the other hand unconsciously .

**Comment by y0c4** [comment]
Would it be possible to set the alignment based on which third of the screen your finger touches first? Ie, If the first trough is on the left third of the screen the alphabet will appear in the left side, and similarly for the right third. Is this feasible?

Many thanks,
Christian

**Comment by ZephyrMathi** [comment]
I don't know the technical complications in implementing the shortcut this way . But if the dev want's to implement this feature that would be an possible option , Without harming the both hands usability .



> Would it be possible to set the alignment based on which third of the screen your finger touches first? Ie, If the first trough is on the left third of the screen the alphabet will appear in the left side, and similarly for the right third. Is this feasible? Many thanks, Christian
> […](#)
> On 12 Apr 2020, 14:39 +0100, ZephyrMathi ***@***.***>, wrote: > But this launcher is for both Right handed and Left handed users if this feature is introduced it would be dificult for left handed users . > Good point. > Maybe a simple left/right handed toggle could be used to move the alphabet accordingly? > (Alphabet has it's own category in settings already anyway so it wouldn't be much of a problem to add the left/right handed toggle there.) Well I am a Right handed user Myself but I use my phone with my left hand when I am using computer , Driving , while in classes and While Eating as Right hand is occupied , Which is more Time than Me Dedicatedly use my Phone . Both Hands Usability I one of my favorite features and the one I use one a regular basis . Which , I cannot say everyone uses their phones regularly with the other hand but at times I am sure everyone uses their phone with the other hand unconsciously . — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Martin5001** [comment]
> Would it be possible to set the alignment based on which third of the screen your finger touches first? Ie, If the first trough is on the left third of the screen the alphabet will appear in the left side, and similarly for the right third. Is this feasible? Many thanks, Christian

Well, I am not a dev (@8bitPit what do you think?), but this seems quite complicated to do from a visual design perspective. Because you would have to move the alphabet from one side of the screen to the other across the whole screen with the apps list – like if the alphabet is on the right and you touch on the left then it would have to move across the screen. I'm not sure how this could be animated.

**Comment by 8bitPit** [comment]
#162 is about a similar concept, but the request is about opening apps when you "scroll" to the left. If that's okay for you I'll merge this issue with 162.

**Comment by 8bitPit** [comment]
Merged with #162

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
