### ISSUE TITLE
Niagara Pro doesn't work after factory reset

### ISSUE THREAD

**Issue by enderstripe** [8bitPit/Niagara-Issues#1245]
**Describe the bug**
Niagara Pro Annual won't work when I factory reset my phone. 

**To Reproduce**
1. I factory reset my phone
2. Logged in same account that I used to buy Niagara Pro
3. Google Play Subscription said I brought pro.
4. When I try to buy it again with the button at the bottom, Niagara Launcher said I already brought it.

**Smartphone**
 - Device: Moto Z3
 - Android version: Android 9

**Screenshots**
![Screenshot_20200409-113121](https://user-images.githubusercontent.com/63413877/78913485-13229b80-7a57-11ea-9910-d1c049179f95.png)

**Comment by 8bitPit** [comment]
Thank you for the bug report, I'm very sorry for the issue. I found the bug today and will ship a fix in 0.24. Right now, you can only restore the subscription by clearing Niagara Launchers data.

**Comment by 8bitPit** [comment]
Please check out the following article for more information: https://niagaralauncher.helpscoutdocs.com/article/29-lost-access-to-niagara-pro?preview=5e92ef5c04286364bc9839bf
