### ISSUE TITLE
Columns placement of no text favorites icons. 

### ISSUE THREAD

**Issue by celiososa** [8bitPit/Niagara-Issues#1247]
I like to display favorite apps without text, minimize home screen layout. It would be useful to either move favorite apps around a designated area to create a stack of icons or visual design and/or allow multiple rows of icons. * = Icon in example below.
____________
* * * *
* * * *
   *    *
*    *
   *   *
_____________

**Comment by 8bitPit** [comment]
Thanks for your request. The list is Niagara Launcher's core element. We also had a little discussion about this a while ago: https://github.com/8bitPit/Niagara-Issues/issues/81 Hope that's understandable.

**Comment by celiososa** [comment]
Understand, how about the size of the icons. Can that be smaller but
increase if notification is received?

Sent via 5G

**Comment by 8bitPit** [comment]
@celiososa we're probably not going to add dynamic icon sizes, but v0.25 introduced a smaller icon size option. You can download it next week on Google Play :)
