### ISSUE TITLE
Home Page Scrolling Selection Text Customization

### ISSUE THREAD

**Issue by ZephyrMathi** [8bitPit/Niagara-Issues#1248]
This Feature Request is just quality of life changes

Problem :-

There are some places in the launcher where the text or floating windows are highlighted (Eg :- while accessing shortcuts , while selecting an alphabet  in scrolling selection section ) the highlight colour is based on the wallpaper this works great in many cases but in my case as I use an Black wallpaper the highlights are in Black which is not appealing .  The scrolling selection alphabets stand a lot due to the very dark nature of the background .

Possible solution :- 

-  Custom highlight colour .

- Custom highlight colour for scroll selection section (optional) would be great .

- Custom Font / Size for the scrolling selection section .

- Fade out the far away alphabets form the selected alphabet (or) shrink the far away alphabets .

- Option to Highlight alphabets with a custom colour to indicate notifications while scrolling in the scrolling selection section .

> These are just some Quality of Life changes not any Useful Feature 

![Screenshot_20200412-170351](https://user-images.githubusercontent.com/63517142/79070418-51d48200-7cf3-11ea-9c83-01fbc06138e6.jpg)
![Screenshot_20200412-191444](https://user-images.githubusercontent.com/63517142/79070419-55680900-7cf3-11ea-981a-365a68fb0094.jpg)
![Screenshot_20200412-191503](https://user-images.githubusercontent.com/63517142/79070450-94965a00-7cf3-11ea-9728-bc2b85af8ef1.jpg)

**Comment by Martin5001** [comment]
I personally wouldn't change the animations, as it would add more delay. What I like about how it is now is it being snappy and fast.

**Comment by y0c4** [comment]
I agree. Keep it simple and snappy.

Many thanks,
Christian

**Comment by ZephyrMathi** [comment]
Yes i too agree to that point .
animations in that part wont work well .
Thanks

**Comment by 8bitPit** [comment]
Change the Launcher's accent color might be possible in the future: https://github.com/8bitPit/Niagara-Issues/issues/303
