### ISSUE TITLE
Mark new apps

### ISSUE THREAD

**Issue by jonassch2903** [8bitPit/Niagara-Issues#1249]
I want a feature that marks new apps for me. To find new apps faster.You can solve this with a dot behind the app, for example.

**Comment by ZephyrMathi** [comment]
Yes I too want this feature as the Play Store has removed the installed notification and the nature of this launched I sometimes forget what app i installed it would be easy to find them if the launcher marks them or create a new section in for them .

Thank You


> I want a feature that marks new apps for me. To find new apps faster.You can solve this with a dot behind the app, for example.

**Comment by Rod911** [comment]
This may not be as intuitive as you wanted, but recently installed apps do show up in the Niagara search screen.

**Comment by ZephyrMathi** [comment]
> This may not be as intuitive as you wanted, but recently installed apps do show up in the Niagara search screen.
I have never used the search in this launcher so I didn't know this existed , after seeing that I think the feature @jonassch2903 has requested is already in the Launcher .

**Comment by jonassch2903** [comment]
But I'm referring to the app list, not the search function

**Comment by 8bitPit** [comment]
@jonassch2903 Niagara's search will be better integrated in the future. For example, it will be more accessible and a tip will appear, that you can find newly installed apps from there.  But we don't have plans to show an indicator in the app list right now, sorry.
