### ISSUE TITLE
Extreme battery saving mode opens search

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1251]
When I turn on extreme power saving on my Galaxy J7, it kills all non essential apps, including launchers, which is fine, but when I turn it back to normal, Niagara starts up but always opens on search screen instead of home. Is there any way to fix this?

**Comment by 8bitPit** [comment]
I believe that has something to do with "press home to search" being enabled. It seems the home button event is fired by the system after disabling power safer mode. Unfortunately there's now way to differentiate if the event was initiated by the system or by the user.
