### ISSUE TITLE
Custom font color

### ISSUE THREAD

**Issue by athelas64** [8bitPit/Niagara-Issues#1253]
At the moment, the text color can be set only to light, dark or based on wallpaper (which gives me black text on black backround in case of animated wallpaper). I would like to have the possibility to choose my own preferred color for the apps list with a simple color-picker (same color for clock and apps is OK).

Thank you!

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible. 
Yes
*Impactful* · Either appealing for many or necessary for some.
Maybe :-)
*Universal* · Has to work everywhere: in every country, on all phones.
Yes
*Independent* · Doesn’t add complexity if it’s not being used.
Yes

**Comment by 8bitPit** [comment]
Hey @athelas64, I'm sorry but this feature will not be released soon, see https://github.com/8bitPit/Niagara-Issues/issues/20

**Comment by 8bitPit** [comment]
Duplicate of #20
