### ISSUE TITLE
Replace ‘google’ button with ‘camera’ button

### ISSUE THREAD

**Issue by y0c4** [8bitPit/Niagara-Issues#1256]
**Is your feature request related to a problem? Please describe.**
As it is currently there are certain features which are present and heavily used by most users, such as the camera. Within the scope of this change I’d like a faster way to access a core feature of any phone - the camera. 

**Describe the solution you'd like**
I would like to replace the Google search button in the bottom right corner with a shortcut to the camera. Alternatively a short-press could launch google search and a long press could launch the camera. Whereas the google search is also used frequently I’d suggest merging the google search with the app search if possible (but that’s a different feature request - I get that).

**Comment by ZephyrMathi** [comment]
Yes , this feature would make sense as I use camera and google often but camera is not as high priority as some other apps in my home page . but i've been using camera from lock screen for a while so this wouldn't be a compulsory feature to have for me , but having a new shortcut will be nice .

**Comment by Rod911** [comment]
Would implementing #300 be a better solution for your request?

**Comment by y0c4** [comment]
I would prefer to have a dedicated shortcut to the camera. Right now I have added a shortcut to the camera app however I would prefer it to be more impactful, so it is easier to tap on when you need the camera. Allowing perhaps a user to choose between camera and google in the widget in the lower right corner might work? 

As to the searching, In my ideal scenario half a swipe up (which now searches local apps) would search Google, and local files, A bit like how the search function work is Mac OS(cmd + space).

**Comment by y0c4** [comment]
Plus, of course searching local apps :)

**Comment by 8bitPit** [comment]
I'll merge this ticket with the one @Rod911 linked. The button might be fully costumizable in the future. By the way, we'll improve Niagara's app search in the future by integrating Sesame: https://niagaralauncher.helpscoutdocs.com/article/20-sesame-integration
We'll probably also make it easier accessible.

**Comment by 8bitPit** [comment]
Merged with #300
