### ISSUE TITLE
Smart folders done in a smarter way

### ISSUE THREAD

**Issue by y0c4** [8bitPit/Niagara-Issues#1257]
**Is your feature request related to a problem? Please describe.**
Currently Niagara does a great job keeping things simple. The intention of this feature request is to push the simplicity further by thinking of apps as few core apps that are enhanced by a cluster of ‘support’ apps. The idea is that you can keep your home screen simple and uncluttered, and the smart folders only branches out when they are relevant to the user context. This is actually inspired by how music/spotify apps currently work within the launcher and I think you are onto something there. I will suggest a couple of potential solutions in the next section. 

**Describe the solution you'd like**
The camera. 
Solution 1: Normal press launches app; long press opens list of support apps (ie, in this example it could be the likes of Instagram, Google Photos etc). This would allow the user to just keep the camera icon in the front screen and at the same time the user has a short cut to all of the apps he/she uses as part of the act of taking photos/videos.

Solution 2: Normal press launches app. User closes down the app again. This prompts Niagara to show a list of support apps where the normal favourites list is. selecting home again will return the user to the normal favourites list.

Solution 3 (Advanced/Might not be feasible): Use user behaviour data to build list of clusters. Ie, by recording the most used apps and then building the list of support clusters depending on the apps the user opens within a certain amount of time after using a ‘core’ app. 

With ‘core’ app I mean one of the apps that the user uses most frequently. For most people that would probably be Mail, Messages, Camera, Maps, Calls.

**Comment by ZephyrMathi** [comment]
Dude this feature already exists in the launcher .
swipe the app in the home screen (it will open the shortcuts) , 
there you can customize it by tapping the pencil symbol .
select the apps you want there .
That's It .


> Is your feature request related to a problem? Please describe.
> Currently Niagara does a great job keeping things simple. The intention of this feature request is to push the simplicity further by thinking of apps as few core apps that are enhanced by a cluster of ‘support’ apps. The idea is that you can keep your home screen simple and uncluttered, and the smart folders only branches out when they are relevant to the user context. This is actually inspired by how music/spotify apps currently work within the launcher and I think you are onto something there. I will suggest a couple of potential solutions in the next section.
> Describe the solution you'd like
> The camera.
> Solution 1: Normal press launches app; long press opens list of support apps (ie, in this example it could be the likes of Instagram, Google Photos etc). This would allow the user to just keep the camera icon in the front screen and at the same time the user has a short cut to all of the apps he/she uses as part of the act of taking photos/videos.
> Solution 2: Normal press launches app. User closes down the app again. This prompts Niagara to show a list of support apps where the normal favourites list is. selecting home again will return the user to the normal favourites list.
> Solution 3 (Advanced/Might not be feasible): Use user behaviour data to build list of clusters. Ie, by recording the most used apps and then building the list of support clusters depending on the apps the user opens within a certain amount of time after using a ‘core’ app.
> With ‘core’ app I mean one of the apps that the user uses most frequently. For most people that would probably be Mail, Messages, Camera, Maps, Calls.

**Comment by 8bitPit** [comment]
Thanks for your great ideas @y0c4 and thanks for helping out @ZephyrMathi. In the future, it's planned that the swipe actions get added automatically: https://niagaralauncher.helpscoutdocs.com/article/38-folders
