### ISSUE TITLE
Shortcuts pinned twice

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1258]
![Screenshot_20200417-125019_Niagara Launcher](https://user-images.githubusercontent.com/35201200/79637171-54185f80-817d-11ea-921d-4931677aca55.jpg)

![Screenshot_20200417-124952_Niagara Launcher](https://user-images.githubusercontent.com/35201200/79637162-3fd46280-817d-11ea-825e-a2b4f636f76a.jpg)

When I go to Galaxy Themes settings and toggle to show its icon on homescreen (originally hidden), it adds the icon twice, first as a regular icon and second as a shortcut. Other apps with same setting (eg. Sams. Device care) don't add the shortcut. If I choose cancel, in Niagara Add shortcut dialog (1st screenshot), only the icon is added without duplicity. (I don't know whether this is a bug in the launcher or it's caused by the app, but flagged bug as it's definitely not expected.)

**Comment by 8bitPit** [comment]
Thanks for letting us know Martin :)

**Comment by Martin5001** [comment]
You're welcome.

**Comment by 8bitPit** [comment]
Fixed in v.0.26.0
