### ISSUE TITLE
Pin Active Music app widget

### ISSUE THREAD

**Issue by DavidIanWarren** [8bitPit/Niagara-Issues#1259]
![Screenshot_20200418-150414](https://user-images.githubusercontent.com/63926454/79668922-1ec43f80-8186-11ea-9a9c-bb6337325ea5.jpg)
I like being able to have a widget, but instead of the Music App widget coming and going only based on activity, I'd love to keep it pinned too (beyond the 1 allowed widget).

**Comment by 8bitPit** [comment]
Then I recommend to use Spotifies media widget for example. Niagara's widget gets the media metadata from the media notification posted by Spotify. When there's no notification we can't get any data.

**Comment by DavidIanWarren** [comment]
I gave that a try. But unfortunately niagara's Spotify widget continues to pop up meaning I have to widgets for Spotify while using the app.

________________________________

**Comment by 8bitPit** [comment]
@DavidIanWarren I can't reproduce that. Spotifies and Niagara's media widget shouldn't show up at the same time (if you only play Songs via Spotify). Can you please restart the launcher and check if this fixes the bug?

**Comment by DavidIanWarren** [comment]
Ah, it was tied to Home Screen Notifications.  Once I turned that off, the Spotify in use widget no longer pops up.

Thx!

________________________________

**Comment by 8bitPit** [comment]
Great, thanks for letting me know :D
