### ISSUE TITLE
Clear Search bar

### ISSUE THREAD

**Issue by tiniwings** [8bitPit/Niagara-Issues#126]
Step1: Click Home -> Search bar opens -> Search for an app eg: 'Firefox'
Step2: Click Firefox app  -> Opens app -> Done browsing
Step3: Click Home/Back button (to open something new)

Now the search bar still shows previously typed entry 'Firefox' - I need to delete the entries manually to search once again. - Can we have the option to clear the entry once we open the app.

Also found strange/intended behavior - Once I open any app from search bar and like to go Home screen, clicking home button opens search bar. Need to click home/back button again to  dismiss it and go to home screen.

**Comment by Shinra04** [comment]
All you gotta do is enable the "drag backspace" option in G-board, and you can easily clear the text with a single gesture.

**Comment by Shinra04** [comment]
But yes, the other 'intended' behaviour seems a bit annoying at times.

**Comment by 8bitPit** [comment]
probably, thc for bringing it up

**Comment by 8bitPit** [comment]
Update: For a few months now, pressing home leads you back to your favorites directly, so I think the issue has been solved. Comment / reopen the issue if you disagree.
