### ISSUE TITLE
Optional display of screentime next to apps

### ISSUE THREAD

**Issue by Imjustcurious** [8bitPit/Niagara-Issues#1260]
I'd fancy it if the launcher would integrate the screentime for apps from Google Wellbeing and then display it on the right side of each app in the same font but with heavily reduced font size so it's visible but not too distracting.

Would really add to the "form a healthy relationship with your phone" aspect in my opinion as it sucks to always open Google Wellbeing to see how long I used what.

**Comment by Imjustcurious** [comment]
And if I didn't open an app it's not supposed to say 0 min, it'd be more aesthetic if only apps I opened display the time

**Comment by ZephyrMathi** [comment]
Don't you already know which apps you used how much time , without looking at digital wellbeing .

**Comment by Imjustcurious** [comment]
I wish that was the case but sadly I'm neither a timer with accurate time tracking nor am I disciplined enough for such endeavor. :O

**Comment by ZephyrMathi** [comment]
I don't know about the whole utility thing but it might look gud on some setups .

**Comment by 8bitPit** [comment]
I had something very similar in my mind. Either showing the daily phone usage timer on the home screen or showing the time of apps that are distracting.

**Comment by 8bitPit** [comment]
I hope you understand that this is a low priority ticket though, it's a cool addition but has to be tested and tweaked a lot I suppose.

**Comment by Imjustcurious** [comment]
Showing the total phone usage time wouldn't be that helpful in my opinion.

I think it should be as high resolution as possible - showing the screen time of each app on the homescreen.

There are quite some apps I'm using for productive things. If it just showed total screen time that wouldn't be represented there

**Comment by 8bitPit** [comment]
True, showing just one number isn't necessarily helpful.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1811
