### ISSUE TITLE
When disabling everything under "At a glance" I want to use the extra space on my home screen for more apps: it's free real estate

### ISSUE THREAD

**Issue by moritz1000** [8bitPit/Niagara-Issues#1261]
**Is your feature request related to a problem? Please describe.**
I disabled everything under "At a glance" (clock, date, weather, battery percentage) expecting to have more space for apps on my home screen and that everything moves up way higher because of the free space.

**Describe the solution you'd like**
I added a picture showing three screens labeled **1,2,3**. **1** is default. In **2** I was moving the screen upwards with my thumb while taking the screenshot. I would like this to be my new starting position. This would also create more space for favorite apps. 

What I absolutley never like to happen is picture **3** where I scrolled down a bit and now there is even more space at the top. Also the position does not reset to **1** when I go back home (from exiting an app) or press my home button again.

![Niagara Idea](https://user-images.githubusercontent.com/35174351/80114725-6a565f00-8573-11ea-9acb-0da89a5b1b67.png)

**Comment by ZephyrMathi** [comment]
You can do that by going to [edit mode] and then choosing [move whole list] and them moving it up this will create more room for apps .

Hope this Helps what you are looking for .

**Comment by moritz1000** [comment]
Thank you, this is what I was looking for. I did not know that you can click on "Move whole list" since... well the whole list is already moving when you are scrolling up or down.

**Comment by 8bitPit** [comment]
@moritz1000 thanks for creating such a well explained feature request. I know that this option to move the whole list is kind of hidden right now, but we plan to improve that soon.

**Comment by moritz1000** [comment]
EDIT: Could you also add a function that the app icons stay fixed at the same position with or without the music widget above? So that the icons don't move up when the music widget is gone? That would also make the [move whole list] function more predictable and useful.

**Comment by 8bitPit** [comment]
@moritz1000 maybe that will be added, but I can't guarantee it: https://github.com/8bitPit/Niagara-Issues/issues/243
