### ISSUE TITLE
Specific font size adjustment.

### ISSUE THREAD

**Issue by swooned** [8bitPit/Niagara-Issues#1263]
It would be great if you can add specific font sizing for the app itself. I know I can I just said University but I can read everything except Niagara Launcher. I can only change app size, but it doesn't change the font size with it.

Either way to be able to just make the font a bit bigger would really help.

**Comment by 8bitPit** [comment]
Yeah, this is planned: https://niagaralauncher.helpscoutdocs.com/article/55-change-font-size

**Comment by 8bitPit** [comment]
Duplicate of #148
