### ISSUE TITLE
Widgets are sometimes not updating

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1264]
The custom home screen widget seems to get stuck from time to time.
Also see: https://www.reddit.com/r/NiagaraLauncher/comments/g5ieun/how_often_do_widgets_update/

**Comment by luxcalor** [comment]
Yes, sometimes I have to restart Niagara to update the widget. Even though both Niagara and the widget providing app are allowed to work in background and whitelisted for any battery optimization.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1474
