### ISSUE TITLE
Remove "uninstall" option from apps that cannot be uninstalled

### ISSUE THREAD

**Issue by zroncarij** [8bitPit/Niagara-Issues#1266]
Such as:

Stock phone
Stock calendar
Stock camera
Stock email
QuickMemo+

Moreover, if someone wants to disable the app add that option instead.

**Comment by Martin5001** [comment]
Yes, the option to disable the app instead is a good idea.

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/1053
