### ISSUE TITLE
Edit mode: Heading position

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1267]
I remember there was a discussion post back when the Edit mode was introduced about that the heading would look better if not so close to the other elements - and the reason for it being that it was not possible to move the icons down from it because the "Move whole list" function would be affected by that.

I think this problem could be solved by moving the heading down and merging it with the close/apply button. This is inspired by Eon music player.

(The button would of course move with scrolling.)
Note: It looks not balanced due to one of the drag icons being cut off, but you know, it's just a quick concept.

![Edit Mode](https://user-images.githubusercontent.com/35201200/80375828-317ef880-8899-11ea-9fdf-45f9cb174bf7.png)

**Comment by 8bitPit** [comment]
Edit mode has been removed in v0.29
