### ISSUE TITLE
Use the new Niagara Knowledge Base in Settings Help as webview

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1268]
I think the new Niagara Launcher Knowledge Base is really useful and looks great so it would be great to integrate it to the Help section in Settings directly as a webview.

**Comment by 8bitPit** [comment]
That's already planned :D Fortunately Help Scout (our knowledge base providers) offers an API to integrate the webview directly in our app. Then, we don't even have to use webview.

**Comment by 8bitPit** [comment]
Fixed in v.0.27
