### ISSUE TITLE
Allow changing language independently

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1269]
It would be good to have an option to set different than system langauge - for users learning language or in case the primary language is not available, user may choose his or her second language (I assume English is the only fallback now but correct me if not.)
(Also it would be easier to take screenshots for concepts, documentation or translation, not so important though.)

**Comment by 8bitPit** [comment]
Hey Martin, I'm sorry, but we don't plan to add a language chooser for the reasons mentioned here: https://github.com/8bitPit/Niagara-Issues/issues/656
