### ISSUE TITLE
Add A Feed Page to The Left

### ISSUE THREAD

**Issue by keeratsawhney** [8bitPit/Niagara-Issues#127]
Feedback Page is Important to Check Other Widgets Such a Weather, Callender, App Shortcuts ,Etc Similar to Oneplus Launcher. Also Integration Of Google Feed Could Help Alot.

**Comment by dojwB** [comment]
Google feed can come handy for ton of people. OnePlus like drawer is also cool idea tho.

**Comment by 8bitPit** [comment]
See #59
