### ISSUE TITLE
Ability to reset app launch count (or whatever metric calculates frequency) for recent apps that show on the homescreen

### ISSUE THREAD

**Issue by adamzeis** [8bitPit/Niagara-Issues#1270]
I have a few frequent apps that show on the homescreen under my favorites that I use often for a short time, however, I'd like to be able to "reset" the launch count of these apps so that they stop showing as frequent temporarily. I don't want to completely stop them from showing at all again ever, just until they become frequent again. 

For example, this weekend I used the Hue app quite often and it shows now as a frequent app. I don't plan to continue using it for a while now, and while I don't want it to stop showing as a frequent app forever, I'd still like to be able to remove it from the frequent list right now until it "becomes" a frequent app again.

**Comment by Martin5001** [comment]
Maybe resetting by toggling the recommendations off and on again could be an elegant solution.

**Comment by 8bitPit** [comment]
While it's a minor thing in my opinion, I get your use case and see why i'd make sense. @Martin5001 that's a cool idea, but Niagara's usage system is also used to determine how many apps you launched in a certain time span (https://medium.com/niagara-launcher/niagara-launcher-in-2020-df3f6aa2d184) or to suggest you what apps to favorize or hide (The latter is in the works), so a reset would also interfere with these little features.

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.
