### ISSUE TITLE
Whenever I launch the game it crashes. 

### ISSUE THREAD

**Issue by kazimShaikh** [8bitPit/Niagara-Issues#1271]
**Describe the bug**
whenever I launch this game called Shadow Fight 3, it takes 2 try all the time to launch. First time it carshes and then second time it works fine. I am facing this issues since last 4-5 updates.  

**To Reproduce**
1. Launch the Game. 
2. Crashes on first try. 
3. Launch for the second time and it works. 
4. Theres the error. 

**Smartphone (please complete the following information):**
 - Device: Redmi K20 Pro / Xiaomi Mi 9T Pro. 
 - Android version: Android 10 (Q), MIUI 11. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by ZephyrMathi** [comment]
Yes I too Experience this issue , I have experienced this quiet a few times in the past few days in any games o played .

Note : Only the new games I installed have this issue the old ones are working fine .

Device : OnePlus 6
Android 10

**Comment by 8bitPit** [comment]
Do these games really crash? Does an error message show up?

**Comment by ZephyrMathi** [comment]
No a black screen appears and returns to home screen

**Comment by 8bitPit** [comment]
Ah I see, I may found the cause, but because I can't reproduce it, I'll add a debug message in the next message. When the game opens and you're reading this, we know where the bug is.

**Comment by 8bitPit** [comment]
Hey @kazimShaikh & @ZephyrMathi can you please try out this apk: https://drive.google.com/open?id=1J8OmRUrr-kJIhQ-bJNfVpK9Do0mhz3WT
If the bug is where I suppose, then a short message should pop up when you open the game and it closes again. Can you please check that?

**Comment by kazimShaikh** [comment]
Yes I did the installation. 
Now when I open the game, it says restarting. 
And the game works on the first launch. but the icons 
on the home screen are keep blinking. 
![Screenshot_2020-05-03-16-14-41-468_com nekki shadowfight3](https://user-images.githubusercontent.com/40717328/80912710-88cf0e00-8d5c-11ea-9eca-3b14228c343e.jpg)

**Comment by 8bitPit** [comment]
Thank you very much for testing!

**Comment by 8bitPit** [comment]
Fixed in v.0.26
