### ISSUE TITLE
Edit mode: "Move list" improvement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1272]
There is a problem with the "move list" function that if I want to move the list so it matches some spot on the wallpaper for example, I cannot see the result in real time because the position of the elements in the Edit Mode is different than on the final home screen.

To solve this I would suggest to hide "Add widget" button and hide the text and buttons while moving the list. So only a regular desktop would show when moving (except the move handle being added of course). Then when the user finishes moving the list, it would go back to Edit Mode with all the options visible again.

**Comment by 8bitPit** [comment]
Hi Martin. Soon, the edit mode will be replaced by a simpler system. Then, you won't have this problem anyremore, stay tuned 😉

**Comment by Martin5001** [comment]
Can't wait already 😁

**Comment by 8bitPit** [comment]
Edit mode has been removed in v0.29
