### ISSUE TITLE
Show battery charging indicator next to battery percentage

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1274]
Add a little flash icon next to the battery percentage on the homescreen when the phone is charging.

**Comment by Montell2099** [comment]
Did this idea get ditched? Would be a nice small addition to the pro-users who are hiding the status bar.

**Comment by 8bitPit** [comment]
I still like the idea, but this is rather a low priority ticket, it may take a while once it has been implemented.

**Comment by luxcalor** [comment]
This would be nice. One of the most missed features after I hid the status bar.

**Comment by 8bitPit** [comment]
Added in version  1.1 🎉
