### ISSUE TITLE
Search bar animation speed is too slow

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1275]
**Is your feature request related to a problem? Please describe.**

If the user presses home to show the search, there is an animation where the search bar fades in from the top. The animation speed is slow and can't be turned off or be configured.

![Screenshot_20200502-134439](https://user-images.githubusercontent.com/13085980/80863271-57cadc80-8c7b-11ea-9027-addb641f11b1.jpg)

**Describe the solution you'd like**

The animation should be either:

* faster/snappier by default
* configurable in the settings (or it can be disabled)
* respect the Android developer options

![Screenshot_20200502-134712](https://user-images.githubusercontent.com/13085980/80863317-b09a7500-8c7b-11ea-97f6-8b0c5c5d7643.jpg)

This is probably about milliseconds, but as this is often used in my workflow, it feels super slow and I'd like to disable the animation or speed it up.

**Comment by Martin5001** [comment]
Yes I would like it a bit faster too. I think it's mainly that it takes long for the keyboard to show, so maybe If the keyboard would open just with the search animation instead of slightly after it, it could be enough.

**Comment by 8bitPit** [comment]
Thanks @andys8 & @Martin5001, I hope you can both understand that this is a low priority ticket.

**Comment by andys8** [comment]
It's slowing down the interaction I've the most with the launcher. The change is simple. So low effort, high return value - I'd vote for `high priority` 😉

**Comment by andys8** [comment]
Is it possible to fire up the keyboard as soon as the home button is pressed and not when the animation ended (like @Martin5001 wrote)? That would be nice, too.........

**Comment by 8bitPit** [comment]
Yes, I'll try that

**Comment by 8bitPit** [comment]
Fixed in v.0.30
