### ISSUE TITLE
Widget should be automatically removed after app is uninstalled

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1276]
If I add a widget and then uninstall the app, it stays on the homescreen and must be removed manually. I don't know if it's a bug or it's just made this way but I think the widget should be removed automatically.

**Comment by 8bitPit** [comment]
Yeah, that's a bug. Thanks for reporting!

**Comment by 8bitPit** [comment]
Will be fixed tomorrow!

**Comment by 8bitPit** [comment]
Fixed in v.0.27
