### ISSUE TITLE
Keyboard remains open when exiting Termux

### ISSUE THREAD

**Issue by insanum** [8bitPit/Niagara-Issues#1277]
**Describe the bug**
For some reason when exiting Termux the keyboard remains open. I don't see this behavior with any other launcher.

**To Reproduce**
1. Start Termux
2. Enter `exit` or `exit 0` and hit Enter
3. Termux properly exits but the keyboard remains.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - Android version: 10

**Comment by 8bitPit** [comment]
Thank you for the report. I could reproduce & fix it :)

**Comment by 8bitPit** [comment]
Fixed in v.0.27
