### ISSUE TITLE
Add option to have 'Hidden Apps' button at end of apps list

### ISSUE THREAD

**Issue by xiphiidae** [8bitPit/Niagara-Issues#1278]
I like to keep my apps list as clean as possible, having only apps that I use often visible. However, there are times when I need to access apps that I've hidden, and the current method of doing so is somewhat cumbersome (scroll to bottom of apps list -> Launcher Settings -> Features -> Hidden Apps). I was wondering if it were possible to provide an option that would allow for moving the Hidden Apps to the end of the apps list, alongside Niagara Pro and Launcher Settings, allowing for a more convenient way to access the Hidden Apps list. I bought Pro to support this great launcher, so I would have no issue with this being a Pro-only option.

**Comment by 8bitPit** [comment]
You can also access hidden apps via search, I believe, that's the fastest way to get to them.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
