### ISSUE TITLE
Wig

### ISSUE THREAD

**Issue by wag123ideias** [8bitPit/Niagara-Issues#1279]
Muito simples, como você ver na foto widget fica escondido deveria ter um Modo de não ficar assim.

Very simple, as you see in the photo widget is hidden should have a way of not being like this.
![Screenshot_20200506205501](https://user-images.githubusercontent.com/64935217/81240263-49632480-8fdd-11ea-9691-20eccc761e49.jpg)

**Comment by wag123ideias** [comment]
Deveria fiar assim com os números da previsão aparecendo mas fica escondido oculto.
It should run like this with the forecast numbers showing but it is hidden hidden.
![IMG_20200506_220937_489](https://user-images.githubusercontent.com/64935217/81243608-b3cc9280-8fe6-11ea-99fa-e70a673ddc68.jpg)

**Comment by 8bitPit** [comment]
Hope this helps: https://niagaralauncher.helpscoutdocs.com/article/43-widget-options
