### ISSUE TITLE
Niagara Launcher Weather API migration from Dark Sky to Climacell

### ISSUE THREAD

**Issue by MasterSingleton** [8bitPit/Niagara-Issues#1280]
Since as you may all know Apple has Acquired Dark Sky in early April 2020 and has stopped supporting the Android App version and will stop supporting it's API in around 2021/2022.                                               Is it possible to please migrate from Dark Sky to [Climacell](https://www.climacell.co/weather-api/) as I've used [Climacell](https://www.climacell.co/weather-api/) to a certain degree and loved it that it's similar to Dark Sky back in 2018 in order to still have accurate hyper local weather data and warnings prior to Dark Sky stopping it's weather API support thanks.

**Comment by 8bitPit** [comment]
Thanks for your suggestion Marcus. Their service looks promising, but also not cheap. We would need the Pro plan which costs 120$/month (or 1440$/year).

**Comment by MasterSingleton** [comment]
Thanks for your response. The pricing is definitely on the high side but it looks like the only like for like direct Weather API replacement for Dark Sky at this stage unfortunately.

**Comment by 8bitPit** [comment]
I'd suggest to wait one year, maybe a couple of weather provides will also make special offers shortly before Dark Sky's API is being shut down.

**Comment by MasterSingleton** [comment]
I agree with your outlook.

**Comment by 8bitPit** [comment]
Great :D I hope you don't mind if I close this issue, because we're not certain what weather provider we'll choose.
