### ISSUE TITLE
Toggle/move widget/favorites area

### ISSUE THREAD

**Issue by vebulous** [8bitPit/Niagara-Issues#1281]
Problem: I use KLWP and have created a snazzy calendar agenda komponent, but it sits low on the screen, takes up about half of the screen when activated. Niagara launcher's favorite/widget/music/dock area thing (what is that called?) blocks touches  through to my live walpaper. So, i cannot activate the touches on the live walpaper because they're being blocked by the launcher. Exhibit A.

![IMG_20200509_225242](https://user-images.githubusercontent.com/26128449/81490164-aa446400-924c-11ea-9270-aeaa19f05e3f.jpg)

Solution: have the ability to move the favorites/widget/music/dock aaaallllllll the way to the bottom; or remove all or some of  the favorites/widget/music/dock elements. Via toggles. Exibit B.

![IMG_20200509_232810-1](https://user-images.githubusercontent.com/26128449/81490766-124a7880-9254-11ea-8f0d-8c58868b1bbb.jpg)

Summary:
Option to move maximum top position lower than 50% from top of screen. Or toggle on/off
Adds more customizability and minimalism.
Could probably be an easy fix requiring little effort.
Could use existing customisation elements or add new toggle(s) to achieve goal.

**Comment by 8bitPit** [comment]
Thanks @vebulous, it will be possible to move Niagara Launcher's home screen list more down (probably even in the near future).

**Comment by vebulous** [comment]
> Thanks @vebulous, it will be possible to move Niagara Launcher's home screen list more down (probably even in the near future).

Thanks for the reply. I cant wait for this tiny lottle itsy bitsy annoyance to go away. Other than this, im absolutely loving Niagara Launcher. The things that are out of its scope are easily implemented with KLWP and KWGT.

**Comment by 8bitPit** [comment]
Feature added in v0.28
