### ISSUE TITLE
Separate sliders for icon size and list spacing

### ISSUE THREAD

**Issue by asuetin** [8bitPit/Niagara-Issues#1282]
Currently, when you move the icon size slider in the settings, the spacing between list items stays the same. So if you just want smaller icons, you inevitably end up with a crammed-looking list.

I would argue that an icon pack like [Drops ](https://play.google.com/store/apps/details?id=com.aiocen.iconpack.drops) with small icons is a perfect fit for Niagara's style. However, that pack hasn't been updated in years and I've been unable to find a similar one. Theoretically, this look would be possible to achieve with any icon pack if we could adjust the size and the spacing of the icons separately (and if it smallest allowed icon size was even smaller than it currently is).

**Comment by 8bitPit** [comment]
Hi, unfortunately this feature won't be added this year: https://github.com/8bitPit/Niagara-Issues/issues/304
