### ISSUE TITLE
Navigation Bar Split Screen Shortcut Fails with Niagara Launcher

### ISSUE THREAD

**Issue by deba94** [8bitPit/Niagara-Issues#1287]
**Describe the bug**
With a split screen navigation bar shortcut enabled (for example, long press recents to open/close split screen), using the shortcut leads to a split screen style navbar, but does not split the screen.

**To Reproduce**
1. Enable a split screen navigation bar shortcut (either via settings>buttons and gestures>navigation bar & gestures>navigation bar customization (example taken from Oxygen OS), or by installing a 3rd party app such as "Split Screen Shortcut" by etsang (tested))
![Screenshot_20200518-081854](https://user-images.githubusercontent.com/22893568/82212310-55ee5380-98e0-11ea-9d82-5127226c9223.jpg)

2. Use the shortcut
![Screenshot_20200518-082100](https://user-images.githubusercontent.com/22893568/82212483-9cdc4900-98e0-11ea-997a-63114983d870.jpg)

3. Observe the bug (split screen nav bar, but no screen split)
![Screenshot_20200518-082105](https://user-images.githubusercontent.com/22893568/82212495-a2d22a00-98e0-11ea-92f6-37abf2a1c709.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android version: ever since Android 10

Additional note:
Split screen shortcut functions normally with the OnePlus launcher:
![Screenshot_20200518-082551](https://user-images.githubusercontent.com/22893568/82213238-d5c8ed80-98e1-11ea-89c0-743cb00db1a5.jpg)

![Screenshot_20200518-082607](https://user-images.githubusercontent.com/22893568/82212898-48859900-98e1-11ea-9887-c162785a0b8a.jpg)

Here's a video to better explain the situation:
https://i.imgur.com/U6j94HX.mp4

**Comment by 8bitPit** [comment]
Thank you very much for explaining the bug in such detail @deba94. Can you please also check if the bug also happens on other **third**-party launchers, like Nova or Lawnchair?

**Comment by deba94** [comment]
No problem @8bitPit thanks for looking into this. Big fan of Niagara by the way, great work.

Both Nova Launcher and Lawnchair (2) appear to have the same issue, please see below for a screen recording:
http://imgur.com/a/odKc0tf

Let me know if you need any more info and I'd be happy to help.

**Comment by 8bitPit** [comment]
I fear that this bug is not getting caused by Niagara but by your system then. I doubt I can fix it.

**Comment by deba94** [comment]
I think you're right. I appreciate the help, regardless. 

I've submitted a bug report to OnePlus and they seem to be looking into it. Hopefully something comes of it.

Keep up the good work.

**Comment by 8bitPit** [comment]
Thank you very much :D
