### ISSUE TITLE
#1276 fix probably did not take effect

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1289]
I'm running v0.28.2 on Samsung Galaxy J7 with Android 9 and the bug #1276 is unfortunately still present.
I tried it with "Another Widget". If I uninstall the app while the widget is still on the screen, the widget changes its text to "Loading data" but does not get removed from the screen. Otherwise it's uninstalled correctly (not in the apps list or widgets list).

**Comment by 8bitPit** [comment]
Oh okay, thanks for telling me, I reopened #1276.

**Comment by 8bitPit** [comment]
@Martin5001 the widget now gets automatically removed after its parent app gets uninstalled, can you please confirm?

**Comment by Martin5001** [comment]
Yes, it works now. Thanks

**Comment by 8bitPit** [comment]
Awesome, thanks :D
