### ISSUE TITLE
Alphabet should be fixed in place

### ISSUE THREAD

**Issue by dojwB** [8bitPit/Niagara-Issues#129]
When you drag your finger on alphabet (in app drawer) list moves, but it shouldn't move. Like dock on macOS, it can expand but never move left or right (in this case, up and down) 
It should always look like this
![it should always look like this](https://user-images.githubusercontent.com/43079520/45244913-8788dc00-b302-11e8-92d8-1df086763756.png)
Not like this
![not like this](https://user-images.githubusercontent.com/43079520/45244931-a1c2ba00-b302-11e8-8075-ca573ff538ae.png)
Or this
![or this](https://user-images.githubusercontent.com/43079520/45244944-b43cf380-b302-11e8-88bb-d1401026635f.png)

**Comment by Shinra04** [comment]
No.
This feature of this launcher is what makes it far more convenient and enjoyable to scroll in. Taking it away makes the scroll more restrictive and less intuitive.

**Comment by 8bitPit** [comment]
You would cover the alphabet with your finger, that's why it's "fluid". Furthermore, it adds a unique style to Niagara.
