### ISSUE TITLE
cannot interact with live wallpaper (KLWP) since 0.27+

### ISSUE THREAD

**Issue by vebulous** [8bitPit/Niagara-Issues#1291]
**Describe the bug**
Up until niagara-launcher v0.26.0, i had the ability to touch and interact with a live walpaper under the launcher to an extent (submitted a feature request to maximize the total screen realestate to interact with walpapers [here](https://github.com/8bitPit/Niagara-Issues/issues/1281) ). In my case a KLWP. Upon update to 0.27.0 and later 0.28.2, the live wallpaper interactivity is completely blocked by Niagara launcher. Just to make sure the problem wasnt with the wallpaper, i tested it with Nova and it worked fine. Niagara was the culprit. Had to downgrade to 0.26.0 to go back to pre-i-need-to-complain-aboit-this state. And 0.26.0 works fine.

**To Reproduce**
1. Install an interactive live wallpaper.
2. Enable it.
3. Try to interact with it.

**Smartphone**
 - Device: OnePlus 7 Pro (GM1917)
 - Android version: Android 10
 - OxygenOS veraion: 10.3.2.GM21AA
 - Google Play Services version: 20.15.16
 - Niagara Launcher version: 0.27+
 - Nova Launcher version: 6.2.12

**Comment by 8bitPit** [comment]
Thank you for reporting :)

**Comment by Noe-H** [comment]
I have the same issue, can't interact with any Live Wallpaper even in 0.26

LG V30, Android 9

**Comment by 8bitPit** [comment]
Fixed in v.0.31

**Comment by Daniel-Brum** [comment]
I'm having a similar problem using the latest (not stable) version. Less than half of the screen actually works for touches in live wallpapers. I'm using a Meizu M6 Note with Flyme 7.1.

**Comment by 8bitPit** [comment]
@Daniel-Brum, as of now, you can only interact with your KLWP live wallpaper with elements you placed above Niagara Launcher's favorites, unfortunately.

**Comment by Daniel-Brum** [comment]
Sorry for taking so long to reply. Does that mean that I can't interact at all unless I have at least one favorite app?

**Comment by 8bitPit** [comment]
@Daniel-Brum, you could drag Niagara's widget all the way down (Niagara settings > Features > Niagara widget > Move widget) and optionally hide the clock & date. Then almost the whole screen should be interactable.

**Comment by Daniel-Brum** [comment]
Oh, that worked perfectly. Thanks a lot!
