### ISSUE TITLE
Widget gets cut off, possible to add the ability to resize width?

### ISSUE THREAD

**Issue by adamzeis** [8bitPit/Niagara-Issues#1292]
Using the "At a Glance" widget on a Pixel 4XL and often times the text is cut off. Is there a way to resize the width of a widget so this doesn't happen? 

![Screenshot_20200520-062359](https://user-images.githubusercontent.com/39461983/82441863-97ac0500-9a6c-11ea-80ce-c40ae9c4da13.png)

**Comment by 8bitPit** [comment]
Yes, you can do that with a hidden commands. Go to Niagara's app search and type "/widget filled". We'll also add an "official"way to do it though, the update will be published in 7 to 12 days on Google Play.
