### ISSUE TITLE
Google Assistant Functions Inhibited by Niagra Launcher. 

### ISSUE THREAD

**Issue by carstent02** [8bitPit/Niagara-Issues#1295]
Google Assistant is quickly becoming a more and more useful tool for me and many others. My current phone is an LGG7 ThinQ. It is a little unique in that it has its own dedicated assistant button. You can imagine that it is frustrating when this button does not function on the homepage of Niagra launcher. It does work on all other pages as does the "okay Google" phrase. However on the Niagra launcher home page neither function. The only way to access assistant is to touch and hold the google button in the bottom right. This can be inconvenient at times but in general I just hate how Niagra can't make use of the bottoms that are part of the phone nor the voice commands. Likewise Niagra doesn't allow the phone to be put to sleep with two taps of the homescreen even though that setting is on through the system settings but this is beside the point. Please fix this!!

**Comment by 8bitPit** [comment]
Thanks for reporting, can you please check if this works on other third party launchers (i.e. a non preinstalled launcher pike Nova). However, you can open the Google Assistant by long pressing Niagara's Google button.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
