### ISSUE TITLE
YouTube Picture in Picture breaks home button to search

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1296]
**Describe the bug**
YouTube picture in picture mode makes it impossible to press the home button to search for apps in the first seconds. Will work after ~ 4 seconds.

**To Reproduce**
1. Play a video in youtube app
2. Press home button for picture in picture mode (needs premium)
3. Tap the home button to trigger search
4. Search will not work
5. After some second the it works
6. This is not the case for other elements like apps on the home screen

**Smartphone (please complete the following information):**
 - Device: OnePlus 8
 - Android version: 10

**Screenshots**

Can't press home in navigation buttons (grey). YouTube PiP has focus.
![Screenshot_20200521-181051](https://user-images.githubusercontent.com/13085980/82580360-54968280-9b8f-11ea-8e4b-f350bba23823.jpg)

Can press home button (white) after ~ 4 seconds
![Screenshot_20200521-181055](https://user-images.githubusercontent.com/13085980/82580363-55c7af80-9b8f-11ea-948f-93784e06ccf7.jpg)

The behavior is the same with Nova Launcher. So the issue is likely caused by the behavior of the OS or YouTube. Maybe there is a  workaround or way to improve it.

**Comment by 8bitPit** [comment]
I believe that's a system bug, can you reproduce this on other third party launchers? However we're considering a new way to access search quickly, e.g. by swiping up.

**Comment by andys8** [comment]
Same issue occurs with Nova. See the last paragraph.

**Comment by 8bitPit** [comment]
Oh sorry, I didn't read the last paragraph 😅 the only workaround I can imagine is changing the trigger to open search.
