### ISSUE TITLE
Mirrored mode to right side

### ISSUE THREAD

**Issue by kllr007** [8bitPit/Niagara-Issues#1297]
I starting to like this launcher, but one thing bothers me - I am right handed, and would like to have option to have mirrored all things to right. Is that possible ?

**Comment by 8bitPit** [comment]
You don't have to tap on the apps icon or name to launch it, but maybe the option to mirror the layout will be added, see #12

**Comment by kllr007** [comment]
yeah but for me its happen most of times that instead of launching app it will go to app list.

I was hoping more to be like this - 
![Niagara_Launcher_1](https://user-images.githubusercontent.com/50110692/82753447-fbfcfa80-9dc5-11ea-8d5d-a6444c4a5183.png)

**Comment by 8bitPit** [comment]
Maybe, we'll add an option to mirror the layout completely, but we're not sure yet.

**Comment by 8bitPit** [comment]
Merged with #12
