### ISSUE TITLE
Pro feature "At a glance": Show Network cell info / meter

### ISSUE THREAD

**Issue by moooztar** [8bitPit/Niagara-Issues#1298]
Hi,

I have converted the whole family to Pro Niagara users and we all love it. It would be of great help to be able to see the **signal meter and name of connected cell provider** for us that have chosen to hide the status bar (pro feature) 

It would be logical to put this under "At a glance" with Show clock, Show date, Weather and battery % on / off.

The statusbar is way too small (font) for many people and it is very valuable info (as we have free data on one provider but not the rest; and that one provider has poorer coverage). 

Thanks! Love Niagara.

Moo

**Comment by Rod911** [comment]
From https://github.com/8bitPit/Niagara-Issues/issues/1226#issuecomment-622263260
> We're trying to only include the most necessary icons. For the rest, you can peek at Android's notification shade by scrolling up without letting go your fingers.

**Comment by moooztar** [comment]
To grow as a launcher ppl have different needs. So to get the "noise" away from the notification area of the phone (which you provide in the PRO feature) AND the fact that I struggle with my eyesight it would be a wonderful feature (for many more than me I reckon).

Niagara is so simple to use that even my old father now is a steady user, and then the need for "the most important info up top" would include signal bar + cell provider (and discard the rest of Androids rolldown notification area as in PRO hide it).

We live in Europe (Scandinavia) and all users in all countries have different needs in regards of this :-) Here we have free data on one provider but since the coverage is poorer than the rest the phone will "swap" and the only way to see this is the "provider name next to the cell strength meter"
..and the senior market is a market you can coin (willing to pay for a simple user experience on Android). 

I have bought 3 full versions (family) and will continue to spread the good word.. Consider it please!

**Comment by 8bitPit** [comment]
Hi @moooztar, first of all sorry for my very late reply and thank you for the support. We currently don't plan to show network info in Niagara's widget. However, what might help you is that you can still quickly fade in the system's status bar at the top by scrolling down without your finger leaving the screen ([read more](https://medium.com/niagara-launcher/niagara-pro-even-cleaner-4448f55b5571)): 
![1_7Ogdb0EJdvdl5foLUkomKA](https://user-images.githubusercontent.com/9284845/92069944-09555800-edab-11ea-9745-7e3ac4d38d55.gif)

**Comment by moooztar** [comment]
Thank you! It is only a "nice to have". :-)
