### ISSUE TITLE
Some applications not recognized as music app

### ISSUE THREAD

**Issue by H3liumBoy** [8bitPit/Niagara-Issues#1299]
I notice that some applications are not detected as music app. For example Google podcasts. I love the feature that the apps that are marked as music apps only pop up when Bluetooth is connected. Makes the UI less cluttered.

I guess there is a list of apps that have the option or there is some detection algorithm for determining  what apps are music related.

Would like an option for an option to create an manual override from settings menu to mark an application as "Music" related.

**Comment by Martin5001** [comment]
> Would like an option for an option to create an manual override from settings menu to mark an application as "Music" related.

That´s how it already works. In older versions of Niagara you can set music app in the "Edit mode" - long press on the empty space next to clock to get to the Edit mode and then scroll down to the Music apps section. On the latest version of Niagara, Music apps can be set directly from the homescreen. Just press the app icon for a longer time and you´ll see a pop up.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case you need further assistance.
