### ISSUE TITLE
UI - Icon long press menu padding

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1300]
The new UI looks really nice and is a lot easier to use too. Just a minor suggestion: I think the divider should have the same padding as other elements, now it has half of it. (Or it probably has the same, but seems to have less beacuse the line is centered in that space.) Screenshot:
![Screenshot_20200526-171040_Niagara Launcher](https://user-images.githubusercontent.com/35201200/82919953-f8f53c00-9f76-11ea-98f5-1b35880b9b2f.png)

**Comment by 8bitPit** [comment]
That's deliberate because the divider already divides the buttons around it with the line.
