### ISSUE TITLE
UI - Ripple effect triggered incorrectly on Launcher Settings button

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1301]
I just found a really minor bug with the new icon long press menu. If I tap just on the top edge of the menu, right above the app name, it shows the ripple effect on the Launcher Settings button. There should be no ripple effect. (Affected areas marked on the screenshot.)

Niagara version 0.29.2
Android 9
Samsung Galaxy J7

![Screenshot_20200526-171040_Niagara Launcher](https://user-images.githubusercontent.com/35201200/82920682-e0d1ec80-9f77-11ea-9761-c9486f35a976.jpg)

**Comment by 8bitPit** [comment]
You're catching every little glitch, thanks a bunch :D

**Comment by Martin5001** [comment]
No problem :D

**Comment by 8bitPit** [comment]
Fixed in v.0.30
