### ISSUE TITLE
UI - App rename - minor improvement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1302]
This is really minor suggestion: When I go to the app long press menu to rename the app, the blinking cursor shows when the textbox is focused and then stays there until the popup is closed. I think it would feel better if the textbox lost its focus when user exits the keyboard. This would visually ensure the user that the change will be applied and that there is no confirmation required.
![Screenshot_20200526-174807_Niagara Launcher](https://user-images.githubusercontent.com/35201200/82922377-cf89df80-9f79-11ea-9401-7496a390d01d.jpg)

**Comment by 8bitPit** [comment]
I believe that has something to do how Android handles editable text fields. This only happens when I press "back" instead of "enter" and seems to be intended by Android.

**Comment by Martin5001** [comment]
I think yes, it makes sense in most cases for Android to do this and it is probably intended. But maybe in this case it could be changed somehow? (I don't mean in a hacky way of course, but somehow, I'm not a dev but I would expect it would be possible.)

**Comment by 8bitPit** [comment]
Fun fact: There is no (non-hacky) way to detect if the keyboard is currently open: https://www.reddit.com/r/ProgrammerHumor/comments/4uz1xj/oh_i_just_need_to_detect_if_they_keyboard_is_open/
So I would just leave it as it is 😅
