### ISSUE TITLE
Pro Upgrade and Multiple Accounts

### ISSUE THREAD

**Issue by tiger73** [8bitPit/Niagara-Issues#1303]
**Describe the bug**
I am attempting to upgrade to Pro within the app. It takes me to Google Play for payment. The phone has multiple accounts but doesn't let me change to another account for purchase. I cannot locate the "Pro" option in the Google Play Store for direct purchase as I did for Nova Launcher Pro. I understand this is partially a Google Play Store issue, but I want to purchase Pro. Need guidance. I couldn't find another way to reach Support folks. Thank you.

**To Reproduce**
1. Go to 'Edit Mode'
2. Click on 'Niagara Pro'
3. Click on '"Buy once - own forever'
4. Within "Google Play" dialog, Click in "Buy"

**Smartphone (please complete the following information):**
 - Motorola Edge Plus
 - Android version: 10

**Screenshots**
None attached

**Comment by 8bitPit** [comment]
Like you said, that's a Google issue, unfortunately. Maybe the third tip here can help: https://niagaralauncher.helpscoutdocs.com/article/29-lost-access-to-niagara-pro

**Comment by tiger73** [comment]
Hello,

Thank you for the reply. As I also mentioned, I don't have this issue with
Nova as I have purchased Nova Pro directly from Google Play Store. I like
your design principles and would like to switch to Niagara.

Paying 10.99 for a utility is a bit steep. I wouldn't expect it to be so
difficult to give someone my money. Multiple accounts on a phone is not
that unusual.

As an attempted workaround I have resurrected an old phone and set it up
with my primary Google account for purchase purposes. Will I be able to
install on the new, problematic phone after purchase via the old mobile?
Again, since there is no "Pro" on the Play Store, I cannot push the Pro
directly to the problematic device.

Thank you,

-t

**Comment by 8bitPit** [comment]
I can understand your frustration. This is not a bug caused by Niagara Launcher, this is an issue from Google's payment system. The reason why there was no bug with Nova is, because they had to make use of paid apps (because in-app-purchases weren't a thing back then) and Google treats them differently. To answer your question, I wouldn't do that, because the purchase might still not being recognized on your second account. Here's another thread that can help you to solve this issue: https://github.com/android/play-billing-samples/issues/2

**Comment by 8bitPit** [comment]
And  this might also help: https://supercell.helpshift.com/a/boom-beach/?s=in-app-purchases-billing&f=how-to-change-google-account-to-make-in-app-purchase&p=web

**Comment by tiger73** [comment]
Hello,

I reviewed the provided links. The process below made the most sense, but
did not work. It appears I might have to rebuild the phone from scratch,
starting withe my 'primary' Google account, despite this phone being my
backup (Google Fi) device. It seems the 'primary' account on the device is
the one that setup started with, and that the selection of a different
account within Google Play does not seem to be an effective workaround. I
will rebuild the phone and report back.

My Use Case (Current):
As part of my initial setup, transfer the Google Fi stuff and account to
the phone.
Add my 'primary' Google account to the phone

Unsuccessful workaround:
Re-download the app with the correct account:

   1. Uninstall the game from your device
   2. Open the Play Store App and go to settings (3 lines on the top left
   corner)
   3. Make sure the account showing here is the wanted payment account
   4. Re-install the game
   5. Launch the game and try to make a purchase. The displayed payments
   account should mirror the one used during the game installation

**Comment by 8bitPit** [comment]
Real bummer. So you're saying you don't want to have Niagara Pro on your primary account, right?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
