### ISSUE TITLE
/Idea/ Phone back tap gesture

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1304]
(I don't know how difficult this would be. Just an idea.)

Maybe a good way to launch search (or any other action) would be a double tap on the back of the phone.

This could be done using phone's gyro/accelerometer and an algorithm to detect specific vibrations produced by user tapping on the back of the phone.

(Google has something similar so I'm not sure if they have patented it or something, but I believe it could be legal as long as you not use their code and data model.)

(Alternatively maybe sound could be used too – the microphone could detect the vibrations as sound.)

**Comment by 8bitPit** [comment]
That requires the sensors to be always active and can consume more battery. Afaik the rotation sensor that is always active does only detect significant rotation. Moreover, that "gesture" is so unused that it could feel quite strange.

**Comment by Martin5001** [comment]
That about the battery is an interesting point. I never thought about it. I always thought that the gyro must be constantly rotating anyway, maybe it just changes speed. But don't know. I think that if Google has it in Pixels, it cannot be that problematic though, as they wouldn't try it then.

**Comment by Martin5001** [comment]
Just to let you know, recently iOS 14 beta introduced this feature as well in its Accessibility features. More here: http://www.youtube.com/watch?v=ZLyDvABxGF0&t=8m27s

**Comment by Montell2099** [comment]
> Just to let you know, recently iOS 14 beta introduced this feature as well in its Accessibility features. More here: http://www.youtube.com/watch?v=ZLyDvABxGF0&t=8m27s

I think that'd be an interesting addition, if the user could map the shortcut to whatever they want. Exciting idea :)

**Comment by 8bitPit** [comment]
> I always thought that the gyro must be constantly rotating anyway, maybe it just changes speed. 

If I'm honest, I don't know either. But those sensors could consume more battery if they need to be more precise. 

> Just to let you know, recently iOS 14 beta introduced this feature as well in its Accessibility features. More here: http://www.youtube.com/watch?v=ZLyDvABxGF0&t=8m27s

I heard about the iOS integration, but also heard that it often triggers the gesture when laying down the phone on a table. 

> I think that'd be an interesting addition, if the user could map the shortcut to whatever they want. Exciting idea :)

With the recent addition of the double tap to lock gesture, all actions you'd need to execute quickly are already there, what shortcuts would you like to bind to those gestures? Anyway, I just came across an article about an app that lets you do exactly that, hope it's helpful for both of you: https://www.xda-developers.com/tap-tap-brings-ios-14-android-11-back-tap-gesture-any-android-device/

**Comment by Martin5001** [comment]
> what shortcuts would you like to bind to those gestures?

I was thinking about search – not every phone has a home button nowadays and using swipe up gesture might be weird because apps are in a list, which also scrolls down... So I was thinking about back tap mainly as a solution for this.

> I just came across an article about an app that lets you do exactly that, hope it's helpful for both of you

Thanks, I'll use that.

**Comment by 8bitPit** [comment]
I was thinking about search – not every phone has a home button nowadays and using swipe up gesture might be weird because apps are in a list, which also scrolls down... So I was thinking about back tap mainly as a solution for this.

> We plan to make the Google button more versatile by converting it to a generic search button. Then, it would be possible to also assign Niagara's app search to it.

**Comment by 8bitPit** [comment]
So I'm closing this because in my opinion it's better if this feature is provided by a dedicated app (like the one mentioned above).
