### ISSUE TITLE
/Sesame Integration – UI/ Share same icon pack

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1305]
(This is really minor – I'm posting it now just because the Sesame Integration is new so it may be easier to talk with the Sesame team now than changing something later on.)

It would be nice if Sesame could automatically use the icon pack selected in Niagara.
I'm not sure if they would agree with that though as it would be sort of taking over their own settings.

**Comment by 8bitPit** [comment]
There is a bug that Niagara Launcher doesn't respect its own icon pack setting for apps suggested by Sesame that show up when you haven't typed in anything yet. That will be fixed in the next update.

**Comment by Martin5001** [comment]
Aha, so you're already using only Niagara's settings for that, but it doesn't work now. Copy that. :)

**Comment by 8bitPit** [comment]
Fixed in v.0.30.2
