### ISSUE TITLE
Temporarily show recently installed app on the homescreen

### ISSUE THREAD

**Issue by adamdjensen** [8bitPit/Niagara-Issues#1306]
A small issue I've been having with Niagara is that I sometimes install a bunch of apps to try out, but forgot their name or first letter when I go to use them. 
If recently installed apps could maybe be included in suggestions or marked in the app list it could be easier to find them without knowing the name.

**Comment by Rod911** [comment]
Recently installed show up in the search screen, this way they don't clutter your homescreen, but are easily reachable.

**Comment by adamdjensen** [comment]
> Recently installed show up in the search screen, this way they don't clutter your homescreen, but are easily reachable.

Oh that's great. Thanks for the tip!
