### ISSUE TITLE
Some sesame search strings default to app store search 

### ISSUE THREAD

**Issue by Feckweed405** [8bitPit/Niagara-Issues#1307]
Some search strings in the new integrated Sesame search default the search to the app store vs Google. 

**To Reproduce**
1. Activate Sesame through Niagara 
2. Enter, for example, 'marvelous marble wallpaper pixel weather not updating' 
3. Sesame search defaults to app store search only, nor Google. 
4. Same search in Sesame app itself gives Google search option. 

 - Device: pixel 2xl 
 - Android version: stable Android 10
![Screenshot_20200602-113839](https://user-images.githubusercontent.com/50028312/83546006-a7443880-a4c5-11ea-889b-93785ebfda1f.png)

**Comment by 8bitPit** [comment]
Thank you for reporting. I can't solve this without the help of Sesame's devs, because the integration doesn't allow this yet. I already forwarded your request and will let you know when it's fixed.

**Comment by Feckweed405** [comment]
Thanks for getting back so quickly, for the Launcher and for Sesame integration! I totally understand it needs to be fixed on their side. I will use the Google search for longer strings and Sesame for shorter ones. Thanks again!

**Comment by 8bitPit** [comment]
Fixed in v.0.30.3
