### ISSUE TITLE
Hidden apps not working

### ISSUE THREAD

**Issue by marcogargano** [8bitPit/Niagara-Issues#1308]
Tapping on Hidden apps nothing happens, you will redirect to the home.

Xiaomi Redmi 3s
Android 6.0.1
Miui Global 10.2

Congratulation for this project!

**Comment by 8bitPit** [comment]
Many thanks :) I can't reproduce the bug, hidden apps screen works fine for me. Does the bug only occur sometimes or all the time? Moreover, do you have many apps installed / are a lot of apps hidden?

**Comment by marcogargano** [comment]
I made a little movie, I don't know what really happens next. 
After I tapped "Hidden apps", it show my the homepage.
I don't have a lot of apps installed, the hidden apps are almost 10%.

![Niagara-Issues-1308](https://user-images.githubusercontent.com/3099816/84484909-b4b6ab00-ac9b-11ea-8770-0adfaa0eb2a3.gif)

THX!

**Comment by 8bitPit** [comment]
Thank you very much for the video & additional info @marcogargano. Is the list sometimes accessible or is the button always broken?

**Comment by marcogargano** [comment]
I never see the Hidden apps list 😅

**Comment by marcogargano** [comment]
Great @8bitPit !!!
v0.31.1 fix it! Now it's working good 🤩🤩🤩
Thanks a lot!

**Comment by 8bitPit** [comment]
Awesome, thanks for telling me :D
