### ISSUE TITLE
A thoughtful list of suggestions (gestures, functionality, aesthetics)

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#131]
I have used your launcher for two days and I've enjoyed it. I love the minimalistic approach and single gestures necessary to reach all apps.
However, there's room for improvement and I'm glad you're actively replying to us testers.

I've read through all 100+ suggestions and issues beforehand (don't ask why), and I think I now have a good understand of what's necessary and what's not.
 I have 4 important suggestions I'd like to share below, keeping in mind the core purpose of this launcher- minimalism and quick access. 

- Since most of the screen already has gestures, there isn't much room for adding more. I have a few suggestions for this issue.
-> Swipe from bottom left and right corners of screen(to centre) to launch apps(such as Phone and Camera apps respectively; editable by users). Minimalistic icons at the corners (e.g. grey colour).
 You did suggest this, but may have thought it less useful. But it saves users the space for two such apps from taking up space in Favorites.
-> One of the few places without a useful gesture is along the left edge of the screen. Currently, touching it brings up apps scroll and tbh it's unnecessary.
 A better use would be to turn this region into a 'swipe right into screen' gesture. To further improve on it, you can add 3 different swipes-- horizontal swipe, swipe slanted up, swipe slanted down (each showing a minimalist symbol to what they are for)
- To add to this point, it would be intuitive if you were to make the horizontal 'swipe right into screen' gesture open the Google NEWS FEED. This is very important to a lot of users as they use it everyday.(I found your app through it)
-> Along with this, the Google SEARCH is very useful to quickly look things up online without opening a browser app. If you were to add a slim search bar right above the navigation bar, it would be perfect (you could scale down the icon size/padding to make some room). Alternatively, you could add it to the swipe from corners gesture or the swipe from left edge even.
- Another important missing functionality I've noticed is of widgets.  Though I've made a previous post on this, I don't think I suggested a way to implement it. 
So to add this, I thought the swipe from left edge gesture would work perfectly. You swipe into a widgets page from there. To go back out you just swipe back, but this time from the right edge, which is intuitive. Widgets are something a lot of users have personalised for themselves, I cannot even mention all the possibilities with them; removing/delaying it too long wouldn't be in the best interest.
- Finally, one more necessary improvement would be revamping the Favourites page. The reason I mention this is because 8 apps isn't enough for many. However, I can see that you cannot add more apps in a single list, all of which are visible. Yet, scrolling down a list is problematic for other gestures.
 I have a way to change this, allowing you to solve three issues with this one change-- folders, swipe down/up gestures, more Favourite apps.
 What to do? Add more Favourite pages. How to do it while letting you access it within one swipe? Add a label below the date and the first app named say, "Favorites"(to make room for this, move the clock and date slightly upwards; keep it aligned to left to preserve minimalistic look). Make this label interactive like the apps, where you can tap on the right edge to interact with; if you make this a swipable element, you can allow access to secondary page(maybe 3 max.), each accessible with just gestures. Tapping on these named labels, or FOLDERS, expands/contracts their respective contents. The need for folders was actually reduced due to the ease of access to apps in this launcher; however, people tend to forget certain app names, and it would be handy to have these gesture folders to reach the apps without hassle.
 This does away the need for clunky folders with grid layouts. It also gets rid of the need for scrolling in the Favourite apps (without ridding of the Apps scroll) which also gets rid of the issue with the choppy SWIPE UP/DOWN gesture. 
-> Swipe up can be used for searching apps btw; it's more intuitive than tapping Home. 

I also have a few crucial aesthetic suggestions:

- Users can have wildly varying wallpapers, from bright to dark. It would be an annoyance if users had to change them to see things better on the launcher. To counter this issue:
-> Adding shade to the top and bottom of the screen helps users see status bar icons better and maintaining a sense of symmetry. I've borrowed this idea from Nova launcher, but it's something which makes sense.
-> Along with this, reading time, date, app names and notifications in them isn't easy due to no tint. However, tinting makes the launcher look less minimalistic. To counter this, a subtle change like adding a soft black colour (not shadows, which create perspective and look weird) all around the texts (maybe icons even).
- I love the Apps scroll on this launcher, it feels smooth and enjoyable. However, it feels a bit off that only the scroll shows this flow of smoothness, and not the apps list itself. Adding scrolling animations to the apps would be a nice touch, but this is a rather personal preference.

I do notice there's some room in the top right corner, but maybe you have plans for weather or updates or the sort over there.

That's about everything I wanted to say. I've thought a lot about this, and I hope you can implement these suggestions in the coming updates. I understand not all of it is easy to make possible; perhaps you could make some of these features paid (let us beta testers get it for free though ;p). I would love to get a reply from you and other users on what you all think about my suggestions. Thanks for taking the time to read all this. :D

**Comment by 8bitPit** [comment]
I am speechless, what a detailed and great feature list, thanks a ton!

Here is my response to every idea:
-	**swipe from bottom left and right corners**: neat idea, but problematic with the Google search bar / Google search button
-	**left edge of the screen**: That’s meant to be for lefties, but maybe that should be an option toggle. 3 different swipes: that contradicts a bit to the idea of minimalism, I do not want that many gestures, (that is my second problem with your first point) gesture customization would be needed. I want to create a launcher that works out of the box.
-	**Google News Feed**:  For now, it’s easier to integrate the Google apps itself (e.g. by opening it on long pressing the search bar you mentioned). It’s the same feed, but without the need of a companion app.
-	**Widgets**: I don’t know if I go the Apple way (swiping left), everything else is based on vertical scrolling / swiping (except opening notifications). Furthermore, having multiple same direction gestures could be confusing (swipe right on apps vs. swipe right the screen’s left edge). I could also offer a widget page as a dedicated section in the scrollbar. 
-	**Favorites**: Folders will be implemented. My idea is a folder that can be clicked and swiped like an app. A swipe reveals all notifications from apps which are included in that folder. So, do you mean, something like a “tab” system for folders? I would only implement one of those two systems, since both ideas would solve the same issue. 
-	**Swipe up can be used for searching apps**: good idea, will test that! 
 Aesthetics:
-	**Adding shade to the top and bottom**: Already implemented at the top. Has a nice nonlinear interpolation, so it doesn’t stand out that much.
-	**Text background**: Background boxes would clutter up the screen imo
-	**App list scrolling animation**: There is no animation for the sake of speed (you don’t have to wait until your apps fade in, or something like that). For which animation exactly are you looking?
-	**Top right corner**: Nothing is planned yet to fill that space.


Sry for not writing a lengthy answer, compared to your post. We can discuss more about your suggestions in the comments :)

**Comment by Shinra04** [comment]
So to answer to your queries, I have made it simpler by creating an reference image for explanation. Along with this, I have included some changes to my initial suggestions based on your reply.

![picsart_09-08-05 06 01](https://user-images.githubusercontent.com/43073817/45253781-afbc1d80-b38a-11e8-9f58-bca1d2a552d6.jpg)

In the image, I have marked out some coloured regions.
- The white to the right is obviously everyone's favourite app scroll in the world. 
- The white to the left is the Google news feed. It can be the Google app too, but on the condition that it would be possible to make the news tab of the app directly show up on swiping right from the edge. Otherwise, it would be a hassle.
- The little black circles at the corners are the quick access apps I was talking about. As you can see, they will not interfere with any other elements, as you are swiping from that point and then outwards, meaning other elements won't be clicked on. It would be convenient if I could move my Phone and Camera apps to each of those corners.
- The blue is where I'd wanted the Google search bar; with a scale like that, it wouldn't interfere with any other elements. If you can create a custom bar which is slim and transparent, it would be a nice touch to the minimalist theme.
- Now, you must've noticed the three red arrows from the left black circle. As you guessed, it will be for accessing 3 other elements, each with a single gesture. To make it simple, on tapping the circle, the icons of the 3 elements would show up at the end of the swipes to be performed.
 Since you said that multiple right swipe gestures would get confusing, perhaps this would fix the issue, while still being quick and intuitive. The elements I was thinking of including here were the widgets screen, and the Phone app, or it could be switched to the other side. My point was to keep one of the black circles to launch an app you want to launch in a quick swipe, while the other had a few more options and relatively slower single swipe. 
- The widgets page will have to be easily accessible, which is why I thought of this single swipe way. Alternatively, the widgets page could be made into a separate folder. Speaking of which, you will notice the purple regions. That was where I'd suggested to add a folder. The darker purple is where the name of the folder would be, the lighter purple is the extended area where you can interact with this folder element, like the rest of the apps. 
 This can be swiped for more such folders. When you tap it, the folder(whose apps are currently shown below) will condense, revealing other such folders(in condensed state, only name visible). Swiping on the folders here to show notifications from all apps within may get chaotic. Perhaps disabling swipe on condensed folders would be the way to go. Upto 8 folders can be created, order can be set by user. 
 Here, I'd like to point out as you said, that another 'Widgets' folder could be created. But this would make it slightly difficult to access if the user doesn't want to place it in the 2nd position.

As for the aesthetics:
- The shade was subtle then. No problem with that, but would like to see my navigation bar a bit better; it just looks weird as you can see in the pic.
- When I said improving readability of text, I didn't mean by creating visible boxes. What I suggested was a sort of subtle black 'glow' to the text, creating a soft outline on all the text, preventing the need for tint.
- The animation I was talking about was just a scroll of the apps themselves, with no such 'inertia' when stopping at a letter, making it just as quick as it currently is. However, now that I think about it, it may be a bit unsettling, as the direction of flow of the scroll would be opposite to that of the direction of moving apps; I guess you could add this bit to the 'not now' part.
- The top right corner seems a bit empty, but I'll leave that part up to the other users to suggest on.

**Comment by Henderson42** [comment]
Just wanted to chime in here if I may. 

Firstly it's a great launcher. Loving it.

I'd suggest that for the sake of scrolling and favourites the Google search bar would be better placed at the top in a similar fashion to the app search when you begin scrolling. Replacing it with said app search when scrolling is initiated. This would help provide continuity to the launcher. 

I like your idea about the quick drag from the bottom corners for quick access but unsure if it'd be good idea to use it for apps as it seems somewhat redundant on account of the favourites which provide not only quick access but the extra context menu for in-app actions. (On a side-note it'd be nice if swiping on the phone app gave a list of "favourites" or "frequently used" contacts).

Maybe one of the corners could be used for dragging an overlay which is used for widgets? I don't use many but it'd be nice to have the ability to use them in this launcher somehow. 

Keep up the good work.

**Comment by Shinra04** [comment]
- Replacing apps search with Google search is what's redundant to me. If I wanted to search something online, I'd have to do an addition swipe and then a tap on the bar to get there. Present version of app has a neat little G icon.
- The quick access element was suggested by me for apps which didn't have any text notifications and for widgets, as these things would take up unnecessary space on the Favorites page.
- I initially was suggesting at an overlay for the widgets, but right now the better idea is creating a collapsible folder for it (purple in the pic).

**Comment by Henderson42** [comment]
Sorry, I was suggesting a persistent Google search bar at the top. This then becomes the pre-existing app search bar when you swipe to begin scrolling. 

Hope that is clearer.

**Comment by Shinra04** [comment]
That's an outdated placement, and for a good reason: it's much harder to reach up there with one hand than if it were at the bottom, or where it currently is as an icon.

**Comment by Henderson42** [comment]
True. I'm forgetting that you would be able to move the rest of the launcher up to fill the space at the top that I was thinking of filling when I made the suggestion. My bad!

**Comment by Shinra04** [comment]
That is what I'd initially suggested, by the blue region in the pic.

**Comment by Henderson42** [comment]
Yeah I'd agree. I was struggling to visualise because the blue box was over an app and the empty space at the top still present. 

I also have an S8 so I think the long aspect ratio is exacerbating the empty space.

**Comment by Shinra04** [comment]
Actually, it's just like that. I couldn't exactly magically move the apps to create space in the bottom, which was why I'd explained it in the beginning in my initial list of suggestions.

**Comment by 8bitPit** [comment]
`The white to the right is obviously everyone's favorite app scroll in the world`
Thank you :)

`The white to the left is the Google news feed [...] The blue is where I'd wanted the Google search`
So, should there still be a news feed / search bar? The G-button should have solved those two problems (also if I am implementing the feed, the button could open it instead of the Google app)

`The little black circles at the corners [for] Phone and Camera apps`
Most phones have double tap on home / power button to open the camera though. 

`three red arrows from the left black circle`
Yeah, neat idea with, but I am still thinking that could be two a bit two much. One swipe up, down gesture, a Google button (and maybe one gesture on the left side?) should be enough in my opinion.

`widgets page could be made into a separate folder `
Could be like a folder on the homescreen or a scrollbar section.

`the purple regions. That was where I'd suggested to add a folder`
Personally, I like your newer idea for folders in thoughtful suggestions #2 better, they are more intuitive & easy to reach. (Tomorrow I’ll answer your second list of suggestions)

Design:

`would like to see my navigation bar a bit better`
There is no bottom “scrim” yet, I will implement that.

`subtle black 'glow' to the text`
That should look very similar to a shadow, shouldn’t it?

Thanks again.

**Comment by killoid** [comment]
i am ok with the gesture integration but please add an option to turn off all the gestures & custom actions of hardware/navbar buttons provide by the launcher.

**Comment by Shinra04** [comment]
@killoid Hardware/navbar buttons are left untouched in my suggestions.

**Comment by Shinra04** [comment]
@8bitPit

- There is no longer a need for a search bar or a different gesture for news feed; your method is very convenient. 
If you're considering implementing Google now integration, it would be a nice touch of refinement. The Google app news feed is the same and gets the job done, but it kind of feels like a temporary fix. It's up to you if and when you decide to change that.

- Yeah, I guess camera is not an issue, but perhaps a gesture from the bottom left corner would be handy for launching Phone app. I'm not entirely sure yet how the element should visually appear, as a circular icon would look weird with respect to the placement of the G icon.
- Accessing widgets via folders feels quicker to me, a single tap. Maybe include an option to change between the two: "Widgets appear in folders list/apps list".
 Speaking of widgets, I feel we can allow them to be placed in a grid fashion. Easy to fit in many, and keep it hidden away in a folder so it looks neat.
- Yes, I find my newer suggestion an upgrade to my previous one stated here. It strengthens the support for minimalism and ease of access.
- Thanks, it'll be a nice touch.
- Yes it looks similar to a shadow, but the difference is that shadows have this black glow only to one direction of the text, which looks unsymmetrical. The glow would be equally all around the text. So you could say, the light source comes from the front and towards the screen.

**Comment by 8bitPit** [comment]
`The Google app news feed is the same and gets the job done, but it kind of feels like a temporary fix. `
Maybe I'll implement the feed, but not for now.

`Speaking of widgets, I feel we can allow them to be placed in a grid fashion`
I would use also use a list for them, nearly every widget looks good when it has it's maximum width.

`Yes it looks similar to a shadow, but the difference is that shadows have this black glow only to one direction of the text, which looks unsymmetrical.`
I'll try that out and will send you my results.

**Comment by 8bitPit** [comment]
Hey, I want to thank you once again for your detailed requests. As of now, I decided against a widget page, you can find the reasons here: #117. If you want to discuss further on Niagara Launcher's gestures, please comment here: #2. If you want to discuss about another idea, please open a dedicated request, one ticket per request makes it easier to keep track of them. Thanks :)
