### ISSUE TITLE
Smart app list - show file browser on download finish

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1311]
If I download a file using a web browser, Telegram, Twitter or any other app, it usually does not have an option to quickly open that file - clicking the "File downloaded" notification usually just opens the app, but not the downloaded file.
So I have to open my file manager app and locate the downloaded file here. But I don´t want/need the file manager app being shown in my favourites permanently.

So I think it would be useful to show a file manager app of choice in the apps list dynamically (similar to the Music apps category). I´m thinking maybe it could be possible to detect a download finished, using [DownloadManager API](https://developer.android.com/reference/android/app/DownloadManager), and display a file manager app as a contextual suggestion in the apps list to quickly open file manager.

(The suggested file manager app could either be chosen by the user, or a shortcut to the Android built-in file manager could be used as well - should be possible using `Intent.ACTION_GET_CONTENT`.)

**Comment by adamdjensen** [comment]
Can't you just use open the files via the notification you got?

**Comment by Martin5001** [comment]
> Can't you just use open the files via the notification you got?

Usually not, it just opens the app from which I downloaded the file, not the file.

**Comment by 8bitPit** [comment]
In my opinion, that's also a feature the browser should provide. Afaik both Chrome and Firefox for example open the file when you tap on the notification

**Comment by Martin5001** [comment]
Yes, you're right, this probably wouldn't be impactful enough.
