### ISSUE TITLE
Bug in app drawer

### ISSUE THREAD

**Issue by meninbluu** [8bitPit/Niagara-Issues#1315]
There is a huge gap between the first application and status bar which I am facing while scrolling up in app drawer.

1. Go to app drawer by tapping on "A" alphabet.
2. You'll see a gap between the first app and status bar.

Smartphone (please complete the following information):
 - Device: Redmi Note 8 Pro
 - Android version: MIUI 11, Android 10

Screenshot
![Screenshot_2020-06-15-08-47-55-932_bitpit launcher](https://user-images.githubusercontent.com/66931573/84614836-ee2e2700-aee4-11ea-8cae-2029dce07a5f.jpg)

**Comment by Rod911** [comment]
This gap exists to aid you in reaching the first app while using your phone with one hand.

**Comment by meninbluu** [comment]
Is there setting to remove this gap? I mean it doesn't look good. Thanks in advance
