### ISSUE TITLE
Option to remove gap between the first application in app drawer and status bar

### ISSUE THREAD

**Issue by meninbluu** [8bitPit/Niagara-Issues#1316]
Problem:
The gap between first application and status bar doesn't seems look good. 

Solution:
An option to enable or disable this gap would be helpful.

Screenshot:
![Screenshot_2020-06-15-08-47-55-932_bitpit launcher](https://user-images.githubusercontent.com/66931573/84619999-6223fb80-aef4-11ea-8f5f-7ffa3758adf1.jpg)

**Comment by Martin5001** [comment]
I think it makes sense to have the app list lower on the screen as it makes it easier to reach with one hand on larger screens. But I agree that it doesn't look good with the top space being empty like this.

So I suggest to add a heading "All apps" here similar to what Samsung does with their One UI. (1/3 for heading, remaining 2/3 for interactive elements.) The heading would fade out when scrolling.

This way you wouldn't need an additional toggle, while avoiding the space being empty on large screen phones. (This could be used based on screen size, as smaller screens don't have this issue.)

**Comment by meninbluu** [comment]
Thanks for considering my suggestion. I still think that there should be a
toggle or setting to adjust the gap. Adding "All Apps" heading would look
unpleasant. Rest depends on you.

Thanks in advance.

Regards,
Aditya Roy

**Comment by Martin5001** [comment]
> Rest depends on you.
(It depends on 8bitPit, not me, I was just adding my comment. Sorry if I made this confusing.)

**Comment by 8bitPit** [comment]
@Martin5001 I think the all apps header looks great, maybe we're going add that. @meninbluu I fear a toggle for enabling the padding isn't [impactful ](https://niagaralauncher.helpscoutdocs.com/article/8-niagaras-design-principles) enough.
