### ISSUE TITLE
Home button stopped working completely while in Niagara 

### ISSUE THREAD

**Issue by craPkit** [8bitPit/Niagara-Issues#1317]
**Describe the bug**

[please also see my comment for an addition] 

After using it for a few days, "home to search" (HTS) stopped working for me, completely. Specifically, nothing at all happens when I press home from the launcher's home screen. 

Things that had happened in the day(s) before it broke:
* I enabled Sesame integration using sesame trial. 
* I upgraded sesame to pro. 
* Samsung updated my Note 10+ to the version below

My best guess is Samsung's security update, but really, that's as good as any. 

**To Reproduce**
(for me) 

1. Optionally, disable HTS
2. Enable HTS

(your mileage may vary) 
Sesame integration on/off doesn't make a difference, and neither does "Google search button at the bottom". 

**Things I've already tried** to mitigate the issue, all to no effect:
* restart Niagara (from its settings) 
* restart the phone
* kill all apps 
* uninstall Sesame
* reinstall Sesame 
* clear sesame cache and data 
~~(since there's no Backup and I've configured Niagara's shortcuts and favourites heavily, I refrained from reinstalling/clearing Niagara)~~
* switch from full screen gesture navigation to button navigation (system setting) 

**Smartphone:**
 - Device: SM-N975F 
 - Android version: Build QP1A.190711.020.N975FXXU4CTE9 (Android 10, Samsung One UI 2.1) 
 - Niagara Version: 0.30.3 Pro

**Comment by craPkit** [comment]
Still not working after clearing all of Niagara's and Sesame's data. Home button does nothing, doesn't even nav back to home from alphabetic app list.

**Comment by 8bitPit** [comment]
Thanks a lot for your detailed report. Apologies for the very late reply. Can you reproduce this behavior with other third-party launchers like Nova or Lawnchair?

**Comment by craPkit** [comment]
I just set up Lawnchair (as close to my Niagara setup as I could) to test this. Home button or gesture works as expected with Lawnchair, but not with Niagara.

I also retested with Niagara 0.32.4 (Pro) and with all possible navigation modes (classic Navbar, Samsung gestures, Google gestures). 

Meanwhile, my system has been updated to `Android 10 QP1A.19011.020.N975FXXU6DTH7` / Samsung One UI 2.5

**Comment by 8bitPit** [comment]
Thanks again, I'll look into this.

**Comment by qgauvrit** [comment]
Exact same issue here on my Galaxy Z Fold 2.

System info:
Device: SM-F916B
Android version: Android 10, Samsung One UI 2.5
Niagara Version: 0.32.4 Pro

**Comment by itay2005** [comment]
Exact same think on my galaxy note 9, android 10 one ui 2.1
I have the niagara launcher for a few days and then home button on niagara launcher didn't work, I didnt update my phone at this time, I also tried different versions of the launcher, some of the version I used in past and they was working fine,  but it didn't work. I also tried to change my phone language. 

Sorry of my English if I made mistakes.

Thanks

**Comment by 8bitPit** [comment]
Thank you everyone for your replies. I'm thinking the same as @itay2005 - that was probably a system bug. The navigation buttons/navigation gestures are entirely controlled by the system and a submodule of the preinstalled launcher.

**Comment by craPkit** [comment]
I just upgraded to OneUI 3, and it seems to be working now.

**Comment by 8bitPit** [comment]
Great, thanks for your reply :D
