### ISSUE TITLE
Feature Request : Ability to put the clock and date at the very bottom of the screen 

### ISSUE THREAD

**Issue by barberob** [8bitPit/Niagara-Issues#1319]
*Is your feature request related to a problem? Please describe.*
At the moment I write this, I'm only able to put the clock really close to the bottom of the screen but we can see at least one favorite app

*Describe the solution you'd like*
So, I would love to put the clock at the very bottom, so we would only see the clock, date and weather, which looks soooooo clean.
Looks like an easy feature but I don't know how it is developed. 
I took a picture where I dragged all the way down the list to show you how it would look
like  : 
![Screenshot_20200617-124555](https://user-images.githubusercontent.com/50527053/84890839-38590900-b09b-11ea-9a9c-ef04b3e0cdde.jpg)

While the maximum is actually like this : 
![image](https://user-images.githubusercontent.com/50527053/84892081-3db75300-b09d-11ea-97e7-df19a3a0e068.png)

(Sorry for bad english)

**Comment by 8bitPit** [comment]
Thanks for the suggestion. For now, you could place an empty widget between the clock and app list, this will hide the app

**Comment by topsy-turvy99** [comment]
![Screenshot_2022-10-04-09-25-39-42_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/193731023-1ae4bfbc-ab4f-4a16-814b-dae4905189b3.jpg)

I just tried it out with a blank widget, but it seems the app is still partially visible (which can still be triggered), so thought will report it, just in case it helps 😅

**Comment by 8bitPit** [comment]
Thanks for checking @Amorphous404. We don't plan to support this use case anymore (allowing full screen widgets).
