### ISSUE TITLE
Use Multiple Icon Packs At Once

### ISSUE THREAD

**Issue by ModdedGamers** [8bitPit/Niagara-Issues#1320]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to switch launchers and when I come back to Niagara I have to set a lot of custom icons.

**Describe the solution you'd like**
Make it so there is 1 primary pack and then a list of other packs you would want. The launcher takes all applicable icons from the primary pack and puts them in. Than the secondary packs are searched, in order, for the other icons. If no Icon is found for an app, it is left unchanged.

**Comment by Rod911** [comment]
See #1219
