### ISSUE TITLE
More options to purchase Pro

### ISSUE THREAD

**Issue by immutable-pro** [8bitPit/Niagara-Issues#1321]
**Is your feature request related to a problem? Please describe.**

I have bought a Huawei tablet and I love Niagara Launcher (I already own the Pro version for my OnePlus phone). My tablet lacks of Google Play Store, so although I can install Niagara from an APK (from the Niagara News Telegram) I can't acquire a new licence of Pro, that I would gladly pay for.

**Describe the solution you'd like**

I would like to see a different option to acquire the pro licence, not  bound to the Google Play Store.

**Comment by Rod911** [comment]
Some devices don't come with Google Play Services and Google Play. Niagara Launcher needs them to verify your purchase. You could try MicroG to install a similar but open source service. (Use at your own risk.)
