### ISSUE TITLE
Implement in-app-search from Sesame

### ISSUE THREAD

**Issue by Rod911** [8bitPit/Niagara-Issues#1323]
From [Reddit](https://www.reddit.com/r/NiagaraLauncher/comments/gy898m/this_functionality_is_missing_in_the_sesame/).

Allow user to search using apps using sesame API

<img src="https://i.imgur.com/lzBez6c.png" alt="App search using sesame" />

**Comment by fredskis** [comment]
Are there plans to implement this? 
Proper Sesame integration is a killer feature and what brings me back to Nova every time. 

Usability goes up immeasureably when your workflow is just: 
1. Swipe up
2. Type search
3. Tap Enter to search primary app OR tap icon to app-search (Maps, YouTube, Wikipedia, etc)

Can we donate somewhere to prioritise this feature? 😁

**Comment by 8bitPit** [comment]
With Niagara v1.4, Niagara's search screen now lists the top 3 Sesame in-app search results you've set up.

**Comment by 8bitPit** [comment]
Implemented in v1.4
