### ISSUE TITLE
Icon pack list - show placeholder when loading

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1324]
### Show a placeholder when icons list is loading
This pack has 4000+ icons and it takes quite a while for the list to load.
![Obrázek1](https://user-images.githubusercontent.com/35201200/85199168-caf0e680-b2ed-11ea-970c-a62c35c4e2a9.png)
![Obrázek2](https://user-images.githubusercontent.com/35201200/85199178-d2b08b00-b2ed-11ea-8273-425d82c68980.png)
![Obrázek3](https://user-images.githubusercontent.com/35201200/85199214-0c819180-b2ee-11ea-9454-5cda513b50df.png)
![Obrázek4](https://user-images.githubusercontent.com/35201200/85199216-10adaf00-b2ee-11ea-8f2e-ee5b7879caea.png)

**Comment by 8bitPit** [comment]
Love the idea

**Comment by Montell2099** [comment]
Great idea, and nicely illustrated as well @Martin5001! This would be a dope addition to the icon selection section.

**Comment by 8bitPit** [comment]
Since v0.34, Niagara Launcher now shows you the first icon pack icons instantly; there's no need for a loading indicator anymore 😁
