### ISSUE TITLE
Icon change - show app name

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1325]
I wanted to change icons for all my apps in the home list to letters of alphabet based on their names.
Doing this I noticed it's quite easy to forget which app I'm currently selecting the icon for while searching the icons list.

So my suggestion is to add the name of the edited app to the title ~~or just on top of the list of icons under the title (similarly to the alphabet in "All apps" section)~~. (Edit: Realized the second wouldn't make much sense – scrolling still needed.)

**Comment by 8bitPit** [comment]
Great idea!

**Comment by ssssamstrup** [comment]
Have run into the same problem lots of times, great idea!

**Comment by 8bitPit** [comment]
Added in v0.31
