### ISSUE TITLE
Slow search / search debouncing

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1326]
**Describe the bug**

With version 0.30.x the search feels slower and lags behind the inputs. From the outside it looks like there is debouncing implemented on the inputs or the asynchronous handling is really slow. I'm not using the Sesame integration.

**To Reproduce**

Example. Type search ("fit") and hit enter will open "Finanzguru" instead of "Fit" because the search is slow.

![Screenshot_20200622-161448~2](https://user-images.githubusercontent.com/13085980/85298405-52805600-b4a4-11ea-9235-d86c554b9605.jpg)

After ~ 1s the actual search result is shown:
![Screenshot_20200622-161531~2](https://user-images.githubusercontent.com/13085980/85298496-75ab0580-b4a4-11ea-9848-44ad1a2b629d.jpg)

Therefore it's not possible to type and hit enter without opening intermediate results.

**Smartphone (please complete the following information):**
 - Device: OnePlus 8
 - Android version: 10
 - Niagara: 0.30.3

**Comment by andys8** [comment]
Is there a released version of Niagara where https://github.com/8bitPit/Niagara-Issues/issues/1275 was fixed already but #1326 (this issue) not introduced? I need a usable, fast search bar.

**Comment by 8bitPit** [comment]
Sorry for my late response Andy. I improved debouncing in version v0.31, it will only activate if you type more than four characters and don't used swipe typing.
