### ISSUE TITLE
Swiping back home leaves the Google button mid screen and shades the lower half of the screen

### ISSUE THREAD

**Issue by iamlevik** [8bitPit/Niagara-Issues#1329]
**Describe the bug**
Swiping back home from an app leaves the Google button mid screen and shades the lower half of the screen. If I remove the Google button, doesn't seem to happen.

**Steps to reproduce the behavior:**
Browse on Chrome, be on YouTube and after a couple of minutes while swiping or clicking home button, you'll see Google icon to be misplaced and shades the lower part of the launcher.

**Device: OnePlus 6T
Android version: 10**
Screenshots: ![Screenshot_20200626-110146](https://user-images.githubusercontent.com/48520797/85838688-9cb64f80-b7a2-11ea-8142-8cebab150338.jpg)

**Comment by Rod911** [comment]
Niagara version?

**Comment by iamlevik** [comment]
Version 0.30.3

**Comment by Rod911** [comment]
Supposed to have been fixed in v0.24.

Merging with #1185.
