### ISSUE TITLE
Stackable widgets on home screen

### ISSUE THREAD

**Issue by MetalGrim** [8bitPit/Niagara-Issues#1330]
Add ability to stack widgets of same size on top of each other and allow switching between them with a simple swipe. This way we can keep our home screen clean but still have multiple widgets.

**Comment by ZephyrMathi** [comment]
I don't know the complications in impliment that one but that will be a great adition of feature . Would love to see it

**Comment by 8bitPit** [comment]
Interesting idea, can I ask you what widgets you'd stack on top of each other?

**Comment by 8bitPit** [comment]
And btw, related issue: https://github.com/8bitPit/Niagara-Issues/issues/1165

**Comment by luxcalor** [comment]
> Interesting idea, can I ask you what widgets you'd stack on top of each other?

This idea is a great. I use a 24h clock-like planner and similarly designed 24h clock widget showing various astronomical data. I used to have them side by side in my previous launcher, but there's no going back now, so this scrolling thing would be even better solution. 
![1609899676890](https://user-images.githubusercontent.com/76074147/104191829-b2315500-5426-11eb-8637-daaf25daf2ba.png)

**Comment by 8bitPit** [comment]
We concluded to go for pop-up-widgets instead: https://help.niagaralauncher.app/article/41-adding-multiple-widgets
If everything's working as planned you can add widgets to your apps swipe menu and maybe also to the google button in the future.

Btw your widget looks great @luxcalor your design would fit great on a smartwatch 😁

**Comment by diegolameira** [comment]
Hey, I don't think those workaround neither it's future feature will fill what was requested, and I'm willing to help you guys in development of what would be the best match... I think it would be a stack custom widget like iOS 14 have. And recently was added in beta Action launcher. Google it.

I don't know if I can achieve the development of this feature inside this repo, but I will take a look and if possible I will at least start a pull request.

**Comment by 8bitPit** [comment]
Hi @diegolameira, I'm sorry, we're currently not planning to add swipeable widgets.

**Comment by Nxt3** [comment]
That's pretty disappointing considering Niagara is suited perfectly for stacks of widgets.

**Comment by TFackler** [comment]
After discussion things with the team, we decided to have another look at stackable widgets as we feel like right now this is the most "Niagara-feeling" option to support multiple widgets on the home screen. That's why we are re-opening this issue.

That is to say, no guarantees can be made at this point in time.
If we are going to implement it, the scrolling through widgets would be horizontal rather than vertical to reduce confusion with other scrolling actions on the home screen.

**Comment by TFackler** [comment]
Here is a very good looking proposal from @topsy-turvy99 (from #1879)

https://user-images.githubusercontent.com/96917972/159335843-1edd2732-6251-4e25-afdd-4cc5f6de4c1e.mp4

**Comment by topsy-turvy99** [comment]
> After discussion things with the team, we decided to have another look at stackable widgets as we feel like right now this is the most "Niagara-feeling" option to support multiple widgets on the home screen. That's why we are re-opening this issue.
> 
> Here is a very good looking proposal from @topsy-turvy99 (from #1879)
> 
>  Stackable.Widgets.For.Niagara.Launcher.mp4 
> That is to say, no guarantees can be made at this point in time. If we are going to implement it, the scrolling through widgets would be horizontal rather than vertical to reduce confusion with other scrolling actions on the home screen.

Thank You For Taking Under Consideration, Take Your Time No Worries On That 🙂

Yes, Vertical Scrolling Will Have Issues With Niagara, Horizontal Scrolling We Be Better For Niagara (Samsung Newly Introduced Stack Widgets Does The Same).

Here For Reference: https://www.androidpolice.com/how-to-use-samsung-smart-widgets/

**Comment by missyraja** [comment]
Please make the horizontal scrolling widget a reality both in pop-up folder as well as on the home screen... Since A12 Google has actually made functioning widgets and also encouraged a lot of other apps to refine their widgets as well.  And also for the fact a lot of large screen device have a lot of space for them. Ao it's high time you guys consider it and integrate it in someway into niagara... Hope you guys consider it in future builds

**Comment by thuvasooriya** [comment]
can we have a popup for the default niagara widget. currently sliding through it does nothing. so if we can an option to enable popup for it. we could include additional widgets in there say screen time widget which wouldn't go nicely with any other app popups you would have on your home screen.

**Comment by PankajGautam04** [comment]
Please add widget stack feature to Niagara. I'm waiting for this for very long time.

**Comment by SuperSheykh** [comment]
This is the perfect time to implement this feature. It keeps things tidy as we all love in Niagara while boosting productivity and help from our devices. 
Many if not all the launchers have been or are working on it at this point and time. To me it should be prioritized over all other features right now.

**Comment by luxcalor** [comment]
Agreed. This would be nice. Waiting for this the most.

**Comment by YuenJoshua** [comment]
hope so. That would be great to Niagara!

**Comment by SuperSheykh** [comment]
I'm so happy to see this marked **planned**. You guys are incredible. Thank you Niagara for making us get the best of our devices. ❤️

**Comment by 8bitPit** [comment]
Thank you @SuperSheykh :D

**Comment by p34c3-n-l0v3** [comment]
Great to see this on the list of upcoming things!

**Comment by garvongithub** [comment]
Please support this stackable widgets in the pop ups menu too

**Comment by 8bitPit** [comment]
Released in [v.1.9](https://github.com/8bitPit/Niagara-Issues/releases), popup widgets will follow shortly 😀
