### ISSUE TITLE
ChangeChange the search button browser on the main page 

### ISSUE THREAD

**Issue by j00ao** [8bitPit/Niagara-Issues#1334]
Change the browser of the search button on the main page

**Comment by 8bitPit** [comment]
Thanks for your request @j00ao. You're probably referring to [this issue](https://github.com/8bitPit/Niagara-Issues/issues/142), right?

**Comment by j00ao** [comment]
Yes

**Comment by Maxr1998** [comment]
Please refer to the linked issue for further information then :D
Closing this one.
