### ISSUE TITLE
Paged favourites

### ISSUE THREAD

**Issue by martinpengellyphillips** [8bitPit/Niagara-Issues#1335]
**Is your feature request related to a problem? Please describe.**

I'd like to 'group' favourites by context and switch between those groups easily. For example, apps I use for work vs apps I use personally. I also dislike when the list of apps runs off the bottom of the screen as it breaks the clean feeling of Niagara.

**Describe the solution you'd like**

Rather than run favourites off the bottom of the screen, enforce a hard break and create a new 'page' of favourites. This will maintain the clean look whilst also enabling more logical / contextual grouping of favourites on different pages. Swiping up and down on the list of favourites (or potentially in the empty sidebar) would switch between pages. Niagara would always return to last viewed page (when exiting apps list / search etc) to maintain context. A small dot indicator could be added to indicate current page in the empty left side space, but not essential.

The nice thing here is that it would mostly be a cosmetic change - adding a hard break and scrolling pages of favourites at a time.  

<img src='https://user-images.githubusercontent.com/214338/88153086-d8ef9b00-cbfc-11ea-8dac-2b8edbdd7556.jpg' width='35%' /> <span>Swipe to next page</span> <img src='https://user-images.githubusercontent.com/214338/88153098-dd1bb880-cbfc-11ea-9341-ab2e6fa3b05d.jpg' width='35%'/>

**Comment by martinpengellyphillips** [comment]
To further support a sense of context switching, the widgets on each page could be customisable independently from other pages perhaps? E.g. Date on page 1 opens personal calendar whilst Date on page 2 opens work calendar.

**Comment by 8bitPit** [comment]
Cool idea @martinpengellyphillips! However it also adds a whole new layer to Niagara Launcher's ui, so I can't say yet if this feature will be realized. For your reference, here's also a similar request: #537

**Comment by praveenchandranpk** [comment]
Brilliant idea!

**Comment by luxcalor** [comment]
Great idea

**Comment by 8bitPit** [comment]
Hey @martinpengellyphillips, we concluded not to add different pages for now to keep Niagara Launcher simple; I'm sorry. However, with v1.2, we just introduced folders to categorize your favorites: https://medium.com/niagara-launcher/pop-up-date-4a5d3522df2d. I hope this can help you, too!
