### ISSUE TITLE
Put shortcut apps before notifications

### ISSUE THREAD

**Issue by martinpengellyphillips** [8bitPit/Niagara-Issues#1336]
**Is your feature request related to a problem?**

If I have a lot of notifications for an app, then I have to scroll lots to access a shortcut app in that 'group'. For example, I have 'calendar' inside 'email'. When I have lots of new mails I have to scroll before I can open the calendar. This slows me down and feels like it defeats the purpose of easy quick access (I could scroll the app list faster instead). 

**Describe the solution you'd like**

Put shortcut apps before notifications.

Perhaps also separate shortcuts from notificationss in the flyout panel and allow each to be scrolled independently.

**Comment by 8bitPit** [comment]
I'd say notifications should be ranked higher than shortcuts because they're more urgent. When an app sent you a notification you usually open it because of it. If not, you'd normally swipe away that notification. In either case it makes sense to me to show it at the top.

**Comment by martinpengellyphillips** [comment]
I don't agree on notifications having implicit urgency. I'll regularly have notifications that I don't action straight away, but want to come back to later in the day (so I don't clear them). 

Also, if I want to open an app, then that's more urgent at that time 😉

This is a minor friction point for me, but one I encounter every day. If not addressed I'll eventually either:

a) Turn off embedded notifications in Niagara.
b) Stop using nested apps in Niagara.

So not a big deal, but one that slightly reduces the stickiness of the product for me.

**Comment by 8bitPit** [comment]
> I don't agree on notifications having implicit urgency. I'll regularly have notifications that I don't action straight away, but want to come back to later in the day (so I don't clear them).

For that, I recommend using Android's [notification snoozing](https://android.gadgethacks.com/how-to/bring-back-notification-snoozing-android-10-0206278/) feature. We're also working to integrate notification snoozing into Niagara and are planning for an option to snooze non-urgent notifications automatically.
