### ISSUE TITLE
Change how Navigation gesture bar works

### ISSUE THREAD

**Issue by Sharlimar** [8bitPit/Niagara-Issues#1339]
In the home menu when you want to Swipe to the next app this is how it's implemented:

**Niagara Launcher:** Swipe Left goes to the next app / Swipe Right does nothing 
**Oneplus Launcher / Android:** Swipe Left does nothing / Swipe Right goes to the next app
 
The problem with Niagara is that if you want to smoothly go through the apps, you have to Swipe Left to go to the next app and then change to Swipe Right to go through the apps

It's two diferent moves instead of one type of move

What I suggest is to change to "Swipe Left does nothing / Swipe Right goes to the next app" because you just do Swipe Right's to go through the next apps

Thank you!

**Comment by 8bitPit** [comment]
Hey, apologies for the late reply. Unfortunately we have no control over the recents app screen, you can read more about that here: https://niagaralauncher.helpscoutdocs.com/article/7-gesture-navigation
