### ISSUE TITLE
Apps overlapp in list

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#134]
![image](https://user-images.githubusercontent.com/9284845/45252291-39042d80-b354-11e8-8be3-cc2aa978771f.png)
(provided by BluDragyn)

If you noticed when that happens, pls comment!

**Comment by BluDragyn** [comment]
It happened to me, once, when I first installed a new app (I think it was telegram, but I don't recall), I simply set Nova as my home screen app, and then switched back to Niagara, and all was well.

**Comment by 8bitPit** [comment]
@BluDragyn did it reappear?

**Comment by BluDragyn** [comment]
@8bitPit no, i only experienced the issue once, and never again. And I have since installed and uninstalled quite a few apps.

**Comment by 8bitPit** [comment]
Ok, I believe it's fixed now XD
