### ISSUE TITLE
Keep Media Player on screen all the time

### ISSUE THREAD

**Issue by 1080pixelz** [8bitPit/Niagara-Issues#1340]
The media player widget is well designed and I don't want it to go away after a while when im not listening to music, basically I want the widget on my homescreen at all times.

**Comment by 1080pixelz** [comment]
First off, are you a Niagara dev? I'm sure no one in the team wouldn't try to counter an idea because no idea is a bad idea. This isnt a ridiculous request at all because users who are attracted to music widgets like me know that kwgt widgets have a response delay after clicking the play/pause, previous and next button and the transition sucks. On the other hand, Niagara's music widget looks nice aesthetically, has smooth animation and transition with no delay which they can use to their advantage. I would like a music widget on my screen at all times and I'm sure many others would.

**Comment by Martin5001** [comment]
I wouldn't call it ridiculous – I understand it might look good on some setups – but I agree with @Montell2099 that it wouldn't be much useful – at least I personally wouldn't use it. (Not the dev.)

**Comment by 1080pixelz** [comment]
I understand why it may be a useless feature to many users but think about it this way, they have nothing to lose by adding this feature because im sure there are many people like me who adore the  music widget and would like to keep it on at all times. It's also an easy feature to implement because its simply locking the widget in place (and the album art goes away once the media session ends but the song name and artist(s) is still displayed kinda like the KWGT music widgets) this widget has a lot of potential and is def better than kwgt which is always delayed and laggy. Anyways, at the end of the day its the devs who make the right decision so please niagara developers if you're reading this, it would be really cool to add this feature (small but means a lot).

**Comment by 8bitPit** [comment]
In my opinion, the media widget takes up too much space to be always visible. Moreover, not every media player supports resuming a session after it has ended. On top of that, Android 11 already keeps the media player in the notification shade, so you can also resume it that way.

> I understand why it may be a useless feature to many users but think about it this way, they have nothing to lose by adding this feature

Unfortunately it's not that easy: https://help.niagaralauncher.app/article/8-niagaras-design-principles
