### ISSUE TITLE
App missing from list

### ISSUE THREAD

**Issue by opie4624** [8bitPit/Niagara-Issues#1341]
**Describe the bug**
App "[The reMarkable Companion](https://play.google.com/store/apps/details?id=com.remarkable.mobile)" doesn't show up in my app list or when searching.
Perhaps related to #1212

**To Reproduce**
1. Install "[The reMarkable Companion](https://play.google.com/store/apps/details?id=com.remarkable.mobile)"
2. Scroll to `T`
3. Type in anything that would result in a search hit ie: "remarkable", "companion", etc.
4. Don't see it anywhere

**Smartphone (please complete the following information):**
 - Device: Moto Z4 Verizon
 - Android version: Android 10, July Security Patches

**Screenshots**
![Screenshot_20200803-134200](https://user-images.githubusercontent.com/6883/89236939-cd11ba80-d5a6-11ea-8bba-9c958c89582b.png)

![Screenshot_20200803-134208](https://user-images.githubusercontent.com/6883/89236945-d0a54180-d5a6-11ea-99df-ae4dcb34b9da.png)

**Comment by 8bitPit** [comment]
Thank you for reporting @opie4624. Did you perhaps reinstalled the app? Up to version v0.31 there was a bug that reinstalled sometimes don't show up. We rolled out a fix in v0.31 which is currently in alpha, you can download it [here](https://github.com/8bitPit/Niagara-Issues/releases) or wait around one week to get the update automatically via Google Play.

**Comment by opie4624** [comment]
I didn't reinstall it anytime recently, though I believe the app name changed during one of the latest updates. 0.31 did fix the bug.

**Comment by 8bitPit** [comment]
Great, thanks for letting me know!
