### ISSUE TITLE
Unify Sesame shortcuts icons shape

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1345]
If you use Sesame integration to add contacts as swipe shortcuts, the contact letter icons are circular, but if there's a profile picture, it gets shown in a square. (Don't know if this is a bug or it's just implemented that way, but I'd expect it all to be a same shape.)

(Android 9 on Samsung Galaxy J7)

**Comment by 8bitPit** [comment]
It was quicker to implement it that way, but your suggestion makes totally sense.

**Comment by 8bitPit** [comment]
Fixed in v.0.90
