### ISSUE TITLE
Over Heating while Sesame is running .

### ISSUE THREAD

**Issue by ZephyrMathi** [8bitPit/Niagara-Issues#1346]
When Sesame is running in background my phone is overheating even when idle . once I uninstalled Sesame the overheating stopped . I have not tried installing it again . just wondering if this a problem just for me or anyone experienced this ?

Device :
One Plus 6
Android 10

**Comment by 8bitPit** [comment]
I didn't hear anyone else having the same issue, but Sesame has there one issue repository on GitHub, maybe you can also ask there: https://github.com/SesameCrew/sesame_issues

**Comment by 8bitPit** [comment]
So I'm closing this ticket here, feel free to open one on Sesame's tracker.
