### ISSUE TITLE
Media widget bug

### ISSUE THREAD

**Issue by TheC92** [8bitPit/Niagara-Issues#1348]
v0.32.1

Even if you turn off the media widget option, the media widget appears when you clear the music notification and play it again.

https://drive.google.com/file/d/1AXhWv4G0s2zKtShotVg2yPCAr5gz78rI/view?usp=drivesdk

**Comment by Montell2099** [comment]
The same bug is happening to me, and I don't know what might be triggering it. Restarting the launcher doesn't make a difference, checking & unchecking the "show media widget" option only works temporarily.

![Screenshot_20200831-151235](https://user-images.githubusercontent.com/43126233/91724497-af337780-eb9d-11ea-8798-03dab18f19a4.png)
![Screenshot_20200831-151245](https://user-images.githubusercontent.com/43126233/91724506-b2c6fe80-eb9d-11ea-8f18-fa5f8d9de239.png)

**Comment by 8bitPit** [comment]
Thanks for the report :)

**Comment by 8bitPit** [comment]
Fixed in v.0.32.2
