### ISSUE TITLE
Settings - group search related options together

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1349]
Currently if you go to the "Features" section, it is divided by these main labels:

- Home
- General
- Tips and tricks.

Also there are 3 individual settings somehow related to search - Press home to search, Google search and Sesane search integration. These are under different labels (Home and General) - I suggest grouping them together, maybe under a separate Search label, so it would be:

- Home
- Search
- General
- Tips and tricks

**Comment by 8bitPit** [comment]
The feature tab is a bit of a mess right now, I agree.

**Comment by 8bitPit** [comment]
I reordered the feature settings in v0.33. They should now be a little bit more organized.
