### ISSUE TITLE
Settings - bottom flyouts don´t respond to back button

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1350]
I just noticed the new bottom flyouts do not respond to tapping back button - instead of closing, it gets you back to previous settings section, while the flyout is still shown in the foreground.

**Comment by 8bitPit** [comment]
Thanks, this is going to be fixed in v0,32.1.

**Comment by 8bitPit** [comment]
Fixed in v.0.32.2
