### ISSUE TITLE
Agenda does not follow 24h clock settings

### ISSUE THREAD

**Issue by bartlibert** [8bitPit/Niagara-Issues#1351]
**Describe the bug**
My device is configured to use 24h clock notation (as is the default in a lot of non-English speaking countries), but the new "Your agenda" widget still shows the appointments in a.m./p.m notation.

**To Reproduce**
1. Set your device to use 24h clock notation (or use a locale where this is the default)
2. Click on the date in the Niagara widget
3. Look at an appointment in your agenda
4. Observe it is not using 24h notation

**Smartphone (please complete the following information):**
 - Device: Oneplus 7
 - Android version: Android 10

**Comment by 8bitPit** [comment]
Thanks, this will be fixed very soon.

**Comment by bartlibert** [comment]
I've seen that this was changed in the new version, but it's still not correct. The am/pm indication is gone, but the hours are not using the 24h format. E.g. an appointment starting at 1 p.m. is shown as "01:00" instead of "13:00".

**Comment by 8bitPit** [comment]
Fixed in v.0.32.3
