### ISSUE TITLE
Home app issue

### ISSUE THREAD

**Issue by Sba12** [8bitPit/Niagara-Issues#1353]
The system keeps forgetting which is the home app and every now and then when pressing home it asks which home app to use. Even if I keep telling to set Niagara as always it keeps coming out.

Niagara version 0.32.1
Device: OnePlus 3 - Oxygen Os 9.0.6

**Comment by 8bitPit** [comment]
Thanks for the report. Does this also happen when using other third-party launchers?

**Comment by Sba12** [comment]
To my recalling it never happened with other launchers like Google pixel
launcher and Nova.
Also I forgot to mention that this problem occurred only with the latest
version on Niagara, it never happened before.
Also with this update notifications stopped working like they used to, I
excluded Niagara from battery optimisation settings and now they work fine
but the other problem remains nonetheless.

**Comment by 8bitPit** [comment]
I believe on some devices the preinstalled launcher launches when a third-party launcher has been stopped after an update. I think there's little we can do to fix it though.
