### ISSUE TITLE
Full day appointments in agenda not found when clicking

### ISSUE THREAD

**Issue by TomDeSmet** [8bitPit/Niagara-Issues#1354]
**Describe the bug**
Clicking full day appointments in the agenda widget gives a 'could not find appointment' notification.

Working with 0.32.2

**To Reproduce**
1. Activate agenda widget option from Niagara
2. Click on agenda
3. Click on a full day appointment

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - Android version: Android 9

**Comment by 8bitPit** [comment]
Hi, thanks for the report. It seems to work with Google Calendar, can I ask you what calendar you're using?

**Comment by TomDeSmet** [comment]
I'm using Google Calendar as well (v 2020.32.0-325695287-release). Haven't got any other calendars installed.
I can see the transition for a few milliseconds and then the error pops up and the transition is gone.

**Comment by 8bitPit** [comment]
Oh okay. I tweaked some stuff in the last version I just released (v0.32.3), can you please check if that solves the issue?

**Comment by TomDeSmet** [comment]
Fixed! Superb. Really like this launcher!

**Comment by 8bitPit** [comment]
Great, thanks for letting me know and thank you for the kind words :)
