### ISSUE TITLE
Open calendar app when click on date

### ISSUE THREAD

**Issue by romavonk** [8bitPit/Niagara-Issues#1358]
When I click on the date in version 0.32.3 a calendar widget is openen instead of the chosen calendar app.
When I want to open the calendar app, I have to scroll all the way down and click "^" to open the calendar app.

Can you please make it possible again to open the calendar app directly?

When you use the "schedule" view in Google Calendar, is looks almost the same as the widget.
But because your in the app, ton's of options are available. 

![google-calendar](https://user-images.githubusercontent.com/49060089/92603146-42ac2d00-f2af-11ea-9b34-a7444469f6a9.jpg)

**Comment by 8bitPit** [comment]
Hi @romavonk, you can already switch back to the old method of opening the calendar, here's how: https://niagaralauncher.helpscoutdocs.com/article/76-calendar-faq****

**Comment by romavonk** [comment]
Great, thanks!

Verzonden vanaf mijn mobiel

Op wo 9 sep. 2020 21:49 schreef Peter Huber <notifications@github.com>:
