### ISSUE TITLE
Google Button

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#136]
A floating action button in the bottom right corner (in favorites) instead of a search bar.

Taping it opens Google quick search,
long pressing it opens the Google app itself.

![screenshot_20180908-155601](https://user-images.githubusercontent.com/9284845/45254882-10922880-b380-11e8-8352-9b98f1cfeaa7.png)

**Comment by 8bitPit** [comment]
Opinions?

**Comment by Felvesthe** [comment]
It's good, but with option to disable if someone doesn't use Google.

**Comment by GittyMac** [comment]
I really like that.

**Comment by 8bitPit** [comment]
@Felvesthe Yes, it can be disabled.

**Comment by pablomeza10** [comment]
I really hope that button is coming soon 😂

**Comment by Shinra04** [comment]
I think it's a good way to keep things original and quick. Right corner will be for Google only then.
Can it be possible to make the press and hold action open news feed tab of Google app. Or a double tap would be better for that.

**Comment by zamber** [comment]
Cool feature. Any plans to support other search providers, like DDG?

**Comment by 8bitPit** [comment]
@zamber not for now, since there is no quick box / quick search mode for DDG (I think?)

**Comment by 8bitPit** [comment]
The feature is implemented, I'll leave it open for discussion for a  few days though.

**Comment by rastamanjohn** [comment]
Just enabled this, it's dope, I would suggest to automatically not suggest Google app in frequent if this is enabled. (Same for clock and calendar, dunno if that's already implemented)

**Comment by 8bitPit** [comment]
@rastamanjohn good idea! It is not implemented yet, but the usage algorithm ignores clicks on the date/time view & Google button.

**Comment by silpack69** [comment]
assistant instead of search would be better
