### ISSUE TITLE
Using other calendars than the Google Calendar in the widget

### ISSUE THREAD

**Issue by AndiWebred** [8bitPit/Niagara-Issues#1361]
The calender Niagara Widget works fine with the Google calendar app. Which I dont use. I use the calendar from simplemobiletools. I can open the app via the widget, but the widget wont show my dates.

It would be nice, if you can choose, which app the widget uses to present the dates.

But I can understand, of this request is a bit too special.

**Comment by 8bitPit** [comment]
I'm afraid simplemobiletools has to implement Androids content provider API to let Niagara Launcher have access to the apps calendar: https://niagaralauncher.helpscoutdocs.com/article/76-calendar-faq
