### ISSUE TITLE
Shading issue

### ISSUE THREAD

**Issue by Peaulixs** [8bitPit/Niagara-Issues#1362]
Shading issue.. Pixel 3 Android 11 Niagara 0.32.4.. Niagara bug or Android 11 bug?

![Screenshot_20200913-213517.jpg](https://user-images.githubusercontent.com/62362754/93035269-8cc44400-f60a-11ea-821b-955ca13bf222.jpg)

**Comment by 8bitPit** [comment]
Thanks for reporting @Peaulixs :D

**Comment by 8bitPit** [comment]
Fixed in v.0.33
