### ISSUE TITLE
Stopwatch shortcut doesn't start automatically

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1363]
While using Android 10 the stopwatch shortcut both opened _and started_ the stopwatch instantly. Now on Android 11 it only opens up the stopwatch, but you need to start it manually.

Is this something that you as a developer can adjust, or is it simply system-based?

Cheers!

**Comment by Montell2099** [comment]
Seems like they have made some adjustments, now it starts automatically again. Yay! 🎈

**Comment by 8bitPit** [comment]
Ah, great :)
