### ISSUE TITLE
Separate weather widget from calendar, like before.

### ISSUE THREAD

**Issue by meduzen** [8bitPit/Niagara-Issues#1365]
I’m a Niagara Pro user who’ve just updated the app. I wish there was a toggle to have the weather widget behave as before ([as described in this article](https://medium.com/niagara-launcher/hows-the-weather-5ecf3b183b0e)).

The new weather widget behaviour is a downgrade for users who don’t care about the calendar because:
- There’s no “more” link anymore to go to Dark Sky.
- The weather icon is on top of the home screen, and the thumb has now to move to the bottom of the screen to navigate in the weather, which is far from the icon and less practical than having it more in the middle of the screen.
- It now requires to scroll down in order to see day+2 forecast.

**Comment by 8bitPit** [comment]
Hi @meduzen, while we don't offer the old weather dialog design anymore, you can separate calendar & weather:

>  You can disable Niagara's calendar agenda that will open up when tapping on the date below your favorites. To to that enter the hidden command "/legacycalendar" (entering it a second time will toggle legacy mode off again). Here's how to execute hidden commands. To access Niagara's weather forecast, you can hold on the date, that will now open your agenda & weather forecast. If you don't want to see your calendar events there and also not the reminder that you can see them there, deny Niagara Launcher the calendar permission and tap on "don't ask again" or "deny forever" when asked.

By the way, you can still access Dark Sky's detailed weather forecast by taping on the dates. Hope that helps.
