### ISSUE TITLE
Google calendar reminders in at a glance widget

### ISSUE THREAD

**Issue by TomDeSmet** [8bitPit/Niagara-Issues#1366]
Can you show Google calender reminders in the at a glance widget? They don't show up now (not even as a +n).

I've read in other posts that it is cumbersome to integrate to do apps but I guess reminders from calendar is doable as you already use the api for the appointments?

Maybe next to showing then as upcoming (just treat them as an appointment in the text field) you could add an icon + number next to the +1 to indicate the number of reminders for today.

**Comment by 8bitPit** [comment]
Unfortunately, Google Calendar doesn't share reminders via Android's calendar API: https://niagaralauncher.helpscoutdocs.com/article/76-calendar-faq
