### ISSUE TITLE
Add birthdays in calendar widget

### ISSUE THREAD

**Issue by neyb** [8bitPit/Niagara-Issues#1367]
Niagara widget support now calendar entries, but I cannot see birthday in it.

So maybe showing birthdays like calendar entries would be cool.

Maybe birthday is more related to contact than calendar and that s why there are not shown.

**Comment by 8bitPit** [comment]
Hi @neyb, birthdays are already supported in Niagara Launcher, at least if you're using Google calendar. Unchecking "Birthdays" and then checking it again in Google Calendar can help (You can find the option in Google Calendar when you tap on the menu icon at the top light and scroll down the menu that opens). Moreover, tapping on refresh (also on Google Calendar, accessible through the three dots at the top right) could also fix it.

**Comment by neyb** [comment]
Hi. Sorry for the delay.

I tried what you suggested but still I cannot access them.

I actually fix it unchecking the "contact" calendar and checking it again. Do it's probably a niagara bug, I guess.

Thx

**Comment by 8bitPit** [comment]
Thanks for letting us know. Can I ask you from where you unchecked the contact calendar? Did you check the checkbox in Niagara Launcher or in calendar app?
