### ISSUE TITLE
I paid for the pro version. Changed phones and can't use my pro features

### ISSUE THREAD

**Issue by leolopez2020** [8bitPit/Niagara-Issues#1368]
I bought Niagra Launcher Pro version when I had a Google Pixel 4 XL which was running whatever the latest version of Android was available in mid 2020. Then I had to switch phones, and I am signed in to the account i purchased the pro version in. I am now using a Galaxy S10 running on Android 10. I see that on my purchase history I still have proof that I have bought it on the email I'm signed into. I am signed in to more than one google account. But the one I have selected on the play store is the one I did purchase the pro version in. So my concern is why can't I make use of these features if nothing much has changed except the phone? I would really like to not have to change launchers because of it. I would 
really appreciate an explanation or a fix to this.

**Comment by 8bitPit** [comment]
Hey @leolopez2020, I'm very sorry for the issue. I hope following these steps can help: https://niagaralauncher.helpscoutdocs.com/article/29-lost-access-to-niagara-pro

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
