### ISSUE TITLE
Homescreen notifications enables media player

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1369]
When ticking the box for "Homescreen notifications" the media player appears as well. Tried it several times with the same results.

![Screenshot_20200921-145942](https://user-images.githubusercontent.com/43126233/93770736-e507d100-fc1c-11ea-932c-14d77ba41b24.png)
![Screenshot_20200921-145952](https://user-images.githubusercontent.com/43126233/93770707-d5888800-fc1c-11ea-9c89-2e982d6c2de9.png)

Also, is there no way any more to control the spacing between the Niagara widget & where the favourites start? I really miss that functionality, I think it's jammed in too close together nowadays.

**Comment by 8bitPit** [comment]
Thanks for reporting :)

**Comment by 8bitPit** [comment]
Btw, you can still move favorites by opening Niagara's settings and tapping on Features > Niagara widget > Move widget

**Comment by Montell2099** [comment]
Yes, I'm aware of this. I was talking about the padding between the Niagara Widget & where the favourites list starts.

**Comment by 8bitPit** [comment]
Sorry, my mistake. We're not planning to add an option for changing the padding between the widget and favorites, however, we slightly increase it for everyone.

**Comment by ajeeshed** [comment]
> Sorry, my mistake. We're not planning to add an option for changing the padding between the widget and favorites, however, maybe we slightly increase it for everyone.

Please give the same padding for media player widget and favourites also. Don't look that good when they are so close. Thanks

**Comment by 8bitPit** [comment]
@ajeeshed for now, we and most of our users I think are quite happy with how it looks, we currently don't plan on changing it.

**Comment by 8bitPit** [comment]
Because the media widget is currently not supported if embedded notifications are deactivated, the media widget toggle turns off itself if the notification toggle gets deactivated. That's why it will also turn on itself if the other is also turned on.
