### ISSUE TITLE
Show status bar longer

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1371]
When using the pro version & having the status bar hidden, it would be pleasant to have the status bar show up for just a _few_ more seconds, before it disappears again, when doing a tiny swipe down.

I have a hard time taking in all the info during the quick appearance of the status bar, but maybe it's just me.

**Comment by 8bitPit** [comment]
Agreed, either showing it longer or keeping the status bar visible if you don't let go with your fingers could be helpful.

**Comment by Montell2099** [comment]
That would definitely be a nice adjustment to this function, great idea.

**Comment by luxcalor** [comment]
> keeping the status bar visible if you don't let go with your fingers could be helpful.
 
Came here to suggest this. Would be really helpful.

**Comment by topsy-turvy99** [comment]
Now the status bar is visible for 5 sec with a light swipe down gesture, not sure which version pushed the changes, so ig the issue is fixed now 👍

**Comment by Amorphous404** [comment]
@8bitPit
