### ISSUE TITLE
Ability to display certain apps during certain time. 

### ISSUE THREAD

**Issue by vovakenih** [8bitPit/Niagara-Issues#1372]
For example, people might use meditation or exercise apps only in the morning, and a reading app only in the evening. It would make life so much better if those (and other) types of apps were displayed only during a certain time frame during the day and hidden during the rest of the day to declutter and simplify the main screen.

**Comment by 8bitPit** [comment]
Thanks for your suggestion @vovakenih. We plan to make this possible by integrating Tasker or other automation apps like Automate: https://github.com/8bitPit/Niagara-Issues/issues/786

**Comment by vovakenih** [comment]
Thank you for building the most flowless android experiences! I can't wait to try those integrations.

**Comment by 8bitPit** [comment]
Thank you very much :D

**Comment by Amorphous404** [comment]
- Merged with #786
