### ISSUE TITLE
MIUI: Time *time* is shown twice. There is time in the notification panel and then there is time in the Nigara home. as well

### ISSUE THREAD

**Issue by kaos1180** [8bitPit/Niagara-Issues#1373]
**Describe the bug**

**To Reproduce**
1. Go to 'Home of Nigara Launcher'
4. You should be able to see that the *time* is shown twice. Basically, in MIUI on its default launcher when you are on a page of apps which has clock widget, the top on the notification time automatically disappears, i don't know much but i hope that is easy to implement in Nigara, and no I am not talking about the time which appears when i bring the notification shade down, Much love.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - Android version: Android 9, MIUI 11

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Unfortunately we can't tell the system to just hide the clock in the status bar (without root privileges). However, you can hide Niagara's larger home screen clock (Settings > Features > Niagara widget > and disable "Show clock". Moreover, you can also hide the whole status bar with Niagara Pro: https://medium.com/niagara-launcher/niagara-pro-even-cleaner-4448f55b5571
Hope this helps.
