### ISSUE TITLE
At-a-glance upcoming event time until is misleading

### ISSUE THREAD

**Issue by dgunay** [8bitPit/Niagara-Issues#1374]
**Describe the bug**
When I have an event coming up, the "in N hr" bit shows as the amount of hours rounded down to the nearest hour, which makes it seem like I have much less time than I really do.

E.g. I have a meeting at 2 pm, and it is currently 12:05pm. I have much closer to 2 hours but the at a glance widget tells me I have 1.

**To Reproduce**
1. Schedule event
2. Wait until 1hr and 55 minutes until the event

**Smartphone (please complete the following information):**
 - Samsung Note 8 SM N950U
 - Android 9

Screenshot

![Screenshot_20200929-120459_Niagara Launcher.jpg](https://user-images.githubusercontent.com/16074091/94604647-d50b7500-024c-11eb-9b2b-e709482c1226.jpg)

**Comment by Rod911** [comment]
I believe this was intentional, the remaining hours are rounded _**down**_.

**Comment by dgunay** [comment]
In that case, I think it would be nice if that behavior were configurable or could say something like "1hr 55m". I personally find the rounding-down behavior confusing and occasionally a little stressful before realizing I have more time than it says. Consider it a feature request I suppose.

**Comment by 8bitPit** [comment]
I added an explanation to our [calendar faq page](https://niagaralauncher.helpscoutdocs.com/article/76-calendar-faq): 
> ### The time until an event occurs is slightly off
> For example if an event is one hour and fifty minutes away, Niagara Launcher will show in 1h, because in general, time spans are rounded down if they get rounded, like your age. Android does this as well (e.g. when displaying for how long a notification is the notification shade).

However, as you suggested, we may display the exact event time instead of the time until the event occurs in the future.

**Comment by mrtrevelyan** [comment]
As someone who also just got stressed out by the rounding down of the event (on an otherwise very calming launcher!), I'd like to add my support for an option for the calendar to show exact event time - great idea!

**Comment by 8bitPit** [comment]
Niagara Launcher will show the absolute event time in version 0.34.0 and onwards.

**Comment by 8bitPit** [comment]
And thank you very much for pointing that out :D

**Comment by dgunay** [comment]
No problem, thank you for addressing this.

**Comment by real-mizuya** [comment]
Oh No, I really loved this feature 😭 can you make this optional? I would love to see how many hours and minutes are left until the next event starts. Can you make it possible to show both? Starting time and time until it begins? 🤔

**Comment by 8bitPit** [comment]
@real-mizuya I fear that showing both hours and minutes would take up too much space. Events that start in less than an hour will show the minutes left to the start date.

**Comment by real-mizuya** [comment]
Thank you for the information. Can you still add the option to see both? People don't have to activate it. It would be really cool 😍

Thank you so much for this amazing launcher and all your work and Support! ❤️

**Comment by 8bitPit** [comment]
Thank you very much @real-mizuya. We're trying to keep the number of options/toggles as low as possible for the sake of keeping Niagara Launcher simple. Here's why: https://help.niagaralauncher.app/article/8-niagaras-design-principles
