### ISSUE TITLE
Icon size smallest after deactivating ultra battery saving mode Note 20 Ultra 5G

### ISSUE THREAD

**Issue by MorningstarPhoenix** [8bitPit/Niagara-Issues#1375]
**Describe the bug**
Before turning on the ultra battery saving mode on Galaxy Note 20 Ultra 5G icon and text size in Niagara are normal. After turning on and then off said mode, icon and text size defaults to smallest.

**To Reproduce**
1. Activate ultra battery saving mode
2. Turn off said mode
3. See error

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra 5G
 - Android version: Android 10

**Screenshots**
Can't upload now

**Comment by 8bitPit** [comment]
Thanks for reporting @MorningstarPhoenix!

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1318
