### ISSUE TITLE
Turn off search button on app screen

### ISSUE THREAD

**Issue by rob4jen** [8bitPit/Niagara-Issues#1376]
**Is your feature request related to a problem? Please describe.**
I don't use the search button ever but frequently assume tap it by mistake. 

**Describe the solution you'd like**
A simple option to turn it off would be great. I couldn't find one. If it's there sorry about the duplicate. 

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by Rod911** [comment]
The Google 'G' button or the home button? Both can be disabled from the settings.

**Comment by rob4jen** [comment]
The search button on the apps screen.




________________________________

**Comment by Rod911** [comment]
As of now, the search button can only be hidden on the favourites list. And there are no plans right now to disable it.
