### ISSUE TITLE
Search Button Adjustment

### ISSUE THREAD

**Issue by BornabeWylde** [8bitPit/Niagara-Issues#1379]
**Using Home Button as the Search isn't working well with Gesture Navigation.  Google Pixel 4**

**Solution Suggestion**
Would love to have the Search Button not just in the Apps List, but available as an option on the Home Screen.  Could implement a Press once for Search (Sesame Search) and Press 'n Hold for Google if both are enabled.

Another good option may be to have the Search (Sesame Search) come up with the Swipe Up gesture, similar to how the Notification Shade comes down with Swipe Down.  In this instance we could go full minimalist and not have it show in the Apps listing or anywhere if the gesture swipe up is enabled.  This would be my favorite implementation.

Added Note:  Could we please remove the word 'apps' from the Search Bar at the top if we're using Sesame?

**Comment by jardrog** [comment]
I read in the notes on sesame integration that swipe up to launch sesame was being thought about already, I just wanted to voice that I'd love this option as well

Another thought I had would be an option to have a "minimalist" icon for sesame search just like the Google search that is already included with Niagara

Love Niagara launcher already, thanks for all the work you guys do!

**Comment by 8bitPit** [comment]
Thank you both guys! We're planning to make the Google button customizable (and 'rebrand' it to Niagara button or something along those lines): https://github.com/8bitPit/Niagara-Issues/issues/300
It might also get a Sesame logo if the user chooses bind the button to Niagara's search and Sesame is installed. 

About the empty search box text "Search apps": while it's true that you can search way more stuff with Sesame, I think adding a second phrase (and translating it) is unnecessary, because I think the term does still make sense.

**Comment by BornabeWylde** [comment]
A customizable button there would be AMAZING!!  Shrinking it a bit would be perfection!  I'm not really worried about it saying Search apps even if Sesame is on so that's fine to keep it as it is, unless you're ok with just renaming it to just Search and then it applies to anything you search from it no matter what's installed, that would be nice and a little more minimalistic.

I think having the button as an option to choose Google, Sesame or Niagra logo would be great.

**Comment by 8bitPit** [comment]
The Google button on the bottom right is a [Floating action button](https://material.io/components/buttons-floating-action-button) and it's size is kind of standardized. For consistency amongst other apps, I'd say it's better to keep it as it is.

**Comment by 8bitPit** [comment]
Merged with #300
