### ISSUE TITLE
Back button on home page

### ISSUE THREAD

**Issue by pankaj89** [8bitPit/Niagara-Issues#138]
Hello,

I am using Version 0.2 build 6, in Pixel with Android Pie, here always back button is visible on home screen. I think because of this any incoming call is always shows in dialog from top, not on full screen.

Please solve it.

**Comment by 8bitPit** [comment]
Hey,
Android does not let you remove that, I am sorry. I can assure you that this has nothing to do with your incoming calls though.

**Comment by pankaj89** [comment]
Okay got it actually in default launcher there is no back button but i checked other launchers also back button is there in other also. 
regarding call, when phone is in sleep mode it shows in whole screen and in awake position it shows dialog regardless of launcher we used.

No problem!!

Thanks for this awesome launcher.

**Comment by 8bitPit** [comment]
You're welcome.
