### ISSUE TITLE
Spacing and position of widgets

### ISSUE THREAD

**Issue by Raeigor** [8bitPit/Niagara-Issues#1380]
Hello,

I would like to see added the possibility to space as much as wanted the Niagara or external widget with the app list. If possible, i would also like to be able to choose which widget goes first, where the media player appears (ex : between 2 widgets) and the possibility to leave a blank space when not playing music, that the media player will fill up when listening to a song.
Hope you understood,

Thank you !

**Comment by 8bitPit** [comment]
Hi @Raeigor, we don't plan to make the widget position and spacing completely customizable, however, we'll add the option to replace Niagara's clock with the widget (the widget will be shown above the date & media player) and increase the spacing between the date and the first app or the media player.

**Comment by 8bitPit** [comment]
Related: https://github.com/8bitPit/Niagara-Issues/issues/1355
