### ISSUE TITLE
Add shortcuts for search & calendar agenda

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1381]
This allows the user to also launch search & calendar agenda from favorites or from third-party-apps (like KLWP/KWGT).

**Comment by CerberusCode** [comment]
Thanks. This is a useful featureThanks. This is a useful feature

**Comment by Shaheer0983** [comment]
Yes absolutely

**Comment by xuko** [comment]
Any plans to develop this feature? It would be very useful

**Comment by 8bitPit** [comment]
Here's an update: We don't plan to make real shortcuts for opening search and the agenda, however we already added these actions to the Niagara button and you can open Niagara's agenda via KLWP: https://help.niagaralauncher.app/article/59-klwp-integration

**Comment by Amorphous404** [comment]
Will it be worth listing Niagara as device assistant, so that the user can call Niagara search from any app?
https://github.com/8bitPit/Niagara-Issues/issues/2040#issuecomment-1235774461

**Comment by 8bitPit** [comment]
@Amorphous404, isn't the home button / home gesture almost doing the same thing?

**Comment by Amorphous404** [comment]
I mean with the assistant feature, one doesn't have to go to the favorites/homescreen page to call the Niagara search

**Comment by Amorphous404** [comment]
https://user-images.githubusercontent.com/96917972/208619536-679a0f96-d3ed-4b13-b391-1a66c5817349.mp4

**Comment by 8bitPit** [comment]
Gotcha, thanks for clarifying. Because our launcher doesn't heavily focus on keyboard-based search, I'd say the feature is not completely matching Niagara's design.

**Comment by Amorphous404** [comment]
Okay, No worries :)
