### ISSUE TITLE
Configurable pull down action

### ISSUE THREAD

**Issue by DavidMulder0** [8bitPit/Niagara-Issues#1382]
Feature request
=============
Right now a pull down shows notifications. I would love if a pull down could be configured to trigger the app search. My wife has an iPhone and the 'pull down to search' action feels surprisingly natural.

Context
=======
When using button navigation it's easy to trigger search using a double tab of the home button, however this convenience is lost when switching to some gesture navigation systems (at least on mine the home gesture seems to be disabled in the launcher). The result is that getting to the app search takes far too many steps.

---

And let me just say: thank you for your amazing work on this launcher. Still haven't upgraded to pro as I am not using the weather or calendar functions anyway, but I love your work so much I think this is going to be the first app I am going to buy in years. Point is: good luck and thanks!

**Comment by Martin5001** [comment]
I'd definitely use this. And it would really fit nicely with the search opening animation coming from top. 👍

**Comment by Martin5001** [comment]
Also an idea: maybe two-fingers swipe could be used in addition to single-finger swipe, so you could use one gesture for notifications and the other for search.

**Comment by 8bitPit** [comment]
Thanks for your suggestion David. While I don't want to make gesture in Niagara Launcher customizable as of right now, the swiping *up* might open Niagara's search in the future, see: #122

**Comment by 8bitPit** [comment]
@Martin5001 I don't want to add two-finger gestures, because everything in Niagara Launcher should be accessible by using your phone just with one hand.

**Comment by DavidMulder0** [comment]
@8bitPit Completely understand the 'danger' of allowing too much configuration. Is there any way you would recommend to quickly access the search on devices that do not allow a double home gesture?

From a UX point of view I do have to also note that the search comes down from the top (just like notifications), so a pull down feels more 'correct' there. Additionally the favorites list starts at the top, so a pull down can always be recognized, whilst a swipe up would require somehow differentiating between scrolling down and triggering the gesture. 

The way I personally see it is that the current swipe down is extremely redundant, as all relevant notifications are already on my favorites list. Obviously that's not the case for those who only put 3 or 4 apps on their favorites, but based on most people who share their home screens it seems to be the case. Once folders arrive this will probably become even more true (assuming folders will 'merge' notifications from all apps in a folder). 

Anyway, just my 2cts xD . Still understand the impact of too much configuration options, so yeah, good luck with the development and keep safe 🙂 .

**Comment by ajeeshed** [comment]
> @8bitPit Completely understand the 'danger' of allowing too much configuration. Is there any way you would recommend to quickly access the search on devices that do not allow a double home gesture?
> 
> From a UX point of view I do have to also note that the search comes down from the top (just like notifications), so a pull down feels more 'correct' there. Additionally the favorites list starts at the top, so a pull down can always be recognized, whilst a swipe up would require somehow differentiating between scrolling down and triggering the gesture.
> 
> The way I personally see it is that the current swipe down is extremely redundant, as all relevant notifications are already on my favorites list. Obviously that's not the case for those who only put 3 or 4 apps on their favorites, but based on most people who share their home screens it seems to be the case. Once folders arrive this will probably become even more true (assuming folders will 'merge' notifications from all apps in a folder).
> 
> Anyway, just my 2cts xD . Still understand the impact of too much configuration options, so yeah, good luck with the development and keep safe 🙂 .

It's also a fact that the notification panel is accidentally opened while swiping down which seems to me as totally inconvenient. Atleast make an option to disable the pull down gesture because the current one is causing issue while scrolling through favourite list and search results. I totally agree with @DavidMulder0 here

**Comment by 8bitPit** [comment]
Thanks @DavidMulder0 😀

> @8bitPit Completely understand the 'danger' of allowing too much configuration. Is there any way you would recommend to quickly access the search on devices that do not allow a double home gesture?

Yes, you'll be able to use the new swipe up gesture even when your firmware doesn't allow you to take use of "press home to search". 

>  I do have to also note that the search comes down from the top (just like notifications), so a pull down feels more 'correct' there. 

Yeah, but the keyboard pops up from the bottom, so I think it's a tie 😉

> current swipe down is extremely redundant, as all relevant notifications are already on my favorites list. 

I for example don't use Android's notification shade to check notifications but to toggle quick tiles, change the brightness or open settings.

@ajeeshed 

> It's also a fact that the notification panel is accidentally opened while swiping down which seems to me as totally inconvenient.

In that case I think it's better to tweak the gesture speed threshold at which the shade opens.

**Comment by teneko** [comment]
> Thanks for your suggestion David. While I don't want to make gesture in Niagara Launcher customizable as of right now, the swiping _up_ might open Niagara's search in the future, see: #122

Well, you now how swiping up feels like? I first have to swipe up, then I need to to be sure having swiped up until I cannot, and then I have to swipe again to show the app search. This is quite user unfriendly. I need a faster way.

When "working" with the notification shade, I _always_ have to work with my left hand, so a fast right hand swipe down make no sense, when I cannot navigate the navigation shade with my right hand...

So in the end of the day, the swipe down gesture won't be used and so I ask the same question as the issuer, can you please make the swipe down customizable?
