### ISSUE TITLE
Select custom icon dialog/sheet: Show which icon pack is currently selected

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1383]
First and foremost I would love to see the introduction of a minimalistic text indicating which icon pack the current icon is from, if that's feasible. Or perhaps a tick icon ✅ in the list, right beside the name of the icon pack from where the currently selected icon is from. 

Since we cannot do any form of backups of our custom icon setups, it would at least be somewhat helpful to know which icon pack the current icon is located from.

Secondly, on my Pixel 2 (non-XL) with 3-button navigation I can _barely_ click the "**Get more**" link. Some more padding in the bottom perhaps to make it compatible with smaller screen-phones using the 3-button navigation.

As you can see in the screenshots, the whole text is covered by the navigation bar and if I'm lucky I am just able to click the placeholder for the link.

![Screenshot_20201014-151758](https://user-images.githubusercontent.com/43126233/95994423-92db5980-0e30-11eb-97e5-d2815b5ca733.png)

![Screenshot_20201014-145846](https://user-images.githubusercontent.com/43126233/95994405-8a831e80-0e30-11eb-8940-ca6fbf156186.png)

**Comment by 8bitPit** [comment]
As always, thanks for report and your feedback @Montell2099. We already fixed the bottom padding bug, a patch will roll out soon.  I also like the idea of indicating somehow which icon pack is currently being used. In general, I think there's a lot of stuff we can improve when selecting custom icons.

**Comment by Montell2099** [comment]
Thanks for your quick and detailed reply! Always a pleasure conversating about details as these with you. Great to hear that the bottom padding is already patched and ready to be released, it's just a small issue — but still worth noting to make the launcher even more flawless.

>I also like the idea of indicating somehow which icon pack is currently being used. In general, I think there's a lot of stuff we can improve when selecting custom icons.

It gladdens me that you're positive about these suggestions. I'm excited about what the future holds for these matters.

**Comment by Montell2099** [comment]
By the way, there's also a tiny bug where the text strings of the icon names are being cut off at the edge. Screenshot provided below:

![Screenshot_20201015-131543](https://user-images.githubusercontent.com/43126233/96337386-1098a280-1087-11eb-8a0b-fd75061afc33.png)

**Comment by 8bitPit** [comment]
@Montell2099  Thank you :D Regarding the cropped app names, does that also happen when switching to another font?

**Comment by Montell2099** [comment]
> @Montell2099 Thank you :D Regarding the cropped app names, does that also happen when switching to another font?

No, it seems to have been triggered by some specific font choice of mine — I've tried to recreate without success, it seems to be all good for now.

**Comment by 8bitPit** [comment]
Thanks for letting me know @Montell2099
