### ISSUE TITLE
Custom icon selection – suggested icons

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1386]
Many icon packs offer different variants of the same app icon which you can choose from, so It might be useful to have these alternative icons suggested on top of the list.

It could be done by taking the name off the app and searching the list for everything containing that. Although this might not be always 100% accurate (eg. when searching for Facebook Messenger vs some other messenger) I think it would be useful nonetheless.

**Comment by Montell2099** [comment]
I agree, or if the launcher could somehow fetch the categorization of the app the question and default search for that text. For example, "_messaging_", "_sport_", "_music_", "_contacts_", "_bank_" etc.

**Comment by 8bitPit** [comment]
Cool idea @Martin5001! We're also planning on making it easier/quicker to replace icons of apps which are not supported by the active icon pack quicker. However, that will take a while. I hope I can share more details next year.

**Comment by 8bitPit** [comment]
We could now finally turn your great ideas into reality with our brand-new Icon Assistant :D https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b.
