### ISSUE TITLE
App Lock and Full Hidden apps

### ISSUE THREAD

**Issue by billouetaudrey** [8bitPit/Niagara-Issues#1387]
Post a request for a guy :) 

Hello bro, heres my feature request.

App lock - it could be useful to have a toggle on/off for this so that it'll be not a big mess when accidentally long pressing on any apps and have the access to edit fav, remove or uninstalling the apps.

Hidden apps -  Once any apps is hidden, it should not be viewable in search bar unless you unhide it ( Maybe add an option )

Thanks

**Comment by CerberusCode** [comment]
Thanks bro, hope niagara will add this feature even in a free version

**Comment by 8bitPit** [comment]
Thanks for helping them out @billouetaudrey! Here's why we don't plan to add a password protection feature: https://help.niagaralauncher.app/article/63-password-protected-hidden-apps. However, hiding hidden apps from search might be possible in the future: https://github.com/8bitPit/Niagara-Issues/issues/468
