### ISSUE TITLE
Changing icons stoped working

### ISSUE THREAD

**Issue by ondrejholan** [8bitPit/Niagara-Issues#1388]
**Describe the bug**
Changing icon of app from borealis icon pack doesnt show any icons. It worked previously, but it stoped working. It only shows empty page with search box, Maybe it is, because there is too many icons (pack has about 20 000 of them)

**To Reproduce**
1. Pres and hold on app.
2. Click on icon.
3. Select borealis icon pack
4. No icons show up

**Smartphone (please complete the following information):**
 - Nokia 6.1 (android 10) and Nexus 5 (android 9)

**Screenshots**
![a](https://user-images.githubusercontent.com/3161780/96332371-e5508c00-1063-11eb-84d0-d55cfbaf9e31.jpg)

**Comment by Montell2099** [comment]
Does this happen consistently 100 % of the time? It happens for me sometimes with big icon packs, but only occasionally & if I'm tapping away at a fast pace to change the icon.

**Comment by ondrejholan** [comment]
Yes, this happens to me everey time with Borealis icon pack. Before it happened maybe once or twice.

**Comment by 8bitPit** [comment]
> Maybe it is, because there is too many icons (pack has about 20 000 of them)

Yes, they need some time to load. However, I think this would be clear if Niagara Launcher displays a loading circle (#1324), what do you think?

**Comment by Montell2099** [comment]
> I think this would be clear if Niagara Launcher displays a loading circle (#1324), what do you think?

I think this is a great idea, a clean-looking loading circle would be nice to see whilst loading huge icon packs. 🙂

**Comment by ondrejholan** [comment]
Yes that would be great. I almost always immediately search for icons so it takes a even longer (little more than 2 minutes on my phone), so it would help to have some feedback to show it is working.

**Comment by 8bitPit** [comment]
Great, I'll merge this issue with #1324 then.

**Comment by 8bitPit** [comment]
Merged with #1324
