### ISSUE TITLE
Icons cannot be changed after uninstalling icon packs

### ISSUE THREAD

**Issue by 71** [8bitPit/Niagara-Issues#1390]
**Describe the bug**
Icons cannot be changed after uninstalling icon packs.

**To Reproduce**
1. Install an icon pack
2. Change an app's icon
3. Uninstall the icon pack
4. The icon stays the same, and when tapping it a dialog informs us that icon packs must be installed to change icons (so the icon cannot be set to its original look).

This can be fixed by installing another icon pack, resetting the icon, and then uninstalling the icon pack again.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - Android version: Android 11

**Comment by 8bitPit** [comment]
Thank you very much for reporting @71 😀 This will be fixed once icons get reset when the corresponding icon pack gets uninstalled: https://github.com/8bitPit/Niagara-Issues/issues/1322

**Comment by 8bitPit** [comment]
Merged with #1322
