### ISSUE TITLE
New animation – only the ripple effect goes off when tapping date

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1391]
I noticed that sometimes the new bouncy-zoom animation, which is awesome by the way, does not trigger when tapping the date and weather. So I tried to investigate it and this is what I found:

It happens if you tap just on the edge of the clickable area.

If you start from the point where no touch is registered and move slightly closer to the button, really pixel by pixel, you'll find a spot where touch is being registered and the ripple effect animation is triggered, but no bounce. But the bounce animation is correctly triggered just about a pixel further. So it's really a tiny tiny thing, but can cause this bug if you have that luck and randomly hit that 1px thick border :D Hashtag nitpicking :D
~~(Don't know if this happens with the app icons touch areas too – didn't have the patience to open and close the app over and over while trying this :D)~~ It happens with app icon touch areas too. Just encountered that randomly.

Samsung Galaxy J7, Android 9

**Comment by 8bitPit** [comment]
Good catch, I think you're the only one who noticed this, haha 😁 I haven't found what caused this and I think it's not worth spending too much time on fixing this. So this bug might not get fixed, I hope that's okay for you.
