### ISSUE TITLE
Being able to disable app icons.

### ISSUE THREAD

**Issue by Aesew** [8bitPit/Niagara-Issues#1392]
For performance and simplicity, a simple toggle to close all apps icons. (Not only for favorites, for all apps as i said.) 
Because as i do not like installing icon pack. And as Niagara don't and will don't support icon shaping, there is not really a reason to see app icons for me.

**Comment by 8bitPit** [comment]
Hi, I've reopened this issue #448. We're not sure yet if we'll add an option to also hide app icons from the app list, but if we do that, we'll announce it here: https://github.com/8bitPit/Niagara-Issues/issues/140

**Comment by 8bitPit** [comment]
Merged with #140
