### ISSUE TITLE
Weather widget stopped working

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1393]
In Niagara 0.33.0 the weather widget stopped working after I opened its settings popup, haven't changed anything though, and pressed home button to go straight back to the home screen. It disappeared even though I kept it enabled. I tried to turn it off and on again, which didn't help. Restarting Niagara didn't have any effect either.

**EDIT:** Now I also noticed that my WiFi dropped so it might be the cause, but it should reload when back online – I tried to force it by manually changing the location and it still didn't load even when online. So I'm not sure what's the cause, but it's definitely not expected behaviour.

Samsung Galaxy J7, Android 9

**Comment by 8bitPit** [comment]
Thanks for reporting, now it should work again (a launcher restart might be necessary to refresh weather immediately).
