### ISSUE TITLE
[Feature request] Swipe up (or swipe up & hold) to search on home screen

### ISSUE THREAD

**Issue by UsamaKarim** [8bitPit/Niagara-Issues#1395]
Please add swipe up or Swipe up & hold to open search. Now I have to go for a two way process to open search which is frustrating. Sesame integration make use of search alot better. It would be convenient if you add fastest access to search. Thanks 😊

**Comment by 8bitPit** [comment]
Hi, swiping up to search is currently under discussion, you can join it here: #122

**Comment by 8bitPit** [comment]
Merged with #122
