### ISSUE TITLE
Add a way to add seperators between apps on favorite.

### ISSUE THREAD

**Issue by StarrKiss** [8bitPit/Niagara-Issues#1397]
One thing I get annoyed it is that I have the Sesame app on my Favorites page, but it blends in with the other apps, so to speak, even after I've renamed it and changed its icon:

![Screenshot_20201027-100134](https://user-images.githubusercontent.com/13007697/97320339-ad9fcc00-183b-11eb-9319-4e500d897e51.jpg)

I would like the ability to add seperators to the favorites screen, just like icons, that you'lld be able to drag around in the edit screen to place where you want. 
Imagine something like this:
![output](https://user-images.githubusercontent.com/13007697/97321499-f0ae6f00-183c-11eb-85ff-ede4eed9fab8.png)

but with addition spacing above the top and the bottom as if it were the height of a normal app.

**Comment by 8bitPit** [comment]
Hi @StarrKiss, thanks for the suggestion. I fear this feature wouldn't be impactful enough, it wouldn't be used by many. You can read more about Niagara Launcher's design principles here: https://help.niagaralauncher.app/article/8-niagaras-design-principles.
Great wallpaper btw!
