### ISSUE TITLE
#request - Add option to change the icon shapes

### ISSUE THREAD

**Issue by Rixon46** [8bitPit/Niagara-Issues#1398]
Please add option to change the icon shape Because of this i can't able to use the adaptive icon's and add option to pick the icon's from gallery

**Comment by 8bitPit** [comment]
Hi, good news is that I just reopened this issue: https://github.com/8bitPit/Niagara-Issues/issues/448
Changing icon shapes might be supported soon™!

**Comment by 8bitPit** [comment]
Duplicate of #448
