### ISSUE TITLE
Apps Crashing/Freezing

### ISSUE THREAD

**Issue by Quannino** [8bitPit/Niagara-Issues#1399]
Ok so I've been using Niagara Launcher for a while now and I noticed some of my apps are freezing and crashing. Also everytime I exit an app and went to app switcher it'll lag/freeze for couple of seconds and this goes for most of my apps. Here's the list of apps that has been freezing,crashing alot -
Brave Browser
Deezer 
Youtube Vanced/ Youtube
Discord

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 8
 - Android version: Android Pie (9)

**Comment by 8bitPit** [comment]
Hi, thanks for reporting. However, we cannot cause other apps to crash, we only launch them. Moreover, Niagara Launcher doesn't have control over the app switcher / Android's recents screen either, you can read more about it here: https://help.niagaralauncher.app/article/7-gesture-navigation

**Comment by Quannino** [comment]
Ok but whenevee Im using the launcher, I experience these bugs. I never encountered any of these issues when im on samsung one ui

**Comment by 8bitPit** [comment]
Can you please check if those bugs are reproducable with other third-party launchers as well (e.g. Nova Launcher)?

**Comment by Quannino** [comment]
I did and no.. When Im using other launcher I never encounter such thing which is why I'm reporting this issue and also the launcher is still in early access so its possible

**Comment by 8bitPit** [comment]
That's strange. I'm certain that launchers cannot cause crashes of other apps (that would be an Android security flaw). But I'll closely watch if others will report similar issues, and reopen this issue on that case. Thanks for reporting!
