### ISSUE TITLE
Background blur

### ISSUE THREAD

**Issue by saboooor** [8bitPit/Niagara-Issues#14]
there should be an option to blur the background on the apps screen

**Comment by 8bitPit** [comment]
A blur option is more memory consuming and doesn’t go for live wallpapers. Furthermore, for solely that feature Niagara must be granted reading your files (storage permission), which I am not a huge fan of. See issue It's the same problem as in Issue #15

**Comment by 587saboor** [comment]
I like the background blur on the apps screen, that way, it looks like the stars disappear like magic lel

**Comment by zbhoy** [comment]
Is Muzei very memory consuming? It seems to implement the blur pretty well without problems. IF they are on GitHub maybe check that out

**Comment by 8bitPit** [comment]
I hoped we could implement this without any permissions and workarounds once Android 12 arrives, but that wasn't the case :/ The full explanation why I'm closing this ticket: https://help.niagaralauncher.app/article/64-blur-wallpaper

> Unfortunately, Android does not offer a blurring mechanism for launchers (Android 12 introduced blur support but not for only blurring the wallpaper). We could implement our own solution, but Niagara Launcher would require the file access permission, and the workaround wouldn't work in Android's lock or recent screen and wouldn't support live wallpapers. However, we added a subtle tint effect behind the app list to increase readability without needing to blur the wallpaper.
