### ISSUE TITLE
Ability to have only App names in the list, instead of icons and App name.

### ISSUE THREAD

**Issue by krishnapsn** [8bitPit/Niagara-Issues#1402]
It would be great if we could have only app names to give the launcher a more minimal look. At least in the favourites screen.

**Comment by UsamaKarim** [comment]
Just like Before Launcher?

I used that launcher for some days but I can't regret the beauty of Niagara Launcher. But still, we can test this feature, definitely

**Comment by Rod911** [comment]
Duplicate of #140
