### ISSUE TITLE
Swipe up gesture is not working on MIUI

### ISSUE THREAD

**Issue by UsamaKarim** [8bitPit/Niagara-Issues#1403]
Swipe up gesture is not working on MIUI when I have fullscreen gesture on. It works only 1/10 times. I have to swipe again & again to make it work. I am using sesame integration

**Smartphone Information**
 - Device: Xiaomi MI 9T
 - Android version: Android 10

**Comment by 8bitPit** [comment]
Hi, sorry for my late reply. Can you reproduce this issue on other third-party launchers like Nova launcher or Lawnchair?

**Comment by UsamaKarim** [comment]
> Hi, sorry for my late reply. Can you reproduce this issue on other third-party launchers like Nova launcher or Lawnchair?

Nova launcher have same issue. I have to double swipe up for opening search bar rather I disable double check gesture or not. It also doesn't work every time, it has to be a specific area to work. Please implement a better support of gesture
![IMG_20201121_072422](https://user-images.githubusercontent.com/64292174/99870670-d62aa400-2bf6-11eb-9797-411e5bf1f133.jpg)

**Comment by 8bitPit** [comment]
Good news: With v0.34, you can now swipe up from anywhere on your home screen to access Niagara's search.
