### ISSUE TITLE
Double notification

### ISSUE THREAD

**Issue by mgithuber** [8bitPit/Niagara-Issues#1405]
Showing notification two times. Pls see the YouTube vanced notification. 

Niagara 0.33.1, Android 6.0.1, Asus ZenUI

![Screenshot_20201111-085350](https://user-images.githubusercontent.com/50730036/98896562-37ec5f00-24cf-11eb-9f96-1df6df5a6a44.jpg)

**Comment by 8bitPit** [comment]
Thanks for the report @mgithuber. How does Android's notification display those notifications?

**Comment by mgithuber** [comment]
> Thanks for the report @mgithuber. How does Android's notification display those notifications?

This is how it looks

![Screenshot_20201112-152636](https://user-images.githubusercontent.com/50730036/98925261-c971c600-24fb-11eb-8f9c-fa976057ea2d.jpg)

**Comment by mgithuber** [comment]
Disclaimer: This log might include personal information.

Device: WW_Z00L
Manufacturer: asus
Android version: 23
No. of visible notifications: 1

android - Change keyboard - Microsoft SwiftKey Beta Keyboard - Microsoft SwiftKey Beta Keyboard
prio: 0
has low priority: false
cat: sys
text: Microsoft SwiftKey Beta Keyboard - Microsoft SwiftKey Beta Keyboard
android.title: Change keyboard
android.allowDuringSetup: true
android.subText: null
android.showChronometer: false
android.icon: 17302753
android.text: Microsoft SwiftKey Beta Keyboard - Microsoft SwiftKey Beta Keyboard
android.progress: 0
android.progressMax: 0
android.showWhen: true
android.rebuild.applicationInfo: ApplicationInfo{c22a966 android}
android.infoText: null
android.originatingUserId: 0
android.progressIndeterminate: false
ongoing_event

**Comment by mgithuber** [comment]
Above report for you. Sent as per the instructions you gave me in Telegram 

https://t.me/niagara_launcher/117960

**Comment by 8bitPit** [comment]
Thanks @mgithuber 😀 According to the log, the text from your notifications already seems to be duplicated: 

> Microsoft SwiftKey Beta Keyboard - Microsoft SwiftKey Beta Keyboard

**Comment by mgithuber** [comment]
Dear Peter, now am using Android 10 device and am not facing this double notification issue in Android10 .  I think you can close the issue because now I don't have Android 6 :))

**Comment by 8bitPit** [comment]
Thanks a lot for letting me know and congrats to your new phone :D
