### ISSUE TITLE
New Weather API

### ISSUE THREAD

**Issue by blu-bots619** [8bitPit/Niagara-Issues#1406]
**Is your feature request related to a problem? Please describe.**
Weather api or weather widget is not working/showing. I think this would happened because the Dark Sky has disconnected working in android

**Describe the solution you'd like**
Please change the old weather api(Dark Sky) and add other weather api like, OpenWeatherMap or other else..

Please fix this problem because i love this launcher

**Comment by 8bitPit** [comment]
Is the problem reproducable? Does it work again? Dark Sky hasn't been shut down yet, it should still work fine: https://help.niagaralauncher.app/article/9-dark-sky-api-shutting-down

**Comment by blu-bots619** [comment]
But it is not working for me. I don't know

**Comment by 8bitPit** [comment]
Hm okay, since when it stopped working on your device @blu-bots619?

**Comment by blu-bots619** [comment]
It's not showing when i enabled this option at the first time.

**Comment by 8bitPit** [comment]
Can you please write me your order number of Niagara Pro via mail? Then I can look into this. Our address is niagaralauncher@gmail.com
