### ISSUE TITLE
Can't dismiss notifications

### ISSUE THREAD

**Issue by blu-bots619** [8bitPit/Niagara-Issues#1407]
**Describe the bug**
I can't dismiss notifications from homescreen while swiping to dismiss that.

**To Reproduce**
1. Open homescreen notifications(if available)
2. Swipe to dismiss notifications 

**Smartphone (please complete the following information):**
 - Device: Lava R1
 - Android version: Android 6

**Comment by 8bitPit** [comment]
Hi, can you please check if notifications can be dismissed in the latest version again we rolled out a few days ago (v0.33.2)?

**Comment by blu-bots619** [comment]
> Hi, can you please check if notifications can be dismissed in the latest version again we rolled out a few days ago (v0.33.2)? 

    Let me check that.

**Comment by blu-bots619** [comment]
I'm using the latest version of niagara launcher. Is any way to show u the proof of this problem.

**Comment by 8bitPit** [comment]
Oh okay. Can you please describe further when exactly the issue happens? Does dismissing notification not work for all notifications and how often does it occur? Moreover, does a device restart fix it?
