### ISSUE TITLE
Sesame Settings keeps surfacing new items in your stacks/folders

### ISSUE THREAD

**Issue by Nxt3** [8bitPit/Niagara-Issues#1408]
**Describe the bug**
When you have Sesame Settings integrated, shortcuts keep getting added to your "stacks/folders" after you've already edited it to be a certain way. So, for example, Spotify will continue to surface new shortcuts in your stack as they surface to the app. It's annoying because I don't want more added. I don't think this was a thing in Nova Launcher with Sesame Settings.

**To Reproduce**
1. Have Sesame Settings integrated

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android version: 11

**Comment by 8bitPit** [comment]
Hi @Nxt3, to disable dynamic shortcuts, swipe on the app you want to remove them and tap on the edit pen. From here, tap on "Edit shortcuts" and you'll get forwarded to Sesame. Then tap on "Pin long-press shortcuts", add your favorite shortcuts and make sure "Show only these shortcuts when I long press" is enabled. Hope that helps! If it didn't, feel free to reopen this issue.

**Comment by Nxt3** [comment]
That works if I wanted any shortcuts. I have Facebook Messenger as a favorite and since I don't want any shortcuts added for Facebook Messenger, pinning some doesn't solve the problem. I did figure that out for Spotify though since I only wanted "My Library" as the only pinned shortcut.

**Comment by 8bitPit** [comment]
Ah okay, maybe it will be possible in Niagara Launcher to hide all shortcuts of an app in the future. I also recommend to open a ticket at Sesame's repository to higher your chances of getting the feature 😉: https://github.com/SesameCrew/sesame_issues/issues

**Comment by Nxt3** [comment]
Yeah I'd keep this closed as it's probably something that needs to be added to Sesame.

**Comment by Nxt3** [comment]
Just found a setting in Sesame that I didn't notice before: you can Blacklist apps you don't want shortcuts for. My solution was to blacklist Messenger.

**Comment by 8bitPit** [comment]
Great, thanks for letting me know 😀
