### ISSUE TITLE
Sesame widget not triggering on press

### ISSUE THREAD

**Issue by Oted** [8bitPit/Niagara-Issues#1409]
Hey I just added the Sesame widget integration but pressing the widget (below the clock) does nothing. This is how it looks, not sure if this is known issue or maybe I have missed some setting?

![Screenshot_2020-11-15-19-25-34-312_bitpit launcher (1)](https://user-images.githubusercontent.com/2505359/99193328-91c38200-2778-11eb-9e7f-52532f98275f.jpg)

**Comment by 8bitPit** [comment]
Strange, when I tap on the widget it opens Sesame. Have you tried restarting your phone? Moreover, does the widget work in other launchers?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
