### ISSUE TITLE
Solutions for non-Google users

### ISSUE THREAD

**Issue by jacksongoode** [8bitPit/Niagara-Issues#1410]
This is quite broad but would entail either removing the suggestions to buy Niagra Pro (since the user cannot connect to Play services) or offering a method of activation via serial from another service like Patreon.

Providing a de-Googled alternative would always be appreciated by users.

**Comment by aaronhuggins** [comment]
I will second this. I'm a fan and have paid for the app using the Play store. I would happily pay again or subscribe somehow outside of the Play store in order to use pro features on a de-googled phone.

**Comment by 8bitPit** [comment]
Thank you both for the request and for your kind words. Unfortunately, it takes quite an effort to also make Niagara Pro available outside of Google Play, you can read more on why that is here: https://github.com/8bitPit/Niagara-Issues/issues/1137
However, there is an alternative, see: https://help.niagaralauncher.app/article/10-purchase-help

> Can I purchase Niagara Launcher without Google Play?
Some devices don't come with Google Play Services and Google Play. Niagara Launcher needs them to verify your purchase. You could try MicroG to install a similar but open source service. (Use at your own risk.)
