### ISSUE TITLE
Haptic feedback when using the Alphabetical scroller

### ISSUE THREAD

**Issue by Nxt3** [8bitPit/Niagara-Issues#1411]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have some tactile feedback when using the scroller so I know I'm doing something. Just feels satisfying.

**Describe the solution you'd like**
Either a toggle or make it default that there is feedback when touching the alphabet scroller.

**Comment by 8bitPit** [comment]
While this feature can be neat for some, I think it's better to keep Niagara Launcher simple and don't add the option to vibrate the device while scrolling. I fear too few people would use it and if we make it a default I can imagine many would complain because they want the phone to be silent when doing common tasks. More about Niagara's design principles: https://help.niagaralauncher.app/article/8-niagaras-design-principles

**Comment by Nxt3** [comment]
Maybe the level of vibration isn't being conveyed. Not talking about a violent haptic event like a phone call or a notification; rather, a subtle feedback to know you've scrolling. On the right phone, it feels like "notches".

This is best explained using the Beta version of Sync for Reddit. There is a scroller for subreddits that emit tiny haptics when scrolling along it. It's rather satisfying.

![Screenshot_20201118-130808](https://user-images.githubusercontent.com/2940826/99570144-843c1100-299f-11eb-938f-0ba2faaca64a.png)


Given this is the main way to interact with your apps through Niagara launcher, it would be an improvement for sure.

**Comment by 8bitPit** [comment]
Sorry for the late reply @Nxt3. I believe the feature can be satisfying for some users, but I fear even the smallest vibrations can feel a little gimmicky after a while for the majority. This is more for apps where you don't use the scrollbar very often, in my opinion. Furthermore, to make it optional, I'd say it had to really make an impact and improve the UX drastically.

**Comment by 8bitPit** [comment]
I go a bit more into detail in this article: https://help.niagaralauncher.app/article/99-vibration-for-alphabet-scrolling
