### ISSUE TITLE
Action button in notification should load without reopening

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1412]
This is not really much important, just for polishing: When you receive a notification containing an email address for example, the email action is suggested. This button takes a few seconds to load, which is fine most of the time, but if you swipe-open the notification before it loads, it gets blocked and doesn't show until you close and reopen the swipe popup again. So I think it would look better to fade the button in as soon as ready without the need to refresh by reopening the swipe. (Don't know how it would affect the performance though. That's why I'm not labelling it as bug as it may be this way on purpose.)

**Comment by 8bitPit** [comment]
Makes sense, yeah. Thanks for noticing Martin 😀

**Comment by 8bitPit** [comment]
I tried to reproduce this, and it works fine on my device. Can you please check again?

**Comment by Martin5001** [comment]
So I tried again with Gmail. The test message contained a web link to trigger Chrome action button. And actually the action button didn't show at all – even after waiting – until first swiping the notification. (So it was probably not "blocked" by the popup like it seemed to me originally.)

1. I received the email, name of the contact was displayed in the notification preview
![20210221_115600](https://user-images.githubusercontent.com/35201200/108622880-0410c600-743c-11eb-897e-9fc7181ee064.jpg)

2. then I swiped to reveal the message content with the link – no button showed yet
![20210221_115540](https://user-images.githubusercontent.com/35201200/108622896-1c80e080-743c-11eb-9a82-6d358bedd68d.jpg)

3. then I closed the swipe popup and then opened again – this time the button showed
![20210221_115520](https://user-images.githubusercontent.com/35201200/108622913-2c98c000-743c-11eb-816b-6df776b5abe9.jpg)

I suspect it could be because the text of the message itself wasn't actually in the swipe preview at first – instead there was the name of the contact from which the test email was sent. The Android default notification was collapsed too:
![Screenshot_20210221-120105_Niagara Launcher](https://user-images.githubusercontent.com/35201200/108623014-d24c2f00-743c-11eb-9e64-fd0b3cdc3173.jpg)
![Screenshot_20210221-120122_Niagara Launcher](https://user-images.githubusercontent.com/35201200/108623017-d7a97980-743c-11eb-8f98-c1784b38cfd7.jpg)

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)
