### ISSUE TITLE
Change min height of widget

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1416]
If a custom widget is placed (Spotify in this case) it should default its size to a minimal height at which it can fully fit (see screenshots).
1. Size after adding the widget (doesn't fully fit, gets cropped):
![Screenshot_20201120-135038_Niagara Launcher](https://user-images.githubusercontent.com/35201200/99802505-1b3bd100-2b38-11eb-9967-0de239396bd5.jpg)

2. Manually adjusted to its somewhat ideal size:
![Screenshot_20201120-135115_Niagara Launcher](https://user-images.githubusercontent.com/35201200/99802575-38709f80-2b38-11eb-9b6f-17923d0ec220.jpg)

3. Manually adjusted – too stretched (this should ideally be not possible) not as important as point 1 though
![Screenshot_20201120-135119_Niagara Launcher](https://user-images.githubusercontent.com/35201200/99802682-65bd4d80-2b38-11eb-86bc-afdfd6dad433.jpg)

**Comment by 8bitPit** [comment]
Every widget provider can choose their widgets default height, but many apps don't provide a sensible default because grid-based launchers enforce a min-height of one row. To work around that, we could also enforce a certain min-height.

**Comment by 8bitPit** [comment]
Added in v.1.2
