### ISSUE TITLE
Better icon support

### ISSUE THREAD

**Issue by HTSamurai** [8bitPit/Niagara-Issues#1417]
**Is your feature request related to a problem? Please describe.**
When I ma using my phone, because I am using Niagara launcher it doesn't show the icons from MIUI theme, which can be confusing since I am very used to these icons.

**Describe the solution you'd like**
When you click on the icon in the app editor thingy when you click and hold an app, have a "Default icon" to use a defualt, or in my case, MIUI or Huawei theme, an "Icon pack" option, and a "Select from gallery" option to pick an image you saved. Alot of launchers already have this so I hope this is added soon.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Afaik, other third-party launchers can't access MIUIs/Huawei's themes. Can you please check if Nova Launcher or Lawnchair Launcher supports that?

**Comment by HTSamurai** [comment]
I can't check

**Comment by 8bitPit** [comment]
I just checked it, and these launchers also don't support MIUI themes. Unfortunately, I believe the launchers have to be whitelisted by Xiaomi/Huawei to support themes.
