### ISSUE TITLE
Calendar Widget not updating

### ISSUE THREAD

**Issue by jmrlopes** [8bitPit/Niagara-Issues#1419]
**Describe the bug**
In the Widget of Niagara , sometimes it doesnt show the next event in my calendar. I have to go again into settings and disable an enable the option of Show Next Calendar Events

**Smartphone (please complete the following information):**
 - Device: TPlink Neffos X9 - Model TP913A
 - Android version: Android 8.1

**Comment by 8bitPit** [comment]
Fixed in v.0.34.0
