### ISSUE TITLE
Support other search engines

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#142]
Problem: Not as easy to implement, since Search engines like DDG (Duck Duck Go) does not offer a quick search feature in their app.

**Comment by marijnnk** [comment]
While this is true, I suggest we can map any app or shortcut to this button. When opening the duckduckgo browser, it automatically shows the keyboard. Other search engines do support a quick search feature. We could also mimic the functionality of "Just Search" ([link](https://f-droid.org/en/packages/co.pxhouse.sas/)) available on f-droid.

For the button icon, perhaps there could be some preset icons and optionally be able to pick your own. Or just use the google icon for google and the search icon for anything else.

**Comment by oldmanjoe** [comment]
I would like to see a setting like this ... Type the search button could be configurable to call another app, like Samsung Finder (my case) or any other.

**Comment by p4t44** [comment]
Can you do it so that it just opens searchs in a browser? I use ddg but have never used there app, I'd just like to have searches open in my browser of choice.

**Comment by 8bitPit** [comment]
@p4t44 Most likely, this would let you open any browser. Since you can set ddg as your default engine in any browser I know, it would work.

**Comment by p4t44** [comment]
@8bitpit I enabled the Google search button without the Google app installed. Tapping it just comes up with a toast saying "app not installed".

**Comment by 8bitPit** [comment]
@p4t44 Yup, this is intended.

**Comment by hannahswain** [comment]
I'm really liking Niagara, but I feel forced to use Sesame to be able to search through a different search engine. While it's great to have that option, I'd rather just be able to choose the search engine through Niagara and have that open in the system default web browser.

**Comment by UsamaKarim** [comment]
It might be a completed feature as we have sesame implemented in our search

**Comment by 8bitPit** [comment]
Added in v1.2.0 with the Niagara button: https://github.com/8bitPit/Niagara-Issues/releases
