### ISSUE TITLE
Removed calendar event should disappear without reopening

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1420]
When I tap on an event in the calendar widget, the calendar opens, if I then remove the event here and go back, the calendar widget is still open and shows the deleted event. If I tap on that deleted event here, it correctly says "Item not available". For this to update and hide the deleted event, it's needed to close and reopen the widget.

I think it makes sense that the widget stays open (because you opened the calendar from there, it makes sense to come back to it) but the deleted event should disappear without the need of this refreshing.
(Similar to #1412)

**Comment by 8bitPit** [comment]
Fixed in v.0.34.0
