### ISSUE TITLE
Icon preview in settings doesn't always update

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1422]
If you set one icon pack via Niagara settings and then open another icon pack app, which is using Blueprint, and apply it from the dashboard itself, the icon pack changes, but the preview in the Niagara settings doesn't update until you manually switch the icon pack again in the Niagara settings.

Niagara 0.33.2
Android 9

**Comment by 8bitPit** [comment]
I see. Blueprint is a special case because the icons can change. Do the app icons not update at all, or is it just the preview that's not changing?

**Comment by Martin5001** [comment]
@8bitPit It's just the preview.

**Comment by Maxr1998** [comment]
I couldn't reproduce this here, please re-open or reply if it's still happening for you. It might have just been fixed since.
