### ISSUE TITLE
Option to move media player to bottom of home page.

### ISSUE THREAD

**Issue by tripledouble721** [8bitPit/Niagara-Issues#1424]
Just wondering if there could be an option to move the media player below the 8 favorite apps instead of having it above the apps. I feel like it would be easier to reach and some people might enjoy the option. Thanks

**Comment by sid32** [comment]
Like replace the search button? Would need an option to appear, even if user has search button turned off.

**Comment by Martin5001** [comment]
> Like replace the search button? Would need an option to appear, even if user has search button turned off.

Maybe in this case the search button could change into a full search bar which would be placed below the media player. So you'd have the player at the bottom and the search bar under it. This way the functionality would remain, while the layout would stay balanced. (Or if the search is disabled, only the media player would show, same as now. No additional toggle needed for this, just the one to place the player to the bottom.)

**Comment by 8bitPit** [comment]
Hi @tripledouble721, thanks for the suggestion.  If we add an option to move Niagara's widget to the bottom, it would still make it hard to reach your favorites at the top. If you're having difficulties in reaching anything on Niagara's home screen, I recommend moving the Niagara widget (and with it the whole list) further down. Moreover, for the sake of simplicity, we'd like to add as few toggles as possible: https://help.niagaralauncher.app/article/8-niagaras-design-principles
