### ISSUE TITLE
Unassigned action in notification – visual enhancement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1425]
![20201129_202843](https://user-images.githubusercontent.com/35201200/100625372-bc8b0a00-3324-11eb-97aa-3affb6666817.jpg)

When a notification action is shown, but the corresponding app is not set as default for that action, the generic "Open" action doesn't have any icon but has margin. I think either an generic icon could be added or the margin should be removed. (I personally would prefer the latter – no icon, no margin.)

**Comment by 8bitPit** [comment]
Fixed in v.1.1
