### ISSUE TITLE
Apps on homescreen shouldn't be in Hidden App List. 

### ISSUE THREAD

**Issue by sid32** [8bitPit/Niagara-Issues#1427]
Apps that on are on the homescreen and then hidden to keep your list clean shouldn't be listed in the Hidden App section in 0.34.0  or at least should be marked as on homescreen.

**Comment by Martin5001** [comment]
I think they should remain listed here to prevent confusion – they are in fact hidden, so should stay on that list – but giving them an indicator that they are also on the home screen is something I'd like to see too 👍

**Comment by 8bitPit** [comment]
Hi @sid32, I agree with Martin and say it's better to have every hidden app listed in the hidden app section. If you want to find out if an app is also one of your favorites, you can long-press it.
