### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1428]
On v 0.34.0 notifications stopped working after some time. Notification is shown in the system, but not in Niagara. Disabling and re-enabling didn't help. Restarting the launcher fixed it.

I noticed that when I tapped the empty "no new messages" area it showed the Niagara settings dialog for enabling/disabling notifications, so maybe it somehow got disabled during this (showed as enabled though). Or it could be I left the phone locked and battery optimization killed it, but I don't think so, because previously it didn't cause any problems. Unfortunately I don't have any more information yet, but will update this issue if I find something new.
(Running on Samsung Galaxy J7 with Android 9)

**Comment by 8bitPit** [comment]
Thanks for the report Martin, I think I've found the issue in 0.34.1; but if it reappears, please reopen this ticket :)
