### ISSUE TITLE
Don't show the notification access prompt if already granted

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1429]
If I disable the notifications feature and then re-enable it, I get prompted with the Niagara dialog asking for permission even though it's already granted and have to tap okay to get past it. This is not exactly a bug in functionality – it works, and the toggle in the dialog correctly switches itself to show the permission is granted – but it's not expected either. I think it should show only when the permission is actually not granted.
![Screenshot_20201202-202402_Niagara Launcher](https://user-images.githubusercontent.com/35201200/100921091-5f39b900-34dc-11eb-84ef-0d53be43c696.jpg)

**Comment by 8bitPit** [comment]
Fixed in v.0.34.1, thanks!
