### ISSUE TITLE
Back Button on favorite screen

### ISSUE THREAD

**Issue by pradyw** [8bitPit/Niagara-Issues#143]
Add some functionality to back Button which is just resting there.
like
- slide open/close Google feed
- launch any app
- or just toggle another page with widgets

**Comment by 8bitPit** [comment]
Cool, haven't thought about that. However, it wouldn't go well with the idea of a back button, so it could be confusing for many.

**Comment by pradyw** [comment]
Hmm, may be confusing for some at first  but after some time may be useful.
Or can be optional.

**Comment by 8bitPit** [comment]
@dino-
`How about a left swipe on the Home "pill"?`
I do not support the feed. If I will, that could be nice gesture to open it.

`Also, with gestures turned on in Android P, the back button is always on, even though it does nothing. I think it goes away in the Stock P launcher. Is this a bug?`
Android does not let you remove the button, I'm sorry.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
