### ISSUE TITLE
Customize gestures

### ISSUE THREAD

**Issue by romavonk** [8bitPit/Niagara-Issues#1430]
Please integrate the option to customize the gestures.
Let the user choose the action when "Double tab alphabet", "Swipe up", "Tab home button"
My personal preference would be:
"Swipe up" to lock screen
"Tab home button" to search

**Comment by 8bitPit** [comment]
Hi @romavonk, for the sake of simplicity (https://help.niagaralauncher.app/article/8-niagaras-design-principles), we're not planning to add such options as of know. However, the G-button will probably be customizable in the future: https://github.com/8bitPit/Niagara-Issues/issues/300

**Comment by TomDeSmet** [comment]
It would be nice though. I'd settle to be able to customize the swipe up gesture only.
