### ISSUE TITLE
Add more weather icons (e.g. to indicate different rain intensities)

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1433]
I'm thinking if there is the possibility to add more colors to the weather's icons of the widget. I think that I would be pleasant if there a difference between the sun and the moon (example: light purple). Also, the icons could be more solid to make it easier to watch. When we are outdoors and strong light environments, or the wallpaper makes it hard as well sometimes. More solid icons could make them more easy to understand for various people. 

With this I'm not saying that I don't like the icons. I think that it could be same icons but more solid, keeping the same minimalistic style.

Also, I think that it could be great to add a couple more icons. In order to differentiate more different weather conditions. For example, the icon for the rain don't change no matter the kind of rain. I think that would be great to add an icon for light rain, heave rain, thunderstorm, partly cloudy, cloudy...
For example, a have a couple of ideas.

light rain = 1drop
rain = 2 drops
Heavy rain = 3 drops
Thunderstorm = a simple lightning alone or with a small cloud.
Could be simar with snow.
Or icon for winds, etc.

I think, it is important to add more variety to have a clearer understand of the weather, without the necessity to enter webpage in order to have more info.
Also this would make the launcher more attractive.

Here are some ideas, I don't own them. It is just to illustrate the concept.
 
![weather-icons-collection_1167-124](https://user-images.githubusercontent.com/72170242/101270136-d28d3600-373b-11eb-86d0-0a5f4eca5c5c.jpg)
![9d1675f12ab5325fb0b1f9dd4f0c4379](https://user-images.githubusercontent.com/72170242/101270145-e2a51580-373b-11eb-90a2-1d6ac0d4a3a1.jpg)
![345b2745e1ea5d2e5bb88a5e6d3cc20e](https://user-images.githubusercontent.com/72170242/101270147-ea64ba00-373b-11eb-997c-81c3615399f4.png)

**Comment by 8bitPit** [comment]
Hi @Just-SKY, thanks for your suggestions! The reason why we keep the color palette very limited is that they fit on more wallpapers that way. Moreover, In my opinion, outlined icons fit the launcher's style better and we tried to improve the contrast between icon and wallpaper by adding a light shadow effect (but not when the text color is set to dark, for the sake of consistency).

Regarding your thoughts on extending weather icons, I strongly agree. Actually, we're already working on that, haha :)

**Comment by 8bitPit** [comment]
Added in v.1.1.1

**Comment by smeijer** [comment]
Are the weather icons in Niagara launcher custom, or is it a readily available pack?
