### ISSUE TITLE
Letting up while scrolling too sensitive?

### ISSUE THREAD

**Issue by robertlankford** [8bitPit/Niagara-Issues#1435]
**Is your feature request related to a problem? Please describe.**
I'm often frustrated when scrolling up or down through the list of applications and I lift up to stop the scrolling action.  The action of lifting up will often move up or down a letter in the alphabet.  For instance, if I'm scrolling up and stopping on "G", sometimes I'll get the "F" list of icons instead.  If scrolling down to "G", I might get "H" application icons.

Obviously, this doesn't happen ever time, and can totally be called 'user error'.  But I've used Niagara for years now and this still happens commonly throughout my day.  So, I'm a hopeless case at this point, I suppose.  😀

**Describe the solution you'd like**
I have no idea how to 'fix' this.  Is there a way to 'deaden' the responsiveness of movement as a scrolling action slows down?  In other words, can movement that comes nearly to a stop require an exaggerated amount of movement again in order to continue the scrolling action?  Or, can the act of lifting your finger make more of an effort to determine where you just *were* rather than were you currently *are* in this split second in order to try and preserve the letter you're intending to stop on?  Like, bring up the letter that we were on 1/10th of a second ago perhaps??

**Comment by 8bitPit** [comment]
Hey, @robertlankford, that's a wonderful suggestion! I especially like your second solution :)

**Comment by topsy-turvy99** [comment]
Fixed in v1.6 i suppose?

- The circle now snaps to each letter more prominently.

https://medium.com/niagara-launcher/spring-clean-your-home-screen-889e58d60708
