### ISSUE TITLE
Performing a search too quickly loses characters in the search term once opened in Google Search

### ISSUE THREAD

**Issue by Nxt3** [8bitPit/Niagara-Issues#1437]
[Here is a screen recording of the issue.](https://drive.google.com/file/d/19iiuKbf6DMhAFa3vFQZgL51zUB57r5kH/view?usp=drivesdk)

**Comment by praveenchandranpk** [comment]
Have the same issue.

**Comment by mrtrevelyan** [comment]
Yes I can confirm this is happening to me too! Guess there's some lag between writing the search term and activating the search.

I note that I have also enabled Sesame integration, and I've noticed this through a few versions of the launcher, including the most recent alpha release - in case that helps with the investigation.

**Comment by Nxt3** [comment]
This is still an issue despite two updates to Sesame Search. It's started to affect how I search in other apps too--my muscle memory is building in such a way that I've started delaying pressing the search button by a second or two.

**Comment by Nxt3** [comment]
Seems to be fixed in the 2.0 beta!

**Comment by 8bitPit** [comment]
You're welcome, thanks for reporting @Nxt3 :D
