### ISSUE TITLE
Google Assistant (long press on Google button)

### ISSUE THREAD

**Issue by jacobsface** [8bitPit/Niagara-Issues#144]
I know some people have said it would interfere with scrolling, but currently it doesn't register as scrolling from the main screen. I think the Google button looks a little out of place off to the side. I think it would look better centered. A tap would open the Feed (as it does now), a swipe up could bring up search (as it does now), and a long press could summon Google assistant

**Comment by 8bitPit** [comment]
Scrolling up will probably be an open search gesture.

**Comment by 8bitPit** [comment]
Was implemented a long time ago, so I'm closing it :)
