### ISSUE TITLE
Shortcuts (no Sesame) duplicated

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1440]
Android 9 (Samsung Galaxy J7)
Niagara 0.34.1
Shortcuts for Google Maps are duplicated (all of them)
(I temporarily disabled Sesame to see if it's caused by that but nothing changed.)
![Screenshot_20201211-161046_Niagara Launcher](https://user-images.githubusercontent.com/35201200/101920159-c0901500-3bcb-11eb-9033-1eb155921503.jpg)

**Comment by 8bitPit** [comment]
Hmm, I don't think this is a bug. The first bunch of shortcuts are from Maps installed on your work profile, and the other ones are from your default profile.

**Comment by 8bitPit** [comment]
But if that's not the case please reopen this ticket.

**Comment by Martin5001** [comment]
> Hmm, I don't think this is a bug. The first bunch of shortcuts are from Maps installed on your work profile, and the other ones are from your default profile.

So now I found out it's not the work profile, but it's the Samsung Secure Folder, which is similar to work profile (also creates separate instances of apps). So I don't know if this is expected or not. (I personally would think the Secure Folder apps should not be shown here as they are ment to be launched from the Secure Folder itself.)

(@8bitPit I can't reopen the issue, because I'm not the one who closed it, so if it's indeed a bug, you'll have to reopen it yourself.)

**Comment by 8bitPit** [comment]
> So now I found out it's not the work profile, but it's the Samsung Secure Folder, which is similar to work profile (also creates separate instances of apps). So I don't know if this is expected or not. (I personally would think the Secure Folder apps should not be shown here as they are ment to be launched from the Secure Folder itself.)

Ah I see, thanks for explaining. Android doesn't provide a way to differentiate between a feature like that or a 'real' work profile :/

> (@8bitPit I can't reopen the issue, because I'm not the one who closed it, so if it's indeed a bug, you'll have to reopen it yourself.)

Oops 😅
