### ISSUE TITLE
Calendar update faster - Swipe up (more options)

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1441]
**_SOMETIMES_** the events that are more than 12 hours don't appear on the home screen when the moment or day comes. So, we could be sure the events will appear on the home screen by making the calendar update faster. As result, there isn't the necessity to open them manually in order to make them appear on the home screen.

Second, the "Swipe up" option is great, I love it. However, the options of " app search button" is already available in the app list. So, it could somewhat ambiguous because one makes the other useless (app search button). We could take advantage of Swipe up by adding the options to change the usage of it. Because there could be people out there like me that like and use the app search button in the app list.
Ex: We could use the Swipe up to open (chrome search, compose email, widgets, shortcuts, add events etc). So it could increase the productivity. 

If the person wants to keep the _swipe _up_ for searching app, there could be the possibility to make the search button in the app list a _lock button , so we take advantage of both 
![IMG_20201221_123302](https://user-images.githubusercontent.com/72170242/102810437-59235380-4389-11eb-905b-1da927e4084b.jpg)

**Comment by 8bitPit** [comment]
Sorry for the late response @Just-SKY. I'm happy to tell you that the calendar issue is fixed in v1.1.1. We don't plan to make the swipe gesture customizable but the Goggle button will be: #300
