### ISSUE TITLE
Birthdays not shown in calendar on Android 11

### ISSUE THREAD

**Issue by edisso10018** [8bitPit/Niagara-Issues#1442]
Been away from Niagara Launcher for a while. Great progress made in the meantime!

I have enabled the calendar in the Niagara-Widget. Under Settings - Functions - Niagara-Widget - Calendar - Filter Events all my calendars (including birthdays) are enabled. Now if I tap on the calendar on the homescreen events from all my calendars are shown but no birthdays. The integrated Google Calendar app shows the birthdays.

This happens only on my Pixel 4 XL with Android 11. On my Lenovo tablet with Android 10 the birthdays are correctly shown in Niagara's calendar widget.

Any ideas?

**Comment by 8bitPit** [comment]
Thank you, @edisso10018 😀 I hope the steps described under "A few calendar events are not showing up." & "How can I show my contacts birthdays?" from the following article can help: https://help.niagaralauncher.app/article/76-calendar-faq

Cheers!

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.

**Comment by edisso10018** [comment]
No, it does work with the latest version (0.90.4). Did a full reset though.

**Comment by 8bitPit** [comment]
Thank you very much for letting me know :)
