### ISSUE TITLE
Scrolling length prevents using the uninstall button in Hidden apps

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1444]
Current state:
![Screenshot_20201213-140732_Niagara Launcher](https://user-images.githubusercontent.com/35201200/102012815-c06b5300-3d4c-11eb-89ef-e48601730806.jpg)
Expected:
![Screenshot_20201213-140739_Niagara Launcher](https://user-images.githubusercontent.com/35201200/102012821-c5c89d80-3d4c-11eb-982e-8fac684cc62f.jpg)

**Comment by 8bitPit** [comment]
Makes sense 👍

**Comment by 8bitPit** [comment]
Fixed in v.1.2
