### ISSUE TITLE
Music Controls doesn't work when we play music by using google assistant

### ISSUE THREAD

**Issue by Veecks** [8bitPit/Niagara-Issues#1446]
**Describe the bug**
When we say google assistant to play a song and then return to home screen and try to control it with the niagara media widget it doesn't work

**To Reproduce**
1. Say "Ok google"
2. Ask it to play a song. Ex: "Play a song on Spotify"
3. Press your home screen button/swipe up to homescreen.
4. Try to pause the music.
5. It will not work. See error.

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Note 10]
 - Android version: [e.g. Android 10 (One UI 2.5), updated]

**Screenshots**
Screenshots aren't applicable, but I have a screen record.

**Comment by 8bitPit** [comment]
Thanks for reporting, @Veecks! Does the same happen on Niagara Launcher's latest version (v0.34.1)? And if so, does it happen every time you do the steps you mentioned?

**Comment by Veecks** [comment]
Hello, yes it does happen in Niagara 0.34.1 and it happened every time I tried

**Comment by 8bitPit** [comment]
Thanks for the update @Veecks, we'll look into it.

**Comment by Amorphous404** [comment]
I can't reproduce the issue.

https://user-images.githubusercontent.com/96917972/209556739-6386352f-8f42-4234-8de0-936ba21e7a96.mp4

**Comment by 8bitPit** [comment]
Thanks for testing @Amorphous404. @Veecks does the issue still appear on your device?
