### ISSUE TITLE
Remove unwanted search terms from Search History

### ISSUE THREAD

**Issue by mrtrevelyan** [8bitPit/Niagara-Issues#1448]
Request:
The ability to remove search terms from the search history that appears below the search menu (I'm using the Sesame integration and pro alpha build 0.34.1).

Possible solution:
Holding down on the relevant search item to bring up an option to remove the search term.

Thank you for listening!

**Comment by 8bitPit** [comment]
Thanks for your request, @mrtrevelyan. Unfortunately, Sesame doesn't provide us a method to hide a specific search result yet. Please forward this issue to their issue tracker: https://github.com/SesameCrew/sesame_issues.
However, you can hide search results from within their app, and they won't show up in Niagara Launcher as well, although that's a bit of an inconvenience.
