### ISSUE TITLE
Setting Digital Wellbeing time limit locks Home, Recents and Back buttons

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1453]
If I open the Digital wellbeing panel, I have for example used Chrome for 2 hours. If I then set the time limit to e. g. 15 minutes, Chrome is now correctly blocked, but my phone gets stuck at the Digital Wellbeing screen. I can interact with it, but cannot leave it because neither Home, Recents nor Back button works. So the UI is responsive, just not the buttons.

To fix this I had to restart the device – except once, when I was able to get back to the home screen after waiting for about 15 seconds, this time I noticed the icon is greyed and the app is blocked, so it works, just causes this freeze/buttons lock.

My Galaxy J7 running Android 9 has the Digital Wellbeing feature, but it uses Samsung's own service, so it may be caused by their implementation.

Edit: This issue doesn't occur with other launchers (tried Nova and stock Samsung Launcher).

I'm using Niagara 0.34.1 but I don't know whether this issue is new or not as I've not used Digital Wellbeing before.

(If any logs could be useful, I've adb installed on my PC, so I could help with that if needed.)

**Comment by Cyberdroid1** [comment]
Try again without Niagara.

**Comment by Martin5001** [comment]
> Try again without Niagara.

Sorry, forgot to mention, but yes I did that. Tried with Nova and the stock launcher and this issue didn't occur.

**Comment by Martin5001** [comment]
Sorry to everyone for making this confusing – I came back to test it again after @Cyberdroid1 commented and **the issue is no longer present**, so I'm closing it.

(I think the issue was caused by Samsung Secure folder, because it now works since I uninstalled it. Most likely the problem was Secure Folder creating separate instance of Chrome, which digital wellbeing then couldn't access.)
