### ISSUE TITLE
Favorites list and widget too high

### ISSUE THREAD

**Issue by EbonJaeger** [8bitPit/Niagara-Issues#1454]
**Describe the bug**
When on the home screen, the widget and favorite apps list appear to be being drawn higher than they should be, with the default clock widget being half off the screen. Interestingly, the alphabet list seems to be in the correct location.

**To Reproduce**
1. Go to the home screen

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G7 Optima Maxx
 - Android version: Android 10
 - Niagara Version: 0.34.1

**Screenshots**
![Screenshot_20201228-182946.png](https://user-images.githubusercontent.com/5157277/103249164-ee9b8600-493b-11eb-9b3d-65c39fa59969.png)

**Comment by EbonJaeger** [comment]
Holy cow that pasted huge... uhh.. Oops.

**Comment by Nxt3** [comment]
I've had this happen a few times upon returning to the homescreen.

**Comment by 8bitPit** [comment]
Hey @EbonJaeger, apologies for my late reply. I believe you're referring to this bug: https://github.com/8bitPit/Niagara-Issues/issues/1069. You can work around it by going to Niagara's settings > Features > Niagara widget > Move widget

**Comment by EbonJaeger** [comment]
@8bitPit no worries! Thanks for the workaround; I must have missed that other issue before. Sorry!

**Comment by 8bitPit** [comment]
Glad it helped @EbonJaeger :D
