### ISSUE TITLE
Ability to resize and allow media widget to be displayed all the time.

### ISSUE THREAD

**Issue by lukeyeh** [8bitPit/Niagara-Issues#1455]
**Is your feature request related to a problem? Please describe.**
1. The ability to resize the media widget. (Currently AFAIK there is only one size for the media widget)
2. Have the media widget be always displayed.

**Describe the solution you'd like**
Seems like the default media widget does not act as a normal widget. Perhaps the solution is to design a custom widget and this may solve the issue.

**Comment by 8bitPit** [comment]
Thanks for your requests, @lukeyeh. For the sake of simplicity, we only want to offer one widget size. You can read more about why that is here: https://help.niagaralauncher.app/article/8-niagaras-design-principles. Moreover, afaik, there's no reliable way for a launcher to offer a persistent media widget (https://github.com/8bitPit/Niagara-Issues/issues/375).
