### ISSUE TITLE
Cannot set as default launcher

### ISSUE THREAD

**Issue by FuryMartin** [8bitPit/Niagara-Issues#1456]
**Describe the bug**
Cannot set Niagara as default launcher on EMUI 11

**Smartphone:**
 - Device: [Honor 30 pro]
 - Android version: [EMUI 11]

**Screenshots**
![Screenshot_20210103_031854_com.android.permissioncontroller_edit_1023601596718.jpg](https://user-images.githubusercontent.com/41051953/103464960-d4fea200-4d72-11eb-8e88-fa8a4e66916e.jpg)

**Possible Reason**
This may relate to HUAWEI's HMS

**Comment by 8bitPit** [comment]
Hi @FuryMartin, I believe this is because Huawei made the decision to block third-party launchers in China: https://www.xda-developers.com/huawei-confirms-blocking-third-party-launchers-chinese-emui-9/. I'm sorry.
