### ISSUE TITLE
Search results placed incorrectly

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1457]
Niagara v 0.90.1 on Android 9, Sesame integration enabled – Search results are placed like this:
![Screenshot_20210104-155922_Niagara Launcher](https://user-images.githubusercontent.com/35201200/103548573-48ed9700-4ea6-11eb-8d0c-d021a2ace7b6.jpg)
Closing and reopening Search again fixed it. I've not noticed this happening before 0.90.x release. Btw. I disconnected my Bluetooth headphones about the same time as entering Search, so when I then came back to Home, it was hiding the Music apps list and the media widget. So maybe that is related. This issue happened twice so far, but I haven't found a way to reproduce it.

**Comment by 8bitPit** [comment]
Interesting. I couldn't find a way to reproduce this either.

**Comment by Martin5001** [comment]
I encountered this again, couldn't reproduce it this time either, but again the media player was shown. In this situation it wasn't hiding the player though like before, I just went from Chrome playing video to home screen and then opened search and it was offset like before.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1342
