### ISSUE TITLE
Niagara Dots does not support shortcuts

### ISSUE THREAD

**Issue by 71** [8bitPit/Niagara-Issues#1459]
**Describe the bug**
When Niagara Dots is enabled, shortcut icons keep their appearance.

**To Reproduce**
1. In Chrome, visit a website and press "Add to Home screen" to create a shortcut (there are other ways to create shortcuts, but this is an easy one).
2. Enable Niagara Dots.
3. Shortcuts will keep their icons instead of being dots, unlike regular app icons.

**Smartphone:**
 - Device: Pixel 4
 - Android version: Android 11

**Comment by 8bitPit** [comment]
Hi @71 👋 To still see shortcut icons in your swipe actions, Niagara dots doesn't change their icons by default, but you can do that manually by long-pressing on the shortcut and tapping on the icon in the options dialog. I hope that helps :)
