### ISSUE TITLE
Add Google Tasks to Integrated Calendar

### ISSUE THREAD

**Issue by DerekRoberts** [8bitPit/Niagara-Issues#1460]
**Is your feature request related to a problem? Please describe.**
No.  It's a feature to make Google Tasks users happy.

**Describe the solution you'd like**
The integrated calendar is great.  If Google Tasks could be added it would be good enough to replace my Business Calendar 2 widget.  Please look at the widget in the screenshot below.  Anything with a checkbox is a Google Task.

![Widget with Google Calendar and Tasks](https://user-images.githubusercontent.com/4391600/104079993-7e61ef80-51da-11eb-9b33-314a8df40b47.png)

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by luxcalor** [comment]
That will be really nice indeed

**Comment by 8bitPit** [comment]
Unfortunately, in contrast to calendar events, Google doesn't provide access via an offline API to tasks: https://github.com/8bitPit/Niagara-Issues/issues/1347

**Comment by DerekRoberts** [comment]
@8bitPit Thanks for the response and sorry about the duplicate.  Sounds like I should be sending requests to Google instead.

**Comment by 8bitPit** [comment]
No problem at all @DerekRoberts 😀
