### ISSUE TITLE
Show search results from bottom to top. 

### ISSUE THREAD

**Issue by praveenchandranpk** [8bitPit/Niagara-Issues#1461]
**Is your feature request related to a problem? Please describe.**
One hand usage in bigger phones is an issue currently as the results are shown from the top to bottom. 

**Describe the solution you'd like**
Show most matched search results near the keyboard. 

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by JHerseth** [comment]
Cant you just tap the search icon on the keyboard to activate the top search result? I can, but I also use Sesame together with Niagara.

**Comment by 8bitPit** [comment]
To keep Niagara Launcher simple, we don't plan on adding a toggle to sort search results the other way round. Niagara's search should already be one-hand-friendly because of the "press search to open" button.

**Comment by praveenchandranpk** [comment]
It's not just press to open. There are many other functions. What if I search for a contact to call them by swiping left for the menu? What if I want access the shortcuts of the searched item?  And what if I want open the second item on the search list? In bigger phones it's an issue. It's my experience. KISS launcher and sesame app has that functionality.
