### ISSUE TITLE
Remove 5secs delay for KLWP launching intents

### ISSUE THREAD

**Issue by JHerseth** [8bitPit/Niagara-Issues#1462]
**Is your feature request related to a problem? Please describe.**
When you press "home" Android will introduce a 5 secs delay to any app and service trying to execute an intent unless the app sending that intent is the current launcher. This prevents Kustom Wallpaper to launch apps without delay since it is running as a service. 

**Describe the solution you'd like**
Workaround described here:
https://help.kustom.rocks/i194-launchers-touch-features-support-aka-remove-5-secs-delay

**Comment by 8bitPit** [comment]
Thanks for your request, @JHerseth (and apologies for my late response). Depending on how many users are requesting the workaround for the 5 secs delay, we might add it.

**Comment by Clybell** [comment]
Hello! I'm also having this issue, and it would be nice if the workaround could be added.

**Comment by YosefBayoude** [comment]
Same I am having this issue as well, would be nice if it got solved

**Comment by 8bitPit** [comment]
I heard that this issue, fortunately, has been fixed on Android 11 (https://help.kustom.rocks/i2745-clarification-for-fixes-for-delay-to-launch-in-android-11-for-klwp-klck-in-latest-versions). This would be great news because the workaround that KLWP suggests is super hacky.

**Comment by YosefBayoude** [comment]
Unfortunately I can't confirm, I'm on Android 10, but for those in the same situation (or if it isn't fixed) I have found a workaround.
!! Requires ROOT and EdXposed !!
https://github.com/GermainZ/StopSwitchDelay
Works decently for me

**Comment by Maxr1998** [comment]
I just tested this again and can confirm that it is in fact fixed on Android 11 and above.
Since the proposed workaround for earlier versions is, as mentioned, quite hacky, we're not interested in implementing it and will thus close this report.
