### ISSUE TITLE
SIGNAL chat bug

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1463]
This bug happens when I receive messages on signal. When I have 1, 2 or more chats, I can't enter a specific chat as I used do in WhatsApp. If I touch the chat, it doesn't even open the app. Instead, I have to open the entire app, in order to open a specific conversation. It's important because signal is very relevant now.

Second bug happens when I send a message using niagara's chat. The chats closes at the first message I send, so it is impossible to have a normal conversation. In order to continue with the chat (conversation) I have to open the entire app. 
It was not the case with WhatsApp where I could send multiple messages using the niagara's chats.
That's very frustrating because signal is the main app for both me and many of my contacts now

 - Xiaomi mi 9t
 - Miui 12
 - Android 10

**Screenshots**
![IMG_20210111_214257](https://user-images.githubusercontent.com/72170242/104266814-0273db80-5456-11eb-800c-29f787fae87b.jpg)

![IMG_20210112_102158](https://user-images.githubusercontent.com/72170242/104342073-118f7380-54c0-11eb-918c-1b51c5a04bde.jpg)

**Comment by Just-SKY** [comment]
The same thing is happening with telegram and other apps, I just tested is not working as it use to be. I don't know if change like that in the new update

**Comment by Just-SKY** [comment]
Now, I don't know if this is the way that this normally work with other apps because I installed other apps and the same thing happened then installed WhatsApp just to test, and it works normally.
Let me know if it is really a bug, or just WhatsApp is like that after test many apps.
It would be very frustrating if only WhatsApp works like I reported above.

**Comment by 8bitPit** [comment]
Thanks for reporting :D Can you please check if both appear in Android's notification shade?

**Comment by Just-SKY** [comment]
Yes, both appear in Android's notification shade.

**Comment by 8bitPit** [comment]
Oh, sorry, I meant if you could check if both _issues_ appear in the notification shade.

**Comment by Just-SKY** [comment]
Crap , it happens in the notification shade as well. "Game over" 😞. This makes me hate WhatsApp even more. 😓

**Comment by Just-SKY** [comment]
In the notification shade, I can't send multiple messages because it closes at the first message sent.
However, about opening specific conversation is something I can do, using the notification shade, which is something I can't do using niagara's chat. I think that  the first one there is nothing to do about it, but the second one maybe there is some that can be done.

**Comment by 8bitPit** [comment]
I see, thanks for testing, @Just-SKY. Can you please also try if tapping on Signals notification in another launcher opens the specific conversation? Most other launchers show notifications of an app after you long press on its icon.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
