### ISSUE TITLE
Add new event button in Agenda header

### ISSUE THREAD

**Issue by luxcalor** [8bitPit/Niagara-Issues#1465]
When there are several events in the day, current "new event" button is way down in Agenda, gets lost among events and is not convinient to find and reach. 

A simple + button in the upper right corner of Agenda view would be instant to reach and universal. 

Opening calendar by tapping "Your agenda" would be nice too. Then tapping on the date could open the day view in calendar, if that is possible to implement. 

![20210114_022743](https://user-images.githubusercontent.com/76074147/104529552-b326da00-5612-11eb-8334-762249b189b6.jpg)

**Comment by 8bitPit** [comment]
Thanks for the idea @luxcalor. I could also imagine a floating action button on the bottom right would fit this use case: https://material.io/components/buttons-floating-action-button

**Comment by luxcalor** [comment]
Agreed, if done right the floating action button would be even better. 👍

**Comment by Rod911** [comment]
New event button is shown on top under current date

**Comment by luxcalor** [comment]
Well, if there are many (5 or more) events in the day  the new event button is not on top at all currently. Peter's idea of floating button to add events is very good imo.
