### ISSUE TITLE
App icon reappears in "app-folders" after uninstall

### ISSUE THREAD

**Issue by luxcalor** [8bitPit/Niagara-Issues#1466]
App icon reappears in "app-folders" after uninstall. When tapped suggests installing the app. When deleted from the folder reappears again after some time. Happens only in app folders, not in the app drawer or favorites.

**Comment by 8bitPit** [comment]
Thank you for reporting :)

**Comment by 8bitPit** [comment]
Does the issue still happen on v1.2? If so, please let me know :)

**Comment by luxcalor** [comment]
Hi Peter,
No, this doesn't happen in 1.2. It's an amazing update, thank you very much.

**Comment by 8bitPit** [comment]
Awesome, thank you very much for getting back :D
