### ISSUE TITLE
Show icon pack categories in custom icon selection screen

### ISSUE THREAD

**Issue by luxcalor** [8bitPit/Niagara-Issues#1468]
Option to access third party icon pack's native application while changing icon for a partıcular app. It is often faster to find icons by categories provided in native apps.

**Comment by 8bitPit** [comment]
Agreed :)

**Comment by 8bitPit** [comment]
Implemented in v1.7: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b; thanks for your suggestion!
