### ISSUE TITLE
Duplicates in icon pack search 

### ISSUE THREAD

**Issue by luxcalor** [8bitPit/Niagara-Issues#1469]
Icon duplicates appear in search results within an icon pack. Reev Pro in this case. Not sure if it is a Niagara isuue, but this doesn't happen in other launchers with the same pack. 

![S10114-13221841](https://user-images.githubusercontent.com/76074147/104585497-c5cdfd00-566c-11eb-92fc-93505e4c36e6.jpg)

**Comment by 8bitPit** [comment]
Thanks for reporting @luxcalor. We'll fix this in v1.2.

**Comment by 8bitPit** [comment]
Fixed in v.1.2
