### ISSUE TITLE
[To Close]Blur wallpaper when displaying all app list

### ISSUE THREAD

**Issue by billouetaudrey** [8bitPit/Niagara-Issues#1472]
Hi, I have a little idea/suggestion, Is it possible to blur wallpaper when display all app ? Thanks :)

It's perfect for better look of app name ;)

Thanks

**Comment by billouetaudrey** [comment]
Sorry found here https://help.niagaralauncher.app/article/64-blur-wallpaper

**Comment by Rod911** [comment]
Thanks for the request, as this was already requested and discussed in #14, I'm closing this ticket.

Duplicate of #14
