### ISSUE TITLE
Add an option to display only text and no icons

### ISSUE THREAD

**Issue by edapm** [8bitPit/Niagara-Issues#1476]
**Is your feature request related to a problem? Please describe.**
Although there is an option for having no text and only icons, there isn't one for only text (no icons).

**Describe the solution you'd like**
Add the option to have only text displayed and no icons. (Example: In [Before Launcher](https://beforelabs.com))

**Comment by Rod911** [comment]
This was discussed and decided not to implement it. See #140

**Comment by edapm** [comment]
Oops sorry I didn't notice #140

**Comment by 8bitPit** [comment]
No problem, @edapm :)
