### ISSUE TITLE
Split Screen not supported

### ISSUE THREAD

**Issue by thesumitnew** [8bitPit/Niagara-Issues#1477]
I need to use Split Screen feature,  I can use 2 apps at the same time in split Screen feature in launcher of my Phone but in Niagara Launcher Split Screen not supported. Please fix this issue.

**Comment by 8bitPit** [comment]
Hi @thesumitnew, your device seems to not support split-screen mode in combination with third-party launchers. Does split-screen work with other third-party launchers like Nova Launcher or Microsoft Launcher?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)
