### ISSUE TITLE
Gallery Images as icons.

### ISSUE THREAD

**Issue by Shaheer0983** [8bitPit/Niagara-Issues#1478]
**Is your feature request related to a problem? Please describe.**
I like making my own icons and In sure many of us do. But Im not a developer and dont know how to turn them into apks. When I use shortcut maker to apply those icons notification functionality of niagara is lost.

**Describe the solution you'd like**
Like nova launcher and lawnchair I think niagara should allow gallery images to be used as icons.

**Comment by 8bitPit** [comment]
Hey, sorry, but we don't plan to add this in the near future: https://github.com/8bitPit/Niagara-Issues/issues/581
