### ISSUE TITLE
Weather widget not working

### ISSUE THREAD

**Issue by erbold-bu** [8bitPit/Niagara-Issues#1479]
**Description**
Even though location access is allowed and the weather widget is enabled, the weather information doesn't show on the homescreen at all.

**To Reproduce**
1. Allow location access to Niagara Launcher
2. Enable weather widget in Niagara settings

**Smartphone:**
 - Device: Samsung Galaxy Note 20 Ultra
 - Android version: Android 10

 **Screenshots**
![20210124_121016](https://user-images.githubusercontent.com/66581972/105620160-26172880-5e3d-11eb-9628-7391702337b6.jpg)

**Comment by Just-SKY** [comment]
Do you have pro-version? Or Did you were trying a limited free trial? 
That's a possibility of why it stopped working.

**Comment by 8bitPit** [comment]
Hi @erbold-bu, please send us your order number of Niagara Pro via mail (support@niagaralauncher.com), and we'll help :) Here's how to retrieve the order number: https://help.niagaralauncher.app/article/18-looking-up-order-number.

**Comment by Heloomg** [comment]
Have the problem been resolved ? And can i ask for you phone wallpaper ?

**Comment by aruchomka** [comment]
necroposting but where did you get these super cool pixelated icons???

**Comment by happen2me** [comment]
> necroposting but where did you get these super cool pixelated icons???

I fount it! [PixBit](https://play.google.com/store/apps/details?id=pixbit.prime)
