### ISSUE TITLE
Reduce/ Increase font size 

### ISSUE THREAD

**Issue by bumjrah** [8bitPit/Niagara-Issues#148]
Especially for home page. So icon can look bigger/stand out more than the text. Or to go even further, option to remove text and remain icon only for home.

**Comment by 8bitPit** [comment]
Hiding them completely would be troublesome: https://github.com/8bitPit/Niagara-Issues/issues/79

**Comment by TFackler** [comment]
Anyone stumbling upon this, hiding the app names is implemented since v.0.7.5a4. 
Please refer to [#79](https://github.com/8bitPit/Niagara-Issues/issues/79#issuecomment-591304719)

**Comment by TomDeSmet** [comment]
Changing font sizes would be great! Good for A11Y too.
