### ISSUE TITLE
Integration issue with latest sesame beta update.

### ISSUE THREAD

**Issue by prtkjn95** [8bitPit/Niagara-Issues#1480]
In the latest sesame update device search is finally fixed and works perfectly. However same doesn't work with niagara launcher Integration. And i assume its because niagara doesn't have storage permission to read device files. 

1. Join sesame beta update and install.
2. Now search for any files with niagara launcher and click on it.
3. Now it will give you error saying "Error"
4. Do the same with sesame app and it is working fine. So issue is with niagara launcher.

**Smartphone**
 - Device: [Redmi Note 8 Pro]
 - Android version: [e.g. Android 10]

**Screenshots**
![Screenshot_2021-01-25-11-43-37-856_bitpit launcher](https://user-images.githubusercontent.com/69669829/105668139-bc615200-5f02-11eb-8d3e-f6900c301aa3.jpg)

**Comment by prtkjn95** [comment]
Well screw this launcher. Back to tried and trusted nova. Wastage of 1 year subscription. Dev is non responsive. Reported this issue multiple times in telegram group too. Lol no one cares.

**Comment by 8bitPit** [comment]
Well, there they go. If you're reading this, you can always request a refund if you're unhappy with Niagara Pro. Moreover, for quick support, please write us at niagaralauncher@gmail.com

**Comment by kd-21** [comment]
Home navigation buttons not hide in remi note 8 pro

**Comment by kd-21** [comment]
Because i update mobile version 10 to 12 so i give me third party gesture not working. So please help me how can i remove button with using niagra app

**Comment by Amorphous404** [comment]
Hi @kd-21, Please refer to this article: [Gesture Navigation Issues](https://help.niagaralauncher.app/article/7-gesture-navigation)
