### ISSUE TITLE
Niagara Settings activity flashes after closing

### ISSUE THREAD

**Issue by jiruffe** [8bitPit/Niagara-Issues#1481]
**Describe the bug**
Niagara Settings activity flashes after closing with gesture navigation

**To Reproduce**
1. Go to Niagara Settings
2. Swipe up on gesture navigation bar
3. See error

**Smartphone**
 - Device: Sony Xperia 1
 - Android version: Android 11

**Screenshots**

https://user-images.githubusercontent.com/16442741/105692795-d79b8400-5f39-11eb-9939-dd11ce65979c.mp4

**Comment by 8bitPit** [comment]
Thanks for letting us @jiruffe :) I'll check what I can do about that (it may take some time because we're busy planning Niagara Launcher's release right now).

**Comment by 8bitPit** [comment]
Fixed in v.1.2
