### ISSUE TITLE
Ability to change search engine from Google. 

### ISSUE THREAD

**Issue by lcw731** [8bitPit/Niagara-Issues#1484]
Would like ie to be able do change search from Google. Preferably search engine of my choosing, or at least able to change to duck duck go or start page.

**Comment by 8bitPit** [comment]
Thanks for the request @lcw731, we're planning to add that: https://github.com/8bitPit/Niagara-Issues/issues/142

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/142
