### ISSUE TITLE
Selectable square (edgy) theme 

### ISSUE THREAD

**Issue by Aesew** [8bitPit/Niagara-Issues#1487]
In android 9 and above niagara looks like a default launcher with its curved style. But when using android 8 or  below it doesn't gives the same vibe. Because these versions is styled square. To fix this there could be a option to select a square theme, or there can be a edge radius changer.
I know niagara is simple but i want it to be looks similiar with the android version i use. People like me, will love this.

**Comment by Martin5001** [comment]
> To fix this there could be a option to select a square theme, or there can be a edge radius changer.

I think it should rather change automatically based on the Android version. This way no additional toggle would be needed.

**Comment by Aesew** [comment]
> > To fix this there could be a option to select a square theme, or there can be a edge radius changer.
> 
> I think it should rather change automatically based on the Android version. This way no additional toggle would be needed.

Yeah, this could be a better implementation.This one will be more simple and fit the simplicty of niagara.

**Comment by 8bitPit** [comment]
Hey @Aesew, thanks for your suggestion. I believe most users want to have a uniform experience across Android versions. Afaik, other launchers, or apps don't have Android-specific themes as well. Moreover, we also try to keep things uniform to make development and testing easier (https://help.niagaralauncher.app/article/8-niagaras-design-principles). Sorry.
