### ISSUE TITLE
Customizing Swipe Actions

### ISSUE THREAD

**Issue by AustinTHoag** [8bitPit/Niagara-Issues#1489]
Hello,

I haven't ran into any issues, but I wanted to post an idea that I would love to see implemented. I'm an extreme novice when it comes to app development, so I am unsure if this is possible or not.

I would love to be able to fully customize the suggestions that pop up when do you swipe actions over the apps. I know you are able to add/remove other apps, as if it is behaving like an app folder. But, some of them are in there by default, and cannot be removed. I've attached a screenshot of what I'm meaning, and blurred out some personal info.

Green = I am able to add/remove this option

Red = I am unable to remove these options

![Screenshot_20210202-143600](https://user-images.githubusercontent.com/78443859/106653358-b0117080-6564-11eb-94fa-ff4bffaf1cf2.png)

Apologies if this has already been requested, I couldn't find anything already posted about this. Again, I am very new to this, and joined GitHub specifically to post on here. I love Niagara Launcher, so keep doing what you're doing!

**Comment by 8bitPit** [comment]
Hi @AustinTHoag, sorry for the late reply. I hope this guide helps: https://help.niagaralauncher.app/article/84-hide-shortcuts

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
