### ISSUE TITLE
Cluttered bottom - Option to move Google Fab to top

### ISSUE THREAD

**Issue by Sacchid** [8bitPit/Niagara-Issues#149]
Cluttered bottom, especially with notifications on recent apps. 
![screenshot_20180909-102502](https://user-images.githubusercontent.com/22224760/45261222-2ef93200-b41b-11e8-90a9-e58018bb5125.png)

 Option to move Google Fab to top

**Comment by rastamanjohn** [comment]
I think it will be quite uncomfortable to have to reach all the he way up...

**Comment by rastamanjohn** [comment]
To declutter, I'd suggest having the frequent apps visible on a sort of 'next Page's by scrolling a bit, so we don't have to see the white line at first

**Comment by 8bitPit** [comment]
@rastamanjohn I agree, it would go against the "one hand usage design". Maybe I'll a swipe up gesture for accessing search / showing your recently used apps

**Comment by Sacchid** [comment]
1. I didn't though that it'll uncomfortable to reach way up, as don't use big phone. And there was non assigned space.
2.

**Comment by Sacchid** [comment]
Or integrate with home button press (option) ie option between custom Nigara search and Google search as one can open apps directly via Google search. 
![screenshot_20180909-151417](https://user-images.githubusercontent.com/22224760/45263257-a2af3500-b443-11e8-830d-c8a2acd7d24f.png)

**Comment by 8bitPit** [comment]
Then you would loose one the button's feature: either Google quick search or Google App
