### ISSUE TITLE
Sort Favourites my most used (Like Alphabets)

### ISSUE THREAD

**Issue by Onomic** [8bitPit/Niagara-Issues#1490]
I am suggesting an option be added to allow favourites to be sorted by most used. I understand there is a feature to add suggested apps below favourites but this is not enough. First problem is it takes a while to suggest. The bigger issue is if you have a lot of favourites there are no suggestions. I used to have a app called "app swap" and it was a simple concept that would sort your drawer by most used. It was genius
 Likewise I would love to see my favorites sorted by most used because right now I have to manually do this and it's extremely time consuming and annoying. The suggestions feature as stated above doesn't show suggestions with lots of favourites so what's the point?

**Comment by 8bitPit** [comment]
I'm sorry, but we don't have plans to make the maximum number of suggestions customizable: https://github.com/8bitPit/Niagara-Issues/issues/454. We believe the most efficient way to set up Niagara Launcher is by having 8 favorites and accessing the rest of the apps via the alphabet (its sub-sections are sorted by usage) and with swipe actions: https://help.niagaralauncher.app/article/38-folders.
