### ISSUE TITLE
pending notifications on top of favorites 

### ISSUE THREAD

**Issue by berdzena** [8bitPit/Niagara-Issues#1491]
First off all, It's great launcher for daily use and thanks to developers... only one thing that I'm missing is to show pending notifications on top of the favorites.. i mean from apps that are not in favorites.. Thanks.. 🙏 (sorry for my bad English)

**Comment by 8bitPit** [comment]
Hi @berdzena, something similar is planned 😄 https://help.niagaralauncher.app/article/35-notification-section

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/152
