### ISSUE TITLE
Apps to the right

### ISSUE THREAD

**Issue by rbj1112** [8bitPit/Niagara-Issues#1492]
Can the option to move the apps to the right be implemented for us left handers.

**Comment by sgregson** [comment]
Might be worth noting that while the alphabet appears on the right, you can still use the left edge to scroll through the app list.

Check out https://help.niagaralauncher.app/article/39-left-hand-mode

**Comment by 8bitPit** [comment]
Thanks a lot for helping them out @sgregson :)

**Comment by 8bitPit** [comment]
@rbj1112 if you have any further questions, please let me know.
