### ISSUE TITLE
Allow several profiles

### ISSUE THREAD

**Issue by tsvikas** [8bitPit/Niagara-Issues#1493]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I'm driving and need a different set of favorites than usual. Or I'm at work and need a different set of favorites .

**Describe the solution you'd like**
User can set different "profiles", each with different favorite apps (and maybe different notification settings.
Optional: the launcher switch to the right profile when it recognize location / wifi / etc.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

I believe it possible to keep this feature simple - I imagine one button with the profile name, pressing it allows the user to choose a different profile.
More than that, it'll allow users to keep each favorite list short - further simplifying the phone use.

**Comment by GintokiHub** [comment]
https://github.com/8bitPit/Niagara-Issues/issues/13 
perhaps these could be merged?

**Comment by 8bitPit** [comment]
Hi @tsvikas, I'm sorry, but we're not planning on supporting different profiles (https://github.com/8bitPit/Niagara-Issues/issues/1335). However, we just added [folder support](https://medium.com/niagara-launcher/pop-up-date-4a5d3522df2d) and are considering adding an API for Tasker in the future (#786).
