### ISSUE TITLE
Choppy animation on Oxygen OS 11

### ISSUE THREAD

**Issue by adamkhldanial** [8bitPit/Niagara-Issues#1496]
**Describe the bug**
Exiting from any application, to the homescreen in Oxygen OS 11 is somewhat choppy, like there's a brief second of the screen lagging/glitching out before you can use it. When I swipe up to go back to the homescreen, it takes a split second for icons and everything to appear and during that it's just the blank home screen.

**To Reproduce**
1. Go to any application
2. Go back to the homescreen
4. The animation kinda lagging/glitching

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - Android version: Android 11

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

https://user-images.githubusercontent.com/78545904/106900742-d6d0d200-6731-11eb-834d-9751dd1dce9c.mp4

**Comment by bmalin92** [comment]
I had this experience on my Pixel 5 when I first installed the launcher. In my case, restarting the device resolved it for me. Not sure if it will help in your situation, but figured I'd pass it on.

**Comment by adamkhldanial** [comment]
Hi @bmalin92 first of all, thanks for your suggestion but I have restart my phone a couple times, and it seems like the glitch still appears. I have also cleared the launcher's cache and restarted it. Whether this glitch because of OOS 11 towards third party launcher (in this case Niagara), or there is a bug in Niagara that makes the animation kinda lagging.

**Comment by 8bitPit** [comment]
Unfortunately, we have no control over that. A submodule of the preinstalled launcher handles all the gesture navigation animations: https://help.niagaralauncher.app/article/7-gesture-navigation.
