### ISSUE TITLE
Transparent background on menus

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#15]
the menu when you hold/swipe right (or folder menu, which is in issue 13) should have an option to make it have a transparent/translucent background with an option to add blur

**Comment by 8bitPit** [comment]
A blur option is more memory consuming and doesn’t go for live wallpapers. Furthermore, for solely that feature Niagara must be granted reading your files (storage permission), which I am not a huge fan of.

**Comment by 587saboor** [comment]
@8bitPit oh ok, so should it rely on the background blur? As shown here https://github.com/8bitPit/Niagara-Issues/issues/14

**Comment by 8bitPit** [comment]
Both issues have the same implementation problem

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.

**Comment by Amorphous404** [comment]
Merged with #1674
