### ISSUE TITLE
Search the web instead of the playstore

### ISSUE THREAD

**Issue by andys8** [8bitPit/Niagara-Issues#1501]
## Currently

A search string marching no app or shortcut will default to a search in the play store

## Proposed Change

Instead of searching in the play store, search on the web. Or make it configurable.

## Reason

I'm installing maybe 10 apps a year. I'm searching for stuff on the web thousands of times. It would be quicker if this could be done directly with the search bar and not defaulting to a play store search.

![Screenshot_20210207-021612](https://user-images.githubusercontent.com/13085980/107133702-4e962c80-68eb-11eb-9436-02a6a8ac3f6e.jpg)

**Comment by adamkhldanial** [comment]
Hi @andys8 in order to access the global search, you need to integrate Niagara with Sesame. And after that, you can use the Niagara search bar as the global search with additional features/shortcuts. 

You also can read it here: 
https://help.niagaralauncher.app/article/20-sesame-integration

**Comment by andys8** [comment]
## Status

* Sesame integration is marked as blocked https://github.com/8bitPit/Niagara-Issues/issues/1914#issuecomment-1097003474
* Web search feature is planned https://github.com/8bitPit/Niagara-Issues/issues/1828#issuecomment-1026168956

@8bitPit How good are chances this feature is going to land?

**Comment by 8bitPit** [comment]
Quite good ^^

**Comment by topsy-turvy99** [comment]
> Quite good ^^

> ![IMG_20220901_005356.jpg](https://user-images.githubusercontent.com/96917972/187765204-7fed084c-b050-4f09-ad40-de7751ab0bef.jpg)
> 

Was just curious, Point no 2 from #1828, the option to complete the search query whether via Google app or default browser will also be added?

**Comment by 8bitPit** [comment]
Great news, @andys8, our integrated web search is now in beta: https://medium.com/niagara-launcher/going-global-6bb58c2d6bb7#:~:text=Bonus%3A%20Beta%2DTest%20Web%20Search.
> ![image](https://user-images.githubusercontent.com/9284845/207311589-420e18a4-120c-4a1f-aeee-911bece64b8e.png)
As a little bonus, we’re also inviting all of you to the beta of a feature that will be useful for everyone: Web search results right in Niagara Launcher’s app search. By using the secret command [/web-search](https://niagaralauncher.app/app-link/secret-command?cmd=web-search) you opt in to our beta and can start searching the web right away, no third-party integration or Niagara Pro is required.

I hope it's okay if I close the ticket.

**Comment by andys8** [comment]
Hey there, pretty cool. Do you think a different mode could work too?

Right now, every input will result in a search suggestion, therefore sent to the search provider and make the whole launcher appear slower. The fallback is still app search in the store. I personally would prefer not sending the suggestions to Google, but have the fallback changed to a search instead.

**Comment by 8bitPit** [comment]
Great point, @andys8. We'll try out showing the first web suggestion (which is the user's original input) immediately and decouple it from the true search engine suggestions.

**Comment by Maxr1998** [comment]
> Great point, @andys8. We'll try out showing the first web suggestion (which is the user's original input) immediately and decouple it from the true search engine suggestions.


This issue should be fixed in [v1.10.0](https://github.com/8bitPit/Niagara-Issues/releases).
