### ISSUE TITLE
Color options for Google button on dark backgrounds

### ISSUE THREAD

**Issue by bmalin92** [8bitPit/Niagara-Issues#1502]
If you use a wallpaper with a lot of black in it, the Google button in the bottom-right usually turns black and blends in with the wallpaper (especially on OLED screens). I think it'd be nice if we could have a little more control over the icon's color.

Example of blending here: https://imgur.com/a/IpCS0MA

This is probably my favorite launcher I've ever used, so thank you for creating such a masterpiece :)

**Comment by 8bitPit** [comment]
Thank you very much for your kind words @bmalin92 :) I'm sorry, but we decided to not add further customization options in the upcoming months: https://help.niagaralauncher.app/article/44-feature-requests
