### ISSUE TITLE
Option to show search results from bottom of the screen

### ISSUE THREAD

**Issue by VikramNisarga** [8bitPit/Niagara-Issues#1503]
Sesame has an option to show search results from bottom of the screen which helps in single handed use of phone with tall screen. It would help a lot if Niagara Search had the same option as well

**Comment by 8bitPit** [comment]
Hi @VikramNisarga, we decided to keep everything arranged from top to bottom for uniformity. In my opinion, our search screen is already tall-phone-friendly because you can launch the first search result with the search key on your keyboard.

**Comment by VikramNisarga** [comment]
When we want to select anything other than the first result, it's easier if the results were displayed bottom-up

**Comment by 8bitPit** [comment]
Yes, but in this case you can also type a few letters more to make the result move to the top. In almost all cases you want to launch the first result, so I don't think this is an issue. The main problem of bottom-aligning the search layout is that it is confusing for the user as everything else is top-aligned.

**Comment by VikramNisarga** [comment]
In my opinion it's better if have an option for the user to choose, because I always try to pick the app displayed in the search results after typing a couple of letters instead of typing some more letters to bring it up to the top. But I get your point.

**Comment by 8bitPit** [comment]
I see. We're trying to add as few toggles as possible (here's why https://help.niagaralauncher.app/article/8-niagaras-design-principles). I find it better to offer either a top-aligned or bottom-aligned interface and the top-aligned one is better suited here also because almost all other apps are listing stuff top-aligned.
