### ISSUE TITLE
Agenda: multi-day events not sorted properly

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1504]
If you have several multi-day events listed in your calendar, they can appear in the wrong order:

# Example
- Event A from Monday, 6 PM to Tuesday 6 PM
- Event B from Tuesday, 11 AM to Thursday 11 AM

## Niagara sorts them like this:

**Monday:**
- Event A starting at 6 PM

**Tuesday**
- Event B starting at 11 AM
- Event A ending at 6 PM

## Instead of this:

**Monday:**
- Event A starting at 6 PM

**Tuesday**
- Event A ending at 6 PM
- Event B starting at 11 AM

**Comment by phil-scott-78** [comment]
Add to this the next event doesn't display properly either of it goes past midnight. E.g. The next event is a 6p to 6a event but the 9p one is displayed here

![Screenshot_20210210-161539](https://user-images.githubusercontent.com/2447331/107573419-820eda80-6bbb-11eb-8e21-700ff7bfe0b3.png)

![Screenshot_20210210-161752](https://user-images.githubusercontent.com/2447331/107573469-905cf680-6bbb-11eb-9fd3-b9956b1bf4be.png)

**Comment by 8bitPit** [comment]
Thank you very much for reporting @phil-scott-78 :)

**Comment by jadtaylor** [comment]
Is there a timeline on addressing this bug?

**Comment by 8bitPit** [comment]
Thank you both for your patience, @phil-scott-78 and @jadtaylor. We fixed this in [v.1.9](https://github.com/8bitPit/Niagara-Issues/releases) and will roll out this version on Google Play over the upcoming weeks.

**Comment by phil-scott-78** [comment]
Great, thanks for the heads up. I'll be looking for it
