### ISSUE TITLE
Dual apps are not working in Niagara launcher in MIUI phone

### ISSUE THREAD

**Issue by zhangj3** [8bitPit/Niagara-Issues#1505]
**Describe the bug**

Dual apps are not working in Niagara launcher in MIUI phone

**To Reproduce**
1. Go to 'settings'
2. Click on 'Dual Apps'
3. add Wechat and QQ to dual app
4. See error when click the dual apps

**Smartphone (please complete the following information):**
 - Device: Redmi K20 Pro Premium Edition
 - Android version: Android 10, MIUI 11.0.8 Stable

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.
WeChat and QQ are enabled in the Dual Apps
![image](https://user-images.githubusercontent.com/49198958/107469903-8c25de80-6ba5-11eb-913d-1f5ec3798676.png)

when click the dual QQ and dual wechat, error happens
![image](https://user-images.githubusercontent.com/49198958/107470047-c0999a80-6ba5-11eb-8a7e-0a4b59647dc1.png)

![image](https://user-images.githubusercontent.com/49198958/107470011-b4add880-6ba5-11eb-8a99-76fdab45b679.png)

**Comment by zhangj3** [comment]
Ops....I find this https://help.niagaralauncher.app/search?collectionId=5e885ac42c7d3a7e9aea61cb&query=dual+app

may I ask for a refund?  dual app is very important in my daily work

**Comment by 8bitPit** [comment]
@zhangj3 sure, please send me your order number to niagaralauncher@gmail.com, and I'll take of it.
