### ISSUE TITLE
Persistent 'Set as default launcher' Tip

### ISSUE THREAD

**Issue by r32dubber** [8bitPit/Niagara-Issues#1506]
**Describe the bug**
Upon initial intallation, a series of tips are shown above the favorites list with one such tip allowing you to set Niagara as the default launcher.  Upon clicking 'Sure' and setting it as the default in Android Settings, the tip disappears as expected.

However, my setup uses a different launcher and implements a gesture to launch Niagara which replaces my app drawer.  Using it in this manner means another launcher will be the default and I don't intend to set Niagara as the default.  But if Niagara is not the default launcher, a persistent 'Welcome back! Do you want to set Niagara as default again?' tip is shown atop the favorites list.  The bug is that there is only a 'Sure' option and no other way to dismiss that tip short of clicking 'Sure' and setting it as the default launcher.  There should be a 'No' option or a way to disable those tips in the settings.

**To Reproduce**
1. Install Niagara Launcher
2. Open Niagara
3. Click 'Sure' to the tip asking to set Niagara as the default launcher
4. This will launch the Android Settings app, choose Niagara as the default launcher
5. Upon making a selection you will be returned to the home screen, now Niagara Launcher.
6. Note the 'set as default launcher' tip has disappeared
7. Run a different launcher
8. If prompted to set the non-Niagara launcher as default then do so, otherwise open Android Settings and locate the default apps section and set the non-Niagara launcher as default
9. Run Niagara (either directly from the app drawer or via a gesture)
10. Note the tip now says  'Welcome back! Do you want to set Niagara as default again?' with no other option except 'Sure'.

**Smartphone (please complete the following information):**
 - Pixel 3
 - Android 11

**Screenshots**
![Screenshot_20210212-002403](https://user-images.githubusercontent.com/78945491/107733416-00a56e00-6cc9-11eb-9aab-438d77b4ca3e.png)

**Comment by 8bitPit** [comment]
I hope this article helps: https://help.niagaralauncher.app/article/100-foldable-device-support 😀

**Comment by r32dubber** [comment]
Ah, excellent tip.  I was not aware of the 'secret commands'.  TYVM, I look forward to getting a lot of mileage out of your app and I'm excited to see how it evolves.

**Comment by Amorphous404** [comment]
- Duplicate of #949
