### ISSUE TITLE
Tapping time on home screen opens clock app

### ISSUE THREAD

**Issue by atp800** [8bitPit/Niagara-Issues#1507]
Currently tapping the time/clock on the homescreen opens a list of alarms, but doesn't actually open the clock app, or show the timer or stopwatch
To access these, you still have to find the clock app separately

It should be changed to either also show the timer/stopwatch, open the phone's default clock app, have some other way of easily switching to it

**Comment by 8bitPit** [comment]
Hi, thanks for reporting @atp800 :) I hope the workaround mentioned here helps: https://github.com/8bitPit/Niagara-Issues/issues/295
