### ISSUE TITLE
Customize Which App is opened by Weather Icon

### ISSUE THREAD

**Issue by meagerfindings** [8bitPit/Niagara-Issues#1510]
I would like to be able to launch a weather app of choice when clicking on the weather icon.

Ex: Click to launch stock Pixel weather app from Google or choose another installed weather app.

**Comment by 8bitPit** [comment]
We decided not to include that option; however, you can launch OpenWeather's from the hourly forecast widget. More info here: https://help.niagaralauncher.app/article/105-weather-widget

**Comment by Amorphous404** [comment]
- Merged with #407
