### ISSUE TITLE
I can't put any widgets on the home screen

### ISSUE THREAD

**Issue by jacundinaj** [8bitPit/Niagara-Issues#1511]
Hello, I can't place any widgets on the home screen, an error occurs.  I would like your help please, I will attach screenshots and a video for you to understand the problem.

My device: Xiaomi MI MIX 3 - MIUI 12.0.2.0 (Android 10)
![Screenshot_2021-02-17-16-45-36-311_bitpit launcher](https://user-images.githubusercontent.com/79226751/108265171-30c89300-7147-11eb-8075-cdd10e5f1069.jpg)

https://user-images.githubusercontent.com/79226751/108265578-b9dfca00-7147-11eb-80ef-93e97ae5cb32.mp4

**Comment by 8bitPit** [comment]
Thanks for the update :) Can you please share on which launcher adding the widget worked? Because the bug crashes Xiaomi's settings screen, I fear it might be caused by the OS.

**Comment by 8bitPit** [comment]
If my previous reply didn't help, please let me know.
