### ISSUE TITLE
Brightness and volume slider

### ISSUE THREAD

**Issue by callmeRam** [8bitPit/Niagara-Issues#1514]
It would be efficient if there was a brightness slider below the clock widget and volume slider whenever an app plays music.

Although volume can be increased with physical buttons, having a slider right below the music player helps in many scenarios. 
1. For those users whose volume change buttons no longer works. 
2. When the phone is put on charging
3. It's easy to slide than to click the button seldom times to set the right volume

Same goes for brightness. An average user, changes brightness many times a day. Having it on homescreen will add to user experience and would save some swipes from the finger.

PS - The slider can be themed with the overall theme decided by Niagara launcher making the home screen more pleasing to look.

**Comment by 8bitPit** [comment]
Hi @callmeRam. I fear these sliders wouldn't be impactful enough: https://help.niagaralauncher.app/article/8-niagaras-design-principles. Both volume and brightness sliders are easy to access in Android, and thanks to Adaptive brightness introduced in Android 9, I believe most users won't regularly change the brightness of their screens.

**Comment by callmeRam** [comment]
I agree that brightness slider might not be impactful enough. But volume slider can be useful in some cases. For example:

Let's say a person is not actively using his device and that device is put on charging mode on a stand. (Pixel stand or something to incline the device at an angle where he can see it easily). The said person has put spotify playlist to play on that device while he is working on his other device/laptop.

Now when he needs to change the volume, rather than clicking the button and then silde, it would more easy to just silde the volume slider on the homescreen (which can be put right below naigara's music widget).


Thanks for reading. If you think a feature this will be useful, please do add an option to enable it in niagara settings.

Thanks again. 😁
