### ISSUE TITLE
About Settings page

### ISSUE THREAD

**Issue by callmeRam** [8bitPit/Niagara-Issues#1515]
Back button  (<---) icon on top of any settings page to take back the user from inner setting page to outer page.

Why?
In most cases, any user will go back by back gesture or physical button. But when holding phone using two hands, many a times users tend to click back icon rather than using gesture.

When I myself was trying settings of Niagara launcher, seldom times I went to click the icon to go back to be reminded that there is no such icon. It can become frustrating sometimes if a person is more used to click back icon.

**Comment by 8bitPit** [comment]
Thanks for letting us know, @callmeRam. I believe this happens because some users might not be fully familiar with gesture navigation yet. In my opinion, a back arrow at the top is hard to reach and redundant.
