### ISSUE TITLE
Backup settings

### ISSUE THREAD

**Issue by jew4blackberry** [8bitPit/Niagara-Issues#1516]
Hey. We would love a a way to backup our Niagara settings to the cloud or locally. 

Thanks.!

**Comment by Martin5001** [comment]
It's already automatically backed up to cloud (AFAIK), but it would be great if manual export option was added as well. It would be great for people who share their custom setups with others – there are some community apps where you can share your backup files along with the icon pack links etc. for easy setup.

**Comment by Rod911** [comment]
Thanks for the request, please see #222
