### ISSUE TITLE
Allow changing dark/white text and dark/white theme from tasker

### ISSUE THREAD

**Issue by csumpasd** [8bitPit/Niagara-Issues#1519]
Klwp has a bug where it doesn't properly update the primary wallpaper color, so niagara doesn't update the text color and theme either.

I'd like to request a way to change these options without relying on klwp or niagara settings. Doing this using a tasker integration (assuming it is possible) seems to be the best way to go.

Tell me if I can help with anything.

Thanks, csum

**Comment by Martin5001** [comment]
This could be useful for other integrations too. For example setting the theme based on ambient light sensor.

**Comment by Oddward** [comment]
Apparently Niagara can't detect any live wallpaper's primary colour actually, and it sets a specific colour for each one which might be some hardcoded/default the live wallpaper has set or something

Seems like Tasker integration is likely -
[https://github.com/8bitPit/Niagara-Issues/issues/786](issue 786)

**Comment by csumpasd** [comment]
> Apparently Niagara can't detect any live wallpaper's primary colour actually, and it sets a specific colour for each one which might be some hardcoded/default the live wallpaper has set or something

Klwp does actually export the primary color, and Niagara reads it correctly, the problem I found is that klwp only ever updates the "primary wallpaper color" value when you save the wallpaper in the editor.

I might be missing something, and this is most likely a klwp issue, but providing a workaround in niagara would open up a lot more possibilities in my opinion.

**Comment by 8bitPit** [comment]
@csumpasd thanks for reporting. If we add a Tasker integration, we want to keep it as simple as possible and are most likely using for showing and hiding apps and not for customization features. Otherwise I fear the integration could get bloated pretty quickly and I wouldn't know where to stop.

@Oddward depends. Fortunately, Android 8.1 introduced a way live wallpaper apps can share metadata of the wallpaper like primary, secondary and tertiary color and if it's better to display dark instead of light text (via colorHints): https://developer.android.com/about/versions/oreo/android-8.1#wallpaper

**Comment by csumpasd** [comment]
> @csumpasd thanks for reporting. If we add a Tasker integration, we want to keep it as simple as possible and are most likely using for showing and hiding apps and not for customization features. Otherwise I fear the integration could get bloated pretty quickly and I wouldn't know where to stop.

@8bitPit thanks for responding. If you only let tasker change values that are already changeable in Niagara settings, that could be a clear line where to stop.

I understand all this would be a lot of work to implement. Would you say I'm better off reporting this issue to the folks over at Kustom?

**Comment by 8bitPit** [comment]
> If you only let tasker change values that are already changeable in Niagara settings, that could be a clear line where to stop.

Hmm, we would know when to stop, but creating an API for every toggle/setting would take a considerable amount of time to implement and maintain. I fear, this feature wouldn't be impactful enough to rectify the amount of time it costs.  

> I understand all this would be a lot of work to implement. Would you say I'm better off reporting this issue to the folks over at Kustom?

Yeah, that would be great :)
