### ISSUE TITLE
Media Player (Album Cover)

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1521]
The square album cover of the media player widget is nice, I like the minimal appearance. However, it would be great to give the opportunity to use other shapes like you guys did with the icons. It wouldn't  change that minimal appearance, and it could give a entire new look. So, people could choose the cover of their widget media as the shape of their icons.
Also,It would be great to if you add more different media player widget to choose and not just be forced to one.
Keep the great jop guys, while I keep doing my part by sharing this great app to all of my friends.

**Comment by 8bitPit** [comment]
Hi @Just-SKY, I'm sorry, but we're not planning to add further customization options soon: https://help.niagaralauncher.app/article/44-feature-requests.
