### ISSUE TITLE
displays vanilla launcher after closing apps even if Niagara is set to default launcher

### ISSUE THREAD

**Issue by davidwang20** [8bitPit/Niagara-Issues#1523]
**Describe the bug**
Title

**To Reproduce**
Start at Niagara launcher front page

open an app

click the three lines and swipe up to close and return to homepage 

**Smartphone (please complete the following information):**
Samsung S10e Android 11 One UI version 3

**Screenshots**

https://user-images.githubusercontent.com/25164585/109396062-9bff2b80-78e4-11eb-8d44-2deb2d1d0be0.mp4

**Comment by davidwang20** [comment]
fixed after set to default again and device restart

**Comment by 8bitPit** [comment]
Hi @davidwang20, glad you could work around it. Unfortunately, there's nothing we can do to prevent this issue on Samsung devices: https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default
