### ISSUE TITLE
Search – space is interpreted as special character

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1524]
When I type space into the search bar, app with name containing special character is searched instead.
![Screenshot_20210228-140008_Niagara Launcher](https://user-images.githubusercontent.com/35201200/109419457-d7295980-79cd-11eb-95af-1c61c9839430.jpg)

This happens regardless of Sesame integration being enabled or not.
Niagara 1.0.1
Android 9
Samsung Galaxy J7

**Comment by Nxt3** [comment]
It might be because the app name has a space in it

**Comment by 8bitPit** [comment]
It's because we treat all special characters as the same character, and we count both space and the beta symbol as special characters. Even though search results might look a little odd in this case, I believe it's okay to leave the algorithm as it is.
