### ISSUE TITLE
Fill screen option for custom widget makes widget controls inaccessible due to Alphabet menu overlap

### ISSUE THREAD

**Issue by itsmebg** [8bitPit/Niagara-Issues#1525]
**Describe the bug**
I'm using a custom clock and weather widget instead of Niagara's built-in widget but would like to stretch it across the screen as otherwise some information on my custom widget gets cropped. I have used the option "Fill screen", which displays my widget correctly. However, the widget has two control icons (Refresh and Settings) at the top right, which become inaccessible as the Alphabet menu area overlaps. Please introduce dead areas (left and right) for custom widgets that fill the screen to make widget controls and other tap actions in these areas accessible again. Thank you!!!

**To Reproduce**
1. Replace Niagara clock widget with a custom widget that has control buttons or tap functions either on the far left or right side of the widget.
2. Hold widget down to enable widget related menu and select "Fill screen", then "Enable" on the next window
3. Try and tap on either the left or right side of the widget that has a widget control Button and you'll notice that instead of the widget actions the Niagara Alphabet menu pops up.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android version: Android 10

**Screenshots**
![Screenshot_20210301-070358](https://user-images.githubusercontent.com/79828727/109463232-8f054800-7a5c-11eb-96ef-c99bd21e4daa.jpg)

**Comment by 8bitPit** [comment]
Thanks for reporting @itsmebg. The alphabet takes precedence over the widget to keep your app list easily accessible, disregarding the widget's size and position. If the widget has clickable buttons on its edges, I recommend disabling the "fill screen" mode.
