### ISSUE TITLE
Play Store rating experience enhancement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1526]
In the community section there is the "Rate us" link, which takes the user to the Play Store page outside of Niagara. This is fine, but there's one more option: Since Android 5 you can use [this API](https://developer.android.com/guide/playcore/in-app-review) to show a rating dialog/widget directly in the app.

Advantages:
- seamless
- no need to close Play Store app after giving review
- seems to load faster than the full Play Store app

So I think this would be a nice enhancement.

EDIT: I mean this to complement the current implementation and show this dialog after some time of using Niagara. Not as a replacement of the current Rate us button. Should've made this more clear at the beginning, sorry.

**Comment by 8bitPit** [comment]
Since version v1.1, we're actually using this dialog and rolling it out to more and more users :) The dialog can show up after getting/reading a changelog message from Niagara Launcher.
