### ISSUE TITLE
Transparent screenshots - missing weather icon

### ISSUE THREAD

**Issue by NoeDeMontard** [8bitPit/Niagara-Issues#1527]
**Describe the bug**
With the new transparent screenshot feature, the weather icon is missing from the screenshot.

**To Reproduce**
1. Activate the weather icon
2. take a trasparent screenshot

**Smartphone (please complete the following information):**
 - Device: oneplus 3T (A3003)
 - Android version: Android 9 (Pie) (OxygenOS 9.0.6)
 - App version : 1.1.0

**Screenshots**
Classic screenshot:
![Screenshot_20210306-165207](https://user-images.githubusercontent.com/75419554/110212619-82d61c00-7e9c-11eb-911c-9478e83cd5b9.jpg)
Transparent screenshot:
![Screenshot_210306-164432](https://user-images.githubusercontent.com/75419554/110212627-908ba180-7e9c-11eb-9526-f1410242c1f1.png)

**Comment by 8bitPit** [comment]
Thanks for reporting. This can happen on some devices, unfortunately. Because /screenshot is merely a debug feature, we're not planning to add a workaround for this.

**Comment by NoeDeMontard** [comment]
Thanks for responding. 
I though that even if it was a debugging feature I would report it in case the fix was easy. 
Have a nice day!

**Comment by 8bitPit** [comment]
I appreciate that @NoeDeMontard! Thank you very much, and have a great weekend 😀
