### ISSUE TITLE
Dark mode not always applying

### ISSUE THREAD

**Issue by rastamanjohn** [8bitPit/Niagara-Issues#153]
The shortcuts menu (when u swipe left on an app, and when you long press an app) should be themed also when wallpaper theme is toggled, currently (at least for me) it is themed only when I set the system to dark theme, not the app.

Also it would be nice to have an AMOLED black option, tho I'm sure it was already requested ; )

**Comment by rastamanjohn** [comment]
Actually, just tested some more, the issue is that when system theme is set to light and app is set to wallpaper based, even if the wallpaper is dark (and I know system recognizes it as dark cuz if I put system theme to wallpaper based it all becomes dark) it will stick to light theme (I thought it was dark because of the dark app bar and Google FAB where both dark, haven't tested further).

**Comment by 8bitPit** [comment]
Thx, will test that.

**Comment by 8bitPit** [comment]
Unfortunately I couldn't reproduce it yet. Does it still happen on your device?

**Comment by 8bitPit** [comment]
See https://github.com/8bitPit/Niagara-Issues/issues/485 for further instructions.

**Comment by mendelmaleh** [comment]
@8bitPit nope

**Comment by 8bitPit** [comment]
great :)
