### ISSUE TITLE
Can't add Magnifier shortcut

### ISSUE THREAD

**Issue by marcinsmialek** [8bitPit/Niagara-Issues#1530]
**Describe the bug**
After "adding" Megnifier shortcut, it's not available on app list, and it can't be added to the swipe shortcuts list.

**To Reproduce**
Steps to reproduce the behavior (trying to translate to English, as there's no option in app to change language):
1. Open Niagara Settings
2. Click on 'Functions'
3. Click on 'Add shortcut'
4. Scroll down until Maginifier appears (Lupa in Polish)
5. *Click 'Magnifier' to add it*
6. Open app list
7. *App list doesn't contain Maginifier*
8. Go to home screen
9. Swipe any icon to the right to open shortcuts
10. Magnifier is not on the list

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 Ultra
 - Android version: 11
 - Language: Polish

**Extra info**
Working shortcut intent found by Tasker:
action=android.intent.action.MAIN
category=android.intent.category.LAUNCHER
component=com.sec.android.app.magnifier/.MagnifierWidget

Magnifier doesn't appear on the app list even in the stock Samsung launcher, but its shortcut can be added to the home screen.

**Comment by 8bitPit** [comment]
Thank you very much for reporting. Does the same bug also occur when using another third-party launcher (e.g., Nova Launcher or Microsoft Launcher)?

**Comment by marcinsmialek** [comment]
I haven't tried Microsoft, however it worked flawlessly with Nova Launcher and stock Samsung launcher.
I have the telemetry enabled, so I hope you'll get more data

**Comment by 8bitPit** [comment]
I see; thanks for testing. The shortcut you mention seems to be a Samsung-specific shortcut; I'll do some testing on a Samsung device in a couple of days. Thanks again :)

**Comment by 8bitPit** [comment]
Fixed in v.1.2.0
