### ISSUE TITLE
Weather location text has not enough contrast in dark mode

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1531]
Niagara v 1.1.0
Fixed weather location input text box has dark text on dark background, making it hard to read.
![20210307_171646](https://user-images.githubusercontent.com/35201200/110246794-59cf8d00-7f69-11eb-81a7-5ef6c8831554.jpg)

**Comment by 8bitPit** [comment]
Thanks, Martin! I fixed it in v1.1.1
