### ISSUE TITLE
"Force stop" option in long press menu

### ISSUE THREAD

**Issue by wimstefan** [8bitPit/Niagara-Issues#1532]
**Is your feature request related to a problem? Please describe.**
No problem - just an idea.

**Describe the solution you'd like**
When long-pressing an icon a menu pops up with a couple of options ... I'd like to have the possibility to force-stop an app in this menu. Many times I want an app freezes or I want to stop it and I have to go via the info button in the right top of the menu to be able to force-stop it. 

I hope there is a solution not complicated ... ;-)

**Comment by 8bitPit** [comment]
Hi Stefan, I believe a force-stop button is not impactful enough, I fear it wouldn't be used by many: https://help.niagaralauncher.app/article/8-niagaras-design-principles

**Comment by wimstefan** [comment]
Hello Peter,

I'm sure if nobody else is reacting on this issue it's just an individual hiccup 😉

Only if more people think it's a useful feature it's worth thinking about implementing it - always taking into consideration it's not too much of an hassle for you guys.

Thanks for your tremendous work 🙏🏼

**Comment by 8bitPit** [comment]
Thank you very much for your kind word and understanding :)

**Comment by luciodaou** [comment]
Definitely not an individual hassle. I miss it a lot. I know I'm a power user and Niagara is focused on simplicity, but that would be very useful, even if was an advanced setting.
