### ISSUE TITLE
12-hour time locale in chinese

### ISSUE THREAD

**Issue by kkren** [8bitPit/Niagara-Issues#1533]
**Describe the bug**
The position of am/pm in the agenda is incorrect in the Chinese locale. For example, the time of 10:00 am is displayed as "10:00 上午". However, a more standard way of displaying am/pm in Chinese is "上午 10:00".

**To Reproduce**
1. open agenda widget

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - Android version: Android 11, simplified Chinese locale

**Comment by 8bitPit** [comment]
Thanks for reporting, here's how it looks on my device (Pixel 5). I don't know what the characters mean, unfortunately, but it looks to mee that "上午" is placed properly at the beginning:
![image](https://user-images.githubusercontent.com/9284845/112645934-4bc5ab80-8e47-11eb-8fbe-6a0b3d91a3ed.png)

**Comment by kkren** [comment]
Hi, the time locale in the weather widget is correct, but it is incorrect in the agenda.
![图片](https://user-images.githubusercontent.com/23287823/112712810-a07f2a00-8f0c-11eb-80cd-1a0564e8679e.png)

**Comment by 8bitPit** [comment]
This should be fixed with v.1.4
