### ISSUE TITLE
Small circular battery icon next to XX%

### ISSUE THREAD

**Issue by dep-dt** [8bitPit/Niagara-Issues#1536]
**Is your feature request related to a problem? Please describe.**
It's sometimes difficult at a glance to see the battery percentage because it just appears inline with the rest of the text. 

**Describe the solution you'd like**
A small, dynamic circular battery icon showing how much battery is left in addition to the percentage that's there currently. An example is Android's circular shaped battery gauge. 

"Thu, March 11, 2021 🔋75% ⛅ 64°"

Thanks for the great app!

Android battery icon for reference. 

![Screenshot_20210311-081236.jpg](https://user-images.githubusercontent.com/55112925/110792664-abb23480-8241-11eb-9650-e3aac376eed0.jpg)

**Comment by 8bitPit** [comment]
Hi Danny, thank you very much for your kind words. I fear if we add that, a lot of users would find the battery percentage ring redundant and request a toggle to turn it off. I believe the feature wouldn't be impactful for having a toggle. More about Niagara's design principles here: https://help.niagaralauncher.app/article/44-feature-requests

**Comment by dep-dt** [comment]
Thanks for your consideration @8bitPit !
