### ISSUE TITLE
Weather: Clarify "current location" option updates location automatically

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1537]
When you go to set manual location for weather forecast instead of automatic, a popup shows, asking me if I really want to do that. This requires one extra tap to dismiss that popup. I think it would be better to display this info on the same dialog where the user enters the fixed location. Just as information text, without interrupting the user.

**Comment by 8bitPit** [comment]
It's not just a confirmation, though. There are three methods NL to enter the location:
- Current location: Uses location services and updates location periodically
- Fixed location - Automatic: Uses location services once
- Fixed location - Enter manually: Let's you enter the location.

**Comment by Martin5001** [comment]
I see, I didn't know that. Maybe this needs a bit more explanation then?

**Comment by 8bitPit** [comment]
@Martin5001 good idea 🙂

**Comment by Martin5001** [comment]
I think one option could be to change the fixed location selection dialog this way: remove the description text and show current location city name as button label instead of the "Okay" text.
So you would have the structure like this: "Fixed location" (title of the dialog), "Berlin" (primary button), "Set different location" (secondary button)

**Comment by 8bitPit** [comment]
@Martin5001 the location could need several seconds to load, though, and the user most likely hasn't granted the location permission yet to detect it automatically.

**Comment by Martin5001** [comment]
Oh, that's true.
Or maybe when there's the textbox in which user types the location, there could be a button next to it with that "find location" icon.
![20210327_135449](https://user-images.githubusercontent.com/35201200/112721443-0ca96000-8f04-11eb-807f-b3765e2759b6.jpg)
So the fixed location option would get the user straight to the textbox, which would now have this location button added. (Similar to what some map/weather apps do, so users would probably be used to that and understand it easily.)

**Comment by 8bitPit** [comment]
Added in v.1.5
