### ISSUE TITLE
UI bug – Weather location selection dialog stuck on screen

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1538]
Weather location selection dialog is stuck on the screen and can't be closed by tapping away. Even pressing back or home button doesn't work (the system was otherwise completely responsive though – could open apps and go back to home, but the dialog was still there). Eventually I was able to close it by swiping it down.

![Screenshot_20210311-203230_Niagara Launcher](https://user-images.githubusercontent.com/35201200/110844337-9670f080-82a9-11eb-8dcb-9168dd079967.jpg)

The dialog itself is sort of responsive – I can change the selection, but when I select Fixed location, it doesn't continue to the next popup where it would then be set.
When I press Home button, it opens the Niagara search, but the dialog is still overlapping the screen.

![Screenshot_20210311-203704_Niagara Launcher](https://user-images.githubusercontent.com/35201200/110844397-a8eb2a00-82a9-11eb-9ae1-cb9efb8185cb.jpg)

Then I went back to home screen and tried closing the location selection dialog by swiping it down. It closed and revealed the next popup with the Automatic location loading animation, which was like stuck under it, so I then closed that dialog as well and everything was back to normal.

This bug occurred after I accidentally tapped one of the two location options (don't remember which one it was) twice rapidly – basically double tapped it – or maybe I tapped both of them simultaneously, I don't know for sure, I just accidentally touched the screen as my phone slipped a bit. I tried to reproduce it but unsuccessfully.

I'm using Niagara 1.1.1 on Samsung Galaxy J7 running Android 9

**Comment by timm0e** [comment]
Hey :wave: 

Does this still happen to you in the latest version of Niagara Launcher? (1.6.5)
