### ISSUE TITLE
In app search, allow a suggestion to be sent up to the search field for further editing

### ISSUE THREAD

**Issue by dgsullivan** [8bitPit/Niagara-Issues#1540]
When using app search, I often wish that I could refine/edit one of the items in the list of suggested completions.

I would appreciate it if you could add this feature, which both the Google Search app and Sesame provide. In those apps, each item in the list of suggested completions includes an arrow next to it that can be used to send the item up to the search field for further editing. Thank you!

**Comment by luxcalor** [comment]
Would be very useful
