### ISSUE TITLE
Weather not working

### ISSUE THREAD

**Issue by nonyonah** [8bitPit/Niagara-Issues#1542]
I've tried clearing cache, fresh install and even disabled and enabled the widget but no avail. It sees my location alright but it can't show me the weather in my location

**Comment by Just-SKY** [comment]
Does the weather icon appear on your screen? Or just the date and battery porcentage?

**Comment by nonyonah** [comment]
Just the date and battery, no weather

**Comment by Just-SKY** [comment]
Probably, it could help you.
Well, what I found is that when you enter your location manually, you must follow certain order. Like, your town, city, and country. I found is that if you skip the main city by just writting your town and country, or changing the order randomly the weather widget disappear. Then, you could enter your location again and the right location could appears in your widget; however the weather is still missing no the main screen.
You can uninstall niagara launcher, clear cache, clear all data, and it wont appear.
The solution, I found was to clear **the cache** of the '' android system, system UI, system launcher; and the weather is back.

**Comment by jbwaagmeester** [comment]
I have the same issue. The solutions you provide also do not seem to work for me. For some reason, the icon does not show up.

**Comment by nonyonah** [comment]
Yeah the solution you gave doesn't work. I feel that Niagara launcher should include an option where it lets us use our own API key from openweather

**Comment by Just-SKY** [comment]
Sorry to hear that, it worked for me. To be honest, I'm very disappointed with this weather provider. The information on the widget do not match the icons. I think, I am gonna create a ticket about it.

**Comment by 8bitPit** [comment]
Hey @nonyonah, can you please send me your purchase order number via mail (support@niagaralauncher.com) to further debug the issue? Here's how to get it: https://help.niagaralauncher.app/article/18-looking-up-order-number
