### ISSUE TITLE
Huge number glitch 

### ISSUE THREAD

**Issue by Milteus** [8bitPit/Niagara-Issues#1543]
So, what happens is, the launcher looks fine before I go to bed, I know it sounds weird but overnight (while it's not in even charging), that number pops up when I unlock the phone. I tried restarting the phone, it didn't work, I tried restarting the launcher, it didn't work either. What did work was do uninstall and install again, but it's tiring to do these every 2 days. If I tap or hold on them, nothing happens, and they fill in a huge portion of my home screen. 

Huawei Mate 20 lite
 Smartphone 
Android 10

![Screenshot_20210316_043840_bitpit launcher](https://user-images.githubusercontent.com/80804020/111412801-c96e1680-86e5-11eb-9a12-365d87a57fde.jpg)

**Comment by asavill** [comment]
Pretty sure this happens when you use a cracked version of Niagara 😬 .

https://help.niagaralauncher.app/article/108-random-numbers

**Comment by 8bitPit** [comment]
Yes, @asavill is right. Please consider buying Niagara Pro or keep enjoying the free version @Milteus.
