### ISSUE TITLE
Haptic feedback for alphabet slide

### ISSUE THREAD

**Issue by cipherster** [8bitPit/Niagara-Issues#1544]
I believe it is a feature that improves the user experience.

Could you add haptic feedback to the alphabet while we slide in apps list. Like when it hit a letter in list, a gentle haptic feedback gives little depth to the app list. 

Thank you!

**Comment by 8bitPit** [comment]
Hi @cipherster 👋 I'm sorry, but we decided to not include haptic feedback for the alphabet: https://help.niagaralauncher.app/article/99-vibration-for-alphabet-scrolling
