### ISSUE TITLE
Tapping home from an app should not redirect to the search results

### ISSUE THREAD

**Issue by pomdtr** [8bitPit/Niagara-Issues#1549]
**Is your feature request related to a problem? Please describe.**
I never want to go back to the search results when tapping the home button.

**Describe the solution you'd like**
Going back to home from an app should go back to the favorite list.

**Comment by pomdtr** [comment]
Ok there seems to be a delay, this is a nice touch. I'll close the issue :)

**Comment by 8bitPit** [comment]
Thanks @pomdtr :)
