### ISSUE TITLE
Feature request: Horizontal alphabet row

### ISSUE THREAD

**Issue by praveen2203** [8bitPit/Niagara-Issues#155]
Horizontal row at bottom could be a fun way to navigate.

**Comment by rastamanjohn** [comment]
I wouldn't consider it ergonomic or comfortable, as the launcher is meant for portrait use.

**Comment by 8bitPit** [comment]
It wouldn't fit the overall design, sry

**Comment by praveen2203** [comment]
Thank you for considering!
