### ISSUE TITLE
Cannot view hidden apps, or create a new gesture

### ISSUE THREAD

**Issue by CrimsonRuby11** [8bitPit/Niagara-Issues#1552]
**Description**
Whenever i try to view the hidden apps or press on add shortcut in niagara settings, it redirects me to the home

**Steps to reproduce the behavior:**
1. Go to 'Niagara Settings'
2. Click on 'Features'
3. Click on 'Hidden apps' or 'Add shortcut'

**Smartphone:**
 - Device: Motorola Moto C Plus
 - Android version: Android 7

**Screenshots**

**Comment by 8bitPit** [comment]
Thank you very much for letting us know @CrimsonRuby11 :)

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)
