### ISSUE TITLE
Moto G7 Gestures 

### ISSUE THREAD

**Issue by Sakurauwu** [8bitPit/Niagara-Issues#1553]
Hello, I recently got a new phone, the Moto G7 Supra. It has a system navigation similar to iphones, but I have noticed one of the gestures does not work, as it is blocked by the launcher. 
This gesture is used to open all the recently used apps, but with the launcher running, it only goes straight to the home page. 

I was hoping it would be possible for a patch, if Gestures and Niagara launcher are compatible to do that. As far as I have noticed, this is the only problem between Gestures and Niagara.

**Comment by 8bitPit** [comment]
Hey, @Sakurauwu 👋 Gesture navigation has to be supported by Android/submodule of your preinstalled launcher; more about that here: https://help.niagaralauncher.app/article/7-gesture-navigation. Unfortunately, there's nothing third-party launchers could do about the issue.
