### ISSUE TITLE
APP opening issues

### ISSUE THREAD

**Issue by TriunnMaegin** [8bitPit/Niagara-Issues#1555]
Two days ago after clicking to open apps, they wouldnact like they load but never come up. They show as open in the background but upon opening or trying to re-elect them from the screen that shows active apps they would just "minimize again". It was causing issues on Google but that it's working again but now having issues with opening Email, An stock option Calculator app, and others. I haven't tried turning of Niagra to see if it is the issue but I don't see what else the issue could be. I have tried restarting my phone and powering it down for 20 minutes.

Android Galaxy S21+

**Comment by 8bitPit** [comment]
Thank you very much for reporting. Does the same bug also occur when using another third-party launcher (e.g., Nova Launcher or Microsoft Launcher)?

**Comment by TriunnMaegin** [comment]
I e never used another launcher. I noticed a glitchy flicker the other day regarding the Niagra launcher (been using it for quite awhile now.) Then the 9ther day apps would launch and minimize to the background and not stay open but would go to the "scroll screen" for app selection.The issue seems to have resolved itself today but it lasted about 4 or 5 daysSent from my Galaxy
-------- Original message --------From: Peter Huber ***@***.***> Date: 3/24/21  11:01  (GMT-06:00) To: 8bitPit/Niagara-Issues ***@***.***> Cc: TriunnMaegin ***@***.***>, Author ***@***.***> Subject: Re: [8bitPit/Niagara-Issues] APP opening issues (#1555) 
Thank you very much for reporting. Does the same bug also occur when using another third-party launcher (e.g., Nova Launcher or Microsoft Launcher)?

**Comment by 8bitPit** [comment]
Thanks for the additional info. Unfortunately, we can't do anything about that as the OS is responsible for launching apps and a submodule of the preinstalled launcher takes care of Android's recents screen.
