### ISSUE TITLE
Colour of popups when swiping

### ISSUE THREAD

**Issue by bastschonet** [8bitPit/Niagara-Issues#1556]
Hi, 
if using a black wallpaper (minimalism, non distracting, batterysaving, simple) and open the app popup by **swiping** over the icon, the popup is hardly distinguishable from the background. Depending on the ambient light it's sometime completely not distinguishable.
Please find screenshot (first picture) attached.

**Describe the solution you'd like**
Same behaviour as when **long-press** the app icon. Please see other screenshot (second picture)
Then the background fades / greys out a bit and the popup gets more focus.
Also, that woud be more consistent. Same visual occurance no matter if long press or swipe.

I'm pretty sure, this would cover the principles of NL...
![swipe_not-prefered](https://user-images.githubusercontent.com/81433775/112665122-014e2a00-8e5b-11eb-864a-3e02434de836.jpg)
![long-tap_prefered](https://user-images.githubusercontent.com/81433775/112665107-fdbaa300-8e5a-11eb-8c48-0f3812eafc4c.jpg)

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Hi @bastschonet, thanks for your ticket. I'm sorry, but we're not planning to make the background color customizable (more about missing customization features here: https://help.niagaralauncher.app/article/44-feature-requests). In your case, I recommend switching to light mode: Niagara settings > Dark theme > Always disabled.

**Comment by bastschonet** [comment]
Hallo Peter,
danke für Deine Antwort. Ich respektiere die konsequente Haltung und finde
dies auch gut. Das bewahrt Euer Produkt davor sich zu verzetteln.

M.E. wäre es vom Design durchgängig, wenn der Hintergund bei Swipe-Aktion
gedimmt wird so wie es auch beim Öffnen der Pop-Ups für Einstellungen
(langes Drücken ) geschieht. Warum ist das unterschiedlich?

Was Deinen Vorschlag wg. light-mode angeht: Ich finde ein komplett
schwarzen Hintergrund und dunkle Pop-Ups absolut passend zu Euren
Prinzipien = DarkMode. Einfach, ablenkungsfrei und minimalistisch.  Man
überlegt nicht ständig, welchen Hintergrund oder welche Farbe als nächstes
verwendet werden kann. Zudem kann dies bei OLEDs die Laufzeit je nach
Nutzung spürbar erhöhen.

Danke, dass Du Dir die Zeit nimmst.

Grüße, Jens
