### ISSUE TITLE
show notifications of apps within the pop-up

### ISSUE THREAD

**Issue by bastschonet** [8bitPit/Niagara-Issues#1557]
Hi,

I suggest that **notifications** of apps within the pop-up (folder) get **passed through to the homescreen**.

So the homescreen could be much more **simpler and cleaner**.

E.g. one messaging app on the homescreen and others within it's pop-up. Thus, never miss a notification...

Nova provides this as shown on the attached screenshot. Here GoogleKeep is located in the folder of RememberTheMilk (2nd icon from left). GoogleKeep has a notification which I could see at a glance from the homescreen.

![RTM-210326_180241](https://user-images.githubusercontent.com/81433775/112667521-a10cb780-8e5d-11eb-8a34-77bb17cc84c8.jpg)

**Comment by 8bitPit** [comment]
Thank you for requesting, @bastschonet. We're planning to add this: https://github.com/8bitPit/Niagara-Issues/issues/1201
