### ISSUE TITLE
Split second blink when returning to home screen and tapping anywhere

### ISSUE THREAD

**Issue by brnlee** [8bitPit/Niagara-Issues#1558]
**Describe the bug**
I am encountering a bug where when I go back to the home screen from another app and tap anywhere, the screen blinks for like a frame or so. This bug only occurs when I have side swipe gesture navigation on. 

This is purely a visual bug but it annoys me enough so that I switch back to bottom-only swipe gestures. I've checked if this behavior occurs with the default OneUI launcher and can confirm that it doesn't occur for me. This bug also does not occur if I  switch between apps through the recent apps menu.

I really want to be able to use the side+bottom navigation gestures but I will hold off until this bug is resolved.

**Screen Recording**

https://user-images.githubusercontent.com/16778474/112736028-f7452d80-8f25-11eb-84ef-4301020c10e4.mp4

**To Reproduce**
1. Have side swipe navigation enabled
2. Go to any app
2. Swipe up to return to home screen
3. Immediately tap anywhere on the home screen
4. See the blink

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - Android version: 11
 - One UI version: 3.1

**Comment by abonhote** [comment]
Having spent some time with the s21 ultra, I am quite sure this is a Samsung issue. It happens with Niagara and with Smart launcher, not specific to Niagara. Still, it should be addressed.

**Comment by 8bitPit** [comment]
Yes, @abonhote is right. We don't have control over it, unfortunately, we have to wait for Samsung (or Google, because the bug is also present in AOSP) to fix it.
