### ISSUE TITLE
Ability to double / tripple tap <app.icon> on favorite top list. Trigger 2nd and 3d possible app launch. 

### ISSUE THREAD

**Issue by GintokiHub** [8bitPit/Niagara-Issues#1559]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a bug or problem. 
However if we look at it in a problem - solution kind of way.
I would love the ability to double tap or perhaps even a triple tap option for app icons. 
Filling for the function of making it easier to get to the app you want without spending as much time doing so.
 [...]

**Describe the solution you'd like**
I think this system would work well. 
Long press app icon. [perhaps just in the favorites area] and then get a menu where one would be able to chose from another app,
app action or perhaps even widget, same as for the third tap, - different function.
An example say I use protonmail. This is my main e-mail app however I also use k9mail. This is for my secondary e-mail accounts.
If in favorites this would solve clogging of many apps, it would cut down on space needed for your favorites.  
The third tap in this example could: 1: - be the openpgp app for managing my private public keys I might use  in conjunction with my k9mail. OR perhaps an popupwidget which triggerts some kind of view of a widget supported by one of the former apps mentioned.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Thanks for your request. The problem with double or triple tap gestures is that they slow down the single tap gesture. That's because the app has to wait if the user does another tap after registering one. To quickly open related apps, we recommend to take us of the newly released pop-ups :D https://medium.com/niagara-launcher/pop-up-date-4a5d3522df2d
