### ISSUE TITLE
Disable letter wave for Left hand scroll 

### ISSUE THREAD

**Issue by linusljungblom** [8bitPit/Niagara-Issues#1560]
When scrolling with my left hand thumb the alphabet letters expand as there would be a right hand thumb scrolling. This does not look that good 

**Solution**
and would be better if the scrolling wave would be disabled and just present the letter that you are on together with a static Alphabet.

**Comment by peat80** [comment]
Indeed some sort of left-hand-mode would be nice.
So that the alphabet strip shows on left side then or something. 🤔

**Comment by 8bitPit** [comment]
Thanks for your suggestion @linusljungblom :) In my opinion, the wave effect belongs to Niagara Launchers' fluid visual identity. For me, it would look weird if the alphabet scrolls without animation with the left-hand mode while. @peat80, unfortunately, the scroll handle would overlap with the app names if we moved the alphabet to the left: https://help.niagaralauncher.app/article/39-left-hand-mode

**Comment by peat80** [comment]
Things could work in left-hand-mode, but the app names then would have to be textually right aligned. But that could look strange eventually. 🤔 🤷🏻‍♂️ 🤪

**Comment by Oddward** [comment]
> Things could work in left-hand-mode, but the app names then would have to be textually right aligned. But that could look strange eventually. 🤔 🤷🏻‍♂️ 🤪

It would be asymmetrical then

Niagara is designed to be used by either hand one-handed, the main screen isn't strictly a right handed design per se, but because English is a left-to-right language it looks more visually balanced to have the alphabet on the right. Also remember the full width of list items is used for notification previews. 

I imagine a left hand mode would probably be focused on making other actions easier for left handed use (like the buttons in pop-ups, or swipe gestures maybe) 🤔

The wave animation for the left side looks like the letter you're on is magnetically attracted to your thumb, I thought that was good visual feedback lol

**Comment by peat80** [comment]
Indeed, that would look horrible and would destroy niagaras beauty. The wave animation is looking great as it is. 😀

Stupid me also just yet discovered that one can browse through apps by swiping left and right. I always swiped from the right side so the thumb is on the way to see where you are. 🤔
By swiping from the left it works great. So there is actually no need for a left hand mode. One just has to know that you can swipe on both sides. 🤔 🤷🏻‍♂️ 😂

Anyways, keep up the good work. Niagara is awesome & gets even better after each update it seems. 😎👌

**Comment by Oddward** [comment]
@peat80 when Niagara is first installed it shows a tip at the top that mentions the left side scrolling along with a few other features lol

And strange that your thumb covers stuff on the right; the wave animation works both ways, to move the letters into view as you place your thumb on the alphabet on the right, and to make it more obvious where you are on the left. Good that the left works for u

**Comment by peat80** [comment]
> @peat80 when Niagara is first installed it shows a tip at the top that mentions the left side scrolling along with a few other features lol
> 
> And strange that your thumb covers stuff on the right; the wave animation works both ways, to move the letters into view as you place your thumb on the alphabet on the right, and to make it more obvious where you are on the left. Good that the left works for u

If you scroll on the right with your left thumb the thumb is logically all over the screen. 🤔

I also should read tips more carefully then. 🤔 😀

Also after using niagara for quite some time now i realised i do not use the app menu that often anymore. Most of the tiime i use the swipe to search function to reach apps.
And also i realised that i probably could never change launchers again. This thing is simply awesome. 🤭👌
