### ISSUE TITLE
Manual icon selection – show full name on longpress

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1561]
When I want to select an icon manually from the list, often there are icons with longer names which don't fit. It would be useful to be able to see their full name on long press. (For example in a bubble, such some apps do for navigation elements – they display their title on long press, or what Windows or Mac does on mouse hover.)

**Comment by 8bitPit** [comment]
Good idea!

**Comment by 8bitPit** [comment]
Implemented in v1.3 (or earlier; I don't know anymore 😅)
