### ISSUE TITLE
Icons all pulse non stop

### ISSUE THREAD

**Issue by hobhobuk** [8bitPit/Niagara-Issues#1562]
Unsure why.. tried restarting etc. 
Been like this for about 24 hours.

Unsure why. 

https://user-images.githubusercontent.com/41590371/113408348-1bca5b00-93a7-11eb-867e-7bb92812b1ba.mp4

**Comment by 8bitPit** [comment]
Thanks for reporting @hobhobuk. Does a device restart help?

**Comment by hobhobuk** [comment]
Hey

Have restarted phone and it seems fine now :)

**Comment by Maxr1998** [comment]
Perfect, please let us know if it happens again.
