### ISSUE TITLE
Widget settings popup icons are not loaded immediately

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1563]
This is not really a big issue, just a minor UI enhancement: when I long press on the Niagara widget and the settings popup shows, it takes a little moment before the icons are loaded. (As opposed to the Agenda popup, where all icons are already in place when the popup shows.)

![Screenshot_20210402-173108_Niagara Launcher](https://user-images.githubusercontent.com/35201200/113429730-4cc38380-93d9-11eb-95d6-3b6b599596b9.jpg)

![Screenshot_20210402-173121_Niagara Launcher](https://user-images.githubusercontent.com/35201200/113429747-55b45500-93d9-11eb-9447-469368a60db2.jpg)

Niagara: 1.1.3
Android: 9.0
Device: Samsung Galaxy J7

**Comment by 8bitPit** [comment]
This was a performance optimization. Usually, the icons would load while animating in, but this animation overlap can cause stutters (see: https://programmer.group/hardware-layer-for-android-optimization.html). However, with v1.4, most images will already be loaded before the sheet animates in.

**Comment by 8bitPit** [comment]
Fixed in v.1.4
