### ISSUE TITLE
Weird numbers filling screen when overcharged.

### ISSUE THREAD

**Issue by lI-Hamza-Arshad-Il** [8bitPit/Niagara-Issues#1567]
**App version: 1.1.3**

I dozed off while my phone was still charging last night, and woke up 8 hours later to find my home screen filled with gibrish numbers. Phone normally takes an hour to fully charge. Model **LG-G6.**

I've restarted phone, launcher, changed to default launcher and switched back, removed all widgets and so on but the issue remains. Those numbers appear below charging widget and kind of in place of first favorite pushing it down the screen. Interacting with it by tapping/double tapping highlights it but no options appear. Move Widgets options seems to consider it as my first favorite but it doesn't appear as one in the Edit Favorite section.

**Here are the screen shots:**
<a href="url"><img src="https://user-images.githubusercontent.com/82019818/113672276-f1dba600-96d0-11eb-86a0-660660718a23.jpeg" width="250"></a>
<a href="url"><img src="https://user-images.githubusercontent.com/82019818/113672294-f7d18700-96d0-11eb-84ff-8c5389dfb912.jpeg" width="250" ></a>

Clearing cache did not resolve the issue so i had to clear all the data and now it's working fine (had to reconfigure my settings.)

_It's my first time using Github so excuse any weird formatting please._

**edited images size

**Comment by Rod911** [comment]
Please see this article https://help.niagaralauncher.app/article/108-random-numbers

**Comment by lI-Hamza-Arshad-Il** [comment]
Got it. Thanks.
