### ISSUE TITLE
Wallpaper out of focus

### ISSUE THREAD

**Issue by gomltet** [8bitPit/Niagara-Issues#1568]
**Describe the bug**
At apply a theme from google themes, the wallpaper is out of focus, cropped and shifted. Why its niagara, when i apply the same in native lancher appears perfect
**To Reproduce**
1. Choose any theme from google themes on your phone or with web application
2. Apply theme and go to main page

**Smartphone (please complete the following information):**
 - Device: samsung m31
 - Android version: android 11 

>  @ui3.0

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.
![Screenshot_20210406-124809_Niagara Launcher](https://user-images.githubusercontent.com/82050500/113749121-43872f00-96d7-11eb-8b19-c405767e0829.jpg)
![Screenshot_20210406-124838_Galaxy Themes](https://user-images.githubusercontent.com/82050500/113749145-4d109700-96d7-11eb-8b71-60a4ef7190fe.jpg)

**Comment by 8bitPit** [comment]
Hi @gomltet, here's why the bug happens and how to work around it: https://help.niagaralauncher.app/article/36-wallpaper-bugs. Please let me know if you still have any questions :)
