### ISSUE TITLE
Alphabetic list trigger side switch

### ISSUE THREAD

**Issue by TheodoreDiketer** [8bitPit/Niagara-Issues#1569]
**Description of the problem**
I'm right handed and it's much easier for me, and I imagine for other right handed people, to scroll through my favourite apps on the right side than in the middle section of the screen. However, since the trigger area for the alphabetic list is on the rightmost side or leftmost side I accidentally trigger it much more than I would want. I imagine the same happens for left handed people but the opposite (can accidentally trigger the alphabetic list while scrolling on the left side of the screen)

**Solution I would like to be added**
A simple toggle in the settings that either lets the user use the rightmost/leftmost/both sides to trigger the alphabetic list.

**Conclusion**
I think this feature would really be impactful in the usage of every user or at least most of the users, add no complexity whatsoever to the code/interface and, I imagine, simple to implement too.

Thank you!! :)

**Comment by 8bitPit** [comment]
Hi Theodore 👋 I'm sorry, but we don't plan to add this option, see: https://github.com/8bitPit/Niagara-Issues/issues/865

**Comment by Silv14** [comment]
Dang.  I'd like this too
