### ISSUE TITLE
Dismiss music/media notification

### ISSUE THREAD

**Issue by rastamanjohn** [8bitPit/Niagara-Issues#157]
It would be nice if it would be possible to swipe away music notification, like in notifications (when paused).

**Comment by 8bitPit** [comment]
Sure!

**Comment by 8bitPit** [comment]
I just implemented it, will be available with the next Update.

**Comment by Montell2099** [comment]
A little off-topic, but how often does updates get released for this launcher?

**Comment by 8bitPit** [comment]
Currently once every two to three days.

**Comment by rastamanjohn** [comment]
Wow that was fast! Thanks @8bitpit!
