### ISSUE TITLE
Fullscreen sometimes leaves gesture bar visible with dead zone

### ISSUE THREAD

**Issue by renolc** [8bitPit/Niagara-Issues#1571]
**Describe the bug**
Apps that go into fullscreen will sometimes leave the gesture bar visible. It will sometimes be on the side, other times on the bottom. In either case, whichever side it is on, the fullscreen app won't receive inputs within a finger width of the bar.

**To Reproduce**
1. Open app that is fullscreen (I've noticed on Slay the Spire, YouTube when fullscreening a video, and Play Books when opening a book to read)
2. The gesture bar will sometimes be visible on the side of the screen (the physical bottom) or on the bottom of the screen (the side faced down while rotated) when it should be hidden
3. On the side with the visible bar, interactions near the edge of the screen aren't interpreted by the fullscreen app. In the case of Slay the Spire, buttons on that side aren't interactive
4. In some cases when the bar is hidden as expected, if you swipe back home then bring the app back into the foreground the bar will then be visible, or if already visible on the side it will move to the bottom

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 11

**Screenshots**
See the gesture bar on the right side
![Screenshot_20210410-145506](https://user-images.githubusercontent.com/4680221/114282802-2b374d00-9a14-11eb-9c84-d80950ccd297.png)

See the gesture bar on the bottom
![Screenshot_20210410-145514](https://user-images.githubusercontent.com/4680221/114282818-3ee2b380-9a14-11eb-97f5-ab6803c304de.png)

**Comment by renolc** [comment]
Here's another example I just ran into while opening a book on Play Books. Notice the bar on the bottom of the screen which should be hidden. It's presence interferes with tapping on the progress indicator at the bottom which can normally be done to toggle different display options.

![Screenshot_20210410-212422](https://user-images.githubusercontent.com/4680221/114289130-787ee300-9a43-11eb-82ab-4426324119bf.png)

**Comment by Just-SKY** [comment]
It seems to be more a system issue that a Niagara problem.

**Comment by renolc** [comment]
This does not happen in the default Pixel Launcher. Only when I change to Niagara.

**Comment by Codelefant** [comment]
I have the same issue on a Pixel 3 with Android 11. Going back to the home screen and reopening the app usually fixes the bar, but does not prevent future issues.

**Comment by 8bitPit** [comment]
Thank you very much for your reporting. I also fear that this is a system issue that occurs with third-party launchers: https://help.niagaralauncher.app/article/114-recent-apps-screen-issues. To check that, could you please try to reproduce the same bug on another third-party launcher (e.g., Nova Launcher or Microsoft Launcher)?

**Comment by renolc** [comment]
Yes, it appears the same issue occurs on Microsoft Launcher. Unfortunately I believe this makes Niagara unfixable, at the moment. Guess I'll go back to stock for now until google fixes this issue.

**Comment by 8bitPit** [comment]
Bummer, but thank you very much for sharing :)
