### ISSUE TITLE
Calendar - current day - shortcut to google[system] calendar app

### ISSUE THREAD

**Issue by terezo** [8bitPit/Niagara-Issues#1573]
Hello,

Was using niagara calendar widget for a while but realised I almost always need to open google calendar anyway. I am used to create, view, open and edit events in google calendar and the widget is another interface for the same purpose for me. 

**Would love to see feature of opening default/google calendar after tapping on date.** It could be in Settings - niagara widget - Calendar.

Appreciate your effort and believe there are many users who like the calendar widget, but for me it is not that case.

Thanks

**Comment by Oddward** [comment]
The agenda currently opens your default calendar app when tapping an event or adding one 🤔 What exactly is the request?

**Comment by terezo** [comment]
I meant opening calendar app after tapping on date on home screen (not calendar widget). Current date - one below current time.

**Comment by Oddward** [comment]
I don't think this is very impactful. Seems like you want the Niagara widget to function as a shortcut to the Google calendar app, which is already in the app list and can be added to favourites. 

And as far as I understand all the actions mentioned can be done via the agenda which will open the default calendar app to perform the actions (e.g. if your default is Google calendar, then the add event button launches Google calendar's add event activity page) 🤔

**Comment by terezo** [comment]
Hi, yes I wanted it as a shortcut to the calendar. It used to function like that already before, widget was introduced, If I remember it correctly.

But al this converstaions makes me think and give another chance to the widget and I found it sufficient and I finally got used to it. So there is no need on my side anymore :D Thanks for that :)

You can close this issue :)

**Comment by 8bitPit** [comment]
Glad that you're now content with the new widget @terezo :) If you change your mind in the future, you can also switch back to the old behaviour and open the calendar app directly with the help of a secret command. You can find it in this FAQ > I want to open my calendar app directly when tapping on the date: https://help.niagaralauncher.app/article/76-calendar-faq
