### ISSUE TITLE
主页面出现乱码

### ISSUE THREAD

**Issue by polaris9527** [8bitPit/Niagara-Issues#1574]
![Screenshot_20210418_122103](https://user-images.githubusercontent.com/82744628/115134331-d44bfc00-a041-11eb-8580-efb65a365c33.jpg)
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by Maxr1998** [comment]
Please see [this help article](https://help.niagaralauncher.app/article/108-random-numbers).
