### ISSUE TITLE
Need to get Feature Request

### ISSUE THREAD

**Issue by SopheakdeyHean** [8bitPit/Niagara-Issues#1577]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by Maxr1998** [comment]
Hello, it seems that didn't really work. Could you add details about what you're actually requesting please?
