### ISSUE TITLE
Option to dismiss "Set as default launcher again" warning 

### ISSUE THREAD

**Issue by rosenpin** [8bitPit/Niagara-Issues#1578]
### Use case
I'm using a launcher wrapper called IntentTask but there are several others like AutoTools for example.  
Launcher wrapper are used to provide users with more automation possibilities or functions that are only available for launchers (access to shortcuts for example).  
The launcher wrapper is configured with the actual default launcher, so the default launcher as far as Android is concerned is the 'wrapper', while the actual app that opens when you tap the home button is the configured launcher (Niagara in my case)   
**You can think of a launcher wrapper as an empty intent that launches the default launcher on creation, and provides user with other functionalities outside of said activity**

### Issue
The issue I'm experiencing is that Niagara keeps prompting me to set it back as my default launcher, while it practically already is.  
Unfortunately, this prompt is pretty obnoxious and **can't be dismissed**.  
I should also add that I think this issue isn't specific for my use case, I think anyone should be able to ignore/dismiss this warning, not everyone need to set Niagara as default in order to avoid this warning message.
#### Screenshot
![screenshot-2021-04-27_10_00_25](https://user-images.githubusercontent.com/5289630/116199251-959ffb00-a73f-11eb-92e1-b445f73a5ce9.png)

Video example:

https://user-images.githubusercontent.com/5289630/116206999-13680480-a748-11eb-8c2b-85a150d6ba4f.mp4

## Possible solutions
I get why you so aggressively prompt users to set Niagara as the default launcher, some of its behavior depends on it being the default launcher (like access to shortcuts), and I think it's good to have a persistent indicator allowing less knowledgeable users to switch back to Niagara as the default launcher, but I think its place is at the top of the settings menu, or at least allow it to be dismissed, either make it swipeable like other notifications, or add a "don't show again button"

**Comment by Oddward** [comment]
**Preface:**
I think the prompt is both there to simplify the UX for most users, and also to kinda urge users to use Niagara so as to get used to the decluttered minimal interface. A lot of new users evidently end up wanting additional bloat and excess customisation settings after getting a launcher designed for the opposite lol

**Current solution:**
Niagara does actually have a secret command for this (i.e. commands entered in the Search page for various debugging functions and extra *unofficial* features etc)

Type `/suppresssetlauncherprompt` in Search and hit enter

**Comment by 8bitPit** [comment]
Thanks for your detailed ticket @rosenpin :D I hope the [secret command](https://help.niagaralauncher.app/article/74-entering-hidden-commands) @Oddward shared could help.

**Comment by rosenpin** [comment]
Where can we find a list of all the secret commands?

**Comment by 8bitPit** [comment]
@rosenpin most secret commands are intended for debugging purposes, and we don't have a public list for them. However, you can find a couple of commands by visiting our knowledge base and searching for "secret command": https://help.niagaralauncher.app/search?query=secret+command,

**Comment by Amorphous404** [comment]
- Duplicate of #949
