### ISSUE TITLE
Swipe up on Niagara homescreen has long delay before it enters multitasking pane

### ISSUE THREAD

**Issue by SluggoTR** [8bitPit/Niagara-Issues#1581]
There is a 1-2 second delay when entering the multitasking pane using the swipe gesture navigation bar on the Niagara home screen. I have to now hold my finger in the middle of the screen for 1-2 seconds before it opens the multitasking pane. Works instantly in other apps, and didn't use to have this behavior. 

**To Reproduce**
1. Use the pill style/swipe style navigation bar (button style still seems ok)
2. Go to Niagara home screen
3. Swipe up on navigation pill
4. Hold finger in the center for 1-2 seconds

**Smartphone:**
 - Device: Samsung Note 20 Ultra
 - Android version: 11
 - One UI Version: 3.1

**Other notes**
May be a One UI/Samsung issue. Seemed to start with a software update from my carrier. Not the only person experiencing the issue - 
https://www.reddit.com/r/NiagaraLauncher/comments/n0m681/swipe_up_on_niagara_homescreen_has_long_delay/gw7l77x/?context=3

**Comment by 8bitPit** [comment]
Hey, @SluggoTR, apologies for the late reply. Yes, this is a Samsung issue, unfortunately (and should also be reproducible on other third-party launchers like Nova Launcher or Microsoft Launcher). I hope  Samsung fixed it by now.

**Comment by SluggoTR** [comment]
Thanks for the reply. No, unfortunately it hasn't been fixed yet :/
