### ISSUE TITLE
Search Engine on Niagara Launcher

### ISSUE THREAD

**Issue by winfieldfwatson** [8bitPit/Niagara-Issues#1582]
While the Google search engine may be the no 1 engine still used, BING, as an engine is superior when one wants to search and have more accurate results (esp if using query syntax). 
The ability to modify the search engine presented on the home Niagara Waterfall would be a nice feature and also integrate a standard many apps which present an engine to use already have integrated.
please consider 🙏

**Comment by Oddward** [comment]
If you're referring to the floating Google button then that will likely be added. See: [https://github.com/8bitPit/Niagara-Issues/issues/300](this issue)

FYI, if you use the Sesame search integration you can set any search engine to open results with from the Niagara search page, you can do it in Sesame > settings menu > search settings

**Comment by 8bitPit** [comment]
I'm happy to tell you that in v1.2., we added the Niagara button that is freely customizable: https://help.niagaralauncher.app/article/116-niagara-button 😀
