### ISSUE TITLE
G

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1584]
G

**Comment by Oddward** [comment]
Niagara is currently using OpenWeather. There's no guarantee a different provider will be more accurate as it depends on your location (and if that were the case DarkSky wouldn't have been as popular as it was), for most users it seems accurate enough

There have been a few reports about inaccuracies that I've seen in discussions but not too many. Currently the main suggestion is to install the OpenWeather app, through it you can contact those devs and report to them about your specific location, this in turn can help improve the weather experience for all users later

Doesn't seem that simple to change weather providers & they're all premium APIs
