### ISSUE TITLE
Samsung launcher activates

### ISSUE THREAD

**Issue by PaulReiber** [8bitPit/Niagara-Issues#1586]
https://user-images.githubusercontent.com/58688/116834224-eb2a3c80-ab71-11eb-9e84-4a8c34151986.mp4

**Describe the bug**
Samsung launcher activates when it should not

**To Reproduce**
1. open some apps
2. click / swipe |||
3. close all but one app
4. tap outside that app
5. wrong launcher appears

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy tab S7 +
 - Android version: 11

**Screenshots**
screen recording

**Comment by PaulReiber** [comment]
Problem only evident right after installing Niagara Pro.
After reboot I am not seeing the problem any more.

**Comment by 8bitPit** [comment]
Thanks for sharing the bug, Paul. We'd love to be able to fix it, but unfortunately, this one is caused by Samsung: https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default. Fancy wallpaper btw :D
