### ISSUE TITLE
UI enhancement: Hidden apps list heading

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1587]
If you go to the Hidden apps list, at first it shows only the big heading text, but if you then scroll a little, you'll see both the big heading and the "pill" style box, so essentially the same thing twice. Then if you scroll more, you'll see only the "pill" small heading.

I think it would be better if the little "pill" heading showed only after you scroll past a certain threshold where the big text heading would now be completely covered by the smaller heading. So only one of these could be visible at a time, never both at once.

Use more of the top section here when scrolling
![Screenshot_20210503-171608_Niagara Launcher](https://user-images.githubusercontent.com/35201200/116895948-fcd41880-ac33-11eb-885f-ff07e6ae73ff.jpg)
so this wouldn't show yet
![Screenshot_20210503-171625_Niagara Launcher](https://user-images.githubusercontent.com/35201200/116896053-212ff500-ac34-11eb-94a4-b503299ddebb.jpg)
until you scroll more like this
![Screenshot_20210503-172058_Niagara Launcher](https://user-images.githubusercontent.com/35201200/116896071-268d3f80-ac34-11eb-879d-b06d0a600cbe.jpg)

**Comment by 8bitPit** [comment]
Oh I forgot to tell you that we implemented this a while ago :D
