### ISSUE TITLE
Notification swipe gesture too insensitive

### ISSUE THREAD

**Issue by aryankatwal** [8bitPit/Niagara-Issues#1588]
Don't keep the rubber effect while pulling the notification tray because it adds a delay while doing that and I am always get frustated because sometimes it takes even 3 try to open the notification tray.

https://user-images.githubusercontent.com/83635369/116973497-49722f00-acda-11eb-9a5b-5b299be52141.mp4

**Comment by luxcalor** [comment]
Agree. This is probably the only thing that is slightly annoying in niagara.

**Comment by dgustala** [comment]
> Agree. This is probably the only thing that is slightly annoying in niagara.

Totally agree with @luxcalor

**Comment by Montell2099** [comment]
I don't really agree, the rubber band effect is very satisfying & works consistent for my personal use.

Perhaps the threshold of the swipe sensitivity should be customizable to help you with this issue.

**Comment by Flyb4ck** [comment]
I agree on this being annoying too. When I swipe to expand the status bar is always a 2 or 3 times retry. when Niagara was in beta I thought it would have been fixed soon but after months this is still bothering me. If there are people that appreciate the effect then would be nice to have a switch.

**Comment by Montell2099** [comment]
I might be wrong, but maybe this problem is worse on certain phones/OS/Android versions, because I recognize this occurring a few times — but then I often discard it as my own fault for releasing the swipe too early.

I don't see it all too often though on my Pixel 2 with Android 11, but it might need some tweaking to work better on more devices.

**Comment by Oddward** [comment]
As far as I can tell the rubber band effect just acts as visual feedback for the user's input & should be a separate issue from the sensitivity of the pull-down gesture. It's true that it's not perfectly responsive, although I can get it to a fairly reliable level usually

**Curious** : for those who always have trouble with it, are you showing or hiding the status bar?

**Comment by Maxr1998** [comment]
The rubber band effect doesn't actually affect the swipe threshold - it's possible however that this threshold is too high for some devices (especially those with touch lag differently behaving digitizers).

**Comment by awnumar** [comment]
+1 on this, are there any plans on fixing it?

- Sometimes the notification drawer doesn't come down at all and takes multiple swipes
- There's a noticeable delay between pulling it down and the drawer coming down. You can test this by comparing it with pulling down from the top of the screen (see video in #1870). Might be related to the animation, if so I'd like to be able to turn the animation off as the latency is annoying 

OnePlus 7T Android 11

**Comment by awnumar** [comment]
> Curious : for those who always have trouble with it, are you showing or hiding the status bar?

I have my status bar visible

**Comment by abhy-kumar** [comment]
+1 on potentially adding a swipe sensitivity option on this.

**Comment by slick92** [comment]
+1 on S22 Ultra. Not being able swipe down on the home screen on bigger phones is extremely troublesome.

**Comment by Oddward** [comment]
I'll close this for now, if there are any further issues feel free to add a comment or request to reopen
