### ISSUE TITLE
The media control widget is broken

### ISSUE THREAD

**Issue by akashpandey** [8bitPit/Niagara-Issues#1591]
**Describe the bug**
The media control widget for Niagara launcher which is used by YouTube, Netflix etc is wonky and doesn't update the state(Play, Pause) at times.

**To Reproduce**
1. Use media apps like YouTube, Netflix
2. Check the media control widget state
3. Most times it shows "Pause" state even if media is paused, and doesn't respond to taps at times.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: Android 11 running latest security patch

**Screenshots**
Not applicable.

**Comment by luxcalor** [comment]
Happens from time to time for me too. Even though media is playing, Widget becomes unresponsive.

**Comment by 8bitPit** [comment]
Thank you very much for the report. Does the media player notification in Android's notification shade reflect the play/pause state correctly?

**Comment by luxcalor** [comment]
Yes, the mini player in the notification shade does reflect and respond correctly. The one in niagara becomes unresponsive from time to time. Also sometimes after the media is paused niagara's widget disappears altogether from the home screen, even though notification player is still present and paused in the shade. Happens with all media applications I use.

**Comment by 8bitPit** [comment]
I see; thanks, @luxcalor. About the media player getting removed, that is intentional and we also cannot keep it at all times, see "Why doesn't the Media widget stays on screen all the time?": https://help.niagaralauncher.app/article/11-media-widget.

**Comment by luxcalor** [comment]
Hi @8bitPit, there is no problem for me with widget disappearing after some time of non activity, it's good actually. Also in the new version the widget doesn't go away when two media apps are open, it just reflects the last one that was active, which is perfect. It's not freezing anymore too. It all works and feels great currently, even on a very old Android version. Thank you very much for fine-tuning all those details, really makes it a joy to use.

**Comment by 8bitPit** [comment]
Awesome, thank you very much for reporting back :D
