### ISSUE TITLE
Widget setting dialog is dismissed when tapped on it

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1592]
If an app invokes the Niagara "Add widget dialog", this dialog can correctly be dismissed either by tapping cancel or tapping somewhere empty on the screen. But the dialog also closes when you tap inside it, on the dialog body itself, which is not expected.

![Screenshot_20210506-201720_Niagara Launcher](https://user-images.githubusercontent.com/35201200/117348141-27c7a200-aeaa-11eb-9c91-e8cdde90310b.jpg)

Niagara 1.1.3
Android 9.0
Samsung Galaxy J7

**Comment by 8bitPit** [comment]
Fixed in v1.2.
