### ISSUE TITLE
"Add widget" dialog animation – use fade out instead of movement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1593]
Just a really minor UI nitpick: The Niagara "Add widget" dialog has a semi-transparent dark background, which, if you dismiss the dialog, animates so that it falls from top to bottom and out of the view. But during this animation you can see the edge of that dark background layer as it moves. So I think it would be better to use a fading animation instead of moving, so you couldn't see where the background layer ends.
(I think it's the same for the Add shortcut dialog as well.)

**Comment by Amorphous404** [comment]
Fixed? If not can you share a recording of the issue, i can't seem to notice it 😅

**Comment by 8bitPit** [comment]
Oh yeah, we fixed it :D
