### ISSUE TITLE
Swipe down to app only search like iphone, Swipe up is hard

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#1594]
Swipe up is hard becacuse trigger point is onbottom of screen. But swipe down is free, anywhere on screen.It make feel easy like iphone spotlight search page. 

Try to make a toggle in settings for that.

**Comment by 8bitPit** [comment]
You can also swipe up from anywhere to open search. If you have more favorites that can fit on one screen, you might need to scroll up first. Please let me now if that helps.

**Comment by rubslopes** [comment]
Swipe down would mess with the "open notifications tray" functionality.
