### ISSUE TITLE
Calendar – open calendar arrow button not easily accessible with long agenda list

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1596]
The little arrow button at the bottom of the agenda widget is always at the very bottom of the list, regardless of how long it is. This means that when I have more events, I can access that button only after scrolling all the way down.
![Screenshot_20210508-194958_Niagara Launcher](https://user-images.githubusercontent.com/35201200/117548957-05638f00-b038-11eb-9c2d-f6a94ebc1ee8.jpg)
I think it should instead be fixed to the relative bottom of the visible part of the widget and overlay the content when scrolling, making it always accessible.

**Comment by luxcalor** [comment]
Yep, opening calendar by tapping on "my agenda" would be very nice.

**Comment by Martin5001** [comment]
> Yep, opening calendar by tapping on "my agenda" would be very nice.

Or that, yes

**Comment by 8bitPit** [comment]
@Martin5001 & @luxcalor You can also tap on the dates to open the calendar; the calendar will also scroll to that day. Because of this, I'd leave it the way it is.
