### ISSUE TITLE
Add or replace widget title wrapping

### ISSUE THREAD

**Issue by WendySclerandi** [8bitPit/Niagara-Issues#1598]
The title on the screen to create or replace a widget has a wrong wrapping in spanish. 
The screen is the one that appears when you press and hold on the calendar widget and press 'add new widget'.
I am using a xiaomi redmi Note 7. 

![Screenshot_2021-05-12-21-56-35-310_bitpit launcher](https://user-images.githubusercontent.com/21165322/118062291-0ca6d780-b36d-11eb-96fb-5c055b8971f9.jpg)

![Screenshot_2021-05-12-19-53-41-589_bitpit launcher](https://user-images.githubusercontent.com/21165322/118061890-3ca1ab00-b36c-11eb-9f9d-d582f9a17dd5.jpg)

**Comment by 8bitPit** [comment]
Thanks for reporting, @WendySclerandi :) Android 10+ disables hyphenation for all text views by default to increase performance. I agree that it looks quite odd without the correct hyphenation; I'll enable it for the headline in v1.3.

**Comment by 8bitPit** [comment]
I turned on auto-hyphenation in v1.3., I hope it looks better now.
