### ISSUE TITLE
Proton Calendar Issue

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1599]
Proton Calendar doesn't appear among the options in Niagara's agenda widget, so I'm not able to visualize my events and agenda in niagara's widget.

**Comment by 8bitPit** [comment]
Thanks for reporting. I fear that Proton Calendar doesn't make use of Android's calendar API. Can other third-party apps (e.g. "Another widget") access its calendar? More details here: https://help.niagaralauncher.app/article/76-calendar-faq

**Comment by Just-SKY** [comment]
Sadly, it seems to be a proton calendar issue,  and u were right because I tried it with other 3-party apps. I didn't know it didn't work with other 3rd-party apps cuz I had never try it before. 
I can only

**Comment by 8bitPit** [comment]
Ah, that's a bummer. Thanks for letting me know, I'll close the issue.
