### ISSUE TITLE
Colored Menus

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#16]
the menu when you hold/swipe right (or folder menu, which is in issue 13) should have some color settings

**Comment by 587saboor** [comment]
Heres a suggestion for colored menus, maybe it could link to the colors of the wallpaper like the app search bar does

**Comment by Chaphasilor** [comment]
I agree there should be some kind of consistency with the wallpaper/search bar, but I don't think we need to manually select a color. Just keep it clean with a toggle for day/night mode and extract the colors from the wallpaper...

**Comment by 8bitPit** [comment]
Yeah… maybe it will be implemented, but at a later date.

**Comment by 8bitPit** [comment]
Hey again. I thought a bit about offering a colored menu option and I came to conclusion not to add it, because I want to keep the settings to a minimum.
