### ISSUE TITLE
Add option to disable pop-up shortcuts

### ISSUE THREAD

**Issue by Veecks** [8bitPit/Niagara-Issues#1600]
**Describe the bug**
Shortcuts(quick actions) can't be hidden properly with Sesame because the shortcuts will come back automatically after a while since this is how Sesame works.

**To Reproduce**
1. Follow the guide posted in Niagara's official page to hide some app shortcuts: https://help.niagaralauncher.app/article/84-hide-shortcuts
2. After a while, the shortcuts will come back.

OBS: considering my experience, this bug can be quickly perceived when trying to hide youtube shortcuts, it will come back after a few minutes, but this is my personal experience and I can't say it will be the same for other devices.

OBS 2: I am pretty sure this is a general bug, brcause there are some people who also related it to me.

**Smartphone (please complete the following information):**
 - Device: [Galaxy Note 10]
 - Android version: [Android 11, ONE UI 3.1]

**Screenshots**
Not applicable.

**Comment by luxcalor** [comment]
Yep, I have the same issue. The only solution that works permanently for me, is to add apps to blacklist in sesame.

**Comment by Montell2099** [comment]
I am experiencing the same issue, I wonder if there's a potential fix/work-around on Niagara's end — or if this boils down to how Sesame works.

**Comment by Veecks** [comment]
> I am experiencing the same issue, I wonder if there's a potential fix/work-around on Niagara's end — or if this boils down to how Sesame works.

Yeah, me too. But maybe this functionality could be implemented into Niagara without sesame as a workarround. It would be a simple "hide" rather than desactivating it in sesame.

**Comment by 8bitPit** [comment]
Do these shortcuts also come back if you tap on "Toggle all off" at the top right in Sesame's shortcut options of a specific app?

**Comment by Veecks** [comment]
> Do these shortcuts also come back if you tap on "Toggle all off" at the top right in Sesame's shortcut options of a specific app?

Yes, they do. Actually i ve found 2 workarounds for this bug:
1. You can fix one shortcut in the specific app options and hide all the others. This way, only the fixed shortcut will show and the other ones will be hidden. For me, this workaround is not very satisfying because I don't want any of the shortcuts to be shown, also, there was a time when the shortcuts also came back even with the fixed shortcut, but it was just one time.

2. If you put an app in the sesame's blacklist, all the shortcuts of this app will be hidden and it will not come back. This is the best solution for me since I don't like shortcuts. That's it!

**Comment by Montell2099** [comment]
> Do these shortcuts also come back if you tap on "Toggle all off" at the top right in Sesame's shortcut options of a specific app?

I tried disabling all shortcuts for Snapchat in the pop-up menu two days ago, and today all of them have been automatically enabled again unfortunately.

**Comment by 8bitPit** [comment]
Ah, I see. Maybe we'll add an option to disable pop-up shortcuts for a specific app.

**Comment by Veecks** [comment]
> Ah, I see. Maybe we'll add an option to disable pop-up shortcuts for a specific app.

That would be awesome! Thank u for ur hard work!

**Comment by Oddward** [comment]
FYI, for those using Sesame to hide the shortcuts for now, the most reliable way to do it is to add the app to Sesame's blacklist, this seems to keep them hidden, whereas toggling stuff off does eventually toggle itself back on for some reason (I think when there's any change in its shortcuts such as a new contact)

**Comment by Montell2099** [comment]
@Oddward Thanks man, I've tried using the Sesame blacklisting function for the first time now. Let's hope it'll be a viable work-around.

**Comment by 8bitPit** [comment]
Fixed in v.1.4
