### ISSUE TITLE
Folder Popup in Icon selection screen 

### ISSUE THREAD

**Issue by ModProg** [8bitPit/Niagara-Issues#1602]
When first opening the folder pop up, than via long press the folders options and than change the icon, this happens:
![](https://i.imgur.com/FNLA215.jpg)

**Comment by luxcalor** [comment]
Wow, which icon pack is that? Looks very nice. Don't have this issue with the packs I use, BTW. :)

**Comment by ModProg** [comment]
video:

https://user-images.githubusercontent.com/11978847/118435219-d5268b00-b6de-11eb-9ed6-1697a4ad0d1c.mp4

**Comment by 8bitPit** [comment]
Fixed in v.1.2.2.

**Comment by 8bitPit** [comment]
Btw, thanks for reporting @ModProg :)
