### ISSUE TITLE
Please support the alignment of characters, not alphabets.

### ISSUE THREAD

**Issue by whaaatsup** [8bitPit/Niagara-Issues#1603]
Like Samsung Music, I hope you can support the alignment of non-alphabet characters. The app "쿠팡(coupang)" is searched in "K", but there are several apps that are misaligned, so it's very inconvenient to find the app.

![KakaoTalk_20210514_163125376](https://user-images.githubusercontent.com/74079450/118238705-d8016000-b4d3-11eb-9c88-0b0c78cf983a.jpg)

**Comment by 8bitPit** [comment]
Our goal is to keep the alphabet short to be able to easily navigate it with one hand. That's why we romanize Korean names and put them into Latin letter sections. The romanization algorithm itself is provided by Android, so we cannot improve it, unfortunately.
