### ISSUE TITLE
Favorites not resizing on resolution change

### ISSUE THREAD

**Issue by deb0011** [8bitPit/Niagara-Issues#1605]
On my s21 ultra, I have a schedule running to switch the screen resolution down to 1080p when the battery drops below 30%.

Whenever the resolution changes (both up and down) the niagara home icons and widget fail to resize automatically. So when I go up to 1440p, everything becomes small and it's the opposite when my phone goes down to 1080p.

Restarting the launcher from advanced settings fixes this issue. Can this be automatically done by the launcher somehow?

**Comment by 8bitPit** [comment]
Hi @deb0011, thank you very much for the bug report. We're planning to fix it, see  #1318 😀
