### ISSUE TITLE
Google Button Swipe Up Broken

### ISSUE THREAD

**Issue by kumaraadarsh17** [8bitPit/Niagara-Issues#1608]
**Describe the bug**
Google search page launches and crashes when swiping up on the Google Button.

**To Reproduce**
1. Activate Google Button in settings.
2. Swipe up on the button
3. Search page shows for a split second and disappears.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 11X
 - Android version: Android 11

**Screenshots**
https://user-images.githubusercontent.com/16821040/118667438-a65d0180-b811-11eb-8570-4f1a4a70e1ae.mp4

**Comment by 8bitPit** [comment]
Hi @kumaraadarsh17, I hope the following thread can help: https://github.com/8bitPit/Niagara-Issues/issues/1500

**Comment by kumaraadarsh17** [comment]
Hey, Thanks for the response. I updated to the latest beta and using the Niagara Button, it works now.

**Comment by 8bitPit** [comment]
Great, thank you for letting me know :)
