### ISSUE TITLE
Toggling pitch black theme causes widget to go blank

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#1609]
If I have a dark theme enabled and then toggle the pitch black theme, Samsung Notes widget placed in a popup goes blank like this:
![Screenshot_20210518-192522_Niagara Launcher](https://user-images.githubusercontent.com/35201200/118697519-a8be5c00-b80f-11eb-94ee-3095f0ca8725.jpg)
It happens with dark theme only. Not when switching from/to light, but only black/dark.
Restarting the launcher fixed it temporarily.

Niagara 1.2.2
Android 9
Samsung Galaxy J7

**Comment by thedanwray** [comment]
Mine does this to the widget as well, but I don't change my theme. I usually notice it after leaving the phone to charge overnight, and have to restart the launcher to get the widget to come back.

**Comment by 8bitPit** [comment]
Fixed in v.1.3.6
