### ISSUE TITLE
Google floating button desn't work with Google Go

### ISSUE THREAD

**Issue by muzscaly** [8bitPit/Niagara-Issues#1610]
**Describe the bug**
On the tap on button it shows toast "app isn't available" refers to normal Google app. That button IMO must also open the Google Go when normal Google app isn't installed.

**To Reproduce**
1. Uninstall/Disable Google App
2. Install Google Go App
3. Activate Google button
4. Tap on the button
5. ???
6. No profit

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A10
 - Android version: Android 10 Q

**Screenshots**
![Screenshot_20210520-104440_Android System.jpg](https://user-images.githubusercontent.com/15150065/118948470-956ad800-b958-11eb-9a4c-394752c16786.jpg)

**Comment by 8bitPit** [comment]
Thanks for the report, @muzscaly. We're replacing the Google button with the Niagara Button. It will let you freely customize what app to launch: https://help.niagaralauncher.app/article/116-niagara-button. If you want to try it out right away, feel free to join our beta: https://help.niagaralauncher.app/article/107-beta-tester

**Comment by 8bitPit** [comment]
kk; thanks for letting me know :)
