### ISSUE TITLE
Weird floating button in Android 12 beta 

### ISSUE THREAD

**Issue by Simon-JB** [8bitPit/Niagara-Issues#1612]
Since I installed the android 12 beta, using Niagara's latest beta version, I have this weird floating button that bears the Niagara icon, can be dragged on either side of the screen (but not removed) and doesn't do anything when pressed. It is overlayed constantly on the screen, whatever the current app. 

![Screenshot_20210520-135708](https://user-images.githubusercontent.com/37332354/118974813-89d8da80-b973-11eb-8f1d-f2fd0b10dbdc.png)

I can't be sure though if it is a buggy new Android related feature that somehow picked Niagara's icon or a bug specific to Niagara launcher. 
Just thought I'd let you know just in case!

**Comment by 8bitPit** [comment]
Thanks for reporting @Simon-JB. Someone from our Telegram community found out what this button is and how to disable it; I hope this helps: https://help.niagaralauncher.app/article/118-android-12-disable-floating-niagara-button.

**Comment by Simon-JB** [comment]
Oh, many thanks, this does the trick indeed…! I think we can close the issue. For new users though if this toggle is activated by default when Niagara has the permission, it can be a bit weird so maybe there's a setting to change by the time Android 12 is out (no rush though)

**Comment by 8bitPit** [comment]
Agreed, that shortcut button does not make sense for the screen locking feature. We'll check if Android 12 accessibility API offers a way to hide the shortcut button by default.
