### ISSUE TITLE
Visual glitch in app closing animation

### ISSUE THREAD

**Issue by finkrer** [8bitPit/Niagara-Issues#1614]
**Describe the bug**
App icons are often surrounded by visual artifacts in the end of the new app closing animation when using gestures.

**To Reproduce**
1. Open an app that has an icon on the home screen.
2. Swipe up to close the app
3. Observe the glitchy effect when the icon sets into place

**Smartphone (please complete the following information):**
OnePlus 5T, Android 11

**Screenshots**
Some of the glitches that can be seen, look at the Telegram icon:
<div style="display: flex;">
  <img src="https://user-images.githubusercontent.com/22712590/119256391-f5bc7c80-bbd9-11eb-84a1-cb1516f4fffd.png" width="300" />
  <img src="https://user-images.githubusercontent.com/22712590/119256392-f9500380-bbd9-11eb-9ee9-439ce308d5cf.png" width="300" />
</div>

**Comment by finkrer** [comment]
If that helps, that square seems to be a part of the app's window, since it changes color depending on what color the window's background is.

**Comment by 8bitPit** [comment]
Thanks for reporting @finkrer. It sound's weird, but the close animation is from a submodule of your preinstalled launcher; OnePlus launcher in your case. The same artifacts should also be reproducible with other third-party launchers then, e.g., Nova Launcher or Microsoft Launcher. Unfortunately, we have to wait for OnePlus to fix that.

**Comment by finkrer** [comment]
Perhaps I should have said that I'm using a custom ROM, so my preinstalled launcher is Pixel Launcher. Does it mean deleting it would break the animations altogether?

I will try reproducing it with other launchers and report back.

**Comment by finkrer** [comment]
Well, I've tried it with the launchers you mentioned. On Nova it works flawlessly, no glitches. Microsoft Launcher doesn't seem to have this feature? Pixel Launcher has the same animation as Nova and it also works great.

I tried deleting Pixel Launcher, it broke everything, haha. So I guess it does take the animation from there. Don't worry, it's all fine now.

If it's not possible to fix this, maybe the animation should be made optional? The launcher looks very high-quality otherwise, and then you get these ugly glitches when closing an app.

**Comment by 8bitPit** [comment]
I can always reproduce this issue on Niagara and Nova Launcher with this app: https://play.google.com/store/apps/details?id=net.helpscout.android. We submitted a bug report to Google, and they're investigating it: https://issuetracker.google.com/issues/194427611. For most apps, the bug only occurs if you touch anywhere while the animation is running. If we get complaints about this more frequently, we'll probably make this animation optional.

**Comment by finkrer** [comment]
Seems to be working fine for me now, most likely after a ROM update. My default launcher is now, uh... Shishu Foot Lettuce, which may have something to do with it.  

But yeah, if you tap anywhere during the animation, Niagara flashes for a split second after it ends.

**Comment by dustinkerstein** [comment]
Just wanted to note that I can also replicate this on LineageOS 18.1 on a Pixel XL. However, with gesture controls enabled, it happens much more frequently as you're obviously touching the screen to invoke the minimize action. It'd be nice if the animation could be optionally disabled. Thanks!

**Comment by 8bitPit** [comment]
Does that still happen with our latest release (v1.8) on Android 13?

**Comment by finkrer** [comment]
No, haven't seen it for a long time. Definitely not on Android 13.

**Comment by 8bitPit** [comment]
Awesome, thanks for letting us know @finkrer.
