### ISSUE TITLE
Choosing speakers in media player

### ISSUE THREAD

**Issue by AmitStein98** [8bitPit/Niagara-Issues#1617]
I think it would make sense for the built in media player to have the option to choose which speakers will play the media, like how it is in the notifications shade

**Comment by Oddward** [comment]
I think that feature in the notification shade is device-specific. I don't have it on Xiaomi MIUI, someone I know has it on Huawei's EMUI

**Comment by timm0e** [comment]
Hey :wave: 

Thank you for your feature request!

We believe that this option would rarely be used, and would therefore not be considered impactful for our minimalistic media widget.
