### ISSUE TITLE
Hiding an alphabet in apps list, too

### ISSUE THREAD

**Issue by Fen0MeN102** [8bitPit/Niagara-Issues#1618]
Heya. There is a bug in 1.2.3 (from 24th may), which makes an alphabet hiding after using in the apps list (like on the main screeen), if the hiding is enabled. So that's how my idea was born.
How about to make people choose between "hiding modes" - on the main screeen, on the apps list (that one would be beautiful, too) or everywhere? That will be really nice!

**Comment by Fen0MeN102** [comment]
Sorry for informal suggestion lol

**Comment by 8bitPit** [comment]
Thank you very much @Fen0MeN102, the alphabet should now be working again fixed with the latest version :)
