### ISSUE TITLE
Quick app opening

### ISSUE THREAD

**Issue by afroninjaen** [8bitPit/Niagara-Issues#162]
It would be nice to have some way of opening the first app that appears when using the alphabet slider, either by double clicking or maybe swiping. I know its only a matter of seconds, but it would make it seem even more seamless than it already is.

**Comment by pradyw** [comment]
Yup, a quick right swipe  will be very good.

**Comment by 8bitPit** [comment]
Yeah, would be neat, however finding a gesture that is both intuitive and not easy to trigger it accidentally is tough. If you've got some specific ideas pls tell me.

**Comment by afroninjaen** [comment]
I'm thinking maybe when you slide your finger all the way to the left, still holding down on the alphabet, the first icon would light up letting you know that it would open if you'd let go, and it would stop lighting when you slided back in right direction and then work as normal.

**Comment by Shinra04** [comment]
I was thinking the same @afroninjaen. It's the most intuitive. 

On another note, wouldn't it be nice to see the same highlight effect on the first app that shows up when you're searching for an app (which launches when you tap search)

**Comment by jakcharvat** [comment]
Love this idea. I feel like it could be both intuitive and non intrusive

**Comment by phlppk** [comment]
I would love a quicklaunch feature like this. I imagine swiping on the menu side of the screen cycling through the letters, when at the desired letter is in scope, moving the finger to the app list continuing the swipe could be used to select the app and launch it on release

**Comment by Grishnackh6** [comment]
Its been brought to my attention (via reddit), Ive had the same as this.  (As well as an idea for Folders)
Please view my post here :)
https://www.reddit.com/r/NiagaraLauncher/comments/btprel/idea/

**Comment by casidiablo** [comment]
I also like this idea! Was about to suggest it myself. I wonder why is this marked as problematic? Are there architectural decisions baked into the app that makes it extra difficult to implement?

**Comment by realslacker** [comment]
I also would love to see the launch without lifting your finger... Seems really intuitive.

**Comment by adamdjensen** [comment]
this may be a little too nintendo wii, but what about flicking your phone to launch the top app of the letter you selected?

**Comment by 8bitPit** [comment]
> this may be a little too nintendo wii

Made my day XD Yeah, this might be a little gimmicky but it's a cool idea nevertheless :)

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, we’ve decided to close all feature requests that are unlikely to be implemented in 2022. This is one of those, unfortunately. I'm sorry.
