### ISSUE TITLE
Pop-up folders notificator

### ISSUE THREAD

**Issue by Crolug** [8bitPit/Niagara-Issues#1621]
Pop-up folders are great feature but they need some form of notification that inside them there are new embedded notifications waiting, like a simple dot in the corner of an icon, something like this.

**Comment by Oddward** [comment]
You can follow this issue [https://github.com/8bitPit/Niagara-Issues/issues/1201](#1201) for now, although maybe a new separate open issue would be better 🤔

**Comment by Rod911** [comment]
Issue is similar enough to linked issue.
Merging with #1201
