### ISSUE TITLE
TuneIn does not close

### ISSUE THREAD

**Issue by diceware** [8bitPit/Niagara-Issues#1622]
**Describe the bug**
When TuneIn is closed, the media widget does not  closes

**To Reproduce**
1. Start Tunein
2. Start any radio  station
3. Go back home
4. Media widget is still appearing

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - Android version: Android 11

**Screenshots**

**Comment by 8bitPit** [comment]
Hey @diceware, thanks for letting us know. Does the media player also still appear in Android's notification shade after closing the app?

**Comment by diceware** [comment]
Yes, it does.

--
Sergio Giraldo .:. sent from mobile
{+31 6 2193 9574}

________________________________

**Comment by 8bitPit** [comment]
Sorry for the late reply. To me, something very similar happened recently but with Spotify. However, I realized that Spotify's media player was still visible in the notification shade, but only after I'd fully expanded the quick settings. Could you please check if that's also happening to your player?
