### ISSUE TITLE
Convert Japanese characters in search

### ISSUE THREAD

**Issue by norocchi** [8bitPit/Niagara-Issues#1623]
I'd like to add a function to convert Japanese _hiragana_ characters to _katakana_ in the Niagara's search field. If the app internally search apps using both _hiragana_ and _katakana_, the experience will be greater.

## What Japanese characters are
We use three character systems, _hiragana_, _katakana_ and _kanji_. _hiragana_ and _katakana_ are syllabic, and easy to replace each other. For example:
- "あ" (_hiragana_) to "ア" (_katakana_)
- "か" (_hiragana_) to "カ" (_katakana_)

## How we input characters
We first input _hiragana_ and then convert to _katakana_ or _kanji_. Since we want to get an answer quickly when searching apps, the steps of inputting some characters and converting are troublesome.
For example, I search for a map app and its name is "マップ (_katakana_ is used)" (Romanized: mappu, _hiragana_: まっぷ). I input "ま" at first but the map app does not appear since "ま" and "マ" is different. I need to input "まっぷ", then convert to "マップ", and finally find the map app.
If Niagara's search function uses both _hiragana_ and _katakana_ to search apps, it's very convenient to search.

## References
- [Hiragana Katakana Table](https://katakanachart.com/hiragana-katakana-table/)
  - The second table of the page is helpful for listing all characters. There are totally 154 characters (77 _hiraganas_, 77 _katakanas_).

**Comment by 8bitPit** [comment]
Hi @norocchi, pardon for the late reply. We plan to migrate to Android's [App Search Library](https://developer.android.com/jetpack/androidx/releases/appsearch) once it's stable. Reading the changelog of v1.0.0-alpha02 of the library, this feature might be inbuilt, it reads "Full support of Chinese/Japanese/Korean/Thai languages" but I'm not sure if that includes Hiragana to Katakana transliteration. I'm merging this issue with https://github.com/8bitPit/Niagara-Issues/issues/1066
