### ISSUE TITLE
Inconsistent position of notification icon

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1624]
I'm not entirely sure if this is a bug — but even whilst receiving short messages, the notification icon can get displayed very far out to the right side.

Perhaps it has to do with the link I received that got "splitted", due to its length. I'll attach a screenshot of the potential issue.

![Screenshot_20210529-182859](https://user-images.githubusercontent.com/43126233/120172835-bd352800-c203-11eb-8155-bbe5f228d7f6.png)

**Comment by Rod911** [comment]
Might be caused by multi-line notification and not necessarily the content of the notification itself.

**Comment by Montell2099** [comment]
> Might be caused by multi-line notification and not necessarily the content of the notification itself.

True indeed!

**Comment by 8bitPit** [comment]
Yup, it's because Android's TextViews are expanded to their full width if the line length is greater than one. Here's an article that explains it and also does a hacky workaround, but I'm not sure if it's worth doing that. https://medium.com/@mxdiland/android-textview-multiline-problem-61f8c3499bbb
