### ISSUE TITLE
Media controls don't work for Sonos app

### ISSUE THREAD

**Issue by leonkielstra** [8bitPit/Niagara-Issues#1625]
**Describe the bug**
Whenever I play music through sonos I can't play/pause or skip a song with the media controls that appear on the home screen. Those controls work fine with Spotify.

**To Reproduce**
1. Play any song with the sonos app
2. Go to the home screen
3. Press any of the media controls
4. Nothing happens

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 pro
 - Android version: Android 11, also didn't work for Android 10.

_Let me take this opportunity to say: Thanks for the wonderful clean launcher!_

**Comment by 8bitPit** [comment]
Hey, thank you very much for reporting and your kind words :) It seems that this app doesn't support transport controls properly. Please contact the developers of your music app and ask them if they can support transport controls & implement proper media sessions (e.g., you can share [t​his](https://medium.com/androiddevelopers/understanding-mediasession-part-4-4-dcc77c535f99) Medium article).

**Comment by leonkielstra** [comment]
Thanks for your response! I'll send them a message, but I'm not very confident that they will care enough.

**Comment by 8bitPit** [comment]
Great! Fingers crossed that they'll do something about it.

**Comment by UrsKR** [comment]
2 years in, did anything about Android media handling change so you could improve the situation without Sonos changing their app, @8bitPit ?

For me personally, the situation would appear improved if you hard-block Sonos from appearing as a media app on the home screen. What do you think?
