### ISSUE TITLE
Adding a popup folder to hidden apps crashes Niagara and resets default launcher. 

### ISSUE THREAD

**Issue by shadeyg56** [8bitPit/Niagara-Issues#1626]
**Describe the bug**
I tried adding a popup folder to my app list and then adding it to hidden apps. This resulted in the whole launcher crashing and it was no longer my default launcher 

**To Reproduce**
1. Create a new popup folder in settings menu
2. Add the folder to app list/remove from favorites 
3. Go to settings and hidden apps. Add a new app and try to add the folder you made. 
4. Launcher will crash and no longer be default. 

**Smartphone:**
 - Device: Samsung Galaxy A10e
 - Android version: Android 10

**Comment by 8bitPit** [comment]
Thanks, @shadeyg56. We'll remove folders from the "Hide unused apps" screen.

**Comment by shadeyg56** [comment]
@8bitPit why not make folders hideable? What if somebody just wants to group all of their hidden apps into one folder?

**Comment by Oddward** [comment]
> @8bitPit why not make folders hideable? What if somebody just wants to group all of their hidden apps into one folder?

That's essentially what folders are currently good for, but instead of keeping them hidden they're consolidated to the bottom of the app list

**Comment by shadeyg56** [comment]
> 
> 
> > @8bitPit why not make folders hideable? What if somebody just wants to group all of their hidden apps into one folder?
> 
> That's essentially what folders are currently good for, but instead of keeping them hidden they're consolidated to the bottom of the app list

I mean it is a bit of a niche feature but then those apps would no longer be hidden. I guess it may not be worth the time to add though.

**Comment by 8bitPit** [comment]
@shadeyg56 for me the hidden category itself is like a folder. If you want to hide your hidden apps even more, you could try the following: https://help.niagaralauncher.app/article/111-remove-hidden-apps-from-search

**Comment by 8bitPit** [comment]
Anyway, the bug is fixed in v.1.3
