### ISSUE TITLE
Media playing notifications visible WITHOUT homescreen (app) notifications

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#1628]
**Is your feature request related to a problem? Please describe.**

I like my homescreen minimal and as decluttered as possible. However, the need for enabling homescreen notifications as mandatory for having media playing notification visible is disslike for me...

**Describe the solution you'd like**
Ability to show media playing on the homescreen without the need for homescreen notifications on (for favorited apps or any)

**Comment by 2zqa** [comment]
Quick workaround: I would suggest using a widget as a workaround for now.

**Comment by tjsuominen** [comment]
Unfortunately widget is not an option as I already have a widget in place and Niagara supports only one widget at a time.

**Comment by Montell2099** [comment]
Even though I personally don't utilize the media player in Niagara, I fully support the idea of separating these features.

**Comment by tjsuominen** [comment]
Yes, and it's not about the settings, it's about implementation. And Peter is very good on that! It's not a deal breaker for me (being premium user), but something I would definitely like to have in the future.

**Comment by 8bitPit** [comment]
Thanks, @tjsuominen :D I agree it doesn't make sense to have the user enable the notification feature for the player to be visible. We did this because the media widget is closely tied to Niagara's notification internally, but that shouldn't be affecting the user. I'll change this soon.

**Comment by tjsuominen** [comment]
That's great news to hear, all I have to do is to inpatiently wait :-)

**Comment by Montell2099** [comment]
Great news! I've been very excited about Niagara since the beginning, even more so after the pop-up feature got implemented recently.

I consider any update from here on out to be a complete luxury for us users, further improving on different QoL aspects, surely combined with some secret gems from the devs. 

Cheers!

**Comment by 8bitPit** [comment]
Implemented with v1.3 :)
