### ISSUE TITLE
Results from app search by alphabet are displayed too high on the screen to be easily reachable 

### ISSUE THREAD

**Issue by PemikM** [8bitPit/Niagara-Issues#1629]
When I search for app using the alphabet the first results are shown too high on the screen to be easily reachable using one hand. I always have to swipe a little bit down to tap on them. 

Possible solutions:
1) Move the results little bit down. 
2) Allow users to choose how high on the screen they want to see the result for the chosen letter. Like we can choose now how high we want to have the Niagara widget. 

![Screenshot_20210603-223646](https://user-images.githubusercontent.com/71567466/120717431-d0781a00-c4c7-11eb-8604-7cff223d4faf.png)

**Comment by 8bitPit** [comment]
Hi @PemikM 👋 I'm sorry, but we don't plan to add this feature this year: https://github.com/8bitPit/Niagara-Issues/issues/869
