### ISSUE TITLE
Round media player icons

### ISSUE THREAD

**Issue by Artt-ies** [8bitPit/Niagara-Issues#1630]
I think the music widget is a very well made as it suit the Niagara Neo font perfectly, which (for me) become a problem when using other fonts. Music widget play/pause, skip track buttons have a sharp edge which I think doesn't go well with fonts like open sans, product sans or Samsung sans. Making an option to enable a more traditional music widget design seen in most android phone should be a good solution to this problem.

Another thing about font is that I think there should be an option to disable font shadow, as it create too much effect and distraction thus distroy the simplicity of the home screen.

**Comment by 8bitPit** [comment]
Thanks for your suggestions, @Artt-ies. While we are not planning to add further customization options (https://help.niagaralauncher.app/article/44-feature-requests), we'll try out adjusting the media player's look and alter it.

**Comment by 8bitPit** [comment]
Implemented in v1.3, I hope you like the new design :D https://medium.com/niagara-launcher/a-healthy-home-screen-2c99e87651be

**Comment by Artt-ies** [comment]
@8bitPit hi, I just installed the beta today. The new design definitely looks much better. I also noticed dismiss box also got a round corner too, which make things even better.

**Comment by 8bitPit** [comment]
Great to hear that; thanks, @Artt-ies 😀
