### ISSUE TITLE
Bug on Chinese pinyin

### ISSUE THREAD

**Issue by LIETIAN183** [8bitPit/Niagara-Issues#1631]
**Describe the bug**
The app list identify Chinese character with multiple pinyin(prounciation) wrong.

**To Reproduce**
1. download app name "重生细胞"
2. The character "重" have two pinyin, "zhong" and "chong", but in "重生细胞" it should be "chong", however we can see this app in app list section "z", and it actually should be in "c"

**Smartphone (please complete the following information):**
 - Device: OnePlus 8
 - Android version: Android 11

**Screenshots**
![Screenshot_20210604-213717__01.jpg](https://user-images.githubusercontent.com/33315283/120812393-8ec09100-c512-11eb-8488-cc8964250271.jpg)

**Comment by LIETIAN183** [comment]
I tested another character with multiple pinyin, maybe the app don't have the ability to identify which pinyin is correct

**Comment by 8bitPit** [comment]
Hi @LIETIAN183, to romanize Chinese words, we're using Android's transliteration engine, which is not implemented by us, so we can't fix it without having to create our own system which would be too time-consuming, unfortunately. For the apps that are not transliterated properly I recommend applying this little workaround: Prepend the letter of the alphabetic section you want to see it in by renaming it: https://help.niagaralauncher.app/article/97-edit-app-icons-and-names. I hope this helps!
