### ISSUE TITLE
Unknown numbers

### ISSUE THREAD

**Issue by VolodymyrBryzh** [8bitPit/Niagara-Issues#1632]
**Describe the bug**
Unknown numbers on home screen.

**To Reproduce**
1. Install launcher
2. Do nothing
3. Wait a bit

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9C
 - Android version: Android 10 Q

**Screenshots**
![Screenshot_2021-06-05-15-37-25-090_bitpit launcher](https://user-images.githubusercontent.com/85398443/120891990-76389f80-c614-11eb-82ed-302f63ed71b4.jpg)

**Comment by Rod911** [comment]
Please see this article https://help.niagaralauncher.app/article/108-random-numbers
