### ISSUE TITLE
Remove quick access.

### ISSUE THREAD

**Issue by Ryder-Booth-000000** [8bitPit/Niagara-Issues#1633]
Many apps have unbearably long lists of quick actions that you access by swiping left. With the new wighets it would be nice to be able to remove these. I do not know if this is feasible but it would be nice.

**Comment by PemikM** [comment]
You can do it already if you have bought Pro version and you are using Sesame shortcuts. I am not sure whether you need payed version of Sesame too.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1600
