### ISSUE TITLE
Additional Favourites / Time based favourites 

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#1639]
**Is your feature request related to a problem? Please describe.**

The home screen is quite limited in terms of favourites which can be seen at one time

**Describe the solution you'd like**

While retaining its simplicity could you implement a way to swipe left or right to view additional favourites. 

Second feature it would be amazing if favourites could also change depending on time of day e.g. Favourites related to work show up from 9-5  and then change afterwards

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by Rod911** [comment]
See #165
