### ISSUE TITLE
Shortcuts.. 

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#1640]
**Describe the bug**

I use an app called Shortcut Maker and other than standard shortcuts it will allow you to create shortcuts to activities, intents within apps, has custom activities e.g. Incognito mode for chrome. Now shortcuts created do appear on the homescreen but I can't see a way to add them to a folder. 

Maybe not a bug but how can I do this? I just want a folder with these shortcuts rather than them sitting in my favourites 

Thanks 
**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by Rod911** [comment]
Long press the shortcut you created, select "Show in apps list", you can then edit your popup folder and be able find the shortcut in the apps list

**Comment by Lorestan00** [comment]
Thanks that's awesome
