### ISSUE TITLE
Pls add a widget for digital wellbeing.

### ISSUE THREAD

**Issue by k-bhatia2** [8bitPit/Niagara-Issues#1645]
**Is your feature request related to a problem? Please describe.**
It would be nice to swipe over the digital wellbeing icon (and using the widget in popup) and see the screen time etc.

**Describe the solution you'd like**
Samsung devices(OneUI) already has a digital wellbeing widget, need exactly that and I think niagara can make it happen.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by 8bitPit** [comment]
Hi @k-bhatia2, we might do that in the future but integrated the widget more into the launcher: https://github.com/8bitPit/Niagara-Issues/issues/1260. To quickly access screen time you can long-press any app inside Niagara Launcher and tap on "Screen time" on supported devices. Moreover, I recommend to install a third-party wellbeing app (like Action Dash) for a usage stats widget on your home screen.

**Comment by 8bitPit** [comment]
Merged with #1260
