### ISSUE TITLE
OFFLINE MODE - KILL SWITCH

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1648]
I belive that in order to increase the transparency of niagara launcher and afirm the trust of its users. It could be great to add an internet kill switch where the user decide if use Niagara's online services like weather (which I think is the only one that needs internet to function) or go fully offline.

I think that Niagara has been constructed in a way it could work fully offline without losing any functionality except weather info. 

![Screenshot_2021-07-01-16-28-59-327_ch icoaching typewise](https://user-images.githubusercontent.com/72170242/124199295-cda12280-da8f-11eb-89f3-95f047fe04d2.jpg)

![Screenshot_2021-07-01-16-39-22-093_bitpit launcher](https://user-images.githubusercontent.com/72170242/124197078-012d7e00-da8b-11eb-9054-d3b63691b0df.jpg)

Also, as you said "I can understand" and give the user the option to disable the data collection of "error and usage reporting." I think there is anything else more transparent that kill the internet connection and give the user the control over ther personal privacy. For many people's mind, what could be more private that give Niagara Launcher an offline mode. Where the user is sure its data isn't going out. As well, I'm sure the e will be lots of people who will still using online services. 

I'm sure that create an offline switch isn't difficult,  nor is it a problem. Also, it is a way to prove to the community your transparency and reassure many user. It will increase Niagara's popularity. 

I just wanna thank you for your hard work, and I hope you to understand my concerns, and I sure I'm not the only want. Many will thanks to have an option like this; I'll be anxiously waiting for your answer and sea your aproach towards this matter. Thanks again.

**Comment by 8bitPit** [comment]
An offline would unfortunately break our authentication mechanism for the Niagara Pro subscription and possibly future online features. Moreover, if I understand you correctly, you'd like to have an offline switch because of privacy. You can already disable all of Niagara Launcher's analytics with the method you shared above. If I added an offline mode button, you'd still have to trust me the same amount as before, it doesn't add any kind of guarantee that couldn't still collect your data if I had malicious intentions.

**Comment by Just-SKY** [comment]
The idea of the kill switch its because I can track every byte an app use, but I didn't thought about authentication mechanism specially the subscriptions. 
Also, I would like to know if the data of the wellbeing initiative is something proper of Niagara, or it is collected through Google's digital wellbeing.

**Comment by Oddward** [comment]
You could remove the app's access to the internet (Permissions) if you wanted to ensure it's offline, no?

And the initiative is Niagara's own analytics I believe (that's why they can detail what they do and don't collect) 🤔

**Comment by Just-SKY** [comment]
Yeah that's right I could restrict the internet access of an app; however, you'd surprise how many apps bypass those restrictions many times. That's way I trust in a few amount of apps, and Niagara is one of them because the transparency they've shown.

**Comment by Just-SKY** [comment]
Apart of my previous question "if the data of the wellbeing initiative is something proper of Niagara, or it is collected through Google's digital wellbeing." I would like lo know. For example, If by the use of the notification summary, a persona is automatically participating in the wellbeing program. Because it caught muy attention the descripción of the feature. 

![Screenshot_2021-07-11-11-22-30-086_bitpit launcher_1](https://user-images.githubusercontent.com/72170242/125204411-6a0ab800-e23a-11eb-8cf1-15202972ce71.jpg)

If it is not, I think that it can create confussion for many users who are not into the digital wellbaing initiative. I think that if the feature is not related, it would be better to create a clearer description (description and functionality of the feature itself) which does't mix the 2 topics (the feature itseft and digital wellbeing initiative). A not clear description could discorage its usage, because poeple could think that its mere use could be count as an automatic participation. 

However, if the use of that feature is counted as a participation of the wellbeing initiative. I think it could be seen as a bad move by many people, who could think that is forced way to make them participate in the program if they want to use new useful features. 

I mention this as an observation because I believe that a bad description could lead or create misunderstandings. 
As well, it's important to make it clear to user, so they can decide if use it not knowing the implications it has. 

As well that I would like to know personally, if they have relationship or not. 
Keep the great work.

**Comment by Oddward** [comment]
@Just-SKY as far as I can tell the initiative is a separate feature with its own setting in Niagara settings. Users are asked directly if they wanna enter the initiative, regardless of whether they use the Notification Summary or not (my phone is too old to support the summary feature but I can enter the initiative), no one is automatically entered

Anyone who enters can also opt out or request their data via *Niagara settings > Advanced > # Analytics > Digital Wellbeing Initiative* 


The description is to say that the feature is not in a final release stage, more of a beta, which suggests there could be more digital wellbeing features later, including or replacing Notification Summary

**Comment by 8bitPit** [comment]
Yup, @Oddward is right. The feature doesn't enable the analytics of the Digital Wellbeing Initiative.
