### ISSUE TITLE
Apps with notifications visible on the main screen?

### ISSUE THREAD

**Issue by coffinshaker** [8bitPit/Niagara-Issues#1649]
**Is your feature request related to a problem? Please describe.**
Could there be an option so all applications that receive a notification show up on the main screen below the favorite apps?

**Describe the solution you'd like**
If the notification is dismissed, the application disappears from the list. That would be somewhat similar to the media player apps that show up on top when there's a bluetooth sink connected.

An example would be a YouTube app which I don't have in favuorites, but I would like to see and dismiss any notification about new video without going to the status bar.

**Comment by 8bitPit** [comment]
Thanks for your suggestion, something along the lines is planned :) https://github.com/8bitPit/Niagara-Issues/issues/152

**Comment by 8bitPit** [comment]
Merged with #152
