### ISSUE TITLE
Better weather API

### ISSUE THREAD

**Issue by BanthaFood** [8bitPit/Niagara-Issues#1652]
I've experienced that the weather forecast/icon integrated into the homescreen isn't really accurate. E.g. it's raining and the icon shows sunshine.

For me in Germany WetterOnline (weather&radar in other countries) has proven itself to be the most reliable weather app. I've looked it up and they offer API implementation, too. I don't know how good it is in other countries. Maybe someone has experiences with that or a better alternative.

**Comment by Maxr1998** [comment]
While we would love to support more localized weather providers, it would imply a disproportionate amount of effort. Open Weather, the provider that we're currently using, offers a reasonable data quality world-wide, in one API. It's unlikely that we'll add more weather providers in the near future, so I'll close this issue for now, but will update it if our stance ever changes.
