### ISSUE TITLE
widget bug 

### ISSUE THREAD

**Issue by rraammiinn** [8bitPit/Niagara-Issues#1653]
- Device: samsung galaxy j3
 - Android version: 5.1
--------------------------------------------------------------------------------
when I reset my phone widgets turn to some digits. 
--------------------------------------------------------------------------------
![Screenshot_۲۰۲۱-۰۷-۰۴-۰۱-۲۵-۰۱](https://user-images.githubusercontent.com/67558318/124366722-f7607200-dc66-11eb-9554-609678c5e821.png)
#

**Comment by 8bitPit** [comment]
Please refer to this article: https://help.niagaralauncher.app/article/108-random-numbers
