### ISSUE TITLE
Bug: keyboard stays open after swiping on G button

### ISSUE THREAD

**Issue by lepa22** [8bitPit/Niagara-Issues#166]
Open an app, then return to the home screen.
Swipe app on the G button to open Google search. Keyboard opens as it should.
Then press the home button. Google search closes, but keyboard stays open.
If you reopen Google search without running another app and press home, keyboard closes normally.

I'm using a Samsung Galaxy J5 2016 with SwiftKey beta keyboard.

**Comment by BluDragyn** [comment]
Stays open for me on both my Galaxy S9 Plus (stock, 8.0) and Motorola Nexus 6 (Carbon ROM, Pie beta)

**Comment by jakcharvat** [comment]
Able to recreate. GBoard, Android 8.0, Galaxy S8. Video coming

**Comment by jakcharvat** [comment]
See #151
