### ISSUE TITLE
Double tap anywhere on home screen to sleep the screen

### ISSUE THREAD

**Issue by iamSRQansari** [8bitPit/Niagara-Issues#1663]
People like me always wants everything to be done from the screen itself without clicking any hardware button. almost every launcher supports double tap on home screen to sleep the screen feature. 
It would be great if you can add a gesture detector on home screen to detect **Double Tap** and as it detects double tap it should **Sleep** the screen.

**Comment by 8bitPit** [comment]
Hi @iamSRQansari, we already added this feature for Android 9 and rooted devices, hope this guide helps: https://help.niagaralauncher.app/article/73-lock-screen-on-older-android-versions
