### ISSUE TITLE
Can't disable notification summary

### ISSUE THREAD

**Issue by joaquim-verges** [8bitPit/Niagara-Issues#1666]
**Describe the bug**
I ran into an issue with notification summary which made me want to disable it to verify that was the cause (google assistant reminder notifications not showing). But when I tried to disable it, tapping the toggle to turn it off instead opens the bottom sheet to configure it, with no way to turn the entire feature off.

**To Reproduce**
1. Enable notification summary
2. Try to disable it

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android version: 11

**Screenshots**
![Screenshot_20210716-182126.png](https://user-images.githubusercontent.com/3353417/126021180-d63f24c2-beba-48fa-bf1c-411e3c2da0de.png)

**Comment by Just-SKY** [comment]
If you want to disable the notificación summary, you have to delete or uncheck the apps that you selected for your notification summary. When the notification summary is empty, it disable itself automatically. 

1 
![1](https://user-images.githubusercontent.com/72170242/126021863-9bfacb5a-903a-453e-a67e-4087494afd20.jpg)
2
![3](https://user-images.githubusercontent.com/72170242/126021872-088ee3c5-947f-48ad-8ab2-142405c49c11.jpg)
3
![2](https://user-images.githubusercontent.com/72170242/126021875-7c092253-6480-4b3a-8fdb-91893b8b8f5f.jpg)

**Comment by joaquim-verges** [comment]
Thank you! Missed that. UI didn't make it clear

**Comment by Rod911** [comment]
Closing as issue is resolved, reopen if necessary.
