### ISSUE TITLE
Bug: Can't pause music with music control buttons.

### ISSUE THREAD

**Issue by akastanis** [8bitPit/Niagara-Issues#167]
The play button doesn't change to a pause button when music is playing.

Using stellio player.

**Comment by 8bitPit** [comment]
Is it only a visually bug or is your song still playing as well?

**Comment by akastanis** [comment]
The song is still playing.

**Comment by tiniwings** [comment]
Same issue here with Poweramp player.

**Comment by Montell2099** [comment]
It seems this "now playing" feature is more or less buggy regardless of music app. An option to hide it would be nice in the meantime, until these problems are sorted out.

Thank you for your great work!

**Comment by Bullnados** [comment]
Musicolet is working fine.

**Comment by 8bitPit** [comment]
Needs to be fixed by the music app developer, see: https://niagaralauncher.helpscoutdocs.com/article/11-media-player-widget-issues
