### ISSUE TITLE
Full day event not shown

### ISSUE THREAD

**Issue by coffinshaker** [8bitPit/Niagara-Issues#1670]
**Describe the bug**
The full day event from the next day is not shown along the date and weather.

**To Reproduce**
1. Set a full day event in the Google Calendar
2. It doesn't appear on the main screen on the preceding day.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 10 III
 - Android version: 11

**Screenshots**
![image](https://user-images.githubusercontent.com/15804477/126164941-fdf15a13-3d67-40e4-8bcd-746a0133f0e0.png)
![image](https://user-images.githubusercontent.com/15804477/126164989-0b2a2d1a-e897-4c0c-b11a-22020b589b7a.png)

**Comment by 8bitPit** [comment]
Hey @coffinshaker, we only show all-day events for the next day a few hours before the next day starts to not "spam" your home screen with calendar events.

**Comment by coffinshaker** [comment]
I understand it. Now when it's 23:00 I indeed see it. Is there any chance to make it configurable in the future?

**Comment by 8bitPit** [comment]
I'm sorry, but we currently don't plan on making this customizable.
