### ISSUE TITLE
Custom Widget keeps going blank.

### ISSUE THREAD

**Issue by pcebo** [8bitPit/Niagara-Issues#1672]
**Describe the bug**
My custom widget keeps turning into a blank, translucent rectangle. I'm in s21 ultra. Custom widget app is "Canada weather". "Replacing the widget" fixes it... Until the next time, that is. Unsure of trigger/steps to reproduce, but happens daily, it seems.

**To Reproduce**
1. Add a custom widget.
2. ??? Wait 1 day
3. Observe blank widget.

**Smartphone (please complete the following information):**
 - Device: s21 ultra 5g
 - android ver 11

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.
This is expected behavior...
![Screenshot_20210722-173511_Niagara Launcher](https://user-images.githubusercontent.com/7888117/126833399-6aaa37b4-cb7c-4b95-a81a-57cefe459412.jpg)

And this is what it reverts to... Daily.
![Screenshot_20210723-154300_Niagara Launcher](https://user-images.githubusercontent.com/7888117/126833449-82ab5eb1-5218-4e02-9b9c-e86a0f632f32.jpg)

**Comment by 8bitPit** [comment]
Thanks for reporting; we'll roll out a fix soon: https://github.com/8bitPit/Niagara-Issues/issues/1671
