### ISSUE TITLE
Direct sync from google account for agenda widget

### ISSUE THREAD

**Issue by k-bhatia2** [8bitPit/Niagara-Issues#1675]
Hey, I'm a niagara pro user. I'm using a xiaomi phone which comes with a built in calendar app which has significant lag in syncing with my google Calendar. The issue is that the niagara agenda widget is dependent on that xiaomi calendar (even when I have google Calendar app installed) I'd be really nice if niagara agenda becomes capable of connecting to my google account directly and sync events. A live example is "one calendar" (you can find it on play store). A seemingly small issue...but will really appreciate if a solution to this is povided.

**Comment by 2zqa** [comment]
I don't believe it uses any calendar app at all. I'm guessing Xiaomi Calendar app is actually the "correct one", representing what the calendar providers are well, providing. As for fixing that issue, I'm not entirely sure. But this sounds like a bug that Xiaomi should fix (aggressive battery saver, if I were to guess), not Niagara Launcher.

**Comment by Rod911** [comment]
Niagara uses the Calendar API of the Android system and not the calendar apps to show the events, I'd recommend increasing the sync frequency of the calendar from your settings.

**Comment by Maxr1998** [comment]
The lag is, as you said, an upstream issue, so not possible to fix for us.

Building our own calendar synchronization would be a lot of work (authentication, network requests, caching) that's out of scope for the launcher, so not something we'll provide.
