### ISSUE TITLE
Appearing and disappearing music or streaming apps

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1676]
I love how my apps (music and streaming) appear when I connect my earbuds, headphones, etc. It is a very good way to keep my homescreen clean because those apps just appear when needed. 
The problem is that all those apps are always active on my homescreen while I have my earbuds connected. 

I think it would be great if those selected apps collapse as soon as the music start playing, and the same apps reappear again when the music is paused or stopped. 

It is unnecessary to have those apps active, because users can olny use 1 app at the time, and they can enter that app through the media witget while active (without the necessery to enter through the app). If the user want to use or chance to a different music or streaming app. He/she can pause the music, and when the apps appear again. The user can select other app of his/her preference. 

It is a good way to keep the homescreen clean and save space because many times users have many apps that take so much space when they have their earbuds connected without losing such a great feature. 

I think it would fit perfectly Niagara's philosophy.

**Comment by 8bitPit** [comment]
The problem I see here is that this will irritate users why their apps are going away even though the device is still connected. Moreover, the user might not use the section exclusively for media apps. For example, a fitness app appearing on the home screen comes in handy while starting a run or a navigation app while driving. Those apps would also disappear after starting the music app, which seems counterintuitive. To fix your issue, I recommend creating a folder in your media apps section. That way, you can declutter your home screen. I hope this helps!

**Comment by Just-SKY** [comment]
I didn't think about the possible issues, and I just thought about possible ways to reduce distractions. Feel free to close it.
