### ISSUE TITLE
Gesture navigation swipe up in app list or search should return me to favorites.

### ISSUE THREAD

**Issue by ceiphr** [8bitPit/Niagara-Issues#1677]
**Is your feature request related to a problem? Please describe.**
Whenever I am in Niagara search or the app list, I swipe up on the gesture navigation bar, assuming it will return me to my favorites list. Currently, swiping up in search or the app list will keep that activity open instead of returning to favorites.

**Describe the solution you'd like**
Swipe up should return me to favorites.

**Comment by PemikM** [comment]
Do you mean the Android gesture swipe from the bottom? It actually works, but you have to make a really tiny swipe. Which makes it not very useful. I wish it would work better too.

**Comment by ceiphr** [comment]
> Do you mean the Android gesture swipe from the bottom?

Yes. Thank you for telling me about the tiny swipes. That does work.

Hopefully the devs will get this implemented for any swipe up.

**Comment by notepadnine** [comment]
currently it shows recently installed items

**Comment by 8bitPit** [comment]
You cvan swipe down to go back to the home screen from search. I hope that helps!

**Comment by ceiphr** [comment]
It sort of helps to know this, but it doesn't seem convenient to swipe down, especially when there are scrollable contents on the page. The Pixel launcher supports this functionality.

**Comment by Oddward** [comment]
Swipe up to search plus swipe down to go back home is a pretty natural set of gestures - it's bringing the kb up and pushing it back down - useful for Search coz most of the bottom region is occupied by the keyboard. Both gestures only work if "swipe up to search" is enabled

Having it for the app list too sounds like more inconvenience for others than convenience 🤔

**Comment by Oddward** [comment]
I don't think this issue needs to stay open since it's not exactly a problem or enhancement and discussions have stopped. 

FYI, you can swipe down anywhere or swipe from the right edge (back gesture) to go back home. Let us know if anything's up
