### ISSUE TITLE
Swipe up app searches 

### ISSUE THREAD

**Issue by TheSatman01** [8bitPit/Niagara-Issues#1679]
If the search result lists only 1 app why not automatically open it? That would be awesome if you could do that.

**Comment by Rod911** [comment]
Pressing the search icon on the keyboard opens the first result, irrespective of the number of results. Opening the result automatically would be unhelpful if you need to change your search query.

**Comment by TheSatman01** [comment]
Nonsensical reply as my comment was regarding 1 search result remaining and automatically opening it thereby reducing actions ie having user pressing another key.

**Comment by Rod911** [comment]
Just because there's only one result remaining doesn't always mean you'll want to open that result.

**Comment by 8bitPit** [comment]
I share my sentiments with @Rod911. If we improve our search screen and add web suggestions, there will rarely be one result anyway.

**Comment by Amorphous404** [comment]
🔗 Mergred with #1911
