### ISSUE TITLE
[Feature Request]: Partial open sourcing

### ISSUE THREAD

**Issue by AZMCode** [8bitPit/Niagara-Issues#1680]
It could be useful to open-source this project to help find bugs, accept code contributions from the open source community, and perhaps even list this launcher on F-Droid.

Now, I'm aware that this launcher has paid-for features, and I understand these must remain closed source to stay an effective source of income for the project, however there are open-sourcing options that could coexist with the current revenue model.

For example, the main launcher could be released under a strong copyleft license like GPL to ensure no one else can make money off of the main launcher code, while allowing possible community pull requests and forks. The paid features of the app could be delivered through a closed-source extension to it, perhaps even opening up a third-party extensions API.

While this is certainly not the only option to partially open-source the launcher, as many other models, and perhaps even a custom license could be used, I believe it should be an option worth considering at least.

**Comment by ceiphr** [comment]
I have a related suggestion:

Abstract key parts of Niagara and open source those components. 

Examples: Open source the alphabet component or pop-up component under MIT. Sure, other projects can use the components, but they can't copy Niagara's implementation. 

If those components become popular, contributions can help make them more robust and efficient.

**Comment by sandeshdroid** [comment]
I believe hiring more employee to speed development is better for dev. If dev is abandoning project then open source would be option.

**Comment by AZMCode** [comment]
> I believe hiring more employee to speed development is better for dev. If dev is abandoning project then open source would be option.

Why not both? There are plenty of commercial open-source projects with paid employees.

**Comment by 8bitPit** [comment]
I'm sorry @AZMCode, but we don't plan to open-source it anytime soon, please refer to this ticket: https://github.com/8bitPit/Niagara-Issues/issues/180.
