### ISSUE TITLE
Hide Niagara's (Pro - Settings) icons

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1682]
I think that it's unnecessary to keep Niagara pro option when a user is already pro user.

Also, It would be great to have the opportunity to hide or eliminate  the settings of Niagara launcher of the main list of apps. I think that they add more space, and it is something that rarely a user use when niagara is already adjusted. Instead, Niagara's settings could appear when the user trigger the "**search app**' option or eliminate it from the app list. Users can enter Niagara's settings using long press option. 
![1](https://user-images.githubusercontent.com/72170242/128888848-535de7a8-2a2b-45e0-89ab-0f51b1e54e3b.jpg)

The point is to hide something which is not often used, and it's not necessary to be always there. 

![Screenshot_2021-08-07-20-02-35-044_bitpit launcher_1](https://user-images.githubusercontent.com/72170242/128619083-68e7eae9-c1e9-44ea-9210-ad5d91173ba3.jpg)

**Comment by sandeshdroid** [comment]
It is already hidden for pro user altest for me.

**Comment by Just-SKY** [comment]
That's weird cuz I've been a pro user for quite some time, and it has never disappeared. Now, I dont if it's a bug.

**Comment by Oddward** [comment]
Ya the Niagara Pro button should not be there for any verified pro user. If there's no issues verifying Niagara's license via Google Play Services on your device then maybe it's a bug, although it's the first I've seen this mentioned. Does it show the content normally with no errors when u go to _Niagara Settings_ > _Niagara Pro_ ?

The button at the bottom of the list shouldn't rly affect any user even if they're not using it. It does server to show users that don't use the long-press a way to access the settings though, which is a fairly common thing to open (to change icons/theme/wall, check version, restart launcher if it gets bugged, go to community channels etc). The idea to customize it wasn't rejected, but it's low priority I guess

**Comment by Just-SKY** [comment]
Yeah I'm pro user, so everything works as intended and no errors. Just the normal bugs that everybody faces. I bought it normal via Play Store. 

      About the other thing, I get that it should not affect the users. However, I don't see why there are 2 ways for Niagara's settings. I believe that the settings in the main list of apps is unnecessary because it is so easy to enter the settings through long press (everywhere)  which is already implemented. It is better to keep the most discreet one, and It will make it cleaner (by just keeping the apps)

     I believe that if you give to many options for the same thing, it will make the app somewhat messy. If you give users just one option, I'm sure they will get used to it.), though it is my humble opinion.

**Comment by notepadnine** [comment]
It is so relaxing not seeing niagra pro option in setting menu after purchasing.

**Comment by Oddward** [comment]
@Just-SKY many users may not know they can long-press to access Niagara settings, in which case they would scroll through the alphabet and access it that way. It might also be faster for some to use the alphabet instead of long-press (alphabet is instant)

I'm dunno if it's unnecessary or not

A lot of things that seem intuitive to us don't seem that way to others, I see a lot of users asking for help for stuff that's right in the long-press menu

______
I would think you shouldn't give your phone to people who accidentally tap stuff or are malicious 😅

**Comment by 8bitPit** [comment]
Hi @Just-SKY 👋 The "Niagara Pro" button shows up if you either didn't unlock Niagara Pro or if your subscription does not renew; have you perhaps canceled your subscription? About showing the settings in the list: Yes, that is redundant but similar to Android which lets you open the system settings from the notification shade and from the launcher's app list/drawer, we also show our settings in multiple locations to make it easier finding them.

**Comment by lezsakdomi** [comment]
For me it shows up even though I have a renewing subscription:
![Screenshot_20210924-081457_Niagara_Launcher](https://user-images.githubusercontent.com/8544161/134627214-f7b80d62-3e35-4b09-ba17-290c8043c87b.png)
![Screenshot_20210924-081510_Niagara_Launcher](https://user-images.githubusercontent.com/8544161/134627222-eee2b5fb-2794-4a58-b520-dbb3bcd9bb40.png)
![Screenshot_20210924-081516_Google_Play_Store](https://user-images.githubusercontent.com/8544161/134627231-5eb2cf5f-0e4f-4b3f-86e3-cc9c25da2e79.png)

**Comment by akanjans** [comment]
I once made a similar request to the one here (in a different ticket: https://github.com/8bitPit/Niagara-Issues/issues/1985)

My request is a little bit different but seems better placed in this threat: could you hide  the entire Niagara Launcher section (incl settings and recently installed apps) when viewing the main app list or Pop-up folders section?

When I navigate towards the "Pop-up folders" section (diamond icon), I am annoyed by the Niagara Launcher section that shows underneath. I have hidden all apps and have organized them in pop-up folders to create a super clean UI. But whenever I now view those pop-up folders, the cluttery Niagara Launcher section unnecessarily shows underneath. 

Note that I am not asking to remove the "Niagara launcher" section. I would ask for the Niagara Launcher to still be available, but only when you actively navigate towards the Niagara launcher section at the bottom of the alphabet (dot icon).

I hope you're willing to consider this change.
