### ISSUE TITLE
Niagara Dots 

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1683]
I decided to give niagara dots a try, and I'm really enjoying them a lot more than what I thought. 
The problem is that there are some icons that don't change, and to be more specific some apps' **shortcuts** are ones that do not change. 
![1_1](https://user-images.githubusercontent.com/72170242/128658722-3241ae93-3c4d-4424-9050-bef9a512503f.jpg)
The image shows that I applied the Niagara dot, but they don't change. 
![2](https://user-images.githubusercontent.com/72170242/128658904-333e4528-25e4-46b2-91bb-8a3f92195fa2.jpg)
In addition, I have to tell personaly that the idea works because there is anything that catch my attention, I feel that my usage has decreased in some degree. 
I need the manual color change cuz the dots cannot be used with all wallpapers. 

Xiaomi - miui12 - androide 10

**Comment by Oddward** [comment]
Custom icon packs do not apply to the default shortcuts atm, it's not a bug. I think it was to ensure that they look alright inside pop-ups regardless of the user's setup. 

If you want to customize a shortcut you'd have to add it to your app list or pop-up manually first, and then if you wanted to you could add it into that pop-up again & hide the original shortcut with Sesame 🙃 - it's not ideal but it works for those who really need to customize. 

_P.S. Sesame might keep bringing the original shortcuts back randomly unless you blacklist that app_

**Comment by Just-SKY** [comment]
Ok, I get it
