### ISSUE TITLE
Highlight or a notification of new apps.

### ISSUE THREAD

**Issue by TiagoOz** [8bitPit/Niagara-Issues#1686]
Many times when we have several apps installed and we end up downloading some others it is a little difficult to find these new apps. 
So I believe an improvement would be to highlight or have a notification about these newly installed apps.

**Comment by sandeshdroid** [comment]
Swipe up from buttom. New app will be at top.

**Comment by TiagoOz** [comment]
OMG I didn't realize it, thank you
