### ISSUE TITLE
Deleting fonts opens a new 'font-tab' every time, overlaying the previous ones

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#1687]
https://user-images.githubusercontent.com/43126233/129625971-dab2167a-ffff-4332-9639-6cb94705d40c.mp4

I guess this screen capture speaks for itself.

**Comment by 8bitPit** [comment]
Max fixed that in v.1.4.0 or v1.4.1, I can't remember 😅

**Comment by Montell2099** [comment]
> Max fixed that in v.1.4.0 or v1.4.1, I can't remember 😅

That sounds great! Thanks for your response.

**Comment by Montell2099** [comment]
> Max fixed that in v.1.4.0 or v1.4.1, I can't remember 😅

I just tested out ver. 1.4.1, and the problem with multiple font-tabs opening is now gone, but after removing a font the font-tab doesn't seem to refresh and still shows the removed font until you manually close & open the font-tab yourself.

**Comment by 8bitPit** [comment]
I see, thanks for the second report :D
