### ISSUE TITLE
Duplicate text/element glitch when returning to Niagara

### ISSUE THREAD

**Issue by rohan1269** [8bitPit/Niagara-Issues#1690]
https://user-images.githubusercontent.com/80900420/130042442-48ba0b0c-6d90-4ac3-9e40-88695ed59d2c.mp4
I updated Niagara launcher recently and this is happening when I unlock my phone

**Comment by Maxr1998** [comment]
The duplicated texts definitely shouldn't happen. I also had that already, but a launcher restart fixed it. I'll investigate.

**Comment by Maxr1998** [comment]
Duplicate of #1804. Merging into the newer issue since there are more details collected there.
