### ISSUE TITLE
Remove bouncing effect on home screen when swiping down for notifications panel

### ISSUE THREAD

**Issue by itssandeepd** [8bitPit/Niagara-Issues#1691]
**Is your feature request related to a problem? Please describe.**
This is indeed a minor inconvenience like the swipe down might not register when trying to swipe down the notification panel. 

**Describe the solution you'd like**
So at rest if there is no more possibility of scrolling down ghe favorite app list, the bounce effect should be removed so that the swipe down for notifications panel gesture will get registered.

Please remember: a feature should be...
*Simple* · Easy to configure and easy to use. As few settings & toggles as possible.
*Impactful* · Either appealing for many or necessary for some.
*Universal* · Has to work everywhere: in every country, on all phones.
*Independent* · Doesn’t add complexity if it’s not being used.

**Comment by heytherewill** [comment]
+1. I don't remember this being an issue before, but since I updated to Android 12 this has become the major annoyance of this otherwise flawless product

**Comment by 8bitPit** [comment]
I'm glad to tell you that the bounce effect doesn't interfere with the notification gesture. I hope this guide helps in opening the shade more easily: https://help.niagaralauncher.app/article/98-notification-gesture
