### ISSUE TITLE
App Closing Animation Incorrect - Android 12

### ISSUE THREAD

**Issue by Fosmos** [8bitPit/Niagara-Issues#1692]
**Describe the bug**
The correct closing app animation no longer shows on android 12 (it does maybe the first few frames but doesn't do the fancy bit with the app icon, so the window just shrinks and fades away)

**To Reproduce**
1. Get a phone with Android 12 installed
2. Open an app that's also on the home screen (when you'd expect the animation to work)
3. Minimize it using the home button/gesture

**Smartphone (please complete the following information):**
 - Pixel 4a
 - Android 12 (SPB4.210715.014) but it was present also on beta 4.1 (That's when I joined the beta so I'm not sure if it was present before then)

**Video**
https://user-images.githubusercontent.com/59673626/131121119-9bc72d23-244d-41e1-be44-b171b621419a.mp4

**Comment by 8bitPit** [comment]
Thanks for reporting @Fosmos :) Unfortunately, this change was done by Google, and we don't have any control to change this. We'll forward this ticket to Google (via https://issuetracker.google.com/).

**Comment by asavill** [comment]
@8bitPit Can you link the issue you raised with Google so we can engage with it for visibility. Disappointed they've borked this animation again.

**Comment by Maxr1998** [comment]
We've decided to close issues that are blocked by external parties since there's no short-term possibility for us to fix them and we want to focus our attention on other reports.

**Comment by Fosmos** [comment]
Any updates on this issue? (I know Android 13 just launched the other day ahead of its anticipated date)

**Comment by Amorphous404** [comment]
> Any updates on this issue? I know Android 13 just launched the other day ahead of its anticipated date, so no rush. Just curious seeing as the last update on the Google issue said there should be something new in Android 13 and Launcher3.

You can try the latest Niagara version 1.8.5 and check if the new animation works on your device :)

**Comment by Fosmos** [comment]
Yes, I started using it again when 1.8.5 was released and was happy to see it working again 😄 It doesn't look 100% correct in all scenarios but at least its working (and maybe I'm just too picky), so good stuff!
