### ISSUE TITLE
Custom font not working with large size font file

### ISSUE THREAD

**Issue by fangqiuming** [8bitPit/Niagara-Issues#1695]
**Describe the bug**
When nigara open some large size (>8MB) font file, "not a valid font file" toast will present.
Fonts in some language usually break this limit (if exists).

**To Reproduce**
Niagara Launcher 1.3.6 Play Version with Niagara Pro
Use these fonts for testing:
https://fonts.google.com/specimen/Noto+Sans+SC#standard-styles
Only NotoSansSC-Thin.otf (7.82MB) works.

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - Android version: Android 11

**Screenshots**
![photo_2021-08-29 04 20 35](https://user-images.githubusercontent.com/12030413/131230144-0176122d-4a75-4937-84bd-cf1e9c382f0e.jpeg)

**Comment by tenhow** [comment]
the same problem, cannot add Microsoft yahei

**Comment by 8bitPit** [comment]
Fixed in v.1.5
