### ISSUE TITLE
Notification Summary By Channels 

### ISSUE THREAD

**Issue by mateo0023** [8bitPit/Niagara-Issues#1696]
It's a very simple request. I love the notification Summary feature on Niagara. However, it's missing the option to select only certain notification channels for an app to be on a summary. For example, soccer apps have notifications for match updates as well as news articles. The ones for the match updates are "urgent" and I'd like to not be sent to my summary. 
Another example would be Instagram (or other social media) I'd like to send the update notifications (the ones meant to raise engagement) to the summary while still receiving messages in real-time

**Comment by Maxr1998** [comment]
Good point, this is already tracked in #1685 however. Please subscribe there to receive updates.
