### ISSUE TITLE
Your Agenda > My Day

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#1698]
### Is your feature request related to a problem?

No a problem, but a visual improvemet.

### Describe the solution you'd like

Replace the description of "Your Agenda" with "My Day" as there is also weather info (and perhaps something else in the future) included. It's mine, not yours ;-)

**Comment by Maxr1998** [comment]
The way we understand it, Niagara serves as your personal assistant giving you an overview over your day - and we generally don't use the first person in the app.
I suppose it's a personal preference thing, I'll bring it up to discuss internally though.

**Comment by tjsuominen** [comment]
Good justification and point taken, thx.

Great that you bring that to the table. Same kind of discussion / user feedback has been around 'Your phone' app naming on Windows.

**Comment by Maxr1998** [comment]
We've decided to keep it as is now, thus I'll be closing this issue. Hope that's ok for you :smile:

**Comment by tjsuominen** [comment]
Well, I'm not calling a riot due to this 😂 still i would like to keep my viewpoint as a better one.
