### ISSUE TITLE
Customize google feed button

### ISSUE THREAD

**Issue by Srithesh-17** [8bitPit/Niagara-Issues#1699]
### Is your feature request related to a problem?

No,not a problem... it's more like a feature request..but it's just improvising current feature.

### Describe the solution you'd like

Someone like me doesn't really look google feed..like never...but i like that google feed button being on my home screen...so, I'd suggest u to let us customize that button(like option to add any quick actions or something like that).
Thanks:)

**Comment by 8bitPit** [comment]
Your wish is my command :D https://help.niagaralauncher.app/article/116-niagara-button
