### ISSUE TITLE
Option to hide scrollbar/alphabet

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#17]
An options toggle for not showing the scrollbar in the "favorite" section

**Comment by Chaphasilor** [comment]
Do mean literally just hiding it? But that it still works? Or disabling it so that you first have to "open" the app drawer and then can scroll like normal? I think I'd prefer the second one, it would make it more intuitive and limit accidential navigation!

**Comment by 8bitPit** [comment]
Just hiding it, you can try it out for yourself by updating the launcher.

**Comment by 8bitPit** [comment]
If you don't like the idea, just post a comment.

**Comment by Chaphasilor** [comment]
It definitely looks cleaner! I just would love to be able to swipe up to start scrolling down, without having to touch the sides...

**Comment by 8bitPit** [comment]
But then you always go to the top of your apps and you’re are not right where you want to be.
