### ISSUE TITLE
Notification Indicator

### ISSUE THREAD

**Issue by singhalritik1112** [8bitPit/Niagara-Issues#1701]
### Is your feature request related to a problem?

The way launcher presents notifications on homescreen is good but feels a bit cluttered if instead of showing a part of notification near app it would be much uncluttered if it only shows a indicator or a dot rest we all have to just swipe it to reveal it!

### Describe the solution you'd like

I want you to implement notification Indicator instead of just revealing a part of that notification it's both cluttered as well as against privacy

**Comment by Oddward** [comment]
As far as I understand, if you disable Notification Dots in your system settings it disables the notification previews while keeping the embedded notifications in the pop-ups. Not sure if it shows any indicator (I don't have notification dots feature)

**Comment by 8bitPit** [comment]
Thanks for the suggestion. While we don't plan on adding this option (https://github.com/8bitPit/Niagara-Issues/issues/800) on some OS's you can switch notification dots individually as @Oddward recommended: 
![file-uFyndBH2g8](https://user-images.githubusercontent.com/9284845/134334808-af8f4c0f-39eb-4cbc-ae73-5b1adf471954.png)

**Comment by ndremir** [comment]
![IMG_20240410_092043](https://github.com/8bitPit/Niagara-Issues/assets/128324996/b959692c-3ce9-4fb7-b6c7-c7aad176bda6)
There may be a circle or a line above the application list.
