### ISSUE TITLE
Returning to default launcher

### ISSUE THREAD

**Issue by jlsdlygith** [8bitPit/Niagara-Issues#1702]
### Describe the bug

There are random times when I click on back, it goes back to the default launcher. For example

1. Changing wallpper using "Stokie"  app.
2. When I tap "arrow back" on some apps. 

I have already set this App as the default launcher. If ever it goes back to the default launcher, I press the home button and it goes back to Niagara launcher. 

### Steps to reproduce

1. Changing wallpper using "Stokie"  app.
2. When I tap "arrow back" on some apps. 

There are times I can't replicate the issue, but these are what I have experienced. 

### Device name

Huawei Nova 5T

### Android version

Android 10

**Comment by Oddward** [comment]
This kinda thing used to happen on some systems which would reset the default launcher often. Android 10 was when 3rd party launcher support was the worst coz Google just changed how stock launchers worked for the sake of gesture navigation & it caused a lot of compatibility issues

I don't think Niagara can do anything about this, should be on the system side to be updated. Or did it start after some update?

Similar to Samsung OneUI you can try setting default through Niagara's prompt, plus going to settings & manually setting default launcher to Niagara

**Comment by notepadnine** [comment]
ALL HEUAWEI MOBILE HAS THIS PROBLEM, IRRESPECTIVE TO LAUNCHER IT HAPPENS TO ANY OTHER DEFAULT APP

**Comment by 8bitPit** [comment]
Yeah, this is not in our control, unfortunately: https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default
