### ISSUE TITLE
No fade on bottom of the app list when using gesture navigation

### ISSUE THREAD

**Issue by Joristdh** [8bitPit/Niagara-Issues#1703]
### Describe the bug

When using 3-button navigation a nice fade effect is applied to the bottom (and top) of the screen when scrolling through the app list. However, when using gesture navigation this fade effect is missing (see screenshot). It is still applied to the top, but not on the bottom.

### Steps to reproduce

1. Make sure gesture navigation is enabled
2. Go to the app list
3. Scroll so that an app icon is behind the navbar
4. Notice that no fade effect is applied

### Device name

Google Pixel 5

### Android version

Android 11

### Screenshots / Screen recordings

![signal-2021-09-14-102536](https://user-images.githubusercontent.com/6518350/133223531-5c0ab67d-5e4c-4734-891e-8462a06381b0.png)

**Comment by 8bitPit** [comment]
Thank you for mentioning it. This is intended: Depending on what's under the gesture bar, it adjusts its color to be always visible in contrast to the navigation button bar. The fade effect helps you to see the navigation buttons better, but with gesture navigation turned on, we don't need that.

**Comment by Joristdh** [comment]
Thank you for your response, however on my device (Pixel 5, Android 11) the gesture bar does not change to a contrasting color when white text is displayed under it:
![signal-2021-10-04-110746](https://user-images.githubusercontent.com/6518350/135826785-8b11bb64-bca1-4fb3-97ee-7592ba803901.png)

Also, I really like the fade aesthetic on the icons, even when it isn't necessary to see the icons on the gesture/navigation bar. So I really hope you could reconsider your "working as intended" stance, but I'd understand if you don't.

**Comment by 8bitPit** [comment]
> Thank you for your response, however on my device (Pixel 5, Android 11) the gesture bar does not change to a contrasting color when white text is displayed under it:

Ah, that's because the white surface of the text is too small for the bar to change the color.

> Also, I really like the fade aesthetic on the icons, even when it isn't necessary to see the icons on the gesture/navigation bar. So I really hope you could reconsider your "working as intended" stance, but I'd understand if you don't.

We wanted to go for a more immersive look and find it cleaner but I can see now that this might be up to personal preference. However, I don't want to add a toggle for that because this feature wouldn't be impactful enough (see: https://help.niagaralauncher.app/article/8-niagaras-design-principles). I hope that's understandable.
