### ISSUE TITLE
Add next alarm time to Niagara widget

### ISSUE THREAD

**Issue by PemikM** [8bitPit/Niagara-Issues#1704]
### Describe the solution you'd like

In my opinion it is generally useful to have time of next alarm shown on the phone home screen. It allows you to see at first glance whether the alarm is set and if it is set to correct time. I don't see any negatives on adding it as there is enough space on the Niagara widget.

**Comment by Maxr1998** [comment]
For people whose alarms rarely change, this might be a bit bloaty/redundant and ruin the clean look. So *if* we are going to implement this, we would make to have it configurable. That somewhat contradicts our [design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles) however..

**Comment by 8bitPit** [comment]
Yeah. I'm sorry @PemikM, but we're not planning to add an alarm icon right now: https://github.com/8bitPit/Niagara-Issues/issues/4.
