### ISSUE TITLE
Niagara on Fold 3

### ISSUE THREAD

**Issue by Dholisek** [8bitPit/Niagara-Issues#1705]
### Describe the bug

When I am on the main page using swipe gestures on the galaxy fold 3, I am not able to swipe up to look at the recently used apps, I have to enter an app and then swipe up to gain access to recently used apps. 

### Steps to reproduce

Enable swipe gestures as navigation method 
Open apps
Go to home screen unfolded 
Try to swipe up to look at recently accessed apps 
See error 

### Device name

Samsung Galaxy Z Fold 3

### Android version

Android 12

**Comment by 8bitPit** [comment]
I hope the last paragraph of this article helps: https://help.niagaralauncher.app/article/114-recent-apps-screen-issues

**Comment by Dholisek** [comment]
Excellent that helps, thank you for your time

Dan

**Comment by 8bitPit** [comment]
Awesome, thanks :D
