### ISSUE TITLE
UI: equalize space between elements

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#1706]
Make the space (see red marks) between Agenda white-box and calendar text equal to space between clock time and date.

Very minor, but would look more consistent when "Your agenda" visible.

![1632151898365.jpg](https://user-images.githubusercontent.com/7660277/134030040-e290fcfe-9f34-4736-aeef-4aa479af0682.jpg)

**Comment by Maxr1998** [comment]
The top-padding/position of the calendar sheet is device dependent and calculated dynamically, so not actually aligned with the date at all. That is especially true if you move the date vertically or have the "replace clock with widget" option enabled.
