### ISSUE TITLE
Option for simple, always-on icons at the bottom of home screen

### ISSUE THREAD

**Issue by russellweiss** [8bitPit/Niagara-Issues#1709]
### Is your feature request related to a problem?

I need to be able to quickly call up the "Phone" and "Messages" app without scrolling through a list.  I know that these can be put at the top of the favorites list, and I also believe that some users would prefer a greater level of prominence (see idea below).

### Describe the solution you'd like

Just installed Niagara yesterday, and it's great.  It is certainly an adjustment after using the standard OneUI launcher for many years.  

After configuring Niagara for the first time, I realized that I lost easy access to the phone app, as well as the messages app.  I use these very frequently.  The workaround that I found was to make these "Favorites" and put them at the top of the favorites list.

That said, these two apps are essential, and require fast and easy access. 

I think that the option to have "always-on" icons at the bottom of the screen to launch 2-3 essential apps would be useful, and would help new users to adjust to using Niagara.  I can provide screenshots of what I'm talking about if necessary, but it would basically be similar to what the OneUI launcher does for the "always-on" icons at the bottom of the screen.

**Comment by notepadnine** [comment]
I think this will loose its monotonous charm. Spend more time and you will realize beauty.

But for that purpose I think better **if we can enhance icon or icon text size to few item of favourite list. This can highlight those icon apart. I support colorise CLOCK text**

**Comment by Oddward** [comment]
This is essentially the kind of thing the [Niagara button](https://help.niagaralauncher.app/article/116-niagara-button) was made for. I created a folder for the swipe up action of the Niagara button, and in it I have my quote app, phone, messages, camera & settings (the basic phone apps) all tucked out of the way

I.e. A solution already exists that fits with Niagara's current design & principles better

**Comment by Rod911** [comment]
Closing for the reasons mentioned above, feel free to reopen if necessary.
