### ISSUE TITLE
Multiple Home Screen Option for Apps & Widgets

### ISSUE THREAD

**Issue by russellweiss** [8bitPit/Niagara-Issues#1710]
### Is your feature request related to a problem?

As strange as it may sound, some users may not remember the name of certain apps, making them more difficult to recall.  For example, I use a few home automation products that have their own apps, and while they are generally controlled by a single app (SmartThings), at times, I need to go into the specific app designed for these devices (smart plugs, etc.).

In general, I find that it is much faster to access apps via Niagara as long as I remember the name.  If I do not, it can be a chore.  Pop-up folders help quite a bit, but I had another idea that might help certain users.

Also, with the current layout, there's very little space for widgets.  I rely on a few widgets, so having alternate screens would provide a lot more room.

### Describe the solution you'd like

OneUI gives the user the option to have multiple screens to view icons.  For example, on OneUI, I can swipe left or right.  In practice, I've configured just a few screens that have my most frequently used app icons for home automation and other purposes.

I recognize that this can be achieved through pop-up folders.  An option might be nice to get a little bit more "real estate" and allow a swipe to the left to reveal a new screen with icons to launch the most popular apps.  In fact, you could have dedicated screens assigned to a single folder.  For example, if you swipe left from the home screen, the entire screen is devoted to the contents of a folder.

That said, I also have some widgets that I rely heavily upon.  Being able to swipe left and see a screen with as many widgets as needed would be amazing.

I truly believe that adding the "multi-screen" functionality would be the best of all worlds -- the fast access that Niagara provides and the ability to use more space for widgets and app shortcuts that OneUI provides.

Please let me know if you need screenshots or a Loom video to describe this in more detail.

**Comment by Maxr1998** [comment]
Multiple home screens and swipe navigation doesn't really fit into the design of Niagara Launcher, so we most likely won't implement this.
Having mutiple widgets is currently [only supported through pop-up folders](https://help.niagaralauncher.app/article/41-adding-multiple-widgets), we may eventually allow more than one widget in there.
