### ISSUE TITLE
Support calendars of iCal formats

### ISSUE THREAD

**Issue by lezsakdomi** [8bitPit/Niagara-Issues#1711]
One can add a calendar to Google Calendar by importing it from an URL. I have one such, but it does not show up in the Niagara Launcher. (I can select the filter for it, but I see no events.)

Either hide these calendars from the filter or make them working. Or as a temporary solution hide them from the filters, and later on implement supporting these.

**Comment by 8bitPit** [comment]
Thanks for reporting @lezsakdomi. We're using Android's calendar API to query all calendar events from all publishing calendars. It seems that Google Calendar hasn't provided these calendar events yet, I hope this troubleshooting guide can help: https://help.niagaralauncher.app/article/76-calendar-faq.

**Comment by 2zqa** [comment]
As an workaround, try installing ICSx5 and subscribe to any amount of ical urls you like. It's free on F-Droid, but also available on play store if you want to support the development. I can confirm these do show up.
