### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by dansmeah** [8bitPit/Niagara-Issues#1712]
### Is your feature request related to a problem?

I feel that things like scrolling through the alphabet should give haptic feedback for each letter. 

### Describe the solution you'd like

I feel that things like scrolling through the alphabet should give haptic feedback for each letter.

**Comment by Rod911** [comment]
Please see https://help.niagaralauncher.app/article/99-vibration-for-alphabet-scrolling

Duplicate of #200
