### ISSUE TITLE
Surface Duo dual screen margin adjustment OR disable two column mode flag on v1.4.1 beta

### ISSUE THREAD

**Issue by karlchan** [8bitPit/Niagara-Issues#1713]
### Is your feature request related to a problem?

So happy with your commitment to some foldables and tablets! Two column mode is nice and works pretty well with my MS Surface Duo in many of its postures. However, in the dual screen mode, the left margin on the left screen seems a little too shifted over, and the second column over on the right screen need some more left margin. Refer to screenshot.

![duo_x_niagara](https://user-images.githubusercontent.com/767932/134499789-28d4f540-54fc-453c-b723-a2983f503d70.jpg)

Single screen works well!
![duo_x_niagara_2](https://user-images.githubusercontent.com/767932/134499791-5971bd17-279d-4b7e-a770-205a71ae3821.jpg)

### Describe the solution you'd like

1. Maybe add a option/slider in the settings to adjust margins for each column? OR 
2. just the ability to disable the dual column, I know this kind of defeats the purpose of the new beta. OR
3. I know this is could be a big request, but with the announcement of the Duo2 yesterday, maybe support for dual screens. I know we're in the minority, but Niagara launcher is the ONLY viable launcher replacement that I recommend: https://www.reddit.com/r/surfaceduo/comments/ph58ad/found_a_viable_ms_launcher_replacement_that/

**Comment by Maxr1998** [comment]
Thanks for your report! We're already in talks with Microsoft to improve the Niagara Launcher experience on the Surface Duo. See [this](https://twitter.com/NiagaraLauncher/status/1441047598383632385) and microsoft/surface-duo-sdk#36 for more reference. We're now waiting for Microsoft to improve their SDK so that we can fix this issue.

**Comment by 8bitPit** [comment]
Hey @karlchan, I also want to thank you for the detailed report. We just released an update that fixes the margins for the dual-screen layout: https://github.com/8bitPit/Niagara-Issues/releases. As Max said, we hope we can make further improvements soon.

**Comment by karlchan** [comment]
@8bitPit THANK YOU! works well now on the MS Surface Duo. Hope you can make further improvements to foldables/dual screen devices down the road!
