### ISSUE TITLE
Fold 3 2 column dead space bug

### ISSUE THREAD

**Issue by dr3am37** [8bitPit/Niagara-Issues#1715]
Hi

In the latest version there's dead space around the 4th app in a column, not sure how to replicate as it went away.

**Comment by dr3am37** [comment]
![Screenshot_20210923-124032_Niagara Launcher](https://user-images.githubusercontent.com/91037083/134573740-376d4d03-d675-4396-a674-056eb83a5511.jpg)

**Comment by dr3am37** [comment]
Update on how to replicate, this occurs when you get a message in let's say WhatsApp, if you press it and go to the app, when you come back the notification is gone but the expanded spaces remain

**Comment by Maxr1998** [comment]
Thanks for the report, Peter already noticed this on his Fold, too. We'll fix it soon. And yes, it's related apps not resizing after a notification was dismissed.

**Comment by dr3am37** [comment]
Awesome, thanks for the hard work

**Comment by dr3am37** [comment]
Seems like it's fixed in the blnew release, thanks!

**Comment by 8bitPit** [comment]
Ah yeah, @Maxr1998 fixed it, thanks for reporting :)
