### ISSUE TITLE
[Feature Request] Utilize Android 12 dynamic colors / material you

### ISSUE THREAD

**Issue by Charaktor** [8bitPit/Niagara-Issues#1716]
With the upcoming Android 12 a dynamic color system will use a color pallet based on the current wallpaper, to dynamicly color the OS and apps to have a more consistent look throughout the ux. 

This dynamic color system would fit great in Niagara. Especially for the niagara button and also as light backgrounds in pop-up folders and the 'sheets'.
Maybe even in the settings or as the fonts color.

I'd love to see this subtle design change. Imo this will make Niagara even more seemless integrated.

**Comment by 2zqa** [comment]
I agree. Although it will be quite a design overhaul, I like the idea. I'll also bet on a ton of news coverage ("Top 10 Apps Using The New Android 12 Material You Design!"), although that should definitely only be a bonus and not a consideration.

**Comment by 8bitPit** [comment]
You might have already seen it, Niagara Launcher [now supports Material You color schemes](https://twitter.com/NiagaraLauncher/status/1468257542673506306) :) We're currently tweaking the colors to make the new theme more noticeable. I'll close this ticket, but you can still reply to this thread if you want to provide feedback.

**Comment by missyraja** [comment]
I've really enjoyed the new update as I'm on a12... Hope you guys make it more noticeable for others...

Thank you guys ..
