### ISSUE TITLE
[Feature Request] Custom Font Scaling Support, as font really looks small on my device

### ISSUE THREAD

**Issue by RishavArya002** [8bitPit/Niagara-Issues#1717]

**Comment by Montell2099** [comment]
I'm all for this. A font size slider right next to the icon size slider would be terrific, as some fonts are just smaller by default than others.

**Comment by Racle** [comment]
Same issue with custom font.

One font was extremely large, other one was extremely small 😅

**Comment by 8bitPit** [comment]
While we didn't add a font slider, we now automatically scale custom fonts to have the proper size. I hope this helps!

**Comment by Montell2099** [comment]
> While we didn't add a font slider, we now automatically scale custom fonts to have the proper size. I hope this helps!

Sounds great! I'll try it out.

**Comment by Racle** [comment]
Forgot to comment, this seems to be working well, at least with my fonts.

**Comment by 8bitPit** [comment]
Awesome, thanks for letting me know :D
