### ISSUE TITLE
Persistent Widget & Clock

### ISSUE THREAD

**Issue by Princebtw** [8bitPit/Niagara-Issues#1720]
### Is your feature request related to a problem?

Hi , i would like to request a feature which enables users to keep widget and clock persistent in homescreen. While scrolling up through favourites i would like to move the list up and Widget & clock moves upwards and hit the top and stay persistent there

Favorites can move upwards and downwards completely

### Describe the solution you'd like

Keep the widget & clock on homescreen and don't want it to disappear during scrolling

**Comment by Maxr1998** [comment]
Probably not a thing we'll add, especially because favorites shouldn't normally be scrollable anyway (Niagara recommends up to 8 favorites).
