### ISSUE TITLE
Re-add Niagara button long press

### ISSUE THREAD

**Issue by EXOgreen** [8bitPit/Niagara-Issues#1723]
While I love the update for the Niagara button, I would love to see the long press of the button be remapable again. I used long press for Google News forever and it's in my muscle memory. Also adding the settings for said Niagara button to the actual settings menu so it isn't hidden behind a long press when people forget.

(and maybe custom icon support? 🙏)

**Comment by Maxr1998** [comment]
We changed the long-press from Google Assistant to the configuration menu to have it quickly accessible and easier to discover. Two actions (tap and swipe) should still be enough, if you need more, I suggest adding a folder to either of the actions.

Custom icons could potentially arrive in the future, but there aren't any specific plans for now.
