### ISSUE TITLE
Pop up screen size consistency

### ISSUE THREAD

**Issue by cbalx** [8bitPit/Niagara-Issues#1724]
### Is your feature request related to a problem?

Pop up window sizes depend on how far down the screen the app icon is located. This means that the icons on the top have larger windows than icons on the bottom. It gets a bit frustrating I'll be considering not only how much I'll use an app where I place the app on thr favourites list but also need to consider how big I want the widgets and how many apps I want to be listed in the pop up window which sometimes don't align. For example I want to place my chat apps near the middle or top of the favourites list where my hands naturally rest but I don't need a large pop window for those apps. Whereas for other apps I don't use often I'll place lower on the favourites list but they'll have a widget which I want to be much larger. 

### Describe the solution you'd like

Can we please have an option that'll allow the pop windows to be consistently sized no matter where I place the app icon on the favourites list. Or way I can resize how large I want the pop window to be per app icon?

**Comment by missyraja** [comment]
This is a must

**Comment by topsy-turvy99** [comment]
Fixed?

**Comment by 8bitPit** [comment]
The popups size now solely depends on its content's size (except if the popup would be larger than the available space - can happen if the keyboard is open at the same time, for example). Does this solve your issue @cbalx?
