### ISSUE TITLE
Archive or delete for email pop-up.

### ISSUE THREAD

**Issue by msshane** [8bitPit/Niagara-Issues#1725]
### Describe the solution you'd like

 I often try to clear emails - particularly work ones - from my inbox without actually deleting them. So I have become a heavy user of the Archive function, which does exactly that. 

Right now in my Niagara email pop-up, a swipe right or left on the email both lead to "Delete". That redundancy send unnecessary (and thus arguably against Niagara design principles). 

So I'm requesting that a swipe right be "Delete", and a swipe left be "Archive". That would add some extra functionality (big, because it'll truly allow for dismissing of emails from the homescreen instead of having to enter into the app), in a universal way, without adding any real additional complexity. So I think it fits within Niagara's design principles. Likely pretty easy to implement to, which doesn't hurt.

Thanks for considering!
-Matt

**Comment by Oddward** [comment]
Swiping left or right in Niagara pop-ups only clears the notifications, it doesn't affect your emails, only way to affect content in the app is to press the action buttons below the notification which are exposed according to the app in question

Your request has little to do with the launcher

**Comment by Maxr1998** [comment]
Oddward already answered this, only the buttons in the notification actually impact the emails, swiping just clears the notification.

If you want to choose between "archive" and "delete", you can do that in the Gmail settings.
