### ISSUE TITLE
Organize apps in categories

### ISSUE THREAD

**Issue by RaniAgus** [8bitPit/Niagara-Issues#1726]
### Is your feature request related to a problem?

I find it a little bit difficult to find each app I use for a certain moment of my day, eg:
- when I'm studying I use a pomodoro app, a Calendar and Spotify
- when I have free time, I use Instagram, Twitter, Spotify, etc
- when I'm about to go to sleep, I use my clock and a To-Do app for my tomorrow tasks

I mean, as each app is categorized by name, I have to scroll through the alphabet to find them.

### Describe the solution you'd like

It would be nice if there was a way to categorize apps by type (100% user defined), so my left scroll is "by category" and my right scroll is "by name".

**Comment by Maxr1998** [comment]
Using different sorting orders depending on where you scroll would be quite confusing to some users. Instead, I'd suggest using folders, or (as a potential future feature) contextual awareness/profiles that allow a specific set of apps to be shown as favorites.
Something like that has been discussed a few times already, but so far we haven't really worked on it. It will probably still take some brainstorming to find a good solution here.

**Comment by 8bitPit** [comment]
Thanks for the suggestion @RaniAgus. As Max pointed out, we might opt for simple profiles instead. For your use case I recommend placing category-based folders in your favorites or in your app list.
