### ISSUE TITLE
Search: add calculator

### ISSUE THREAD

**Issue by x1unix** [8bitPit/Niagara-Issues#1729]
### Is your feature request related to a problem?

Hello, can you please add some basic calculation feature to Niagara search? I moved from iphone and used spotlight calculator pretty much (abbility to write some basic math expression in search bar and get instant answer)

### Describe the solution you'd like

The same behavior like in iOS spotlight or Google Chrome omnibar: abbility to enter some basic math expression (like 2+2) and get instant answer in search result.

**Comment by Rod911** [comment]
If you have Sesame Integration enabled you already get this in the search results.

**Comment by timm0e** [comment]
Good news! We're planning on overhauling our search, and we think that this feature is very handy! :tada:
