### ISSUE TITLE
A thoughtful list of suggestions #2 (Launcher layout, folders, and design)

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#173]
1) Currently, some feel the launcher looks a bit off with the Google button placement. Though convenient, I must say it does feel like it doesn't fit in well enough.

 After seeing the suggestion for folders placement in a pic by @8bitPit in thread #13, I came up with a way to fix it, and here's a pic for reference.
![screenshot_20180910-235211](https://user-images.githubusercontent.com/43073817/45317039-6 BC8828800-b556-11e8-8914-a5c29421b17d.png)
EDIT: Idk if the file uploaded cuz I wrote this from phone, so here's a link in case it didn't:
https://photos.app.goo.gl/LFxSfw8T1SCEDDw78
 - If the layout of the launcher is fixed in this position*, i.e., scrolling is no longer possible, then the slim line with stay fixed halfway and at the middle of the Google icon, which now looks aesthetically better. 
- As the scroll on Favorites page doesn't exist anymore now, the swipe up/down gesture can be implemented much more easily. To make up for the missing scroll in Favorites page, Recent apps will be put under a folder. However, there may be upto 8 apps only per folder. I think that's more than enough though, considering we will have a bunch of folders easily accessible.
*For this position to be fixed, the clock and date elements have to be fixed a bit higher.

2) Coming to the topic of folders, here's what I wanted to share:
- Instead of having named folders, use circular icons with a minimal symbol, all of which change colour like how the Google icon currently does (it looks great btw). The icons would be comparatively smaller in size.
 So for Favorites it will be the star as it is in the scroll, for Recents it could be a mini clock, for widgets those little squares with one tilted, and the other folders will have options users can select from (such as for music, it'll be the music symbol thing, whatever that's called). Of course, there needs to be quite a few such icons, users can help choose which by commenting here.
 This would look really really good and go well with the minimal feel of the launcher.
- If I place my finger on a folder icon, that folder's apps show up and if I DRAG my finger across to other folders, their respective apps show up. 

3) This is just something stupid I thought was cool. I don't really need it either. But I was thinking if, in the pic, the Google icon could be dragged across to the left end of the horizontal SLIDER, it would act as a switch to switch to left-handed mode; when it's swiped, the app icons move to the right side with their app names to their left side, and the app scroller moves to the left. Now, idk if the clock and date should move to the right as well, it might look kinda weird. Just wanted to share that idea (which is cool).

4) How about making the horizontal line glow :o it can glow white when battery isn't low, and red otherwise, how about blue when charging.
Could help if you're considering making a hide status bar feature.

Okay, that's about it for this one. Thanks for taking the time to read. Would love to discuss further with others.

**Comment by jakcharvat** [comment]
Really nice in depth analysis, love it!

My reactions:
- I like the idea of putting recents in a folder. I would also suggest one folder for all apps with an unread notification. However, I don't like the idea of being limited to 8 apps per folder. I feel like the folder could be a scrolling list with either no limit, or a limit of at least 20 apps. 
- I like the idea for the folder icons, but I would keep the labels for reason mentioned several times already on this GitHub. 
- LOVE the idea with the folder previews
- Swiping the Google Logo to switch the hand modes is a cool idea, we could then only have the scroll bars on the active side, and they could switch together with the G logo

**Comment by Shinra04** [comment]
My reactions to your reactions, in order:
- Having an entire folder just for apps with unread notifications is... weird.
 However, I do see that perhaps 8 apps may not be enough for everyone. So here's my new suggestion: the scroll will not be removed, but the horizontal line dividing apps and folders below will remain fixed. Also, to make the swipe down gesture easier, it can be changed to swiping down on the G icon, which feels intuitive. Swipe up gesture cannot be implemented due to scroll, and so the search apps trigger with continue to be a tap on home.

- I see no reasons to have entire folder named written because: 1 being horizontally next to each other, named folders would take up too much space and so you can't see enough folders, making it hard to access them, 2 it will look clunky and stray from the theme of minimalism 3 you will be seeing these folders a lot of times during the day, I'm sure anyone will be able to tell which folder contains what, icons only make it easier.
- They aren't folder previews. Dragging a tap over folders directly opens their respective list of apps.
- Yes, in doing so, we can free up the left/right edge of screen (for right/left-handed mode respectively) for more gestures.

**Comment by 8bitPit** [comment]
`Currently, some feel the launcher looks a bit off with the Google`
I personally like the placement; the floating action button is visually balanced with the app list.

`If the layout of the launcher is fixed in this position`
That's not possible, what if you've got a tiny phone or you use Niagara in split screen mode?

` the slim line with stay fixed halfway and at the middle of the Google icon`
the line could be for example at the top and placing the button there would not look good.

'Recent apps will be put under a folder'
2 problems: It would be slower to reach them & you don't know which apps are exactly in the folder, since they are controlled by the launcher, so you wouldn't open the folder.

`Instead of having named folders, use circular icons with a minimal symbol`
Yeah, agree, I had the same thought ^^

`Google icon could be dragged across to the left`
Yeah, cool idea, but you usually don't toggle the mode more than once & it's not that intuitive, bc it has a Google symbol on it. 

`How about making the horizontal line glow`
Yeah nice idea to functionalize the divider, however it does only show up when recently used apps are visible and a red/blue tint would not look good on many wallpapers

Thanks for your suggestions!

**Comment by Shinra04** [comment]
@8bitPit

- I think the G icon looks great, with a nice placement too. The only reason it looks off to me is because of the moving horizontal line.
- I don't understand why the horizontal line can't be made into a divider between the apps above and folders below? Isn't it the same as making a dock of a sort, which surely doesn't cause issues for tiny screens or split-screen mode. It'll be like a tail to the G icon, which currently doesn't move up or down either.
- So if Recents can't be moved to a folder either, then how about keeping the scroll, but having a folders DOCK at the bottom, which will be an overlay on the Favorites scroll list of apps. In this manner the folders can stay in a static position (which makes it easy to access both folders as well as Recents) as well as keep the G icon attached to a line, making it look less like it's just floating awkwardly. 
Just to clarify, when I suggested to put recent apps in a folder, the apps in this folder would be automatically generated by the launcher, just like how it currently is, except it won't be in the Favorites page itself 

- Okay maybe you don't have to make the G icon itself the toggle to switch handed mode, but you could make it an option in the settings right? I can't say how intuitive it would be for a left-handed user though, you'll have to see about that.

- Yeah, it was just an idea that came to me. If you were to implement a docked folder system though, the horizontal line would be in place. 
Agreed that the tint would look weird. How about making a strip of white which is slightly thicker than it currently it. The strip can be full at 100%, it shortens to reveal a thinner line as the charge reduces. Nothing important though.

Thanks for the reply :)

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
