### ISSUE TITLE
Time shrinks

### ISSUE THREAD

**Issue by akastanis** [8bitPit/Niagara-Issues#1730]
### Describe the bug

Sliding the Niagara widget up causes the time display to shrink.

### Steps to reproduce

Side the Niagara widget up

### Device name

Google Pixel 3a XL

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_20211014-164711](https://user-images.githubusercontent.com/9420507/137410648-e239d2d2-d3c4-4213-95cd-2670b5f53289.png)

**Comment by Maxr1998** [comment]
As @Oddward said, this is intended and not a bug. If you don't want the time to get smaller, give the widget more space.
