### ISSUE TITLE
Folder in app drawer

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#1732]
### Is your feature request related to a problem?

because hiding is sometimes not a solution. But still i want tidyness

### Describe the solution you'd like

Option to create folder in app drawer. Currently this is limited to favourite.

**Comment by Oddward** [comment]
Long press a folder after creating it and tap "show in app list" and it will be in app list

Ask for help in any of the community channels before filing a bug report or feature request, especially it something seems like it should already be possible

**Comment by Maxr1998** [comment]
As mentioned, this is already possible. Closing.
