### ISSUE TITLE
Media controls open wrong YouTube video when using picture in picture

### ISSUE THREAD

**Issue by PauldeKoning** [8bitPit/Niagara-Issues#1733]
### Describe the bug

The media controls at the top usually show the YouTube video you are watching. This stops working as soon as your YouTube video is in picture in picture mode. 

However, when you have a YouTube notification that recommends a video it starts showing again.

When you click on the media controls to open the YouTube video, you expect the current playing video to open in the YouTube app. Instead what it does is it takes the video of the recommendation notification and starts playing that video.

### Steps to reproduce

1. Play a YouTube video
2. Play video in picture on picture mode
3. Have a YouTube video recommendation notification
4. Click on media controls picture to open the YouTube app
5. The recommended video starts playing

### Device name

Samsung a50

### Android version

Android 11

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)

**Comment by PauldeKoning** [comment]
Apologies but I do not use this launcher anymore mostly because of this bug, I'd guess it was quite a specific issue to my case/phone. Cannot help testing now anymore though! I since upgraded phone too.

**Comment by 8bitPit** [comment]
I see; I'll close this issue then. Thank you for letting us know, and happy Holidays!
