### ISSUE TITLE
Provide an option to add app to pop-up folder

### ISSUE THREAD

**Issue by msshane** [8bitPit/Niagara-Issues#1734]
### Is your feature request related to a problem?

Right now, in order to add an app to a folder, you need to go to the desired *folder*, open it, edit it, find the app you want, and add it to the folder. 

This may seem logical, but it's not the way folder organization often happens. Rather, a user often sees an app in their application list and says "That should go in the 'Food' folder". But then what needs to happen is: 

1. See app
2. Open app options
3. Realize there is no option to add to folder; only to favourites
4. Close app
5. Locate desired pop-up folder
6. Open folder options
7. Edit folder
8. Find the desired app (again, even though it was right in front of you in the first place)
9. Select the app and add to folder.

Annnnnnoyyyyyinnnng! (Especially during initial app/folder organization when you are placing hundreds of apps in dozens of folders).

### Describe the solution you'd like

In the options menu for each app, instead of just having an 'Add to Favourites' option, please add an 'Add to Pop-up Folder's option. This could open a list of all pop-up folders, so the correct one can be selected.

**Comment by topsy-turvy99** [comment]
Added in v1.7.0 (fixed)

- Directly add apps to folders: Long-press an app and tap Add to category to quickly add it to pop-up folders and other categories.

**Comment by Maxr1998** [comment]
You're right, we actually implemented this. I'll have to eat my words :grin:
Thanks for the heads-up!

**Comment by msshane** [comment]
Your welcome, I guess.
Thanks for keeping track, and for the quick note. 😊
