### ISSUE TITLE
Dont show subscription expiration notification when pro was bought

### ISSUE THREAD

**Issue by henningBunk** [8bitPit/Niagara-Issues#1735]
I tried the free subscription and canceled it immediately. After a week I decided to keep using Niagara so I bought pro.Today I received the notification that I would loose pro features if I dont resubrscribe. That is not correct and shouldnt be shown imho.

**Comment by henningBunk** [comment]
@Maxr1998 I had the impression it came frm Niagara but in the end I am not totally sure, could also have been one from Google Play. Since I cannot recreate it right now I cannot confirm it, sorry.

**Comment by Maxr1998** [comment]
Good to know. I'll assume it came from Google Play, and since we unfortunately can't fix that, I'll close this issue for now.

**Comment by 8bitPit** [comment]
Hey @henningBunk; unfortunately we can't do anything about that  :/ The problem is that we need to offer two different in-app purchases for the subscription and the lifetime variant. The problem is that Google doesn't know these purchases are related and unlock the same content.
