### ISSUE TITLE
Cortana implementation

### ISSUE THREAD

**Issue by CBluebaer** [8bitPit/Niagara-Issues#174]
Please let the user choose between google search an cortana. Also as an icon in the front.

**Comment by jakcharvat** [comment]
You use Cortana? Honestly, I've spoken to hundreds of Android users and you are the first to use Cortana. I feel this isn't the highest priority for that reason

**Comment by 8bitPit** [comment]
Yeah, sry too few people use cortana (esp. on their phone)

**Comment by laggingreflex** [comment]
Please reconsider, there are dozens of us... [DOZENS](https://www.youtube.com/watch?v=lKie-vgUGdI)
