### ISSUE TITLE
fonts are not changing on app names 

### ISSUE THREAD

**Issue by Udayanithig** [8bitPit/Niagara-Issues#1742]
### Describe the bug

Fonts are not changing on app names (home screen). But on the settings page and clock widget, it is working as expected.

### Steps to reproduce

1. Go settings
2. Go to Look >> Font 
3. Select Niagara Neo

### Device name

Xiaomi 11 Lite 5G NE

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_2021-10-29-21-34-23-909_bitpit launcher](https://user-images.githubusercontent.com/76005728/139467737-585b49c8-1345-4e9b-aee9-583d1c7c529f.jpg)
![Screenshot_2021-10-29-21-34-38-173_bitpit launcher](https://user-images.githubusercontent.com/76005728/139467754-b7175ccc-3b2a-4898-bd99-0da0f92ee586.jpg)
![Screenshot_2021-10-29-21-34-35-010_bitpit launcher](https://user-images.githubusercontent.com/76005728/139467759-287979c5-1bba-4d66-b420-c8ac12538130.jpg)

**Comment by Maxr1998** [comment]
Shadows on the text look kinda weird too - are you by any chance using a theme engine/design or system feature that could impact font selection?

**Comment by Udayanithig** [comment]
It is due dark mode on MIUI. Turning off dark mode solves the problem.
