### ISSUE TITLE
Icon shape

### ISSUE THREAD

**Issue by niakoi1** [8bitPit/Niagara-Issues#1744]
### Describe the bug

If icons are customized, changing shape does not take.
Pixel 5, latest Android

### Steps to reproduce

1. Customized icon looks with some icon pack. I use umbra
2. Try changing icon shape

### Device name

Google pixel 5

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20211102-121146](https://user-images.githubusercontent.com/54175464/139827878-54b087aa-5cfe-40ba-954b-be308dfcc1ae.png)

**Comment by 8bitPit** [comment]
Thanks fire the report. Icon packs have to support the different shapes (called adaptive icon packs). Most do not, however, see Niagara launchers disclaimer in the icon shake chooser.
