### ISSUE TITLE
Large padding when using the new A12 clock widget

### ISSUE THREAD

**Issue by buzzcola3** [8bitPit/Niagara-Issues#1746]
### Describe the bug

While using the new stock A12 clock widget, and disabling the stock Niagra date widget the padding on top is way too dank

### Steps to reproduce

1. Disable the Niagra date and time
2. Enable the A12 clock widget

### Device name

Xiaomi mi mix 2s

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20211104-172009](https://user-images.githubusercontent.com/31044374/140378942-f0d4f42c-7693-4b89-8c85-90b05744f964.png)

**Comment by Maxr1998** [comment]
I think the current release works like that for widgets generally, stay tuned for the next update, that will allow to decrease the padding quite a bit.
