### ISSUE TITLE
Shortcuts created by an app can not be added to the pop-up of the app

### ISSUE THREAD

**Issue by Flummic** [8bitPit/Niagara-Issues#1747]
### Describe the bug

**Situation**: I use Vivaldi as my main browser on my phone (Chromium-based) and I created a shortcut to a webpage on my start-screen of my phone. 
So far everything worked as expected an the shortcut was conveniently added to the applist of the launcher. 

**Problem**: Now I wanted to add the newly created shortcut to the pop-up of the vivaldi-app, which is already one of my niagara-favourites so adding the shortcut would allow quick-access to the webpage. Sadly that is not possible as the shortcut doesn't show up as an option. 
It is possible to add the shortcut to pop-up-folders of different apps, but it is impossible to add it to the pop-up of the app that created the shortcut.

**My dream:** I would love to add my most used bookmarks/webpages as shortcuts to my browser's pop up for quick and convenient access straight from my homescreen.

### Steps to reproduce

1. Use your broser-app of choice to create a shortcut of a webpage on your homescreen
2. Move it out of the Niagara-Favourite-List and into the App-List of Niagara
3. Try to add the new shortcut to the Pop-Up-Folder of the browser-app
4. See that it doesn't show up as an option there, but it does do so in all the other pop-up folders

### Device name

Google Pixel 3

### Android version

Android 12

### Screenshots / Screen recordings

![image](https://user-images.githubusercontent.com/78422787/142086863-c7224f30-2671-4e08-9f83-5f5e1dd89246.png)
![image](https://user-images.githubusercontent.com/78422787/142086885-cd09a7ce-8c73-4a03-9984-8b0763b4d04e.png)

**Comment by Flummic** [comment]
Okay I found a **solution** to my issue:
I have to open the _Sesame-Settings_ in which I can select Vivaldi and add all available shortcuts via a long press. 
This autmatically adds the shortcut to the Niagara-Pop-Up of Vivaldi :)

Still I think that the behavior I described above is unintuitive and my solution does only apply to people who use Sesame, which is why I will keep the this issue open for now and let you (devs) decide 😜

**Comment by Maxr1998** [comment]
Actually, this is possible even without Sesame. When selecting apps for the pop-up, you have to scroll to the shortcuts section at the very bottom, click on "More shortcuts" ("Weitere Verknüpfungen" in German), scroll to Vivaldi, and select the website shortcut.

**Comment by Flummic** [comment]
> Actually, this is possible even without Sesame. When selecting apps for the pop-up, you have to scroll to the shortcuts section at the very bottom, click on "More shortcuts" ("Weitere Verknüpfungen" in German), scroll to Vivaldi, and select the website shortcut.

That solution does not work for me, since the website doesn't show up as a shortcut there 🤔 
How can I add webpages to the list of shortcuts?

**Comment by Maxr1998** [comment]
> > Actually, this is possible even without Sesame. When selecting apps for the pop-up, you have to scroll to the shortcuts section at the very bottom, click on "More shortcuts" ("Weitere Verknüpfungen" in German), scroll to Vivaldi, and select the website shortcut.
> 
> That solution does not work for me, since the website doesn't show up as a shortcut there 🤔 
> How can I add webpages to the list of shortcuts?

I simply selected "add to homescreen" from within Vivaldi. The shortcut was then added to my favorites. It *could* be that this behavior only recently changed and wasn't rolled out yet, but that still somewhat surprises me.

**Comment by Flummic** [comment]
> > That solution does not work for me, since the website doesn't show up as a shortcut there 🤔
> > How can I add webpages to the list of shortcuts?
> 
> I simply selected "add to homescreen" from within Vivaldi. The shortcut was then added to my favorites (and also visible in the described section). It _could_ be that this behavior only recently changed and wasn't rolled out yet, but that still somewhat surprises me.

Interesting -> now it shows up in the described section. I don't know what changed, but thank you for your help! Keep up the awesome work on this beauty of a launcher! 👍 I really appreciate it!
Btw. I LOVE the "Bundled Messages Feature"!

**Comment by 8bitPit** [comment]
Thank you very much for your kind words @Flummic :D
