### ISSUE TITLE
Blur the wallpaper in the  apps drawer window.

### ISSUE THREAD

**Issue by gsunny729** [8bitPit/Niagara-Issues#1748]
### Is your feature request related to a problem?

Sometimes wallpaper distract the apps names in apps drawer. Some launchers blur the wallpaper in apps drawer to clearly the view the apps. If possible do that to Niagara launcher.

### Describe the solution you'd like

Update

**Comment by Maxr1998** [comment]
Please see my last comment in #1674 for why this isn't possible right now.

**Comment by Amorphous404** [comment]
Duplicate of #14
