### ISSUE TITLE
Search Ui needs to be consistent

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1749]
### Is your feature request related to a problem?

Hey I'm suggesting a ui refresh for the search ui of Niagara... It isn't consistent with any other Niagara screens.. the Niagara settings background, pop-up folder background and the agenda widget background all have either a dark or light background depending on the theme but the search seems to have a transparent background.. for anyone having a lot going on in his wallpaper the search results seems to be illegible to some extend.. 

### Describe the solution you'd like

Make the search ui have the same background color as the pop-up folder or the agenda widget...

And also make sesame more integrated with Niagara and the ability to see the search results from bottom to top.. rather than just top to bottom providing the results an easy reach...

**Comment by Maxr1998** [comment]
The search is a simple screen similar to the app list and favorites, thus I don't see a full re-design as necessary. For better legibility, I recommend using a wallpaper with good contrast, and experimenting with the text color options. For what it's worth, there'll be  a change in the near future which should resolve your concerns, so please look forward to that. Can't say much more for now :wink:
