### ISSUE TITLE
Remap google button to different app

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#175]
There should be an ability to remap the google button on favorites and change the icon to something from an icon pack or gallery

**Comment by 8bitPit** [comment]
Yeah, it has low priority though.

**Comment by silpack69** [comment]
mayb just remap it to assistant instead of search.  who uses search anymore :D

**Comment by Shinra04** [comment]
Tap and hold home to open assistant. That's hard-coded into all Android by now, right?

**Comment by 8bitPit** [comment]
@Shinra04 yes, I cannot override the home button's long press gesture

**Comment by 8bitPit** [comment]
The button might be even remappable to other actions, for example "open Niagara's search", "open folder" or "show widget"

**Comment by 8bitPit** [comment]
Merged with #300
