### ISSUE TITLE
[Request] gesture on homescreen 

### ISSUE THREAD

**Issue by JONI350** [8bitPit/Niagara-Issues#1751]
### Is your feature request related to a problem?

Not a problem, i feel like this could improve a lot and help to have even less things on homescreen basically and a easy access to them improving focus

### Describe the solution you'd like

Basically select the app u want to be opening with the swipe left or right, for this to be more consistent u could disable pop ups on apps tho, so u could do like this, on any part of the screen, if disabling pop ups isnt a valid point then u would be able to do so on places without apps on screen tho

https://user-images.githubusercontent.com/25126715/142749115-e17dbbe2-8815-4f1f-bf3f-b0314d4302ba.mp4

The config would just looks as simple as this
![Polish_20211121_010801760](https://user-images.githubusercontent.com/25126715/142749231-4629104c-e69f-41df-a082-25d7f086152f.jpg)

**Comment by Maxr1998** [comment]
That would, as you said, interfere with other gestures in the launcher, and reduce the risk of accidental inputs. It also doesn't provide much value, as it's barely quicker or even slower than just launching an app in the favorites, the only benefit would be a visual one for a small set of users - at the same time, and would complicate the experience for everyone else, so we don't plan to implement this.
