### ISSUE TITLE
Wind data

### ISSUE THREAD

**Issue by NIKLSON2** [8bitPit/Niagara-Issues#1755]
### Is your feature request related to a problem?

Hello! The wind decides quite a lot in my country: it's cold when it's there, and warm when it isn't. 

### Describe the solution you'd like

I would like to see wind speed information somewhere in an open weather widget.

**Comment by tjsuominen** [comment]
Then I recommend to utilize a third party weather app and widget for such info. Plenty to choose from.

**Comment by Maxr1998** [comment]
We thought about this, but unfortunately it'd make the weather interface too crowded and confusing. As @tjsuominen said, you could just use a third-party weather app for this, e.g. [OpenWeather](https://play.google.com/store/apps/details?id=uk.co.openweather), which uses the exact same data.
Pro-tip: when you long-press the hourly weather view in Niagara, it'll launch OpenWeather for you.

**Comment by NIKLSON2** [comment]
Great answer, meaning "I can't develop this." I could download a
third-party widget at any time if I wanted to. But I want to see the wind
in the embedded widget. If you can't or don't just have no desire to do
this function, then say so, no need to mention the possibility of
downloading third-party widgets.
