### ISSUE TITLE
Option to hide predefined replies in home screen notifications

### ISSUE THREAD

**Issue by luxcalor** [8bitPit/Niagara-Issues#1756]
### Describe the solution you'd like

I just never use these ready made replies. They take a lot of space in pop-up folders and I would rather see all the unread notifications (as it was at some point before) instead of just the last one with replies.

To clarify, I mean "yes", "no", "will get to you later" etc suggested replies and not "reply to", "mark as read", "archive" action buttons. The latter ones are very useful.

**Comment by Maxr1998** [comment]
We show the same suggestions as the Android OS, having a toggle for those doesn't fit Niagara's design principles, as an option like this wouldn't be impactful enough to be warranted. However, I think you can completely disable smart replies in the system settings, for all apps. That should also disable them in Niagara Launcher.

**Comment by luxcalor** [comment]
I currently use Niagara on an Android 6 device, and there are no smart replies whatsoever outside of Niagara and no option for this in settings. But I get your point.
