### ISSUE TITLE
Notification summary

### ISSUE THREAD

**Issue by RPM28XI** [8bitPit/Niagara-Issues#1758]
### Is your feature request related to a problem?

Current Notification  Summary took a lot of space. Can you format as attached photo.

### Describe the solution you'd like

Floating one row summary over favorites app list with icons of notifying apps for added clarity.
![Screenshot_20211130-130241_Niagara Launcher](https://user-images.githubusercontent.com/8072208/143995116-a1517b50-38a4-4d5c-90d7-a1e0007bb8db.jpg)
![PicsArt_21-11-30_13-11-12-157](https://user-images.githubusercontent.com/8072208/143995117-6e36e597-62c7-4faf-9516-f180b7f3261f.png)

**Comment by Maxr1998** [comment]
I don't think that'd fit in with our current design, and might make the notification summary less visible. Using the same style and layout as all the other apps and tips is a conscious decision.

I'd suggest you to set Niagara as default launcher though, and if you can't, [use `/suppresssetlauncherprompt`](https://help.niagaralauncher.app/article/74-entering-hidden-commands) :wink:
