### ISSUE TITLE
[Request] Other directions to niagara button

### ISSUE THREAD

**Issue by JONI350** [8bitPit/Niagara-Issues#1759]
### Is your feature request related to a problem?

Not a problem, imo the niagara button could have swipe down left and right interactions too, and imo its a simple and useful feature

### Describe the solution you'd like

Basically just what i said there isnt much to elaborate about, I'm gonna leave a pic here just in case tho

![Polish_20211201_031909106](https://user-images.githubusercontent.com/25126715/144182609-205f3e24-41dc-4445-96ae-a7a73a75c7fe.jpg)

**Comment by Maxr1998** [comment]
Please see "Why can we only utilize one swipe gesture?" in [this article](https://help.niagaralauncher.app/article/116-niagara-button).

**Comment by Amorphous404** [comment]
Duplicate of #1641

**Comment by Amorphous404** [comment]
- Duplicate of #1641
