### ISSUE TITLE
[Request] Option to completely remove app drawer

### ISSUE THREAD

**Issue by JONI350** [8bitPit/Niagara-Issues#1760]
### Is your feature request related to a problem?

Somewhat a problem? Basically i have an widget that if i select to fill the screen i just cant use its functions because i click on alphabet, i also was just messing around to use only the search option instead so it'd be extra useful in my case

### Describe the solution you'd like

Basically just add a option to hide/remove drawer, like even tho if u hide all apps it stills showing this screen

![Screenshot_20211201-031919_Niagara Launcher](https://user-images.githubusercontent.com/25126715/144183053-ed8ed911-257d-4828-b6ce-a6d7274a3767.jpg)

https://user-images.githubusercontent.com/25126715/144183766-158efd8d-beac-440b-97a5-472c503eb1da.mp4

Like here when i try to like a song

**Comment by Maxr1998** [comment]
Don't use the full-width widget option if it interferes with the alphabet, see this for more info: #1714. Regardless, we don't intend to allow hiding the app drawer, this is not how Niagara is intended to be used, and it contradicts heavily with our [design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles).
