### ISSUE TITLE
Suggestion: Add "Recently installed apps" as suggestions when editing folder pop-ups

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#1763]
I often like to categorise new apps I just installed, into folders I've already got. It would be so much easier to have them suggested right in the edit screen instead of me needs to manually look for each new app from my apps list.

**Comment by luxcalor** [comment]
Agreed, that would be awesome.

**Comment by 8bitPit** [comment]
Oh, that's smart, great idea!

**Comment by 8bitPit** [comment]
Added in v.1.6

**Comment by Shinra04** [comment]
Weell, you got it half-way, or rather, solved a slightly different hindrance,

It would be great if while you're choosing which apps to add into a selected folder, the "Recently installed" list of apps are also present under the Advanced label (currently you only see hidden apps).

**Comment by 8bitPit** [comment]
@Shinra04 In addition to the recently installed apps section, recently installed apps (I believe they have to be less than 3 days old) should be listed at the top under "suggestions" when you add a folder. These are not necessarily the same apps that show in the recently installed section (because those in the section stay longer there), but this should still solve the problem for your use case, right?

**Comment by Shinra04** [comment]
> @Shinra04 In addition to the recently installed apps section, recently installed apps (I believe they have to be less than 3 days old) should be listed at the top under "suggestions" when you add a folder. These are not necessarily the same apps that show in the recently installed section (because those in the section stay longer there), but this should still solve the problem for your use case, right?

Ohh yes, you're right. I'm not sure how I missed that, was this always there or only recently added? Anyway, my bad for not noticing, haha. 

The recently installed folder is really handy though! I use it way more than some of my other folder that are just collecting dust down below.

**Comment by 8bitPit** [comment]
> Ohh yes, you're right. I'm not sure how I missed that, was this always there or only recently added? Anyway, my bad for not noticing, haha.

We added that in v1.6 :D

> The recently installed folder is really handy though! I use it way more than some of my other folder that are just collecting dust down below.

Thank you very much - and thanks again for your suggestion!
