### ISSUE TITLE
Support multiple widgets in pop-ups

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1764]
### Is your feature request related to a problem?

I use a lot of widgets and there isn't that much space to work with...

### Describe the solution you'd like

Including the possibility of adding more than one widget to a pop up folder and the ability to resize them individually would permit an important role of widgets...

**Comment by 8bitPit** [comment]
Thanks for your request, @missyraja :) We discussed this a few times internally and are still not sure whether we should support multiple widgets in pop-ups (we're not fans of widget pages: https://help.niagaralauncher.app/article/41-adding-multiple-widgets). Can I ask you which devices you'd put in the same pop-up?

**Comment by missyraja** [comment]
@8bitPit  thanks for noticing this... I too feel a widget page is slightly off than what Niagara is trying to accomplish.. and I'm not interested in multiple widgets on the home screen... 

The pop-up folders you guys have come up with is Highly functional and yet i feel there are more potential to them..

I have 5 apps currently as my favourites.. each app would have two to four apps and probably a widget in each pop-up...

The problem arises when i have productivity apps compiled into one folder and each app has their own widget.. now i have to place them either in a different folder or not use them for quick interactions...

After the introduction of a12 widgets seem to coming back in fashion and for the kwgt users they have always been a form of self expression and functionality....

I know you guys are pretty good with minimalism and productivity so i hope you guys find someway for widgets to have more space in Niagara..

Wishing you guys luck..

**Comment by E0697** [comment]
Please add support for this.
It's much more convenient than having to use a seperate popup for every widget, which would take a lot of extra space.

**Comment by 8bitPit** [comment]
Implemented in v.1.9.1 🎈https://github.com/8bitPit/Niagara-Issues/releases
