### ISSUE TITLE
More customisation options for two-column layout

### ISSUE THREAD

**Issue by Not-Dhanraj** [8bitPit/Niagara-Issues#1766]
When two column layout is enabled all apps are always in two columns. And in big screen devices while changing landscape to potrait there is a big empty space
![Screenshot_20211204-080156_Niagara Launcher](https://user-images.githubusercontent.com/80586983/144693827-a1d9e189-d529-4d4b-9509-77e576f3bf5e.jpg)
![Screenshot_20211204-080143_Niagara Launcher](https://user-images.githubusercontent.com/80586983/144693835-cb11072b-2f11-43ca-b14e-8f3d51291e1f.jpg)
.

### Describe the solution you'd like

That would be great if there could be an option for two column layout in landscape mode/potrait mode only.

**Comment by TFackler** [comment]
Hello and thanks for reaching out.

We had thought about this and the two column mode will automatically revert to one column in prortrait mode, if there is not enough space for two. In your case it seems like your tablet is... too big :D 

We hope this doesn't bother you too much. Please reach out again, if it does.

Closed for now.
