### ISSUE TITLE
Floating Niagara Button

### ISSUE THREAD

**Issue by foenicxxx** [8bitPit/Niagara-Issues#1767]
Why not to have the Niagara button floating over the apps too with an option to enabled or disabled?😜

**Comment by Maxr1998** [comment]
Niagara button already floats over the apps in a way, so I'm not exactly sure what you mean. Could you elaborate on this please?

**Comment by foenicxxx** [comment]
I mentioned in the telegram group too (https://t.me/niagara_launcher). As directed by the Moderator of that group, I raised this. Easy to understand with and example, I am reading a pdf file on my android device, I come across a word for which I need to find a meaning, if the Niagara button floats over that pdf reader app which is already assigned with installed dictionary app by upward gesture, I can just switch over to that dictionary app with that gesture.

https://play.google.com/store/apps/details?id=com.easytouch.assistivetouch

It's something like the above app, but with the Niagara button which has all gestures. Now the button has only two, touch and upward swipe. If the button has other gestures too like downward, left and right and even double and triple taps which can be assigned as per the user's choice.

I understand, it is a long way to go and launcher too would become heavy. Hope you developers will definitely find a way for it. It's like shortcut to some apps which the user frequently jumps to from the Niagara button itself which keeps floating over any other app.

**Comment by Maxr1998** [comment]
Thanks for the detailed explanation.
Regarding other gestures on the button, we have our reasonings for why we don't support this lined out [in our knowledge base](https://help.niagaralauncher.app/article/116-niagara-button).
Making Niagara Button available globally in all apps is unfortunately out of scope for a launcher, and doesn't fit [Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

**Comment by foenicxxx** [comment]
Hmm. Gone through your links and understood your 'valid' points. Anyway thanks. I'll have to make or use an alternate one....👍
