### ISSUE TITLE
I want to use multiple widgets at the same time at Niagara Launcher.

### ISSUE THREAD

**Issue by whaaatsup** [8bitPit/Niagara-Issues#1768]
### Is your feature request related to a problem?

It is inconvenient that multiple widgets cannot be used on one screen at Niagara Launcher like other Launchers.

### Describe the solution you'd like

Niagara Launcher would also be good to support functions such as the iPhone's stack widget.

**Comment by 8bitPit** [comment]
Hi there, thanks for your request. You can also widgets to pop-ups with Niagara Pro: https://help.niagaralauncher.app/article/41-adding-multiple-widgets. Moreover, we might support adding multiple widgets to one pop-up: https://github.com/8bitPit/Niagara-Issues/issues/1764
