### ISSUE TITLE
Used Material You colors do not update when changed

### ISSUE THREAD

**Issue by atzarul** [8bitPit/Niagara-Issues#1769]
### Describe the bug
Niagara launcher does not change used theme colors (material you colors) after a different set was than the default one was selected on 'Wallpaper & style'

### Steps to reproduce

1. Change your wallpaper. The default Material You colors is automatically selected by Android 12 and Niagara uses them.
2. Open the wallpaper picker again and choose a different Material You colors set (from the 4 given choices)

Expected result: Niagara updates its Material You used colors.
Actual result: It doesn't.

### Device name

Google Pixel 6

### Android version

Android 12

### Screenshots / Screen recordings

<img src="https://user-images.githubusercontent.com/9862423/145406297-3f7c6d54-d36a-4d2c-9a94-2fa96cb169ff.png" width=500/>
<img src="https://user-images.githubusercontent.com/9862423/145406342-182bd14c-55c4-40e2-bf4a-463a40c31d44.png" width=500/>
<img src="https://user-images.githubusercontent.com/9862423/145406472-490e163e-e34a-4938-89b1-4c32eb5a83af.png" width=500/>

**Comment by Maxr1998** [comment]
Interesting, it looks like Android 12 refreshes the launcher when setting a wallpaper, but not when changing the colors. This seems like an oversight in the framework, but we'll probably have to add a workaround for it.
Does a launcher restart fix it?

**Comment by atzarul** [comment]
No, it does not, as far as I can tell.

But maybe my expectations here are wrong. It seems (when I've used another wallpaper) that you're not actually using that Material You accent color (even when using the default set), but still derive it yourself. I guess it's a coincidence that for some wallpapers your derived color matches the material you default color. Not sure what to expect anymore.
