### ISSUE TITLE
Uninstalling Dual Messenger apps removes all icons for that app from the launcher

### ISSUE THREAD

**Issue by BluDragyn** [8bitPit/Niagara-Issues#177]
Had WhatsApp, Skype, Snapchat, and Telegram installed twice via Dual Messenger on my S9+ (SM-G965U), and uninstalling any of them results in the "main" icon being removed as well. (i.e. uninstall second copy of Telegram, and the remaining copy has no icon in Niagara). 

Restarting the launcher bring it back, but removes usage data.

**Comment by 8bitPit** [comment]
fixed in version 0.5.0
