### ISSUE TITLE
[Request] toggle to disable the background tint on app drawer

### ISSUE THREAD

**Issue by JONI350** [8bitPit/Niagara-Issues#1770]
### Is your feature request related to a problem?

Somewhat a problem, the tint seems not smooth and it let the thing kinda ugly(at least with my wallpaper) so it'd be nice if there was a toggle to disable it tho

### Describe the solution you'd like

Just a plain simple toggle

**Comment by Maxr1998** [comment]
Since this has been widely requested, we're working on adding a toggle and will probably roll it out on the next update.

**Comment by ravtakhar** [comment]
@Maxr1998 I have been manually tinting my wallpapers for a very long time. Are you able to add the opposite as well? 

-- The ability to add a default tint to the homescreen as well.

**Comment by Rod911** [comment]
As of v1.5.1 You can disable the wallpaper tint from Settings > Look > Tint wallpaper.

**Comment by Maxr1998** [comment]
@ravtakhar could you create a new issue for your use-case please?
