### ISSUE TITLE
Improve gesture navigation using accessibility service

### ISSUE THREAD

**Issue by DamonBaker** [8bitPit/Niagara-Issues#1773]
https://developer.android.com/reference/android/accessibilityservice/AccessibilityService#GLOBAL_ACTION_RECENTS

One of drawbacks of Android's gesture navigation with third party launchers is the annoying delay when swiping up to access recents. (At least on Samsung, not sure about other devices)

An option to change the "swipe up to search" feature to open recents instead would be really nice to have, as it would fix the and could also be a productivity feature for users even if they're not using gesture navigation.

The Microsoft launcher has a similar feature, where you can assign a gesture to open the recents screen.

**Comment by TFackler** [comment]
Hi and thanks for reaching out :)

Adding a workaround in order to reduce the delay on a gesture for a portion of our userbase seems like a lot of bloat for a relatively small return. In addition to that, there will be users who don't want this functionality and thus a toggle would be needed to enable or disable this feature.
At this point in time we don't feel like it would be worth the tradeoffs and therefore we won't add this feature, sadly.

Closed.

**Comment by AndyL964** [comment]
> Hi and thanks for reaching out :)
> 
> Adding a workaround in order to reduce the delay on a gesture for a portion of our userbase seems like a lot of bloat for a relatively small return. In addition to that, there will be users who don't want this functionality and thus a toggle would be needed to enable or disable this feature. At this point in time we don't feel like it would be worth the tradeoffs and therefore we won't add this feature, sadly.
> 
> Closed.

You don't have to add anotjer toggle. You can just have this take place whenever the Swipe up to search feature is disabled since in that case the home gesture wouldn't anything anyway.

This delay is reportedly fixed in Android 13 but yet to be fully confirmed.

**Comment by TFackler** [comment]
> You don't have to add another toggle. You can have Recents take its place when the Swipe up to search feature is disabled since in that case the home gesture wouldn't do anything anyway.
For Niagara to open the recent apps screen, it would need access to the `accessibility` permission, which is a rather powerful permission. In addition to have this behaviour enabled by default, we would have to go through the process of multiple checks for the accessibility permission being granted by default.

We don't feel like it would justify requiring this permission.

> This delay is reportedly fixed in Android 13 but yet to be fully confirmed.

Thanks for letting us know :)

**Comment by AndyL964** [comment]
> > For Niagara to open the recent apps screen, it would need access to the `accessibility` permission, which is a rather powerful permission. In addition to have this behaviour enabled by default, we would have to go through the process of multiple checks for the accessibility permission being granted by default.
You already use the Accessibility permission for quick-lock gesture. There's no need to make it enabled by default; if people don't find it annoying then they can leave it off just like with the wallpaper offset feature.

**Comment by TFackler** [comment]
If we don't enable it by default it would require a toggle. 

If it is enabled by default, Niagara will require the accessibility permission by default too, and we don't want a permission that powerful to be requested by default.

In addition to that, this feature would only benefit a relatively small amount of users.

So we don't feel like it would be worth the tradeoffs.

**Comment by AndyL964** [comment]
> > This delay is reportedly fixed in Android 13 but yet to be fully confirmed.
> 
> Thanks for letting us know :)
Welp, unfortunately as it is, it remains unfixed in One UI 5.


> If we don't enable it by default it would require a toggle.
> 
> If it is enabled by default, Niagara will require the accessibility permission by default too, and we don't want a permission that powerful to be requested by default.
> 
> In addition to that, this feature would only benefit a relatively small amount of users.
> 
> So we don't feel like it would be worth the tradeoffs.
Isn't there already a toggle in settings? You could just prompt or bring the user to go there and enable it.
