### ISSUE TITLE
Remove Black Border Around Notification Inline Reply Box

### ISSUE THREAD

**Issue by sweet00th** [8bitPit/Niagara-Issues#1775]
### Is your feature request related to a problem?

The black border around notification inline reply box is ugly and archaic.

### Describe the solution you'd like

A more Google-ly borderless semi-transparent reply box looks much better and fits well with the Android 12 modern aesthetic.

**Comment by 8bitPit** [comment]
Apologies for the one-year delay, we have missed your ticket 😅 The border's color should be tinted in your wallpapers main color or primary Material You color. Could it be a bug that it's not taking that color?
