### ISSUE TITLE
Notes - Section 

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1776]
### Is your feature request related to a problem?

A quick notes section would increase the value of Niagara Launcher because the user don't have to search for extra 3rd party apps. Also, it would help users to increase their productivity because it would be always there fast and easy. (shopping list, quick notes, copy and paste info for later, etc.) 
Also, I feel it would fit perfectly Niagara's philosophy. 
As being a proper section of Niagara, you could give it your excellent touch (design) as well as it would fit perfectly. It would be something uselful for everyone. 

Also, it would be great if the user can create a backup data where it saves the Niagara's settings and notes if they chage their phone or something happens. 

### Describe the solution you'd like

![Screenshot_2021-12-12-20-19-18-571_bitpit launcher_1](https://user-images.githubusercontent.com/72170242/145750955-42debecb-894a-4168-8b70-cfe7dd461bb8.jpg)

Or

![Screenshot_2021-12-12-20-58-21-298_bitpit launcher_1](https://user-images.githubusercontent.com/72170242/145750920-6630a6b0-6db3-472a-8069-e2fa3159f1d5.jpg)

**Comment by TFackler** [comment]
Hello, thanks for reaching out and thank you for the mock-ups :)

Regarding adding notes to Niagara:
One of our design principles is too keep Niagara clean and simple, therefore adding a lot of features, which fall into the domain of other apps is something we are wary of.
We are however currently thinking about adding or better integrating a todo list into Niagara (#1285), which might cover a part of your request. Should we decide to integrate said todo list, we might also consider notes.

Regarding backing up of settings:
We are already considering this. Please see #222 :)

Closed.

**Comment by TFackler** [comment]
@Just-SKY wrote a small tutorial how to set up something similar as the requested feature, which you can read [here](https://github.com/8bitPit/Niagara-Issues/issues/2052#issuecomment-1242740038).
Thank you for that :)
