### ISSUE TITLE
App icons appear smudgy when at lower PPI

### ISSUE THREAD

**Issue by Dinjoralo** [8bitPit/Niagara-Issues#1777]
### Describe the bug

When using Niagara on my tablet with a much lower PPI than my phone, certain app icons have a smudgy, low-res-upscaled look. These apps look crisp when at higher resolutions in other launchers, which indicates it is an issue with Niagara.

### Steps to reproduce

1. Install an app such as Vivaldi Browser
2. Go to developer options and set the "Smallest Width" to a very high value, like 752
3. View icon for Vivaldi Browser in launcher

### Device name

Amazon Fire HD 10 2019

### Android version

Android 9 (Pie)

### Screenshots / Screen recordings

![Screenshot_2021-13_11-04](https://user-images.githubusercontent.com/2925248/145857201-880ba21e-75dd-47ba-8697-099cfe1f4766.png)

**Comment by Maxr1998** [comment]
You're right, I've recently noticed this too. There might be a bug in the code we use to render the icons. I'll open an internal ticket to look at this.

**Comment by topsy-turvy99** [comment]
> You're right, I've recently noticed this too. There might be a bug in the code we use to render the icons. I'll open an internal ticket to look at this.

I use my at around 512 dp, but i tried in other dp too, but i feel icons in Niagara looks less sharp, i tried comparing with other launchers too, like Nova and smart launcher side by side, it does looks that way

**Comment by 8bitPit** [comment]
You're both correct and happy to tell you that we fixed this in v1.7: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b
