### ISSUE TITLE
Folders in the app drawer / make hidden section easier to access

### ISSUE THREAD

**Issue by dark5un0** [8bitPit/Niagara-Issues#1778]
### Is your feature request related to a problem?

_Hi, long term follower (was a pro user at the start but got a refund since I didn't use the app cause of this issue but back to being pro again) but not user till recently because I have a ton of apps which I don't want to yet / ever uninstall but want to have in a folder rather than cluttering up the app list. Some are infrequent ones yet having about 6/8 is daunting. Sometimes I might forget a name & going to the hidden section is a few too many steps._ **Thus I propose:**

1. Either have folders / single omni folder that is also in the app list like the favorites * or the settings O.. To put any infrequent extras OR
**2. Give the option to make available the hidden folder for those who use it as a storage (which I prefer than above even since it's also alphabetically organized already).**

### Describe the solution you'd like

Give the option to make available the hidden folder for those who use it as a storage (which I prefer than above even since it's also alphabetically organized already).

**Comment by Heptameron123** [comment]
I am sure of the need to hide with quick access confidential data, and in the image one of the simple options, to hide this misunderstanding:
![Screenshot_20211223_102029](https://user-images.githubusercontent.com/93233919/147208007-434d59b8-adf6-455c-8d84-1ff87ef4dc2e.jpg)

**Comment by Heptameron123** [comment]
>

 You can do this using the available functions - by creating a folder with the necessary applications without removing them from the list of hidden ones.

**Comment by Heptameron123** [comment]
> > 
> 
> Сделать это можно с помощью доступных функций - создав папку с необходимыми приложениями, не удаляя их из списка скрытых.

... otherwise there is no point in this function.

**Comment by Oddward** [comment]
I'll close this issue, ya?

You can do this by:

- create a folder pop-up (edit favourites > scroll to the bottom > create folder)
- add your apps to the folder, or add them from the hidden app list (edit pop-up > scroll to bottom > hidden apps)
- move the folder to the app list _(long-press > show in app list)_ - all folders will be grouped at the bottom of the app list
- hide your unwanted apps
