### ISSUE TITLE
Niagara auto-reply feature

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1785]
### Is your feature request related to a problem?

Sometimes when you are working or busy, and you dont want to waste time or cannot replay to messages because you are at school, work, gym, etc. Those messages reduce your productivity and increase distractions. However, at the same time you wish you could respond those messages to let the people know that you cannot respond at the moment without wasting time. 

### Describe the solution you'd like

It would be great if there were a way in which your cellphone autoreplay (with auto programmed text messages by the user) to those incoming messages for you. In order to work, the user can choose which apps they want to activate the auto replay function, like the summary feature that it's already implemented. So, when you receive a notification fro m those apps in particular, niagara can autoreplay. 

Or al lest, show you in the screen (like summary) if you wish to autoreplay (without showing you the messages, in order to do not distract you) where you touch and respond without reading the message or wasting time. 

 This kind of feature helps both the receiver (you) and helps the sender because they will know that you are busy or can't respond at the moment (depending of the situation). It would be very uselful and would help with productivity as well. 

**This feature can be integrated with the focus mode.**
 
Here is an ides of how it could be implemented. 
![Screenshot_2021-12-23-14-47-03-276_com bllocosn_1](https://user-images.githubusercontent.com/72170242/147367715-b586a5f9-acc6-44df-87dd-2ff758f358f8.jpg)
![Screenshot_2021-12-23-14-47-00-770_com bllocosn_1](https://user-images.githubusercontent.com/72170242/147367718-f990ac91-c91e-40ee-901b-c2209a771beb.jpg)
![Screenshot_2021-12-23-14-47-24-147_com bllocosn_1](https://user-images.githubusercontent.com/72170242/147367963-dc81ded6-0796-4837-ba59-05861f5e360a.jpg)

**Comment by Maxr1998** [comment]
While this sounds like a useful feature, and I do like the style of your mock-ups, I think this is out-of-scope for Niagara, thus unlikely to be implemented.
