### ISSUE TITLE
Some weather conditions are untranslated in Turkish

### ISSUE THREAD

**Issue by Sparrow34tr** [8bitPit/Niagara-Issues#1786]
![IMG_20211216_092558](https://user-images.githubusercontent.com/61355386/147501437-a1f8db2d-17a5-4e21-8237-898afbd858f3.jpg)

**Comment by 8bitPit** [comment]
Hi @Sparrow34tr, thanks for letting us know. OpenWeather provides the weather translations for weather conditions. It would be great if you write them that one translation string is missing: https://help.niagaralauncher.app/article/105-weather-widget#:~:text=Why%20are%20some,openweathermap.org/questions.

**Comment by Sparrow34tr** [comment]
> Merhaba @Sparrow34tr, bize bildirdiğiniz için teşekkür ederiz. OpenWeather, hava koşulları için hava durumu çevirileri sağlar. Onlara bir çeviri dizesinin eksik olduğunu yazarsanız harika olur: https://help.niagaralauncher.app/article/105-weather-widget#:~:text=Why%20are%20some,openweathermap.org/questions.

![image](https://user-images.githubusercontent.com/61355386/162542995-5f241a24-f4d2-4d0c-bef4-ead17ec1b67e.png)

**Comment by Maxr1998** [comment]
@Sparrow34tr Here's the API URL we use: `https://pro.openweathermap.org/data/2.5/onecall?lat=<redacted>&lon=<redacted>&appid=<redacted>&exclude=alerts&units=metric&lang=tr`.
Let us know if they need anything else from us.
