### ISSUE TITLE
Add sensitivity configuration to swipe gestures

### ISSUE THREAD

**Issue by thinkscape-gmbh** [8bitPit/Niagara-Issues#1788]
### Is your feature request related to a problem?

The request consists of 2 related issues:

1. Location: Homescreen. If you want to access the notification or settings bar on top of the screen you can swipe down from anywhere on the screen. In many cases I rather scroll the applications on the home screen down instead of getting the notfication / settings bar down. 

2. Accessing the application overview with a swipe up gesture is very slow on Niagara Launcher compared to stock Android. You swipe up and need to wait for some time until you can access the application overview.

Both use cases are very common and done very often on daily basis. Therefore the waiting times for the application overview and the inconsisten behaviour to access the notification / settings bar is very annoying and time consuming. 

### Describe the solution you'd like

It would maybe help if you can configure the sensitivity so users can adjust to their preferences.

**Comment by ljmusg** [comment]
+1

I also have trouble with the pop up folders on apps. Usually I'm scrolling the app list several times before I manage to open the pop up folder.
