### ISSUE TITLE
Weather unreliable / weather without location service

### ISSUE THREAD

**Issue by maskyad** [8bitPit/Niagara-Issues#179]
I hope the weather app could work without the location activate. Something like "favourite list is places" and u choose one for show the weather.

**Comment by 8bitPit** [comment]
I am using Google's Awareness API and it doesn't let you choose a manual location. I would have to use another weather provider for that, so it's not that easy.

**Comment by jakcharvat** [comment]
Wouldn't it be possible to somehow trick awareness API into thinking you're here/there? Or would that require mock location access?

**Comment by Scorpionk1** [comment]
Dark Sky provides an API for free

**Comment by Scorpionk1** [comment]
Dark Sky fornece uma API gratuitamente.

**Comment by jakcharvat** [comment]
@Scorpionk1 Sorry, I am Czech, the developer is German, the common language is English. Please stick to that

**Comment by Scorpionk1** [comment]
Dark Sky has free APIs. I do not know if you can disable the location.

**Comment by Shinra04** [comment]
Is there any way to fix your location to a place, requiring you to only temporarily switch on location when you're going to a different place. It would be a neat fix, as I too don't like leaving my location on.

**Comment by 8bitPit** [comment]
@Scorpionk1 it's not completely free:
`The first 1,000 API requests you make every day are free of charge.`
`Every API request over the free daily limit costs $0.0001.`

**Comment by 8bitPit** [comment]
@Shinra04 that's not possible with Google Awareness, sry

**Comment by Nik-Sch** [comment]
So, I don't really know whether this is helpful or not. My i3bar uses "the" yahoo weather api and this works with no problems and also without any api key; at least as far as I can tell. It just requires a woeid (where on earth identifier) and then calls this url: [https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where woeid="26821871" and u="C"&format=json&env=store://datatables.org/alltableswithkeys](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid=%2226821871%22%20and%20u=%22C%22&format=json&env=store://datatables.org/alltableswithkeys) (here woeid is set to Berlin, Germany).
If you want to look further into the code, here is the github link: [github:ultrabug/py3status](https://github.com/ultrabug/py3status/blob/master/py3status/modules/weather_yahoo.py).

However, my problem is that I couldn't quickly find any decent documentation on Yahoos website about this and I am kind of bothered by the `env=store://datatables.org/alltableswithkeys` thingy at the end of the url as it suggests being a pirated keystore or something?!
Just wanted to share this with you, in case this is a good alternative to the google awareness api :)

**Comment by 8bitPit** [comment]
Thanks @Nik-Sch. Unfortunately Yahoo will shut down the service, they wrote: 

> The weather.yahooapis.com and fallback endpoints are being retired. We will no longer be providing free Weather API services for public users. 
Please contact yahoo-weather-ydn-api@oath.com if you have any questions, comments, or interest in supported paid services.

([source](https://developer.yahoo.com/weather/?guccounter=1))

**Comment by deadcombo** [comment]
You can always use OpenWeatherMap, for example.

**Comment by 8bitPit** [comment]
@deadcombo OpenWeatherMap is not free, unless you have less than 60 calls per minute: https://openweathermap.org/price Unfortunately that's not enough for Niagara, it would cost 40$/month

**Comment by CircleYuanX** [comment]
And when it is not showing whether information on the home screen with telling me the information is "currently unreliable" in the setting, it keep requesting the location information.
Sticking to a place is needed, and I want to see the weather information no matter it's reliable or not. Because when it disappears, I feel like I paid for something but didn't get anything back…

**Comment by Vv2233Bb** [comment]
Is it not possible to fetch the info from a preinstalled weather app. Most phones have some sort of a weather map preinstalled.

**Comment by 8bitPit** [comment]
@Vv2233Bb It's not possible by default, those apps would have to provide an API, so Niagara can request/receive data.

**Comment by 8bitPit** [comment]
@CircleYuanX If the launcher has weather data, it will show it to you, whether it's reliable or not.

**Comment by Vv2233Bb** [comment]
@8bitPit what about widgets?

**Comment by 8bitPit** [comment]
@Vv2233Bb yeah, that would work. Widget support is planned: https://github.com/8bitPit/Niagara-Issues/issues/117

**Comment by sauces1313** [comment]
A suggestion: if you could classify weather apps like you have music players (I think) for the favorites/home screen persistent notification, everyone could just continue using whatever weather app they have, basically all of them have persistent notifications. On-screen location would be virtually the same also.

**Comment by OceTech** [comment]
Weather works great in my location.

**Comment by debdipta-h** [comment]
Weather working great in my location. Thanks a lot for this awesome launcher @8bitPit.

**Comment by 8bitPit** [comment]
@debdipta-h Great to hear that it's working, thank you :)

**Comment by 8bitPit** [comment]
Some of you suggest to let the user provide his own API key, but personally I'm against it because of two reasons:

1. My goal with Niagara is to create a very simple and clean launcher. Providing weather data without having the user to go through to the step of setting up an account and generating his id is way easier.

2. An API key is a unique identifier to track how many calls a service, e.g. an app already has requested. Having the user generate its own id which he can use with his app is shady, because as a result one app would have multiple API keys to circumvent the free calls limit deliberately. OpenweatherMap doesn’t mention such abuse specifically in their TOS, like Dark Sky does for example, at least I didn’t find something. But I believe it’s shady and in a legal gray area.

**Comment by 8bitPit** [comment]
See #1016

**Comment by adguardgirl** [comment]
Would it be possible to implement weather through the name of the city you are located in? For example some launchers allow you to enter the city name (and postal code if needed).

**Comment by 8bitPit** [comment]
Hey @adguardgirl, sure! You can already type in your city when choosing the location for weather forecast.
