### ISSUE TITLE
Well being feature. Screen time

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1791]
In pop up if we could get app usage time ex. 24 min., then it might be a good feature for digital wellbeing, though screen time we are able to reach after long tapping an app. But if you think it's good then ☺️. 

This feature could take space in front of app's name or below the app's name...

Thanks![Screenshot_20211230_053120.jpg](https://user-images.githubusercontent.com/96849717/147712261-74d50abc-7047-4c40-915c-79fbd2d208e6.jpg)

**Comment by Maxr1998** [comment]
Unfortunately, the Digital Wellbeing app doesn't publish screen times to other apps, so we have no means to display them.
