### ISSUE TITLE
Widgets do not update in Airplane mode 

### ISSUE THREAD

**Issue by luxcalor** [8bitPit/Niagara-Issues#1792]
### Describe the bug

When in Airplane mode widgets in Niagara immediately stop updating. I mean widgets showing time, calendar and other offline data. Restarting Niagara brings everything up to date momentarily, only to go out of sync next minute. 
After exiting airplane mode and restarting Niagara everything works fine. All battery optimizations are switched off for Niagara and related applications, background operation allowed. This was not the case before last update. 

### Steps to reproduce

1. Switch Airplane mode on
2. Observe widgets stop updating
3. Switch Airplane mode off
4. Restart Niagara and everything is back to normal. 

### Device name

Meizu Pro 6

### Android version

Android 6.0 (Marshmallow)

**Comment by timm0e** [comment]
Hey :wave: 

In the Spring Clean update, we addressed an issue with widgets freezing. Did the update also fix it for you?
