### ISSUE TITLE
Nested folders 

### ISSUE THREAD

**Issue by northmendo** [8bitPit/Niagara-Issues#1794]
### Describe the solution you'd like

It would be really helpful is you could nest a folder inside another folder.  I.E. favorite folder number 1 could have favorite folder number 2, 3 and 4 inside of it.

**Comment by TFackler** [comment]
Hello and thanks for your feedback.

Sadly enough I don't think your suggestion will work well with our design principles. Easy, fast and straightforward navigation is what we strive for and having nested folders seems counter-productive.
