### ISSUE TITLE
[Request] Give users the ability to tint homescreen wallpaper as well

### ISSUE THREAD

**Issue by ravtakhar** [8bitPit/Niagara-Issues#1796]
### Is your feature request related to a problem?

I have been manually tinting my wallpapers for a very long time and was very excited to see the tint by default through the launcher. Are we able to get an option that allows us to tint the home screen as well?

Thanks!

### Describe the solution you'd like

Toggle/option within settings which enables the user to tint the home screen wallpaper.

**Comment by 8bitPit** [comment]
I'm sorry, @ravtakhar, we don't plan to offer tinting the home screen. In our opinion, tinting the home screen would only make sense if we also tint the wallpaper in Android's recent apps screen, and we can't do that without being a "wallpaper app." If you want always to have the wallpaper tinted, we still recommend using apps like [Blur wallpaper](https://play.google.com/store/apps/details?id=dk.appdictive.blurwallpaper) (we're not affiliated with the devs of Blur Wallpaper, that's my recommendation).
