### ISSUE TITLE
Show recently searched results in Search

### ISSUE THREAD

**Issue by pratyakshm** [8bitPit/Niagara-Issues#1797]
### Is your feature request related to a problem?

Yes
Whenever I open the search screen, it always shows the most recently installed apps. 

### Describe the solution you'd like

This is an example:
Say I have Firefox on my phone. Now, I open Search and search for Firefox. Due to sesame integration, a lot of search results turn up, but I tap on the search result that launches Firefox app.
Next time when I open Search, I want Niagara to show me the most recently tapped items in Search.
I believe that this feels much more natural over just showing the list of recently installed apps.

**Comment by Oddward** [comment]
@pratyakshm It shows a few of the most recently opened shortcuts, but I don't think Niagara stores them, it pulls them from Sesame. When you open the quicksearch app's result it's not stored as a recently opened item in Sesame. If you have the option **"Make shortcuts from my recent searches"** enabled (Sesame > settings > search settings), which should be the default, it should appear in the list of recently opened shortcuts

**Comment by pratyakshm** [comment]
@Oddward I understand, however I cannot reproduce the intended behavior. **"Make shortcuts from my recent searches"** is enabled in Sesame > Settings > Search settings, however Niagara still shows me recently installed apps in the Search UI.

**Comment by pratyakshm** [comment]
@Oddward I had this option already enabled (as is default setting), however I re-installed Sesame and that somehow fixed it. Thanks for the help!
