### ISSUE TITLE
New music player design

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#18]
- Music player artwork with rounded corners
- rounded play/pause and next/previous icons

**Comment by 8bitPit** [comment]
@587saboor, here are some rounded icons that could be implemented: https://material.io/tools/icons/?search=Av&style=round

**Comment by 587saboor** [comment]
@8bitPit ye

**Comment by samerserhan91** [comment]
It's a good idea!!!

**Comment by 8bitPit** [comment]
@michalsukupcak wrote in #316:

> Maybe you could consider adding small rounded corners to album cover art image on homescreen when music is playing? Nothing excessive, something to the equivalent of 3px border radius on the web (ie. text inputs here on Github). Nearly everything else in the launcher's UI is a circle or at the very least rounded (google button, music controls, all the dialogs and overlays and even most app icons nowadays - I even use Cornerfly to round the phone's corners:) and very neatly animated, so the sharp square image feels a bit out of place.

**Comment by 8bitPit** [comment]
I changed my mind about rounded corners for artworks, I believe it’s wouldn’t look good for every artwork. I looked at covers from my music library and noticed they are often designed specially to fit in a square, e.g. some of them have a border, which wouldn’t look with a “cropped” image. 
Spotify also recommends not to change the artwork’s shape:
![image](https://user-images.githubusercontent.com/9284845/46341135-bb240100-c637-11e8-9756-485a193da415.png)

**Comment by 8bitPit** [comment]
@587saboor Would look cool, but the play button would need a new play / pause animation.

**Comment by ssssamstrup** [comment]
Another way to do this, like the lockscreen on Pie 9 does, is set the background image to the albumcover of the currently playing song. This looks great and then you don't need to figure out how it should be framed. Much simpler and functional in my opinion. :)

**Comment by 8bitPit** [comment]
@ssssamstrup: https://github.com/8bitPit/Niagara-Issues/issues/31

**Comment by 8bitPit** [comment]
I finally updated the media player (almost exactly one year later 😅). You can check out the result in v0.9.0: https://github.com/8bitPit/Niagara-Issues/releases/tag/v0.9.0-beta
