### ISSUE TITLE
Suggestion For The Niagara Launcher New Material You Update: Introduce Adaptive Material You Icons

### ISSUE THREAD

**Issue by Amorphous404** [8bitPit/Niagara-Issues#1800]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Dark Mode

![IMG_20211231_205905_732](https://user-images.githubusercontent.com/96917972/147830850-96402077-2823-450a-9488-a8313e6a1fb9.jpg)

Light Mode

![IMG_20211231_205911_572](https://user-images.githubusercontent.com/96917972/147830855-ffde33b8-0213-4390-8d07-42931af70179.jpg)

I really hope in future,
1.Niagara Launcher provides a way to allow user to select different **Accent color,** as Material You Theming is very subtle.

2. Hope Niagara does some magic like incorporating something like lawnchair's (lawnicons) to able to apply material you **adaptive color to icons** as well

I'm really impressed by how lawnchair is able to do it and with its lawnicons , its provides Adaptive colour almost to all the popular apps and it will be updated overtime by the community
I hope Niagara can collaborate to make use of it in it's launcher as Niagara Material You Icons as present Niagara Dots 

I hope Peter And Max comes up with an idea, i would really love it, i hope User with Lower Android version will also be able to enjoy Material You Theming wholly with the help of Niagara Launcher😊

**Comment by paul-omalley** [comment]
I was just thinking about this the other day. 
I know that to add this in would be intense as the launcher would need to have a vector icon for thousands of apps. 

As a potential way around it, there are icon packs like the Pix Material You Icon pack that can create this effect, but to update the icons after a wallpaper change etc, you need to reapply the icon pack. Niagara Launcher could force a refresh of the icon pack when it detects the wallpaper change (which it does to change the Niagara Button colour and Text colour).

**Comment by topsy-turvy99** [comment]
> Good news everybody: Android 13 will open the API Pixel Launcher uses for the Material You icons 🎉 We're planning to use the API once Android 13 releases.

wow great 🔥, hope google makes it mandatory for app developers to add the dynamic icons,

i hope it can be back ported to lower version of Android, so everyone can enjoy the dynamic theming of icons 🙂

what's i like about lawnicons, the icons looks neat and the color refresh faster and changes the icons only for homescreen (favorites), and more popular app icons are added over time by the community and most interestingly lawnicons is open-sourced (https://github.com/LawnchairLauncher/lawnicons) so any launcher can implement it 😅

**Comment by Ralendil** [comment]
What says Paul Omalley already happens. Niagara force the icons to refresh and it works 80% of the times. However, niagara is so fast, that sometimes it refresh them before Pix Material light / dark had time to adapt the color of them.
Maybe I am wrong, but, for the pix material app, it would only need that the niagara refresh happens just 1 second later...

**Comment by unityastronaut** [comment]
I think there's a smarter way to implement themed icons. I could be wrong but I think the way pixel launcher does it, is rather than having a pack of vector icons integrated, the apps that support it have an alternative icon. So the themed icons don't come with the launcher, they come with the apps. Which is way smarter, because rather than having thousands of icons on your phone that are not used, you only get the ones you need when installing the apps. Since Android 13 more and more third party apps are starting to support themed icons as well (WhatsApp, Reddit, etc.). I think the goal for Niagara should be to make use of these alternative icons. That way not a sigle icon has to be saved within the Launcher and nobody has to update the icon pack because the app developers add the themed icons themselves over time.

**Comment by topsy-turvy99** [comment]
> I think there's a smarter way to implement themed icons. I could be wrong but I think the way pixel launcher does it, is rather than having a pack of vector icons integrated, the apps that support it have an alternative icon. So the themed icons don't come with the launcher, they come with the apps. Which is way smarter, because rather than having thousands of icons on your phone that are not used, you only get the ones you need when installing the apps. Since Android 13 more and more third party apps are starting to support themed icons as well (WhatsApp, Reddit, etc.). I think the goal for Niagara should be to make use of these alternative icons. That way not a sigle icon has to be saved within the Launcher and nobody has to update the icon pack because the app developers add the themed icons themselves over time.

Yeah, the devs are planning to use the API to support the inbuilt themed icons
 https://github.com/8bitPit/Niagara-Issues/issues/1800#issuecomment-1087648593

**Comment by topsy-turvy99** [comment]
https://developer.android.com/about/versions/13/features

Themed Icons Api is already alive, and few third party launchers like Hyperion are already on-board
![Screenshot_2022-10-04-11-33-19-29_0b2fce7a16bf2b728d6ffa28c8d60efb.jpg](https://user-images.githubusercontent.com/96917972/193746031-cea18f2f-cdc3-49cc-b2ef-e265587ca2a8.jpg)
![HiShoot_20221004_111551.png](https://user-images.githubusercontent.com/96917972/193744679-7520f74b-f869-414f-a4e3-f728a015110d.png)

Here's the list of apps that added support for themed icons, hope more devs add the support for their apps 😊

https://9to5google.com/2022/09/22/android-13-themed-icons/

**Comment by M00NJ** [comment]
> Good news everybody: Android 13 will open the API Pixel Launcher uses for the Material You icons 🎉 We're planning to use the API once Android 13 releases.

Any news on this?

**Comment by Maxr1998** [comment]
Added in [v1.10.0](https://github.com/8bitPit/Niagara-Issues/releases)🎈

**Comment by RokeJulianLockhart** [comment]
This doesn't appear to be working for me:

> ![Screenshot_20240613-100932](https://github.com/8bitPit/Niagara-Issues/assets/42837531/e6a9fe16-bb4d-43eb-9aac-3493e46ea67a)
