### ISSUE TITLE
Stronger colors of material you. 

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1801]
### Is your feature request related to a problem?

I like the adaptative color of the material you. However, the colors are extremely pale, they are almost imperceptible. I can notice barely coloration. However, there is almost no change when it comes to the **pop-up folders** or agenda. Something that you can enjoy. I change many wallpapers, but any of them really give me that vibe of material you. 

### Describe the solution you'd like

To increase slightly the intensity of the colors especially in pop-up folders and agenda.

**Comment by Maxr1998** [comment]
We experimented quite a while with more saturated colors, but with a lot of wallpapers, it just didn't look good, and didn't fit our quality standards. Thus, we settled on a lighter saturation.

As we did extensive testing internally, it's unlikely we'll change our minds, thus I'll close this as "won't fix".
