### ISSUE TITLE
Hidden apps list

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1803]
### Is your feature request related to a problem?

Currently there isn't any way to see all the apps that have been hidden

### Describe the solution you'd like

![Screenshot_20220101-003523](https://user-images.githubusercontent.com/40870763/147836499-0ad92a0e-ca51-4c05-a495-0b8fe25766c4.png)

There should be a command like /hidden or just hidden... When typed on the search bar to show all the apps that are hidden..

**Comment by JONI350** [comment]
![Screenshot_20220101-015732_Niagara Launcher](https://user-images.githubusercontent.com/25126715/147844275-e6c2a9ab-69b5-4dec-8556-f7b88574f97d.jpg)
Well there's this

**Comment by Maxr1998** [comment]
Right, you can see a list of the hidden apps from the Niagara settings.
