### ISSUE TITLE
Make Niagara button adjustable position

### ISSUE THREAD

**Issue by Koobadee** [8bitPit/Niagara-Issues#1805]
### Is your feature request related to a problem?

I would like to set up my homescreen cleanly but I can't for 2 small adjustments that I cannot make. 

https://photos.app.goo.gl/wtHs6H8GX5FL9mxs6

I would like to be able to bring the Niagara button higher/maybe switch side but there is no option to do it. Also, I cannot drop my folders/apps low enough to create a sort of fake drawer. In the screenshot it shows a little bit of spill over/overlap.

I would love to be able to do both and make my home screen a bit cleaner which fits with the launchers aesthetic and purpose.

Thanks,

-Dave

### Describe the solution you'd like

I would love to be able to do both and make my home screen a bit cleaner which fits with the launchers aesthetic and purpose

**Comment by Maxr1998** [comment]
Probably not something we'll add, the button position is exactly according to the Material Design guidelines.
