### ISSUE TITLE
Assigned music app showing despite already visible widget

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#1806]
### Describe the bug

I have specified Spotify as my assigned music playing app for Niagara. When connecting my Bluetooth headset and playing music, both the widget and app favorite Spotify with 🎵 is shown. Should not show the music app favorite when already playing.

### Steps to reproduce

0. Specified Spotify as preferred music app in Niagara
1. Connect bt headset with phone
2. Start playing music in Spotify
3. Both music widget (ok) and preferred music app icon (not ok) (Spotify app symbol with 🎵) appear in Niagara homescreen

### Device name

OnePlus Nord

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_20211229-144114-01](https://user-images.githubusercontent.com/7660277/147872411-9d9ebd2a-9f66-49fd-8602-34f2c2af63fb.jpg)

**Comment by paul-omalley** [comment]
This isn't a bug. The widget is showing as you have something playing. The designated music apps feature is there so that you can get quick access to certain apps when BT is connected and then have them disappear when disconnected.

**Comment by tjsuominen** [comment]
Ah, this makes sense (yet kind of ruins the UI a bit). Thx for clarifying this / behaviour.

**Comment by Maxr1998** [comment]
Right, I think that was already discussed in the Telegram group too. I'm not sure if a widget should prevent a music app from moving up, I fear it would be confusing if it didn't in such cases. Also, tapping the notification is a different action than (re-)opening the app.

Thus, I think it makes the most sense to close it.
