### ISSUE TITLE
Material You still supplying Niagara Button color even if disabled

### ISSUE THREAD

**Issue by nightwishhh** [8bitPit/Niagara-Issues#1808]
Hi.
I have a Pixel 5 with Android 12 and I have a problem since the last beta update. Material you is disabled in the phone's settings because I don't like it. Well, the instead of picking up the colour for the Niagara button from the wallpaper, as it happened previously, Niagara uses the system accent colour.  
Just imagine a beautiful green wallpaper, with plants and trees accompanied by an artificially looking violet Niagara button. Why violet? Because that's the defined accent colour in Settings.
I think Niagara should offer the same colour options as before for people that don't want to use Material you. Thanks.

**Comment by Maxr1998** [comment]
We change the theme algorithm to use the color provided by Material You for consistency when Material You is enabled, but we maybe should use the old algorithm for when it's disabled..
By disabled, do you mean you disabled it in Niagara, or did you simply switch color palette in the system settings?

**Comment by nightwishhh** [comment]
Hi.
Material you is disabled in the system settings. 
Having the old algorithm in place when material you is disabled would be ideal for my use case.
Thanks

**Comment by JONI350** [comment]
Yeah i think like this too, i, for example use an amoled wall and my phone doesnt even have material you as for now (so even if i like it i would like to niagara and material you being separated, like a toggle to turn niagara material you on and off) and i liked my amoled niagara button who now is a black pastel tho

**Comment by danyev3** [comment]
I would like to report this is also the case on One UI 4 based on A12, my buttons used to be dark purple before updating, suddently became bright blue because that's the default accent color in samsung's Monet implementation. This is an issue since if you are using a custom theme you can't change the Monet colors to match the wallpaper, making niagara's accents peramently blue.
If there is no way to fix it on android 12, I'd really appreciate an advanced toggle to switch back to the old accent color algorithm. Thanks!

**Comment by 8bitPit** [comment]
Thanks for the feedback everyone! We addressed this issue with [v1.5.3](https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.5.3) a while ago, Niagara Launcher should also choose the colors based on your wallpaper again. I also wrote a little article to roughly explain how our new coloring system works: https://help.niagaralauncher.app/article/133-color-system.
