### ISSUE TITLE
UX bug: Hide unused widgets in foldout when editing favorites

### ISSUE THREAD

**Issue by ssssamstrup** [8bitPit/Niagara-Issues#1809]
### Describe the bug

When I want to edit favorites, which I do often - I always have to scroll down, since a not of unused widgets are shown in the widgets section above the favorites menu.

Added screenshot for reference.

Solution: Hide unused widgets in the »More widgets« foldout.

### Steps to reproduce

1. Select »Edit favorites«
2. Scroll down to edit favorites

### Device name

Sony Xperia XZ2 Compact

### Android version

Android 10

### Screenshots / Screen recordings

![Screenshot_20220103-120240](https://user-images.githubusercontent.com/4302516/147925026-743025d2-d219-40d5-85c6-6172e72ee6d5.png)

**Comment by Maxr1998** [comment]
Hmm yes, I understand the problem, KWGT has a lot of (unnecessary) widget configurations. Maybe we can instead introduce a limit, so that it still works for apps with 2-3 widgets.

**Comment by ssssamstrup** [comment]
Since you currently only can show 1 widget, doesn't it make sense just to show that one + the See more foldput/button?

Do people regularly have 2 or 3 widgets they change between, or why would you like to show more? :)

If you have just switched to a new widget it could be nice if the last was shown for some days (like how you show newly installed app in search) though. But that's again more nice to have, than need to have functionality? :)

Best,

✺ Sune Amstrup

Billedkunstner
Besøg min hjemmeside ↣
Følg mig på instagram ↝

**Comment by ssssamstrup** [comment]
Alternatively widgets could be removed from the favorites menu, though that's a larger change.

But you already have a menu for it when a widget is chosen, where you can replace it. It would make sense that "Edit favourites" only lets you edit favorite apps and popups in the list below. And widgets are added when Niagara is opened first time, edited like it is now, when longpressing the current widget or from Niagara settings (if it wasn't added after installing the app.

Hope you can find a good solution. :)

**Comment by ssssamstrup** [comment]
Editing favorites:
![Screenshot_20220105-205907](https://user-images.githubusercontent.com/4302516/148281247-cbddefdb-2b28-4851-8867-39e893ed5a15.png)
![Screenshot_20220105-205913](https://user-images.githubusercontent.com/4302516/148281293-c2d9e756-2203-43fc-8e91-1263f0f7f2a9.png)

vs

Editing widget
![Screenshot_20220105-205853](https://user-images.githubusercontent.com/4302516/148281323-fc4c6d61-04c3-4ce0-a2bb-2c917c16a78b.png)
![Screenshot_20220105-205859](https://user-images.githubusercontent.com/4302516/148281339-0a591829-9c94-416f-8a6f-f777bcdd8661.png)

**Comment by topsy-turvy99** [comment]
> Hmm yes, I understand the problem, KWGT has a lot of (unnecessary) widget configurations. Maybe we can instead introduce a limit, so that it still works for apps with 2-3 widgets.

How about just showing the No widget & Currently selected widget to keep the edit favorites page clean

And showing the currently selected widget app suggestion at the top of the list on>More widget page?

**Comment by ssssamstrup** [comment]
This issue no longer exists for me with the introduction of the new »Multiple widgets« release.
