### ISSUE TITLE
Apps not sorted properly

### ISSUE THREAD

**Issue by mrencrypter** [8bitPit/Niagara-Issues#181]
Apps are not getting sorted properly under specific alphabet.

**Comment by 8bitPit** [comment]
They are not sorted alphabetically, instead apps are ordered by usage.

**Comment by rastamanjohn** [comment]
Oh you/he meant the favorites? Makes more sense

**Comment by 8bitPit** [comment]
@rastamanjohn I believe he is referring to the app list.

**Comment by rastamanjohn** [comment]
Oh lol, didn't notice that apps list too is sorted by usage... Kind of counter intuitive now that I think about it, would be nice to have a switch for it
