### ISSUE TITLE
Animate caret icon on expanding notification in a popup

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1812]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

This is just cosmetic, I consider it would have a better appearance if the arrow flips when u open a notification. Actually, when you open one, it remains in the same position. Like the images.
![3](https://user-images.githubusercontent.com/72170242/148149661-16b4d2e3-ea70-4c75-9709-6ca7b57f04fc.jpg)
![2](https://user-images.githubusercontent.com/72170242/148149683-bce6fd72-8e2e-4448-93a5-a46f538e6f64.jpg)
It could have an animation or just flip.
![1_1](https://user-images.githubusercontent.com/72170242/148149721-883bdcc0-8e23-4d25-ba78-f7e5d8af57b1.jpg)

**Comment by Just-SKY** [comment]
I've noticed that in the new Niagara version; it was added some sort of animation regarding to this topic. It is a nice touch. However, the animation looks somewhat weird. It'd be better that when the user press the notification, the app icon remains static while the notification/s expand downwards.

**Comment by 8bitPit** [comment]
Yup, we now flip the arrow when you expand the notification. We might also animate it, but the animation would require way more time. I'll close this ticket for now.
