### ISSUE TITLE
Optimization for tablets 

### ISSUE THREAD

**Issue by Rashadkafeel** [8bitPit/Niagara-Issues#1814]
### Is your feature request related to a problem?

_No_

### Describe the solution you'd like

A third row for widgets.

**Comment by 8bitPit** [comment]
Hey @Rashadkafeel; I'm sorry but we're not planning to add a third row for widgets. Please refer to https://help.niagaralauncher.app/article/77-missing-customization-features (Grid Layout) and https://help.niagaralauncher.app/article/41-adding-multiple-widgets (What about a widget page?).
