### ISSUE TITLE
Additional swipe directions on Niagara Button

### ISSUE THREAD

**Issue by Slimuk** [8bitPit/Niagara-Issues#1818]
### Is your feature request related to a problem?

The Niagara swipe swipe up feature is very helpful. Adding additional directions will further enhance the button while keeping things simple. 

Thanks :-)

### Describe the solution you'd like

Add additional swipe directions for the Niagara Button.

**Comment by topsy-turvy99** [comment]
![IMG_20220118_001838_938](https://user-images.githubusercontent.com/96917972/149823695-b5e5fe69-097c-4fe1-ba2d-d638aaf29e97.jpg)

https://user-images.githubusercontent.com/96917972/149823711-d5d1d2cd-2940-4aae-a3f8-2f0dfa49611f.mp4

With so many user requesting to add, more swipe gesture to fab, top swipe is already occupied It's Better The Way It Is and right swipe is not feasible (no space) and will Look Kinda Bad Maybe , if left swipe is ever added, please add something of this manner, it will be highly functional , it feels super smooth and functional  User Can Customize It As Per His Liking and will Cover Up For The Right Swipe And It's Simple.

**Comment by 8bitPit** [comment]
I'm sorry @Slimuk & @topsy-turvy99, but we're not planning to add this feature: https://help.niagaralauncher.app/article/116-niagara-button.
> We don't want to overload the Niagara button with dozens of gestures. That's because we want to keep everything simple and easy to remember, and only allowing one swipe gesture makes the behavior of the button more consistent with the behavior of app pop-ups. The swipe-up gesture is the easiest one to execute at the bottom right corner. If you want to keep your home screen free of apps, we recommend adding a pop-up to the Niagara button.

**Comment by Amorphous404** [comment]
Duplicate of #1641

**Comment by Amorphous404** [comment]
- Duplicate of #1641
