### ISSUE TITLE
 Quick options in batch

### ISSUE THREAD

**Issue by alexandrecopi** [8bitPit/Niagara-Issues#1819]
Batch actions could be a nice shortcut to execute some tasks like "set as music app" , "hide" and even creating a feature to select several apps and quickly creating a new folder.

**Comment by TFackler** [comment]
Hello there, thank you for your suggestion.

We think, that the workflows your suggested *batch actions* would speed up are not something users would do repeatedly and thus feel like it is not worth to add the functionality right now.
