### ISSUE TITLE
Cannot install Niagara launcher

### ISSUE THREAD

**Issue by usmanghanni** [8bitPit/Niagara-Issues#1822]
I'm not able to Install launcher via any means. It just say app not installed when trying to install via APK file.  My phone is OnePlus 6 running oxygen os 11.1.1.2

**Comment by Oddward** [comment]
@usmanghanni try clearing the cache of your Google Store & Google Play Services, restarting & trying again. If not, check if you have residual files from an old Niagara installation still on your phone *(not entirely sure where though)*

**Comment by 8bitPit** [comment]
Yup, and if that doesn't work, please feel free to check out this article: https://help.niagaralauncher.app/article/126-installation-failed
