### ISSUE TITLE
After Formatting Smartphone backward version Niagara Launcher

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#1824]
### Describe the bug

I had installed the 1.4.2 free version from the Play Store inside Niagara Launcher, I clicked on the Niagara Pro button and bought the Niagara Launcher Pro Lifetime version for 14.99 euros and then after a few days, again from the Play Store, I got the following updates first 1.5.0 then 1.5.2 and finally 1.5.3. So as you say I have to wait a few days for the Play Store to notify me of the update? If I download the version from the telegram channel after the play store, it will no longer notify me of future updates. So, as you say, I wait for the Play Store to notify me of the updates. P.S. why from the Play Store it is not possible to immediately download the latest version of Niagara Launcher instead of 1.4.2 and then wait for the updates? Generally, when you download an app from the Play Store, the latest version is always downloaded. I await your reply. thanks in advance 
### Steps to reproduce

I had installed the 1.4.2 free version from the Play Store inside Niagara Launcher, I clicked on the Niagara Pro button and bought the Niagara Launcher Pro Lifetime version for 14.99 euros and then after a few days, again from the Play Store, I got the following updates first 1.5.0 then 1.5.2 and finally 1.5.3. So as you say I have to wait a few days for the Play Store to notify me of the update? If I download the version from the telegram channel after the play store, it will no longer notify me of future updates. So, as you say, I wait for the Play Store to notify me of the updates. P.S. why from the Play Store it is not possible to immediately download the latest version of Niagara Launcher instead of 1.4.2 and then wait for the updates? Generally, when you download an app from the Play Store, the latest version is always downloaded. I await your reply. thanks in advance 
Oukitel c16 Pro

### Android version

Android 9 (Pie)

**Comment by 8bitPit** [comment]
I hope my reply to your other ticket clears everything up: https://github.com/8bitPit/Niagara-Issues/issues/1825.

Regarding this:
> If I download the version from the telegram channel after the play store, it will no longer notify me of future updates.

You will still get updates from Google Play once the version from Google Play is higher than the version of the beta build.
