### ISSUE TITLE
Why do I download an old version of Niagara Launcher from the Play Store?

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#1825]
### Describe the bug

 Excuse the outburst, but all downloadable apps from the play store always download the latest version and not an old version. For example AIO LAUNCHER, the latest version is 4.2.0 and 4.2.0 can be downloaded on the play store, as never before Niagara Launcher the latest stable version is 1.5.3 but an old version 1.4 can be downloaded from the play store. 2? I await your news. I ask this because I bought the Niagara Launcher Pro Lifetime Version for a good 14.99 Euro and once the smartphone has been reformatted I download an old version of Niagara Launcher waiting for the updates instead of being able to download the latest version directly from the Play Store or the 1.5 .3?

### Steps to reproduce

 Excuse the outburst, but all downloadable apps from the play store always download the latest version and not an old version. For example AIO LAUNCHER, the latest version is 4.2.0 and 4.2.0 can be downloaded on the play store, as never before Niagara Launcher the latest stable version is 1.5.3 but an old version 1.4 can be downloaded from the play store. 2? I await your news. I ask this because I bought the Niagara Launcher Pro Lifetime Version for a good 14.99 Euro and once the smartphone has been reformatted I download an old version of Niagara Launcher waiting for the updates instead of being able to download the latest version directly from the Play Store or the 1.5 .3?

### Device name

OOukitel c16 Pro

### Android version

Android 9 (Pie)

**Comment by 8bitPit** [comment]
Hi, @Livio78 👋 Our top priority of the Play Store builds is that they're stable. In this instance, we temporarily paused our rollout on Google Play because we had to investigate an issue that caused a couple of crashes. You can now download v1.5 again on Google Play.

**Comment by Maxr1998** [comment]
Closing as this was sorted out via email.

**Comment by Livio78** [comment]
Thank you

    Il lunedì 7 febbraio 2022, 23:57:31 CET, Max Rumpf ***@***.***> ha scritto:  
 
 


Closed #1825.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
