### ISSUE TITLE
Home swipe gesture

### ISSUE THREAD

**Issue by Tarch1** [8bitPit/Niagara-Issues#1826]
### Describe the bug

When in Niagara launcher I try to open the multitasking with swipe gesture nothing appen but in any app the gesture work correctly

### Steps to reproduce

Just use the multitasking gesture on the home screen

### Device name

Samsung Galaxy A52s 5g

### Android version

Android 11

**Comment by 8bitPit** [comment]
Hi, please refer to: https://help.niagaralauncher.app/article/114-recent-apps-screen-issues

**Comment by Tarch1** [comment]
Thank you!!!
