### ISSUE TITLE
Your agenda and Notification Summary integration by tab

### ISSUE THREAD

**Issue by RPM28XI** [8bitPit/Niagara-Issues#1827]
### Is your feature request related to a problem?

Obtrusive notification summary window, but don't want to disable, change the way it is viewed only.

### Describe the solution you'd like

![Picsart_22-01-16_14-34-01-607](https://user-images.githubusercontent.com/8072208/149650162-5a7985e1-8601-4c0f-ae67-9eceecedf63f.png)
Integrate your agenda with notification summary using tabbed interface in the sliding window.

**Comment by topsy-turvy99** [comment]
Notification Summary, Is Good Concept, I Like It Being Implemented In Niagara, But The Only Downside Is Not Being Able To Open It Manually, 

I Personally, Select All The Apps That Doesn't Require My Immediate Attention, But I Would Like To See It When I'm Free, But A User Has To Wait For The Scheduled Time For The Notification To Arrive, I Have Seen Others Request For Changing The Scheduled Time Scheme, But It doesn't Fix The Overall Problem For  All User,

So The Suggestion Will Be Keep The Scheduled Summary The Way It Is, And Provide A Manual Way To Open The Notification Summary.


One More Suggestion I'm Not Opening A New Thread, So Will Just Be Sharing It Here.

If it's feasible provide an option way to select channels For Particular App, For Example, If I Select A Browser For Notification Summary, Every Notification For That App Gets Block, But I Wanted For The Browser Download Notification To Not Be Blocked.

**Comment by TFackler** [comment]
Hello and thanks for reaching out!

The intended purpose of the notification summary was to reduce the number of times users get distracted by notifications, while allowing them to still be up to date after reading the summary. Adding the option of checking the summary manually goes against our idea of what the feature should be. Now you can get the craving of wanting to check the summary whenever you have free time and thus can get more distracted.

What you have described sounds like the prime use case for Android's [focus mode](https://blog.google/products/android/android-focus-mode/). Maybe this could help you achieve your wished for behaviour :)

You can read more about what we intend our notification summary to be and what kind of setup we recommend [over on medium](https://medium.com/niagara-launcher/a-healthy-home-screen-2c99e87651be).

---

In regards to @topsy-turvy99 's request:

Unfortunalety this feature would involve a lot of work on our part, while going against our philosphy of creating something intuitive and simple. Your request would require a user to be able to manually select notification types for each app, thus overloading them with information and choice.
Therefore we will not be implementing this.
