### ISSUE TITLE
Suggestion For Niagara Search: To Add Web Search

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1828]
### Is your feature request related to a problem?

Yes

### Describe the solution you'd like

idk, Why This is very basic, as all the other launcher provides a way to search in web via the launcher search, i know we can use seasme, but why to use a third party app

Solution: In Setting
1. Provide An Option To Set Provider i.e Google.com/ duckduckgo.com / or user defined and  it will automatically select the android default browser to complete the search
2. Provide And Option To Weather To Complete The Search Via Google App or The Default Browser

**Comment by JONI350** [comment]
I use google widget because of this mostly, ive tried sesame but its kinda annoying how cluttered it is imo

**Comment by 8bitPit** [comment]
Hi @topsy-turvy99, happy to tell this feature is planned, please refer to: https://github.com/8bitPit/Niagara-Issues/issues/1501
