### ISSUE TITLE
Widget resizing issue with Samsung Z Fold3

### ISSUE THREAD

**Issue by britchey5** [8bitPit/Niagara-Issues#1829]
### Describe the bug

When opening fold, sometimes the widget does not resize properly and you have to click "resize" for it to expand from the front screen to the inner larger screen

### Steps to reproduce

Open z fold 3
Widget retains smaller size and doesn't expand to fit with rest of screen

### Device name

Samsung Z Fold 3

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20220119-111214_Niagara Launcher](https://user-images.githubusercontent.com/31411836/150180379-bab60d31-f74d-40b4-988a-c0190e0bfe6b.jpg)

**Comment by Amorphous404** [comment]
> 

Can you check if the issue is resolved?

**Comment by Amorphous404** [comment]
> ### Describe the bug
> When opening fold, sometimes the widget does not resize properly and you have to click "resize" for it to expand from the front screen to the inner larger screen
> 
> ### Steps to reproduce
> Open z fold 3 Widget retains smaller size and doesn't expand to fit with rest of screen
> 
> ### Device name
> Samsung Z Fold 3
> 
> ### Android version
> Android 12
> 
> ### Screenshots / Screen recordings
> ![Screenshot_20220119-111214_Niagara Launcher](https://user-images.githubusercontent.com/31411836/150180379-bab60d31-f74d-40b4-988a-c0190e0bfe6b.jpg)

Can you check if the issue is resolved?
