### ISSUE TITLE
Set weather refresh interval

### ISSUE THREAD

**Issue by kxlbe** [8bitPit/Niagara-Issues#183]
Is it possible to set the refresh time for the weather on the homescreen to 1 hour? Because I'm stuck on the same temperature since I activated it. It still shows 26°C while my weather app shows 18°C.

**Comment by rastamanjohn** [comment]
I would suggest to have a refresh frequency setting in settings, and maybe long press the weather on home screen to force refresh, tho don't know what is possible with awareness api

**Comment by 8bitPit** [comment]
Neat idea, yeah that's possible

**Comment by kxlbe** [comment]
Force refresh would be good as well but then you can't open Google weather from home screen without having in the favorites.

**Comment by rastamanjohn** [comment]
:palmface:

**Comment by rastamanjohn** [comment]
@kxlbe that's exactly what I wrote xD

**Comment by kxlbe** [comment]
@rastamanjohn you're right, I didn't read it carefully. Sorry for that :)

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
