### ISSUE TITLE
FILL SCREEN behaviour of home screen custom widget is not uniform

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#1830]
### NL has beautiful padding around all four corner. But widget can use feature called **FILL SCREEN** 
But it look weired when only widget is stretched to edge of screen not other component.
![ddd](https://user-images.githubusercontent.com/5180486/150357036-7740fd7a-4b62-4c71-b8e1-1a775916c0af.jpg)

### Describe the solution you'd like

**A solution can be :** when using **FILL SCREEN** feature of widget, Uniformaly remove padding from all content of screen like clock, date, widget, favourite list. 
Then it will look more beautiful and uniform.

Along with that also increse the width on INLINE NOTIFICATION UNDER ICON. So that it can show more text in FILL SCREEN MODE.

So below point can be done:

1. Remove padding from left or both side of screen edge 
2. Claim unnecessary space wasted on top of screen above clock
3. In FILL SCREEN: Increase width of Favourite icon notification length for more text visibility
4. Separate selection on notification font.

**Comment by notepadnine** [comment]
As per more research I can see, Padding removal can also be done only on LEFT side edge of screen

**Comment by TFackler** [comment]
Hi there,
thanks for reaching out and submitting a request.

The intended purpose of the `Fill screen` option is to allow for a clean look for widgets with a fixed size larger than the available space and therefore be slightly cropped. It was not intended for full size widgets (such as the one you seem to be using). Therefore we unfortunately are not planning on implementing the changes you proposed.
