### ISSUE TITLE
Allow items to be added to folders via long press on the item

### ISSUE THREAD

**Issue by rjrjr** [8bitPit/Niagara-Issues#1831]
### Is your feature request related to a problem?

You know how your can long press an app and choose it make it a favorite? It's frustrating that there is no option to add it to a folder.

I see the item, realize it's missing from a folder -- and now I have to go find the folder, long press it, hope I remember what item I was thinking of... It's a drag, and it's odd. Makes the folders feel like a second class feature.

### Describe the solution you'd like

- Long press the item
- Choose _Add to Folders_
- See a Niagra / checkbox list of all folders, and click away

**Comment by rjrjr** [comment]
Yay! Feeling pretty good about my subscription right now.

**Comment by 8bitPit** [comment]
Added in v1.7; thank you for this wonderful idea!
Changelog: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b

**Comment by rjrjr** [comment]
You made my day. Congrats on the release.
