### ISSUE TITLE
I think that there's problem in ram management  with launcher. 

### ISSUE THREAD

**Issue by soymadip** [8bitPit/Niagara-Issues#1834]
### Describe the bug

Sometimes when I am opening an app which I have opened sometimes ago, its freezing at recent apps section.
But when I am reopening by going back to home, it's opening where I left it before. 

### Steps to reproduce

When re-opening background app.
It's happening some times. 

### Device name

Realme narzo 30

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_2022-01-23-15-34-52-58_92b64b2a7aa6eb3771ed6e18d0029815](https://user-images.githubusercontent.com/84225810/150673561-c3441382-c060-4e03-ab1d-03b5e696ae57.jpg)

**Comment by TFackler** [comment]
Hello there,

thanks for reaching out.
The issue you are experience does seem to have something to do with high memory consumption. Usually the cause for this is not Niagara Launcher however. Any other app could use a lot of memory, thus leading to the behaviour you described. 

We recommend checking the memory consumption of your apps. These links should be useful :)
[Enable Developer Settings](https://www.digitaltrends.com/mobile/how-to-get-developer-options-on-android/)
[How to check apps' memory consumption](https://www.howtogeek.com/768356/how-to-find-which-apps-are-using-the-most-memory-on-android/)

[Why Niagara's consumption might be displayed higher than it actually is](https://help.niagaralauncher.app/article/17-memory-consumption)
