### ISSUE TITLE
Suggestion: To Add Sorting Option In App Selection For Pop Up & Hidden Apps

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1835]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

![Screenshot_20220123-185122_Niagara_Launcher](https://user-images.githubusercontent.com/96917972/150680769-135e6741-746a-45d2-ae08-cb346cf2f50d.png)

Currently, The Apps Gets Listed In The Order In Which User Selects The Apps, It Will Be Great, If Sorting The Apps By Alphabetical Order Was Added, Right Now To Arrange, A User Have To Manually Arrange All The Apps, Which Is Very Tedious Process.

**Comment by TFackler** [comment]
Greetings :)

Thank you for your suggestion. Sadly we do not plan on adding this right now, but we might take a look at it in the future.
