### ISSUE TITLE
Widget sizes for foldables

### ISSUE THREAD

**Issue by JigglyTurtle** [8bitPit/Niagara-Issues#1836]
### Is your feature request related to a problem?

I have an issue with how inconsistent the widgets are between the cover and main screen.

### Describe the solution you'd like

I would either like to have the ability to set the widget to have half the normal width on the main screen, or have 2 different widgets for both if the screens. It would only be visible/available for foldable users so it wouldn't add clutter for most users.

**Comment by 8bitPit** [comment]
Thanks for your suggestion, we'll have an internal discussion about it.

**Comment by Radixtrator** [comment]
Along those lines:
Would it be possible to have the widget position change depending on inner/outer screen? I would love to have it on the bottom with 2 columns on the inner screen, but have it up top with one column on the outer screen. Now either everything is too high on the inner screen or too low on the outer screen(requiring scrolling).

**Comment by MichalFonfara** [comment]
you could just have one widget visible only on the inner screen

**Comment by 8bitPit** [comment]
Happy to tell the home screen stack now also supports two-column mode:
https://help.niagaralauncher.app/article/100-foldable-device-support

**Comment by JigglyTurtle** [comment]
Thank you! I'll be sure to check it out.
Have a great day
