### ISSUE TITLE
Support splash screens on Android 12

### ISSUE THREAD

**Issue by tadfisher** [8bitPit/Niagara-Issues#1838]
### Is your feature request related to a problem?

On Android 12, launching an app that uses the Splashscreen API displays a blank screen.

### Describe the solution you'd like

The Pixel launcher sets an undocumented ActivityOptions flag to enable the splash screen behavior:

```java
Bundle options = ActivityOptions.makeBasic().toBundle() // or just new Bundle()
options.putInt("android.activity.splashScreenStyle", 1)
startActivity(intent, options)
```

**Comment by 8bitPit** [comment]
Oh, that's cool and works like a charm! Will be available with v1.6; thanks for letting us know :D
