### ISSUE TITLE
Launcher Crash on Surface Duo Android 11

### ISSUE THREAD

**Issue by Cheetocabra** [8bitPit/Niagara-Issues#1839]
### Describe the bug

When changing the wallpaper, the device asks what launcher to use (even though it is already set). Once you choose Niagara Launcher, the launcher fails to load ir crashes, and any open apps are stuck on their respective screens. You cannot move them, span them, or open any other apps. You also cannot go home. Restarting the device fixes the issue for that instance. 

### Steps to reproduce

1. Have a Surface Duo.
2. Update to Android 11.
3. Set the wallpaper.
4. Select Niagara Launcher as default.
5. See the bug described above. 

### Device name

Microsoft Surface Duo

### Android version

Android 11

### Screenshots / Screen recordings

![screen-20220125-082831_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/74439770/151009486-1e12ac45-58bd-4962-880f-5051268523a8.gif)

**Comment by 8bitPit** [comment]
Thanks for reporting @Cheetocabra, we'll look into it 😀

**Comment by 8bitPit** [comment]
@Cheetocabra does the issue still happen on your device? If so, please let me know :)

**Comment by Cheetocabra** [comment]
This isn't a problem after updating to Android 12L.

**Comment by 8bitPit** [comment]
Great to hear that, thanks for letting us know!
