### ISSUE TITLE
Music support

### ISSUE THREAD

**Issue by Shlokp** [8bitPit/Niagara-Issues#184]
Been using this launcher for the last few days and it's greatly helped me stop opening and closing the same apps one after each other when I've run out of things to do.

One request I have is support for Saavn Music Player. It is the Bollywood equivalent of Spotify and so having native controls on the home screen for it would be great

**Comment by 8bitPit** [comment]
Thank you, I am currently enhancing the player it will support many more apps by the next update. Please comment here, there is already an open discussion: #47
