### ISSUE TITLE
Outlook error when opening and event from "Your agenda"

### ISSUE THREAD

**Issue by renandadalte** [8bitPit/Niagara-Issues#1844]
When I try to open an event from my agenda, it opens fine with Google Calendar, but when I try to open with Outlook, it shows an error. I've created this event from my Outlook.

Here's a video:
https://user-images.githubusercontent.com/78113117/151873253-ea52f797-2110-48eb-9cc4-af836f4d27c2.mp4

**Comment by sockenklaus** [comment]
Having exactly the same problem using Niagara Launcher 1.5.3 and Outlook 4.2201.2.

**Comment by ljmusg** [comment]
Having the same issue.

**Comment by TFackler** [comment]
Hi there,

the issue you are experiencing is known to us. Sadly we have not figured out what exactly the issue is.

Please take a look at the following:
> Tapping on a calendar event shows an error.
> This is a known issue with Outlook. We believe Outlook causes this issue because we also can't open its calendar events with other calendar widget apps (e.g., Another Widget). If there's an app that can forward you to Outlook from an event, please let us know. To work around the issue, you can install another calendar app (e.g., Google Calendar) and open and edit Outlooks events with it instead.
- from our [Calendar Widget FAQ](https://help.niagaralauncher.app/article/76-calendar-faq)
