### ISSUE TITLE
Material you theming mismatch.

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1848]
### Is your feature request related to a problem?

If primary colour of wallpaper is black than niagara automatically choose some blue/purple colour font and for all background purposes.. ignoring secondary colour of wallpaper.. which leads to mismatch...
![Screenshot_20220203_123448](https://user-images.githubusercontent.com/96849717/152297345-022c427c-8704-4b45-ad13-d74ea71a9126.jpg)

### Describe the solution you'd like

There is better features in TAP TAP app which provide an option to switch between primary and secondary colour (And even tertiary colour) for material you theaming. 

Monet Compat provides pretty accurate colours which will provide good experience to those users who are not on Android 12 yet.

https://github.com/KieronQuinn/MonetCompat

https://user-images.githubusercontent.com/96849717/152297478-7854fb99-3679-4392-b822-707320d93516.mp4

**Comment by TFackler** [comment]
Thanks for reporting :)

We won't be adding an option to let the user choose between the primary, secondary and tertiary color of their wallpaper, instead we will tweak and improve our algorithm for figuring out the color used for our Material You theming. That should fix the issue you are experiencing with your mostly black wallpaper.

**Comment by Foxbat24N** [comment]
Any progress?

**Comment by 8bitPit** [comment]
We reworked the color chooser algorithm, it now deprioritizes unsaturated colors, so the issue you described should be fixed with the next update.

**Comment by 8bitPit** [comment]
Fixed in v1.7: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b
