### ISSUE TITLE
Add "Notification" letter to the alphabet

### ISSUE THREAD

**Issue by alotts** [8bitPit/Niagara-Issues#1851]
### Is your feature request related to a problem?

Notification are already visible in the application list. But the whole list is too long to quickly observe all notifications.

### Describe the solution you'd like

IMHO it could be useful to add  another "letter" to the alphabet, which will group all applications with active notifications.

**Comment by TFackler** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/152
Please see https://help.niagaralauncher.app/article/35-notification-section
