### ISSUE TITLE
Pop-up folders

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1852]
### Is your feature request related to a problem?

Not really.. it's just an aesthetic purpose..

### Describe the solution you'd like

The pop-up folder concept is great. it would be nice to have add customisation to them.  Provide a way to add background images for each Pop-ups.. you can access the settings from the pop-up options..

**Comment by TFackler** [comment]
Hi,

we think that allowing users to add background images to each pop-up folder they create is a bit much and we don't think a lot of people would use this.
If you have not already known, you can use custom icon packs to spice up your pop-up folders' looks.
