### ISSUE TITLE
Pop-up folder color choice 

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#1853]
### Is your feature request related to a problem?

It would be possible to change colors and choose from a variety of colors  for the pop-up folders. Thank you 

### Describe the solution you'd like

It would be possible to change colors and choose from a variety of colors other than clear and black for the pop-up folders. Thank you

**Comment by TFackler** [comment]
Hi there,

this sounds like a simple yet good addition to pop-up folders :)
We will discuss this feature internally and then decide whether we will implement this feature.

**Comment by TFackler** [comment]
It seems like I have misunderstood your request. I was thinking of the folder icon colors and it seems you were referring to the background of a pop-up. 

We would like to keep the backgrounds of the pop-ups uniform and will therefore not implement your requested addition.
