### ISSUE TITLE
Music widget with singer name - song name 

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#1854]
### Is your feature request related to a problem?

Hi, it is possible to have on the Music Widget not only the name of the song but also the name of the singer that scrolls example: "Michael Jackson - Thriller". Thank you 

### Describe the solution you'd like

Hi, it is possible to have on the Music Widget not only the name of the song but also the name of the singer that scrolls example: "Michael Jackson - Thriller". Thank you

**Comment by TFackler** [comment]
As per request and because the singer / band is listed below the song name in the music widget I will close this issue :)
