### ISSUE TITLE
"&" rendered as "&amp" in notification summary

### ISSUE THREAD

**Issue by annappropriate** [8bitPit/Niagara-Issues#1856]
### Describe the bug

When I open my notification summary, the ampersand on the text looks off. I believe it should be just "&" but it says "&amp" instead.

### Steps to reproduce

1. Not sure if you need to change locale. Mine is Swedish
2. Open the notification roll-up

### Device name

Unihertz Titan Pocket

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_20220216-064952-edit-20220216065149](https://user-images.githubusercontent.com/1017417/154205182-0b3918fd-f0ed-4b5b-a1ea-fda40f41708a.jpg)

**Comment by 8bitPit** [comment]
Thank you very much for reporting @annappropriate. That was an easy fix and we'll roll it out with the next update :)
