### ISSUE TITLE
Pop up widget alignment

### ISSUE THREAD

**Issue by Harishkabish** [8bitPit/Niagara-Issues#1858]
### Is your feature request related to a problem?

Placing pop up widgets in line with the home screen app list doesn't help in distinguishing the same.

### Describe the solution you'd like

Placing the pop up widgets as a colourful button alongside Niagara button in a single row with differentiating icon symbols on each widget button would reduce crowding in the apps list and also add a nice touch of colour to the screen

**Comment by TFackler** [comment]
Hello,

we feel like having both alphabetical and thematic categorization is too much, therefore we won't implement this.

If your main concern is to distinguish your pop-up folders containing widgets and your other favorites, maybe you could try to assign custom icons to your folders using icon packs.
