### ISSUE TITLE
Google Assistant's OK Google

### ISSUE THREAD

**Issue by avi12** [8bitPit/Niagara-Issues#186]
Once you integrate Google Assistant's OK Google ability into the launcher - I'll seriously consider using this launcher permanently
I love the simplicity!

**Comment by zamber** [comment]
WFM on a OnePlus 5t:
![screenshot_20180912-164732](https://user-images.githubusercontent.com/557066/45433326-3420e000-b6ac-11e8-8b61-63261ab97da2.jpg)

AFAIK launchers don't have to integrate Assistant if you install [the Google app](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en).

Then open it -> bottom right corner menu icon -> Settings -> The first two elements on the list are in the Assistant category -> tap the 1st one (Settings) -> configure everything as you want.

Also it's daily driver material IMO. You can always go back to your old launcher, even add it to favourites for the transition.

**Comment by 8bitPit** [comment]
@zamber for the explanation, @avi12 do you have any further questions?
