### ISSUE TITLE
Attempting to open a music file through Sesame search integration returns "Error", does not open

### ISSUE THREAD

**Issue by Blake-LeBlanc** [8bitPit/Niagara-Issues#1860]
### Describe the bug

After searching for a music file through Sesame, the file is shown, but tapping the file results in a small popup along the bottom of the screen that says "Error" and the file does not open.

However, if I first open Sesame as a separate app, then search for the file through Sesame itself, the file DOES open properly, firing up the default music app as expected.

This is what leads me to believe it is a bug with Sesame's integration into Niagara.

### Steps to reproduce

1. Search for music file with Sesame integration
2. Select music file from results
3. Receive "error" notice
4. Nothing further happens and music file does not play

### Device name

Moto G Play (2021)

### Android version

Android 11

### Screenshots / Screen recordings

https://streamable.com/2rmq6s

**Comment by Oddward** [comment]
It's a known issue that the devs have requested the Sesame team to help fix but response is uncertain. See the [Sesame x Niagara help article](https://help.niagaralauncher.app/article/20-sesame-integration#:~:text=I%20cannot%20open-,specific,-files%20/%20folders) for more info

**Comment by 8bitPit** [comment]
I'm sorry to tell you, but the Sesame team ceased the development. As such, the app is no longer getting updated and we cannot forward bug reports to them anymore. However, we're working on an alternative to replace Sesame.
