### ISSUE TITLE
Events not visible in Niagara widget(Calendat)

### ISSUE THREAD

**Issue by Shubham20091999** [8bitPit/Niagara-Issues#1862]
### Describe the bug

Events are not visible Niagara Widget.
It does show if there are any upcoming events(on the previous day) 

### Steps to reproduce

1. Add test item to Calendar
2. check Calendar widget

### Device name

Samsung F62

### Android version

Android 11

### Screenshots / Screen recordings

Hi and Lol are just test events I created in different accounts.
Which you can see are not shown in Niagara widget in next screenshot.

![Screenshot_20220226-073835_Calendar](https://user-images.githubusercontent.com/43275176/155824972-62137a62-5895-4e11-9279-e881d0ca7601.jpg)

![Screenshot_20220226-073615_Niagara Launcher~2](https://user-images.githubusercontent.com/43275176/155824969-f15b0e49-ba94-47e6-8420-ec2d7242a5f3.jpg)

**Comment by Oddward** [comment]
I believe those are Google Task events instead of regular calendar events? Google doesn't share tasks with 3rd party apps so Niagara can't see it unfortunately.

I'll close the issue

**Comment by Shubham20091999** [comment]
Even regular calendar events doesn't seem to show up on the day of the event, but on the day before it will show what all events are present in the calendar for the next day.

![Screenshot_20220313-091223_Calendar~2](https://user-images.githubusercontent.com/43275176/158044241-50a1664e-3489-416e-ad89-d62a969d606c.jpg)
![Screenshot_20220313-091235_Niagara Launcher~2](https://user-images.githubusercontent.com/43275176/158044267-c7f1b96f-ba53-4aa1-8dc9-a41d59d17c1c.jpg)
