### ISSUE TITLE
Set as default launcher noti doesn't disappear. 

### ISSUE THREAD

**Issue by tofuisme** [8bitPit/Niagara-Issues#1864]
![Screenshot_20220303-162635_Niagara Launcher](https://user-images.githubusercontent.com/94361006/156541365-70d036ab-1ab2-4f32-aaf8-8b87de63fadd.png)

As u can see  I tired to fix this with resetting  , uninstalling , installing latest and oldest from app but it doesn't disappear

> Android 12

Spork os latest rom

**Comment by Oddward** [comment]
Is the launcher set as the default or not? That wasn't clear

**Comment by Maxr1998** [comment]
Please read [this help article](https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default) and use the secret command if necessary (and the launcher is already your default).

**Comment by Amorphous404** [comment]
- Merged with #949
