### ISSUE TITLE
Light text and Popup remove shadow

### ISSUE THREAD

**Issue by IndomitableAlbus** [8bitPit/Niagara-Issues#1866]
### Is your feature request related to a problem?

I know that the Dev's aren't keen on UI alterations but I think this one should be considered.
Please can the Dev's either remove or allow the user to toggle off the shadow effect on White text and possibly the Popups.
I understand why the effect is there but it's so out of date and totally not " Material You " which is all about clean, sharp lines.
I'm almost always using Dark text mode because Light text looks so bad.
Thank you.

### Describe the solution you'd like

Remove or allow user to remove shadows on text and Popups.

**Comment by TFackler** [comment]
Thanks for reaching out to us :)

Sadly we feel like allowing the user to turn on and off the drop shadow for the font and pop-ups would add too much clutter to the settings and make them more complicated than necessary. In exchange for this complexity all users would have to face the benefit it provides seems rather small. Therefore we won't be implementing this.
