### ISSUE TITLE
Galaxy fold issue when folding

### ISSUE THREAD

**Issue by wesayno** [8bitPit/Niagara-Issues#1867]
### Describe the bug

I am using a Samsung Galaxy Z Fold3. There is an issue with the launcher, while being on the homescreen in unfolded mode, if you fold the phone and immediately unlock it (for example if I've used an app unfolded but want to continue using the phone in folded mode) you don't come to the homescreen, you come to the "search" screen (the screen you get to if swiping up on the home screen). Sorry if I'm bad at explaining but the steps to reproduce might help.

In short: Going from unfolded mode on the homescreen, to folding the phone and immediately unlocking it, I end up on the search screen and not the home screen.

### Steps to reproduce

1. Go to the homescreen in unfolded mode.
2. Fold the phone.
3. Immediately unlock it (for me specifically; with fingerprint) in folded mode.

### Device name

Samsung Galaxy Z Fold3

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20220305-031421_Niagara Launcher](https://user-images.githubusercontent.com/9746942/156863779-230c7467-efa1-47e1-9d82-86b1a6d6df5a.jpg)

![Screenshot_20220305-031408_Niagara Launcher](https://user-images.githubusercontent.com/9746942/156863783-27f54716-0a5a-48a7-92c1-6308575dd5c9.jpg)

**Comment by Amorphous404** [comment]
Hello, @wesayno, could you please check if you are still encountering the issue in the latest version [v1.8.13](https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.13), and let us know?
