### ISSUE TITLE
Shortcuts are reversed

### ISSUE THREAD

**Issue by ArnaudLigny** [8bitPit/Niagara-Issues#1868]
### Describe the bug

Shortcuts are displayed in the wrong order.

### Steps to reproduce

1. Slide an app icon to display shortcuts (if exists)
2. Note that they are displayed in the wrong order

### Device name

Google Pixel 4a 5G

### Android version

Android 12

### Screenshots / Screen recordings

Default (Google)'s behavior:
![2db57155-63f2-476b-8bb7-1aef08860dd8](https://user-images.githubusercontent.com/80580/156907074-312190d5-e589-4056-947e-ff72a21699fd.png)

Niagara's behavior:
![Screenshot_20220114-122455](https://user-images.githubusercontent.com/80580/156907077-5c82f86b-9458-4300-8743-f8e68c522eba.png)

**Comment by ArnaudLigny** [comment]
Hello @Maxr1998 , thanks for your answer. I understand the philosophy of the product and this is why I love it.

I'm still confused by this menu inversion, but maybe it's just me :stuck_out_tongue:

**Comment by Maxr1998** [comment]
Understand that. It might take a while to get used to it.

**Comment by 8bitPit** [comment]
Update: Launcher3 and Google's Pixel Launcher seemed to have stopped sometimes reversing their shortcuts 🎉 There's no need for that workaround we added, so with the next major update, shortcuts will display in the correct order.

**Comment by ArnaudLigny** [comment]
Yeah, great news, thanks @8bitPit for this feedback.

**Comment by 8bitPit** [comment]
Welcome; thank you for writing us! Fixed in v1.7: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b
