### ISSUE TITLE
Latency and reliability issue when swiping down notifications on home screen

### ISSUE THREAD

**Issue by awnumar** [8bitPit/Niagara-Issues#1870]
### Describe the bug

When on the homescreen, you're able to swipe down from anywhere on the screen to access the notifications drawer. In my experience, there's two issues with this:

1. Sometimes the swipe isn't successful and all that happens is the favourite apps move a little without the notification drawer coming down.
2. When the swipe *is* successful, there's a noticable delay inbetween the swipe and the notification drawer actually coming down. What happens is first the favourite icons move, then after they hit the "bottom" of their movement the notifications drawer comes down. Compare this with swiping from the status bar: the notifications drawer comes down instantly with no delay and it works all the time.

This behaviour makes the gesture feel sluggish and annoying

### Steps to reproduce

1. Go to home screen
2. Swipe down from anywhere on the screen, such as the middle or the bottom for example.

### Device name

OnePlus 7T

### Android version

Android 11

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/8942495/156927702-47e40066-3746-4cd9-a88c-10b3a08f4834.mp4

**Comment by Oddward** [comment]
Duplicate: see this older issue [1588](https://github.com/8bitPit/Niagara-Issues/issues/1588)

**Comment by awnumar** [comment]
Maybe, although it's not just the latency that's an issue it's also that sometimes the gesture doesn't work at all and the notification tray doesn't come down

**Comment by Oddward** [comment]
Yes that's the main point discussed in that issue. The list's bounce/stretch effect is just visual aid, it's not really relevant to the issue
