### ISSUE TITLE
YouTube watch later not working from YouTube swipe option

### ISSUE THREAD

**Issue by onlytanmoy** [8bitPit/Niagara-Issues#1873]
### Describe the bug

When I swipe right on YouTube notification and click watch later option, it doesn't actually add that video to my YouTube watch later playlist.

### Steps to reproduce

Basically the description of the bug, let me know if you need more info

### Device name

Galaxy S20 FE 5G

### Android version

Android 12

**Comment by Oddward** [comment]
Is this still the case now? Do you mean the button on the embedded notification doesn't respond to pressing or that once you press it and check your Youtube lists it's not there?

**Comment by onlytanmoy** [comment]
Nope, not facing this issue anymore today. I tried with 2 YouTube notifications and both got added successfully to my Watch later playlist 😊 Closing this ticket, cheers mate.
