### ISSUE TITLE
Show event location in calendar widget

### ISSUE THREAD

**Issue by matosjoaops** [8bitPit/Niagara-Issues#1874]
### Is your feature request related to a problem?

The feature request isn't related to a problem.

### Describe the solution you'd like

I would like an option to have the location of an upcoming event shown in the Niagara calendar widget.

**Comment by TFackler** [comment]
Hello there,

thanks for reaching out. Sadly we won't be adding this feature. 

We feel like showing the location of the next event directly on the home screen would clutter the interface. Adding an option to allow some users to show the location directly would turn the settings less straight forward. Also when opening the more detailed view of the agenda you are able to see the location of the event, so the information is only one tap away :)
