### ISSUE TITLE
Option to Hide the *selected* hidden apps in search results.

### ISSUE THREAD

**Issue by Foxbat24N** [8bitPit/Niagara-Issues#1877]
If possible then put an option to hide the (Selected) hidden apps in search results - The way we select apps for notification summary in the same manner if we can select (some)apps which will not be shown on search results so that they can be made disappeared from the search results. I used the phrase "If possible" intentionally because may be because of seasame it couldn't possible for you to do that. It's not beneficial all the time yet sometimes it helps. 
![Screenshot_2022_0314_054930](https://user-images.githubusercontent.com/96849717/158085975-5a683759-ee1d-4977-a1c4-2fbd18928b62.gif)

**Comment by Foxbat24N** [comment]
Well, I totally agree with your viewpoint... I use search for hidden apps as well as web search or contacts ... I mean everything. 

But if we can add some qps which can be hidden from search result .. it will be bliss for me... The way be select apps for notification summary in the same manner if we can select apps which will not be shown on search results then it work fine for me.

**Comment by Maxr1998** [comment]
Alright, thanks for the reply. I'll close this issue then so that we can focus on other reports. If we eventually change our decision, we'll update this issue.
