### ISSUE TITLE
Whole Niagara Launcher resets itself to some default state

### ISSUE THREAD

**Issue by alenjularic** [8bitPit/Niagara-Issues#1878]
### Describe the bug

This has happened 2 times in the past month, I have no idea what causes it, but the launcher with no input from me completely resets itself, all folders, favorites, widgets, hidden apps gone.

I did nothing in particular, the next time I unlocked the phone all I see is a completely blank launcher. Using Niagara 1.5.6.
I don't need to describe how annoying it is to set everything up all over again...

### Steps to reproduce

Don't know what causes it, or how to replicate it...

### Device name

OnePlus 9 Pro

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_2022-03-17-10-32-56-60_a4824db61f40c53807964ea8b14c92fe](https://user-images.githubusercontent.com/22047276/158780535-4954362b-b6cb-47e2-bea2-b05a85786f17.jpg)

**Comment by Oddward** [comment]
Strange

Did you try restarting Niagara when it happened? And have you tried reinstalling the app since?

**Comment by alenjularic** [comment]
Yeah I did. I force stopped it, after that didn't help, I tried reinstalling it to see if maybe the automatic backup and restore would restore the Niagara launcher data. Unfortunately it did not.

It could also be that the buggy OxygenOS12 had something to do with it. However it only happened with Niagara. I guess it's a very unfortunate series of events...

**Comment by Oddward** [comment]
Why was this issue closed? 

It does seem like some conflict with the local data or backup data. You don't have any resource managing app installed that might clear app data, do you? If Niagara's app data is manually cleared it won't restore to an earlier state. 
And is connection to your google services fine?

**Comment by alenjularic** [comment]
I closed it because it seems like a very obscure bug. If it happens again I'll reopen it. Or if it happens to someone else, they can reopen it. 

I don't have any apps that can clear app data. As for the google services connection, as far as I know they were working OK.
