### ISSUE TITLE
Clock customization 

### ISSUE THREAD

**Issue by mrtomwolf** [8bitPit/Niagara-Issues#188]
Showed my wife the launcher. Her first reaction was to ask if the clock could be analog and centered. It's a thing for her so I'm requesting it =)

**Comment by Shinra04** [comment]
A centred clock would look weird in this launcher. But analog clock is a good idea.

**Comment by KingCollo97** [comment]
This is a feature request related to this: ability to replace the clock widget with a custom widget say a KWGT Widget

**Comment by 8bitPit** [comment]
@plnsgr want's to adjust the clock size (#610)

**Comment by MyChiMan** [comment]
I want to add to the thread and ask if it's possible to move the position of the clock?

I have a good finger of space from the clock to the notifications. If you could move "everything" up that would allow more favorites and or when using a widget like Spotify allow the room to be there without one of your favorites disappearing.

Great work btw on this app

**Comment by 8bitPit** [comment]
@MyChiMan that's nice of you to say :)
In the next update the space above the clock will be reduced for larger phones. Moreover, you'll be able to customize it at some point: https://github.com/8bitPit/Niagara-Issues/issues/112

**Comment by Bushmills** [comment]
/me wonders whether it be more effective to drop built-in clock altogether, not bother about analog clock, but instead focus on (single) widget support, and let requesters install any funky clock widget they like. Or different things you wouldn't start to implement as integral part of Niagara. I know that once I can place one widget there, I will replace the clock immediately, hence becoming ballast in the shape of dead code,

**Comment by TheTimTamSlam** [comment]
I would love a centered clock. I have a super minimal set up (no apps or widgit) and like the feel of a centered clock a lot more. I know I can do this with a widgit, but I just love the look and feel of the clock and calender options you already provide. This could look like the option to move the clock in left and right directions, or even just a left and centered option. Whichever you feel is better for customization or simplicity

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
