### ISSUE TITLE
Suggestion: To Enhance Niagara Widgets On Homescreen (Favorites)

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1880]
### Describe the solution you'd like

![Widget Space Mockup 1](https://user-images.githubusercontent.com/96917972/159638046-c2b967de-feaf-447b-9244-f5b75292cdbd.jpg)
![Widget Space Mockup 2](https://user-images.githubusercontent.com/96917972/159638056-18a048f0-6cec-46c0-afcb-be1190495ebe.jpg)
![Widget Space Mockup 3](https://user-images.githubusercontent.com/96917972/159638059-9ac74552-af12-4101-9662-775d3039653b.jpg)

Another Suggestion In Accordance With Stackable Widget That Will Enhance Widget On Niagara 😅

We currently can't resize the widget horizontally nor can we keep space between the widgets and favorites apps, alternatively we can do it but with blank widget we can't use another widget as we are limited to only one Widget, so came up with this idea, idk if it's feasible, but it's simple and clean.

Concept:

Instead of The Option Add Custom Widget Option , It will be cool if it's replaced with a Widget Space  Option, where in there will be grids (space), where users will be able add custom single or multiple widget in that space, and adjust the size accordingly and keep space between the widget and favorites apps without have to waste widget by replacing it with black widget 🙂

I feel like this will be more flexible, and will the solve issue of users asking for widget panel and other stuff.

**Comment by topsy-turvy99** [comment]
> ### Is your feature request related to a problem?
> _No response_
> 
> ### Describe the solution you'd like
> ![Widget Space Mockup 1](https://user-images.githubusercontent.com/96917972/159638046-c2b967de-feaf-447b-9244-f5b75292cdbd.jpg) ![Widget Space Mockup 2](https://user-images.githubusercontent.com/96917972/159638056-18a048f0-6cec-46c0-afcb-be1190495ebe.jpg) ![Widget Space Mockup 3](https://user-images.githubusercontent.com/96917972/159638059-9ac74552-af12-4101-9662-775d3039653b.jpg)
> 
> Another Suggestion In Accordance With Stackable Widget That Will Enhance Widget On Niagara 😅
> 
> We currently can't resize the widget horizontally nor can we keep space between the widgets and favorites apps, alternatively we can do it but with blank widget we can't use another widget as we are limited to only one Widget, so came up with this idea, idk if it's feasible, but it's simple and clean.
> 
> Concept:
> 
> Instead of The Option Add Custom Widget Option , It will be cool if it's replaced with a Widget Space Option, where in there will be grids (space), where users will be able add custom single or multiple widget in that space, and adjust the size accordingly and keep space between the widget and favorites apps without have to waste widget by replacing it with black widget 🙂
> 
> I feel like this will be more flexible, and will the solve issue of users asking for widget panel and other stuff.

And yes if  it feels like too much for Niagara, you can limit it to only two Widgets 😅, The Sole Reason I'm Asking about thi this is because it will the user resize and position the one widget that we get on Homescreen perfectly

**Comment by Oddward** [comment]
Widget support is intentionally made simple on Niagara, both to make it simple for simple users and as part of Niagara's intention to reduce dependance on widgets and a cluttered interface. Niagara's built-in at-a-glance widget is there coz it covers like 80% of the data most people use widgets for.

This along with stacked widgets would complicate the code base as well as the UX for users that use Niagara for its simplicity. Pop-up widgets were developed to avoid this kind of UX

**Comment by topsy-turvy99** [comment]
> Widget support is intentionally made simple on Niagara, both to make it simple for simple users and as part of Niagara's intention to reduce dependance on widgets and a cluttered interface. Niagara's built-in at-a-glance widget is there coz it covers like 80% of the data most people use widgets for.
> 
> This along with stacked widgets would complicate the code base as well as the UX for users that use Niagara for its simplicity. Pop-up widgets were developed to avoid this kind of UX

Okay, This Isn't much of thing that's needs to be implemented, i was just looking for a way to resize the widget horizontally, and a way to keep the widget at top and favorites apps at the bottom, 

But Stack Widget, Really Seemed Cool For Niagara And Impactful For Niagara, It's Really Simple To Use, Even A Layman Can Use it, I Bet You've tried it out

But If stack widgets alone seems possible in any way, and doesn't cause any issue to launcher code please try to give it a thought, It Would Really be Great For Launcher Like Niagara.

Thank You

**Comment by Oddward** [comment]
The idea is fair, but as mentioned in the other issue the goal is not to incentivize users to use more widgets, it's the opposite, so we're afraid that features like stacked widgets or a widgets page incentivizes users to add many widgets and makes for a more cluttered/clunky experience

Widgets were more significant in the past when phones were slower & apps took too long to check, now most apps don't even offer a widget. Having multiple widgets in one space also needs to load all of them into memory & update them regularly which is wasteful when you only need to check a specific piece of data at a time (hence, single pop-up widgets), stacking/swiped pages is also complicated with widgets having multiple diff sizes


I think it would be cool to be able to shrink apps horizontally, at least to make it half, but having a dynamic grid like that is like developing another home screen layout just to support adding more widgets in a less Niagara way 🤔 


_Why insist on grouping all your widgets on the home screen instead of utilizing unique features like the **pop-up widgets** and **Niagara button**?_

**Comment by topsy-turvy99** [comment]
> The idea is fair, but as mentioned in the other issue the goal is not to incentivize users to use more widgets, it's the opposite, so we're afraid that features like stacked widgets or a widgets page incentivizes users to add many widgets and makes for a more cluttered/clunky experience
> 
> Widgets were more significant in the past when phones were slower & apps took too long to check, now most apps don't even offer a widget. Having multiple widgets in one space also needs to load all of them into memory & update them regularly which is wasteful when you only need to check a specific piece of data at a time (hence, single pop-up widgets), stacking/swiped pages is also complicated with widgets having multiple diff sizes
> 
> I think it would be cool to be able to shrink apps horizontally, at least to make it half, but having a dynamic grid like that is like developing another home screen layout just to support adding more widgets in a less Niagara way 🤔
> 
> _Why insist on grouping all your widgets on the home screen instead of utilizing unique features like the **pop-up widgets** and **Niagara button**?_

I don't know how to reply to all this 😅, I'm not good at putting my mind out,

It's not about incentivising widgets, it about giving user options to user who uses widgets and want to use Niagara with multiple widgets, widgets isn't a thing of past, it's been much better now then what is used to be, with a12 android trying to make widgets better, goodl looking, functional and optimised, and other other developer taking inspiration, there is likely more cool widgets will come along the way,

The whole notion of stacking Widget started with ios, followed by action launcher replicating it in it's launcher (been a year), and now samsung (https://www.androidpolice.com/how-to-use-samsung-smart-widgets/) and with time more oem launcher and third party launchers will likely introduce it, and I don't want Niagara to be left behind.

I know Niagara devs, can add it, but will need some extra effort and time to add it, take your time, no worries on that,

I made everyone around me, to install Niagara launcher, the only complaint i get to hear, are the lack of multiple widget support.

Pop ups are cool, and really appreciate the way it's implemented 🙂, it's better when a widget is added to an app swipe, but gets troublesome, when a user adds it to widget to a popup folder, we can only add single widget when the apps in the popup have their own widgets, and it adds an extra action of swipe down to get the pop up apps, that's why I can't totally make use of it, and about the buttons i use it for different function as we are limited to two gestures so dont wanna waste it on a single Widget 🙂

And about stack widget consuming more ram, you can add a warning when placing a stack widget to make the user aware, that it will use more ram and a warning when placing a non supported widgets on stack.

You guys have much better idea on how to get it done, from what i understand you are not much into widgets that's what's stopping from coming up with a great idea for widgets 😅,

I just want thay you don't close this ticket and keep it low priority ✌️

Here's a ss of me using it in folder see it's not quick to get access to the apps, and lacks adding the widgets from other apps in that folder.
![Screenshot_20220324-105708_Niagara Launcher](https://user-images.githubusercontent.com/96917972/159848515-c72af4e2-4d68-44f5-b850-27f4693b5630.png)

**Comment by Oddward** [comment]
Thanks for clarifying~

It's not usually coz it's difficult that requests are rejected, it's coz it doesn't fit the [launcher's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles) (see the short explanation there). Stacks were suggested since the original iOS announcement, but they're similar to a widgets page (mentioned in [this help article](https://help.niagaralauncher.app/article/41-adding-multiple-widgets) by devs)

Users normally switch from their stock launcher coz they find Niagara simpler, faster & cleaner (that's how it's advertised), what's popular on stock launchers isn't what the target audience usually wants unless it enhances the existing UX, right? 😅

Improving widget support overall is a work-in-progress, but some ideas add a lot of redundancy with existing features now. 

### Suggestion for you
There's diff ways of utilizing the launcher for your use case, e.g. since you have a widget for each payment app you could place their widgets inside their own pop-ups, then
- leave them in the app list under the same letter/symbol for quick access, or
- hide them & use Niagara search (e.g. "Pay") to see them and swipe the one you want
...it shows you only what you need right now

*(remember you can rename apps to change their arrangement or search your custom text)*

_Btw, Niagara button pop-up widgets are like regular pop-ups and can have apps/shortcuts too_

### Suggestion for devs
It might help to have a 3rd option between the widget's "fill screen" option and normal full width option, maybe a **"half width"** if feasible, cycling between the three when the option is selected - it might help with smaller widgets 👀

**Comment by Foxbat24N** [comment]
Which font are you using?

**Comment by topsy-turvy99** [comment]
> Thanks for clarifying~
> 
> It's not usually coz it's difficult that requests are rejected, it's coz it doesn't fit the [launcher's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles) (see the short explanation there). Stacks were suggested since the original iOS announcement, but they're similar to a widgets page (mentioned in [this help article](https://help.niagaralauncher.app/article/41-adding-multiple-widgets) by devs)
> 
> Users normally switch from their stock launcher coz they find Niagara simpler, faster & cleaner (that's how it's advertised), what's popular on stock launchers isn't what the target audience usually wants unless it enhances the existing UX, right? 😅
> 
> Improving widget support overall is a work-in-progress, but some ideas add a lot of redundancy with existing features now.
> 
> ### Suggestion for you
> There's diff ways of utilizing the launcher for your use case, e.g. since you have a widget for each payment app you could place their widgets inside their own pop-ups, then
> 
> * leave them in the app list under the same letter/symbol for quick access, or
> * hide them & use Niagara search (e.g. "Pay") to see them and swipe the one you want
>   ...it shows you only what you need right now
> 
> _(remember you can rename apps to change their arrangement or search your custom text)_
> 
> _Btw, Niagara button pop-up widgets are like regular pop-ups and can have apps/shortcuts too_
> 
> ### Suggestion for devs
> It might help to have a 3rd option between the widget's "fill screen" option and normal full width option, maybe a **"half width"** if feasible, cycling between the three when the option is selected - it might help with smaller widgets 👀

Okay, i won't make this discussion long, i used stack widget for some days in action launcher and really loved the quick Access to different widgets without cluttering the Launcher, how smooth and robust it felt and thought why can't i have it in on of my favorite launcher (Niagara) and it meet three principles of Niagara i.e simple,, impactful independent, literally everyone had been asking for multiple widgets, and even when i posted this mockup on group lot of people asked me on how to add it in Niagara 😅, but yes the devs have their own ideas i respect that, It's just me wanting to make Niagara super functional, honestly speaking i don't use Niagara for simplicity, i just felt in love with the app list on how quickly it let me access to all my apps and the fluidity of it 😊,

Anyways you can close this ticket, will wait for something better along the way 😊

**Comment by topsy-turvy99** [comment]
> Which font are you using?

The bottom one is Typo Round, The First One I'll have to check it out, i cleared up Niagara data so it's not in my font list 😅

**Comment by TFackler** [comment]
Thank you guys for your thorough discussion, we have taken note, but don't think the original request (the one for being able to adjust spacing between the home screen widget and the favorite app list) is a feature we want to implement. It would lead to a more complicated UI for editing the home screen and we don't think it's impact justifies that change.

In regards to the widget discussion, please refer to the responding issue: #1879, #1330
