### ISSUE TITLE
Manually Changed Icon Doesn't Adapt Shape Nor The Dynamic Color

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1881]
### Describe the bug

Manually Changed Icons Fails To Refresh The Shape And Color In Niagara,

I Tried It In Lawnchair, It Works There, Both The Icon Shape And Color Changes When I Refresh Or Change The Shape In Launcher Settings.

App Icon: Youtube (Example)
Icon Pack: https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.dark

### Steps to reproduce

1. Niagara Settings>Look>Icon Shape (Change The Icon Shape)
2.  All Icons Shape Changes Except The Manually Selected Icon

Same For Icon Pack: Select The Same Icon Pack To Refresh The Color, All Icons Change Color Except Manually Selected Icons

### Device name

Redmi Note 8

### Android version

Android 12

### Screenshots / Screen recordings

Niagara
![Screenshot_20220323-180720_Niagara Launcher](https://user-images.githubusercontent.com/96917972/159701788-9ecc80a4-f337-40fc-984c-2198681cdfeb.png)
Lawnchair
![Screenshot_20220323-180613_Lawnchair](https://user-images.githubusercontent.com/96917972/159701797-c4e73580-39f3-4df6-91ab-4dae1b3a54d6.png)

**Comment by TFackler** [comment]
We intend to work on this, but it seems like it will take a lot of effort and it is not our highest priority right nowm therefore implementation of this feature will likely take a while.
