### ISSUE TITLE
Secret codes

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#1884]
### Is your feature request related to a problem?

When you are using sesame with Niagara and you want to type in any Niagara secret codes it doesn't work.. you have to turn off sesame integration and then search for the Niagara secret codes...

### Describe the solution you'd like

Please add your secret codes to sesame integration

**Comment by Oddward** [comment]
Sesame doesn't interfere with secret commands. If you're sure of the issue please share a screenshot or some visual aid and reopen it. 

If you spell them correctly (starting with the forward slash `/`) they work, if you make a typo it'll probably trigger a search result
