### ISSUE TITLE
 Multiple icon packs

### ISSUE THREAD

**Issue by juliex22** [8bitPit/Niagara-Issues#1885]
### Is your feature request related to a problem?

Poor support for dynamic icons.

### Describe the solution you'd like

Well, I discovered a feature in another launcher that I hadn't seen in any other: the possibility to apply more than one icon pack. I found it very useful because most of the time the icon pack is not complete. Also, it would be awesome for someone who uses dynamic icons like me. Because when I change one individually, the refresh to update them doesn't work.

**Comment by Maxr1998** [comment]
I fear this would be too complicated to implement while only having limited use. Instead, we should maybe support refreshing manually selected icon packs, which isn't easy to implement either, but useful for more people and only improves on an already existing feature. I'd suggest you open another ticket for that, though.
