### ISSUE TITLE
How to allow notification access using adb.

### ISSUE THREAD

**Issue by Dr-Sauce** [8bitPit/Niagara-Issues#1886]
My phone doesn't have the notification settings so I'm trying to enable it by using adb.

![Screenshot_2022-03-26-10-27-33](https://user-images.githubusercontent.com/82555878/160219462-c776b344-dc65-4936-87eb-b5f4336bb84e.png)

Does anyone know how I can enable it?

![Screenshot_2022-03-26-10-34-39](https://user-images.githubusercontent.com/82555878/160219516-833685df-d61d-493d-8536-16a521a7e7ca.png)

![Screenshot_2022-03-26-10-28-00](https://user-images.githubusercontent.com/82555878/160219488-844aa3ac-37c3-4014-9c6b-1eb4cfb91d5b.png)

**Comment by Oddward** [comment]
This github repo is for Niagara support, not ADB 😅 please don't misuse it. You could've asked this in the community channels for quicker answers. 

If notification access isn't available it's likely the system doesn't support it and ADB is unlikely to help (the system can block ADB commands anyway). You didn't mention your device details. 

See this quick google to [stackoverflow](https://stackoverflow.com/questions/48855434/enable-notification-access-using-adb)

**Comment by Dr-Sauce** [comment]
@Oddward Sorry for posting here. 

Well, I've searched for answers and I've seen that post. But that adb command doesn't work. Is the command below correct?

`adb shell settings put secure enabled_notification_listeners %nlisteners:bitpit.launcher/bitpit.launcher.service.ServiceNotificationIntercept`
