### ISSUE TITLE
Spotify not playing when screen is off/locked

### ISSUE THREAD

**Issue by Dominoricano** [8bitPit/Niagara-Issues#1888]
### Describe the bug

Spotify will not play music unless screen is on. This issue occurs once i enter either locked screen/always on/ or locked screen with screen off. The music stops playing completely or will play intermittently. 

### Steps to reproduce

Turn Spotify music on, and play music. 
Lock screen. 

### Device name

Samsung Galaxy Z Fold 3

### Android version

Android 12

**Comment by timm0e** [comment]
Thank you very much for reporting. Does the same bug also occur when using another third-party launcher (e.g., Nova Launcher, Lawnchair or Microsoft Launcher)?
