### ISSUE TITLE
Recent apps not working on Poco f1

### ISSUE THREAD

**Issue by nnvkiran** [8bitPit/Niagara-Issues#189]
I have Poco f1 and recent apps are not being populated.

**Comment by nnvkiran** [comment]
It's been 3 days

**Comment by 8bitPit** [comment]
Try to unpin some favorites, maybe they would be suggested.

**Comment by nnvkiran** [comment]
Yes it's working but I have 8 favorites as suggested. It's showing max 8 apps and not scrolling
