### ISSUE TITLE
Add Sort Apps By Name In Pop Up Folder

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1891]
Greetings :)

Thank you for your suggestion. Unfortunately we do not plan on adding this right now, but we might take a look at it in the future.

_Originally posted by @TFackler in https://github.com/8bitPit/Niagara-Issues/issues/1835#issuecomment-1030629284_

I feel like this is the right time to reopen the issue,  it's great that now we can sort app my app usage, wouldn't it be great, if in the same button tapping on it will give other option like sort by name, as user like me likes to keep the apps sorted it alphabetical order to easily look for the apps, as mentioned previously it very tedious to rearrange the app everytime, when a new app is added to the pop up.

Hope, you'll take it under consideration.

Thank You

**Comment by topsy-turvy99** [comment]
![IMG_20220329_130959_099](https://user-images.githubusercontent.com/96917972/160561930-d9ec7a58-084b-4a65-8490-550755db3997.jpg)

**Comment by TFackler** [comment]
Hey there,

would you mind elaborating on your use case?

We feel that in folders with lots of apps it would be more useful for users to have apps they use frequently at the top of the list as to not have to scroll far until they find what they are searching for. 
Your specific use case (icon packs from what I can tell) is handled differently. Users are intended to choose their icon packs using our built-in selection dialog (Niagara settings > Look > Icon pack). In that dialog the icon packs appear in alphabetical order.
Maybe that solves your issue, if not feel free to elaborate more :)

**Comment by topsy-turvy99** [comment]
> Hey there,
> 
> would you mind elaborating on your use case?
> 
> We feel that in folders with lots of apps it would be more useful for users to have apps they use frequently at the top of the list as to not have to scroll far until they find what they are searching for. Your specific use case (icon packs from what I can tell) is handled differently. Users are intended to choose their icon packs using our built-in selection dialog (Niagara settings > Look > Icon pack). In that dialog the icon packs appear in alphabetical order. Maybe that solves your issue, if not feel free to elaborate more :)

i understand, it's just that I'm a little bit ocd, i like keeping things organized, icon packs folder was just as example as it includes lot of apps, and icon packs are not only used for icons, some of them include wallpaper too 😅like every other launcher provides a way to sort apps with various option be it folder or app drawer, since it's Niagara the exception can be made on app list, but with folders I'm happy with the new option of sort by usage it's great

sort by app name wouldn't be hard to implement and it won't clutter Niagara, just tapping on it will show different option that a user can select, just like the screenshot i shared 🙂

**Comment by topsy-turvy99** [comment]
> > Hey there,
> > would you mind elaborating on your use case?
> > We feel that in folders with lots of apps it would be more useful for users to have apps they use frequently at the top of the list as to not have to scroll far until they find what they are searching for. Your specific use case (icon packs from what I can tell) is handled differently. Users are intended to choose their icon packs using our built-in selection dialog (Niagara settings > Look > Icon pack). In that dialog the icon packs appear in alphabetical order. Maybe that solves your issue, if not feel free to elaborate more :)
> 
> i understand, it's just that I'm a little bit ocd, i like keeping things organized, icon packs folder was just as example as it includes lot of apps, and icon packs are not only used for icons, some of them include wallpaper too 😅like every other launcher provides a way to sort apps with various option be it folder or app drawer, since it's Niagara the exception can be made on app list, but with folders I'm happy with the new option of sort by usage it's great
> 
> sort by app name wouldn't be hard to implement and it won't clutter Niagara, just tapping on it will show different option that a user can select, just like the screenshot i shared 🙂

tbh i even have sort all apps list by usage disabled in Niagara setting 😅, i know it's useful and make sense to keep the apps that one use often at the top

**Comment by TFackler** [comment]
Hey there, 

thanks for clarifying. Sadly we don't feel like this change would benefit enough users and thus we don't deem it impactful enough to add.

**Comment by topsy-turvy99** [comment]
Okay thank you
