### ISSUE TITLE
[Bug] Launcher randomly sets off the notification sound with a double vibration

### ISSUE THREAD

**Issue by JacksonCampbell99** [8bitPit/Niagara-Issues#1894]
### Describe the bug

I can't tell any rhyme or reason to it, but ever since I got this launcher I have been getting notification alerts from the launcher without there being any notification. The phone can be on or off. I think it may also be triggering accessibility since there has been a spike in launcher and accessibility vibrations caught since installing this. It is logged in Samsung's Nice Catch.

### Steps to reproduce

Nothing special. I installed it, started using it regularly, and it has been doing this. They were coming in as I was doing this.

### Device name

Samsung Galaxy S20

### Android version

Android 12

### Screenshots / Screen recordings

![image](https://user-images.githubusercontent.com/76508020/161134364-c0863954-d270-47e6-abab-827fd8cb0bdb.png)

![image](https://user-images.githubusercontent.com/76508020/161133350-e222a034-ad40-486f-9a43-59cde6347dd0.png)

**Comment by TFackler** [comment]
Hey there,

Niagara Launcher only sends notification if the 'Notification Summary' is enabled. Are you using said feature?

Also have I understood you correctly that the notifications from Niagara you receive let your phone vibrate?

**Comment by JacksonCampbell99** [comment]
It is not sending notifications. It is making the notification sound and vibrating. As you can see in the screenshots, it can happen every minute, multiple times/minute, or a good while between.

**Comment by JacksonCampbell99** [comment]
I definitely responded.

**Comment by TFackler** [comment]
Hello again,

sorry that the bot just decided to close this issue. Bad bot *bonk*.

We are as confused as you are about Niagara sending this many notifications. It should only do that if you have the notification summary enabled, which you don't and even then they would be a lot less frequent.

After a quick search we also found threads about people having similar issues, like this [thread](https://us.community.samsung.com/t5/Galaxy-S21/Random-notification-sound-but-no-notification-on-my-S21/td-p/1674212) on Samsung's community forums.

If nothing else works, we suggest you disable Niagara's notifications themselves. You can so by going to `Niagara settings > Advanced > App info > Notifications > All Niagara Launcher notifications`.

**Comment by JacksonCampbell99** [comment]
Ok. I will try using the launcher again and test if it is doing it, then try turning off the notifications and see if that stops it. It appeared that it might have been also triggering accessibility, so we'll be able to see if that is the case as well.

**Comment by JacksonCampbell99** [comment]
I re-set the launcher as default and have been using it the last several days. There have been no notification buzzes, so possibly an update fixed the issue since last time I was using it.

**Comment by TFackler** [comment]
We are glad you are no longer experiencing the issue :)
Also thanks for reaching out to us about it and giving Niagara another chance 👍
