### ISSUE TITLE
Sesame search integration not working for installed applications

### ISSUE THREAD

**Issue by ldaniluk** [8bitPit/Niagara-Issues#1897]
### Describe the bug

Sesame is not used in Niagara integration, examples:

- ignoring dashes: if there is an app called "E-mail", in Sesame I can write "email" and it will show up. In Niagara I have to write "e-mail"
- prefix search: if there is an app called "Hue Essentials", in Sesame I can write "hues" and it will show up (matching two first letters of Hue and two first letters of Essentials), in Niagara I have to write using double e "huees"

### Steps to reproduce

1. Install "Hue essentials" app or other app with space in its name.
2. Search for the app in Niagara with Sesame installed and integration enabled. Search query should contain prefixes of two words without space, for example "hues" in case of Hue Essentials.
3. Notice that Niagara does not suggest the app.
4. Notice that Sesame suggests the app.

### Device name

Samsung Galaxy S21 Ultra

### Android version

Android 12

### Screenshots / Screen recordings

I have cropped some screenshots for privacy reasons.

![Screenshot_20220401-085119_Niagara Launcher](https://user-images.githubusercontent.com/5917842/161211175-88268f9c-5014-497d-8af4-70fee4957f69.png)
![Screenshot_20220401-085130_Niagara Launcher](https://user-images.githubusercontent.com/5917842/161211182-5f936e72-e7a8-413f-a25f-7111888ed313.png)
![Screenshot_20220401-085148_Sesame](https://user-images.githubusercontent.com/5917842/161211187-9083cc4b-803b-426e-8ab3-5e6a45b441e7.png)
![Screenshot_20220401-085205_Sesame](https://user-images.githubusercontent.com/5917842/161211194-d744df65-0034-4b11-8e9e-bf9d563288e3.png)
![Screenshot_20220401-085237_Niagara Launcher](https://user-images.githubusercontent.com/5917842/161211195-dfba2d50-d3f7-439e-9531-cb09d2382494.png)
![Screenshot_20220401-085250_Niagara Launcher](https://user-images.githubusercontent.com/5917842/161211196-83c3d686-da1d-41a5-87fc-10ee48235979.png)

**Comment by TFackler** [comment]
Hey there, thanks for reaching out.

We plan on improving our search algorithm. The reason we have been waiting with that is however, that devs over at Android are working on a library for making searches easier and we are currently waiting for its release before updating our search algorithm.

Also there is an old issue about this, so I will close this and link the original: #411
If you have more to add or questions, feel free to head over to the linked issue :)
