### ISSUE TITLE
-Suggestion- Include folders instead of 8 favorite apps 

### ISSUE THREAD

**Issue by Scorpionk1** [8bitPit/Niagara-Issues#190]

**Comment by Scorpionk1** [comment]
Apps of the same color in folders

**Comment by Scorpionk1** [comment]
![photo4956245050036168758](https://user-images.githubusercontent.com/38589444/45423478-dcfa1b80-b669-11e8-895a-ac9cb18ae361.jpg)
![photo4956245050036168759](https://user-images.githubusercontent.com/38589444/45423481-dcfa1b80-b669-11e8-971d-7a9514ba1575.jpg)
![photo4956291972553877530](https://user-images.githubusercontent.com/38589444/45423482-dcfa1b80-b669-11e8-8aac-193a1c7243fe.jpg)

**Comment by 8bitPit** [comment]
Please see #13 for that
