### ISSUE TITLE
Request:Option To Lock Long Press Card Menu

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1901]
### Describe the solution you'd like

i know most traditional launcher provides a way to lock the homescreen, that isn't the case with Niagara as it needs and extra step to move the apps and stuff,

and I'm not asking for app lock to be clear, as mentioned in help article it's just a pseudo layer.

it will be great if in Niagara setting an option is provided to stop the long tap menu from appearing kind of block, toggling it on will prevent the long press menu from appearing , when long tapping it it will show a toast at the bottom, stating it locked. 

it will help prevent anyone from uninstalling or make any modification toan app by long tapping it (happened to me, when i accidentally left my phone open, my small brother accidentally tapped the uninstall an app which led to loss of some important data)

2. it will prevent user like me from keep changing and modifying the layout.

so once everything is set, i can go to Niagara setting toggle on the switch and it will lock, if a user want to make a change he can just go to setting via app list and re-enable it.

you might have a doubt that it will stop showing stop showing the Niagara pro subscription banner at the list for non-pro user for that you can enable this lock only for pro users.

this will help me a lot, i have seen some few users requesting about locking the layout in telegram group too.

Thank You.

https://user-images.githubusercontent.com/96917972/161388674-c0825f9c-e050-4868-a763-30b0de9028a9.mp4

**Comment by Maxr1998** [comment]
Hi, thanks for the suggestion. A very similar idea was already discussed in #1133, we've improved the editing process since then to make it less likely to accidentally edit the home screen. Thus, we don't plan to implement this.
