### ISSUE TITLE
Clicking "Clock" shortcut opens only the Alarm tab in stock Samsung Clock app

### ISSUE THREAD

**Issue by michalsukupcak** [8bitPit/Niagara-Issues#1903]
### Describe the bug

Clicking the "Clock" shortcut on the homescreen opens only the Alarm tab instead of the entire Clock app.

### Steps to reproduce

1. Click "Clock" shortcut on homescreen
2. Only Alarm tab opens, other tabs are missing 

### Device name

Galaxy S21 Ultra

### Android version

Android 12

### Screenshots / Screen recordings

https://drive.google.com/file/d/1hE4dq89HInUOzluteGqS8hkCwiykVr9X/view

**Comment by Oddward** [comment]
This is a duplicate. Please refer to [this issue #1160](https://github.com/8bitPit/Niagara-Issues/issues/1160)
