### ISSUE TITLE
After clearing background apps at once launcher  is opening search instead of going to home screen 

### ISSUE THREAD

**Issue by soymadip** [8bitPit/Niagara-Issues#1907]
### Describe the bug

When sesame shortcut is installed, after clearing all background apps with "clear all" option, launcher is opening search automatically.

Model name :- Realme Narzo 30
Android :- 11, realme ui 2.0

### Steps to reproduce

1. Should have sesame shortcut installed.
2. Clear all background running apps.
3. Then it happens. 

### Device name

Realme narzo 30

### Android version

Android 11

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/84225810/161821356-e442b280-69cb-47c3-a251-f9efd7a15f0e.mp4

Please download it then watch because I guess github's inbuilt player is not able to play the record.

**Comment by timm0e** [comment]
Thanks for your report, we're looking into it :ok_hand:

**Comment by timm0e** [comment]
So it really only happens if sesame is enabled? :eyes:

**Comment by soymadip** [comment]
> So it really only happens if sesame is enabled? 👀

Even it's happening now , I have recorded it recently 👇
https://telegra.ph/Niagara-bug-06-08

**Comment by 8bitPit** [comment]
Thank you for reporting, @soymadip; I hope our latest beta fixes this issue: https://github.com/8bitPit/Launcher/releases. Could you let us know if it does?

**Comment by soymadip** [comment]
> Thank you for reporting, @soymadip; I hope our latest beta fixes this issue: https://github.com/8bitPit/Launcher/releases. Could you let us know if it does?

Since last month, i haven't experienced it. 
Looks like it's fixed

**Comment by 8bitPit** [comment]
Great, thank you for letting us know :D
