### ISSUE TITLE
Add a notification badge instead of full text

### ISSUE THREAD

**Issue by subneil** [8bitPit/Niagara-Issues#1908]
Re-upping this feature request that was closed in 2021 (Happy new year!)

https://github.com/8bitPit/Niagara-Issues/issues/800

Consistent with the minimalist aesthetic of niagara, as a user I'd like a notification dot or unread badge (versus lines of text) to help me find notifications for my favorite apps. E.g. the number 3 on my messages app to denote 3 unread.

Thanks.

**Comment by Rod911** [comment]
I suggest reopening the linked ticket instead on creating a new one.

**Comment by timm0e** [comment]
Hey @subneil, thanks for submitting this issue :pray: 

I've consulted Peter, and sadly we won't be implementing this idea - it would require a toggle that drastically changes the function of the home screen.

However, if you're looking for a way to hide the notification text while still having access to them in the popup, take a look at this: https://github.com/8bitPit/Niagara-Issues/issues/1701#issuecomment-924837224
