### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by somaconspiracy** [8bitPit/Niagara-Issues#191]
Just suggesting, if possible, the option to select from a variety of fonts. Thanks for the awesome app!

**Comment by Shinra04** [comment]
Yeah, makes for a bit more personalisation.

**Comment by 8bitPit** [comment]
Custom fonts usually include only Latin letters and numerals, so applying the font to the whole launcher may be problematic. So just changing the clock font (#34) would be easier.

**Comment by 8bitPit** [comment]
Nevertheless, I agree that would be cool.

**Comment by kStor2poche** [comment]
I think you could choose a set of fonts that works with every lettering and numeric system to choose in the settings by default and allow us to use our custom fonts from our files with a small warning on types of fonts and how they may not scale, with maybe a size multiplier, because some fonts are bigger than others !
Bu still if choosing the default font options is still problematic, just don't do it for now but please let us use our fonts with your launcher because it'd really be a step up for the design.

**Comment by 8bitPit** [comment]
A font picker would work. Your own fonts could even be imported.

**Comment by Shy2papa** [comment]
Would also be awesome if we could choose the font color like nova launcher.

**Comment by 8bitPit** [comment]
@Shy2papa: #20

**Comment by cuprousoxide** [comment]
Android now supports a few different fonts via the Styles & Wallpapers app/setting. I've only seen this setting affect OS stuff - not apps - but would this make the feature easier to implement (in a limited fashion)?

edit: This appears to be limited to Pixel devices and I wouldn't expect you to have device-specific features.
:(

**Comment by 8bitPit** [comment]
That's very interesting, thanks for sharing, let's see if this gets a stock Android feature in Android 11

**Comment by 8bitPit** [comment]
Implemented in v0.11.8

**Comment by adguardgirl** [comment]
I'd love to see the ability to change font size as a feature :)

**Comment by 8bitPit** [comment]
@adguardgirl as of now, we don't plan on adding a slider, but if it gets requested often, we'll definitely reconsider it.

**Comment by Eohis** [comment]
I humbly second adguardgirl's request! I think it would be a nice customization feature!

**Comment by wimstefan** [comment]
Should be third then ... ;-)

**Comment by adguardgirl** [comment]
Oooo! Wouldn't it be sweet if we could optionally toggle a more visible drop shadow for home screen app text? Currently, we have only two font colors, which limits the amount of wallpapers you can use quite a bit. A drop shadow effect on font would make white text easily visible even on light or medium background for example (or black visible on dark bgs or medium bgs). 

Here are a few examples of possible implementation: [](https://stackoverflow.com/questions/3297437/shadow-effect-for-a-text-in-android)

**Comment by 8bitPit** [comment]
I'm sorry @adguardgirl, but we're not planning to add further customization features right now: https://help.niagaralauncher.app/article/44-feature-requests
