### ISSUE TITLE
Random String on numbers on Home Screen 

### ISSUE THREAD

**Issue by unspecial-effects** [8bitPit/Niagara-Issues#1910]
### Describe the bug

A random String of numbers covering the entire length of the Home Screen appears. There is no way to get rid of it.

### Steps to reproduce

1. Set up Niagara Launcher
2. Restart phone
3. Open Home Screen 

### Device name

OnePlus 7T

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_20220408-140546](https://user-images.githubusercontent.com/79784578/162414497-4dd29db4-f6ab-4462-8355-8628b300c8b5.jpg)
![Screenshot_20220408-140553](https://user-images.githubusercontent.com/79784578/162414910-493dc511-bcb3-45ff-88da-b0d8b1ffa47e.jpg)

**Comment by timm0e** [comment]
Hey there :wave: 

Please see our knowledge base entry for this: https://help.niagaralauncher.app/article/108-random-numbers
