### ISSUE TITLE
Auto-select app when there's only one result in the search

### ISSUE THREAD

**Issue by diogox** [8bitPit/Niagara-Issues#1911]
### Is your feature request related to a problem?

It's frustrating to search for an app and have to click the only available result, when I know beforehand that only one app will match my search.

### Describe the solution you'd like

A lot of other minimal launchers offer this.

it would be nice to have an option that you can enable, and that would make it so that when you search for an app - typing just a few letters - if there's only one result that matches the search, that result is selected and opens automatically.

**Comment by timm0e** [comment]
Hey :wave: 

This would interfere with the Play Store search or the Sesame integration.

However, you can just press the Enter Key on your keyboard to open the top-most search result. Then you won't have to click on the entry, and can rely on your muscle memory instead
