### ISSUE TITLE
Notification summary font issues

### ISSUE THREAD

**Issue by Gnysi00wskyyTheGoat** [8bitPit/Niagara-Issues#1912]
### Describe the bug

When entering the notification summary from notification tray, the font that I chose doesn't apply except for the close summary and schedule next button 

### Steps to reproduce

...

### Device name

Huawei Mate 20 Lite

### Android version

Android 10

### Screenshots / Screen recordings

![Screenshot_20220408_195820_bitpit launcher](https://user-images.githubusercontent.com/69399229/162497442-8e38abf7-ef44-4911-88fd-bd8d0bfa4cc2.jpg)
![Screenshot_20220408_195811_bitpit launcher](https://user-images.githubusercontent.com/69399229/162497453-21017efc-cde7-4447-9602-8309e5d95ed7.jpg)

**Comment by Maxr1998** [comment]
Thanks for the report, this will be fixed in the next upadte.

**Comment by 8bitPit** [comment]
Fixed in v.1.6.4 🎉
