### ISSUE TITLE
Unread Message Indicator

### ISSUE THREAD

**Issue by LeIVIat** [8bitPit/Niagara-Issues#1915]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

I would like to have an unread message indicator that isn't dismissed after I cleared my notification shade. 
The Microsoft Launcher has this functionality build in and that is the only thing I miss about this launcher. 

A simple notification dot with the number of unread messages inside would be lovely.

**Comment by Oddward** [comment]
Niagara uses the notification dots feature to enable its notification previews, it's the same feature I believe except Niagara displays the notification content. If you're just trying to avoid having the previews on your app list you can disable **Notification dots** in your system settings (Android 8+ iirc) while keeping **Embedded notifications** on in Niagara settings, so the arrow to open the pop-up appears without the content previews. A numerical indicator isn't likely to be added

**Comment by Oddward** [comment]
Just realized it's also a duplicate of #1701 and #1908 so I'll close this one.

**Comment by Amorphous404** [comment]
Also a duplicate of #800
