### ISSUE TITLE
Make "New Bootup Animation" as default homescreen "favorites" animation.

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1919]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

The animation trigger sometimes; however, would be great to make the "New Bootup Animation" the default animation every time the user return to the main homescreen (favorites).

**Comment by Oddward** [comment]
At the moment the animation is quite slow and there's feedback that it's reducing productivity and plays too frequently, so it may be tweaked. The launcher is supposed to be snappy. It's very unlikely that this would be considered in its current state. 

_p.s. see [Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)_
