### ISSUE TITLE
Have apps flow behind the navigation bar instead of cutting off

### ISSUE THREAD

**Issue by pablomeza10** [8bitPit/Niagara-Issues#192]
The apps look really ugly when half of their icon show up because the other half is behind the navbar, and what I'm thinking if you guys can have it so that the whole icon can show up behind the navbar

**Comment by 8bitPit** [comment]
That would cover those three icon though. Maybe I darken the bar a little then it could work.

**Comment by moviti** [comment]
If possible, the edge of darken nav-bar area would be gradient... 
thanks

**Comment by 8bitPit** [comment]
I implented a fading edge effect, that looks like this (not available yet):
![image](https://user-images.githubusercontent.com/9284845/45588253-11900080-b912-11e8-93ac-bad411049235.png)

**Comment by ACHOKAMAN** [comment]
8bitPit can i have your blur wallpaper it  seems awesome with launcher

**Comment by 8bitPit** [comment]
@ACHOKAMAN: https://www.dropbox.com/s/5lhx4w8um808v36/Niagara_feature_walls.zip?dl=1

**Comment by moviti** [comment]
Wow! It looks great!

**Comment by 8bitPit** [comment]
@Rod911 thanks for closing the issue, I forgot it :)
