### ISSUE TITLE
Installed PWA shortcut cannot launch

### ISSUE THREAD

**Issue by Jokay03J** [8bitPit/Niagara-Issues#1930]
### Describe the bug

When a install pwa,in home screen,shortcut is not available

remark: i had tested pwa on other phone without niagara launcher,it's work

### Steps to reproduce

1.go to kiwi browser(or brave,i had tested in two navigator)
2.add pwa
3.click in shortcut install in home screen

### Device name

Honor 8a

### Android version

Android 9 (Pie)

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/55850775/164405069-e8db0626-5ee4-4c1f-a86a-430a44342df8.mp4

**Comment by Jokay03J** [comment]
pwa work on other phone with niagara launcher(i was tested with a wiko)

**Comment by Oddward** [comment]
Does this work on your stock launcher? If so, can you try it on a different 3rd party launcher like Nova or Microsoft to check if it's a general issue?

**Comment by Jokay03J** [comment]
> Does this work on your stock launcher? If so, can you try it on a different 3rd party launcher like Nova or Microsoft to check if it's a general issue? 
> 
> *And what does that error message on tap say?

It does'nt work on nova launcher and Microsoft launcher("application is not installed")

But it work on stock launcher

*"Application is not available(in french is "l'application n'est pas disponible")

**Comment by Oddward** [comment]
It seems like it's a general issue on your system with 3rd party launchers. Try checking system settings for Niagara and for your browser app in case there are extra permissions needed to launch the pwa. I assume adding a normal website shortcut works fine, ya?

**Comment by Oddward** [comment]
Did you check system app settings for something like a related permission? And tried restarting device? Try Chrome

**Comment by Amorphous404** [comment]
> Sorry,my phone does not work anymore,thanks for help

Thanks for the update, since no one has reported the same issue so far, I'll close this ticket :)
