### ISSUE TITLE
Trying to move internet shorcuts to the app list on free version blocked by a paywall message

### ISSUE THREAD

**Issue by sverpoorten** [8bitPit/Niagara-Issues#1931]
### Describe the bug

On the launcher screen, I added a website-shortcut (using a browser > ... > Add to home screen). I want to move this to the A-Z list. In a previous version of Niagara, this was possible. Since version 1.6.5 I get the paywall concerning Pro pop-ups. When unselecting the shortcut through the favourite list edit-UI, the shortcut is deleted completely instead of moving it to the A-Z list.

### Steps to reproduce

1. Create a website-shortcut using a browser (both Chrome and DuckDuckGo give the same issue)
2. Long-press the shorcut on the home screen
3. Select 'Show in app list'
4. A paywall concerning Pro pop-ups appear

Alternative:
3. Select 'Edit favourites'
4. Unselect the shorcut
5. A pop-up appears asking whether I want to delete the item

### Device name

Nokia G20

### Android version

Android 11

**Comment by 8bitPit** [comment]
Thanks for reporting @sverpoorten, this is not intended and will be fixed with the next release. However, it might take a while until the next update is ready.

**Comment by 8bitPit** [comment]
Fixed this in v1.7: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b
