### ISSUE TITLE
Support for live wallpaper lateral movement options

### ISSUE THREAD

**Issue by GandhiChan** [8bitPit/Niagara-Issues#1933]
### Describe the solution you'd like

Being able to use things like support for wallpaper changes per page of launcher, as seen in traditional layout launchers, would be great - I remember Minima having support for this, and KLWP may as well.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by tjsuominen** [comment]
Per page? Niagara has only one 'page'...

**Comment by Oddward** [comment]
Ya Niagara doesn't really have multiple pages, and it doesn't really have a background layer at all, it shows you your system set background behind its UI. If you want a live wallpaper to react to navigation you'd have to use a live wallpaper app that's built for that, or use KLWP which lets you customize behaviour and has an integration with Niagara: [KLWP/KWGT Integration](https://help.niagaralauncher.app/article/59-klwp-integration) - there are plenty of presets and tips in the community for it too.

Even more could be possible with something like a Tasker integration perhaps ( see #786 )
