### ISSUE TITLE
Hide "latest installs" 

### ISSUE THREAD

**Issue by timovandrey** [8bitPit/Niagara-Issues#1934]
### Is your feature request related to a problem?

I would like to be able to hide the menu item "latest install" (In German: "Kürzlich installiert") as it disrupts the feel of the launcher and shows more than necessary. 

### Describe the solution you'd like

Implement a toggle switch in the appearance menu "Hide latest installs" or something. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
This is a duplicate, please refer to issue #1920 instead, I'll close this one
