### ISSUE TITLE
Samsung devices only open alarm clock rather than the clock app when tapping the time

### ISSUE THREAD

**Issue by timovandrey** [8bitPit/Niagara-Issues#1935]
### Is your feature request related to a problem?

I've actually talked about this with one of the devs before, that's why I have the information, but:

On my Samsung device, when I click the clock, it only opens the alarm clock, but not the general clock application.

Can you make it so that one is able to customize/overwrite which app is opened when tapping the clock, so Samsung devices can also use the full feature?

### Describe the solution you'd like

A "overwrite clock tap action" menu entry in the appearance menu, which lets one choose an app like with the Niagara icon.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
This is a duplicate and an issue with Samsung's clock app, please refer to issue #1160 instead, and [Peter's comment](https://github.com/8bitPit/Niagara-Issues/issues/1160#issuecomment-580500717)
