### ISSUE TITLE
Text Color - Based on wallpaper needs better detection 

### ISSUE THREAD

**Issue by EncryptedCicada** [8bitPit/Niagara-Issues#1937]
### Describe the bug

The option to assign text colour based on wallpaper (light/dark) is needs a more robust algorithm to determine the wallpaper.

Only the very bright/light shaded wallpapers trigger the text to turn dark. Examples attached below.

### Steps to reproduce

Niagra settings > looks > Text colour > Select "Based on wallpaper"

Set wallpaper to a light coloured wallpaper and the text colour still remains white.

Manually changing the colour to light/dark works.

### Device name

Motorola Edge 20

### Android version

Android 12

### Screenshots / Screen recordings

Example of feature failing:-
![Screenshot_20220424-164447](https://user-images.githubusercontent.com/52757733/164973756-233838cc-6bdf-4537-8601-3c8798f8d9f9.png)

Example of it working correctly:-
![Screenshot_20220424-164537](https://user-images.githubusercontent.com/52757733/164973768-4d7e9eed-fc2a-412a-bb14-1575be3fbdfb.png)

**Comment by Oddward** [comment]
The current implementation is handled by the Android system (as of Android 8) made by Google, it wouldn't be easy to just make a better one

According to devs: *their algorithm only suggests a dark text color if the wallpaper has <= 5% dark pixels (luminance <=45%)  and if the mean luminance level of the overall wallpaper is pretty bright (>=75%)*

In your particular examples it doesn't look like it's failing as the contrast seems good, in some other cases a mostly white wallpaper with some very dark patches can have light text. If it's  not optimal for your wall you can manually change it in a couple of taps (Niagara settings > Look > Text color) or have it follow the system theme if available on your device.

I'll close this for now as too out of scope, but is there a known better algorithm?
