### ISSUE TITLE
Minimised applications lidt overlay on going out of app and into launcher

### ISSUE THREAD

**Issue by krakra9** [8bitPit/Niagara-Issues#1938]
### Describe the bug

Using one plus 10 pro 5G, android version 12.
Launvher is set as default and is payed for. I minimise an application and there is a a split second animation of the list of minimised applications. Using gestures to minimise and not on screen buttons.
This happens every time i minimise an application. Please fix

### Steps to reproduce

Open any application.
Minimise application.
Open second application (so there is a list of minimised applications now)
Minimise application (you will see flash of another screen on top of the launcher)

### Device name

one plus 10 pro 5g

### Android version

Android 12

### Screenshots / Screen recordings

I cant do it fasg enough to screenshot. Sorry

**Comment by Oddward** [comment]
If you're referring to the recent apps screen bugging out unfortunately this is a system issue and Niagara can't control it, the system manufacturer or Google (as the source of the gesture issues) need to optimize it. More info in the knowledge base here: [Gesture Navigation Support (highlight link)](https://help.niagaralauncher.app/article/7-gesture-navigation#:~:text=Android%E2%80%99s%20recent%20apps-,screen,-behaves%20differently%20compared)
