### ISSUE TITLE
Support dynamic calendar icon

### ISSUE THREAD

**Issue by pasqualedante** [8bitPit/Niagara-Issues#1940]
### Is your feature request related to a problem?

At this moment, Niagara show as Google calendar icon, Always the 31 number icon. 

### Describe the solution you'd like

It would be better if Niagara (like other launchers) showed the exact number of the icon of the day.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
This is a duplicate, please refer to issue #533 instead, and there's more info in the knowledge base here: [Missing Customization Features (highlight link)](https://help.niagaralauncher.app/article/77-missing-customization-features#:~:text=Supporting%20Dynamic-,Calendar,-/%20Clock%20Icons)
