### ISSUE TITLE
Move search bar to the bottom

### ISSUE THREAD

**Issue by Maciek-Hetman** [8bitPit/Niagara-Issues#1941]
### Is your feature request related to a problem?

Search bar and search results appear on top of the screen. Moving them to the bottom (on top of the keyboard), will make results much easier to reach on tall phones

### Describe the solution you'd like

Move search bar and result to the bottom

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Just-SKY** [comment]
I've been waiting for this too. This positioning would be great if they make the niagara launcher more powerful.

**Comment by Oddward** [comment]
This has been requested & discussed before but I can't find an issue for it (probably mixed in other discussions) 😅 

The search bar is kept at the top coz when you go to Search it's automatically focused and the keyboard pops up so you don't need to tap it, and hitting enter launches the top-most result so you don't need to tap it either. And the rest of the results creep closer to the bottom of the page so reachability shouldn't be a real problem. 

I realize it becomes a reach when the keyboard is removed, but not sure if it's worth changing the layout or adding an option just for that use case 🤔 The search page might get significant changes though when the newer Android search features can be integrated into it.

**Comment by Oddward** [comment]
Actually, refer to issue #1503 , I'll close this one
