### ISSUE TITLE
Change default clock app when click on time widget

### ISSUE THREAD

**Issue by haunt98** [8bitPit/Niagara-Issues#1942]
### Is your feature request related to a problem?

I use 2 clock app. One is MIUI default, the other is Google clock.
Niagara always open MIUI clock. I want to change that in option.

### Describe the solution you'd like

Create option to open which app when click on clock widget.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Hi @haunt98, I hope this guide can help: https://help.niagaralauncher.app/article/112-reset-default-app

**Comment by haunt98** [comment]
Hi @8bitPit, I already clear the default set of Xiaomi clock app but the launcher still doesn't let me choose the Google clock.

![Screenshot_2022-05-02-12-06-01-211_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/5424272/166186809-955e22a5-1b3f-4058-881b-c08d3b41a557.jpg)

![Screenshot_2022-05-02-12-06-04-344_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/5424272/166186830-fc1b1c57-cfcd-4404-8af8-41a5d5a93c99.jpg)

**Comment by Oddward** [comment]
Hey @haunt98 . I just installed Google clock to try this and it works fine, tapping Niagara's clock asked me to choose a clock. If clearing the defaults for the Xiaomi clock doesn't work try uninstalling and reinstalling Google clock

**Comment by haunt98** [comment]
Thank you @Oddward, after I clear cache and data for both Xiaomi clock and Google clock. The launcher let me pick default clock again.
