### ISSUE TITLE
Uninstalling apps via niagara

### ISSUE THREAD

**Issue by CerberusCode** [8bitPit/Niagara-Issues#1943]
### Describe the bug

Uninstalling some apps via this launcher the uninstalled apps are still visible a couple of seconds and it crashes the folder icons that manually themed from icon pack, it revert to default folder icon.

### Steps to reproduce

None

### Device name

Oppo F11 Pro

### Android version

Android 11

**Comment by Oddward** [comment]
I can't reproduce this issue when uninstalling an app from a folder. Is it consistent? And in Niagara versions 1.6.5?

**Comment by CerberusCode** [comment]
Yes it is consistent & I'm using a latest ver 1.6.5

**Comment by Oddward** [comment]
Just to specify, I was referring to the folder icons resetting issue which doesn't happen for me. The app remaining for a few seconds after uninstalling is normal and is just a matter of the list updating I guess. 

The icons don't come back if you restart the launcher?
