### ISSUE TITLE
reminders shown on callender widget

### ISSUE THREAD

**Issue by ahkonbaha** [8bitPit/Niagara-Issues#1944]
### Is your feature request related to a problem?

callender only shows event on google callender not reminders 

### Describe the solution you'd like

adding support for reminders in callender widget so they can shown in main screen

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Hey, unfortunately Google doesn't share certain types of events with other apps, including Reminders and Tasks. See the [help article](https://help.niagaralauncher.app/article/76-calendar-faq#:~:text=Reminders/Tasks%20from-,Google,-Calendar%20don%27t%20show)
