### ISSUE TITLE
google fit integration to widget

### ISSUE THREAD

**Issue by ahkonbaha** [8bitPit/Niagara-Issues#1945]
### Is your feature request related to a problem?

needing to add step tracker widget to main screen

### Describe the solution you'd like

main widget had a google fit integration so our step count can seen there

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by timm0e** [comment]
Thanks a lot for your suggestion!

We think that this would be a nice addition to Niagara Launcher, but sadly we won't be able to implement it in the near future :disappointed: 

We have experimented with adding more things to the Niagara Widget, but with its current design it doesn't really fit. Additionally, we're currently working on making Niagara Launcher a bit more independent of Google's Services for our non-Google users, so it's currently an unfitting time for this feature.

As a result, we won't be implementing it in the foreseeable future as of now, but we might come back to it at some point :+1:
