### ISSUE TITLE
Media widget bug - Youtube thumbnail cannot be displayed

### ISSUE THREAD

**Issue by henman0123** [8bitPit/Niagara-Issues#1946]
### Describe the bug

Sorry, I'm not a native english speaker.

It works perfectly on Youtube ver.15.26.34 (System pre-installed version).

![9839](https://user-images.githubusercontent.com/3104964/166131588-49bd2102-d119-4485-957e-02d3d8d0e2f2.jpg)

When I update Youtube app to newest version, it doesn't work.

![9840](https://user-images.githubusercontent.com/3104964/166131761-0c6c3c21-786e-4d3b-bf45-7a95acb483cc.jpg)

Now I can only use the old version, please help me.

### Steps to reproduce

1.Update Youtube app to the latest version.
2.Media widget can not display Youtube thumnail anymore.

### Device name

Oneplus 8

### Android version

Android 11

**Comment by Oddward** [comment]
Hey. Is this issue always happening for all videos or just sometimes/random? I don't have youtube premium so I can't test it, but using the browser still works fine.

**Comment by topsy-turvy99** [comment]
> ### Describe the bug
> 
> Sorry, I'm not a native english speaker.
> 
> It works perfectly on Youtube ver.15.26.34 (System pre-installed version).
> 
> ![9839](https://user-images.githubusercontent.com/3104964/166131588-49bd2102-d119-4485-957e-02d3d8d0e2f2.jpg)
> 
> When I update Youtube app to newest version, it doesn't work.
> 
> ![9840](https://user-images.githubusercontent.com/3104964/166131761-0c6c3c21-786e-4d3b-bf45-7a95acb483cc.jpg)
> 
> Now I can only use the old version, please help me.
> 
> ### Steps to reproduce
> 
> 1.Update Youtube app to the latest version.
> 2.Media widget can not display Youtube thumnail anymore.
> 
> ### Device name
> 
> Oneplus 8
> 
> ### Android version
> 
> Android 11
> 
> ### Screenshots / Screen recordings
> 
> _No response_

Can you please check, if the thumbnail is shown in the notification panel?

**Comment by henman0123** [comment]
> Hey. Is this issue always happening for all videos or just sometimes/random? I don't have youtube premium so I can't test it, but using the browser still works fine.

Every video has this problem.

**Comment by henman0123** [comment]
> > ### Describe the bug
> > Sorry, I'm not a native english speaker.
> > It works perfectly on Youtube ver.15.26.34 (System pre-installed version).
> > ![9839](https://user-images.githubusercontent.com/3104964/166131588-49bd2102-d119-4485-957e-02d3d8d0e2f2.jpg)
> > When I update Youtube app to newest version, it doesn't work.
> > ![9840](https://user-images.githubusercontent.com/3104964/166131761-0c6c3c21-786e-4d3b-bf45-7a95acb483cc.jpg)
> > Now I can only use the old version, please help me.
> > ### Steps to reproduce
> > 1.Update Youtube app to the latest version.
> > 2.Media widget can not display Youtube thumnail anymore.
> > ### Device name
> > Oneplus 8
> > ### Android version
> > Android 11
> > ### Screenshots / Screen recordings
> > _No response_
> 
> Can you please check, if the thumbnail is shown in the notification panel?

No, it doesn't.
FYI, YouTube Music works properly, but I still hope you can fix this issue.
 
![11204](https://user-images.githubusercontent.com/3104964/169626044-3804df03-bc72-4a20-a2bb-6dc79ec359e2.jpg)

**Comment by Oddward** [comment]
@henman0123 Niagara mirrors its notification data and music info from the notification panel and media session api, if the app playing media is not loading a thumbnail for its playback controls Niagara probably won't be able to know what the thumbnail is. This seems like an issue with Youtube in that case
