### ISSUE TITLE
App icon pack.

### ISSUE THREAD

**Issue by Gizmocombaty** [8bitPit/Niagara-Issues#1947]
### Describe the bug

When i change the icon pack on Nigara launcher the icons witch show does not appear, for example if Ihad selected Crayon a month ago and changed it today to Niagara dots or any other icon pack it will show that icon pack in the settings but not on the homepage.

I have tried to restart and it did nothing

### Steps to reproduce

Go to Niagara settings than change icon pack.
It does not work

### Device name

Huawei p20 pro

### Android version

Android 10

### Screenshots / Screen recordings

![Screenshot_20220501_100012_bitpit launcher](https://user-images.githubusercontent.com/104712706/166137424-8e372bb4-50b3-4300-86e0-640f0a494777.jpg)
![Screenshot_20220501_100006_bitpit launcher](https://user-images.githubusercontent.com/104712706/166137425-c00c3fc5-a892-4463-9639-8c9432ece1f3.jpg)

New descriptoin:

If i go to the Niagara settings and change the icon pack it does not change.

It does not get applied.
It wont show the icon pack i chose when im on the home screen.

If i go to Niagara settings, look, icon pack, change the icon pack from crayon to candy cones. THAN IT DOES NOT CHANGE

**Comment by Oddward** [comment]
Hey. I'm not sure I understand the issue, the icon pack does not get applied? If you have manually changed some of the icons before they won't get automatically changed unless you reset their icon via long-press > tap icon > tap reset

**Comment by Gizmocombaty** [comment]
It wont show the icon pack i chose when im on the home screen.

**Comment by Oddward** [comment]
Does the issue seem to be only on the favorites/some apps or all of them? Can you confirm if you haven't manually changed the icons on the favorites? 

You can long-press a favorite and tap on its icon, if there's a "Reset to default" option it should mean that you've manually set an icon and you'll need to reset it for the applied pack to show.

If there's just a "No icon" option then the applied icon pack should be applied, if it has an icon for that app.
