### ISSUE TITLE
New way to open settings.

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#195]
The bar on the top is currently hard to reach, that's why it will be replaced by a button in the bottom right corner (like the Google button). Problem: the three dot menu would be gone (access to settings / hidden apps / wallpaper) .

**Comment by Scorpionk1** [comment]
Including for the Google button in this way will not pollute.

**Comment by Scorpionk1** [comment]
Open multiple submenus on the same Google button.

**Comment by Scorpionk1** [comment]
This other button you are suggesting could open folders with several submenus by (folder category).

**Comment by pradyw** [comment]
It doesn't needs to be at finger tip, its good where it is on app list

**Comment by Scorpionk1** [comment]
Want to use the launcher with both hands? In this way, the essence would not be applied with one hand.

**Comment by Scorpionk1** [comment]
I found a solution: Put the search bar 🔎 above of the favorites ⭐ in the scrolling of the apps. Then, you will not pollute with a button.

**Comment by pradyw** [comment]
It doesn't need to go anywhere, we can already go to search (in Apps section) by double Tap on home button.

**Comment by Shinra04** [comment]
A simple and minimal solution is to move the three dots right below the apps scroll. It would fit right in cuz it's slim. Tapping it brings up the same menu wallpapers, hide apps, and settings option. 
Apps Search bar will remain on the top.

**Comment by Scorpionk1** [comment]
This will cause a wear with the home button. Not recommended!

**Comment by pradyw** [comment]
Move wallpapers inside Look
