### ISSUE TITLE
Add a option that allows users to add a separate wallpaper for Niagara Launcher.

### ISSUE THREAD

**Issue by Dr-Sauce** [8bitPit/Niagara-Issues#1950]
### Is your feature request related to a problem?

When I change my home screen wallpaper, the lock screen wallpaper changes together. (My phone doesn't support separate wallpapers.)

### Describe the solution you'd like

I'd like a option that allows users to set a separate wallpaper in Niagara Launcher, for people that have a phone/ emulator that doesn't allow separate home, lock screen wallpapers. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Dr-Sauce** [comment]
@oddward I use the default system settings to change my wallpaper. I've tried an app called Wallpaper (an app from Google) to change my home screen wallpaper, but still the lock screen wallpaper changes together.

And ah,, I just tried Muzei but it crashes. Is there any other app you can recommend me?

**Comment by Oddward** [comment]
@Dr-Sauce what device do you have? Maybe your lockscreen is set as transparent or something. If your phone has a themes app maybe it can apply them properly. Are you able to apply any other live wallpaper?

**Comment by Dr-Sauce** [comment]
@oddward I'm using a device that's mostly unknown. 

When you change the wallpaper from the default wallpaper changer, there's no transparent option or anything else. And it seems like live wallpapers don't work on my phone. I've tried a few but they all don't work. 

Would be great if Niagara Launcher adds a option to add a separate wallpaper like square home launcher.

**Comment by TFackler** [comment]
Hi @Dr-Sauce ,

sadly displaying the wallpaper ourselves would pose issues, since some screens android shows would still use the system's wallpaper even if Niagara has its own wallpaper. That and the fact that it would be a lot of effort to implement this feature made us choose to not add your requested feature.

We would recommend you trying out different wallpaper apps to see if one of them allows for separate wallpapers.
