### ISSUE TITLE
App crashing when previewing new whatsapp emojis

### ISSUE THREAD

**Issue by nicoagr** [8bitPit/Niagara-Issues#1952]
### Describe the bug

The launcher crashes when previewing (right swipe on message) whatsapp messages that contain the newly added emojis.
https://emojipedia.org/whatsapp/new/.
The emojis that give me the most issues and crashes are the melting face and face holding back tears.
https://emojipedia.org/melting-face/
https://emojipedia.org/face-holding-back-tears/

Also, when crashing, the default launcher for the device gets reset, and you have to choose the option again.

### Steps to reproduce

1 - Get a friend to send you the melting face emoji
2 - Preview the message your friend sent you
3 - Boom, get crashed

### Device name

Xiaomi Mi 9

### Android version

Android 11

**Comment by Oddward** [comment]
Hey. I can't reproduce this issue atm, having sent the new emojis between a MIUI user and OneUI user it did not crash either, but I've experienced a few instances of certain notifications causing crashes. Is it consistent for you with WhatsApp?

There's a debugging secret command `/notifications` which will print a log of the current state of your notifications, if you experience a notification crashing the system try entering that command in the Search page, then you can review the output if you can identify anything odd (in my case sometimes the specific notification was duplicated in the output), or send the output to the Niagara team, probably via email to support@niagaralauncher.com *(note: a message will tell you that the output can contain sensitive info from your notifications so be careful how it's shared)*
