### ISSUE TITLE
[Query]How to use KLWP?

### ISSUE THREAD

**Issue by onlytanmoy** [8bitPit/Niagara-Issues#1956]
Hiya, please can someone tell me the steps to use KLWP with Niagara Launcher?
Sorry I am not able to understand anything from here https://help.niagaralauncher.app/article/59-klwp-integration
so looking for some noob-friendly steps :)
Thanks.

**Comment by svatas** [comment]
What about this video?
https://www.youtube.com/watch?v=WLME627pPUY

**Comment by topsy-turvy99** [comment]
> @svatas no, that one is for KWGT which I am already aware of, I am looking for instructions on using KLWP with Niagara.

you're looking for help in the wrong place, you can join Niagara's Discord Channel Or Telegram Channel (https://t.me/niagara_showcase), you can check out the preset, other user have created and possibly help you achieve, what you're after

**Comment by onlytanmoy** [comment]
@topsy-turvy99 Thanks for the pointer. I have asked in the #help channel of Niagara's Discord now :) hopefully someone will respond.
