### ISSUE TITLE
Separate icons for favorites (Niagra dots)

### ISSUE THREAD

**Issue by Wf0Te** [8bitPit/Niagara-Issues#1958]
### Is your feature request related to a problem?

Using Niagra dots on favorite apps makes your home screen simple and minimalistic but ruins your app drawer.
![Screenshot_20220510-053516](https://user-images.githubusercontent.com/44049714/167598733-033059c3-08b6-4ffd-8552-b19928617870.png)

### Describe the solution you'd like

If you change the icon of an app from the favorites section of your home screen it will only affect the favorites section. If you don't change the icon from the favorites section it will function normally. Add a button to reset/sync icon to applist. Seems like a pretty simple qol change as far as user experience goes.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
Yes, this would be such a cool feature for Niagara like launcher, not just being limited to Niagara Dot Icons, but giving option in
>Niagara Settings
>Look Page
>Icon Pack
>Select Favorites Icon Pack
>Select App List Icon Pack

to select one icon pack for favorites and other for the app list, it would be too hard to implement, i suppose

I have been looking forward to achieve the same cause i want to use monet based icons on favorites screen and clean simple icon on the app list.

This aligns with Niagara principles too, and will be used by many 🙂

![Screenshot_20220511-143700_Smart Launcher~2.png](https://user-images.githubusercontent.com/96917972/167814657-c8446408-846c-40c7-9bc2-694cf51a2421.png)

![Screenshot_20220511-143704_Smart Launcher~2.png](https://user-images.githubusercontent.com/96917972/167814682-aba0da0c-ec0e-4657-943e-a5092c531972.png)

**Comment by Oddward** [comment]
The issue you described isn't really an issue as far as I can tell since one would normally hide the app from their app list if it's already in their favorites, reduces redundancy and removes the issue you described. 

Having 2 icon packs set sounds nice but would add unnecessary complexity and would require more changes than outlined, e.g. to handle individual custom icons, moving items between lists etc. That request was made before, refer to #1175
