### ISSUE TITLE
Suggestions for additional haptics & controls

### ISSUE THREAD

**Issue by Amorphous404** [8bitPit/Niagara-Issues#1959]
Hey. Thanks for the suggestions, but I'm afraid this just overcomplicates the settings which Niagara tries hard to avoid. One toggle for haptics should be fine and is usually the case in apps. The system also just categorizes them as haptics for touch/tap. See [Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

If the explanation is satisfactory I'll close this for now

_Originally posted by @Oddward in https://github.com/8bitPit/Niagara-Issues/issues/1948#issuecomment-1114578069_

Hey, with the spring update the vibration for swipe right on app to show pop up menu, is tied to allow haptic feedback for vibration, please make it independent of Niagara settings>allow haptic feedback,  just likt long tap vibration when opening context menu
 I
I have the allow haptic feedback turned off in Niagara which also inturn turns off swipe vibration

**Comment by topsy-turvy99** [comment]
And if possible add vibration for swipe up (Niagara Search), And Swipe Down (Notification Panel), just like the stock Pixel Launcher.

**Comment by Oddward** [comment]
I'm pretty sure the long-tap gesture/vibration is a system level thing and not an app-specific gesture, that's why it's not controlled by Niagara's haptics toggle. All of Niagara's own haptics are controlled with that toggle. 

I don't think other launchers have vibration for swipe up and swipe down, at least Samsung doesn't. That sounds like too much vibration all around to me 🤔 Is it really necessary? And do you experience it in other launchers?

**Comment by topsy-turvy99** [comment]
> I'm pretty sure the long-tap gesture/vibration is a system level thing and not an app-specific gesture, that's why it's not controlled by Niagara's haptics toggle. All of Niagara's own haptics are controlled with that toggle. 
> 
> I don't think other launchers have vibration for swipe up and swipe down, at least Samsung doesn't. That sounds like too much vibration all around to me 🤔 Is it really necessary? And do you experience it in other launchers?

I don't like the alphabet scroll, so i have it off, but really miss the subtle vibration when swiping on the app,

And other vibration on notification and search, I'm okay not having it, it feels natural so thought will suggest it

I just checked with some other launchers pixel and Lawnchair have for both, on nova ir lt vibrates only when notification panel is pulled

**Comment by Amorphous404** [comment]
Added swipe up/ swipe down vibration (Fixed)
