### ISSUE TITLE
Google search bar to bottom

### ISSUE THREAD

**Issue by siikanen** [8bitPit/Niagara-Issues#196]
## What?

The should be an easy way to access google search/ search provider on the home screen

## How

Take launcher3 or pixel launcher design for example

**Comment by 8bitPit** [comment]
There is already a Google button for that, you can enable it in Niagara's settings

**Comment by siikanen** [comment]
Oh sorry, I enabled it earlier today and it seems not to be working, posting img soon

**Comment by siikanen** [comment]
[Homescreen](https://i.imgur.com/rcTZYX3_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

Seems that force restarting fixed the issue, however the button is barely visible

**Comment by Shinra04** [comment]
It changes colour depending on wallpaper
