### ISSUE TITLE
Niagara Doesn't Follow System Font Anymore 

### ISSUE THREAD

**Issue by topsy-turvy99** [8bitPit/Niagara-Issues#1960]
### Describe the bug

LineageOS Android 12.1

Afir, Niagara was able to use the system font before the spring update, now it doesn't change, i tried it on my other phone which has ColorOS, it works fine there

### Steps to reproduce

>Phone Settings
>Display
>Font
>Change Font
Go to > Niagara Settings
>Font
>System

### Device name

Xiaomi Redmi Note 4

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20220511-153222_Settings](https://user-images.githubusercontent.com/96917972/167826043-92cf54df-bdde-4c58-9fa1-a806950c9132.png)
![Screenshot_20220511-153311_Niagara Launcher](https://user-images.githubusercontent.com/96917972/167826059-a3ae2592-8509-4ed8-80eb-3f0ae1d163b6.png)

**Comment by Oddward** [comment]
Please refer to issue #1923 , it seems to be some intentional change by Xiaomi maybe. I'll close this as a duplicate

**Comment by topsy-turvy99** [comment]
I'm on a custom rom not miui 😢

**Comment by topsy-turvy99** [comment]
> Please refer to issue #1923 , it seems to be some intentional change by Xiaomi maybe. I'll close this as a duplicate

Please reopen the ticket? I'm on custom rom Lineage OS @Oddward

**Comment by Oddward** [comment]
My bad. The device doesn't need to be mentioned if you're using a custom ROM probably, just mention its custom, and those come with their own bugs usually. 

It might still be related to that bug so I suggest continuing there, it's helpful to keep all the information about the bug in one issue so the scope is clear and others can add onto it @topsy-turvy99

**Comment by topsy-turvy99** [comment]
Okay, i thought it was compulsory to mention the device, that's why I mentioned the OS On First Line 😅,

I don't recognise which font it's using when I set the font to system in Niagara setting, but i shared the screen shot above, system using the font I set and Niagara using a simple font, other manually added font works fine

**Comment by timm0e** [comment]
> i tried it on my other phone which has ColorOS, it works fine there

Just to understand, did you try it with the same version of Niagara Launcher or an older one?

**Comment by topsy-turvy99** [comment]
> > i tried it on my other phone which has ColorOS, it works fine there
> 
> Just to understand, did you try it with the same version of Niagara Launcher or an older one?

Yes, idk i noticed this on latest version, but i think it changed after sitting update,

But, i just cleared Niagara data, and set everything again, the fonts are changing now, but there's a catch it doesn't refresh when font is changed in system, to refresh i have to select another font in Niagara setting, then switch to system, every time to refresh

**Comment by timm0e** [comment]
Thanks for your reply!

Does restarting the launcher also apply the new system font? And does the same happen in other apps too?

**Comment by topsy-turvy99** [comment]
> Thanks for your reply!
> 
> Does restarting the launcher also apply the new system font? And does the same happen in other apps too?

restarting does change the font, but it seems there's a delay for minute for the launcher to adopt the system font, i checked in Hyperion launcher the font refreshed automatically

**Comment by topsy-turvy99** [comment]
Sorry, my device got damaged, and I'll no longer be able to provide any feedback about the issue for that device.

I feel like the issue is more likely related to device/OS, it seems it works fine on all the other devices that i tested with.

**Comment by Oddward** [comment]
Thanks for the update, sorry for your loss

We can probably close this and keep future updates to the linked issue #1923 , it's very rare but seems like there are still a few reports of similar issues
