### ISSUE TITLE
Add a save button when you edit app names.

### ISSUE THREAD

**Issue by Dr-Sauce** [8bitPit/Niagara-Issues#1963]
### Is your feature request related to a problem?

When you edit app names there isn't a **Save** button. I think it would be more Convenient if there was a **Save** button.

### Describe the solution you'd like

How it looks right now & How I wish it would look like.

![Screenshot_2022 05 14_10 14 06 187](https://user-images.githubusercontent.com/82555878/168406326-ac0e8e22-e869-4d15-b30b-af2935e4c7b7.png) ![Screenshot_2022 05 14_10 14 06 187 copy](https://user-images.githubusercontent.com/82555878/168406329-95435193-8815-4ccc-bd07-64671240e7b7.png)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Hey. Thanks for the suggestion, but this is just adding an extra step. Hitting enter on your keyboard should confirm the change, and the cancel button reverts it. I believe this is pretty intuitive on mobile

**Comment by Dr-Sauce** [comment]
Some people like to press a button to confirm stuff. Rather than pressing enter from the keyboard. 

But I guess the current way maybe more simple. Just seemed a little odd, because there's only a cancel button.

**Comment by Oddward** [comment]
@Dr-Sauce ya I get it, although it's pretty consistent across Niagara atm, Search & setting weather location manually also works without buttons. Niagara's main action buttons are also pretty big so if it's there it'll make the text box much higher on the screen to reach (above the keyboard).
