### ISSUE TITLE
Favorites aligned to the bottom 

### ISSUE THREAD

**Issue by JanJenicek** [8bitPit/Niagara-Issues#1965]
### Is your feature request related to a problem?

I like to have my most bottom favorite icon placed as low as possible to easily reach everything. I also have a lot of space above the main widget. When media widget and media labeled icons/folder are shown, some of my icons are pushed bellow the screen and has to be scrolled up to be reachable.

### Describe the solution you'd like

Let user select whether favorite screen should be aligned to the bottom of the screen or to the bottom of the main widget.

This can improve consistency for some users, who prioritize icons position over the main widget position on home screen. Utilizing muscle memory to reach favorite apps.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
This is a duplicate, please refer to issue #808
