### ISSUE TITLE
Niagara Related Crash, App switching not possible

### ISSUE THREAD

**Issue by etm** [8bitPit/Niagara-Issues#1967]
### Describe the bug

Android 12: whenever i try to switch application, i am unable to, android states "Quickstep has stopped".

Does not work either in gesture or button or virtual key mode.

When niagara is disabled, quickstep (android 12 default launcher) works just fine.

### Steps to reproduce

1. swipe up switcher, or click switcher button

-> fail

### Device name

ulefone power armor 14

### Android version

Android 12

**Comment by Amorphous404** [comment]
Does it happen with other third party launchers? (Nova or Lawnchair)
