### ISSUE TITLE
Rename and customize app icons

### ISSUE THREAD

**Issue by Y4hL** [8bitPit/Niagara-Issues#197]
You should be able to adjust each icon to a icon pack of choice, not 1 for everything, also renaming apps on the favourite tab, i would use the rename feature to remove the name, so my amoled wallpaper saves more battery

**Comment by Shinra04** [comment]
Yeah, I think it's some nice optional settings.

**Comment by tamalbuk** [comment]
Related to #41 I believe.

**Comment by 8bitPit** [comment]
@tamalbuk thx & also related to #56.
