### ISSUE TITLE
Larger widget sizes for larger displays

### ISSUE THREAD

**Issue by manoharvhr** [8bitPit/Niagara-Issues#1971]
### Is your feature request related to a problem?

Niagara already support split lists for larger displays, can the pop up widgets also use more of the screen real estate. I have a Z Fold3 and the widgets are tiny compared what I expect to see.

### Describe the solution you'd like

A switch that allows widgets to be larger.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Hey. As Niagara doesn't have a cell grid for sizing widgets, for simplicity they're set to full width and centered, and only the height is adjustable. You could make the widget taller for it to grow to the size you want. If you're on a fold however changes will reflect on both the outer & inner screen atm (note that they're not diff instances, the layout just adapts to the change in width). 

You might wanna follow issue #1836 or #1845 for the changes that would help this case on foldables, if they match your request maybe we can close this one

**Comment by Shinra04** [comment]
I think a toggle for "Fill screen" (already exists for home screen widget) for pop-up folders (their respective widgets included) would help with this issue.
