### ISSUE TITLE
Birthdays not visible in the calendar widget

### ISSUE THREAD

**Issue by iamavu** [8bitPit/Niagara-Issues#1972]
### Describe the bug

Birthdays from Google Calendar are not visible in the calendar widget. I have tried checking and unchecking the birthday section and refreshing the calander app along with restarting launcher but they still won't appear. I have also checked in filtered events if that was disabled but there is no option for birthday(?)

Niagara Version == 1.6.5

### Steps to reproduce

1. Allow calendar permission
2. Enable the calender widget
3. See the preview of events

### Device name

Motorola Edge 20 Fusion

### Android version

Android 11

**Comment by Maxr1998** [comment]
Within Niagara, the section for birthday events should be named "contacts". With that checked, birthdays show up for me. Could you try that too?

By the way, the checkboxes in the calendar app are only an UI filter for that app.

**Comment by iamavu** [comment]
Hey, i can't seem to find the contacts thingy you mentioned.
Here is my filter list
![Screenshot_20220607-134156-902.png](https://user-images.githubusercontent.com/48346347/172330473-94872b91-35d4-4d65-bed5-d6d087334fb7.png)

**Comment by Maxr1998** [comment]
Interesting. I suppose the empty lines are redacted by you? Still weird it has duplicated some of the calendars. Do you use multiple Google Accounts?

**Comment by Maxr1998** [comment]
Ok, thanks. I'll check if that could be causing the issue. In the meantime, could you make sure the birthday calendar is enabled for sync on all accounts within the Google Calendar app?

**Comment by SebastianRumohr** [comment]
I had a similar issue with contacts synced by DAVx5. 

According to a [question in their faq](https://www.davx5.com/faq/contact-birthdays-in-calendars/) I tried the [Birthday Adapter from the Play Store](https://play.google.com/store/apps/details?id=org.birthdayadapter) and it solved my problem. 
The app is also available in F-Droid: https://f-droid.org/packages/org.birthdayadapter/

**Comment by Amorphous404** [comment]
v1.6.0 

More Calendar Events Supported: We fixed some calendar events not being shown in the launcher. This especially happened with privately shared events or events with a blank title.

Fixed?

**Comment by thuvasooriya** [comment]
I'm in Niagara Launcher version **1.8.6** and I can confirm that I still have this issue. 
I had to duplicate all birthdays as full day events for this but soon got tired of it.  🥲
I love this launcher so would really appreciate if this could be fixed. Been missing a lot of birthdays lately.
<img src="https://user-images.githubusercontent.com/74165167/212369239-d6f96d11-030e-48d0-991e-ca984aa60bba.jpeg" alt="niagara_issue_bd" width="200"/>

**Comment by Amorphous404** [comment]
Hey @thuvasooriya, it seems like you're facing some syncing issue, i just tested it out everything works normally here, can you try out the troubleshoot methods outlined in this article:
![IMG_20230117_181502.jpg](https://user-images.githubusercontent.com/96917972/212902328-c5dbcd0b-7975-464c-a0e0-eeb08a31935d.jpg)

https://help.niagaralauncher.app/article/76-calendar-faq
