### ISSUE TITLE
False weather information Bug

### ISSUE THREAD

**Issue by unityastronaut** [8bitPit/Niagara-Issues#1976]
Lately the weather information in the Niagara widget is completely wrong (see screenshot comparison between Niagara widget and Google at a glance). It almost always shows rain even though it hasn't been raining in days where I live (Munich Germany). Restarting or switching off and reenabling weather info doesn't fix the problem, so it's probably wrong predictions by OpenWeather. In that case it should seriously be considered to switch weather providers or have multiple ones to choose from like it used to be, because it's just wrong in every regard. Since Niagara only allowes for one additional widget and that is already occupied by a search bar in my case I have no way to get accurate weather information.

![Screenshot_20220615-131416](https://user-images.githubusercontent.com/82398591/173815079-7b6604ab-5990-4db8-8c73-4c846c8ea8c7.png)
![Screenshot_20220615-131301](https://user-images.githubusercontent.com/82398591/173815082-b0f40f0d-35df-4efe-9bd1-bb2822e1c00f.png)

**Comment by Oddward** [comment]
The weather feature is a proper integration using a paid API, it's not trivial and prolly unnecessary to just offer multiple options. If there are issues with weather data in your region it's advised to install the OpenWeather app through which you can double check and also contact those devs to inform them of the issue, then it can improve for all users. 

Also try diff ways of setting your location (could even try lattitude + longitude with Google Maps). 

If widget space is too limited you can utilize things like the Niagara button or pop-ups (could just bind the search app to the button tap/swipe up if the widget does the same

**Comment by Amorphous404** [comment]
Weather info is provided by OpenWeather, if you find it shows wrong data, it's advised to report it to them like Oddward suggested.

Also the devs are considering switching back to Apple Weather (previously DarkSky).

Please refer #1966
