### ISSUE TITLE
Google feed

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#1979]
### Is your feature request related to a problem?

I already know google feed make niagra neat policy overload, But now as google has invested lot energy in google feed. 
I think it will be more outdated to skip google feed left swipe.

SO i request you implement as left swipe google as togle. **When toggle on, it may offer to install another app(google feed supportive apk). I know this is the only way to do it.** Now let see will you stick with past year answer or you will be open to extend possibilities.

### Describe the solution you'd like

- One toggle to enable google feed
- on toggle on offer install apk to support google feed and enable left swipe for google feed

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Majorzen51** [comment]
You can use the niagra button to redirect to the google feed.

**Comment by Oddward** [comment]
AFAIK there have been no changes to the circumstances that prevented the devs from implementing it before (what changed?), so I see no reason opinions will change on this. And if you want to make a new case for an old issue it's best to comment on that old issue if you wanna request to reopen it.

More info on this help article: [Google News Feed](https://help.niagaralauncher.app/article/32-google-news-feed)

Lemme know if there's a different case to be made for it
