### ISSUE TITLE
Keeping old icons even when icon pack is missing. 

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1980]
### Describe the bug

I don't know if this is intended this way or not, so i'm gonna treated as a bug if not my apologies. 
I've just found that: 

### Steps to reproduce

1. Install an icon pack apply icons manually. 
3. Keep icon pack, but uninstall app/s with the icon pack applied (manually). 
4. Then Uninstalled and install a new one.
5. Apply the new icon pack. 
6. Then reinstall an apps/s, and they appear with the previously icon pack applied which is not longer available. 

Don't know how important this is, but it is something new to know. 

### Device name

Xiaomi 

### Android version

Android 10

### Screenshots / Screen recordings

![aqr](https://user-images.githubusercontent.com/72170242/175563649-45232b20-fe64-4e10-af66-78bbd5af4d2c.jpg)
Second image. 
![asd](https://user-images.githubusercontent.com/72170242/175563653-cf6b088d-c01c-45f5-b9ff-a05a81dd6e73.jpg)

**Comment by 8bitPit** [comment]
Good catch @Just-SKY! For the next major update, we have rewritten our icon system. I just checked, with our new system this doesn't happen anymore :D

**Comment by Just-SKY** [comment]
✌🏼

**Comment by 8bitPit** [comment]
Fixed this in v1.7: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b
