### ISSUE TITLE
Search box to find app on folder modification

### ISSUE THREAD

**Issue by lennelei** [8bitPit/Niagara-Issues#1981]
### Describe the solution you'd like

Hi,

When I want to add an application to a folder, I have to know the exact name of the applications I want to add in order to find it. Having *lots* of applications, it's not easy to do.

I would love to have a search / filter box!

Thank you.

Regards. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
With the future niagara build, you can directly add an app to a popup folder by long tapping on the app 👍

**Comment by Oddward** [comment]
Ya, please try the latest beta (or wait for Play store soon) and see if it solves this issue - [Releases](https://github.com/8bitPit/Niagara-Issues/releases)
