### ISSUE TITLE
Widget stops filling screen after closing unlocked Fold 3

### ISSUE THREAD

**Issue by Zarvinx** [8bitPit/Niagara-Issues#1982]
### Describe the bug

Under certain circumstances, the **Fill screen** feature for widgets stops working. All widgets are affected. 

### Steps to reproduce

1. Have a widget on the Home screen with **Fill screen** enabled. 
2. Unfold device to use inner display.
3. Fold device closed **without locking it first**. It does not matter if "Lock when folded" setting is on. 
4. Unlock outer display. Widget no longer fills the screen but the feature is still enabled. Inner display is unchanged. 

To fix how it appears on the outer display:
1. Disable and re-enable **Fill screen**. 
OR
2. Unfold the device, lock it manually with the power button or double-tap, then fold it closed.

### Device name

Samsung Galaxy Fold 3 

### Android version

Android 12

**Comment by Oddward** [comment]
thanks for the report. The dynamic layout between the two screens depends on the change in width, seems like there's an issue when the width changes from wide to narrow. Since it's reproducible Peter can hopefully look into it on the Fold

**Comment by Amorphous404** [comment]
Related to #2153

**Comment by Zarvinx** [comment]
Now that you brought it back to my attention, I tested and I can no longer reproduce this issue. It works so seamless, I didn't even notice.
Cheers!

**Comment by Amorphous404** [comment]
Hi @Zarvinx, Glad to hear that! Thanks for the update. If you re-encounter the issue, please let us know.
