### ISSUE TITLE
Change icon packs when changing light/dark phone's mode. 

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#1983]
### Is your feature request related to a problem?

There're lots of white icon packs, and I personality use a one of them. I regularly work inside, but when I go outside, and it is bright as hell. I need to switch to phone's mode for better contrast contrast. When Niagara switch to light mode, it becomes impossible to see white icon packs –because niagara does no have enough contrast with light icon packs in light mode– until switching back to dark mode again. 
![1](https://user-images.githubusercontent.com/72170242/176081631-5978139d-aeed-4007-89a3-a702b17c56cf.jpg)
![2](https://user-images.githubusercontent.com/72170242/176081731-f5d25c4b-f2e7-4adb-b930-b40eb84119f6.jpg)

### Describe the solution you'd like

Let the user choose one icon pack when light mode on and another when dark mode on. These packs change according the pack being used. 
I'm sure many people would appreciate something like this. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
It might be a little messy for Niagara to manage 2 icon pack settings, and changing your icon pack or setup will probably mean changing both of them, together with manually changed icons etc. Maybe there's a way to increase contrast enough to continue using the white icons on light mode

At the moment you might wanna use something like Icon Pack Studio and add a faint border or shadow around the icons, e.g. light gray, that will be more visible on the light background. Dynamic icons are also becoming more popular

**Comment by Just-SKY** [comment]
I understand, so I gonna closed this issues.
