### ISSUE TITLE
Repositioning a favorite in Edit favorites scrolls the screen up.

### ISSUE THREAD

**Issue by tiagoad** [8bitPit/Niagara-Issues#1986]
### Describe the bug

I'm using Niagara launcher on a Oneplus 9 Pro, on Oxygen OS 11.2.10.10.LE15BA.

I've got more favorites than the screen height allows for. In the edit favorites screen, when I move a favorite down the screen moves up, making it tricky to position the item without scrolling several times.

Moving up, the response is too quick which also hinders fine adjustment.

### Steps to reproduce

1. Go to the favorites page
2. Add enough favorites that the screen scrolls
3. Try moving one of the top items down

### Device name

Oneplus 9 Pro 

### Android version

Android 11

### Screenshots / Screen recordings

https://gfycat.com/flawedmindlesscaimanlizard

**Comment by tiagoad** [comment]
Thanks @Oddward.

Update to latest firmware (Android 12) exhibits the same behaviour.

**Comment by TFackler** [comment]
Hey there,

I can reproduce the issue of the screen moving up when you move an entry down. We will be looking into this.

The other behaviour however I can't reproduce. I will try some more and then get back to you :)

**Comment by TFackler** [comment]
We also managed to reproduce the second issue and will fix both
But since it isn't high on our priority list right now. it might take a while.

**Comment by tiagoad** [comment]
Hi, any news on this? My app was updated but the issue persists. It makes managing my homescreen quite painful. Thanks!

**Comment by Amorphous404** [comment]
It seems it is a duplicate of the ticket Peter created #1660

**Comment by TFackler** [comment]
@tiagoad Sadly we haven't had the time to be tackling this issue yet.

@Amorphous404 You are right, I will close this issue, please move all future discussions to #1660
