### ISSUE TITLE
Shadow when switching back to launcher 

### ISSUE THREAD

**Issue by macleod-ee** [8bitPit/Niagara-Issues#1987]
### Describe the bug

When in an app and heading back to home (the launcher) this shadow is visible at the top of the launcher for a few seconds and then disappears. I have attached a screenshot.

![Screenshot_2022-07-05-10-29-49-69_a4824db61f40c53807964ea8b14c92fe](https://user-images.githubusercontent.com/4322153/177364069-986421d5-297d-4a5c-ba1d-63e494d853ff.jpg)

I have attempted turning off status bar and still this shows up, dim wallpaper is not on. 

### Steps to reproduce

1. Set a light wallpaper
2. Open an app
3. Go to home

### Device name

Oneplus 8T

### Android version

Android 12

**Comment by Oddward** [comment]
Is your screenshot in another app or on the recent apps/app switching screen or the launcher itself? Niagara can't control what's on the recents

**Comment by drannex42** [comment]
This screenshot is of the launcher itself
![Screenshot_2022-07-08-09-08-31-91_a4824db61f40c53807964ea8b14c92fe](https://user-images.githubusercontent.com/4322153/178008478-9685cea0-e010-49a8-ad9b-e1d86b8db63d.jpg)

And then after three or so seconds the shadow disappears.

**Comment by drannex42** [comment]
This appears to be related to the Recent Apps screen having a delay (although not evident when in recent apps, which is strange). I'll close this.
