### ISSUE TITLE
Doublet-tap Alphabet to sleep show the All App List on next phone unlock if done with fingerprint.

### ISSUE THREAD

**Issue by Fritzzin** [8bitPit/Niagara-Issues#1989]
### Describe the bug

After double tapping to sleep on the alphabet, on the next unlock, if done with a fingerprint sensor, instead of my home screen, I will have the All Apps List open or it will be in the closing animation (sliding back to the right side of the screen).

Seems to be random when I unlock it if the app list is going to be open or in the closing animation.

### Steps to reproduce

1. Turn on the "Quick lock gesture" feature
2. Go back to the home screen
3. Double tap the alphabet to turn off the screen
4. With the phone asleep (Screen off), unlock with the fingerprint sensor 

### Device name

Samsung S20 FE

### Android version

Android 12

### Screenshots / Screen recordings

Video example:
https://user-images.githubusercontent.com/53453816/177924780-7dcab6e1-ce7d-4908-b705-a1de26e02c91.mp4

**Comment by Oddward** [comment]
This isn't a bug, the launcher remembers your navigation position for a few seconds when you navigate away in case e.g. you accidentally launch an app or lock the screen and want to quickly backtrack. If it doesn't happen if you unlock the device after several seconds then it works as intended.
