### ISSUE TITLE
Music App Enhancement: assign music apps to only pin if connected to specific device. 

### ISSUE THREAD

**Issue by JamesL13** [8bitPit/Niagara-Issues#1990]
Since lots of headphones have apps now it'd be really nice if you could set certain music apps to only pin if connected to a certain Bluetooth device. I have Sony and Jabra headphones and connect to Bluetooth in my car so what I'd hope to be able to do is this:

When I set a music app there is an option to assign it to a device with a list of Bluetooth devices I've connected to. This way if I connect to my Sony headphones, my Sony headphone app shows up in the music pins but my Jabra and Google maps apps do not.

If I connect to my Jabra headphones, my Jabra headphones app shows up in the music pins but my Sony and Google maps apps do not.

If I connect to the Bluetooth in my car Google maps shows up in the music pins but my Sony and Jabra apps do not

If a music app doesn't have a device assigned to it then it will always show up when connected to any device.

**Comment by Oddward** [comment]
It's an interesting idea but it seems like it would complicate the UX which is designed to be a quick & simple setup (i.e. just long-press app and toggle "Set as music app"). If it's to reduce the number of items that appear at the top of the favorites you could also put the apps in a pop-up folder and assign the folder as a music app 

I wonder if there's a way to support this in a simplified or automated way

**Comment by timm0e** [comment]
Hey there :wave: 

While the feature you've proposed isn't directly planned, there exist plans for features that will hopefully also cover your use case:

#786 
#755

Sadly I can't give you any ETA on these features, because they're not on the roadmap for this year, and we haven't looked into next year yet  :disappointed:
