### ISSUE TITLE
Applied Icon packs goes missing on reboot

### ISSUE THREAD

**Issue by onlytanmoy** [8bitPit/Niagara-Issues#1991]
### Describe the bug

When I switch on my mobile in the morning, the icon pack that was applied is no more there.
Also in Niagara settings it says icon pack=None
All the apps remain in their place and nothing else resets just the icon pack alone

### Steps to reproduce

1. Apply an icon pack
2. Switch off mobile at night
3. Switch it back on next day
4. Applied Icon pack missing

### Device name

Galaxy S20 FE 5G

### Android version

Android 12

**Comment by Amorphous404** [comment]
Can you please check if you can reproduce the issue on the latest version

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6

**Comment by onlytanmoy** [comment]
@Amorphous404 all good in the latest version, unable to replicate this issue :) thank you!
