### ISSUE TITLE
Hide status bar option doesn't hide the status bar

### ISSUE THREAD

**Issue by jeroendee** [8bitPit/Niagara-Issues#1993]
### Describe the bug

Expected:
Using the option "Hide status bar" hides the top status bar. 

Actual:
Using the option "Hide status bar" doesn't hide the status bar.

### Steps to reproduce

Given a OnePlus 6 with the latest LineageOS 19.1 (Android 12) (and google apppack)
When using the unlocked version of the Niagara launcher
And setting the option: "Hide status bar" to on/true/etc
Then the status bar is still displayed. I.e. is not hidden.

### Device name

OnePlus 6

### Android version

Android 12

**Comment by jeroendee** [comment]
Don't know what happened, it works know....?

**Comment by Amorphous404** [comment]
There are few reports regarding the same in the telegram group, also i personally faced it on my older xiaomi device, and my current device which runs on OxygenOS, where a launcher restart is needed to fix it.

https://user-images.githubusercontent.com/96917972/208745744-7534773b-6e18-4f23-9c92-82898536abc2.mp4

**Comment by 8bitPit** [comment]
Hopefully, our [latest release (v1.9.2)](https://github.com/8bitPit/Niagara-Issues/releases) fixes the issue. @Amorphous404 can you check?

**Comment by Amorphous404** [comment]
@8bitPit Great! Unfortunately, this is random behavior; if you've already fixed it, I'll never see this problem again 😅, but if I notice or receive any reports, I'll let you know 👍
