### ISSUE TITLE
Improve text contrast when showing notification text on home screen

### ISSUE THREAD

**Issue by wardellbagby** [8bitPit/Niagara-Issues#1995]
### Is your feature request related to a problem?

Although Niagra has settings for dimming the wallpaper in the app drawer to improve text readability, there's no similar feature for the home screen, which can lead to text that's borderline unreadable on certain wallpapers and definitely fails to meet accessibility guidelines for text contrast. (See attached image for an example.)

![Screenshot_20220714-041621](https://user-images.githubusercontent.com/7834478/178970997-eb57f8e3-b173-45b8-b7dd-a1d5814ddf9c.png)

### Describe the solution you'd like

To solve this, I recommend a selective dimming: dimming the background of the notification on the home screen only when a notification exists. This keeps the aesthetic of a full screen wallpaper most of the time while still allowing easier readability when on the home screen.

And, similar to the Dim Wallpaper feature, this could also be an optional toggle. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Niagara keeps text colour to only 2 shades - light with text shadow or dark - for maximum contrast, but no setting will work for all wallpapers, in cases like this it's not the colours but the busy nature of the wallpaper that decreases readability. The suggestion will almost certainly need its own toggle separate from the app list dimming which is something we try to avoid as much as possible unless necessary. 

Atm you can try a bolder font or use a darker/dimmer wallpaper (plenty of apps let you dim static images or dims them dynamically on live wallpapers)

___
*P.s. we've explored some digital mockups of this idea before but the result wasn't ideal*

**Comment by Amorphous404** [comment]
🔗 Merged with #717
