### ISSUE TITLE
Choose Whether Popup Folder Stays Open After Trying To Return To Home Screen

### ISSUE THREAD

**Issue by Shrek-SC** [8bitPit/Niagara-Issues#1999]
### Is your feature request related to a problem?

It's quite annoying when you want to go to the home screen to open something from a different folder or list, only to find that a pop up folder I used to open an app is still open, and I also need to then close that too. It's particularly awkward when using gesture input Vs button navigation and was one of the main annoyances I had with iOS.

### Describe the solution you'd like

Can we please have a toggle to disable popup folders still being open after launching an app from it and returning to the home screen?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
This is an intended behavior to prevent accidental touch, If you stay on the opened app for less then 3 secs , the popup i.e previous screen, will still stay.

If more, it doesn't stay anymore

**Comment by topsy-turvy99** [comment]
> ### Is your feature request related to a problem?
> 
> It's quite annoying when you want to go to the home screen to open something from a different folder or list, only to find that a pop up folder I used to open an app is still open, and I also need to then close that too. It's particularly awkward when using gesture input Vs button navigation and was one of the main annoyances I had with iOS.
> 
> ### Describe the solution you'd like
> 
> Can we please have a toggle to disable popup folders still being open after launching an app from it and returning to the home screen?
> 
> ### Feature Request Procedure
> 
> - [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

This is an intended behavior to prevent accidental touch, If you stay on the opened app for less then 3 secs , the popup i.e previous screen, will still stay.

If more, it doesn't stay anymore

**Comment by Rod911** [comment]
As @topsy-turvy99 said, this is intended behavior.
This is the same for search, apps list scroll position and yes popup/folders.
