### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by Chaphasilor** [8bitPit/Niagara-Issues#2]
Add gesture support for things like opening the notification shade (swipe down), opening the app drawer (swipe up), opening the app search (maybe double tap?), etc.

This would go a long way improving the one-handed user experience!

**Comment by 8bitPit** [comment]
Opening the notification shade in android is pretty hacky and I don't know how long this method will be “supported”. Swiping up to open the drawer could be implemented rather easily. However, tapping the right side of the screen is so fast, that you don’t need an extra gesture, in my opinion.
Search could be opened by pressing the home button (even though that’s not a gesture).

**Comment by lepa22** [comment]
I also think that swiping up to open the drawer would make the launcher lose its uniqueness.

**Comment by jakcharvat** [comment]
Ideas by @makash720: 

double tap to screen off

Swipe down to pull quick setting

Swipe right to launch app drawer (not alphabet scroll

**Comment by jakcharvat** [comment]
@8bitPit Here's an idea for how to solve the lack of possible one hand gestures: instead of totally hiding the nav bar you could replace it with either a bar of buttons for different actions, or a gesture based bar for different actions aka Pie's gestures, so a simple pill at the bottom of the screen, tapping out could bring up app search, pulling it right could open the Google App, pulling it left could do something else

**Comment by zamber** [comment]
> Search could be opened by pressing the home button (even though that’s not a gesture).

It is (an option) on OnePlus devices with 8.1. All 3 navigation buttons are then swipe-up gestures from the bottom edge of the device. It's kinda tricky but it works. XDA has an in-house app that adds support for this to other devices but it's pretty hacky.

**Comment by robertlankford** [comment]
I would like to see gesture support added as well.  However, my recommendation wouldn't be for specific actions on specific gestures (like some posts on here).  I'd like to have a series of gestures that the launcher could intercept when it has focus and the ability to map them to various actions as I see fit.

For example, I've personally grown very accustomed to having Google Pay launch with a double-tap on the home screen.   I certainly don't use it enough for it to be in the top 8 favorites, but when I need it, I need it quickly.

It'd be nice to see a series of things (kind of like how Nova does it) that allows you map things to:

- double tap
- triple tap
- tap-n-slide up/down
- pinch/expand
- two finger slide up/down
- etc.

And, of course, the mappings themselves shouldn't just be restricted to launching particular apps.  They could also invoke a series of actions related to android itself (flashlight, airplane mode, whatever).  Heck, launch tasker actions or something, that'd be neat.  In fact, tasker integration might be all you'd need to add.  With the ability to map a gesture to a particular task in tasker, the user could then determine whatever action they actually want done whenever that gesture is detected by defining it in tasker instead.

I love the launcher, but it's a little too focused/basic.  It seems like it could use this type of escape valve, so to speak, to allow all sorts of other features/behaviors without affecting the look-n-feel of the launcher itself.

**Comment by halxinate** [comment]
PLEASE, no swipe gestures. Or only optional. That's counterintuitive and also will interfere with some live wallpapers. Even right side tap is interfering. But all other launchers are even worser. Yours is unique.

**Comment by Hoomum** [comment]
I really don't see a need for gestures. I think that many people like Niagara for being fast and simple and unique but then want to turn it into clones of other launchers.

**Comment by berdzena** [comment]
For those who wants gestures.. Use app called ,, edge gestures,,

**Comment by halxinate** [comment]
The best approach is to have an option check for everything in the app's settings. Because all people are different. Just noticed that the tap opens the app list on both sides :( That's often interfering with the Samsung's Edge Screen swipe for me (I'm using the phone left handed).

**Comment by berdzena** [comment]
I think it would be great, to take some features from nokia z launcher. Niagara+Z=best launcher ever

**Comment by yukicreative** [comment]
I'd like to add that I would love to have at least the swipe up gesture. I keep the alphabet hidden and when I'd like to just get to something at the very top of my app list, it's annoying to have to enter the list wherever I can manage to get it to pop up, and then scroll back to the top to open my app.

**Comment by Sacchid** [comment]
If in-app navigations are going to supported, those should be opt-in and should not mess with already messy android gesture systems - both Android 9 and Android 10 gestures.

**Comment by 8bitPit** [comment]
Hey everyone, I decided to close this issue, because the only accessible gesture that isn't used by Niagara Launcher is the swipe up gesture. This gesture has it's own issue here: https://github.com/8bitPit/Niagara-Issues/issues/122
