### ISSUE TITLE
Custom app name color/ Text color / Text Shadow color

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#20]
Idk if this is possible but the text color should pick color from wallpaper just like how samsung does on the lockscreen clock

**Comment by 587saboor** [comment]
@8bitPit no, i mean colored text, white text with kind of a shade of color from the wallpaper

**Comment by 8bitPit** [comment]
The text would be harder to read though.

**Comment by 8bitPit** [comment]
Thanks for that reference, I’ll keep that in mind and will tell you if I am working on this.

**Comment by zamber** [comment]
@587saboor https://photos.app.goo.gl/jH6kqo2raXiShFHR8 is no longer accessible.
@587saboor s/suddle/subtle/

IMO a a somewhat pointless feature if it's automated. I would rather have an option to change all font and UI colors along with "automatic matching" as an option.

Currently the automatic color picking fails with live wallpapers. A workaround for it is to load a normal image wallpaper with similar colors before loading the live wallpaper.

**Comment by 8bitPit** [comment]
@zamber if you're running atleast Android 8.1 your live wallpaper app could provide correct colors (see: https://developer.android.com/about/versions/oreo/android-8.1#wallpaper), idk how many apps support that though

Btw. I integrated Muzei Live Wallpaper color support for every version (they offer an API)

**Comment by 8bitPit** [comment]
@zamber oof

**Comment by volcbs** [comment]
The white text has drop shadow, but the black text has no drop shadow. Could you just make the black text has drop shadow too? Like white or something lighter to make it readable?

**Comment by 8bitPit** [comment]
@volcbs, sadly text shadows only look good on light colors.

**Comment by timm0e** [comment]
+1 for more shadow. Would definetly improve readability on wallpapers with brighter colors

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.

**Comment by 8bitPit** [comment]
However, custom fonts will be supported: #191

**Comment by Manu99it** [comment]
I'm interested in this also. Smart launcher does this also for the clock widget and it looks fairly good on some walls. I think it improves even readability in some cases

**Comment by Khelgarion** [comment]
I really love this launcher,  but I can't figure out why custom font colors are low priority.  Simple black or white font isn't always readable depending on the wallpaper.   My eyes aren't the best so being able to adjust the colors would help quite a bit.  Otherwise the wallpaper choices are very limited. 

I how this gets moved up the line.

**Comment by KaymaPirog** [comment]
Unfortunately, some apps have the same colors in Niagara Dots! It would be great if there was an option to fully customize their color. This would provide users with a better personalization experience.
A line could be added where an RGB code can be entered.

**Comment by mazany** [comment]
I have issues with readability of the items on some wallpapers. It would be great to be able to either:

1. change color
2. adjust **font size** / weight (**bold**)
3. more prominent **text shadow** / **outline**

**Comment by fallsdevil** [comment]
hey, I know this is about text, but I wanted to expose my idea that I think would be interesting: the option for **dots** instead of app icons to have different colors for everyone on the list, like all dots white, black, some color predominant wallpaper, I think it would be cool and I've been wanting this for a while, I'm an old user.

**Comment by Aisuzuka** [comment]
![圖片](https://github.com/user-attachments/assets/aaeaa984-68a1-4eef-a80b-122c35a41d59)
I think the display effect after customizing the font color and shading will be like the clock in the picture, which improves the readability and looks cooler.

**Comment by halilwb** [comment]
![Image](https://github.com/user-attachments/assets/8f685207-77c1-4761-9607-18c9e0bc3a70)

This is my current setup and The only thing I think is missing is that the colors of the text are the same as the icon colors. It looks much better when using a two-color wallpaper. Niagara can even add this type of wallpaper to its own wallpapers. It looks very simple and nice at the same time. It can be produced in infinite numbers. If we could adapt the text color to the situation, it would have turned into a launcher that is fully integrated with the wallpaper.

**Comment by cmoulder** [comment]
I just discovered this was not an option, and it is quite puzzling to me. I changed my background and neither white nor black are readable on a mid-tone background.
