### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#200]
It would be nice to add haptic feedback on the scrollbars and stuff like that, scrolling through every letter gives like some kind of 1ms vibration

It would make me more obsessed with scrolling on the letters lmao

**Comment by Shinra04** [comment]
You'll get annoyed really soon lol

**Comment by Rod911** [comment]
Will increase battery usage too

**Comment by 8bitPit** [comment]
@Shinra04 is right, would be annoying, you scroll so often through your apps. And as @Rod911 mentioned   it would drain your battery (that's why Android disables vibration when battery saver is turned on)

**Comment by 587saboor** [comment]
@8bitPit atleast a switch on settings
