### ISSUE TITLE
Flickering notification 

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#2000]
### Describe the bug

Hey 👋

Apps with notifications that refresh in real time look like they are flickering while they update the notifications... But it is not the case in the system notifications panel. So can we have it optimised to look smoother when it refreshes it's data?

### Steps to reproduce

Use any app that has an actively refreshing notification

### Device name

Moto G52

### Android version

Android 12

### Screenshots / Screen recordings

Uploading screen-20220720-231651.mp4…

**Comment by Oddward** [comment]
I believe you're referring to silent notifications for things like download status or sticky notifications etc which are only visible inside a pop-up? These aren't important notifications and when they finish they'll normally have a regular text notification so this is not a priority to fix, and note that Niagara's pop-ups aren't really dynamic/real-time at all - e.g. clearing notifications needs the pop-up to close to update the view - so this would require extra work afaik

Will update if there's any change on this subject
