### ISSUE TITLE
 Shortcuts in sesame search results integrated via niagara not working

### ISSUE THREAD

**Issue by twjazzhuang** [8bitPit/Niagara-Issues#2001]
### Describe the bug

Shortcuts in sesame search results integrated via niagara not working

But the shortcut for Sesame Search itself to search can use

### Steps to reproduce

1. open Sesame integration
2. open Niagara Search
3. search any shortcuts
4. run it.
5. and don't work.

### Device name

Google Pixel 6 Pro

### Android version

Android 12

### Screenshots / Screen recordings

https://youtu.be/yvAPSbGS_Jk

**Comment by twjazzhuang** [comment]
"錯誤" is meaning Error.
Add to app list doesn't work.
In Nova works very well.
After this update, the error toast is also gone.

Screen recordings:
https://www.youtube.com/watch?v=2AjP0XNTUtk

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1579

**Comment by 8bitPit** [comment]
From #1579: 
> Thanks @topsy-turvy99, we're reconsidering https://github.com/8bitPit/Niagara-Issues/issues/1887 because Sesame has now been acquired by Branch and stopped development. Regarding this issue, if it's caused by Sesame, I'm afraid Sesame won't fix it anymore, and if it's caused by us it's not worth fixing it because we're building our contact search.

**Comment by 8bitPit** [comment]
> We added one final fix in v1.7 that made opening shortcuts more reliable, though. It might also fix the direct dialog bug.
