### ISSUE TITLE
Folder Icons

### ISSUE THREAD

**Issue by sndri** [8bitPit/Niagara-Issues#2004]
### Is your feature request related to a problem?

Folder icons currently just cycle shades of blue, and I have everything in folders so this doesn't look great

### Describe the solution you'd like

Set them to a gradient or others have suggested, or similar eg using colours from apps within, anything other than cycling blue shades as default 
https://www.reddit.com/r/NiagaraLauncher/comments/p7b9te/change_folder_colour/?utm_medium=android_app&utm_source=share

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Rod911** [comment]
There is an open ticket #1607 but no plans to implement this feature at the moment
