### ISSUE TITLE
Swipe-left favorites shortcut

### ISSUE THREAD

**Issue by MichaelJuskowicz** [8bitPit/Niagara-Issues#2005]
### Is your feature request related to a problem?

I have several apps that I consider to be similar enough that I wish I could combine them so that they take up only one favorite slot. Currently this is accomplished by putting one of the apps inside of the pop-up folder for the other so that it takes up only one favorite slot. But this still requires swiping-right on the favorite and tapping on the right app which is not as quick or seamless when in a hurry. I have accomplished this in other Launchers using the proposed solution but via a swipe-up shortcut.

### Describe the solution you'd like

A shortcut where swiping left on a favorite opens a chosen app (or app shortcut.) For example I might have WhatsApp as a shortcut and swiping left on WhatsApp will instantly open the Messages app.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by MichaelJuskowicz** [comment]
# Another approach
Here's another possible solution that may actually work more synergistically throughout Niagara and is in line with the way Niagara's productivity focused, quick gestural navigation.

## Different solution:
If the user does not lift their finger, when swiping right on a favorite and the pop-up folder is open, the item under the user's finger will be selected when they lift their finger.

This will allow the user to quickly select any item in a pop-up folder with a single continuous gesture.

### Alignment with Niagara style and possibility for future, similar implementations
It also aligns with Niagara's unique style of searching for apps using the alphabet sort gesture, and can even be implemented there; if the user moves their finger horizontally toward the app list while scrubbing through the alphabet it can show a "hover" state on the apps and perhaps even change to scrubbing within that letter.

**Comment by Oddward** [comment]
Folders were made for this use case, the primary difference between them and app pop-ups is you don't need to swipe to open them (just tap) and they're not binded to any specific app. The swipe-left gesture is already used to clear notifications from the notification preview.

Your second suggestion sounds too convoluted imo and will lead to a lot of accidentally launching things, we try to keep a balance of minimal and simple to use
