### ISSUE TITLE
Simple Notification Alerts

### ISSUE THREAD

**Issue by BanterlopeTM** [8bitPit/Niagara-Issues#2007]
### Is your feature request related to a problem?

I find I spend more time on my phone when there is a lot of information presented to me. Notifications are one of the main culprits, the current notification settings available in Niagara offer a lot of information and can clutter the home screen. This takes a very clean, simple aesthetic and makes everything look messy. 

### Describe the solution you'd like

I would like to suggest one more Notification Toggleable option which would allow for notification alerts.
I would imagine this would look something like a Dot or a Number next to the icon. 
I feel this would be a good addition to the launcher as it would help keep the simple aesthetic whilst also alerting the user to the notification so it doesn't go missed. This is especially useful if used in conjunction with 'Hide Status Bar' as that removes the visible stock notification icons.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Rod911** [comment]
Your feature request seems similar to a feature called notification dots, unfortunately we have no plans to implement this feature for the time being. Please see #800.
You can leave your comments in the linked issue or reopen this issue if I misunderstood your query.

**Comment by Oddward** [comment]
Additionally, it sounds like you should make use of the [Notification summary](https://github.com/8bitPit/Niagara-Issues/issues/1990) feature which was developed as a digital wellbeing feature for this very reason @BanterlopeTM
