### ISSUE TITLE
Option to place widgets under apps inside a pop-up

### ISSUE THREAD

**Issue by Just-SKY** [8bitPit/Niagara-Issues#2008]
When I have certain amount of apps inside of a pop-up and add a widget, the apps are pushed down forcing u to scroll in order to reach certain app. 
I want to have my apps first because I can access them more effectively.

### Describe the solution you'd like

Give the option to place widgets under the apps inside of a pop-up. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
For simplicity having toggles for very minor tweaks like this is avoided or there would be dozens & dozens more. Moving major elements up or down for reachability doesn't usually solve the issue as you'll have cases where the other thing is now harder to reach. 

If a widget in a specific pop-up is the issue and that widget doesn't have information that you need at a glance then you can opt to place the widget elsewhere or place the app there instead

_Will update here if there are any changes_
