### ISSUE TITLE
Notification Dots

### ISSUE THREAD

**Issue by praveen2203** [8bitPit/Niagara-Issues#201]
I think you have hit the jackpot with notification dots. I am yet to see an implementation like this. Not even Google's notification dots are THIS useful. I have been using them a lot these days. 

One small improvement can make it better. Please add an indicator for notification dots so that I wont have to look at the notification bar in order to know which apps have notifications for me. 

Also I love the fact that I can still get notifications in dots even after dismissing them. Amazing work here.

**Comment by Montell2099** [comment]
What phone & OS are you on? Can't get then to work on my Pixel 2 with Android P.

**Comment by 8bitPit** [comment]
@Montell2099 I'm sorry. Did you grant the launcher notification access and enabled notification dots in Niagara AND in Androids settings? Furthermore Do not disturb restrictions could be turned on.

![image](https://user-images.githubusercontent.com/9284845/45550148-5f313e00-b82a-11e8-82d5-51abe2f6a1d7.png)
![image](https://user-images.githubusercontent.com/9284845/45550179-6f491d80-b82a-11e8-8d46-772922de164f.png)

**Comment by 8bitPit** [comment]
Nah, it’s not really your fault. I should remove my notification toggle and should link to the system settings instead for Android 8+ devices.

**Comment by 8bitPit** [comment]
@praveen2203 sorry that I did not respond. Does the notification text next to the app icon not show up?
