### ISSUE TITLE
RSS News Feed

### ISSUE THREAD

**Issue by RPM28XI** [8bitPit/Niagara-Issues#2010]
### Describe the solution you'd like

Add news and traffic near me to the agenda sliding sheet.
![Picture1](https://user-images.githubusercontent.com/8072208/184813464-d70477ba-20b9-430d-83a0-43ccb62d8468.png)
https://docs.microsoft.com/en-us/bingmaps/rest-services/getting-traffic-incident-data

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Crsmsg** [comment]
I wish this feature integrated to Niagara

**Comment by Oddward** [comment]
Thanks for the suggestion, but it seems very cluttered and similar to the Google News Feed. The Niagara widget features are meant to be simple & minimal out-of-the-box solutions with very little configuration, and there are no plans for further integration with apps like Google's. A totally customizable RSS feed is very much out of scope

Will try to update here if there are any related changes
