### ISSUE TITLE
Empty Space Below Clock

### ISSUE THREAD

**Issue by deybedanta** [8bitPit/Niagara-Issues#2011]
### Describe the bug

An empty space below the clock appears. I have experienced this multiple times. Restarting the launcher does not help.

### Steps to reproduce

Happens randomly. Hence, no steps.

### Device name

Realme Narzo 50A

### Android version

Android 12

### Screenshots / Screen recordings

https://youtube.com/shorts/YmQmKpOuWlk?feature=share

uploaded here (idk why it's a short)

**Comment by PolyBluee** [comment]
bullshit support, opened this two days ago still no reply. just exceptional.

**Comment by topsy-turvy99** [comment]
> ### Describe the bug
> 
> An empty space below the clock appears. I have experienced this multiple times. Restarting the launcher does not help.
> 
> ### Steps to reproduce
> 
> Happens randomly. Hence, no steps.
> 
> ### Device name
> 
> Realme Narzo 50A
> 
> ### Android version
> 
> Android 12
> 
> ### Screenshots / Screen recordings
> 
> https://youtube.com/shorts/YmQmKpOuWlk?feature=share
> 
> uploaded here (idk why it's a short)

Can you please mention which Niagara version you're on?

And the source from where you installed the app?

**Comment by topsy-turvy99** [comment]
Can you please mention which Niagara version you're on?

And the source from where you installed the app?

**Comment by PolyBluee** [comment]
v1.6.5
persists on 1.7.1 beta
source: paly store

**Comment by topsy-turvy99** [comment]
> v1.6.5
> persists on 1.7.1 beta
> source: paly store

Can you share a screen recording?

**Comment by Oddward** [comment]
> bullshit support, opened this two days ago still no reply. just exceptional.

P.s. this is not a support channel, and attitude is not needed. Reading the [How to Request a Feature / Report a Bug](https://help.niagaralauncher.app/article/44-feature-requests) is a prerequisite to opening an issue. If you want to contact support you can write an email to support or simply chat in one of the official community channels as mentioned in the article

**Comment by Amorphous404** [comment]
> > v1.6.5
> > persists on 1.7.1 beta
> > source: paly store
> 
> Can you share a screen recording?, you Removed the previous video it seems

The blank space usually shows up on pirated/modded versions.

https://help.niagaralauncher.app/article/108-random-numbers


Update to this latest build and please report back if the issue still persists.

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6
