### ISSUE TITLE
Music widget doesn't work well on all music players

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#2012]
### Describe the bug

Music Widget does not work well with all music players, with the Foldplay app the swipe works well to close the player, but the Music Widget only displays the title and not the singer, with the MUSIC System app the Music Widget is not displayed. I hope the developer solves the problem of the Music Widget as soon as possible that works with all music players with an update. Thank you

### Steps to reproduce

Music Widget does not work well with all music players, with the Foldplay app the swipe works well to close the player, but the Music Widget only displays the title and not the singer, with the MUSIC System app the Music Widget is not displayed. I hope the developer solves the problem of the Music Widget as soon as possible that works with all music players with an update. Thank you

### Device name

Oukitel C16 Pro

### Android version

Android 9 (Pie)

**Comment by Oddward** [comment]
The music widget works as long as the app playing media supplies the data it needs using standard Android media APIs, some music apps have some custom handling of their media playback controls/notification and Niagara can't detect those - such apps might have a setting inside to switch between the custom notification and standard one (e.g. Stellio) - and some will occasionally fail to show album art or something. 

Best way to tell if the music player should work with the Niagara widget is to see if everything is right and standard in the system notification tray
