### ISSUE TITLE
Niagara button resets and forgets its setting

### ISSUE THREAD

**Issue by Skellingtor** [8bitPit/Niagara-Issues#2013]
### Describe the bug

Whenever I set the Niagara button at the bottom of the home screen to open Google search, for example, after a short while it will revert back to its default state and ask me to set it up again.

### Steps to reproduce

1. Hold down the Niagara button and set up a function
2. Function works normally for a short time
3. After a while the button becomes a plus sign again and has no functionality

### Device name

Samsung Galaxy S22+

### Android version

Android 12

**Comment by topsy-turvy99** [comment]
So far no one reported anyone facing such issue but anyways thanks for reporting

Note: Beta Build (Might Not Be Stable)
https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.7.2

Can you try this build and report if the same issue persist in this build

Thank You

**Comment by Skellingtor** [comment]
I installed it, I'll come back if it's still happening after a few days,

**Comment by Skellingtor** [comment]
It's been a few days and the problem still persists. I set it to Google search as usual but when I look back at it the next day it's gone.

The swipe up action seems to be fine, my Niagara coin hasn't gone away at all.

**Comment by topsy-turvy99** [comment]
Does this issue only persist with google search shortcut?

**Comment by Skellingtor** [comment]
I mentioned google search because that's what I use the button for but I can try another shortcut for a bit and see if it still happens.

**Comment by Skellingtor** [comment]
I think the issue might be Google search. I set it to camera for a while and it stayed after a whole day, then I changed it to DuckDuckGo for another day and it's still there now. 

Not sure if that's worth fixing, but there you go :P

**Comment by topsy-turvy99** [comment]
Thank you, this will definitely help the devs to get to the root cause of the issue faster.

meanwhile you can try and see if the Google search action gets removed when you set it up for swipe up actions

**Comment by Skellingtor** [comment]
Forgot to come back here but swiping up still works fine for Google search.

**Comment by pri86** [comment]
I have the same issue, swipe up gesture with Google Search is reset after a couple of days whereas some random app that I assigned testwise persists.

**Comment by 8bitPit** [comment]
Thank you both for reporting @Skellingtor & @pri86. This issue seems to be caused by the search shortcuts getting removed; I'll merge this issue with https://github.com/8bitPit/Niagara-Issues/issues/1765.

**Comment by Amorphous404** [comment]
Happy to tell you that the issue has been fixed in 1.8.7, Could you guys please update to this latest build and let us know if it still does?

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.11

**Comment by Skellingtor** [comment]
I've had no issues for a while, thank you for your attention and work!

**Comment by pri86** [comment]
Issue didn't occur since update 👍🏻 Thanks.
