### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by Martinligabue** [8bitPit/Niagara-Issues#2014]
### Is your feature request related to a problem?

when searching for an app sometimes it suggests newly installed apps, but otherwise it's empty

### Describe the solution you'd like

I think a list of most searched apps, or the latest searched ones would be a not intrusive but useful feature.
(Since I'm here I'd also suggest to add the option to sort the searched apps by name/frequency/something else?)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
Something similar has already been requested, you can refer to #1833 and add your reason there on why you think this is feature is useful.

**Comment by Martinligabue** [comment]
thanks @topsy-turvy99 , I didn't find that when searching for similar issues

**Comment by Amorphous404** [comment]
🔗 Merged with #1833
