### ISSUE TITLE
Allow user to change Niagara Button icon

### ISSUE THREAD

**Issue by ModProg** [8bitPit/Niagara-Issues#2017]
### Describe the solution you'd like

Add the ability to choose an Icon for the Niagara Button when using it to display a widget

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
Niagara button auto adapts the icon based on the app you set for tap action.

Coming to your question,
Niagara button doesn't directly place the widget to the button, it puts it's inside a popup folder, hence it shows the folder icon.

**Comment by ModProg** [comment]
> Niagara button auto adapts the icon based on the app you set for tap action.
> 
> Coming to your question, Niagara button doesn't directly place the widget to the button, it puts it's inside a popup folder, hence it shows the folder icon.

Yes, but if you change the folder Icon, it does not update the button.

**Comment by topsy-turvy99** [comment]
that's not possible as of now to manually change the Niagara button icon,
it automatically adapts the icon from the app you set up for tap action, but icons are limited to some few apps.

**Comment by ModProg** [comment]
> that's not possible as of now to manually change the Niagara button icon,
> it automatically adapts the icon from the app you set up for tap action, but icons are limited to some few apps.
> 
> 

yes, that is what the bug report/feature request is about, to take the icon I selected for the folder and display it on the button 

Folder has Callendar icon
![Screenshot_20220818-220113_Niagara Launcher.jpg](https://user-images.githubusercontent.com/11978847/185484336-e48068ef-a2ac-48a6-8d55-b42629b45a2a.jpg)

Button has not 
![Screenshot_20220818-220300_Niagara Launcher.jpg](https://user-images.githubusercontent.com/11978847/185484518-4762f02b-4ff2-438f-91c1-e48918251bf1.jpg)

**Comment by topsy-turvy99** [comment]
That's not how the current niagara button adapts icons, it automatically adopts icons based on apps (limited to few apps of course)

What you're doing is manually changing the folder icon where the calender widget was added.

So i instead suggest to change the request title to "Allow User To Manually Change The Niagara Button Icon"

**Comment by Oddward** [comment]
The icon of the Niagara button reflects the action binded to it - e.g. opening a pop-up - not what item specifically it opens, except for a few ubiquitous browsers & apps. The icons are intentionally kept limited and with a minimal design to simply work and look more fitting with all themes & colours, and it's not really worth having extra configuration just for this use case - [see Niagara's design principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)
