### ISSUE TITLE
Can't add favorite to custom folder when it only appears in 'favorites' section 

### ISSUE THREAD

**Issue by johnw42** [8bitPit/Niagara-Issues#2018]
### Describe the bug

When editing a custom folder, the list of sections doesn't include the ⭐ section.

### Steps to reproduce

From a browser, select "Add to home screen". This creates a shortcut only in the favorites section, not the full app list. In Niagra, long press a custom folder and select "Edit [folder name] popup". The new shortcut does not appear anywhere in the list of items to add.

### Device name

Pixel 6 Pro

### Android version

Android 12

**Comment by topsy-turvy99** [comment]
For the shortcut to show up in edit page

Long press on the web shortcut you added>show in app list

Now it'll show in edit page.

Or with new version that is yet to hit the playstore you can directly add the shortcut to the popup folder by long tapping on it

If you're interested in testing the beta build you can download it from official discord & telegram channels of niagara

**Comment by Oddward** [comment]
topsy is right - when custom items are added to the home screen/favourites they're not indexed with the rest of the app list until you set them to show in the app list, this means they don't appear in the Edit pages except in favourites, but the latest beta versions let you direct add to categories/folders.

The betas are also released here in the github - [Releases](https://github.com/8bitPit/Niagara-Issues/releases)
