### ISSUE TITLE
Location-based app suggestions

### ISSUE THREAD

**Issue by kylepantall** [8bitPit/Niagara-Issues#2019]
### Is your feature request related to a problem?

I find it annoying finding apps that I frequently use in specific locations. E.g. bus passes or Google wallet at the supermarket etc.

### Describe the solution you'd like

Allow choosing locations or assigning places where an app should pin to the top of the list similar to how the music app is brought to the top when headphones are connected. 

This would be super useful and a pro selling feature. Would be nice to also have location based widgets. That show up too - could have a barcode widget that shows when you're at the supermarket etc.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
These feature has already been requested:
#1493
#1335
#786

**Comment by topsy-turvy99** [comment]
These feature has already been requested:
#1493
#1335
#786
