### ISSUE TITLE
Bug when sorting apps in folders.

### ISSUE THREAD

**Issue by loothibrhm** [8bitPit/Niagara-Issues#2020]
### Describe the bug

Trying to order apps inside a folder feels buggy and rough. Especially when I'm trying to move it down slowly somehow the list randomly starts jumping aswell.

1.7.1

### Steps to reproduce

1. Go to "Edit folder pop-up"
2. Try to move an apps position

### Device name

Samsung A50s

### Android version

Android 11

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/111198890/184508128-d58a04c6-49af-48a2-9248-ab474258587a.mp4

**Comment by topsy-turvy99** [comment]
Similar to #1986 ?

**Comment by Oddward** [comment]
Ya, will close as duplicate, please follow the linked issue above

**Comment by Amorphous404** [comment]
Sorry, please follow this ticket:
https://github.com/8bitPit/Niagara-Issues/issues/1660
