### ISSUE TITLE
App organization

### ISSUE THREAD

**Issue by juliex22** [8bitPit/Niagara-Issues#2021]
### Is your feature request related to a problem?

I have a lot of apps and the task of organizing them is very difficult. Folders help a lot, but since I have so many apps, hiding them one by one is quite annoying and I end up getting lost in the middle of the process. Also, if I want to get rid of a folder I have to show them one by one again.

### Describe the solution you'd like

An option to automatically hide applications that are in folders. It would be very functional and would save a lot of time. Please make it happen! It's the only functionality I missed in the launcher.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
It seems the request has already been made #1604, you can close this ticket and follow up the update there and give a 👍

**Comment by Amorphous404** [comment]
- Duplicate of #1604
