### ISSUE TITLE
Semi Transparent Pop-up folder background.

### ISSUE THREAD

**Issue by humayunbd** [8bitPit/Niagara-Issues#2024]
### Is your feature request related to a problem?

Currently Pop-up folder background is either black or white depending on the theme. People use various colors, wallpaper and icons etc. This simple black and white doesn’t blend in.

### Describe the solution you'd like

Add 70%-85% transparency property to (pop-up folder's) background colour. 

Also, to make things simple as possible, no need to add an option to adjust this. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
I guess the request is similar to #1674

**Comment by humayunbd** [comment]
> I guess the request is similar to #1674

No, Not similar. 

Blurring is require extensive coding. Also, use make the Launcher consume more resources. 

Whereas, translucency or transparency will require simple change in colour properties of background.

**Comment by TFackler** [comment]
Thanks for your proposal :)

The background of the pop-ups are actually themed already, they have a slight tint of the color we detect or is determined by Material You as you can see here:
![grafik](https://user-images.githubusercontent.com/38538728/191037362-8b4013be-89de-4ed2-a4d1-d931a3e74351.png)

We feel like adding transparency would not fit well with our currency design. Afaik we don't use transparency anywhere in Niagara yet. 
Therefore we won't implement your request.

**Comment by Oddward** [comment]
the native theming is very subtle and sometimes hard to notice, but it can be customized further via system settings or an app like Repainter which will let you change to any colour/shade. Simply reducing opacity across the board might just serve to reduce readability and look less simple
