### ISSUE TITLE
Make Clock font configurable 

### ISSUE THREAD

**Issue by wimstefan** [8bitPit/Niagara-Issues#2026]
I **love** the built-in clock widget for both its simplicity and functionality. 
I'd only wish to be the font configurable - at least from the clock itself - to make it more outstanding and visible.
I hope that's still inside the philosophy of this great project.

**Comment by topsy-turvy99** [comment]
Why don't you make use of Replace Clock With Widget Option, and replace it with a KWGT widget or any clock widget app that you desire?

The said feature will need an extra option/toggle to make it work.

For More Details: https://help.niagaralauncher.app/article/77-missing-customization-features

Example:

1st Screenshot: KWGT App
2nd Screenshot: Google Clock App

![HiShoot_20220821_203034.png](https://user-images.githubusercontent.com/96917972/185797443-af6b7ff2-a938-4140-9a67-4e255852c1c9.png)

**Comment by topsy-turvy99** [comment]
And Yes, you can overall change the Niagara font to your liking by adding any .ttf & .otf in:

Niagara Settings> Look> Font

**Comment by wimstefan** [comment]
You're right of course.
And I've managed to get a wonderful looking screen with a KWGT widget.

![Screenshot_20220821-232150.png](https://user-images.githubusercontent.com/4605934/185871659-ac94dce4-c643-45ef-9a7c-939839c5fe18.png)

But as I said I really love the simplicity and functionality of the built-in widget and making the Clock font configurable might be worth considering. Now I have to install KWGT, edit the widget of choice to make it working and align the widget with a secret command. Not that simple.

But that might also be a matter of perspective 😏

**Comment by Oddward** [comment]
The thing is, adding more such configuration options to the Niagara widget defeats the simplicity that makes it attractive as you mentioned, and as far as font goes it'll use the custom font that's applied to Niagara in the Look settings so this seems unnecessary. If you want to use a font that looks good for the clock but not for readability of notifications you can set the font to hybrid mode (set it twice) so that general text uses a readable sans seriff font instead.

**Comment by wimstefan** [comment]
> The thing is, adding more such configuration options to the Niagara widget defeats the simplicity that makes it attractive as you mentioned, and as far as font goes it'll use the custom font that's applied to Niagara in the Look settings so this seems unnecessary. If you want to use a font that looks good for the clock but not for readability of notifications you can set the font to hybrid mode (set it twice) so that general text uses a readable sans seriff font instead.
> 
> *We'll close this one, feel free to try & revive the other old issue Topsy linked

Thanks for you reply. I'll follow the other issue then.
Just for my understanding: I'm not sure how to achieve that "hybrid mode" your talking above ... would you mind elaborate a bit more? I'm on the latest version 1.7.5 ...

**Comment by topsy-turvy99** [comment]
Niagara settings>Look>Font>Tap on the currently applied custom font

**Comment by wimstefan** [comment]
I see. That's why it wasn't working for me. I'm using the system font 😏
