### ISSUE TITLE
"Remove from app list" doesn't work for shortcuts

### ISSUE THREAD

**Issue by abonhote** [8bitPit/Niagara-Issues#2028]
### Describe the bug

From the pop-up of Resplash, I long-pressed on "Auto Wallpaper" and chose "show in app list". It now shows up, but it's not removable anymore. It's the same with other app shortcuts, like Skype.

Version 1.7.2

### Steps to reproduce

1. Pick an app with shortcuts. I take play store as example.
2. Open the pop-up
3. Long press on "My apps"
4. Press "AZ Show in app list"
5. Find the shortcut "My apps" in the app list
6. Long press on it
7. Press "Remove from app list"
8. See if it's still there

### Device name

Samsung Galaxy S21 Ultra

### Android version

Android 12

### Screenshots / Screen recordings

https://www.youtube.com/shorts/POuav6Ya6sQ

**Comment by TFackler** [comment]
Thanks for letting us know. We will investigate this :)

**Comment by AndyL964** [comment]
It works if the app is in the Favourites list.

**Comment by Amorphous404** [comment]
Happy to tell you that the issue has been fixed in 1.8.7, Could you please update to this latest build and let us know if it does?

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.11

**Comment by AndyL964** [comment]
Can confirm it's fixed! Thanks a lot.

**Comment by Amorphous404** [comment]
@AndyL964, thanks for reporting, have a great day :)
