### ISSUE TITLE
Niagara widget accessable even when disabled

### ISSUE THREAD

**Issue by ishouldmomo** [8bitPit/Niagara-Issues#2029]
### Describe the bug

Niagara widget is completely disabled (weather, calendar date and upcoming events off).
KWGT widget used.
There is a space between the custom widget and favourites list - visible as a thick bar when pressed - that either brings up the Niagara agenda (touch) or Niagara widget settings (long press). This is unexpected behaviour.

### Steps to reproduce

Disable Niagara widget and use custom widget.
Touch between widget & favourites.

### Device name

Samsung Galaxy A72 SM-A725F

### Android version

Android 12

### Screenshots / Screen recordings
![VideoCapture_20220824-110703](https://user-images.githubusercontent.com/91489321/186392023-623bd06b-8372-48a5-a844-50ae6695dfae.jpg)

_No response_

**Comment by TFackler** [comment]
Hey there, thanks for reaching out.

The behvaiour you describe actually came from people wanting a quick way to access detailed weather and agenda even when using their own fully customized homescreen and having disabled the Niagara Widgets. Therefore we will keep this in. 

I hope the small blank space won't be too intrusive.

**Comment by ishouldmomo** [comment]
Space not intrusive, but the behaviour is annoying when accidentally activated

**Comment by Oddward** [comment]
It shouldn't be easy to accidentally trigger it, it would have to be a tap action in that small space and not a scroll action, in fact it's kinda hard to do it intentionally. Many users appreciate having it there and it's not really worth a whole toggle to enable/disable it. It might help to change the height of your custom widget or the favorites list position if it's an issue

**Comment by Amorphous404** [comment]
🔗 Merged with #2029
