### ISSUE TITLE
Niagara being run as Dex shell

### ISSUE THREAD

**Issue by luciodaou** [8bitPit/Niagara-Issues#2030]
### Describe the bug

Hello, since a few days ago, sometimes when enabling dex on my computer through USB cable I'm getting Niagara Launcher as DeX shell, instead of the windows-like default shell.

Got a S22 Ultra running latest Aug/2022 update.

### Steps to reproduce

Go to any app or screen not part of Niagara Launcher.
Launch Dex.

### Device name

Samsung S22 ultra

### Android version

Android 12

### Screenshots / Screen recordings

![image](https://user-images.githubusercontent.com/53634214/186428144-7094c21e-16f9-4eb3-8b72-3af69d54fe14.png)

**Comment by Maxr1998** [comment]
I believe this isn't really related to Niagara but an issue with DeX instead.
Were there any updates to the OS or system apps recently? Could you check if the same happens if you have another 3rd party launcher set as default launcher?

**Comment by luciodaou** [comment]
> I believe this isn't really related to Niagara but an issue with DeX instead. Were there any updates to the OS or system apps recently? Could you check if the same happens if you have another 3rd party launcher set as default launcher?

It may have started after August update. 

I updated Niagara manually using the APK and now if I open an app on the phone and try to go home, it says Niagara is not supposed to be run in DeX mode.

**Comment by luciodaou** [comment]
Doesn't happen anymore. Closing.
