### ISSUE TITLE
App/pop-up menu doesn't take up full screen width on smaller display sizes.

### ISSUE THREAD

**Issue by AndyL964** [8bitPit/Niagara-Issues#2032]
### Describe the bug

I'm not exactly sure if this is a bug, but the menu which covers up the full screen width on default display size no longer does so when switching to a smaller option.

### Steps to reproduce

1. Go to Settings > Display.
2. Change to smaller display size.

### Device name

OnePlus 8T+5G

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20220826-132829_Niagara Launcher](https://user-images.githubusercontent.com/22827982/186986510-9e316804-b454-4603-8cc6-9ba202fa9e93.png)
![Screenshot_20220826-132840_Niagara Launcher](https://user-images.githubusercontent.com/22827982/186986515-fd58aaba-1cbd-4f2c-a04f-019fb0b218b6.png)

**Comment by topsy-turvy99** [comment]
This is an intended behaviour, if you decrease your screen size (increase screen dp) it will add the padding to the menu card

With Normal Screen Size:
![Screenshot_2022-08-27-05-49-28-94_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/187006363-428fe157-909f-46c1-9d37-832df52c5d95.jpg)

With Lower Screen Size (High DP):
![Screenshot_2022-08-27-05-50-01-54_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/187006412-8b11eb90-6ee6-4b03-93f9-62c75cd1c05c.jpg)

**Comment by AndyL964** [comment]
That's what it may look like since it's the same for everybody, but I just thought it's intended to cover the full screen width to differentiate it from open pop-up folder (which has roughly the same amount of padding when decreasing display size).
![Screenshot_20220826-132826_Niagara Launcher](https://user-images.githubusercontent.com/22827982/187010084-23921656-bdfc-4ba6-b64f-1fce612b591a.png)
![Screenshot_20220826-132835_Niagara Launcher](https://user-images.githubusercontent.com/22827982/187010086-ad580bd1-7e43-4cee-b104-72f17c0f0a94.png)

**Comment by topsy-turvy99** [comment]
From what i understand the process is automatic, The padding is added mainly to align with the tablet (big screen) UI,

The padding even gets added when you use your phone in landscape mode (ig it makes sense to add the padding on higher dp)

**Comment by AndyL964** [comment]
Yeah, I guess it starts to make sense when you consider devices with tablets with bigger screens. At least it gets centered so that's good.
