### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#2034]
### Is your feature request related to a problem?

Is it possible to change the font size while leaving the size of the icons unchanged?

### Describe the solution you'd like

Is it possible to change the font size while leaving the size of the icons unchanged?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
Niagara Launcher doesn't have a font size slider in Niagara Settings #191,
but technically you can still change the font size as niagara follows the system font size.

Phone settings->Display-> Font Size
(the position may differ based on your OS)

**Comment by Livio78** [comment]
Thank you     Il lunedì 29 agosto 2022, 16:26:36 CEST, topsy-turvy99 ***@***.***> ha scritto:  
 
 


Niagara Launcher doesn't have a font size slider in Niagara Settings #191,
but technically you can still change the font size as niagara follows the system font size.

Phone settings->Display-> Font Size
(the position may differ based on your OS)
