### ISSUE TITLE
Notificação permanente 

### ISSUE THREAD

**Issue by Guilherme1084** [8bitPit/Niagara-Issues#2035]
### Describe the bug

Estou usando este aplicativo a muito tempo e gosto muito dele, porém alguns dias atrás, apareceu uma notificação dizendo "bem vindo ao niagara" pedindo para colocar o lançador como padrão, o problema em si, é que mesmo clicando e inserindo como padrão, a notificação persiste em ficar no meio da tela assim, não sendo possível colocar um widget.

### Steps to reproduce

1. Apenas clique na notificação e ela não sairá da sua tela.

### Device name

LG k51s

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_20220829-093544](https://user-images.githubusercontent.com/112400797/187207964-0208a4c1-4173-4fe1-8846-8b743912ef8e.png)

**Comment by topsy-turvy99** [comment]
Only the set to default flash bothers you right even when the Launcher is set to Default?

**Comment by Guilherme1084** [comment]
Desculpe pela demora, após o uso do comando a mensagem desapareceu, muito obrigado continuarei usando o aplicativo ♥️
