### ISSUE TITLE
Niagara Button to launch most used app 

### ISSUE THREAD

**Issue by pwd-github** [8bitPit/Niagara-Issues#2037]
### Is your feature request related to a problem?

Niagara feels like the first modern launcher that's actually designed for phones we've had in a while, but the one thing missing is the ability for the Niagara button to launch the most used app, forcing me to use two hands despite having the button in perfect reach. 

### Describe the solution you'd like

The perfect solution is for the Niagara button to be able to launch the most used app dynamically. I know we can set an app, but this seems like such a no-brainer. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by AndyL964** [comment]
It would be hard to tell which one it'll launch since only a few apps have their own icon when assigned to the Niagara button.

**Comment by Amorphous404** [comment]
Sorry, It will be problematic to implement to switch between multiple apps as @AndyL964 mentioned only few apps show/have their respective icons, so I suggest you to add a popup folder into the button and add all the most used apps into tat folder.
