### ISSUE TITLE
Anywhere launcher 

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2040]
### Is your feature request related to a problem?

At the moment every launcher forces you to go back to a homescreen and then pick an app to open which is okay but a friction creating experience...adding steps to pick your next app

### Describe the solution you'd like

Rather than having to go back to the home screen and then using the alphabet to search for an app a gesture system say a swipe up on the edge of the screen could bring up the alphabet and you can go to a new app regardless what screen your on or what app is open.

I think this works really well Niagara goals of simplicity as it creates a friction less experience jumping from app to app. The scroll mechanism in Niagara is so good that swiping up (or another gesture) and then swiping down on an alphabet is very quick and seamless way to move between apps

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
This can be achieved by using the "Display over other apps" permission, by providing a mini bar (a small section on the edge of the screen left or right) on the edge of the screen to trigger the app list, but i feel it will cause some stability issue or hinder the performance (just my thought)

Another neat option which i personally prefer is the "device default digital assistant method"

Allow users to set "Niagara Search" as the default device assistant app, which will allow users to trigger the Niagara search from any app

Android allows two ways to trigger digital assistant afik via Long press power button and by
swiping from the button edge of the screen.

Example: Kiss launcher search set as device default digital assistant app

![HiShoot_20220902_231147.png](https://user-images.githubusercontent.com/96917972/188211103-e296a8d6-e44e-4e67-bdee-d988cdfc6572.png)

**Comment by Lorestan00** [comment]
Both great ideas. How do you invoke the digital assistant with  Google swipe gestures on?

**Comment by topsy-turvy99** [comment]
I didn't get the question correctly 😅

But yes, you have to give up Google assistant app, if you switch to any other assistant app i.e Niagara Search.

Invoke device assistant the way your system allows it,

swiping for the edge/long press home button for button navigation and long press power button are the traditional way to call the assistant app

**Example: Invoking the assistant app via button edge swip gesture (gesture navigation)**

https://user-images.githubusercontent.com/96917972/188278414-a140f78e-d9f3-46bd-8906-da0d75d419d8.mp4

I hope i answered your question

**Comment by Lorestan00** [comment]
How did you set Niagara search?

**Comment by topsy-turvy99** [comment]
That's Kiss Launcher search

**Comment by notepadnine** [comment]
feels way too complex,

**Comment by 8bitPit** [comment]
Hi @Lorestan00, thank you for your suggestion. We decided to not implemented this feature, see issue #1381: 
> Gotcha, thanks for clarifying. Because our launcher doesn't heavily focus on keyboard-based search, I'd say the feature is not completely matching Niagara's design.

**Comment by Lorestan00** [comment]
Thanks for the response. I wasn't looking for a text based search but a swipe from the left or right sides when in any app and the homescreen alphabet appears and you can use it just as you do on the homescreen to navigate to the the app. Essentially means you need to go to the homescreen less often and it saves you a swipe / button press back home and creates a more friction free experience hopping from one app to another.

**Comment by 8bitPit** [comment]
Oh, I see; sorry that I misunderstood your request. The 10 most used apps are responsible for more than 90% of all app use for most users ([Source](https://arxiv.org/ftp/arxiv/papers/1106/1106.5100.pdf)). That's why it's most of the time more helpful to show the favorites screen first, and direct access to the alphabet wouldn't speed up the launch process in most cases. ,  displaying over other apps is [discouraged](https://www.xda-developers.com/android-q-system-alert-window-deprecate-bubbles/) by Google.

**Comment by Lorestan00** [comment]
That's fair point
