### ISSUE TITLE
Support ability to schedule notification summaries

### ISSUE THREAD

**Issue by akp-j** [8bitPit/Niagara-Issues#2042]
### Is your feature request related to a problem?

The "Notification Summary" is a great feature to help with Digital Wellbeing, but at the moment it is slightly limited. From when you turn the feature on, you get a summary every ~6 hours. This can be improved by allowing the users to customize when they'd like to receive the notification summary. This would be important for a few reasons:

- The current "every 6 hours" means you sometimes have to deal with a notification summary when you don't want to. For example, I'd almost always get a notification summary every morning after I wake up (something I'd rather not get). Users might also not want to get a notification summary at specific times during the day - for example when they're working. There are times during the day when you're more likely (or willing) to act on a notification summary -- for example during lunch, commute etc. and I think it'd be useful to have that control over when you get the summary.

- A 6 hour gap between the summaries can be too long for some people. For example I might want to include a communications app like WhatsApp/Email to the notification summary, but I'd be more comfortable with a 3 hour gap (or a different duration) if I'm actively involved in a conversation or if I'm expecting an email. Effectively, being able to control when I get the summary would reduce the feeling of missing out on something important and would keep me from actively opening an app to check if there's something new. 

This is in line with [what Apple does with their "Scheduled Summary](https://www.androidpolice.com/apple-ios-scheduled-summary-best-feature-google-android-should-steal/)" feature (which lets you choose up to 12 slots for the summary) or what the [Daywise](https://getdaywise.com/) app for Android does. 

### Describe the solution you'd like

The solution can take shape in one of a few ways:

1. Let the user select when they'd like to get a notification summary (the number of times one can request this can be restricted, but ideally this should go up to 12)
2. Or: let the user select the duration between two successive notification summaries (instead of the current default: ~6)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Please refer #1651
