### ISSUE TITLE
Wetter App per Shortcut

### ISSUE THREAD

**Issue by TitusSchroeder** [8bitPit/Niagara-Issues#2043]
### Is your feature request related to a problem?

Jedes Mal, wenn ich eine Wetterapp öffnen möchte (mehr Informationen als Temperatur der jeweiligen Stunde), muss ich bis "W" navigieren, oder müsste die App zu den Favoriten hinzufügen und somit wertvollen Platz verschwenden.

### Describe the solution you'd like

Mein Vorschlag, wäre, dass man bei der Wetteransicht nach Stunde(Niagara Pro) mit einem einfachen Klick auf das Wetterfeld eine selbst auswählbare App starten könnte z.B. WeatherPro.
![Screenshot_20220903-213246_Niagara Launcher](https://user-images.githubusercontent.com/112787620/188293561-114acd59-1661-426b-a2b6-6c960654519a.jpg)

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
If you have the OpenWeather App
[https://play.google.com/store/apps/details?id=uk.co.openweather](), installed you can directly open the weather app by long tapping on the weather card

**Comment by Amorphous404** [comment]
- Merged with #407
