### ISSUE TITLE
Make the app list appear faded when a pop-up folder is open over it.

### ISSUE THREAD

**Issue by thealiensurfer** [8bitPit/Niagara-Issues#2046]
### Is your feature request related to a problem?

Currently, when I use a dark wallpaper, the folder blends into the app list and it's tough to figure out where the pop-up folder starts (attached screenshot). 

![screenshot](https://user-images.githubusercontent.com/5128422/189007285-16a87af3-0e7e-44de-ab6d-89d67ecd9f28.jpeg)

### Describe the solution you'd like

It would be great if:

1. The app list in the background shows as faded so the popup folder is clearly distinguishable from the app list.
OR
2. We have a way to customize the colour of the popup folders.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Disable Pitch black mode (Niagara Settings>Look>Dark Theme>Pitch-black theme)

with normal dark theme you won't face blending issues, also popups automatically adapts color from your wallpaper or the one you set in your system settings (A12+)
https://help.niagaralauncher.app/article/133-color-system
