### ISSUE TITLE
Weeknumber in calendar widget

### ISSUE THREAD

**Issue by chosig** [8bitPit/Niagara-Issues#2048]
### Is your feature request related to a problem?

No, I just want to be able to see the weeknumber.

Option to show the weeknumber in the calendar widget.

### Describe the solution you'd like

A checkbox to show weeknumber

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Sorry, we don't find it Impactful (It is either appealing for many or necessary for some) enough, so we won't be adding the option.
