### ISSUE TITLE
Music Progress Bar on Swipe

### ISSUE THREAD

**Issue by the753q** [8bitPit/Niagara-Issues#2049]
### Is your feature request related to a problem?

You swipe Right for quick shortcuts on all apps. Why not use Right swipe on music player to popup some progress bar? 

### Describe the solution you'd like

Upon right swipe, popup with slider would appear:
![ffg](https://user-images.githubusercontent.com/50169298/189233312-a681cd12-a3d4-4a2b-bf7a-d509a2189d44.jpg)
Maybe thicker, or with additional controls like repeat etc..

Left swipe would still remain music player close action.

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
#973

**Comment by 8bitPit** [comment]
Merged with #973
