### ISSUE TITLE
Swipe for notifications/options stopped working

### ISSUE THREAD

**Issue by textortexxel** [8bitPit/Niagara-Issues#205]
I can't swipe right on, say, Gmail and see the list of accounts, like I used to. Same with other apps . It registers as a simple touch at most.  This has happened after the update that brought recents. Maybe it has something to do with vertical scroll?

**Comment by textortexxel** [comment]
Seems to have fixed itself.

**Comment by 8bitPit** [comment]
Hm... so it fixed itself after a day or so?

**Comment by textortexxel** [comment]
@8bitPit that's still an update or two I guess, but yes, seems like it. Sorry for distraction. Could you close the issue?

**Comment by 8bitPit** [comment]
@textortexxel np, you don't have to excuse yourself :)
