### ISSUE TITLE
Problem with Niagara Pro version

### ISSUE THREAD

**Issue by EvilEmpire23** [8bitPit/Niagara-Issues#2051]
### Describe the bug

My free trial for Pro version ended on 8 Sept and I still have access to all Pro version settings/benefits. I don't know it was supposed to happened and I think it happened due to latest update.

### Steps to reproduce

Can't describe steps for this issue

### Device name

Samsung Galaxy M52 5G

### Android version

Android 11

**Comment by Amorphous404** [comment]
Hey @EvilEmpire23 thanks for reporting :), any update on this, or you still have access to pro?

**Comment by EvilEmpire23** [comment]
I think the bug was fixed and my bugged free trial version was removed. Since then I have purchased the Pro version.

**Comment by Amorphous404** [comment]
Thanks for reporting :)
