### ISSUE TITLE
The purchase interface cannot be called

### ISSUE THREAD

**Issue by xysztm** [8bitPit/Niagara-Issues#2053]
### Describe the bug

I got an error massage clicking “upgrade to pro”. 
I can make both in-app and Play store purchases for other apps (I just tested AccuBattery, CPU-Z, & MEGA).
I give Niagara all permits and try to purchase using another device but it still only shows "error".

### Steps to reproduce

1.Go to "Niagara Pro"
2.Click "Upgrade to Pro"
3.Show a massage "error" with nothing more
![S20911-17181018](https://user-images.githubusercontent.com/34204848/189531450-fb639267-180c-43b9-ac59-59be1c648a23.png)

### Device name

Meizu 18 & Oneplus 7 Pro

### Android version

Android 11

### Screenshots / Screen recordings

Here are other apps' purchase interfaces and my purchased list.
Monthly:
![S20911-21493188](https://user-images.githubusercontent.com/34204848/189531812-0c7336b2-a5f5-4c90-b875-64e291dd70a3.png)
Lifetime:
![S20911-17264838](https://user-images.githubusercontent.com/34204848/189531826-3f7157e6-381d-4761-8211-7423d8188ce1.png)
CPU-Z Just in-app purchased:
![S20911-21510429](https://user-images.githubusercontent.com/34204848/189531847-aa73191a-7a36-45c5-8cf6-205612d6bc57.png)

**Comment by xiaogangrixiaoxia** [comment]
老哥你是不是把play商店给乖巧了？检查一下，这个一般是play商店的问题

**Comment by connercms** [comment]
Not sure if this is the same issue but I also can't complete a purchase, I get the following error 
![Screenshot_20220920_183341_Google Play Store](https://user-images.githubusercontent.com/12799522/191383345-d9d5b051-6338-4d93-a4fe-898d0438395b.jpg)

**Comment by Oddward** [comment]
Have you checked the help article [Purchase Help for Niagara Pro](https://help.niagaralauncher.app/article/10-purchase-help)? Do check your Google account settings in the store just in case there are any notable issues

**Comment by Amorphous404** [comment]
Hey @xysztm can you update to this latest build and check if you can reproduce this issue?

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6

Also with v1.8.0+ you can purchase Niagara Pro without Google Play Store 
https://medium.com/niagara-launcher/going-global-6bb58c2d6bb7
