### ISSUE TITLE
New pop-up/folders offer 'smart' options like "recently installed" as a dynamic folder. 

### ISSUE THREAD

**Issue by itsdrinkingthewater** [8bitPit/Niagara-Issues#2056]
### Is your feature request related to a problem?

Im having to install a separate app for this, which does not obey the aesthetic of Niagara.

Since Niagara already has usage permissions, this one should be an easy dev addition.

Thanks 

### Describe the solution you'd like

An option set (like nova does for their app drawer search) for smart categories like "Most Used", "Recently Installed".

Im having to install a separate app for this, which does not obey the aesthetic of Niagara.

Since Niagara already has usage permissions, this one should be an easy dev addition.

Thanks 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Lorestan00** [comment]
They already have recently installed folder.. But it appears below z in the list. Really there just needs to be an option to move it up to below favourites or perhaps even above

Like you would welcome 'most used' as well.

**Comment by Amorphous404** [comment]
It appears that your request bears a resemblance to an issue that has already been raised #1833. In order to avoid redundancy and promote a thorough discussion of the feature, coul you please forward the discussion suggestion in that particular thread?

Thank you.

🔗 Merged with #1833
