### ISSUE TITLE
Icon assistant keeps prompting that "x icons missing" even if the custom set icons are already cached

### ISSUE THREAD

**Issue by DanyGee** [8bitPit/Niagara-Issues#2061]
### Describe the bug

Once you manually set up your missing icons in a pack, change the pack to a different one (for example Niagara Dots) and then revert to the last pack, although the manually set icons are already cached and applied, the icon assistant prompts that "X icons missing" prior to pack switch.

### Steps to reproduce

1. Niagara Settings > Look > Icon Pack > select a pack with missing icons and apply them manually.
2. Switch to Niagara Dots Icon Pack.
3. Switch back to the pack where you applied missing icons manually.
4. Observe the Icon Assistant prompt - "X missing Icons".
5. Observe that icons are actually not missing.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Samsung Galaxy S21 FE (Exynos onboard)

### Android version

Android 12

**Comment by Oddward** [comment]
The "X missing icons" refers to icons missing from the applied icon pack for your installed apps. Manually adding other icons does not complete the original icon pack itself
