### ISSUE TITLE
Disable icons

### ISSUE THREAD

**Issue by bastschonet** [8bitPit/Niagara-Issues#2062]
### Is your feature request related to a problem?

I want to request the option to disable icons completely.
Reason: less distraction, less temptations

I experienced this with the "blank icon pack", but the left alignment is not good looking with this icon pack. 

### Describe the solution you'd like

Option to set "no icons" in the "look/icon pack" settings.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
There's no plan to support this natively - see issue #140 - you'd have to use the blank icon packs or edit them with Icon Pack Studio for e.g.
