### ISSUE TITLE
Auto Work Folder and Play store link to apps

### ISSUE THREAD

**Issue by rgv890** [8bitPit/Niagara-Issues#2063]
### Is your feature request related to a problem?

I have two feature requests and they're not related to any problems.

### Describe the solution you'd like

1. ) First one is like when you create work profile a folder should automatically be created having work apps in it just like some other launchers have functionality to separate work apps by automatically creating a different tab name Work. This will be very useful if can added. 
2.) Secondly if the popup of apps can also have an option to directly take users to its play store page then it'd be very helpful. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Please keep each issue focused on a single topic so it's easier to track and mark as mentioned in the Feature request article linked with that checkbox 

I don't know about other OEMs atm but Samsung has a link to each app's store page in the system app settings (accessible on Niagara via long-press > App info).

There is some older suggestions around work profiles like #1850 , maybe you can follow up there and add your suggestion

**Comment by topsy-turvy99** [comment]
![IMG_20220929_233240.jpg](https://user-images.githubusercontent.com/96917972/193109363-78edf999-22ed-4fcf-91ce-2e2bd8f6eb89.jpg)

The only thing that's missing from the long press app menu is the link to playstore page, would definitely be a great addition if it gets included, my stock rom doesn'thave the playstore link in the app info page
