### ISSUE TITLE
Extra large icon size for seniors

### ISSUE THREAD

**Issue by PaulReiber** [8bitPit/Niagara-Issues#2066]
### Is your feature request related to a problem?

Niagara Launcher does not accommodate the elderly.

### Describe the solution you'd like

The largest icon size that is available today is too small for seniors with poor eye sight and/or motor control issues.

The font sizes for various parts of the interface are far too small for seniors as well. 

Given its clean and simple design, Niagara Launcher can become the go-to launcher for seniors if these concerns are addressed. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
I think for extreme accessibility needs the system itself should already have features to accommodate for them like scaling the entire screen resolution so everything is bigger. E.g. on Samsung it's in Settings > Accessibility > Visibility enhancements. Is it not enough with those settings applied?

The trigger zones for most things are very generous on Niagara; buttons are big with plenty of padding and full width to make it easy to interact with without the need to hold the device so firmly for e.g.

**Comment by Amorphous404** [comment]
![Screenshot_2022-12-14-18-16-22-29_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/207599253-08b13338-690d-40e2-acfa-8bfb39b9a032.jpg)

Increase the display size in the phone setting, same for the fronts like Oddward suggested.

Additionally, dev is considering adding a native font slider (low priority), if it' often gets requested by users.

**Comment by Amorphous404** [comment]
Hi @PaulReiber, Happy to let you know that with v1.9.2, you can increase the size of your app icons even further, as well as independently adjust/increase the font size of the Niagara launcher, with the following [secret command](https://help.niagaralauncher.app/article/74-secret-commands):  [/scalefont](https://niagaralauncher.app/app-link/secret-command?cmd=scalefont)

[Niagara Launcher v1.9.2](https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.9.2)
