### ISSUE TITLE
option to disable "want to make me your default launcher" message

### ISSUE THREAD

**Issue by kurokirasama** [8bitPit/Niagara-Issues#2068]
### Is your feature request related to a problem?

I use the launcher trough autotools and tasker. Tasker changes via autotools the current launcher according to specified conditions.
The problem is that sometimes, nagara doesn't recognize it is the default launcher (it's ok since technically it isn't, autotools is), but this message appear using quite some space.

### Describe the solution you'd like

Just an option to disable or not show the message

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
The launcher supports hiding the message for these use cases by enterting the secret command `/suppress set launcher prompt` in Niagara search - see the help article: [Niagara launcher not staying as default](https://help.niagaralauncher.app/article/102-niagara-launcher-not-staying-as-default#:~:text=How%20to%20ignore-,the,-%22Set%20as%20default)

**Comment by kurokirasama** [comment]
Cool! Thanks!

**Comment by Amorphous404** [comment]
- Duplicate of #949
