### ISSUE TITLE
tasker integration

### ISSUE THREAD

**Issue by kurokirasama** [8bitPit/Niagara-Issues#2069]
### Is your feature request related to a problem?

nop

### Describe the solution you'd like

Please allow some tasker integration. Particularly, the ability to show on the widget the content of selected tasker variables.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Oddward** [comment]
Please follow this old issue #786 on it, I'll close this one as a duplicate
