### ISSUE TITLE
[Request] Add Alarm / Sound mode on home

### ISSUE THREAD

**Issue by billouetaudrey** [8bitPit/Niagara-Issues#207]
Hey,

Is it possible to see the alarm ( next alarm ) below the clock for example ? 

And why not the sounds mode ( DND, vibrator , silent ) too ?

Thanks

**Comment by 8bitPit** [comment]
`Is it possible to see the alarm ( next alarm ) below the clock for example?`
See _#4.

`And why not the sounds mode ( DND, vibrator , silent ) too ?`
Those icons are already visible in the status bar, so I would not add them. If you want to comment on that, please write in #4.
