### ISSUE TITLE
Few icons don't change in Dark Mode 

### ISSUE THREAD

**Issue by jeffconrad18** [8bitPit/Niagara-Issues#2070]
### Describe the bug

When I turn on the dark mode, not all of the icons change, just a few to the black design. Then when switching off it is the same and some icons remain black. I use the app Material You Dynamic Icon pack.

### Steps to reproduce

Set Material You Dynamic icon pack as icon pack.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Lawnchair

### Device name

Google Pixel 6a

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_20220925-222546](https://user-images.githubusercontent.com/78684384/192163715-c8dfc552-cb5d-4cc5-8955-c66a75afdfc7.png)

**Comment by 8bitPit** [comment]
Are you using [this](https://play.google.com/store/apps/details?id=com.akbon.myd) icon pack? If so, this bug should be gone within the next 24h hours; see [our Discord](https://discord.com/channels/728630549278883950/728630867777290300/1024648159034621982):
> Thanks for the report! Because there is no standardized API for us to know which icon packs are dynamic and take use of Material You, we're keeping a list of all those icon packs. I added this one and another dynamic icon pack from the same dev to our list; it takes up to 24h for the changes to propagate. Afterwards, the icon colors should change automatically.

**Comment by jeffconrad18** [comment]
@8bitPit 
Thanks it works!

**Comment by 8bitPit** [comment]
Great; thanks for letting me know! I'll close this ticket then.
