### ISSUE TITLE
Favourites based on time of day

### ISSUE THREAD

**Issue by pastapete83** [8bitPit/Niagara-Issues#2071]
### Is your feature request related to a problem?

There are some apps that I want to be pinned to favourites, but I only use them at certain times of day.  They don't need to be cluttering my home screen all the time.

### Describe the solution you'd like

In the same way that music apps appear when a certain condition is met (connected to speaker or headphones), could you make it so some apps appear when a time condition is met?

Eg there are some apps I only use in the morning. To have them appear as a favourite between 6-9 am or something.

I feel that it would fit with Niagara's minimalist feel, as it reduces clutter by only having apps appear when they are needed.  It would fit with all 4 of Niagara's design principles.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by the753q** [comment]
Seems like what we need is a rework/or fork of the "Most used" function. So that it automatically gives you most used apps but based on time.
Simpler and no need to manually set up...

Or maybe instead it could be better to have "profiles", and they activate based on time.
Each profile would contain: own favorite apps, specific wallpaper, widgets...

_but basically i just cant imagine setting up apps to auto appear at certain time like in some Alarm or Calendar app interface. Too much work and list gets cluttered easily_

**Comment by pastapete83** [comment]
Hey, thanks for the reply and for considering my suggestion.

I don't use the "most used" function - I find that I prefer fewer apps on
the screen, and it introduces more clutter than I want!

But the idea of profiles would be absolutely amazing - I'm always amazed
more launchers don't do this.

Anyway, I hope you decide to go down that route, but even if you don't,
thanks for a great app.

Pete


 --

Pete Killingley

07541 676363

Personal: ***@***.***

Church: ***@***.***

**Comment by topsy-turvy99** [comment]
> Seems like what we need is a rework/or fork of the "Most used" function. So that it automatically gives you most used apps but based on time.
> Simpler and no need to manually set up...
> 
> Or maybe instead it could be better to have "profiles", and they activate based on time.
> Each profile would contain: own favorite apps, specific wallpaper, widgets...
> 
> _For original idea: I just cant imagine setting up apps to appear at certain time through some Alarm or Calendar app-like interface.
> Too much work and list gets cluttered easily_

A similar request has already been proposed on #786 that helps switch between different favorite apps automatically with the help of automated apps like tasker etc

I have an idea that I'll like to share idk if it's feasible, or you guys agree to it
when i used Nova Launcher i had the option to set any page as the main page by:  Long Tapping on the page>Default Page
(that will make any page as the main homescreen page)

A similar thing that can be done to help users (that don't use automated apps) switch between different profiles manually is by adding multiple favorite pages support (similar to pop-up folders) that can be switched with the help of Niagara Button

Steps: Long Tap On Niagara Button>Switch Favorite Page>Show the Option To Switch between Different Page

Favorites Page 1
Favorites Page 2
Favorites Page 3

Each Page contains their own:
1) Apps,
2) Widgets (if feasible)
3) Wallpaper (Not possible as Niagara doesn't have its own wallpaper implementation and uses a transparent layer that reflects the system wallpaper)

**Comment by Oddward** [comment]
@topsy-turvy99 I think that kind of defeats the purpose of the favourites page, to be your central hub for just the apps you mainly want to focus on, multiple pages isn't likely a direction Niagara will go, and managing multiple pages manually sounds like a bad time and not really fitting with the launcher's design. 

When we need a lot of extra configuration and pages etc to solve a small issue it usually means it's overly complex and we should start removing parts of that design until there's nothing that can be removed without removing the function entirely, i.e. trying to achieve simplicity

I believe Niagara supports work profiles and focus modes? Those are Android features which can be used to remove certain apps e.g. at work hours if I'm not mistaken and only leave selected apps

Another duplicate which is more identical to this is #1517 where Peter added his [response](https://github.com/8bitPit/Niagara-Issues/issues/1517#issuecomment-793001904) at the time. I'll close this one as a duplicate
