### ISSUE TITLE
Notification Preview does not work for WhatsApp and some other apps

### ISSUE THREAD

**Issue by hypghzy** [8bitPit/Niagara-Issues#2074]
### Describe the bug

This might be a system level issue.
In my OS, the "Notification dot" can and only can be enabled individually, app by app, but it still only works for some apps.
WhatsApp have the "Notification dot" enabled but no badge shows up while received some new messages.
However, I have disabled the “Notifiaction dot" for some other app that the "Notification preview" works correctly, and the preview still works even while the "Notification dot" was disabled.

### Steps to reproduce

1. back to the home of the launcher
2. scroll to WhatsApp
3. receive the new message
4. no visable preview
5. right slide the WhatsApp
6. able to see the new message and able to reply.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Nubia Red Magic 7S

### Android version

Android 12

**Comment by hypghzy** [comment]
I changed the notification level from urgent to hight/mid, then it all works.

**Comment by Oddward** [comment]
Thanks for the update. It's strange for an Android skin to work like that - the launcher certainly shouldn't be able to show a notification preview for an app if the Notification dot/icon badge is disabled...
