### ISSUE TITLE
Wallpaper zoom effect and unlock animation

### ISSUE THREAD

**Issue by Jhonycruz05** [8bitPit/Niagara-Issues#2075]
### Describe the bug

In my case, it is somewhat annoying that the wallpaper zooms in, something that happens with other launchers, but they have the option to disable this. Could you fix it with an update that can be disabled in the settings menu? And also the animation when entering the home screen when I unlock the phone is very rough, not smooth at all.

### Steps to reproduce

Just set the wallpaper and you will see the zoom effect, then lock and unlock the device and you will see the transition animation to home screen is abrupt

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova Launcher, Lawnchair.

### Device name

Redmi note 10s

### Android version

Android 12

### Screenshots / Screen recordings

`

**Comment by Oddward** [comment]
The wallpaper zoom is a system feature on MIUI, Niagara doesn't have any config for that, in fact it doesn't have a wallpaper layer so you're just seeing the system level background through Niagara.

And please keep issues to one topic for clearer tracking. 

The unlock animation seems to depend on users and system, and seems kinda random when it does happen as well. I can't tell if it's a system issue or the launcher's. Apparently it's ongoing in this old issue #1804 but is mostly reported on Samsung devices (mine as well), we can add to that issue with regards to the unlock animation, closing this as a duplicate
