### ISSUE TITLE
Is there a way to insert all 8 favorites along with a custom widget without reducing the favorites icons too much?

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#2077]
### Is your feature request related to a problem?

As recommended I insert 8 favorites, after I insert a notes widget under the clock and I was forced to reduce the size of the favorites icons to make them all in the screen. Is there a way to insert all 8 favorites along with a custom widget without reducing the favorites icons too much?

### Describe the solution you'd like

As recommended I insert 8 favorites, after I insert a notes widget under the clock and I was forced to reduce the size of the favorites icons to make them all in the screen. Is there a way to insert all 8 favorites along with a custom widget without reducing the favorites icons too much?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment]
Yes there should be option to move the home screen upwards.There is lot of space to reuse

**Comment by Amorphous404** [comment]
Long tap on the widget>Move widget, reposition the widgets to top
