### ISSUE TITLE
Reclaim space above clock

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2082]
### Is your feature request related to a problem?

When we hide status bar(pro feature), It just hide the status bar
**I am curious if the complete setup(Homescreen)  shift upward to give me additional space created by hiding status bar**
![image](https://user-images.githubusercontent.com/5180486/194802981-831b5f24-ff12-4dac-8642-211d41006d56.png)

Its too much space above clock. If anyhow I can mange it to move upwards then benefit

- I can have my big KWGT or whatever widget like agenda and 8 icons on mobile like s21
- I can easily do swipe up to search
- Will look more consistent because now the space below and above will be same

### Describe the solution you'd like

Autoshift scree upwards when hiding status bar, Or better give a slider to adjust screen space above clock.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by the753q** [comment]
You can literally do that right now, by long tapping Calendar /weather widget, tapping on move widget
(I do not work at niagara)

**Comment by Amorphous404** [comment]
Please don't create multiple tickets for the same.

Duplicate of #2123

**Comment by notepadnine** [comment]
Is it completed?

**Comment by Amorphous404** [comment]
You created two tickets for the same issue, so i closed this and kept the other one open 💀
