### ISSUE TITLE
Pop ups need little makeover

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2083]
### Is your feature request related to a problem?

It has always been the criminology of Apple to make pop up with at least no information. Android win over that. Its pops and notification have more information.

As my concern pop in niagra is way too padded. May be this can be objective issue. But it seems to me.Look this picture
![image](https://user-images.githubusercontent.com/5180486/194803569-195adae0-5d90-430c-978e-9934f24dcb48.png)

I think they need few modification

1. Space vs information must be good. Too much white space and too little information. This impact when we see 2 or more notification in pop up
2: If anyhow they have glass or transparent effect, they will look less blunt. More beautiful
3. I am not very sure on this, but round corner are way too soft than android operating system round corner.

**This gonna be a big task**
4. Convert the pop to slide box which appear just below clicked icon. and shift the below icon after pop up height. I am not designer. But i think it must be something like android 12 widget picker. 
https://youtu.be/xDo1vd60ynA?t=63

### Describe the solution you'd like

https://youtu.be/xDo1vd60ynA?t=63

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Thank you for your suggestions, At present, we have no intentions to alter or revise our existing design layout. However, if we do decide to make changes in the future, we will revisit this discussion. For now, I will close this ticket to allow us to prioritize our attention to the other issues.
