### ISSUE TITLE
Sort Folders by Most Used

### ISSUE THREAD

**Issue by Abel2Disable** [8bitPit/Niagara-Issues#2086]
### Is your feature request related to a problem?

I have alot if apps in my Shopping folder and my TV folder. Some apps I use daily, others rarely, and some occasionally. It'd make apps easier and quicker to find if the most used were moved to the top of each folder. 

### Describe the solution you'd like

Sort Folders in my app list by most used. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Hi @Abel2Disable, thanks for the request. While we're not planning to automatically sort apps in folders by usage, you can quickly sort them by usage manually by editing the folder pop-up and tapping on "sort apps by usage".
