### ISSUE TITLE
Swipe left or right in Home Screen

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2089]
### Describe the bug

Addroid is allowing me to open last used app in swipe and hold. Whenever I try to do this in Niagra Home screen. It is scrolling thorugh apps.  I have other option for gesture too like. Swipe edge UP to some other function and similarly Swipe down edge. 

Please help me to disable alphabet rail or ACTIVATE it only by swiping left or right on Niagra button(Bottom right) or somewhere else. 

This slide to see all apps is killing smooth experience on Default Android System

### Steps to reproduce

Have some swipe gesture like 

- swipe up right edge
- swipe down right edge
- swipe from right edge
- swipe from left edge

It will see you list of all app, not the action.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

S21

### Android version

Android 12

**Comment by Amorphous404** [comment]
![Screenshot_2022-12-15-13-34-27-07_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/96917972/207805744-12516d4a-19ce-480b-a72b-32a9387eaff0.jpg)
https://help.niagaralauncher.app/article/77-missing-customization-features

**Comment by notepadnine** [comment]
its all not about customized gesture. Its about scrolling drawer is preventing some gesture app. For this can it be turned off or limit hit area

**Comment by Amorphous404** [comment]
The two gestures can't work together, for your system gesture to work in Niagara homescreen, the team will need to add an option to disable side alphabets, which isn't impactful enough.

![Screenshot_2022-12-15-15-25-08-23_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/96917972/207829828-cc7c19b2-3517-4e14-bf20-85a55ba92e22.jpg)
https://help.niagaralauncher.app/article/39-left-hand-mode

**Comment by Amorphous404** [comment]
https://user-images.githubusercontent.com/96917972/207845045-76de25cb-ca90-4535-9de6-7ec2449f5608.mp4


Maybe your device/OS is blocking the edge gesture on a third party launcher, i just tried to activate some system apps and third party apps using the side gesture, i was able to call it without any issues.

**Comment by Amorphous404** [comment]
It seems you are creating duplicates (#1661 #1743)  for the same issue with different titles, i suggest you post your comment on the existing ticket instead of creating a new one.

Also about disabling the side scrollbar the dev is clear, he won't be adding an option/toggle as it goes against the design principles which you're already aware of

https://github.com/8bitPit/Niagara-Issues/issues/1661#issuecomment-889969182

**Comment by Amorphous404** [comment]
🔗 Merged with #865
