### ISSUE TITLE
Music Player Integration

### ISSUE THREAD

**Issue by ghoshriju33** [8bitPit/Niagara-Issues#209]
I use Musicolet player as my default music Player. The launcher isnt showing the music widget at all while playing music.

**Comment by 8bitPit** [comment]
Did you enable notification dots? That is required for showing the media player.

**Comment by Scorpionk1** [comment]
I downloaded the app just to test. The commands are okay.

**Comment by ghoshriju33** [comment]
I did enable the notification access the first time I installed the app. And moreover the launcher shows app notifications only a few times. Even though an app sends notification, the launcher most of the times fail to detect the notification

**Comment by ghoshriju33** [comment]
Update: Disabling and enabling the notification dots again worked like a charm.
