### ISSUE TITLE
Remove letter dividers from app list

### ISSUE THREAD

**Issue by emiham** [8bitPit/Niagara-Issues#2090]
### Describe the solution you'd like

This was previously touched on in  #1509, but I'd like to reopen discussion, as well as suggest outright changing the design rather than adding a toggle option, and to make a stronger case for doing so. 

Niagara currently displays a single letter to divide the app list into sections by their initial letter. I'm curious about the rationalization of dividing it this way. I can see why you would instinctively want to section a list that is usually pretty long, but since you scroll using the alphabet you're going to be looking at a much smaller subset of the list by the time you're even looking at app names. 

If it's there to provide visual clarity when using the alphabet to scroll, I would argue that seeing the current letter both by the alphabet and in the app names themselves is enough, but if not I would propose showing the letter when you are scrolling, and hide it when you let go and Niagara shows the rest of the apps that start with different letters. 

As for the reason to remove the letters: even in the best case they add a degree of unnecessary (going by the above explanation) clutter, and in the worst case they take up half the app list, the worst case being illustrated below. 

```
A
🍎 Apple

B
🍌 Banana

C
🥥 Coconut
```

I often find myself having to hide apps that are alone in their section, but then being frustrated that they're not where they're supposed to be. On smaller screens the impact of this is even worse. 

I'm only really bringing this up because Niagara is a beacon of good, well thought out design in a field that's saturated with a lot of junk. This is probably the only thing about the app that I don't understand the reasoning for. So as a last statement: thanks for a great app, I've been subscribed since February 2020.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Since you're already aware that there is an exciting ticket for the same feature #1509, instead of creating a duplicate, I kindly request you to add your valuable feedback there and request to open up the previous ticket :)

**Comment by Amorphous404** [comment]
Duplicate of #808
