### ISSUE TITLE
Independent font size setting

### ISSUE THREAD

**Issue by Finnitio** [8bitPit/Niagara-Issues#2094]
### Is your feature request related to a problem?

I use a small system font in Android. Therefore the font size in the launcher ist small. This ist too small for me to quickly select any item.

### Describe the solution you'd like

A setting for the Font size would bei nice, preferrebly only for the start screen and drawer not the popups.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment]
I also want a capability to select font for notification tet under icons

**Comment by Amorphous404** [comment]
Dev might consider adding an independent font slider for Niagara launcher in future, 

https://github.com/8bitPit/Niagara-Issues/issues/191#issuecomment-770224010

**Comment by 8bitPit** [comment]
There's now a [secret command](https://help.niagaralauncher.app/article/74-secret-commands) to independently set the font scale: [/scale-font](https://niagaralauncher.app/app-link/secret-command?cmd=scale-font)

**Comment by Finnitio** [comment]
Thanks, where ist the terminal in Niagara Launcher?

**Comment by Amorphous404** [comment]
Tap on the command above or type it in Niagara search and hit enter.

**Comment by 8bitPit** [comment]
Implemented through secret command, closing
