### ISSUE TITLE
Swiping Homescreen gesture from App drawer goes back to App drawer. 

### ISSUE THREAD

**Issue by Finnitio** [8bitPit/Niagara-Issues#2095]
### Describe the bug

When I open the App drawer And swipe the Homescreen (Button) gesture the Homescreen does not open instead ist goes back to the Appdrawer

### Steps to reproduce

1. Open App drawer, click on any letter from the alphabet.
2. Swipe Home Screen gesture.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Poco M4 Pro

### Android version

Android 12

**Comment by WhitespaceQ** [comment]
Weird, I have that device and Niagara is working correctly with third party full-screen. Fwiw I'm using Edge Gestures (it's on Play Store) and every penny is worth it.

**Comment by notepadnine** [comment]
Edge gesture(Default with few devices) is not working in home screen

**Comment by Amorphous404** [comment]
Fixed 

Can you try out the latest build and check if you can reproduce the issue.

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6
