### ISSUE TITLE
Notification Center

### ISSUE THREAD

**Issue by ChriGa13** [8bitPit/Niagara-Issues#2096]
### Is your feature request related to a problem?

I'm always stressed when I am getting too much notifications.

### Describe the solution you'd like

First of all, THANKS for developing such a great Launcher!

To my idea:
I've seen you're experimenting with notifications. Why not think about a"Notification Center" view or widget which acts like a real mailbox. 

You can mark the apps from which the notifications should fall into the mailbox. As long as the notifications are in this box or the "Notification Center", I am not disturbed by them and have less stress. Only when I actively decide to navigate to the Notification Center I see the notifications of the selected apps. So very much along the lines of a real mailbox. This could lead significantly to stress reduction and also to get more focus. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by the753q** [comment]
*i dont work@niagara*
I feel like that's a useless extra step. If you have too many notifications, just turn off for unused apps, or set most of them as silent. That way you only see them if you open notification panel.

Having them also in the launcher would be for no reason

**Comment by notepadnine** [comment]
I think is development cost will be too much. Also android notification is serving same purpose. You can change priority of each notification. It is like adding more weight to lightweight launcher.

One way to achieve this:
- Buy pro license
- Create folder 
- Add all your required app in that folder
- Now you can check this folder and ll notification in its pop up

* Correct if I am wrong

**Comment by Amorphous404** [comment]
https://help.niagaralauncher.app/article/122-notification-summary#:~:text=Go%20to%20Niagara%20Launcher's%20settings,matter%20what%20app%20sent%20it.
