### ISSUE TITLE
Gradient at top of launcher 

### ISSUE THREAD

**Issue by pieman2201** [8bitPit/Niagara-Issues#2097]
### Describe the bug

Don't know if this is intended or not, but there's a weird gradient at the top of my home screen that's visible whenever switching apps. I can't find anything saying that this should be there, and I don't see any way to disable/enable it. If it is intended behavior, then my opinion is there ought to be a way to disable it.

### Steps to reproduce

use launcher, try to switch to an app

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova

### Device name

Asus Zenfone 8 

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20221028-121909951~2](https://user-images.githubusercontent.com/9773351/198696326-cdedf5fc-e801-4e8d-91d6-54905ae52502.jpg)

**Comment by tjsuominen** [comment]
Could that be some widget behaving / miss-resized badly?

**Comment by pieman2201** [comment]
No, I don't think so. The widget I currently have to replace the default clock is just the Google Search app widget, and it doesn't produce the same shadow on Nova Launcher.

**Comment by notepadnine** [comment]
It is really weired. Try posting video of resetting launcher and then showing this bug

**Comment by IJustWantANamePlease** [comment]
I have this thing as well, heck I thought this was work as intended😂

**Comment by Amorphous404** [comment]
Hey @pieman2201 can you still reproduce this bug on the latest build? If possible can you please send a screen recording?

**Comment by pieman2201** [comment]
Hi, yes. I'm on 1.8.6 and this still shows up: 

https://user-images.githubusercontent.com/9773351/208212498-acce7c14-ba31-4892-81ed-0e06e06d5c4c.mp4

**Comment by Amorphous404** [comment]
Can you please hide the status bar and check if the top shadow/gradient is visible?

Niagara settings>Look>Hide status bar

**Comment by pieman2201** [comment]
The gradient doesn't show up when status bar is hidden

**Comment by Amorphous404** [comment]
I can reproduce the issue on my device too

https://user-images.githubusercontent.com/96917972/208625628-be51504d-54b7-45d4-8256-c8294cdf3393.mp4


Not sure if it's intended in Niagara, other launchers like Nova & Lawnchair also add this gradient/shadow to add contrast to status bar icons but provide an option to disable it (the shadow is more noticeable on a 10 bit display)

**Comment by 8bitPit** [comment]
Thank you for all your input. Yes, the gradient is intended to improve the readability of the status bar icons. We, unfortunately, cannot fix that the gradient is also getting scaled when transitioning from the home screen to the recents screen. without disabling the gradient. To keep customization simple, we don't plan to add a toggle to turn the gradient off, I'm sorry.
