### ISSUE TITLE
Option to have home button to go back to favorite apps

### ISSUE THREAD

**Issue by DroidFreak32** [8bitPit/Niagara-Issues#21]
It would be nice if there is a switch in the settings to let users decide if going pressing the HOME button should go to the last state or to the favorites apps section.

**Comment by DroidFreak32** [comment]
by last state I mean, if I open telegram and then press home, it goes back to the launcher pointing at apps starting with "T". An option to make it go back to "Favorites" would be nice as I mostly use that.

**Comment by 8bitPit** [comment]
To my mind, it could be confusing, bc you often don’t remember where you have stopped scrolling.

**Comment by Chaphasilor** [comment]
@8bitPit yeah exactly, but this is the current implementation. If you opened an app from the drawer, it goes back to the drawer when you press home

**Comment by Maxr1998** [comment]
Yep, making home go to favorites would be nice.

**Comment by 8bitPit** [comment]
Ah... sorry, I missunderstood you. Originaly in an earlier version of the launcher I did that. Then I noticed every other launcher does it like you mentioned.

**Comment by DroidFreak32** [comment]
Some users prefer one over the other so just a simple switch in the settings would let users choose what they prefer. (Like in nova settings > app drawer > advanced > remember positions).

**Comment by 8bitPit** [comment]
I implemented it in a way that there should be no need for a toggle. Pressing the home button now brings you back to favorites. However, if you tap on it shortly after opening an app (so you probably tapped on the wrong app) Niagara won't reset the "home state".

**Comment by ShinobiWPS** [comment]
> I implemented it in a way that there should be no need for a toggle. Pressing the home button now brings you back to favorites. However, if you tap on it shortly after opening an app (so you probably tapped on the wrong app) Niagara won't reset the "home state".

Well done. Smart.

**Comment by 8bitPit** [comment]
@ShinobiWPS thanks :)
