### ISSUE TITLE
Work Profile Apps Not Showing

### ISSUE THREAD

**Issue by FCP0078** [8bitPit/Niagara-Issues#210]
I have a work profile on my phone and when using Niagara, none of my work apps are showing.
I was also wondering if it's possible to have the work apps to be somehow separated from personal apps. The Pixel launcher achieves this by having a second list of apps in the app drawer on a separate tab that is accessible when swiping left on the drawer.

**Comment by 8bitPit** [comment]
Thanks for suggesting, see #210

**Comment by 8bitPit** [comment]
Oof, I meant #93 XD
