### ISSUE TITLE
Using home-gesture does not toggle app search

### ISSUE THREAD

**Issue by swent** [8bitPit/Niagara-Issues#2101]
### Describe the bug

On previous phones, activating the swipe-up-to-search feature would lead to the app search being toggled when using the home-button/home-gesture. This worked as expected using gesture navigation on my previous oneplus 7 pro. I just switched to a pixel 7 pro, using the home-gesture there will not toggle the app search, it pretty much ruins the smooth operation of this beautiful launcher.
Very strangely changing the global system setting from gestures to buttons will successfully goggle the app search when pressing the home-button.

Please let me know if I can help test/debug this as I am interested in getting this solved.

### Steps to reproduce

1. Make sure swipe-up-to-search is active and enable system gesture navigation
2. Swipe up on homescreen (favourites list movement is animated but stays on favourites, similar to entering recent apps view)
3. Swipe up from the middle of favourites -> successfully activates app search
4. Wipe up on app search (search screen movement is animated but stays on search screen, similar to entering recent apps view)

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

Nova: unable to properly test since gestures on other launchers are usually a paid premium feature but swiping up on homescreen results in the same system animation as on niagara.

### Device name

Google Pixel 7 Pro

### Android version

Android 13

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/5727162/198888677-acbe23c6-b780-4387-8764-1389d0d9f794.mp4

**Comment by Amorphous404** [comment]
Fixed in v1.8.0

Can you please update to the latest version and check if it fixed the issue for you?
