### ISSUE TITLE
Grayscale icons, optional

### ISSUE THREAD

**Issue by ricardosalta** [8bitPit/Niagara-Issues#2102]
### Is your feature request related to a problem?

Colorful icons attract more usage of apps than needed

### Describe the solution you'd like

Grayscaling seems to be proven to help reduce the brain's tendency to click into apps without a need

https://www.wired.com/story/grayscale-ios-android-smartphone-addiction/

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Great thought, @ricardosalta. For now, I recommend using a grayscale icon pack like [Whicons](https://play.google.com/store/apps/details?id=com.whicons.iconpack) (free) or my personal favorite [Reev Pro](https://play.google.com/store/apps/details?id=com.reevpro.grabsterstudios) (paid). We're also working on our own icon pack, it will also be grayscale :)

**Comment by luxcalor** [comment]
Is there a way to use android monochrome icons as an icon pack? Most of the apps do have this style embedded already. 
![ws6td70j56pa1](https://github.com/8bitPit/Niagara-Issues/assets/76074147/f2e9757c-52e7-4e98-b27b-19af874af710)

**Comment by 8bitPit** [comment]
Happe to share our new Anycon packs also include grayscale options! Here's how you can apply them: Download [our latest beta](https://github.com/8bitPit/Niagara-Issues/releases) (or wait for the stable release on Google Play), go to the new Theme color picker (Niagara Settings > Look > Theme color) and choose gray, and finally, apply an Anycon pack (Niagara Settings > Look > Icon Pack) and set the style to 'Theme color'. Hope that helps!
