### ISSUE TITLE
Optionally hide app icons altogether

### ISSUE THREAD

**Issue by ricardosalta** [8bitPit/Niagara-Issues#2103]
### Is your feature request related to a problem?

Shiny icons support the compulsive opening of apps 

### Describe the solution you'd like

Option to hide icons altogether 

For example this launcher does it https://www.minimalistphone.com/

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
https://github.com/8bitPit/Niagara-Issues/issues/140#issuecomment-753679560

Duplicate of #140
