### ISSUE TITLE
Increase Number of suggested apps below favorites

### ISSUE THREAD

**Issue by Finnitio** [8bitPit/Niagara-Issues#2105]
### Is your feature request related to a problem?

I don't use favorites and completely rely on niagara suggestions, therfore it would be nice if I could increase the number of suggestions. See my empty homescreen:
![grafik](https://user-images.githubusercontent.com/12029353/199695610-4aeeb136-c1c0-43fb-a884-dd878b976bd7.png)

### Describe the solution you'd like

Make the number of suggested apps dependend on available space on the homescreen.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
Did you put any apps in the "Stop suggesting" list?

**Comment by Amorphous404** [comment]
Merged with #1357
