### ISSUE TITLE
Home screen has togglable enlarged centralized letter selector

### ISSUE THREAD

**Issue by Zanagn** [8bitPit/Niagara-Issues#2106]
### Is your feature request related to a problem?

I prefer to keep my home screen in Niagara Launcher blank beside the letters to the right. Even though I wish I could tap on a letter once and be where I want to be on the list instantly, I still find it frustrating that the notes are so small I have to tap and drag until I get to where I want to be. However, if the letters were giant and grouped in the center of the screen, I could go where I wanted with a single tap that is easily executable.
![Example 1](https://user-images.githubusercontent.com/49047928/199807730-666d43d9-11b3-4a4b-9904-ee36b0187ff8.png)
This links to an image I made showing how I wanted it to look. It would look similar to the letter selector that you can access in Windows 10/11 (it doesn't have to have the background behind the letters)
Though once you are on the list, the letter list will go back to its original state: being small and to the right.

### Describe the solution you'd like

If the user manually removes everything from the screen, making it blank, This feature would either activate automatically or if they enable it in settings (or the app would suggest it before giving a choice to start it). After enabled, the letters would become larger and group into the center of the screen:
![Example 1](https://user-images.githubusercontent.com/49047928/199807730-666d43d9-11b3-4a4b-9904-ee36b0187ff8.png)
The letters would only go back to their original state once you press a letter and enter the list. This feature would make it so that it is quicker to get to where you want on the list when having a blank home screen on the Niagara launcher.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment]
Its like complete launcher suggestion

**Comment by Amorphous404** [comment]
Sorry, we don't plan to implement such feature/option.
