### ISSUE TITLE
Add recent apps screen fix

### ISSUE THREAD

**Issue by jeffconrad18** [8bitPit/Niagara-Issues#2110]
### Is your feature request related to a problem?

Please add a recent apps screen fix. 
Maybe with QuickSwitch I think there are some people out there who want that feature to.

### Describe the solution you'd like

QuickSwitch - Support

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
![Screenshot_2022-11-11-23-34-50-50_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/96917972/201401729-b77bf177-43a7-4f01-8904-992b5977e88d.jpg)

https://help.niagaralauncher.app/article/7-gesture-navigation

**Comment by jeffconrad18** [comment]
I understand that completely, by the way I already knew that. Still, I think it would be a huge added value. Maybe you can reconsider in the future.
