### ISSUE TITLE
Conditionally hide/show apps on home screen (like music feature)

### ISSUE THREAD

**Issue by Progaros** [8bitPit/Niagara-Issues#2111]
### Is your feature request related to a problem?

I need my news app mostly in the morning and my alarm app only in the evening. At other times I don't want them on my home screen 

### Describe the solution you'd like

Add a visibility feature to the home screen shortcuts (maybe next to the music settings section). To show/hide apps based on time of day (or even better: Tasker variables)

With tasker I could also show an app only once a day until I open it

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Progaros** [comment]
I found a workaround using taskers app actions and adding it to the home screen.
Then you can change the task it's referring to and thereby the icon.

Unfortunately it always shows a small tasker icon:
![Screenshot_20221111-142523](https://user-images.githubusercontent.com/22076711/201351254-37e7aa90-c511-4af4-9b78-8135691c129d.png)
Is there any way to hide this?

**Comment by topsy-turvy99** [comment]
It's already been requested you can follow it up here #786

**Comment by topsy-turvy99** [comment]
> ### Is your feature request related to a problem?
> 
> I need my news app mostly in the morning and my alarm app only in the evening. At other times I don't want them on my home screen 
> 
> ### Describe the solution you'd like
> 
> Add a visibility feature to the home screen shortcuts (maybe next to the music settings section). To show/hide apps based on time of day (or even better: Tasker variables)
> 
> With tasker I could also show an app only once a day until I open it
> 
> ### Feature Request Procedure
> 
> - [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

It's already been requested you can follow it up here #786

**Comment by topsy-turvy99** [comment]
> I found a workaround using taskers app actions and adding it to the home screen.
> Then you can change the task it's referring to and thereby the icon.
> 
> Unfortunately it always shows a small tasker icon:
> ![Screenshot_20221111-142523](https://user-images.githubusercontent.com/22076711/201351254-37e7aa90-c511-4af4-9b78-8135691c129d.png)
> Is there any way to hide this?

If that's an icon you can easily change it

**Comment by Progaros** [comment]
I want to change the icon within Tasker. If I change the icon via long press it doesn't update anymore

**Comment by Amorphous404** [comment]
Hey @Progaros if it's a normal icon/shortcut added by tasker, you should be able to change it 🤔

Can you please send a screen recording?

**Comment by Progaros** [comment]
I can change it manually using an icon pack. 
If I change it within tasker (without using an icon pack) there is always the badge like in the picture above

**Comment by Progaros** [comment]
![Screenshot_20221214-180235](https://user-images.githubusercontent.com/22076711/207659984-09bfe549-a3f5-468b-9b69-d172cfc199a1.png)
![Screenshot_20221214-180223](https://user-images.githubusercontent.com/22076711/207659991-39b8d0bf-d0bd-4608-b994-52f7e03a0395.png)

**Comment by Amorphous404** [comment]
That's an intended behaviour (Andorid feature), it helps users identify which apps the shortcuts belong too, so suspicious apps don't add take advantage of shortcuts feature, however you can override/hide the badge by manually changing the shortcut icon from the launcher.

**Comment by Amorphous404** [comment]
I hope i answered your question.

About
> Add a visibility feature to the home screen shortcuts (maybe next to the music settings section). To show/hide apps based on time of day (or even better: Tasker variables)

Please refer #786 and your valuable feedback there.

**Comment by Progaros** [comment]
ok, thanks
