### ISSUE TITLE
Swipe up gesture

### ISSUE THREAD

**Issue by Vikrantxo** [8bitPit/Niagara-Issues#2112]
### Describe the solution you'd like

Sir, What if we can customize swipe up gesture to open certain apps or to perform certain task

For example, I would like to use gesture to open samsung pay on my device, likewise people can use it open certain apps or to perform task.

Please consider my suggestion

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment]
till niagra listen why dont you use same gesture with niagra button on bottom right

**Comment by 8bitPit** [comment]
I'm sorry, we decided against adding freely customizable gestures, but you can bind Samsung Pay to the Niagara Button: https://help.niagaralauncher.app/article/77-missing-customization-features#:~:text=Freely%20Customizable%20Gestures
