### ISSUE TITLE
Allow search results to appear on the bottom

### ISSUE THREAD

**Issue by dlee098** [8bitPit/Niagara-Issues#2113]
### Is your feature request related to a problem?

The home button to search function is great, but the results being at the top means always having to reach or use two hands to select the search results. . 

### Describe the solution you'd like

If there is an option to have them appear on the bottom instead (I know sense can do this, but native is always better) that would be great

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
You can open up the first result from the Niagara search by tapping on the Enter/search button in your keyboard.

**Comment by Amorphous404** [comment]
Sorry, it's not possible and unfortunately we don't plan to change the behaviour in the near future, however you can open up the first result from the Niagara search by tapping on the Enter/search button in your keyboard.
