### ISSUE TITLE
Launcher resizing self

### ISSUE THREAD

**Issue by AchievedZeus574** [8bitPit/Niagara-Issues#2114]
### Describe the bug

Occasionally, seemingly at random the launcher will resize itself and cut off widgets if there is any. Leaves oversized margins on either side, the index on the side will remain where it should be.
Can be temporarily fixed by restarting launcher.

### Steps to reproduce

Unsure the cause and do not know how to reproduce.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Samsung UI

### Device name

Samsung A715G UW

### Android version

Android 10

### Screenshots / Screen recordings

![Screenshot_20221111-113648_Niagara Launcher](https://user-images.githubusercontent.com/97366514/201397869-41a99222-4735-4a57-a940-22fa6652f72c.jpg)

**Comment by Amorphous404** [comment]
Similar to #2144?
