### ISSUE TITLE
Swipe down to go back to home

### ISSUE THREAD

**Issue by billouetaudrey** [8bitPit/Niagara-Issues#212]
Hey,

again request,on App list, is it possible to go back to home when a I totally pull down the app list ?

Actually, it's pull down the notification bar

Thanks

**Comment by 8bitPit** [comment]
It's a little unintuitive to have one gesture which has several functions.

**Comment by VincentJoshuaET** [comment]
I agree on this. On the Pixel Launcher (at least the one I'm using) when you swipe down while in the homescreen. It shows the notification shade. But when you swipe while in the app drawer, you will return to the homescreen.

**Comment by phlppk** [comment]
> Hey,
> 
> again request,on App list, is it possible to go back to home when a I totally pull down the app list ?
> 
> Actually, it's pull down the notification bar
> 
> Thanks

To me this makes sense. Thinking of the home screen and the lettered menu app list as a continuous stack of cards. swiping down would indeed bring me to the top of the stack - and with another swipe get to the system level pulling down notifications

**Comment by cauerego** [comment]
the problem with this isn't that's unintuitive...

it's that reaching 'A' is already kind of difficult enough as it is. with this, it'd become an even bigger pain!

meanwhile, i can totally understand why someone would want this. it's easier than hitting the home button and both easier and better than swiping all the way up on the alphabet scroller.

perhaps this could combo with #440

**Comment by 8bitPit** [comment]
The swipe down gesture to go back to home only makes sense if their is a corresponding swipe up gesture (to go to the all apps list). That's why I'm merging this issue with #122

**Comment by 8bitPit** [comment]
Merged with #122
