### ISSUE TITLE
Animation malfunction problem 

### ISSUE THREAD

**Issue by HASH0000FFprint** [8bitPit/Niagara-Issues#2120]
### Describe the bug

There is a misbehaving problem with the app closing animation. 

### Steps to reproduce

When you close Twitter, the animation moves to the location of the last app you used. 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

FOLD3

### Android version

Android 13

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/74079450/202050523-f1fa7301-840f-4ead-b9a9-c5eff27b00e2.mp4

**Comment by Amorphous404** [comment]
Can you please try out the latest build and check if you can reproduce the issue.

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6
