### ISSUE TITLE
Space above clock

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2123]
### Describe the bug

look below picture.As pro user I tried all option. The clock is not moving upwards above marked line. 

Why is it intentional (Then any reason for that)
Else please utilize this space and let clock reach to top of mobile screen. So that we can have more information in screen in symmetrical way

![Screenshot_2022-11-21-15-00-43-94_a4824db61f40c53807964ea8b14c92fe](https://user-images.githubusercontent.com/5180486/203018383-e19783b9-25a7-4d9a-bc58-6a82588a9e10.jpg)
![Screenshot_2022-11-21-15-01-07-87_a4824db61f40c53807964ea8b14c92fe(1)](https://user-images.githubusercontent.com/5180486/203018940-7a041a5d-1232-45ba-bc9a-1bb7aefa5e01.jpg)

### Steps to reproduce

occur for both clock size

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

samsung

### Android version

Android 13

**Comment by topsy-turvy99** [comment]
Not sure but i think there's a reason for the limit, Don't know about the technical term but Niagara uses a Faded effect when you scroll past the limit, i think that effect might overlap on the widget if you push it any further.

**Comment by notepadnine** [comment]
> Not sure but i think there's a reason for the limit, Don't know about the technical term but Niagara uses a Faded effect when you scroll past the limit, i think that effect might overlap on the widget if you push it any further.

I have tested that. They have difference in height for both case of clock BIG and small. Even effect start just after status bar. But my prediction is they reserved this space in early days to place some default widgets and then forgot to disable

**Comment by notepadnine** [comment]
help me to remove that extra space

**Comment by notepadnine** [comment]
why padding above clock is differ when it change size and why the padding. Blir effect is too far from this

**Comment by Amorphous404** [comment]
Likely because of the font you're using, try switching to a different font and see if it helps.

**Comment by notepadnine** [comment]
Rather than this, Please see the post image. There is difference in padding between small clock, big clock. please see in your default font.

**Comment by Amorphous404** [comment]
With Niagara Neo

![Screenshot_2022-12-19-23-04-35-61_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/208486091-e5d8a620-72cd-4ca0-9504-b3282de81c12.jpg)

![Screenshot_2022-12-19-23-04-43-47_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/208486262-e9cfea60-751b-43b8-b20f-39fc46d67754.jpg)

**Comment by notepadnine** [comment]
Now please post small clock screenshot

**Comment by notepadnine** [comment]
Now please try to context menu and click move widget. then move top most , then post screenshot

**Comment by notepadnine** [comment]
https://user-images.githubusercontent.com/5180486/208487607-b020b43d-a8ab-4503-a52b-818068a66528.mp4

**Comment by notepadnine** [comment]
So the issue is why BIG clock can not reach to top, at least below status bar

**Comment by Amorphous404** [comment]
Sure, see the same space is allocated for both the size, did you try switching to a different font?

![Screenshot_2022-12-19-23-17-17-15_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/208488209-49252c69-1ab7-4064-a4c3-ab7f99fd35f3.jpg)

![Screenshot_2022-12-19-23-17-32-95_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/208488279-b306c2b6-67e7-4999-89d3-6ee3bd08bae6.jpg)

**Comment by notepadnine** [comment]
I tried below steps
- move the widget top of the screen
- slow stretch down
- then at one point clock become big
- but at this point a lot space above clock

**Comment by Amorphous404** [comment]
As far i understand the space is there for asthenic reason and for the faded/swipe up effect that put in place, not sure but i also tested with Nova Launcher it applies the same padding (might be a limitation can't say for sure).
