### ISSUE TITLE
Hard to see info in widget under clock. puzzled

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2124]
### Is your feature request related to a problem?

Its very hard to explain. But look at this below image
![Screenshot_2022-11-21-15-00-43-94_a4824db61f40c53807964ea8b14c92fe(1)](https://user-images.githubusercontent.com/5180486/203037150-4317e5d8-6461-4f9b-9374-cb3e13b36ae0.jpg)

At one view it is very hard to distinguish between different information. Battery percentage and Date create confusion. Over that weather temperature. It all overwhelm with indistinguishably.

Please devise a solution so that in quick view anybody can know information.

### Describe the solution you'd like

Solution can be any one from below or you guys suggest:
**- Introducing dynamic battery icon (Classical approach: red for low battery, blue for medium, green after 80% juice)
- Just like excel sheet (alternating color approach. There are sixitem at most: 

1. Day
2. Month
3. Date
4. Percentage
5. Weather icon
6. Temperature
 use same approach

- Other approach can be anyhow make view difference between two consecutive item from list of above 5 items**

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
![Screenshot_2022-12-14-17-32-04-61_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/207590420-3fe3d483-79d4-449f-89cb-3c25fd2a9bdc.jpg)

The spacing depends mostly on the font you use, so i suggest you switch to a different font.

About the other changes you requested we don't plan to make any changes to keep the Niagara widgets simple, clean, readable while using less space as possible
