### ISSUE TITLE
Edit colour/add a filter to all icons

### ISSUE THREAD

**Issue by Martinligabue** [8bitPit/Niagara-Issues#2125]
### Is your feature request related to a problem?

Some people might like an icon pack, but they'd want it a little more darker, or more transparent, or with more contrast.

### Describe the solution you'd like

I think an easy and unobtrusive way would be to add effects globally on icons. I thought of a more contrasted filter, or a transparent one, or a monochromatic one... It would help customizability by a lot, it may help with accessibility, and would be just a single option, maybe merged in some way with the shape of the icons option.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
A Greyscale Icon Pack is in development :), you can follow the thead and add your suggestions there.

https://github.com/8bitPit/Niagara-Issues/issues/2102#issuecomment-1315680088
