### ISSUE TITLE
Buying Niagara Pro doesn't work with MicroG

### ISSUE THREAD

**Issue by Der-Eddy** [8bitPit/Niagara-Issues#2126]
### Describe the bug

Running Niagara 1.8.4 on Android 13 with the custom rom CalyxOS which offers MicroG as replacement to Google Services. 
Trying to buy Niagara Pro within the app (neither downloaded from Arora Store or from GitHub releases) will give the error couldn't load prices.
Restarting the device as mentioned in the error yielded no result.

### Steps to reproduce

1. Go to Niagara settings
2. Tap on Niagara Pro

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 3

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_20221124-195900](https://user-images.githubusercontent.com/1234101/203851572-9a9636eb-9698-4997-b849-865e91f0d3c2.png)

**Comment by topsy-turvy99** [comment]
There are issues with Microg which struggles to load the subscription page or even recognise pro at times, if you are okay you can purchase it with google play by linking your subscription to an email so it can work independently of Playstore.


Users on v1.8.4 and above can type the /togglepreferexternal command in Niagara search to get external purchase Page to buy pro subscription outside Playstore if the users downloads Niagara Launcher from one of the other official sources except PlayStore

1) Github
2) Telegram
3) Discord etc 


Tap on the link>Press on Run Command:

https://niagaralauncher.app/app-link/secret-command?cmd=toggle-prefer-external

**Comment by Der-Eddy** [comment]
the togglepreferexternal method did it for me
Finally I can buy Niagara Pro without Google Services :)
