### ISSUE TITLE
Three or more line in calendar agenda preview

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2129]
### Is your feature request related to a problem?

In Home screen we can see only one calendar schedule. It would really kill the requirements of adding custom widget IF we can see two or more event in home screen.

I tried many agenda widget for that. But they do not mix well with the niagra launcher theme and color choices.
![a](https://user-images.githubusercontent.com/5180486/204139891-a8b465d0-3c23-44ca-b006-5a25e484e7dc.jpeg)

### Describe the solution you'd like

Make calendar widget to show more than one event, it can be vertically aligned SIMPLE.

I see no reason to just copy the pixel widget of showing only one calendar event in home screen in niagra launcher. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by notepadnine** [comment]
@Amorphous404  Thanks for showing your efforts. It might look good if you take inspiration from 
[](https://play.google.com/store/apps/details?id=de.mash.android.calendar)
Still great launcher. Seems like new breed born in the era of sheep herd of launchers.

**Comment by Amorphous404** [comment]
The devs are aware of this app, the goal was to keep the settings as minimal as possible to avoid cluttering up with many options,

Anyways, if we reconsider it in future, we will reopen up this ticket, for now I'll close it so we can focus on other issues :)
