### ISSUE TITLE
Theme Google button

### ISSUE THREAD

**Issue by billouetaudrey** [8bitPit/Niagara-Issues#213]
Hey, 

Can you add the possibility to change color and transparency of the Search Bar ( on App list ) and Google Button

Thanks

**Comment by 8bitPit** [comment]
The search bar will be removed soon :) And yeah, at some point you can theme the Google button

**Comment by Damia91** [comment]
Hello! Is there any news about the possibility of changing the color of the Google button? Thank you!

**Comment by 8bitPit** [comment]
Hey @Damia91, unfortunately there isn't. This is a low priority issue, so it may take a long time before this will be implemented.

**Comment by 8bitPit** [comment]
@Puripu noted: 
>I use the google search button frequently, to get to google home and just to search. So I can't hide the button to get a really minimalist view, because I need it.
It would be nice if you could make it transparent, or choose from a few different types of buttons for that search button. Go for an even more minimalist text only view.

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/303
