### ISSUE TITLE
Two feature request

### ISSUE THREAD

**Issue by AyaanMAG** [8bitPit/Niagara-Issues#2131]
### Describe the solution you'd like

1) the way the time and weather are neat looking texts, if a screentime option could be added it would be very nice
2) some options to trigger the search bar when swipinh from up to down like smart launcher, I'm trying to transition from that and the search button is janky cuz you need to go the the whole app list and try scrolling weird ways till the niagra lords bestow upon you, the option to search

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
1. Screen time widget is Planned but no ETA at the moment.

2. You can enable swipe up to search.
(Niagara Settings>Features>Swipe up to search)
