### ISSUE TITLE
Weather wind chill or feels like.

### ISSUE THREAD

**Issue by jobangill7575** [8bitPit/Niagara-Issues#2132]
### Is your feature request related to a problem?

Based on my location in Canada, the weather info is not helpful because it does not show wind chill/feels like temperature. Since the temperature difference between the base temperature and feels like can be up to 20 degrees Celsius, I always have to use Google weather for accurate temperature.

### Describe the solution you'd like

A toggle to enable wind chill temperature would be really helpful.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by topsy-turvy99** [comment]
https://help.niagaralauncher.app/article/105-weather-widget
