### ISSUE TITLE
Haptic feedback too strong

### ISSUE THREAD

**Issue by YaoSta** [8bitPit/Niagara-Issues#2135]
There is too much vibration on some of the animations whereas it's normal on others meaning the same as the one I selected in system settings which I think should be applied to all the animations.
Edit: The buggy animations are pulldown for notification panel and the swipe to access the pop up menu of apps. Also the swipe up on the google icon.
S21 Ultra
One UI 5.0
Android 13
Niagara 1.8.5

**Comment by topsy-turvy99** [comment]
Can you be more specific about what you mean by too much vibration where it's using too much vibration, example alphabet scroll etc.


Also please provide your
Device Name
Rom
Android version
Niagara version

Thank You

**Comment by topsy-turvy99** [comment]
> There is too much vibration on some of the animations whereas it's normal on others meaning the same as the one I selected in system settings which I think should be applied to all the animations.
> Edit: The buggy animations are pulldown for notification panel and the swipe to access the pop up menu of apps. Also the swipe up on the google icon.
> S21 Ultra
> One UI 5.0
> Android 13
> Niagara 1.8.5

Thank you for adding the details, The vibration sensitivity changed after updating to OneUi 5.0, Andorid 13?

**Comment by YaoSta** [comment]
> > There is too much vibration on some of the animations whereas it's normal on others meaning the same as the one I selected in system settings which I think should be applied to all the animations.
> > Edit: The buggy animations are pulldown for notification panel and the swipe to access the pop up menu of apps. Also the swipe up on the google icon.
> > S21 Ultra
> > One UI 5.0
> > Android 13
> > Niagara 1.8.5
> 
> Thank you for adding the details, The vibration sensitivity changed after updating to OneUi 5.0, Andorid 13?

yes I believe so

**Comment by topsy-turvy99** [comment]
Samsung screwed/accidentally swapped the strength vibration effect that it previously used with the recent Oneui 5.0 update, wait for the future phone update hopefully they'll revert back the changes, if not the devs the devs will definitely add a workaround to fix the issue.

Note:
Niagara uses the same vibration as Launcher3 (which your system launcher is built on) . Niagara doesn't cap the strength and doesn't exactly specify the strength and duration.

**Comment by 3166265725** [comment]
> 

I tested lawnchair12.1, and had the same haptic problem. It was indeed a problem with one UI 5. But how to let Samsung know about this problem and fix it?

**Comment by 8bitPit** [comment]
Hey @YaoSta & @3166265725, thank you both for reporting. We added a workaround where we lower the vibration for all affected devices. If Niagara Launcher's haptic feedback still feels wrong, please name us your device, and we'll also adapt its vibration pattern. Regarding where to send Samsung bug reports, that's a good question; I guess the best way is [through their Members app](https://www.samsung.com/ae/support/mobile-devices/how-to-send-error-report-in-your-galaxy-device/).

**Comment by 3166265725** [comment]
> 



> Hey @YaoSta & @3166265725, thank you both for reporting. We added a workaround where we lower the vibration for all affected devices. If Niagara Launcher's haptic feedback still feels wrong, please name us your device, and we'll also adapt its vibration pattern. Regarding where to send Samsung bug reports, that's a good question; I guess the best way is [through their Members app](https://www.samsung.com/ae/support/mobile-devices/how-to-send-error-report-in-your-galaxy-device/).

I tried version 1.8.8, the haptic is still wrong, my device is SM-G9960, Samsung S21+, can you fix it, because it is too difficult to wait for Samsung to fix it .

**Comment by 8bitPit** [comment]
Thanks for sharing @3166265725; I added the S21+ to our vibration workaround list. The vibration should be fixed for you after around 24h or immediately after executing this secret command: https://niagaralauncher.app/app-link/secret-command?cmd=refreshremoteconfig.

**Comment by 3166265725** [comment]
@8bitPit Hello, I executed the command immediately after receiving the message, but it didn’t take effect. I executed the command again just now, but it still didn’t work. Haptic like the haptic of an alarm clock, Should I reinstall Niagara?

**Comment by Lyrillind** [comment]
Samsung S23 Ultra has the same problem.

**Comment by 8bitPit** [comment]
Apologies for the delayed reply @Lyrillind. On the Fold 4, Samsung fixed this with their One Ui 5.1 release. Did they fix it on the S23 Ultra as well?
