### ISSUE TITLE
Home button animation is bugged.

### ISSUE THREAD

**Issue by vishal-mohanty** [8bitPit/Niagara-Issues#2136]
I'm using S22 Ultra with Niagara Launcher v1.8.5 and one problem I face is that everytime I use the home button the animation showed is:

https://user-images.githubusercontent.com/63508870/205416757-b75e8697-67fa-4412-ab46-bfaebbb4c99f.mp4

Is there an option to change the animation?

**Comment by Amorphous404** [comment]
Can you try out this latest build and check if it fixed the issue:

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6

**Comment by vishal-mohanty** [comment]
I've installed the new build, however, the issue seems to persist.

https://user-images.githubusercontent.com/63508870/207742408-c56c5537-5c13-4c9b-9fa0-3bf16ab42de1.mp4

**Comment by Amorphous404** [comment]
Strange, can you please mention your Android Version?

Also can you please check how it behaves on Lawnchair?

https://github.com/LawnchairLauncher/lawnchair/releases/tag/v12.1.0-alpha.4
