### ISSUE TITLE
Home button triggers search - how to revert to normal behavior?

### ISSUE THREAD

**Issue by rd836** [8bitPit/Niagara-Issues#2137]
### Describe the bug

Using Niagara v1.8.5.
Two Moto G6s with Oreo.
On the Moto G6 with the free Niagara, the Home button triggers a search.
Yet on the other Moto G6, with Niagara Pro, it doesn't.
Both phones have "Enable Niagara Button" and "Swipe up to search" set to off.
Where is the setting to turn that search off?
Does this have to do with some feature/bug a few versions ago?

### Steps to reproduce

1. From Home screen, press Home button.
2. Maybe a second press of the Home button is needed.
3. An unwanted search screen that was never there before apprears.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Moto G6

### Android version

Android 8.1 (Oreo)

**Comment by topsy-turvy99** [comment]
Not sure which unwanted search you're referring to, but if you're asking about Niagara Search, then when you enable Niagara Settings>Features>Swipe up to search, Swipe up and the home button from your Favorites screen will trigger Niagara Search.

If you want to disable it, toggle off the Swipe up to search feature.

**Comment by rd836** [comment]
As stated in my original post, the "Swipe up to search" _is_ disabled, yet tapping on the Home button triggers a search, on the non-Pro phone. On the Niagara Pro phone, the setting is honored.

I want to get back to the pre v1.8.0 behavior where the home button didn't trigger an app search.

**Comment by topsy-turvy99** [comment]
You mentioned an unwanted search instead of niagara search, it wasn't very clear, so i thought maybe you accidentally assigned some sort of system/app search for home button (some rom provides that option)

But anyways that shouldn't happen, disabling the swipe up to search should stop the home button from triggering the Niagara search.

**Comment by topsy-turvy99** [comment]
v.1.8.3 beta changelog

![IMG_20221204_232839.jpg](https://user-images.githubusercontent.com/96917972/205507384-e41cdc59-730c-4363-8277-b7a06c406b82.jpg)

**Comment by rd836** [comment]
I don't use any of the fancy features in Niagara. I do not use "gestures", only button taps.

Settings in both phones:
"Enable Niagara Button" DIS-abled.
"Swipe up to search" DIS-abled.
Turning the phone on from scratch in Niagara _free_ v1.8.5 and tapping the home button gets an unwanted Niagara app search.
But in the _Pro_, hitting the home screen home button several times does nothing (the desired behavior).

What I've been politely suggesting is that the _Pro_ version got the bug fix, while the _free_ version did not.
(I hope that isn't part of a new business model.)

**Comment by topsy-turvy99** [comment]
Thanks for reporting, i was able to reproduce it.

Go to Niagara Settings>Features>Enable swipe up to search>And Disable it back, this should fix the issue, do let me know if it worked 👍

**Comment by rd836** [comment]
Yes, that worked.
Amazing that in all my twiddling with the settings I didn't stumble across that myself.
Thanks.

**Comment by Amorphous404** [comment]
> Thanks for reporting, i was able to reproduce it.
> 
> Go to Niagara Settings>Features>Enable swipe up to search>And Disable it back, this should fix the issue, do let me know if it worked +1
> 
>  zz.mp4

By default swipe up to search is disabled, yet the home button triggers Niagara Search.

To fix one has to enable the swipe up to search feature and disable it.

@8bitPit

**Comment by 8bitPit** [comment]
Thank you very much for reporting @rd836 and for finding the culprit @Amorphous404; I'll investigate the issue.

**Comment by 8bitPit** [comment]
Fixed in v.1.8.7: https://github.com/8bitPit/Niagara-Issues/releases/ - thanks again for reporting @rd836!
