### ISSUE TITLE
allow to put niagara settings into folder

### ISSUE THREAD

**Issue by Lehmann11** [8bitPit/Niagara-Issues#2138]
### Is your feature request related to a problem?

Currently the Shortcut in the Applist for "Niagara Settings" and "recently installed apps" cant use custom icon or be put into a folder.

![photo_2022-12-05_04-16-42](https://user-images.githubusercontent.com/119829158/205541963-c5a9fbad-721d-4fbe-9a23-526587ef50db.jpg)

### Describe the solution you'd like

Please let us select custom icons for those 2 hardcoded applist entrys and/or hide them in folders like with normal apps.

![1](https://user-images.githubusercontent.com/119829158/205541901-310da169-488e-46e3-90d5-0af6dc522910.png)

thank you

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Lehmann11** [comment]
also related to this: please consider hiding the category tags when no apps are being shown in the applist cause of folders or all apps being hidden.
![2](https://user-images.githubusercontent.com/119829158/205542375-0d6faf60-df33-4733-bc44-629b0984dd8f.png)

**Comment by Amorphous404** [comment]
> Please let us select custom icons for those 2 hardcoded applist entrys

The team is considering adding the option to change these icons, please refer to #1595

About putting Niagara Settings & Recently installed folder into a folder, this would be problematic/difficult to implement, so it won't be worked on.
