### ISSUE TITLE
Hide Applist popup folder category tag

### ISSUE THREAD

**Issue by Lehmann11** [8bitPit/Niagara-Issues#2139]
### Is your feature request related to a problem?

![31](https://user-images.githubusercontent.com/119829158/205545807-8ac09a29-4ce0-46ce-a690-33540b5ab789.png)

### Describe the solution you'd like

please consider hiding the category tags when no apps are being shown in the applist cause of folders or all apps being hidden.
![2](https://user-images.githubusercontent.com/119829158/205542375-0d6faf60-df33-4733-bc44-629b0984dd8f.png)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Thank you for your suggestion regarding the category tags in the app list. After careful consideration, we have decided not to hide the tags at this time. While we understand that some users may prefer to have the option to hide the tags, we also believe that many users find the tags to be a useful. Additionally, we have determined that adding an option to hide the tags would not have a significant impact on the overall usability and functionality of the app list, and therefore we have decided not to pursue this change at this time. We apologize if this decision is not in line with your preferences, Thank you for your understanding.

For more about our design principles you can go through this article.
https://help.niagaralauncher.app/article/8-niagaras-design-principles
