### ISSUE TITLE
Can't create shortcuts error

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2142]
### Describe the bug

When trying to create shortcuts from either Chrome or using app called Shortcut Maker the shortcut isn't created and I get an error message. This used to work fine a couple versions ago. 
![Screenshot_20221205_201722_Niagara Launcher](https://user-images.githubusercontent.com/81394097/205735359-5ee1a840-0888-467b-99f9-542006b64783.jpg)

### Steps to reproduce

Open Chrome
Three dots menu
Pick 'add to home screen' 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Other 3rd-party launcher(s) tested

Tried Nova launcher and Oneui launcher. No issue

### Device name

Galaxy Fold 4

### Android version

Android 5.0 (Lollipop)

### Screenshots / Screen recordings

![Screenshot_20221205_201722_Niagara Launcher](https://user-images.githubusercontent.com/81394097/205736187-1229408e-a5e9-4073-814d-3f492e49625b.jpg)

**Comment by topsy-turvy99** [comment]
This is a known issue, devs are working to fix it

Meanwhile to temporarily fix the issue:
Restart the Launcher>And try to add the shortcut.

**Comment by Lorestan00** [comment]
Thanks

**Comment by Amorphous404** [comment]
Can you please check if this build fixed the issue :)

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.6

**Comment by Lorestan00** [comment]
I can confirm all fixed. Error message doesn't appear and shortcut is created on homescreen. Thanks

**Comment by ssssamstrup** [comment]
I experienced this in January #2548 and again right now. It seems to be the same issue.
