### ISSUE TITLE
Some app icons disappear when the phone is unlocked

### ISSUE THREAD

**Issue by XtionFuze** [8bitPit/Niagara-Issues#2145]
![Screenshot_20221208-203100](https://user-images.githubusercontent.com/37160600/206624872-f429363c-83d6-4564-a180-aaf34d521871.png)

Not sure what caused it, all I did was unlock my phone and opened up to that. A simple launcher restart fixed it.

**Comment by Amorphous404** [comment]
Hey @XtionFuze sorry for the late reply, can you update to this latest version and check if you can still reproduce the issue, thank you.

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.11

**Comment by XtionFuze** [comment]
I wasn't sure what caused the issue in the first place.
Though I did upgrade to the latest version just now. If it happens again
I'll be sure to submit it again.

Thanks

**Comment by Amorphous404** [comment]
@XtionFuze Feel free to report back here, if the issue continues to show up, I'll close this ticket for now so we can focus on the other issues :)
