### ISSUE TITLE
Icon Notification Indicator 

### ISSUE THREAD

**Issue by xH8TE** [8bitPit/Niagara-Issues#2146]
### Describe the solution you'd like

Please add a notification dot or number next to a favorite icon when there is an unread notification. For example. When a new message comes in, please place a dot (can even be Niagara dot) or number count on top of or overlayed on the icon to indicate there is an unread notification for any app added to the favorite home screen. And/or using the Niagara icon dot pack, please either underline the icon name, or bold the name, or change the icon name to a different color chosen by the end under to indicate there is an unread notification. We need some form of indicator at the icon level that indicators an unread notification. I believe this can help speed up and simplify unread notifications without having to always swipe down into the notification system. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
![Screenshot_2022-12-11-16-18-10-57_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/96917972/206899325-7262f061-0bbd-4dd0-9789-0a7a1933d315.jpg)

To enable it go to
Niagara Settings>Features>Notifications>Notification Preview

**Comment by xH8TE** [comment]
Thank you. However I would like notifications without previews. I would like to maintain my privacy without having the contents of my notification readily able to read on the home screen.  Also if my favorites all have unread notifications then that expands the home screen significantly while not maintaining my privacy of said notifications. I would like to option to simply have an indicator of an unread notification. That maintains the simplicity of the launcher and privacy.

**Comment by Amorphous404** [comment]
> Thank you. However I would like notifications without previews. I would like to maintain my privacy without having the contents of my notification readily able to read on the home screen.  Also if my favorites all have unread notifications then that expands the home screen significantly while not maintaining my privacy of said notifications. I would like to option to simply have an indicator of an unread notification. That maintains the simplicity of the launcher and privacy. 


Here's an old response from the dev regarding the feature:
https://github.com/8bitPit/Niagara-Issues/issues/800#issuecomment-528091213


Kindly request to open the previous ticket #800 and add your valuable feedback there :)
