### ISSUE TITLE
Text color does not switch to dark when live wallpaper switches to light

### ISSUE THREAD

**Issue by harmtemolder** [8bitPit/Niagara-Issues#2147]
### Describe the bug

My device switches between different wallpapers for day and night based on a live wallpaper ([Dark Mode Live Wallpaper](https://f-droid.org/en/packages/com.github.cvzi.darkmodewallpaper/)) as proposed in #1984. I have text color set to "Based on wallpaper". This works perfectly when I switch from another (live or static) wallpaper to this one, but not when this one switches between dark and light or vice versa.

At what times is the wallpaper evaluated for this "Based on wallpaper" setting?

### Steps to reproduce

1. Set Niagara Launcher's "Text color" setting to "Based on wallpaper"
2. Install and apply [Dark Mode Live Wallpaper](https://f-droid.org/en/packages/com.github.cvzi.darkmodewallpaper/)
3. Set it to `#FFFFFF` for day and `#000000` for night
4. Set its time to switch a couple of minutes in the future
5. Wait
6. Notice that the wallpaper changed, but the text color hasn't

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Xiaomi Mi 9 SE

### Android version

Android 11

**Comment by Amorphous404** [comment]
Works fine here in both ways, switching it manually or setting a schedule time to automatically switch between the two.


https://user-images.githubusercontent.com/96917972/206998302-d8f80274-15db-4227-af63-c3d7db716728.mp4

**Comment by wimstefan** [comment]
I can confirm the same happening here both with colors only and wallpapers ...
* Xiaomi Poco X3
* ArrowOS 11
* Dark Mode Live Wallpaper: v1.4.8
* Niagara Launcher: v.1.8.6
   Settings -> Look
   - Dark theme: Use device theme
   - Text color: Based on wallpaper

**Comment by harmtemolder** [comment]
@wimstefan The same as Amorphous404, or the same as me?

I'm not sure what changed on my phone, but right now I don't have the issue of light text on a light background (or dark on dark) anymore. Neither when adjusting Dark Mode Live Wallpaper's time range, nor when having it follow system and forcing dark mode there.

**Comment by wimstefan** [comment]
> @wimstefan The same as Amorphous404, or the same as me?

The same as your issue reported of course :)

> I'm not sure what changed on my phone, but right now I don't have the issue of light text on a light background (or dark on dark) anymore. Neither when adjusting Dark Mode Live Wallpaper's time range, nor when having it follow system and forcing dark mode there.

Please let us know when you find out what changed - it's a bit tedious to change font colour manually twice a day ;)

**Comment by wimstefan** [comment]
I can join the club now 🙂
After waking up and checking my phone I noticed that it not only switched to the light mode for the day as configured in the system settings but the text is dark now! Also switching manually changes the text colour according to the mode 🤔
So it seems that time does wonders in this case. Just don't ask for a logical explanation 😏

**Comment by harmtemolder** [comment]
Haha, you've got to love bugs that solve themselves

@Amorphous404 If you want to dive in deeper, let me know what input we can provide. But otherwise feel free to close this issue

**Comment by harmtemolder** [comment]
Wait, don't close it yet: the issue returned:

This is yesterday, when my phone switched to dark mode while the screen was off, triggering Dark Mode Live Wallpaper, but not Niagara's text color:

![dark text on dark wallpaper in Niagara Launcher](https://user-images.githubusercontent.com/8167752/207782398-034c9259-d603-41c4-8850-43acfb447ef6.png)

When I turned my phone on this morning it was light text on dark wallpaper, so all good. But when I manually switched off dark mode:

![light text on light wallpaper in Niagara Launcher](https://user-images.githubusercontent.com/8167752/207782616-3beb0260-239a-4921-b273-efe9dc841960.png)

**Comment by Amorphous404** [comment]
Can you share both the color code?

**Comment by harmtemolder** [comment]
Sure thing: It's [Solarized Base 03](https://user-images.githubusercontent.com/8167752/208034502-bbda79ba-44ae-4a89-9aeb-83a569c7e7ca.png) (`#002b36`) and [Solarized Base 3](https://user-images.githubusercontent.com/8167752/208034514-e4999f67-d429-4772-b037-8ed76b35809f.png) (`#fdf6e3`)

**Comment by Amorphous404** [comment]
Hey @harmtemolder, Thanks for sharing the code, 
Based on my testing, i don't seem to face the issue with the text color when switching wallpaper on my device. Launchers simply receive inputs from the system and apply the designated text color, so there isn't much we can do to fix the issue. A possible solution could be to check your phone's settings to see if anything there might be causing the problem. If you don't find anything in the settings that could be causing the issue, you may want to contact Xiaomi or the developer of the DarkMode Live Wallpaper app to see if they have any suggestions or solutions.

**Comment by harmtemolder** [comment]
Thanks for testing. The annoying thing is, sometimes it actually does work. And as you say, the issue might just as well be in Dark Mode Live Wallpaper or my Android version. Let's close this issue then

**Comment by rokejulianlockhart** [comment]
@harmtemolder, it's probably not your Android version, per https://github.com/8bitPit/Niagara-Issues/issues/2193#issue-1570135114. I use Fairphone's stock ROM for their Fairphone 4.
