### ISSUE TITLE
App opening animation doesn't trigger for some time after closing app 

### ISSUE THREAD

**Issue by finkrer** [8bitPit/Niagara-Issues#2150]
### Describe the bug

Basically the subject. 

### Steps to reproduce

1. Open an app present on the homescreen
2. Observe the opening animation
3. Swipe to go to homescreen
4. Immediately tap on an app on the homescreen
5. The animation does not play

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

OnePlus 9

### Android version

Android 13

**Comment by Amorphous404** [comment]
The animation doesn't play or the app does not open?

Can you share a screen recording?

**Comment by finkrer** [comment]
https://user-images.githubusercontent.com/22712590/207356028-f76264cb-34b1-4428-a485-ab9e00e15193.mp4

The app does open but without animation. see the attached video. First 2 times I open the app after a pause and the animation plays, then I open it quickly after closing 2 times and it just immediately appears with no animation.

**Comment by Amorphous404** [comment]
Do mention the name of the custom rom and stock launcher, if you changed it

**Comment by finkrer** [comment]
The ROM is PixelExtended and the stock launcher is Pixel Launcher.

**Comment by finkrer** [comment]
You can open any app, same or different. 

Pixel Launcher, which has this animation, works perfectly. In fact, you don't even have to wait for the closing animation to end - all the icons are responsive and trigger the opening animation right away. 

With Niagara, the icons are inactive until the animation is fully completed, and then there's a delay before the opening animation can play.

**Comment by 8bitPit** [comment]
Unfortunately, we have very limited control over the animation; the preinstalled launcher starts the animation and also mostly manages it otherwise [(explanation)](https://help.niagaralauncher.app/article/7-gesture-navigation#:~:text=Android%E2%80%99s%20recent%20apps%20screen%20behaves%20differently%20compared%20to%20the%20pre%2Dinstalled%20launcher.)]. Your issue should be reproducible with other third-party launchers like Nova Launcher or Microsoft Launcher. I recommend submitting a bug report to the Google issue tracker.

**Comment by finkrer** [comment]
Yeah, that was actually me as well, although I haven't had that issue on my new device. 

I'd like to point out that neither of the issues comes from trying to do something before the animation finishes. In this case, it does finish, at least visually. So it's not like I'm trying to break things deliberately, it actually happens all the time during normal use.

**Comment by finkrer** [comment]
Yeah, I've tested the Nova Launcher again and sure enough, the same issue is present. 

I just wonder, does this work properly for you guys? Would a different stock launcher help?

**Comment by 8bitPit** [comment]
@finkrer I see; yes, I can reproduce it on my Pixel phone, so even the most stock-ish Android launcher seems to have the issue. I hope it's okay if I close the ticket here since the only thing we can do is to wait for the Android team providing a fix.
