### ISSUE TITLE
Long tap menu on home screen

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2151]
### Is your feature request related to a problem?

Context menu when long tap on home screen favorite is too vulnerable.

I think a lock home screen option should be added like other launchers.

### Describe the solution you'd like

Long tab should have a option 'LOCK HOME SCREEN'.This  may give following features
1. no context menu by long tap on any favorites
2. no scrolling drawer(optional)
3. no agenda on clicking (optional)

This locked layout can be toggled by **long tap on clock** and selecting disable **lock home screen**

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Duplicate of #1901
