### ISSUE TITLE
Vertical scrolling Wallpapers / parallax effect

### ISSUE THREAD

**Issue by tofuisme** [8bitPit/Niagara-Issues#2152]
### Is your feature request related to a problem?

Reopening this old issue, they said they need  a call back. I am not end user tho .Still I would love much more if I got this feature 

![Screenshot_20221215-223628_Gmail](https://user-images.githubusercontent.com/94361006/207949766-ac83413b-75e3-4db5-8753-e6f3a086c66b.png)

### Describe the solution you'd like

When I draw app drawer. The live wallpaper should be interactive with my fingers and show parallex effect 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Can you please forward the same to #246, so that we don't have duplicates for the same issue :), i close this issue.
