### ISSUE TITLE
Search very slow to update on backspace

### ISSUE THREAD

**Issue by abs3ntdev** [8bitPit/Niagara-Issues#2154]
### Describe the bug

When searching for an app it is quick to update on typing a letter but very slow to update when hitting backspace. This results in hitting enter and the wrong app opening. The update time should be the same for both typing a new letter and deleting a letter. 

### Steps to reproduce

1. Open search
2. Start typing a search
3. Hit backspace

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Samsung Fold 4

### Android version

Android 12

### Screenshots / Screen recordings

https://user-images.githubusercontent.com/86447830/208204456-cdf7708c-97c2-49a4-87bf-ac0ad34e4152.mp4

**Comment by Amorphous404** [comment]
Thanks for reporting it, I was able to reproduce it on my end.

Niagara Search:
https://user-images.githubusercontent.com/96917972/208240043-6a348697-14df-4f7e-bc88-5974471af806.mp4

Nova Search:
https://user-images.githubusercontent.com/96917972/208240062-d9b5a5d7-4373-4651-8304-4a0112b26169.mp4

**Comment by TFackler** [comment]
Thanks for reaching out.

This behavior is intended, and we are optimizing the search by running a complete search less often.

Does this exact scenario happen often and hinders you from using the search?
The way I see this, a user would want to open a specific app, let's say Twitter in the example video. They type `t` and see Twitter at the top of their search results, then they accidentally type another letter (here `i`), notice they have misspelled, but remember that twitter was at the top before, so they delete one character and immediately hit enter. This feels like a rather uncommon and constructed flow and I would rather keep the optimization as is.

Please tell me if I am missing something or if this scenario happens more often than I think :)

**Comment by jjohnstondev** [comment]
That exact scenario happens all the time to me and is one of the reasons I stopped using Niagara for now. The janky search updates feel strange and and the slow update on backspace made me open the wrong app in the way you described enough times for me to be annoyed enough to just find something with a search that updates immediately since search is primarily how I open apps.

**Comment by abs3ntdev** [comment]
any update on this? would love to see it completed

**Comment by TFackler** [comment]
Sorry for the long wait. We've added this and it should be included in the next update :)
