### ISSUE TITLE
Location based home screen 

### ISSUE THREAD

**Issue by prylarer** [8bitPit/Niagara-Issues#2157]
### Describe the solution you'd like

Some apps are needed only for example at home. Option to show certain pop up folder on home screen only when logged in home wi-fi would keep home screen even more simple.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
A similar request has already been proposed and the dev team is giving a thought about it, please refer #786
