### ISSUE TITLE
Big folder feature

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2159]
### Is your feature request related to a problem?

As introduces by Nothing OS. All other OS adapting big folder feature.
One UI 6
MIUI 14
Nothing OS
Iphone Drawer 

now all have big folder feature where you can open icon directly from folder like below
![image](https://user-images.githubusercontent.com/5180486/208719102-a8f22d17-af98-4359-a7d7-796b2eefda05.png)

Any idea or plan to get this feature in Niagra

### Describe the solution you'd like

![nl2](https://user-images.githubusercontent.com/5180486/208720574-3d251ae0-2aeb-4d53-9743-699a426ed394.png)

Because you are linear launcher. I think you should consider linear folders like green box

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Sadly we think this feature would add too much complexity compared to the small reward it brings to the majority of our users. Also introducing this feature is counter-intuitive for our design principle of simplicity and ease of use/one hand usage.
(Ergonomic efficiency · Access everything with one hand - no matter how big your phone is).


If you want to read more about our design principles:
https://help.niagaralauncher.app/article/8-niagaras-design-principles
