### ISSUE TITLE
Notification preview not using device default font

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2160]
### Describe the bug

When using Hybrid mode in Niagra font, Notification preview under favorite are using some fixed font(Called as default). It is not changing even if I change default font of device. **FONT FOR YELLOW HIGHLIGHTED ONE**
![45414966-d4f7a700-b67c-11e8-9ef2-88509ad970ab](https://user-images.githubusercontent.com/5180486/208959277-97266b62-e16e-478e-b37b-6610cf966989.png)

![4444444444Capture](https://user-images.githubusercontent.com/5180486/208959302-0a2a0138-370e-4797-85eb-0902ac136258.JPG)
### Steps to reproduce

- Use custom font in Niagra launcher
- Use font hybrid mode in Niagra Launcher
- Use custom font in Device settings
- Now home screen text under favorites is different font other than device default.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung

### Android version

Android 13

**Comment by Amorphous404** [comment]
It's an intended behaviour as mentioned  in the post you marked, it uses the Niagara default font "Work Sans" not the system default font, when Hybrid mode is disabled for better readability.

**Comment by notepadnine** [comment]
Its creating inconsistency between thirdparty widget and Niagra homescreen by using three fonts
- Device default font in Third party Widget
- Custom font in Niagra favorites
- Work Sans font in long text under favorites in Niagra

**Comment by Amorphous404** [comment]
Switching to system default font for small and long text wouldn't be ideal as it would cause issues for users who use fancy font for the system. So we don't have any plans to switch it.

Regarding inconsistency, i suggest you enable hybrid mode in Niagara settings, so the small & long text use the same font instead of Work Sans
