### ISSUE TITLE
Agenda showing Incorrect Calendar Events 

### ISSUE THREAD

**Issue by Mattrobby** [8bitPit/Niagara-Issues#2161]
### Describe the bug

When using the *Agenda* feature, it has issues syncing to my calendar correctly. Events that are on my calendar do not show up, and old recurring events still are showing. 

Notice that on Dec. 19, only my *Dentist* event shows up in the *Agenda* even though there are other events part of the same category. 

Then on Dec. 21, my *Agenda* shows an *IT Helpdesk* event (that was a recurring event that stopped a few weeks ago) but when you go to my calendar it does not show the event. It is also missing the *BCF Meeting* event for that day. 

> **Note:** I am using *Outlook* to sign into my Office365 calendar. Unfortuantly I cannot try signing into my calendar with a different calendar app due to my organization only supporting *Outlook*. 

### Steps to reproduce

I am not sure the steps to take to reproduce this (I don't have another android device to test this on) but I can list the steps I have taken to fix this: 

1. Log out and back into my calendar app
2. Factory Reset *Niagara Launcher* 
3. Disable and renable the calendars I use
4. Restarting the device 
5. Force stopping *Niagara Launcher* 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6

### Android version

Android 5.0 (Lollipop)

#### What my Agenda shows: 

![image](https://user-images.githubusercontent.com/69593550/209253033-294dc82a-ed6e-4d2d-9056-79bfcfc25756.png)

#### My Calendar (Dec. 19): 

![image](https://user-images.githubusercontent.com/69593550/209253085-bd708a00-d34e-48c2-a150-406a1f4d6d18.png)

#### My Calendar (Dec 21): 

![image](https://user-images.githubusercontent.com/69593550/209253109-686ed933-4eaa-44ac-b9f3-05570fd50b72.png)

**Comment by Amorphous404** [comment]
Hey @Mattrobby, Calendar apps don't necessarily make changes to your calendar available to other apps immediately.


Open Google Calendar and tap on the three dots on the top right and then on Refresh. This should most probably fix the syncing issue, if not you can try out the other steps mentioned in this help article.

https://help.niagaralauncher.app/article/76-calendar-faq

**Comment by Mattrobby** [comment]
@Amorphous404 you were right, it ended up being a problem with my calendar app. Uninstalling and reinstalling fixed it.

**Comment by Amorphous404** [comment]
Glad to hear that uninstalling and reinstalling your calendar app fixed the issue. Thank you for letting me know.
