### ISSUE TITLE
Predictive-back-gesture support 

### ISSUE THREAD

**Issue by Underday** [8bitPit/Niagara-Issues#2162]
### Is your feature request related to a problem?

Animation is not displayed correctly when I close an application that uses this feature

### Describe the solution you'd like

Just add support like app closing animation.

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Underday, Thanks for reporting it, Unfortunately we have very limited control over the animation; the preinstalled/system launcher mostly manages the animation.
To know more about it you can go through this article:
https://help.niagaralauncher.app/article/7-gesture-navigation

The issue should be reproducible with other third-party launchers like Nova Launcher or Microsoft Launcher. Anyways we have filed a bug report in the Android issue tracker regarding this, you can star and add your input there if you're affected by the issue.

https://issuetracker.google.com/u/0/issues/263606935

**Comment by Underday** [comment]
Yes as u said another launcher have this problem too. Thanks for ur response. Have a nice day! And last but not least: this launcher is freaking good, thanks for effort.

**Comment by Amorphous404** [comment]
I'm glad to hear that you find the launcher to be useful. It's always good to receive positive feedback and I'm happy to be able to assist you. Have a great day!
