### ISSUE TITLE
Clock widget visibility issue

### ISSUE THREAD

**Issue by notepadnine** [8bitPit/Niagara-Issues#2164]
### Is your feature request related to a problem?

I am not a use who uses kwgt widget (you can have only one widget) to see just clock. Rather I use some useful widget. And due to vertical space lack, I hide clock.

So clock is complete absent If I hide it and use other widget . see below example
![NL](https://user-images.githubusercontent.com/5180486/209665440-8a7ec306-8511-49b0-aeea-a8d8dea0a613.jpeg)

**No clock in this complete screen. I have to rely on third part widget just for clock and some space saving**

## - show clock before Day time in case of clock replace with widget.

Below option will impact it. See below setting screen
![NL2](https://user-images.githubusercontent.com/5180486/209665725-d6cb8f04-38a5-4382-88b1-2d1aea4e7b10.jpeg)

**And after all that feature just rename  
REPLACE CLOCK WITH FEATURE to
MOVE CLOCK ABOVE/BELOW WIDGET
**

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
> show clock before Day time in case of clock replace with widget.

I'm sorry, to keep the process simple, we decided against adding alternative options.

And normally you can still show the clock above the widgets, if you don't replace the clock with custom widgets.

**Comment by Amorphous404** [comment]
It's understandable that you may feel frustrated if your suggestions or requests for features are not being implemented in the launcher. However, it's important to keep in mind that the development team for any product, including a Niagara launcher, has to prioritize and make decisions about what features to add based on a variety of factors, including the resources and time available, the potential impact on the user experience, and the overall direction and goals for the product.

It's also possible that the feature you are suggesting has already been considered and decided against for one of these reasons, or that it is something that is not feasible to implement for technical or other reasons.

Regardless of the reason, it's important to remember that the development team is always working to improve the product and make it the best it can be for its users.

**Comment by notepadnine** [comment]
I am completely agree with that. It is not sad or happy. Niagra is already nearly perfect launcher. I have my own suggestion so that it may feel private to. If they are not being considered, it does not create love/hate relationship. 

I just think  how many of user suggested feature dev team has opted since one year.

**Comment by Amorphous404** [comment]
> I just think  how many of user suggested feature dev team has opted since one year.

You can use the sorting options provided on the Github. For example, you can sort repositories by the number of forks, the number of stars, the last time they were updated, and so on. To do this, simply click on the relevant sorting option from the dropdown menu on the GitHub page. This will rearrange the list of repositories according to the selected sorting criteria.

Or Alternatively you can visit: https://github.com/8bitPit/Niagara-Issues>Release>Tap on each build and read the changelog.

**Comment by 8bitPit** [comment]
Thanks for your feedback, @notepadnine. Yes, we only accepted implemented/fixed [around 100 feature requests and bug reports from GitHub](https://github.com/8bitPit/Niagara-Issues/issues?q=label%3A%22in+progress+%2F+implemented%22+) since the end of 2020. In my opinion, too much complexity and adding stuff on top of each other is one of the significant issues yearlong software projects struggle with.
