### ISSUE TITLE
Quick-lock gesture security improvement

### ISSUE THREAD

**Issue by ShadowVoyd** [8bitPit/Niagara-Issues#2165]
### Describe the solution you'd like

A togglable setting that makes the "quick-lock gesture" lock the screen AND prevents using biometrics to unlock the device, thus forcing a pin, pattern, password in order to unlock. I have seen security oriented apps accomplish this. An old app called "Trigger" used to do this as well.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Sorry, Third party launchers do not have the ability to control the lock screen. The double tap feature simply locks the screen, and all other functions related to the lock screen are managed by the phone's operating system.

However if your Android device supports it, you can use the Lockdown mode feature that is natively provided by Android by pressing the power button

To know more about the feature you can refer to this article:
https://www.lifewire.com/use-android-lockdown-mode-6287933

**Comment by Amorphous404** [comment]
There is already an article that discusses this topic in detail and explains why the "Device admin" method is not the preferred approach for blocking biometric authentication. It is likely that the app you mentioned uses this method.

https://help.niagaralauncher.app/article/73-lock-screen-on-older-android-versions
