### ISSUE TITLE
Adjustable delay on app switcher gesture

### ISSUE THREAD

**Issue by SelfDestructor** [8bitPit/Niagara-Issues#2166]
### Is your feature request related to a problem?

The swipe up and hold gesture to get to the app switcher currently takes about a whole second to activate compared to the quarter second it currently takes on my Samsung phone from other apps or system menus.

### Describe the solution you'd like

It would be great if the delay for the swipe up gesture could be adjusted, either freely or maybe choose between a few different steps, for example 0.25, 0.50, 0.75 and 1 second.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
![Screenshot_2023-01-01-23-23-57-55_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/96917972/210180290-587ab0b9-efc6-4703-b748-51358af703c2.jpg)

https://help.niagaralauncher.app/article/114-recent-apps-screen-issues
