### ISSUE TITLE
Q-Recently used apps

### ISSUE THREAD

**Issue by JoroBGGalaxyS21U** [8bitPit/Niagara-Issues#2170]
### Is your feature request related to a problem?

How can I get access to my recently used apps? Not favorites, but recently used? Its always send me to recently installed...thanks

### Describe the solution you'd like

I preffer to send me to recenly used instead of recenly installed.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Are you asking to show recently used apps in the Favorites screen or Niagara search page?

**Comment by Amorphous404** [comment]
Or Guessing by your name, it seems you have a samsung device 😅, i think your facing issues with calling the recent screen page, if yes, that's a samsung limitation, you have to swipe up and hold for a second.

Please let me know if it helped fix the issue.

**Comment by JoroBGGalaxyS21U** [comment]
Thank you, I found it :) Only my suggestion is to change in Niagara recentlly installed with recentlly used. Will be more lovely for me :)

**Comment by Amorphous404** [comment]
You're welcome, regarding the recently used apps feature, please refer to this ticket and add your feedback/suggestion.

https://github.com/8bitPit/Niagara-Issues/issues/1833
