### ISSUE TITLE
Foldable - separate homescreens

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2176]
### Is your feature request related to a problem?

Using a foldable such as Fold 4 it would be useful to be able to set two separate homescreen one for the cover screen and one main screen to utilise the space for efficiently for different use cases. 

For example I use the cover screen for quicker action such as phone calls, checking messages but the main screen for reading articles, watching videos so it woudl be, helpful to set different favourites for both screens. 

### Describe the solution you'd like

Niagara recognises the wider format of the main screen so a toggle in settings 'separate home screens' could allow both screens to be treated independently. Set separate favourites, maybe even hide different apps. Essentially set two discrete home screens.

Setting an addtional widget to again use the extra space in the main screen woudl be appreciated too

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
This feature has already been requested, you can follow this ticket and add your suggestion here:

https://github.com/8bitPit/Niagara-Issues/issues/1707
