### ISSUE TITLE
Stackable widgets

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2177]
### Is your feature request related to a problem?

I appreciate the clean interface of Niagara. It can soemtiems feeling limiting particularly when trying to access widgets. Often I woudl liek to see (or access) more than one easily

### Describe the solution you'd like

Rather than add lots of widgets (though I'm not averse to at lesst allowing users to add more) a cleaner solution might be stackable widgets like in IOS and Oneui. This way you view one widget at a time but can swipe on the widget to access other widgets

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hey, thanks for requesting, happy to tell you it's already planned, you can follow this ticket:

https://github.com/8bitPit/Niagara-Issues/issues/1330
