### ISSUE TITLE
Calendar widget not showing events correctly

### ISSUE THREAD

**Issue by kennedybaird** [8bitPit/Niagara-Issues#2178]
### Describe the bug

Best explained through this picture, it seems very regularly calendar events are not showing correctly.

I am using Google Calendar.

I've attached the settings page and you can see that all events are turned on. I'm not sure what I'm doing wrong, as it seems this should function correctly.

### Steps to reproduce

As pictured

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Sony Xperia 5 II

### Android version

Android 12

### Screenshots / Screen recordings

![image](https://user-images.githubusercontent.com/20593811/213257418-c0ffb28e-deb4-43f0-88d5-4caa0e29a2f2.png)

**Comment by Amorphous404** [comment]
It's an Andorid limitation, it takes some time to sync calendar events in third party apps,

I hope the troubleshoot methods mentioned outlined in this article helps fix the issue:
https://help.niagaralauncher.app/article/76-calendar-faq
