### ISSUE TITLE
Disable Media Thumbnail

### ISSUE THREAD

**Issue by ahartstein** [8bitPit/Niagara-Issues#218]
Any chance we could get the ability to turn off the thumbnail? Just have info and controls, maybe the app icon that is playing from, in the same style as the rest of the launcher.

**Comment by 8bitPit** [comment]
Idk why you would like to disable the artwork.

**Comment by ahartstein** [comment]
Sorry I didn't get back to you quick enough, I work the weekends.

I have attached two screenshots both of which the thumbnails are cropped
and can't read them, in my opinion it looks weird. I would much rather opt
for no artwork and have more information about my Media.

**Comment by 8bitPit** [comment]
Oh, I'm sry I  cannot see your screenshots in GutHub
