### ISSUE TITLE
Hiding work profile apps if work app toggle in quick access drawer is turned off in 

### ISSUE THREAD

**Issue by peterjheffernan** [8bitPit/Niagara-Issues#2180]
### Is your feature request related to a problem?

I have work apps on my personal phone. When I turn off work apps in the pull down toggle menu on android the work apps are greyed out. It would be nicer if they were hidden and unhidden on the use of the work app toggle button. 

### Describe the solution you'd like

As above! The greyed out Outlook. Could it be hidden until work apps are toggled back on. 

![Screenshot_2023-01-20-17-04-03-29_a4824db61f40c53807964ea8b14c92fe](https://user-images.githubusercontent.com/123194292/213760180-349737bb-5bc6-437f-8356-917fb5bfa96c.jpg)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
We have plans to add a dedicated section for work apps, Kindly please drop your suggestion to this already existing ticket:

https://github.com/8bitPit/Niagara-Issues/issues/537
