### ISSUE TITLE
Swipe-able widgets on the home screen. 

### ISSUE THREAD

**Issue by Stalkerz37** [8bitPit/Niagara-Issues#2181]
### Describe the solution you'd like

As of now, we can only have 1 widget at the top of the homescreen. If it's possible, I would like to be able to favorite a certain amount of widgets (RAM cleaner, Smart TV etc), and scroll through them at the educated cost of system resources.

Been using Niagara for years and I can say it's come a long way. Appreciate the work! 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
It's Planned, please refer to this already existing ticket:

https://github.com/8bitPit/Niagara-Issues/issues/1330
