### ISSUE TITLE
More flexible horizontal positioning for custom widget

### ISSUE THREAD

**Issue by alexdonh** [8bitPit/Niagara-Issues#2182]
### Is your feature request related to a problem?

Many widgets are horizontally responsive but there are only 2 options as of now: either not fill-screen or fill-screen...

### Describe the solution you'd like

Instead of having only fill screen on and off, I think it would be more fun and nice if we could "resize" (or re-position) the custom widget horizontally.

I would imagine it being dynamically "draggable" just like how it currently is vertically so that we can drag it all the way to the left, right, center or fill-screen, or basically any position we want. 

If dragging is troublesome, a 4-choices setting as an alternative to fill screen would work too. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hey, Niagara launcher doesn't have a grid system, so it's difficult to directly offer horizontal widget alignment feature, for now you can use the secret command mentioned below in the Niagara search.



Horizontal resizing and alignment options ‧ This feature is not fully ready yet, nevertheless we’re interested in hearing your feedback to integrate your feedback as early as possible. With the secret command **/resizex** you can also resize custom widgets horizontally and simultaneously change their horizontal alignment. Here’s an example of how it works: **/resizex.30.L**, sets the width to 30% of the widget’s default width, and aligns the widget to the left. If you want to keep it centered, omit the .L at the end.


**Source:** 
[Design Update: Fresher & Cleaner (Medium)
](https://medium.com/niagara-launcher/design-update-fresher-cleaner-3593149dbfbb)

**Comment by Amorphous404** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/1355

**Comment by alexdonh** [comment]
Thank you for the quick response.

The secret command works perfectly on my end! in terms of UX I would imagine it being draggable-but-sticky to the left, right or center, then having a resize bar just like how it does in vertical. That should do it!

**Comment by Amorphous404** [comment]
Can you please forward your suggestion to the issue i linked #1355, thank you.

**Comment by Amorphous404** [comment]
- Merged with #1355
