### ISSUE TITLE
An invisible bar remains if Niagara Widget is completely replaced with a 3rd party one.

### ISSUE THREAD

**Issue by Rokcy98** [8bitPit/Niagara-Issues#2185]
### Describe the bug

Hello, I'd like to report a bug (I guess it's a bug).
Even if every part of Niagara widget is disabled (the widget is replaced by a third party one), an invisible bar remains there and redirects you to the agenda, if you click on it.
In my opinion, it would be better to have it totally disabled, if I decide to hide the date.

### Steps to reproduce

https://user-images.githubusercontent.com/62332789/214357864-8c8e0450-1778-4de7-8035-7d97855b935f.mp4

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Asus Zenfone 8

### Android version

Android 13

**Comment by Amorphous404** [comment]
It is a bug indeed, but we kept it in because some users found it cool to still have a way to access Niagara's agenda that way

**Comment by Rokcy98** [comment]
We talked already about this on discord, and many users find it annoying, mostly because it's now possible to reach the agenda with the Niagara button. From what I understand, you kept this bug because Niagara button wasn't a thing yet, maybe it's time to remove it now

**Comment by 8bitPit** [comment]
That's a good point, @Rokcy98; we'll fix this with the next update.

**Comment by Rokcy98** [comment]
Wow, thank you very much!

**Comment by 8bitPit** [comment]
Fixed in v.1.8.12: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by Rokcy98** [comment]
This bug has just come back in version 1.9.6 @8bitPit
