### ISSUE TITLE
Removing shortcut leads to an error

### ISSUE THREAD

**Issue by bastschonet** [8bitPit/Niagara-Issues#2186]
### Describe the bug

Pixel 4a, Android 13 update 5 (Jan 2023)
Niagara Launcher 1.8.6

shortcut added to the homescreen (e. g. google maps) 
**removing** the shortcut via context menu (long press) leads to the following error message:

_Error message: NougatShortcutOpException(Pin state already set)
Error occurred with Niagara Launcher v1.8.6 on a Google device which runs Android 13 on 2023-01-16T05:35:50Z. My crash user id is 'none'._

**Interestingly, this occurs not with every shortcut. But with googlemaps it's reproducable.**

Removing the shortcut by editing the favorites list works fine.

Tried "Restart launcher", cleared cache, restart device... Error remains.

### Steps to reproduce

goto homescreen
long press shortcut (e. g. google maps)
tap remove

leads to an error message (see description of bug)

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 4a

### Android version

Android 13

### Screenshots / Screen recordings

_Error message: NougatShortcutOpException(Pin state already set)
Error occurred with Niagara Launcher v1.8.6 on a Google device which runs Android 13 on 2023-01-16T05:35:50Z. My crash user id is 'none'._

**Comment by bastschonet** [comment]
by testing further I found, that this error occurs with **every shortcut** which was added, although it was already present in the favourite list. 

In short: **if the shortcut was added twice.**

**Comment by Amorphous404** [comment]
We fixed shortcut related issue in v1.8.7, Could you please update to this latest build and let us know?

https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.8.11

**Comment by bastschonet** [comment]
Thanks. It works now.
