### ISSUE TITLE
Weather Widget is not working/not showing

### ISSUE THREAD

**Issue by siddharthjain25** [8bitPit/Niagara-Issues#2187]
### Describe the bug

I recently purchase Niagra pro but the weather widget is not working :(

### Steps to reproduce

.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Realme narzo 50 pro

### Android version

Android 13

**Comment by Amorphous404** [comment]
Please refer to this article:
https://help.niagaralauncher.app/article/105-weather-widget

If the issue still persists, please contact us via Email mentioned in the bottom of the article, along with the Order ID

[Looking up Your Order Number](https://help.niagaralauncher.app/article/18-looking-up-order-number)
