### ISSUE TITLE
Phone & Camera quick launch

### ISSUE THREAD

**Issue by pradyw** [8bitPit/Niagara-Issues#219]
Hi, Anything we can do to make them more accessible by one hand, other than adding more fav. & drop down them. thanks

![screenshot_20180915-181315](https://user-images.githubusercontent.com/43058329/45586358-c2e36600-b913-11e8-9d70-47d452e3690e.png)

**Comment by 8bitPit** [comment]
Most phones do have a toggle for opening the camera app, so idk if that's needed.

**Comment by pradyw** [comment]
Sorry, Which type of toggle? I want to enable that.

**Comment by 8bitPit** [comment]
E.g. double tap on power button or home button.

**Comment by pradyw** [comment]
Thanks for reply. 
 i don't have this option. But if any chance of invert position of favt. & Suggested apps.

**Comment by 8bitPit** [comment]
The Google button on the bottom right could be customizable, so you can launch any app with it. What do you think?

**Comment by Alexrodma** [comment]
It would be great! I have never used Google button but I'm a camera heavy user.

**Comment by 8bitPit** [comment]
Great. I'll merge this issue with https://github.com/8bitPit/Niagara-Issues/issues/175

**Comment by 8bitPit** [comment]
Merged with #175
