### ISSUE TITLE
Text colour unaffected by colour of live wallpaper after upgrade from Android 11 to 12.

### ISSUE THREAD

**Issue by rokejulianlockhart** [8bitPit/Niagara-Issues#2193]
### Describe the bug

The colouration of the application labels is unaffected by the colour of my live wallpaper after upgrading from Android 11 to 12.

Stock OS.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Fairphone 4

### Android version

Android 12

**Comment by rokejulianlockhart** [comment]
Realized that reapplication of the Live Wallpaper remediates the problem. Although since Niagara was regardless using #ffffff text on a #ffffff wallpaper, it remains a bug, but I doubt that it's important enough to bother diagnosing.

**Comment by rokejulianlockhart** [comment]
Please reopen, @Amorphous404: I have realized after a reboot of the smartphone that the problem actually merely occurs upon reboot, which explains the document behaviour. Indeed, the way to fix it temporarily remains to be reinitialization of the live wallpaper, but the fault lies with Niagara since it fails to acquire the colour of the wallpaper upon initialization of the device.

**Comment by Amorphous404** [comment]
Please refer to this ticket/comment:

https://github.com/8bitPit/Niagara-Issues/issues/2147#issuecomment-1366036180

**Comment by rokejulianlockhart** [comment]
@Amorphous404, https://forum.fairphone.com/t/fairphone-provides-incorrect-colour-to-launchers-after-reboot-until-live-wallpaper-has-been-reinitialized/93213?u=rokejulianlockhart
