### ISSUE TITLE
Request: better search

### ISSUE THREAD

**Issue by hyperterminal-byte** [8bitPit/Niagara-Issues#2195]
Niagara's swipe down to search feature is really handy for opening apps quickly, however I found it to be quite inefficient in two particular regards which prompted me to request for search to be made better. 

## #1
Display the app pertinent to search query by cross-combining characters from multiple words - in case the app's name consists of two or more words. For example if I want to search for Samsung Health I input `she` and Samsung Health shows up in the search results, wherein the `s` represents the first word; Samsung and the `he` represents the second word; Health.

## #2
Display an app in the search results even if query is slightly mismatched. For example if I type `tle` instead of `tele` still display Telegram in search results.

I hope my request is considered. I do understand if implementing said improvements in search is not technically feasible, I'm not sure how the tech behind Niagara search actually works but this is just my feedback as an end user on enhancing the user experience.

**Comment by Amorphous404** [comment]
Hi @hyperterminal-byte, it appears that your issue is similar to request #411. I suggest that you add your input to the linked issue.

https://github.com/8bitPit/Niagara-Issues/issues/411

**Comment by Amorphous404** [comment]
Hi @hyperterminal-byte, it appears that your request is similar to issue #411. Could you please forward the same to the linked issue.


🔗 Merged with #411
