### ISSUE TITLE
Recent apps overview in navbar

### ISSUE THREAD

**Issue by fingersteps** [8bitPit/Niagara-Issues#2200]
### Describe the solution you'd like

I would love to see the stock android Recent Apps menu (square button on navbar) 
be customized to fit the Niagara launcher theme. Right now my recents menu and niagara kind of clash and the recents look clunky in comparison. I'm not sure this is even feasible in android but it would be a great addition to the launcher. Sorry if this is a duplicate

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @fingersteps, Unfortunately, third-party launchers do not have the ability to alter the navigation buttons as they are set by the system. Nevertheless, there are various third-party apps that offer customization options for these buttons, which you may consider using as an alternative.

**Comment by fingersteps** [comment]
I just found this https://forum.xda-developers.com/t/module-3-3-1-quickswitch-quickstep-enabler-for-supported-launchers.3884797/ . Could it be of any help? It might be a stretch but if it's feasible I don't see why not.

**Comment by Amorphous404** [comment]
My apologies, but this module is specifically designed for users who have rooted their device and enables them to switch their recent screens. Unfortunately, it does not offer any customization options for buttons you're looking for.
