### ISSUE TITLE
D-Pad Support For App selection for Flip Phone

### ISSUE THREAD

**Issue by SamSDK** [8bitPit/Niagara-Issues#2203]
### Is your feature request related to a problem?

I know this may be a niche problem, but I use niagara launcher on a flip phone and I'm always trying but I can't select an app using the D-pad on the phone. I use a SM-G1600 on Android 6.0.1 for reference. If possible I'd like to find a solution to this as I'd love to keep using Niagara on that phone.

### Describe the solution you'd like

I believe this should be a simple feature to add, by simply adding the function to support a D-pad for flip phones. This is purely a functionality request and should not effect the look of the application in any way. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @SamSDK, Your request seems to be similar to issue #2194. Could you please forward your suggestion to that issue?
 

🔗 Merged with #2194
