### ISSUE TITLE
Pop Up Window Dark Mode

### ISSUE THREAD

**Issue by Cdazed** [8bitPit/Niagara-Issues#2205]
### Is your feature request related to a problem?

No option to change pop up windows to dark mode. Light mode in pop up windows make icons with light/white colors difficult to see.

### Describe the solution you'd like

Request the option to change pop up windows to dark mode.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Cdazed, it's already possible. 
Niagara Settings -> Look -> Dark Theme -> Always Enabled.

**Comment by Cdazed** [comment]
Great! Thank you.
