### ISSUE TITLE
Enhancement to agenda 

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#2208]
### Is your feature request related to a problem?

Currently the agenda shows only events and not Tasks added to Google Calendar. 

### Describe the solution you'd like

Adding Tasks that are setup in Google Calendar to show up in agenda is very impactful and does not require hure ui changes. The tasks could have a check marks near them to mark them as completed.

Or provide todoist integration or something to the agenda 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @missyraja, unfortunately Google doesn't share certain types of events with other apps via the calendar API, including Reminders and Tasks.
#1347

![Uploading Screenshot_2023-02-18-16-08-54-09_9c7ad408470e52983cc8816adf9ff347.jpg …]()
https://help.niagaralauncher.app/article/76-calendar-faq

For Todoist integration, please refer to this ticket #1285 and share your suggestions there.

🔗 Merged with 1285
