### ISSUE TITLE
Hide favorite apps from app drawer

### ISSUE THREAD

**Issue by maxloh** [8bitPit/Niagara-Issues#221]
When I open the app drawer, I am finding a app that I didn't add to my home screen. 

It would be nice if you add a option to hide favorite apps from app drawer.

**Comment by 8bitPit** [comment]
Maybe I'll add a toggle for that.

**Comment by 8bitPit** [comment]
The behavior of hidden apps might change in the future, so you can hide an app only from the all apps list. That would give you the freedom to hide all your favorites from it.

**Comment by 8bitPit** [comment]
Implemented in v0.8.2: https://github.com/8bitPit/Niagara-Issues/releases/tag/v0.8.2-beta
