### ISSUE TITLE
Option for a setting to warn about too much screen time

### ISSUE THREAD

**Issue by Pagega7348** [8bitPit/Niagara-Issues#2210]
### Is your feature request related to a problem?

Your launcher has made my life a lot more productive since I got rid of apps like tiktok, for example. But sometimes I notice that I use apps for a very long time. As a result, I miss important things in life and concentrate too little on school.

### Describe the solution you'd like

In these situations, a function that warns me of using my cell phone for too long would help.

The idea is pretty simple:

The user has a switch with which he can switch the function on and off as required. There is a drop-down menu which opens with a simple click and shows times between 5 minutes and one hour (times may vary). If the user switches the function on, he will receive a pop-up message after the set time that he has been using his cell phone for a long time and should perhaps take a break to take care of important things. If the user turns off their display before the time expires, the timer must pause. If the display is switched on again, the timer must restart. The notification only comes if the display is permanently on for a certain period of time. In the message there should be a button to pause this feature for half an hour. this would be useful when doing something important to avoid being annoyed by the message all the time. 

This feature is a useful addition to Focus Mode and Digital Wellbeing and it should increase everyone's productivity without destroying the look and feel of the launcher. it can also be implemented universally.

my problem is similar to one that was addressed some time ago and the solutions suggested there can be easily combined with mine. (Link to the other issue: https://github.com/8bitPit/Niagara-Issues/issues/1811)
### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Pagega7348, thank you for your thorough request. I have noticed that it bears similarities to issue #1784 which has already been reported. To prevent any duplication, could you please add your request to that existing issue? Your cooperation is greatly appreciated. Thank you.

🔗 Merged with #1784
