### ISSUE TITLE
current app is hidden after screen unlock

### ISSUE THREAD

**Issue by krych14m** [8bitPit/Niagara-Issues#2216]
### Describe the bug

Current app is hidden when screen is unlocked.

### Steps to reproduce

1. open any app
2. lock screen
3. unlock screen via fingerprint reader or lock password/code/pattern
4. launcher is visible, but previously opened app is expected to be visible

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

original phone launcher

### Device name

vivo Y72 5G (V2041)

### Android version

Android 13

**Comment by Amorphous404** [comment]
Hi @krych14m, thank you for reporting . Operating system is responsible for returning to the previously used application, not the Launcher. As far as I know, Vivo's FuntouchOS has a reputation for being quite aggressive in killing apps running in the background to conserve battery power. Please check whether any of the battery-saving settings are responsible for the problem you're experiencing.

**Note**: Stock Launcher won't have restriction as it part of OS, Could you please check if the same with another third party launcher like Nova or Lawnchair Launcher.

**Comment by krych14m** [comment]
Oh yes, it helped.
I forgot about this beautiful feature which battery saving is. 😁
Thank you for this tip, I'm closing bug.
