### ISSUE TITLE
Cannot re-install PWA shortcuts that have been moved to app list and then removed

### ISSUE THREAD

**Issue by nagisa** [8bitPit/Niagara-Issues#2221]
### Describe the bug

When a [progressive web app](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen) shortcut that has been moved to the App List is removed, adding it again won’t work until the launcher is restarted.

This does not affect the PWA shortcuts that haven’t been moved to the App List. Restarting the launcher works around the issue.

Version 1.8.15

### Steps to reproduce

1. With Firefox navigate to any website (for this one I have chosen https://news.ycombinator.com)
2. Click the tree-dot kebab menu;
3. Select “Install” or “Add to Home screen” (this will change based on whether the website has PWA metadata);
4. Go through the steps to have the app added to the favourites menu;
5. In Niagara’s Favourites list, open the context menu for the new shortcut by holding it for some time and select “Show in app list”, when asked about removing it from the favourites say “Sure”;
6. In the app list navigate to the newly added shortcut and remove it;
7. Go back to Firefox and try adding/installing the same website shortcut again. You will be sent back to Niagara’s home screen, but the shortcut won’t get added to either the favourites list, nor to the app list.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Sony Xperia 10 IV

### Android version

Android 13

**Comment by Amorphous404** [comment]
Hi @nagisa, Thank you for letting us know about the issue. I was able to reproduce the bug on Iceraven Browser (a Firefox client). It appears that the issue only occurs when a user attempts to add the same web shortcut immediately. However, I was not able to reproduce the same on Chrome & Brave browser.

**Comment by 8bitPit** [comment]
Hey @nagisa, thanks for the well-written bug report. [Our latest release](https://github.com/8bitPit/Niagara-Issues/releases) should address this issue :)
