### ISSUE TITLE
Stray empty rectangle character in notification summary

### ISSUE THREAD

**Issue by zyklixel** [8bitPit/Niagara-Issues#2225]
### Describe the bug

A white rectangle appears behind the notification content, only if the whole content is displayed.

### Steps to reproduce

1. Install any app that produces short notifications (for testing i.e. the "Notify Me" app
2. Add the app to your notification summary
3. Receive a notification from said app
4. Voilà, you have the stray rectangle after the content (if the whole content is displayed)

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Xiaomi 11T

### Android version

Android 13

### Screenshots / Screen recordings

Screen recording of the bug occuring:
https://user-images.githubusercontent.com/77794519/226460901-c90b0e33-5461-4c9b-9bf2-e93ac3a6a24f.mp4
![Screenshot_2023-03-20-21-45-49-818_bitpit launcher-edit](https://user-images.githubusercontent.com/77794519/226462016-0ca08d3a-4f3a-4a9e-967a-e7351df8ef69.jpg)

**Comment by Amorphous404** [comment]
![Screenshot_2023-03-21-02-49-04-66_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/226468363-f80516aa-19f9-4bb8-9399-2c40337e32c8.jpg)

Hi @zyklixel, Thanks for reporting the issue. I can't reproduce the issue on my end. It could be possible the font you are using is causing the issue. Could you please try switching to a different font (Niagara settings -> Look -> Font) and check if you continue to face the same issue?

**Comment by zyklixel** [comment]
I already tried switching to another font, the rectangle is still there:
![Screenshot_2023-03-21-06-44-27-804_bitpit launcher-edit](https://user-images.githubusercontent.com/77794519/226527581-e5100347-62ab-4136-bab3-7d2da64c713e.jpg)
(now with the standard font, work sans)

**Comment by Amorphous404** [comment]
Strange, which version of Niagrara are you currently on?

**Comment by zyklixel** [comment]
1.8.15, updated through discord

**Comment by zyklixel** [comment]
What now?

**Comment by Amorphous404** [comment]
The development team is investigating the issue and will notify you if they require any additional details or have resolved the issue. We appreciate your patience during this process.

**Comment by timm0e** [comment]
Hey @zyklixel, thanks for your bug report!

We sadly aren't able to reproduce the issue :(

Are you using any Custom ROM, or are you running stock MIUI on your phone?


For anyone else encountering this issue, please join in on this thread.
