### ISSUE TITLE
Lock by double tapping issue

### ISSUE THREAD

**Issue by itsjillard** [8bitPit/Niagara-Issues#2226]
Whenever I lock the screen by double tapping the alphabet, and then unlock my phone, it goes to the app drawer instead of home screen. I think it's because by double tapping alphabet to lock screen, moments before it locks, the app drawer is opened (because by default, tapping alphabet opens app drawer). Therefore, it opens the last thing opened, which is the app drawer instead of opening home screen.

**Comment by Amorphous404** [comment]
Please refrain from creating multiple reports for the same issue :)

**Comment by Amorphous404** [comment]
Duplicate of #1989

**Comment by itsjillard** [comment]
> Please refrain from creating multiple reports for the same issue :)

Yep sorry about that, I didn't realise that there was a format for sending bugs/feature requests.
