### ISSUE TITLE
recognize pop-up apps and folders with Niagara Dots

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#2228]
### Is your feature request related to a problem?

Hi, when I use as Icon Pack Niagara Dots how to recognize individual apps from Folders and Pop-ups? Thanks, I await an answer

### Describe the solution you'd like

Hi, when I use as Icon Pack Niagara Dots how to recognize individual apps from Folders and Pop-ups? Thanks, I await an answer

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Livio78 , In the App list, Pop-up folders are placed at the bottom, so there's a clear distinction.

In the favorites list, You can rearrange the position of the folders (Edit favorites page) to make a distinction, or you can edit the name to something similar;
Folder1🔹
Folder2🔹

Additionally, you can follow #1607, which discusses the customizable dots feature, which might be helpful in your case.

And please wait for sometime before posting queries in multiple forums :)

**Comment by Amorphous404** [comment]
🔗 Merged with #1607
