### ISSUE TITLE
Album Artwork No Longer Shows for Music Player

### ISSUE THREAD

**Issue by TheDoctor50** [8bitPit/Niagara-Issues#223]
After the app's latest update (Version 0.3 Build 2), the Album Artwork of music doesn't show up in the launcher's music player. It worked fine before the update, and I quite liked that feature. Please fix this as soon as possible. (Google Pixel XL, Android 9.0)

**Comment by 8bitPit** [comment]
Which music player are you using?

**Comment by TheDoctor50** [comment]
Google Play Music on a Google Pixel XL running Android 9.0

**Comment by Montell2099** [comment]
I'm using BlackPlayer and it's the same, no image shown in the launcher. None of my local mp3's have any image in their metadata so I don't really care. Soundcloud/Spotify still show images.

**Comment by zamber** [comment]
Same story for Spotify. Playing music on desktop + a download of Discover Weekly got triggered when I ran it.

![screenshot_20180916-213144](https://user-images.githubusercontent.com/557066/45600158-5a21e980-b9f8-11e8-8d59-41e77720a474.jpg)

**Comment by TheDoctor50** [comment]
What icon pack are you using?

**Comment by zamber** [comment]
If I got a cent for each time someone asks me this I would have like 10 cents XD.

@TheDoctor50 Icon Pack Studio, background: black circle @ 5% opacity, logo white, a bit smaller than default.

**Comment by TheDoctor50** [comment]
Nope, just the regular app. The issue seems to only affect local music files (mp3, m4a, ect.).
