### ISSUE TITLE
# Symbol looks weird

### ISSUE THREAD

**Issue by McFaul4** [8bitPit/Niagara-Issues#2233]
### Describe the bug

The # Symbol which is supposed to represent the Apps on the app-list which start with a number looks a bit off.

### Steps to reproduce

I installed "360 reality audio live" and on the right you see the weird # symbol

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

OnePlus Nord

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_2023-03-29-15-50-17-16_a4824db61f40c53807964ea8b14c92fe](https://user-images.githubusercontent.com/116670013/229104288-98471860-ee30-4b4e-a1b2-fc86b0def2b7.jpg)

**Comment by Amorphous404** [comment]
Hi @McFaul4, Thanks for reporting the issue, but the problem is caused by the font you're using. Apply a different font to fix the issue.

**Comment by McFaul4** [comment]
oh sry, I forgot that I use a different font
