### ISSUE TITLE
Two-column widget stack for large screens (e.g. Foldables)

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2235]
### Is your feature request related to a problem?

Stackable widgets and widgets in general on the homescreen are great but on foldables in the main inside screen the widgets are stretched out (see screenshot) 
![Screenshot_20230404_025717_Niagara Launcher](https://user-images.githubusercontent.com/81394097/229773793-13672c13-f414-4126-bf1f-3545984e5bb2.jpg)

### Describe the solution you'd like

Niagara on foldables goes from one column of apps on the outside to two columns of apps on the inside larger screen. It would be good if for widgets it adapted in the same way -  so there are two widgets side by side for the main inside screen and one widget on the outside screen. This way like with apps thr space is being utilised better. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Lorestan00, Thank you for sharing your suggestion with us, I am pleased to inform you that our development team is currently working on incorporating the ability to support two stack widgets on wide screens. If everything progresses as planned, this feature should be available in the upcoming builds.

**Comment by Lorestan00** [comment]
That's brilliant news. Thanks for the update

**Comment by TFackler** [comment]
Added in [v1.10](https://github.com/8bitPit/Launcher/releases).
