### ISSUE TITLE
Folder apps - bulk hide in app list

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2236]
### Is your feature request related to a problem?

With apps are in folders you have to individually hide each one from the app list. Quite a cumbersome process

### Describe the solution you'd like

It would be useful when long press on the folder to have an option to 'hide all from app list' which would apply to all apps in that folder. Easily allows a user to remove duplication of apps in folders and in the app list

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Lorestan00, Your request seems to be similar to issue #1604. Could you please forward the same to the linked issue?

🔗 Merged with #1604
