### ISSUE TITLE
Add Notification Settings Toggle to Niagara Button

### ISSUE THREAD

**Issue by skylordjason** [8bitPit/Niagara-Issues#2238]
### Describe the solution you'd like

Add an action to the Niagara Button that can toggle between notification states (sound/vibrate/silent).

This could be a simple toggle to cycle through states, with the button showing the activated mode.

If a swipe toggle, this could be expanded to display the notification settings when a swipe action starts and the user could quickly swipe up to the notification setting they want to set.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
We appreciate your suggestion, Sorry, we don't have no plans to add the proposed feature as it falls outside of the scope of the launcher. Additionally, implementing this feature would require us to ask users for "Do Not Disturb" permission, which may not be suitable for all users. Furthermore, the feature would not be as versatile as the system-level action, which allows for seamless switching between different states with just one action.

We recommend installing third-party apps such as Sound Profile, which are specifically designed to cater to such use cases and bind this app shortcut/widget to the Niagara button to quickly perform the action.

Example: Sound Profile app Widget + Niagara button swipe up action.
https://user-images.githubusercontent.com/96917972/231276119-02162e1a-001f-4c7d-ab91-fbb72bd353a2.mp4
