### ISSUE TITLE
hello my phone is turkish although niagara launcher's native language is english

### ISSUE THREAD

**Issue by basaransemih** [8bitPit/Niagara-Issues#2239]
### Describe the bug

hello my phone is turkish although niagara launcher's native language is english help me

### Steps to reproduce

hello my phone is turkish although niagara launcher's native language is english

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

nova launcher microsoft launcher

### Device name

htc desire 728 dual sim

### Android version

Android 5.1 (Lollipop)

### Screenshots / Screen recordings

![WhatsApp Görsel 2023-04-10 saat 18 30 34](https://user-images.githubusercontent.com/130384567/230933246-d548c8f1-4cae-4080-89e5-8259689ee69a.jpg)
![WhatsApp Görsel 2023-04-10 saat 18 30 33](https://user-images.githubusercontent.com/130384567/230933253-7ffb8d89-3642-4a06-af93-022358e2d507.jpg)

**Comment by Amorphous404** [comment]
Hi @basaransemih, Thank you for reporting the issue. Could you please mention which Niagara version you are currently on?
- Niagara settings -> Advanced -> App info

**Comment by basaransemih** [comment]
1.9.1 Sent from Mail for Windows From: AmorphousSent: 11 Nisan 2023 Salı 14:32To: 8bitPit/Niagara-IssuesCc: basaransemih; MentionSubject: Re: [8bitPit/Niagara-Issues] hello my phone is turkish although niagara launcher's native language is english (Issue #2239) Hi @basaransemih, Thank you for reporting the issue. Could you please mention which Niagara version you are currently on?Niagara settings -> Advanced -> App info—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Amorphous404** [comment]
Thanks for the info, We will update you once we know about the issue.

**Comment by Amorphous404** [comment]
@basaransemih, Could you please update to our latest beta, v1.9.2, and let you know if Niagara is able to mirror your system language i.e Turkish?

[Niagara Launcher v1.9.2](https://github.com/8bitPit/Niagara-Issues/releases/tag/v1.9.2)

If it still does not reflect the changes, A device restart might help.

**Comment by basaransemih** [comment]
Thank you very much.

9 May 2023 Sal 12:47 tarihinde github-actions[bot] ***@***.***>
şunu yazdı:
