### ISSUE TITLE
Option to Disable suggestions/most used apps

### ISSUE THREAD

**Issue by TheDoctor50** [8bitPit/Niagara-Issues#224]
As of the latest update (Version 0.3, Build 2), users only have the ability to limit app suggestions. Please allow the ability to completely disable app suggestions.

**Comment by 8bitPit** [comment]
You can disable the rest manually by long pressing the app which you wouldn't like to see.

**Comment by ShadowXOR** [comment]
Yes please.

**Comment by dvan76** [comment]
Plus one.....
I like that it is minimalist, then you try getting fancy and littering it all up. Please just leave the home page alone ...

**Comment by paddynski** [comment]
Would like that too.

**Comment by abhijain2912** [comment]
Yes please.

**Comment by PaulBags** [comment]
Stop all suggestiins please. Yeah you *could* disable sugfestiins per app for every app, but, why? Why this at all?

**Comment by frederickrl** [comment]
Mark my +1 I would also love to see a Home screen without suggestions! Much Love!

**Comment by 8bitPit** [comment]
Implemented in v0.22.
