### ISSUE TITLE
Vertically center home screen content when long

### ISSUE THREAD

**Issue by atasak** [8bitPit/Niagara-Issues#2240]
### Is your feature request related to a problem?

My home screen is usually pretty full, because I have 8 apps I regularly use and want to keep on there. This is usually no problem, but when notifications start to enter the home screen, it can get a bit long. See screenshots attached. 

![Screenshot_20230410-204348](https://user-images.githubusercontent.com/12663070/230975563-6844e840-30a5-40b1-93a9-423e90800db3.png)
![Screenshot_20230410-204338~2](https://user-images.githubusercontent.com/12663070/230975614-27b53fdd-840d-449a-8d27-5770420b222d.png)

### Describe the solution you'd like

I don't require an always automatic centering option. This has already been discussed in issue #1974, which was rejected. I think, however, that I do have a different use case here. 

My solution would be to only auto center when the content gets over a certain threshold. For example, when the spacing at the bottom is less than half the spacing at the top, the home screen would automatically center such that the space at the top is exactly double that of the space at the bottom. 

I'm not a (UX)-designer, but I think this would not even need a toggle. This could just be automatic behavior, since it only appears when the home screen is excessively long. I would like to hear other people's opinion on this, though. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

_Edit: as always, the attachments have been forgotten_

**Comment by Amorphous404** [comment]
Hi @atasak, Thank you for sharing your suggestion. While I find the idea intriguing; however, I'm unsure whether there is a clear point to determine the spacing at the bottom of the favorite page, given that there is no set limit on the number of favorite apps, and the page is scrollable, but I might be wrong here; therefore, I'll leave this issue for the dev team to review it.

Additionally, I would like to propose another solution to limit the excessive shifting; Maybe we could limit or automatically adjust the notification previews to a single line similar to the pop-up folder (perhaps an option in the notification previews setting page).

Example: It becomes more apparent when all the favorite apps have pending notifications, and one doesn't feel inclined to address them instantly.
![Notification Previews.jpg](https://user-images.githubusercontent.com/96917972/231302966-a2f8953e-7f42-4e74-92cf-7e2100fef365.jpg)

**Comment by Amorphous404** [comment]
Hi @atasak, I just had a chat with the developers, but unfortunately, the dynamic nature of the favorite page makes it difficult for us to incorporate your proposed feature.

Tip: If the notification previews on your favorite page cause an excessive shift, you can disable notification dots permission for your favorite apps. This will disable the previews whilst keeping the embedded app notifications.

• Long press on the app -> App info -> Manage Notification -> Notification dot/badge -> Disable

![Notification Dots.jpg](https://user-images.githubusercontent.com/96917972/233119341-1ed589e1-df30-4095-94e8-bdaf6c628110.jpg)

**Comment by atasak** [comment]
Thank you for checking. It would have been nice, but if it is not feasible, then it won't happen. Good luck with the rest of your project, I have been using the launcher for a few years now and I love it :)
