### ISSUE TITLE
Auto light/dark icons for Lawnicons

### ISSUE THREAD

**Issue by Kuladeep1996** [8bitPit/Niagara-Issues#2245]
### Describe the bug

After applying Lawnicons as iconpack. Icons are not changing with respect light and dark mode.

### Steps to reproduce

Apply Lawnicons as iconpack.
Change launcher from light to dark mode.
Still icons will be in light mode

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Realme 7

### Android version

Android 12

**Comment by Amorphous404** [comment]
Hi @Kuladeep1996, Official [Lawnicons](https://github.com/LawnchairLauncher/lawnicons/releases/tag/v2.0.0) has already been added to the launcher's auto-refresh list; hence it should automatically refresh its color and theme.

Note: In Niagara, Dynamic Icon Packs follow launcher theme settings; if you want the icon pack to follow your system theme, Ensure that Niagara settings -> Look -> Dark theme option is set to "Use device theme."

**Comment by Kuladeep1996** [comment]
![Screenshot_2023-04-16-09-29-57-81_a4824db61f40c53807964ea8b14c92fe~2](https://user-images.githubusercontent.com/74226018/232265832-e42fd288-fc11-4a71-a810-86204d5a53e1.jpg)
Currently I'm using Niagara v1.9.1, is Lawnicons auto refresh enabled in this version?

I'm using the same option you mentioned but system/Niagara is in light mode but icons are still in dark mode.

Tried restarting launcher but it didn't work

**Comment by Amorphous404** [comment]
Yes, it's done remotely.

Do you use any VPN/DNS/Ad-blocker services that block Google's domain?

Additionally, Run this command and check if it helps:
/Refreshremoteconfig

**Comment by Kuladeep1996** [comment]
I'm using DNS, due to that it's not enabled..
Removing DNS and ran the command you gave. Now icons are changing as expected, thanks

**Comment by Kuladeep1996** [comment]
Due to DNS it's not enabled

**Comment by Amorphous404** [comment]
Glad to know! Thanks for the update.
