### ISSUE TITLE
Option to put the home page at the bottom of the app list

### ISSUE THREAD

**Issue by honguyenminh** [8bitPit/Niagara-Issues#2246]
### Is your feature request related to a problem?

I usually hold down the app list bar, but then would want to go the home screen. This can be done by swipe up to the star icon. But it's all the way on the top, and on a tall phone, especially holding the phone with one hand, this is extremely uncomfortable.

### Describe the solution you'd like

Currently, when you are inside the app list, you can swipe up to the "star" icon at the top of the alphabet to go back to home. This is a bit clunky and hard to reach on a tall screen.
An option to put this at the bottom instead of the top would be phenomenal. It's easy to reach when holding the phone with one hand too.
![Screenshot_20230416-121246~2](https://user-images.githubusercontent.com/32929093/232272378-7ad479ce-9f8c-451d-aafe-1c37758a9c53.png)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @honguyenminh, Thank you for your suggestion. Sorry, but we don't plan to change the position of the favorite/star icon to the bottom as this behavior change will not be well-received by all users, and it will require us to add a toggle, which we don't find impactful enough.
[Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)

Tip: You can use the back navigation button or gesture to return to your favorite page.

However, there is an open discussion about adding support for an adjustable scroller (See #334). If this feature gets incorporated into the launcher, it will hopefully resolve the issue you are currently experiencing.


🔗 Merged with #334
