### ISSUE TITLE
Starting a scroll from alphabet characters #, A, B, C doesn't continue when sliding down.

### ISSUE THREAD

**Issue by weardo** [8bitPit/Niagara-Issues#2247]
### Describe the bug

The alphabet navigation for all app list on left/right of the screen doesn't continue when starting with characters #, A, B, C. Starting scroll from other characters work properly.

### Steps to reproduce

1. Start alphabet navigation scroll from any one of the following characters #, A, B, C
2. Continue sliding down the screen without lifting finger.
3. Slider drops and doesn't continue sliding down similar to when lifting finger from the slider.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Motorola G52

### Android version

Android 12

**Comment by Amorphous404** [comment]
Hi @weardo, Thank you for reporting the issue. Could you please provide:

• A screen recording showcasing the issue.
• Mention the Niagara version you are currently on:
Niagara settings -> Advanced -> App info

**Comment by weardo** [comment]
Link for the screen recording: https://youtube.com/shorts/zZetCeStEjE
Version: 1.8.15
Niagara Pro Enabled

**Comment by weardo** [comment]
Closing this as issue seems to be device specific and related to hardware screen.

**Comment by Amorphous404** [comment]
Thanks for the update.
