### ISSUE TITLE
Show the pop-up folder in the alphabet list

### ISSUE THREAD

**Issue by ms-2525** [8bitPit/Niagara-Issues#2253]
Add an option to show the pop-up folder in the alphabet list. I like how we can rename any app and then it appears in that alphabet list.
I want the pop-up folders too to appear in alphabet list based on the name of the folder.
The whole appeal of niagara is that we can quickly find apps by going to the alphabet and so pop-up folders should also be in alphabet list rather than a separate pop-up folder list

**Comment by Amorphous404** [comment]
Hi @ms-2525, Thank you for your suggestion. Unfortunately, I regret to inform you that, at this time, we do not have any plans to display the pop-up folders in the alphabetical list.

----------

Tip: Although the pop-up folders are listed separately at the bottom of the app list, you can quickly access them by tapping the 🔹 icon on the alphabet scroll bar.

https://user-images.githubusercontent.com/96917972/233723328-16d3d648-5424-45a6-acfa-2be9040f3bbd.mp4
