### ISSUE TITLE
Media widget doesn't show SoundCloud cover art on Android 13

### ISSUE THREAD

**Issue by DatHypnoboi** [8bitPit/Niagara-Issues#2254]
### Describe the bug

When playing music with SoundCloud, the song cover art does not display on the media widget. It displays normally on the Android 13 media player and lock screen. Seems like it's probably an Android 13 specific issue, as it works on my old phone running Android 12, but not my new one running 13.

### Steps to reproduce

1. Play a song on SoundCloud on Android 13
2. Look at media widget

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6a

### Android version

Android 13

### Screenshots / Screen recordings

Media widget not working on Android 13:
![Screenshot_20230421-001029](https://user-images.githubusercontent.com/25212257/233566781-7a751b44-0f49-4383-b6c2-48c2696cb363.png)

Android 13 media player showing cover art:
![Screenshot_20230421-001049](https://user-images.githubusercontent.com/25212257/233566797-0629dfe6-8f6d-48db-b346-ed2bdc16db6a.png)

Media widget working on Android 12:
![Screenshot_20230421-001547](https://user-images.githubusercontent.com/25212257/233567444-e2e6937e-1b76-4286-b247-3f2ed9d569ac.png)

**Comment by Amorphous404** [comment]
Hi @DatHypnoboi, Thank you for bringing this to our attention. Could you please check if the album art is visible on any KWGT music widget? If you don't have a widget, you can create one by following the instructions shown in the attached video.

Instructions:
https://user-images.githubusercontent.com/96917972/233744820-86b74934-6923-4831-828b-f17ef4214e86.mp4

**Comment by DatHypnoboi** [comment]
![Screenshot_20230426-001430](https://user-images.githubusercontent.com/25212257/234498748-37f5fabc-d4c4-40c4-bb88-5609700bd0a5.png)

**Comment by Amorphous404** [comment]
Thank you for checking. We'll update you once we know more about the issue. Meanwhile could you please mention the SoundCloud version you're currently using?

**Comment by DatHypnoboi** [comment]
2023.04.25-release (180060)

**Comment by DatHypnoboi** [comment]
Thanks for the help btw, absolutely loving Niagara!

**Comment by 8bitPit** [comment]
Thank you for the report and kind words @DatHypnoboi! I could reproduce the issue and discovered why the artwork didn't show.   The fix itself is relatively simple; however, I noticed that the artwork would reload multiple times for the same song. I have to investigate further how to fix this performance issue as well.

**Comment by DatHypnoboi** [comment]
Nice, hope it goes well!

**Comment by Amorphous404** [comment]
• Fixed SoundCloud's media player artwork not loading 

Fixed in [Niagara Launcher v1.9.6](https://github.com/8bitPit/Niagara-Issues/releases/tag/1.9.6)
