### ISSUE TITLE
Angleichung beim Verschieben von widgets

### ISSUE THREAD

**Issue by user2840** [8bitPit/Niagara-Issues#2259]
### Describe the solution you'd like

![Screenshot_2023-04-23-18-05-19-573_bitpit launcher~2](https://user-images.githubusercontent.com/131606831/233850937-abb9f19e-d4a5-48bb-af3e-78ad4e5e1481.jpg)

Ich denke es wäre angenehm, dass wenn man das Widget auf dem Startbildschirm verschiebt und sich die Kalender/Wetter/Akku Anzeige auf der gleichen Höhe wie das Favoriten Zeichen befindet, dass dieses dann kurz einrastet um es so perfekt platzieren zu können.

Die Funktionen wäre ähnlich wie in Word oder Power Point wenn man zwei Textkörper auf die gleiche weite platzieren will.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

----------
Edited by @Amorphous404

I think it would be nice if you move the widget on the home screen and the calendar/weather/battery indicator is at the same height as the favorite icon that it snaps in place for a perfect placement.

The functions would be similar to Word or Power Point if you want to place two text bodies at the same width.

[Translated with Google Translate]

**Comment by Amorphous404** [comment]
Hi @user2840, Thank you for your patience; I'm not sure if I'm getting the correct translations, but If you're looking for a way to align the widget to the left, you can do so with the help of this secret command:

> With the /resizex command, you can also resize custom widgets horizontally and simultaneously change their horizontal alignment. Here’s an example of how it works: /resizex.30.L, sets the width to 30% of the widget’s default width and aligns the widget to the left. If you want to keep it centered, omit the .L at the end.

Source:
[Design Update: Fresher & Cleaner (Medium)](https://medium.com/niagara-launcher/design-update-fresher-cleaner-3593149dbfbb)

**Comment by Amorphous404** [comment]
- Merged with #1355
