### ISSUE TITLE
Set alarm based on sunrise & sunset time

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#2260]
### Is your feature request related to a problem?

Hey this might be too much to ask but this would be a good addition to Niagara's functionality... 

The agenda widget shows the upcoming Sunrise and Sunset time... It Will be helpful if we could click on it to add them to our upcoming Alarms.

There seems to be no way to set alarm based on sunrise or sunset in my system Google clock. So I usually see when is the sunrise and manually open up the alarm app to set it...

### Describe the solution you'd like

A click on the sunrise or sunset icon which will direct us to the system clock app with the add to alarm option selected with the time we just clicked.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @missyraja, Thank you for your suggestion. Unfortunately, clock apps like Google Clock do not allow external apps to create an alarm.

Tip: You may consider utilizing an app like [Sunrise Companion](https://play.google.com/store/apps/details?id=com.macca895.sunriise) that allows you to automatically schedule alarms for sunset & sunset based on your preferred location.
