### ISSUE TITLE
Request: clicking weather in agenda widget could open link to weather in browser

### ISSUE THREAD

**Issue by JoeScho** [8bitPit/Niagara-Issues#2261]
Hi,

Loving the launcher! 

One feature which I think would be in line with your simplicity guideline yet certainly useful would be to have the weather in the agenda widget (pictured below) open a link to the website the data is retrieved from, so that it is easy to get more detailed info.

![Screenshot_20230425_111004_Niagara Launcher](https://user-images.githubusercontent.com/12475501/234246046-408e816a-5841-45ae-b043-e7af4c04f402.png)

Thanks

**Comment by Amorphous404** [comment]
Hi @JoeScho, Great to hear that you are enjoying the launcher! And thank you for taking the time to share your suggestion with us; unfortunately, we don't plan to add support for opening the weather provider's website at this time. However, If you install our weather provider app "[OpenWeather](https://play.google.com/store/apps/details?id=uk.co.openweather)" you can launch it by performing a long tap on the hourly weather forecast card in the agenda panel.

**Comment by Amorphous404** [comment]
- Merged with #407
