### ISSUE TITLE
Sesame and Shortcuts 

### ISSUE THREAD

**Issue by missyraja** [8bitPit/Niagara-Issues#2265]
### Is your feature request related to a problem?

Currently the swipe up gesture seems to be very restricted. Either you have the inbuilt search from Niagara or the Niagara search + sesame integration or completely disable the swipe up gesture. Would love to have more flexibility with it.

### Describe the solution you'd like

Please provide a way to change the swipe up to any shortcut or app that we want.

Alternatively you can integrate other search shortcut providing apps along with sesame. 

[Pixel search ](https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch) this is a very beautiful search and shortcut providing app that is a better at place with it's ui/ux comparing to sesame. Please integrate the app along the lines of sesame... Or just make the swipe up gesture changeable.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
🔗 Merged with #2266
