### ISSUE TITLE
Integrate Pixel Search app with Niagara Search

### ISSUE THREAD

**Issue by gabey14** [8bitPit/Niagara-Issues#2266]
### Is your feature request related to a problem?

Pixel search (https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch) it's an app which bring the pixel launched search bar with features like universal search similar to Sesame so I was thinking if this could also be integrated into Niagara it would be great 

### Describe the solution you'd like

Just give an option to use sesame or pixel search or give an option when we swipe up it should trigger pixel search or inbuilt search of niagara. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @gabey14, Thank you for your suggestion. Unfortunately, at this time, the Pixel Search app does not offer an API that allows other apps to access its data. However, if the Pixel Search app provides a flexible API like Sesame, we'll think about integrating it.

> Give an option when we swipe up it should trigger pixel search or inbuilt search of niagara.
Sorry, to maintain a simple user interface for our users, we don't plan to add support for customizable gesture for the swipe-up action.
• [**Missing Customization Features**](https://help.niagaralauncher.app/article/77-missing-customization-features)

Tip: You can utilize the Niagara button to launch the Pixel Search app.
Example: Long press on the Niagara button -> Edit "Swipe up" action -> Select Pixel Search app.

**Comment by gabey14** [comment]
Hey thanks for the Tip will be using that till they release their API.

**Comment by Amorphous404** [comment]
No problem! I'll mark this issue as closed for now so we can focus on other existing issues. However, we'll certainly reopen this issue once we decide to integrate it. Thank you for your understanding!
