### ISSUE TITLE
Backup / Save themes and settings 

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2267]
### Is your feature request related to a problem?

Currently there is no way to backup / manually save icon themes and / or folders created. If you want to apply a new icon pack and customise icons. Perhaps create some different folders... You will lose the previous settings

### Describe the solution you'd like

I know this has been raised before as purely a backup option but I think beyond that users might want to simply change up their look and setting of the homescreen.. And go back in the future to previous themes.

I woudl add an option where you can simply select backup / Save icons, folders and settings (e. G. Hidden folders etc). Three tick boxes for each and have the option to name the backup. Files are saved locally and there is an option to import.

In 2023 for a major launcher like Niagara this really should be an option... Nova, Action, etc all have this. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Lorestan00, Thank you for your suggestion. To ensure that we have a thorough discussion on the feature, may I kindly ask you to share your thoughts on this existing "[Backup / Save themes and settings](https://github.com/8bitPit/Niagara-Issues/issues/222)" issue? This will help us to have a broader conversation on the same thread.

Additionally, we would appreciate it if you could fill up this forum and share your feedback with us:
[Manual Backup / Export option poll](https://forms.gle/GYNheWY2YQ3BACieA)

Thank you for your cooperation and for contributing your ideas.

🔗 Merged with #222
