### ISSUE TITLE
shortcuts for searching in apps

### ISSUE THREAD

**Issue by user622628252416** [8bitPit/Niagara-Issues#2269]
### Is your feature request related to a problem?

For instance when searching for a location, I am currently required to first search for the corresponding app, open it, and then search for what I was actually looking for.

### Describe the solution you'd like

There already is a "search for more apps" button at the bottom of the search results list. Adding more shortcuts like "search in maps", "search on google" or "search in chrome" would be a logical extension of this design, which would require minimal effort. [Other launchers do it the same way.](https://static1.anpoimages.com/wordpress/wp-content/uploads/2023/04/pixel-search-on-honor-magic-5-pro.jpg)
Optionally, there could be a setting for reordering these shortcuts. However, hardcoded/alphabetical ordering would probably be sufficient for most users, so this might violate the principle of simplicity.
What could interest a larger group of users while making this feature more universial, is the ability to add custom search engines using their url (eg. "https://google.com/search?q=$QUERY$"). If the corresponding app is installed on the device, android opens it in the app instead of the web browser.

The desktop version of Firefox lets users specify the search engine to be used by prefixing their query with @\<searchengine> (eg. @google, @amazon, etc.). Even though the @ symbol is not as easily accessible on mobile keyboards as it is on physical ones, a similar concept could be another extension to this idea. (the "." or "," symbols could be used as a replacements, as they are easily accessible on mobile keyboards, but not commonly used as the first letters of app names)

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @user622628252416, Thank you for your suggestion. This is already possible with the Sesame Integration. You can enable specific apps and reorder their positions. However, To maintain a clean and minimal search result, we have set a maximum limit of three apps.
• [Sesame x Niagara Pro](https://help.niagaralauncher.app/article/20-sesame-integration)
![Screenshot_2023-05-08-00-33-46-07_a4824db61f40c53807964ea8b14c92fe.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/10bb7b65-87cb-4d3b-94f5-3ef9c562579c)

If your request pertains to native app search functionality support, there is an exciting issue. You can refer to this issue #1887

Moreover, the team is actively working on enhancing the existing search feature. We have recently integrated native web search capabilities (See #1501), and glad to let you know we are also exploring the possibility of adding prefix search. If everything progresses as planned, we may introduce this feature in the near future.
