### ISSUE TITLE
"to-do area" within agenda

### ISSUE THREAD

**Issue by Gunt-r** [8bitPit/Niagara-Issues#2273]
### Is your feature request related to a problem?

The user often sets reminders through Google Assistant but struggles with remembering to complete them. They find it difficult to keep track of these reminders and need a more organized and persistent solution to ensure tasks are not forgotten.

### Describe the solution you'd like

The user would like an "agenda section" with a "to-do area" where all the Google Assistant reminders are compiled into a single spot. This area should allow for grouping low priority reminders and ensure that the reminders persist until they are explicitly marked as complete by the user. This feature would help the user effectively manage and remember their tasks, reducing the likelihood of forgetting them.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Gunt-r, Thanks for your suggestion. Unfortunately, Google doesn't share certain types of events with other apps via the calendar API, including Reminders and Tasks.
#1347

However, the team is planning on integrating Todoist. See #1285

🔗 Merged with #1285
