### ISSUE TITLE
Favorite icon blinks after gesture home

### ISSUE THREAD

**Issue by the753q** [8bitPit/Niagara-Issues#2278]
### Describe the bug
EDIT: I see it looks like same thing happens on Oneplus phones, that it's caused by system animations... Feel free to close...

When you gesture swipe home from a favorite app, and the animation finishes, it's icon on Niagara screen blinks out of existence for a split second.
Looks like if it refreshed.

Doesn't happen with back gesture, as that also has a different animation. 

### Steps to reproduce

1. Open favorite app
2. Gesture navigation swipe to go home
3. Animation shows the app icon travel to it's place. When it gets there, there's a 50% chance it blinks

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova Launcher  (it doesn't have the same animation though)

### Device name

realme

### Android version

Android 12

**Comment by Amorphous404** [comment]
Hi @the753q, Thanks for reporting the issue.

> When you gesture swipe home from a favorite app, and the animation finishes, its icon on Niagara screen blinks out of existence for a split second.
Looks like if it refreshed.

Yes, the same reason applies here as well; the system launcher is causing the issue as it is responsible for handling the app closing animation on third-party launchers.

Fact: RealMe, Oppo, and OnePlus stock launchers are essentially the same under the hood, as they all utilize the same code, just a different name.

> Doesn't happen with back gesture, as that also has a different animation.

On third-party launchers back gesture does not trigger the app minimizing animation; thus, you don't observe the issue.

**Comment by Amorphous404** [comment]
🔗 Merged with #2174
