### ISSUE TITLE
Cumbersome to get web links into categories

### ISSUE THREAD

**Issue by daveQD** [8bitPit/Niagara-Issues#2286]
### Is your feature request related to a problem?

Hello,
I am loving the launcher after a few day's use, but find it clunky to get my web page links, created from Firefox, into a category.

What happens is:
I 'install' a page from the Firefox interface, which creates a link on the Niagara home screen.
I long-press that link and select the category I want the link to live in.
I then want to remove the link from the home screen but keep it in the category. But if I choose Remove it gets removed from both home screen and category.

A workaround is to put in in the app list - then it disappears from the home screen and can be removed from the app list without the link being removed from the category. It's good that this is possible, but obviously it is a clunky workaround.

### Describe the solution you'd like

A relatively clean solution could be to put an option in the popup following 'Remove' that allows you to specify 'Remove from home screen' or 'Remove from launcher'. I'm sure there are other ways too.

Thanks for your attention. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hello Dave! Apologies for the delayed response; nevertheless, thank you for your kind words and for reporting the issue to our attention with such thorough details! Indeed, the current flow is not very intuitive, and the team has plans to improve the behavior. For the time being, you can follow the workaround mentioned in #2291 (Point no 2) and follow up on the issue for further updates.

**Comment by Amorphous404** [comment]
- Merged with 2291

**Comment by Amorphous404** [comment]
- Merged with #2291
