### ISSUE TITLE
FR: Ability to use different icon pack for app favorites (than app list)

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#2287]
### Is your feature request related to a problem?

No matter what icon pack you are using, there's typically tens of more or less 'local' apps which icons are not and won't be (due to fact that those just won't be added to the pack by the devs) part of your current icon pack = leaves the visual appeal inconsistent when scrolling app list.

### Describe the solution you'd like

The ideal solution for this would be **to allow the user to define different icon pack icons for the home screen Niagara app favorites** and then (secondary icon pack) utilize e.g. Niagara dots for the app list. This way the visual UX would be much more pleasing and consistent.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by tjsuominen** [comment]
To add and make clearer this request: favorite app_x icon on home page can be different than the same app_x icon on app selector. HTH.

**Comment by Amorphous404** [comment]
Hi @tjsuominen, Apologies for the delayed response, and thank you for sharing your suggestion! We internally discussed this and concluded not to include different icon pack feature in Niagara Launcher. This decision was made to avoid overcomplicating the launcher. Moreover, it would be difficult for us to implement this as Niagara doesn't inherently distinguish the apps on different pages (changes made to an app's icon or name on one page, i.e., favorites or pop-up folders are synced across the launcher).

>No matter what icon pack you are using, there's typically tens of more or less 'local' apps which icons are not and won't be (due to fact that those just won't be added to the pack by the devs) part of your current icon pack = leaves the visual appeal inconsistent when scrolling app list.

That's one of the reasons why we developed the Icon Assistant feature, which allows users to theme icons not covered by the icon pack easily. You can find more information about this feature in the following article: [Icon Assistant](https://help.niagaralauncher.app/article/130-icon-assistant)
