### ISSUE TITLE
Functionality request 

### ISSUE THREAD

**Issue by denni89** [8bitPit/Niagara-Issues#2293]
### Is your feature request related to a problem?

 it would be nice to have a feature oh do it by default that the home screen stays fixed and doesn't move up and down

https://drive.google.com/file/d/1eu2Lcvv5C6hsG6yRqTQMUmzLRFFA2snv/view?usp=drivesdk

### Describe the solution you'd like

it would be nice to have a feature oh do it by default that the home screen stays fixed and doesn't move up and down

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
• Duplicate of #1028
