### ISSUE TITLE
Show multiline text for buttons, i.e., Sort apps button

### ISSUE THREAD

**Issue by ssssamstrup** [8bitPit/Niagara-Issues#2295]
### Describe the bug

Hi Niagara Team
Thanks for a great launcher!

I use a wide typeface (Agrandir Wide Black) I can't see the text for the sorting order (when editing a folder fx.).

I've included screenshots of the issue:
![Screenshot_20230603-111009](https://github.com/8bitPit/Niagara-Issues/assets/4302516/8fd71e10-075d-420c-8e51-b0562c6e9279)
![Screenshot_20230603-111014](https://github.com/8bitPit/Niagara-Issues/assets/4302516/1522347a-1f29-4c5e-9cb5-fbeea23d4a01)

### Steps to reproduce

1. Set typeface to Agrandir Wide Black
2. Edit a folder
3. Scroll down to pick a sorting order

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Sony Xperia XZ2 Compact

### Android version

Android 5.0 (Lollipop)

### Screenshots / Screen recordings

![Screenshot_20230603-111014](https://github.com/8bitPit/Niagara-Issues/assets/4302516/31f9ae5a-d783-4923-8cf7-3fcbe24514f4)
![Screenshot_20230603-111009](https://github.com/8bitPit/Niagara-Issues/assets/4302516/74d60cac-12b4-4f09-b882-afe3ea84b40f)

**Comment by Amorphous404** [comment]
Hi @ssssamstrup, Thank you for reporting! The upcoming update will contain a fix for this issue.

**Comment by 8bitPit** [comment]
Update: We fixed the bug but have postponed shipping the fix until the next major release (v1.10) to ensure we're not introducing new bugs in the next minor release. Sorry for keeping you waiting @ssssamstrup, but rest assured, it won't take that long until we release 1.10 either.

**Comment by ssssamstrup** [comment]
Hi Peter

Just fine, I've figured out what they mean so no worries. Thanks for letting me know. 😊

Best,

✺ Sune Amstrup

Visual Artist and photographer
↝ View artworks | suneamstrup.dk
