### ISSUE TITLE
Option to disable scrolling on main favorites screen

### ISSUE THREAD

**Issue by Bonjei15** [8bitPit/Niagara-Issues#2299]
### Is your feature request related to a problem?

Currently, the whole favorites screen (including widgets) moves when swiping up/down. This makes the gestures for search and showing notifications more difficult. 

### Describe the solution you'd like

I would love the option to disable scrolling on the favorites screen and keep everything fixed in place when swiping up/down. All my favorite apps fit on the screen at once and do not require scrolling.  Also, it would be great if the notification panel would start moving down as soon as I start swiping down as it does in the default launcher. This would make it feel way more simple and intuitive. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Bonjei15, Thank you for your suggestions,

> Currently, the whole favorite screen (including widgets) moves when swiping up/down. This makes the gestures for search and showing notifications more difficult.

The scroll/rubber band effect is there for an aesthetic reason and doesn't slow down the swipe-up/down gesture.
- See #1022

> I would love the option to disable scrolling on the favorites screen and keep everything fixed in place when swiping up/down. All my favorite apps fit on the screen at once and do not require scrolling.
- Please refer to #1028

> Also, it would be great if the notification panel would start moving down as soon as I start swiping down, as it does in the default launcher. This would make it feel way more simple and intuitive.

if you are experiencing sensitivity issues with the swipe down/notification drawer gesture
- Please refer to #1588

**Comment by Bonjei15** [comment]
I guess I don't understand why we can't keep it at system default. The rubber band effect isn't unusable but it's definitely less consistent than One UI. On One UI it doesn't matter what speed you swipe down or how far. The notification shade starts moving as soon as your finger starts moving. On Niagra your swipe has to be a specific speed/length combo or it doesn't work, and the shade doesn't start coming down until the rubber band animation is complete. It just feels clunky.
