### ISSUE TITLE
Foldables Wave Alphabet inconsistency 

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2302]
### Is your feature request related to a problem?

The wave alphabet on a foldable appears in different places on the cover screen to the main screen. On the cover screen it's further down on the screen and is much easier to get to the letter 'A' than the main screen where the alphabet is stretched all the way to the top. See screenshot

![Screenshot_20230609_001612_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/81394097/26be2832-f26b-4456-aab5-5c91ae4b2efe)

![Screenshot_20230608_233330_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/81394097/e283f63b-adf0-4359-95d4-0dbf2fdea3db)

### Describe the solution you'd like

Currently the alphabets position is inconsistent on cover and main screens. The cover screen works well as the alphabet is easy to reach so it would be helpful that the main screen alphabet mirrors it in terms of position. Or an option to alter the position 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Lorestan00, Thank you for your feedback! We want to clarify that the position of elements, such as the alphabet scroller on the screen, is dynamically adjusted based on the height of the device's display. Currently, we do not have any plans to provide options for altering the position of these elements.

For more information, please refer to this article:
[Foldable Device Support](https://help.niagaralauncher.app/article/100-foldable-device-support)

Tip: If you are experiencing difficulty in reaching the top characters, you can access them by dragging the scroller to the bottom.

Demo:
https://github.com/8bitPit/Niagara-Issues/assets/96917972/4819657e-e451-4b1e-a2fd-2cea7b3b3e06

**Comment by Lorestan00** [comment]
The screen height is the same on the cover and main screen. The width is wider on the main screen but that shouldn't make the alphabet appear higher up. 

This seems like a bug / something that wasn't considered.

Also separate to foldables phones vary in size an option to be able to vary the height of the alphabet would help in this scenario and also small hands vs big hands.  

Lots of reasons to address this. On foldable its just inconsistent as the photos show so disappointing this isn't going to be addressed

**Comment by Amorphous404** [comment]
Sorry, I mean they are adjusted depending on the screen size (Screen ratio)

>This seems like a bug / something that wasn't considered.

I don't think so; the mockup posted in the "[Foldable Device Support](https://help.niagaralauncher.app/article/100-foldable-device-support)" article also has the exact placement.
![IMG_20230616_204234.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/b7422488-b758-4992-b54c-eeb12f39b970)
