### ISSUE TITLE
An invisible bar remains if Niagara Widget is completely replaced with a 3rd party one.

### ISSUE THREAD

**Issue by Rokcy98** [8bitPit/Niagara-Issues#2303]
### Describe the bug

The bug mentioned in issue #2185, and previously solved, has just come back with version 1.9.6.

### Steps to reproduce

Click on the invisible bar

### Device name

Zenfone 8

### Android version

Android 13

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/62332789/4542ece9-2326-4b1d-a4ab-4d47d066ac2d

**Comment by real-mizuya** [comment]
I can confirm, it's back and it's annoying 😔 please completely remove it or at least add an option to hide it, if people want/need the gap. Thank you very much

**Comment by Amorphous404** [comment]
Hi @Rokcy98, Thank you for bringing the issue to our attention. The development team has acknowledged the problem and reopened the previous issue. To ensure we don't have any duplicate entries, I will close this issue.

🔗 Merged with #2185
