### ISSUE TITLE
 Quickly accessible overview of all popup folders

### ISSUE THREAD

**Issue by oliver073** [8bitPit/Niagara-Issues#2306]
### Is your feature request related to a problem?

If you have a lot of apps but don't want to scroll forever to find them, you can use pop-up folders.
An overview of all popup folders can currently only be reached by scrolling all the way down in the app list.

### Describe the solution you'd like

Isn't there an easier way to get to this pop-up folder overview? E.g. by swiping up on the home screen, or by gesturing on the Niagara Button?

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @oliver073, Thank you for reaching out! Please refer to this comment: https://github.com/8bitPit/Niagara-Issues/issues/2253#issuecomment-1518277684

- Merged with #2253

**Comment by Amorphous404** [comment]
Thanks for clarifying and for your kind words! While it is possible to turn off the swipe-up to search (Niagara search) gesture, we currently do not have any immediate plans to switch the action to show the pop-up folder overview. Introducing such an option would require adding a new setting, which we believe may not have a [substantial impact](https://help.niagaralauncher.app/article/8-niagaras-design-principles) on the overall user experience. Rest assured, if our decision changes in the future, we will keep you informed.
