### ISSUE TITLE
Weather app

### ISSUE THREAD

**Issue by TopazOracal11** [8bitPit/Niagara-Issues#2307]
### Is your feature request related to a problem?

I am frustrated when I open the weather & calendar menu and I can't then go from there to a weather app.

### Describe the solution you'd like

I would just like it so that when you press the weather and it opens the weather and calendar. You can then press the weather again (or some other button on this menu) to open the in built weather app (or to choose a weather app).

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @TopazOracal11, Thank you for reaching out! You can indeed open up the [OpenWeather](https://play.google.com/store/apps/details?id=uk.co.openweather) app (our current Weather Provider) if you have it installed. To open it, long-press on Niagara Launcher's hourly weather forecast card in the agenda panel.

- Merged with #407

**Comment by TopazOracal11** [comment]
Ah thank you! Apologies for taking up your time.
