### ISSUE TITLE
Automatic Playback Issue with Niagra Launcher When Connecting to Bluetooth

### ISSUE THREAD

**Issue by gitmudassir** [8bitPit/Niagara-Issues#2308]
### Describe the bug

I have been using Niagra Launcher since its beta version and have always been fond of it. However, I have been experiencing a strange issue for the past few months. Whenever I connect my phone to a Bluetooth device, voice recordings on my phone start playing automatically on the system's Music app, which I never use. I have tried various solutions, such as changing the default Music app, clearing the playlist, disabling the Music app, uninstalling updates, and more, but nothing has resolved the problem.

After further investigation, I discovered that Niagra Launcher is actually the root cause of this issue. I noticed that you recently introduced a feature for the Pro version, where a music player automatically launches when connected to Bluetooth. According to your release notes, this feature should only be available for Pro members, but it has negatively affected the Free version as well.

The problem is that there is no option for free users  to disable the option to play the default music app. This means I am forced to listen to unwanted .wav or MP3 files saved on my device every time I connect to Bluetooth, which is a significant setback.

I would love to purchase the premium version of Niagra Launcher, but I hesitate to do so knowing that there are already bugs present in the free version. Regardless, it is crucial to address and fix this issue for the sake of other new users who want to try out the launcher. Thank you.

### Steps to reproduce

1. Keep some MP4 and wav files in your device (the system's music player automatically scans it).
2. Launch the latest version of Niagra free app
3. Connect to any Bluetooth device 
4. See the music player launching forcefully 

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Android launcher, Apex, Microsoft, Nova

### Device name

Vivo 1938

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20230617_190525](https://github.com/8bitPit/Niagara-Issues/assets/52833823/04e16017-7300-4258-a5ce-d761e3992a96)

**Comment by Amorphous404** [comment]
Hi @gitmudassir, Thanks for reporting the issue!

> Whenever I connect my phone to a Bluetooth device, voice recordings on my phone start playing automatically on the system's Music app, which I never use. I have tried various solutions, such as changing the default Music app, clearing the playlist, disabling the Music app, uninstalling updates, and more, but nothing has resolved the problem.

Please check if your system or music player app offers auto-playback feature? If it does, make sure to disable those options.
![IMG_20230617_235544.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/fa03e4fc-189a-49f2-b461-acf5edb9a260)

>I noticed that you recently introduced a feature for the Pro version where a music player automatically launches when connected to Bluetooth. According to your release notes, this feature should only be available for Pro members, but it has negatively affected the Free version as well.

Yes, the Pro version offers a feature where the selected music apps automatically pop up on the favorites page when you plug in your headphones or speakers. However, it doesn't automatically launch and play the music apps. Given that you don't have the Pro version, I don't think this feature is causing the issue.
• [Plug & Play](https://medium.com/niagara-launcher/plug-and-play-da12f66d757b)

If all the troubleshooting steps fail, could you uninstall [Niagara Launcher](https://play.google.com/store/apps/details?id=bitpit.launcher) from your device and check if you continue to face the same issue?

Thanks,
