### ISSUE TITLE
Message bubbles

### ISSUE THREAD

**Issue by CerberusCode** [8bitPit/Niagara-Issues#2314]
### Describe the bug

This message is bouncing everytime i try to minimize. I compare this to my secondary launcher a Nova Launcher & it works as normal like in default launcher. 

### Steps to reproduce

None

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova Launcher

### Device name

Redmi Note 11 Pro+ 5G

### Android version

Android 13

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/65819283/d2f3c2de-0428-4820-9e19-432a5a121b2e

https://github.com/8bitPit/Niagara-Issues/assets/65819283/43e9d488-ada9-44a7-8a07-b2b92daeebdd

**Comment by Amorphous404** [comment]
Hi @user, Thank you for reporting the issue! If the status bar is invisible, the chat bubble is supposed to hide from the launcher screen automatically (Android's limitation). However, it seems it's not working as expected on your device.

Could you enable the status bar in Niagara launcher settings and check if the bubbles continue to have the same animation? Also, please recheck in Nova Launcher, but this time hide the status bar.

Thanks,
