### ISSUE TITLE
Add hidden apps in popups

### ISSUE THREAD

**Issue by Martinligabue** [8bitPit/Niagara-Issues#2315]
### Is your feature request related to a problem?

When adding apps to popups, hidden apps are not listed.

At the moment this can be done by unhiding an app, adding it to the popup and then hiding it again.

This might help those who like to have some apps organised in folders but not visible in the main list, it would be another way to access hidden apps.

### Describe the solution you'd like

At the bottom of the list, there may be a way to list the hidden apps as well.

I searched for similar issues, and I found a bug but it was for the opposite thing. https://github.com/8bitPit/Niagara-Issues/issues/1626

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @Martinligabue, Thank you for reaching out! It's already possible to directly add the hidden apps to the pop-ups. To add them, Long press on the app/folder, Edit [name] pop-up -> Scroll all the way down -> Select hidden apps.

![Screenshot_2023-06-25-06-54-01-76_a4824db61f40c53807964ea8b14c92fe.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/6b813fd5-6ae1-4df3-8f0d-007f6441553d)

**Comment by Martinligabue** [comment]
> Hi @Martinligabue, Thank you for reaching out! It's already possible to directly add the hidden apps to the pop-ups. To add them: Long press on the app/folder -> Edit [name] pop-up -> Scroll all the way down -> Select hidden apps.
> 
> ![Screenshot_2023-06-25-06-54-01-76_a4824db61f40c53807964ea8b14c92fe.jpg](https://user-images.githubusercontent.com/96917972/248521602-6b813fd5-6ae1-4df3-8f0d-007f6441553d.jpg)

you're right, I don't know how when I tried I didn't see it, thanks
