### ISSUE TITLE
List of Material You Icon Packs

### ISSUE THREAD

**Issue by Amorphous404** [8bitPit/Niagara-Issues#2316]
Note: Colors only change/auto-refresh in Android 12+ devices thats supports [Material You](https://www.androidauthority.com/what-is-google-material-you-3272386/).

**Free**

1) [Lawnicons](https://github.com/LawnchairLauncher/lawnicons/releases)

2) [Arcticons You Icon Pack](https://github.com/Donnnno/Arcticons/releases)
-> Select the version
-> Download the You version.
Example: Arcticons-v6.7.1-you-release.apk

**Paid 💵**

1) [Pix Material You Icons](https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.iconpack)

2) [Pix Material You Light/Dark](https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.dark)

3) [OneYou Icon Pack](https://play.google.com/store/apps/details?id=com.pashapuma.oneyou.icons)

4) [OneYou Themed Icon Pack](https://play.google.com/store/apps/details?id=com.pashapuma.oneyou.themed)

5) [OneYou Accent Icon Pack](https://play.google.com/store/apps/details?id=com.pashapuma.oneyou.accent)

6) [Dynamic Material You Icon Pack](https://play.google.com/store/apps/details?id=iconpack.onsurface.monet)

7) [Dynamic Light Icon Pack](https://play.google.com/store/apps/details?id=iconpack.onsurface.monet.light)

8) [Dynamic Dark Icon Pack](https://play.google.com/store/apps/details?id=iconpack.onsurface.monet.dark)

9) [Lavien Adaptive For You](https://play.google.com/store/apps/details?id=osmanonurkoc.lavien.foryou)

10) [Lavien Adaptive For You Outline](https://play.google.com/store/apps/details?id=osmanonurkoc.lavien.foryou.outline)

11) [Epik Material You Icons](https://play.google.com/store/apps/details?id=com.lknninex.epik)

12) [Saga Material You Icons](https://play.google.com/store/apps/details?id=com.lknninex.saga)

13) [Adaptive You Icon Pack](https://play.google.com/store/apps/details?id=com.jndapp.adaptive.material.you.iconpack)

14) [Nothing Material You Icons](https://play.google.com/store/apps/details?id=dev.narikdesign.nothingmaterialyou)

15) [YouLine Icon Pack](https://play.google.com/store/apps/details?id=com.asn360.youline.iconpack)

16) [Lena Adaptive Icon Pack](https://play.google.com/store/apps/details?id=one4studio.iconpack.lenaadaptive)

**Comment by Donnnno** [comment]
Hi! Thanks for making this list, unfortunately Arcticons You is delisted on Google Play currently (due to their vague 'repetitive content' policy). :( 
So for now, the working link is: https://github.com/Donnnno/Arcticons/releases/

**Comment by Amorphous404** [comment]
Hi @Donnnno, I'm sorry to hear that! I hope that Google considers your appeal and reinstates the Icon Pack on the Play Store :) And thank you for letting me know! I replaced the link with your GitHub release page.

**Comment by hanubeki** [comment]
Caelus Adaptive:
https://play.google.com/store/apps/details?id=one4studio.iconpack.caelusadaptive

**Comment by hanubeki** [comment]
Vera Material You:
https://play.google.com/store/apps/details?id=one4studio.iconpack.veramaterialyou

**Comment by hanubeki** [comment]
Nyon Material You:
https://play.google.com/store/apps/details?id=dev.lknninex.nyon.material

**Comment by Donnnno** [comment]
Arcticons Material You is back on Google Play btw: https://play.google.com/store/apps/details?id=com.donnnno.arcticons.you.play

**Comment by 8bitPit** [comment]
Thank you for the list guys! I've now converted this ticket to a help article: https://help.niagaralauncher.app/article/150-list-of-android-material-you-icon-packs. Moreover, Niagara Launcher should automatically refresh all the listed icon packs when changing the wallpaper (can take up to 24 hours to work for the packs @hanubeki added since I just added them)

By the way, I am glad to hear Google Play finally reverted the false strike for you, @Donnnno!

**Comment by hanubeki** [comment]
LuX Adaptive:
https://play.google.com/store/apps/details?id=com.jndapp.lux.adaptive.iconpack

**Comment by hanubeki** [comment]
TOONISH Material You:
https://play.google.com/store/apps/details?id=com.lknninex.toonish

**Comment by Donnnno** [comment]
Arcticons Day & Night isn't a material you icon pack, but is one that switches based on your theme preferences.

I haven't published it on Google Play, due to being scared of getting kicked off the platform again...

But it's downloadable from GitHub & F-Droid:
https://f-droid.org/en/packages/com.donnnno.arcticons.daynight/

**Comment by hanubeki** [comment]
Nothing Material You: Adaptive:
https://play.google.com/store/apps/details?id=dev.narikdesign.nam

**Comment by hanubeki** [comment]
Lavien Adaptive Shady You:
https://play.google.com/store/apps/details?id=osmanonurkoc.lavien.shady.you

**Comment by hanubeki** [comment]
iMaterial:
https://play.google.com/store/apps/details?id=com.pashapuma.imaterial.icons

**Comment by ujwal246** [comment]
OneMax (You) - Icon Pack by Eatos
https://play.google.com/store/apps/details?id=com.eatos.onemax.you

**Comment by hanubeki** [comment]
iMaterial Light:
https://play.google.com/store/apps/details?id=com.pashapuma.imaterial.light

**Comment by hanubeki** [comment]
OnePro (You):
https://play.google.com/store/apps/details?id=com.eatos.oneyoupro

**Comment by hanubeki** [comment]
Lavien Lines Monet:
https://play.google.com/store/apps/details?id=osmanonurkoc.lavien.lines.monet

**Comment by hanubeki** [comment]
iTinted:
https://play.google.com/store/apps/details?id=com.eatos.itinted

**Comment by hanubeki** [comment]
Simply Adaptive:
https://play.google.com/store/apps/details?id=com.italiano.simplyadaptive

**Comment by hanubeki** [comment]
Simply You:
https://play.google.com/store/apps/details?id=com.italiano.simplyyou

**Comment by TFackler** [comment]
This Issue is discontinued as we have moved our feedback to [https://feedback.niagaralauncher.com](https://feedback.niagaralauncher.com).

The successor of this issue can be found here: [List of Material You Icon Packs](https://feedback.niagaralauncher.com/p/list-of-material-you-icon-packs). Please post future updates there :)
