### ISSUE TITLE
History and settings icon should follow system colors

### ISSUE THREAD

**Issue by SpktKpkt** [8bitPit/Niagara-Issues#2318]
### Is your feature request related to a problem?

This is something that drain my eyes for a long time, the history and settings icon/button should follow the the system colors.

![Screenshot_20230626-174030](https://github.com/8bitPit/Niagara-Issues/assets/1786221/a0e28e58-a9a7-42aa-bb3d-959149ae8eb8)

### Describe the solution you'd like

Follow the system colors.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @SpktKpkt, Thank you for your suggestion! Please refer to this existing issue #1595

- Merged with #1595
