### ISSUE TITLE
Allow to align to top

### ISSUE THREAD

**Issue by JamesStuder** [8bitPit/Niagara-Issues#2320]
### Is your feature request related to a problem?

I would like the ability to have the launcher align to top of screen rather than 1/4 way down screen as it currently does 

### Describe the solution you'd like

Option in setting to move launcher home screen to top of screen

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @JamesStuder, Thank you for reaching out! It's already possible to reposition the favorite apps position. Here's how:
-> Long press on the Niagara widget
-> Move widget
-> Hold the bar and drag it to the top

**Comment by JamesStuder** [comment]
Thank you
