### ISSUE TITLE
mode like ios Focus mode 

### ISSUE THREAD

**Issue by tofuisme** [8bitPit/Niagara-Issues#2321]
### Is your feature request related to a problem?

I have an idea ‌for fav app section. 

When I tap the gaming mode button, it will change the whole fav section as a user select of app for gaming mode. Much like ios focus mode

### Describe the solution you'd like

Add more page of fav section and shortcut button and boom💥 U got this.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @tofuisme, Thank you for your suggestion! Currently, we don't have plans to add multiple paged favorites as it might overcomplicate the launcher. However, we are considering adding the functionality to set contextual favorite apps with automation tools like Tasker & Automate. Please check out #786 for more information.

In the meantime, you can use the [Pop-up folder](https://help.niagaralauncher.app/article/115-pop-ups) feature to group all your Game apps.

**Comment by Amorphous404** [comment]
- Merged with #786
