### ISSUE TITLE
Pop-up background color/theme

### ISSUE THREAD

**Issue by robschertzer** [8bitPit/Niagara-Issues#2322]
### Is your feature request related to a problem?

I am using Whicons icon pack; all icons therefore are white. In order to see them in the Niagra pop-ups, I have to set my Pixel 6 Pro theme as dark. Otherwise when in light mode, the pop-up background is white making none of the icons visible. 

### Describe the solution you'd like

Pop-up background color option in Niagara settings. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @robschertzer,

Thank you for your suggestion! Unfortunately, we have no plans to include a manual color setting for the pop-up in the Niagara launcher. Our UI automatically adjusts its color based on the wallpaper and Material You palette. We have intentionally designed it to be subtle to enhance its compatibility with a wide range of wallpapers. We feel adding more [customization options would make the launcher more complex](https://help.niagaralauncher.app/article/8-niagaras-design-principles) and would also compromise its consistency.

If you would like more information on this topic, you can refer to the following article:
1. [Our Color System](https://help.niagaralauncher.app/article/133-color-system)
2. [Missing Customization Features](https://help.niagaralauncher.app/article/77-missing-customization-features)

Regarding the issue you mentioned, if you use a completely white icon pack such as Whicons or Reev Pro, we recommend setting the Niagara theme to always dark. Here's how you can do it:
-> Niagara settings
-> Look
-> Dark theme
-> Always enabled

![Demo.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/e8c57fb2-e1c7-4f96-8a0e-5d3e4d0940cb)

We hope this solution helps.
