### ISSUE TITLE
Cannot dismiss "Set as default launcher" message.

### ISSUE THREAD

**Issue by KlingonDragon** [8bitPit/Niagara-Issues#2323]
### Describe the bug

Some devices don't let you change the default launcher. I can't find a way to dismiss this 'suggestion ' and remove it from the favourites home screen.

Please provide an option to dismiss it next to the "sure" option for those who can't (or perhaps don't want to) set this launcher as the default.

### Steps to reproduce

Install launcher
Don't set as default
Look at favourites list

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Kindle Fire

### Android version

Android 7.1 (Nougat)

**Comment by Amorphous404** [comment]
Hi @KlingonDragon, Thank you for reaching out! Please follow this guide to remove the prompt.

[How to ignore the "Set as default launcher" prompt](https://help.niagaralauncher.app/article/102-launcher-not-staying-as-default#:~:text=How%20to%20ignore%20the%20%22Set%20as%20default%20launcher%22%20prompt)

If you set Niagara Launcher as default with other methods and Niagara Launcher and want to make the set as default launcher prompt disappear, enter the following secret command: /suppress set launcher prompt or tap on the following link to have it entered for you: https://nlaun.ch/c/suppresssetlauncherprompt. Enter the command a second time to enable the set as default launcher prompt again.

**Comment by KlingonDragon** [comment]
This should not require a secret command. There should just be a button to hide it.

**Comment by Amorphous404** [comment]
- Duplicate of #949
