### ISSUE TITLE
Distinction between frequently used apps and alphabetical apps

### ISSUE THREAD

**Issue by trigili** [8bitPit/Niagara-Issues#2326]
### Is your feature request related to a problem?

It's difficult to tell at a glance where the frequently used apps in my app drawer end and where the alphabetical ones begin. 

### Describe the solution you'd like

Some sort of subtle indicator or distinction between frequently used apps and the rest of the apps for a given letter in the app drawer. For example, the option to have the names for frequently used apps in bold, or a small divider between the end of the frequently used apps in the beginning of the alphabetical ones.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @trigili, Thank you for your suggestion! We internally discussed this option and decided not to proceed with it at this point. The main reasons being it might clutter the app list, and we don't find it impactful enough and will require us to add a toggle to deactivate it, which we reserve for [highly requested and functional features](https://help.niagaralauncher.app/article/8-niagaras-design-principles). However, we'll keep an eye on the demand, and if anything changes, we'll reconsider your request.

In the meantime, if you prefer the standard sort list, you can achieve it by going to Niagara Settings -> Features -> and disabling "Sort all app list by usage."

Thank you for your understanding,
