### ISSUE TITLE
Align options for widgets

### ISSUE THREAD

**Issue by IAMGeeCee** [8bitPit/Niagara-Issues#2328]
### Is your feature request related to a problem?

If you add a widget to the screen which is more of a square shape than a long thin shape, it gets aligned in the center. This can look very bad with some of the marterial you widgets such as the clock and weather. If you could choose to align to the left or center of the screen it would be great.

### Describe the solution you'd like

I'd like to be able to press down on a widget and have an option called align. When you press it, another menu will open with the options left, center (maybee right?).

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @IAMGeeCee, Thank you for your suggestion! For now you can utilize the following [secret command](https://help.niagaralauncher.app/article/74-secret-commands#:~:text=You%20can%20enter%20secret%20commands,written%20with%20or%20without%20spaces.) to adjust the widget alignment:

**Horizontal resizing and alignment options ‧** This feature is not fully ready yet, nevertheless we’re interested in hearing your feedback to integrate your feedback as early as possible. With the secret command /resizex you can also resize custom widgets horizontally and simultaneously change their horizontal alignment. Here’s an example of how it works: /resizex.30.L, sets the width to 30% of the widget’s default width, and aligns the widget to the left. If you want to keep it centered, omit the .L at the end.

**Source:**
[Design Update: Fresher & Cleaner (Medium)](https://medium.com/niagara-launcher/design-update-fresher-cleaner-3593149dbfbb#:~:text=Horizontal%20resizing%20and%20alignment%20options)

Demo:
![Widget Alignment.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/4e6c901a-ef8f-4b3a-a5bd-bb1c73f78e94)

For further discussion, you can join #1355

**Comment by Amorphous404** [comment]
- Merged with #1355

**Comment by IAMGeeCee** [comment]
Thank you @Amorphous404 ! I'll give it a go.
