### ISSUE TITLE
OpenVPN icon flashing when VPN is connected

### ISSUE THREAD

**Issue by Melechite** [8bitPit/Niagara-Issues#233]
Don't know if this is intended, but I find it to be annoying. Awesome launcher btw
![flashing](https://user-images.githubusercontent.com/34435894/45616879-01dafe00-ba71-11e8-8bcc-3852593c0387.gif)

**Comment by 8bitPit** [comment]
Probably the VPN update's its notification in the background

**Comment by 8bitPit** [comment]
Should be fixed by now.
