### ISSUE TITLE
Double line results for web searches

### ISSUE THREAD

**Issue by MathisP75** [8bitPit/Niagara-Issues#2330]
### Describe the solution you'd like

Typing something too long in the Niagara search bar will result in cut off content that makes different results look the same, for instance in a web search.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
- Duplicate of #2331
