### ISSUE TITLE
Cut off content in search results 

### ISSUE THREAD

**Issue by MathisP75** [8bitPit/Niagara-Issues#2331]
### Is your feature request related to a problem?

Typing something too long in the Niagara search bar will result in cut off content that makes different results look the same, for instance in a web search.

### Describe the solution you'd like

Allowing for double line results would be a great fix.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by MathisP75** [comment]
Example:
![Screenshot_20230711-222351.png](https://github.com/8bitPit/Niagara-Issues/assets/98901170/49adac78-f4cd-42b8-a2bf-4f2e9c72bf8d)

**Comment by 8bitPit** [comment]
Thanks for letting us know @MathisP75, we'll take a look

**Comment by TFackler** [comment]
Thanks for the good suggestion 👍 

I took care of it and it will be included in the next update C:

**Comment by MathisP75** [comment]
> I took care of it and it will be included in the next update C:

Has it been implemented yet? I am on the latest version and it's not there.

**Comment by 8bitPit** [comment]
CC @TFackler

**Comment by TFackler** [comment]
Hi there,

What version of Niagara are you running? I'm on 1.11.5, and it works fine.

![image](https://github.com/8bitPit/Niagara-Issues/assets/38538728/380106dd-ea44-4102-ac29-4b112e672ff7)

**Comment by MathisP75** [comment]
I am on 1.11.5 and I still get cut off content. However, my search screen does not look like yours (I don't have the "Web suggestions" title). Is that related to Sesame search?

**Comment by MathisP75** [comment]
So this is only for the /web search feature, would it be possible to add it to the Sesame search interface in Niagara?

**Comment by TFackler** [comment]
This is indeed related to Sesame Search.

I have changed the behavior so that Sesame's web suggestions are displayed similarly to Niagara's. 

Until the next update is released and the change takes effect, you can replace Sesame's web search with your own by typing `/websearch` into the search bar, hitting enter, and choosing a web search engine afterwards. It will only replace the actual web search, the rest of Sesame will still work like you are used to.

**Comment by 8bitPit** [comment]
Fixed in v.1.11.6
