### ISSUE TITLE
Make player widget change between active media players when swiping from left (like pop-up apps) and remove player when swiping from right (like app notifications in Niagara)

### ISSUE THREAD

**Issue by ssssamstrup** [8bitPit/Niagara-Issues#2332]
### Is your feature request related to a problem?

Android has this annoying autoplay bluetooth feature, which has turned media player notifications into a fighting arena for getting control of the media control, when bluetooth is turned on.

On my phone this opens 4 apps in the background, who each launches a player notification in the hope of being the app getting media control. This often leads to the wrong media player being shown on Niagara, than the one I want to use.

### Describe the solution you'd like

It would be great if I was able to »cycle« through the open media players/controls to use the right one from the launcher, rather than finding and opening the app from the list. And still be able to dismiss the media app when I'm done listening, like it works now. 

I suggest being able to cycle through them, by swiping from left to right and dismissing the current by swiping from right to left. This follows the UX for pop-up apps and Niagara app notifications. 😊

I don't know if the Niagara music widget is connected to the notifications and the solution is possible.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @ssssamstrup, Thanks for your suggestion! Unfortunately, that's not possible; Please refer to #2258

> Android has this annoying autoplay bluetooth feature, which has turned media player notifications into a fighting arena for getting control of the media control, when bluetooth is turned on.

I think this feature is specific to your Android skin. Hopefully, there may be a setting available to turn off this functionality unless it's a system bug.

**Comment by Amorphous404** [comment]
- Merged with #2258

**Comment by ssssamstrup** [comment]
Cool, thanks for the explaination on #2258 @8bitPit.
