### ISSUE TITLE
Dim Wallpaper 

### ISSUE THREAD

**Issue by ajaykhosh** [8bitPit/Niagara-Issues#2337]
### Is your feature request related to a problem?

Add adjustable option for dim wallpaper, or blur option 

### Describe the solution you'd like

Add adjustable option for dim wallpaper, or blur option

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by wimstefan** [comment]
![Screenshot_20230728-091327.png](https://github.com/8bitPit/Niagara-Issues/assets/4605934/3fe3bd3f-1b35-49bc-a633-5db822376be9)

**Comment by Amorphous404** [comment]
Hi @ajaykhosh, Thank you for your suggestions! Currently, we do not have plans to include these options. We recommend using one of the alternative third-party apps mentioned in the [Wallpaper Blur](https://help.niagaralauncher.app/article/64-blur-wallpaper) article to achieve the same functionality.

However, you can already apply dim in the app list and search. To do that, go to Niagara settings -> Look -> Turn on "Dim wallpaper" toggle.

Thanks,

**Comment by ajaykhosh** [comment]
I want more dark dim or lite dim. I know Already default dim option, but not a adjustable options
