### ISSUE TITLE
App names starting with numbers

### ISSUE THREAD

**Issue by speedpro** [8bitPit/Niagara-Issues#2339]
### Describe the bug

Apps where the name starts with a number (e.g. "2degrees") don't show up anywhere in the launcher (not even in search) 

I have to open Google play just to find a button that allows me to open the app. I'm assuming it's because the app name starts with a number.

### Steps to reproduce

1. Go to google play store and install 2degrees
2. Scroll through launcher looking for it. It won't be there. I would expect an additional *#* section in the sidebar beneath "z"
3. Use search and type "2degrees".
4. No results will be displayed

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Oppo Reno2 Z

### Android version

Android 11

### Screenshots / Screen recordings

![Screenshot_2023-07-29-08-04-12-03_a4824db61f40c53807964ea8b14c92fe](https://github.com/8bitPit/Niagara-Issues/assets/9342516/eaec27d8-6fa3-4ebb-8e6f-05185c8d8f47)

**Comment by Amorphous404** [comment]
Hi @speedpro, Thank you for contacting us! Here's what occurred: Normally, apps with numbers are listed under "#" in the app list. However, in the case of the 2degrees app, it has a different name (Mobile) for the launcher. This variation in naming is sometimes done by developers to make their apps more distinguishable among others. I hope this clarifies the situation.

Demo:
![2degrees.jpg](https://github.com/8bitPit/Niagara-Issues/assets/96917972/995f66b7-6871-4abf-9e5e-9a338fc62da0)
