### ISSUE TITLE
Bug with Morning Mode & folder

### ISSUE THREAD

**Issue by IJustWantANamePlease** [8bitPit/Niagara-Issues#2340]
### Describe the bug

During Morning Mode, the folder cannot be opened after quickly tapping twice on an app in it. Opening search or going into app list fixs it. Happens in favourite, forgot to test in app list.

### Steps to reproduce

1. Turn on Morning Mode.
2. Create a folder and star it.
3. In the morning, open the folder and quickly tap twice on any icon in it.
4. The folder is closed and cannot be opened.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Redmi Note 11T Pro (Xaga)

### Android version

Android 13

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/69347951/2143e915-de12-4ed3-b3fe-65c80b79d02c

**Comment by Amorphous404** [comment]
Hi @IJustWantANamePlease, Thank you for letting us know about this. Have you attempted to resolve the issue by restarting the launcher? You can do this by going to Niagara settings -> Advanced -> Restart Launcher.

**Comment by IJustWantANamePlease** [comment]
> Hi @IJustWantANamePlease, Thank you for letting us know about this. Have you attempted to resolve the issue by restarting the launcher? You can do this by going to Niagara settings -> Advanced -> Restart Launcher. Moreover, is this easily reproducible?
> 
> Quick update: I just tested this, and I couldn't reproduce it on my end. Hopefully, It should be resolved with a launcher restart. Please test and let us know. Thanks!
> Demo:
> https://github.com/8bitPit/Niagara-Issues/assets/96917972/5c31457d-1277-4b19-b130-5baa7db4d6ef
> 
> 

Yes, launcher restart can fix the issue, but it's not necessary. Simply swiping up to search or entering app list can fix it. However, it can still be triggered after a restart, and it's pretty stable.

The way to trigger this bug is to quickly tap twice on the app icon, to dismiss the Morning Mode popup before it fully shows. In your video the app is opened normally, which wouldn't produce the bug.

**Comment by IJustWantANamePlease** [comment]
In a recent version of Niagara Launcher, popup windows (from the bottom) no longer respond to any gestures until they finish their animations. This... is a bit annoying in some cases, but it also solves this issue. I think it's safe to close it now.🫡
