### ISSUE TITLE
Vibration Strength Options

### ISSUE THREAD

**Issue by the753q** [8bitPit/Niagara-Issues#2341]
### Is your feature request related to a problem?

On low end phones, vibration motor is quite annoying on high strengths.

Happens when you scroll through the alphabet

### Describe the solution you'd like

A vibration strength picker.
Easy solution would be maybe 3 options, weak default strong

But i think the best solution would be to have the setting take you back to the homescreen, where it also shows you a pop up at the bottom with vibration strength options, so you can quickly choose and test the vibration

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Amorphous404** [comment]
Hi @the753q, Thank you for your suggestion! Niagara utilizes the Launcher3 vibration sensitivity (system default). If the vibration strength doesn't suit your preference, we suggest adjusting it within the system settings.

Thanks,

**Comment by the753q** [comment]
Yeah but my device only supports turning vibration on or off

**Comment by Amorphous404** [comment]
I'm sorry to hear that! Our app relies on the Android default framework, making it challenging to incorporate a native sensitivity settings. Developing a custom solution might not be reliable at this point. I recommend reaching out to your phone manufacturer and suggesting the addition of a slider to adjust sensitivity within your phone settings!

Thank you for your understanding.
