### ISSUE TITLE
App title shows over large letter before full

### ISSUE THREAD

**Issue by OfficialKris** [8bitPit/Niagara-Issues#235]
If you press the alphabet bar over a long app title the app title shows over the letter your on. But then disappears after it is the full letter.

**Comment by Montell2099** [comment]
"But then disappears after it is the full letter."
Could you explain further & with a screenshot perhaps?

**Comment by OfficialKris** [comment]
![ezgif-5-e0ee93794b](https://user-images.githubusercontent.com/37947442/45854385-d24e1f00-bd18-11e8-98d1-a9a1d228798c.gif)

**Comment by 8bitPit** [comment]
@OfficialKris Should be fixed with the latest update

**Comment by 8bitPit** [comment]
Does the issue still persist? If so, feel free to open it again.

**Comment by OfficialKris** [comment]
Was fixed with the update right after your initial comment, forgot to follow up.

**Comment by 8bitPit** [comment]
no, problem, great that it's working :)
