### ISSUE TITLE
Wish the launcher supported QuickSwitch

### ISSUE THREAD

**Issue by Ahtaler** [8bitPit/Niagara-Issues#2351]
### Is your feature request related to a problem?

QuickSwitch is a Magisk/KernelSU module which systemlessly allows supported launchers to access the recents (QuickStep) APIs

While this may go against some of the original design intent of the Niagara launcher's features, which means it can't be work on all phones. But it should meet the remaining three, Simple, Impactful and Independent :) .

### Describe the solution you'd like

Would like to see Niagara launcher supported QuickSwitch

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by CasperOng** [comment]
![Screenshot_20230902-053603.png](https://github.com/8bitPit/Niagara-Issues/assets/90828938/4aae3c2f-5c76-4cba-a033-b6a0a326d0d9)
