### ISSUE TITLE
App profiles that only show certain apps in the list

### ISSUE THREAD

**Issue by IMNOTIKE** [8bitPit/Niagara-Issues#2354]
### Describe the solution you'd like

Having multiple "profiles" as in work and personal to keep work related apps separate from personal life related apps.
It would be nice to see:
- apps tagged with a profile ( or multiple profiles) would show up only when selecting that profile
- the list of favourites and widgets could be set per-profile

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Maxr1998** [comment]
Something similar was suggested in #2071 and #1517. Please read the latter for a reply from Peter.
