### ISSUE TITLE
Support Google Device Policy Work Profiles

### ISSUE THREAD

**Issue by EvanHammond** [8bitPit/Niagara-Issues#236]
Google Device Policy can create a profile for a given policy. This ends up installing duplicate applications under a given policy. Using the current build if Niagara, I can only see the non-profile version of the app.

Using Smart Launcher (showing work profile apps):
![screenshot_20180917-102623](https://user-images.githubusercontent.com/1012801/45633220-d6eaad00-ba64-11e8-9f3d-8386e2920c9c.jpg)

Current Niagara:
![screenshot_20180917-103229](https://user-images.githubusercontent.com/1012801/45633403-511b3180-ba65-11e8-954e-9772729fae49.jpg)

**Comment by 8bitPit** [comment]
Thank you for suggesting, I will support them, see: #93
