### ISSUE TITLE
Unable to remove/delete app shortcut from app list

### ISSUE THREAD

**Issue by salixor** [8bitPit/Niagara-Issues#2364]
### Describe the bug

App shortcuts which have been added to the app list can not be removed.
They keep reappearing if you tap "Remove from app list".
Rebooting the device or re-starting the app does not solve the issue.

### Steps to reproduce

- Go to the app list
- Swipe on an app to show its shortcuts
- Long press a shortcut and click "Show in app list"

Case A :
- Go to the app list
- Long press this shortcut in the app list and click "Remove from app list"

Case B :
- Swipe on the same app to show its shortcuts again
- Long press the same shortcut and click "Remove from app list"

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 5

### Android version

Android 13

**Comment by TFackler** [comment]
I have confirmed this bug on v1.9.9.

**Comment by salixor** [comment]
Thanks a lot for the workaround !

**Comment by Maxr1998** [comment]
Fixed in [v1.10.0](https://github.com/8bitPit/Niagara-Issues/releases)🎈
