### ISSUE TITLE
Use system material colors everywhere option

### ISSUE THREAD

**Issue by the753q** [8bitPit/Niagara-Issues#2365]
### Is your feature request related to a problem?

Sometimes, Niagara's algorhitm selects a totally different color than system does.

For example, it selected blue (as it should from a blue wallpaper), but after restart switched to green?? There's barely any green on my background.
Though it's possible that upon restart, it took the color from the raw uncropped wallpaper image, whose other parts may contain green

### Describe the solution you'd like

Niagara already uses system color for settings, for app pop-ups.

I would suggest giving us an option to choose system or niagara color, and apply that to the whole launcher.
![screen](https://github.com/8bitPit/Niagara-Issues/assets/50169298/6776ec20-21b7-4e46-9bb8-c5b6f5e25d7f)
(search button should be dark red if following system, or then pop-up should be green to follow Niagara)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by the753q** [comment]
Latest release has colors reworked

**Comment by RokeJulianLockhart** [comment]
> https://github.com/8bitPit/Niagara-Issues/issues/2365#issuecomment-1848452685

@the753q, so that they adhere to what the system defines? Static colouration is Material 3, but not You.
