### ISSUE TITLE
Pressing home button for search options

### ISSUE THREAD

**Issue by asherperlmuter** [8bitPit/Niagara-Issues#237]
First of all, love the app... It's great.

Okay so it would be nice if there was the ability to turn off the press home button for search option if I didn't want it on

Also if I am using it, it would be cool if when I searched (for example) WhatsApp (or even just "wha") and press enter, it opens WhatsApp without having to actually click the WhatsApp icon
Because it's the top search result

**Comment by 8bitPit** [comment]
thank you,

`ability to turn off the press home button for search option if I didn't want it on`
see #61

`press enter, it opens WhatsApp without having to actually click the WhatsApp icon
Because it's the top search result`
see #114
