### ISSUE TITLE
Search Apps - Recently Installed (alternate option)

### ISSUE THREAD

**Issue by Kreyzey** [8bitPit/Niagara-Issues#2380]
### Is your feature request related to a problem?

Recently installed apps being dual located - the swipe up to search location is not the most efficient or productive use of real estate,

### Describe the solution you'd like

Given an option to toggle recently installed with recently opened or most used applications.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
I'm sorry, but we don't plan to add a recently used section for the reasons discussed in https://github.com/8bitPit/Niagara-Issues/issues/1833. Nevertheless we now make better use of the search screen's real estate: v1.10 (currently in [beta](https://github.com/8bitPit/Niagara-Issues/releases)) now lists recently and frequently searched apps in the search screen.
