### ISSUE TITLE
[bug?] Icons are blank for quick actions 

### ISSUE THREAD

**Issue by Rod911** [8bitPit/Niagara-Issues#239]
![Screenshot](https://i.imgur.com/jjFXIkX.png)

Is it a bug or a feature? 
V 0.3 build 3
Android 6.0

Also: Are these implemented by app devs or you because I would like to see this for more apps.

**Comment by 8bitPit** [comment]
Those are called app shortcuts and are implemented by the devs of their corresponding apps. They were introduced in Android 7.1, I did my best to backport them though, so you can use them in older Android versions as well. Unfortunately that's very limited, and sometimes icons can not be supported.
