### ISSUE TITLE
Pop-up doesn't close after tapping on an option and then coming back to the Home screen

### ISSUE THREAD

**Issue by murielg** [8bitPit/Niagara-Issues#2392]
### Describe the bug

Opening the Pop-Up of an app, tapping on an option, and then tapping the back button to come back to the home screen still show the pop-up being opened. I would expect the pop-up would close after tapping on an option from the pop-up list. 

### Steps to reproduce

1. In your favorites, side swipe on a Favorite app, such as Gmail
2. Tap on a pop-up option, such as Compose
3. Tap The back button
4. The pop-up is still open

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Pixel 6 Pro

### Android version

Android 13

**Comment by 8bitPit** [comment]
Thanks for the feedback @murielg and apologies for the late reply. The popup only remains open if you quickly return to the home screen, here's why: https://help.niagaralauncher.app/article/86-pressing-home-doesnt-show-favorites. Hope that helps!

**Comment by murielg** [comment]
@8bitPit Just tested that and it's behaving as expected. Thanks for the reply! We can close this :D

**Comment by 8bitPit** [comment]
Great, thanks for testing!
