### ISSUE TITLE
Use root access to lock the screen instead of accessibility

### ISSUE THREAD

**Issue by ZooNooU** [8bitPit/Niagara-Issues#2396]
### Is your feature request related to a problem?

hello!
I think this would be a cool implementation, as it would save abit of battery when it comes to locking the screen (the launcher won't be constantly listening to user input to determine double tap all time), if you would kindly consider making an option to use root access instead of accessibility access to lock the screen + it would be more seamless.
thanks for this amazing launcher :D

### Describe the solution you'd like

Kindly implement this feature of using root access to lock the screen alongside the accessibility one.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by ZooNooU** [comment]
found the solution after reading the already added features section, sorry for this

**Comment by 8bitPit** [comment]
Hey @ZooNooU, thanks for your request. I'm not sure if a root-based screen locking mechanism is more battery friendly than running an accessibility service, but you can try it for yourself - Niagara Launcher already supports root-based screen locking (although the feature somewhat hidden) :) https://help.niagaralauncher.app/article/73-lock-screen-on-older-android-versions
