### ISSUE TITLE
2 horizontal widgets on tablets

### ISSUE THREAD

**Issue by SnowSquire** [8bitPit/Niagara-Issues#2422]
### Is your feature request related to a problem?

Widgets have a lot of empty space as most are not designed to be so wide, as they are on a tablet.

### Describe the solution you'd like

Having two horizontal widgets would be a nice solution, I realize this is much more likely to get rejected which is why I split it from my other issue. I don't know how much you guys focus on the tablet experience which is understandable. I also realize that widget stacks exist, which is a great solution on phone, but even when held vertically my tablet is more than double the width of my phone.

The implementation could be as simple as asking the user if they want a widget stack or two horizontal widgets when its detected that they are running on a tablet.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by SnowSquire** [comment]
I don't like spamming another issue but 3 columns of apps might also be nice on tablets, I'm fine with my current assortment of apps though.

**Comment by TFackler** [comment]
Hi there,

We have added a 2 column widget stack on wide devices starting with version 1.10.

It will still take a week or so to be available on Google Play, but you can already get it via our Telegram channel:
https://t.me/s/niagara_news

That's why I'll close this ticket.
