### ISSUE TITLE
Improve transliterated sorting

### ISSUE THREAD

**Issue by sorgelig** [8bitPit/Niagara-Issues#2431]
### Is your feature request related to a problem?

Currently if you use English locale, then all non-English names will put into `#` section which is inconvenient.

### Describe the solution you'd like

Generally speaking transliterate from all languages to Latin while sorting should be no harm. So the best way is to not look at current locale and simply sort transliterated names from all languages.

If it impossible to do it (why?) then give a choice in settings which language(s) user wants to sort regardless the application locale.

In v1.9.9 i could temporary switch to Russian locale and get all Russian names sorted according to transliteration, then switch back to English and keep that sorting. In v1.10.0 it doesn't work anymore, sorting get reset after switch back to English.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Hey @sorgelig, thanks for letting us know. Does your phone allow using two locales at the same time? If so, you can use English and add Russian as your secondary language.

**Comment by sorgelig** [comment]
My phone is Xiaomi Mix Fold 3. It doesn't have Russian. Generally speaking, Russian can be added/unlocked through mod, but as i see in locale settings it doesn't allow more than 1 locale. The dialog has radio button as a chooser, so only one locale at a time.

**Comment by sorgelig** [comment]
With help from SetEdit app i've added second language to system_locales variable, and now Russian sorting is working. 
But it would be better if Launcher would provide option to add it locally (not involving system variable editing).

**Comment by 8bitPit** [comment]
Thanks for checking. The Mix Fold 3 probably does not support Russian because it was exclusively released in China; the Russian locale should be selectable on other Xiaomi or Android phones. This makes it an edge case for just a handful of phones and users; I'm sorry, but we've decided to keep it as it is.

**Comment by sorgelig** [comment]
It's not about specific language. Xiaomi phones don't support more than one language setting. So you cannot add any language (Russian or other - doesn't matter). So if i want English interface with sorting additionally by other language on Xiaomi, then it's impossible.
It's not edge case. All Xiaomi phones affected.

**Comment by 8bitPit** [comment]
I'm sorry, I forgot about that. Nevertheless, I believe only a handful of users have their locale set to a different language of where they want transliteration to be applied. I'm afraid changing the behavior might not be impactful enough. We will monitor how many requests we will receive about transliteration, and re-prioritize this ticket if there's a high demand. Sorry for the inconvenience.
