### ISSUE TITLE
Hide an app from the list if the app was added to a folder/folders

### ISSUE THREAD

**Issue by cotton-more** [8bitPit/Niagara-Issues#2433]
### Describe the solution you'd like

A pop-up folder could be created to hold one or many apps. One app could be added to multiple folders.

It would be nice that the app is removed from the list of all apps when the app is added to any folder.

It should be possible to search the app.

When a new folder is created, then all apps should be visible for adding to the folder.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thank you for the request. This feature has already been requested, so please head over there to share your thoughts: #1604.
