### ISSUE TITLE
Manually Select Black or White Text

### ISSUE THREAD

**Issue by 8bitBucy** [8bitPit/Niagara-Issues#2435]
### Is your feature request related to a problem?

I'm a bit color blind and was trying to pair a black icon pack with a sunset orange wallpaper, but Niagara was selecting white text. I could hardly see the text. I'm sure it is set to detect saturation or brightness. 

### Describe the solution you'd like

It would be great to override the text color Niagara picks, and allow us to manually select the black or white text.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
I'm sorry for not getting back to you sooner.

Niagara tries to select white or black text depending on the brightness of the currently selected wallpaper. You can override this selection by going to the bottom of the all apps list > Niagara Settings > Look > Text color (at the bottom) > select Light or Dark, depending on your preference.

I hope this information does not come too late.
