### ISSUE TITLE
Design flaw

### ISSUE THREAD

**Issue by irfan850007** [8bitPit/Niagara-Issues#2436]
### Describe the bug

Hello. There is some design flaw in the widgets that are on home screen. Because whenever i want to click "+" on a widget, the alphabetical letters on the right pop ups and does not let me tap on the plus sign of the widget. Please help 

### Steps to reproduce

Home page

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Nokia 3.1 Plus

### Android version

Android 10

**Comment by HDFLucky** [comment]
I believe this is the same issue I reported over 2 months ago (which has not seen any action). https://github.com/8bitPit/Niagara-Issues/issues/2377

**Comment by TFackler** [comment]
Duplicate of #1714
