### ISSUE TITLE
BUG inserting ttf or otf characters in the new version 1.10.2

### ISSUE THREAD

**Issue by Livio78** [8bitPit/Niagara-Issues#2442]
### Describe the bug

I discovered a new BUG in the new version of Niagara Launcher 1.10.2. When I try to insert a character taken from an external .ttf or .otf file it doesn't let me insert it, while in previous versions I was able to insert characters from ttf or otf files. Please fix this bug as soon as possible.

### Steps to reproduce

- Settings
- I wait
- Characters
- TTF or OTF file faded and not selectable

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Oukitel C16 pro

### Android version

Android 9 (Pie)

**Comment by 8bitPit** [comment]
Hey @Livio78, thank you for the report. We've indeed modified how the Font File picker works in v1.10. It is supposed to only you show ttf, otf files and folders. I've tested this with Google Files, but it seems that other file pickers don't work with the approach we used. Do you mind sharing what file picker you're using?

**Comment by Livio78** [comment]
I downloaded .ttf and .otf files from various sites and copied them to the internal memory of the smartphone, I go to select them and they are faded and unselectable, in previous versions these files were working. Could you write me the procedure for inserting characters with the new version of Niagara? Thank you

**Comment by 8bitPit** [comment]
We have yet to release a fix, but we'll do that soon. The bug has something to do with the file manager that is installed on your phone, this is the app that opens to select your font file. Can you share which file manager app you have installed in your phone? Are you using the preinstalled file manager or do you have installed a separate one?
Here are a few examples of file manager apps: https://www.androidpolice.com/best-file-managers/#x-plore-file-manager

**Comment by Livio78** [comment]
The file manager I use is Files by Google.

**Comment by 8bitPit** [comment]
Thank you for letting us know. This issue should be fixed with v1.10.3: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by Livio78** [comment]
thank you

    Il venerdì 24 novembre 2023 alle ore 15:40:50 CET, Peter Huber ***@***.***> ha scritto:  
 
 


Thank you for letting us know. This issue should be fixed with v1.10.3: https://github.com/8bitPit/Niagara-Issues/releases
