### ISSUE TITLE
Dont show "hidden app" among the icons in "Recents" Screen

### ISSUE THREAD

**Issue by yedpodtrzitko** [8bitPit/Niagara-Issues#2444]
## Current behaviour

- mark app as hidden in apps list
- use the app frequently
- open the "Recents" view
- app's icon will appear among the "frequented apps" on the bottom

## Expected behaviour
- app icon wont be shown in the Recents view. 
 
I dont have control over the icons on the bottom and afaik there's no deterministic way how to remove the icon from there. When the app is marked as hidden, I would prefer to have it hidden there as well. See screenshot below for example - Instagram is marked as hidden app, but I still see its icon and I cant remove it.

![WhatsApp Image 2023-11-22 at 13 08 48](https://github.com/8bitPit/Niagara-Issues/assets/135112713/43db993d-5949-49db-a652-ed95e4326e21)

I'm still undecided if this should be marked as a feature request or bug.

### Describe the solution you'd like

app which is hidden from the app list should be hidden from the icons on the bottom of app overviews as well.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

### Describe the solution you'd like

- icon of hidden app wont appear in "Recents" view

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Manu99it** [comment]
How that depends on Niagara? Recent apps in here are managed by system / system launcher

**Comment by yedpodtrzitko** [comment]
I am not Android dev, so I dont know the details how it works there. Closing then, thanks for answer.

**Comment by Manu99it** [comment]
However I have a suggestion for you: if you want to hide it from there, there are apps, like icebox for example, that permit you to freeze apps. As a side effect of being freezed, the system won't show these apps in the recent row. Keep in mind however that freezed apps won't show notifications
