### ISSUE TITLE
Option to switch between frequently searched or recently installed

### ISSUE THREAD

**Issue by NikunjKhangwal** [8bitPit/Niagara-Issues#2449]
### Describe the solution you'd like

While the frequently searched results in new update could be useful for most users, i much prefer recently installed apps showing up in search windows like it used to do before. If possible can we have the option to toggle between these two? Also if you guys do add this, please increase the number of recently installed app showing up to 7, previously it used to be 5.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Hi @NikunjKhangwal, thanks for the suggestion. Our search both shows recently installed and frequently searched apps, more info here: https://help.niagaralauncher.app/article/152-search-suggestions.
