### ISSUE TITLE
Battery icon

### ISSUE THREAD

**Issue by Tareq4322** [8bitPit/Niagara-Issues#2450]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I think if there is a battery icon next to battery percentage it would be great. The battery percentage without any icon looks kinda odd.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Duplicate of #1688
