### ISSUE TITLE
YouTube quick actions widget and Samsung Calendar widget not working properly

### ISSUE THREAD

**Issue by stonemcstoned** [8bitPit/Niagara-Issues#2469]
### Describe the bug

YouTube quick actions widget is only showing search bar no matter the size and the Samsung Calendar app widget is not visible

### Steps to reproduce

add YouTube quick actions widget or Samsung Calendar widget to any pop-up or favourites list

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

One UI Home

### Device name

Samsung Galaxy A10

### Android version

Android 11

**Comment by Maxr1998** [comment]
Both issues should be fixed since 1.10.8. Could you try the latest version from the GitHub releases and report back whether it works for you?

**Comment by stonemcstoned** [comment]
![Screenshot_20231220-075701_One UI Home](https://github.com/8bitPit/Niagara-Issues/assets/152992948/e8d2f38e-8f15-4b6c-bc9a-cb0e8b4deb71)
![Screenshot_20231220-075430_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/152992948/f3815c69-e694-46ca-b470-804b0dd5ac81)

the calendar widget has been fixed but youtube quick actions widget still has an issue, the bottom buttons are not visible, though i can click them.

**Comment by stonemcstoned** [comment]
The calendar widget has been fixed but the YouTube quick actions widget
bottom buttons are not visible, though I can click on them. I accidentally
closed the thread in github, I'm not familiar with github so I apologise
for my mistake
