### ISSUE TITLE
Move up when clock disabled 

### ISSUE THREAD

**Issue by tnclftn** [8bitPit/Niagara-Issues#2470]
When unchecking "Show clock" the app list and widgets could move up and claim the free space in order to fit longer app list. Otherwise the option makes less sense since it only makes it look less busy but leaving just empty space above everything.

**Comment by NiagaraSupport** [comment]
Hello and thank you for your report. You can currently use the 'Move Widget' option to manually fill out that space. 
If your desired use case involves automatically snapping the home screen contents to the top, unfortunately, that would clash with one-handed usage. The current option of setting a fixed position or moving the widget and favorites down allows for easier handling in that context.
