### ISSUE TITLE
Swipe up to search delayed after exiting and app.

### ISSUE THREAD

**Issue by lcasta7** [8bitPit/Niagara-Issues#2473]
### Describe the bug

A cool feature, of the `Swipe up to search` option, that I like is that you can also use the home button on the navigation bar to trigger Niagara's search.

This feature is delayed when exiting an app. I often find myself having to press the home button, or swipe up, multiple times in order to have the actual search come up.

As a user of Niagara, I would like to the latency of launching the search to be reduced after exiting an app so that I can better multi-task

screen-recording will be attached

### Steps to reproduce

1. open an app
2. exit the app by hitting the home button on the nav bar
3. keep hitting the nav bar until the search comes up

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung Galaxy S10e

### Android version

Android 12

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/121523377/d199b76d-052f-4ffd-934d-bda24e5ed7c9

**Comment by NiagaraSupport** [comment]
Hey there,
Since this issue was reported, we've made some updates. The delay is intended to prevent accidentally triggering the search by double tapping. The time set has since been adjusted, so I'll close this ticket now.
