### ISSUE TITLE
Default home screen is visible for a few seconds. 

### ISSUE THREAD

**Issue by FarazAhmad541** [8bitPit/Niagara-Issues#2477]
### Describe the bug

Don't know about other models but on my vivo y53s it shows default home screen and app drawer for a couple of seconds and switch back to Niagara afterwards when the device is locked for extended period of time i.e. 50 to 60 mins. 

### Steps to reproduce

Keep the device locked for about 50 to 60 mins
Unlock the device
The Default home screen can be seen for initial 2 to 3 secs. 

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova Launcher 

### Device name

Vivo y53s

### Android version

Android 13

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
I'm currently addressing some older tickets. Is the issue you mentioned still happening?
