### ISSUE TITLE
Switch Apps Gesture Breaks After Switching Users

### ISSUE THREAD

**Issue by jedthe3rd** [8bitPit/Niagara-Issues#2478]
### Describe the bug

The switch app gesture stops working when you switch to a different user. I can temporarily fix the issue by clearing the Pixel Launcher storage.

### Steps to reproduce

On an Android 14 Pixel Device with Niagara Launcher installed and set as default home screen and another user created with Niagara Launcher set as default home screen:
1. Enable Gesture Navigation
2. Switch to a different user
3. Try to activate the switch app gesture navigation

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

Microsoft Launcher

### Device name

Google Pixel 5

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Thank you for your report. Unfortunately, gestures are something we have little to no control over, so contacting Google, as jedthe3rd did, is likely the best approach for getting it fixed.
