### ISSUE TITLE
Going to the wallet shortcut from the lock screen and unlocking the device returns user to the launcher home screen

### ISSUE THREAD

**Issue by ramkumarshankar** [8bitPit/Niagara-Issues#2480]
### Describe the bug

When tapping on the wallet shortcut on the Android lock screen, the user is taken to a screen with their configured payment cards. 

Unlocking the device at this point takes the user back to the Niagara launcher. This means the user now has to go back to Wallet app for contactless payments.

On the default Pixel launcher, unlocking the device on the wallet screen keeps the user on the same screen so that they can make contactless payments easily.

### Steps to reproduce

1. Ensure you have a shortcut to the wallet on your lock screen.
2. Lock your device.
3. Wake up the device.
4. Touch and hold the wallet shortcut on the lock screen. The user will now be taken to a screen showing their configured payment cards with a "fingerprint" icon to unlock the device.
5. Unlock the device.

Actual - the user is taken to the Niagara launcher home screen.

Expected - the user should remain on the wallet payment cards screen in order to make contactless payments. This is the behaviour on the Pixel launcher.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6 Pro

### Android version

Android 14

**Comment by ramkumarshankar** [comment]
Thanks for taking a look at this. I tried this again recently just to be sure, and the issue is not happening anymore.

The behaviour of Niagara launcher and the Pixel launcher is the same. This issue can be closed.

**Comment by NiagaraSupport** [comment]
Thanks for letting us know.
