### ISSUE TITLE
Anycon - filter and smart folders

### ISSUE THREAD

**Issue by Lorestan00** [8bitPit/Niagara-Issues#2481]
### Is your feature request related to a problem?

It would be helpful to offer ways to find apps more quickly through filtering based a particular category of apps e..g social media, travel

Similarly through categories the  manual process of creating folders of apps which can be time consuming could be automated. 

### Describe the solution you'd like

Anycon feature I think could be utilised not just to add icons to apps where an icon hasn't been developed but also by using the categories which were created to enable this... as a filter. 

A single filter bar above favourites. You would click it and a search field appears with all the categories below. You can either scroll to find the category or search. The relevant apps appear temporarily in place of favourites. At the moment through search you can sort of achieve this but there is no way to know what the categories are which have been created in the backend of Anycon. This surfaces that data. 

Further to this when creating folders you would have the option to pick a category which would automatically create a folder with apps in that category. Essentially allowing for 'smart folders' each time new apps are installed they would appear here

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
I'm working through some older tickets at the moment. We have something similar planned already, and I've forwarded your suggestions to the relevant dev. Please refer to #2621 and its content for more details. I'll mark this as a duplicate and close it.
