### ISSUE TITLE
Publish an Android shortcut for launching Niagra search

### ISSUE THREAD

**Issue by gsxdsm** [8bitPit/Niagara-Issues#2482]
### Is your feature request related to a problem?

I'd like to be able to launch Niagra search from other apps (ex edge gestures). In order to do this Niagra needs to publish a shortcut to its internal search activity. Thanks!

### Describe the solution you'd like

An Android shortcut published to launch directly to Niagra search 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by alankyshum** [comment]
Sesame has been my search app until I replaced it with Niagara, and I love how easy I can trigger search from any app by using [One Hand Operation +](https://play.google.com/store/apps/details?id=com.samsung.android.sidegesturepad) app on Samsung device. I wish I could trigger Niagara search as easy as triggering Sesame.

Surfacing Niagara Search to Android would open up huge opportunity, e.g. tasker automation to send input to Niagara, Bixby routine, voice command, etc. all it does is just opening that Niagara search activity public.

Or an easier solution to achieve that maybe allowing the search action to be triggered through intent, so I can create shortcut for it using [shortcut maker](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker)

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
Working through some older tickets right now. Perhaps [this](https://niagaralauncher.app/app-link/search ) helps.
