### ISSUE TITLE
Sort Folder names by international characters

### ISSUE THREAD

**Issue by ssssamstrup** [8bitPit/Niagara-Issues#2483]
### Describe the bug

#455 added support for international characters. Please let Folder names follow the same sorting for characters as for App names.

Folders support (at least - which I use) Æ, Ø and Å. But when renaming a folder using Æ, Ø or Å, they are placed wrong:
* Æ and Å are placed after A and
* Ø is placed after O.

In the Danish alphabet these should be placed at the end like A, B, C...Z, Æ, Ø, Å.

### Steps to reproduce

Create a Folder. Rename it Æ, Ø or Å.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Sony XZ2 Compact

### Android version

Android 10

**Comment by NiagaraSupport** [comment]
Hey there,
I'll go ahead and close this now, as it was implemented a while back.
