### ISSUE TITLE
Different behavior in agenda for dates and events 

### ISSUE THREAD

**Issue by Mamacanoa** [8bitPit/Niagara-Issues#2485]
### Describe the bug

When I click a date in the agenda it opens Google Calendar. When I click an event it opens my actual default calendar app.
Expected behavior would be to always open my selected default calendar app. 

### Steps to reproduce

1. Open Niagara widget
2. Click on date to open calendar agenda view
3. Click on a date where there is no event (-> Google calendar)
4. Click on a listed event (-> default calendar app) 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Oneplus Nord 

### Android version

Android 12

### Screenshots / Screen recordings

Default calendar app is acalendar 

https://github.com/8bitPit/Niagara-Issues/assets/44476909/0b341d84-8b51-4461-bd56-989b3a351239

**Comment by NiagaraSupport** [comment]
Thanks for the report, and sorry for the late reply. I am working through some older tickets right now.
Calendars are wonky regarding default settings. One way I found to ensure the default calendar is being used over the Google Calendar is:
- Disable Google Calendar in the app settings.
- Re-enable it.
- The next time you click on something in the agenda, use the "Always open with" option.
I hope this helps.
