### ISSUE TITLE
New clock widgets: missing am/pm

### ISSUE THREAD

**Issue by pasqualedante** [8bitPit/Niagara-Issues#2489]
### Describe the bug

When I add one of the new clock widget, if my system clock is set in 12 hours mode, AM/PM is missing. 

### Steps to reproduce

Add one of the new clock widget to home screen. 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Redmi Note 9

### Android version

Android 12

**Comment by 8bitPit** [comment]
Hey @pasqualedante, thanks for the report. It's intended that Niagara Launcher doesn't show an AM/PM indicator for a cleaner look, similar to the lock screen on most Android devices. We removed the AM/PM indicator in 2018 when our launcher was in beta.
