### ISSUE TITLE
Reverse app search result display ordering for better one handed use

### ISSUE THREAD

**Issue by DGollings** [8bitPit/Niagara-Issues#249]
Really like the launcher, especially the 'home button' application search shortcut.

Can't find app, press home, keyboard pops up near bottom of screen, tap a letter. Tap the app

Except that the app I'm looking for tends to be near the top of the screen. Which makes it more difficult to reach with one hand. If results are sorted from bottom of display area to top it would be easier to use.

Example:
Search input field
**Closest match**
Next closest match
(whitespace)
(whitespace)
(whitespace)
Keyboard

Would be easier using one hand as:
Search input field
(whitespace)
(whitespace)
(whitespace)
Next closest match
**Closest match**
Keyboard

My thumb is on or near the keyboard position, the app I'm looking for is most likely out of reach near the top. The result that tends to be nearest my thumb tends to be a hidden app. The last thing I probably want to click, or maybe I simply have short thumbs :)

**Comment by 8bitPit** [comment]
Hey, thanks for your request, I'll try that out.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
