### ISSUE TITLE
Widget has no rounded corners when launcher restarted, until prompted to be shown again

### ISSUE THREAD

**Issue by grigoriosmaz** [8bitPit/Niagara-Issues#2490]
### Describe the bug

Widget corners start off unrounded until it exits view and re-enters it again

### Steps to reproduce

Add widget, force stop app, open it again, widget corners are now no longer rounded.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

One UI Home

### Device name

Galaxy A54

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/103335202/3b93e6e4-4e5c-495f-8b3b-a0831de92d54

**Comment by NiagaraSupport** [comment]
Hey there thank you for your report.
Working through some older tickets right now. Is the issue shown still occurring?
