### ISSUE TITLE
Improve one hand / thumbs navigation

### ISSUE THREAD

**Issue by Morgy93** [8bitPit/Niagara-Issues#2491]
### Is your feature request related to a problem?

I'm always frustrated when the things I want to reach quickly are far away from my thumb.

On stock Android you can place apps on the bottom of the screen which are as close as possible to the left or right thumb:

<img width="288" alt="image" src="https://github.com/8bitPit/Niagara-Issues/assets/7961978/93ffa63f-9de8-41a1-ba70-3454e3df3e37">

(random internet image) 

Using Niagara Launcher the apps are far away from the bottom corners:

<img width="407" alt="image" src="https://github.com/8bitPit/Niagara-Issues/assets/7961978/3ead034f-d791-49ce-9bfd-191c92233c60">

And the "sort by usage" sorts them to the top instead of bottom which means that the most used apps are sorted even further  away from the thumbs.

### Describe the solution you'd like

There could be multiple things to improve here:

- Make sort by usage sorting from the bottom up instead of top down. (Making this configurable would be perfect)
- Pulling the layout to the bottom so the massive whitespace is removed. The layout could then move upwards if there are more favorites. But at least it is always possible to have things on the easy to reach bottom area.
- Possibility to add more of this quick action buttons like for the camera on the screenshot above.
- Possibility to add more swipe options to the quick action button. Currently it only supports the swipe up action, but it could also support swipe left, right and down.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hello, thank you for your feature requests. Regarding your second point, you can move the favorites list further down on your screen by adjusting the position of the Niagara widget. This might already solve the issue. If not, I believe it would be best to split these into several different tickets. It's easier for us and our community to keep track of requests when they are reported one by one. Could you please open individual issues for each of your requests?
