### ISSUE TITLE
Set a specific timer automatically as a shortcut when pressing the Niagara Button

### ISSUE THREAD

**Issue by AmmarAriffin** [8bitPit/Niagara-Issues#2492]
### Describe the solution you'd like

As easy as reading the title. A shortcut for Clock to set a timer automatically (15 minutes, 30 minutes, 30 seconds)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your request.
I'm working through some older tickets right now. Currently, you can set up a shortcut to the clock for the Niagara button, also allowing you to start a new timer on the button press.
