### ISSUE TITLE
Takes a long time to switch back to recent app

### ISSUE THREAD

**Issue by djnotes** [8bitPit/Niagara-Issues#2497]
### Describe the bug

the app takes a long time to switch back to recent app. I haven't seen similar issue with any other launcher. I love Niagara's design and overall, but this delay is just overwhelming. What is the technical reason behind this delay? Are you killing apps when pausing them? 

### Steps to reproduce

Open a few apps and spend a few minutes in one app. Then swipe up the phone to see your recent apps. Choose to one of the recent apps. it takes considerable time for the app to draw on screen and be usable. 

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Nokia 3.2

### Android version

Android 11

**Comment by NiagaraSupport** [comment]
Hello there, thank you for your report. Unfortunately, this seems like a hardware-specific problem, so there isn't anything we can do about it. We don't terminate open apps or clear their cache ourselves. Sorry. If I can help you otherwise, feel free to let me know.
