### ISSUE TITLE
More widgets on homescreen without folders

### ISSUE THREAD

**Issue by masterbumikcz** [8bitPit/Niagara-Issues#2498]
### Is your feature request related to a problem?

I would like to see all my to-do list with other widgets as soon as I open my phone, without need to open folders

### Describe the solution you'd like

More widgets on homescreen without having them in folders. Plus something like scrolling down to have more space for them would be great too

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hello there, and thank you for your request. Unfortunately this would collide with our [design philosophy](https://help.niagaralauncher.app/article/8-niagaras-design-principles#:~:text=has%20to%20be%E2%80%A6-,Simple%3A,-It%20is%20easy).
We try to keep the home screen clean and simplistic to avoid clutter. I'll keep track of this request, but close it for now. Thank you for your understanding.
