### ISSUE TITLE
Very high battery usage

### ISSUE THREAD

**Issue by Caioflandau** [8bitPit/Niagara-Issues#2499]
### Describe the bug

I noticed my phone's battery started draining pretty quickly recently. When I checked battery usage by app, Niagara jumped to the top (its usually not even top 5 on my phone). Not sure exactly when it started, but probably less than a couple weeks ago?

Might be related: I noticed that going back to the home screen from an app takes a bit - there's some lag. Reason I think it might be related is that maybe Niagara is doing some heavy processing on main thread which could impact battery usage and also make the UI less responsive. I'm on a new-ish high end device (details below), so this is not a hardware problem - also no other apps have this issue.

### Steps to reproduce

Just use the app 🙂

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Oppo Find X5 Pro

### Android version

Android 14

### Screenshots / Screen recordings

Recording of the lag I mentioned:
https://github.com/8bitPit/Niagara-Issues/assets/663302/bcf74467-30f4-4345-8fd7-3877520b2fa6

**Comment by Caioflandau** [comment]
App usage in comparison with other apps (Instagram/Line/Facebook are typically top 3 every time, by far):

![Screenshot_2023-12-22-20-10-16-51_0ba066473b79d6e213a1f6f52505e2ee](https://github.com/8bitPit/Niagara-Issues/assets/663302/8ff6f46b-ad59-4388-904b-8a2ad0cf6876)

**Comment by NiagaraSupport** [comment]
Hi there, thank you for your report. Battery usage this high is unusual; it might, however, not be Niagara itself that causes numbers like these. ([Link to knowledge base article](https://help.niagaralauncher.app/article/17-memory-consumption#:~:text=memory%20usage%20of%20several%20services%20that%20Niagara%20Launcher%20uses%2C%20but%20not%20part%20of%20Niagara%20Launcher)).
Is this issue still occurring?
