### ISSUE TITLE
Most used apps above favourites

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#25]
I dont really like having to scroll down just to see and open my most used apps, maybe there should be a setting where you can put most used apps above or under favourites

**Comment by jakcharvat** [comment]
Or you can just remove your favourites... 

I've done that and don't regret it a single bit. Most of the time the app I want is already in the list

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
