### ISSUE TITLE
Show alarms and weather information as notification. 

### ISSUE THREAD

**Issue by Rod911** [8bitPit/Niagara-Issues#250]
Similar to showing the whole notification by swiping the respective app, swipe on the clock to show upcoming alarms, events and detailed weather info.

**Comment by 8bitPit** [comment]
Could be a neat feature, will keep that in mind!

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
