### ISSUE TITLE
Animations are not okey after OneUi 6 Update

### ISSUE THREAD

**Issue by hayrirtr** [8bitPit/Niagara-Issues#2500]
### Describe the bug

After OneUi 6 update animations are like buggy/stuttared/seizing up. I do not know the correct word for that sorry for my language knowledge. 

Swiping up to go to the homescreen, icon just goes to air, nowhere.  It is not going where it actually in the favorite list. And as I mentioned before this animation is also buggy. There is something like a fps drop. It also happens when swiping up to search in the homescreen. 
And in some app that camera bar area at the top it goes black and then white again while going to home screen. 

Also,  in opening an app animation the corners are not rounded.

So in general animations are buggy. I really like the niagara launcher and want to use it but with this problem I took a break unfortunatally until it is fixed. 

### Steps to reproduce

Swipe up

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Samsung s23

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hi there, and thank you for your report. Is this issue still occurring? 
If so, unfortunately, it isn't something we can fix ourselves. Some [secret commands](https://niagaralauncher.app/app-link/secret-command?cmd=togglecloseappanimation) might provide an acceptable workaround until the issue gets fixed.

**Comment by hayrirtr** [comment]
Unfortunately it is still same. Problems are still occuring. And that secret command is not changing anything also, if it should, i do not know why it is not working. 

So if you can not do it, is one ui responsible for this and samsung must fix this? Can it be fixed with a newer version of one ui then? Sorry if I ask silly questions. I really like your launcher and I want to use it. 

By the way I haven't tried any other launcher about this situation. I am not using any other. Before I wrote it occurs with other launchers but i think i misunderstood the question.

**Comment by NiagaraSupport** [comment]
I'm sorry to hear that it didn't help in this case. The bug may get fixed with newer versions, and they are at least aware of it. When exactly, unfortunately, we can't influence. 
I'll close this ticket and reference it in #2417, as it's similar.
