### ISSUE TITLE
Clicking on "Wallpapers" leads me to a "Live Wallpapers" page so I cannot use latest wallpaper features

### ISSUE THREAD

**Issue by tandrasi** [8bitPit/Niagara-Issues#2501]
### Describe the bug

I am trying to use the new wallpaper features added in the latest update. Clicking on "Wallpapers" in Niagra Settings always leads me to a page for "Live Wallpapers" which I cannot get out of no matter what I try. I have rebooted my phone and even re-installed Niagra. It's like it's hardcoded to open this page and there's nothing I can do.

### Steps to reproduce

1. Click on Niagra Settings > Look > Wallpaper
2. Sadness :(

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung Galaxy S10+

### Android version

Android 12

### Screenshots / Screen recordings

![Screenshot_20231223-205206_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/72114492/fda88964-06b8-4180-b996-e6a248af6c34)
![Screenshot_20231223-205214_Live Wallpaper Picker](https://github.com/8bitPit/Niagara-Issues/assets/72114492/9e5f0df5-c8a1-47ca-82d2-d323b727579f)

**Comment by NiagaraSupport** [comment]
Thank you for reporting the issue. I'll go ahead and close the ticket now.
