### ISSUE TITLE
Anycons Outline wrong color in folders when using manually selected icons 

### ISSUE THREAD

**Issue by Manu99it** [8bitPit/Niagara-Issues#2505]
### Describe the bug

I've already reported it on telegram 2 weeks ago but I think there is better. When using the outline icon pack (it's awesome btw!), if you select a custom icon, it doesn't change between light/dark when theme changes. The bug is similar to the one addressed by a previous bug fix, but for manually selected icons. I'll leave a screenshot

### Steps to reproduce

1. Stay in dark mode or light mode system Wide
2. Use outline icon pack
3. Select an icon in a folder and change it with another icon from outline icon pack
4. Change to light/dark theme system Wide
5. The folder background changes color, the icons change color, but manually selected icons don't

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 5

### Android version

Android 14

### Screenshots / Screen recordings

![Screenshot_20231224-120043](https://github.com/8bitPit/Niagara-Issues/assets/19348772/e0b75516-332e-4cf7-ab0a-8a172b7ccaf4)

**Comment by 8bitPit** [comment]
Thank you for the report @Manu99it! We could reproduce and fix the bug, we'll release the fix with out next update.
