### ISSUE TITLE
Today's weather at a glance

### ISSUE THREAD

**Issue by Scott123456** [8bitPit/Niagara-Issues#2506]
### Is your feature request related to a problem?

I'm frustrated by the hourly forecast for today's weather. As pointed out in #2232, scrolling through a full day of hourly conditions is cumbersome, and for me not easily gleaned from (i.e., not "at-a-glance").

I've read the FAQ on "Why is there no daily forecast for today?" and I disagree with the justification for this, especially when pretty much every weather app provides this.

### Describe the solution you'd like

I have a proposed solution for those who want a simple and easy to view display of today's weather. OpenWeather has a Morning, Afternoon, Evening, and Night forecast (screenshot attached) for the current day. Could this be used to replace the hourly forecast so it all fits on one page without horizontally scrolling through the entire day? Is it available through the API? If not, can it be recreated using the hourly data?

![Screenshot_20231224-082133](https://github.com/8bitPit/Niagara-Issues/assets/10225537/1a969574-d92d-4250-b8a2-219b6a404332)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Manu99it** [comment]
I have a similar issue. The weather data displayed is somewhat lacking and not so useful. The main issue for me is that if you click the hourly data in any way it doesn't open the default weather app

**Comment by tjsuominen** [comment]
For Niagara, I do not think it's main focus is to develope the weather part much further. There are 10s of weather apps with good widgets, just place the one you like with the launchers multi widget functionality.

**Comment by gui-baeta** [comment]
> For Niagara, I do not think it's main focus is to develope the weather part much further. There are 10s of weather apps with good widgets, just place the one you like with the launchers multi widget functionality.

I do think that some kind of simple "click to go to <your default weather app>" when clicking on the weather information in Niagara is still a worthwhile thing. If the usability can be improved with low effort, it should.

Now, I'm an advocate for simplicity and not cluttering things up for the sake of it. If this were to be implemented in some way like I'm saying it should be done right of course. I don't like things made out of the blue and specially not in something like Niagara where the decisions take into account how the tiniest change could impact usability and complexity.

In sum, I do think this should be something to look at but not at all a priority.

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your report and sorry for any frustration caused. Also, thank you to everyone participating in this discussion as well.

To be completely honest, this is not something we will be looking into in the near future. Aside from the reasons already provided by others, some people prefer the hourly forecast and we try to keep the amount of optional toggles and sliders to a minimum if possible [(link to our design philosophy)](https://help.niagaralauncher.app/article/8-niagaras-design-principles).

As mentioned by tjsuominen, I'd suggest turning off the weather in the widget settings and switching to a weather app or widget of your choice for now. If we ever rework the weather, I'll address the points made here with the team.
