### ISSUE TITLE
Niagara and KLWP 

### ISSUE THREAD

**Issue by AidanIgast127** [8bitPit/Niagara-Issues#2507]
I don't know if it's my os, Niagara Launcher, or KLWP

but it seems like Niagara doesn't recognize KLWP as wallpaper, is it something wrong with Niagara's integration?

note: I did receive notification like something was stopped, I don't know what it's too fast.

my device info:
INFINIX HOT 11s NFC - Android ver 11

![Screenshot_20231226-033020.jpg](https://github.com/8bitPit/Niagara-Issues/assets/154846671/3b3a5faf-cf00-4359-9fd6-605fddd70caf)

![Screenshot_20231226-033032.jpg](https://github.com/8bitPit/Niagara-Issues/assets/154846671/850590ea-d4ae-482b-a512-65a7fdccb81a)

![Screenshot_20231226-033054.jpg](https://github.com/8bitPit/Niagara-Issues/assets/154846671/9a9a4201-6735-4ae9-9dbe-34540916e8aa)

![Screenshot_20231226-033103.jpg](https://github.com/8bitPit/Niagara-Issues/assets/154846671/580f19e3-a764-4666-9284-ddb777367898)

edited:
1. I've tried to My other device with different vendor, also the result is same.

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for your report. 
Unfortunately, this isn't something we can fix. In this case, the theme color has to be provided by KLWP. Let me link this article right [here](https://help.niagaralauncher.app/article/36-wallpaper-bugs#:~:text=wallpaper%20notifies%20the%20Android%20system) real quick. I'd recommend addressing this issue with KLWP as well. 
Feel free to let me know if you need any more help.
