### ISSUE TITLE
Alphabets interfering with Widget 

### ISSUE THREAD

**Issue by sjhalapuzha** [8bitPit/Niagara-Issues#2508]
### Describe the bug

This can't be written in feature request. The alphabets on the right side of the home page always interferes with calendar and task widgets.  As a result it fails the purpose of widget which is adding task and events. The alphabets sensitivity should be a little lower so it will not overlap with widget buttons

### Steps to reproduce

Just select something on the widget, on the right side of the widget

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Iqoo Neo 6

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_20231226_180353](https://github.com/8bitPit/Niagara-Issues/assets/83710936/e01d61f5-0da3-4cfa-b9ed-1940c6ca6e6d)

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for your report. In this particular case, I recommend disabling the 'Fill screen' option for the widget. Doing so should enhance usability. However, if this doesn't address your issue specifically, to be honest, it probably isn't something we can fix in the near future. If you have any further questions or if there's anything else we can assist you with, please feel free to let us know. We appreciate your understanding and feedback!
