### ISSUE TITLE
provide a non-search way of viewing hidden apps

### ISSUE THREAD

**Issue by aerickson** [8bitPit/Niagara-Issues#2509]
### Is your feature request related to a problem?

The setup step that recommended hiding apps made it seem easy to view hidden apps (I thought it was possible to swipe from left or something), but I now see it's only via searching. I like the idea of having frequently used and less used (hidden apps), but the discoverability is low. For example, I have games that I rarely play and don't remember the names that I've hidden... in Pixel Launcher I'd have a page or folder.

I've unhidden all of my apps (I had 300 hidden) for now.

### Describe the solution you'd like

Please provide a non-search way of viewing hidden apps.

Potential solution: if swiping from left side, the alpha scroller should show hidden apps. Swiping from right will still only show non-hidden apps.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, thank you for your report.
If I understand your desired use case correctly, I'd suggest setting up pop-up folders with your hidden apps in the all-apps list. You could then link this folder to the Niagara button's tap or swipe-up gestures to quickly access them.
Let me know if this isn't a sufficient solution for you or if you need help setting it up.
