### ISSUE TITLE
Option to disable Android's Night light when Morning mode is ended

### ISSUE THREAD

**Issue by Elyssy** [8bitPit/Niagara-Issues#2510]
### Is your feature request related to a problem?

No. 

### Describe the solution you'd like

I wonder if we could add an option to disable Android's Night light (maybe also Extra dim) when morning mode is turned off. 

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, thank you for your report. 
Sorry to say that this isn't something we have access to or can easily implement ourselves. Could you elaborate on your desired use case here? If all you wish for is to set up a daily routine for when Nightlight is on, that is already possible through the system settings. Let me know if you need any help with that, or your reason differs.
