### ISSUE TITLE
Daily Random Wallpaper

### ISSUE THREAD

**Issue by darthmk** [8bitPit/Niagara-Issues#2514]
### Describe the solution you'd like

Hi,
I really appreciated the new wallpaper collections introduced in the new version!
I think it would be great to have a setting to change randomly the wallpaper daily so to have a different wallpaper every day.
Thanks for all your work on this amazing project!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, and thank you for your request,
I'll go ahead and close this ticket as it is similar to, and referenced in #2514
