### ISSUE TITLE
Niagara Launcher' Text

### ISSUE THREAD

**Issue by AidanIgast127** [8bitPit/Niagara-Issues#2515]
is it possible for Niagara's Text color to change adaptivity from wallpaper?
just like anycons icon pack and Niagara's button?

**Comment by NiagaraSupport** [comment]
Hi there, and thanks for the request.
Fonts are something that will be worked on in the near future, and I'll make sure to bring up your suggestion to the rest of the team then. But it is probably infeasible for us right now, so I'll close the ticket for now. I appreciate your understanding.
