### ISSUE TITLE
switch between any language with one click

### ISSUE THREAD

**Issue by faon-92** [8bitPit/Niagara-Issues#2518]
### Is your feature request related to a problem?

Hi,
I use french with Gboard and Chinese with wechat input keyboard, I need ro click twice everytime I switch. Is it possible to allow ome click switch by Niagara Launcher?

### Describe the solution you'd like

One click switch between any language,. somewhere on main screen 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hello there and thank you for your suggestion.
I'm afraid this is infeasible for us to implement. I'd recommend trying out different multilingual keyboard apps in this case or addressing the issue with Gboard or WeChat instead.
