### ISSUE TITLE
Match Notification Summary icon to Niagara Anycon style

### ISSUE THREAD

**Issue by mzwolsky** [8bitPit/Niagara-Issues#2521]
### Describe the solution you'd like

I love the new Anycons and wallpapers, a big kudos for those!

This is for a small inconsistency I've noticed: The icon that's displayed atop the favorites for Notification Summaries is always a simple material design icon. It would be very neat if that adapted to the chosen Anycon style too (for example watercolor in this screenshot).

Thanks and Happy New Year 🎇

![Screenshot_20240101-141120](https://github.com/8bitPit/Niagara-Issues/assets/42410002/c75acf3b-9649-4a5e-a2c7-7227818de396)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, thanks for your suggestion.
The idea there was that the summary should somewhat stand out from the rest of the screen, but we might reevaluate that decision.

**Comment by mzwolsky** [comment]
Thank you for considering it and sharing your reasoning behind it! From an accessibility standpoint I can see that a summary that stands out might be better 🤔

**Comment by 8bitPit** [comment]
Implemented in [v.1.12](https://github.com/8bitPit/Niagara-Issues/releases); thanks for the suggestion, @mzwolsky!

**Comment by mzwolsky** [comment]
Thank you! Looks great 😀
