### ISSUE TITLE
When I change wallpaper, the launcher crash and restart

### ISSUE THREAD

**Issue by wenyetom** [8bitPit/Niagara-Issues#2523]
### Describe the bug

I use the app called "Wallpaper Changer" to change my wallpaper, and the launcher seems to crash and restart.
I tried to reinstall old version, then I found that this problem is existed since version 1.10.0.

### Steps to reproduce

Change wallpaper

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova Launcher, One UI Launcher

### Device name

Samsung Galaxy S23

### Android version

Android 14

### Screenshots / Screen recordings

https://youtu.be/N7dRrWFVFjA

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your report.
I can't find any crashes in the video. The launcher seems to be simply restarting/refreshing the home screen on a wallpaper change, which is normal. Feel free to elaborate if I missed something.

**Comment by wenyetom** [comment]
I would like to know that this process of restarting is removable? As shown in the video, restarting did not occur before version 1.10.0. Therefore, I suspect that some new feature may be causing the launcher to restart when wallpaper changed.

**Comment by NiagaraSupport** [comment]
If the wallpaper changes, we need to restart the U/I so that the color palette (theme and such) changes to the correct colors. This didn't happen before version 1.10.0. Unfortunately, there is currently no way around the restart. I appreciate your understanding.

**Comment by wenyetom** [comment]
OK, I understand. I probably know how to prevent launcher restarting. Thanks for your help and answer.
