### ISSUE TITLE
More swipe options for quick action button

### ISSUE THREAD

**Issue by Morgy93** [8bitPit/Niagara-Issues#2525]
### Is your feature request related to a problem?

This is an improvement idea from https://github.com/8bitPit/Niagara-Issues/issues/2491

### Describe the solution you'd like

Currently you can only configure the "swipe up" gesture for the quick action button.

I'd love to have a "swipe left", "swipe right" and "swipe down" configurable action.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hello there, and thank you for your report. I'm afraid that adding more gestures to the Niagara button clashes with our design philosophy. For more information on this topic and our decisions, you can refer to this [article](https://help.niagaralauncher.app/article/116-niagara-button).

To address your issue specifically, I recommend attaching pop-up folders to the tap or swipe gesture, respectively.
Let me know if you have any further concerns.

**Comment by Morgy93** [comment]
Let me copy it here:

> Why can we only utilize one swipe gesture?
We don't want to overload the Niagara button with dozens of gestures. That's because we want to keep everything simple and easy to remember, and only allowing one swipe gesture makes the behavior of the button more consistent with the behavior of app pop-ups. The swipe-up gesture is the easiest one to execute at the bottom right corner. If you want to keep your home screen free of apps, we recommend adding a pop-up to the Niagara button.
https://help.niagaralauncher.app/article/116-niagara-button

Well, that's sad. I'd say the "easiest" gesture (for me) would be to swipe down, but that's probably up for debate as well.
I mean, if it is configurable, everyone can configure it to their likings. Keeping things simple does not mean to prohibit options.

I'd be more than happy if you are about to re-think your "design philosophy", anytime.

Closing for now~

**Comment by NiagaraSupport** [comment]
Thank you for your understanding. I keep log of most requests should our philosophy change at some point I'll bring it up again.
