### ISSUE TITLE
Graphical Artifacts on Pixel when returning to home screen

### ISSUE THREAD

**Issue by austinrheald** [8bitPit/Niagara-Issues#2527]
### Describe the bug

When returning to home screen on Pixel 8 Pro, Android 14, using gesture navigations - graphical artifacts can be seen in transparent space behind app icons. Does not occur 100% of the time, but enough to be very noticeable. This issue occurs with most third party launchers I have tried (Nova, MS) except Smart Launcher. Have tried latest QPR beta as well as a completely fresh stock image flash, result is the same. 

### Steps to reproduce

1. On Pixel device using Android 14 with gesture navigation, open any app from favorites list.
2. Swipe to return home.

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

Nova, Microsoft, Smart Launcher 

### Device name

Google Pixel 8 Pro

### Android version

Android 14

### Screenshots / Screen recordings

https://photos.app.goo.gl/QHRypJZU3PWQZMKD7

**Comment by RobertHarnett** [comment]
Seems to be similar to #2155

**Comment by burgergit** [comment]
I have the same but, also Pixel 8 Pro.
See attached picture.

If it helps I also have a video if needed.

![screen-20240115-193009_exported_3617~2](https://github.com/8bitPit/Niagara-Issues/assets/149727067/44a17a5e-66f5-4bbb-b01e-9ec59f63289d)

**Comment by NiagaraSupport** [comment]
Hi there, thanks for reporting this.
Unfortunately, it's a Hardware issue that we can't do much about ourselves, except wait for a fix from Google. I appreciate your understanding.

**Comment by burgergit** [comment]
@NiagaraSupport 
Thank you for the update.
Do you know if this issue is known to Google?
What is the preferred way to let Google know about this issue?
Do they have a bug tracker?

**Comment by TFackler** [comment]
Seems to be similar to #2155

**Comment by NiagaraSupport** [comment]
> @NiagaraSupport Thank you for the update. Do you know if this issue is known to Google? What is the preferred way to let Google know about this issue? Do they have a bug tracker?

They likely know about the issue, but addressing it with them directly through the Google [issue tracker](https://issuetracker.google.com) might prove helpful.

Since #2155 is similar, I'll go ahead and close this.
