### ISSUE TITLE
Support for app's daylight and dark mode icon

### ISSUE THREAD

**Issue by liyafe1997** [8bitPit/Niagara-Issues#2528]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Some apps have different icon for daylight mode and dark mode. (For example, this one https://play.google.com/store/apps/details?id=com.sl.SLBiljetter). 

But in niagara launcher, it only refresh the icon when change icon pack or icon settings. So if I change this settings in daylight mode, I only can get the daylight icon of the apps, even the system is switched to dark mode.

For niagara launcher, it is better to refresh the icons when switching daylight and dark mode. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there and thank you for your suggestion.
This is not something we should consider implementing for now. The feature must be more widespread to justify forcing an icon refresh on everyone twice daily. You can use a [secret command](https://niagaralauncher.app/app-link/secret-command?cmd=refreshicons) to restore the icons manually if you wish to do so; perhaps this helps a bit. Thanks for understanding.
