### ISSUE TITLE
an option to have a pop up created in all apps list actually sort and appear in the all apps list

### ISSUE THREAD

**Issue by markmidg** [8bitPit/Niagara-Issues#2529]
### Is your feature request related to a problem?

when creating a new pop-up it is misleading to state it is created in Favorites or All apps list when it is actually appended to the end of the All apps list, not put in it.  it should either be a functional option to append or integrate, or just simply integrate as Pop-ups are in the Favorites.

### Describe the solution you'd like

an option to have a pop up created in all apps list be actually sorted and appear in the all apps list next to the apps. so a new pop-up named "Cool" would be found under C, just like a Calculator app would be.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Hey @markmidg, thanks for the feature request. It was already requested at https://github.com/8bitPit/Niagara-Issues/issues/2415. Could you please react with a thumbs up to the other issue so we can track its popularity?
