### ISSUE TITLE
For the minimalist in us, an option to not display labels on the favorite screen

### ISSUE THREAD

**Issue by sfosdal** [8bitPit/Niagara-Issues#253]

**Comment by andrewmcloughlin** [comment]
Or an option to hide favourites entirely

**Comment by 8bitPit** [comment]
It would look add, please look at the image I posted here #79.

**Comment by sfosdal** [comment]
I've uploaded a mock up of what I was trying to describe to the issue you've referenced. It may need some additional tweaks, but not so bad hopefully.
