### ISSUE TITLE
disable the search button

### ISSUE THREAD

**Issue by AnotherNora** [8bitPit/Niagara-Issues#2530]
### Is your feature request related to a problem?

I'm peeved when the Niagara button turns into the search button when scrolling through my apps

### Describe the solution you'd like

I thought it would be nice if there was an option to prevent the Niagara button from turning into the search button. Instead, either have no search button or always have the niagara button.

I believe this will make the niagara button more predictable and more consistent. 

I personally use the niagara button to launch a launcher with a lot of widgets, and I never use it. 

Thanks you (⁠*⁠´⁠ω⁠｀⁠*⁠)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, thank you for your request.
I'm sorry to say this is not impactful enough to be implemented for now. We try to keep the launcher clean and simple where we can, which includes avoiding adding additional sliders or toggles if not necessary. More on our design philosophy can be found [here](https://help.niagaralauncher.app/article/8-niagaras-design-principles).
