### ISSUE TITLE
Minimal live wallpaper

### ISSUE THREAD

**Issue by StDensity** [8bitPit/Niagara-Issues#2533]
### Describe the solution you'd like

Just as Wallpaper, it would be cool to have minimalistic live wallpaper just like the ones on pixel devices. I know it's hard to make but it would be a feature cool to have. Giving more emphasis to the minimalistic live feature. 

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by tjsuominen** [comment]
There are tens already available and you can get basically all of them as APK for your phone.

**Comment by StDensity** [comment]
> There are tens already available and you can get basically all of them as APK for your phone.

Yeah but it would be a coolf feature to have. 
All of those wallpaper doesn't support Niagaras one had design.
