### ISSUE TITLE
Align apps higher up when searching with alphabet 

### ISSUE THREAD

**Issue by MathisP75** [8bitPit/Niagara-Issues#2534]
### Is your feature request related to a problem?

If there are too many apps starting with a certain letter, the lower ones will be cut off when searching with the alphabet. This is because they are aligned way too low. 
![Screenshot_20240104-112051](https://github.com/8bitPit/Niagara-Issues/assets/98901170/075f05b5-11d4-4f6c-944b-7e073433371e)
Here, for instance, there are more apps below the Microsoft 365 app, but they aren't shown. This requires an extra step to open them, as I have to scroll down a bit to see the apps after releasing the alphabet with my finger.

### Describe the solution you'd like

An option to align the apps at the top of the screen would solve this issue.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, thank you for your suggestion.
Perhaps this can already be circumvented by renaming some apps or placing them in a [pop-up folder](https://help.niagaralauncher.app/article/115-pop-ups#:~:text=App%20Pop%2Dups-,Pop%2Dup%20Folders,-To%20add%20one). Let me know if these solutions won't work in your case.

**Comment by MathisP75** [comment]
These are not solutions, they are workarounds. It would simply be better to have the apps aligned higher up so that we can see more of them.

**Comment by NiagaraSupport** [comment]
Apologies if the suggested workarounds don't meet your needs. Currently, there are no plans to adjust the alignment of the all apps list, as it may negatively impact other use cases, such as one-handed usage, for example. We appreciate your understanding.
