### ISSUE TITLE
Add live preview in wallpaper

### ISSUE THREAD

**Issue by Cosin45** [8bitPit/Niagara-Issues#2536]
### Describe the solution you'd like

Live preview Like Google wallpaper

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there and thank you for your suggestion.
A live preview within the wallpaper selection screen is currently not planned, but the Look settings screen will feature one in the future, so I'll close this for now.
