### ISSUE TITLE
move shortcuts to a folder

### ISSUE THREAD

**Issue by firefoxOnFire** [8bitPit/Niagara-Issues#2537]
### Is your feature request related to a problem?

I have created shortcuts from a app. But it was cluttering the screen, so I decided to put them in folder, but it was very hectic to add them in folder one by one using Niagara add shortcut option.

### Describe the solution you'd like

It's very hard to create shortcut one by one in a popup folder. Instead create all the shortcuts from an app then move them to a folder.

Add a move to a folder button after long press. Like add category. In add category, whenever i remove original shortcut, it is getting removed from folder too.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for your report. When long-pressing the popup folder, you can use the "Edit Folder popup" option and then simply select all apps and shortcuts (at the bottom of the list) to add to that folder in one go.
Let me now if this doesn't address the issue you are facing.

**Comment by NiagaraSupport** [comment]
Thank you for the clarification. I believe I understand the issue better now. The process to achieve your desired use case is somewhat unintuitive and I apologize for any confusion. Let me summarize the steps to reach your goal more efficiently:

1. Add shortcuts to the home screen as needed.
2. Edit the pop-up folder and include the shortcuts you want in that folder.
3. Use the "Edit favorites" option to uncheck shortcuts you do not want on the home screen. The delete dialog appearing during this step is a UI bug, thank you for bringing this to our attention. You can safely click "delete" here, it will only remove the shortcut from the home screen.
      - The "Remove" option when long-pressing a shortcut is intended to delete it from anywhere, including pop-up folders.
4. Now, all the shortcuts should be exclusively in the folder.

Let me know if there is something else I can help you with.

**Comment by NiagaraSupport** [comment]
It doesn't add them to the app list automatically(the one you see when scrolling through the alphabet), but to add them to the folder they don't need to be in there. You can add them through the 'Edit Shortcuts pop-up' screen( screenshot 1) , at the very bottom under 'Add shortcut' (screenshot 2) and select them there (screenshot 3)
<img width="285" alt="Screenshot 2024-01-10 at 15 25 48" src="https://github.com/8bitPit/Niagara-Issues/assets/151941204/50ff1daf-252c-4673-9acc-da9bf37694c1">
