### ISSUE TITLE
"enable pro badge" on the Niagra button hides the numerical value of coin flips. 

### ISSUE THREAD

**Issue by sefsli** [8bitPit/Niagara-Issues#2538]
### Describe the bug

when enabling the Niagara pro badge on the Niagara button, this supersedes the option to see how many times you flipped the coin. 

so when flipping the "coin" the number is not shown and the coin just shows Niagra pro. 

maybe this is intentional, just wanted to call it out. 

### Steps to reproduce

1. long pressed Niagara button
2. select enable pro badge
3. flip a coin by swiping up on button
4. see no numbers

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Other 3rd-party launcher(s) tested

na

### Device name

galaxy Z flip 3

### Android version

Android 5.0 (Lollipop)

**Comment by NiagaraSupport** [comment]
Hey there and thanks for your report. The number should appear with or without the pro badge active, but the coin flip needs to result in tails. If it lands on heads, the very same pro badge is shown, which is however intentional.
Let me know if this doesn't address your issue.

**Comment by BadRobotzero** [comment]
> ### Describe the bug
> 
> when enabling the Niagara pro badge on the Niagara button, this supersedes the option to see how many times you flipped the coin. 
> 
> so when flipping the "coin" the number is not shown and the coin just shows Niagra pro. 
> 
> maybe this is intentional, just wanted to call it out. 
> 
> ### Steps to reproduce
> 
> 1. long pressed Niagara button
> 2. select enable pro badge
> 3. flip a coin by swiping up on button
> 4. see no numbers
> 
> ### Does the issue also occur with other 3rd-party launchers?
> 
> Not applicable
> 
> ### Other 3rd-party launcher(s) tested
> 
> na
> 
> ### Device name
> 
> galaxy Z flip 3
> 
> ### Android version
> 
> Android 5.0 (Lollipop)
> 
> ### Screenshots / Screen recordings
> 
> _No response_

**Comment by BadRobotzero** [comment]
Call out then right back in few sec

**Comment by NiagaraSupport** [comment]
Hi there, not sure what the last response meant, is there anything i can help you with.
