### ISSUE TITLE
Empty name for Folders

### ISSUE THREAD

**Issue by nwmatheis** [8bitPit/Niagara-Issues#2559]
### Is your feature request related to a problem?

I have app icon names turned off and would like to have a folder with no name beside it. But if I leave the folder name blank, it refers to 'Folder'. And if I enter a space, it again reverts to 'Folder'. This would allow increased visual/thematic consistency when turning app icon names off.

### Describe the solution you'd like

When deleting the default name 'Folder', allow the folder name to remain blank.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there and thank you for your report.
If you hide the names of favorites in the Look settings, the folder name will also be hidden.

**Comment by nwmatheis** [comment]
Thanks for the quick reply!


Best regards,
Nikolaus
