### ISSUE TITLE
Preview icons + widgets when applying wallpaper

### ISSUE THREAD

**Issue by nwmatheis** [8bitPit/Niagara-Issues#2560]
### Is your feature request related to a problem?

It would be helpful to preview icons + widget(s) before applying wallpaper to make sure the wallpaper doesn't interfere with icons + widget(s) and/or that wallpaper elements are positioned correctly in remain to icons + widget(s).

### Describe the solution you'd like

Include a preview of icons + widget(s) during wallpaper selection

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, thank you for your suggestion.
Something like that will be coming in the future, see #2536 response.

**Comment by nwmatheis** [comment]
That's great!


Best regards,
Nikolaus
