### ISSUE TITLE
No Haptics on homescreen. Redmagic 9 Pro

### ISSUE THREAD

**Issue by supermanscottbristol** [8bitPit/Niagara-Issues#2561]
### Describe the bug

Hi folks.
I've got haptics enabled and working on my redmagic 9 pro, but when I scroll down the list of apps on the home screen I get no haptic feedback.
It worked fine on my previous phone which was a Xiaomi Mi 10

### Steps to reproduce

1 Go to Homescreen
2 Scroll down apps on right hand side

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova

### Device name

Redmagic 9 Pro

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hello, and thank you for your report.
I can't speak for the specifics of this phone, but haptic feedback can differ based on device hardware and motor quality. If the quality isn't optimal, we might limit haptic usage to avoid a subpar experience.
How would you rate the RedMagic 9 Pro here?

**Comment by supermanscottbristol** [comment]
I've got rid of the RM9 now. 
It had excellent haptic feedback but just would not work with Niagara. 
I'm now on a OnePlus 12 and the feedback on that works fine with Niagara.

**Comment by NiagaraSupport** [comment]
I see. Thanks for sharing the info, and I'm glad it is working on your new phone now. We'll try to look at why it wasn't working on your old phone.
