### ISSUE TITLE
Widget columns

### ISSUE THREAD

**Issue by antzac** [8bitPit/Niagara-Issues#2562]
### Is your feature request related to a problem?

No - feature request

### Describe the solution you'd like

Ability to "split screen" the widgets above the app list. At the moment I have a weather widget which is edge to edge currently and would be better suited to be square, with another square widget e.g calendar next to it. Would be really cool to see this. I guess similar to how Apple iOS widgets look.
### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, and thank you for your request.
Sorry to say, we currently don't have any plans to add such a feature, as it clashes with our [design philosophy](https://help.niagaralauncher.app/article/8-niagaras-design-principles). I'd instead recommend using the [Widget Stack](https://help.niagaralauncher.app/article/41-adding-multiple-widgets) for multiple widgets. 
We appreciate your understanding.
