### ISSUE TITLE
[Feature Request] Work application support

### ISSUE THREAD

**Issue by wfmer** [8bitPit/Niagara-Issues#2563]
### Is your feature request related to a problem?

Google rnrecently implemented personal/work application segmentation. This is a must have, so despite being a pro user I am back to the stock launcher.
I wish Niagara would implement a way to manage this feature. Adding/Removing apps from the segmentation as well as pausing/unpausing.
![Screenshot_20240120-000636](https://github.com/8bitPit/Niagara-Issues/assets/128558499/39766358-279c-45ca-ab24-7e47e84b0306)

### Describe the solution you'd like

The stock UI works decently well.
I'm sure theres a simpler approach but similarly I'd love to see work apps in a different 'list' when viewing apps. The intent there is work/life separation so not seeing the apps or their notifications is key.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by wfmer** [comment]
This drop-down option is an alternative. Can prob. mark as low, still would love to see a option built into the launcher.
![Screenshot_20240125-203800](https://github.com/8bitPit/Niagara-Issues/assets/128558499/8ba1770f-53ff-438a-9d61-f9eda5ddf054)

**Comment by NiagaraSupport** [comment]
Thanks for your request,
This is similar to #2540 and #1517, so I'll go ahead and close this one.
We appreciate your understanding.
