### ISSUE TITLE
[Feature Request] Time-based widgets

### ISSUE THREAD

**Issue by guit4eva** [8bitPit/Niagara-Issues#2564]
### Describe the solution you'd like

It would be really great to have time-based widgets. For example, there are certain widgets I only use at certain times of the day (morning/evening etc) - it would be amazing to have these widgets surface only during the specified time to keep the home screen clean.

Example:

Habit tracker - have the checkbox widget appear in the evening (6pm-9pm) when I do the specific habit.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by StDensity** [comment]
This is an interesting feature. Keeps the home screen clean.

**Comment by guit4eva** [comment]
Other use cases would be things like:

- Work apps only displayed during work hours
- Fitness apps surfaced outside work hours
- Sleep apps/trackers surfaced after 8pm
- Social apps etc removed after certain time of the day to help curb usage
- Recipe apps etc surfaced after 5pm
- etc

I find the music-based widgets appearing when BT is connected super useful, I feel like a feature like this would also be really amazing :)

**Comment by StDensity** [comment]
I really like this feature, I'll bring more automation to people's life. Now they won't forget stuffs cause it pops up on the screen when you need it. This will be cool for apps like Duolingo.

**Comment by wfmer** [comment]
Have a tidbyt at home, this reminds me a lot of that motion to reduce time on screen. Same motion just different approach as your using the screen, just spending less time through optimization. 
Definitely useful on the tidbyt and can see similar uses. 
Devils advocate POV: Big crux is widget support from the apps, displaying the info you need/want. Niagara can implement and the widget content can still only be partially useful causing you to dive into the app, negating the time optimization users set up.

**Comment by NiagaraSupport** [comment]
Thanks for your request,
This is similar to #2540 and #1517, so I'll go ahead and close this one.
We appreciate your understanding.
