### ISSUE TITLE
Microsoft To-Do integration

### ISSUE THREAD

**Issue by StDensity** [8bitPit/Niagara-Issues#2566]
### Describe the solution you'd like

Microsoft To-do list is a free and powerful Todo app. It'll be great to see Microsoft Todo integrated to the launcher. Not as a widget, something like agenda but you can see tasks. Can easily see my day in that. I know about agendas, but I don't want to put my to-do to the calendar. It'll be a cool feature to have, if we can implement this feature in an innovative way. Something like how we can see agendas but different and simple. At least we should be able to see tasks in my day. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, and thank you for the request.
Sorry to say we currently don't plan to add such a feature. I like the idea, but given the substantial time investment and the availability of apps and widgets already fulfilling the use case, we cannot prioritize this. Should we ever revisit that decision, I'll bring up the points you mentioned with the team. We appreciate your understanding. For more info on our design philosophy, see [Niagara's Design Principles](https://help.niagaralauncher.app/article/8-niagaras-design-principles)
