### ISSUE TITLE
Live calendar icon date

### ISSUE THREAD

**Issue by BADMS** [8bitPit/Niagara-Issues#2567]
### Is your feature request related to a problem?

Active icon that shows day number.

### Describe the solution you'd like

Similar to other launchers.
Icon packs already implement the days 1-31, as I'm sure you know 👍

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hi there, and thank you for the request.
I am sorry to say, that we currently do not plan to implement this feature as we focus on prioritizing impactful changes in line with our [design philosophy](https://help.niagaralauncher.app/article/8-niagaras-design-principles). We appreciate your understanding.
