### ISSUE TITLE
Font size for time not applied when setting larger system display size or text size 

### ISSUE THREAD

**Issue by PhilT** [8bitPit/Niagara-Issues#2568]
### Describe the bug

If you change the system display size to `Large` or the system text size to `Extra large` then the time is rendered in a smaller font.

### Steps to reproduce

Settings -> Display & brightness -> Display size -> DISPLAY SIZE -> Large

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Huawei P30 Pro

### Android version

Android 12

### Screenshots / Screen recordings

Default display size:
![Screenshot_20240124_065922_bitpit launcher](https://github.com/8bitPit/Niagara-Issues/assets/34678/7495ef38-b478-4464-b4db-ba515ddbcebb)

Large display size:
![Screenshot_20240124_064843_bitpit launcher](https://github.com/8bitPit/Niagara-Issues/assets/34678/7c490cfd-d5c5-4c4a-9a09-f02d212c9e1e)

**Comment by NiagaraSupport** [comment]
Hey there, and thanks for the report.
It appears the rescaling brought the clock too close to the top of the screen, which caused the format to change. This is intended behavior, but you can revert to the large clock format by long pressing the clock and selecting the 'Move Widget' option to move it further down again.
Feel free to let me know if you need any more help.

**Comment by PhilT** [comment]
I didn't even know about the long press on the widget!Adjusted and fixed the issue for me. Thanks!
