### ISSUE TITLE
Notification Summary issue

### ISSUE THREAD

**Issue by CR1MS0N24** [8bitPit/Niagara-Issues#2569]
### Describe the bug

Notification Summary not working as intended all app notifications I set it to target slip through restarts and fresh installs have been tried the summary in that case lasts only a few hours before breaking again

### Steps to reproduce

Not sure how to reproduce but error might be MIUI?

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Xiaomi Redmi 9C

### Android version

Android 10

**Comment by CR1MS0N24** [comment]
Perhaps the issue is being worked on if so apologies

**Comment by NiagaraSupport** [comment]
Hey there, sorry for the late reply.
Could you clarify what breaks? Do you receive no summary at all, or is something else going wrong?
If the problem occurs with other 3rd party launchers, it's probably not something we can easily fix, but we'll look at it.

**Comment by CR1MS0N24** [comment]
Hi yes it's just the summary that breaks well the summary and the morning mode notification but other than that everything else works, also sorry im not sure what 3rd party service causes it to interfere with these features

**Comment by NiagaraSupport** [comment]
It could be related to #1144 and the tickets mentioned there, unfortunately, hinting at potential hardware-specific issues beyond our control. However, some of the previous answers could be helpful here, and I'll bring this issue up with the team to see if we can help.
