### ISSUE TITLE
Nothing Icon Pack does not show up

### ISSUE THREAD

**Issue by Auroria-code** [8bitPit/Niagara-Issues#2572]
### Describe the bug

I have a nothing phone with the nothing Icon Pack app from nothing. It works great with my nothing Launcher how ever if I want to use it with Niagara it does not show up as an option. I even goes to the default icons when the pack was previously enabled. Is this a problem on my side, am I doing something wrong?

### Steps to reproduce

1. Have the nothing Launcher with the nothing icons open
2. Open Niagara
3. Icons are stock android, no option to change that

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

Nova launcher

### Device name

Nothing phone (1)

### Android version

Android 13

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
As far as I can tell, the Nothing Icon pack only works on the Nothing OS (see [Playstore desc.](https://play.google.com/store/apps/details?id=com.nothing.icon&hl=en_US#:~:text=Please%20note%20that%20Nothing%20Launcher%20V2.1.0%20or%20above%20is%20required%20to%20ensure%20this%20Icon%20Pack%20works%20correctly)). There are however some 3rd party nothing styled icon packs on the playstore. Let me know if I can provide further assistance.

**Comment by Auroria-code** [comment]
Yeah, the nice thing about the official one is that it converts icons it does not know, the 3rd party one doesn't. But thanks for the response
