### ISSUE TITLE
Widget Pop-Up Button to Open Google Tasks App 

### ISSUE THREAD

**Issue by Bloofire** [8bitPit/Niagara-Issues#2575]
### Is your feature request related to a problem?

Apologies if duplicate, but new to GitHub my search didn't find anything. I noticed a the widget popup, the only way to open the Google Tasks app is clicking on a specific task then backing out of the task. However, I have long list (don't we all...) and sometimes i just want to see everything at one glance and reprioritize. The Notes widget has a button that opens the app. Is this possible for Tasks as well? Many thanks.
![Screenshot_20240127-094710](https://github.com/8bitPit/Niagara-Issues/assets/13499150/0785c08d-376a-41d9-a351-be13e9ef0204) 

### Describe the solution you'd like

Button/Toggle within popup widget for Google Tasks widget to directly open Tasks App in the selected list, similar to Google Keep/Notes. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your request.
Unfortunately, we don't directly handle widget content or behavior ourselves. I'd suggest requesting this feature on Google's [issue tracker](https://issuetracker.google.com/savedsearches/566277) for the best chances of implementation.
