### ISSUE TITLE
Pro verification failing on Graphene OS

### ISSUE THREAD

**Issue by Dev8904** [8bitPit/Niagara-Issues#2576]
### Describe the bug

I am currently trying to verify my purchase but it keeps failing. I know that I have google play/services working as I have been able to verify purchase on other apps. Unfortunately on Niagara launcher it keeps failing with a 404 error.

I have tried to give google play/service all the permissions it needs as well as adding no battery restriction but this does not do anything.

Device: Pixel 7a
Rom: Graphene OS
Version: 1.11.2
Android Version: 14

### Steps to reproduce

1. Install google play/services.
2. Sign in to google play
3. Install Niagara launcher
4. Verify purchase

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 7a

### Android version

Android 14

### Screenshots / Screen recordings

![image](https://github.com/8bitPit/Niagara-Issues/assets/118224693/8a56d54d-7eb2-4f0f-927b-7c645f375243)

**Comment by NiagaraSupport** [comment]
Hi there, and thank you for the report.
If the issue persists, please notify [support@niagaralauncher.com](mailto:mailto:support@niagaralauncher.com). They 
deal with the purchases and should be able to help.
