### ISSUE TITLE
Double tap alphabet to launch any shortcut

### ISSUE THREAD

**Issue by Anarchtism** [8bitPit/Niagara-Issues#2577]
### Is your feature request related to a problem?

I want a custom, easily accessible, shortcut, but don't like how the Niagara button looks.

### Describe the solution you'd like

Being able to customize what double tapping the alphabet does would be nice. I'd personally use it to run a Tasker task.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for your request.
I'm sorry to say that investing time and resources into implementing this seems unreasonable for now. Perhaps you can achieve a similar use case by using pop-up folders or third-party apps on the Play Store. I appreciate your understanding.
