### ISSUE TITLE
Non-Urgent Notification Compartment 

### ISSUE THREAD

**Issue by jbasye0** [8bitPit/Niagara-Issues#2578]
### Is your feature request related to a problem?

I dislike the fact that the only way I can see Non-Urgent notifications is through either a summary that sends every six hours or by going directly to the app. While it's better than having no way of sifting through less important notifications, I thought there should be another way of seeing them at anytime in one place without having to wait for the summary.

### Describe the solution you'd like

When the feature is turned on (I'd imagine it would be toggled within the notification settings in Niagara settings), a user would be able to select which apps they want to utilize this feature if they haven't already selected apps for the Notification Summary. If they all chose apps for that feature, they would instead be asked if they want to use the same apps for this setting, or if they want to remove or add apps to it. From there, the notifications for those apps would not appear or make a sound (similarly to Notification Summary). Instead, they would silently appear in a place that can accessed by clicking on something called Non-Urgent Notifications which would be under the Niagara Launcher tab on the home screen. The notifications would be stored there for users to peruse through and delete at any time.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by mbartlett21** [comment]
Even if there was a place where we could go and look at a partial summary would be nice

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for your request.
Perhaps the [summary](https://niagaralauncher.app/app-link/secret-command?cmd=summary) secret command is helpful here. It allows you to trigger the summary at any time. Please let me know if I can help you further.

**Comment by mbartlett21** [comment]
It would still be nice to have a button instead of having to use a secret command to check nonurgent notifications. I don't see that this issue should be closed

**Comment by NiagaraSupport** [comment]
I'm sorry about that. Tickets with the awaiting response label get closed automatically after two weeks if there is no response. Regarding the issue, #2585 seems quite similar, so I'll leave this closed, but reference it over there. Thanks for your understanding!
