### ISSUE TITLE
Different Wallpapers for Different Layouts

### ISSUE THREAD

**Issue by DieSaemmel360** [8bitPit/Niagara-Issues#2579]
### Is your feature request related to a problem?

It's Kinda annoying to have to set either a horizontal or vertical Wallpaper and then have it be streched if you rotate your device(tablet for me).

### Describe the solution you'd like

So the idea I had was to maybe enable users to set different Wallpapers for the different rotations(as default it could just be that when you select a wallpaper it just automatically gets put for both rotations unless you change it manually). though i do not know how taxing this would be on the device/ what problems its implementation comes with.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for your request.
As far as I know, Android's native settings don't offer a built-in option to set different wallpapers for portrait and landscape modes. Unfortunately, manually changing wallpapers upon flipping the phone is currently the only option, and investing time in automating this process is not feasible at the moment. I'd recommend searching for specialized wallpapers, that work in both modes or using a third-party wallpaper app.
