### ISSUE TITLE
Feature request: opt for Another Widget for 

### ISSUE THREAD

**Issue by varxx** [8bitPit/Niagara-Issues#258]
I'd like to replace the standard clock on the home screen with the widget called "Another Widget". It had an excellent, low-key weather indicator. It's the main thing I miss by using Niagara instead of one of the other launchers that support widgets. Thanks.

**Comment by 8bitPit** [comment]
Niagara can already display the weather, you can enable it in the app's settings. Regarding widget support, please look at #117, and for Another widgets "At a glance feature" see: #55
