### ISSUE TITLE
Phone laid down when launcher open then turn off phone

### ISSUE THREAD

**Issue by Rexx-DZN** [8bitPit/Niagara-Issues#2583]
### Is your feature request related to a problem?

Instead of having to turn off your screen manually always or double tapping. There should be an added function that the phone locks itself or turns the screen off when it is laid down on a table and is on the launcher immediately. This is handy if u are in a rush and forgot ur phone on a table or some other scenario. It is more secure and automatic.

### Describe the solution you'd like

To keep things simple this should just be a feature of the launcher that u don't need to toggle. Otherwise make it a toggle it is up to you. Since the launcher is about keeping it simple and smart, this should be an option.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by justme30s** [comment]
Hm I think this is not up to the launcher though. It's more like the shortest time light goes off and screen locks . But I haven't seen any manufacturer have a instant lock when turning face down the phone . Just on pixels it triggers DND mode if you want when face down . But not locking the screen . Maybe with tasker or something of the sort .

**Comment by NiagaraSupport** [comment]
Thanks for your request.
As mentioned by justme30s, this is more on the hardware side of things. I would recommend requesting this feature directly with your phone's manufacturer.
