### ISSUE TITLE
Show apps of adjacent letters when swiping right on the launcher

### ISSUE THREAD

**Issue by annguyen1291** [8bitPit/Niagara-Issues#2584]
### Is your feature request related to a problem?

Currently, when the user swipes right on the launcher, it only shows the apps that start with the selected letter. This can result in a lot of empty space on the screen, especially if there are few or no apps for that letter. It also makes it harder for the user to find the app they are looking for, if they are not sure about the exact spelling or the first letter.

### Describe the solution you'd like

I suggest that the launcher should also show the apps of the adjacent letters, i.e., the letters before and after the selected one. For example, if the user swipes right on the letter B, they should see the apps that start with A, B, and C. This would make better use of the screen space, and also improve the navigation experience of the users, as many people are not proficient at alphabetical order. It would also allow the user to quickly switch between letters by swiping left or right, instead of having to go back to the main screen and select another letter.

This feature would align with the product vision of providing a simple and intuitive launcher for the users, and also address a common user need of finding and launching apps easily.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by CerberusCode** [comment]
I agree with you, this idea has come to me a long ago and forgot, its good that you post this and yeah this scroll alphabet needs a redesign.

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your suggestion.
However, our choice to display only one letter at a time comes from our design philosophy, aiming to provide a clean and uncluttered experience. If you'd like to view adjacent letters, I recommend tapping the alphabet or scrolling down the apps list itself. I appreciate your understanding.
