### ISSUE TITLE
[Notification summary] - allow user to choose when to receive the summary

### ISSUE THREAD

**Issue by wtfzambo** [8bitPit/Niagara-Issues#2585]
### Is your feature request related to a problem?

First of all I want to show my appreciation for Niagara and the dev team. It's such a cool product and tbh I could NOT imagine using my phone without it. You guys are great.

---

Regarding my "problem". I love the new "Notification Summary" feature that you included. I think it's very very useful, especially the fact that one can select which apps to filter.

What I find weird, is that I have no way to choose **when** to receive the summary:

- I use it mainly when I'm working, to avoid being distracted, but I can't tell it _"show me the notifications at 6PM"_.
- When I'm not working, I'd like to receive the notifications in real time, but if the summary is on, I have to wait for it, or disable it entirely until the day after.
- Also, depending on the last time one checks  the summary, the "wait for it" option might not even be possible, cause I have no way to specify when I'm gonna receive it next. Sometimes the summary comes at 2AM, I'm already sleeping by then 😅.

![image](https://github.com/8bitPit/Niagara-Issues/assets/47462792/2771200d-5fd6-4e57-9773-ea19811ad660)

### Describe the solution you'd like

I'd like a possibility to select if / when to receive the summary, so that I can tailor it around my day and needs.

This could be something like:
- An option to "schedule" the summary (e.g. enabled between 8AM and 6PM), but this probably doesn't fit your design principles.

- Much simpler, a quicker way to toggle it so that user doesn't have to go through 5 clicks to enable / disable it when needed.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Theoretically, the secret command could be set up as a shortcut on the home screen, providing quick access to the summary whenever needed. However, we are currently dealing with some bugs here, and the command doesn't execute as it should. This will be fixed in the future, hopefully making this viable as a workaround.

The summary feature wasn't initially intended for quick checks or frequent toggles, so it is unlikely that there will be much improvement in those aspects in the near future. But your desired use case may overlap with other feature requests, like #2540, for example.

**Comment by wtfzambo** [comment]
> the secret command could be set up as a shortcut on the home screen

That was my initial thought, but I could not do that because as soon as I visit that link, the command runs. If I try in another browser, somehow I never get the option "Add to Home screen".

Nevertheless, I am currently using the summary and getting used to it. I saw #2540 and it does indeed overlap quite a lot. I'll see what you guys will do in the future, probably you can close this I think. Thanks :)

**Comment by NiagaraSupport** [comment]
> If I try in another browser, somehow I never get the option "Add to Home screen."

This will hopefully get fixed soon. I'll try to remember to post an update here then. 
Thank you for your feedback and understanding. :)
