### ISSUE TITLE
App list doesn't show when unlocking after Android auto starts

### ISSUE THREAD

**Issue by ChanceM** [8bitPit/Niagara-Issues#2587]
### Describe the bug

App list is not visible when unlocking after connecting Android Auto. Swiping provides haptic feedback but the app list is not visible. Must lock and unlock again for it to function.

### Steps to reproduce

1. Connect USB to head unit.
2. Unlock phone
3. Swipe app list

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6 XL

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hi there, thanks for the report.
I'll try to reproduce the issue. Just for clarification, is the issue occurring on your phone or the car's display?

**Comment by ChanceM** [comment]
It happens on the phone screen. Leaving the phone connected to Android Auto, if I unlock the phone to look at another app the list does not show up unless I lock and unlock again.

**Comment by NiagaraSupport** [comment]
Hey again,
I'm sorry to say that I haven't been able to reproduce the issue. It functions as intended with the current version of Android Auto that Mercedes(A180) uses. Unfortunately, this suggests the problem may be related to specific hardware or third-party factors beyond our scope. I'm sorry for not being able to help you here.
