### ISSUE TITLE
typo in french

### ISSUE THREAD

**Issue by MRandl** [8bitPit/Niagara-Issues#2588]
### Describe the bug

The tutorial contains a typo in french (see attached)
It shows "montres moi", should be either "montre-moi" without an S (informal) or "montrez-moi" (formal). 
The hyphen is optional but is considered more elegant.

![signal-2024-02-05-213908_002](https://github.com/8bitPit/Niagara-Issues/assets/17947709/8572ef7d-d7be-4f9b-9531-2b1f14109989)

### Steps to reproduce

not applicable

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

pixel 7a

### Android version

Android 14

**Comment by MRandl** [comment]
Also the weather prompt is not the only place where this typo is made, but I'll report it only once of course.

**Comment by NiagaraSupport** [comment]
Hi there, and thanks for the report. 
I changed it to "montrez-moi" and it will update with newer versions. If you encounter any other translation mistakes, those are typically handled through [Crowdin](https://help.niagaralauncher.app/article/80-help-translate). Feel free to submit or help fix them there; we appreciate all contributions.
