### ISSUE TITLE
Return to favourites menu after launching an app from drawer 

### ISSUE THREAD

**Issue by edwardally** [8bitPit/Niagara-Issues#259]
It will be great if can be configured to always return to favourites menu each time call an app from drawer or after screen off.

**Comment by Montell2099** [comment]
I'd prefer this as well.

**Comment by 8bitPit** [comment]
See #21

**Comment by edwardally** [comment]
I think this is different. It use the home button to return to favourites menu using home button but I'm suggesting is it return to favourites menu after an app was triggered. Thanks

**Comment by 8bitPit** [comment]
@edwardally
`by last state I mean, if I open telegram and then press home, it goes back to the launcher pointing at apps starting with "T". An option to make it go back to "Favorites" would be nice as I mostly use that.`

I believe that's what he meant.
