### ISSUE TITLE
Swipe down on home screen doesn't always work

### ISSUE THREAD

**Issue by joelnfrancis** [8bitPit/Niagara-Issues#2590]
### Describe the bug

To open the notification shade, swiping down from the middle of the screen works flawlessly in almost all launchers. But doing this in niagra launcher is a hit or miss. 

### Steps to reproduce

1. Swipe down on home screen

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova launcher, minimalist launcher 

### Device name

Samsung S21 FE

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your report.
Gestures are usually part of the system behavior, and there shouldn't be any difference between 3rd Party Launchers (see [more](https://help.niagaralauncher.app/article/7-gesture-navigation#:~:text=Gesture%20animations%20are%20buggy/laggy)). Could you perhaps elaborate on what's hit or miss or provide a screen capture to help solve this issue.
