### ISSUE TITLE
Pixel 4a 4g:  Can't hide the gesture hint, please resolve it only in the home page(launcher). ( Android 13 )

### ISSUE THREAD

**Issue by PandiaJason** [8bitPit/Niagara-Issues#2591]
Niagara Pro User more than 1.5 years. Niagara is the greatest launcher than all other launchers. Thanks 
Annoying Gesture Hint 
![Screenshot_20240208-234220.png](https://github.com/8bitPit/Niagara-Issues/assets/100123063/cb69dbce-7ee2-408c-a842-e9eee322e770)

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request.
This is, unfortunately, not something we influence directly. It's more of an Android flavor /system-specific thing. Some phones apparently offer an option to hide the gesture suggestions (for Samsung, see [here](https://www.samsung.com/ph/support/mobile-devices/how-to-hide-the-navigation-bar-on-galaxy-devices/#:~:text=If%20you%20want%20to%20hide%20the%20gesture%20suggestions)), if that's not the case here, I'd recommend talking to their support.
