### ISSUE TITLE
Timer when opening app

### ISSUE THREAD

**Issue by jochuannes** [8bitPit/Niagara-Issues#2593]
### Is your feature request related to a problem?

Some anti-addiction features could be usefull

### Describe the solution you'd like

Minimalist phone has a feature I'd love to see on niagar, one can set a timer that will delay the opening of an app, as to minimize senseless phone usage.

![Screenshot_20240209-130844](https://github.com/8bitPit/Niagara-Issues/assets/64692298/1b0e34d4-bdc2-4a99-afd9-2a6e9b2459a4)
![Screenshot_20240209-130841](https://github.com/8bitPit/Niagara-Issues/assets/64692298/4cf090a8-4bdd-484b-b780-aca0fb9ae5de)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request.
Digital Well-Being is something we care about, and improvements will be made in the future. 
For now, perhaps our [Morning Mode](https://help.niagaralauncher.app/article/141-morning-mode) fits your use case.
