### ISSUE TITLE
Reopening the issue  #2591 

### ISSUE THREAD

**Issue by PandiaJason** [8bitPit/Niagara-Issues#2594]
I had seen Niagara Launcher loads in immersive mode while first time setup, and then continues with a gesture hint. So there might be chances for improvement.

I had seen some gesture hint third party disabler without root on pixel devices. 
https://play.google.com/store/apps/details?id=com.full.imm

The only reason I'm using my pixel 4a 4g is because of the Niagara Launcher.

Thanks

**Comment by NiagaraSupport** [comment]
We delved into immersive mode before, and unfortunately, it does come with some quirks – for example, needing two swipes for navigation and occasionally still showing the status bar. The fixes needed for these would require too much work to warrant consideration for now.
If third-party disablers don't address your concerns, regrettably, we won't be able to help as well. Appreciate your understanding.
