### ISSUE TITLE
Media Widget low resolution Pocket Casts 

### ISSUE THREAD

**Issue by b-aaron** [8bitPit/Niagara-Issues#2596]
### Describe the bug

The media widget is showing a low resolution cover image, when playing a podcast in Pocket Casts. The media notification itself is not low resolution.

### Steps to reproduce

1. Enable media widget on home screen
2. Play podcast in Pocket Casts
3. Notice media widget cover image of low resolution, unlike the media notification.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung Galaxy S20 FE

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_20240210_114246_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/72910336/993a477f-00df-4763-a56f-d2cb055fde7f)
![Screenshot_20240210_114233_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/72910336/cd85062a-0808-408d-8038-8c4a87cf32e4)
![Screenshot_20240210_114147_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/72910336/68d021be-ff62-4c6d-83e2-fda49fc800d1)
![Screenshot_20240210_114136_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/72910336/c44cb60f-1ea6-4130-89ac-b3cd3c43dcfb)

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your report.
Could you also provide some complete screen captures? We'll see what we can do.

**Comment by b-aaron** [comment]
> Hey there, thank you for your report.
> Could you also provide some complete screen captures? We'll see what we can do.
@NiagaraSupport 
Sure! Here they are. Btw, this is now Android 14 with OneUI 6.0

![Screenshot_20240228_162740_Niagara Launcher.jpg](https://github.com/8bitPit/Niagara-Issues/assets/72910336/40646760-78e6-4267-aea8-aa0269aca441)

![Screenshot_20240228_162746_Niagara Launcher.jpg](https://github.com/8bitPit/Niagara-Issues/assets/72910336/c36bef1f-ec56-4bf6-8287-6e62974ff5fb)

![Screenshot_20240228_162750_Niagara Launcher.jpg](https://github.com/8bitPit/Niagara-Issues/assets/72910336/453a861a-f877-462c-bcf0-0ebb1e6e31b4)

![Screenshot_20240228_162809_Niagara Launcher.jpg](https://github.com/8bitPit/Niagara-Issues/assets/72910336/fc64477e-3f0c-4c9e-8f0b-18bf6b8013d7)

![Screenshot_20240228_162814_Niagara Launcher.jpg](https://github.com/8bitPit/Niagara-Issues/assets/72910336/3b967a89-2d1c-4e85-892a-0426169ecd73)

![Screenshot_20240228_162819_Niagara Launcher.jpg](https://github.com/8bitPit/Niagara-Issues/assets/72910336/112889aa-81ea-414d-badc-6739ef222046)

**Comment by NiagaraSupport** [comment]
Thanks, we'll take a look at it.

**Comment by b-aaron** [comment]
I'm not sure, whether this Issue was coming from Niagara Launcher or Pocket Casts itself, but it seems to be fixed now. Closing.
