### ISSUE TITLE
Swipe up or left to scroll all apps

### ISSUE THREAD

**Issue by ThePianoMan2255** [8bitPit/Niagara-Issues#2598]
### Is your feature request related to a problem?

I apologize if this has already been requested and rejected. 

One feature I feel is some what lacking is the ability to scroll past the favorite apps to all apps instead of using the alphabet to get to all apps. It feels less natural to me to always hit the alphabet when I just want to scroll past and then look through my apps for notifications.

I know I know, use the notification drop down, but honestly I like how it's presented in the launcher. 

### Describe the solution you'd like

The ability to swipe up from the bottom, to the right or left to open up all apps without clicking the alphabet. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, and thank you for the suggestion.
Unfortunately, the idea doesn't have enough impact or reach to warrant implementation at this time, given that access to the all apps list is already possible with a single tap or swipe. Nonetheless, we do appreciate your understanding and value the input.
