### ISSUE TITLE
Material You icon packs not following dark/light themes

### ISSUE THREAD

**Issue by Donnnno** [8bitPit/Niagara-Issues#2599]
### Describe the bug

Hi, this is an issue bothering me for a while now (as an icon pack dev), especially since Niagara is my favorite launcher to use for a while now. 

I've noticed that Niagara fails to switch icon packs with different color configurations that are dependent on the system's dark and light themes. 

We've tested many launchers, some of the biggest competitors, like Nova, Smart, or Hyperion do handle this correctly, you can view the test results over here: https://github.com/Arcticons-Team/Arcticons/issues/1874

The test is based on four icon packs:
- Arcticons Material You
- Arcticons Day & Night
- Pix Material You Light/Dark
- Lawnicons

I know your priorities at this moment when it comes to icons is to Anycons, but don't forget to give some love to the other icon packs too :) 

Thanks!

### Steps to reproduce

1. Use one Material You icon pack.
2. Switch between dark & light mode.
3. (nothing happens)

### Does the issue also occur with other 3rd-party launchers?

Problem does occur with some launchers*

### Other 3rd-party launcher(s) tested

See list above

### Device name

Samsung Galaxy Ultra 22

### Android version

Android 14

### Screenshots / Screen recordings

1. Niagara

https://github.com/8bitPit/Niagara-Issues/assets/31142286/5f2d849e-a18b-4a0c-94a8-43037af50a2f

2. Hyperion

https://github.com/8bitPit/Niagara-Issues/assets/31142286/4b93b51e-1161-4a2d-b288-1f97b440be8a

**Comment by NiagaraSupport** [comment]
Thank you for the report.

Currently, we need to manually incorporate icon packs that utilize light and dark mode theming. You can find the current list of supported packs [here](https://help.niagaralauncher.app/article/150-list-of-android-material-you-icon-packs). If you have more that should be added, please mention it [here](https://github.com/8bitPit/Niagara-Issues/issues/2316#:~:text=I%27m%20closing%20this%20ticket%20since%20there%27s%20nothing%20we%20need%20to%20implement%2C%20but%20please%20still%20feel%20free%20to%20notify%20us%20about%20new%20Material%20packs%20and%20we%27ll%20include%20them%20in%20our%20help%20article%20and%20add%20auto%2Dtheming%20support%20for%20them.).
The ones you mentioned have already been included and should work fine within the following patches.

Best regards,

Team Niagara

**Comment by Donnnno** [comment]
Hi, thanks for the reply! 
Good to know that it's a manual approach. And hopefully newer versions fix the theme switching. :)
