### ISSUE TITLE
Show whole app list when scrolling

### ISSUE THREAD

**Issue by Maxr1998** [8bitPit/Niagara-Issues#26]

**Comment by 8bitPit** [comment]
I'll experiment with that

**Comment by jakcharvat** [comment]
What exactly does this mean? Categories like 'communication', 'games', 'entertainment'; or all letters; or folders?

**Comment by OfficialKris** [comment]
If you would do this. I think it would be better to have it granular to app level not letter level. Like iOS scrolling. Or a setting to toggle in between the modes. Other than this I love this launcher. :P

**Comment by 8bitPit** [comment]
@OfficialKris do you mean a plain scrollbar?

**Comment by Maxr1998** [comment]
@8bitPit this looks nice!

**Comment by JeremieVenditti** [comment]
@8bitPit that would be awesome!

**Comment by disacrol** [comment]
Yes, it's awesome, I would love that too.

**Comment by Bullnados** [comment]
Will the choosen app opened immediatelly? Oft course only optional

**Comment by ShadowXOR** [comment]
This would be great.

**Comment by Montell2099** [comment]
Would be very exciting seeing this proposition in effect, I'm glad to see the positive response on the mock-up screenshot I posted a couple months ago.

Thanks again for your development of this great launcher that just keeps on giving. The recent padding adjustment feature is superb!

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
