### ISSUE TITLE
App name changes don't stick. Revert to the original name after undetermined amount of time. 

### ISSUE THREAD

**Issue by dlee098** [8bitPit/Niagara-Issues#2602]
### Describe the bug

Issue started about a month ago. When I change the name of an app, it reverts back to the original name after some time. In this case I am changing a Korean app name to it's equivalent in English so that when I search I do not need to change the input language. But it keeps changing back. 

### Steps to reproduce

1. Rename app from Korean to English name.
2. After some time the name changes back to Korean. 

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Galaxy Fold 5

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hi there, thanks for the report.
Interesting behavior. Have you tested if this occurs on other 3rd party launchers? If so, which ones? And do names also revert if you rename them in Korean? Might be the system itself is overwriting the names.
