### ISSUE TITLE
Pro License not recognized automatically

### ISSUE THREAD

**Issue by ValPB** [8bitPit/Niagara-Issues#2606]
### Is your feature request related to a problem?

I am using a "stateless" Android device, that means it has no battery and syncs everything on startup. That means: during startup there is no internet connection and time is set wrong.

So every time i start this device (every few days) Niagara will be started and complains about the missing license. So every time i have to fix this license problem manually.

That means it shows:

"There's a problem with your Niagara Pro membership"

I have to click on this, and if the time is already set correctly and the internet connection is running, then it recognizes, yes i have a license and everything is wonderfull.

### Describe the solution you'd like

It would be supercool if Niagara could check after 5 seconds again, if it could get his license. (Or if it simply could remember the license status of the last run at startup and check for its license 1 minute after startup...)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your report.
In theory, you should be good without a license check for 30 days. If the date and time are way off, it might cause some issues. We'll look into it and see what we can do.

**Comment by ValPB** [comment]
Hi - i just wanted to ask: Any news/updates on this issue?

**Comment by Maxr1998** [comment]
This is most indeed caused by the incorrect date. We could possibly introduce a workaround for this, but it isn't a high priority for us right now. What I wanted to know still — what's the date/time you usually see when starting the device? Is it the date that the device was last powered on, or something way in the past?

**Comment by ValPB** [comment]
Hi - thank you for again for the prompt answer.

I just tried it, and the date/time was something way in the past: 6th of April 2023 (i guess the last update of the system).

But wonderful - i am looking forward to the next update and report if it works!

**Comment by ValPB** [comment]
Hi again,

sorry for the late answer, but I wanted to have a controlled update.

And yes - i have now updated (manually/under control) and yippie!!! Yes! It works now!

So it still complains after startup, but when the internet connection is ready, the "membership problem message" goes away.

Thank you for fixing this!!

**Comment by Maxr1998** [comment]
Happy to hear our solution works for you!
