### ISSUE TITLE
App Closing Animation

### ISSUE THREAD

**Issue by manishag733** [8bitPit/Niagara-Issues#2607]
### Describe the bug

I'm using a Samsung device and when I was on Android 13, the app closing animation for any app used to work properly just like it does on the native launcher when using the swipe gestures. Meaning that when I close an app, the icon of the app moves up from the bottom and then bounces into it's place on the home screen/app list.

But after the Android 14 update, the app just closes abruptly and it looks very rough. I do not know if this occurs on other skins as well or just OneUI.

### Steps to reproduce

1. Make sure gesture navigation is turned on.
2. You must be on Android 14 (OneUI 6.0)
3. Open any app from the homescreen/app list.
4. Close the app by swiping up from the navigation bar area.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung Galaxy A52 4G

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/95606361/c4d27511-7e90-47bb-a49c-edecee1ce0e2

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your report.
This seems similar to #2417, so I'll close this as a duplicate.
