### ISSUE TITLE
spacer widget to split the clock and favourite items

### ISSUE THREAD

**Issue by creativename123** [8bitPit/Niagara-Issues#2608]
I would like to have to option to add a spacer widget so I can space out the two sides above and below the widget. 
See screenshot for example. A transparent widget that doesn't do anything but fill up space would be nice.

![Screenshot_2024-02-28-01-09-12-49_a4824db61f40c53807964ea8b14c92fe](https://github.com/8bitPit/Niagara-Issues/assets/16190107/819359cd-6d96-4326-bc3b-0a68fb2396a9)

### Describe the solution you'd like

A certified Niagara Launcher Widget™ that is entirely transparent. Which allows me to resize the widget using existing NL functionality and add empty space between the clock and fav shortcuts. The goal being to not have the clock, fav items, or other homescreen items blend in with the background. Goal can be achieved by allowing users to add a "spacer" widget which doesn't block the wallpaper (since its transparent, unlike the FF widget used in the example)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request,
Not all widgets automatically fill the space they are given, so you could already achieve this by using the 'Move and resize' option the widget provides(see screen). There are also some empty/invisible widgets available on the Play Store if you want absolutely nothing in that space. Let me know if I can provide any further help.
<img width="284" alt="Screenshot 2024-02-28 at 11 44 47" src="https://github.com/8bitPit/Niagara-Issues/assets/151941204/007432d3-4b55-442f-af2e-e155ac1cc3cb">

**Comment by creativename123** [comment]
I prefer to have nothing in that space, like you said an invisible widget. Are you familiar with which apps contain invisible widgets in the playstore? I can't seem to find one specifically for that.
