### ISSUE TITLE
Pixel-gap in the media play button

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#261]
https://i.imgur.com/w6ihtQj.jpg

I am experiencing this tiny UI bug with SoundCloud, 
Spotify, YouTube & BlackPlayer.

**Comment by 8bitPit** [comment]
The media player design has been updated and this bug has been fixed.

**Comment by 8bitPit** [comment]
Fixed in v.0.9.0: https://github.com/8bitPit/Niagara-Issues/releases/tag/v0.9.0-beta
