### ISSUE TITLE
[Notification summary] Allow notifications to be swiped away "in batch"

### ISSUE THREAD

**Issue by wtfzambo** [8bitPit/Niagara-Issues#2610]
### Is your feature request related to a problem?

So I started using the notification summary about a week ago; getting used to it is admittedly strange but I like it.

But if one receives a lot of notifications, it's a bit of a hassle to swipe them all away one by one. Closing the summary doesn't clear them, because they show up in the next one.

### Describe the solution you'd like

I'd like the possibility to clear notifications in batches by swiping them away by App, rather than doing it 1 by 1.

Also, I believe if I click a notification on the (not just enlarging it, but going to the source), the notification should be cleared from the summary. Right now it stays there until it's swiped away.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the request.
Closing the Summary should theoretically clear the remaining notifications. If that's not the case for you, another issue might be at play here. If so, could you tell me what app the notifications are send from, so we can try to reproduce the issue.

**Comment by wtfzambo** [comment]
> Closing the Summary should theoretically clear the remaining notifications. 

Ah, I see. Currently the notifications I capture with the summary are from:
- Whatsapp
- Reddit
- Linkedin
- Headway
- Amazon Shopping

However, I am using a notification manager app ([this one](https://play.google.com/store/apps/details?id=com.samruston.buzzkill&hl=en&gl=US)) that was intended to send me google calendar notifications also when phone is completely on mute. Could it be that one that's creating issues?

**Comment by wtfzambo** [comment]
Small update:

I uninstalled "Buzz Kill", the notification manager, but it seems that closing the summary doesn't clear the notifications still.
