### ISSUE TITLE
toggl time tracking integration

### ISSUE THREAD

**Issue by jdlewin** [8bitPit/Niagara-Issues#2611]
### Describe the solution you'd like

i'd love to see some launcher support for Toggl, the time tracking tool. something similar to the way mail and messaging data gets pulled out and displayed.

at present their first party widget really clashes with the vibe 
![android_screenshot](https://github.com/8bitPit/Niagara-Issues/assets/19195907/2594eeb8-ddb6-48ea-bd28-e7ed712ae08c)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your suggestion. 
At the moment, our policy towards integrating third-party apps hinges on significant demand or changes offering a clear, impactful benefit, which I'd argue is currently not the case. However, I'll collect similar feedback and write it down for future consideration. 
If your main gripe is with the widget's look, I'd recommend using a widget stack and swapping to another widget or empty widget in the meantime.

**Comment by jdlewin** [comment]
I understand. It’s not a hugely popular use case. Appreciate your closing the loop.

🤙🏻🌴🌺
________________________________
