### ISSUE TITLE
Icons not showing when open app popus

### ISSUE THREAD

**Issue by bjorne900** [8bitPit/Niagara-Issues#2612]
### Describe the bug

When I have applied a big icon pack like Borealis there is often a delay (a few seconds) before certain icons show up when I open an app popup.

### Steps to reproduce

Swipe right on an app to open app popup.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova launcher

### Device name

Galaxy A71

### Android version

Android 13

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
Since #2486 is similar, I'll go ahead and close this one but reference it there.
