### ISSUE TITLE
Add more widgets to the vertical scroll rather than stacks

### ISSUE THREAD

**Issue by Fill49** [8bitPit/Niagara-Issues#2613]
### Is your feature request related to a problem?

Stacks have a 4 widget max and are essentially hidden until you scroll, requiring additional swipes. Also, the pop up folder feature is nice, but again requires additional swiping and remembering if there is a pop up widget already set up.

### Describe the solution you'd like

Please add the ability to add additional custom widgets vertically as a power user feature. It would be more efficient as a power user to use the already best feature of the launcher, which is the vertical scroll on the homepage, but with widgets. No need for additional steps as the set up Icons are already there. Just allow for custom widgets to be added below the existing widgets as is done with the app icons. With the development of better widgets, they will functionally replace app icons so why not allow for the same utility.
Thanks.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thank you for your suggestion.
This request is going in the direction of a widget page. Unfortunately, as mentioned [here](https://github.com/8bitPit/Niagara-Issues/issues/117#:~:text=Feb%2015%2C%202019-,I%20am%20not%20really%20a%20fan%20of%20widget%20pages.,-The%20only%20thing), this is not something we plan to explore in the near future. We appreciate your understanding on this matter.
