### ISSUE TITLE
Wallpaper zoom in 

### ISSUE THREAD

**Issue by Dhanseelan-S** [8bitPit/Niagara-Issues#2616]
### Describe the bug

A bug in MIUI where the wallpaper we set zooms in considerably irrespective of the app we use to set the wallpaper (both built in and 3rd party apps), this bug is passed to niagra launcher as well,  so requesting the niagara team to develop a seperate inbuilt wallpaper app to seperate themselves from other OS issues

### Steps to reproduce

1.Go to niagara settings
2.Click on look
3.Click on wallpapers
4.Choose any wallpaper
5.Apply the wallpaper (lock/home or both screen)
6.We can notice the wallpaper zoom in.

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Redmi Note 10 Pro

### Android version

Android 13

### Screenshots / Screen recordings

![Screenshot_2024-03-05-22-19-34-040_bitpit launcher](https://github.com/8bitPit/Niagara-Issues/assets/162351802/acd7a6ed-48cf-47b1-a15c-9aa2486b4286)
![Screenshot_2024-03-05-22-20-06-712_bitpit launcher](https://github.com/8bitPit/Niagara-Issues/assets/162351802/15274cce-4bc7-4038-8861-10e44b32fa79)

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your suggestion.
Developing a separate inbuilt wallpaper app seems a bit overkill here. I'd suggest checking [this](https://help.niagaralauncher.app/article/36-wallpaper-bugs) out first. Perhaps some of the points there prove helpful.
