### ISSUE TITLE
Add a way instantly visually find an app in folders

### ISSUE THREAD

**Issue by Clement-E** [8bitPit/Niagara-Issues#2619]
### Is your feature request related to a problem?

First of all I like you app, thanks for your job.
I appreciate and understand the balance you do between adding features and keeping design 'pure'.

As a user, I like Niagara for it's clean design. That's the main reason I use it. 
But :) I suffer a bit the lack of visual indication in custom folders and I have hard time to find instantly an app in folder... 

### Describe the solution you'd like

May I suggest to add possibility to associate a color to an app corresponding to a very discreet tag in UI?

Something like this (wireframe done in 2minutes on my phone and there is no doubt that there would be a more clever solution, but idea is here. )

Thanks for your job anyway

![Screenshot_20240309-164427](https://github.com/8bitPit/Niagara-Issues/assets/45621549/af59141d-8a81-48e9-86d2-6455d3eeccac)
![Screenshot_20240309-162430](https://github.com/8bitPit/Niagara-Issues/assets/45621549/313ba64b-0020-4fbf-b8b5-05a92fb11211)

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, and thank you very much for the suggestion.

The material icon pack you've selected unfortunately always uses a singular color for the icons. However, other icon packs like Watercolor and Sticker also offer the original app colors as a choice. Switching to one of those might already solve your issue. If not, feel free to let me know.
Additionally, it's worth noting that you can manually change individual app icons to use different packs. So, even if you prefer the material icon pack for the home screen, you could set up others for apps in the pop-up folder.

**Comment by Clement-E** [comment]
Hey, thanks for answering.
that's definitely more readable with other icon packs
![Screenshot_20240316-214319](https://github.com/8bitPit/Niagara-Issues/assets/45621549/e5fa7835-6e23-44a7-b573-d03e3849bde9)

But it forces me to use a heavy icon pack. 
I find it less flexible in term of 'sorting' stuff. 

Again, i didn't do any Figma work in order to find a clever clean/simple solution (for the setting part especially) so that's easy for me to suggest but maybe you could consider it worth the pain :)

**Comment by NiagaraSupport** [comment]
Sorry for the late response.
I understand your point here, but unfortunately, the suggested change doesn't fit our design philosophy and needs more impact before we consider implementation. For now, you'll need to choose between existing Anycon packs and third-party options. Thanks for your understanding.
