### ISSUE TITLE
non scrolling time & date

### ISSUE THREAD

**Issue by lepa22** [8bitPit/Niagara-Issues#262]
I'm suggesting that the clock/music widgets are kept in place, while apps are scrolled behind them.

**Comment by lepa22** [comment]
I mean that, in the current implementation, when you scroll up in the homescreen, the clock also moves up. What I'm suggesting is that the clock is immovable and the apps in the homescreen get behind it when scrolling up.

**Comment by 8bitPit** [comment]
That would take away precious space though, especially on small devices.

**Comment by lepa22** [comment]
I agree. You could add it as an option, if you find it useful, though.

**Comment by 8bitPit** [comment]
Closing because of similar reasons mentioned in #808
