### ISSUE TITLE
Slide down (open notificaties) vibrates even when haptics are off

### ISSUE THREAD

**Issue by jcassee** [8bitPit/Niagara-Issues#2623]
### Describe the bug

When I disable haptic feedback, the slide down gesture that opens the notification panel still gives a short vibration.

### Steps to reproduce

1. Disable haptic feedback in Niagara
2. Go to the home screen and slide down

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6 Pro

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
We'll look at it. If you prefer not to use haptics for now, disabling them in the system setting should work, at least.

**Comment by jcassee** [comment]
Thanks! (I do like haptics in other places... :slightly_smiling_face:)

**Comment by NiagaraSupport** [comment]
I'm sorry, but we're unable to disable the feedback in this case. It seems that the swipe-down gesture operates at a system level. While we can utilize the system's haptic feedback for our own actions, we can't override the system behavior itself. If you have any other questions or concerns, please let me know.

**Comment by jcassee** [comment]
Alas, makes sense. Thank you for the investigation.
