### ISSUE TITLE
Adjustable scroll bar/alphabet size/font size & position

### ISSUE THREAD

**Issue by ttlog** [8bitPit/Niagara-Issues#263]
Since smartphones these days are huge for our hands, could you make the alphabet bar start from the middle of the screen and not go all the way to the bottom? This could help tremendously with screen sizes over 5.5inches. Thanks

**Comment by stuartglossop** [comment]
Or give a choice for different sized phone's?

**Comment by Scorpionk1** [comment]
Self-adjusting cut / the alphabet would line up within the "cut" of your preference.

**Comment by ttlog** [comment]
I think it would be better if you could choose the active area that activates the rolling alphabet. Different phones have different bezels so you can't say that a 5.5inch screen is the same in every form factor

**Comment by 8bitPit** [comment]
I already calculate it's position based on your phone's size, eg here is mine:
(@ttlog Yeah, you're right especially Samsung phones still have physical buttons and therefore have larger bezels)
![image](https://user-images.githubusercontent.com/9284845/45922455-bab79780-becc-11e8-8a82-fd004c8cd792.png)

**Comment by homer1993** [comment]
I would like to add something to this topic, namely the investigation of the launcher for left-handers. It would be very useful for left-handers if there was the possibility to put the alphabet list on the left side so that the one-hand operation is more intuitive.

**Comment by 8bitPit** [comment]
@homer1993, that might be implemented: #12

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
