### ISSUE TITLE
Allow Different Media to pop up depending on which device is connected

### ISSUE THREAD

**Issue by magicalvulture** [8bitPit/Niagara-Issues#2632]
### Is your feature request related to a problem?

I have a long list of media apps, between all the music apps and all the different TV apps that exist these days. I don't want to scroll through every one every time I connect to bluetooth. For example, when my phone connects to my car bluetooth I want to see Spotify, youtube music, and my podcast app. But, when I connect the bluetooth headphones I keep on my nightstand, I want to see youtube, Disney+, and Hulu. 

### Describe the solution you'd like

Add a toggle in settings to enable the ability to choose which category of apps appears for each bluetooth device that connects to the phone, instead of just Music for all bluetooth devices. So I could have my music apps for one device, and my TV apps for a different device. Or if I connected my bluetooth game controller to the phone it would show the apps in my Gaming category. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, and thanks for the request.
Unfortunately, due to the complexity and estimated limited impact/ reach, we currently do not have plans to implement this feature. However, if we receive more feedback and requests on this topic in the future, we might reevaluate. We appreciate your understanding.
