### ISSUE TITLE
Add a left-aligned text, no-icon mode.

### ISSUE THREAD

**Issue by dessalines** [8bitPit/Niagara-Issues#2633]
### Is your feature request related to a problem?

Many simple launchers such as Olauncher, don't use any icons, as it creates a less-distracting homescreen.

Currently, I'm using the blank icon pack to simulate a **no-icon mode** for niagara launcher, but it doesn't look great since the text is not left aligned:

![Screenshot_2024-03-22-15-23-22-04_a4824db61f40c53807964ea8b14c92fe](https://github.com/8bitPit/Niagara-Issues/assets/930215/6b54e56d-15e8-43b7-bb37-4e26e04055fa)

Compare with Olauncher:

![unnamed](https://github.com/8bitPit/Niagara-Issues/assets/930215/02a5db40-76c7-4d97-a082-37526d79fe23)

### Describe the solution you'd like

It'd be great to have a no-icon mode added to niagara launcher.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request.
Unfortunately, it's unlikely that we will implement complete left alignment for icons. Even if we add a toggle to disable icons, left-handed users need to be able to use the left side of the screen to navigate the alphabet and all app lists. Have you considered trying the Outlined icon pack? It could be a great alternative.
<img width="286" alt="Screenshot 2024-04-11 at 14 30 06" src="https://github.com/8bitPit/Niagara-Issues/assets/151941204/2f529969-b5b4-4b1e-aa94-0dc7c34e39f6">
<img width="286" alt="Screenshot 2024-04-11 at 14 30 25" src="https://github.com/8bitPit/Niagara-Issues/assets/151941204/09368456-bb8f-43bb-b7de-6f2f1c58ce1b">

**Comment by dessalines** [comment]
The left-handed hidden alphabet list is still to the left of your icons anyway (in the margins), so removing the icons and shifting the title left (but not past the margins), shouldn't cause any conflicts.

**Comment by NiagaraSupport** [comment]
Yes, I just mentioned that, because it wouldn't be as much to the left as in the Olauncher screenshot. To the actual request, there are no [current plans](https://help.niagaralauncher.app/article/151-hide-app-icons) to remove icons as a whole. If there are more requests in the future It may get reconsidered, but for now I'll close this. Appreciate the understanding
