### ISSUE TITLE
Disable alphabet selector

### ISSUE THREAD

**Issue by mara-vodvarka** [8bitPit/Niagara-Issues#2634]
### Is your feature request related to a problem?

Hi,

I'm trying to find a launcher for my grandma - something as simple as possible, with access to only very few apps that she needs and with notifications hanging around the home screen, like she's used to from her old button phone. 

### Describe the solution you'd like

If we could disable the alphabet selector and have only featured apps, notifications and clock, possibly a widget to toggle sound and disable top bar swipe down it would be awesome!

Thank you

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request.
Implementing something like this doesn't align with Niagara's core design, where the alphabet plays a significant role. I recommend looking for specialized accessibility launchers on the Play Store designed with this use case in mind. They might offer precisely what you're looking for already.
