### ISSUE TITLE
More weather data available?

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#264]
Is the launcher able to pull more weather data than just temperature & forecast-icon from the weather provider?

For example being able to toggle on wind speed/precipitation risk in the "at a glance-weather widget" as well?

**Comment by Rod911** [comment]
#250

**Comment by 8bitPit** [comment]
Currently I am getting data from Google's Awareness API, it does only provide temperature & humidity, hence I cannot show more info as of right now, sry.
