### ISSUE TITLE
Show next alarm in clock widget

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2640]
### Is your feature request related to a problem?

Hello
Add an icon or text to notify next alarm in clock widget

### Describe the solution you'd like

Hello
Add an icon or text to notify next alarm in clock widget

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request.
I'll close this as duplicate of #4 , #1789 , #1704
