### ISSUE TITLE
Google Calendar: Birthdays not shown in the calendar widget

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2641]
### Describe the bug

Hello,
Google birthday Calendar don't show events in calendar widget

### Steps to reproduce

See your calendar widget if your an birthday event

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Google pixel 7

### Android version

Android 14

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
We have an article dealing with this [here](https://help.niagaralauncher.app/article/76-calendar-faq#:~:text=How%20can%20I%20show%20my%20contacts%27%20birthdays%3F). If this doesn't help, feel free to reach out again. Also, manually creating recurring events could serve as a workaround for now.

**Comment by spottech** [comment]
Hello,
I notice that it's only the new contacts that don't show up. I don't know if there's a refresh time for the widget???

**Comment by NiagaraSupport** [comment]
Unfortunately, there isn't a manual refresh option available. However, if troubleshooting helped with initial issues, repeating the process periodically may also help with newer contacts. Apologies for any inconvenience; we don't have the contacts' permission to smooth things out ourselves.
