### ISSUE TITLE
Pop-Up folder / Notifications full screen or imersive

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2646]
### Is your feature request related to a problem?

Hi,
For better visibility, can you provide a full screen mode or imersive mode for pop up folder and notifications.
Thanks 😊

### Describe the solution you'd like

Hi,
For better visibility, can you provide a full screen mode or imersive mode for pop up folder and notifications.
Thanks 😊

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Thanks for the suggestion. We have no plans to implement this feature currently as its impact and reach are considered too limited. Things might change in the future, but for now, I will close this ticket. I appreciate your understanding.

**Comment by BlasterOverlord** [comment]
Please add this! Fullscreen folders would be great.
Widgets in pop up folders don't look good because they are forced into a smaller proportion making the widget look ugly, please consider fullscreen folders. Plus I believe with sleek animations, fullscreen folders would be more preferred.
