### ISSUE TITLE
Remove sesame integration 

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2648]
### Is your feature request related to a problem?

Hello,
Sesame is to end  of support and buggy, can you integrated directly an basic web search with the search app of Niagara.
Like Smart Launcher or Nova. 
It's the big option missing in Niagara....
Thanks 😊

### Describe the solution you'd like

Hello,
Sesame is to end  of support and buggy, can you integrated directly an basic web search with the search app of Niagara.
Like Smart Launcher or Nova. 
It's the big option missing in Niagara....
Thanks 😊

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by 8bitPit** [comment]
Thank you very much for your feedback, @spottech. Agreed, Sesame is no longer working smoothly, and we plan to discontinue the integration. We're already working on providing web results without the integration. You can try our work-in-progress web results feature by running the secret command [/web-search](https://niagaralauncher.app/app-link/secret-command?cmd=web-search) (tap it to run it; if that's not working, please read this guide). I hope that helps!

**Comment by spottech** [comment]
Hello, 
I'm testing actually, he is work well for the moment with Duckduckgo provider 👍👍👍👍

**Comment by spottech** [comment]
Hi,
I'm heavy testing new search features, 
It's possible to add contacts and files too?

**Comment by 8bitPit** [comment]
Thanks for testing @spottech. We don't plan to add file search to Niagara Launcher but we're hoping we can release a beta version of our integrated contact search soon.

**Comment by spottech** [comment]
@8bitPit good news 😁😊

**Comment by TFackler** [comment]
Contact search has been added with v1.12.0.

**Comment by Plazzmex** [comment]
I see that as of June I can no longer enable the sesame integration? I know that most search functions are now integrated into Niagara search, but there are a few that I miss, like percentage calculation and conversion calculation (lbs to kg for example)

**Comment by 8bitPit** [comment]
Hi @Plazzmex, you can still enable the Sesame integration,  we just moved its settings to _Features_ > _Search_. Moreover, the settings might only be shown if you have already installed Sesame.
