### ISSUE TITLE
New Feature Cursor alphabets can edited

### ISSUE THREAD

**Issue by kevin240407** [8bitPit/Niagara-Issues#2651]
### Is your feature request related to a problem?

I hope the right side feature with the alphabet is updated and can be edited, the alphabet feature is a little boring for those who already use Niagara Launcher 😄

The right cursor is too same, make interesting and unique differences, so it doesn't look boring.

Please update again, don't forget to fix the bugs

### Describe the solution you'd like

Additionally, letters feature added to search for wallpapers and icon packs, thank you

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the feedback.
We're generally cautious with visual customization requests, as it can be challenging to introduce impactful yet universally appealing changes. If you could elaborate on what or how exactly you'd like things to change, it might help with evaluation.
