### ISSUE TITLE
More polices for Niagara clock widget

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2652]
### Describe the solution you'd like

Hello, 
It's possible to add more polices for Niagara clock? 
Polices can match to the most popular polices of lock screen Android smartphone customisation. 
Like basic police of Google, Samsung and ???? 
Thanks

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Thank you for your request.
If you're referring to the clock fonts, we can add more, but we are limited to those we have or can get licenses for. We also try not to overload the dialog with options, though expanding them in the future is a possibility.

You can also [set up a custom font yourself](https://help.niagaralauncher.app/article/79-custom-fonts#:~:text=How%20to%20use%20custom%20fonts). The first option in the clock style dialog represents your current text font and will apply to the clock too. Additionally, you might consider using [3rd party clock widgets](https://help.niagaralauncher.app/article/23-custom-clock#:~:text=potential%20calendar%20events.-,Fully%20custom%20clocks,-If%20you%20want) for more variety.
Let me know if I can provide any further help.

**Comment by spottech** [comment]
Hello,
Thanks. 
I test and see it 😉
