### ISSUE TITLE
Google app minimizes to Niagara button when button is disabled

### ISSUE THREAD

**Issue by sAleksovski** [8bitPit/Niagara-Issues#2656]
### Describe the bug

Google app minimizes to Niagara button even when the button is disabled, and enables the button temporarily.
The button sometimes shows a white circle, sometimes does not show anything, but can be pressed and blocks the widget behind it.

### Steps to reproduce

1. Disable Niagara button 
2. Open Google app
3. Minimize app
4. See app minimized to Niagara button
5. Press the Niagara button
6. Google app is opened

Expected: App is not minimized to the Niagara button since it is disabled

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Samsung S20 FE

### Android version

Android 13

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/7473800/6df2f12e-fdc3-44c8-8034-c964a6334137

**Comment by 8bitPit** [comment]
Thanks for the detailed report, along with the video, @sAleksovski! We'll fix the bug until our next release. In the meantime, you can remove the faulty animation by enabling the Niagara button (Niagara settings > Features > Niagara button), changing the tap action from Google to another app (long press the Niagara button > Edit tap action and select any other action) and optionally disabling the Niagara button again.

**Comment by sAleksovski** [comment]
Thanks for the workaround. I just tried it and it fixes my issue.

**Comment by 8bitPit** [comment]
Fixed in v.1.11.6.
