### ISSUE TITLE
"Round icons" option does not work

### ISSUE THREAD

**Issue by lukwoj1** [8bitPit/Niagara-Issues#266]
Hello,

I noticed that icons are not round after selecting "Round Icons" in the settings.

Phone: Nexus 6P
Android 8.1.0

**Comment by OverRidingSky** [comment]
Not at all, or not for some apps. Using the feat. myself it looks like some of them get a round icon from a nother resource instead of creating one. I have no actual solution, but I'd be interested in find out how they are collected.

**Comment by 8bitPit** [comment]
@lukwoj1 & @OverRidingSky they are provided by the apps themselves (I am not supporting adaptivce icons yet which works differently)

**Comment by 8bitPit** [comment]
Adaptive icon support is planned though: https://github.com/8bitPit/Niagara-Issues/issues/448
