### ISSUE TITLE
Add more colourful clocks widgets 

### ISSUE THREAD

**Issue by a2l0i7m0** [8bitPit/Niagara-Issues#2662]
### Is your feature request related to a problem?

Add an option to change the color of the Niagara clock style

### Describe the solution you'd like

Add an option to change the color of the Niagara clock style

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Closing, since it's a duplicate of #2519

If you have an opinion to share, please head over there.
