### ISSUE TITLE
Allow folders to be placed at top of app list/moved

### ISSUE THREAD

**Issue by bornasalman** [8bitPit/Niagara-Issues#2665]
### Is your feature request related to a problem?

Folders at bottom of app list seems counterintuitive, they should be quick access groups of apps. Folders are massively inferior to app pop-ups.

### Describe the solution you'd like

Allow folders to be integrated into the app list or moved to the top. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
I'm sorry to say there are no plans to implement that change. It is a matter of preference and hard to get right for everybody. If you start your swipe motion from the bottom down they'll be right there at the start, for quick access.
