### ISSUE TITLE
Larger home screen pop-up notification trigger

### ISSUE THREAD

**Issue by bornasalman** [8bitPit/Niagara-Issues#2666]
### Is your feature request related to a problem?

Home screen notifications could be leveraged better for streamlined simplicity. And saves several clicks.

### Describe the solution you'd like

Allow the entire notification region to open notification pop-up and only the app icon to open the app.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
Answering some older tickets right now. You can swipe right on notifications for easier access to the notification pop-up. Perhaps this helps.

**Comment by bornasalman** [comment]
> Hey there, thanks for the suggestion. Answering some older tickets right now. You can swipe right on notifications for easier access to the notification pop-up. Perhaps this helps.

Ended up combining my two issues to create a solution. 
Using folders on favourites list so that tapping it opens the pop-up rather than the whole app. 
Swipe is still reserved for app pop-ups but not necessary for favourites notifications this way.
