### ISSUE TITLE
The setting item for folder icon shape is gone

### ISSUE THREAD

**Issue by liyafe1997** [8bitPit/Niagara-Issues#2668]
### Describe the bug

After updated to 1.11.5, the setting for folder icon shape seems is gone, I can't change the folder icon shape (rounded, square, etc).

Pervious version is OK.

I am the Niagara pro user. it is installed from Google Play.
![Screenshot_2024-04-20-12-23-45-856_bitpit launcher](https://github.com/8bitPit/Niagara-Issues/assets/18359157/b67886ce-2094-4f17-8259-9fe1b25ce1a7)
![Screenshot_2024-04-20-12-23-42-423_bitpit launcher](https://github.com/8bitPit/Niagara-Issues/assets/18359157/a75b94b6-6c98-4dc4-84ff-b05bdad26338)

### Steps to reproduce

Goto settings, appearance, there is no the setting for folder icon shape.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Redmi K30pro

### Android version

Android 5.0 (Lollipop)

**Comment by NiagaraSupport** [comment]
Hi there, and thanks for reaching out.
The feature you're looking for has been moved. You can now find it [here](https://help.niagaralauncher.app/article/153-new-icon-shape-picker). Feel free to let me know if you need any more help.
