### ISSUE TITLE
YouTube notifications are never being displayed; WhatsApp notifications sometimes disappear

### ISSUE THREAD

**Issue by UESPAsputnik** [8bitPit/Niagara-Issues#267]
Hi,

Thanks for the great launcher!

There are just two minor issues:
- None of my YouTube notifications get displayed in the launcher. **<- please ignore this. There was a wrong setting in my YouTube app.** 
- WhatsApp notifications sometimes disappear after a while (though I haven't yet been able to detect a pattern of what causes them to disappear)

**Comment by Scorpionk1** [comment]
There is no problem here in either case.

**Comment by UESPAsputnik** [comment]
> There is no problem here in either case.

Yeah, sorry. I managed to fix the YouTube notifications (notification dots needed to be activated for YouTube, then it worked). But WhatsApp still is a problem sometimes. WhatsApp notifications work 9 out of 10 times, but occasionally they don't show up or randomly disappear.

**Comment by 8bitPit** [comment]
If they dont't show up you can send me a notification log if you want to (advanced > dev options > send notif. log), so I can tell you why they don't show up.

**Comment by UESPAsputnik** [comment]
I think I found the cause of the WhatsApp problem:

When you receive messages in several chats, and then clear one of them ("mark as read"), all of them disappear in Niagara instead of just this single chat.

**Comment by 8bitPit** [comment]
Ah okay, are you on Android 5 / 6?

**Comment by 8bitPit** [comment]
Thanks, I will try that myself and check if I've got the same issue.

**Comment by 8bitPit** [comment]
@alainsr can you provide me a notification log? (Niagara's settings > Advanced > Send notification log)

**Comment by alainsr** [comment]
Never mind. Working here already...

Em dom, 14 de out de 2018 às 11:59, Peter <notifications@github.com>
escreveu:

**Comment by 8bitPit** [comment]
Does the issue still persist? If so, feel free to open it again.
