### ISSUE TITLE
Music launcher moves up clock widget

### ISSUE THREAD

**Issue by Sconerad** [8bitPit/Niagara-Issues#2674]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

When the music launcher starts, it pushes the list of favourite apps down. Can there be an option to have the music launcher push up the other widgets, so that the favourites don't go down and off screen (in some cases). 

I understand that I can move everything up but I like the standard bottom line of the favourites bar with 8 and not have it move down

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your suggestion.
Unfortunately, moving the widgets up can lead to other issues, such as the clock changing format, which might not be ideal for some users (also see the faq [here](https://help.niagaralauncher.app/article/11-media-widget#:~:text=Why%20does%20the%20media%20widget%20push%20favorites%20to%20the%20bottom%3F)). In your case, I'd recommend adding your music app to the [widget stack](https://help.niagaralauncher.app/article/41-adding-multiple-widgets). This way, the media widget won't appear, even when enabled. Let me know if that doesn't address your issue sufficiently.
