### ISSUE TITLE
Animations to fix and create

### ISSUE THREAD

**Issue by kStor2poche** [8bitPit/Niagara-Issues#268]
So, I've been using niagara for around 2 weeks now and i've got to say it's a really good launcher, but I've still seen some things to improve in the animations, so here are those things : 
-first, sliding in the list feels a little bit choppy, if you could add an animation (i'd personally love to see the "wipe" one from nova) that could stack each letter so it doesn't bother the usability it could be really great

-second is more of a bug : when searching, the google button pops back above the keyboard to finish it's animation, so I think either deleting it when searching or adding a delay for the keyboard to open could be a solution

-third is the settings panel wich lacks some animations when changing pages

-and fourth and last, would be the return to the favorites form the drawer : for me it feels too inconsistent, so I think unifying it could be good. 
So here's a little exemple that I think could be great : -make the drawer fade out
                                                                                                      -make the favorite apps come in alphabetical order to 
                                                                                                        their location on the fav screen from the bottom  or any 
                                                                                                        other side of the screen

So that was it, thanks in advance for reading all this. English is not my native languauge, so I do apology if anything was not clear.

**Comment by 8bitPit** [comment]
@master-mind007 and me would also like to see a fade animation while starting to touch and releasing the scrollbar: 
> Don't you think in app menu while scrolling there should be fade in and fade out animations?

(from: https://github.com/8bitPit/Niagara-Issues/issues/832)

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
