### ISSUE TITLE
Search Apps sometimes unresponsive 

### ISSUE THREAD

**Issue by IllumiC** [8bitPit/Niagara-Issues#2682]
### Describe the bug

When pressing the home button to access the Search Apps, the Search Apps bar does not appear when an ongoing animation is occuring.

### Steps to reproduce

Open an app,
Press home button,
press home button again while the animation is occuring.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/40494666/770b1d87-eaa8-4674-92ba-d2f323bb6e9a

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
When pressing home to open the search, the delay is intentional to prevent accidental activations. I'll suggest tweaking the time set to avoid confusion. Feel free to let me know if I can help you with anything else.
