### ISSUE TITLE
Notification Summary Settings Reseting 

### ISSUE THREAD

**Issue by darksim33** [8bitPit/Niagara-Issues#2687]
### Describe the bug

Since the last update the notification Summary features keeps disabling and Reseting

### Steps to reproduce

I can't figure out a pattern 

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Google Pixel 6a

### Android version

Android 14

**Comment by jedthe3rd** [comment]
I am also getting this issue.
I am on a Google Pixel 5, Android 14 (UP1A.231105.001.B2)

**Comment by NiagaraSupport** [comment]
Thank you everyone for reporting this.
The bug should be fixed with the [v1.11.9](https://github.com/8bitPit/Niagara-Issues/releases) patch

**Comment by jedthe3rd** [comment]
The fix seems to be working for me.

**Comment by NiagaraSupport** [comment]
I'll close this then. Should any issues persist, it'll be reopened.

**Comment by GalenMarek1138** [comment]
Hello,

I am on version 1.11.9 and I have one of the problems that was absorbed into this thread:
My Summary is including apps I did not select. 

I tried specifically selecting those (2) apps that were not selected but included in the Summary, saving with them both "checked," going back in and unselecting them, then saving again so they were both "unchecked." But no dice.

I'm on a Samsung Galaxy S21 Ultra 5G 
Android 14
One UI 6.1

Thank you
