### ISSUE TITLE
Two-column layout for normal phones

### ISSUE THREAD

**Issue by Hayyan612** [8bitPit/Niagara-Issues#2693]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I would like to have option of Two-column layout on Niagara for normal phones. I believe it'll be appealing for many.

Specifically Two-column layout for fav apps on home screen.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
@Hayyan612  Have you used notification preview feature of Niagra launcher. I am sure you might not need dual column once you used it.
