### ISSUE TITLE
Some small tweaks to increase the user experience 

### ISSUE THREAD

**Issue by hieunott** [8bitPit/Niagara-Issues#2698]
### Is your feature request related to a problem?

1. Highlight or push app information to the right side of the app header.
2. I usually change the wallpaper on my phone using the default app. Niagara Launcher does not have the option to go to the quick wallpaper changer on the main interface and need many operations to change.
3.  The application category needs a separate application for the newly installed application so that the user does not have to search after the request.

### Describe the solution you'd like

1. Change application information location 
2. Add the option to edit the background image in the main interface.
3. A place to show newly installed apps.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your suggestions.
For future tickets, it would help us if you split them up into one bug/feature request per ticket.

1. Could you explain what you're referring to exactly, the App info option in the long-press dialog or something else?
2. You can create shortcuts to the default wallpaper app with apps like [this](https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker&hl=de&gl=US) for example
3. There is a 'Recently installed' pop-up folder at the bottom of the all apps list

**Comment by contact-maximux** [comment]
Just swipe up, First app will be recently installed app
