### ISSUE TITLE
Move app with notification 

### ISSUE THREAD

**Issue by spottech** [8bitPit/Niagara-Issues#2700]
### Is your feature request related to a problem?

Hello, it's just an Idea.
Automatically move apps with notification to the home screen.
SeeU

### Describe the solution you'd like

Hello, it's just an Idea.
Automatically move apps with notification to the home screen.
SeeU

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the request.
I'll close this as a duplicate of #152.
