### ISSUE TITLE
Some suggestions for the at a glance feature:

### ISSUE THREAD

**Issue by Galvanizim** [8bitPit/Niagara-Issues#2701]
### Describe the solution you'd like

Here are some suggestions for the at a glance  feature: 

○ Low battery alert for wearable devices
○ Flashlight on notification by listening system Flashlight notification 
○ Missed call from [person's name] by listening system notification.
○ A new notification from [person's name] by  listening system notification. 
○ Do Not Disturb on notification by listening system notification 

○ Severe weather changes alert (potential rain coming at 5 p.m., etc.)

○ Similar to notification summary, notification reminder feature that allows users to select specific applications and a preferred time of day to receive a consolidated summary of notifications from those chosen applications. This feature aims to enhance the user experience by providing a more organized and manageable way to review notifications, preventing potential information overload and ensuring that important notifications are not missed. (It won't block the notifications; it will remind them again.)
○A notification page in the Niagara widget for apps not in favorites (users need to enable this).

○ With the use of the Health Connect API, useful health information such as sleep time and more can be obtained and shown at a glance. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestions.
The status bar and notification features already cover a few of these features, so they'll unlikely be added. However, I've forwarded your points to the person in charge and will close this ticket for now. We appreciate your understanding.
