### ISSUE TITLE
Notification Summary includes unselected apps

### ISSUE THREAD

**Issue by ambrosehayes** [8bitPit/Niagara-Issues#2702]
### Describe the bug

The notification Summary is including Spotify in the summary, both in app notifications and the now playing has moved to the summary as well. The now playing is more frustrating as there is no longer music controls in my notification shade. The summary settings have Spotify not selected. 

### Steps to reproduce

In notification Summary settings

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 6

### Android version

Android 14

### Screenshots / Screen recordings

![Screenshot_20240523-002537](https://github.com/8bitPit/Niagara-Issues/assets/69030880/a141af0c-5858-4a0c-9b3c-9c5a0f04bd5d)
![Screenshot_20240523-002512](https://github.com/8bitPit/Niagara-Issues/assets/69030880/c23d6f3f-6873-4ca3-8cc2-fa23b02e7237)

**Comment by NiagaraSupport** [comment]
I assume this is connected to #2687, so I'll close this as a duplicate for now.
