### ISSUE TITLE
Block/lock apps for a time

### ISSUE THREAD

**Issue by Trillionshot** [8bitPit/Niagara-Issues#2708]
### Is your feature request related to a problem?

I did not see this request in the base archive. Though I'm new to GitHub. Sorry if I missed it.

Feature request 
• ability to block or lock my apps so I cannot use them for a time. Individually and/ or an option to lock all but home screen tool/apps. It would lock their respective widgets as well.

Reason:
• I love this launcher you made. I don't want to switch to another minimalist one that has that feature but none of the ones you made. 
If not possible, I understand. I believe this feature is inline with the simplicity described below.

Thank you for your work and this launcher!
Been a pro member for years now!

### Describe the solution you'd like

Block / lock apps for a set time. 

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by Trillionshot** [comment]
On no I just found someone else who posted a request like it now. 
I don't know how to delete mine...

**Comment by TFackler** [comment]
Hi, and thanks for the suggestion; no worries, I will close this issue for you and link the respective issue: #2407 

Please add your thoughts there :)
