### ISSUE TITLE
KWGT widgets shrink on screen rotation

### ISSUE THREAD

**Issue by TFackler** [8bitPit/Niagara-Issues#2712]
### Describe the bug

When having a KWGT widget displayed in Niagara Launcher, rotating the device (with this behavior enabled in Niagara Launcher) will shrink the displayed widget. Repeatedly rotating, will lead to the widget shrinking indefinitely.

### Steps to reproduce

1. Add a KWGT widget
2. (Have rotating home screen enabled for Niagara Launcher, Niagara Settings > Features > Allow home screen rotation)
3. Rotate device and see that the widget is shrinking with each rotation

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Smart Launcher

### Device name

Google Pixel 4

### Android version

Android 14

### Screenshots / Screen recordings

<img src="https://github.com/8bitPit/Niagara-Issues/assets/38538728/066d6641-6970-48fc-91f0-03b63b2083a3" width=33% height=33%>

https://github.com/8bitPit/Niagara-Issues/assets/38538728/0d7c03c3-633b-49f3-bb35-596ed9934db1

**Comment by gerrymuchtar** [comment]
Adding more evidence for this issue.

https://github.com/8bitPit/Niagara-Issues/assets/171511399/e52f2646-ac74-4c73-aa6e-9d72589e9f0b



Other 3rd-party launcher(s) tested
Smart Launcher
Nova Launcher

Device name
Realme GT Master Edition

Android version
Android 13

Screen recordings attached.

Thank you.

**Comment by TFackler** [comment]
We have found a workaround for this issue and added it to our help page: [KLWP/KWGT Integration](https://help.niagaralauncher.app/article/59-klwp-integration)

For the sake of completion I will also post the excerpt here.

> When a KWGT widget is displayed in Niagara Launcher, rotating the device shrinks the displayed widget. Repeatedly rotating will cause the widget to shrink indefinitely. Please note that Niagara Launcher will only rotate with your device if that behavior is enabled (Niagara Settings > Features > Allow home screen rotation).
> 
> To fix this, head into KWGT > tap the menu in the top right (the three dots) > App settings > Widget, then:
> - Set Widget Orientation to Auto Rotate
> - Set Widget Size to Locked

If this workaround does not work for you, please let me know.

**Comment by gerrymuchtar** [comment]
Well done team! It works flawlessly and appreciate it for making the documentation. Case resolved and closed. Thanks again.
