### ISSUE TITLE
Tapping notifications does not open respective app

### ISSUE THREAD

**Issue by TFackler** [8bitPit/Niagara-Issues#2714]
### Describe the bug

Notifications shown within Niagara Launcher (in folders, app pop-ups, and the notification summary) do not open their respective app upon tapping.

This also affects other parts of the app that use notifications / launch intents under the hood, like tapping the media widget, not opening the active media app, and opening widget settings, not launching anything.

The issue only appears on Niagara v1.12.0 and v1.12.1 and Android versions 14 and 15.

We are actively working on a fix.

### Does the issue also occur with other 3rd-party launchers?

The problem doesn't occur with other launchers

### Device name

Google Pixel 5

### Android version

Android 14 and 15

**Comment by 8bitPit** [comment]
Fixed in [v.1.12.2](https://github.com/8bitPit/Niagara-Issues/releases)

**Comment by brog-io** [comment]
The hot fix doesn't work for me

**Comment by 8bitPit** [comment]
Thanks for reporting @brog-io. Could you provide your Android version and whether the issue only affects one or multiple apps?

**Comment by brog-io** [comment]
> Thanks for reporting @brog-io. Could you provide your Android version and whether the issue only affects one or multiple apps?

I'm using android 14, oneui 6.1. And it affects every widget, from different apps.

**Comment by 8bitPit** [comment]
I see, we'll fix the widget bug with our next release
