### ISSUE TITLE
Widget funktioniert nicht richtig wenn Bildschirm füllen aktiviert 

### ISSUE THREAD

**Issue by P1hi** [8bitPit/Niagara-Issues#2717]
### Describe the bug

Google Task Widget kann nicht den Bildschirm ausfüllen weil man sonst beim Aufgaben abhaken das Alphabet auf der linken Seite durch das Widget aktiviert.

### Steps to reproduce

1. Widget Einstellung
2. Bildschirm füllen aktivieren
3. Aufgabe bei Google Task versuchen abzuhaken 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Huawei p smart 2020

### Android version

Android 9 (Pie)

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/171349146/6bb20762-15ca-4ceb-af43-c51ee43a96f3

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
I'll close this as a duplicate of #1525. Please take a look at the answers given there.
