### ISSUE TITLE
Change widget settings inaccessible

### ISSUE THREAD

**Issue by elea11** [8bitPit/Niagara-Issues#2718]
### Describe the bug

Editable widgets aren't accessible since 1.12.0.
![Screenshot_20240531-162334_Niagara Launcher_1_1](https://github.com/8bitPit/Niagara-Issues/assets/61006322/b8b2d005-1539-4b54-a5e0-740567e87222)
The settings of editable widgets aren't accessible through the above option anymore. OS: LineageOS 21, MicroG (no stock play services)

### Steps to reproduce

Long-press home screen widget>press 'change widget settings>nothing happens.

Examples for affected widgets: https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.dark, https://play.google.com/store/apps/details?id=com.google.android.deskclock

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Lawnchair, Trebuchet

### Device name

Google Pixel 7 (Panther)

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this.

We are working on a fix, and it should be available starting with v1.12.3. 
Please stay tuned.

**Comment by elea11** [comment]
Thanks for fixing. It works as expected again now.

**Comment by NiagaraSupport** [comment]
I'll go ahead and close this then.
