### ISSUE TITLE
Music Apps do not show when connected to Android Auto

### ISSUE THREAD

**Issue by humzakh** [8bitPit/Niagara-Issues#2720]
Music Apps properly show when connected to headphones or speakers, but not when connected to a car via Android Auto.

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
Android Auto bugs are difficult to address since we can't try to reproduce them, and they might be beyond our control. Could you provide more info, like device, OS, and car model? We'll gather more feedback and may reopen this at a later date.
