### ISSUE TITLE
Notification text bug

### ISSUE THREAD

**Issue by GregStillPlays** [8bitPit/Niagara-Issues#2722]
### Describe the bug

I've been a beta tester for the last couple of days as well as a premium user for a couple of years now. I quickly noticed that, unlike before, tapping the conversation I had in the notification popup no longer opens the app and I am frustrated by this. I hope a solution can be found soon.

### Steps to reproduce

1. Be on favourites page
2. receive a repliable message and answer it with whatever
3. try to tap the conversation to open the app.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

samsung galaxy a53

### Android version

Android 14

**Comment by 8bitPit** [comment]
Hi @GregStillPlays, thank you for letting us know. I'm happy to tell we could already fix the issue with our latest beta: https://github.com/8bitPit/Niagara-Issues/releases; hope this helps!
