### ISSUE TITLE
Cannot create Google password manager shortcut through Chrome

### ISSUE THREAD

**Issue by tmnc** [8bitPit/Niagara-Issues#2732]
### Describe the bug

In previous versions I would occasionally see this fail on the first attempt to create an icon on the home screen, but it would usually work on the second try. Now it's not working at all

### Steps to reproduce

Chrome browser,settings, password manager, add shortcut to your home screen (Chrome 125.0.6422.147) 

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Pixel 8 pro 

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this issue.

I have tried to reproduce the issue on my Pixel 5 (Android 14) and another developer's Pixel 8 (Android 15) and it's working fine on both of them.

Could you send us a screen recording of the issue?
