### ISSUE TITLE
Option to disable / clear search history

### ISSUE THREAD

**Issue by Fufec** [8bitPit/Niagara-Issues#2734]
### Is your feature request related to a problem?

I am fully content with the launcher and its minimalistic design, except for the search history. On purpose, I didn't put any social media apps on my home screen to reduce my time spent on them. While I appreciate the option to disable these apps from dynamically appearing on the home screen, I tend to mindlessly open the search bar and access the apps from the search history instead. Hiding the apps somewhat works, but it also removes them from the app list, which bothers me because I use the list mainly to check which apps I have installed. I would like to have the option to still access the apps from the app list without having them appear in the search history.

### Describe the solution you'd like

There are three solutions that I came up with:
1. An option to completely disable the search history. The search bar would stay, but there would be no apps under it. It could be located in the Niagara settings as a on/off switch.
2. Selecting the option to hide the app from appearing on home screen would also disable the app from showing in the search history.
3. A separate option in the context menu to select whether an app should be included in search history.

I'd personally choose the first solution, but any of these would personally work for me.
Thanks for the launcher, it's great.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for opening this issue.

I have not yet considered the digital well-being aspect of recommending often-searched apps. I think this does make sense so that I will discuss this internally.

I will close this issue, however, since it's a duplicate. Further discussion should be held in #2456
