### ISSUE TITLE
Add original twitter icon to Anycons

### ISSUE THREAD

**Issue by TFackler** [8bitPit/Niagara-Issues#2736]
From [ArsonCoding](https://github.com/ArsonCoding)

### Is your feature request related to a problem?

I don't know where else to post recommendations cause I still dont really understand how github community post work, but would you be able to bring back the old twitter icons in the custom icon styles (assuming Niagara had Twitter icons idk i haven't used it long) so I don't have to remember how much Elon has added fire to the already burning trashcan that is Twitter. (will not call it the other name)

### Describe the solution you'd like

Add the original twitter icon (the bird) to Anycons.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
After internal discussion, we have decided not to add the original Twitter icon to Anycons since the new Twitter app still contains its new branding once opened, so we do not really see the benefit.

If you disagree, feel free to leave a comment and maybe we will change our mind if enough people want this.

**Comment by saitota** [comment]
I still have the old Twitter app installed, before the icon changed, and have stopped updating the app. Because when I see the X icon, I feel sick.

I really want Anycons to bring back the old Twitter icon. Please take a look at my inconsistent Niagara launcher.

![image](https://github.com/8bitPit/Niagara-Issues/assets/1152469/06ba299e-3d2f-49cc-b3d7-dd9f3456fe91)
@TFackler

**Comment by TFackler** [comment]
While I understand your frustration with Twitter's rebranding and your decision to not update the app. We do not feel like this warrants adding an additional icon. Very few users will have done the same thing as you and sadly the old version will likely break in the near-ish future.

In your case, I would recommend picking another Anycon for the Twitter app, such as "Messages" or "Text Messaging".
