### ISSUE TITLE
Auto Picture-in-Picture

### ISSUE THREAD

**Issue by strangetoucan** [8bitPit/Niagara-Issues#2748]
### Describe the bug

Facing an issue in OnePlus 12R where I watch a video and when I turn to picture-in-picture and when went back to full screen it automatically turns to picture in picture until I reset the video

### Steps to reproduce

- Watch a video in picture in picture 
- Then revert back to full screen

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

OnePlus 12R

### Android version

Android 14

**Comment by TFackler** [comment]
Hi there and thanks for reporting this issue.

Could you please attach a screen recording showcasing the bug? With that we can better investigate the problem.
