### ISSUE TITLE
Notification preview not working 

### ISSUE THREAD

**Issue by PandaSaucePan** [8bitPit/Niagara-Issues#2749]
### Describe the bug

Only popup notification appear in notification bar.
![Screenshot_20240616-222137](https://github.com/8bitPit/Niagara-Issues/assets/172993408/d3a636c9-6e98-420c-926e-0e13ef941f7a)

### Steps to reproduce

N/A

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Moto G34 5g

### Android version

Android 14

**Comment by TFackler** [comment]
Hi and thanks for reporting this. 

Have you checked out this help article? 
https://help.niagaralauncher.app/article/131-enabling-notification-dots
