### ISSUE TITLE
Ability to open app with notification without opening the notification

### ISSUE THREAD

**Issue by AZMPlay** [8bitPit/Niagara-Issues#275]
I've noticed that when an app I use has a notification, I can't open it from the launcher without activating the notification action. Could you people add a fix for this?

**Comment by 8bitPit** [comment]
Hi, you could snooze the notification since Android 8, you can simply dismiss the notification or you can open the app in search.

**Comment by AZMPlay** [comment]
What if dismissing the notification or snoozing it is not an option? It just feels bothersome to have the app in front of you, then having to look it up again in search

**Comment by AZMPlay** [comment]
Maybe clicking on an app with a notification, without sliding to display them could just open the app instead? Maybe there can be an option for that?

**Comment by 8bitPit** [comment]
`What if dismissing the notification or snoozing it is not an option?` 
But that's  exactly what snoozing is for!

**Comment by AZMPlay** [comment]
Because of unavailability, in previous versions of Android

**Comment by 8bitPit** [comment]
Ah okay, maybe I will backport the feature for Niagara notifications

**Comment by AZMPlay** [comment]
Thanks a lot!

**Comment by Shinra04** [comment]
A simple fix could be that if you tap on the app icon, it will open the app, and if you tap on the notification next to it, it will open the app with that particular notification as it normally does.

**Comment by drakovyrn** [comment]
Actually, simply clicking to open and swiping to view notifications makes a lot of sense. I noticed it wasn't possible to open the app itself if it had notifications, but it wasn't too bothersome for me. I can see how it would be for others, though. Mostly, I would just like to see consistent design.

**Comment by ryny24** [comment]
+1!!! Wow, I'm happy I'm not the only one struggling with this. 

Please, please allow an app to run without having to click the notification.

**Comment by AZMPlay** [comment]
Welp. The feature was now added :) Danke!
