### ISSUE TITLE
Calendar widget not working 

### ISSUE THREAD

**Issue by Clemodd** [8bitPit/Niagara-Issues#2751]
The widget for calendar was working and since few months, it only shows the olds events and not the news added.

It bother a little..

**Comment by TFackler** [comment]
Thanks for reporting this issue, please try to reset Android's calendar storage to try and kickstart the sync process again: https://acalendar.tapirapps.de/en/support/solutions/articles/36000104171-reset-the-android-calendar-storage

Please let me know how it goes.
