### ISSUE TITLE
Not able to set Niagara as default launcher

### ISSUE THREAD

**Issue by anoopksharma22** [8bitPit/Niagara-Issues#2752]
### Describe the bug

System asking to set default launch every time I navigate to home

### Steps to reproduce

1. Navigate to Home twice
2. It asks to set default launcher, set Niagara as default launcher 
3. Navigate to home. And the process repeats.
Check the video.

https://github.com/8bitPit/Niagara-Issues/assets/64915087/fd26d868-7e04-4661-95fb-af2c88d507f2

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

One plus Nord 3 5g

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/64915087/1417332d-5841-4451-929f-e53e29cb2564

**Comment by TFackler** [comment]
Thanks for reporting this issue.

It seems that the launcher is not set to be the default properly.

Have you tried this with other third-party launchers, such as [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en_US) or [Lawnchair](https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah&hl=en_US)? You wrote that you have, but I don't see any other launchers appear in the change default launcher prompt, so I wanted to make sure.

Please try to set the default launcher manually, by going to the device settings > Apps > Default apps > Home app > select Niagara Launcher.
