### ISSUE TITLE
YouTube Music stops playing in the background after ~1m

### ISSUE THREAD

**Issue by c0up** [8bitPit/Niagara-Issues#2754]
### Describe the bug

1. Start playing music in YouTube music
2. Background the app and see the music widget appear
3. After around 1m, music stops playing, the widget disappears, and I have to go back into the app and press Play again

This has happened repeatedly all day.
![Screenshot_20240617_145300_YouTube Music](https://github.com/8bitPit/Niagara-Issues/assets/39813682/4b0aa206-7e9a-40b0-82f8-d12bbdeaa70f)
![Screenshot_20240617_145315_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/39813682/72ea875e-9e79-4c26-8fd7-08b54686c375)
![Screenshot_20240617_145417_Niagara Launcher](https://github.com/8bitPit/Niagara-Issues/assets/39813682/58ab7299-115d-4514-8c7e-9ce157cc5f6c)

Note that when I tap on the launcher music widget and open YouTube music, it says "App isn't available"

### Steps to reproduce

1. Start playing music in YouTube music
2. Background the app and see the music widget appear
3. After around 1m, music stops playing, the widget disappears, and I have to go back into the app and press Play again

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Flip 4

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this issue.

Could you please check if this behavior also appears with the stock launcher installed on your device as well as another third-party launcher like [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en_US) or [Lawnchair](https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah&hl=en_US)?

This behavior seems odd and not necessarily related to Niagara Launcher.
