### ISSUE TITLE
Make Niagara button icon customizable

### ISSUE THREAD

**Issue by errantepiphany** [8bitPit/Niagara-Issues#2755]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

All app icons in Niagara are editable, including being able to select from different installed icon packs, *except* the Niagara button. Please let us customize the Niagara button icon - thank you!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Duplicate of #2672
