### ISSUE TITLE
Advanced calculator

### ISSUE THREAD

**Issue by SoappGuy** [8bitPit/Niagara-Issues#2759]
### Is your feature request related to a problem?

Now there's a simple calculator in search, but imagine how cool it would be to have something like [qalculate](https://github.com/Qalculate/libqalculate) instead! More mathematical operations, conversion of different units of measurement, and so on. 

### Describe the solution you'd like

It may be possible to use [libqalculate](https://github.com/Qalculate/libqalculate) for the implementation (I'm not sure how much its license would interfere), but even without it, adding simple conversions and math functions shouldn't be too difficult.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for your feedback.

Sadly, the library you linked seems to be a C++ library mainly and Android development requires Java / Kotlin code. This means we can't simply import the library, and we would need to either find a port of the library or write functionality ourselves.

That said, the current calculator already supports some more advanced calculations, like certain functions (`sqrt`, `ceiling`, `sin`, etc.), modulo, and power.

You can find a non-exhaustive list of what the integrated calculator is capable of here: [Integrated Calculator](https://help.niagaralauncher.app/article/173-integrated-calculator).

I hope this is satisfactory.

**Comment by SoappGuy** [comment]
Thanks for the list of calculator features, it will come in handy. Now, about libqalculate, I found [this repository](https://github.com/jherkenhoff/libqalculate-android), it looks like the library can be compiled into .arr and then used in Java and Kotlin projects, and it's also available in [Maven Central](https://central.sonatype.com/artifact/com.jherkenhoff/libqalculate), so it can be easily added to a project via build.gradle. It would be really cool to integrate such a powerful thing into search, and it's quite possible (I'm not really an Android developer, so I have no idea what I'm talking about). 

Anyway, it's just an idea, maybe it's too complicated to integrate this library, I'm just bringing this information to you guys, thanks for your attention.

**Comment by TFackler** [comment]
Thanks for linking a port for Android. We will check it out and see if it provides much more functionality that we deem useful.

**Comment by TFackler** [comment]
We have taken a closer look, and sadly, the library's license conflicts with our own, making it impossible for us to use it.

Are you happy with the current calculator's abilities or are you missing certain functionality?

**Comment by SoappGuy** [comment]
Current calculator is OK, not amazing, but OK. If it is not possible to use this library I'm closing issue.

**Comment by Plazzmex** [comment]
The only thing missing for me in the calculator right now is percentage calculation. For example when entering 100*5% would be great to have it calculate the 5 percent of 100...
Apart from that the calculator is great

**Comment by TFackler** [comment]
@Plazzmex Thanks for the suggestions. Since I think this is past the original idea of this issue, I have created a new issue for unit conversion: #2832

About the percentage calculator, we are unsure, but will discuss this.
