### ISSUE TITLE
Allow users to create folders please

### ISSUE THREAD

**Issue by LawHrdz** [8bitPit/Niagara-Issues#276]
It be a bit nice if users were able to create folders so then we wouldn't have to scroll all the way to the bottom for apps that are still frequently used. I know it takes away part of the simplicity of the app but at the same time it add functionality for users that per say might uses multiple messaging apps at a time and all of those take half of the space leaving other essential apps all the way at the bottom

**Comment by Scorpionk1** [comment]
Our dear developer is aware from the first day to implement folders.

**Comment by 8bitPit** [comment]
Pls see #13
