### ISSUE TITLE
Switch the language of the Calender date

### ISSUE THREAD

**Issue by shungiku** [8bitPit/Niagara-Issues#2760]
### Is your feature request related to a problem?

My system language of Android is Japanese but I'd like to use English Calender date for more minimal looks. 

### Describe the solution you'd like

Feature of switching Calender date language to English. 

### Feature Request Procedure

- [x] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by shungiku** [comment]
Thank you for your reply!
I set Niagara's app language to English and I'm completely satisfied with it.

**Comment by TFackler** [comment]
Thanks for the quick reply. I am glad you are happy with the workaround.

I will close this issue then :)
