### ISSUE TITLE
App shortcut within pop-up folder

### ISSUE THREAD

**Issue by stevenae** [8bitPit/Niagara-Issues#2763]
### Is your feature request related to a problem?

I'd like to be able to swipe to access app shortcuts within pop-up folders, which I use to organize similar apps and maintain a clean home screen, in the same manner as I can with apps not in a pop-up folder. 

### Describe the solution you'd like

I'd like to be able to swipe to access app shortcuts within pop-up folders, which I use to organize similar apps and maintain a clean home screen, in the same manner as I can with apps not in a pop-up folder. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by stevenae** [comment]
Hi,

I meant shortcuts which surface from swiping right on an application --
attaching a screenshot of one.

**Comment by TFackler** [comment]
I understand you mean shortcuts visible by swiping right on an app. Unfortunately, that doesn't answer my question for your specific use case. You can long-press a shortcut inside a pop-up and then select "Show in app list." Then, you can edit the folder and add the shortcut directly.

What apps do you have in folders whose shortcuts you'd like to use?
