### ISSUE TITLE
Make available on ios/iphone

### ISSUE THREAD

**Issue by Sab-rie** [8bitPit/Niagara-Issues#2771]
### Is your feature request related to a problem?

I have both android and ios and I'm so used to niagara that using my iphone frustrates me, even though it should be my main phone for its camera. Please add it to ios.

### Describe the solution you'd like

App added to ios/iphone

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
We appreciate your suggestion.

Sadly, iOS does not support the use of third-party launchers, since Apple puts great value on their user interface and user experience.

This means we cannot make Niagara Launcher available on iOS.
