### ISSUE TITLE
Division by zero crash

### ISSUE THREAD

**Issue by lrcf** [8bitPit/Niagara-Issues#2776]
### Describe the bug

The launcher crashes when attempting to divide by zero (as a float) using the search feature.

### Steps to reproduce

1. Open search
2. Write `2/.0`
3. Niagara should crash

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 8

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this. I could reproduce the crash. We will investigate and fix the issue soon.

**Comment by lrcf** [comment]
Thanks @TFackler. Just checked and it was fixed.
