### ISSUE TITLE
App Blocking/Delayed Opening

### ISSUE THREAD

**Issue by stangtr** [8bitPit/Niagara-Issues#2779]
### Is your feature request related to a problem?

Sometimes when we get into a habit of opening apps when we're bored or have a little free time, we waste it by getting sucked into an app we don't need to be in.

### Describe the solution you'd like

Having a pop-up that says something like: "How much time do you want to spend in this app" and select a time in minutes or have a count down before you can open the app will help deter us from mindlessly opening an app and getting stuck in it.

I've seen some other minimal launchers with this feature, and it would be great on Niagara. I like the layout and existing features of more than the other launchers.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for this proposal, please check out this issue with a similar request: #2407 

I will close this ticket as a duplicate, but feel free to add your thoughts to the aforementioned issue.
