### ISSUE TITLE
Apps stops redrawing

### ISSUE THREAD

**Issue by phil-scott-78** [8bitPit/Niagara-Issues#2799]
### Describe the bug

Intermittently I'll return to the home screen and Niagra longer draws. I get haptic feedback, things are working and I can still click on icons, but nothing is being redrawn. Locking the screen and returning will redraw the screen but it remains in a state where it nothing is being redrawn. 

The app is actually responsive. If I "scroll" to the bottom I won't visually see it, but I can lock the screen and come back and the launcher will show the proper state. I can swipe down from the top and still access notifications. It's just Niagra redrawing that seems to be affected. 

This seems to have only started to occur with the past two android builds. My current one is AP2A.240705.005 but it was also occuring with AP2A.240605.024

Removing the app and deleting the settings doesn't seem to help. This is with widgets and no widgets.

### Steps to reproduce

Seems to happen at random. Sometimes it'll happen when returning from the home screen, others when swiping from an active app

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nova

### Device name

Pixel 8 Pro

### Android version

Android 14

**Comment by brnslmn** [comment]
Does changing Niagara's battery to Unrestricted produce the same thing?

**Comment by phil-scott-78** [comment]
Ran it with unrestricted battery for a while. Still seeing the issue, unfortunately

**Comment by phil-scott-78** [comment]
Not sure how I missed #2595, but I'm almost certain my issue duplicates it. I had installed from gh releases so I didn't have the screen locking service option available. Went ahead and got the play store version and with that enabled it has been much smoother for me.

**Comment by phil-scott-78** [comment]
Went all weekend with the increased permissions and no issues. Gonna go ahead and close this as duplicated by #2595
