### ISSUE TITLE
Slider drawer colour?

### ISSUE THREAD

**Issue by krypticallusion** [8bitPit/Niagara-Issues#28]
Can you guys have a sort of tint given to the slider drawer instead of having it all in transparent, would make reading app names and things far more legible!

**Comment by 8bitPit** [comment]
I am not a huge fan of tinting the whole wallpaper. However if this will be requested often I will implement that!

**Comment by Sacchid** [comment]
How about giving toggle/option in settings for transpert/tint/blurred background?

**Comment by 8bitPit** [comment]
If you want to further discuss about the feature, please visit: https://github.com/8bitPit/Niagara-Issues/issues/705
