### ISSUE TITLE
9Folder email support

### ISSUE THREAD

**Issue by d96moe** [8bitPit/Niagara-Issues#280]
9Foldee email notifications doesn't work, ie you can't see the emails under the icon in Niagara

**Comment by 8bitPit** [comment]
Please send me a notification log by going to Niagara Settings > Advanced > Debug options > Notification log.

**Comment by d96moe** [comment]
Done!

Best regards
Fredric


Den tors 27 sep. 2018 kl 18:12 skrev Peter <notifications@github.com>:

**Comment by 8bitPit** [comment]
Thanks,

Your notification log reads
`[has_low_importance=true]`
so the dev flagged the notification to have a low priority. I've got a notification filter that blocks those messages from showing up as a preview (you can still swipe that app to the right you can read the notification). Maybe I'll add an option to change the filter.

**Comment by d96moe** [comment]
Thanks for the info.
I managed to get it working.
Apparently, 9folders set the notification flag has_low_importance to true
if you select the notification sound to be silent. However, if you select a
sound AND then select the special 9Folder notification setting "silent
notification" (ie in nines internal settings “) it DOESN'T 😂

Took some testing to fix, even tested the app AutoNotificaton
 https://play.google.com/store/apps/details?id=com.joaomgcd.autonotification
The app fixed the issue but also tipped me regarding the fact that
importance level is tied together with the notification sound setting.

Thanks for a great Launcher, I really like it. Keep up the good work!

Best regards
Fredrc

Den fre 28 sep. 2018 00:07Peter <notifications@github.com> skrev:

**Comment by 8bitPit** [comment]
@d96moe glad you could solve the problem :)
