### ISSUE TITLE
permanent camera indicator

### ISSUE THREAD

**Issue by MarkusWucher** [8bitPit/Niagara-Issues#2808]
### Describe the bug

After using the camera in Snapchat or WhatsApp for example it stays permanent in the right upper corner. Only restarting the phone solves the issue.

### Steps to reproduce

Use camera. In any App
![Screenshot_20240718-175431](https://github.com/user-attachments/assets/756693fd-4819-4776-8ded-96f7a2aaaaed)
__

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

fairphone 4

### Android version

Android 13

**Comment by brnslmn** [comment]
This should be an overlay from the OEM launcher. Does force closing Snapchat/Whatsapp make it go away?

**Comment by TFackler** [comment]
I agree with @brnslmn. 
This is likely not an issue with Niagara Launcher but with your phone's "Android flavor".

It would be great if you could test whether the same issue appears when using other third-party launchers like [Nova](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher) or [Smartlauncher](https://play.google.com/store/apps/details?id=ginlemon.flowerfree).
