### ISSUE TITLE
alphabetize the list of icon packs

### ISSUE THREAD

**Issue by sfosdal** [8bitPit/Niagara-Issues#281]

**Comment by sfosdal** [comment]
![screenshot_20180926-232706](https://user-images.githubusercontent.com/684453/46164771-b6300d80-c243-11e8-95e0-e5145ddb34da.png)

**Comment by DanHolli123** [comment]
I have the same issue and it would be great, I use Elun which ends up at the bottom of the page

**Comment by 8bitPit** [comment]
Great idea @sfosdal :)

**Comment by sfosdal** [comment]
this appears to have been taken care of in the most recent release

**Comment by sfosdal** [comment]
nice

**Comment by 8bitPit** [comment]
@sfosdal Yup :)
