### ISSUE TITLE
Second layer applist 

### ISSUE THREAD

**Issue by darksim33** [8bitPit/Niagara-Issues#2835]
### Is your feature request related to a problem?

With more and more apps installed the list can get quite cluttered. Especially, for apps that are only usef from time to time. 

### Describe the solution you'd like

A second layer for the applist would be nice to store the apps which are only occasionally used or which serve a special purpose or are maintainance related like headphone apps.
While grabbing and moving the applist to the center there could be a sweet point where similar to the "back" gesture a icon or a preview appears to swap list. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for the suggestion.

For this particular use case, I would recommend either using [pop-ups/folders](https://help.niagaralauncher.app/article/115-pop-ups) or, if that is not enough, adding your thoughts to #165 .
