### ISSUE TITLE
Suggestion: Docked folders

### ISSUE THREAD

**Issue by Shinra04** [8bitPit/Niagara-Issues#284]
https://photos.app.goo.gl/pTMiYwFPpMVGs8mB6

- Static Folders overlay in Favourite screen.
- The Recent apps present behind if you scroll up. Alternatively can be made into an autogenerated folder.
- Tap or tap and drag across icons to switch between folders. First folder is Favorites screen for simplicity.
- Only necessity of tint was to show it as overlay, not necessary in actual implementation.

**Comment by 8bitPit** [comment]
Forwarded image from @Shinra04:
![image](https://user-images.githubusercontent.com/9284845/46203663-c830af80-c31a-11e8-8f45-e5c46dc551df.png)

Hey shinra, as you know I thought also of categorization. My idea would be labels, where your categorized apps show up beneath (by clicking on the header). Also, most used apps / apps with messages in that category could show up automatically there. 

Currently I am working on other stuff though, so I can’t show you my ideas right now. I will contact you when I’ve got some updates and we can discuss folders further.

**Comment by Shinra04** [comment]
@8bitPit

So you mean you're going to be implementing something quite like the suggestion I had first given, in my first 'A thoughtful list of suggestion' (thread #131)? (Pic included there too, for those who want to see)
 It was about labels at the upper part of the screen, which could be tapped on to reveal apps as a list below, and could be swiped left and right for other such 'tappable' labels. 

I found 2 problems with that though:
- It's extra work to reach the upper part of the screen.
This is also why Google had moved the search bar from where it used to be(i.e. up) to where it is now(i.e. down).
Solution: move folders bar to lower part of screen.

- Labels take up way more space than icons. It makes it more work to swipe across many just to get to that one folder you want.
Solution: Icons have the benefit of speed of access to more folders, as more are in view. If you're concerned about keeping a clutter-free look without multiple icons like in the pic, you could make the icons translucent, or perhaps create labels with only 1-2 letter visible; for example 'Ga' for 'Games', 'So' for social media, etc. Tapping the (transparent) circular icons open the respective folder with its title and apps shown.

**Comment by Shinra04** [comment]
Hmm...
So you mean to say you're considering creating additional letters in the apps list, but these letter are going to be two letters (arranged in alphabetical order)?
So 'Games' will appear right below 'G' as 'Ga' in the app scroll? And as soon as you navigate to 'Ga' the apps of this folder will be shown? And I'm assuming there will be a title 'Games' at the time which you can tap to condense the list into only the folder name, revealing other regular apps.

If this is the case, then I think it'll work just as well, because the folders will still be only a single gesture away. Perhaps highlighting the two 'folder letters' would be a nice idea. 

However if we have to navigate to the first letter of the folder and then tap on the folder under that letter, it would be too much.

**Comment by 8bitPit** [comment]
@Shinra04 good point

**Comment by 8bitPit** [comment]
Merged with #13
