### ISSUE TITLE
Error when closing applications

### ISSUE THREAD

**Issue by KaymaPirog** [8bitPit/Niagara-Issues#2854]
### Describe the bug

When closing apps with a gesture on Pixel 8, there are strange glitches for a split second
I.e. strange red pixels around the icon.

### Steps to reproduce

1. Go to any app
2. Work in it a little bit (YouTube for sure).
3. Exit the application (this does not always happen)

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Google pixel 8

### Android version

Android 14

**Comment by TFackler** [comment]
As the original request was in Russian, I have translated it using DeepL.com

Original message:

# Ошибка при закрытии приложений

### Describe the bug

При закрытии приложений жестом на Pixel 8, появляются странные глитчи на доли секунды
Т.е. вокруг иконки странные красные пиксели


### Steps to reproduce

1. Зайти в любое приложение
2. Чуть поработать в нем(в Ютубе точно)
3. Выйти из приложения (это происходит не всегда)

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

_No response_

### Device name

Google pixel 8

### Android version

Android 14

### Screenshots / Screen recordings

_No response_

**Comment by TFackler** [comment]
Thanks for reporting this issue.

This might be related to another issue: visual glitches when going home on Pixel devices.

It looks something like this:
![image](https://github.com/user-attachments/assets/80236a59-838e-4cfa-aa26-4a40302e85ac)

Could you please try to capture the bug happening and then upload a screen recording here? With that, we could verify whether these two issues are related.
