### ISSUE TITLE
Google Tasks Integration into Calendar 

### ISSUE THREAD

**Issue by noisystyle** [8bitPit/Niagara-Issues#2872]
### Is your feature request related to a problem?

Make all Google tasks activities visible in calendar view 

### Describe the solution you'd like

Using APIs provided by Google 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
Nobody does that freely except google itself. google task api are way complex to work with other API

**Comment by TFackler** [comment]
Thanks for the suggestion. Sadly, we will not be adding this.

> Niagara Launcher does not support them. Unfortunately, Google doesn't provide other apps access to their reminders and tasks via the on-device Android calendar system. They provide a dedicated API, but it requires an active internet connection for synchronization, and its functionality is not as comprehensive as it appears. Furthermore, the API has not received any updates since its release; therefore, we do not intend to integrate it in its current form (see [this](https://issuetracker.google.com/issues/128979662) and [this](https://issuetracker.google.com/issues/36759725) issue on their tracker).
(from [our help page](https://help.niagaralauncher.app/article/76-calendar-faq))
