### ISSUE TITLE
Disable click/tap on third party and Niagra widget

### ISSUE THREAD

**Issue by contact-maximux** [8bitPit/Niagara-Issues#2878]
### Is your feature request related to a problem?

Hello Team, thanks for super clean default widgets. I hardly move anywhere from niagra home screen, As weather, time, calendar event, notification, required app for entire day, everything is visible in one quick look.

### Describe the solution you'd like

 So 

> Disable tap/click on widgets. You can use universal switch in settings like. 
- Disable click on Niagra widgets
- Disable click on all widget
- Or provide **disable click** settings in every widget setting window
- ### **Elsewise disable click/tap on third party widget is utmost required.**

This way accidental click will not move me to another app and then closing them by pressing millions times back button

> If you still not convinced with this. Please make tap/click on widget as **long click/long tap.**

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, I'll merge this with #2879 as well.
