### ISSUE TITLE
Toggle to Hide Search Button for Distraction-Free Home Screen

### ISSUE THREAD

**Issue by debojitsantra** [8bitPit/Niagara-Issues#2881]
### Is your feature request related to a problem?

The persistent search button can be a distraction and trigger for users who struggle with app addiction, like myself. I often hide apps like YouTube to maintain self-control, but the search button can still tempt me to mindlessly scroll and relapse.
A toggle switch to turn the search button on or off would help me avoid this distraction and support my self-control.

### Describe the solution you'd like

Add a single toggle switch in the settings to turn the search button on or off. When toggled off, the search button disappears.

This solution aligns with Niagara Launcher's design principles:

- Simple: Easy to configure and use, with only one additional toggle.
- Impactful: Necessary for users like me who struggle with app addiction, and potentially appealing to others who value a distraction-free ui.
- Universal: Works everywhere, on all phones, without affecting other features.
- Independent: Doesn't add complexity if not used. the toggle is simple and self-contained.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
If  you are pro user, you can assign any task to right bottom button. also disable search by swiping up

**Comment by debojitsantra** [comment]
> If  you are pro user, you can assign any task to right bottom button. also disable search by swiping up

I want to disable this button....![Screenshot_20240905-124911~2.png](https://github.com/user-attachments/assets/2a55ecf5-3c6b-4956-97e6-b0fbba5d5912)

**Comment by contact-maximux** [comment]
This is not possible right now. But you can change action of it. Long tap in it and assign task
- flip coin
- lock screen
or something similar

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
Sorry to say it is not planned to hide the search button in the all-app screen right now. The impact just isn't high enough to warrant adding additional toggles right now. I did note your feedback however, in case this decision is reevaluated.
Also for clarification purposes the [Niagara Button](https://help.niagaralauncher.app/article/116-niagara-button) is a different functionality all together and can be disabled in the settings.
