### ISSUE TITLE
I hope you can optimize MIUI.

### ISSUE THREAD

**Issue by phrynus** [8bitPit/Niagara-Issues#2883]
### Describe the solution you'd like

I hope you can optimize MIUI. NIUI will not restore gesture navigation

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for your request.
I'm not sure if I understand the issue correctly. I'd recommend addressing problems with MIUI with their support first.
