### ISSUE TITLE
Menu offset when removing 10+ apps

### ISSUE THREAD

**Issue by andersoyvind** [8bitPit/Niagara-Issues#2898]
### Describe the bug

I uninstalled a fair bit of apps, going down the alphabet in an orderly fashion. As I afterwards wanted to open something at P, I was left off at S.

### Steps to reproduce

Have 100 apps

Uninstall 20 of them, perhaps those early in the alphabet, but maybe not all for one letter.

Verify that menu navigation now is offset.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Google Pixel 8 Pro

### Android version

Android 14

**Comment by andersoyvind** [comment]
After writing the bug report, I retried navigation, and it was working as intended again. So workaround: Wait?

**Comment by NiagaraSupport** [comment]
Hey, thanks for the report.
I'm glad it works now. Could have been any number of issues. I'll close this for now, as it can reopen if the problem resurfaces.
