### ISSUE TITLE
Edge screen OEM features inaccessible from main/favorites screen

### ISSUE THREAD

**Issue by Philippe-Choquette** [8bitPit/Niagara-Issues#2899]
### Describe the bug

The back gesture from the Android gesture navigation seems intentionally disabled on the main/favorites screen of the launcher. This makes sense in the context that it's the first layer of the launcher, and you can't go back further. However, it makes some OEM features that are usually accessible from screen edge swipes impossible to use. The launcher mistakes those gestures as interactions with the alphabetical app scroll-bar.

### Steps to reproduce

1. Enable Android's gesture navigation _(swipe from the side of the screen for "Back", and from the bottom to access the home screen or the app switcher)_
2. Enable an OEM gesture which is triggered by a swipe from the side of the screen
3. Attempt to trigger the OEM feature from the main/favorites screen of the launcher

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

The launcher provided by my device OEM doesn't have the same issue, since they make the back gesture accessible anywhere. I didn't compare with other launchers yet.

### Device name

REDMAGIC 9 Pro

### Android version

Android 14

### Screenshots / Screen recordings

Here's an example with the "Z-SmartSidebar" feature on REDMAGIC (gaming brand of Nubia) devices:

https://github.com/user-attachments/assets/2c5dda51-7d84-4942-809c-66336ba35acc

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report.
This isn't something we'll work on right now, as it clashes with our alphabet design, and the perceived impact isn't high enough. I've forwarded it to the team, and if the need grows or more requests come in, we might reevaluate. I appreciate your understanding.
