### ISSUE TITLE
Split screen and floating windows

### ISSUE THREAD

**Issue by lina01482003** [8bitPit/Niagara-Issues#2903]
### Describe the bug

My favorite feature on my Xiaomi 13T is split screen and floating windows. While Niagara launcher is set as default, none of those work. I don't know if it's a bug ir missing feature but i paid for premium and have been using it for over a year but this is making me reconsider.

### Steps to reproduce

1. Go to menu od open/recent apps
2. Press down on one to activate the floating windows/split screen tool menu
3. The screen freezes and you have to exit the menu

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Xiaomi Launcher 

### Device name

Xiaomi 13T 

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this. 

Could you please confirm whether the same issue appears when using other third-party launchers, such as [Smart Launcher](https://play.google.com/store/apps/details?id=ginlemon.flowerfree&hl=en) and [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en)?

This is likely another restriction set by the Xiaomi developers when using custom launchers on their devices.
