### ISSUE TITLE
Slow app closing animation 

### ISSUE THREAD

**Issue by binoysam** [8bitPit/Niagara-Issues#2906]
### Describe the bug

When I am closing any app , the app closing animation is lagging and slow 

### Steps to reproduce

Opening any app
Closing the app
Back to home screen and the screen freezes and lags

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Other 3rd-party launcher(s) tested

Nova launcher 

### Device name

Realme gt 2 

### Android version

Android 14

**Comment by TFackler** [comment]
Thanks for reporting this issue.

Could you please attach a screen recording of the issue so we can identify it properly?
