### ISSUE TITLE
straight access to calender 

### ISSUE THREAD

**Issue by faiz-wxyz** [8bitPit/Niagara-Issues#2912]
### Describe the solution you'd like

hi there. it will be great if there is an option to put straight access to calender (not to show "My Agendas") when tapping on the date on the homescreen. thank you

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Hi there,

Try opening [this link](https://nlaun.ch/c/legacy-calendar) on your phone or type `/legacy-calendar` into Niagara Launcher's app search and hit enter.

This will toggle the behavior you are requesting.

**Comment by faiz-wxyz** [comment]
worked just fine. thank you
