### ISSUE TITLE
When App is listed in a pop-up folder, hide it in app list

### ISSUE THREAD

**Issue by romavonk** [8bitPit/Niagara-Issues#2925]
### Is your feature request related to a problem?

When App is listed in a pop-up folder, hide it in app list.
Now the app is default listed twice, in the pop-up folder and in the app list (not logical).

### Describe the solution you'd like

Automaticly hide-out an app from the app-list when it is added to a pop-up folder. 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by jstorrs** [comment]
Even if folders just had a manual function to mass hide everything inside the folder contain it would help. The current method of having to do them one by one is just soooooo tedious and error prone.

**Comment by PaulWebb** [comment]
Please don't just combine this and forget about it. Surely it can't be that difficult if other launchers do it....

**Comment by 8bitPit** [comment]
Thanks for the suggestion, @romavonk! We're planning to add some kind of mechanism to speed up the process of hiding apps from the app list. We will post any updates in the issue you referenced (#1604).

**Comment by martin-krueger** [comment]
I suggest an action in the folder setting to remove all apps in the folder from the app list. This would make it easier to handle a bunch of Apps.

**Comment by Hazem42** [comment]
I feel like this is a must and really should be on the top of the list
