### ISSUE TITLE
search won't work for substrings

### ISSUE THREAD

**Issue by zzjjaayy** [8bitPit/Niagara-Issues#2940]
### Describe the bug

Search won't work for substrings of words. Results only show up where the query matches the start of a word in the apps' names.
Should be an easy fix.

### Steps to reproduce

- using V1.12.9 {Latest for me}
- Swipe up to search
- Assuming you have "Play Store", type in "Ay"{case won't matter}
- "Play Store" won't show up

EXPECTED: 
Play Store **_should_** show up.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

OnePlus Nord 2 5G

### Android version

Android 13

### Screenshots / Screen recordings

Attaching my current search settings and bug demo: 
![Screenshot_2024-09-30-19-49-52-82_a4824db61f40c53807964ea8b14c92fe](https://github.com/user-attachments/assets/bce32b27-38f5-439b-9a24-2acac7c20095)

https://github.com/user-attachments/assets/1f153a36-cb1d-407a-be4b-73d48bf936fc

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the report. 
Two characters aren't enough for the fuzzy search to trigger, as it might confuse people if too many entries show up.
Try typing in 4 characters and it should work as intended.

**Comment by zzjjaayy** [comment]
@NiagaraSupport do you think it would be better to trigger fuzzy on 3 letters? I usually type 3, like in the video I attached and I miss having it from one of the previous versions. I understand that addition of search categories has inflated the possible result count but maybe we could make it less restrictive for at least the app names?

**Comment by NiagaraSupport** [comment]
I'll ask why 4 is the magic number here and get back to you.
