### ISSUE TITLE
Niagara Wallpapers not loading 

### ISSUE THREAD

**Issue by Stormy314** [8bitPit/Niagara-Issues#2945]
### Describe the bug

Niagra pro is unable to load up wallpapers due to "no Internet connection" despite the phone being connected to a stable Internet connection.

### Steps to reproduce

1. Open "Niagra settings"
2. Select "Look"
3. Select: "Wallpapers"
4. Many or all wallpaper folders are "Offline"
![Screenshot_20241001-044300](https://github.com/user-attachments/assets/61c9ef1f-8807-433c-92de-f1a71aeeb8d4)

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Google Pixel 7 pro

### Android version

Android 14

### Screenshots / Screen recordings

![Screenshot_20241001-044300](https://github.com/user-attachments/assets/47e33aa6-e36b-462a-8583-1a03eb2473ad)

**Comment by jspayton2300** [comment]
I am experiencing the same issue.
Google Pixel 9 Pro XL
Android 14

**Comment by NiagaraSupport** [comment]
Thanks for the report.
Is it just the preview / thumbnail or the rest as well?

**Comment by jspayton2300** [comment]
When I try to tap on the thumbnail/preview I get the message about not
being connected to the Internet, while I am definitely connected to the
Internet. None of these wallpapers will come up, only the ones I can see
the preview.

**Comment by NiagaraSupport** [comment]
Thanks for the clarification. We'll update you once we know more.

**Comment by jspayton2300** [comment]
Excellent, thank you.

**Comment by aleksod** [comment]
> Just wanted to add that I'm getting this on my Cat S22 Flip phone as well. Internet fully works in every other app, and everything else about the Niagara launcher works well. The wallpaper thumbnails all load in fine, but when I tap on any of them, I get the "No internet connection" error.
> 
> Not sure how else to help troubleshoot, but happy to try any suggestions on my end.

I have the same exact problem on CAT S22 Flip.
