### ISSUE TITLE
Request: Select alarm/clock app

### ISSUE THREAD

**Issue by justcallmeandres** [8bitPit/Niagara-Issues#295]
I use an alarm clock alternative from the play store and have disabled the stock clock app.

Currently, when I click the clock wiget, an error message pops up: "Application is not installed."

Please provide a way to select which app is opened when clicking on the time widget!

Thanks!

**Comment by 8bitPit** [comment]
hmm... Niagara opens any app which reacts to "AlarmClock.ACTION_SHOW_ALARMS". Please ask the developer of your alarm app if can support it.

**Comment by 8bitPit** [comment]
In the future, you can choose your clock app freely though.

**Comment by justcallmeandres** [comment]
Thank you for the heads-up! Look forward to the new updates.

**Comment by 8bitPit** [comment]
For Samsung users: Unfortunately, Samsung's alarm screen doesn't let you choose to switch to other features of the clock app (timers, stopwatch, world clock, etc.). For now, you can workaround this by installing Google's clock app: https://play.google.com/store/apps/details?id=com.google.android.deskclock

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.
