### ISSUE TITLE
Swipe left to go to Google News

### ISSUE THREAD

**Issue by rod-miranda** [8bitPit/Niagara-Issues#2950]
### Describe the solution you'd like

I would like the option to use the swipe left to get to Google News like in the originals stock launchers in Android. Thanks for the attention!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by NiagaraSupport** [comment]
Hey there, thanks for the suggestion.
Unfortunately, there are no plans to imitate the stock launcher in this way. However, you can already create shortcuts on the homescreen or map them to the [Niagara Button](https://help.niagaralauncher.app/article/116-niagara-button) for easy access, or use the widgets / [widget stack](https://help.niagaralauncher.app/article/41-adding-multiple-widgets) for similar functionality. Let me know if you need any help with that.
