### ISSUE TITLE
Request: Show all apps with notifications in favourites section

### ISSUE THREAD

**Issue by Matt-T10** [8bitPit/Niagara-Issues#296]
Is it possible to add an option to show any app that has a notification in the favourites section? Thanks

**Comment by Co2p** [comment]
I like the original idea:
Temporarily promote apps with notifications to the favourites section.
As long as it is possible to mute apps, and the older notifications get pushed back down to the normal app-list

**Comment by 8bitPit** [comment]
See: #152
