### ISSUE TITLE
Icons/text resizes when screen resolution changes

### ISSUE THREAD

**Issue by sambernard** [8bitPit/Niagara-Issues#297]
First of all- thanks for creating this launcher! It's sleek, performant and really easy to use.

I've noticed one issue: when I put my phone into power saving mode (which changes the screen resolution), all the icons/text in the launcher is scaled up. Depending on how may favorite/recently used apps are on the screen, some icons on the home screen may overflow.

I've included pictures below for comparison. Once again- thanks for all your work on this app!

WQHD+ (2960x1440):
![1538329930102](https://user-images.githubusercontent.com/170295/46260783-41f1a600-c49f-11e8-9f84-18aaf79c6a34.png)

Power Saving Mode (FHD+ 2220x1080):
![1538329878451](https://user-images.githubusercontent.com/170295/46260787-4a49e100-c49f-11e8-9f60-b1af56e57b9e.png)

**Comment by 8bitPit** [comment]
For anyone who's also experiencing this problem, here's a workaround to fix the problem temporarily:
Change the icon size manually (Niagara's settings > Look > Icons > App icon size) and revert the change.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
