### ISSUE TITLE
Niagara button swipe up shows multiple apps

### ISSUE THREAD

**Issue by martin-krueger** [8bitPit/Niagara-Issues#2970]
### Is your feature request related to a problem?

Some apps, like wallet or a time tracker, I want to open fast but I don't want them in my favorite because I need them less often but when I need them I want them fast.

### Describe the solution you'd like

I propose to extend the Niagara button to open an app list if you swipe up.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by DashDashCZ** [comment]
You can get it to open a folder where you put these. I'm using it like so.

**Comment by martin-krueger** [comment]
@DashDashCZ That's it! Thx
