### ISSUE TITLE
Interfaces show Czech while system language setting is English

### ISSUE THREAD

**Issue by UlyssesZh** [8bitPit/Niagara-Issues#2972]
### Describe the bug

Language shown on interfaces of Niagara Launcher settings (and sometimes widgets) are in Czech while the system language setting is English.

### Steps to reproduce

This can sometimes happen after the phone restarts. If it happens, it persists through launcher restart.

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

AOSP launcher, TinyBit Launcher

### Device name

Google Pixel 9 (GrapheneOS)

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/user-attachments/assets/8e9efac3-616e-4694-92ef-bef5fec7d8f7

**Comment by TFackler** [comment]
Thanks for reporting this issue.

Could you please check whether you have the app-language of Niagara Launcher set to Czech?

You can do so by going to Niagara Settings > Advanced > App info > Language > System default

**Comment by UlyssesZh** [comment]
Thank you. Fixed it in this way.
