### ISSUE TITLE
Custom Search UT

### ISSUE THREAD

**Issue by mrtrevelyan** [8bitPit/Niagara-Issues#2973]
### Is your feature request related to a problem?

The only choices in the baked in Niagra search options are Google and DuckDuckGo. No custom url field. 

### Describe the solution you'd like

The option to create a custom search url (so we can use AI search engines for example) would be a nice addition! (I know this is integrated in a round about way via Sesame, but would be nice to have it baked in so that one can just swipe up, and the default results come from ChatGPT, Perplexity et al!

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for the suggestion. We already have an issue on custom search engines #2711. Please add your thoughts there :)
