### ISSUE TITLE
Request: Replace time/date with a widget of your choice

### ISSUE THREAD

**Issue by colluphid42** [8bitPit/Niagara-Issues#298]
There's a clock in the status bar. I don't need another one on the home screen. I'd prefer to put a widget at the top of the favorites list on the homescreen instead.

**Comment by Scorpionk1** [comment]
I also think there is no need for a clock in this launcher or in any other launcher. Offering widget is of paramount importance.

**Comment by 8bitPit** [comment]
See: https://github.com/8bitPit/Niagara-Issues/issues/44
