### ISSUE TITLE
Add more Widgets

### ISSUE THREAD

**Issue by KxJiN** [8bitPit/Niagara-Issues#2985]
### Describe the solution you'd like

I had the idea to add the ability to install more than one widget on the screen at once (I'm not talking about what is already implemented in the launcher) I want it to be implemented as widgets on the lock screen in Nothing OS or IOS.

![nothing-os-lockscreen-41](https://github.com/user-attachments/assets/dea1d616-1a9d-4965-8af8-c66af37faebd)
.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by contact-maximux** [comment]
I dont think any app have such capability to modify existing lock screen. Either changes lockscreen app or change operating system. Any launcher migh not be that permissible candidate
