### ISSUE TITLE
Calendar and notes widget

### ISSUE THREAD

**Issue by kkeshav93** [8bitPit/Niagara-Issues#299]
Some how to show the next calendar appointments and notes... They are crucial part of everyone's life... It would be amazing if you can figure out a way to show them.

**Comment by 8bitPit** [comment]
For showing appointments, see: https://github.com/8bitPit/Niagara-Issues/issues/55
AFAIK there is no way you can integrate notes (except with widgets, see https://github.com/8bitPit/Niagara-Issues/issues/117 for that)
