### ISSUE TITLE
Google Feed / Google Now

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#3]

**Comment by 587saboor** [comment]
@jakcharvat ye with those companion apps like the one lean launcher has

**Comment by Chaphasilor** [comment]
I don't know if this is possible, but Sesame Shortcuts integration would be awesome! It's working in Nova launcher and it is sooo useful!

**Comment by jakcharvat** [comment]
@587saboor eaxctly. Many launchers have it, would love to see it in Niagara as well. The lack of Google Now is one of the main minuses of Niagara for me (even though the rest of the stuff makes up for it)

**Comment by 8bitPit** [comment]
Google now: Isn’t the assistant and the google app replacing the news feed? (I’m not a Google Now user, so I’ve little experience). Also, I don’t know which gesture should be used to open it.

Sesame: I should do some research. As of now, I believe Nova & Sesame partnered for a search integration and its rather exclusive.

**Comment by 587saboor** [comment]
@8bitPit
No, the gesture should be to swipe to the right to get to the news feed

**Comment by 8bitPit** [comment]
That gesture is for opening notifications

**Comment by 587saboor** [comment]
@8bitPit oh s**t, how about swipe left

**Comment by Chaphasilor** [comment]
@8bitPit the swipe right only needs to work on thw favorites screen, and maybe even onky from the edge of the screen...

**Comment by 8bitPit** [comment]
@587saboor that is for deleting notifications.

**Comment by 8bitPit** [comment]
@Chaphasilor When you click near the edges of the screen you begin to scroll.

**Comment by 587saboor** [comment]
@8bitPit swipe down from favourites?

**Comment by 8bitPit** [comment]
That's an option

**Comment by jakcharvat** [comment]
Or even double finger swipe up

**Comment by Maxr1998** [comment]
Google Now Feed is kinda dying, seemingly. I'd appreciate if it could be possible to just have a button/gesture to launch the new discover feed in Google Assistant.

**Comment by 8bitPit** [comment]
@jakcharvat that doesn't go well with the idea of using the launcher with one hand

**Comment by jakcharvat** [comment]
@8bitPit I get that, but we're sort of running out of possible one handed gestures here. @Maxr1998 I know not many people use now feed any more, but I still love how it is curated to my liking, and currently keep it as my main news source. I like having it one swipe away. If you implement that FAB for search Peter, then maybe long pressing it could be a customisable gesture, including the possibility for Google Now?

**Comment by 8bitPit** [comment]
Long pressing is a good idea. Must it be the now Feed? I don't really get the the difference between it and the google app.

**Comment by 8bitPit** [comment]
Great! So would So would you mind if I'm just including the Google search button at the bottom right? The google app is way faster & easier to implement.

**Comment by 587saboor** [comment]
@8bitPit ye no problem at all, as long as it has news  im ok with it

**Comment by jakcharvat** [comment]
Sure. Keep doing what you're doing @8bitPit, you're doing a great job!

**Comment by 8bitPit** [comment]
Thank you 😃

**Comment by pablomeza10** [comment]
Would it be possible to add the Google Search widget on the main screen?

**Comment by 8bitPit** [comment]
@pablomeza10 do you mean a widget from another app? That's currently not possible. However, I will test either a button at the bottom right or a swipe up gesture to launch the Google app.

**Comment by cauerego** [comment]
why is this still open?

**Comment by 8bitPit** [comment]
@cauerego it's open because Google Now integrated yet, but I have currently no plans to support it.

**Comment by Saucerpan** [comment]
I believe the swipe notification opening gesture should be replaced with holding down on the application, and the settings for the shortcut will open once you keep holding after the notification window appears. This is because I think the swipe on the app gesture isn't the best for one hand usage and because the shortcut settings opens too easily. This opens up the possibility for Google feed integration which is one of my favorite things to have in a launcher. I used Google feed on action launcher before and it to me has become something that I use daily. I know you can just open up the Google app to view the feed but I really doesn't work out for me. There's quite a bit of extra loading time as well. Having the feed just a swipe away from the home screen is the best option in my opinion.

**Comment by 8bitPit** [comment]
@Saucerpan a long press is way slower to execute though. But the feed could be opened with another gesture.

**Comment by Saucerpan** [comment]
This is understandable. I just was thinking that most other launchers that have the option to view notifications on the app shortcut share this same gesture. I suppose if the swipe gesture for the notifications is acceptable. I was thinking you could possibly implement another page that would be accessed by swiping from the right. This page would feature a traditional launcher grid with support for widgets. This is where the user would store their secondary most used applications. Yeah, usually have two categories of apps, apps that I use most often and apps that I regularly use but arent important enough to add to my favorites. So having three horizontal pages with a feed page and a widgets/shortcut grid page.

**Comment by colbycdev** [comment]
Please, please, please bring this to Niagara. It's the shortfall of man a launcher. Be better than all the others!

**Comment by Jeffrey04** [comment]
Can we have swipe right to get to google now, and long press (instead of swiping right on the app/notification) to have shortcut/actions? This is because I didn't know swiping right is for the shortcuts/actions until I start reading this issue (:

**Comment by 8bitPit** [comment]
I thought about integrating Google Now and I decided not to implement it for now for the following reasons:
-	The swipe right gesture to open it wouldn’t fit for Niagara
-	Google doesn’t want other apps to use it, so you would have to make or take use of a second apk which is not very user friendly 
-	The feed could have a negative impact to the app’s performance
-	It would cost a time to develop & test it (that applies to a lot of features, but should be kept in mind anyway)
-	The Google app has the same feed build in their Google app. Just adding the G-button to your homescreen and tapping it when you want to browse the feed is a much simpler and imo, more elegant solution.

**Comment by Methotrex8** [comment]
Have you considered adding an icon in the alphabet for the Google Feed? That solves the lack of 1 handed gestures being limited.

**Comment by 8bitPit** [comment]
@Methotrex8 I fear that opening the app by letting go the scrollbar could feel odd. That's why I added the G-button instead.

**Comment by YuriAzael** [comment]
The launcher is pretty good.  By adding more options to customize folders and icons, including startup, also adding an effect while scrolling through the alphabet in search of apps.  More customization should be added, and adding more widgets, apart from Google News Feed, would facilitate user convenience even by adding a Google search bar.  Excellent launcher, thanks.
#AddingGoogleFeed
>
