### ISSUE TITLE
Custom Google button behaviour

### ISSUE THREAD

**Issue by rituraj22** [8bitPit/Niagara-Issues#300]
I would love to launch a custom app from the google fab button, as I often need to locally search for files using fast finder. 
Just adding an option to launch custom app from the button with maybe a generic search icon would be awesome.

**Comment by 8bitPit** [comment]
Yeah, good idea

**Comment by 8bitPit** [comment]
By the way, being able to bind the button to a folder or widget would also be nifty.

**Comment by 8bitPit** [comment]
Implemented with the new Niagara Button: https://help.niagaralauncher.app/article/116-niagara-button
