### ISSUE TITLE
Search by partial string match with app names 

### ISSUE THREAD

**Issue by ShinobiWPS** [8bitPit/Niagara-Issues#301]
The current behaviour when I search for  "launcher" word is :not found

The ideal behavior would be to search for "launcher" and get: Niagara Launcher (also case insensitive).

I think from a programmig point of view this is achievable quite easily. It provides a better experience and usefulness of your launcher with a little change. 

What do you say?

**Comment by 8bitPit** [comment]
substring search is already integrated, it's also case insensitive :) Niagara just doesn't show up there, since you are in the launcher already.
