### ISSUE TITLE
Show media widget even if the song is not playing

### ISSUE THREAD

**Issue by evetesla** [8bitPit/Niagara-Issues#3024]
### Is your feature request related to a problem?

Sayangnya opsi ini masih belum ada

### Describe the solution you'd like

Create an on/off option so users can choose between wanting the media widget to always be there or not. I myself want widget media to always be there. Hopefully this can be implemented.

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for your suggestion.

Could you please elaborate on why you want this kind of behavior?

If you want quick access to music apps, we recommend selecting music apps so that they appear whenever you connect speakers or headphones to your device.
