### ISSUE TITLE
Custom Accent Color 

### ISSUE THREAD

**Issue by d02d33pak** [8bitPit/Niagara-Issues#303]
To be able to edit the accent color (like on search fab etc)

**Comment by 8bitPit** [comment]
Good idea.

**Comment by Danjcb** [comment]
Yeah, at the very least have it match the theme, white or black

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
