### ISSUE TITLE
App overview button problem 

### ISSUE THREAD

**Issue by gurken00** [8bitPit/Niagara-Issues#3036]
### Describe the bug

Hello, 

I have a problem with the app overview button not working. I reported this problem, but I canceled the report because the button suddenly started working. However, I've been watching the launcher work for a few days now, and I've been experiencing this problem several times a day. The only thing that helps is to disable the niagara launcher, use the Pixel's default launcher and turn the niagara launcher back on. 

Translated with DeepL.com (free version)

### Steps to reproduce

Go to home screen
Click app overview button 

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Device name

Google Pixel 9 Pro 

### Android version

Android 15

**Comment by TFackler** [comment]
Thanks for reporting this issue.

Could you please check whether the issue also appears on other 3rd party launchers like [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en_US) or [Lawnchair](https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah&hl=en_US)?

Possible workaround are force-stopping the preinstalled launcher and switching to gesture navigation.

Please keep me updated.
