### ISSUE TITLE
Icon consistency 

### ISSUE THREAD

**Issue by saurabhserv** [8bitPit/Niagara-Issues#3038]
### Is your feature request related to a problem?

![Screenshot_2024-11-29-12-52-22-67_99c04817c0de5652397fc8b56c3b3817](https://github.com/user-attachments/assets/c5dd3061-a555-4b6f-9515-caac82b0bc99)
![Screenshot_2024-11-29-12-48-10-42_a4824db61f40c53807964ea8b14c92fe](https://github.com/user-attachments/assets/2e3f2531-adeb-4279-af4f-3fc955390b1b)

### Describe the solution you'd like

Make icon like Microsoft launcher in default 

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
Thanks for letting us know about this inconsistency.

Sadly, these icons are supplied to us by the system, and thus, we cannot change them to look the same as in the Microsoft launcher.

We recommend using a third-party icon pack of your liking instead. You can find a lot of free ones on the Play Store.
