### ISSUE TITLE
I want add my personal icons

### ISSUE THREAD

**Issue by 900RH4F3Z** [8bitPit/Niagara-Issues#3042]
### Is your feature request related to a problem?

Yes why not expecting my icon, s

### Describe the solution you'd like

Sir plz hlep

### Feature Request Procedure

- [X] I have read the [knowledge base article on feature requests](https://help.niagaralauncher.app/article/44-feature-requests) and followed the steps mentioned

**Comment by TFackler** [comment]
You can apply third-party icon packs you downloaded from the Play Store ([Third-party icon packs on Google Play store](https://play.google.com/store/search?q=icon%20pack&c=apps&hl=en)) by going to Niagara settings > Look > App icons > find them under the subheader called "installed icon packs", then select it and follow the on screen instruction.

If you are talking about something else, please elaborate.
