### ISSUE TITLE
Can't show weather!

### ISSUE THREAD

**Issue by anshulkapoorr** [8bitPit/Niagara-Issues#3050]
### Describe the bug

![Screenshot_20241208-141323](https://github.com/user-attachments/assets/d61e526d-0da3-4348-b46c-bcf63af1b1ed)

### Steps to reproduce

![Uploading Screenshot_20241208-141323 (1).png…]()

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Other 3rd-party launcher(s) tested

No

### Device name

Realme Narzo N53

### Android version

Android 14

### Screenshots / Screen recordings

![Screenshot_20241208-141323 (1)](https://github.com/user-attachments/assets/b0fbb499-7973-4a2c-8c07-4d2fb162f59d)

**Comment by TFackler** [comment]
Please reach out to our support at [support@niagaralauncher.com](mailto:support@niagaralauncher.com).
