### ISSUE TITLE
One handed mode - Option to pull down the app drawer / favourite list to bottom half

### ISSUE THREAD

**Issue by prsntg** [8bitPit/Niagara-Issues#307]
An option to enable one handed mode where if you pull the favorite list (and app drawer) down after already reaching the top of the list, it moves down to the bottom half of the screen. 

A smooth elastic animation would make it look cool. Something like - Just swipe down and it comes down and moves up to original position like an elastic band. Swipe down and hold then the list locks in bottom half. And back button to release the list back to top of the screen? This would make the launcher truly one handed. 

I know this will interfere with pull down for notification gesture. But as already discussed in other threads, if apps with notification are automatically added to favorite list, pull down for notification may not be a necessary option. Please think about this or any other idea you may have to introduce a one handed mode to this launcher.

**Comment by 8bitPit** [comment]
There should already be enough whitespace at the top, so you can reach your apps easily. Furthermore, there will be an option to adjust it for your needs, see: #112

**Comment by cauerego** [comment]
in my 5.5 screen with my 9ish hand, there isn't.

and i still would want notification pull down... at least until i can get pie accessibility button.

i was going to suggest exactly this just now, lol. thankfully, remembered to search first. dam GitHub lack of auto dupe prevention!

another idea would be to also ordering from bottom to top.

**Comment by 8bitPit** [comment]
> in my 5.5 screen with my 9ish hand, there isn't.
can you please provide a screenshot?

> and i still would want notification pull down... at least until i can get pie accessibility button.
You can pull down the notification tray already, just try swiping a bit faster

> another idea would be to also ordering from bottom to top.
Tried that, but doesn't look good.

**Comment by cauerego** [comment]
you mean a photo with my hand holding it and being unable to reach it? if that's so, picture the hand holding position in different situations and people's different grips (even with same sized hand).

pulling down fast doesn't work always or anywhere reliably enough. it's quite annoying in my experience.

how about making it always work when it's already all way pulled down? i.e. the apps can't go up anymore, which is the default behavior of the home button anyway. (was this suggested already? couldn't find it)

i'd still love to see the bottom-to-top ordering. #249 

but pulling down the apps like suggested in here, or even further away until the first app on the top is touching the bottom of the screen, would come first for me! :)

this would conflict with the previous suggestion, but i'd be fine to access the notification with a home button -> swipe down to bring apps to the limit -> swipe again for notification.

not to mention that the quick swipe notification as it is today can surely stay. if it works for others, i dun care.

**Comment by 8bitPit** [comment]
> you mean a photo with my hand holding it and being unable to reach it? if that's so, picture the hand holding position in different situations and people's different grips (even with same sized hand).
Was more interested in seeing the amount of whitespace at the top XD

> pulling down fast doesn't work always or anywhere reliably enough. it's quite annoying in my experience. how about making it always work when it's already all way pulled down? i.e. the apps can't go up anymore, which is the default behavior of the home button anyway. (was this suggested already? couldn't find it)
Here is a related issue: #362. Btw the swipe down already works if you are at the top or are scrolling to the top.

**Comment by cauerego** [comment]
still not sure how this can help, but there you go: https://photos.app.goo.gl/4VJRGYqVrURaQHYt9

**Comment by 8bitPit** [comment]
Btw, you can now adjust the launchers top padding: https://github.com/8bitPit/Niagara-Issues/issues/112.
It's not exactly what you requested originaly, but I think it solves the problem without introducing another gesture which would interfere with the swipe-down-to-open-the-notification-shade gesture. Feel free to open the issue again if you disagree.
