### ISSUE TITLE
Media Player showing up mistakenly

### ISSUE THREAD

**Issue by Antoine95280** [8bitPit/Niagara-Issues#309]
When i receive a notification from a favorite app, music control widget displays by it self

**Comment by 8bitPit** [comment]
Which app is it? Can you please provide me a notification log when that happens again? (Niagara settings > Advanced)

**Comment by Antoine95280** [comment]
That's Skype

**Comment by disacrol** [comment]
+1
Whenever I have a chat message notification from Skype, music widget pops up, no artwork or text, just the controls, which do not perform any action.

**Comment by xRayJiN** [comment]
I've the same problem when i download something through firefox nigthly. It doens't happen with google chrome, dunno about other launcher.

**Comment by 8bitPit** [comment]
@xRayJiN & @disacrol does the player still open accidentally?

**Comment by xRayJiN** [comment]
@8bitPit yes, only on Firefox nightly btw

**Comment by 8bitPit** [comment]
@xRayJiN which version of Niagara do you have installed? (You can go to Niagara's settings > Advanced to check that.)

**Comment by xRayJiN** [comment]
@8bitPit latest one from telegram, v. 0.7.8a3

**Comment by 8bitPit** [comment]
Thanks, I could also reproduce the issue on the latest version, I'll keep you updated.

**Comment by 8bitPit** [comment]
This bug should have been fixed in version 0.8. Please contact me if I'm wrong.

**Comment by disacrol** [comment]
@8bitPit I stopped using Skype, but I'll let you know if this occurs with any other app in the future.

**Comment by 8bitPit** [comment]
Thanks @disacrol
