### ISSUE TITLE
[Feature Request] Two-finger swipe down for app search

### ISSUE THREAD

**Issue by michalsukupcak** [8bitPit/Niagara-Issues#311]
Hi,

Tiny suggestion I thing would be cool: Since the launcher is IMO gesture-heavy, which I really like, the ability to swipe down with two fingers anywhere (either in favorites or in app list) to quickly open app search would be pretty neat.

(I know there's already the option to tap the home button to initialize app search, still this option would still fit pretty well.)

**Comment by pradyw** [comment]
It's neat, but not one handed use friendly.

**Comment by 8bitPit** [comment]
Sorry, as @pradyw pointed out, this would go against Niagara's principles.
