### ISSUE TITLE
[Minor Tweak] Rounded corners for album art image

### ISSUE THREAD

**Issue by michalsukupcak** [8bitPit/Niagara-Issues#316]
Hi, 

Maybe you could consider adding small rounded corners to album cover art image on homescreen when music is playing? Nothing excessive, something to the equivalent of 3px border radius on the web (ie. text inputs here on Github). Nearly everything else in the launcher's UI is a circle or at the very least rounded (google button, music controls, all the dialogs and overlays and even most app icons nowadays - I even use Cornerfly to round the phone's corners:) and very neatly animated, so the sharp square image feels a bit out of place:

![](https://lh3.googleusercontent.com/7AB5AOCctJoY6FIjrpGq00XWNF8p99JpRiJkntoFx8NJuLgPFzBl7NspWFiXvKXjLO5VCEFR_3ZgguX_dQ1r2DZFWqZGLJqa4CNRoyNhn6A6xIlqBPKEXRIMrTD1tEfnD9VPsReCeihBxJ-q-Sf4Rm0npEU_vkallb7t4C_zwNw7Askk0KEti8AL3W1B8Nfucoz5jCI9cKhjrJhu4JK8mwd2auULiFBhSETplOhcnwbjl33EwczwKyTGNawIeRQ3LOBJ-5N317uAecQXvjdUhNwIhlQ-yljA-104vhyiV5rZBtqqXGwbWc4FN3XTX1p84z3RDI-TKfuQVK_dl5F74xrLbRx7B_B8D58TuIiQafKqnv1Q0mt3lhZJXlxhuYBNtjemYqnyiKk4cOwZCM0xOlUFNDDJKn5vrksUBchjVh49VJHF5rqSKbk7Rn3NOdEOrrYn5brgB1V9NrZnN03GEPfacUtoW2hQwSncElIS_cqbi6LsiyUkSHtZVi3wK5lbg0Afx4jWxL1Ac9NUXxl8hFKdMcq_XLH4lD8GL0KJ3zO6rKF29z96HpWaqjCS9uYB3Q4R2Bl1XQMU5VltxXN1crQyeKJG268Fdpg_siIAJQsF62EDGEfqVRnkxVNJdIU9=w574-h1020-no)

**Comment by 8bitPit** [comment]
Hey, reposted your issue in #18
