### ISSUE TITLE
Divider/Separator for frequently used apps

### ISSUE THREAD

**Issue by pradyw** [8bitPit/Niagara-Issues#318]
Make saperation line optional or small.

**Comment by 8bitPit** [comment]
maybe I'll tweak it.

**Comment by 8bitPit** [comment]
The divider is for differentiating favorites & most used apps, so you can see which apps are movable, hiding it could be confusing.

**Comment by sangampandasp9** [comment]
Ya really most of them are reporting to bring it back!!
So it's better to make it optional 
Isn't it @8bitPit

**Comment by sangampandasp9** [comment]
Ya really I am like a user as @disacrol has stated
I use telegram and Instagram on my daily basis but don't and never keep it in the favorites place as I don't want to keep it there 

But it's something like a different feeling to divide them by a divider as it's all done by Niagara !!
So personally to be honest, I really don't have any objections about the divider 
But it were some users who were constantly reporting in the Niagara discussion group 
So we both just wanted to bring that forward to here


But ya we all really don't want it as you( @8bitPit ) stated that it's a buggy thing to  have it there 
so.....

**Comment by 8bitPit** [comment]
Thanks for your comments guys. I agree, some changes should be made.
I also thought about a smaller divider, but I’m still unsure if it is needed at all. I got the feeling some people only disabled / limited suggestion, because they got annoyed by the divider.
Btw, adapting the dividers length to the text field widths would be quite painful to achieve in Android XD

**Comment by disacrol** [comment]
I suspected that 😁 well anyway some sort of center-aligned divider, even if small, would be great to be able to enable as an option

**Comment by sangampandasp9** [comment]
👍🏼👍🏼

**Comment by pradyw** [comment]
Or may be just a little gap bet'n favourite & suggestions.

**Comment by usakuja** [comment]
seperation line concept was very clean.
now if i want to change alignments of my apps.like i want to keep it at the last.it cannot happen as i cannot send it below suggested apps.nor is there line divider to make two first and two last apps

**Comment by venugopaljd** [comment]
I would suggest one of the below solutions:
1. Provide a swipe up gesture which will populate the recommended/frequently used apps (Similar to the swipe up gesture which populates the app drawer in launchers like Microsoft launcher).
2. Provide a button similar to the Google button which would provide access to the recommended/frequent apps.
3. Provide a blank line followed by a separator below which the recommended/frequent apps are populated.

**Comment by 8bitPit** [comment]
@venugopaljd sorry for my late reply. I have two concerns about 1. & 2.: 
>Additionally, suggestions are meant to save you one tap, so to my mind they make more sense below that. Moreover, the user never knows what Niagara suggests him, so many wouldn't even scroll to the most-used-category, because they don't know if they find the app they want to open there.

(taken from: https://github.com/8bitPit/Niagara-Issues/issues/971)

**Comment by 8bitPit** [comment]
With the "new" edit mode, I believe suggestions are getting explained and differentiated pretty well. I think the divider is neither needed nor requested by many anymore. That's why I'm closing this issue.
