### ISSUE TITLE
Calendar/Agenda Page

### ISSUE THREAD

**Issue by giasonasT** [8bitPit/Niagara-Issues#319]
Similar to the Star/Favourites landing page, you could add a page with a calendar icon that would function as an agenda showing upcoming calendar events (with options for future lookahead - 1 day, 1 week, 2 weeks etc)

For reference, [this](https://imgur.com/a/qN2knSI) is an agenda widget I tend to use via the Chronus app. I think a similar style would fit nicely with Niagara

A separate landing page for the agenda will still keep the clean look and add even more functionality to this wonderfully minimalistic launcher. 

Keep up the good work

**Comment by Scorpionk1** [comment]
Scrolling is the difference of the launcher. Certainly, the use of resources implemented as: agenda, alarm, masses, widget, would make this mechanism with a much more differentiated hand.

**Comment by Scorpionk1** [comment]
Scrolling is the difference of the launcher. Certainly, the use of resources implemented in this "roll" like: calendar, alarm, mass, widget, would make this mechanism with a much more differentiated hand.

**Comment by Shakira786** [comment]
Love the idea of an agenda / calendar page. I get that the idea is to be minimalist but I'm sure it could be designed not to be like every other launcher out there... Ooh or it could be something simple as a widget on the corner etc... Not sure if that sounds intelligent enough 🙈

**Comment by 8bitPit** [comment]
I will implement an "at a glance" widget, maybe a long press / swipe gesture could bring up more details

**Comment by giasonasT** [comment]
> I will implement an "at a glance" widget, maybe a long press / swipe gesture could bring up more details

I appreciate this!

That being said, I can still tap on the date which takes me to the calendar app for my agenda

Keep up the good work

**Comment by Shakira786** [comment]
Ooh that would be awesome too. Thank you for the response and the amazing
launcher. Definitely better than what's out there at the moment.


Shakira

**Comment by jakcharvat** [comment]
Perhaps swiping right on the at a glance could bring up the same menu it does for app shortcuts, only it would show the calendar stuff

**Comment by 8bitPit** [comment]
Thanks @Shakira786  & @giasonasT

**Comment by 8bitPit** [comment]
@jakcharvat yup, that would fit.

**Comment by Bartvz** [comment]
Bb b TV y__

**Comment by bcdiaconu** [comment]
I am for it too. Something similar to what Windows phone used to have as left is for widgets (tiles were on wp) and right for apps. Than one could choose which screen to start in. And of course a good widget for calendar and to-do.

**Comment by 8bitPit** [comment]
Implemented in v0.32
