### ISSUE TITLE
Net location should be sufficient for weather

### ISSUE THREAD

**Issue by RobVanBrunschot** [8bitPit/Niagara-Issues#320]
Hi, I noticed the GPS is requested for the weather location and this is not on normally.
Please use the Net location for the weather information because that location should be accurate enough, in that case GPS itself is not necessary. 

I further love your launcher, great work!

Regards, Rob

**Comment by Scorpionk1** [comment]
Disables the weather forecast and checks the forecast on google. Simple!

**Comment by RobVanBrunschot** [comment]
That is not helping very much.
I know I can do that but I like the weather info, only the use of GPS is not needed.
Google also does not need GPS.

**Comment by Rod911** [comment]
The developer uses Google awareness API which apparently consumes very little power to provide weather info and other user information. And yes it requires GPS to be enabled.

**Comment by RobVanBrunschot** [comment]
If that is the situation, it is to bad.
Especially Google should not need GPS because all info needed to find out where the device is must be already available.

**Comment by 8bitPit** [comment]
Yup, @Rod911 is right, there is not much I can do. I only could use another weather provider.

**Comment by Rod911** [comment]
Closing because it's similar to #179
