### ISSUE TITLE
develop a component that will work even if the launcher is not the active app

### ISSUE THREAD

**Issue by sfosdal** [8bitPit/Niagara-Issues#324]
I've found myself loving the quick access your launcher provides to the alphabetic list of apps.

It's so natural to me that I'd I've tried to use it while in other apps.

Could there be component to Niagara that would enable this?

It would be a very nice app switcher.

**Comment by Scorpionk1** [comment]
If it were possible for Niagara to have the function of becoming a "floating bubble"
