### ISSUE TITLE
Widget page

### ISSUE THREAD

**Issue by Shakira786** [8bitPit/Niagara-Issues#326]
I think a widget page with your reminders etc which helps me alot with work, would be awesome.

**Comment by rastamanjohn** [comment]
And how would you access that? Up, down, right and left swipes are already in use...

**Comment by stuartglossop** [comment]
Yeah a page just for widgets! Swipe over to the left like you would with the Google feed. Just for widgets and nothing else

**Comment by Scorpionk1** [comment]
Just decrease the number of favorites available from 8 to 4 at the most. There will be enough space left to include the widget.

**Comment by Scorpionk1** [comment]
Just decrease the number of favorites available from 8 to 5 at the most. There will be enough space left to include the widget.

**Comment by Scorpionk1** [comment]
People are not understanding the logic of Niagara. The developer will not list a new page. The home screen will be exclusive!

**Comment by tuur29** [comment]
Maybe something like [Action launcher's shutters](https://lh3.googleusercontent.com/GPoYijq-4CKQ-JnO83YssB_1QjZICAAztBOFhv_R9wP9kEhsf1N4Pg0b9Z6dvk9fV-F6=w1774-h955-rw)? Swiping to the left on an app could open a popup with that app's widget. Maybe a page in the settings that allows you to add custom shortcuts to the list which opens a chosen widget.

**Comment by Scorpionk1** [comment]
> Maybe something like [Action launcher's shutters](https://lh3.googleusercontent.com/GPoYijq-4CKQ-JnO83YssB_1QjZICAAztBOFhv_R9wP9kEhsf1N4Pg0b9Z6dvk9fV-F6=w1774-h955-rw)? Swiping to the left on an app could open a popup with that app's widget. Maybe a page in the settings that allows you to add custom shortcuts to the list which opens a chosen widget.

The action launcher's shutters are suitable for the Niagara. It's the most efficient way to assign widget!

**Comment by rastamanjohn** [comment]
> Just decrease the number of favorites available from 8 to 5 at the most. There will be enough space left to include the widget.

5 apps on a homescreen is quite useless imo

**Comment by Scorpionk1** [comment]
> > Apenas diminua o número de favoritos disponíveis de 8 a 5 no máximo. Haverá espaço suficiente para incluir o widget.
> 
> 5 aplicativos em uma tela inicial é imo inútil

The most commonly used applications to fill the list of favorites would not be useful. Dumb!

**Comment by rastamanjohn** [comment]
> > > Apenas diminua o número de favoritos disponíveis de 8 a 5 no máximo. Haverá espaço suficiente para incluir o widget.
> > 
> > 
> > 5 aplicativos em uma tela inicial é imo inútil
> 
> The most commonly used applications to fill the list of favorites would not be useful. Dumb!

So you'd prefer having in your favorites apps you never use??? I don't get you

**Comment by 8bitPit** [comment]
> Maybe something like Action launcher's shutters?

@tuur29 had the same thought. Imo it would fit well.

**Comment by 8bitPit** [comment]
Please visit #117 for further discusion.
