### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Beautyx98** [8bitPit/Niagara-Issues#328]
I used the app for an hour and I'm so pleased with this app it's differently in nice way, but you need to make the animation better (slowing it down)
And i wish if there is an option for ordering apps in type instead of alphabet (alphabet is good but like an other option if you want to) 
Ps:I'm using my oneplus 5t on Android 8.1

**Comment by lepa22** [comment]
Well, you can just press the home button to search for apps.

**Comment by 8bitPit** [comment]
Slower animations would get boring really quick. For folders / categories, look at #13
