### ISSUE TITLE
Direct app launch (feature request)

### ISSUE THREAD

**Issue by HotLittleDad** [8bitPit/Niagara-Issues#331]
I love the simplicity of the home screen and being able to just jump into the app drawer fluidly. Would it be possible tho to launch an app from the list without having to lift the finger? Like an invisible divider where you start swiping for the letters on the right and then, when you've got the letter you're after, you switch to the left, choose your app, release your finger and launch the app. All in one "swipe"

I tried showing what I mean here. The dial appears normally, but when you move too far left...
![screenshot_20181003-110232_niagara launcher](https://user-images.githubusercontent.com/43808664/46401815-58e20380-c6fe-11e8-83ab-ce83b21d2d50.jpg)

(excuse my mock up)... you jump into app selection where, upon lifting the finger, that app is launched
![screenshot_20181003-110826_niagara launcher](https://user-images.githubusercontent.com/43808664/46401818-5c758a80-c6fe-11e8-944a-464a02a3f626.jpg)

Personally I would also like an option to close the app drawer once an app is launched (so that when the app is closed you're back at favorites and not at the letter I left off)

**Comment by jakcharvat** [comment]
Hi. I like your idea regarding the quick app opening. I believe it was discussed earlier and received generally positive feedback. As for your second request (the returning to favorites) that is on by default in the newest build 😉

**Comment by HotLittleDad** [comment]
Maybe I should check for updates 😬 thanks for informing me about the returning to favorites!

**Comment by 8bitPit** [comment]
@HotLittleDad can you please repost your mockups here: #162 Thanks in advance.
