### ISSUE TITLE
Password For Hidden Apps

### ISSUE THREAD

**Issue by alicagatay** [8bitPit/Niagara-Issues#332]
In my opinion, it will be safer if you add a password authentication for hidden apps, and I think you should hide hidden apps in the search bar. (For example, the user should not be able to find a hidden app just by searching its name. )

**Comment by 8bitPit** [comment]
The feature is designed for hiding bloatware, not for security reasons. You can use a locker app, like MaxLock for password protection.

**Comment by markr1955** [comment]
Most other launchers require confirmation before accessing hidden apps. Apparently, hiding bloatware is not necessarily the primary reason to hide apps. If that is the reason you have included it in the app, then you should include a disclaimer that the user should not consider using the features to hide sensitive apps. Using a locker separately is confusing, adds another layer to accessing applications and often requires creating another passcode to remember.

**Comment by 8bitPit** [comment]
A launcher cannot hide apps entirely though, e.g. they still appear in Android's settings and you can launch them with another launcher. So in my opinion a screen lock adds only a pseudo layer of security.

**Comment by morais300** [comment]
The hide apps feature is good, but it would look even better if you had the option of blocking applications with error limit when typing the password.

**Comment by paijojo** [comment]
this is important. don't just password for hiden application. 
But add also the application lock feature with a password, then Niagara launcher will be the number 1 best launcher in the world.

**Comment by paijojo** [comment]
It is too slow development.
see and follow all the input I gave, then you will finish quickly well.

**Comment by laggingreflex** [comment]
I agree with @8bitPit, I too only expect this to hide bloatware and/or uninstallable and unneeded system apps (like default camera, messaging, SIM related apps). Though still be able to find them through search when needed once a while. Hiding them permanently might cause unnecessary nuisance. 

As for passward protection and other securty features, again, I think a launcher may not be the best place to look for those. I personally wouldn't even trust a launcher (alone) for that purpose. There are much better and fool proof ways to hide apps designed specifically for that purpose.
