### ISSUE TITLE
Folder in favorites + icons

### ISSUE THREAD

**Issue by HikariKobushi** [8bitPit/Niagara-Issues#333]
I was thinking about favorite home screen and I had a feeling that option to add folder to favorites page would be great idea. I would say choosing 7 apps + 1 folder would still keep it neat and tidy but add more choices for the home screen. What do you guys think?

**Comment by rastamanjohn** [comment]
I wish people would search before opening new issues. This has already been requested a dozen times #13

**Comment by HikariKobushi** [comment]
I am sorry rastamanjohn. I did search for it but I did not find it. Maybe was requested few weeks ago but I am not going to spend an hour to search for it.

I am with you I don't like to read same thread multiple times and I will do better search next time or won't request anything new... Depends on time that I have.
