### ISSUE TITLE
Contact integration into Launcher

### ISSUE THREAD

**Issue by prsntg** [8bitPit/Niagara-Issues#336]
Any plans to integrate Contacts into this launcher? What I was thinking is to have a 'contact mode' where favorite page will display favorite contacts (with option for direct call/message with swipe gestures) and a swipe will activate all contacts in the same alphabetical scrolling style as in app drawer.  And some gestures to get into 'contact mode' and come out of it to normal 'App mode'?

**Comment by 8bitPit** [comment]
When "legacy" shortcuts (#62) are implemented, you can add as many contacts as you want to you app list or your favorites.

**Comment by prsntg** [comment]
Yes, I get it. But there are launchers that include a mini Contact app within (just listing the contacts and making calls, no dialing or editing). And this launcher UI is very suitable for a great contacts handling.

**Comment by 8bitPit** [comment]
Maybe it would be good if shortcuts appear in the search as well.

**Comment by berdzena** [comment]
Might be best solution to add swipe down on google button to open personal search in google app

**Comment by tduyduc** [comment]
I would like a contact search feature, which can be the same place as (app) search function à la Smart Launcher 3. When the search function is invoked, the launcher searches for both apps and contacts (if the user grants Android permission). Tapping a contact makes a call. Tapping and holding a contact launches a contact information page.
![screenshot_20190110-105527_smart launcher pro](https://user-images.githubusercontent.com/15998902/50945332-cacca480-14c6-11e9-9cf2-c6776b489ae2.jpg)

**Comment by berdzena** [comment]
Would be great.. Thats only one thing i miss in NL

**Comment by 8bitPit** [comment]
This will be possible with Sesame, once the app is integrated: #88
