### ISSUE TITLE
Feature request: Possibility to completely disable "Most used apps" section on home screen

### ISSUE THREAD

**Issue by RadCraftplay** [8bitPit/Niagara-Issues#337]
Currently users can only limit amount of "Most used apps" shown on home screen. Some of them would like to be able to disable all recommendations, and see only favorite apps on their home screen

**Comment by pradyw** [comment]
Duplicte to #204

**Comment by 8bitPit** [comment]
You can long press every app you don't like to see and click on "don't suggest" to hide it.
