### ISSUE TITLE
Customizable Clock / Clock font

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#34]
If you know some cool fonts, let me know! They have to be 100% free to use, though. [Like those (Google Fonts)](https://fonts.google.com/)

**Comment by jakcharvat** [comment]
Product sans would be great, unfortunately not officially available 😞 Although Action Launcher and Material Notification Shade have it and they're in the play store, so maybe it is possible, don't know for sure.

I'd love to see the whole launcher support Roboto, Roboto Condensed and Roboto Mono.

**Comment by 587saboor** [comment]
@8bitPit i can send you all the fonts dedicated to product sans if you want me to

**Comment by 587saboor** [comment]
@jakcharvat power shade, material notification shade have it

**Comment by 8bitPit** [comment]
I believe, that there is a 100% free font as well, that just looks like open sans for digits. All those other chars don't matter.

**Comment by jakcharvat** [comment]
in my opinion the ability to customize the font of the whole launcher would be nice for consistency, so a don't with please numbers wouldn't do the trick.

**Comment by 8bitPit** [comment]
You're right, forgot about AM/PM. Custom fonts usually include only Latin letters and numerals, so applying the font to the whole launcher may be problematic.

**Comment by DroidFreak32** [comment]
I think Ubuntu monospaced fonts would be good too!

**Comment by Sacchid** [comment]
Here are some cool fonts (ttf &/ otf) - 
https://drive.google.com/folderview?id=1w9lHcbeo7BccLZUEznKNYzGrG5laCIhM

**Comment by 8bitPit** [comment]
@Sacchid Thank you. Are they 100% free to use?

**Comment by 8bitPit** [comment]
I searched for minimal geometric fonts, like product sans, I didn't find any good one though (which is free to use).

Product sans:
![image](https://user-images.githubusercontent.com/9284845/45439780-02fbdc00-b6bb-11e8-8d7e-ede4a3c7c384.png)

Roboto (Android's default font):
![image](https://user-images.githubusercontent.com/9284845/45440211-f62bb800-b6bb-11e8-873d-22368522d3c1.png)

Please let me know if you've got a hot tip!

**Comment by Sacchid** [comment]
@8bitPit, 
Here's the libery of more than 300 OFL fonts - [https://fontlibrary.org/en/catalogue](url) 
The open font licence - [https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL](url)
The SIL Open Font License (OFL) is a free, libre and open source license specifically designed for fonts and related software based on our experience in font design and linguistic software engineering......

**Comment by OverRidingSky** [comment]
And if all fails, maybe "add font" button?

**Comment by 8bitPit** [comment]
Custom fonts are now supported, but for now, you cannot only change the clock's font: #191

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.

**Comment by wimstefan** [comment]
As suggested in #2026 I'm asking if it is possible to open that issue again and see if it is possible to offer a customizable clock font ...

**Comment by 8bitPit** [comment]
@wimstefan I reopened the issue, and we're reconsidering if custom clock fonts / a customizable clock makes sense.

**Comment by wimstefan** [comment]
> @wimstefan I reopened the issue, and we're reconsidering if custom clock fonts / a customizable clock makes sense.

That's great news 😃
Thank you so much for reconsidering this issue 🙏

**Comment by 8bitPit** [comment]
Added in our second Weeks of Winter update, v1.10.7 🎈 
Man, that was an old issue; glad we can finally cross it off our to-do list!
[Link to the release](https://github.com/8bitPit/Niagara-Issues/releases)
