### ISSUE TITLE
about incentives and simplicity: a hello from cregox

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#346]
#345 praise being said...

i'll eventually add more issues and list them here by editing this soon... if you don't mind.

above all issues i see, there's one: incentive.

the cool clean UX says "keep it simple, stupid. let's minimize" however being able to effortlessly add apps will bring the opposite incentive - to keep adding apps at will.

i've recently moved away from 250 ish apps down to 50 ish. and i don't regret it.

#newissues #sidenote even with this little amount, the current design is still limiting in at least 2 ways: too many apps start with P, and; can't add simple widgets, such as map friend location, which is one of my favourites.

anyway, back to the incentives...

one way to change this is by making a "trashy apps" separation when seeking for apps, for those we're going to install and forget. that could be simply cleaned with a single button. this is different from "apps not in the home screen" because there are lots we use without needing to activate them.

in my experience, the magic number of apps to keep in my home screen is around 30. and this is yet another contradictory factor in Niagara... while simple, it doesn't really favour my simplification.

keep it up, can't wait to see the final release! ;)

cheers!

**Comment by 8bitPit** [comment]
Thanks @cauerego, widgets will be implemented (#117). Furthermore, you can hide your apps already and still access them by Niagara's search.

**Comment by cauerego** [comment]
true, I saw that feature. but it can send an opposite message and, thus incentive. those are either important apps we want to hide, system apps we don't care, trashy apps indeed, or a mix match in between.

good to know about the widgets, thanks! :)

was the issue too big and/or confusing or you simply wanted to comment only in those two branch aspects, @8bit?

**Comment by 8bitPit** [comment]
> too many apps start with P

Sorry, forgot that issue. Apps are sorted by usage, so after a day or your most used apps which start with "P" should appear at the top, so having many apps beginning with the same letter shouldn't be problematic.

> was the issue too big

Yeah, I prefer one new GitHub issue for each request, so I can track them better.

**Comment by cauerego** [comment]
yeah, i'm quite aware Devs prefer to keep issues separated... reason why i tried to do so!

sorry/notsorry for all the confusion and continued wordy posts. :)

my point was actually that you haven't addressed the only issue i meant to bring here: incentives.

so, here's an idea... i'll close this and begin a simpler one, with just this idea.

thanks so much for taking the time to try and help me out learning more about Niagara, though! i was waiting to see the suggestions and auto ordering in my favourites (still got nothing) and didn't even realize there was some magic there on the P letter.

this will bring me to yet another new issue, more like a UX bug. TK.

cheers!
