### ISSUE TITLE
Keyboard press should open search/corresponding app list section

### ISSUE THREAD

**Issue by mattexpa** [8bitPit/Niagara-Issues#349]
In other launchers' app drawers you can Type in the app's First Letter and straight jump to it's Position in the listing. I would love that because i have a blackberry so my keyboard is permanent and i could just Type "f" for Facebook and the drawer would automatically scroll down to the app's with f as their First letter.

**Comment by 8bitPit** [comment]
Agree, would come in handy for Blackberry users.

**Comment by 8bitPit** [comment]
@jjjhhhppp proposed to open Niagara's app search when pressing a keyboard key. In my opinion this would be even more intuitive.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2021). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2022 or later.
