### ISSUE TITLE
Fingerprint authentication

### ISSUE THREAD

**Issue by AkSxx** [8bitPit/Niagara-Issues#352]
Please add fingerprint authentication for hidden apps like in the smart launcher 5 and double tap to sleep gesture through devadmin, timeout and root.

**Comment by 8bitPit** [comment]
Fingerprint authentication for hidden apps would be a pseudo protection feature, since you could still open those apps with other other apps (e.g. another launcher / Google app). If you want a real protection, use apps like MaxLock (Open Source)

**Comment by 8bitPit** [comment]
And for double tap to sleep, see: #63
