### ISSUE TITLE
list of features request

### ISSUE THREAD

**Issue by ChrisBren** [8bitPit/Niagara-Issues#353]
1. Integrate sesame search.
2. Edit Clock format and font
3. Edit icon per app.
4. Hidden apps included in app drawer is not hidden enough, i suggest hidden apps and wallpapers settings should be moved inside Niagara's settings.

**Comment by rfrank128** [comment]
Would it be possiblessed to have a flashlight icon? I had one with my basic samsung guide but I have to close down niagra to use it, or get one filled with adware. Thanks.

**Comment by 7israndom** [comment]
Allow the whole launcher to be flipped so it's easier to use with left hand.

**Comment by 8bitPit** [comment]
@ChrisBren 
1. #88 
2. #34 & #23
3. #41 
4. Yeah, hidden apps will probably be moved to settings.

**Comment by 8bitPit** [comment]
@rfrank128 the flashlight icon should be accessible above the notification tray.

**Comment by 8bitPit** [comment]
@7israndom you can already scroll on the left side. If you want the scrollbar on the left side please refer to #12
