### ISSUE TITLE
Don't show greek letters in scrollbar

### ISSUE THREAD

**Issue by AmiinosEddagh** [8bitPit/Niagara-Issues#354]
i think there is a bug when the first letter of an app is not A...Z like utorrent it shows M instead of µ
![screenshot_20181005-135923_niagara launcher](https://user-images.githubusercontent.com/6989232/46536792-7900f680-c8a7-11e8-89d9-a1855cf9339d.jpg)

**Comment by 8bitPit** [comment]
It already shows a capital µ (it looks the same as an "M") but in the future it will be categorized as latin M.

**Comment by AmiinosEddagh** [comment]
hi
sorry i didn't know that 😜
keep up the good work
