### ISSUE TITLE
Support device policy enforced work profiles

### ISSUE THREAD

**Issue by voss** [8bitPit/Niagara-Issues#355]
Any chance you'll support work profiles in the future? My phone has a work profile enforced via the Device Policy app, and I'm not able to see the apps living in the work profile when I use Niagara.

**Comment by 8bitPit** [comment]
Hey voss, I am working on it right now :)

**Comment by 8bitPit** [comment]
Duplicate of #93

**Comment by voss** [comment]
Amazing! Thank you (: 👍🏆
