### ISSUE TITLE
let's build the trash, for minimalism incentive!

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#358]
continuing from #345, #346 and few others...

there must be an awesome blog post about this concept somewhere already. except they'll use very different keywords...

folders (#13) are just as useless as labels. look at Google inbox. they moved away from labels, which were already, by the way, a great technical upgrade from folders.

but, still, we keep installing apps nonetheless. and getting annoyed by having too many of them, most of which we don't use or care about. after a while, they stay there because it's easier than uninstalling one by one. and removing by usage, as many cleaning apps will do, is equally annoying, because there are quite a few useful apps that bypass that usage while there are trashy ones that won't appear, given how each app behave or what they do.

enter the trash!

simply leave them there, instead of uninstalling or hiding. and once they start to bother for whatever reason, simply take it away.

we're probably not using much more than 60 apps, anyway, and 30 on a regular basis. and those are small enough numbers for the current Niagara interface to handle perfectly fine.

long live the minimalist God! :D

**Comment by 8bitPit** [comment]
In my opinion folders do work they should show contextually though and apps should be categorized automatically. Sorry to ask again, but can you please explain why hiding apps isn't enough. You can access hidden apps quite fast by using Niagara's search. I believe many would be confused that there is one "hidden apps section" and a "trash can folder".

**Comment by cauerego** [comment]
automatic categories are not the same, at all, as folders. in a way, the alphabetical sorting is currently a (lazy) automatic categorization.

the trash would offer:
- a simple way to uninstall them all.
- a very clear incentive to keep fewer apps installed.
- socially speaking, it's even better if other people see this and understand its use.

hidden apps are for:
- "removing" uninstallable native apps.
- cleaning up the list of all apps while keeping them installed.
- eventually could be even more hidden, as to avoid anyone else to see them.

the apps you'd want in either can easily be completely different. and the way each feature works can be quite different as well.

they're about as different from each other as automatic categories are from folders or labels. ;)

**Comment by 8bitPit** [comment]
For me the trash & hidden apps make perfectly sense as one category. The hidden apps are not meant to be just for bloatware you can and should place all apps you don't want to see in the all apps list there. System apps could be shown at the bottom of the hidden apps section and a trash can icon could be placed next to non system apps to quickly uninstall them. Furthermore I planned on a  recommendation system that suggests apps to hide if you didn't use them often. I really think one category does the job as well, in my opinion it would be more simple for the user to understand, too.

**Comment by cauerego** [comment]
good point. how about calling that one category "basement" or something different, then?

but then, how to have a simple "empty trash" button, instead of going one app per time to clean them up?

given even google files actually asks to uninstall one app per time when we choose more than one while cleaning up, perhaps this is either technically impossible or not recommended... even still if you do want to go forward with the trash idea, perhaps we could use a better design.

in that sense, perhaps still offering an option to trash or hide apps could both move them into the basement category, in which we could see them separately.

then, hidden apps would group with system ones and could be trashed as you've mentioned, one by one. and trashed apps could be cleaned all at once, or individually moved into hidden mode instead.

definitely low priority. :D

**Comment by 8bitPit** [comment]
> given even google files actually asks to uninstall one app per time when we choose more than one while cleaning up, perhaps this is either technically impossible or not recommended... even still if you do want to go forward with the trash idea, perhaps we could use a better design.

Yup, you can only uninstall apps one by one, at least without root permissions. The only thing I could do is showing the next uninstall dialog after Niagara detected an uninstallment, but that conflict with the already open dialog of the last uninstallment, which say's: app xy uninstalled successful, but I haven't tested that yet.

I think there should be an per-app toggle to remove apps from Niagara's search completely. Maybe those apps could be grouped together. I think that would go into the direction of your idea, what are your thoughts on this?

**Comment by cauerego** [comment]
yeah, the trashed app would definitely not show anywhere outside the trash category.

with the risk of repeating myself too much...

you see, there are a lot of apps we install that we may need to install again later or not. then there are those we uninstall, then need to install again, but over the past 2 years we only used them twice! and then we just leave them there... until space is needed, or we suspect they might be abusing the RAM somehow, or just taking space on the launcher.

meanwhile, hidden apps are ones we have no doubt: they should be installed. but we just don't need or want their icons there on the list.

i think the trash category makes a lot of sense even without that distinct function of not showing on search. still, yeah, it sure could use a different name and style.

thanks for asking! 💯  :D

**Comment by 8bitPit** [comment]
Hey again @cauerego. I'm sorry but I still can't see why there is a need for another slightly modified hidden app section. For the sake of simplicity I'll keep it the way it is. I'm sorry.
