### ISSUE TITLE
Show favorites at the bottom of letter section

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#359]
continuing from #346

if the app is already a favourite or at the home page through suggestions or any other mean, does it need to get promoted to the top of its letter on the full alphabetical listing?

**Comment by 8bitPit** [comment]
Yeah I believe it would be nice trade-off between the current implementation and hiding them completely #221 (which would require an additional toggle, since some people don't want to get rid of them).

**Comment by cauerego** [comment]
2 months ago you closed #221 with a nice option to hide the app there.

as a very minor addition, wouldn't it be better if hiding an app from the full list, which is already favourite, would immediately hide it just from the full list?

any way, just wanted to bump this in general, because it's still a completely different solution to the same general issue. probably you chose to resolve 221 because it was much easier, but it doesn't change at all, imho, the status of this issue. 😁

sorry if this is too much! in fact, i'll even go ahead and close this anyway, picturing you'll never find the time to go around, that nobody else seem to care and that even me, i still today think this would be very minor.

cheers.
