### ISSUE TITLE
Add animation to Google button/show tutorial

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#360]
there could be a very little arrow top, from the Google button, for instance. a visual reminder there's an action there, for going straight to the very useful search.

**Comment by Rod911** [comment]
Could add a small bounce animation when returning to favorites section instead of an arrow.

**Comment by 8bitPit** [comment]
Maybe an arrow / bounce animation that disappears after using quick search?

**Comment by cauerego** [comment]
after using quick search *for a while*, as to get used to it. 🕺

**Comment by disacrol** [comment]
Maybe an bounce animation but just until the user tries or out. Kind of an onboarding feature.

**Comment by 8bitPit** [comment]
@disacrol that's the thing I suggested :P

> Maybe an arrow / bounce animation that disappears after using quick search?

**Comment by disacrol** [comment]
@8bitPit Jesus, I'm getting blind over time 😁

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
