### ISSUE TITLE
Animations of alphabet 

### ISSUE THREAD

**Issue by Axoji** [8bitPit/Niagara-Issues#361]
In my point of view it would be great to let user chose which of two components will apply - if I see it right it is bumpy, wave animation (it is distracting to me so I will turn it off) and sliding it more to upper/lower end of screen when our finger reach ends (which is really intuitive to me and really cool).

**Comment by 8bitPit** [comment]
The wave animation is part of Niagara's style so there would be missing something if I remove it, or make it optional.

**Comment by 8bitPit** [comment]
Moreover, the animation has also a practical purpose: Your finger won't cover the alphabet while scrolling.

**Comment by Bushmills** [comment]
My favourite animation would also be no animation at all, and i notice that I find the non-animated letter bar of T Launcher so much cooler. Animations wear off after a while, then they start to become annoying.

**Comment by 8bitPit** [comment]
@Bushmills most animations fo have a purpose though, they're not just eye candy. In this case:
>Your finger won't cover the alphabet while scrolling

**Comment by Bushmills** [comment]
I'm aware of that - but there's also the letter bubble popping up to the left of the letter bar when touched, which ought to be indication plenty.
