### ISSUE TITLE
Adjust notification gesture threshold

### ISSUE THREAD

**Issue by Axoji** [8bitPit/Niagara-Issues#362]
As in the title, I tend to do really short rapid swypes to open my notification bar and the at ~half of times my swypes are to short to open notification tray. I do not have this problem on any other launcher or while expanding an notification on tray or tray itself to larger form (which is handled system side so it should be reference) so it is crearly a defect.

Tested on custom 8.1.0.

Here is https://my.mixtape.moe/mocmhb.mp4 link to screencast - on beginning you can see this to short rapid swype which didn't work, and then how android handled tray elements response to short swypes. It is flustrating option for me now - half of my swypes just do not do anything and it is not consistent with android behaviour so it is UX defect, really annoying one.

**Comment by 8bitPit** [comment]
The gesture is based on your fingers acceleration. I cannot set it to the threshold to low, because sometimes you just want to scroll up on your favorites (if you have many).

**Comment by 8bitPit** [comment]
It should be easier to trigger now.

**Comment by 8bitPit** [comment]
Fixed in v.0.7.8
