### ISSUE TITLE
Scrollbar design suggestions

### ISSUE THREAD

**Issue by prsntg** [8bitPit/Niagara-Issues#366]
1) Instead of a separate bubble showing the selected alphabet, can the alphabet in the scrollbar itself be enlarged (like looking through a lens?) when selected?

2) The total scrolling length (or height) is same as the height of the alphabet list itself. It makes sense when scrolling through the alphabet list on the right side. But for the scrolling in opposite side of alphabet list (left side), can the scrolling speed be doubled for a better one handed usage? i.e if I start scrolling from bottom, I should reach alphabet A when my hand reaches only till half the height of the alphabet list.

**Comment by 8bitPit** [comment]
1. The bubble is for assuring a good contrast, app names & the letter of the current section would overlap if it wasn't there.

2. An even smaller space to scroll would be too hard to reach specific sections.
