### ISSUE TITLE
backup favourites

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#368]
this will look like a very minor issue, but it's a huge annoyance to me.

i just added 20 favourites, after 2 days with 8 I got no recommendation/suggestion for the most used ones. none.

eventually, though, I'd love to see the recommendations. I just don't want to store my list, one by one, to have to add them again, one by one, once i find out the auto engine is still not good enough for my actual usage.

not to mention in case i have to get a new phone, which happens more than i want to.

**Comment by 8bitPit** [comment]
I will add a full backup function, where you can store your favorites & the app usage database, see #222

**Comment by cauerego** [comment]
not quite the same idea though.

i'll edit the op and let you decide if this should be reopened.

**Comment by cauerego** [comment]
original post text, fwiw:

this will look like a very minor issue, but it's a huge annoyance to me.

i just added 20 favourites, after 2 days with 8 I got no recommendation/suggestion for the most used ones. none.

eventually, though, I'd love to see the recommendations. I just don't want to store my list, one by one, to have to add them again, one by one, once i find out the auto engine is still not good enough for my actual usage.

not to mention in case i have to get a new phone, which happens more than i want to.

**Comment by cauerego** [comment]
yeah, pretty much something like that! while keeping an option to easily go back to our favorites...

i'm glad you had this in mind already. :)
