### ISSUE TITLE
Icons and Font

### ISSUE THREAD

**Issue by imishayera** [8bitPit/Niagara-Issues#370]
First off, It's amazing. The launcher is incredibly fluid and fast (even in mine. I'm using Nokia 1, the low end phone). The wave scroll bar is super cool.
My request, like the customizable app name, customizable app icons individually. And in addition to that font options may allow for more personalization (altho i find the default fitting and adequate, the customizability of that may be well recieved. You could ask other users for their opinion on as well).
Great job so far, Kudos. And Keep Up the great work, brothers.
Thanks.

**Comment by 8bitPit** [comment]
Thanks @imishayera for your kind words :)
Please refer to #41 & #191
