### ISSUE TITLE
Wallpaper getting reset

### ISSUE THREAD

**Issue by mubharad** [8bitPit/Niagara-Issues#372]
Wallpaper (custom WP set from Google photos, not from launcher WP) keeps getting reset and gives black background since v 0.5.0 onwards. Prior version did not had the issue. Is it device or release version specific?

Thanks

**Comment by 8bitPit** [comment]
Which device / Android version do you use?

**Comment by mubharad** [comment]
I've Moto g5 plus on Android 8.1 (custom rom)

**Comment by mubharad** [comment]
I never had this issue with other launchers. I'll try using other photo apps and see if the issue was only with Google photos or with others as well.

Thanks

**Comment by mubharad** [comment]
Appreciate the feedback, Peter.

The issue happened again with another app through which I set the wallpaper, so it is happening often though I'm not able to recollect under what circumstances it gets changed.

Thanks

**Comment by 8bitPit** [comment]
This bug was not reported since, I don't believe it has something to do with Niagara.
