### ISSUE TITLE
Hide app list moved?

### ISSUE THREAD

**Issue by moviti** [8bitPit/Niagara-Issues#374]
After the latest ver.0.5.0, it moved back into the setting. In my opinion the last implementation (bottom of alphabetical list) was better way to access easily, wasn't it?

**Comment by randompherret** [comment]
Agreed. I aggressively hid some, but having to go to settings to get to them is cumbersome

**Comment by moviti** [comment]
@8bitPit Thanks for your replies and hard work!

In my case, I use "hide app list" as "low priority folder". if the folder feature came here, this hide list would be fine in the current position (under the setting).

**Comment by 8bitPit** [comment]
@moviti ah okay, you could also use search for opening hidden apps.
