### ISSUE TITLE
 [Feature Request] Persistent Music Widget

### ISSUE THREAD

**Issue by drakovyrn** [8bitPit/Niagara-Issues#375]
Hi, I love the the simplicity of Niagara, and it's surprisingly smooth.

However, one thing that I use my phone for the most is music, and I don't like that the music widget only shows when music is playing. I'd like to be able to always show the music widget, with favorites underneath.

Thanks,
Christian The Satanist

**Comment by sauerbraten** [comment]
Adding to this, I'd like to be able to completely disable the music player showing up on my home screen. Pulling down on the launcher to get Spotify in the notification area is enough for me. So if you make an option for this, maybe take both into account :)

**Comment by 8bitPit** [comment]
I'm sorry @drakovyrn, I can only provide the music player when there is an active media session. Your suggestion would only be possible with implementing custom widgets (#117)

**Comment by 8bitPit** [comment]
@sauerbraten already on my list: #111
