### ISSUE TITLE
[Feature Request] No most used

### ISSUE THREAD

**Issue by drakovyrn** [8bitPit/Niagara-Issues#376]
As it says in the title, I have no use for the frequently used feature, and instead of the option for *less* frequently used, I would rather have an option for *no* frequently used.

Thanks,
Christian The Satanist

**Comment by Rod911** [comment]
#128

**Comment by drakovyrn** [comment]
Sorry, I didn't see the previous issues before. I don't get it, though. Shouldn't *not* having a feature be easier to implement than having a feature?

**Comment by 8bitPit** [comment]
Some people only want a few recommendations, that's why I added that as a second option. Also you can disable the rest manually by long pressing the app which you wouldn't like to see (#224).
