### ISSUE TITLE
[Feature Request] Swipe to favorites from app list

### ISSUE THREAD

**Issue by drakovyrn** [8bitPit/Niagara-Issues#377]
When in the app list, swiping down stops at the top of the list, I think swiping down after reaching the top should transition back to favorites.

At the moment, it's only possible to get back to favorites by scrolling with the Alphabetical List.

Thanks,
Christian The Satanist

**Comment by Rod911** [comment]
You can return to the favorites by pressing the home or back key.

**Comment by disacrol** [comment]
It's a good suggestion though, it kinda makes sense.

**Comment by 8bitPit** [comment]
See: #212
