### ISSUE TITLE
[Regression] Press home from home screen to search apps

### ISSUE THREAD

**Issue by preetangad** [8bitPit/Niagara-Issues#378]
This used to work. When you are on the home screen and press the home button, it used to bring up the search bar for apps. I loved that feature and now it does nothing at all. Please please bring it back!

**Comment by Rod911** [comment]
This option exists but disabled by default after a recent update. You can re enable it by going to Niagara settings - > Home Screen - > Advanced - > Press home to search.

**Comment by preetangad** [comment]
Thank you, I hope this feature always stays!
