### ISSUE TITLE
Open app without clicking notification

### ISSUE THREAD

**Issue by preetangad** [8bitPit/Niagara-Issues#379]
If an app has an unread notification, like a facebook message, sometimes I just want to leave the notification unopened and still open the app. However, when you tap the name of the app, it always opens the notification, and for example the person who sent the message can see that I've seen the message.

I would like there to be a way to open an app that has an unread notification without clicking the notification, for example to open other messages. Currently the only way to do this is to search for the app and then click the name since that isn't linked to notifications.

Perhaps if you swipe on app and it has notifications, there can be a way to click the app name or something to go into the app and not into the notification.

**Comment by Rod911** [comment]
See #275
