### ISSUE TITLE
Notification dot not working on Android pie

### ISSUE THREAD

**Issue by mioaki** [8bitPit/Niagara-Issues#380]
I am using the custom rom pixel experience 9.0 on a redmi note 5 pro. Notification dot is working properly on the default pixel launcher but doesn't when switching to Niagara.

**Comment by beshoy312** [comment]
Can I ask you what rom are you using and good is it

**Comment by mioaki** [comment]
I am using pixel experience 9.0 with derp kernel updated to 3.3. The rom is almost bug free. But it doesn't have a lot of customization, no full screen gestures. The battery life is meanwhile the best.
