### ISSUE TITLE
Light /Dark Tap feedback on app tap

### ISSUE THREAD

**Issue by ShinobiWPS** [8bitPit/Niagara-Issues#383]
Currently, the highlight is white.
My device is not considered high end so when I tap on an app in the launcher and I have a Light wallpaper (almost white) I can't know if I tapped on the app or not since my device is not that fast.That leadsme to tap twice because the phone its not a quad-hexa-twelve-uber-core one and I can't see the white highlights if and when that happens. 

Ideally if the user has a light wallpaper and it triggers the light theme, the launcher should highlight in black(or something dark) to have a contrast.

What you think?

**Comment by 8bitPit** [comment]
Great idea! I'll add a dark ripple effect for dark text mode.

**Comment by Saucerpan** [comment]
It would be great if the color toggle could be separate from the dark text mode. I have a darker wallpaper but would still personality prefer a dark ripple effect.

**Comment by 8bitPit** [comment]
@Saucerpan Sry, I believe extra settings for that would be overkill, I want to keep them simple.

**Comment by 8bitPit** [comment]
Available in version 0.5.2
