### ISSUE TITLE
Web search from launcher 

### ISSUE THREAD

**Issue by ShinobiWPS** [8bitPit/Niagara-Issues#384]
Since we don't have space for widgets, nor home screen space for apps, and I could have many many favorites apps, is it possible to have the search bar at the top 🔝 above the clock 🕒 so hitting enter in that search or showing suggestions from a search engine (optional) which would open the OS default browser?

The search bar at this point would be enhancable by mixing app search and Web search ;) MORE USABILITY 🎉 🎉 🎉

I'm bringing this because your launcher seems an improved version of Evie launcher which I liked/loved, simple, easy usability /straight to what is essential, convenient to use and NOT distracting, but Niagara still miss some features from that point of view, nothing to force someone, you choose.

**Comment by Rod911** [comment]
Enable the Google button on the home screen, you can do a swipe up action on it to bring up web search or just click it for the Google feed.

**Comment by ShinobiWPS** [comment]
Why the app should has to tie usability/UX with a specific product/company?

what about people that care more about their privacy?

At this point the Google button can become WebSearch Button, firing the OS-default  browser with a new tab, if the search bar it's too complex.

**Comment by 8bitPit** [comment]
> showing suggestions from a search engine (optional) which would open the OS default browser?

See: #58 

> Why the app has to tie usability/UX with a specific product/company?

Also requested here: #142
