### ISSUE TITLE
Swipe Gestures

### ISSUE THREAD

**Issue by AllTheKritturs** [8bitPit/Niagara-Issues#385]
Swipe left to show all apps swipe right to home screen (letters hide in home screen)

**Comment by Rod911** [comment]
Nope, doesn't work that way, never will. Conflicts with the scroll and notification view.

**Comment by 8bitPit** [comment]
@Rod911 is right, swiping right is for opening and swiping left for deleting notifications.

**Comment by GreyCannibal** [comment]
Swipe right → for toggles 😍 and hide notification bar.

**Comment by 8bitPit** [comment]
Which toggles do you mean @GreyCannibal ?
