### ISSUE TITLE
Tap&hold menu white on white wallpaper worsening confusion/usability

### ISSUE THREAD

**Issue by ShinobiWPS** [8bitPit/Niagara-Issues#386]
I think the issue it's pretty self explanatory.
Ideally a darker borders or darker background of the popup would be beneficial.
![photo5900227459528371973](https://user-images.githubusercontent.com/11430881/46662726-2039a280-cbb4-11e8-9a33-7c916d6d5ce6.jpg)

**Comment by 8bitPit** [comment]
Good idea, I added a little shadow effect, which will be available in the next version:
![image](https://user-images.githubusercontent.com/9284845/46755989-b78f1a80-ccc6-11e8-840e-86f7459264f3.png)

**Comment by 8bitPit** [comment]
Available in version 0.5.2
