### ISSUE TITLE
Hide app(icon) name

### ISSUE THREAD

**Issue by motherfusca** [8bitPit/Niagara-Issues#388]
It would be great (and cleaner) if we could hide app names (at least in the home screen)

**Comment by Scorpionk1** [comment]
Go to edidtar name. Give it a whitespace and Ok.

**Comment by Scorpionk1** [comment]
Go to the edit name. Give it a whitespace and Ok.

**Comment by Scorpionk1** [comment]
Go to the edit name. Delete the name ... Give a blank and Ok.

**Comment by 8bitPit** [comment]
See #79
