### ISSUE TITLE
Able to suppress a 'warning'

### ISSUE THREAD

**Issue by MathieuDR** [8bitPit/Niagara-Issues#389]
Hello.

I'm using EAS as well, which would also prefer the default 'home functionality', and then redirects to the 'real' launcher.

However, when I configured EAS as the default Home app, and let EAS redirect that functionality to Niagara, Niagara is making a fuss of not being the default home application.

Is there, or will there be a a 'suppress warning' functionality?

**Comment by 8bitPit** [comment]
Currently there is no way, but maybe I'll add one.

**Comment by 8bitPit** [comment]
Sorry, the feature is unlike to be implemented, because the amount of people wishing for it is too small.

**Comment by Amorphous404** [comment]
- Duplicate of #949
