### ISSUE TITLE
App 8tracks doesn't show up anywhere in the app list

### ISSUE THREAD

**Issue by clone81** [8bitPit/Niagara-Issues#392]
So weird thing...the app 8tracks doesn't show up anywhere in the app drawer or in hidden apps. I have to go to the Play Store to open it.

**Comment by 8bitPit** [comment]
Weird, it should be categorized under "#". Have you tried opening it with Niagara's search?

**Comment by Rod911** [comment]
Works fine for me, they show up on the top of the list.

**Comment by 8bitPit** [comment]
Please write back to me / reopen this issue if you're issue hasn't been solved yet.

**Comment by clone81** [comment]
I uninstalled and reinstalled 8 tracks and it shows up five now. Thank you.
