### ISSUE TITLE
Icon resizing does not work

### ISSUE THREAD

**Issue by ewaucq** [8bitPit/Niagara-Issues#394]
In 'App icon size', I changed the size from 'Small (Default)' to Meduim which did the job.
But changing back to any other value does not work, icons are still displayed Medium size.

**Comment by 8bitPit** [comment]
Thanks for reporting, so you cannot change the value on the dialog? Can you please provide some screenshots?

**Comment by 8bitPit** [comment]
Please write back to me / reopen this issue if you're issue hasn't been solved yet.
