### ISSUE TITLE
[Request] Thumb friendlier navigation

### ISSUE THREAD

**Issue by alexstyl** [8bitPit/Niagara-Issues#397]
With a quick glimpse, the launcher seems very promising!

I noticed that all the lists in the app start from the top as opposed to the bottom or to be centered on the screen. That makes it very hard to hold the phone in most cases without awkwardly moving it around on the hand.

My 2c would be to populate all lists you have (i.e. the favorites in the home screen) from the bottom or center the results in the screen, so it's easier to reach with your thumb.

If you follow that principle, it would be awesome if you could make the fast scroller with the first letters of the app start from the middle of the screen instead of top (or set a maxHeight) so that it is more thumb friendly.

**Comment by 8bitPit** [comment]
Thanks, I believe bottom / centered list would look a bit strange though. Adjusting the top padding will be possible in the future, see: #334
