### ISSUE TITLE
Move favorites: drag & drop icon disappearing behind FAB

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#399]
[Screenshot](https://imgur.com/a/GB8k6Zv)

As of now the upper screen real-estate is being wasted, resulting in the far-right dotted icon disappearing behind the "accept-button" (_can't remember the name of those Material UI handy buttons_) if you max out with 8 favorites.

Only a small aesthetic annoyance imo, as the functionality of the menu sn't affected at all.

**Comment by 8bitPit** [comment]
I agree, those drag'n'drop icons shouldn't disappear behind the floating action button (I guess that's the term you searched for ^^). The padding at the top is for using the phone with just one hand though. I'll come up with another solution to fix it!

**Comment by Montell2099** [comment]
Thank for quick feedback, it sounds great! Always get excited seeing updated for this launcher.

**Comment by 8bitPit** [comment]
Updated the drag & drop layout in version 0.5.2. Thanks for your help @Montell2099 :)
