### ISSUE TITLE
Avoid going to the top of Favourites list on Home tap

### ISSUE THREAD

**Issue by ShinobiWPS** [8bitPit/Niagara-Issues#400]
Sorry @8bitPit , I know, another Home-button issue :)

Currently, if a user has more favourites than screen space AND
the user scrolls down (in the same view) probably because it's looking for an app which can't find in favourites
WHEN the user taps on the home button instead of firing the app-search, the launcher moves the user view to the top of the list.
You can get the app-search only if you tap Home button ANOTHER time.

**Comment by 8bitPit** [comment]
Available in version 0.5.2
