### ISSUE TITLE
Apps in alphabetized list are not in alphabetical order

### ISSUE THREAD

**Issue by sfosdal** [8bitPit/Niagara-Issues#401]
one example, in the attached screenshot
```
WhatsApp
Wallpapers
Whole Foods Market
Wikipedia
```
should really be
```
Wallpapers
WhatsApp
Whole Foods Market
Wikipedia
```

![screenshot_20181011-090456](https://user-images.githubusercontent.com/684453/46818143-5b171400-cd35-11e8-9dc0-d83a45da02bd.png)

**Comment by 8bitPit** [comment]
Apps are also sorted by usage in the app list.
