### ISSUE TITLE
[New setting] Autoopen search bar

### ISSUE THREAD

**Issue by CiriousJoker** [8bitPit/Niagara-Issues#408]
Would make it way quicker for user's who mostly use the search bar anyway.

**Comment by 8bitPit** [comment]
You can press home to open search if you enable it in Niagara's settings.

**Comment by CiriousJoker** [comment]
I know, but even with that enabled, it still takes two presses instead of one like 90% of the time

**Comment by 8bitPit** [comment]
Sorry, but Niagara is not designed around search. I suggest using Kiss launcher for example if you want that or use the slightly slower home button gesture. I'll partly explain why I don't want to add a lot of toggles here: #808. Sorry for the inconvenience.
