### ISSUE TITLE
Ability to change individual icons

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#41]
I have problems with icon packs, app icons that should be changed, dont change because of a different package name, so it would be better to change the icon to a different icon in the icon pack to get the right icon that fits

**Comment by 8bitPit** [comment]
Cool feature, but takes some time.

**Comment by Rod911** [comment]
This issue has been referred way too many times 😁

**Comment by disacrol** [comment]
Yep. Another one was just opened. I guess that's why 'not now' label was removed.
