### ISSUE TITLE
Updating icon pack does not automatically update new icons

### ISSUE THREAD

**Issue by M4rku5in** [8bitPit/Niagara-Issues#410]
I use my own icons. Updating the icon pack does not automatically update new icons. All must be done manually. Other launchers know this.

**Comment by Rod911** [comment]
Thanks for bringing this up. I use icon pack studio and every time I install an app I have to update the icon pack which is fine but I also have to go through the settings to refresh the launcher icons.

**Comment by 8bitPit** [comment]
Thanks for reporting @M4rku5in, does it work in Lawnchair launcher?

**Comment by M4rku5in** [comment]
I'm sorry @8bitPit, but I have not tried Lawnchair launcher yet. For years I used the Nova launcher until the Niagara launcher appeared. He charmed me and did not want to use another. Evie and Microsoft launcher with icon packs work well.

**Comment by 8bitPit** [comment]
Wow, this bug is one and a half years old. Finally, it will be fixed in v0.26.

**Comment by 8bitPit** [comment]
Sorry, the fix introduced another bug so I had to revert the changes. This has not been fixed yet.

**Comment by 8bitPit** [comment]
Fixed in v.1.5
