### ISSUE TITLE
[feature request] hide status bar clock on home screen

### ISSUE THREAD

**Issue by nontheoretical** [8bitPit/Niagara-Issues#415]
Add the option to hide and show the clock from the statusbar while in the app. Like toggling the "systemui > status bar > clock" whenever the app is opened.

Note that I am not talking about  an immersive mode where the whole status bar is hidden.
#101 does not satisfy this request.

**Comment by Scorpionk1** [comment]
If your device does not have the function of hiding the icons in the status bar. I'm only sorry for you!

**Comment by Rod911** [comment]
Possible duplicate of #225
