### ISSUE TITLE
Seconds on Clock

### ISSUE THREAD

**Issue by ModProg** [8bitPit/Niagara-Issues#416]
I would really love to have the possibility to add to the Clock Widget.

**Comment by Montell2099** [comment]
Is it purely an aesthetic preference, or do you have any use for seeing the seconds displayed on the clock?

**Comment by heroh9** [comment]
Would be great to have an option for it

**Comment by 8bitPit** [comment]
Yeah, maybe I'll add that.

**Comment by martyrcomms** [comment]
Hi
I have a problem with the clock it is the clock at the top of my screen is showing a different time to the clock settings one.  It is slow can't see any obvious reason for it to be displaying the difference.  Otherwise I like the app but I'm late for meetings all the time lol

**Comment by 8bitPit** [comment]
@martyrcomms can you please post a screenshot?

**Comment by martyrcomms** [comment]
Yes I will try to send you that over the weekend

**Comment by 8bitPit** [comment]
@ModProg, I've decided not to add a seconds toggle to the clock, to keep the launcher simple. However, you could replace the default clock with a custom widget in the future which shows seconds (https://github.com/8bitPit/Niagara-Issues/issues/117)
Sorry for the inconvenience.
