### ISSUE TITLE
Huawei File Manager is not considered the default

### ISSUE THREAD

**Issue by palopezv** [8bitPit/Niagara-Issues#419]
And as such, most icon packs do not assign the right icon replacement. The problem I suspect comes from the app name: com.huawei.hidisk. Niagara is somehow interfering with the assignment. Case study: Whicons. With Lawnchair 1 from the Store, the archive is properly replaced, yet with Niagara the icon is the one selected with the EMUI theme manager, that is the system icon pack.

**Comment by 8bitPit** [comment]
Do you get the same problem in other launchers like Niva / Lawnchair as well?

**Comment by palopezv** [comment]
No. Both Nova, Lawnchair, replace the icon with the one provided by Whicons. Same for Zwart and Golden Icons, the other free icon packs by Randle. I also tested with Minty Icons Free and these launchers do the substitution without trouble.

To be really sure, I also tested Rootless, Lean, Apolo and Arrow (a.k.a. Microsoft Launcher). All work as expected.

**Comment by 8bitPit** [comment]
>  Case study: Whicons. With Lawnchair 1 from the Store, the archive is properly replaced, yet with Niagara the icon is the one selected with the EMUI theme manager, that is the system icon pack.

Oh sorry, must have forgot to read the end of your first comment, I'm dumb.

I'll try to fix the issue in Niagara's "Halloween update" where I focus on enhancing icon pack support & custom icon selection.

**Comment by palopezv** [comment]
Cool. Thank you for all your work. I'm in love with it. :smiley:
