### ISSUE TITLE
Very weird bug???

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#42]
Overdraw feedback enabled so you can see it easier https://photos.app.goo.gl/qqUVeKvZ223ufkD87 

Overdraw feedback disabled (you can still see it)
https://photos.app.goo.gl/mhSh5232ZqMfTXvF7

**Comment by jakcharvat** [comment]
Can you please name the bus something more appropriate next time?

**Comment by 587saboor** [comment]
@jakcharvat done

**Comment by 8bitPit** [comment]
@587saboor your album is empty.

**Comment by 8bitPit** [comment]
Btw you can also include pictures right in the comment. Just paste it.

**Comment by jakcharvat** [comment]
O have a pic @8bitPit, I'll send it

**Comment by jakcharvat** [comment]
https://photos.app.goo.gl/dZ18io6qWywhdQrw5

all credits go to @587saboor 

I'm on my phone, so can't paste directly in.

anyways, it's a vid, not a pic

**Comment by 8bitPit** [comment]
Oh, I'll look into it.

**Comment by jakcharvat** [comment]
Thanks. Really subtle and hard to notice at first, but quite annoying once I know about it

**Comment by 8bitPit** [comment]
I don't what is causing the problem but maybe i have some ideas:

1. Maybe the shadow of that circle is buggy. With the newest update I removed it so you can test if it's gone.

2. It could be your custom font.

**Comment by 587saboor** [comment]
@8bitPit ok so i just updated it, and it looks like it's the shadow's problem

**Comment by 8bitPit** [comment]
Great! It's certainly because of the combination with the shadow and the "reveal" animation for the circle. I'll try to animate the shadow in and you can give me feedback if the bug reappears. Therefore, I’ll let this issue open.

**Comment by jakcharvat** [comment]
#50 is caused by this according to @587saboor
