### ISSUE TITLE
Daily wallpaper

### ISSUE THREAD

**Issue by heroh9** [8bitPit/Niagara-Issues#421]
Add an option to have daily wallpapers from bing or something

**Comment by Scorpionk1** [comment]
Bing wallpapers are great! I think the developer will not want to implement this marvel.

**Comment by 8bitPit** [comment]
Yeah, that feature would be quite time intensive & I would need a server or at least some infrastructure to provide those images. Moreover, I also need the wallpapers themselves ^^. I would recommend using [Muzei Live Wallaper](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei) or similar apps.

**Comment by heroh9** [comment]
I am gonna close this now then
