### ISSUE TITLE
App shortcuts

### ISSUE THREAD

**Issue by farvardinzad** [8bitPit/Niagara-Issues#422]
Given that long press on app icons provides option to uninstall etc, are you planning to add functional shortcuts such as new email/calendar events, favourite contacts etc?

**Comment by 8bitPit** [comment]
App shortcuts can be accessed by swiping to the right. Moreover, "legacy" shortcuts, will also be available in the future, see #62 :)

**Comment by farvardinzad** [comment]
Brilliant!

Thanks.

-------- Original Message --------

**Comment by 8bitPit** [comment]
You're welcome.
