### ISSUE TITLE
Add 'Move Favorites' button in home settings

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#423]
Now that there is a menu to move favorites around, there should be a button to access that menu from settings.

**Comment by 8bitPit** [comment]
I believe the option in the long press menu is enough, since you also hold on an app to drag it on grid based launchers

**Comment by IdmFoundInHim** [comment]
Yes, but in those, you can hold and drag apps around without having to press a button in between.  If the goal is to be like grid launchers, then long-press without drag should open the mini-menu, but a long-press and drag should simply move the app.

**Comment by 8bitPit** [comment]
That would conflict with some ideas I have in mind, visit #367 for details.
