### ISSUE TITLE
Samsung Clock App - Alarms only from widget

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#429]
> Niagara opens any app which reacts to "AlarmClock.ACTION_SHOW_ALARMS".
_Originally posted by @8bitPit in https://github.com/8bitPit/Niagara-Issues/issues/295#issuecomment-426055238_

![screenshot_20181014-202559](https://user-images.githubusercontent.com/30935172/46924153-8f1d5e00-cfef-11e8-87b3-6f08f08f6bbb.jpg)

I could not find a good replacement in my research, but on Samsung, clicking the widget only shows my alarms (launching the window shown above). It does not have other tabs, like stopwatch. Is there a different action that could be used to open the clock app that does not have this limitation?

**Comment by IdmFoundInHim** [comment]
I also understand this may not be possible/ideal.  I found [this](https://stackoverflow.com/questions/3590955/intent-to-launch-the-clock-application-on-android).

**Comment by 8bitPit** [comment]
To my mind, that's the best way to implement it, since most apps react to the intent and setting your alarm for tomorrow is often used. Having a list of clock packages and check if one of your apps is on the list is not a very good solution, because it doesn't work for every clock application.

**Comment by 8bitPit** [comment]
It can be changed in the future though: https://github.com/8bitPit/Niagara-Issues/issues/295
