### ISSUE TITLE
Immersive mode / Hide Navigation bar

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#43]
And user can pick if they want navbar only, status bar only, or no navbar or status bar

**Comment by 8bitPit** [comment]
Maybe, I my opinion the navbar is quite important, but it could be an option.

**Comment by 587saboor** [comment]
@8bitPit yes navbar is important but some people dont need it on the home screen because home and back button doesnt do anything *technically*

**Comment by jakcharvat** [comment]
I don't see a reason for keeping the navbar on the homescreen unless you're planning on having the buttons actually do something

**Comment by jakcharvat** [comment]
Then that is the approach I would prefer. maybe a toggle in the settings letting the user choose whether to show or hide the Nav Bar

**Comment by 587saboor** [comment]
@jakcharvat lol thats what the main post says

**Comment by jakcharvat** [comment]
oh you're right. lol 😂

**Comment by disacrol** [comment]
@8bitPit why low priority? Isn't this already implemented (hide status bar)? What else can be done here?

**Comment by 8bitPit** [comment]
@disacrol this feature toggle would also hide the navigation bar, (the buttons at the bottom). However, on Android 10 with gesture enabled, this wouldn't make much difference, in my opinion (because the new bar is so tiny).

**Comment by 8bitPit** [comment]
I believe this option is not needed anymore with the new gesture options most new user interfaces offer.
