### ISSUE TITLE
Advice from a Chinese user

### ISSUE THREAD

**Issue by xrkxrk** [8bitPit/Niagara-Issues#431]
In Chinese mode, only use A ~ Z to classify the application (Translate the first Chinese word into pinyin and combine it with the English classification) instead of treating Chinese characters as A single category, because there are too many Chinese characters.
![screenshot_20181012005817](https://user-images.githubusercontent.com/33193003/46924577-d5f36e00-d058-11e8-9d83-b0f44e5d5d87.png)

**Comment by 8bitPit** [comment]
Thanks for your suggestion @xrkxrk, please refer to #234
