### ISSUE TITLE
[Request] Home Screen apps

### ISSUE THREAD

**Issue by benanrarbieri** [8bitPit/Niagara-Issues#434]
Is there a possibility of after putting Show Clock off, instead keeping the same amount of 8 apps on the home screen, would change to a layout with 10 apps?

(Best launcher ever, thx devs!)

![img_20181014_232448_614](https://user-images.githubusercontent.com/42393207/46926844-de23bd00-d008-11e8-8184-304f523d2c01.jpg)

![img_20181014_232529_697](https://user-images.githubusercontent.com/42393207/46926865-fb588b80-d008-11e8-8756-2e0c43197842.jpg)

**Comment by Rod911** [comment]
You can add as many favorites as you want.

**Comment by benanrarbieri** [comment]
Hey, Rod911...

The request is referring to the blank space after putting Show Clock off, that could be filled showing two more apps. More aesthetic than essential.

Thx for the comment. ✌️

**Comment by Rod911** [comment]
Ah ok, but I think this was intentional so that it would be easier to reach the top apps on larger screen phones. Same as in the app list where there is a gap in the top so that you won't have difficulty to reach the first app.

**Comment by benanrarbieri** [comment]
I perceived the intention of the gap, actually. But you are right, on hella screens (>6") would be difficulty to reach the apps. I probably based the request in a personal taste, not considering the others sizes of screens.
Thanks man!

**Comment by 8bitPit** [comment]
@benanrarbieri, here is an issue about making the top padding adjustable, that could help you: #334.
