### ISSUE TITLE
Disable clock / replace it with a 3rd party widget

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#44]

**Comment by jakcharvat** [comment]
Having At A Glance would be wonderful for example

**Comment by 587saboor** [comment]
@jakcharvat ye and i mean 3rd party widget, not only at a glance,
The developer doesnt have to implement at a glance that way, google already made it as an official widget

**Comment by 8bitPit** [comment]
Widgets are a quite complex. I did include them in an alpha version, but they were buggy, hence I removed them.

**Comment by 587saboor** [comment]
Im closing this issue since its now available with beta build

**Comment by 8bitPit** [comment]
Thanks @587saboor.
