### ISSUE TITLE
Remove/hide favorites from app list

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#440]
this is a simple fix for being able to easily hit "A" and it's also an improvement, imho, of the UX behind it. the home button already works perfectly for hitting the home page.

**Comment by 8bitPit** [comment]
I just find it faster & way more comfortable to go to favorites that way. I believe go to "A" isn't that hard.

**Comment by cauerego** [comment]
perhaps make a bigger space between them, then?

although, from imagining how you position your hand in a big screen, now i can picture why you think there's no issue reaching out to the top app... (i still plan to give you a photo on that other issue, lol)

i can't one-handed hold my phone firmly enough like that. thumbs are always closer to the bottom.

**Comment by 8bitPit** [comment]
Their could also be an option to customize the alphabet/scrollbar size and position to adjust it to your needs.

**Comment by cauerego** [comment]
i hope this will get "low priority" and "not now" in any case! :D

it was just a random idea for a minor annoyance.

**Comment by 8bitPit** [comment]
You're right :P

**Comment by 8bitPit** [comment]
Some thoughts from @Rod911:
> You should be able to hide favorite apps from the app list without removing them from the favorites.
You normally won't be launching apps from the app list if you have it in the favorites.
IMO this will also reduce clutter in the app list.

**Comment by 8bitPit** [comment]
I've come to the conclusion to not hide the star at the top. Accessing your favorites by scrolling up is fast and comfortable if you're currently scrolling through your apps. However, the scrollbar might be resizable in the future (https://github.com/8bitPit/Niagara-Issues/issues/263).

**Comment by 8bitPit** [comment]
I'm sorry, I renamed the wrong issue, I fixed it. But if someone his here, because he'd like to hide is favorites from the app list, please take a look at: https://github.com/8bitPit/Niagara-Issues/issues/221

**Comment by cauerego** [comment]
i'm still very much annoyed by how difficult it is to get to letter A.

two new ideas would be helpful to me:

- bring star icon up, either graphically or on movement wise, so it's a higher effort to go there.

- likewise, with a bigger effort to go down from home, or from hitting home from the star, it'd go down to A.

please! 😁😘

**Comment by 8bitPit** [comment]
Thanks for your ideas @cauerego, maybe I'll try them out once I have more time.
