### ISSUE TITLE
Apps not in alphabetical order / Option to sort apps alphabetically

### ISSUE THREAD

**Issue by kmsram420** [8bitPit/Niagara-Issues#441]
Apps within each alphabet is not sorted alphabetically

**Comment by kmsram420** [comment]
Oh ok. I didn't knew that. Thanks

**Comment by deepaklunked** [comment]
A switch to disable this behavior would be good.

**Comment by kmsram420** [comment]
Reopening the issue for others to comment.

**Comment by kmsram420** [comment]
It makes sense to me but I thought there was some bug. I am closing the issue.

**Comment by 8bitPit** [comment]
@kmsram420 ah okay, I reopen it though, so other people can discuss here if a toggle is needed or come up with a better solution :)

**Comment by Liggliluff** [comment]
I don't have many apps, so no letter has apps that needs to be scrolled to. Always having the apps alphabetical would be preferred.

**Comment by deepaklunked** [comment]
Why can't we try this. Initially, let the apps be sorted alphabetically. Then based on the usage, only put those apps on top that are used more frequently, and the rest be sorted alphabetically. That way, the less used are still sorted alphabetically, and the most frequent apps are on the top.

**Comment by 8bitPit** [comment]
@deepaklunked that's kind of how I do it already. I just list apps you pinned on other launchers higher. I also place other apps (e.g. Play Store / Android's settings) on top of others.

**Comment by 8bitPit** [comment]
But you're right, I should adjust/enhance the algorithm.

**Comment by deepaklunked** [comment]
BTW, I really really love the launcher. Very simple and fast. Kudos to you.. Keep up the work..

**Comment by 8bitPit** [comment]
@deepaklunked thank you :)

**Comment by Liggliluff** [comment]
I really like the look of the launcher too. It just sucks that I can't have Google Translate (named "Översätt") to appear after Z, where I expect it to be.

So along with having a switch for reordering the apps under a letter by most used, a switch to use national alphabet or ISO alphabet would be great too.

**Comment by Hoomum** [comment]
To be honest I do think a toggle is the answer. Some people (like those with OCD or autism for example) like things to be ordered. Others are happy to keep the launcher set by usage

**Comment by scatterthought** [comment]
Hi all, this is my first comment. I'm not sure if there was any resolution, but I would also be in favour of a toggle for app alphabetical behaviour. As was mentioned before, I think it's fastest when you always know where an app is (e.g. Play Store always follows Play Movies & TV). It would be particularly helpful as I sometimes start at the wrong letter (O when looking for P) and scroll to find the app.

Great work on Niagara Launcher!

**Comment by deepaklunked** [comment]
@8bitPit 
Hi, I noticed you added the "basic feature" label to this issue. Does that mean you are working on bringing it to the app soon? Just curious.

**Comment by 8bitPit** [comment]
@scatterthought thanks, that makes sense. I've changed my mind and will maybe add a toggle in a future version.

**Comment by 8bitPit** [comment]
@deepaklunked I'm working on a pro version and categorized the requests in basic & pro features.  So the label means, it will be available in the free version. Btw, every feature which has been implemented will still be available for free.

**Comment by deepaklunked** [comment]
@8bitPit That sounds good. Hopefully, we get to see the pro version soon..

**Comment by 8bitPit** [comment]
@deepaklunked thank you :)

**Comment by zbhoy** [comment]
Any update on this? It's a daily problem for me having it sorted by usage.

**Comment by 8bitPit** [comment]
@zbhoy nope, not yet. Sorry.

**Comment by gingerzapps** [comment]
I would love a toggle! I saw a comment mentioning if you use Sync a lot it would be easier to have it automatically sort rather than scroll to the bottom of the S section. What I have trained myself to do is automatically jump to the next letter if I know an app is at the bottom of a letter group, then scroll up 1 or 2 apps rather than scrolling down through all the S's. Knowing exactly where an app with be within a list is much more convenient in the app drawer than usage based sorting. If apps are in an unexpected order I tend to open the wrong app accidentally often because I expect something to be right at the bottom or top of a section. Usage based sorting is fine for the main home screen favorites or common apps section, but the app drawer in my opinion should be predictable.

**Comment by 8bitPit** [comment]
A toggle has been added in v0.9.2: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by kpoxan** [comment]
thank you! You are the best.

**Comment by Liggliluff** [comment]
It's great to see that this is now implemented, making the app order consistent.

All that's left is the support for different alphabets, with #455
