### ISSUE TITLE
Option to disable Romanization

### ISSUE THREAD

**Issue by infodusha** [8bitPit/Niagara-Issues#442]
[bug] Apps with english and russian names are mixed.
E.g.
![screenshot_niagara_launcher_20181016-080934](https://user-images.githubusercontent.com/5677047/46994112-9cd00200-d11b-11e8-961d-f11b4f341278.png)

**Comment by Rod911** [comment]
I dont know how to pronounce that word but pretty sure that the clock belongs under C. ☺️
Jokes aside, non English languages are not yet completely supported, hopefully will be in the future.

**Comment by infodusha** [comment]
Rod991, it worked fine in older versions

**Comment by 8bitPit** [comment]
@infodusha that behaviour is intended, so you don't have too much letters on the scrollbar. For the romanization  process I am using the entries shown in the column "Passport (2013)" last one in that table: https://en.wikipedia.org/wiki/Romanization_of_Russian#Transliteration_table

**Comment by infodusha** [comment]
@8bitPit ok, then we need a feature to disable this =)

**Comment by 8bitPit** [comment]
@infodusha By looking at your screenshot I recognized that it's not fully supported yet. Moreover, can you please explain to me, why the new Romanization seems wrong to you? Unfortunately I cannot write in cyrillic, so I am having a hard time to implement Romanization correctly. Here is a sheets document I opened up, where you can tell me which letters are romanized wrongly.

**Comment by infodusha** [comment]
Ok, the problem was a bug. To fix it i renamed fitst letter in problem apps and then backuped names. Now i have only english letters in the list. I think it google backup bug(i recovered data recently, but a new niagara version come)
Romanization is a feature, i see, so it is fully good at passport 2003. But it is uncomfortable to mix english and another langs apps. So it is a good feature but i need to disable it.
Besides, would it be a donate link or an lisense app? I would buy.

**Comment by Liggliluff** [comment]
Wouldn't it be better to have this in the other direction? Display the Russian alphabet instead and have the option to sort Latin names under Russian letters, or Latin separate.

**Comment by 8bitPit** [comment]
@Liggliluff  I believe most apps names are not be translated into Cyrillic, when e.g. your phone's language is set to e.g. Russian

**Comment by Liggliluff** [comment]
@8bitPit You are probably right.
Then having the option between Latin and Cyrillic would be nicer. The Cyrillic alphabet is in a different order, and some users might prefer that order.

Users are also able to rename apps to make it suit their situation better.

**Comment by 8bitPit** [comment]
This is issue has been merged with #455
