### ISSUE TITLE
Optimize thumb navigation

### ISSUE THREAD

**Issue by Runee** [8bitPit/Niagara-Issues#443]
I love that this (very promising) launcher is focused on one-handed use, but it would be great to double down on it. 

When rearranging your favorite apps, it would make sense to drag them with your right thumb, instead of having to use your left hand. 

Also, I feel like there should be a lefthanded mode option for all the lefties out there. Or even a toggle, so that the interface can be easily mirrored.

**Comment by Rod911** [comment]
(#13)

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
