### ISSUE TITLE
French date is not capitalized

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#449]
![image](https://user-images.githubusercontent.com/9284845/47048427-a6e51580-d19a-11e8-9f5c-3989c0bd6207.png)

**Comment by AZMPlay** [comment]
Seems like this also happens in spanish

**Comment by 8bitPit** [comment]
I just checked how other apps are doing it and it seems like they don't capitalize the date as well:
![image](https://user-images.githubusercontent.com/9284845/57284941-7622ea00-70b2-11e9-945f-2b63cf6382e2.png)
That's why I'll close the issue for now, but let me know if I'm wrong thinking the date should start with a small letter in French.
