### ISSUE TITLE
Implement a global search in place of the app-only search

### ISSUE THREAD

**Issue by klemy** [8bitPit/Niagara-Issues#450]
I have a suggestion : Would it be possible to implement a global phone & app searching in the current app search bar ?

If I remember well, a searching interface has already developed in the Android SDK in order to be implemented in apps and to be used in launchers.

**Comment by 8bitPit** [comment]
Thanks for suggesting, do you mean searching for contacts (#334)?

**Comment by Rod911** [comment]
#336 you mean.

**Comment by 8bitPit** [comment]
Whoopsie, @Rod911 thx 😅

**Comment by klemy** [comment]
Hey @8bitPit and @Rod911, I have took a screenshot in order to show you the offline search integration in the Google search bar :
![screenshot_20181019-094726_google 1](https://user-images.githubusercontent.com/10001945/47233262-6b349080-d3d2-11e8-95e2-1cd18664dd54.jpg)

Here you can see :
- my search (letter "p")
- some online search prediction from google (indeed)
- 3 offlines searches from installed app
  - 2 from contacts
  - 1 from Trainline ; **the more interesting** (https://play.google.com/store/apps/details?id=com.thetrainline)

I have also tested with Asana (https://play.google.com/store/apps/details?id=com.asana.app) and it show me some uncompleted tasks.

**Comment by klemy** [comment]
With more investigations, I have found the system : it's the Firebase App Indexing (https://firebase.google.com/docs/app-indexing/) !

Perhaps is it possible to get the content of the database and use it in an another app than Google Search ?

**Comment by 8bitPit** [comment]
Thanks for your research @klemy, could you please repost your comments here: #58?
