### ISSUE TITLE
group/separate apps letters for better alphabet navigation

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#453]
my letter C and P are flooded. more than 9 apps in each, go below the screen when navigating through the alphabet scroll. there could simply be two C's and two P's on the list and the second one will go through the second part.

meanwhile, all other letters get less than 3 apps or so. lots with 1 app or even none.

granted, the zero letters don't even appear, so that's already optimized.

however, when M N O have altogether less than 5, they could all show the same "screen" with all their apps... except when touching O, the O would be on top or some way to highlight it.

**Comment by 8bitPit** [comment]
> my letter C and P are flooded. more than 9 apps in each.

Apps are sorted by usage to minimize the problem.

> however, when M N O have altogether less than 5, they could all show the same "screen"

Maybe, it could be confusing though, since some letters would be grouped and others aren't.

**Comment by 8bitPit** [comment]
> I just can't find where
@cauerego here you go: #359 :P

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.

**Comment by 8bitPit** [comment]
Fixed it 😉.

**Comment by cauerego** [comment]
well... just to say "i don't envision participating anymore"! 🥺

at least while it's closed source.

cheers! 😁😘
