### ISSUE TITLE
set maximum number of suggested apps at home

### ISSUE THREAD

**Issue by cauerego** [8bitPit/Niagara-Issues#454]
the default should be around 16. but perhaps it's nice to let us choose it somehow, instead of "reducing the number of suggested apps" settings, just let us slide through numbers.

i like the 1 screen without scrolling, but i prefer 2 screens at home: 8 with favorite and 8 with suggested. at least for now.

on the previous version, it was perfect like that!

but after the latest update, to 0.5.4, it broke down to 8. :(

**Comment by 8bitPit** [comment]
For many, 16 is way to much, most prefer having eight apps. However, in the next version, the algorithm will be adjusted: If you pinned more than eight apps, you would get still some suggestions from apps you use *very* often.
And I agree, a slider could be helpful.

**Comment by cauerego** [comment]
i'm getting mixed feelings here...

i read "yeah, sounds like a good and simple plan", the slider. yay! :)

then there's this tag "not now" and moved to "low priority"...

is it that complex to "just do it"?

at least now i know i'll have to go back on manually adding my favs for now. :(

cheers, i swear i'll stop to annoy you soon enough! ;)

**Comment by 8bitPit** [comment]
> then there's this tag "not now" and moved to "low priority"...
is it that complex to "just do it"?

It's not that difficult, but there are several reasons why I labeled it as low priority:
1. I believe it's not that urgent.
2. I am using a library from @Maxr1998 ([ModernAndroidPreferences](https://github.com/Maxr1998/ModernAndroidPreferences)) which doesn't support sliders yet.  
3. I want to take some time, to think about how the slider should exactly work (labels,values), or if there is an alternate solution which makes it redundant.

**Comment by Maxr1998** [comment]
Slides will probably be added soon, could do it next week if needed. But it makes sense to first take a look whether it's needed.

**Comment by cauerego** [comment]
i actually was picturing the only thing making it difficult was the slides ux/ui in itself, lol. glad to see that was indeed the case... those things still can get surprisingly complex, even today.

and i also hope for an alternate solution!

in any case, since there's a moving screen already, perhaps this setting could go there?

and then change the name to "organize home screen" as to also move suggestions around, while still their own section.

there could be a magical scroller there like the alphabet but with numbers, increasing or decreasing the amount of suggested apps only (i should probably update op title to reflect this, "home apps" was never the intention) with a smooth animation showing up and hiding up the lower apps, as we scroll up and down.

**Comment by 8bitPit** [comment]
That's a very creative way for a slider. The ability to move suggestion would break the usage based sorting though.

**Comment by cauerego** [comment]
so?

if i'm moving them, it is because i want to break the sorting and only use the suggestions per existence anyway.

there can always be a button to bring back the "sort by usage". :)

**Comment by cauerego** [comment]
yeah, it's probably not a good idea being able to move the suggested apps, not sure what I was thinking anymore... we could always favourite up the suggested app and then move them at will.

let's leave this at the slider.

**Comment by 8bitPit** [comment]
okay :)

**Comment by TheCombatBeard** [comment]
Can I add to this? When the slider does come around, can we bring it to zero suggested apps? I don't want my home screen littered with the apps I didn't put on there.

**Comment by 8bitPit** [comment]
@TheCombatBeard Yeah, possibly. Until then you can minimize the number of suggested apps in Niagara's settings (Features) and long press >& tap on "don't suggest" on the ones you don't like to see.

**Comment by henrov** [comment]
I would like to be able to set the total number of shortcuts to some arbitrary number. Or have it fill out the screen. Half my home screen is empty now (Oneplus 7 pro)

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2021). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2022 or later.
