### ISSUE TITLE
Custom Shortcut Icons

### ISSUE THREAD

**Issue by ghost** [8bitPit/Niagara-Issues#458]
It would be rad if we could change the icon of app shortcuts

**Comment by 8bitPit** [comment]
Yeah, at first I'll implement the option to individually change app icons :)

**Comment by GPAgethub** [comment]
https://github.com/8bitPit/Niagara-Issues/projects/1#card-14038870

**Comment by 8bitPit** [comment]
Implemented in v0.11.0 for shortcuts that are pinned.
