### ISSUE TITLE
Tips & tricks, e.g. tutorial on first launch

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#46]
Have a Splash Screen to help users understand the basic navigation, gestures etc. also point them to report any issues here

**Comment by 8bitPit** [comment]
Tips could also be shown in settings, sometimes even in the homescreen itself (just like the "set default launcher message").

**Comment by jakcharvat** [comment]
Honestly, I find that slightly too intrusive. I'm definitely against the idea of showing it on the homescreen, maybe I'd be OK with something like the suggestions in the settings on stock Oreo and Nougat, but I still think a Splash Screen would be the most user friendly method. Just my opinion

**Comment by 8bitPit** [comment]
Oh, I did not mean the Android nougat settings tips style. Just a dedicated section there, which is called "tips & tricks"

**Comment by zamber** [comment]
It's called a FRE (First Run Experience). Usually implemented as a side-scrolling presentation of core features or an overlay guiding through basic usage.

IMO it's a design anti-pattern. I did QA on an app that implemented it halfway through development and it was a massive PITA for automated and manual testing while it managed to fail explaining anything more than the Play Store description did.

Ideally the FRE would not block the user with pointless scrolling (people don't read this either ways as the pattern is overused in apps). Having slight nudges guiding to settings should suffice. Once in settings the user will be able to explore on their own (even if it means finding the Help or Tips & Tricks section).

**Comment by 8bitPit** [comment]
@zamber Good points!

**Comment by cauerego** [comment]
couldn't agree more with @zamber...

oh wait, i could! as much as i now hate to admit, Disco Jeff have so many such valid points: https://blog.codinghorror.com/level-one-the-intro-stage/

please, do not add tutorial on launch! let kids play and adults complain!! :D

**Comment by 8bitPit** [comment]
Hey guys, I finally added a small & nonintrusive tutorial. Instead of going through (or skipping) annoying tutorial screens, the user gets a few tips on their home screen, which they can check whenever they want.
