### ISSUE TITLE
Google Quick Search for Home Button

### ISSUE THREAD

**Issue by deba94** [8bitPit/Niagara-Issues#460]
It would be great to have the option of using Google Quick Search (like the swipe up option for the Google button) for "press home to search". It still pulls up installed apps, but has the added bonus of searching other local databases (contacts, for example) and performing a web search if all else fails.

**Comment by ShinobiWPS** [comment]
Use the search function before posting, this is already discussed in other opened/closed issues!

**Comment by deba94** [comment]
@ShinobiWPS Mind specifying which ticket this is a duplicate of? I did do a search and saw no duplicates, closed or open. 

This is specifically for adding Google Quick Search to the home button.
