### ISSUE TITLE
Static apps in the bottom

### ISSUE THREAD

**Issue by joser93** [8bitPit/Niagara-Issues#461]
Hello, I know that the app should be simplistic, but some apps should be static across any view, like phone app or your favorite browser than instead to scroll or search in your favorite apps.

**Comment by vulpes-vulpeos** [comment]
In my opinion it will kill unique design of this launcher.
You can add them to favourites and press back button when you are in app drawer to go back instantly to your favourite apps.

**Comment by 8bitPit** [comment]
Yeah sorry, a dock doesn't fit well with Niagara's design
