### ISSUE TITLE
[Request] Editable Icons

### ISSUE THREAD

**Issue by Guyzers** [8bitPit/Niagara-Issues#463]
Icons have a good impact on making the screen minimalist. So what I am thinking is:

1. Adaptive Icons (You Probably Know this already)

2. Manual Icon Change. You can change. The Icon by long tapping the app and tap the 'Edit Icon' option. You can either choose from an App Icon, the System Icons or your Galerry.

Just a small request that could make the app better.

**Comment by 8bitPit** [comment]
Thanks for your requests @Guyzers, here are the corresponding issues:

> Adaptive Icons

#448 

>Manual Icon Change.

#41
