### ISSUE TITLE
Custom wallpaper?

### ISSUE THREAD

**Issue by cloudkicker24x** [8bitPit/Niagara-Issues#466]
I keep setting the wallpaper to the image I want but then it randomly gets changed constantly how do I stop this

**Comment by bencherianskaria** [comment]
Yup same here. I set wallpaper using from gallery or from apps like Wallpaperscraft. But it changes back to stock wallpaper

**Comment by cloudkicker24x** [comment]
So obnoxious literally the only thing keeping me from exclusively using this launcher

**Comment by 8bitPit** [comment]
That's weird, does this happen to you on third party launchers like Nova / Lawnchair launcher as well?

**Comment by bencherianskaria** [comment]
Nope. Doesn't happen with Nova or Microsoft launcher

**Comment by cloudkicker24x** [comment]
Thank you!

**Comment by 8bitPit** [comment]
> it takes you to a page containing all the stock images that end up replacing the wallpaper I select.

Sorry I don't fully understand what you mean, can you please provide a screenshot? You could also try to reset your defaults of your wallpaper app which opens when you click on "wallpapers":
![image](https://user-images.githubusercontent.com/9284845/47383798-c71a5480-d705-11e8-86d0-65bfda402bfa.png)

**Comment by 8bitPit** [comment]
Does the issue still persist? If so, feel free to open it again.
