### ISSUE TITLE
Custom font style

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#467]
Like bold, italic, light, condensed, etc.

**Comment by Montell2099** [comment]
Is this, together with clock font customization, coming soon?

**Comment by orionyt** [comment]
I want to change the color, blue, red, black, yellow, etc...

**Comment by 8bitPit** [comment]
@orionyt see: #20

**Comment by 8bitPit** [comment]
@Montell2099 sry, currently other features are on my to do list for now, so this may take a while.

**Comment by Montell2099** [comment]
Will there perhaps also be a selection of appropriate fonts to chose from, or just custom font styles? Would be nice to be able to scale down the size of the clock as well, but I guess that falls under another category than this topic.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
