### ISSUE TITLE
When I uninstall an app that has been marked as favorite, it still shows up on the home screen. 

### ISSUE THREAD

**Issue by anshumanpati6** [8bitPit/Niagara-Issues#469]
And it stays there until the item is removed from favorites. I know it's a minor bug. But still.

**Comment by 8bitPit** [comment]
Thank you @anshumanpati6, I will fix the bug asap :)

**Comment by disacrol** [comment]
Just wanted to add the same happens for any app automatically added to favorites (i.e. for being widely used)

**Comment by 8bitPit** [comment]
Oh, you're right 😅 the next alpha will fix it. Thanks for letting me know @disacrol!

**Comment by disacrol** [comment]
Yep, and fixed in public beta. This can be closed.

**Comment by 8bitPit** [comment]
Neat!

**Comment by 8bitPit** [comment]
Fixed in v0.6.0
