### ISSUE TITLE
Media player not showing / support more Music Players

### ISSUE THREAD

**Issue by lepa22** [8bitPit/Niagara-Issues#47]
I saw in a couple of screenshots that there is a music widget. However, when I play music (I am using BlackPlayer) I don't see that. Is this feature supported for certain music players?

**Comment by 587saboor** [comment]
Yes, as far as i know, it supports spotify

**Comment by jakcharvat** [comment]
should support most players, although for example Samsung Music integration is not perfect. You might need to allow the launcher to read your notifications

**Comment by 8bitPit** [comment]
You have grant notification access (should mention it somewhere in the app). All players using the "Media notification template" from Android. For example, on Android 8 and higher, it looks like this:
![image](https://user-images.githubusercontent.com/9284845/44954302-50e53880-aea0-11e8-8b13-53e084788ab6.png)
(image source: Material design)

Reported players, where it isn't working: Apple music & Samsung music

**Comment by 8bitPit** [comment]
Yeah, it could be possible to support other media players as well I just have to read it's notification data and see, if there is an option to get the picture. I'll be adding a button to send me this information in Niagara settings.

**Comment by jakcharvat** [comment]
Retro Music with "Classic  Notification Style" enabled doesn't work either. just with the default one

**Comment by DroidFreak32** [comment]
One more to add to the list is Poweramp music player. But I'm on nougat .

**Comment by Maxr1998** [comment]
Audible is also said to have issues.

**Comment by Maxr1998** [comment]
Good point. Will do some tests later today.

**Comment by 8bitPit** [comment]
Apparently, it’s also not working for “Vanilla Music”.

**Comment by Shinra04** [comment]
Add an option in settings to grant notification access. I can't seem to do so from anywhere currently.

**Comment by 8bitPit** [comment]
@Shinra04 it should appear in your favorites list.

**Comment by Shinra04** [comment]
I don't see any such option to grant the permission there. Players like SoundCloud work fine, but Poweramp does not.

**Comment by jakcharvat** [comment]
That's not an issue of the permission, that's an issue of the notification not being recognised

**Comment by Shinra04** [comment]
Oh okay. It's probably being looked into already then.

**Comment by 8bitPit** [comment]
@lepa22 @Shinra04 @DroidFreak32. You can now send me those media notification details since the latest Update. Click Settings > Advanced > Developer Options. I can check if those media players can be supported.

**Comment by Shinra04** [comment]
Idk if it's okay to send here but here it is:

--- com.maxmpz.audioplayer - ---
Notification(pri=1 contentView=com.maxmpz.audioplayer/0x7f030056 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 category=transport vis=PUBLIC)
[android.icon=2130837833]
[android.appInfo=ApplicationInfo{f2524fc com.maxmpz.audioplayer}]
[android.originatingUserId=0]

**Comment by 8bitPit** [comment]
I did some research and found a possible solution to solve the problem for most of those mentioned players, I will give you an update soon.

**Comment by Scorpionk1** [comment]
Okay, you will succeed. great job!
