### ISSUE TITLE
Weather widget not properly working

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#471]
Tapping the weather widget part (when enabled in settings) opens Google weather page as expected. But if I have used Google app recently (e.g to perform a search), it opens the Google app in that search screen instead.

Steps to reproduce:
1 - enable both weather AND Google button in Niagara settings
2 - open Google app, tap recents nav button, swipe off Google app (to ensure it is killed)
3 - tap the weather widget: OK, Google app is opened on the weather screen
4 - tap home nav button and swipe up from the Google button, do a simple search (in my case, I searched for 'iceland whales' 😊)
5 - tap home nav button, and tap again the weather widget: NOT OK, 'iceland whales' search results page is shown instead
6 - tap recents nav button, swipe off Google app (again, to ensure it is killed)
7 - tap the weather widget: OK, Google app is opened on the weather screen

So it seems the weather widget is not forcing Google app to switch to its weather page as long as it is already running in background.

Note that in my case I have free RAM memory to spare, so this easily reproducible. This might not be a problem on devices with less RAM or different memory management settings that eventually lead to the Google app to be killed the moment it goes to background when home nav button is tapped on step 4.

**Comment by disacrol** [comment]
What do you know, Google app was missing an update from 19/10, and this is no longer reproducible after the update.

First time the "please check if you have the latest version" argument was actually valid on me 😅

Feel free to close the issue. Thanks!

**Comment by Rod911** [comment]
Cheers

**Comment by 8bitPit** [comment]
Great! Btw @disacrol you described your in so much detail, love it :)

**Comment by disacrol** [comment]
@8bitPit as a dev I am used to solve issues and suffer from the lack of detail, I couldn't do that to you 😁

**Comment by 8bitPit** [comment]
@disacrol Awesome, thanks again and happy coding!

**Comment by disacrol** [comment]
@8bitPit I'm afraid this is reproducible again. I'm now using the latest alpha but I'm almost pretty sure this was also reproducible in the latest beta from the play store.

Steps to reproduce are the same.

Xiaomi Mi A2
Oreo 8.1

**Comment by disacrol** [comment]
I'm using Google app version 8.49.4.21.arm64, updated around a week ago.

I can record a video if it helps.

**Comment by 8bitPit** [comment]
Oh sorry, forgot about the issue, thanks for reminding 😅. I just fixed it, the update will be available in around a week.

**Comment by disacrol** [comment]
Thanks!

**Comment by disacrol** [comment]
It is, just checked, thanks.
