### ISSUE TITLE
Feature request/traditional app drawer

### ISSUE THREAD

**Issue by twiztidgamer** [8bitPit/Niagara-Issues#473]
Please add the option to place the scrollable app drawer with an arrow at the bottom of screen that can be swiped up to open the stock Android P grid style app drawer layout while leaving every other aspect of y'all's unique home screen layout as is currently 

Thanks in advance for considering my request

**Comment by 8bitPit** [comment]
Thanks for your request. A traditional app drawer would be against Niagara's design. Also, I believe, adding a second app list/grid would be unintuitive. For more details, visit #81
