### ISSUE TITLE
Music widget interaction kill the music app

### ISSUE THREAD

**Issue by Francesco-Musio** [8bitPit/Niagara-Issues#474]
I use Spotify to listen to music. While i listen to something the informations are displayed fine in the widget, but when i try to stop the music or change song the widget cose itself and shortly after Spotify is killed.

**Comment by 8bitPit** [comment]
Yeah that's intentional. You don't need to see an artwork / show media controls if no music is playing

**Comment by Francesco-Musio** [comment]
I understand that when I close the app the widget goes away, but if while I listen to something I try to change the song the app is killed

**Comment by 8bitPit** [comment]
Oh that's a strange bug. Does the widget disappear in Android's notification tray as well?

**Comment by Francesco-Musio** [comment]
Yep. I'm asking just in case it's a bug, but I have a LeEco Le1 and it's a little buggy, so it cancellare also be a problem in my side

**Comment by 8bitPit** [comment]
Ah okay, then I cannot help you, sorry. Either your OS or Spotify has a bug.
