### ISSUE TITLE
Google Wallpapers app doesn't work

### ISSUE THREAD

**Issue by Rojo10000** [8bitPit/Niagara-Issues#477]
When I try to update my wallpaper to the option of one different wallpaper each day, it doesn't work. However, if I put a regular wallpaper from the same app (without the "one each day" option enabled), it does let me change it. I think that option is treated as a live wallpaper, and doesn't seem to be supported by Niagara Launcher.

**Comment by disacrol** [comment]
Yes, probably a problem with Google wallpapers or how Niagara interacts with it. I use Muzei and it switches wallpaper daily without any issues.

**Comment by 8bitPit** [comment]
Live wallpapers should work with Niagara, there are some wallpaper related bugs though. Can you please provide me with more details in which way it's not working (e.g. it doesn't change or show up at all)?

**Comment by Rojo10000** [comment]
So I go to the bottom of the app list and open the wallpaper settings (under Niagara settings), and the Google Wallpapers app opens automatically. Then, I proceed to open one of the many categories the app has (such as the Earth), and select the option to change the wallpaper daily. Afterwards, the app shows me a wallpaper and it lets me select if I want it for the main screen, the lock screen or both. Then I select both, but it automatically changes the backround to one with red feathers (I think it's a default one or something). However, if I choose one wallpaper directly (without the daily option), it does change the background.

**Comment by 8bitPit** [comment]
Ah, gotcha. I am using Niagara on an Essential phone and it works there, so I cannot reproduce the issue. Nevertheless I will search for the bug. So, I guess it does work on other launchers, like nova or Lawnchair?

**Comment by Rojo10000** [comment]
Yes, I had Nova Launcher previously and it worked fine.

**Comment by 8bitPit** [comment]
Does the issue still persist? If so, feel free to open it again.
