### ISSUE TITLE
Swipe individual notification scrolls to bottom

### ISSUE THREAD

**Issue by joser93** [8bitPit/Niagara-Issues#479]
Hello.

This is a current bug and maybe not many noticed, when you receive a lot of notification (some social app for example), and you want to remove a single notification using the launcher notification list per app, it scrolls at the bottom of the notifications list.

Should keep the scroll at it's position or adjust for the list with the removed notification.

**Comment by 8bitPit** [comment]
Weird, it does work on my device. Could you please provide a video / GIF?

**Comment by joser93** [comment]
Sure, I did more tests and I guess that the problem has to be linked with some actions that displays in the scroll.

http://imgur.com/a/30atFMS, sorry for the gift quality, but still shows the bug in action. I hope will work for you.

**Comment by 8bitPit** [comment]
I tested swiping away notifications from various apps, one of them had app shortcuts. The error only occurred on the latter, so you're right. Thanks for sending the video and for your guess.

**Comment by 8bitPit** [comment]
Fixed in v.1.4
