### ISSUE TITLE
Adjustable notification filter

### ISSUE THREAD

**Issue by Ayush0298** [8bitPit/Niagara-Issues#481]
First of all I really like the launcher. Congrats.,..
But it is not showing Notifications for some apps as it shows for other apps.(on right swipe). And these apps include Google Play Store , YouTube, Phone dialer(for missed calls), and several other apps.
Hope you got what I'm saying.
Looking forward for solution.
Thanks....

**Comment by disacrol** [comment]
@8bitPit isn't this a bug? Or is it intended for now only some types of notifications are shown in favorites?

**Comment by 8bitPit** [comment]
Thanks @Ayush0298. Niagara has an inbuilt notification filter that blocks some messages from showing up as a preview (you can still swipe that app to the right you can read the notification). Maybe I'll add an option to change the filter, so you can individually adjust which apps / notification categories / importance levels get shown.

**Comment by Ayush0298** [comment]
For some apps ( Flipkart And Google duo) it is not even showing on right swipe.

**Comment by 8bitPit** [comment]
Oh okay, can you please send me a notification log then? (Niagara's settings > Send notification log) and please include the issue number (481) in the mail.

**Comment by Ayush0298** [comment]
Is it necessary?

**Comment by 8bitPit** [comment]
It isn't necessary, but I cannot see why the notification isn't shown without getting the log.

**Comment by Ayush0298** [comment]
Ok I have sent the required..

**Comment by 8bitPit** [comment]
I received your message, it reads that you disabled notification dots's for Flipkard. Enabling them in Flipkard's app info should solve your issue.

**Comment by Ayush0298** [comment]
It was ON ...
It was enabled from beginning....

**Comment by 8bitPit** [comment]
There are two notification dot toggles which are important. One of them if is a system wide switch and the other one is for your individual app. Please make sure both, are enabled. Furthermore DND can override the global toggle.
![image](https://user-images.githubusercontent.com/9284845/47458025-e635e680-d7d8-11e8-89df-65dc6e50f108.png)
![image](https://user-images.githubusercontent.com/9284845/47458030-e7ffaa00-d7d8-11e8-9af4-930ffd9fc8e0.png)
![image](https://user-images.githubusercontent.com/9284845/47458033-ea620400-d7d8-11e8-8494-3d295fd40a06.png)

**Comment by Ayush0298** [comment]
All permission regarding notification are granted. Can I share SS to you?

**Comment by 8bitPit** [comment]
Sorry, what do you mean by "SS"?

**Comment by 8bitPit** [comment]
Btw is the dot showing up on other launchers?

**Comment by Ayush0298** [comment]
Yes. Earlier I was using Microsoft Launcher and it was all fine.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
