### ISSUE TITLE
Make the launcher utilise the entire screen on devices with 18.5:9 aspect ratio 

### ISSUE THREAD

**Issue by GigaFyde** [8bitPit/Niagara-Issues#482]
So far I'm very pleased with how the launcher performs and feels.

However, on my Samsung Galaxy A8 (2018), the clock is positioned rather low on the screen,
which leaves quite a gap at the top,

Could this be improved so that the launcher stretches from the top to bottom?

![screenshot_20181020-131319_niagara launcher](https://user-images.githubusercontent.com/8044811/47347982-c0adbd80-d6b0-11e8-95bb-f9563c6b93a8.jpg)

**Comment by 8bitPit** [comment]
Thanks, please refer to #112

**Comment by GigaFyde** [comment]
@8bitPit Apologies, I searched for a duplicate before posting this, and it seems I did not look close enough.
