### ISSUE TITLE
Quick-Close of spotify tile shown in home screen

### ISSUE THREAD

**Issue by Chairos88** [8bitPit/Niagara-Issues#483]
As the title says, it would be awesome to have implementation of a quick-close feature that allows spotify closure from the tile shown in the home screen, without needing to open the app again. I'd suggest to use the long-press action to show a menu displaying various properties or another viable option is to allow lateral sliding of the tile to close it.

**Comment by 8bitPit** [comment]
@disacrol is right, you can close the music widget by swiping it away
