### ISSUE TITLE
Music player not working / Media player not showing up

### ISSUE THREAD

**Issue by berdzena** [8bitPit/Niagara-Issues#485]
Music player widget not working with poweramp player. Other players like jetaudio is working well. Im on huawei p8 lite 2017 with android 8.0

**Comment by 8bitPit** [comment]
Here is a section from Niagara's FAQ which could help:

> <strong>Media player:</strong>
> <ul>
> <li>It&rsquo;s not showing up: you must enable notification dots &amp; your media player has to support that feature.</li>
> <li>Artwork not showing / Controls not working: Please contact the developer of your music app and ask him if he can support transport controls &amp; implement proper media sessions.</li>
> <li>Blurry artwork: Disable &ldquo;Blur on lock screen&rdquo; in your player&rsquo;s settings.</li>
> <li>Is visible even when not playing a song: Will be fixed soon.</li>
> </ul>

**Comment by xu67100** [comment]
Hi Guys,
I use to listen my music and for information i think i got the same "issue". The player appears in the notification center but not above fav apps.
(I have podcast addict which is perfectly fonctionnal). Thx

**Comment by berdzena** [comment]
For local music... Use STELIO music player, its working perfectly with Niagara launcher..

**Comment by xu67100** [comment]
Indeed. Thanks for your work. Good Luck ! See you.

**Comment by 8bitPit** [comment]
You could try to download [Android Auto](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead&hl=en). The app is made by Google and also shows media controls for other apps. With that app you can test if it was me or the developer of the media app you're using who messed up :P

Just install the app and start playing music. The media player widget should show up. If e.g. it doesn't contain the artwork of thze song, it wasn't provided by the media app.

**Comment by 8bitPit** [comment]
For those of you who don't have access to the app via Play Store, you can also download the apk here: https://www.apkmirror.com/apk/google-inc/android-auto/ (Apk-mirror)

**Comment by Dedisurya** [comment]
Pop up control music button of application You2mp3 is not pop up. So i can not to control the music when i want it music play or pause and another. When i use original launcher of my smartphone the pop up menu of you2mp3 is show pop up, but when i use this launcher that is nothing.

**Comment by 8bitPit** [comment]
@Dedisurya thanks for letting me know does it work with Android Auto?
> For those of you who don't have access to the app via Play Store, you can also download the apk here: https://www.apkmirror.com/apk/google-inc/android-auto/ (Apk-mirror)

**Comment by 8bitPit** [comment]
Please read https://niagaralauncher.helpscoutdocs.com/article/11-media-player-widget-issues for more info.
