### ISSUE TITLE
Bug report: notification bar clock frozen

### ISSUE THREAD

**Issue by ravishankarurp** [8bitPit/Niagara-Issues#486]
I've noticed that the notification bar clock on the top right corner is currently frozen for me since last night. Currently reads 8:00:56 (I've enabled seconds display), but when I pull down the notification bar, the clock on the top left corner is okay.

**Comment by 8bitPit** [comment]
The status bar on your phone is not controlled by your launcher, so that's an Android framework or Custom Rom bug
