### ISSUE TITLE
choose the icon of the application you want

### ISSUE THREAD

**Issue by MangaBlaze** [8bitPit/Niagara-Issues#489]
hello, I would like to ask if in the next version of the application, or in the final version, will be introduced a way to choose the icons of their applications, even from different iconpacks ... (for example, the icon of WhatsApp chosen by an iconpack and the telegram's icon chosen by another). For what I've noticed, for now, you can only keep the default icons from each iconpack ... I hope my idea is taken into consideration, best regards

**Comment by Rod911** [comment]
See #41
