### ISSUE TITLE
Rounded music player icons

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#49]
![like this](https://image.flaticon.com/sprites/new_packs/151845-music-player-icons.png) 
Kinda like that but without the extra buttons ofc

**Comment by jakcharvat** [comment]
Wouldn't this sorta fit under #18?

**Comment by 587saboor** [comment]
@jakcharvat kinda, but this is for icons, not artwork

**Comment by jakcharvat** [comment]
I feel they could be merged together. Really similar requests, complementing each other. Let's see what @8bitPit says...

**Comment by 8bitPit** [comment]
Yes, merging them is a good idea

**Comment by 8bitPit** [comment]
closing it, merged with #18
