### ISSUE TITLE
Suggest more most used apps

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [8bitPit/Niagara-Issues#493]

**Comment by 8bitPit** [comment]
The recommendation algorithm will be tweaked again in the next version, so more most used apps will be shown again.

**Comment by disacrol** [comment]
@8bitPit but can there be more than 6?

**Comment by Rod911** [comment]
What do you mean? I get 9. I haven't set any favs.

**Comment by disacrol** [comment]
Maybe it is related with the recommendation algorithm then, that seems to consider the number of favs. I have 6 most used currently, but as soon as I add a favorite, i only get 5 most used.

I've set 'smallest' icon size, so a least 2 or 3 more apps would fit in the home page just fine without any scrolling.

**Comment by 8bitPit** [comment]
@disacrol yes, the algorithm tries to show around 8 apps in the home screen (+/- some apps if you launch them (in)frequently).

**Comment by 8bitPit** [comment]
Duplicate of #454
