### ISSUE TITLE
Pie integration?

### ISSUE THREAD

**Issue by kelahrim** [8bitPit/Niagara-Issues#494]
Hello everyone! I'm using Niagara on a Pixel 3. Any thoughts on Pie integration? The swipe up for recents gesture in Pie has a Google search bar and your five most recent apps below (in the native launcher). In Niagara, this is just open space. I know most used apps make their way to your favorites bar but the open space would be better utilized with this native functionality I think.

**Comment by kelahrim** [comment]
Apparently this is a repost. My bad!

**Comment by kelahrim** [comment]
Apparently this is a repost. My bad!

**Comment by 8bitPit** [comment]
No problem :)
