### ISSUE TITLE
App actions/notifications close animation

### ISSUE THREAD

**Issue by Raka30** [8bitPit/Niagara-Issues#497]
when I slide from the logo icon to the right there will definitely be a "no new notification" or another pop up like Spotify will appear
well here the bug is when after the slide and back, the animation is not smooth, indeed there is no animation, unlike when dislide, please fix it, I really like your launcher and as much as possible I will support you

**Comment by 8bitPit** [comment]
Thanks, I'll add an animation just don't know which one.

**Comment by 8bitPit** [comment]
Added animation in v0.7
