### ISSUE TITLE
Increase font size of Alphabet on RHS of Home screen

### ISSUE THREAD

**Issue by ghost** [8bitPit/Niagara-Issues#498]
Current version as of this writing has font size in bubble that is too small for me to read. I have weak eyesight. 

If I put my thumb on the alphabet "scroller" the individual alphabet in the bubble is too small for me to see clearly. 

Kindly enable a setting to increase the size of this bubble alphabet. Thanks.

**Comment by 8bitPit** [comment]
That's a good idea, I'll implement that. In the meantime, you could increase the system's font size.

**Comment by Anitaislam** [comment]
I am very excited about the whole situation.

**Comment by Anitaislam** [comment]
This is great 🏡

**Comment by 8bitPit** [comment]
Merged with #263
