### ISSUE TITLE
Music widget not showing details for Samsung Music

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#5]
Android 8.0.0, Galaxy S8

The music player shows a black space instead of the cover, no labels (song name, artist), however the controls still work. 

It works with any music player other than Samsung Music for me. Samsung Music is the only one with that issue. 

Please refer to [this screenshot](https://photos.app.goo.gl/uSY7sKRa51EwzyDc8).

**Comment by 8bitPit** [comment]
So, im closing this issue, bc #47 has more information in it's comments
