### ISSUE TITLE
Letter scrollbar below Apps

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#50]
Not sure if this is intentional, but when scrolling through the alphabet, the current letter is shown behind the App list, rather than over. just seems kind of weird. 

refer to this screenshot: https://photos.app.goo.gl/ZZFY6ZueY4kBNLyHA

**Comment by 587saboor** [comment]
@jakcharvat that is made in part of a fix for the weird bug that has no name, once it is fully confirmed as fixed, this bug may automatically fix itself

**Comment by jakcharvat** [comment]
So you think it's related to #42?

**Comment by 587saboor** [comment]
@jakcharvat ye

**Comment by 587saboor** [comment]
@jakcharvat whoa i just realized we hit 50 issues

**Comment by 8bitPit** [comment]
@jakcharvat yup it's related and not intentional.
