### ISSUE TITLE
Bug with Deezer notification

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#500]
When playing music using Deezer, the artist of the playing song is never shown on the notification area in the main screen. No problem in the actual notification.
What is more, the area where the artist name should appear is empty but, in case I have played anything before using another app, that artist is shown instead, even if I have killed the app and notification.

For example:
1 - Start playing AC/DC - Thunderstruck on Spotify, return to home screen: notification displays both artist and name correctly
2 - Start playing Queen - Bohemian Rhapsody on Deezer, return to home screen: notification says I'm listening to AC/DC - Bohemian Rhapsody (now wouldn't that be something?)

Same happens even if I killed Spotify or ditch its notification. It's like it's getting artist info from cache or something. 

If I restart my phone however, and just open Deezer and play a song, only the song name is displayed: artist below is empty.

Could you check? Let me know what can I do to help.

Thanks

**Comment by Rod911** [comment]
Can you "send notification log" under advanced settings and a screenshot of home screen if possible to the dev. Make sure you dismiss other notifications.

**Comment by disacrol** [comment]
Just did so, in three separate steps to better illustrate the issue.

**Comment by 8bitPit** [comment]
Thanks a ton for your detailed explanation when the media player info doesn't update. I could reproduce the bug and fixed it afterwards. The patch will be available with the next update in a few days.

**Comment by disacrol** [comment]
Good to know, thanks.

**Comment by Rod911** [comment]
Also congrats on 500 issues Peter 👏

**Comment by 8bitPit** [comment]
Thanks @Rod911, I'm glad issue 500 is such an good example how a bug report should look like :)
Also thanks again @Rod911 for managing the issue page, you're helping me a lot.

**Comment by mzpro10** [comment]
That's weird. I have Deezer and I don't experience that problem you described...

**Comment by disacrol** [comment]
@mzpro10 do you see both the title and the artist of the song? In the notification area of the launcher's home page?

**Comment by mzpro10** [comment]
@disacrol I just tried it out and you're right artist names don't show. That's probably because deezer have designed a custom TextView for the artist name but used the general notification title for song name where Niagara is able to access but can not target the custom TextView of the artist name. I don't think they are willing to fix it for every app but Deezer is a popular app.

**Comment by disacrol** [comment]
@8bitpit seems to have fixed it already. I didn't know that was the cause, do you have any idea why Deezer uses a custom TextView?

**Comment by mzpro10** [comment]
@disacrol using a TextView enables styling. If you see the artist name has a smaller font and different text color, that would not have been available if they just used the secondary text property of the notification object.

**Comment by disacrol** [comment]
I see. @8bitpit are you parsing Deezer's text view on the upcoming patch? Or did you just make sure 'earlier' notifications' artist name doesn't show up?

**Comment by 8bitPit** [comment]
@disacrol I do not extract the media information from the notification, I get it from the current [media controller](https://developer.android.com/reference/android/media/session/MediaController.html#getMetadata()) instead. I don't know why Deezer doesn't set the artist name there.

**Comment by disacrol** [comment]
@8bitPit no chance to fix it specifically for Deezer? Or find some generic and lightweight way to lookup missing notification information? Not sure if Deezer is the only media player with this problem, and I'll be using Deezer for a while.

**Comment by 8bitPit** [comment]
There are two ways to get the artists name & icon. Either from the notification directly or from the current media controller. I am currently using the latter, because a lot of players use custom notification styles where you don't have access to it's content. I could introduce some kind of toggle where you can switch between those modes, but that would be still an unpleasing solution imo.

**Comment by disacrol** [comment]
@8bitPit I'm closing this, seems fixed on the latest alpha.

**Comment by 8bitPit** [comment]
Great!
