### ISSUE TITLE
Some unexpected actions 

### ISSUE THREAD

**Issue by Shi-Ao** [8bitPit/Niagara-Issues#504]
1. When I using the "Samsung Music." I sometimes can't see the wedgit at home page, and sometimes it shows up, but disappear quickly.

2. The notification spot doesn't work well. It never showed up since I started using this app. By the way, I've accepted the app to use the system data.

(I'm using Samsung Galaxy Note 3 LTE version)

**Comment by 8bitPit** [comment]
The media player only works when the notification listener is active. You can check that if you go to send notification log in Niagara's advanced settings. If the log reads "listener not connected" restart your phone and check again. Also refer to #485 & #201.

**Comment by OceTech** [comment]
My music will stop playing randomly if I'm on the home screen.  I generally use YouTube Music.
