### ISSUE TITLE
Alternative open app animations

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#507]
E.g. a slide animation.

**Comment by mzpro10** [comment]
Not a bad idea

**Comment by disacrol** [comment]
An interesting idea worth polling.  Actually, what about asking beta testers about their opinion on specific design ideas (I mean when an alpha/beta channel exists)? Via push notifications. Just so that you get feedback also from users not usually checking telegram or GitHub. Just an idea.

**Comment by briancalderon** [comment]
Slide in from bottom has always been my favorite animation type on my current launcher.

**Comment by polarhive** [comment]
It'd be amazing to have the app opening and closing animations as in lawnchair and the OnePlus launcher ported to Niagara.

**Comment by disacrol** [comment]
This. I fancy the animation used in lawnchair.

**Comment by 8bitPit** [comment]
@polarhive & @disacrol afaik  the android 9 animation cannot be achieved without using magisk modules or something similar: https://plus.google.com/+CliffWade/posts/fHRScGVCBf6

**Comment by ssssamstrup** [comment]
Would love circle reveal as an option as well, from where you pressed and outwards.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.

**Comment by HerrBlauzahn** [comment]
I know that it's not 2021 but recently the app opening animation changed so I figured I try to convince you to give (pro) users the option to choose the opening animation as it would be nice to do so.
Hope you reconcider your scheduling with this feature, have a nice day.

**Comment by 8bitPit** [comment]
Hi @HerrBlauzahn, the reason why we don't provide alternative launch animations is because we try to keep the launcher as simple as possible. In this particular case I think it wouldn't be impactful enough, you can read more about Niagara Launcher's design principles here: https://help.niagaralauncher.app/article/8-niagaras-design-principles
