### ISSUE TITLE
Smart prediction

### ISSUE THREAD

**Issue by Dreamer-4pda** [8bitPit/Niagara-Issues#508]
Please, add smart prediction based on time and location, like in Nokia Z launcher. 
With Z launcher you not need use app drawer, because needed app already on screen.

**Comment by mzpro10** [comment]
Why don't you just use the freaking Z Launcher!?

**Comment by Dreamer-4pda** [comment]
Because Z Launcher stuck in alpha 
Niagara looks like perspective project
I can't find any launcher with prediction better then in Z
I like Niagara, I love smart prediction why I can't wish mix it?

**Comment by disacrol** [comment]
Of course you can wish. It's a good suggestion, and this is the best place for introducing new ideas. Actually I think there is already a suggestion around here on GitHub about location-based / wifi / Bluetooth connected -driven suggestions. I'm on mobile, but look around.

**Comment by 8bitPit** [comment]
Thanks for your suggestion @Dreamer-4pda and thank you @disacrol for linking the related issue.
