### ISSUE TITLE
Drawing letter

### ISSUE THREAD

**Issue by Dreamer-4pda** [8bitPit/Niagara-Issues#509]
Please add ability to draw letter above screen for quick search, like in Nokia Z Launcher.

**Comment by mzpro10** [comment]
And make sure to make it easy to disable cz it's really useless

**Comment by Dreamer-4pda** [comment]
cz?

**Comment by AtomAntReturns** [comment]
Fantastic idea. I second this

**Comment by 8bitPit** [comment]
Yeah, that was a cool idea from the Z Launcher team. However, imo it looks like it's faster to either scroll on the right bar or open search, so it's unnecessary.

**Comment by nlko** [comment]
The thing is that in z-launcher when I'm searching, I'm searching through apps and through users too. This way you I don't necessary have to pin contact, telephone, or text apps on the main screen to quickly interact with them.

**Comment by Dreamer-4pda** [comment]
@nlko, yep, in Z launcher I open app drawer or contacts once at month or less. All needed apps always placed on screen. If I need different app, I draw letter.
I watch for Niagara, but use Z Launcher.

**Comment by 8bitPit** [comment]
@nlko maybe #336 might interest you.

**Comment by berdzena** [comment]
Sorry but i dont think scroll is more faster then search by gestures.. Im using z launcher and believe me its more faster..
Thanks..
