### ISSUE TITLE
Another Niagara launcher

### ISSUE THREAD

**Issue by lepa22** [8bitPit/Niagara-Issues#51]
Searching in google for "niagara launcher" returned this launcher with the same name.
![niagara2](https://user-images.githubusercontent.com/16370046/44972001-586c1680-af60-11e8-909c-948efd13dc54.jpg)

**Comment by 8bitPit** [comment]
I noticed that, too. Here is something interesting:

That launcher             |  Cm Launcher
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/9284845/44973365-9404e180-af5c-11e8-9534-31d7438528e0.png) | ![image](https://user-images.githubusercontent.com/9284845/44973395-b696fa80-af5c-11e8-99b2-2712f35558c8.png)


That launcher             |  Cm Launcher
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/9284845/44973365-9404e180-af5c-11e8-9534-31d7438528e0.png)|![image](https://user-images.githubusercontent.com/9284845/44973515-1a212800-af5d-11e8-8742-f074635c6bf8.png)

🤔🤔🤔

And the devs recent apps:
![image](https://user-images.githubusercontent.com/9284845/44973238-2d7fc380-af5c-11e8-82d9-5a4e75056af2.png)

**Comment by lepa22** [comment]
Do you think we could report it or talk to the developer?

**Comment by jakcharvat** [comment]
Thing is, good so was released before your Niagara Launcher @8bitPit. What exactly do you want to report him for!

**Comment by lepa22** [comment]
I don't know, faking apps? CM launcher is developed by Cheetah Mobile, so this guy is either faking CM, even using their screenshots and logo, or actually is Cheetah Mobile using another profile for marketing purposes.

I don't know if someone can report an app for these reasons, that's why I'm asking.

The other alternatives could be that @8bitPit changes the name of his launcher, which I don't think it would be something that he wants to do, or else there could be confusion and some users may install the shady Niagara launcher instead of 8bitPit's product, thus getting a wrong impression of it.

**Comment by 8bitPit** [comment]
It could also be a theme for CM-Launcher, I personally never I used it, so idk. Quite large file size for just a theme though (20MB).

**Comment by jakcharvat** [comment]
I don't think renaming Peter's Niagara Launcher is the way to go, unless he strikes a deal with Google to have a message in the 
Play Store search results saying the real Niagara launcher was renamed to ... and a link to it.

**Comment by 8bitPit** [comment]
Funnily enough, I did already rename the launcher during the closed alpha phase. It originally was called “Wave Launcher”, then a few months later I got an email from Google telling me, an app with that name already exists (ironically it does not anymore) and I must rename it. I renamed it to Niagara in 2017, before the other Niagara Launcher was in the store. I hope that I don’t get such a mail this time!

**Comment by jakcharvat** [comment]
Would be awful if you do. Let's hope this gets sorted somehow

**Comment by zamber** [comment]
Cheetah Mobile is notoriously bad. They live from selling usage statistics to third-parties. They trash the Play Store with crappy usage-sucking or ad-feeding apps. Their browser is a 💩 security-wise.

My best guess is that smithlauncher is CM-owned and is used as a tool for pushing down legitimate apps in search results, not "marketing".

Report it. Maybe Google will do something about it, but I doubt it. CM already pays for it's UX sins by not being featured or "EditorPicked" in the Play Store.

**Comment by cauerego** [comment]
i'd vow for another name anyway. Niagara isn't very Google friendly. even "niagara app" or "niagara launcher" might take some time before Google will pick it up. 

how about some sort of mix up? "nyiawave" is unused.

or perhaps "wooave launcher". :D

pretty sure you can come up with something more unique, if you like the idea and never thought you could.

**Comment by 8bitPit** [comment]
Seems that the issue had "solved" itself, the launcher isn't available anymore

**Comment by 8bitPit** [comment]
And no, I didn't request the removal and I did not inform Google about it. I don't know why it's not available anymore.

**Comment by cauerego** [comment]
and it looks like "niagara launcher" have already (or finally) been indexed by google! 🎉
