### ISSUE TITLE
Bug when uninstalling apps

### ISSUE THREAD

**Issue by mzpro10** [8bitPit/Niagara-Issues#510]
When an app is in the Favorite list and gets uninstalled by long pressing for the context menu and uninstalling from there. The app is not being removed it remains in the list. Tried it with a few apps and does the same thing.

**Comment by disacrol** [comment]
Seems the same reported in https://github.com/8bitPit/Niagara-Issues/issues/469 and https://github.com/8bitPit/Niagara-Issues/issues/501.
