### ISSUE TITLE
Feature request for Home Screen

### ISSUE THREAD

**Issue by mzpro10** [8bitPit/Niagara-Issues#511]
It would be great to replace most used apps list with recently installed apps list ti make them more accessible.

**Comment by Ahmedhossam2543** [comment]
It would be great if you leave the music widget in its place rven when thr music turned off that would make the user use the widget instead of the app

**Comment by Ahmedhossam2543** [comment]
The wallpaper must be more customizable and i syggest to allow wallpaper alvums to be shuffled through period if time like let the user choose an album that he made in his gallery and it shuufles automatically through a period of time that he chooses

**Comment by shumsk01** [comment]
Potentially add a horizontal scroll bar across the bottom, and a left handed bar vertically as a customization option for people with shorter thumbs and left handed people.

**Comment by 8bitPit** [comment]
@mzpro10 see: #227

**Comment by 8bitPit** [comment]
@Ahmedhossam2543 & @shumsk01 please open seperate issues next time.
@Ahmedhossam2543 see #117 and use another app for switching wallpapers, like Muzei.
@shumsk01 refer to #70 & #12
