### ISSUE TITLE
Double tap to open favorite apps and...

### ISSUE THREAD

**Issue by DomieMic65** [8bitPit/Niagara-Issues#513]
1) Sometimes double tap is needed to open favorite apps.
2) Swipe up and then down required in order to open notifications 
Both issues are somehow random but quite often.

 - Device: LG G6
 - OS: Android 8.0, Oreo

Restarting the launcher and the phone did not help.

Thnx
Michael

**Comment by disacrol** [comment]
How many favorites have you defined?

**Comment by DomieMic65** [comment]
No more than eight

**Comment by DomieMic65** [comment]
After some usage and for being more precise:
The favorite apps do not open with double (quick) tap. They just need second tap. They are unresponsive with the first.
The same with the notifications. They need some up and/or down swipe to expand.

**Comment by DomieMic65** [comment]
Yes. I am very sure. It happens only in Niagara. The unresponsive notifications tend to be more of an issue though.

**Comment by 8bitPit** [comment]
@DomieMic65 I am sorry, I have no idea why Niagara not behaving as intended. Let me know if you detect a pattern.

**Comment by DomieMic65** [comment]
I think I found something.
When I am in an app and go back to homescreen the apps are responsive and open instantly.
When I go to homescreen and swipe down to open notifications, I mean within the screen not from the edge, then the apps need second tap to open.
Regarding the notifications needing more swipes I didn't find a pattern.

Thanks again for your time and great effort!
