### ISSUE TITLE
Widget support and google feed support

### ISSUE THREAD

**Issue by adnbwta** [8bitPit/Niagara-Issues#516]
Can you add widget support or google feed support to the launcher ? Like the widget will be separated in shelf that can be accessed by swiping right from the favorite screen, and google feed by swiping left, or maybe just by swiping left you get both google feed and widget section like in oneplus launcher.

**Comment by Rod911** [comment]
Enable the Google button in Niagara Settings > Home Screen.
Click to open feed.
Swipe up for quick search.
Press and hold for Google assistant.
As for widgets, post requests in #117
