### ISSUE TITLE
Highlight apps with notification in app scroll

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#519]
Short Version: I'd like to consider making letters in the app scroll red or orange when they include an app with a non-persistent notification.

Longer version:
The swipe to see notifications feature is amazing. To help the user find apps with active notifications, I would like to see the letters in the alphabet list change color. If an app in the 'A' section, for example, has a (non-persistent) notification, the 'A' in the right side will be orange, red, or some other distinct color. Originally, I was going to suggest bringing these apps to the home screen below the most used apps but quickly scrapped that idea since it would cause clutter.

**Comment by 8bitPit** [comment]
Probably I'll add something similar to your scrapped idea - a notification folder, see: #9. So maybe there will be no need to mark letters when they include apps with notification.

**Comment by 8bitPit** [comment]
Merged with #9
