### ISSUE TITLE
Startup animation on every return to home

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#52]
I like the animation of the launcher when starting after force stopping the app, idk if this is possible but maybe you could redo the animation every time the launcher opens without force closing?

Or you could do a different method which is to completely force stop the app after user opens an app or locks the screen

**Comment by jakcharvat** [comment]
@587saboor this one? https://photos.app.goo.gl/fPyD9d5i6tQz9kMH9

**Comment by 587saboor** [comment]
@jakcharvat ye

**Comment by zamber** [comment]
There were reports of Niagara using a lot of RAM. On low-end devices this may lead to the launcher being closed completely, not just suspended. This would trigger the animation.

@587saboor does it happen for other launchers on your device? Do you have any launchers that animate on 1st run but do not on subsequent ones?

**Comment by kStor2poche** [comment]
I found the one when you come back from a favorite app who had a notification really cool too !

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
