### ISSUE TITLE
Suggestion for gestures for finding and opening your apps faster!

### ISSUE THREAD

**Issue by Girfes** [8bitPit/Niagara-Issues#523]
I really like the idea of scrolling with your thumb to find your app, but the part where you have to stop, lift your hand and press the app icon feels somewhat unnatural.. I thought that maybe there could be a gesture as an option for that. For example, you are using your thumb to scroll to the letter you want, you stop, without lifting your thumb, you swipe a bit the the left, it locks to your letter and then continue scrolling up and down to select your specific app and once you do, you continue swiping all the way to the left and it opens the app!

**Comment by 8bitPit** [comment]
Please refer to #162
