### ISSUE TITLE
[App icon changing] Search app icons

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#524]
Maybe add a search bar for changing app icons so you don't have to keep scrolling on big icon packs

**Comment by picroger** [comment]
But is there any way to change a single icon?

**Comment by 587saboor** [comment]
@picroger yes in the alpha build on tg

**Comment by disacrol** [comment]
On the new alpha you can, but left to the search button there is a bar named 'Edit icon', I guess to work as a title bar, that I believe would be more intuitive if it worked as a search bar and show 'Search...' instead, what do you think?

**Comment by picroger** [comment]
> On the new alpha you can, but left to the search button there is a bar named 'Edit icon', I guess to work as a title bar, that I believe would be more intuitive if it worked as a search bar and show 'Search...' instead, what do you think?

> @picroger yes in the alpha build on tg

Hey guys, but where can i get the alpha version? A have the playstore one, wich is the beta I think.
Thanks for tips.

**Comment by Rod911** [comment]
Niagara News
Updates & Important announcements about Niagara launcher.
https://t.me/niagara_news

**Comment by Rod911** [comment]
@picroger Niagara News
Updates & Important announcements about Niagara launcher.
https://t.me/niagara_news

**Comment by 587saboor** [comment]
@8bitPit should i close this now that it's in the alpha or on release or..

**Comment by disacrol** [comment]
@picroger I suggested a slight enhancement, but I can open a separate issue for that suggestion on case you guys prefer.

**Comment by 8bitPit** [comment]
Implemented in v.0.6.0
