### ISSUE TITLE
Request - No icons option 

### ISSUE THREAD

**Issue by picroger** [8bitPit/Niagara-Issues#527]
It would be a really cool feature to remove all icons, ending up with a pure list of apps. I would be actually looking forward to the next step in the minimalist goal. 

It's propably a pretty "easy" improvement to do, I think.

GREAT APP!

**Comment by 8bitPit** [comment]
Thanks, see: #140

**Comment by picroger** [comment]
Sorry about that!!

> Thanks, see: #140

**Comment by 8bitPit** [comment]
@picroger No problem :)
