### ISSUE TITLE
Disabling home screen animations

### ISSUE THREAD

**Issue by MTR2D2** [8bitPit/Niagara-Issues#528]
Option in settings to disable home screen animations.

**Comment by 8bitPit** [comment]
Do you mean disabling the scrollbar effect? The wave is helps you to see every letter even while scrolling

**Comment by MTR2D2** [comment]
No, not the scrollbar effect. What I'm referring to is the animation when
returning to the homescreen from any app.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
