### ISSUE TITLE
MainView not aligned at top position

### ISSUE THREAD

**Issue by pimboli** [8bitPit/Niagara-Issues#542]
Hello, 
I have the problem that the "main view" starts not at the top.
I attached a screenshot from my Oneplus 6t Android P.
![screenshot_20181108-182626](https://user-images.githubusercontent.com/5020679/48216277-8a489180-e384-11e8-966b-f0fb2ecc2562.jpg)
.

It would be much nicer if the clock would be positioned at the top so that users would not need to scroll always to get to the last items.

Is there a setting or is it a bug?

**Comment by Rod911** [comment]
Well it's a feature 😉
See #334 & #434

**Comment by MydVDZ** [comment]
It is a nice feature but i think there should be a setting to push it up or use it as stock.
