### ISSUE TITLE
Message Notifications not working for WhatsApp

### ISSUE THREAD

**Issue by mahadhir1605** [8bitPit/Niagara-Issues#546]
It shows notifications in the launcher for other apps, games and so on. But fails to show notifications from WhatsApp!

**Comment by Rod911** [comment]
Refer #267 for help.
If you still have issues you can send a notification log and see if he can help you (Niagara's settings > Advanced > Send notification log)

**Comment by 8bitPit** [comment]
Thanks for providing a notification log @mahadhir1605, it seems that you disabled notification badges for WhatsApp, you can re-enable them in WhatsApp's app info (in "Notifications")

**Comment by mahadhir1605** [comment]
Thanks for your response! I'm attaching herewith, the notification settings
for WhatsApp in my device, and system settings for notifications, as my
device is running Oreo! I've all notification settings correct!

*(Does running Oreo have any negative impact on my missing WhatsApp
Notifications?)*

**Comment by mahadhir1605** [comment]
Thanks for your response! I'm attaching herewith, the notification settings
for WhatsApp in my device, and system settings for notifications, as my
device is running Oreo! I've all notification settings correct!

(Does running Oreo have any negative impact on my missing WhatsApp
Notifications?)



https://drive.google.com/folderview?id=1o3c2CgDCTRf3uSp5j4reFRw46s2axpYd

**Comment by 8bitPit** [comment]
There should be a switch for allowing notification dots, e.g. on stock Android Pie it's listed in AppInfo > Notifications > Advanced. Hope that helps.
![image](https://user-images.githubusercontent.com/9284845/48284352-71f97500-e45f-11e8-80ed-4daeebed3d84.png)

**Comment by 8bitPit** [comment]
@mahadhir1605 please let me know if that helped.

**Comment by mahadhir1605** [comment]
I'm sorry but your ideas didn't help me

**Comment by 8bitPit** [comment]
That's a bummer, can you please provide a screenshot from WhatsApp's notification settings?

**Comment by mahadhir1605** [comment]
I think I'm unable to post screenshot in replies. I'm adding Google drive
link of the screenshot.
https://drive.google.com/file/d/1JTJBLNF89mxvvWkkY_oQcj_ZiPaHYpIu/view?usp=drivesdk

**Comment by 8bitPit** [comment]
@mahadhir1605 oh sry, I meant Android's notification settings for WhatsApp (System Settings > Apps > WhatsApp > Notifications), can you screenshot those setings? 

PS: You can just paste the image in your comment, it will be uploaded automatically :)

**Comment by 8bitPit** [comment]
And there is no "show notification dots/badges / show in homescreen" toggle?

**Comment by mahadhir1605** [comment]
Badges turned on.
Notifications hidden in lock screen.
All other options are on by default.
