### ISSUE TITLE
Simple favorite folders

### ISSUE THREAD

**Issue by 7xcritical** [8bitPit/Niagara-Issues#547]
I'd like the feature to add some simple folders 
I could see it being a thing where it opens to a list to the right and there are about five or six apps in there, and maybe the ability to chose the icon for individual folders
edit: spelling

**Comment by 8bitPit** [comment]
Thanks for your suggestion, could you please repost your ideas here: #13

**Comment by Rod911** [comment]
Hey @8bitPit Feature requests and Bug reports should go [here](https://github.com/8bitPit/Niagara-Issues/blob/master/README.md) not directly to issues page, that will definitely help with common duplicate issues.
