### ISSUE TITLE
Duplicate Icons in custom icon search

### ISSUE THREAD

**Issue by xYvanB** [8bitPit/Niagara-Issues#549]
Double icon with the "search" function in "edit icon" on v0.6.0alpha2

1. Go to 'Edit Icon'
2. Click on 'Search Icon'
3. Type the name of an app (indifferent)

**Screenshots**
![photo_2018-11-11_14-00-30](https://user-images.githubusercontent.com/16927302/48313282-37581f80-e5ba-11e8-8a1d-33602bce5a33.jpg)
![photo_2018-11-11_14-00-35](https://user-images.githubusercontent.com/16927302/48313284-39ba7980-e5ba-11e8-8e90-bc4d3cd62db4.jpg)

**Smartphone:**
 - Device: OnePlus 3
 - OS: SkyDragon, Android Pie 9.0

**Comment by 8bitPit** [comment]
From Telegram:

> Thanks for the report, duplicates appear, because the icon appears in two categories of the pack. Will be fixed.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
