### ISSUE TITLE
At a Glance / show appointments

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#55]
Something like that:
![image](https://user-images.githubusercontent.com/9284845/44999381-1624f280-afbd-11e8-88dd-5252e01bfdfc.png)

**Comment by jakcharvat** [comment]
This seems really similar to #4, #24, #44

Just letting you know

**Comment by LukasB79** [comment]
it would be superb with this "widget" - at a glance - the only thing which is missing for minimal calendar support - i think

**Comment by Victoor** [comment]
This will be amazing! 😋

**Comment by 8bitPit** [comment]
@KSW7031 please open a separate issue for requests which are not related. Also, as @Rod911 mentioned, lockscreens are not part of launchers, e.g. see: #321.

**Comment by LukeBiel** [comment]
Yes! I'd love to see my next calendar event under the clock, that is the only thing I miss in this launcher. It is perfect except this

**Comment by maracuja-juice** [comment]
Would this be able to get appointments from Outlook aswell? (I have an iCloud calendar configured in Outlook)

**Comment by tjsuominen** [comment]
Is still with low priority for Beta. There seems to be at least two alternatives to implement this: 1) bake into Niagara as option or 2) allow widgets support on home-screen for user to pick-up preferred "At glance" widget. The Google one (modded from Pixel) does not support other calendars than Google, but there's a 3rd party one "At a glance widget" that supports other calendars. I use the later one currently.

**Comment by techhahn** [comment]
Please make glance widget a high priority, I miss many events because of lack of such functionality.
Love what you did with settings page (Samsung one UI style). Please make similar thing. On swiping down on home screen reveal more info about the events.

**Comment by ShadowXOR** [comment]
I need this so badly.

**Comment by Rod911** [comment]
Seems unnecessary since it can now be done using widgets

**Comment by paddynski** [comment]
Support widgets to the right of favourites on main screen. I have a lot of empty space on my tablet.

**Comment by tjsuominen** [comment]
So if this "Calendar items" / "At a glance" is coming as Niagara feature (ie. configurable in Niagara settings) and NOT as widget, then users could have still a widget in place (eg. for hourly weather forecasts). Lets see how the implementation goes... :)

Another related question: could there be option to include more than one widget to the home-screen?

**Comment by tjsuominen** [comment]
If / when this "At a glance" gets implemented (I know it will ;o)) - it think it should have the ability to include multiple Google Calendars (e.g. as I have separate calendars for e.g. Family, Work, Personal).

**Comment by y0c4** [comment]
this would be a great addition. Perhaps use the same technique as when the phone registers a headset and moves all of the music apps to the top of the list ? So when an event is coming up the different apps defined as calendar apps goes to the top of the list.

**Comment by tjsuominen** [comment]
Hmmm... @y0c4 that sounds interesting alternative scenario as NOT fixed placeholder. Needs two options to be able to define in settings:

1) heads-up time (before the item is shown)
2) which calendars are taken into account

But yes, that could be an alternative if could be implemented in a pretty, neat, minimal UI way (which for sure Peter is capable of doing).

**Comment by 8bitPit** [comment]
@y0c4 cool idea, we'll consider it :D By the way, this feature may be available at the end of 2020.

**Comment by tjsuominen** [comment]
Great to know @8bitPit - you have my pennies when this is available :)

Strongly hope to have those abovementioned options available in the settings as for some events you need x amount of heads-up time AND several calendars.

But as said, great that it's perhaps coming :=)

**Comment by 8bitPit** [comment]
Yeah, calendar events should definitely be shown in advance and I agree, there should be a way to filter calendars. But I don't know the details yet :)

**Comment by es881** [comment]
> Something like that:
> ![image](https://user-images.githubusercontent.com/9284845/44999381-1624f280-afbd-11e8-88dd-5252e01bfdfc.png)

**Comment by 8bitPit** [comment]
Implemented in v0.32
