### ISSUE TITLE
Unlock phone using "OK Google"

### ISSUE THREAD

**Issue by Scryptic7** [8bitPit/Niagara-Issues#551]
I used to be able to just say "OK Google" or "Hey Google" to unlock my phone when using another launcher but I'm not able to when using Niagara. At first, I thought it was something wrong with my phone but I later found out that it is not a default Android feature... that it was a feature offered (or supported) by the other launcher. It would be fantastic if Niagara could include this feature. It is so much easier when I can set my phone in the cradle in my vehicle and then say, "Hey Google, navigate to XYZ" without having to unlock the phone manually first.

**Comment by 8bitPit** [comment]
The "hey Google"-Command shouldn't depend on your active launcher. Have you installed the official Google Assistant app?

**Comment by Scryptic7** [comment]
I have. Perhaps I do, in fact, have s problem with my phone, but I did read
something about the other launcher supporting it so I thought that since I
no longer use it, that might be why it's not working anymore. The other
launcher was Apex. Niagara has taken it's place... I'm a big fan of
minimalism.
