### ISSUE TITLE
Slideshow Wallpaper

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#552]
Currently, I can select up to 25 lock screen pictures that change in a cycle. A similar feature for the launcher wallpaper would be nice.

**Comment by 8bitPit** [comment]
Muzei Live Wallpaper lets you do that: https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=de

**Comment by disacrol** [comment]
Plus, it does blue the background which is great in a launcher like this.
