### ISSUE TITLE
Option to use original icon

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#553]
For when you choose an icon pack but you prefer the original icon of a given app, it would be great to have the ability to choose the original icon. In other words, not apply the icon pack for a given app.

Case in point, I like the Pixel-style 'pixip' icon pack, hundreds of icons, but hate the dull grey icon they use for Waze. I use Waze a lot and it's on my favorites, and the original icon is already round and would blend in great on the screen, but I simply cannot choose it's original icon.

**Comment by Xavi3RElvis** [comment]
I await for this functionality so much, need to revert icons to defaults per app

**Comment by 8bitPit** [comment]
Implemented in v.0.31
