### ISSUE TITLE
App icon gets cropped when "smallest" size selected

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#554]
Minor issue with #94 implementation.

When "Smallest" icon size is selected in options, app icon resets to default size after checking app info.
This is noticeable since the icon gets visually cropped on two sides.
This is quite a temporary problem since scrolling around and getting back to the screen it resides resets it back to "Smallest" size.

1. Select "Smallest" App Icon size in Niagara 'Look' settings
2. Tap and hold on any app icon and select "application info"
3. Tap Back
4. Icon of that app resets back to default size (apparently) leading to it being slightly cropped
5. Scroll to any other section and scroll back to where the app is located: no longer cropped

This is also reproducible on the favorites screen - in which case tapping Home on step 3 also reproduces the issue.

Device: Xiaomi Mi A2
OS: Android 8.1 (Oreo)
Flavor: Android One

**Comment by 8bitPit** [comment]
Thanks for the report, in should be fixed in the latest version (0.6.0 beta) :)

**Comment by disacrol** [comment]
Yes, fixed, just tried it. Thanks.
