### ISSUE TITLE
Introduce New Features

### ISSUE THREAD

**Issue by satbirkaushik** [8bitPit/Niagara-Issues#555]
(My device: motorola Moto G (4) (athene_f), API 24)   

Please introduce some new features in this like:
1. Remove search icon from this.
2. Add new Google colorful icon to this by that user can search from google and existing application. So no need that search icon separatly.
3. Add swipe left to show google feeds like pixel and google now launcher.

**Comment by Rod911** [comment]
Related issues : #199, #3, #182
Tip: swipe up action on the Google FAB/icon to bring up Google feed.

**Comment by satbirkaushik** [comment]
Which  Google FAB/icon?
At the botton roght corner that one?

**Comment by Rod911** [comment]
Yes, click for feed, swipe up for quick web search, long press for assistant.

**Comment by satbirkaushik** [comment]
Great, btw you are frm this launcher team??

**Comment by satbirkaushik** [comment]
One more feature,
1. How can we add any widget or app shortcut to favorite.  If not possible then introduce this as well.

**Comment by Rod911** [comment]
Na I'm just helping out. Feel free to ask if you have any other questions.

**Comment by satbirkaushik** [comment]
Thxx rod. :)

**Comment by Rod911** [comment]
Widget support is a well requested feature, see #117 for more info.
