### ISSUE TITLE
Music widget gets cut

### ISSUE THREAD

**Issue by zenoweed** [8bitPit/Niagara-Issues#560]
I'm using the Samsung music player from play store. And the widget that comes on the homescreen is cut at the right and left edge.

**Comment by 8bitPit** [comment]
Can you please provide a screenshot @zenoweed? Thanks in advance.

**Comment by zenoweed** [comment]
Hey dev yes I can provide a screenshot. But I sort of found out that the problem was created because I had increased screen zoom which decreased the dpi. Once I brought screen zoom to the default setting the problem was gone.
