### ISSUE TITLE
App icon disappears when dismissing notifications

### ISSUE THREAD

**Issue by spajo** [8bitPit/Niagara-Issues#563]
Hi,  
I downloaded Niagara just a while ago to test it and I have to say it looks and feels very nice, but let's get to the bug report :)

---

When dismissing (swiping away) the notification of a not-favourited app its icon disappears.

**To Reproduce**
1. Do a new installation of the App
2. Scroll down to the app which has one or more notifications
3. Swipe right to show the notification(s)
4. Swipe away the notification
5. Swipe up or down to dismiss the notification view
6. See that the Icon and the title of the app are not visible, but are clickable.

**Expected behavior**
The icon and the title of the app should be visible.

**Video**
[gfycat url](https://gfycat.com/RepentantJubilantFrigatebird) - it shows broken behaviour 
[second video](https://gfycat.com/PleasantDimHornshark) - it shows (I think?) correct behaviour, I tried to reproduce it after a reboot and then it worked :P

**Smartphone (please complete the following information):**
 - Device: OnePlus 5 (cheeseburger)
 - OS:  8.1.0, October security patch
 - Niagara version: 0.5.4

If I encounter it once again I'll be in touch.

Regards,
Rafal

**Comment by 8bitPit** [comment]
Thanks for taking your time to write such a detailed & informative report :)
I noticed the bug as well, couldn’t reproduce it though. I’ll try it on new installed apps. 

Have a great weekend!

**Comment by 8bitPit** [comment]
Does the issue still persist? If so, feel free to open it again.
