### ISSUE TITLE
Weather update

### ISSUE THREAD

**Issue by Hetulkat** [8bitPit/Niagara-Issues#564]
Please add an option to set the frequency of weather update on the widget! And add AccuWeather and other weather provider's support

**Comment by 8bitPit** [comment]
Sry, I cannot change the frequency myself, because I'm currently using Google's Awareness API, more details here: https://github.com/8bitPit/Niagara-Issues/issues/179

**Comment by Hetulkat** [comment]
What about AccuWeather support?
