### ISSUE TITLE
Add Simplified Chinese support.

### ISSUE THREAD

**Issue by f0rb1d** [8bitPit/Niagara-Issues#572]
**Is your feature request related to a problem? Please describe.**
Add support for Simplified Chinese language.

**Describe the solution you'd like**
I've already made a language pack for the app, I put it here: [Translation Work](https://pastebin.com/bqCavfZ9)

**Describe alternatives you've considered**
Also you can call other users to proofread it :D

**Additional context**
Love the app.

**Comment by BruceZhang1993** [comment]
Nice job,  it will be better if the app drawer list is shown as pinyin's first alphabet, not chinese characters :)

**Comment by 8bitPit** [comment]
Wow, I’m certain that was a lot of work, thanks a ton for providing translations into Chinese! Supporting different languages is one if the enhancements I would love to implement in the next few months. I will come back to you.

**Comment by 8bitPit** [comment]
@BruceZhang1993 see: #234

**Comment by 8bitPit** [comment]
Added in v0.7
