### ISSUE TITLE
Show non-Latin letters in alphabet

### ISSUE THREAD

**Issue by Guaolbux** [8bitPit/Niagara-Issues#575]
I'm Korean and I used this app for few months. 
I really like this app and thank you for hard work! 
But as i woke up today morning, I found that apps with korean name is in #list.
before, there was korean list. 
so please check this issue for Korean users.
Maybe because of app update I think but not sure..

**Comment by Guaolbux** [comment]
I like to have Korean lists seperately.. so can we have setting for enabling non-english lists?

**Comment by Rod911** [comment]
This was a temporary fix until non English languages are supported, app list will be improved.

**Comment by 8bitPit** [comment]
Merged with #455
