### ISSUE TITLE
Search the web in search bar

### ISSUE THREAD

**Issue by maskyad** [8bitPit/Niagara-Issues#58]
Enable an option that allow the user to search things on internet using the search bar.

https://imgur.com/a/0pqnG4I

**Comment by 8bitPit** [comment]
I'm not a huge fan of that, but I may be impending it, I'll let you know.

**Comment by jakcharvat** [comment]
Would be a nice feature in my opinion. makes it easy for the user

**Comment by AtomAntReturns** [comment]
Very useful feature. Would love to see this implemented

**Comment by Fabus1184** [comment]
Would be nice

**Comment by klemy** [comment]
I confirm this functionality would be very useful to me. I hope it will be implemented!

**Comment by STeeL835** [comment]
A button that would redirect search query to Google Play app would be nice too

**Comment by 8bitPit** [comment]
@STeeL835 here is an open issue about that :  #145 :)

**Comment by klemy** [comment]
Hello all, my comment it a little duplicate from my initial request #450.

I have found the way with which Google gives in-app information with his search bar : it's the Firebase App Indexing ( https://firebase.google.com/docs/app-indexing/ ) !

Perhaps would it be possible to get the content of this database and use it in an another app than Google Search ?

**Comment by Fabus1184** [comment]
Nice idea, are you into programming right now, so could you test this maybe
xD?


Am Do., 1. Nov. 2018 um 19:40 Uhr schrieb Clément Lesné <
notifications@github.com>:

**Comment by disacrol** [comment]
You mean the app search bar? Swiping up from the Google button does the same (need to enable it in Niagara options)

**Comment by marsknightUNLOCKED** [comment]
Meanwhile you could also just install that app:
https://github.com/veniosg/JustSearch
It replaces OK Google with a simple search as assist app, so you just need to long-press home to search the internet.

**Comment by KJamp** [comment]
Hey @8bitPit, I didn't want to create a new Issue and thought it would fit here.
I used the Nova Launcher before with the Sesame as my search app and I would love so use it on Niagara as well.
So the option to change the default search app, or the app that launches on the homebutton press would be amazing.

**Comment by Rod911** [comment]
@KJamp related issue: #88

**Comment by verboze** [comment]
I think the Sesame integration might be a better route. Not everybody might want this feature (I do), and Sesame's search implementation is extensive. I've used it with Nova launcher, and it's great!

**Comment by nachomestre** [comment]
In relation with global search, Ive liked a lot how they do it in other launchers, including in search results, config options like night mode. Using the same search as the Config App, it would send you to the Config section in order to be able to toggle the option.

**Comment by 8bitPit** [comment]
This will be possible with Sesame once the app is integrated: #88
