### ISSUE TITLE
Option to choose icons from Gallery

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#581]
Currently, icons can only be selected from icon packs. Here is a screenshot, provided by Ashis Mahapatra on Telegram how a new selection screen could look like:
![image](https://user-images.githubusercontent.com/9284845/48666349-013a0480-eac0-11e8-8190-a3ff429e183c.png)

**Comment by ssssamstrup** [comment]
Just wanted to update that I'm still really missing and looking forward to this function! ☀🙏 Miss having my own icons in the launcher. 😊

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
