### ISSUE TITLE
Fling up to return home

### ISSUE THREAD

**Issue by thebenign** [8bitPit/Niagara-Issues#585]
As a feature request, I feel it would be intuitive if while you're holding the alphabet bar, flinging up would return to home. I know there are similar requests, but this would not be so much a gesture as it would only respond while holding the bar, and makes sense since you know that "up" ascends the list.

**Comment by thebenign** [comment]
Correct, quickly sliding the finger up. This could be in a threshold speed and range to identify a "flick" motion. Sliding to the top is also easy enough, but if I'm holding my phone one-handed, I cannot reach my thumb all the way up to the star without engaging my other hand or changing my hand position.

**Comment by Rod911** [comment]
This could be useful for some, but I feel this may be redundant as pressing home or back button does the same while maintaining one hand use.

**Comment by 8bitPit** [comment]
I believe the fling gesture could be triggered accidentally very easy, in contrast to the star at the top
