### ISSUE TITLE
Request to make Symmetric Alphabets

### ISSUE THREAD

**Issue by zenoweed** [8bitPit/Niagara-Issues#589]
Hey dev could you make the alphabests symmetrical to the screen. By default it is a bit lower and starts after the clock.

**Comment by Rod911** [comment]
That's to help with one handed use.

**Comment by berdzena** [comment]
Maybe horizontal alphabet at the bottom of screen would be good idea

**Comment by zenoweed** [comment]
It might mess up with the softkeys but it would look good.

**Comment by zenoweed** [comment]
On second thought it might work but it might need a narrow phone

**Comment by 8bitPit** [comment]
See: #334 & #255
