### ISSUE TITLE
Widget screen

### ISSUE THREAD

**Issue by n0rrin** [8bitPit/Niagara-Issues#59]
I love the minimized design but it is in its natute that there is a lack of informations. 
So it would be nice to have a second screen with those informations.

I would prefer to swipe right to it, because in my homescreen is a lot of place under the 7 icons but that is maybe difficult for other user's screens with less space or when there are a lot of notifications decreasing this space.

**Comment by 8bitPit** [comment]
Weather will be added in the favorites tab. Also, widgets will probably be implemented, but this will take some time. Yeah, swipe gestures are hard, because left and right swipe are already used for opening and deleting notifications.

**Comment by n0rrin** [comment]
Weather on the homescreen would be nice, maybe one appointment too, but in my opinion most widgets would destroy the clean look. That's why i recommend another screen. 

It is nice that you do not nned to choose calendar or alarmclock as one of the 7 apps for the homescreen, because you reach them by the time or date. Same would be with a weather symbol.

**Comment by icantremember** [comment]
Google app's At A Glance widget has a great clean look, too. Upcoming appt plus basic weather.

**Comment by n0rrin** [comment]
Yes, but please no google stuff. It's hard enough that niagara launcher is not open source...
;)

**Comment by tjsuominen** [comment]
My preference (and how I use it currently in Nova) and perhaps the best way to allow most flexibility for (Niagara) users: Implement widgets support (yes, I know that's under Niagara's radar for being implement, perhaps ;). By having widgets supported, user would then be allowed use detailed "At glance" or "KWGT" or something else they prefer.

The most, IMO, important things for "At glance" like info is the current weather and upcoming (or current) event from your calendars.

**Comment by 8bitPit** [comment]
I came to the conclusion that widget pages wouldn't work well in Niagara, see issue #117 for more details:

> I am not really a fan of widget pages. The only thing widgets have in common there is, well, they’re all widgets. So why should they be grouped together? Showing a weather widget below the clock and accessing your calendar agenda via a swipe / by tapping on a button makes more sense to me. Also, widgets often tend to use much ram. The concept of a widget list would kind of endorse user to cluster the page full of widgets. A swipe menu shows only a single widget at once, so not every widget has to be loaded into ram when you want to access one.
That’s why I’m planning to add the following integration:
You can place a single widget below the clock or replace it for showing weather and / or time, or an at a glance widget.
More widgets can be accessed by swiping right on an app.
Another idea would be that you can customize the google search button at the bottom right, so it can also launch a widget, e.g. your calendar.

That's why I'm closing the issue. If you have further ideas how to implement widgets in Niagara, post your ideas in the linked issue.
