### ISSUE TITLE
Request right swipe include long tap options

### ISSUE THREAD

**Issue by zenoweed** [8bitPit/Niagara-Issues#592]
It really useful cuz right swiping in Niagra is really cool. But when you turn off notification dots (to save up memory) the right swipe become useless unless it has the extra things/options that come with the right swipe. Thanks

**Comment by 8bitPit** [comment]
You can also open app shortcuts with the right swipe. Furthermore, e.g. widgets / legacy shortcuts could also show up there in the future.
Btw, I believe you're not saving a lot of RAM by disabling notifications, maybe you were mislead by the service's memory usage: https://github.com/8bitPit/Niagara-Issues/issues/84
