### ISSUE TITLE
Icon pack selection bug

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#60]
"Can't select the bottom icon pack for some reason. I try and it selects the top (no icon pack) instead. So in this case, pure icon pack - Steven (Telegram)"
![photo_2018-09-04_12-06-47](https://user-images.githubusercontent.com/9284845/45025217-2e3b5700-b03b-11e8-8002-37cc8b7c87cb.jpg)

**Comment by rastamanjohn** [comment]
I'm pretty sure this is a bug with Pure, I had the same problem, now that I saw this I tested and only Pure icon pack is bugged, others work fine.

**Comment by shalu7x** [comment]
Click on icon pack option.
Select any icon pack.
Then click again on icon pack option, by default it's changed to None even if the selected icon pack is preselected.
