### ISSUE TITLE
Request for ease of access?

### ISSUE THREAD

**Issue by nagijara** [8bitPit/Niagara-Issues#600]
How about a swipe up to go to the app list that's only accessible with the alphabet?
It's like the swipe up for menu but it just goes the alphabetic list of apps, haven't seen this requested which should be common sense to have by me , it's just intuitive
Cuz for ex in the menu you can go from letter to letter by swiping up and down, what about going to the home screen the same way? And from the home screen to the list?

**Comment by nagijara** [comment]
Going from the main screen to the app list with a swipe would be really good , since it's just intuitive

**Comment by Rod911** [comment]
Refer #122
