### ISSUE TITLE
Request : Scrolling feedback & Dynamic Scrolling

### ISSUE THREAD

**Issue by kuabhishek123** [8bitPit/Niagara-Issues#602]
Can I suggest adding some feedback while scrolling like small vibration per alphabet or every 500-800 msec.
And also a dynamic scrolling feature where scrolling depends on speed of swiping, like a fast swiping will quickly take you from A to Z and slow swiping will scroll the way it currently scrolls.

PS : The best launcher I have tried yet. Thanks for making it. Hope you will make it even better.

**Comment by Rod911** [comment]
See #200

**Comment by kuabhishek123** [comment]
What about dynamic scrolling ?

**Comment by 8bitPit** [comment]
@kuabhishek123 thanks for the compliment :)
Regarding the scroll gesture, do you have something like this on your mind? https://github.com/8bitPit/Niagara-Issues/issues/122

**Comment by kuabhishek123** [comment]
No, I was thinking something like the scrolling speed with respect to the
rate of swiping by our touch.

So, If we swipe fastly(on the alphabets) the scrolling will be very fast
and reach from A to Z or Z to A very quickly and when we move our finger
slowly it will be like it currently is.

What happens now is that the alphabets follow our touch so for A we need to
reach very high and for Z we need to reach very low.

Instead I am suggesting that if we start from suppose K and swipe very
fastly then we should reach A by the time our fingers reach F or E.
i.e. the scrolling will be dynamic in speed depending on the speed of our
swiping.

*P.S.* : *Thank you* for replying, I know what I am suggesting is just a
little thing which will be quite hard to implement but I just want the
launcher to be even better than it is now.

**Comment by 8bitPit** [comment]
Lists on Android automatically scroll based on your gestures acceleration value. If I tweak the "speed multiplier" it would probably cause discomfort, since the default values remain untouched in every other app.

**Comment by kuabhishek123** [comment]
Ok, but can you just generate a demo app after increasing the speed multiplier, and try it out for once, it's just my hunch but I think you'll feel much better with the increased speed.
If it feels better then maybe you can add a feature to increase the speed multiplier in the settings.

PS: The scrolling animation is so lit that I find myself scrolling over the alphabets for no reason xD, and that's when I notice that I need to put extra effort to reach A or Z fully. Thanks again.
