### ISSUE TITLE
Keyboard remains open when home is pressed while renaming app

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#606]
Could be related with #151.

When renaming an app, if I press home, the keyboard remains open.

Sorry for short description, I'm on mobile, but I think it's clear. Let me know if you need a video or something.

**Comment by Rod911** [comment]
As far as I've noticed, this issue is not specific to any particular app. I use fast finder, and I face the same problem.
My conclusion, any app that has an overlay on the home screen with a text field will have this problem.
Only work around for now is to press back when keyboard is open instead of pressing home button.

**Comment by disacrol** [comment]
Not sure if I was clear: this happened renaming any app using Niagara.

Regarding any other app, pressing home should always hide clipboard. If any app has this problem, then I believe it is that app's developer responsibility to hide it. Although I never used a launcher before where the keyboard remains open when pressing home. Shouldn't the it be delegated to the launcher to handle the event triggered when home is pressed?

Anyway, for the specific case of when I'm renaming an app, it was fixed in the latest alpha, thanks!

**Comment by Rod911** [comment]
Well it seems I might have 
been wrong because since other apps no longer have this problem since 0.6.1. While keyboard staying active when renaming apps issue still persists.

**Comment by 8bitPit** [comment]
> Regarding any other app, pressing home should always hide clipboard. If any app has this problem, then I believe it is that app's developer responsibility to hide it.

You're right, but I noticed Googles launcher is hiding the keyboard when pressing home as well, so they assume the launcher takes responsibility for the keyboard.

> While keyboard staying active when renaming apps issue still persists.
So, you're saying the keyboard still stays open on the latest build after renaming an app?

**Comment by Rod911** [comment]
Pressing 'ok' closes the keyboard but pressing home doesn't.

**Comment by disacrol** [comment]
Exactly, this is only a problem when home is pressed.

Isn't there a way on the launcher side to implement behaviour to be triggered everytime home is pressed, no matter the app / screen?

**Comment by 8bitPit** [comment]
> Isn't there a way on the launcher side to implement behaviour to be triggered everytime home is pressed, no matter the app / screen?
Okay, seems to be Android version specific, atleast it works on my device (Essential phone Android 9)

> Isn't there a way on the launcher side to implement behaviour to be triggered everytime home is pressed, no matter the app / screen?
Yes, I'm using that trigger already. But sometimes the keyboard shouldn't close the keyboard e.g. when pressing home to search is enabled. That's why I close the keyboard when onPause() will be called on the rename activity.

**Comment by disacrol** [comment]
I'm not able to reproduce this at the moment. There is a chance this was fixed on the last update, which I find strange since I could swear I've reproduced this after the latest update.

I should have checked the exact version at that moment.

Close this if you prefer, I can reopen it as soon as I reproduce it again.

**Comment by 8bitPit** [comment]
@disacrol thank you :)
