### ISSUE TITLE
Hide Niagara Settings

### ISSUE THREAD

**Issue by Az1718** [8bitPit/Niagara-Issues#607]
I'd like to see the Niagara Settings section hidden unless you scroll using the sidebar to it, similarly to the home screen. I feel like the app list should only show apps.

**Comment by 8bitPit** [comment]
I noticed many users didn't find the settings in Niagara, so hiding the section would worsen the problem. Furthermore giving an option to hide the symbol would be overkill.

**Comment by Az1718** [comment]
Yeah, I didn't realize that the settings were there for like a day. I kept going into the settings from the default apps page. 

Maybe add a pop up when they first use it to show them where the settings are? Or have an option to have it not show unless you're using the scroll bars in the settings?

**Comment by 8bitPit** [comment]
@Az1718 atleast I could fix the discoverability problem: https://github.com/8bitPit/Niagara-Issues/issues/342
