### ISSUE TITLE
Apps rendered on top of Google Assistent window

### ISSUE THREAD

**Issue by wizzackr** [8bitPit/Niagara-Issues#611]
Bug: when pressing & holding the Google knob to access Google Assistent the favourite apps are rendered on top of the search assistant window. Most importantly: Great work so far!

**Comment by wizzackr** [comment]
Yes, sorry for double posting. Damn, thought I had thoroughly looked...

**Comment by Rod911** [comment]
No problem, if you have any information or feedback about the issue you can write it there.
I'll close this issue.
