### ISSUE TITLE
Advanced further left swipe

### ISSUE THREAD

**Issue by supmir** [8bitPit/Niagara-Issues#614]
Instead of just going to the first letter, swiping further to the left after holding on the first letter will go to the second letter and so on. Then if an app becomes unique, swiping further left will launch the app

**Comment by disacrol** [comment]
What do you mean? Swiping to the left from where? Letters are selectable by swiping up and down, not left and right.

**Comment by supmir** [comment]
I'm recommending a feature. Where after holding on a letter, dragging it to the left will go to the next letter

**Comment by Rod911** [comment]
@supmir but isn't that what scrolling up and down is supposed to do?

**Comment by Rod911** [comment]
I see what you mean, sorry. Here's a suggestion that might interest you. 
https://github.com/8bitPit/Niagara-Issues/issues/162#issuecomment-426955586

**Comment by supmir** [comment]
@Rod911 Nice! Thank you. I do however think that it would be better if #162 is combined with the second letter like I said.

**Comment by 8bitPit** [comment]
I'll merge this issue with #162, please post further ideas there.

**Comment by 8bitPit** [comment]
Merged with #162
