### ISSUE TITLE
Play/pause not working with Musicana music player

### ISSUE THREAD

**Issue by karthikkasturi** [8bitPit/Niagara-Issues#619]
I am unable to play/pause from the launcher when I'm listening to music on Musicana. I am able to do the same from Notifications and the launcher recognises that the content has been paused/resumed and the play/pause icon changes respectively but clicking on the icon in the launcher does nothing. I'm running miui 10 with Android Oreo on a Redmi Note 5 pro device, if that helps.

**Comment by 8bitPit** [comment]
Duplicate of #485
