### ISSUE TITLE
Shortcut support (e.g. add websites to homescreen)

### ISSUE THREAD

**Issue by pablomeza10** [8bitPit/Niagara-Issues#62]
I would appreciate shortcuts since I'm so used to them.

**Comment by Maxr1998** [comment]
This isn't done yet, so we'll keep this open :P

**Comment by cauerego** [comment]
Google maps seem to have a kind mixed shortcut for adding a very convenient people location. and obviously Chrome have that "add to home" thing.

should we open a new issue for these?

**Comment by 8bitPit** [comment]
@pablomeza10 Those are Map's app shortcuts:
![image](https://user-images.githubusercontent.com/9284845/46584225-ed32ca00-ca60-11e8-8f3d-fd497473bd4f.png)
I believe that shortcut you're referring to is an app shortcut.

**Comment by 8bitPit** [comment]
Here's another example provided by @t0ffe. Those are not legacy shortcuts but something similar. Shortcuts which can be created from an app.
![image](https://user-images.githubusercontent.com/9284845/52078300-243e6580-2593-11e9-9d81-b11966dbe0ff.png)

**Comment by 8bitPit** [comment]
The feature would also allow to pin any shortcut to your favorites or in the app list (https://github.com/8bitPit/Niagara-Issues/issues/40).

**Comment by pulinagrawal** [comment]
Just wanted to let you know that I would really appreciate getting this feature. This and widget support are the two reasons holding me back from promoting this app to other people. I have already got a couple of people hooked to this app.

**Comment by Shuunen** [comment]
Same here 👍 great app would be perfect with this feature

**Comment by 8utl3r** [comment]
+1

**Comment by Olieee0730** [comment]
I keep having trouble with the wallpaper it won't come out centered I basically see half of it?

**Comment by Shuunen** [comment]
> I keep having trouble with the wallpaper it won't come out centered I basically see half of it?

This has nothing to do with this issue

**Comment by duall** [comment]
+1, I'm using island which disables heavy applications while not use, it's not able to auto-add application shortcut (unfreeze and run) when it's disabled. Niagara says feature not available yet. Looking forward.

**Comment by merrypoppin** [comment]
about the music player shortcut, i think you should redefines it and make it more nice. A little bit space i mean gap between the clock and the apps because the current look so small and very near to each other

**Comment by FoxxMD** [comment]
Very much looking forward to this!

**Comment by Kaiouss** [comment]
Nice to have as a follow on to this feature, would probably like to whole sale view and delete the shortcuts I've already created. Looking forward to being able to free up lots of space on my phone by replacing apps with their pwa alternatives 🙂

**Comment by jackweekes** [comment]
I purchased Niagara Pro, hoping that the this feature will come soon. This is the one feature I need to use Niagara daily.

Looking forward to this.

**Comment by 8bitPit** [comment]
@jackweekes Thank you very much. It might come sooner than you'd expect 😉

**Comment by 8bitPit** [comment]
https://medium.com/niagara-launcher/shortcuts-finally-34c52d9f90dc?source=friends_link&sk=f780e899811cd3fc486319a940fb9838

**Comment by 8bitPit** [comment]
Implemented in v0.11.0 🎉

**Comment by hoborm** [comment]
I just found out that this feature I was missing is already implemented. I'm happy about that, however, I would like to add a suggestion to have an option to add the shortcut to the favorites from the "app drawer" after holding the shortcut down. It currently has only the option to add to the app drawer "Show in app list".

**Comment by 8bitPit** [comment]
@hoborm you can add it to your favorites after adding it to your app list. This makes sure that shortcuts can behave like apps once they're added. You can also hide an app/shortcut from the app list and favorize it afterwards without revealing it in the app list (Hidden Apps > Tap on your app > Add to favorites). I know, this procedure is not intuitive. I'm already planning to improve it and enhance overall Niagara's user experience by a lot :)

**Comment by ssssamstrup** [comment]
For reference, now that PWAs exists and in some browsers makes making shortcuts unavailable when a site supports PWA: https://github.com/8bitPit/Niagara-Issues/issues/785#issuecomment-2128970716
