### ISSUE TITLE
Notification controls don't work on Niagara

### ISSUE THREAD

**Issue by jurrabi** [8bitPit/Niagara-Issues#621]
With apps like Netflix, that have buttons to control playback in the notification area, the controls show on the icon in the favorites section, but don't work.
I don't know if this is a bug or if it is a feature request. I also haven't seen it mentioned before.
Huawei P9 Lite, Elite custom ROM

**Comment by Rod911** [comment]
Do the controls work for music players for you?

**Comment by 8bitPit** [comment]
@jurrabi thanks for letting me know. In my opinion Android's audio system is a bit of a mess, there are multiple ways to control media playback. I will try to find the one which is compatible for most apps.

**Comment by jurrabi** [comment]
Thanks to you for making this nice launcher. If you need me to test something in my specific configuration, just let me know.

I just realized another use case I do with netflix: Casting to chromecast. In that case the controls also don't work in the launcher (they do in the message section).

Best regards.
