### ISSUE TITLE
Good feed integration and dailer integration in home page.

### ISSUE THREAD

**Issue by ShaviSuri** [8bitPit/Niagara-Issues#622]
Many users have habit to check google feed app Daily, I have an idea, you can place Google app icon near the time and date by default, So user will save space for more favourite apps. 
and I think we should Integrate phone app too somewhere by default. I don't have idea on phone app integration. 
Thanks, I wish you will consider my suggestion.

**Comment by 8bitPit** [comment]
Hey @ShaviSuri, there is already a button to open the Google app (which is almost like the feed), it's not enabled by default and can be found in Home screen > Google button in Niagara's settings. The dailer could be opened in the same way, see: #175.

**Comment by ShaviSuri** [comment]
Thanks for your reply.

**Comment by 8bitPit** [comment]
You're welcome.
