### ISSUE TITLE
Add option to not show recommended apps?

### ISSUE THREAD

**Issue by karthikkasturi** [8bitPit/Niagara-Issues#623]
I think this should be present as an option as I would like limited apps on my home screen. I have 8 favorites they fit the screen perfectly but the recommended apps overflow and kind of spoil the clean feel for me which is why I use this launcher. Please let me know if this setting already exists and I'm just not looking in the right place.

**Comment by Rod911** [comment]
At the moment you can hide them as they show up by long pressing each app and selecting the 'stop suggesting' option.
See #128
