### ISSUE TITLE
Custom icon issue

### ISSUE THREAD

**Issue by ameykhaire** [8bitPit/Niagara-Issues#625]
![Attachment](https://i.imgur.com/X31uwEB.jpg)
In previous version some kind of icon would be applied to the apps but in this new version no icon is being applied. 

Note: the icon pack does not contain these icons

**Comment by Rod911** [comment]
What did you use to make the icons?
Try reinstalling the icon pack and select the icon pack again from Niagara settings.

**Comment by ameykhaire** [comment]
@Rod911 yeah already did that. These icons are not included in the icon pack then also the were changed automatically. But this is not happening in the latest version

**Comment by ameykhaire** [comment]
@Rod911 I used oriels icon pack

**Comment by Rod911** [comment]
What's the icon pack?

**Comment by ameykhaire** [comment]
@Rod911 oriels icon pack

**Comment by Rod911** [comment]
Seeing the same icons in lawnchair too, could be an issue with icon pack.
