### ISSUE TITLE
Recent Apps Section Disappears after screen turned off 

### ISSUE THREAD

**Issue by sxg997** [8bitPit/Niagara-Issues#629]
Each time I lock the phone, the recent apps section disappears. I can bring it back only till if I restart the launcher, but vanishes again once screen turned off.
I used hundreds of times various apps a day still no most used apps shown.
I think it may be occurring perhaps because I have more than 8 favourite apps set.
Please solve this bug. Most used apps section is a necessity instead I would suggest to provide an option to make it available at the top than at the last.

**Comment by berdzena** [comment]
https://github.com/8bitPit/Niagara-Issues/issues/550
