### ISSUE TITLE
Non-English sort problem

### ISSUE THREAD

**Issue by jook1356** [8bitPit/Niagara-Issues#631]
I submited a few days ago with this problem that non-english sort is not working. And now I realized that the reason of this problem. There are so many chinese words, and it can't be sorted. So developer decided not to sort non-english language, but I think it must apply only to chinese. Another non-english language alphabet is not like chinese, it just like english. Not so many alphabet. I think you know this well.

Please, I need non-english sort function so much.
It was very comfortable when non-english sort work well. But now, it's hard to find non-english apps. I believe that you will solve this problem very well.

How about to make option that non-english sort toggle switch?

Thank you for developers that realize this app, and I really respect developers.

**Comment by jook1356** [comment]
A little bit different. It looks only for chinese. I think it's better to roll back  to previous version that working all language sort support and you may support pinyin for chinese separately!

Thank you ^_^

**Comment by 8bitPit** [comment]
That's on my list as well :) #575

**Comment by jook1356** [comment]
Oh thank you so much!
I will wait :D

**Comment by 8bitPit** [comment]
Closed the issue here, to better keep track of everything.
