### ISSUE TITLE
Further slide down favorites for easy one hand use

### ISSUE THREAD

**Issue by ascended1** [8bitPit/Niagara-Issues#634]
Not sure if this has been suggested before, but I'd like to see the ability to further slide down the favorite apps menu to make it easier to use it one handed, especially for the very bottom favorite apps.

If you don't understand what I mean, take a look at Samsungs new One UI, were the presenter shows how the settings menu work. 

https://youtu.be/rsGJegE7DIw?t=129

**Comment by Rod911** [comment]
The UI is already adjusted for one hand use. You'll notice this only if you have a "tall" screen. See #112

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case the previous reply didn't help.
