### ISSUE TITLE
BUG - Spotify crashes using media buttons

### ISSUE THREAD

**Issue by thegoldgoat** [8bitPit/Niagara-Issues#637]
Every time I click on the media buttons on the home screen for Spotify, Spotify crashes - works fine with the stock music app.
If I click on the album image, Spotify opens correctly.
I guess the problem is that I'm not using the official Spotify app, my version is 8.4.70.666 armv7 released by Alex (don't know if it helps).
Lock screen and notification controls both work fine.

**Comment by 8bitPit** [comment]
Thanks for the report, it seems that the app isn't handling transport control events correctly, see: #485 & #500.
