### ISSUE TITLE
Automatic light/dark themes by time of day

### ISSUE THREAD

**Issue by deadcombo** [8bitPit/Niagara-Issues#640]
This would be great, and in my case it would match my system, which already does this system-wide.

Thank you.

**Comment by 8bitPit** [comment]
Thanks for your suggestion, could be implemented, is a low priority feature though.

**Comment by disacrol** [comment]
Shouldn't be too hard though 😊 I would also like this option, and it doesn't bring any configuration overhead to the menus.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
