### ISSUE TITLE
Clock Frozen at 9:00

### ISSUE THREAD

**Issue by Rapahannock** [8bitPit/Niagara-Issues#642]
Following the upgrade to Beta 0.6.2, the clock on the home screen is frozen at "9:00", for me.

I have tried rebooting my phone following the update.
-Force closing Niagara
-Clearing Cache
-Clearing Memory
-Uninstalling, then reinstalling.

I am Running Android 7.0
Phone: Asus AR

Thanks

**Comment by vulpes-vulpeos** [comment]
Same situation on Galaxy S7 G930FD running Android 8.0.0

**Comment by Rapahannock** [comment]
Issue corrected in beta 0.6.1. Thanks so much!

**Comment by Rapahannock** [comment]
Issue corrected in beta 0.6.1. Thanks so much!

**Comment by vulpes-vulpeos** [comment]
Issue solved, thank you :)

**Comment by 8bitPit** [comment]
Sorry for the trouble guys.
