### ISSUE TITLE
Music Player Cosmetic Issue

### ISSUE THREAD

**Issue by JKweiw** [8bitPit/Niagara-Issues#645]
The skip and back circle buttons on the music player gets sliced by the frames of the left and right side of the launchers main menu (favorites).

**Comment by 8bitPit** [comment]
Thanks for letting me know, the patch will fix that :)

**Comment by Rod911** [comment]
Seems fixed now

**Comment by 8bitPit** [comment]
Yeah, fixed in version 0.7.1.
