### ISSUE TITLE
Tunable spacing/sensitivity of alphabet on RHS

### ISSUE THREAD

**Issue by ghost** [8bitPit/Niagara-Issues#646]
I know there was a ticket (#498) specifically with respect to the sizing of the letters but I often find myself having to exert extra effort to correctly center my thumb on the letter I want because it's pretty sensitive to the distance travelled. It would be nice to see some combination of the following:

1. Add an option to increase the amount of distance the thumb must cover to move between alphas (e.g. decreased sensitivity)
2. Add an option to increase the letter size (already mentioned)
3. Add an option to change the spacing between the letters (similar to 1, but 1 is probably better)

**Comment by 8bitPit** [comment]
Hey @greyveil, thanks for your ideas. 
Here's another approach I mentioned two days ago in the Telegram discussion group:
> @timm0e proposed a similar idea to me a few days ago: Just like on keyboards, the hit region for the letters could change in relation to how often you open it, the size of the letter/space in between wouldn’t change to keep everything uniform.

**Comment by oarodrig** [comment]
Another option may be if moving between letter to letter got more granular as the speed of your swipe decreases. For example, when swiping at a normal pace, the launcher will behave much like how it does now. However, as swipe speed decreases, we can be given a larger area to scroll in before it moves to the next letter.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
