### ISSUE TITLE
App search - leverage store keywords, user tags

### ISSUE THREAD

**Issue by joedeveloper** [8bitPit/Niagara-Issues#647]
I am falling in love with this launcher! 

Still having trouble finding the apps I want quickly though.

I imagine that metadata from the app is available, such as categories etc leveraging those would help immensely I think.

Right now it looks like only the app name is considered.

A further enhancement might be to allow users to add custom tags / info that would also be considered for search results.

Thanks!

**Comment by disacrol** [comment]
Discussion on #58 includes your request, check it out.

**Comment by yashpalgoyal1304** [comment]
And, if the searched app is not installed, then that search can be opened in the Play store.... but this is not something I am craving for..... just the idea came to my mind..... (ref: lawnchair)

**Comment by joedeveloper** [comment]
> Discussion on #58 includes your request, check it out.

@disacrol - I actually quite like that the App search is separate from the Google search ( though I could live with it being unified as long as weighting could be customized ). What this is about is being able to find all your productivity / games / sound / photo related apps without having to do manual renaming hacks etc., or having a perfect memory.

@yashpalgoyal1304 True - I think the google search already does that though.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
