### ISSUE TITLE
Disable vibration after swiping right option

### ISSUE THREAD

**Issue by rishabhgautam9** [8bitPit/Niagara-Issues#648]
Swiping right on every app and notification creates a vibration even in dnd mode . If possible there should be option to disable the vibration while swiping. Thank you

**Comment by 8bitPit** [comment]
Yeah, I am thinking about adding a toggle for that for quite some time. However, I believe adding such settings could easily bloat the settings menu.

**Comment by rishabhgautam9** [comment]
Yes, true but if possible you can either add it in advanced setting or if not , is it possible that it is automatically disabled in dnd mode atleast.Thanks.

**Comment by skelewir** [comment]
You could detect system vibration setting instead of creating your own.

**Comment by 8bitPit** [comment]
@skelewir yeah, but I don't know anyone who has it enabled :P

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
