### ISSUE TITLE
Simple request - Search Icon 

### ISSUE THREAD

**Issue by geraldcfrancisco** [8bitPit/Niagara-Issues#652]
This is a very minor and i believe ahould be a quick fix, I use a pure black wallpaper and when i go to the app list, a search button will appear on the right  bottom of the screen. My only issue with it is that it has a slight white outline around the top edge of the button, when using a pure black wallpaper it shows up and sticks out like a sore thumb. Would be great if its just removed entirely as it doesnt really add to the aesthetic even when using a regular wallpaper. Cheers, lovin the launcher so far

**Comment by 8bitPit** [comment]
In fact that request isn't that simple. I am using a plain [Floating Action Button](https://material.io/develop/android/components/floating-action-button/) which seems to have a subtle rim light at the top.
