### ISSUE TITLE
advertising appears even if the cell phone is blocked

### ISSUE THREAD

**Issue by orionyt** [8bitPit/Niagara-Issues#653]
advertising appears even if the cell phone is blocked, And videos with sound appear, and that is heard when my cell phone is blocked, and I have to turn it on and shut down the sound of cell phone, which I do NOT want to do, please avoid that the ads appear when the cell phone is blocked.

**Comment by disacrol** [comment]
Are you sure that behaviour does not happen with other launchers? Which app exactly are you getting those ads from?

**Comment by Rod911** [comment]
Niagara does not have any ads. You may want to check which apps are showing ads using [this](https://play.google.com/store/apps/details?id=imoblife.toolbox.full) along with [this](https://play.google.com/store/apps/details?id=com.imoblife.checkadd_plug_in)

**Comment by orionyt** [comment]
Thank you very much for having clarified my question, I love this app, for
me, it is the best launcher I have seen and I think it should be used as a
factory launcher, although I have still seen some other bug; as for
example, that the applications are stuck remaining on others ...

**Comment by 8bitPit** [comment]
@orionyt I can guarantee you that Niagara doesn't contain any ads. 
I appreciate if you create a separate issue for your second bug report.

**Comment by orionyt** [comment]
Tank you, your app is incredible.

**Comment by 8bitPit** [comment]
@orionyt you're welcome, thanks for your kind words :)

**Comment by orionyt** [comment]
Thank you very much for having clarified my question, I love this app, for
me, it is the best launcher I have seen and I think it should be used as a
factory launcher, although I have still seen some other bug; as for
example, that the applications are stuck remaining on others ...

El 14 dic. 2018 12:21 PM, "Peter" <notifications@github.com> escribió:

@orionyt <https://github.com/orionyt> you're welcome, thanks for your kind
words :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/8bitPit/Niagara-Issues/issues/653#issuecomment-447392565>,
or mute the thread
