### ISSUE TITLE
Alternatively open GoogleGo when Pressing on G-Button

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#655]
Open the Google Go app when pressing on Google search button

**Comment by Rod911** [comment]
But if you implement #300 or #175, you'd solve both problems right?

**Comment by 8bitPit** [comment]
@Rod911 kind of, my idea would be that Google Go would open automatically if the Google app isn't installed, so the user doesn't have to remap it manually.

**Comment by pada23** [comment]
Please add an feature so that a tap on G icon will open Google webpage on chrome/browser in case no google/google go app is installed on the device

**Comment by 8bitPit** [comment]
Good idea @pada23

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
