### ISSUE TITLE
Align home objects (clock, date, weather, favourites, suggested) on top, middle or bottom of screen

### ISSUE THREAD

**Issue by chareos** [8bitPit/Niagara-Issues#661]
Please allow choice about whre to place home items (clock, date, weather, favourites, suggested)

Top
Middle
Bottom
of screen.

This would offer choice to play best with any wallpaper out there.

**Comment by 8bitPit** [comment]
I don't know if that's a real need, e.g. the clock should always stay at the top; the huge font size would make look it weird, when the clock is in between the date/apps.

**Comment by chareos** [comment]
Sorry, I meant the whole block clock+date+weather+favourites+suggested, not the single elements

**Comment by 8bitPit** [comment]
Ah okay, here's a similar idea: https://github.com/8bitPit/Niagara-Issues/issues/334
