### ISSUE TITLE
Samsung Themes wallpapers are misaligned 

### ISSUE THREAD

**Issue by seekr** [8bitPit/Niagara-Issues#663]
I've tested this in Galaxy S8 and S9:

When I pick a samsung theme, the theme wallpaper shows up shifted to the right as seen in the screenshot below.

This only applies to Niagara, if I switch to default launcher the wallpaper appears correctly aligned.

https://postimg.cc/ygmRqhJB/e32133c7

**Comment by 8bitPit** [comment]
Thanks for the report :)

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/663
