### ISSUE TITLE
Hide icon packs in app list by default

### ISSUE THREAD

**Issue by ankit-jawanpuria** [8bitPit/Niagara-Issues#667]
Will be nice if we get a setting toggle to remove icon cards from app drawer. Since icon cards clutters the drawer and they are of no daily use.

**Comment by 8bitPit** [comment]
Like in https://github.com/8bitPit/Niagara-Issues/issues/140? The issue only is about hiding icons in your favorites though, but that can be changed.

**Comment by Rod911** [comment]
You can hide apps by long pressing each app and selecting 'hide app'.
Alternatively, you can go to hidden apps in Niagara Settings and hide multiple apps by pressing the + button and selecting the apps you want to hide.

**Comment by ankit-jawanpuria** [comment]
How nice if we get a option in setting...
When checked... All icons cards get hidden by default. No hiding one by one.... Will be a charm

**Comment by 8bitPit** [comment]
@ankit-jawanpuria:

> Alternatively, you can go to hidden apps in Niagara Settings and hide multiple apps by pressing the + button and selecting the apps you want to hide.

**Comment by AtomAntReturns** [comment]
I think OP's talking about a text-only drawer, and wants a "disable all icons" option in the settings.. Correct me, OP, if I'm wrong

**Comment by ankit-jawanpuria** [comment]
@AtomAntReturns
I talking about an option in setting to disable/hide all icon cards from the app drawer

**Comment by AtomAntReturns** [comment]
Upload a mock-up, dude. It'll help devs get a better idea of what you want

**Comment by Rod911** [comment]
@AtomAntReturns Explain what you mean by "app card"? Secondly, why would you want to hide all apps? How would you open your apps then?

**Comment by ankit-jawanpuria** [comment]
@Rod911
Whenever we install an icon pack from play store. We by default get an icon of that particular icon pack in our app drawer. 
I feel one hardly uses the icon of icon pack. Hence an option to disable all icon of icon pack from app drawer.
Hope u now understand what I mean by icon cards

**Comment by ankit-jawanpuria** [comment]
Can telegram an screen shot of the setting from an different app. Which might help you to understand what I mean more clearly.
 Whagsapp/telegram 9431133616
@Rod911
@AtomAntReturns

**Comment by 8bitPit** [comment]
@ankit-jawanpuria Gotcha. As you know, I wrote you back on Telegram, but for the others, I re-post my response:
>Great idea Ankit. I thought about a system which recommends you which apps should be hidden (e.g. wallpaper apps - because you can access them by tapping on "wallpapers" or launchers - those are still available by tapping on  "set home app")

**Comment by 8bitPit** [comment]
@ankit-jawanpuria PS: you can also put attach images on GitHub, just paste them :P

**Comment by ankit-jawanpuria** [comment]
![img_20181229_160808_630](https://user-images.githubusercontent.com/44938548/50537360-76e7c480-0b84-11e9-8f7e-4ace1938e903.jpg)
![img_20181229_160802_828](https://user-images.githubusercontent.com/44938548/50537361-77805b00-0b84-11e9-813b-d490d6ecad40.jpg)

**Comment by ankit-jawanpuria** [comment]
hope now one understand what i wanted to say.

**Comment by 8bitPit** [comment]
Yeah, thanks for the explanation :)

**Comment by AtomAntReturns** [comment]
@ankit : what launcher is that ?

**Comment by ankit-jawanpuria** [comment]
@AtomAntReturns it's Hyperion Launcher
https://play.google.com/store/apps/details?id=projekt.launcher

But m addicted to Niagara Launcher right now. ☺

**Comment by Bushmills** [comment]
original post says "and are of no daily use". In fact, as one doesn't switch icon sets frequently, but tends to settle for the most favoured set and keeps it there - why would many other icon sets clutter the folder? Simply uninstall them. Additional benefit: no impact on storage.

**Comment by 8bitPit** [comment]
Niagara Launcher now suggests you to hide icon packs when you edit your hidden apps. This makes hiding all your icon packs a pretty quick process during setup without confusing the user (by hiding them automatically).
