### ISSUE TITLE
Implement Back Stack

### ISSUE THREAD

**Issue by xRayJiN** [8bitPit/Niagara-Issues#668]
Going back when you're in the section "Hidden Apps" takes you to the home instead of the settings

**To Reproduce**
1. Go to Settings
2. Click on Hidden Apps
3. Click on "←"
4. Go back to the home instead of the settings

Instead going back to the home i think it's a good idea go back to the settings as expected. 

**ScreenRecord**
[Google Drive](https://drive.google.com/open?id=1GION_2RnlgOzfMPOrQP9yBJ_cSx12RM_)

**Smartphone:**
 - Device: OnePlus 3
 - OS: Android 9.0.0 (Pie)
- App:  V. Alpha 0.7

**Comment by Rod911** [comment]
This is probably because a few versions back, the hidden apps section shortcut was in the bottom of the apps list along with the wallpaper and Niagara settings. In which case returning to home screen made sense. But since it's been moved into the settings, it should return to the settings itself. This is not a bug but a valid issue.

**Comment by 8bitPit** [comment]
@xRayJiN yeah, good idea, thought the same a while ago. My current architecture doesn't allow "backstacking" (save previous states, which will reopen when clicking on the back button) yet, but I'm working on it right now.

**Comment by xRayJiN** [comment]
That's great to know, thanks :D

**Comment by 8bitPit** [comment]
@kklorenzotesta noticed:
> On the add/replace widget menu when an app have more than one widget a click on it shows the list of widgets for that app. When pressing the back button I should go back to the main widget list instead of the main home, it is really annoying when I want to see which are the widgets that I can try.

**Comment by 8bitPit** [comment]
Implemented in v0.18: https://medium.com/niagara-launcher/polishing-niagara-launcher-f9c6f7e0c6ab
