### ISSUE TITLE
SD-Card apps won't stay "categorized"

### ISSUE THREAD

**Issue by prashantdawar** [8bitPit/Niagara-Issues#671]
After hiding sim toolkit from menu , it automatically comes back after bootup. Kindly fix this issue. Facing from at least a month now.

Device: nexus 5

**Comment by 8bitPit** [comment]
There is a bug which affects apps  installed on external storage. They won't stay as favorites/hidden. I'll try to fix that.

**Comment by prashantdawar** [comment]
It's system app. It's nexus 5.

**Comment by prashantdawar** [comment]
After hiding sim toolkit from menu, it comes back after restart. See these attachments for issue.

![screenshot_20181224-074012](https://user-images.githubusercontent.com/2283741/50389377-a1361e00-074f-11e9-885c-66b55abb81de.png)
![screenshot_20181224-074006](https://user-images.githubusercontent.com/2283741/50389378-a1ceb480-074f-11e9-9b0c-9568ddf3f8e0.png)
![screenshot_20181224-073959](https://user-images.githubusercontent.com/2283741/50389379-a1ceb480-074f-11e9-9a23-2f4bda4061ad.png)

**Comment by 8bitPit** [comment]
@prashantdawar it should be fixed by now (v 0.7.3), or does Niagara "unhide" apps from time to time?

**Comment by disacrol** [comment]
Strange, I've hidden Sim toolkit since I first installed Niagara and never noticed it again.
