### ISSUE TITLE
Few wee little requests

### ISSUE THREAD

**Issue by ekb606** [8bitPit/Niagara-Issues#673]
kill system clock on home page and replace with clock widget of chiice

add optional ability to insert top or bottom of screen taskbar for most important 3 to 5 apps you never moved even if you only open them once a year ... (especially great for tablet users)

integrate url and other nav links into app list

Great app, so far, until i loaded it I`d forgotten how stupidly complex Nova was and how hopelessly cramped and bloated most of its themes are.  Thank you.

**Comment by 8bitPit** [comment]
> kill system clock on home page and replace with clock widget of chiice

#44 


> add optional ability to insert top or bottom of screen taskbar for most important 3 to 5 apps you 
never moved even if you only open them once a year ... (especially great for tablet users)

https://github.com/8bitPit/Niagara-Issues/issues/573


>integrate url and other nav links into app list

Can be added as soon as shortcuts can be created; https://github.com/8bitPit/Niagara-Issues/issues/62


>Great app, so far, until i loaded it I`d forgotten how stupidly complex Nova was and how hopelessly 
cramped and bloated most of its themes are. Thank you.

Thank you :)
