### ISSUE TITLE
"Launcher3 keeps stopping" when swipe to clear backstage

### ISSUE THREAD

**Issue by lannyroyaldoyle** [8bitPit/Niagara-Issues#674]
Phone: Nokia 7 Plus (TA-1062)
Andriod Pie
When I swipe up from navigate bar, the clear all button is covered by my apps, and I try to swipe left or right to see my other apps, or click the clear all, it will flashback and remind me " Launcher3 keeps stopping"

**Comment by 8bitPit** [comment]
"Launcher3" is the default launcher on your device. Seems to be a system level bug, I can't fix that.
