### ISSUE TITLE
Suggestion: Swipe down to expand app notification instead of swipe right

### ISSUE THREAD

**Issue by joshiain** [8bitPit/Niagara-Issues#675]
I propose switching the expand notifications gesture to be a swipe down on the application, instead of swiping right.

This will keep things more consistent with android pie notifications, as currently you swipe down on notifications in the notifications panel to expand them.

It will also free up your swipe right gesture (perhaps to use to swipe between folders in the future?).

I understand that currently swiping down opens the notification panel itself, but you can change the initial activation area of this to be above the apps to avoid any conflict

**Comment by colbycdev** [comment]
I recommend swing down with t o fingers or similar for all notifications. However, you have a point

**Comment by 8bitPit** [comment]
@colbycdev one goal of Niagara is that you can use your phone with one hand. Two finger gestures can hardly be triggered single handed.

**Comment by colbycdev** [comment]
@8BitPit I call BS. I do it all the time with Nova

**Comment by joshiain** [comment]
@8bitPit Stock Android notifications is able to handle this by introducing a slight delay in expanding the notification to differentiate between scrolling and expanding the notification

**Comment by 8bitPit** [comment]
@colbycdev If you're holding your device like in the picture on the left, you don't have a second finger ready for a quick gesture.
![image](https://user-images.githubusercontent.com/9284845/50541740-09e82500-0bac-11e9-8b5b-628f193d2f52.png)

**Comment by 8bitPit** [comment]
@joshiain tried that already, unfortunately it felt poor. Also, discoverability would suffer.
