### ISSUE TITLE
Feature Request: Gesture Bar

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#68]
As I wrote in #2: 

> Here's an idea for how to solve the lack of possible one hand gestures: instead of totally hiding the nav bar you could replace it with either a bar of buttons for different actions, or a gesture based bar for different actions aka Pie's gestures, so a simple pill at the bottom of the screen, tapping it could bring up app search. 

Pulling right, up, double press and long press could be user - defined, and could be use to launch apps, open notif shade, open recent apps, etc. 

From #63: 

> Could have screen lock as either a double tap / long-press option, or as a dedicated button at the side of the bar alá Pie's rotation lock icon.

**Comment by 8bitPit** [comment]
Neat idea, that would indeed some gesture related issues. I would choose a round button at the bottom right though. With the following gestures: Single tap, long press and swipe (from the center of the circular button away, like a common camera toggle on lock screen).

**Comment by jakcharvat** [comment]
That's not a bad idea, I just personally love Pie's gestures which offer more flexibility and a greater amount of different gestures, hence why I suggested that, feel free to do yours. 

Your idea would also need a right/left handed toggle ;)

**Comment by emailradhesh** [comment]
Using Navigation Gestures helped me. I find combination of apps with specific goals for each shall help get better user experience. However each of us have own views about this request.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
