### ISSUE TITLE
Media Player doesn't jump to track start but to track before the played track

### ISSUE THREAD

**Issue by Bullnados** [8bitPit/Niagara-Issues#681]
Don't know if it is a feature request or a bug.
But if you press the backward arrow the player doesn't jump to the start of the strack, but to the track before.
Behaviour
Track 3 -->Backward --> Track 2
Expectoin
Track 3 -->Backward --> Track 3 start

**Comment by 8bitPit** [comment]
I can't change it, that's implemented in your player.
