### ISSUE TITLE
Menu jumping

### ISSUE THREAD

**Issue by tamcl444** [8bitPit/Niagara-Issues#685]
## We're getting a lot of duplicate issues.
**Please use GitHub's search function to locate existing tickets and contribute to these instead of opening another one.**

---

**Describe the bug**
Alphabetical menus stay consistently positioned until letter "V" but are misaligned for the remaining letters. 

**To Reproduce**
1. Use the alpha scroll menu. 
2. Look at alignment of the letter headers for app menus on the left side of the screen. 

**Expected behavior**
Menu headers should remain consistently aligned. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung tablet
 - OS: Android 8.1
 
**Additional context**

**Comment by 8bitPit** [comment]
Thanks for the report, could you please provide a screenshot of the misaligning texts?

**Comment by tamcl444** [comment]
![screenshot_20190101-193404_niagara launcher](https://user-images.githubusercontent.com/46303898/50577752-e4058f00-0dfc-11e9-883b-b1a4df6a78e7.jpg)
![screenshot_20190101-193513_niagara launcher](https://user-images.githubusercontent.com/46303898/50577756-f2ec4180-0dfc-11e9-8f15-c7d0d0c98dcb.jpg)
![screenshot_20190101-193556_niagara launcher](https://user-images.githubusercontent.com/46303898/50577758-f8e22280-0dfc-11e9-9d87-38dc63daa4b4.jpg)
![screenshot_20190101-193619_niagara launcher](https://user-images.githubusercontent.com/46303898/50577759-fed80380-0dfc-11e9-9441-4e5c0394f541.jpg)
![screenshot_20190101-193630_niagara launcher](https://user-images.githubusercontent.com/46303898/50577760-05ff1180-0dfd-11e9-86f0-2c6ac4f9e5f8.jpg)

**Comment by tamcl444** [comment]
The difference in alignment occurs while the alpha menu at the right is being used to scroll.

**Comment by 8bitPit** [comment]
Thanks for the screenshots, here you can find some information why it's implemented in that way: https://github.com/8bitPit/Niagara-Issues/issues/36

**Comment by tamcl444** [comment]
Thanks, I didn't see that thread. For consistency, I would prefer the last menu item to end in the middle of the screen to keep the menu headers aligned, but that's just personal preference. Thanks for creating this. I have had many different devices and launchers over the years, and yours is the cleanest and best design by far.
