### ISSUE TITLE
White outline around G button on black wallpapers

### ISSUE THREAD

**Issue by globalplayers** [8bitPit/Niagara-Issues#686]
## We're getting a lot of duplicate issues.
**Please use GitHub's search function to locate existing tickets and contribute to these instead of opening another one.**

---

**Describe the bug**
On completely black wallpapers the Google G button has a small white outline at the top which can't be removed. 

**To Reproduce**
1. Set a completely black wallpaper

**Expected behavior**
The G button should be completely black

**Screenshots**
![screen](https://user-images.githubusercontent.com/22224229/50622049-be66ab80-0f0a-11e9-9c7b-a2e615e6b767.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 9 (Pie)

**Comment by 8bitPit** [comment]
Thanks for your informative report, you can find some information about that here: https://github.com/8bitPit/Niagara-Issues/issues/652
