### ISSUE TITLE
Wallpaper cropped half way

### ISSUE THREAD

**Issue by Zifoduk** [8bitPit/Niagara-Issues#687]
Wallpaper is cropped half way down the screen. Top half of screen is the bottom section of the wallpaper image and then the bottom half of the screen is black

**Comment by 8bitPit** [comment]
Thanks for the report. Did that happen after updating Niagara? Can the issue be reproduced?

**Comment by 8bitPit** [comment]
Furthermore, could you please tell me which device you're using?

**Comment by MyChiMan** [comment]
Same issue here, however i think it looks cool. (Until i want to change wallpaper)

Motorola Moto Z2 Play and Z2 Force. Thank you for all your work

**Comment by 8bitPit** [comment]
@MyChiMan thanks. Which apps are you guys using to set your wallpapers? Does it work properly with Google Photos?

**Comment by MyChiMan** [comment]
@8bitPit sorry for late reply.

Head down the alphabet - settings - look - wallpaper collection - "blurred photos" 
This was the one i tried to use. Everyone here uses about a quarter of the wallpaper. I can't recall if I searched for this and downloaded it or it was on the device sorry.

**Comment by 8bitPit** [comment]
Ah okay, and which app did you use to apply them?

**Comment by CarlosDunick** [comment]
google photos - use as - wallpaper ;) To be honest i can not remember if this was my eacxt procedure for it was many moons ago. I know I had to download it first. I may have used Gallery back then however.

Sorry I can not be more helpful, we all appreciate your follow up and continual work on your awesome launcher!

**Comment by Zifoduk** [comment]
Sorry for not replying.
The device is use is a Huawei P8 Lite 2017.
The bug happens regardless on which wallpaper app i use but more specifically ive tried: gallery, Huawei's themes app, Google Photos and Zedge.
This happens on all the niagra apps after update around december(i think).... currently using 0.7.3 and it still happens. Then it fixes itself after like 3 restarts of my phone.

**Comment by disacrol** [comment]
Are you sure it doesn't happen with other launchers?

**Comment by Zifoduk** [comment]
No it doesn't just Niagara

**Comment by 8bitPit** [comment]
Merged with https://github.com/8bitPit/Niagara-Issues/issues/688
