### ISSUE TITLE
Long Press App Shortcuts

### ISSUE THREAD

**Issue by ejchis** [8bitPit/Niagara-Issues#689]
I would prefer to be able to lock the desktop once it has been set and then access app shortcuts with a long press on the app rather than swiping. A long press is much more intuitive and distinguishable from the edge swipe to access all apps.

**Comment by 8bitPit** [comment]
I would say a long press, takes... well... a long time to perform, compared to swipes.

**Comment by ejchis** [comment]
Thanks for the quick response. I'm very much enjoying testing your launcher
so far. It's a great concept. Not being able to lock the home screen feels
like a big missing feature at this point. And I think having the option to
long press or swipe would add a much needed layer of polish. Could
definitely see this as a daily driver with those updates.

Eric

**Comment by 8bitPit** [comment]
Thanks, my idea was to split the menu into options (app info, uninstall, edit icon, etc.) & actions (notifications & app shortcuts). In my opinion the default launcher implementation makes little sense, for example:  why would you like to see notifications when you're about to move an app? Why would you click on uninstall when you want to launch shortcuts?
Furthermore, it's pretty hard to move apps accidentally in Niagara, you have to long press an app (takes one second), tap on "move", rearrange the app and then tap the apply button. Hence I believe there is no need for a locking option.

**Comment by rawkode** [comment]
I came to request this too. I'd prefer to swap swipe and long press, could this be configurable?

I find I often long press and then need to cancel and swipe. Using long press removes any cognitive blocks, as it's how other launchers work

**Comment by 8bitPit** [comment]
@rawkode At first I wanted to implement it that way. The problem with this approach is that the dialog shouldn't cover the app , so you can drag & drop it. With the long press menu, you cannot move apps accidentally and every option can be reached easily.

**Comment by 8bitPit** [comment]
@ejchis 
> to hide all of those unnecessary options from popping up once my desktop is
set.

You don't have to deal with them anymore, when you swipe on an app to open shortcuts :P
