### ISSUE TITLE
Request: Dual messenger support

### ISSUE THREAD

**Issue by josephwalden13** [8bitPit/Niagara-Issues#69]
Support for galaxy dual messenger apps. In the Samsung experience launcher they show up in the app drawer, however in most other launchers you can add them to the home screen as shortcuts. 

Loving the launcher so far btw :)

**Comment by 8bitPit** [comment]
Thanks! For shortcut support, see #62

**Comment by BluDragyn** [comment]
That's not the same thing though.

**Comment by BluDragyn** [comment]
Dual Messenger allows you to install a second copy of certain messaging apps (I know for sure that WhatsApp, Kik, and Snapchat are on that list), for use with multiple accounts. The second installation doesn't show up at all in Niagara.

**Comment by josephwalden13** [comment]
Actually it doesn't show up in any launcher except the galaxy one. For other launchers you add it as a home screen shortcut, so app shortcut support is all that's necessary

**Comment by BluDragyn** [comment]
Nova Launcher: https://s15.postimg.cc/jw5ms688r/20180910_203858.jpg

Rootless Pixel Launcher: https://s15.postimg.cc/r0ng0p7mz/Screenshot_20180910-204050_Rootless_Pixel_Launcher.jpg

Lawnchair: https://s15.postimg.cc/6gim2dci3/Screenshot_20180910-204420_Lawnchair.jpg

It shows up in launchers besides Samsung Experience. It's not just an app shortcut. It actually install a *second copy* of the app.

**Comment by BluDragyn** [comment]
Additionally, uninstalling the second copy causes the "main" icon to disappear in Niagara. Restarting the launcher brings it back.
