### ISSUE TITLE
T9 keyboard on app search

### ISSUE THREAD

**Issue by BrommD** [8bitPit/Niagara-Issues#692]
Hi, I would like to see an embedded T9 keyboard coming up, when the included app search function is invoked, instead the default keyboard.

Thx, Dejan

**Comment by 8bitPit** [comment]
Hi. If you want to open apps quickly, you can scroll to them with Niagara's scrollbar, that is even faster than opening search, waiting for the keyboard to open and typing. Also, I believe T9 keyboards are rarely used, so many are not familiar with concept anymore.

**Comment by BrommD** [comment]
Hi, thanks for fast reply. Well, I suppose the later reason might be the culprit hereby :) . Still a T9 is more accurate when having lot of apps installed, that any scrollbar...

Thx anyway

Dejan
