### ISSUE TITLE
[Feature Request] Developer commands list

### ISSUE THREAD

**Issue by AZMCode** [8bitPit/Niagara-Issues#698]
Have a list of developer commands pop up on the search screen when you type in slash, as if they were search results.

**Comment by 8bitPit** [comment]
Good idea, maybe that can be discovered to easily though. Most commands are meant for debugging.

**Comment by AZMPlay** [comment]
Maybe have a toggle for it in the advanced features setting menu, or under Miscellaneous->Advanced-> Debug options

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
