### ISSUE TITLE
Alphabet scroller on the bottom

### ISSUE THREAD

**Issue by pablomeza10** [8bitPit/Niagara-Issues#70]
This is kinda overkill but I'd like to see this feature, which is to put the alphabet scroller on the bottom and have the apps slide in horizontally. True, there would be sort of an issue with the navbar, but overall I'd think it would look cool.

**Comment by 8bitPit** [comment]
Yeah, it's creative, however i never saw a list scrolling horizontally on a phone app. I believe it is only used for tabs & pictures. Moreover there is not enough space to fit the scrollbar at the bottom.
