### ISSUE TITLE
Support for one plus 6T

### ISSUE THREAD

**Issue by prattsp** [8bitPit/Niagara-Issues#701]
The home doesn't utilise my complete one plus 6t 6.4" display and it shrinks within the limited boundary- infact only in the centre of the screen.

Also the icons are within a round circle... Which makes the actual icon smaller in size.... Hard to identify icons.

**Comment by 8bitPit** [comment]
> The home doesn't utilise my complete one plus 6t 6.4" display and it shrinks within the limited boundary- infact only in the centre of the screen.

It's planned that the area at the top can be adjusted: https://github.com/8bitPit/Niagara-Issues/issues/334

> Also the icons are within a round circle... Which makes the actual icon smaller in size.... Hard to identify icons.
Those are called adaptive icons. It seems your system set them as default. I did not implement a way to disable them yet, but you can install a custom icon pack or change the size of your icons in Niagara's settings.
