### ISSUE TITLE
Google and search buttons

### ISSUE THREAD

**Issue by DoggoOfSpeed** [8bitPit/Niagara-Issues#704]
Could you add an option to change the size of the Google (If enabled) and the search button?

**Comment by 8bitPit** [comment]
In my opinion there is no need to change the buttons size. It's 56dp x 56dp which is large enough to tap the button easily and small enough to not disrupt the layout.

**Comment by Vv2233Bb** [comment]
OK. It just looks weird when app icons are set to small.
