### ISSUE TITLE
Muzei problems

### ISSUE THREAD

**Issue by LumpBloom7** [8bitPit/Niagara-Issues#709]
Muzei will be shifted to the right even though there's only a single screen, with no way to center the wallpaper. 

Double tap gesture also doesn't get passed to the live wallpaper. Three finger tap works fine however.

**Comment by IdmFoundInHim** [comment]
I am able to reproduce the double tap issue, but not the centering problem. Perhaps the double tap gesture is reserved (but not implemented) in Niagara. I only use Muzei with still wallpapers. What is displayed to the left of the shifted wallpaper?

Samsung Galaxy Note5 Verizon on Android 7 (Nougat) Build NRD90M.N930VVRS3CRH1
Muzei v3.0.2

**Comment by LumpBloom7** [comment]
Well my wallpapers is wider than the screen itself, so instead of using the center, it'll just use the left part of the wallpaper.

Android 9.

**Comment by IdmFoundInHim** [comment]
Okay. My wallpapers aren't wide, so that would explain why I can't reproduce the first issue.

**Comment by disacrol** [comment]
And that centering issue only happens when using Niagara?

**Comment by LumpBloom7** [comment]
I'm not sure. Some launchers have it centered, some don't....
Action Launcher seems to have it centered (only consistent example I could give)

**Comment by disacrol** [comment]
I think I that happened to me when I used muzei some months ago.

**Comment by 8bitPit** [comment]
> Double tap gesture also doesn't get passed to the live wallpaper. Three finger tap works fine however.

@LumpBloom7 this has been implemented in v0.8.2 😃

**Comment by 8bitPit** [comment]
Duplicate of #687
