### ISSUE TITLE
Add option to hide clock/date

### ISSUE THREAD

**Issue by Maxr1998** [8bitPit/Niagara-Issues#71]

**Comment by 8bitPit** [comment]
Will be added

**Comment by databoy2k** [comment]
Could this be done as an option rather than mandatory? I preferred the look with AM/PM personally... Thanks. This is a great launcher.

**Comment by jakcharvat** [comment]
AM/ toggle is coming @databoy2k. This would also be optional 😉

**Comment by 8bitPit** [comment]
@databoy2k see #23.

**Comment by AtomAntReturns** [comment]
Thanks for the toggle option. Too bad it only hides clock and not the date. I like my homescreen with nothing on it except the wallpaper.

**Comment by Rod911** [comment]
Implemented in 0.6.1

**Comment by Maxr1998** [comment]
Yep, closing.
