### ISSUE TITLE
Option to toggle shadow overlaying status bar

### ISSUE THREAD

**Issue by gumnutTHFC** [8bitPit/Niagara-Issues#710]
I use a flat coloured wallpaper for simplicity's sake, and it looks quite ugly having a shadow overlay it. An option to toggle this shadow on/off would be great

**Comment by 8bitPit** [comment]
Sorry @gumnutTHFC, I've decided not to add this option to keep Niagara simple. However, there will be an option to hide the status bar all together (https://github.com/8bitPit/Niagara-Issues/issues/101)
