### ISSUE TITLE
More than 8 apps in favourites

### ISSUE THREAD

**Issue by pettably** [8bitPit/Niagara-Issues#711]
Could you please add a feature where we can increase the limit of 8 apps in the favourites. On my note 9, there's still plenty of extra room at the bottom

**Comment by Rod911** [comment]
There is no limit. You can add more favorites from the app list by long pressing your app and selecting add to favorites.

**Comment by pettably** [comment]
Oh ok. I saw the warning when I set it up, but as you said, I was able to select more afterwards

**Comment by Rod911** [comment]
Cheers
