### ISSUE TITLE
Left hand mode

### ISSUE THREAD

**Issue by CarnageMarkus** [8bitPit/Niagara-Issues#713]
It would be really nice to be able to see alphabet on the left side of screen.
As I am left handed, my initial "tap" is mostly a near miss of letter I actually wanted to go to... And I have to scroll right after to find what I wanted.
Therefore being able to switch alphabet to the left would make it more precise for me.

**Comment by Rod911** [comment]
You can already use the left side.
The scroll doesn't appear on the left so that it won't overlap the app names.
See #12

**Comment by CarnageMarkus** [comment]
I know i can scroll from both sides, but my accuracy is far from ideal, being left handed and having to guess correct vertical position, because alphabet is on the right. 

I am sorry for duplicate. The first post in referenced issue exactly reflects what I meant. :)
