### ISSUE TITLE
Custom actions on swipe right on app

### ISSUE THREAD

**Issue by raflut** [8bitPit/Niagara-Issues#716]
I think it is great that it is possible to swipe right on apps but I would like to have the possibility to set custom action when I swipe.

Currently when I swipe right on the Phone app I get quick access to 3 contacts but I cannot select the contacts my self. Also I would like the possibility to select more than 3 contacts.

Also it would be nice if the action on swipe right could be to open a different app or shortcut within an app. In that case I could set up the following:

* Clicking on Facebook opens facebook but swiping opens the facebook messenger app
* Clickiing on mail opens my mail app but swiping opens my SMS app.
* Clicking on camera opens my camera app but swiping opens my galley.

This would enable fast access to more apps but without adding more icons on the screen.

Swiping right on an app could also be used to open a folder so apps could be grouped and quickly reached. So clicking opens a main app and swiping opens/shows a folder.

The last is pretty much a duplicate of the folder request with the addition that clicking on a folder opens a pre set application and swiping right actually opens the folder.

**Comment by 8bitPit** [comment]
I'm sorry, I overlooked your issue. Your ideas sound great, I'll plan that the user can add shortcuts in favorites, the app list or further ones in the app swipe menu. Also I'm thinking about customizing the swipe right gesture, so you can open one shortcut faster instead of having a shortcut list. The shortcut only would only open instead of the menu if the corresponding app doesn't have a notification attached.

**Comment by geohaze** [comment]
Has this issue ever been fixed? I can't seem to change the contacts in the list the phone app gives.

**Comment by 8bitPit** [comment]
@geohaze nope, all issues that are open have not been implemented yet. #88 might also do the job for you and may be added sooner.

**Comment by 8bitPit** [comment]
Implemented a couple of weeks ago but forgot to close this issue 😅: https://medium.com/niagara-launcher/niagara-pros-swipe-actions-8b45b16ae8c3
