### ISSUE TITLE
Typo/spelling

### ISSUE THREAD

**Issue by jamierc** [8bitPit/Niagara-Issues#722]
Under options, features, advanced, limit suggestions - it currently says 'Less suggestions'. This should say 'Fewer suggestions'.

Grateful if you could amend. Thanks

**Comment by 8bitPit** [comment]
Oh thank you!

**Comment by ButtsBrow** [comment]
In UK English "Favorite" includes a "u" so Favourite. Would this be automatic in a final version if it is picked up from the users language choice in settings.

**Comment by 8bitPit** [comment]
@ButtsBrow it's possible, English (UK) could be added on [Crowdin](https://crowdin.com/project/niagara-launcher/settings#translations)

**Comment by 8bitPit** [comment]
Fixed in v.0.7.5
