### ISSUE TITLE
Apps not found in app drawer after removing from favorites

### ISSUE THREAD

**Issue by eldavidmx5** [8bitPit/Niagara-Issues#728]
Apps not found in app drawer after removing from favorites. Not even after reboot. I had to uninstall and reinstall install apps to make them appear again.

**Comment by 8bitPit** [comment]
Which app was it? Did you rename it? Or could it be, that you hid it by accident?

**Comment by eldavidmx5** [comment]
It was Pandora. I looked in the hidden apps and it wasn't there. I did re named it with just blank spaces to remove the name from the home screen.

**Comment by Rod911** [comment]
When you rename an app to a blank space it is moved to # section in the app list, ie to the top.

**Comment by eldavidmx5** [comment]
It must have been that. I never noticed that section before. Thanks!

**Comment by eldavidmx5** [comment]
It must have been that. I never noticed that section before. Thanks!
