### ISSUE TITLE
Facebook Messenger notifications are duplicated

### ISSUE THREAD

**Issue by JayJeyaruban** [8bitPit/Niagara-Issues#730]
**Describe the bug**
Facebook Messenger notification is duplicated (most recent). Didn't have this issue on previous version of launcher.

**To Reproduce**
1. Get FB Messenger notification

**Expected behavior**
Single notification (per message)

**Screenshots**
https://imgur.com/a/p8j3VLC

**Smartphone (please complete the following information):**
 - Device: Nokia 7 Plus
 - OS: 9 Pie
 - Launcher ver: 0.7.3

**Comment by 8bitPit** [comment]
Thanks for the report. A screenshot would be really helpful :)

**Comment by JayJeyaruban** [comment]
Edited with link to picture.

**Comment by 8bitPit** [comment]
Thank you. I could also reproduce the issue with a telegram private chat message. Will try my best to fix it.

**Comment by TricksterJo** [comment]
Just to contribute with another experience: I used Niagara but because I need to use regurlarly website shortcuts I'm momentarily using the default moto launcher and it's happening in this launcher too. I'm not sure it has to do with Niagara or not but considered this could be useful info.

**Comment by 8bitPit** [comment]
I didn't get any duplicated messages anymore. Does the issue still happen on your device? If so, feel free to open the ticket again.

**Comment by JayJeyaruban** [comment]
I still seem to have the issue on version 0.7.8

![niagara_error_n7](https://user-images.githubusercontent.com/17066459/57560714-a81ca080-737f-11e9-8ab6-3a828301c129.jpg)

**Comment by TricksterJo** [comment]
I have duplicated notifications when I enter the app. I get the first notification and then, when entering, the second one. Android 8, Moto G6 play.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by 8bitPit** [comment]
@JayJeyaruban could you reproduce the bug on a third party launcher?

**Comment by 8bitPit** [comment]
Furthermore, @TricksterJo & @JayJeyaruban can you please send me a the notification's metadata? You can do that by opening Niagara's app search and typing in "/notifications".

**Comment by JayJeyaruban** [comment]
@8bitPit I don't think I can reproduce the issue unless you can suggest a launcher? Nova launcher for example I long press on an icon and it will display a preview akin to what you show on the homescreen itself without duplicating (as I mentioned before, swiping right on an app to view the full notification works fine on Niagara and isn't the feature Nova has).

I've attached the notification meta as requested. I've replaced the contact's name with [redacted].
[niagara_notif_meta.txt](https://github.com/8bitPit/Niagara-Issues/files/3170540/niagara_notif_meta.txt)

**Comment by TricksterJo** [comment]
Here it is

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by 8bitPit** [comment]
Hey, does this still happen on the latest version? (https://github.com/8bitPit/Niagara-Issues/releases)

**Comment by JayJeyaruban** [comment]
Seems resolved one my 2 devices.

**Comment by 8bitPit** [comment]
Great :)
