### ISSUE TITLE
Start of app list appears inline with chosen letter when swiping letter list

### ISSUE THREAD

**Issue by JayJeyaruban** [8bitPit/Niagara-Issues#731]
**Describe the solution you'd like**
When swiping along the alphabet list, it would be nice if the start of the items of the letter you stopped at would be next to your thumb.

[Consider this image](https://imgur.com/a/OiMKF6U). I've swiped down to U. My most frequently tapped item for this letter is at the top of the list, however it will spawn at the top of the screen away from my thumb.

**Comment by 8bitPit** [comment]
Interesting idea. Problem is, that in your example, you wouldn't have much space for the apps if they appear at the bottom. Moreover, the constant of the alignment of the first app could look clumsy.

**Comment by JayJeyaruban** [comment]
Regarding the space for apps to appear at the bottom - this can happen regardless and require the user to scroll a bit if it's a long list anyway (I have a lot of apps beginning with T apparently). The idea was if it's a frequently used app, it would be at the top of the list for that letter anyway.

Regarding the possibly clumsy appearance - [I have this happen when I go to Y](https://imgur.com/a/XXEd1Et) (last letter I have) which is sort of what I imagined (just aligned next to the letter in the list) - unless this is a bug?

Maybe have this as an optional feature (or something like it) if there's enough interest?

**Comment by 8bitPit** [comment]
> Regarding the space for apps to appear at the bottom - this can happen regardless and require the user to scroll a bit if it's a long list anyway.

Yeah, but when moving apps more to the bottom, it would happen more often.

> [I have this happen when I go to Y](https://imgur.com/a/XXEd1Et) (last letter I have) and when I let go these items stay in place and the bottom of U appears above, settings below this etc. This is sort of what I imagined (just aligned next to the letter in the list) - unless this is a bug?

It is not a bug, more a not so good looking workaround: https://github.com/8bitPit/Niagara-Issues/issues/36

> Maybe have this as an optional feature (or something like it) if there's enough interest? [I see there might be some interest](https://github.com/8bitPit/Niagara-Issues/issues/732) in making it easier/quicker to select an app once a letter has been chosen from the alphabet.

Those are interesting ideas as well, unfortunately I didn't get any results which felt good yet.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
