### ISSUE TITLE
Allow selecting and starting an App directly

### ISSUE THREAD

**Issue by Flos** [8bitPit/Niagara-Issues#732]
**Is your feature request related to a problem? Please describe.**
I just installed the launcher and I like how simple and clean it is. But right now two steps are necessary to start an app. It would be awesome if we we could combine the "Search" of an app (A/z) with the opening of an selected app. ( One swipe to open an App) 

**Describe the solution you'd like**
I would suggest that the app allows in the left third of the screen to select between the found apps from that letter. Maybe it could be implemented a bit like a "Zoom" so the space between the Letters gets depending on the amount of apps and the distance to the left screen bigger, so that an selection between the apps is easy feasible. I see here two options,  by swiping fully to the left the currently highlighted app will open. 
Alternativ as soon as an app is highlighted, releasing the touchscreen will start that app.

**Comment by 8bitPit** [comment]
Sorry for responding so late. Are you suggesting something similar to: https://github.com/8bitPit/Niagara-Issues/issues/162?
