### ISSUE TITLE
Music widget doesn't work with newpipe

### ISSUE THREAD

**Issue by Gabgab2003** [8bitPit/Niagara-Issues#733]
The widget that displays on top of the homescreen displays an "app not available" toast if clicked, however pause next and previous work just fine. If there are any logs I can send, please tell me how to locate them.

**Comment by 8bitPit** [comment]
Thanks for the report. I could reproduce the bug & I'll to fix it.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.

**Comment by Gabgab2003** [comment]
@8bitPit no its fixed, thanks for your hard work :heart:

**Comment by 8bitPit** [comment]
Awesome, thanks for letting me know :D

**Comment by breakgimme** [comment]
i have the same issue on the latest stable release (some update broke it apparently)

**Comment by breakgimme** [comment]
> Hmm... @breakgimme does the notification not show up at all or is it just not clickable?

it does not have any title and you cant click on it (will throw an error) but pause, next and previous buttons work
![IMG_20201015_162210.jpg](https://user-images.githubusercontent.com/30757793/96142985-f0d87180-0f02-11eb-9495-5c7ac68efaac.jpg)

**Comment by 8bitPit** [comment]
Hey @breakgimme, I hope the first paragraph of the following article can help: https://help.niagaralauncher.app/article/11-media-player-widget-issues
