### ISSUE TITLE
Set picture files as app icons

### ISSUE THREAD

**Issue by real-mizuya** [8bitPit/Niagara-Issues#735]
I would love to set some icons (pictures in PNG-format) as app icon. Unfortunately, I can just set icon from icon packs. Can you add this feature? 
So the user can **select picture files and set them as app icons** 

PS: I searched for similar issues/requests, I only found this (https://github.com/8bitPit/Niagara-Issues/issues/458), but it's something different.

**Comment by 8bitPit** [comment]
Oh there is already  a similar issue open: https://github.com/8bitPit/Niagara-Issues/issues/581 ;)
