### ISSUE TITLE
add an option to set the launcher theme to depend on the device theme

### ISSUE THREAD

**Issue by 587saboor** [8bitPit/Niagara-Issues#736]
(the device theme meaning the dark and light modes in android pie)

**Comment by 8bitPit** [comment]
Good thought. I am also looking forward to an Android Q beta build. where the dark theme gets applied throughout the whole system, at least I hope so.

**Comment by 8bitPit** [comment]
Has been implemented in v0.9.0 https://github.com/8bitPit/Niagara-Issues/releases/tag/v0.9.0-beta
