### ISSUE TITLE
Smart links

### ISSUE THREAD

**Issue by doug-scott** [8bitPit/Niagara-Issues#737]
Would be nice if whenever an app's notification flag is set that app will be temporarily moved to the top of the list of apps, and once the notification is handled the app gets sent back to its original spot in the list.

**Comment by Rochey** [comment]
I think this would be great. I love the idea that the apps with notifications pop to the top of the home screen and then when you've finished with the notification the app would drop out (unless it's already a suggested app).
I think something similar to this has already been suggested too. Maybe #9 bit I'd have to have a look to make sure it was that one.

**Comment by 8bitPit** [comment]
Yeah, I would also suggest to post your ideas in #9. I had some similar ideas (a dedicated social/communication category). I'll share further details after I implemented the basic categorization system.
