### ISSUE TITLE
An option to put apps with notification to the top of the list

### ISSUE THREAD

**Issue by bala7s** [8bitPit/Niagara-Issues#739]
In the app list section, it would be nice if the app with active notifications would move to the top of the list above the letter A and #. So opening notifications from the app list rather than from the built in notification are would make accessing notifications faster and would eliminate the need of having a separate are for this specific purpose.

**Comment by 8bitPit** [comment]
Thanks for your idea @bala7s. You can share it in #9 if you want to. I've also got some plans for a notification category (for social/communication apps). More plans on that later.
