### ISSUE TITLE
An option to move apps list next to the letters. 

### ISSUE THREAD

**Issue by bala7s** [8bitPit/Niagara-Issues#740]
In this case the apps would stick to the letters on the righ side of the screen. This option would allows to make a lot new features and a new way to navigate in the UI: If I swipe vertically, I move between letters. However with a horizontal swipe I could shift the focus from the letter to the app in a specific letter and scroll through them. With a further horizontal swipe I could select the specific app with releasing my finger. This would be very similar to Else's UI that were introduced like 10 years ago.

**Comment by sangampandasp9** [comment]
I think this would be a great implementation!!
👍🏼👍🏼
Isn't it??

**Comment by bala7s** [comment]
No, or, at best, partly. That issue doesn't describe any working method, just mention the issue itself without further solution.

My idea is actually based on this concept UI: https://www.youtube.com/watch?v=M4sVGR5uRhc

This could be applied to Niagara, because the base of the tho is very similar. Both have a scrollable list where the pointer that select the desired section is your finger what you use for the scrolling itself. It is very quick and convenient, because this unifies the scroll and the select into one action.

Currently you can select the letter with scrolling, but it can be possible to select between individual apps with the same scrolling, and selecting the active one by simply releasing the finger.

Also it would be possible to implement adaptive icon's menu by showing the menu items next to the app icon, and it also would be accessible the same way as the icon itself.
I think this feature was also reported, but I can't find it right now.

**Comment by Rod911** [comment]
@bala7s like hotLittleDad's [idea](https://github.com/8bitPit/Niagara-Issues/issues/162#issuecomment-426955586)?

**Comment by bala7s** [comment]
> @bala7s like hotLittleDad's [idea](https://github.com/8bitPit/Niagara-Issues/issues/162#issuecomment-426955586)?

Yes, basically this is the same, but the design should be better than that.

**Comment by 8bitPit** [comment]
Merged with #162
