### ISSUE TITLE
A completely separate (third) screen for widgets. 

### ISSUE THREAD

**Issue by bala7s** [8bitPit/Niagara-Issues#741]
There are currently two screen, one for the home screen, and one for the app list. A third, above the home screen with the ability to put widgets there would be really great. It would be accessible with a vertical swipe.

**Comment by sangampandasp9** [comment]
I think it's not acceptable as it will kill the simplicity of Niagara as its light weight and also it will make it more complex !!
So I don't think so ...

**Comment by bala7s** [comment]
I think it wouldn't kill simplicity, but would be a really important feature, because I really miss the calendar widget for example.

**Comment by bala7s** [comment]
I commented this to #117. I guess this can be closed as duplication.
