### ISSUE TITLE
Triggering app list from active app

### ISSUE THREAD

**Issue by mubharad** [8bitPit/Niagara-Issues#742]
## We're getting a lot of duplicate issues.
**Please use GitHub's search function to locate existing tickets and contribute to these instead of opening another one. Most common features which are implemented in other launchers are requested already.**

---

**Is your feature request related to a problem? Please describe.**
Feature request. Currently to switch to another app from within an active app would entail using Android recent button. However Android recent button wouldn't serve the purpose when an app has not been used for quite some time and in such cases one has to go to home and then trigger the required app. Or use another app that will help launch what is needed.

**Describe the solution you'd like**
Being able to trigger app list (or search for app) while an app is active in the foreground would be quite useful. This is similar to the pie control available with some custom rom's.

**Describe alternatives you've considered**
A similar solution is available via Swiftly switch, JINA sidebar, Sesame. However having the feature native in Niagara would eliminate the need for such apps for effective multitasking.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
