### ISSUE TITLE
Mark apps as 'new' if they are newly installed

### ISSUE THREAD

**Issue by darkshuffle** [8bitPit/Niagara-Issues#747]
As there is no app drawer so to speak it would be nice to have some discrete marker on a new app that has not been opened or display then in the notification section (music player area) on the home screen.

**Comment by 8bitPit** [comment]
Good idea @darkshuffle, it's on my list :)

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/227
