### ISSUE TITLE
To make separate settings for music widget and app notifications

### ISSUE THREAD

**Issue by sangampandasp9** [8bitPit/Niagara-Issues#749]
It will be a great feature to make separate options for app notifications and music widget
Coz as the music widget is very useful, the app notifications kinda a bit brings down the look , So....

Really it's from"Brad"

**Comment by 8bitPit** [comment]
Thanks for forwarding the issue, it was also requested some time by someone else: https://github.com/8bitPit/Niagara-Issues/issues/111 though :P
