### ISSUE TITLE
Changing the length of the button that triggers launching an app

### ISSUE THREAD

**Issue by liyomlim** [8bitPit/Niagara-Issues#750]
I use the launcher on a tablet (SMP900) which is designed to be used in landscape mode. This leaves me with an issue with the "invisible" bar/button that triggers an app to launch. I understand that it's part of the design the launcher was going for, but on tablets, it becomes more of an annoyance when a very huge part of the screen that seems empty would be able to trigger something.

I suggest having an option in being able to resize the length of the button that triggers which gives respect to the original design or an option to just let the icons launch the app (which would be inconvenient for phones in my opinion).

Thanks for hearing me out :) Loved the launcher form the moment I installed it.

**Comment by 8bitPit** [comment]
Thank you. Does the empty touch area bother you because you trigger it accidentally?

**Comment by liyomlim** [comment]
Yep 😂 so its basically my fault hahaha

**Comment by disacrol** [comment]
This is yet another reason to really think how to address landscape mode 😉 https://github.com/8bitPit/Niagara-Issues/issues/255

**Comment by 8bitPit** [comment]
Merged with #841
