### ISSUE TITLE
Media Player widget goes missing randomly

### ISSUE THREAD

**Issue by lucassantilli** [8bitPit/Niagara-Issues#751]
Everything is working just fine, and then a few hours later you play a song and there's no widget. The issue also occurs when the app is force closed for any reason. When the app is restarted from settings the same problem occurs.

When it happens you have to go through Android settings and revoke Niagara's notification access, and after granting it again, the widget appears instantly even if a media is already being played.

**Comment by 8bitPit** [comment]
You're probably using a Huawei or Xiaomi device. They often force kill background services like Niagara's notification listener service, which is needed for getting the current song.
