### ISSUE TITLE
Remember search and scroll position when coming back to home from an app

### ISSUE THREAD

**Issue by laggingreflex** [8bitPit/Niagara-Issues#752]
**Is your feature request related to a problem? Please describe.**

Scenario 1: You search "R" and launch an app "Reddit". Then when you're done you press Home. 
Scenario 2: You scroll to "R" and launch "Reddit". Then when you're done you press Home. 

In both scenarios pressing the Home button you lose the search and the scroll position. 

Sometimes I find a rarely use app (so don't exactly remember its name, just found it scrolling or searching) and immediately after launching I wanna uninstall it, but there's no easy way to getting back to the search or scroll position from which I had launched that app.

**Describe the solution you'd like**

When pressing Home, it should remember and show the last used search result or scroll position.

**Comment by 8bitPit** [comment]
If you quickly return the launch screen, the position will be remembered. Maybe I should increase the time span for it to happen though.

**Comment by 8bitPit** [comment]
Okay, I increased the threshold to 5 seconds (it was 3 seconds before). There is also some initial delay from the framework itself, so you'll have to add approximately two second to those numbers.
