### ISSUE TITLE
About Chinese Pinyin Sorting

### ISSUE THREAD

**Issue by dibin666** [8bitPit/Niagara-Issues#754]
This page will enable your app to sort Chinese alphabets.In China, many people use your launcher and hope that the next version will support Chinese initials.

https://blog.csdn.net/awu_scanner/article/details/52593509

**Comment by 8bitPit** [comment]
Thanks, you can find the corresponding issue here: https://github.com/8bitPit/Niagara-Issues/issues/754

**Comment by yfdyh000** [comment]
#234.

**Comment by 8bitPit** [comment]
oh, I linked this post itself, instead of the Pinyin-issue. Thanks for the correction @yfdyh000.
