### ISSUE TITLE
Google search on home screen

### ISSUE THREAD

**Issue by prabhumns** [8bitPit/Niagara-Issues#758]
Right now there is an option to add google search button on home screen. But it is opening google app now. Instead it would be better if it open search shortcut directly which automatically opens keyboard also with cursor in the search place. Right now that search shortcut is accessible by right swiping the google app and clicking search there.

**Comment by 8bitPit** [comment]
You can also swipe up on the Google search button to open quick search.

**Comment by 8bitPit** [comment]
Maybe you'll be able to customize the button in a future release: https://github.com/8bitPit/Niagara-Issues/issues/300
