### ISSUE TITLE
Swipe down on home screen fir notifications

### ISSUE THREAD

**Issue by prabhumns** [8bitPit/Niagara-Issues#759]
Home screen now looks great. Thanks to this launcher. But i am missing swiping down anywhere on home screen to see notifications. That feature is helpful as right now there is no action for swiping down on Home screen.

**Comment by 8bitPit** [comment]
Thank you. Actually there is already a swipe down to access notifications feature implemented, but you may have to swipe faster to trigger it. It is far from perfect, see: https://github.com/8bitPit/Niagara-Issues/issues/362

**Comment by prabhumns** [comment]
Please decease the speed that we have to swipe for notifications and i think it is working only on top half of screen. It should work for whole screen.

**Comment by 8bitPit** [comment]
@prabhumns the problem is that it works better on some devices than on others, e.g. on an Essential Phone, which I'm using, the gesture works great.
The gesture can be triggered from the bottom half on every device though.
