### ISSUE TITLE
Unifying favorites & app list

### ISSUE THREAD

**Issue by prabhumns** [8bitPit/Niagara-Issues#761]
Right now as far as i know we can access menu only by side quick scrolls to specific alphabets. I saw some suggestions mentioning to allow to directly scroll for complete menu. This removes the feeling of menu and home screen being different. My idea is that when we scroll down the home screen it ends let it stick there for the first time but it should scroll continuously to the menu if we scroll at the same place for the second time just after first time. Which means that double scrolling at the end of hone screen should open complete menu. Finally it looks like stock android 9 home screen gestures where it sticks at some place and second scrolls shows complete menu.

**Comment by 8bitPit** [comment]
The easiest and probably cleanest way to implement it would probably a swipe up gesture which works like "swipe to refresh", but you swipe from the bottom up. However that would also take the gesture which could also be used for accessing the app search or something else. Please join the discussion here: https://github.com/8bitPit/Niagara-Issues/issues/122

**Comment by PaulBags** [comment]
No, no app search - this. Niagras an apps list, please just scroll.

Search is a feature of last resort, if I'm hitting search something went wrong - I don't want to get there from a gesture.

Doing nothing is better on swipe up than search.
