### ISSUE TITLE
Niagara settings and wallpaper default icons

### ISSUE THREAD

**Issue by MyChiMan** [8bitPit/Niagara-Issues#765]
Hey guys, My partner and I Love your launcher. We just want to see it grow! Motorola Moto Z Play, Moto Z2 Play & Moto Z2 Force.

So a cosmetic suggestion is to be able to change the default icons "settings" & "wallpapers" when you scroll down to the bottom of the alphabet.

After you spend all your time customising your home screen and to go to the bottom of the list to find these terribly bland icons not matching is an eye sore. 
Can you make this happen please?

-Two other points was moving the clock closer to the notifications to free up space and remove dead space.
-Some form of landscape enable/disable mode.
(I have found the threads and commented)

Thank you guys for bringing us this launcher! Keep up the great work!

**Comment by 8bitPit** [comment]
> So a cosmetic suggestion is to be able to change the default icons "settings" & "wallpapers" when you scroll down to the bottom of the alphabet.

Good idea! It may take some time though, since it's not an essential feature and I've got a tightly packed schedule.

> Hey guys, My partner and I Love your launcher. We just want to see it grow! Motorola Moto Z Play, Moto Z2 Play & Moto Z2 Force. 
Thanks a lot, give your partner my regards :)

**Comment by CarlosDunick** [comment]
Thanks! I will pass that on. Good luck with your project. When you are ready to charge, we are ready to pay.

**Comment by rd836** [comment]
Please tuck the Niagara Wallpapers into the Niagara Settings, so there is only one item visible pertaining to Niagara.

**Comment by MyChiMan** [comment]
I don't know how to do that. Nothing's working for me can you please tell me how?

**Comment by disacrol** [comment]
@rd836 please create a separate thread for that suggestion, thanks

**Comment by disacrol** [comment]
@MyChiMan I believe he's not asking you to do that, he's just suggesting another improvement to the dev.

By the way, I noticed you also suggested some sort of screen rotation support. I'm also keen to such feature 😉 you can follow and contribute to that discussion here: https://github.com/8bitPit/Niagara-Issues/issues/255

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
