### ISSUE TITLE
Notification not dismissing on swipe

### ISSUE THREAD

**Issue by rainaakshay** [8bitPit/Niagara-Issues#766]
on expanding the notification box, it doesn't dismiss notifications on swipe. On poco f1 running android 9 miui 10

**Comment by 8bitPit** [comment]
Thanks for the report, I noticed the bug as well, but unfortunately I couldn't fix it yet.

**Comment by prabhumns** [comment]
I faced the same issue with same device. But i restarted my device once. It is fixed now. Try restarting ur device once.

**Comment by 8bitPit** [comment]
I still couldn't figure out the root cause, sorry. Btw @prabhumns, restarting Niagara (you can do that in Niagara's settings > Advanced) should be enough.

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/428

**Comment by nijoachacko** [comment]
It sane as on my Xiaomi MiA1
