### ISSUE TITLE
Wether, gps location.

### ISSUE THREAD

**Issue by CiPiT13** [8bitPit/Niagara-Issues#767]
Thank you. Very minimalist launcher. I really loved this launcher. One thing about whether, I can't always turn on my gps location because it takes a lot of power. Again thank you!

**Comment by 8bitPit** [comment]
Thanks for the kind words. You can find the reasons why location needs to be on for receiving the weather here: https://github.com/8bitPit/Niagara-Issues/issues/179

**Comment by CiPiT13** [comment]
Thank you 8bitPit. I read about Google's Awareness API and understood all.
Good luck.

вс, 24 февр. 2019 г., 17:04 Peter <notifications@github.com>:

**Comment by 8bitPit** [comment]
Thx :)
