### ISSUE TITLE
Back Up/Restore • Feature

### ISSUE THREAD

**Issue by NeoXIkaros** [8bitPit/Niagara-Issues#769]
Here's Hoping It's Not Duplicated 

But How About The Ability To Back Up/Restore Your Current Look & Settings Of Your Niagara • Launcher Just In Case You Change Smartphones And What To Keep The Exact Same Setting, Name Changes, Icons, Hidden Apps....Etc.

As Soon As I Get A New Smartphone I Install The Launcher Because Well...It Is The Greatest :) And Personally Couldn't Compare To Any Other (My Opinion Of Course).

However It Can Be Somewhat Bothersome To Edit The Launcher to My Liking From Scratch Every Time.

Lots Of Love Cheers!

**Comment by Rod911** [comment]
Planned. #222
