### ISSUE TITLE
Restore non-English sort order

### ISSUE THREAD

**Issue by stephenjfox** [8bitPit/Niagara-Issues#770]
The launcher used to show all apps sorted alphabetically (perhaps in Unicode order). It's been a few releases but this is not longer the case.
Now, all non-English app names are grouped under "#" in the app list, their alphabets ignored.

---
Background: I'm an American polyglot and I don't keep my phone in English. Because of i18n, some  app names change to whatever language I'm in. If that's something like Japanese or Korean (which have a syllabery and alphabet respectively) I would expect these characters to have their own "section" in the app list, just as Airbnb, Alarm and Away are all under the "A" section.

Hope that wasn't confusing.

**Comment by disacrol** [comment]
@stephenjfox is this what you mean? https://github.com/8bitPit/Niagara-Issues/issues/455

**Comment by stephenjfox** [comment]
@disacrol Actually, no. I __wish__ that was the case, but I don't have that behavior anymore.
On my phone, all apps that have a non-ISO/English first-character are grouped _un-alphabetically_ under `#`

**Comment by disacrol** [comment]
You shouldn't have had this behaviour because it was not implemented yet, hence that issue is still open.

This is why, for the time being, apps are grouped under "#".

Sorry if I'm not understanding what you mean.

**Comment by voidby** [comment]
Still exists in 0.7.5
