### ISSUE TITLE
Redrawing of launcher everytime the wallpaper changes

### ISSUE THREAD

**Issue by Martinligabue** [8bitPit/Niagara-Issues#775]
**Describe the bug**
I use an automatic wallpaper changer (the app from j4velin), every time I unlock the screen it changes the wallpaper, and the launcher resets, if I scroll it restart from the favourites more or less a second after unlocking
**To Reproduce**
1. Use Wallpaper changer, set to "change every time the screen unlocks"
2. Unlock the screen and try to scroll
3. The launcher will like restart(?) going back to favorites after some seconds

**Expected behavior**
It shouldn't redraw

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Device: Mi A2 Lite
 - OS: Android 9 (Pie)
 
**Additional context**
Not applicable

**Comment by 8bitPit** [comment]
It partially restarts itself to apply changes in the theme, but you can disable auto theming in Niagara's settings. You should also disable that for the text color.

**Comment by erikaemma** [comment]
> It partially restarts itself to apply changes in the theme, but you can disable auto theming in Niagara's settings. You should also disable that for the text color. Hope it helps

How to disable it?

**Comment by 8bitPit** [comment]
@erikaemma you can disable our dynamic theme by going to _Niagara settings_ > _Look_ > _Theme color_ and changing the color from _Auto_ to something else.
