### ISSUE TITLE
Home App - Unable To Make Niagra Default - Pixel XL 3 w Work Partition

### ISSUE THREAD

**Issue by KKenui** [8bitPit/Niagara-Issues#777]
I'm unable to keep Niagra as the default Home Launcher so everything I do I get a pop-up asking me to select which program to use. Ive tried all the basics, cleared cache on both home launchers. Uninstall reinstall. Tried going all different ways to select Niagra. When I select Niagra it pops to Niagra home. When I go to verify it's default

**Comment by 8bitPit** [comment]
I'm sorry to hear that. Are you using the version from the Play Store or an alpha build from the Telegram group?

**Comment by thgirb** [comment]
I also have the same problem. Is there anything I can do?

Play store version.
My phone: Doogee BL7000

Thank you for your time :)

**Comment by 8bitPit** [comment]
Have you tried going to Android's settings > Apps > Default Apps > Home app > Niagara?
Furthermore, do other launchers stay as default? If yes, which apps?

**Comment by thgirb** [comment]
Yes, I have already tried that, but it is still asking me everytime I press the home button.

Previously, I used Nova launcher and it worked just fine.

Thank you :)

On Apr 4, 2019 22:53, Peter <notifications@github.com> wrote:

Have you tried going to Android's settings > Apps > Default Apps > Home app > Niagara?
Furthermore, do other launchers stay as default? If yes, which apps?

**Comment by 8bitPit** [comment]
Hmm... maybe the launcher launcher crashes when its going to the background. In that case an error message pops up after two consecutively occurring crashes.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.

**Comment by KKenui** [comment]
It does. Even after all the update.  Unsblr to even use

℅©®™

**Comment by 8bitPit** [comment]
Hey @KKenui can you set other third-party launchers like Nova Launcher as deafault? If not, I'm afraid I can't help. This might be a restriction from your work or from the device.
