### ISSUE TITLE
My Observations

### ISSUE THREAD

**Issue by JosephSeun** [8bitPit/Niagara-Issues#780]
1.) I think it would be nice if the background could blur a little more when swiping to view all apps 
2.) A Google now integration would be amazing
3.) Option to edit size of date and time

That's all I think would be good for now. Thanks, the launcher is really amazing

**Comment by 8bitPit** [comment]
Hey, thanks for your requests, here are some related issues:
1) https://github.com/8bitPit/Niagara-Issues/issues/14 & https://github.com/8bitPit/Niagara-Issues/issues/705
2) #3 
3) #188 & #117 

Btw, please request one feature per issue next time :P

**Comment by JosephSeun** [comment]
Instead of a white or dark background for the notifications, could it maybe
be a blurred background or everything else on the screen blurs apart from
the notifications

Sorry for sending so many issues by the way. :D

**Comment by 8bitPit** [comment]
No problem at all :D
