### ISSUE TITLE
Time indicator for media player

### ISSUE THREAD

**Issue by casungo** [8bitPit/Niagara-Issues#783]
It would be cool if the current time of the song was displayed in some way.
I have made some sort of guideline here ![Niagara suggestion](https://user-images.githubusercontent.com/25723446/53912578-863e2f00-4059-11e9-8bb9-c6e98479a2c8.jpg)
Maybe the colour should change based on the wallpaper and/or adjusted manually.

**Comment by 8bitPit** [comment]
Thanks for the mock-up, cool idea!

**Comment by Kilo-Five** [comment]
This would be great so long as its minimal in its implementation!

**Comment by 8bitPit** [comment]
Merged with #783
