### ISSUE TITLE
Request: Option to disable most used entirely

### ISSUE THREAD

**Issue by ericHumanFriend** [8bitPit/Niagara-Issues#784]
I personally prefer the look of my homescreen without any app logos. I find that navigating by scrolling is fast enough for me with Niagara that I prefer the aesthetic of a clean homescreen over the convenience that the most used apps section provides. Because I manually remove each app as it appears in my most used anyway, I would appreciate a toggle in the settings to disable the most used section entirely.

Thanks,
  Have a nice day!

**Comment by 8bitPit** [comment]
Hey @ericHumanFriend, thanks for bringing it up. However, there is already an open issue about disabling suggestions entirely :P
https://github.com/8bitPit/Niagara-Issues/issues/224
