### ISSUE TITLE
Add feature to right-align app list

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#788]
With the new feature to hide app names, should there be an option to put all the app icons and the interface on the right for more intuitive one-handed usage? It would make it easier to reach the actual icons
<del>I'm not entirely sure about this one myself.</del>
Here is an elementary mockup. After looking at it, I am starting to like the idea more.

![20190309_163755](https://user-images.githubusercontent.com/30935172/54077706-59249300-428a-11e9-9df8-229609cdb186.png)

**Comment by 8bitPit** [comment]
Thanks for the mockup, that design would probably go well with #12

**Comment by IdmFoundInHim** [comment]
True, though I personally would use it right-handed. It would have a slightly different feel. I already find the launcher to be usable with one hand (kudos for that). I just think it would feel more natural to tap/swipe on icons rather than empty space.

**Comment by 8bitPit** [comment]
Nevertheless, I'll merge this with the left hand mode issue, because the layout would be identical, but you don't have to use this mode with your left hand of course. You could still scroll on the right hand side, just like you can do that already on the left hand side.

**Comment by 8bitPit** [comment]
Merged with #12
