### ISSUE TITLE
App search

### ISSUE THREAD

**Issue by colin-walker** [8bitPit/Niagara-Issues#790]
Feature suggestion/alteration.

Instead of "Press home to search" could there be an option to "Swipe up to search" which mirrors the swipe down for notifications action.

For those using gestures and have navigation buttons hidden it might be a better option.

**Comment by colbycdev** [comment]
I like this, since I use my fingerprint sensor as one button nav, and long press home button isn't exactly an option

**Comment by 8bitPit** [comment]
Thanks for the suggestion, if you want to, you can join the discussion here: #122
