### ISSUE TITLE
Option to hide status bar on homescreen

### ISSUE THREAD

**Issue by lwrncslcd** [8bitPit/Niagara-Issues#792]
Currently I use Full Immersive mode from a SystemUI Tuner app to hide the status bar on the home screen and everywhere. But there is an issue with Niagara launcher when I reply to a notification, the reply box gets hidden behind the keyboard. I was wondering if we could have the support to have the option to hide the status bar from within the launcher itself.

**Comment by lwrncslcd** [comment]
When Status bar is on:
https://i.imgur.com/F5ULKN6.jpg

Full Immersive mode on:
https://i.imgur.com/i5dDNve.jpg

**Comment by 8bitPit** [comment]
Duplicate of #101 & #43
