### ISSUE TITLE
Auto favourites and all align to middle

### ISSUE THREAD

**Issue by JosephSeun** [8bitPit/Niagara-Issues#797]
Could you guys make an option or feature that will automatically align all the favourites and widget to the middle (even when the music widget or notifications pop up they all get automatically aligned to the middle)

**Comment by 8bitPit** [comment]
Sorry for not replying @JosephSeun. The issue is similar to https://github.com/8bitPit/Niagara-Issues/issues/808, so I changed it's title to include yours.
