### ISSUE TITLE
Toggle for alphabetical sorting

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#8]
It could be nice to have a toggle to sort apps alphabetically within the sections. It would make it faster to find apps within the sections if you have many apps.

**Comment by Chaphasilor** [comment]
I didn't even notice it isn't sorted alphabetically until you pointed it out! Why? An alphabetic sort is the only thing that makes sense in a list-style drawer that's sorted by letters...

**Comment by jakcharvat** [comment]
@Chaphasilor it is sorted based on usage. Most used app on the top, least at the bottom. I'm OK with that, but Alphabetical scrolling would still be a nice option IMO

**Comment by 8bitPit** [comment]
To my eyes it’s cool, because you don’t have to “extra scroll” when you have more apps that fit in the screen. Most likely the app you want to use is on one of the top positions. Also, it’s so subtle that - as you mentioned - users won’t even notice, I like that.

**Comment by Chaphasilor** [comment]
@8bitPit well, I'm used to an alphabetic sorting, so for the letters where I have a lot of apps for I would automatically scroll down, so a option in settings would be nice

**Comment by 8bitPit** [comment]
Okay, can you test it for another few days and write back to me, if you are still bothered?

**Comment by Chaphasilor** [comment]
@8bitPit will do!

**Comment by 8bitPit** [comment]
Thanks!

**Comment by jakcharvat** [comment]
@8bitPit I like the during base on usage now that I've had the launcher for a while and it actually learned what I'm using. Maybe just making it so if there are apps that have either not been opened yet since installing the launcher or that have the same number of installs, then those get sorted alphabetically? I found it frustrating when I first opened the launcher and had sis all over the place, with the ones I use most in the middle 😉

**Comment by 8bitPit** [comment]
I fear that user will then forget about the option and don't change it later. Usually if there is no usage data yet, apps are sorted alphabetically. However I did add an automatic importer. It looks at all your installed launchers and places your pinned apps at the top of each letter section.

**Comment by Chaphasilor** [comment]
@8bitPit You might be right, but what about having it default to your sorting? Then those who really want to could change it and the rest doesn't need to bother.
Also while we're at it, this automatic importer you mentioned can't import browser shortcuts (or any other shortcuts probably) yet, I had some websites pinned to my homescreen and they all disappeared. Could those get imported as well?

**Comment by 8bitPit** [comment]
Sadly, the launcher doesn't support those kind of shortcuts right now. Just the so called "App shortcuts" that were introduced in Android 7.1. I've got some fancy ideas, e.g. they can be placed not only only in favorites, but also in the app list. Moreover, I want to have an suggestion system that recommends you to use shortcuts for most used apps. Shortcuts are a great Android feature, but it is not used by many and therefore I don't know if I should implement it yet. It would be quite time consuming.

**Comment by Shinra04** [comment]
@8bitPit Aren't app shortcuts the quick actions on the apps?

**Comment by 8bitPit** [comment]
@Shinra04, yup, those quicj actions are also called app shortcuts. The other type of shortcuts I referred to are "legacy" shortcuts. Visit #62 for more information.

**Comment by jakcharvat** [comment]
I think a feature showing suggested shortcuts could be quite cool

**Comment by Shinra04** [comment]
Are these legacy shortcuts different from app slices? I couldn't quite get what they were from the linked suggestion.

**Comment by 8bitPit** [comment]
@Shinra04:
App slices are the new widgets (introduced with Android P, but backwards compatible).
App shortcuts are those you get when you long press an app on a default launcher, they can change dynamically (Android 7.1+).
Legacy shortcuts are the oldest ones, those are usually also listed under widgets in a launcher. For example, "Add website to homescreen" is a legacy shortcut
