### ISSUE TITLE
Bind configuration also to keycode 82

### ISSUE THREAD

**Issue by Bushmills** [8bitPit/Niagara-Issues#801]
Users who configure their device to permanently show a menu button in the navbar do so for a predictable location of that button. They are also used to apps responding to that button, often by popping up the configuration dialog of the foreground application.
Though Niagara launcher features a configuration dialog (bottom of the alphabetic app selector bar), that configuration can't be opened by key code of the menu key.
By additionally binding Niagara configuration to that keycode, users will also be enabled to pop up the configuration dialog by tapping the permanent menu ḱey, rather than being forced to resort to the island solution to get to the configuration, as currently offered by Niagara launcher.
Users who don't configure such a permanent menu button wouldn't be affected at all by that addition, therefore backward compatibility is retained.

Estimated complexity: low
Nice to have
Basic feature,

**Comment by 8bitPit** [comment]
Good idea @Bushmills, almost forgot that the menu button exists ^^.

**Comment by 8bitPit** [comment]
To better plan ahead and give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that are unlikely to be implemented this or next year (2021 & 2022). This is one of those, unfortunately. I'm sorry.
