### ISSUE TITLE
Bitdefender claims Niagara is Adware

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#802]
After installing the latest update to Niagara (0.7.6a), Bitdefender has flagged it as containing Adware, specifically the threat Adware.Dowgin.gDJWV. I believe this is a false positive because there are no ads in the launcher. Is there any reason that Niagara would be seen as a threat?

**Screenshots**
![Screenshot_20190320-190830](https://user-images.githubusercontent.com/30935172/54726279-dbde0580-4b48-11e9-982f-74d774fe62b9.png)
![Screenshot_20190320-190836](https://user-images.githubusercontent.com/30935172/54726280-dbde0580-4b48-11e9-8da3-ba8a8f7db5ce.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note5 (Verizon)
 - OS: Android 7 (Nougat)

**Comment by stanleylai** [comment]
Seeing the same on Bitdefender Free.

Device: Pixel 2XL
OS: Android 9

**Comment by 8bitPit** [comment]
Thanks for the reports, I'll try my best to figure it out and keep you updated. I did not place any advertisements in the launcher.

**Comment by 8bitPit** [comment]
@IdmFoundInHim  & @stanleylai I've found out that Bitdefender has a submission form, especially for uploading false positives: https://www.bitdefender.com/submit/
Please upload Niagara's apk there and send it to Bitdefender. Maybe the Bitdefender team will take a closer look and whitelist it afterwards.

**Comment by disacrol** [comment]
In the meantime, that version is temporarily off play store to avoid any misunderstanding. Will be back as soon as this is figured out. Thanks!

**Comment by IdmFoundInHim** [comment]
Where would be the best place to get an APK? I probably need the affected version and couldn't find that one in the Releases tab.

**Comment by disacrol** [comment]
@IdmFoundInHim version 0.7.5a3 had that problem, and for some reason also the beta version that was uploaded to Google Play some days after (pulled off in the meantime). You can find the problematic apk in TG news channel from earlier this month.

**Comment by 8bitPit** [comment]
The latest apk(s) are not tagged as "agressive adware" anymore. Here's what I wrote in the Telegram news channel about it:
> Bitdefender, an antivirus app detected the last alpha as "aggressive adware”. As you can see, Niagara doesn’t contain any ads at all and I’m not about to change it. It appeared randomly, so I hope it goes away after just changing some lines of code. I’m sure it tries to detect some patterns which could have been removed by now, or maybe someone modified the apk, filled it with ads and uploaded it on a shady side. Someone else using Bitdefender could have downloaded it and Bitdefender blacklisted the apk, idk.

**Comment by 8bitPit** [comment]
But let me know if the issue reappears.

**Comment by IdmFoundInHim** [comment]
Sorry, I forgot about this for a while. But, that was only because the issue disappeared.

**Comment by 8bitPit** [comment]
Great :)
