### ISSUE TITLE
Screen lag / delayed screen response

### ISSUE THREAD

**Issue by mrcadillac** [8bitPit/Niagara-Issues#803]
I have to tap the screen once after coming from the lockscreen or from notifications and toogles for the launcher to be responsive

**Comment by 8bitPit** [comment]
Does it happen every time you unlock your phone? Moreover, can you please share a video which shows the lag?

**Comment by mrcadillac** [comment]
I stand corrected it doesn't do that when it is unlocked. However, it does every time I come from the notifications. 

https://gfycat.com/SharpCookedBrant 

Thank you.

**Comment by 8bitPit** [comment]
That's pretty weird, I haven't got similar reports yet. Could the delay come from your ROM?

**Comment by agudmund-git** [comment]
Can confirm, I'm having the same issue. Never took the time to figure out which circumstances led to it, but every time I pull down the notification shade, it recreates the issue

**Comment by 8bitPit** [comment]
Hey guys, this might be an issue with your firmware. I can't recreate this behavior and no one else mentioned this. Disabling notification dots on Niagara might help, but apart from that I have no idea. That's why I'm closing this.
