### ISSUE TITLE
Home and Lock Screen images revert to previously selected images

### ISSUE THREAD

**Issue by marcelholdinga** [8bitPit/Niagara-Issues#806]
Niagara appears to automatically revert the Home and Lock Screen images to pictures I had set a long time ago. 
Phone is Moto G6 64GB running Android 9. Issue occurred before updating to 9 from 8.0.0. The phone is not rooted
How can I make sure the backgrounds I set stay? All other launchers accept the images I set without reverting to an image I set 4 months ago...
Thanks in advance for any info/advice.

**Comment by disacrol** [comment]
@marcelholdinga that's odd. Which app do you use to set your wallpapers? Do that keep reverting back to the old ones or did it just happened once?

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
