### ISSUE TITLE
Notification not working in my Redmi Note 3 running Android Marshmallow 

### ISSUE THREAD

**Issue by Saurabh3333** [8bitPit/Niagara-Issues#810]
I am unable to see the notifications as expected from the launcher i.e. on the home screen. On swiping, it always shows "No New Notifications". Still, the native notification is working. I mean the I can see the notification in the notification panel. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 3
 - OS: Android 6(Marshmello) MIUI 10

**Comment by 8bitPit** [comment]
I'm sorry, if the notifications have stopped showing up, that might be an Android framework bug, which appears on Huawei/Xiami devices.
If they didn't even show up once, make sure Niagara has notification access.
Related issue: https://github.com/8bitPit/Niagara-Issues/issues/588

**Comment by Saurabh3333** [comment]
I have checked again, all possible notification access is already given. It is not shown even once.

**Comment by Saurabh3333** [comment]
@8bitPit I don't know how but suddenly notifications started working after a Niagara crash. 
Should I close this issue?

**Comment by 8bitPit** [comment]
Thanks for the info @Saurabh3333, it seems that it's the framework bug, it might reappear after receiving an update for Niagara. I might have a workaround though. I'll post updates in #588 and close this issue.
