### ISSUE TITLE
Media player sometimes not showing up on new version (0.7.7)

### ISSUE THREAD

**Issue by Rojo10000** [8bitPit/Niagara-Issues#811]
I know there's already a problem with some phones in which the widget doesn't show up in any version, but in my phone (Samsung Galaxy A5 (2017), running Android Oreo (8.0)) it used to show up in version 0.7.6, but it doesn't in version 0.7.7. I use Spotify to listen to music, and if I go back to another version, the widget shows up correctly.

**Comment by randompherret** [comment]
The update also broke podcast addict's widget

**Comment by Rojo10000** [comment]
Strangely enough, I haven't done anything and now it does appear...

**Comment by 8bitPit** [comment]
Thanks for letting me know guys, can you paste the notification's log here? You can get it by tapping on Advanced > Send notification log from Niagara's settings. It might look similar to this:
`--- com.google.android.music - Cider Time - Lifeformed---
Notification(channel=playback_v1 pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0xffff5722 category=transport actions=5 vis=PUBLIC)
FLAG_ONGOING_EVENT
FLAG_NO_CLEAR
FLAG_FOREGROUND_SERVICE
Oreo:
[show_badge=false]
[matchesInterruptionFilter=false]
[getImportanceExplanation=You set the importance of these notifications.]
[importance=2]
[has_low_importance=false]
Pie:
[userSentiment=USER_SENTIMENT_POSITIVE]
General:
[priority=0]
[has_low_priority=false]
[category=transport]
[text=Lifeformed]
[android.title=Cider Time]
[android.reduced.images=true]
[android.subText=Fastfall - Dustforce Original Soundtrack]
[android.template=android.app.Notification$MediaStyle]
[android.showChronometer=false]
[android.icon=2130838375]
[android.text=Lifeformed]
[android.progress=0]
[android.progressMax=0]
[android.appInfo=ApplicationInfo{e7db83d com.google.android.music}]
[android.showWhen=false]
[android.largeIcon=android.graphics.Bitmap@5d83832]
[android.infoText=null]
[android.wearable.EXTENSIONS=Bundle[mParcelledData.dataSize=896]]
[android.mediaSession=android.media.session.MediaSession$Token@6db59a2]
[android.progressIndeterminate=false]
[android.remoteInputHistory=null]
[android.compactActions=[I@efd3700]`

**Comment by Rojo10000** [comment]
Here you go, just keep in mind that right now it does appear; I'll try to send the log when Niagara doesn't show the media controls:

--- com.spotify.music - Billie Eilish---
Notification(channel=playback_channel pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x6a color=0xff121314 category=transport actions=4 number=0 vis=PUBLIC semFlags=0x0 semPriority=0 semMissedCount=0)
FLAG_ONGOING_EVENT
FLAG_ONLY_ALERT_ONCE
FLAG_NO_CLEAR
FLAG_FOREGROUND_SERVICE
Oreo:
[show_badge=false]
[matchesInterruptionFilter=true]
[getImportanceExplanation=Tú determinas la importancia de estas notificaciones.]
[importance=2]
[has_low_importance=false]
General:
[priority=0]
[has_low_priority=false]
[category=transport]
[text=Billie Eilish]
[android.title=bad guy]
[android.subText=WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? de Billie Eilish]
[android.template=android.app.Notification$MediaStyle]
[android.showChronometer=false]
[android.icon=2131231380]
[android.text=Billie Eilish]
[android.progress=0]
[android.progressMax=0]
[android.appInfo=ApplicationInfo{30c722d com.spotify.music}]
[android.showWhen=true]
[android.largeIcon=android.graphics.Bitmap@2e48362]
[android.infoText=null]
[android.mediaSession=android.media.session.MediaSession$Token@b1ffd12]
[android.progressIndeterminate=false]
[android.remoteInputHistory=null]
[android.compactActions=[I@2a2edb0]


--- android - Spotify se ejecuta en segundo plano - Spotify---
Notification(channel=FOREGROUND_SERVICE pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x2 color=0xff607d8b number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
FLAG_ONGOING_EVENT
Oreo:
[show_badge=true]
[matchesInterruptionFilter=true]
[getImportanceExplanation=Tú determinas la importancia de estas notificaciones.]
[importance=2]
[has_low_importance=false]
General:
[priority=0]
[has_low_priority=false]
[category=null]
[text=Spotify]
[android.title=Spotify se ejecuta en segundo plano]
[android.icon=17303932]
[android.text=Spotify]
[android.appInfo=ApplicationInfo{9eb0429 android}]
[android.foregroundApps=[Ljava.lang.String;@50b73ae]
[android.showWhen=true]

**Comment by 8bitPit** [comment]
@Rojo10000 I've found the bug and fixed it. An update will be available soon

**Comment by 8bitPit** [comment]
An alpha is available here: https://t.me/niagara_news
After a couple of days of testing it'll be released to the Play Store as well.

**Comment by markybob** [comment]
How can I completely remove the media controls?

**Comment by 8bitPit** [comment]
@markybob that's not possible without disabling all notifications. However, a toggle is planned: https://github.com/8bitPit/Niagara-Issues/issues/111

**Comment by 8bitPit** [comment]
Fixed in v.0.7.8
