### ISSUE TITLE
Make hidden apps easier to access like double tap or something like that

### ISSUE THREAD

**Issue by Gabe-hrh** [8bitPit/Niagara-Issues#815]
## We're getting a lot of duplicate issues.
**Please use GitHub's search function to locate existing tickets and contribute to these instead of opening another one. Most common features which are implemented in other launchers are requested already.**

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 8bitPit** [comment]
You can already access hidden apps easily from Niagara's app search. Hope that helps.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
