### ISSUE TITLE
中文排序

### ISSUE THREAD

**Issue by Doggylin** [8bitPit/Niagara-Issues#816]
## 中文排序问题

* 亲爱的开发者，对于大部分中国用户来说，中文排序是非常有必要的，现在所有的中文应用全部都在 ```#``` 这个分类下，查找应用非常的不方便，望开发这采纳

**Comment by 8bitPit** [comment]
Thanks for reaching me out, you can get more details about it here: #234

**Comment by 8bitPit** [comment]
Duplicate of #234

**Comment by trngish** [comment]
亲爱的开发者，对于大部分中国用户来说，中文排序是非常有必要的，现在所有的中文应用全部都在 # 这个分类下，查找应用非常的不方便，望开发这采纳
