### ISSUE TITLE
Player widget won't work with SONOS

### ISSUE THREAD

**Issue by tinuh99** [8bitPit/Niagara-Issues#817]
The player widget is showed when Music with SONOS is played. But you can't toggle the speaker on or off. When pushed on or off on the widget nothing happens. When pushed the picture on the widget the SONOS app open and you can toggle on or off the speaker with the SONOS app

**Comment by 8bitPit** [comment]
Hi @tinuh99, thanks for the report.
Can you please share a screenshot which shows the button where you would expect the speaker to turn on or off?

**Comment by tinuh99** [comment]
Its the same like spotify. You tab in the middle to stop or play the sound.



Peter <notifications@github.com> schrieb am Do., 4. Apr. 2019, 17:55:

**Comment by tinuh99** [comment]
Here is the picture you asked.

![20190404_182622](https://user-images.githubusercontent.com/49246016/55572856-e1227f00-5708-11e9-9eaf-2a67a30652a8.jpg)

**Comment by 8bitPit** [comment]
It's likely that the SONOS app don't handle transport controls correctly, more info here: https://github.com/8bitPit/Niagara-Issues/issues/485
