### ISSUE TITLE
back behavior with android Q new gesture navigation

### ISSUE THREAD

**Issue by moviti** [8bitPit/Niagara-Issues#818]
## We're getting a lot of duplicate issues.
**Please use GitHub's search function to locate existing tickets and contribute to these instead of opening another one.**

---

**Describe the bug**
back button feature does not work with android Q new gesture navigation

**To Reproduce**
1. in android Q DP2, gesture navigation enabled, any app (exclude home screen) is in active.
2. left swipe home button(pill)
3. nothing happen

**Expected behavior**
back to previous page or upper menu.

**Smartphone (please complete the following information):**
 - Device: [Pixel3]
 - OS: [android Q DP2]
 
**Additional context**
when gesture navigation inactive, back button works as usual.

**Comment by 8bitPit** [comment]
Thanks for the report. Does the back button work correctly in the default launcher?

**Comment by moviti** [comment]
Yes, it works.

**Comment by 8bitPit** [comment]
I'm closing this, because the Android team has announced that gesture navigation is disabled when using a third party launcher on Android Q (for now):
>Custom launchers are another area where we’ve heard feedback and we’re continuing to work on issues, particularly with stability and Recents. Starting in Beta 6, we’ll switch users to 3-button navigation when they are using a custom launcher by default. We’ll address the remaining issues in a post-launch update allowing all users to switch to gestural navigation. 

Source: https://android-developers.googleblog.com/2019/07/android-q-beta-5-update.html
