### ISSUE TITLE
全局化呼出应用列表手势

### ISSUE THREAD

**Issue by yinlixue** [8bitPit/Niagara-Issues#819]
左滑呼出菜单操作全局化，这样就可以在其他应用界面切换应用程序了，而不用返回到主界面

**Comment by yinlixue** [comment]
I am sorry for that ,and I have written it in another request on Github.Thanks for your attention.


发自坚果 Pro

Peter <notifications@github.com> 于 2019年4月4日 下午11:39写道：


Please post your requests in English, I can't understand you otherwise ;(

―

**Comment by 8bitPit** [comment]
No problem :)
