### ISSUE TITLE
Global Outbound App list gestures

### ISSUE THREAD

**Issue by yinlixue** [8bitPit/Niagara-Issues#820]
Make a global gesture by using the left Slide outbound app list operation so that you can switch applications in other app interfaces without returning to the main interface

**Comment by 8bitPit** [comment]
Android has an inbuilt app switcher / recents screen, so I believe creating an additional is unnecessary.

**Comment by yinlixue** [comment]
Yes,I agree with you,we can open the app we have started use the inbuilt app switcher,but we can't if the app was not started.Just a suggestion.🙂


发自坚果 Pro

Peter <notifications@github.com> 于 2019年4月4日 下午11:44写道：


Android has an inbuilt app switcher / recents screen, so I believe creating an additional is unnecessary.

**Comment by 8bitPit** [comment]
I think a separate screen which can be accessed by swiping from anywhere is a bit too much for a minimal launcher. However, there are multiple apps which let you do that, e.g. Edge Action: https://www.xda-developers.com/get-samsung-galaxy-s9-s8-note-8-edge-screen-any-android-phone/

**Comment by yinlixue** [comment]
Yeah, that's really a bit too much for a launcher.And thanks for your advice,I will try it. And Niagara launcher is my favorite launcher among those I have used although it was not perfect (^o^).Thank you for developed and attributed it. :)


发自坚果 Pro

Peter <notifications@github.com> 于 2019年4月5日 上午12:03写道：


I think a separate screen which can be accessed by swiping from anywhere is a bit too much for a minimal launcher. However, there are multiple apps which let you do that, e.g. Edge Action: https://www.xda-developers.com/get-samsung-galaxy-s9-s8-note-8-edge-screen-any-android-phone/

―

**Comment by 8bitPit** [comment]
Thanks a lot :)
