### ISSUE TITLE
Double tap to open search

### ISSUE THREAD

**Issue by sampathbalivada** [8bitPit/Niagara-Issues#822]
A feature which opens search box on double tap on the home screen would be awesome.

**Comment by DennisL94** [comment]
I noticed the Google app doesn't work so can't really search on the fly which is a bit awkward for a launcher like this.

**Comment by 8bitPit** [comment]
@sampathbalivada a double tap gesture is problematic, I explained it here: https://github.com/8bitPit/Niagara-Issues/issues/63. Moreover, you can already enable "press home to search", so I think the feature would maybe be redundant.

**Comment by 8bitPit** [comment]
@DennisL94 What happens exactly if you press the G-Button? Do you have the Google app installed?
