### ISSUE TITLE
Add ability to select new or replace favorite app options.

### ISSUE THREAD

**Issue by DennisL94** [8bitPit/Niagara-Issues#823]
## We're getting a lot of duplicate issues.
**Please use GitHub's search function to locate existing tickets and contribute to these instead of opening another one. Most common features which are implemented in other launchers are requested already.**

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 8bitPit** [comment]
You can add/remove your favorites by long pressing an app.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
