### ISSUE TITLE
Flashing Pocket Casts mini-player

### ISSUE THREAD

**Issue by garyp75** [8bitPit/Niagara-Issues#825]
**Describe the bug**
The Niagara mini-player on the home screen flashes on and off when playing podcasts on Pocket Casts

**To Reproduce**
1. Install Pocket Casts
2. Play podcast
3. View mini player on home

**Expected behavior**
Player doesn't flash on and off

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: [e.g. Android 9 (Pie)]
 
**Additional context**

**Comment by 8bitPit** [comment]
Sorry for the bug. How often does it flash? Moreover, can you please send a screenshot from the original notification showing in the notification shade? It might update every second because it has e.g. a playback time indicator. In that case it won't be easy to solve the flickering.

**Comment by garyp75** [comment]
Screenshot attached.

Doesn't appear that a timer is in the notification but it does flash at
about once per second so wonder if you are onto something.

The flashing also coincides with the play button flickering between play
and pause.

The notification in the shade does not flicker at all.

**Comment by 8bitPit** [comment]
The flicker indicates that the notification has changed and Niagara's media player has been refreshed. Android's notification shade doesn't indicated updates of the notification. However, it's the fault of the media player app. it should not update so often. That's why I'll close this issue.

**Comment by garyp75** [comment]
Thanks Peter, it stopped doing it a month or so ago implying that Pocketcasts fixed their excessive pollling

**Comment by 8bitPit** [comment]
Great to hear @garyp75 and sorry for the very delayed reply 😅
