### ISSUE TITLE
Hide sensitive notification content / privacy settings for homescreen notifications

### ISSUE THREAD

**Issue by rickcardeira** [8bitPit/Niagara-Issues#827]
Feature request on this awesome launcher: 

The ability to hide content on main screen (example: showing only "1 new message" instead of the message content).

**Comment by 8bitPit** [comment]
Thanks for the request, that's a good idea.

**Comment by Montell2099** [comment]
This would be an awesome addition to the homescreen notification system, I would also like to be able to only display the sender or disable it totally and show "_1 new message_".

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
