### ISSUE TITLE
App box 

### ISSUE THREAD

**Issue by prfctvaccum** [8bitPit/Niagara-Issues#828]
I find it very difficult to find the rest of my apps. I understand the concept, but it would be incredible that the other apps could also be seen in a "normal" way. In a "horizontal" way, grouped. Not only vertical.

Thank you!

**Comment by 8bitPit** [comment]
Sorry, but I really think a traditional design would go against Niagaras fundamental ideas: https://github.com/8bitPit/Niagara-Issues/issues/473

**Comment by 8bitPit** [comment]
Duplicate of #473
