### ISSUE TITLE
Hibernating feature for apps.

### ISSUE THREAD

**Issue by killoid** [8bitPit/Niagara-Issues#83]
hello, i viewed the post about this app on xda & decided to try it. it is fantastic & has great minimalistic design. i was previously using kiss launcher & i miss only one feature from that launcher, the ability to hibernate any app (long pressing over apps show that option, of course root is needed). it would be really awesome if you can include that feature in this launcher. thanks in advance!

**Comment by 8bitPit** [comment]
Thanks a lot and also thx for trying it out! Yeah, it could be implemented, it's not that requested though, so maybe in the future.

**Comment by jakcharvat** [comment]
This would be a really nice feature. Also, Samsung has it in their Launcher on Oreo and Nougat, so maybe they offer an SDK for it?

**Comment by 8bitPit** [comment]
Sorry guys, I've decided not to include this feature in Niagara, I want to keep it simple. As @Sacchid suggested, I recommend Greenify as well.
