### ISSUE TITLE
Option to reset all custom app icons

### ISSUE THREAD

**Issue by grantsrosen** [8bitPit/Niagara-Issues#830]
I often set custom icons when an icon pack doesn't have a certain icon themed. As it is now, when I switch icon packs, I have to manually go to every icon I've changed and hit "reset to default". It'd be great to have a feature in Settings to reset all custom icons so that when changing icon packs, you can start fresh. Similar to the setting in Nova.

**Comment by disacrol** [comment]
This makes perfect sense. An 'Apply to user-defined icons' checkbox should appear below the list of icon packs in the icon pack selection popup dialog, unchecked by default, and should be hidden if there are no icons customized by the user. Also, maybe, a confirmation popup should appear if the user checks that checkbox and selects an icon pack.

**Comment by 8bitPit** [comment]
I agree, that would be helpful. I would love to develop it further, imo there should be an icon section where you also can change custom icons more quickly.

**Comment by Montell2099** [comment]
I remember Nova Launcher having an option to reset all custom icons, but also a function to save your current icon selection to a backup-file. This was priceless when you wanted to try out a new set of icons, without having to manually restore every single one if you'd want to revert back to your old icon selection.

Would this be a reasonable function in Niagara as well, together with a function to reset all custom icons, or is it perhaps too much of a niche that only a portion of the users would care for?

**Comment by 8bitPit** [comment]
@Montell2099 I would prefer an auto restore function. For example if you switch from pack A to B, it would reset all custom icons, but if you switch back it would restore them.

**Comment by shmykelsa** [comment]
I agree with @grantsrosen 

I consider this a pretty basic feature for a launcher, and I really think it should be considered for Niagara. Though @8bitPit's view is actually interesting.

So I came up with a crossover:

A.) Changing icon pack scenario
1) Go to settings > Look > Icon pack
2) Select an icon pack
Niagara will change all the icons regardless but:
IF the icon pack was previously chosen and some icons were changed, it will prompt "Do you want to also load custom icons previously set?"
IF yes: then it will load both standard and custom icons
IF no: then it will just load the standard icons

B.) Resetting custom icons scenario:
It will reset all custom icons for the current icon pack

**Comment by 8bitPit** [comment]
Great ideas @shmykelsa! Moreover, Niagara could suggest custom icons for apps "not supported" by the active icon pack  automatically. Niagara could look up other icon packs or suggest a similar icon from the same pack (based on app name, app category, etc.)

**Comment by 8bitPit** [comment]
Custom icons are getting handled a lot better now: https://medium.com/niagara-launcher/the-iconic-update-e37c253f57b

> Select an icon pack
Niagara will change all the icons regardless but:
IF the icon pack was previously chosen and some icons were changed, it will prompt "Do you want to also load custom icons previously set?"

This is exactly what happens now when Icon Assistant is disabled. When Icon Assistant is enabled, Niagara saves and resets your custom icons and restores them when you switch back to the same icon pack. Thanks for your great suggestions, everyone!
