### ISSUE TITLE
Notification v. 0.7.8.a

### ISSUE THREAD

**Issue by M4rku5in** [8bitPit/Niagara-Issues#831]
In the last downloaded version of Google Play 0.7.8.a (10.04.2019), notifications for missed calls and messages stopped working. It does not work even after restarting the phone.

Smartphone (please complete the following information):

Device: [LG G6 ThinQ] 
OS: [android 8.0.0]

**Comment by M4rku5in** [comment]
The new version of Niagara Launcher 0.7.8a3 is fine and the notifications are already working normally.

**Comment by 8bitPit** [comment]
> The new version of Niagara Launcher 0.7.8a3 is fine and the notifications are already working normally
great :)
I'll close the issue for now, but if the problem reoccurs, you can open it again.
