### ISSUE TITLE
Direct access to Play Store from favorites?

### ISSUE THREAD

**Issue by steveharman** [8bitPit/Niagara-Issues#835]
**Is your feature request related to a problem? Please describe.**
Having switched to Niagara from Smart Launcher the one thing, the only thing, I miss is having convenient access to the Play Store without having to search out the Play Store app.

**Describe the solution you'd like**
At the foot of the favorites list we currently have a hardcoded & very useful entry for Settings.  In a similar way could we have a Play Store option beneath settings?  It could be optional in Niagara Settings to enable / disable Play Store.

Its sole purpose would be to act as a shortcut to the Play Store app.  Icon could be a shopping basket perhaps?

Niagara is an excellent product - congratulations and thanks!

**Comment by 8bitPit** [comment]
An alternate option would be showing an option in search to open the Play Store: #145 
What do you think?

**Comment by Martin5001** [comment]
I personally would use both of these suggestions (or let users select in settings).
(But if you really wanted to stick with one of them only, then I would prefer the icon at the foot of the favourites.)

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
