### ISSUE TITLE
Left alphabet menu

### ISSUE THREAD

**Issue by Ciuvn** [8bitPit/Niagara-Issues#836]
I'm New user of Niagara and I think Niagara should have an option for left-hand user which want to navigate with one left hand only ^^

**Comment by 8bitPit** [comment]
Thanks for the report, you can share your thoughts about a left hand mode here: #12

**Comment by 8bitPit** [comment]
Duplicate of #12

**Comment by Ciuvn** [comment]
Thank and I don't even know that left hand also can scroll down with right indication. I think it enough and don't need to have an option to move the indication to the left. Thank 8bitPit!

**Comment by 8bitPit** [comment]
You're welcome, thanks for your response.
