### ISSUE TITLE
Misleading location grant request

### ISSUE THREAD

**Issue by disacrol** [8bitPit/Niagara-Issues#837]
I always have GPS enabled to use weather Niagara widget. But if energy saving is automatically enabled due to low battery, I get a notification on Niagara home screen as if I haven't granted location access for weather to be updated.

Maybe location is disabled on battery saving mode, but maybe Niagara could somehow keep track of the user already granted such permission so it is not asked again.

This does not occur if I manually enable battery saving mode.

Xiaomi Mi A2 (Android One), running Android P.

**Comment by 8bitPit** [comment]
There are two "weather not working" notifications. Which one shows up? The one that asks you for the permission again or the one which asks you to enable gps on your device?

**Comment by 8bitPit** [comment]
@disacrol ;)

**Comment by 8bitPit** [comment]
This won't be fixed anymore, because Google's weather API will be shut down soon:
> This method is deprecated as of August 07, 2019, and will be turned off on January 31, 2020. Google does not offer alternate functionality for the Weather contextual signal. ([source](https://developers.google.com/android/reference/com/google/android/gms/awareness/state/Weather))

However, I'm switching to a paid weather provider that offers much higher quality data and can be used without location services. I hope it's understandable that users have to pay on a regular basis to use this service, because I have to pay the provider monthly or per weather refresh.

**Comment by disacrol** [comment]
@8bitPit I was being notified via an e-mail I very rarely check :) Just changed e-mail settings to make sure I don't miss these updates. And of course, this issue will soon no longer make sense.

**Comment by 8bitPit** [comment]
You can't come with this excuse anymore after #152 gets implemented 😁
Just kidding, thanks for letting me know.
