### ISSUE TITLE
Visual slowdown/lag when using App Drawer after extended periods of phone use

### ISSUE THREAD

**Issue by Chibiwong** [8bitPit/Niagara-Issues#840]
**Describe the bug**
App drawer/alphabet list begins to visually lag after phone/launcher have been running for a while (usually 24+ hours). The bug is "fixed" by resetting launcher, but then it'll come back after another 24 hours of operation or so. Video has been attached to show the visual bug, and also shows it being corrected after Resetting Launcher

**To Reproduce**
1. Use Niagara Launcher
2. Have the phone on for 24 hours+ or more
3. Eventually when you use app drawer, it will show significant visual slowdown when pulling on the app drawer and scrolling through the list

**Smartphone (please complete the following information):**
 - Device: ZTE Axon M Z999
 - Android version: Android 7.1.2

**Screenshots**
Video recording of the issue: https://www.dropbox.com/s/8c3mspxmvi9m7t1/20190418_094249.mp4?dl=0

**Comment by 8bitPit** [comment]
Thanks for the report. I couldn't reproduce the lag, but I'll investigate it.

**Comment by 8bitPit** [comment]
I'm sorry, but neither someone else from the Niagara Telegram community nor me could reproduce it.
