### ISSUE TITLE
Make Niagara work better for bigger screens (tablets)

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#841]
At the moment, seems Niagara hasn't been developed having bigger screens (tablets) in mind > the UI looks and UX feels a bit stretched. Could Niagara have better "true" tablet (aka bigger screens) support in the future?

**Comment by 8bitPit** [comment]
You're right, Niagara is designed to be used on mobile. Do you have suggestions how to improve the layout for tablets?

**Comment by tjsuominen** [comment]
As I'm just an average user, can't name specific uc's, but I'm sure Niagara could do better. Hope that's taken into design table at some point.

**Comment by Freakandr0id** [comment]
![Niagara](https://user-images.githubusercontent.com/50051398/56851015-7ed52c80-690a-11e9-9048-2f69174bc745.png)

As I wrote to you by Mail: For example a way to arrange the favorite apps horizontally (as seen in the picture)

**Comment by tjsuominen** [comment]
I think that there should be proper effort put to the design / UX for larger screens in general IF @8bitPit desides to do so (mean invest proper implementation time into larger screens). But as said, would love to have Niagara to work on bigger screens with better UX / UI than currently.

**Comment by Martin5001** [comment]
Also now when widgets are implemented, clock and widget could be displayed on the left side, while app list would sit on the right side. (Something similar to iPad widgets in latest iOS beta (13?).) This could be another option so user could choose between this two column layout or the one suggested by @Freakandr0id

**Comment by Shaheer0983** [comment]
> Also now when widgets are implemented, clock and widget could be displayed on the left side, while app list would sit on the right side. (Something similar to iPad widgets in latest iOS beta (13?).) This could be another option so user could choose between this two column layout or the one suggested by @Freakandr0id

This idea is great.

**Comment by shmykelsa** [comment]
I personally think Niagara should consider a landscape mode. [This comment](https://github.com/8bitPit/Niagara-Issues/issues/841#issuecomment-487291566) has some potential but I'm thinking of something else.

Favourite section might split up in two with two different case scenarios:

Case 1: No Niagara Widget and no custom widget -> Apps on two columns
Case 2: Niagara Widget and/or custom widget -> Widgets stacked on the left and pinned apps on the right with independent scroll

Also the alphabet should have less vertical padding in this case. In most scenarios landscape would stretch the letters to a point where they are overlapped.

Drawer should be in two columns too. 

When opening a menu from an app, by long press or swipe, the popup should go in the opposite column (in my opinion)

**Comment by 8bitPit** [comment]
Two-column layout and more in tablet optimizations implemented in v.1.4(.1): https://medium.com/niagara-launcher/niagara-unfolded-928606673609
