### ISSUE TITLE
Navigation bar is not transparent

### ISSUE THREAD

**Issue by steffj** [8bitPit/Niagara-Issues#842]
**Describe the bug**
The navigation bar should be transparent. In fact, its background is black.

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G (2015)
 - Android version: Android 5.1

Thank you very much for solving this problem.

**Comment by 8bitPit** [comment]
Hey @steffj unfortunately I couldn't reproduce this. Have you also tried out other third party launchers? Does it also happen there?

**Comment by steffj** [comment]
No, only with Niagara. But obviously it is not a widely spread bug. Thank you and all the best.

________________________________
Von: Peter <notifications@github.com>
Gesendet: Sunday, September 1, 2019 11:04:06 PM
An: 8bitPit/Niagara-Issues <Niagara-Issues@noreply.github.com>
Cc: steffj <s.j@live.at>; Mention <mention@noreply.github.com>
Betreff: Re: [8bitPit/Niagara-Issues] Navigation bar is not transparent (#842)


Hey @steffj<https://github.com/steffj> unfortunately I couldn't reproduce this. Have you also tried out other third party launchers? Does it also happen there?

**Comment by 8bitPit** [comment]
I'm sorry I couldn't reproduce the bug with an Android 5.1 emulator. Since this bug also happens on other third party launchers that are based on Google's launcher code base, I believe this could be a firmware bug.
