### ISSUE TITLE
Top-padding, saving two values, for media player on/off?

### ISSUE THREAD

**Issue by Montell2099** [8bitPit/Niagara-Issues#843]
Would it be possible to save two different values of top-padding, depending on if it was set while the media player was active or inactive?

Would be great to have it save two different values Then these two screenshot scenarios could happen seamlessly — without having to manually adjust it back every time.

I'm using 8 favorites & the last one disappears while the media player is active, unless I change the top-padding from my standard.

Media player inactive
![Screenshot_20190419-173155](https://user-images.githubusercontent.com/43126233/56434261-1ff13100-62d4-11e9-80f7-4c43dbbe15d7.png)

Media player active
![Screenshot_20190419-173134](https://user-images.githubusercontent.com/43126233/56434262-1ff13100-62d4-11e9-8e3c-979902e46356.png)

**Comment by 8bitPit** [comment]
I would prefer an that the padding adjusts itself automatically: https://github.com/8bitPit/Niagara-Issues/issues/243
