### ISSUE TITLE
Duplicated apps visual glitch

### ISSUE THREAD

**Issue by spirosbond** [8bitPit/Niagara-Issues#845]
![Screenshot_2019-04-21-15-18-40](https://user-images.githubusercontent.com/1714848/56470674-471d3f00-6449-11e9-8ef3-f971be5ac360.png)
![Screenshot_2019-04-21-15-18-35](https://user-images.githubusercontent.com/1714848/56470680-4f757a00-6449-11e9-98b6-f7fe9d3c11d5.png)

**Describe the bug**
There is a watermark effect when scrolling

**To Reproduce**
Normal operation.just scroll in the apps menu

**Smartphone (please complete the following information):**
 - Device: LG G6
 - Android version: Android 8.0

**Screenshots**
Attached

**Comment by 8bitPit** [comment]
That's pretty strange, I've never seen that before. Did restarting Niagara / your device help?

**Comment by spirosbond** [comment]
I remember seeing this in the past when I was developing one of my apps with a list view... If I remember correctly it was some king of declaration in the Android Manifest that created this, but I can't remember exactly. Can't find something online either. Do you use some kind of graphics optimization or pro-guard?

Didn't have the problem btw for a while - I guess until the last update.

A reboot fixed it for now. Let's see for how long.

**Comment by 8bitPit** [comment]
Thanks for the advice, I'm using a recycler view and have pro guard enabled. 

> Didn't have the problem btw for a while

So it's nothing new? That makes me wonder even more, because as I mentioned, your the first person to report it. Are you using a custom ROM?

**Comment by 8bitPit** [comment]
Because it seems that this happend only to you, that also might be an issue with your custom rom or firmware. I'm sorry, but I'm afraid I can't fix this.
