### ISSUE TITLE
Weather shortcut is not working with the beta version of the google app

### ISSUE THREAD

**Issue by BjarneRentz** [8bitPit/Niagara-Issues#846]
**Describe the bug**
Just to let you know:
Since the last update of the google app in the beta channel the weather icon and shortcut is not  working. When i exited the beta channel it works again. It´s not realy a bug in the niagara launcher at the moment but maybe it will effect the non beta users in the future aswell.

**To Reproduce**
1. Join the beta channel of the[ google app](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=de&gl=de)
2. Update the google app
3. The Weather icon won´t update and when pressed nothing will happen

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - Android version: Android 9 
- Google app version: 9.72.1.21.arm64
- Niagara version 0.7.8

**Comment by 8bitPit** [comment]
Thanks for the info, I'll check it out

**Comment by Montell2099** [comment]
Thanks for the heads-up, will be leaving the beta until this bug is sorted out.

**Comment by BjarneRentz** [comment]
Yes the weather icon is still there as I noticed today it will update irregularly but it won't open the weather info.

**Comment by 8bitPit** [comment]
I could reproduce the issue and found out Google introduced some bugs related to the weather: https://www.androidpolice.com/2019/04/22/google-weather-applet-breaks-as-new-knowledge-graphs-are-introduced/

**Comment by BjarneRentz** [comment]
Just got another update to version 9.78.3.21 and the weather icon and shortcut are both working again :+1:

**Comment by Rod911** [comment]
Seems fixed, closing
