### ISSUE TITLE
Shortcuts not working on EMUI 9 after disabling Huawei stock launcher 

### ISSUE THREAD

**Issue by edvinnn** [8bitPit/Niagara-Issues#847]
**Describe the bug**
After disabling Huawei's default launcher trough the adb shell I can't get the shortcuts on Niagara to work at all. I have tried rebooting the launcher. 

**To Reproduce**
1. Connect phone to PC. Run `adb shell` to get a terminal to the phone.
2. Then run `pm disable-user --user 0 com.huawei.android.launcher`
3. Try opening a shortcut from Niagara Launcher
4. See error (screenshot)

**Smartphone (please complete the following information):**
 - Device: [Huawei P20]
 - Android version: [Android 9 (EMUI 9.0)]

**Screenshots**
![Screenshot_20190423_113350_bitpit launcher](https://user-images.githubusercontent.com/14109085/56570753-cb8fcf00-65bb-11e9-8e57-3d4e005c5c66.jpg)

**Comment by 8bitPit** [comment]
Thanks for the bug report @edvinnn. Does the same happen on other third party launchers?

**Comment by sauces1313** [comment]
This happens whenever Niagra is not set as Home default in settings also.
I also see the "set niagra as home" in the niagra notification area, which I'd like to request a switch to hide that. I'm using niagra as my primary, but setting pixel launcher as home in settings and using a gesture to launch niagra app.

**Comment by edvinnn** [comment]
Update: I have been struggling with this for weeks, but after installing another third party launcher to try if it worked there (which it did), and after switching back to Niagara it works there as well now.

**Comment by 8bitPit** [comment]
> This happens whenever Niagra is not set as Home default in settings also.

Yeah, Android only allows active launchers to query for shortcuts.

>I also see the "set niagra as home" in the niagra notification area, which I'd like to request a switch to hide that. 

Sorry, Niagara is meant to be the default launcher, partly because of the shortcut issue that would arise otherwise.

**Comment by 8bitPit** [comment]
@edvinnn thanks for letting me know, glad that it's working now. I'll close this issue for now, but will open it again when someone is reporting it again.

**Comment by sauces1313** [comment]
> Yeah, Android only allows active launchers to query for shortcuts.
> 
Understood
> 
> Sorry, Niagara is meant to be the default launcher, partly because of the shortcut issue that would arise otherwise.

Thanks for the head's up. I found a (glitchy) work around to allow the Pixel Launcher style Overview (my original goal) while leaving Niagra as default Home.
