### ISSUE TITLE
Moveable Google search icon

### ISSUE THREAD

**Issue by aureole1599** [8bitPit/Niagara-Issues#848]
Moveable Google search icon. It would be nice to move it due to background appearance and due to touching while scrolling through apps.

**Comment by 8bitPit** [comment]
I'm sorry @aureole1599, I'll have the same concerns about this as I have about https://github.com/8bitPit/Niagara-Issues/issues/850

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
