### ISSUE TITLE
Gradient notification bar

### ISSUE THREAD

**Issue by aureole1599** [8bitPit/Niagara-Issues#849]
I think it would be nice to see a gradient (left being more opaque than right) of the notification bar that surrounds the app you click on within the main home screen. Or maybe no notification bar at all. It does not seem to be an issue with fast loading apps. However, with slower loading apps, the bar isnt very appealing, but would be if there was a gradient effect maybe.

**Comment by 8bitPit** [comment]
>  It does not seem to be an issue with fast loading apps. However, with slower loading apps, the bar isnt very appealing, but would be if there was a gradient effect maybe.

I'm sorry, I'm not certain to what issue you're referring to. Can you please post a screenshot/video showing it?

> Or maybe no notification bar at all.

That's planned: #491

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
