### ISSUE TITLE
Empty space while scrolling to the top of app list.

### ISSUE THREAD

**Issue by killoid** [8bitPit/Niagara-Issues#85]
when i browse the app list & reach the top portion, it has an empty space like ss.
![screenshot_niagara_launcher_20180907-001308](https://user-images.githubusercontent.com/6173607/45180539-8346bb00-b23d-11e8-836f-13c3a4b5c8c4.png)

**Comment by 8bitPit** [comment]
Niagara is optimized for using your phone with just one hand. Without the extra space, it would be hard to reach your apps at the top.
