### ISSUE TITLE
Moveable and sizable icons 

### ISSUE THREAD

**Issue by aureole1599** [8bitPit/Niagara-Issues#850]
I think it would be nice to be able to move the icons to different areas of the screen to make unique setups with wallpapers. This goes for the clock and weather widgets as well. If worried about the scroll bar crossing over the icons, (assuming that's why you constrain them to the left) I think a blurred out effect would be nice to have when opening the scrolling effect.

**Comment by 8bitPit** [comment]
I'm trying my best to align give give icons & labels the right margins, but I'm against layout customization, because Niagara should stay a minimal launcher with a reasonable amount of settings.

**Comment by 8bitPit** [comment]
Closing because it would the additional amount of settings could bloat the launcher.
