### ISSUE TITLE
Search icons by color

### ISSUE THREAD

**Issue by gustavorgsd** [8bitPit/Niagara-Issues#851]
I think it would be cool and easier for some people that instead of having the alphabet search on the right side, having a spectrum of colors that you can choose. When you choose the color a list of icons that have that color on the background will show.

**Comment by 8bitPit** [comment]
In my opinion categorizing by colors is a bit flawed, because a lot of apps have icons with a lot of different colors, e.g. FDroid, Slack and almost every Google app (Google, Maps, Chrome, Play Store, Drive, News, etc.). Those apps could not be categorized well by colors.

**Comment by 8bitPit** [comment]
Closing because it couldn't be implemented well.
