### ISSUE TITLE
Two columns when hiding names on favorites

### ISSUE THREAD

**Issue by ecarl65** [8bitPit/Niagara-Issues#852]
I like that you have a setting to hide the app name of the favorites and only use the icon. It occurs to me that in that scenario there's a lot of wasted space. It would be great to allow two or more columns of icons in that situation. Then I could have more favorites accessible without scrolling. Thanks!

**Comment by 8bitPit** [comment]
Thanks for the request @ecarl65. However, supporting a grid wouldn't be that easy. The whole layout is optimized for lists and it would go against Niagara's fundamentals. More info here: #81
