### ISSUE TITLE
Widget layout suggestion

### ISSUE THREAD

**Issue by saleh2000** [8bitPit/Niagara-Issues#853]
Intelligent, elegant, smooth & simple app. I just suggest to add a small dot (like that one at the bottom of screen which opens niagara settings) at the right top of screen & which could be used to open a thin vertical bar containing the most important wigets & shortcuts like: turn off home screen button... etc. in that way which keeps the simplicity of this app. That would be highly appreciated. Thank you.

**Comment by Rod911** [comment]
Widget support is in the works.
Go to #117 for further discussion.

**Comment by 8bitPit** [comment]
I think such settings would fit great in Android's quick settings. I'm sure the're several apps which let you place some quick tiles there. Niagara will also support shortcuts in the future (#62).  They could be placed in your favorites, app list or by swiping right (#13). Hope that helps.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
