### ISSUE TITLE
Wallpaper glitch

### ISSUE THREAD

**Issue by Exynouz** [8bitPit/Niagara-Issues#854]
When I put a wallpaper on by scrolling down to wallpapers option and choosing a wallpaper from my gallery, it doesn't show properly there is a black part on the left side of the screen.

 - Device: [Samsung GALAXY A5]
 - Android version: [e.g. Android 5.0.2 (Lollipop)]

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/687
