### ISSUE TITLE
Google assistant voice activation

### ISSUE THREAD

**Issue by tiaankruger** [8bitPit/Niagara-Issues#856]
**Describe the bug**
Now, this might not be related, but it did start to happen when I downloaded and started using Niagara launcher.
But I can almost never just say "ok google" and have my phone activate the assistant.
So I cant easily set reminders/alarms/etc.
When I press the google button on the launcher it triggers, but not any other time.
Like I said, maybe it is something else, but it started when I started using Niagara Launcher.
And now persists even after I remove the app.
I REALLY like the launcher and would prefer to use it. but I really use the assistant a lot, and about ready to try factory reset because of this.
Any reports of similar issues?

**To Reproduce**
I don't know how to describe it more than I already did above

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - Android version: Android 9 (Pie)

**Comment by 8bitPit** [comment]
That's weird, I know a couple of people that use Niagara in combination with the Assistant. You're the first to report this issue. I think it doesn't have something to do with Niagara, especially because the issue still persists after removing it. That would be a terrible security flaw from Android otherwise.

**Comment by tiaankruger** [comment]
I removed both Niagara and google apps from my phone, reloaded them, and set it all up again.
I think probably around the time i started using the launcher something went wrong in the google app.
if there is any connection between the bug and the launcher I dont know.
but it is super inconsistent and not really repeatable, so I am just going to close this.

Keep up the work on the awesome laucher!!
