### ISSUE TITLE
Phone completely freezed in the main screen

### ISSUE THREAD

**Issue by yoancrul** [8bitPit/Niagara-Issues#859]
U can't confirm if this is because of the launcher but it's the only beta app i'm currently using, i'm using a S8+ and the hole phone froze, i couldn't turn it off, and since i've been expiriencing a few issues with the launcher lately i'm pretty sure its the launchers fault

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/803
