### ISSUE TITLE
Android Pie Recents

### ISSUE THREAD

**Issue by Topaz8** [8bitPit/Niagara-Issues#86]
Please sir. Do you ever think you'll integrate Android Pie recent + swipe to app drawer functionality here? Thanks.

**Comment by 8bitPit** [comment]
I would like to, however Android doesn't let me. The recents are only supported for first party launchers right now - just for your default homescreen on your phone.

Here is an article about that: https://www.androidcentral.com/android-pie-recents-system-launchers-only

**Comment by Topaz8** [comment]
Oh ... Damn! I understand. Thanks. So even through root it's impossible?
Also. I read an article where developers for the lawnchair app succeeded in doing so..
But anyways thanks. Great work

**Comment by Topaz8** [comment]
Farewell. Thanks very much sir😊. Good luck 😊

**Comment by 8bitPit** [comment]
Ok, the issue will be reopened, because it's technically possible. Due to the enormous time & effort needed, it won’t be implemented soon.

**Comment by Topaz8** [comment]
Sorry, I didn't understand well.
You meant to say it WILL be implemented soon ... Right?

**Comment by 8bitPit** [comment]
@Topaz8 Sorry for the confusion. No, it won't be added soon, because it's so hard to implement.
