### ISSUE TITLE
Open app on horizontal swipe

### ISSUE THREAD

**Issue by BurningcodeValkyrie** [8bitPit/Niagara-Issues#860]
It'll be a nice feature to have a swipe gesture to open an app (example: swipe to rapidly open the camera app). For example you could have the alphabet on the right and swiping from left to right to open the camera; or you could have the alphabet on the left and the swipe from right to left (for all lefties out there)

**Comment by 8bitPit** [comment]
There will be an option to place apps in the app swipe menu, see https://github.com/8bitPit/Niagara-Issues/issues/13. Perhaps, it will open the app directly without opening the menu when it would only contain one entry.

**Comment by 8bitPit** [comment]
If you want to talk further about your idea, please comment here: #13
