### ISSUE TITLE
Option to disable scrolling in left or right side of screen

### ISSUE THREAD

**Issue by Daniel-Brum** [8bitPit/Niagara-Issues#865]
Having an option to disable alphabet scrolling in one of the sides of your screen could be a great idea. I think it would be really useful.

**Comment by mousse04** [comment]
I'm one who would be able to disable the scrolling from one side ;)

**Comment by JonathanBrose** [comment]
I always accidently trigger alphabet scroll on the left side of the app list. I dont even understand why its enabled there when the Alphabet is on the opposit site (right site)
Otherwise really great app

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.

**Comment by Daniel-Brum** [comment]
No problem. Thanks a lot for the attention. Best of luck for you!

**Comment by 8bitPit** [comment]
Thank you Daniel.

**Comment by WMattWood** [comment]
I would be interested in disabling the left side scroll.  15 minutes into using it however, maybe in a few days I will no longer notice it... but intuitively my brain wants the left side to remain stable.

**Comment by bubasruba66-design** [comment]
please, consider giving the users option to choose about the sides :/ just fell in love with the launcher and bought the pro version hoping it will be easy to switch as advertised as 'enabled option to use left side'

**Comment by TheCyberQuake** [comment]
Please add this as an option.
Imo it's not intuitive to have a space without visuals interacting with something on the opposite side of the screen.
I am also very frequently triggering it while trying to use the back navigation gesture.

Gonna be honest, as someone who is paying the subscription for pro:
It's quite obnoxious that y'all said "Feel free to reopen this ticket in 2021 or after", and then every time people come in to open up their own ticket _well after 2021_, y'all keep closing it and referring to this ticket.
