### ISSUE TITLE
SwiftKey issues 

### ISSUE THREAD

**Issue by rawfish61** [8bitPit/Niagara-Issues#866]
**Describe the bug**
Suppresses key pop-ups, multi toggle keys have issues (hard press on the period key to access exclamation point does not work) and cosmetically, all color is suppresses in the keyboard which was set up to make secondary keys visible. Hard to use keyboard now. 

**To Reproduce**
1. SwiftKey was previously installed and set as default keyboard 
2. I installed launcher
3. Started using and immediately noticed the behavior 

**Smartphone (please complete the following information):**
 - Device: pixel 3xl
 - Android version: [current 
![Screenshot_20190508-090718](https://user-images.githubusercontent.com/50410365/57377567-c496be00-7170-11e9-8284-4ae63c61dcc6.png)
]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
