### ISSUE TITLE
Quick Screen Lock

### ISSUE THREAD

**Issue by JohnCale47** [8bitPit/Niagara-Issues#867]
**Is your feature request related to a problem? Please describe.**

As the launcher doesn't have a lock screen option it would be cool if you add a lock screen button at the bottom where the Google button is..

*Describe the solution you'd like**

Maybe replacing the Google button cause for me that button is useless ..

**Comment by 8bitPit** [comment]
Duplicate of https://github.com/8bitPit/Niagara-Issues/issues/63
