### ISSUE TITLE
Please optimize  app to support chinese characters  sorting!

### ISSUE THREAD

**Issue by WuHaoyang000** [8bitPit/Niagara-Issues#868]
Hello, I'm from China, it's  so hard to use the alphabet ! Can you change the Chinese first character  alphabet into English type? Such as change the sort of 相册 into “x”catalog instead of putting it into “相”  catalog. Thanks !
It cause lots of inconvenience when I use it.
For instance,  hard to find needed app!
Sincerely you can optimize it !thanks!
![Screenshot_20190510-101029_Niagara Launcher](https://user-images.githubusercontent.com/37330735/57497832-e24c5a80-730b-11e9-8eec-230be3e3496c.jpg)

**Comment by Rod911** [comment]
Refer #234
