### ISSUE TITLE
Customisable Upper padding inside app drawer like home screen.

### ISSUE THREAD

**Issue by KHarishKrish** [8bitPit/Niagara-Issues#869]
I would like to see the padding adjustment inside the app drawers as in the home screen. To adjust the drawn list to accommodate the widget which will always be visible, and will be like a single screen with a lower app drawer.

**Comment by 8bitPit** [comment]
Thanks for the request @KHarishKrish

**Comment by KHarishKrish** [comment]
Any eta's ?

**Comment by 8bitPit** [comment]
Sorry I can't give you an ETA. It's rather on low priority, currently supporting widget and shortcuts for example is more important. So it may take a while. Sorry.

**Comment by KHarishKrish** [comment]
Thanks for the reply. Will wait. :+1:

**Comment by KHarishKrish** [comment]
Hi,

any updates on custom padding of the full list screen.

**Comment by 8bitPit** [comment]
No, sorry.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2021). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2022 or later.
