### ISSUE TITLE
[Request] Scroll from anywhere of the screen when it's empty

### ISSUE THREAD

**Issue by veyselerden** [8bitPit/Niagara-Issues#870]
I have nothing on my main screen (intentionally) but still i am not able to scroll anywhere of my screen. If I want to open app list I must use the right side.

This is my screen:
![Screenshot_20190512-050807](https://user-images.githubusercontent.com/12845347/57576911-5d308500-7474-11e9-9692-cfb7f0e5ced3.png)

Being able to scroll from anywhere under the clock would be awesome.

**Comment by 8bitPit** [comment]
Hi @veyselerden. In my opinion opening the scrollbar from anywhere could lead to accidentally going to the app list. Furthermore I've planned to support live wallpaper background taps (more on that here: #709).

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
