### ISSUE TITLE
The uninstall option when the pop up after a long press is barely showing

### ISSUE THREAD

**Issue by NecrobyNerton** [8bitPit/Niagara-Issues#871]
Ok so when i try to uninstall an app by long pressing it and well the uninstall option at the bottom when i scroll is barely showing, i have picture of it.

I am using a samsung galaxy s7
Android 8.0
![Screenshot_20190512-061100_Niagara Launcher](https://user-images.githubusercontent.com/50537146/57577769-7a6a5100-747e-11e9-959e-1b82eedb39e7.jpg)

Edit: Yes i have scrolled all the way to the bottom and thats how much it shows, it is kinda annoying...

Edit2: Well i kinda figured it out why it does that... i think it is a scaling issue since well i usually use the wqhd resolution (2k res) ànd well when i tried the fhd (1080p res) it showed a bit more and the hd (720p res) is showing just fine...

**Comment by 8bitPit** [comment]
Thanks for the report and for the mentioning the resolution change, I'll try to reproduce the bug.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
