### ISSUE TITLE
Missing icon on floating action button

### ISSUE THREAD

**Issue by Azhagubalan** [8bitPit/Niagara-Issues#874]
Pls see the screenshots both search and Google search buttons looks ugly in latest Niagara alpha 080 version. I even restarted Launcher, phone but nothing worked. Pls fix this issue ..
My Phone runs on Android 5.0.2 ZenUI

In Home screen Google looks like this
![Screenshot_2019-05-17-11-25-57](https://user-images.githubusercontent.com/50730036/57906420-8a779b80-7897-11e9-9e78-a92cbca04ba8.jpg)

In App list Search is looking like this
![Screenshot_2019-05-17-11-25-31](https://user-images.githubusercontent.com/50730036/57906497-d4f91800-7897-11e9-929a-11f5c4fbd2d8.jpg)

**Comment by Azhagubalan** [comment]
@Maxr1998 @8bitPit I hope you saw this bug :)) I haven't got reply because you replying to every thread but ignored my issue

**Comment by 8bitPit** [comment]
Sorry for having not replied @Azhagubalan. I'll try to fix it.

**Comment by Rod911** [comment]
Fixed
