### ISSUE TITLE
Separator for frequenty used apps

### ISSUE THREAD

**Issue by venugopaljd** [8bitPit/Niagara-Issues#875]
**Is your feature request related to a problem? Please describe.**
There is no separator for frequently used apps which gets recommended and displayed on the home screen.  The first time the frequently used apps are displayed there is a text separator. Clicking of the text separator, removes it and the app list is shown as a single list with the frequently used apps listed at the bottom. Normally I add the most important app at the bottom so that i can open it with single handed operation. but if the frequently used apps are listed below one handed operation may become a bit difficult

**Describe the solution you'd like**
Please provide a persistent separator so that the frequently used apps are below this separator, this way we have separation between the favorites added by us and suggestions by the launcher Alternatively kindly provide a button(similar to the google search button) which will display the frequently used apps list

**Comment by 8bitPit** [comment]
Thanks for the well explained request. There is already an open issue about showing a divider: #318 ((I've changed the title of the issue, because I think it wasn't as descriptive as yours)). Would you mind posting your ideas there?
