### ISSUE TITLE
Idea for Niagara launcher

### ISSUE THREAD

**Issue by berdzena** [8bitPit/Niagara-Issues#876]
Idea for Niagara launcher. In my opinion it would be great 
https://photos.app.goo.gl/312qf9LgUvzoHLGM7

**Comment by Martin5001** [comment]
It looks cool. But you would have to tap more times to open category, scroll, tap again to finally open the app/contact you want. So I personally wouldnt prefer that.

**Comment by 8bitPit** [comment]
Thanks for the cool mockup @berdzena! Folders or categories will definitely be supported, however probably not in the same way you might have thought, but also not to different ;) 

Check out: https://github.com/8bitPit/Niagara-Issues/issues/13. You can discover several different ideas for folders here and repost your own video there if you want. I've expressed my thoughts on folders there as well.
