### ISSUE TITLE
Option to center widgets

### ISSUE THREAD

**Issue by gmpgaurav** [8bitPit/Niagara-Issues#877]
If possible please provide an option that enables the clock widget on the home screen to be placed centrally.

**Comment by 8bitPit** [comment]
There will be free different alignment modes for widgets:
![image](https://user-images.githubusercontent.com/9284845/57967525-7c418200-7960-11e9-82b6-6f61ecb183cf.png)

**Comment by 8bitPit** [comment]
Implemented in v.0.8
