### ISSUE TITLE
Change stock font to Pixel Launcher font

### ISSUE THREAD

**Issue by theplasticbling** [8bitPit/Niagara-Issues#878]
I can tell that the developers are going for a stock looking and feeling launcher. The font ruins it for me. Being able to use the same font that the stock Android launcher uses (Pixel Launcher) would make things look better.

**Comment by 8bitPit** [comment]
I can't use the font [due to legal reasons](https://fonts.google.com/license/productsans). However, I could add a font picker, where you can provide a font for the launcher. See: https://github.com/8bitPit/Niagara-Issues/issues/191
