### ISSUE TITLE
Sort by Usage - Volatility Adjustment

### ISSUE THREAD

**Issue by IdmFoundInHim** [8bitPit/Niagara-Issues#879]
I like that the launcher sorts apps by usage and can automatically suggest favorites. As an extra feature, could there be a setting to adjust how volatile the sorting/suggesting is (i.e., to set how many previous days of usage stats are considered by the launcher)?

**Comment by 8bitPit** [comment]
In my opinion adding such an option is a bit too much for a simple and minimal launcher. However, changing how many suggestions pop up on the homescreen could come in handy for more people, so  would like to add a slider for that: https://github.com/8bitPit/Niagara-Issues/issues/454

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
