### ISSUE TITLE
Add rubberband overscroll effect

### ISSUE THREAD

**Issue by blurryfaze** [8bitPit/Niagara-Issues#880]
It would be nice if you add a flow/smooth scrolling effect in favourites/home screen ...when the scrolling gets at the end it would be great if you add a bouncing effect like one in the pixel launcher all apps reach the end ...i think you got the point what I'm tryin to say...

**Comment by 8bitPit** [comment]
Thanks for the request, I thought about that as well.

**Comment by andys8** [comment]
Is implemented now, right?

**Comment by 8bitPit** [comment]
Oy, yeah, thanks @andys8 :)
