### ISSUE TITLE
Suggestions to improve the launcher 

### ISSUE THREAD

**Issue by praveenchandranpk** [8bitPit/Niagara-Issues#882]
1. Since the launcher already uses left and right gestures my suggestion is to provide a left swipe on the google button to access camera and a back button gesture to open some other app or notification toggle.

2. The current widget solution is nice. I think it would be much better if we can swipe that top area to left and right to add more widgets.

3. Search integration with sesame. Since it's a minimal launcher it's a must have in my opinion. 

4. Inbuilt widgets would be nice. For battery, events, etc. All minimal.

5. Ability to add shortcuts.

6. A snooze button for notifications would be awesome.

7. Show all the apps which has unread notifications right under the favourite apps and above the most used apps.

**Comment by praveenchandranpk** [comment]
1. Since the launcher already uses left and right gestures my suggestion is to provide a left swipe on the google button to access camera and a back button gesture to open some other app or notification toggle.

2. The current widget solution is nice. I think it would be much better if we can swipe that top area to left and right to add more widgets.

3.

**Comment by 8bitPit** [comment]
> Since the launcher already uses left and right gestures my suggestion is to provide a left swipe on the google button to access camera and a back button gesture to open some other app or notification toggle.

You might be able to choose which app opens when tapping on the button. Furthermore, the swipe gesture might be also customizable.

> The current widget solution is nice. I think it would be much better if we can swipe that top area to left and right to add more widgets.

You can access more widgets in the future by placing them in the app swipe menu. I think adding both implementations would be a bit too much. (More info here: #117)

>Search integration with sesame. Since it's a minimal launcher it's a must have in my opinion.

Planned: #88 

> Inbuilt widgets would be nice. For battery, events, etc. All minimal.

See: #55, #100 & #159 

Ability to add shortcuts.

> #62

A snooze button for notifications would be awesome.

> Yup. Could you please open a separate issue for that?

Show all the apps which has unread notifications right under the favourite apps and above the most used apps.

> #152
