### ISSUE TITLE
Apps invisible while scrolling in app list

### ISSUE THREAD

**Issue by khamdany43** [8bitPit/Niagara-Issues#883]
**Describe the bug**
In app drawer, all app not show except the scroll letter app.
**To Reproduce**
Just scroll up little faster

**Smartphone (please complete the following information):**
 - Device: [wiko harry]
 - Android version: [Android 7.0.0 (nougat)]

**Screenshots**
![5_6273550959947-1558357412237](https://user-images.githubusercontent.com/32181799/58023670-92a33580-7b3a-11e9-80b0-636d1133a897.gif)

**Comment by 8bitPit** [comment]
Thanks for the report. I could reproduce it and hope I can fix it soon.

**Comment by 8bitPit** [comment]
Should be fixed in v.0.8.0 alpha 5.
