### ISSUE TITLE
Homepage Notification Alert

### ISSUE THREAD

**Issue by bgirly49** [8bitPit/Niagara-Issues#884]
Please forgive me if this has been addressed..
I only see non favorite app notifications if I am scrolling through entire list and I happen to see one. Is there a way for a generic notification alert to show  on home page to let me know somewhere in my app list there is a notification ?

**Comment by 8bitPit** [comment]
Are you looking for something like this: https://github.com/8bitPit/Niagara-Issues/issues/152?

**Comment by bgirly49** [comment]
To keep it simple and clean,  perhaps the star on top on alphabet app list
could change color. I have an LG G6 that has no led notifications, so I
downloaded an app called No LED that basically adds a customized colored
dot to screen when screen is timed out to indicate a missed call etc..
On side note...I love what you are creating with this launcher and
understand that adding too many features defeats the purpose.

.

**Comment by 8bitPit** [comment]
Thanks for the kind response @bgirly49. In my opinion the notifications should show up on the homescreen directly (but only important ones, like those from messengers). If they only show up on the app list, you might access them faster by just swiping down and opening Androids notification shade.

**Comment by bgirly49** [comment]
That is true. May I ask if the "add a website bookmark or shortcut"  has
been implemented?
I am learning how to navigate through your discussion site and it looks
like some have features like widgets or shortcuts that I dont have...or
maybe I am not reading it correctly.

**Comment by 8bitPit** [comment]
You're right. Shortcuts, including web shortcuts don't work on Niagara, but it's planned to support them: #62
