### ISSUE TITLE
Swipe on dialer or messaging icon on favourites

### ISSUE THREAD

**Issue by syedasad1213** [8bitPit/Niagara-Issues#885]
Problem:- 
                  I have a habit of keeping dialer and messaging app on my favourites tray...so when we swipe to right on that icon it generally shows notifications.

Solution:-
                   When we swipe right in the dialer or messaging app it should show contacts which should be customisable and on clickng the contact the call should be engaged or if it's a messaging app it should Directly take to type a message there.......

   Swipe on dialer app➡️select your favourite contacts(should appear) and after setting that .
Swipe on dialer app➡️tap on the contact ➡️ calling....
 And the same with messaging app

**Comment by 8bitPit** [comment]
I agree, that would be need. Once Sesame has been integrated into Niagara, that will be possible (#88). In the distant future, it might be even possible without the help of Sesame: #336.
