### ISSUE TITLE
A snooze button for notifications.

### ISSUE THREAD

**Issue by praveenchandranpk** [8bitPit/Niagara-Issues#886]
In the latest versions of android there's a snooze option for notifications. It would be awesome if that can be added to this launcher.

**Comment by 8bitPit** [comment]
That could come in handy. I noticed that the [option is missing on Android Q](https://9to5google.com/2019/05/08/android-q-beta-3-notifications-priority-snoozing/), so let's see first what the Android team will do with the feature.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
