### ISSUE TITLE
Messenger Lite is not showing up in the list or hidden files.

### ISSUE THREAD

**Issue by Nayoshi12** [8bitPit/Niagara-Issues#889]
I am not really sure what is happening with the app, but i have facebook messenger lite it is not showing up.

**Comment by Rod911** [comment]
- Have you installed it on the SD card?
- Does it show up in other launchers?
- Have you renamed the app?

Try reinstalling the app and tell me if it still doesn't show up.

**Comment by Nayoshi12** [comment]
I'm sorry false alarm, the app was named lite for some reason. 

Sorry for the inconvenience.

**Comment by Rod911** [comment]
Happy to help.
