### ISSUE TITLE
Ending a call goes to home screen

### ISSUE THREAD

**Issue by pronojitsaha** [8bitPit/Niagara-Issues#892]
**Describe the bug**
After ending a call (made from dialer or any other app) the launcher goes back to home screen. This has been happening since last week, earlier ending the call would go back to the app from which call was initiated. 

**To Reproduce**
Open dialer, then make a call. Then end the call and you are taken to the home screen of the launcher instead of the dialer. 

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - Android version: Android 9. 0.13(Pie)

**Comment by 8bitPit** [comment]
Thanks for the report. Can you reproduce the issue on Lawnchair, Nova or on any other third-party launcher?

**Comment by pronojitsaha** [comment]
The issue went away when i removed the Phone app from Favorites. Right now
its showing in the most recent app and doesnt have the issue.


-
Regards,
Pronojit Saha

**Comment by 8bitPit** [comment]
Thanks for coming back to me. I couldn't figure out what causes the issue, but I'm glad that it's working again on your device.
