### ISSUE TITLE
Aspecto de Lanzador

### ISSUE THREAD

**Issue by MarcosAlcaraz** [8bitPit/Niagara-Issues#897]
We contacted you to make a great improvement for your Microsoft Launcher software.

People like their software with their tools and improvements, there is no problem in that aspect, the improvement that appeals to a growing audience is the aesthetics of the Niagara Launcher, clean, simple and with the essential tools at hand. 
(https://play.google.com/store/apps/details?id=bitpit.launcher).
To quickly access the aforementioned Launcher.

We would love for you to add minimalism as an additional mode of your Launcher.

Personal note:

I'm Marcos, I currently use Niagara Launcher for its minimalism and important accesses such as the Clock, calendar, weather and of course the search engine, I can also anchor favorite applications such as Instant Messaging and Camera.

For some time I have thought about using your Launcher only that I personally do not like the classic application grid, I really like the Bing search engine, the news section and also the Microsoft tools, all at hand, but I would like much that added the aesthetics of Niagara Launcher, I know colleagues who think the same, we are fanboys of Microsoft and its software in general but this aspect is what bothers us at times.

Thank you very much, please implement the Recommendation.

Thank you very much for your attention.
Very good day!

Translated by Google translator
Traducido por Google Traductor

Les contactamos para hacerle una gran mejora para su software Microsoft Launcher.

Le agrada a las personas su software con sus herramientas y mejoras, no hay problema en ese aspecto, la mejora que le agrada a un público creciente es la estética del Niagara Launcher, limpio, sencillo y con las herramientas esenciales a la mano. 
(https://play.google.com/store/apps/details?id=bitpit.launcher).
Para que accedan rápidamente al Launcher mencionado.

Nos encantaría que añadieran el minimalismo como modo adicional de su Launcher.

Nota personal: 

Soy Marcos, actualmente uso Niagara Launcher por su minimalismo y accesos importantes como el Reloj, calendario, clima y por su puesto el buscador, adicionalmente puedo anclar aplicaciones favoritas como la Mensajería Instantánea y la Cámara.

Desde hace tiempo he pensado en usar su Launcher solo que personalmente no es de mi agrado la clásica reja de aplicaciones, me agrada mucho el buscador de Bing, la sección de noticias y además las herramientas de Microsoft, todo a la mano, pero me agradaría mucho que añadieran adicionalmente la estética de Niagara Launcher, conozco colegas que opinan lo mismo, somos fanboys de Microsoft y su software en general pero este aspecto es lo que nos molesta en momentos.

Le agradezco mucho que porfavor implementen la Recomendación.

Muchas Gracias por su Atención.
¡Muy buen día!

**Comment by 8bitPit** [comment]
I'm so sorry for only replying now @MarcosAlcaraz. Other search engines will be supported in the future: https://github.com/8bitPit/Niagara-Issues/issues/142. However, there will be no dedicated news section  integrated into Niagara Launcher, at least it's not planned for now. Here's why I decided against a feed section for Niagara Launcher (e.g. the Google Feed):

> I thought about integrating Google Now and I decided not to implement it for now for the following reasons:
- The swipe right gesture to open it wouldn’t fit for Niagara
- Google doesn’t want other apps to use it, so you would have to make or take use of a second apk which is not very user friendly
- The feed could have a negative impact to the app’s performance
- It would cost a time to develop & test it (that applies to a lot of features, but should be kept in mind anyway)
- The Google app has the same feed build in their Google app. Just adding the G-button to your homescreen and tapping it when you want to browse the feed is a much simpler and imo, more elegant solution. [[Source](https://github.com/8bitPit/Niagara-Issues/issues/3)]

**Comment by 8bitPit** [comment]
Hope this helps :)
