### ISSUE TITLE
Letters not visible in launcher search bar

### ISSUE THREAD

**Issue by Azhagubalan** [8bitPit/Niagara-Issues#898]
@8bitPit , @Maxr1998 , Pls see the search bar and keyboard(top) in the screenshot. I wrote some letters in launcher search bar but letters are not visible. Pls fix this issue
Launcher version - 080 alpha4
My phone - Asus Zenfone 2 laser
Android version - Lollipop 5.02, ZenUI

![Screenshot_2019-06-04-21-04-58](https://user-images.githubusercontent.com/50730036/58893195-4399fa80-870d-11e9-855d-944b457b6e48.jpg)

**Comment by Rod911** [comment]
Using any themes?

**Comment by Azhagubalan** [comment]
No, nothing, my phone Android version doesn't support.

**Comment by Azhagubalan** [comment]
@Maxr1998 , @8bitPit , pls see the screenshot letters not visible in reply bar as well. I got notification 
![Screenshot_2019-06-04-21-18-57](https://user-images.githubusercontent.com/50730036/58894543-d2a81200-870f-11e9-94ec-fb67e341461a.jpg)
 from retro music telegram group ... But showing telegram x in the reply instead of showing group name retro music.. I restarted my phone, restarted launcher .. nothing fixed. Pls fix these issues.

**Comment by Azhagubalan** [comment]
Pls click the link https://github.com/8bitPit/Niagara-Issues/issues/874#issue-445278642 

The issues in the above link is fixed now  in launcher version 080aplha4

**Comment by 8bitPit** [comment]
Thx for the report @Azhagubalan

**Comment by Azhagubalan** [comment]
Now this issue is fixed in Launcher Version 0.9.1. Everything fine now. No issues in Android 5 :))

**Comment by Rod911** [comment]
Thanks for the report, closing issue.

**Comment by 8bitPit** [comment]
@Azhagubalan awesome. Thanks for closing the issue @Rod911
