### ISSUE TITLE
Add option to autoselect app in search with only one result

### ISSUE THREAD

**Issue by bhajneet** [8bitPit/Niagara-Issues#899]
**Is your feature request related to a problem? Please describe.**
It can be difficult to reach for a single result when searching. It can be faster to autoselect the single result of a search.

**Describe the solution you'd like**
There is an app on f-droid called [Search Based Launcher](https://f-droid.org/packages/com.vackosar.searchbasedlauncher/) for "When the results narrow down to one app, it can be automaticaly started (Autostart button)."

For users that have set home button to "search", they would be able to double tap home button from any app and swipe a single word to open a different app. E.g. user is in an app and wants to look up directions, they tap home to open launcher, they tap home again to open search, they swipe the word "maps", and since it's the only result in their app list "Google Maps" automatically opens.

**Comment by Rod911** [comment]
Pressing 🔎 on Keyboard to open first app has been implemented (#114)
