### ISSUE TITLE
Notifications section

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#9]
Having a section in the scrolling drawer that would show all the apps that the user has a notification from would be a feature that would make it easy to go through all the notifications and it would set this launcher even further apart from the others. I personally prefer going through notifications in the launcher to going through them in the notification shade, as I find going through the notifications in the shade cluttered and chaotic. 

Hope I haven't made too much of a mess from that paragraph. 😂

**Comment by 8bitPit** [comment]
Great idea! In my opinion it’s still too similar to the notification shade. However, I planned related feature for folders: Swipe right a folder to see all app notifications. So, for example you can read all your Twitter, Instagram, etc. messages when opening the social notification section.

**Comment by jakcharvat** [comment]
Let's keep all further discussions here @8bitPit, so we don't clog up telegram as well: 

I know it's similar, but I prefer the layout of Niagara notifications, hence why I suggested it. If you have time, I'd love it if it made its way in. If it doesn't, no problem 😉

**Comment by 8bitPit** [comment]
I'll think about that, maybe it will be implemented in the future

**Comment by 8bitPit** [comment]
Merged with #152
