### ISSUE TITLE
Android 9 Quickly switch between apps

### ISSUE THREAD

**Issue by Yashigeshi** [8bitPit/Niagara-Issues#902]
**Describe the bug**
Quickly switch between apps gesture on Pixel 3 XL with Android 9 sometimes doesn't switch back to the last used app but some random one. 

The gesture is "Quickly switch between apps" on this page:
https://9to5google.com/2018/08/06/how-to-use-android-9-gesture-navigation/

**To Reproduce**
1. Swipe the home (pill) button to right
4. It should switch to last used app, but occasionally (50% of time?), it switches to random app. I can't figure out when it does and doesn't.

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - Android version: Android 9 (Pie)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Sorry for the issues. Unfortunately, a third party launcher cannot take control over the gestural system. More info can be found in the comments of this post: https://www.reddit.com/r/NiagaraLauncher/comments/bva1mg/third_party_launcher_devs_need_to_implement/
