### ISSUE TITLE
Large empty space 

### ISSUE THREAD

**Issue by TheCombatBeard** [8bitPit/Niagara-Issues#903]
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by TheCombatBeard** [comment]
When you go to Niagara Settings > Features > Advanced > Time & Date, and turn off the 3 options, it leaves a large empty space at the top of the home screen. I think this is because you wanted the launcher to be used by one hand, but aesthetically, it looks terrible.

In this situation, can we move up the favorites list so that it starts when there top of the clock would've been? Holding my phone now, my thumb wouldn't have been any farther away from that location.

**Comment by Rod911** [comment]
Assuming you have the latest build, you press and hold the blank area on top of the favorites which will give you a slider. You can drag this slider to adjust how much gap you want between the first app and the top of your screen. 
Follow Niagara News on Telegram: https://t.me/niagara_news

More info in #112
