### ISSUE TITLE
Google Asistant and Request

### ISSUE THREAD

**Issue by cemozbey** [8bitPit/Niagara-Issues#904]
I think this launcher perfect . I hope you will win great success. Maybe font be more visible because on my wallpaper I have no clear view . Maybe alphabet can be portable . Maybe you can add application folder. My opinion is that. And Google Asistant doesn't work with "OK Google" command plase check that .

**Comment by 8bitPit** [comment]
Thanks for your kind feedback, I linked you a few related issues. Hope that helps :)
> Maybe font be more visible because on my wallpaper I have no clear view .

https://github.com/8bitPit/Niagara-Issues/issues/705

> Maybe you can add application folder.

https://github.com/8bitPit/Niagara-Issues/issues/13

> And Google Asistant doesn't work with "OK Google" command

#186
