### ISSUE TITLE
Add tactile feedback to alphabet

### ISSUE THREAD

**Issue by amminadabz** [8bitPit/Niagara-Issues#906]
But let it be disabled in settings. Some tactile motors are crap and it would be annoying on those phones, but I have a Pixel 3 and I can say from my experience with the home button multitasking slider that a little "tic" makes any kind of incremental slider feel way more responsive.

**Comment by Rod911** [comment]
Decided not implement this feature for reasons discussed in #200.
I'll close this here. Further discussion in linked issue.
