### ISSUE TITLE
Add animation to quick Google search

### ISSUE THREAD

**Issue by amminadabz** [8bitPit/Niagara-Issues#908]
When the user swipes up on the Google button to do a quick search, a little animation would make it seem more responsive. I feel weird swiping on a button that doesn't move.

**Comment by 8bitPit** [comment]
Yeah, that would definitely feel more polished. Someone else feels the same #360

**Comment by Martin5001** [comment]
Just an idea: The button could be attached to a spring so it could be draggable just slightly in the up direction, and when the button is released it would pull it back.

**Comment by 8bitPit** [comment]
@Martin5001 Yeah, I would choose a springy animation. And yes, you're right. This issue is not about the same as #360 is, I'll reopen it.
