### ISSUE TITLE
Continuous scrolling within page by using alphabet slider

### ISSUE THREAD

**Issue by Yashigeshi** [8bitPit/Niagara-Issues#910]
Current: Sliding on alphabet slider jumps to the beginning of alphabet page (a, b, c). If one alphabet page contains many apps (say 30+ apps in "a") and they don't fit to screen, you then have to swipe the app list to find apps towards the bottom of the page. You have to use 2 different scrolling methods in your "find an app to open" journey.

Request: Sliding on alphabet slider seamlessly scrolls across apps, not just beginning of alphabet pages. Use relative touch position on X axis to control scrolling speed (right=faster scroll for moving to page to page quickly, left=slower scroll to search a particular app within a page). That way, you can integrate two scrolling mothods ( page scroll and app scroll ) into one single method (alphabet slider).

**Comment by Rod911** [comment]
Please refer #162 and leave suggestions in linked issue.
