### ISSUE TITLE
Allow rearranging of Time/Date/Android Widget

### ISSUE THREAD

**Issue by Jeffrey04** [8bitPit/Niagara-Issues#912]
Having widget support is great, but it would be better if we can somewhat re-arrange the time, date and widget. I would like to have my Widget placed on top, followed by some vertical space, before time and date.

**Comment by 8bitPit** [comment]
Thanks for the feature request @Jeffrey04. I might add an option, but I hope you understand that this has low priority. The priority also depends on how many people would like swap the Clock with the widget. I think most widgets fit well below the clock, I'm sure you found a widget where it's not the case. Can you please tell me which widget you'd like to have at the top?

**Comment by Jeffrey04** [comment]
The official "at a glance" widget actually. The current implementation of the widget makes the layout looking horrible with date and time enabled. So I was thinking it would be nice if I could put the widget on top, followed by a bit of vertical space, before showing the time and date, followed by the shortcuts.

**Comment by 8bitPit** [comment]
@Jeffrey04 Niagara Launcher will also get its own at a glance widget at some point: https://github.com/8bitPit/Niagara-Issues/issues/55

**Comment by 8bitPit** [comment]
Update: Swapping the date with a custom widget may be possible in the future: https://github.com/8bitPit/Niagara-Issues/issues/1355
Oh and by the way, Niagara Launcher now offers its own at a glance widget 😃 https://medium.com/niagara-launcher/second-anniversary-update-of-niagara-launcher-d4a07345fbaa

**Comment by 8bitPit** [comment]
Merged with #1355
