### ISSUE TITLE
*bug*

### ISSUE THREAD

**Issue by lucalg74** [8bitPit/Niagara-Issues#916]
**Describe the bug**
installed the app. I follow the wizard but when i say OK to use Niagara as default home it opens SETTINGS with other otions possible
**To Reproduce**
1. install
2. give authorization
3. click OK on USE NIAGARA AS HOME 
4. No error, but no way to go on

**Smartphone (please complete the following information):**
 - Huawei P20 lite
 - Android version: 9
**Screenshots**

**Comment by Rod911** [comment]
Related issue : #777

**Comment by 8bitPit** [comment]
It should lead you to a list where you can choose your default apps, like your home apps, but Huawei is sometimes a bit special ^^. I'd suggest to navigate to the setting manually by going to Settings > Apps > Default Apps > Home app.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
