### ISSUE TITLE
Change background based on Dark theme

### ISSUE THREAD

**Issue by avi12** [8bitPit/Niagara-Issues#917]
Basically, let the user choose a certain background for when dark mode is disabled, and another background for when dark mode is enabled
I suggest determining if dark mode is enabled by the system setting, and not via the time of day

**Comment by 8bitPit** [comment]
You're idea sounds inspired by [iOS 13](http://www.iphonehacks.com/2019/06/ios-13-ipados-hands-on-dark-mode.html) ;) Hope you can understand that this request only has a low priority, because it's a minor cosmetic change and Live Wallpaper apps could also implement that.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
