### ISSUE TITLE
Messages notification not clearing

### ISSUE THREAD

**Issue by kliwete** [8bitPit/Niagara-Issues#918]
**Describe the bug**
I use the Messages app by Google and have it as a favorite. The notification that appears next to the app icon does not clear properly.

**To Reproduce**
1. Receive multiple text notifications
2. Look on home screen and see that you have "2 new messages" displayed next to app icon
3. Dismiss only one of the notifications, but keep the other active
4. Look on home screen and see the it still says "2 new messages" next to app icon

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s8
 - Android version: Android 9 (Pie)

**Screenshots**
![20190620_224304](https://user-images.githubusercontent.com/52061090/59898309-6b47be80-93ad-11e9-86dc-5550a59329c4.jpg)
![20190620_224237](https://user-images.githubusercontent.com/52061090/59898323-7b5f9e00-93ad-11e9-8e2f-3d071b9051d8.jpg)

**Comment by 8bitPit** [comment]
Thanks for the detailed report! Does that happen on a regular basis? Moreover, does that only happen with the app *Messages*?

**Comment by kliwete** [comment]
Hey, sorry about the late reply, I've been on vacation visiting family. Messages is the only app I've noticed it in. I also have Textra on my phone and when I switched to that as my default messaging app it only shows the first message, but will show the next one when I dismiss the earlier message.
I don't know how to add a screen shot in a comment, so I'll try to be detailed.
For example: I receive a text at 6:31 and that notification will be displayed on the home screen. I then receive another one at 6:40. The display on the home screen doesn't change. It only shows the first message received at 6:31. I then dismiss the notification for the 6:31 message and now the home screen will display the 6:40 message.
When I change to the stock Samsung Messages app it will only display that I have a notification and how long ago the most recent one was received, but none of the details of the notification. Like who it's from or the contents of the message.

**Comment by 8bitPit** [comment]
No problem, hope your vacation was great. 
Because Android's notification system is quite complex, I can't say if those bugs are caused by the messenger, Niagara or by the system. I'll keep an eye on it and try to reproduce it.

PS: you can attach images to a comment by just pasting it in (at least on desktop).

**Comment by almabook** [comment]
hey you can fin many reference on google
[https://stackoverflow.com/questions/2665634/how-to-clear-a-notification-in-android](url)
[https://developer.android.com/reference/android/app/Notification](url)
[https://medium.com/@krossovochkin/android-notifications-overview-and-pitfalls-517d1118ec83](url)
[https://github.com/invertase/react-native-firebase/issues/948](url)

**Comment by 8bitPit** [comment]
Thanks @almabook but I believe the issue is caused by something else.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device (v0.34.1)? If so, feel free to open the ticket again.
