### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by markdunhill73** [8bitPit/Niagara-Issues#919]
Could you make it so that we can choose to have the back button on the right hand side of the screen and not just the left, thanks

**Comment by Rod911** [comment]
Which back button are you talking about?

**Comment by markdunhill73** [comment]
Just the software one alongside the home button (pill) on the phone screen

**Comment by Rod911** [comment]
The buttons on your navigation bar (I'm assuming this is what you're referring to) are set up by your phone's operating system and is not part of any launcher. If you can't find the settings for it in your phone then there's not much that can be done about it.

**Comment by 8bitPit** [comment]
You could change the layout to "right-to-left" but I think that would come with to many side effects XD
