### ISSUE TITLE
Different apps if you slide down the right side vs left side of screen?

### ISSUE THREAD

**Issue by zohebrehman** [8bitPit/Niagara-Issues#92]
Kinda like folders but dragging down the left side of the screen will show one set of apps (kind of like a folder) and dragging down the right side will show another set of apps

**Comment by jakcharvat** [comment]
IMHO it wouldn't work well with the one handed usage principle, but I'll leave the issue floating around as it definitely is an interesting idea.

**Comment by 8bitPit** [comment]
It's a bit confusing for non advanced users.
