### ISSUE TITLE
gmail homescreen notifications do not work (Huawei)

### ISSUE THREAD

**Issue by annie-may** [8bitPit/Niagara-Issues#920]
Problem: 

First of all, I do love this app. It is wonderful in so many ways. An issue for me is that gmail notifications do not show on the homescreen on my Huawei mate 20 lite. (I have a Samsung tablet too, where I use the launcher, and the gmail notifications work fine there.)

I have checked that notifications are enabled (they are) - it seems that the gmail app itself sends notifications (for example, lock screen and banners on the android system), but the gmail notifications do not show on the app list homescreen. 

**To Reproduce**
(Not sure how to complete this section.)

**Smartphone (please complete the following information):**
 - Device: Huawei mate 20 lite, model SNe-LX1
 - Android version: Android 8.1.0

Hope this is enough to go on, thanks.

**Comment by 8bitPit** [comment]
Hey, thanks for the report and thanks for the kind words :)
While I can't say you the exact cause, I suggest to check a couple of settings:
- Please make sure that Notification **dots** are enabled. Both in the global notification settings and in the system settings for gmail. I posted a few screenshots of them here: #481
- Niagara also filters some notifications, like ads or ongoing notifications, but not mails. They would still show up in the app swipe dialog though; swipe on Gmail to the right to open it.
- If the above doesn't help, you can also check if Niagara has access to the notification. Go to Niagara's app search and type in */notifications*. All visible notifications that can be used by Niagara should show up in the dialog. If the Gmail notification shows up, you can tap on *share* to send the notification data to me for further investigation - but please make sure to remove any personal information.

Please let me know if that helps.

**Comment by annie-may** [comment]
I am so sorry but I am not as technically minded as many people here I think. I have no idea what 'Niagara's app search' is. Thanks,

**Comment by 8bitPit** [comment]
No problem, I'm happy to help ;)
Navigate to Niagara's all apps list and press on the search-button on the bottom right to open it.

**Comment by annie-may** [comment]
Thank you so much Peter. 

I sent myself a test message and then searched notifications. I got the below. 

NB. I have Outlook too and the notifications show on it -  that notification was present at the time. 

All personal info. redacted. Hopefully this helps. 

Disclaimer: This log might include personal information.
Device: SNE-LX1
Manufacturer: HUAWEI
Android version: 27
No. of visible notifications: 4
com.google.android.gm - [redacted]
prio: 0
has low priority: false
cat: email
text: gmail
android.title: [redacted]
android.reduced.images: true
android.subText: [redacted]
android.template: android.app.Notification$BigTextStyle
android.showChronometer: false
android.text: gmail
android.progress: 0
android.progressMax: 0
specialType: 
android.appInfo: ApplicationInfo{c2f9f78 com.google.android.gm}
android.showWhen: true
android.people: [Ljava.lang.String;@1ada651
android.largeIcon: android.graphics.Bitmap@342aeb6
android.bigText: gmail

[redacted]

android.infoText: null
android.wearable.EXTENSIONS: Bundle[mParcelledData.dataSize=1484]
android.progressIndeterminate: false
android.remoteInputHistory: null
gameDndOn: false
auto_cancel
group_summary
show: false
filter: true
imp. expl.: You must set the importance of these notifications.
importance: 4
low importance: false

com.google.android.gm - [redacted]
prio: 0
has low priority: false
cat: email
text: gmail
android.title: [redacted]
android.reduced.images: true
android.subText: [redacted]
android.template: android.app.Notification$BigTextStyle
android.showChronometer: false
android.text: gmail
android.progress: 0
android.progressMax: 0
specialType: 
android.appInfo: ApplicationInfo{b6407b7 com.google.android.gm}
android.showWhen: true
android.people: [Ljava.lang.String;@27b3b24
android.largeIcon: android.graphics.Bitmap@c55568d
android.bigText: gmail

[redacted]
android.infoText: null
android.wearable.EXTENSIONS: Bundle[mParcelledData.dataSize=1484]
android.progressIndeterminate: false
android.remoteInputHistory: null
gameDndOn: false
auto_cancel
show: false
filter: true
imp. expl.: You must set the importance of these notifications.
importance: 4
low importance: false

com.microsoft.office.outlook - [redacted] 
prio: 0
has low priority: false
cat: email
text: [redacted]
android.title: [redacted]
android.reduced.images: true
android.subText: [redacted]
android.template: android.app.Notification$BigTextStyle
android.showChronometer: false
android.text: [redacted]
android.progress: 0
android.progressMax: 0
specialType: 
android.appInfo: ApplicationInfo{ec30042 com.microsoft.office.outlook}
android.showWhen: true
android.largeIcon: null
android.bigText: Re: gmail
checking. From: [redacted]
android.infoText: null
android.progressIndeterminate: false
android.remoteInputHistory: null
gameDndOn: false
android.title.big: [redacted]
show_lights
only_alert_once
auto_cancel
local_only
group_summary
show: true
filter: true
imp. expl.: You must set the importance of these notifications.
importance: 3
low importance: false

com.microsoft.office.outlook - [redacted]
prio: 0
has low priority: false
cat: email
text: Re: gmail
android.title: [redacted]
android.reduced.images: true
android.subText: [redacted]
android.template: android.app.Notification$BigTextStyle
android.showChronometer: false
android.text: Re: gmail
android.progress: 0
android.progressMax: 0
specialType: 
android.appInfo: ApplicationInfo{8276853 com.microsoft.office.outlook}
android.showWhen: true
android.largeIcon: null
android.bigText: Re: gmail
[redacted]
android.infoText: null
android.progressIndeterminate: false
android.remoteInputHistory: null
gameDndOn: false
android.title.big: [redacted]
show_lights
only_alert_once
auto_cancel
local_only
show: true
filter: true
imp. expl.: You must set the importance of these notifications.
importance: 3
low importance: false

**Comment by 8bitPit** [comment]
Thanks a lot for the log Annie. It seems that notification dots are disabled for Gmail notifications (because the log reads *show: false* beneath Gmail notifications. Android has a separate toggle to show notifications also in the launcher. To change that, long press on the Gmail app in Niagara, then tap in the *i*. After that, go to *Notifications* and search for a switch called *Allow notification dots* or something similar:
![image](https://user-images.githubusercontent.com/9284845/59979872-e39cc280-95ed-11e9-9387-5743a136c978.png)

**Comment by annie-may** [comment]
Thank you Peter. I cannot find a 'dot' option anywhere on my phone but I can see notifications are enabled (notification badges etc.). Perhaps it is a Huawei issue? 

thanks.

**Comment by 8bitPit** [comment]
Hmm... Yeah *notification badges* should be the same as *notification dots*. If you enabled it for Gmail,  it should work, I don't know what is causing the notification not to show up. Gmail could also disable notifications to show in the launcher, but I doubt that they make turn that off for newly received emails.

**Comment by annie-may** [comment]
How odd. Not to worry. Thank you for all of your help, Peter. I will continue to use the app but it suits me very well otherwise.

**Comment by annie-may** [comment]
Hi again Peter,

I wanted to send an update because I happened upon the solution to this issue, completely by accident. It turns out that I had _notification badge_ enabled but I did not have the _notification dot_ enabled. 

The how to: 

In the gmail app, go to _Settings_
then _General settings_
then _Manage notifications_
then, under your email address (see screenshot) below, long press _Email_
![Screenshot_20190801-064225](https://user-images.githubusercontent.com/52123301/62269056-cdbec080-b429-11e9-9487-93bad239592d.jpg)

and then select _Show notification dot_ (see second screenshot)
![Screenshot_20190801-064442](https://user-images.githubusercontent.com/52123301/62269074-dadbaf80-b429-11e9-8f49-c4c7ebc087b9.jpg)

The notifications for the Gmail app then work perfectly on the Niagara homescreen. You can select which notifications you receive (important only, all. etc.) under individual account settings. 

These settings are for the phone and OS below but they may be quite universal: 
Device: Huawei mate 20 lite, model SNe-LX1
Android version: Android 8.1.0

Hope that is helpful. Thanks Peter.

**Comment by 8bitPit** [comment]
That's great to hear! I didn't know you can control notification dots on an per-notification-category-level on Huawei (That's a bit too much control imo 😄). Thanks for the update @annie-may 😃

**Comment by 8bitPit** [comment]
Oh - I noticed that this is in fact a feature coming directly from Android 😅.

**Comment by annie-may** [comment]
HA! We don't want too much control! ;) 

And don't ask me - I discovered it by accident so it's already well above my reading level! 

No worries Peter. Thanks for all your help.
