### ISSUE TITLE
Exclude Niagara from Digital Wellbeing on Android 9.0+

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#921]
(This is different issue than #893 )
Would it be possible to set Niagara not to show in Digital Wellbeing statistics?
It makes it inaccurate and seems not to give much sense to have a launcher listed in this statistics.

**Comment by 8bitPit** [comment]
Sorry, Android doesn't provide an option to exclude certain apps, this is unfortunately not possible.
