### ISSUE TITLE
App search on Main screen

### ISSUE THREAD

**Issue by kasik96** [8bitPit/Niagara-Issues#923]
It would be nice if I cloud replace "Google Search" button on the main screen with "App Search" button. I don't really have use for Google Search, but App Search would really help me a lot. Thanks.

**Comment by Rod911** [comment]
You can press home to search if you enable it in settings > features > Advanced.

**Comment by 8bitPit** [comment]
@kasik96 thanks for the request. On top of that what @Rod911 suggested, it might be even possible to remap the button to other actions in the future, I added your request to https://github.com/8bitPit/Niagara-Issues/issues/175.

**Comment by 8bitPit** [comment]
Merged with #175
