### ISSUE TITLE
New App Alert

### ISSUE THREAD

**Issue by DevIyer** [8bitPit/Niagara-Issues#925]
When I install a new app, I want the launcher to highlight it on the alphabetically sorted list. 

For example, if the app is Netflix, I would fancy a colored dot next to N or like N to be emboldened. Just thinking out loud here.  Having said that, kudos to you for this wonderful launcher. It's fluid and intuitive. Cheers!

**Comment by 8bitPit** [comment]
Thanks for the request and for your kind words @DevIyer. My plan is to show recently installed apps in the search screen when you haven't typed in anything yet. Similar to a notification dot, a small indicator would also appear next to the search icon. What are your thoughts on this? Btw, here's a link to an open issue about this: https://github.com/8bitPit/Niagara-Issues/issues/227
