### ISSUE TITLE
Swipe right to open recent apps

### ISSUE THREAD

**Issue by drey4211** [8bitPit/Niagara-Issues#926]
I love this launcher. Going back and forth from iOS to Android, I love to see my recent apps. If this can be integrated that would be great.

Also if I get an email or notification, the app on the homescreen showing the notification until I clear it would be awesome!

**Comment by 8bitPit** [comment]
Thanks @drey4211, I think those two requests are similar to yours: https://github.com/8bitPit/Niagara-Issues/issues/756, https://github.com/8bitPit/Niagara-Issues/issues/152
Hope that helps.

**Comment by drey4211** [comment]
Thanks! I didn't realize that was still an option! I got rid of my nav bar
on my OnePlus and didn't pull hard enough I guess when I tried it.


On Jul 4, 2019 at 03:50, <Peter <notifications@github.com>> wrote:

Thanks @drey4211 <https://github.com/drey4211>, I think those two requests
are similar to yours: #756
<https://github.com/8bitPit/Niagara-Issues/issues/756>, #152
<https://github.com/8bitPit/Niagara-Issues/issues/152>
Hope that helps.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/8bitPit/Niagara-Issues/issues/926?email_source=notifications&email_token=AMPWH73DJLUK7UBHU4JMQCTP5WTSRA5CNFSM4H5S2CRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZGT7UA#issuecomment-508379088>,
or mute the thread
