### ISSUE TITLE
When will Niagara be out of beta? 

### ISSUE THREAD

**Issue by codesharkasm** [8bitPit/Niagara-Issues#927]
**Describe the bug**
My org won't let me install unreleased apps... can you give an ETA on the 1.0 play store release? 
**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by Rod911** [comment]
It will be available when it's ready, please do not ask for ETAs. I'd recommend not installing unreleased apps on a company device.

**Comment by codesharkasm** [comment]
Ok that's fine. No offense meant. 👍

Keep up the good work.

**Comment by 8bitPit** [comment]
Thanks @codesharkasm for your interes :) I hope I can release Niagara by this year.
