### ISSUE TITLE
Work/Android Enterprise/Island apps not present

### ISSUE THREAD

**Issue by jeffre** [8bitPit/Niagara-Issues#93]
Typically, apps installed under Android Enterprise will appear alongside other apps in a launcher, except they have a small briefcase icon in the lower right corner. 

More about Android Enterprise: https://www.android.com/enterprise/employees/

To experiment with Android Enterprise features without the hassle check out Island:
https://play.google.com/store/apps/details?id=com.oasisfeng.island

**Comment by 8bitPit** [comment]
Thanks for your tips and links! I hope I can support them someday.

**Comment by 8bitPit** [comment]
fixed in version 0.5.0
