### ISSUE TITLE
Music artwork as background in home screen

### ISSUE THREAD

**Issue by sergiorgiraldo** [8bitPit/Niagara-Issues#931]
When I am using spotify, artwork can be retrieved from the music.

Lets have it in the home screen, Niagara shows the artwork as the background while it is playing.
 
When the music stops, it returns to the original wallpaper

**Comment by 8bitPit** [comment]
Hey, I'm sorry to tell that this feature might not be implemented for the reasons described in https://github.com/8bitPit/Niagara-Issues/issues/31. However, feel free to reply in the linked issue. It might be implemented if many people are interested.
