### ISSUE TITLE
Add shortcut to Android file manager

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#933]
Could you add shortcut to Android built in file manager the same way as described in #835 for the Play store (probably file manager should be listed on top not bottom however)? Now I have to go to storage settings to open the file manager, which is not really comfortable.
(This is definitely possible to do because Android allows creating settings shortcuts (#422).)

**Comment by 8bitPit** [comment]
Hi. As soon as shortcuts will be supported, you'll be able to place it in your app list. Would that solve your problem?

**Comment by Martin5001** [comment]
It would work, however I would prefer the same visual approach as #835 for same reasons (file manager and Play store are both more system features than usual apps, so I think it should be separated from them.)

**Comment by 8bitPit** [comment]
Right, but I think some people would get confused why the files app doesn't appear in their app list, but below. Of course a switch to toggle the behavior could be added, but I'm trying as much as possible to minimize the amount of settings, so Niagara stays simple.

**Comment by Martin5001** [comment]
@8bitPit I understand this. The problem is that built in Android file manager (not Google Files app) is not listed as app so the shortcut can be only in Niagara favourites, not all apps. But I would prefer to not list in favourites, but still have quick access.

**Comment by 8bitPit** [comment]
Ah okay. However, Niagara will handle shortcuts a little different from other Launchers. They will also show up in the app list 😉

**Comment by 8bitPit** [comment]
Merged with #62
