### ISSUE TITLE
Ability to add other live wallpapers as background

### ISSUE THREAD

**Issue by tjsuominen** [8bitPit/Niagara-Issues#934]
**Describe the solution you'd like**
Ability to add / change wallpaper to other than existing live wallpapers (e.g. Pixel live wallpapers through Google wall).

**Comment by 8bitPit** [comment]
Hey @tjsuominen, I think the Wallpaper app from Google lets you change your wallpaper to any image on your phone. Furthermore, Niagara offers a couple of selected wallpapers (accessible from Niagara's settings). Did I misinterpret your question?

**Comment by tjsuominen** [comment]
Sorry @8bitPit - I had misunderstood this part as users are able to utilize 3rd party Wallpaper apps. Close this as not valid.

**Comment by 8bitPit** [comment]
@tjsuominen no problem 😉

**Comment by 8bitPit** [comment]
Thanks @Rod911 for closing the issue btw
