### ISSUE TITLE
Option to make icon bigger

### ISSUE THREAD

**Issue by HubKing** [8bitPit/Niagara-Issues#935]
The current "Larger" is not large enough. In fact, the "Smallest" and "larger do not seem that much different (probably not even twice larger?).  Please allow us to set a bigger size.

**Comment by 8bitPit** [comment]
Thanks for the request, I added it to https://github.com/8bitPit/Niagara-Issues/issues/452

**Comment by 8bitPit** [comment]
Merged with #452
