### ISSUE TITLE
App context menu is missing.

### ISSUE THREAD

**Issue by HubKing** [8bitPit/Niagara-Issues#936]
Currently, long-pressing an icon shows Niagara's own menu. If it is possible, add app's launcher context menu items below Niagara's own menu items. If that is technically not possible, please add a way to invoke app's context menu, such as a three-lime menu icon to the right of app's label.

**Comment by 8bitPit** [comment]
I'm sorry, which context menu do you mean?

**Comment by HubKing** [comment]
This one. https://developer.android.com/guide/topics/ui/shortcuts
It is a standard feature that the stock launcher and many other popular third-party launchers support.

**Comment by 8bitPit** [comment]
Oh, gotcha. You can open shortcuts by swiping right. In my opinion separating shortcuts & app options is cleaner and the swipe gesture can be executed more quickly.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
