### ISSUE TITLE
Rounded edges option on the music player image

### ISSUE THREAD

**Issue by Stefano-Martinelli** [8bitPit/Niagara-Issues#938]
I would really like and option that roundes up the angles of the image in the on screen music player (for example the album image of Spotify)
![Screenshot_20190722-001831](https://user-images.githubusercontent.com/53155959/61597995-8c533780-ac17-11e9-952c-24a6759b0451.png)

**Comment by Rod911** [comment]
https://github.com/8bitPit/Niagara-Issues/issues/18#issuecomment-426212018
> Spotify also recommends not to change the artwork’s shape:
> ![image](https://user-images.githubusercontent.com/9284845/46341135-bb240100-c637-11e8-9756-485a193da415.png)
