### ISSUE TITLE
horizontal favorite apps list

### ISSUE THREAD

**Issue by Francais04** [8bitPit/Niagara-Issues#940]
It would be very cool , if developers add an option in which you will be able to turn vertical favorite apps list to horizontal, like dock bar.
Thanks, your user ))

**Comment by 8bitPit** [comment]
Hey @Francais04, I'm sorry but I guess that design isn't suited for Niagara. The whole has to be rebuilt, things like notifications or the swipe menu wouldn't work in horizontal mode.

**Comment by 8bitPit** [comment]
Duplicate of #155
