### ISSUE TITLE
Edit mode: Favourites rearrangement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#941]
**Describe the bug**
I can drag the icon up to the top of the screen, while it's probably supposed to stop on top of the list (where description text is located)

**To Reproduce**
1. Go to Edit mode
2. Drag app to the top of the screen

**Comment by Rod911** [comment]
I don't believe this is an issue as the icons snap back in place when you release them.

**Comment by Martin5001** [comment]
You´re probably right. It´s more just a small visual enhancement.

**Comment by 8bitPit** [comment]
That's the default implementation of Android. I think draggable items in other apps behave the same. Furthermore, it isn't that simple to change this. For example, the bounds that determine to which position you can drag the app around would change constantly while dragging and scrolling (at the same time). Moreover, an animation has to be added when the drag limit has been reached. All in all, I wouldn't say it's worth the effort 😉
