### ISSUE TITLE
Edit mode: Saving changes enhancement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#942]
**Is your feature request related to a problem? Please describe.**
Currently there are two buttons (checkmark in the bottom and back button on top) with the same action.

**Describe the solution you'd like**
I think it would be better to use back button to discard changes and the checkmark button to apply them.

**Comment by 8bitPit** [comment]
Thanks for the reuquest @Martin5001. In my opinion a "discard changes" option isn't really needed, because you can't overwrite that much anyways. I thought it would be simpler for the user not to have two different options.

**Comment by Martin5001** [comment]
@8bitPit I agree. As you say "I thought it would be simpler for the user not to have two different options." then maybe it would be better to remove the backward arrow and keep only the checkmark button. So there would be only one button.

**Comment by 8bitPit** [comment]
The back arrow is shown for consistency. But I plan on tweaking the navigation system, anyways (e.g. with #668). Maybe, I'll remove the button in some screens.

**Comment by 8bitPit** [comment]
I'll close this issue, but let #668 open.
