### ISSUE TITLE
Swipe Gestures follow my hand

### ISSUE THREAD

**Issue by nkm0476** [8bitPit/Niagara-Issues#944]
**Is your feature request related to a problem? Please describe.**
Okay. I recently in love with Apple's UI design. So i thought maybe it can be used in Niagara Launcher! 

**Describe the solution you'd like**
So when you swipe the app, there's some quick options inside. What I want is swipe page follows my finger. Not one-swipe sudden open.

**Comment by 8bitPit** [comment]
Would be neat, agreed. However, I hope you can understand that other features on the roadmap have higher priority than this 😉

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
