### ISSUE TITLE
Clock clipping off the top of the screen

### ISSUE THREAD

**Issue by CalebKeatts** [8bitPit/Niagara-Issues#946]
After the latest update suddenly the clock clips off the top of the screen.
**To Reproduce**
1. Go to the home screen
**Smartphone**
 - Device: Moto e4 plus (Owens)
 - Android version: android 7.1.2 
Note I have a lineage os ROM installed 

**Screenshots**
![Screenshot_20190729-144637](https://user-images.githubusercontent.com/53448155/62075652-a1c9f200-b213-11e9-8698-7feffa76735e.png)

**Comment by Rod911** [comment]
Hey thanks for the report. 
Can you tell me which version of Niagara you are using? 
Seems that you may have used edit mode to shift the app list upward.

**Comment by CalebKeatts** [comment]
I am using version 0.8.0

**Comment by Rod911** [comment]
Try these steps :
- Open edit mode.
- Select "move whole list"
- Drag the upper slider down till you feel the clock in the right place.

Reply here if it didn't work for you.

**Comment by CalebKeatts** [comment]
Thank you that worked.

**Comment by Rod911** [comment]
Glad I could help
