### ISSUE TITLE
Dual messenger apps don't work,

### ISSUE THREAD

**Issue by veedhoor** [8bitPit/Niagara-Issues#95]
Dual messenger crashes when launched.

**Comment by jakcharvat** [comment]
This does not seem like an issue related to the launcher. Have you tried opening the app with a different launcher? What phone do you use, and what version of Android is it running?

**Comment by veedhoor** [comment]
Yes, dual messenger works fine on different launchers. I am using Samsung Note 8 with Android Oreo i.e. 8.

**Comment by BluDragyn** [comment]
Can confirm. Is an issue with Niagara. Dual Messenger apps do not show up for me in Niagara, and when switching back to them, they crash. Both work in Nova, Rootless Pixel Launcher, and Samsung Experience Launcher on my Galaxy S9 Plus

**Comment by 8bitPit** [comment]
They should work now (with version 0.5.0)
