### ISSUE TITLE
Widgets don't initialize on start

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#952]
>There is a bug in the latest stable version (0.8.0). When I turn off my phone and turn it back on, some widgets, such as Google's quick look, disappear and display a white box. If I restart the launcher, it doesn't work either. 

(source: @Jemorax, Niagara discussion group on Telegram)

**Comment by cauerego** [comment]
if it's the same bug that happens to me at random (just tried rebooting and turning it off, no such issue here), then the work around is replacing the Google at glance by itself.

**Comment by 8bitPit** [comment]
@cauerego have you already tried the latest build (v.0.9.10)? The bug shouldn't occur there anymore.

**Comment by 8bitPit** [comment]
Fixed in v.0.9.11

**Comment by Rod911** [comment]
Users reported this issue as on v0.30

**Comment by 8bitPit** [comment]
(Hopefully) fixed in v0.31. Hard to say to be honest.
