### ISSUE TITLE
Upcoming events next to the icon

### ISSUE THREAD

**Issue by augsemaugse** [8bitPit/Niagara-Issues#954]
Great launcher. Thanks for all the work. 

Would it be possible to show the upcoming events as a notification next to the calendar icon like it's done for other apps like Telegram, WhatsApp, mail or so?

**Comment by Martin5001** [comment]
#932 could be another option.

**Comment by 8bitPit** [comment]
Thanks for the kind words @augsemaugse. As Martin pointed out, this feature has already been requested: #932 / #53

**Comment by 8bitPit** [comment]
Duplicate of #55
