### ISSUE TITLE
Widget space

### ISSUE THREAD

**Issue by uhnmake** [8bitPit/Niagara-Issues#956]
Today, i've updated the app and used the new widget option and i noticed the lack of space/bad position of the text on it. 

1. Go to 'Config' 
2. Click on 'Functions'
3. Click on 'Select Widget'
4. Select the Deezer widget (in my case)

 - Device: Sony Xperia XA1
 - Android version: Android 8.0.0 (Oreo)

Screenshots:
![Screenshot_20190808-202122](https://user-images.githubusercontent.com/53921478/62744337-90a39100-ba1c-11e9-8388-e89f933589a1.png)

**Comment by Rod911** [comment]
Try:
- Press and hold on the widget.
- Select resize from the options
- Drag the sliders to adjust the position and height of your widget.

**Comment by 8bitPit** [comment]
@uhnmake did that help?

**Comment by uhnmake** [comment]
Yes! It did, thank you!

**Comment by Rod911** [comment]
Great. Closing.
