### ISSUE TITLE
On app widget list back button shouldn't go to home

### ISSUE THREAD

**Issue by kklorenzotesta** [8bitPit/Niagara-Issues#957]
On the add/replace widget menu when an app have more than one widget a click on it shows the list of widgets for that app. When pressing the back button I should go back to the main widget list instead of the main home, it is really annoying when I want to see which are the widgets that I can try.

**Comment by 8bitPit** [comment]
Yes, agreed. This will be fixed: #668. I'll add your comment to this issue.

**Comment by 8bitPit** [comment]
Merged with #668
