### ISSUE TITLE
Android9

### ISSUE THREAD

**Issue by chenleiPNG** [8bitPit/Niagara-Issues#959]
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by chenleiPNG** [comment]
嗯

**Comment by chenleiPNG** [comment]
咯

**Comment by 8bitPit** [comment]
Hey @chenleiPNG, I'm sorry, but I couldn't figure out what the bug is you wanted to submit.
