### ISSUE TITLE
Material design - enhancement

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#960]
The white box shown when I long press an app or swipe seems to me like it has too much radius on the corners. All the other elements in Android or other apps use sharper rounded corners so I think this should be adjusted to better fit material design for consistency.

**Comment by 8bitPit** [comment]
Yes, the default corner radius is smaller (4dp vs.  16dp). However, tweaking the shapes used for cards & dialogs, etc. make the app feel more unique, the Material design team [wrote an interesting article](https://material.io/design/shape/about-shape.html#) about Shapes in the Material Design specs. In my opinion the UI also feels a bit more modern with larger rounded corners, I really like them. 

Btw, In [one of their design studies](https://material.io/design/material-studies/owl.html#shape) they're also using a corner radius of 16dp :P

**Comment by 8bitPit** [comment]
I'm closing this, but this is issue is still open for discussion.
