### ISSUE TITLE
Widgets are blank

### ISSUE THREAD

**Issue by flamendless** [8bitPit/Niagara-Issues#962]
Widgets are blank. Tested on Huawei GR5 2017

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 8bitPit** [comment]
Thanks for the report. Which widgets have you tried out? Is every one of them blank?

**Comment by 8bitPit** [comment]
I think this is a duplicate of: https://github.com/8bitPit/Niagara-Issues/issues/952

**Comment by flamendless** [comment]
@8bitPit yes, all widgets are blank

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 8bitPit** [comment]
Thanks for the reply @flamendless. I'll close this issue but keep #952 open.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device?
