### ISSUE TITLE
Provide an option to remove the search button in the app list

### ISSUE THREAD

**Issue by jibin1313** [8bitPit/Niagara-Issues#964]
It's very annoying when you are going through your app list and you accidently click the **search button** at the bottom. It's really frustrating.

> `Note`: This is **not** the Google search button at the bottom of the home screen.

Please provide an option to remove this search button in the apps list. We can already opt to remove Google search button at bottom of the home screen. Please add a similar option in the Niagara settings.

**Comment by 8bitPit** [comment]
Hey @jibin1313, sorry for the delayed response. For the sake of simplicity I would not like to add another toggle, see #808 for more info.
