### ISSUE TITLE
App close animation / transition 

### ISSUE THREAD

**Issue by eXplicitWisher** [8bitPit/Niagara-Issues#965]
Right now app close animation is not appealing. Please make it great.

**Comment by Rod911** [comment]
I don't believe currently android allows third party apps to change app closing animations.
Only way you may be able to this might be using custom ROMs. [For eg](https://forum.xda-developers.com/android/software/mod-ios-11-animation-t3630402)

Animations to home screen after the app is closed may be possible.

**Comment by Martin5001** [comment]
I am not sure what exactly is meant by the original post but I would like to point out that maybe the animation which needs to be tweaked a little bit is the one shown when going from Niagara settings back to the home screen. This should look the same way as other apps on close, thus roll out to bottom not fade out.

**Comment by eXplicitWisher** [comment]
"Some X app to homescreen" transition is what I meant.
CPL launcher is able to do that now. Check it out and you'll get the idea.

**Comment by 8bitPit** [comment]
@eXplicitWisher can you please share a video of the close animation?

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
