### ISSUE TITLE
work profil notification

### ISSUE THREAD

**Issue by pyxos8** [8bitPit/Niagara-Issues#966]
It should not be possible to see the content of a notification of an app that is in the work profil (ex: email content)

my phone is a galaxy s8+ (android 9)

**Comment by 8bitPit** [comment]
I recommend disabling "notification dots" for those apps, notifications won't appear on the homescreen afterwards. Here's an example how you can disable notifications from Google Keep: Settings > Apps > Keep Notes > Notifications > Allow notification dot:
![image](https://user-images.githubusercontent.com/9284845/63447727-cbee8880-c43c-11e9-8f76-4b384975ec9f.png)

**Comment by pyxos8** [comment]
It is not about notification dots, but really the content, here in my settings I have disabled the option to show notification content, but in my launcher, I'm still able to see it.

![image1](https://user-images.githubusercontent.com/46497673/63449997-15c07a00-c40f-11e9-87cc-0d1460fa49d1.jpg)
![image2](https://user-images.githubusercontent.com/46497673/63450003-1822d400-c40f-11e9-86de-ac8f5101dee2.jpg)

**Comment by 8bitPit** [comment]
I think the option you disabled only applies to the lockscreen, not your homescreen. You should still be able to also notifications in Androids notification shade, so I think also showing them in Niagara would make no difference. However, you could disable notifications altogether for your work profile apps.
