### ISSUE TITLE
about the location of the app list in the screen

### ISSUE THREAD

**Issue by ZYLHL** [8bitPit/Niagara-Issues#967]
**Is your feature request related to a problem? Please describe.**
Sometimes, I use phone by left hand, and sometimes right hand.but I can only slide alphabet by the right hand. IT'S A LITTLE INCONVENIENCE!

**Describe the solution you'd like**
Put the list in the center of the whole screen, you can both slide alphabet on the right and left.

**Comment by Rod911** [comment]
You can scroll the app list on both the sides

**Comment by 8bitPit** [comment]
https://twitter.com/NiagaraLauncher/status/1128699719629275136 :)

**Comment by 8bitPit** [comment]
A dedicated left hand is also planend: #12
