### ISSUE TITLE
12

### ISSUE THREAD

**Issue by nhatthanh1144** [8bitPit/Niagara-Issues#968]
**Describe the bug**

**To Reproduce**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential Phone]
 - Android version: [e.g. Android 9 (Pie)]

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Closing because you posted just the default feature request template.
