### ISSUE TITLE
Add tictictic sound when we scroll through the alphabet

### ISSUE THREAD

**Issue by sunboyzz** [8bitPit/Niagara-Issues#969]
It would be great if you could enable the scroll sound when we drag through the alphabet. Also provision to disable it if user doesn't want it to. 

Reference soumd.: Apple iPhone has a sound when we scroll over the time picker in alarm screen or time setup screen. Exactly that sound would match this.

**Comment by NoveTheGreat** [comment]
I wholly support this idea
Just, a really soft tictictictictictictic sound as you're scrolling through the alphabet

**Comment by 8bitPit** [comment]
Thanks for the idea, I'll try this out.

**Comment by MarcAlx** [comment]
Maybe a soft vibration to bring a kind of haptic feedback on each letter change.

**Comment by 8bitPit** [comment]
@MarcAlx see: #200

**Comment by Methotrex8** [comment]
I'm not a fan of sound or other feedback when scrolling, but I think this is a GREAT IDEA. I won't personally use the tictictic sound, but yes, I hope this can happen. :) Nice suggestion @sunboyzz!

**Comment by Montell2099** [comment]
> Thanks for the idea, I'll try this out.

I know this might be the _absolute_ lowest priority "issue" right now, but have you got around to trying out different tick-sounds & what did you make of it? Not suitable for the launcher?

**Comment by 8bitPit** [comment]
Sorry, I haven't tried it out yet.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2021). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2022 or later.
