### ISSUE TITLE
Homescreen clock won't update. 

### ISSUE THREAD

**Issue by GurrehmatO** [8bitPit/Niagara-Issues#97]
The clock is stuck on 1:06. While the status bar clock is at 8:22

**Comment by 8bitPit** [comment]
That's odd. Can you share your device / Android version? How often does this hapen?

**Comment by 8bitPit** [comment]
![image](https://user-images.githubusercontent.com/9284845/45258028-a645ac00-b3b0-11e8-868e-d6acd7e2d1da.png)
(provided by Vatsal Dangi)
