### ISSUE TITLE
[Request] Tabbed categorization 

### ISSUE THREAD

**Issue by DeltaSingh** [8bitPit/Niagara-Issues#970]
To remain within the aesthetics of the app, rather than having individual folders that appear in the app list, is it possible to also have the option to create a different set of tabbed categories that the user can swipe through? 

All apps - Social - Entertainment - Photography - Settings

Of course this would interfere with the swipe for the app's notification function. I personally think many users would find the option of choosing what behaviour they want more appealing.

**Comment by 8bitPit** [comment]
Hey @DeltaSingh, thanks for the request. There is an ongoing discussion about how apps can be grouped together: https://github.com/8bitPit/Niagara-Issues/issues/13. Please post your ideas there. Btw, here are my thoughts on folders/categories:

>Thanks everyone for providing so many ideas! Here are some of my thoughts:
My intention is to keep app options from app actions separated. So, if you want to get some info about an app or you want to modify it, you can always do that by long tapping. Swiping opens shortcuts & notifications instead. I also thought you could add custom shortcuts / widgets & related apps there as well.
I would also like to add another categorization features as well. Here’s the deal: it wouldn’t be one system which works the same for every category: it would be tailored to each category individually.
For example: Every app which is placed in the music category will show up above your favorites when you connect your headphones / speakers. Games could be filtered out in the app list and added at the bottom. So, they get an own section which has a controller, or something related as an icon.
A message/mail folder on the other hand can always be accessed from within the favorite list, but every app which has a notification attached will be shown in the favorites directly.
Those are just some ideas and the challenge would be to keep it simple, so it should feel intuitive how each category works.
Next to supporting widgets & shortcuts, folders are one of the biggest challenges.

(source: #13)

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
