### ISSUE TITLE
New favorites design/functionality: Add several widgets and ability to rearrangable widgets and shortcuts freely

### ISSUE THREAD

**Issue by ssssamstrup** [8bitPit/Niagara-Issues#972]
**Problem**
I'd like to be able to add another widget and rearrange widgets and shortcuts, in stead of all shortcuts being shown below the widget.

**Solution**
I mainly use the startscreen with my todo widget, but have shortcuts I'd like to keep on top (all music control notifications and 1 shortcut (unless you add Sesame to the searchbar).
The ideal solution would be the ability to add several widgets and rearrange shortcuts, notification controls and widgets freely.

For my current setup, I could then both have my todo and calendar visible on my startscreen, as well as a link to Sesame app above them.

If the time/date block was then made into a Niagara widget, this would also be a solution to #912, by making it arrangable.

Otherwise thank you for a great launcher, I enjoy using it every day!

**Comment by 8bitPit** [comment]
Thank you @ssssamstrup. For the sake of simplicity I would keep the one widget limit on the favorites screen. However, there will be still a way to place multiple widgets:

> That’s why I’m planning to add the following integration:
You can place a single widget below the clock or replace it for showing weather and / or time, or an at a glance widget.
More widgets can be accessed by swiping right on an app.
Another idea would be that you can customize the google search button at the bottom right, so it can also launch a widget, e.g. your calendar.

(from: #117)

**Comment by 8bitPit** [comment]
Merged with #117
