### ISSUE TITLE
Media Player playback bar

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#973]
Here you can share your thoughts on the media playback bar.

**Comment by th80de** [comment]
I like the new media buttons. You could make the outline of the play/pause button the progress bar that fills up when media plays. It could have same accent color as the Google button.

**Comment by Mammutor** [comment]
You can Put The Media Playback bar at The bottom of The Album Cover as a little Line that filles up

**Comment by Martin5001** [comment]
I made a simple concept (Colors would be based on cover main color and system theme.):
![niagara-music-1](https://user-images.githubusercontent.com/35201200/64077264-de838000-ccce-11e9-8c40-92b0bf5af96c.png)
![niagara-music-2](https://user-images.githubusercontent.com/35201200/64077267-ea6f4200-ccce-11e9-8450-6c441a62007f.png)

**Comment by Montell2099** [comment]
![12](https://user-images.githubusercontent.com/43126233/64086566-51294580-cd39-11e9-9b6c-fde2a27ecac4.jpg)

 Just a shot in the dark. Maybe something along the lines of what @th80de wrote.

**Comment by th80de** [comment]
@montell2099 - this is what I had in mind.

**Comment by Martin5001** [comment]
@Montell2099 – The cover image however would need to be bigger to balance the layout as the circle/play button now takes more space.

**Comment by JDKardia** [comment]
Love the implementation, would love seeing a feature addition per @Montell2099's suggestion. 

My suggestion is a side to side swipe between media players, as I frequently switch between Spotify and pocket casts, and if I could seamlessly pivot between them, that would be great.

**Comment by Montell2099** [comment]
@Martin5001 Yes, that is true — or adding some 20 px of margin.

I don't know how big the provided images usually are from Spotify/SoundCloud etc, but you wouldn't want to upscale them that's for sure. Also, for simplicity we need to keep the media player as compact as possible.

**Comment by 8bitPit** [comment]
Hey everyone, thanks for your ideas and mockups.
@Montell2099, implementing the progress bar would be possible and would work with most players on Android 5+ (Lollipop). Figuring out a simple, minimal & intuitive design is way harder here.
Because the media player is more a gimmick than essential and not ne main focus of Niagara, I don’t want to add want to add customization options for it. Niagara should stay simple. That’s why the progress bar would show up on everyone’s homescreen. 
While the concept of your is wonderful by itself @Martin5001, the player could be a bit too intrusive for some users, because they want to see as much of their wallpaper as possible. 
Yours is also great @Montell2099, no doubt. But this time I fear some might complain that the bar makes the button layout asymmetric and less minimal.
If I’m honest I think that this is almost an impossible task, I definitely thought about this too much ^^. You can’t really add information to something without keeping it as minimal as it was. The cleanest idea I could come up with is a small indicator (maybe progress circle or numbers) next to the subtitle. But even by the fact that the indicator changes each second some would prefer a still player. Because of this and because its easy to see the progress of the current playing track by simply tapping on the player to open the app, I’m now feeling that a progress bar isn’t necessary.
But I would love to hear your thoughts on this, please let me know what you think.

**Comment by Martin5001** [comment]
> But even by the fact that the indicator changes each second some would prefer a still player.

If some non numerous indicator was used, then this could be solved by refreshing the indicator every few seconds instead of refreshing continuously. Or it might be user optional.

**Comment by Martin5001** [comment]
The progress bar could grow not from left to right, but from the middle to both sides. So then it could be placed under the player as a thin line (about 2 pixels or so).

**Comment by casungo** [comment]
Hello! I've made a mockup with the playback bar around the image of the song, maybe I've made the line a little too big, but the idea it's there. ![Click here to view the mockup with 75% of the song played](https://i.imgur.com/Qpr93qk.png) or ![click here to view the mockup with 50% of the song played](https://i.imgur.com/KM9BIWi.png).
Hope to see some feedback from various users :smiley:!

**Comment by casungo** [comment]
I've also made another mockup with the line placed vertically between the song image and the title/artist/buttons.

This is the mockup with 100% of the song played:

![100%](https://i.imgur.com/DaHDbKl.png)

This is the mockup with 50% of the song played:

![50%](https://i.imgur.com/dE8MLh8.png)

The line is maybe a little too thick.
Let me know!

**Comment by ClaudiaAtGitHub** [comment]
Would it be possible to have the option of choosing which version of the media player widget to use?  Maybe I'm in the minority but I actually much prefer the original media player widget, which is a lot more unobtrusive, as I'd prefer not to have the album art taking up space plus I really like the simple look of the old controls.   (I know I'm nitpicking -- in every other regard, I absolutely LOVE Niagara Launcher -- it makes my phone so much easier and enjoyable to use!)

**Comment by 8bitPit** [comment]
Thanks for sharing your ideas @casungo. Similar to a playback circle around the button, I believe that some might complain that the player’s layout is too asymmetrical, because the artwork isn’t centered at the beginning of the song, for example. Additionally, your second concept would fit great in the layout, however I believe that a vertical playback bar is very uncommon and might be not ideal for indicating progress.

**Comment by Martin5001** [comment]
Hope you won't mind if I come back to my own concept mentioned at the beginning (I don't want to be too egocentric :D). So as @8bitPit said it might be too intrusive, that's definitely true, this could be solved by using some transparency (maybe with blur effect) like iOS or MIUI does with notification center controls. But I am pretty unsure how would it fit into stock Android material design.

**Comment by ClaudiaAtGitHub** [comment]
@8bitPit 

Yes, your email was very helpful!  I'm disappointed that I won't be able to revert to the smaller and simpler previous version, but I understand your reasoning.   

I do hope you at least keep the background of the media player widget transparent, though -- otherwise, it's going to be this huge rectangle taking up a fifth of my screen!  (If not, I hope there will be an option to disable the media player widget altogether.)

**Comment by airuhc** [comment]
Im with @ClaudiaAtGitHub I really prefered the older style of media player would be awesome if there was a way to switch back to the other style.

**Comment by gdn-mhr** [comment]
What about a small white line below the artist which starts in the center and increases towards both sides as the song goes on? Maybe it would even look nicer if artist and title would be centered too(?)


![001](https://user-images.githubusercontent.com/56309634/70397716-e319ac00-1a14-11ea-9ad8-fcfb2aec1f22.png)
![002](https://user-images.githubusercontent.com/56309634/70397717-e319ac00-1a14-11ea-9a19-076256ce8ef7.png)


(Just took one of the screenshots from this theard as it was the most simple to edit, sorry)

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate of which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2021). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2022 or later.
