### ISSUE TITLE
Add your own android P recents provider

### ISSUE THREAD

**Issue by Technoboss28** [8bitPit/Niagara-Issues#974]
I loved this launcher.  The only thing stopping me from using it on my daily driver is the lack of android P recents like in Hyperion or Lawn Chair. If Niagara is based on Launcher3 with some minor modifications you could integrate your own recents or even navigation gestures (like on the OnePlus port). 

The solution is to rebuild Niagara on top of Launcher3 (cuz I doubt it's based on launcher3 right now as it's so unique) and maybe reach out to the devs of Hyperion or Lawn Chair. You've put such a cool spin on the home screen I'd love to see what you can do to the recents or even navigation gestures.

**Comment by 8bitPit** [comment]
Thanks @Technoboss28. Yes, Niagara is not based on Launcher3. Rebiulding Niagara on top of Launcher 3 would cost way too much time, I'm sorry. Please also check out this issue: https://github.com/8bitPit/Niagara-Issues/issues/86
