### ISSUE TITLE
Settings heading scroll animation – snap in place

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#975]
When I scroll in settings and stop scrolling before reaching the top, heading text stays partially offset and the logo is semi transparent – it stops in the middle of the animation. I think it should snap in place in the direction I was scrolling so the animation would finish.

**Comment by 8bitPit** [comment]
Agreed, this can look weird.

**Comment by 8bitPit** [comment]
Implemented in v0.9.2
