### ISSUE TITLE
Edit mode – Disable swipe gesture on app list

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#976]
I think swipe gesture should not be enabled in edit mode. (Apps cannot be opened in this mode and this sort of bypasses it when user taps for example Open new window in Chrome.)

**Comment by 8bitPit** [comment]
In the future you might also be able to edit the swipe menu, so I wouldn't disable it in edit mode.

**Comment by Martin5001** [comment]
Ok, can't wait for the future then to see what will come :)
