### ISSUE TITLE
Wallpaper change quick revert

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#977]
When trying new wallpapers, it would be awesome to have an option to quickly restore previous wallpaper if we don´t like the new one after a try without needing to redownload the old one or finding it in the gallery.
(As far as I know, Android API allows doing that. Could work like: detect change - show option to revert/keep - restore backup/set new wallpaper)

**Comment by 8bitPit** [comment]
I think this can only work if the launcher gets the "read external storage" permission to extract the current wallpaper. Additionally I think the launcher would have to store the current wallpaper each time the sets a new one. I think this might be overkill for just one feature.

**Comment by Martin5001** [comment]
I think users would not mind granting the permission if it's explained how it is used, (they always have the choice to disallow it anyway). And storing the image should not be a problem either as phone storages getting bigger and bigger. (Anyway, this feature could be optional.) What I am sure about is that it would make your launcher even more unique as no other provides such option.
But, of course, the decision is yours.

**Comment by 8bitPit** [comment]
This sounds more like a feature that wallpaper apps should provide.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
