### ISSUE TITLE
Messenger notification - open link bug

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#978]
Notification came from group chat in Messenger and showed a Open in Chrome link but when I clicked that to test this new feature, nothing happened.

Maybe this could be caused by:
- One member of group chat sent a video from his phone (not external link)
- One member changed group name

Otherwise the content of notification was regular text.

UPDATE: YouTube video link does not work either.

I am using Android 9 (Nokia 5),

**Comment by 8bitPit** [comment]
Thanks Martin, it should work now: https://github.com/8bitPit/Niagara-Issues/releases/tag/v0.9.1-beta

**Comment by Martin5001** [comment]
Thank you for quick reaction. Now it's fixed.

**Comment by 8bitPit** [comment]
Great 😁
