### ISSUE TITLE
Contacts thumbnail/icon transparent area is black

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#979]
When I swipe on Contacts app, sometimes the contact name letters (icons) show the letters black (or more dark grey) instead of white – unfortunately I was not able to reproduce this bug or take screenshot as it "resolved itself" when I came back to homescreen later. (I have seen it before but I thought the letter icons are simply different in Phone and Contacts apps, but now I realized they aren't.)

Update: This problem seems to be connected with dark/light theme change. Letter keeps black after switching to light theme and vice versa.

(Using Android 9.)

**Comment by 8bitPit** [comment]
Niagara doesn't interfere with the icons of app shortcuts, it just uses the ones provided by the app. I believe I can't fix this, unfortunately. Btw, are you using Google's contacts app?

**Comment by Martin5001** [comment]
Yes, I am using Google's app. Then I might send a feedback to them.

**Comment by Martin5001** [comment]
Or maybe Google will fix this eventually with the new dark mode. Is there anyone using Android 10 who can say if dark theme is used in Android's native quick actions? (If so then Google might notice this bug on their own.)
