### ISSUE TITLE
Notification opening finnicky (swipe down gesture)

### ISSUE THREAD

**Issue by jakcharvat** [8bitPit/Niagara-Issues#98]
The gesture to open the notification shade works about 1 in 10 times. Refer to video:https://photos.app.goo.gl/Lf9HYw4LxC4hUPf18

**Comment by lepa22** [comment]
It seems to me that opening the notification shade depends on how fast you swipe down.

**Comment by jakcharvat** [comment]
Oh that's a good point. Now that you've said it it does look that way. But it requires a really high speed right now, could you try tweaking that a little bit @8bitPit please?

**Comment by 8bitPit** [comment]
It's based on your finger’s acceleration. I made it harder to trigger, so you can also scroll through your favorites without accidentally opening the notification tray.

**Comment by lepa22** [comment]
But since, as currently implemented, you have to be at the top of your favorites for the gesture to work, it doesn't need to be acceleration-based. Just swiping down when at the top of your favorites should open notifications.

**Comment by 8bitPit** [comment]
@lepa22 gestures are always based on acceleration, there is no better way to trigger the gesture.

**Comment by 8bitPit** [comment]
@jakcharvat is it more comfortable now?

**Comment by jakcharvat** [comment]
Oh sorry just got back to this issue, abd yes, it feels much better. Thank you!
