### ISSUE TITLE
Notification gets duplicated

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#981]
Notification (from Messenger) got duplicated in the preview on the homescreen (but not in swipe view, there it is shown normally).
This happened probably because I swiped and viewed the notification too quickly after notification occur (before or at the same time with system notification popup minimizing). This is probably mostly rare situation, but still better to be handled if possible.

**Comment by Rod911** [comment]
Anything similar to #730?

**Comment by Martin5001** [comment]
Yes. Sorry I didn't notice this issue, otherwise I would comment on there.

**Comment by Rod911** [comment]
Weird, OP reported his issue had been fixed.

**Comment by Martin5001** [comment]
It looks more like an edge case. I was probably just too quick because I wanted to test new Smart replies, so when the notification came I opened it almost immediately (by the way at this time I was in Chrome). Normally this does not happen when I use the app daily.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)
