### ISSUE TITLE
Navigation gestures stop working on Android 10

### ISSUE THREAD

**Issue by supermueller** [8bitPit/Niagara-Issues#982]
**Describe the bug**
The navigation gestures for showing up recent app and switching between them stop working on Android 10. This will only happen if the launcher is in front and the two button navigation known from Android Pie is selected. The three button option works but have graphic clitches.

**To Reproduce**
1. Select the two buttons gesture navigation in the preferences of Android 10 (see screenshot)
2. Bring launcher to front by pressing the home button.
3. Try to bring up the recent apps by swiping up the home button.
4. The recent apps will not show up.

**Smartphone (please complete the following information):**
 - Device: Essential Phone
 - Android version: Android 10

**Screenshots**
![Screenshot_20190904-001557](https://user-images.githubusercontent.com/2378496/64212301-3675de80-cea9-11e9-83f3-db1373346348.png)

**Comment by supermueller** [comment]
After restarting my phone all works fine.

**Comment by amminadabz** [comment]
Restart didn't fix it for me. Pixel 3, Android 10.
