### ISSUE TITLE
Not wrap contact names in Contacts app quick actions

### ISSUE THREAD

**Issue by Martin5001** [8bitPit/Niagara-Issues#983]
Contact names are wrapped with ... but there is enough space left so it shouldn't wrap. (The same text is not wrapped in Phone app quick actions by the way.)

**Comment by 8bitPit** [comment]
If believe that's because Niagara displays the shortcut's short label (Each shortcut can have a short and long label).

**Comment by Martin5001** [comment]
So that means it is possible to change, or not? I mean switch to the long label?

**Comment by 8bitPit** [comment]
Yes, that can be changed.

**Comment by 8bitPit** [comment]
Fixed in v.0.32
