### ISSUE TITLE
AlbumArt not working with PocketCasts

### ISSUE THREAD

**Issue by intruden313** [8bitPit/Niagara-Issues#985]
**Describe the bug**
Ever since updating to Niagara 0.9, the album art stopped functioning in PocketCasts. As far as I can tell, it was working properly in 0.8.2. My first assumption was that PocketCasts had made a change on their end, but I have not received an update for PocketCasts since July 1st.

Other apps such as Spotify and Apple Music appear to have no issue oddly enough.

I apologize if this is redundant or a known bug, but I did not see this addressed upon searching for it.

**To Reproduce**
1. Open PocketCasts
2. Play any podcast
3. Go home/Open Niagara
4. Media Artwork will show a generic music icon

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9 (Snapdragon)
 - Android version: Android 9 (Pie)

**Screenshots**

![image](https://user-images.githubusercontent.com/18371396/64356449-e5f9a080-cfd0-11e9-8bd9-bd73469ce014.png)

**Comment by 8bitPit** [comment]
Hey @intruden313, have you already tried the steps I mentioned here: #485?

**Comment by intruden313** [comment]
Thank You for the reply @8bitPit, I just tested it on Android Auto and sure enough, it did not have any album art. What confuses me about this is it _used_ to display properly. And judging by PocketCasts' track record, I doubt they made any changes on their end.

Regardless, they definitely don't follow Media Sessions protocol. Now I'm only curious why it worked prior.

**Comment by 8bitPit** [comment]
Thanks for trying it out. I'll keep an eye on how many people run into similar issues. Nevertheless, I'll close this issue here and leave #485 open.
