### ISSUE TITLE
Font scaling issues

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#986]
**Describe the bug**
Several users on Telegram mentioned that the font on the launcher scales up after a while. 
Restarting the launcher fixes this issue temporarily.

**To Reproduce**
I couldn't reproduce this myself. Please let me know if you can.

If you're facing this issue as well, can you please write me which device and Android version you use? Furthermore, have you changed the font or display size in Android's settings?

**Comment by LuhMie** [comment]
Phone model: Gionee P7
Android version: 7.0
Font display size has been set in the phone settings. Niagara just increases the font after some time so I had to restart launcher for it to go back to normal size

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, feel free to open the ticket again.
