### ISSUE TITLE
Show more apps

### ISSUE THREAD

**Issue by gabrielfilgueiras** [8bitPit/Niagara-Issues#987]
I'm really enjoying this launcher.
 My suggestion is to pop up recently or frequently used apps when you click the middle button to search for apps.

**Comment by Martin5001** [comment]
Just a note: I personally vote for this, but some users might prefer more simple look, so this should probably be optional.

**Comment by 8bitPit** [comment]
Hey, I changed the title of https://github.com/8bitPit/Niagara-Issues/issues/227 to include your suggestion.

**Comment by 8bitPit** [comment]
Merged with #227
