### ISSUE TITLE
Support Android 10's gesture navigation

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#989]
I created this issue to let you know, that any third party launcher can't support gesture navigation (at least not without root permissions):

>Custom launchers are another area where we’ve heard feedback and we’re continuing to work on issues, particularly with stability and Recents. Starting in Beta 6, we’ll switch users to 3-button navigation when they are using a custom launcher by default. We’ll address the remaining issues in a post-launch update allowing all users to switch to gestural navigation. [(Source)](https://android-developers.googleblog.com/2019/07/android-q-beta-5-update.html)

I am frustrated about how Android lets you think gesture navigation can be supported by third party launchers,  but this is not the case, unfortunately.

However, Google plans to let third party launchers support gesture navigation later this year.

**Comment by 8bitPit** [comment]
By the way, here's a similar statement from Nova Launcher: https://twitter.com/Nova_Launcher/status/1169295641538940930

**Comment by 8bitPit** [comment]
Update: [Android 10 on the Pixel 4 supports gesture navigation with third-party launchers](https://www.androidpolice.com/2019/10/17/the-pixel-4-supports-android-10-gesture-nav-with-third-party-launchers/)
I believe other phones running Q will get a patch soon.

**Comment by McKean** [comment]
Just installed the update on my Pixel 3. Gesture navigation now works on Nova launcher but sadly not on Niagara.

**Comment by cuprousoxide** [comment]
Since this Android update, the navigation/gesture setup now named "2-button navigation" is kind of wonky. Swiping up to see recent apps often doesn't work right and requires fiddling on my part. It was all working fine on my Pixel 3 before that Android 10 update.

Is this understood to be related to the topic? Has this already been reported? If it somehow hasn't, I can make a new Issue with details.

**Comment by 8bitPit** [comment]
@McKean can you please post screenshots or record a video showing how gesture navigation works with Nova and not with Niagara?

**Comment by 8bitPit** [comment]
Hey @cuprousoxide, especially on Android 10 2-button gesture navigation is quite buggy with third party launchers. Unfortunately third-party can't do anything, at least on non-rooted devices. You can read more about this here: #86

**Comment by McKean** [comment]
@8bitPit http://imgur.com/gallery/yOW2URE
It's fairly straight forward... In one case I can select it in the other I can't. When switching to Niagara while having gesture navigation enabled it will default to one of the others.

**Comment by 8bitPit** [comment]
@McKean very interesting, thank you for the screenshots. Afaik, Google hasn't announced that gesture navigation is yet compatible with third-party launchers. However, when they release documentation to make it possible, I'll try my best to support gesture navigation asap.

**Comment by Mr-invisibles** [comment]
Well it's seems not to be a problem on Huawei mate 10 pro to use swipe gestures.
Works like a charm, but still on Android pie
![Screenshot_20191127_012743_com android settings](https://user-images.githubusercontent.com/49566461/69683605-b3ce7b00-10b5-11ea-993e-5cfd4230d63a.jpg)

**Comment by shmykelsa** [comment]
https://forum.xda-developers.com/apps/magisk/module-quickswitch-universal-quickstep-t3884797

Can this be helpful at all?

**Comment by 8bitPit** [comment]
Thanks @shmykelsa. Sadly, Niagara Launcher doesn't work with Quickswitch, because it's pretty difficult and time consuming to provide a recents provider, when the app doesn't share its code base with [Launcher3](https://android.googlesource.com/platform/packages/apps/Launcher3/) (Most other grid-based launchers are forking this launcher / using this launcher as their base). More on that here: #86

**Comment by McKean** [comment]
@8bitPit google just released a security patch, since then I was and to choose gesture navigation. Could have also been due to an update from Niagara. Just wanted to let you know it's working on the pixel 3 now. Thanks for all the great work on this amazing launcher.

**Comment by 8bitPit** [comment]
@McKean That's great news! Will download the security patch on my Essential phone later. Thanks for sharing :)

**Comment by rnp5285** [comment]
I took a little break from Niagara just because of the gesture navigation not working. Updated to December android 10 security patch and it lets you use gestures! Slightly buggy trying to go home when already home but it's fine.

**Comment by 8bitPit** [comment]
Thanks @rnp5285. Yeah, it is. Sadly, we have to wait for Google to fix those 😪

**Comment by cauerego** [comment]
few weeks ago it wasn't even working for me. but today i just tried it and it's working "good enough", just like with the "before launcher" (as mentioned in telegram chat.

**Comment by joshiain** [comment]
I have gestures working for me as well on a Pixel 3. The only issue I've encountered so far is when using facebook messenger from the chat heads, swiping up to go home takes me to the search screen rather than the home screen. Works well when using the actual messenger app, and don't encounter this issue with 2 button navigation. @8bitPit is this a bug you could fix, or reliant on Google at this stage?

**Comment by cuprousoxide** [comment]
I can also confirm that Gesture navigation has been re-enabled on my Pixel 3 for a while now and works mostly fine. There's still a little bit of weirdness regarding app switching but I haven't snooped enough to figure out if it's necessarily a problem with Niagara.

> 
> 
> I have gestures working for me as well on a Pixel 3. The only issue I've encountered so far is when using facebook messenger from the chat heads, swiping up to go home takes me to the search screen rather than the home screen. Works well when using the actual messenger app, and don't encounter this issue with 2 button navigation. @8bitPit is this a bug you could fix, or reliant on Google at this stage?

Have you disabled "Press home to search" in Niagara?
Launcher Settings > Features > Search > Press home to search

**Comment by 8bitPit** [comment]
@joshiain which version of Niagara Launcher do you use?

**Comment by awnumar** [comment]
Niagara v0.11.5 here on the OnePlus 7T latest build: Oxygen OS 10.0.7, gestures still not working.

**Comment by joshiain** [comment]
@cuprousoxide I've disabled Press home to search for now and that stops the issue, but ideally I'd like to enable it again as I used that feature

@8bitPit I'm currently using v0.11.7

**Comment by 8bitPit** [comment]
@awnumar, OnePlus has to ship Google's December security patch. Before that, gestures won't work on third-party launchers.

**Comment by 8bitPit** [comment]
@joshiain understandable. I cannot reproduce the bug, can you please record a video demonstrating it?

**Comment by joshiain** [comment]
@8bitPit Sure, how can I send it to you privately? Since it requires opening messenger, it has some private stuff

**Comment by 8bitPit** [comment]
You can send it to me via mail (niagaralauncher@gmail.com). I can assure you that I won't make this video public. Nevertheless, please make sure to reduce the amount of private information as much as possible.

**Comment by disacrol** [comment]
@8bitPit now running Android 10 and can confirm only 2 and 3 -gesture navigation works on Niagara, while Nova also supports the new gestures. Could it be they found a hack that works around Google's limitation? I noticed @McKean reported Nova supporting Android 10 gestures back in November, before Google's December patch that officially allowed gestures on third party launchers.

**Comment by 8bitPit** [comment]
@disacrol I don't think they found a workaround, I'm sure they would have announced it on Twitter. They're FAQ still reads that there is no workaround: https://help.teslacoilapps.com/faq/gesture-navigation. Either it's a bug from your firmeware or it explicitly whitelists Nova Launcher I guess.

**Comment by disacrol** [comment]
Maybe Xiaomi specifically changed the OTA for Nova, but notice that FAQ page still cites Google's announcement that third party launchers wouldn't have access to gestures yet, way before they decided to support other launchers in December's patch. Also, see for example that Action Launcher on the other hand clearly announced full gestures support: https://blog.actionlauncher.com/action-launcher-v45-adds-android-10-gesture-nav-support-actiondash-widget-more-bf6b4b91e65

**Comment by 8bitPit** [comment]
@disacrol this was a in my opinion misleading publicity stunt from Chris Lacy. Gesture navigation does work automatically on any third party launcher with Google's December security patch. 
Android did not introduce a new API or anything, the preinstalled launcher (to be more precise, a sub-module of the launcher) handles gesture navigation even if a third-party launcher like Niagara Launcher is being used.

**Comment by disacrol** [comment]
Now you've got me confused. Then why are gestures disabled if I'm using Niagara while having Android 10 OTA I've received this month?

**Comment by 8bitPit** [comment]
@disacrol I have no idea. I could get gestures to work instantly on any third party launcher including Niagara since 3rd December, the day Google and the Essential phone's developers released the patch. Have you also tried restarting your phone, setting another launcher as default, etc.?

**Comment by joshiain** [comment]
> @joshiain You can send it to me via mail ([niagaralauncher@gmail.com](mailto:niagaralauncher@gmail.com)). I can assure you that I won't make this video public. Nevertheless, please make sure to reduce the amount of private information as much as possible.

@8bitPit Were you able to get anything from the video I emailed?

**Comment by shmykelsa** [comment]
So I've received December patch update (Oxygen OS 10.3.1) and nothing has changed so far... What is it supposed to change?

**Comment by awnumar** [comment]
I'm on the January patch set, Oxygen OS 10.0.8, gestures still not working.

They work before I set Niagara (0.15.2) as default but once I do it stops working.

**Comment by 8bitPit** [comment]
@shmykelsa @awnumar One Plus has to merge part of code Google made available in Google Pixels December security patch into their codebase. One Plus' January patch doesn't necessarily have the code to enable gesture navigation for all third party launchers.

**Comment by cauerego** [comment]
one more little thing...

gesture navigation sucks balls, functionality wise, when compared with fng (fluid navigation gestures). just so you guys know:

https://play.google.com/store/apps/details?id=com.fb.fluid

i've stumbled upon it, had some resistance to adopt it because it's not so pretty and it has some issues... but in the end, the sum of what works was all i could care for.

**Comment by camopy** [comment]
![appSwitch](https://user-images.githubusercontent.com/29547465/78302976-39ee4880-7512-11ea-8d60-dd7f2a810946.gif)

That's all get when swiping up from any screen (swiping up from home screen nothing happens), I can't access the app switcher. Also, nothing happens when swiping left or right on the bottom of the screen, it should switch to recent apps.

Is this related to Niagara or google? I have the latest security patch installed:
![image](https://user-images.githubusercontent.com/29547465/78303337-d87aa980-7512-11ea-8c5d-9d2228dee823.png)

**Comment by y0c4** [comment]
That is strange - when I swipe up half way I do get the app switcher. I got an Oppo phone so it is the Oppo app switcher that appears, but that’s fine with me.

**Comment by camopy** [comment]
This is what happens when "Press home to search" is activated

**Comment by camopy** [comment]
This is what happens when "Press home to search" is enabled:
![pressHome](https://user-images.githubusercontent.com/29547465/78588689-70c7a580-7815-11ea-98df-a012536d9a77.gif)

**Comment by 8bitPit** [comment]
@camopy unfortunately Niagara doesn't have any control about the gestures and recents screen, so your firmware manufacturer has to fix that. More info here: https://niagaralauncher.helpscoutdocs.com/article/7-gesture-navigation

**Comment by 8bitPit** [comment]
Because there's nothing we can do here except for waiting for the oems to release updates I'll close this.
