### ISSUE TITLE
landscape & portrait

### ISSUE THREAD

**Issue by cavanist** [8bitPit/Niagara-Issues#992]
Hello, can you separate portrait and landscape settings like other launchers (Renegade etc.) because if I design portrait screen, it doesn't fit correctly on landscape mode...

The second request is, my previous launcher was able to set not only the position of widget, but also width of ANY widget..

thank you

jan

**Comment by 8bitPit** [comment]
Hey Jan, landscape mode is under discussion, see: #502 & #841. For your second request I opened up a dedicated issue: #994.
