### ISSUE TITLE
Favourites doesn't populate most used apps when any most used app is blocked from Favourites

### ISSUE THREAD

**Issue by guptadd** [8bitPit/Niagara-Issues#993]
**Describe the bug**
Favourites doesn't populate most used apps when any most used app is blocked from Favourites

**To Reproduce**
1. Have at least 2 apps in home screen which are not favourites (i.e. Most Used Apps)
2. Block one of them from favourites
3. The favourites list doesnt populate with the next app

**Smartphone (please complete the following information):**
 - Device: LG G7
 - Android version: Android 9 (Pie)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can paste them here directly.

**Comment by 8bitPit** [comment]
Hi. It is intended that a new suggestion won'T necessarily show up if you remove one. That's because only suggestions of apps you use most often will show up.

**Comment by 8bitPit** [comment]
Feel free to open the issue again in case my previous reply didn't help.
