### ISSUE TITLE
Map to home button

### ISSUE THREAD

**Issue by asant0s** [8bitPit/Niagara-Issues#996]
Ability to select other actions when selecting home button, i.e. different search, actions, folders, etc..

This might fall under gestures as its typically found under that category for other launchers but I would consider this just an expansion to the existing setting for home button and not a baked out new gestures category

Thanks!

**Comment by 8bitPit** [comment]
Thanks for the request :)
I can't tell yet, but this might be problematic with Android 10's new gesture navigation (They're not compatible with third-party launchers yet, but this will be patched. See #989 for more info).

**Comment by Sn00PiG** [comment]
At the settings we can already select "Press home to search" - if you could implement this action to launch an app, e.g. a custom search like Sesame that would be brilliant!

**Comment by ssssamstrup** [comment]
Seconding @Sn00PiG comment. 

Would be lovely with a list of options, like Fluid Navigation. Don't know if their solution can be implemented in Niagara, but that would make it really useful for all kinds of different peoples setup.

**Comment by 8bitPit** [comment]
@Sn00PiG what about integrating Sesame into Niagara directly? 😉 #88

**Comment by 8bitPit** [comment]
@ssssamstrup yup, this would be possible, but gesture navigation is becoming the new standard. Android Q will also allow you to use gestures with third-party launchers soon.  So, I'm not entirely sure, how relevant this feature will be in the future.

**Comment by ssssamstrup** [comment]
Well most people won’t be using Android 10 and the new gesture navigation for a while (or untill they buy a new phone who knows when). I don’t know how Niagaras users are spread across versions, but most slightly old phones won't get updated at all, so adding this option would still be great for them/us and for users who are stuck on earlier versions.

All the best,

● Sune Amstrup

Strategisk grafisk designer og billedkunstner
Planlægger POST Design Festival 2019
Forbedrer arbejdsvilkår med Visuelt Forum

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
