### ISSUE TITLE
App title rather than icons.

### ISSUE THREAD

**Issue by Chaupeter** [8bitPit/Niagara-Issues#997]
This feature is not related to any known bug.

Is it possible to have the option of displaying the App name ( title ) instead of the icon and to have this list left justified in the home screen. 

This would present a user with a list of apps to choose from rather than either an icon and title or just an icon which are the options at present.

Thank you for your consideration.

**Comment by Martin5001** [comment]
Also when you select icons only option, the ripple effect shown behind them on tap should be disabled I think (or be under the icon itself only, not the area where text was supposed to be before), but there might be some reason for this, I don't know.

**Comment by 8bitPit** [comment]
@Chaupeter do you mean something like this: #140

**Comment by 8bitPit** [comment]
@Martin5001 the ripple shows you the item's touch area. I think changing it to a smaller circle would be inconsistent.

**Comment by 8bitPit** [comment]
Duplicate of #140
