### ISSUE TITLE
Add more ways to access settings

### ISSUE THREAD

**Issue by Aweotranx** [8bitPit/Niagara-Issues#999]
**My English is bad, that's why I will write in my native language. I feel the trouble.**

Esto no es más que una pequeña sugerencia con respecto al como se muestra la configuración del launcher en si. 

A nivel personal me incomoda un poco que aparezca al final del listado de aplicaciones. 

Agradecería muchísimo si es que se pudiese acceder de alguna otra forma. Como a través de un gesto, por decir algo. O también la opción de que aparezca en el menú de búsqueda en forma de tuerca.

**Comment by Martin5001** [comment]
?Que es esto "en forma de tuerca", por favor? ?Es un differente vocablo para es? (Google no trasladar esta parte muy bueno.)

I just put it into Google Translator and tweaked it a little using a dictionary so you guys won´t have to do that. (And Google actually did a suprisingly decent job considering it is just an AI.):

> This is just a small suggestion regarding to where the launcher settings option icon is placed - at the end of the list of applications.
I would greatly appreciate if it could be accessed in some other way. For example via a gesture. Or also the option to be shown in the search menu in the form of a nut.

**Comment by 8bitPit** [comment]
As always, thanks for the translation @Martin5001  😁

@Aweotranx  Agreed, it seems that not everyone seems to even find them in the first place. I'd suggest the following: Adding "Niagara settings" to the app list (that would show up under "N"). This symbol would be treated like an app, this means, that you could search for this and that you can hide it.

**Comment by Martin5001** [comment]
@8bitPit Would you move the wallpaper setting button to the app list as well? If so, just note that the default Android wallpaper app is named the same which might be confusing (at least in some languages).

**Comment by 8bitPit** [comment]
Thanks for the hint. I wouldn't add the wallpaper button to the app list, just a second settings button.

**Comment by 8bitPit** [comment]
To better plan ahead and to give users an estimate which features will be added to Niagara, I’ve decided to close all feature requests that that are unlikely to be implemented in the next year (2020). This is one of those, unfortunately. I'm sorry. Feel free to open this ticket again in 2021 or later.
